import type { SubtopicPracticePack } from "./types";

/**
 * Topic 18 (9700 Biology) practice — `data/courses/biology-9700.json` (`t18-1` … `t18-3`).
 *
 * Crosswalk to `data/syllabus/biology-9700-learning-outcomes.md`:
 *
 * **`t18-1` (18.1 Classification)** — d1 species concepts; d2 three domains; d3 Archaea vs Bacteria;
 * d4 Eukarya hierarchy; d5 kingdoms Protoctista + Fungi; d6 Plantae + Animalia; d7 virus classification;
 * d8–d10 application / compare / consolidation.
 *
 * **`t18-2` (18.2 Biodiversity + continued)** — d1 ecosystem / niche; d2 biodiversity levels; d3 random sampling;
 * d4 quadrats / transects; d5 Lincoln index; d6 Spearman r_s calculation; d7 Pearson r calculation; d8 Simpson D; d9–d10 integration.
 *
 * **`t18-3` (18.3 Conservation)** — d1 extinction causes; d2 maintaining biodiversity; d3 ex-situ / in-situ sites;
 * d4 assisted reproduction; d5 invasive species; d6 IUCN + CITES; d7–d10 consolidation.
 */
export const BIOLOGY_TOPIC18_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t18-1": {
    noteId: "t18-1",
    drills: [
      {
        id: "t18-1-d1",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 2,
        marks: 8,
        stem: "Discuss the biological species concept, the morphological species concept and the ecological species concept. For each, state its basic idea and give one strength and one limitation that an examiner would credit.",
        modelAnswerPoints: [
          "Biological species concept: natural interbreeding producing fertile offspring / reproductive isolation between species; strong for many sexual populations; weak for fossils, some asexual groups, or cryptic isolation data.",
          "Morphological species concept: classification by observable structural features; practical in field and museums; can fail with cryptic species or high within-species variation.",
          "Ecological species concept: defines species by niche (resource use, role); useful when ecology diverges; boundaries can be unclear if niches overlap or shift.",
        ],
        workedSolution: [
          "The biological species concept defines species primarily by patterns of reproduction: populations whose members interbreed naturally and produce fertile offspring are considered one species, while barriers to gene flow maintain separate species; this links directly to evolutionary independence and is very powerful when breeding tests or clear pre-mating barriers can be observed in living sexual organisms.",
          "Its limitations are well known: it cannot be applied honestly to extinct lineages known only as bones or shells, it is awkward for strictly asexual or mainly clonal organisms where ‘interbreeding’ is not meaningful, and morphologically similar but reproductively isolated cryptic species may be missed if only courtship or genetic data reveal isolation.",
          "The morphological species concept groups organisms by shared structural traits and is therefore the workhorse of museum taxonomy and rapid field identification where detailed breeding studies are impossible; it is transparent and repeatable when diagnostic characters exist.",
          "However, unrelated lineages can converge on similar shapes, producing false lumping, while a single widespread species with strong sexual dimorphism or life-stage change can be over-split if only dead adults are compared, which is why morphology must be interpreted alongside other evidence when possible.",
          "The ecological species concept emphasises the role of a taxon in its community—its niche including resources, habitat use, and biotic interactions—and is especially helpful when species are separated by habitat or resource partitioning despite looking alike.",
          "The trade-off is that niche edges are not always discrete, seasonal or regional niche shifts can blur boundaries, and competition can change with community context, so ecologists often combine niche information with genetics and reproduction rather than relying on niche alone.",
        ],
        commonMistake:
          "Treating one concept as ‘correct’ in all cases, or giving a one-line definition with no strength/limitation for each concept.",
        tags: ["species-concepts", "definitions"],
      },
      {
        id: "t18-1-d2",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe how living organisms are classified into three domains. Name the three domains and explain in outline why this scheme is used for cellular life.",
        modelAnswerPoints: [
          "Three domains: Archaea, Bacteria, Eukarya.",
          "Reflects deep evolutionary relationships (e.g. molecular / ribosomal RNA evidence), not only shape or habitat.",
          "Separates major lineages of prokaryotes (Archaea vs Bacteria) as well as eukaryotes.",
        ],
        workedSolution: [
          "Modern classification places all cellular organisms into three domains called Archaea, Bacteria and Eukarya, instead of splitting life only into prokaryotes and eukaryotes, because molecular phylogenetics—especially comparisons of conserved ribosomal RNA and other core sequences—shows that the great majority of ‘prokaryote’ diversity falls into two ancient, distinct clades rather than one.",
          "Eukarya share a suite of cytological features including a nucleus and typically organelles bounded by double membranes, and group together on trees of life as a third domain distinct from both prokaryotic domains.",
          "Using three domains therefore organises biodiversity by evolutionary history and major cellular grade, which is why syllabuses present it as the uppermost framework before kingdom- and species-level detail within Eukarya.",
        ],
        commonMistake:
          "Listing domains without stating that the split is rooted in evolutionary / molecular evidence, or inventing a fourth domain.",
        tags: ["domains", "classification"],
      },
      {
        id: "t18-1-d3",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "State that Archaea and Bacteria are prokaryotes. Describe three named types of difference between Archaea and Bacteria as required at A Level, limited to membrane lipids, ribosomal RNA and composition of cell walls.",
        modelAnswerPoints: [
          "Both lack a nucleus / membrane-bound organelles (prokaryotic).",
          "Membrane lipids: archaeal lipids have distinct chemistry (e.g. ether-linked isoprenoid chains) compared with typical bacterial fatty-acid ester lipids.",
          "Ribosomal RNA: archaeal rRNA sequences group separately from bacterial rRNA in phylogenetic comparisons.",
          "Cell walls: typical bacteria have peptidoglycan; many Archaea lack peptidoglycan and use different wall polymers (or S-layers).",
        ],
        workedSolution: [
          "Archaea and Bacteria are both prokaryotic in the sense that they do not package DNA in a membrane-limited nucleus and do not possess the membrane-bound organelle set typical of eukaryotic cells, yet they are not minor variants of one group because multiple independent lines of evidence separate the domains.",
          "Plasma-membrane lipid chemistry differs systematically: bacterial membranes are built mainly from fatty acids ester-linked to glycerol, whereas archaeal membranes commonly use ether-linked isoprenoid chains with stereochemistry distinct from bacterial lipids, altering fluidity and stability especially in extreme environments.",
          "Ribosomal RNA of the small subunit and associated translational machinery sequences place Archaea closer in some respects to eukaryotes than to Bacteria for some core proteins, while still keeping them prokaryotic in cell organisation, which is why rRNA trees were historically used to justify domain-level separation.",
          "Cell-envelope composition also diverges: the characteristic peptidoglycan mesh of most bacteria, which gives Gram staining patterns, is absent in many Archaea, which instead may have pseudopeptidoglycan or proteinaceous surface layers, so ‘prokaryote’ must not be read as ‘bacterium with a few tweaks’.",
        ],
        commonMistake:
          "Saying Archaea are ‘extreme bacteria’ without the specific syllabus differences, or claiming Archaea are eukaryotes.",
        tags: ["Archaea", "Bacteria", "prokaryotes"],
      },
      {
        id: "t18-1-d4",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Describe the classification of organisms in the Eukarya domain into the taxonomic hierarchy from kingdom to species. Explain what it means for two organisms to share the same genus but differ at species level.",
        modelAnswerPoints: [
          "Hierarchy (high to low): kingdom, phylum, class, order, family, genus, species.",
          "Lower ranks = smaller groups sharing more recent common ancestry / more detailed similarity (in teaching answers).",
          "Same genus: very close relationship; species: reproductively / diagnostically distinct units within that genus context.",
        ],
        workedSolution: [
          "Within the domain Eukarya, each species is placed in a nested set of ranks that run, from the broadest to the narrowest required here, kingdom, phylum, class, order, family, genus and species, so that a full binomial name refers to genus plus species epithet while higher ranks bundle many species into successively larger groups.",
          "Moving down the hierarchy reduces the number of included species and increases the fraction of traits that are expected to be shared, which is why taxonomists can predict, for example, that two members of the same family are more similar overall than two members only known to share a phylum.",
          "If two organisms are assigned to the same genus, they are judged to share a comparatively recent common ancestor and a suite of derived characters that warrant that generic label, yet they remain different species if reproductive isolation, fixed diagnostic differences, or other agreed species criteria separate them, which is exactly the contrast ‘same genus, different species’ is meant to capture in examination answers.",
        ],
        commonMistake:
          "Reversing the order of ranks (e.g. putting class above phylum) or confusing genus with family.",
        tags: ["hierarchy", "Eukarya"],
      },
      {
        id: "t18-1-d5",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 2,
        marks: 7,
        stem: "Outline the characteristic features of the kingdoms Protoctista and Fungi as treated in this syllabus.",
        modelAnswerPoints: [
          "Protoctista: very diverse eukaryotes; many unicellular; autotrophic and heterotrophic forms; not plants, animals or fungi.",
          "Fungi: eukaryotic heterotrophs; extracellular digestion then absorption; cell walls usually with chitin; often filamentous mycelium; can be uni- or multicellular (e.g. yeast).",
        ],
        workedSolution: [
          "Protoctista is best thought of as a kingdom-level container for eukaryotic organisms that are not classified as plants, fungi or animals, which makes it inherently heterogeneous: it includes abundant unicellular algae and protozoa-like forms, some of which are photosynthetic autotrophs while others are heterotrophic phagocytes or osmotrophs, and some colonial or simple multicellular representatives that do not fit plant or animal body-plan criteria.",
          "Because the group is defined partly by exclusion from the three better-circumscribed kingdoms, examination answers should stress eukaryotic organisation, diverse nutrition, and frequent unicellularity rather than pretending one lifestyle fits all members.",
          "Fungi are eukaryotic heterotrophs that secrete digestive enzymes across their surface and absorb soluble products, rather than ingesting food into a gut; their cell walls typically contain chitin, and many species grow as networks of hyphae forming a mycelium, though yeasts demonstrate a common unicellular fungal life style.",
          "Multicellular fungi produce specialised reproductive structures (mushrooms, sporangia) for spore dispersal, and the combination of absorptive nutrition, chitinous walls and hyphal growth distinguishes them clearly from plants with cellulose walls and photosynthetic chloroplasts in the syllabus picture.",
        ],
        commonMistake:
          "Describing Protoctista as ‘bacteria’ or claiming all fungi are photosynthetic.",
        tags: ["Protoctista", "Fungi", "kingdoms"],
      },
      {
        id: "t18-1-d6",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 2,
        marks: 7,
        stem: "Outline the characteristic features of the kingdoms Plantae and Animalia as treated in this syllabus.",
        modelAnswerPoints: [
          "Plantae: multicellular eukaryotes; photosynthetic (general statement); cellulose cell walls; autotrophic nutrition via photosynthesis in green plants.",
          "Animalia: multicellular eukaryotes; heterotrophic by ingestion; no cell walls; specialised tissues / organ systems (general).",
        ],
        workedSolution: [
          "Members of kingdom Plantae considered in general biology courses are multicellular eukaryotes whose cells are surrounded by cellulose-containing walls and whose green parts contain chloroplasts for photosynthesis, making them predominantly autotrophic producers that fix carbon for ecosystems using light energy, with bodies adapted for light capture, gas exchange, support, and long-distance transport in larger forms.",
          "That combination—cellulose walls, chloroplast-based photosynthesis, and life cycles with alternation of generations in many lineages—contrasts with fungi and animals even when some plant structures are non-photosynthetic (e.g. roots) because the overall nutritional mode remains plant-like.",
          "Kingdom Animalia comprises multicellular eukaryotes that ingest organic food, digest it internally in a cavity or tract, and absorb nutrients, and they lack the rigid cell walls found around plant cells, instead using collagen-containing extracellular matrix and contractile proteins for movement and support.",
          "Animals typically show increasing levels of tissue organisation—epithelia, muscle, nervous tissue—and many have complex sensory and motor integration, which matches the heterotrophic, active foraging lifestyle that defines the kingdom at this outline level.",
        ],
        commonMistake:
          "Saying animals have cell walls, or that all plants are non-motile without nuance (many have motile gametes or parts).",
        tags: ["Plantae", "Animalia", "kingdoms"],
      },
      {
        id: "t18-1-d7",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Outline how viruses are classified at this level of the syllabus. Explain why viruses are not placed in the three-domain system of Archaea, Bacteria and Eukarya.",
        modelAnswerPoints: [
          "Viruses classified by nucleic acid type: DNA or RNA; single-stranded or double-stranded.",
          "Viruses are not cells; three-domain system classifies cellular life.",
        ],
        workedSolution: [
          "At this level, viral classification emphasises the nature of the genome: whether the inherited information is DNA or RNA, and whether that genome is single-stranded or double-stranded, because these features determine replication strategy and underlie higher groupings used alongside structural information in professional taxonomy.",
          "This molecular basis is more fundamental for viruses than habitat or host, even though host range is biologically important, which is why examination answers should pair nucleic acid type with strandedness rather than only naming a disease.",
          "The three-domain scheme is an evolutionary framework for cellular organisms with ribosomes, membranes, and independent metabolism; viruses are acellular, lack a metabolism in the cell sense, and reproduce only by hijacking host machinery, so they are not treated as a fourth domain alongside Archaea, Bacteria and Eukarya in the standard school-level treatment.",
        ],
        commonMistake:
          "Placing viruses inside Bacteria because many infect bacteria, or omitting strandedness.",
        tags: ["viruses", "classification"],
      },
      {
        id: "t18-1-d8",
        noteId: "t18-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best matches the ecological species concept as usually applied in teaching?",
        options: [
          { id: "A", text: "Species are defined primarily by measurable niche and resource use in the ecosystem." },
          { id: "B", text: "Species are defined only by fertility of laboratory crosses, regardless of habitat." },
          { id: "C", text: "Species are defined solely by total body mass of individuals." },
          { id: "D", text: "Species are defined only by the number of bones in the skull." },
        ],
        correctOptionId: "A",
        explanation:
          "The ecological species concept ties species boundaries to roles, resource use, and interactions—i.e. niche-based reasoning—rather than to morphology alone or arbitrary single traits.",
        distractorRationale: {
          B: "That emphasis matches the biological species concept’s breeding focus, not the ecological concept’s niche focus.",
          C: "Mass is not a species concept used in the syllabus comparison.",
          D: "Bone counts are morphological data; they may support identification but are not the ecological concept itself.",
        },
        tags: ["species-concepts", "MCQ"],
      },
      {
        id: "t18-1-d9",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Explain why the biological species concept is difficult to apply to a museum collection of fossil mollusc shells, and state which alternative concept is usually more appropriate. Justify your answer in exam language.",
        modelAnswerPoints: [
          "Biological concept needs interbreeding / fertility data not preserved in dead shells.",
          "Morphological species concept more appropriate: compare shell form and structure.",
          "Acknowledge risk: cryptic species may look similar; still morphology is the available evidence.",
        ],
        workedSolution: [
          "The biological species concept requires information about gene flow and reproductive isolation—whether individuals could or would interbreed and produce fertile offspring under natural conditions—which is simply not encoded in accretionary shell material once the soft parts and behaviour are lost to decay.",
          "Preserved fossils therefore cannot be tested for breeding compatibility, seasonal mating, or hybrid fitness, so applying the biological concept would mean substituting guesswork for the very observations the concept is built on.",
          "Taxonomists instead use the morphological species concept, measuring shell shape, ornament, proportions, and growth lines to delimit species boundaries, which is repeatable and consistent with museum practice even though morphological similarity can occasionally mislead when cryptic species differ little in shell form.",
          "Acknowledging that limitation strengthens the answer: morphology is the best available concept, not a perfect substitute for breeding data.",
        ],
        commonMistake:
          "Asserting palaeontologists can still use breeding experiments, or recommending ecological niches without fossil environmental data.",
        tags: ["species-concepts", "application"],
      },
      {
        id: "t18-1-d10",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Integrate what you know about domains, the eukaryote hierarchy, and virus classification: explain where a named photosynthetic multicellular organism and a named DNA virus would each be placed in classification, and state one reason viruses are treated differently from cellular life.",
        modelAnswerPoints: [
          "Photosynthetic multicellular organism: Eukarya → appropriate kingdom (Plantae) → lower ranks as known → binomial species.",
          "DNA virus: classified by DNA genome and ss/ds; not assigned to domains as cellular organisms are.",
          "Viruses acellular / not independent cells; domains classify cellular organisms.",
        ],
        workedSolution: [
          "A green multicellular plant would be placed in domain Eukarya because it has membrane-bound nuclei and organelles, then in kingdom Plantae within that domain, and subsequently in a particular phylum, class, order, family, genus and species according to its structural and reproductive characters, ending in a binomial such as Quercus robur at the species level if that were the identification.",
          "A virus with a double-stranded DNA genome would be described as a DNA virus and further as double-stranded DNA in the syllabus scheme, rather than being inserted as if it were a tiny bacterium in domain Bacteria.",
          "The difference is conceptual: domains map the deepest branches of cellular life with ribosomal translation and membrane systems, whereas viruses are obligate intracellular parasites without a cellular organisation, so their classification axis is genome chemistry and structure, not kingdom membership inside Eukarya.",
        ],
        commonMistake:
          "Putting viruses in kingdom Monera or Plantae, or omitting ss/ds for the virus.",
        tags: ["integration", "classification"],
      },
    ],
    flashcards: [
      {
        id: "t18-1-f1",
        noteId: "t18-1",
        difficulty: 1,
        front: "Biological species concept — one-line idea.",
        back: "Natural interbreeding with fertile offspring; reproductive isolation between species (sexual groups).",
        examPhrasing: "State what is meant by the biological species concept.",
        tags: ["species"],
      },
      {
        id: "t18-1-f2",
        noteId: "t18-1",
        difficulty: 1,
        front: "Morphological species concept — one-line idea.",
        back: "Species delimited by observable structural / phenotypic similarity and diagnosable traits.",
        examPhrasing: "State what is meant by the morphological species concept.",
        tags: ["species"],
      },
      {
        id: "t18-1-f3",
        noteId: "t18-1",
        difficulty: 2,
        front: "Ecological species concept — one-line idea.",
        back: "Species defined by niche: resource use, interactions, and role in the ecosystem.",
        examPhrasing: "State what is meant by the ecological species concept.",
        tags: ["niche", "species"],
      },
      {
        id: "t18-1-f4",
        noteId: "t18-1",
        difficulty: 2,
        front: "Three domains — names.",
        back: "Archaea, Bacteria, Eukarya.",
        examPhrasing: "Name the three domains of life.",
        tags: ["domains"],
      },
      {
        id: "t18-1-f5",
        noteId: "t18-1",
        difficulty: 3,
        front: "Archaea vs Bacteria — two syllabus differences (not just ‘both small’).",
        back: "Different membrane lipids; different rRNA sequences; cell walls differ (peptidoglycan typical in bacteria, not in many Archaea).",
        examPhrasing: "State differences between Archaea and Bacteria.",
        tags: ["Archaea", "Bacteria"],
      },
      {
        id: "t18-1-f6",
        noteId: "t18-1",
        difficulty: 3,
        front: "Eukarya hierarchy — order from kingdom to species.",
        back: "Kingdom → phylum → class → order → family → genus → species.",
        examPhrasing: "Give the taxonomic hierarchy in Eukarya from kingdom to species.",
        tags: ["hierarchy"],
      },
      {
        id: "t18-1-f7",
        noteId: "t18-1",
        difficulty: 3,
        front: "Fungal cell wall polymer (common).",
        back: "Chitin (not cellulose).",
        examPhrasing: "Name a major component of fungal cell walls.",
        tags: ["Fungi"],
      },
      {
        id: "t18-1-f8",
        noteId: "t18-1",
        difficulty: 4,
        front: "Plant vs animal cell walls (syllabus level).",
        back: "Plant cells: cellulose cell walls. Animal cells: no cell walls (as in teaching comparisons).",
        examPhrasing: "State a major structural difference between plant and animal cells.",
        tags: ["Plantae", "Animalia"],
      },
      {
        id: "t18-1-f9",
        noteId: "t18-1",
        difficulty: 4,
        front: "Virus classification basis (9700).",
        back: "DNA or RNA genome; single-stranded or double-stranded.",
        examPhrasing: "Outline how viruses are classified at this level.",
        tags: ["viruses"],
      },
      {
        id: "t18-1-f10",
        noteId: "t18-1",
        difficulty: 5,
        front: "Why viruses are outside the three-domain system.",
        back: "Domains classify cellular organisms; viruses are acellular and not independent metabolising cells.",
        examPhrasing: "Explain why viruses are not placed in Archaea, Bacteria or Eukarya.",
        tags: ["viruses", "domains"],
      },
    ],
  },

  "t18-2": {
    noteId: "t18-2",
    drills: [
      {
        id: "t18-2-d1",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Define the terms ecosystem and niche.",
        modelAnswerPoints: [
          "Ecosystem: community of organisms interacting with one another and with the abiotic environment in an area.",
          "Niche: functional role of a species, including resources, habitat use, trophic relationships and interactions.",
        ],
        workedSolution: [
          "An ecosystem comprises the living community in a defined place together with the non-living factors such as climate, soil, water chemistry, and physical structure, and it includes the flows of energy and nutrients that link organisms to those abiotic conditions.",
          "A niche describes how a species actually ‘fits’ into that ecosystem: which resources it uses, where and when it lives, how it obtains energy, and how it interacts with competitors, predators, mutualists, and pathogens, rather than being just a place name alone.",
        ],
        commonMistake:
          "Defining niche only as ‘address’ or habitat without role, or treating ecosystem as only a list of species.",
        tags: ["definitions", "ecology"],
      },
      {
        id: "t18-2-d2",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 2,
        marks: 7,
        stem: "Explain that biodiversity can be assessed at different levels, including the number and range of different ecosystems and habitats, the number of species and their relative abundance, and genetic variation within each species.",
        modelAnswerPoints: [
          "Ecosystem / habitat diversity: variety of ecosystems, communities, and physical settings.",
          "Species diversity: species richness and evenness / relative abundance (not species count alone).",
          "Genetic diversity: allelic / heritable variation within populations of a species.",
        ],
        workedSolution: [
          "At the broadest scale, biodiversity includes how many distinct ecosystem types or major habitat mosaics occur in a region, because different physical settings support different community compositions and processes, so losing a rare habitat type can erase specialised assemblages even if some species also live elsewhere.",
          "Species-level assessment must combine how many species are present—richness—with how evenly individuals are divided among them, because a plantation dominated by one tree species with a few rare natives is less diverse in the ecological sense than a mixed forest with similar richness but more even representation.",
          "Within each species, genetic variation among individuals and populations underpins adaptation to pests, climate, and disturbance, so conservation of biodiversity is not complete if only ecosystem maps and species lists are saved while unique locally adapted gene pools disappear.",
        ],
        commonMistake:
          "Equating biodiversity only to species richness, or ignoring evenness and genetic variation entirely.",
        tags: ["biodiversity", "levels"],
      },
      {
        id: "t18-2-d3",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain the importance of random sampling when determining the biodiversity of an area.",
        modelAnswerPoints: [
          "Reduces investigator bias (choosing ‘typical’ or easy spots).",
          "Gives unbiased estimate / each part of area a chance to be sampled.",
          "Supports valid comparison between sites / statistical inference.",
        ],
        workedSolution: [
          "If quadrat or transect positions are chosen subjectively, humans naturally favour accessible ground, visually striking patches, or places where a target species is already visible, which inflates or deflates counts relative to the whole site and makes results difficult to repeat.",
          "Random coordinates or a random start with systematic rules give every location an equal chance under the design, which is the standard way to obtain a representative snapshot of abundance and species composition for the defined sampling universe.",
          "Only with such representativeness can confidence limits, tests, or comparisons between treatments and control areas be interpreted honestly in reports and management decisions.",
        ],
        commonMistake:
          "Saying random sampling ‘increases species’ rather than reducing bias in estimation.",
        tags: ["sampling", "methods"],
      },
      {
        id: "t18-2-d4",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 3,
        marks: 8,
        stem: "Describe and explain the use of frame quadrats, line transects and belt transects to assess the distribution and abundance of organisms in an area. Name a type of organism each method suits especially well.",
        modelAnswerPoints: [
          "Frame quadrat: counts or % cover within known area for sessile / slow organisms; scaled to unit area.",
          "Line transect: organisms on/under line or at points—good for gradients / change along a line.",
          "Belt transect: strip sampled with quadrats along line—more data than single line, used where wider swath needed.",
        ],
        workedSolution: [
          "A frame quadrat encloses a small known area of habitat; inside it you count individuals of sedentary species such as turf plants or barnacles, or estimate percentage cover for overlapping plants, then scale up to the whole habitat only after many random or systematic replicate placements, which is why it is ideal for sessile or very slow organisms that stay within the frame during observation.",
          "A line transect lays a tape across the habitat and records either every individual that touches the tape or species presence at regular interval points along the gradient, which is efficient for showing how community composition changes with distance along moisture, altitude, or pollution gradients because the line samples the environmental axis directly.",
          "A belt transect combines the line with a defined width, often by placing a series of contiguous or spaced quadrats along the tape, so you sample a strip rather than a hairline, improving detection of rare or small organisms and giving better abundance data for mobile but non-randomly distributed species than a single linear contact record alone.",
        ],
        commonMistake:
          "Recommending quadrats for fast-flying birds without qualification, or confusing line with belt transect width.",
        tags: ["quadrats", "transects"],
      },
      {
        id: "t18-2-d5",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "In a mark-release-recapture study, 45 snails are marked on the first day and released. On the second day, 60 snails are captured, of which 15 carry marks. Using the Lincoln index in the form N = (number marked first × total in second sample) ÷ (number of marked individuals recaptured in second sample), estimate population size. State three important assumptions of the method.",
        modelAnswerPoints: [
          "N = (45 × 60) / 15 = 180 snails (allow correct arithmetic from shown formula).",
          "Assumptions e.g.: closed population (no large immigration/emigration/birth/death between samples).",
          "Marks retained and not harmful; random mixing of marked and unmarked; second sample random.",
        ],
        workedSolution: [
          "Substitute into the Lincoln index: N = (M × C) / R with M = 45 marked first, C = 60 caught second, R = 15 marked in the second catch, giving N = (45 × 60) / 15 = 2700 / 15 = 180 snails in the defined population at the time of sampling.",
          "The estimate assumes the population is approximately closed between capture events, meaning large-scale immigration, emigration, births, or deaths do not greatly change N or the proportion marked, otherwise the ratio of marked to unmarked in the second sample no longer reflects the whole population.",
          "Marks must stay visible and must not alter behaviour or survival relative to unmarked individuals, otherwise recapture probability is biased.",
          "Marked individuals must mix randomly with unmarked ones so the second sample is a fair draw, and capture in the second round should itself be unbiased, which in practice requires careful effort and often multiple recapture days for mobile animals.",
        ],
        commonMistake:
          "Inverting the formula, or listing assumptions that are vague (‘be careful’) without biological meaning.",
        tags: ["Lincoln", "mark-release"],
      },
      {
        id: "t18-2-d6",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem:
          "At six sites, water nitrate concentration (mg dm^-3) and mayfly abundance (individuals per minute) were recorded:\nSite: 1, 2, 3, 4, 5, 6\nNitrate: 2, 4, 6, 8, 10, 12\nMayfly: 18, 15, 12, 9, 6, 3\nUsing the formula for Spearman’s rank correlation coefficient r_s provided in the examination, calculate r_s and state whether nitrate and mayfly abundance show a negative monotonic association.",
        modelAnswerPoints: [
          "Rank nitrate 1–6 in order (already increasing); rank mayfly 6,5,4,3,2,1 (reverse order).",
          "Perfect negative monotonic relationship across the six paired ranks.",
          "r_s = −1 (accept strong negative correlation near −1 if working shown with d² method).",
          "Interpretation: higher nitrate rank associates with lower mayfly rank (negative association).",
        ],
        workedSolution: [
          "Assign ranks to each variable separately: nitrate ranks are 1 through 6 in ascending order.",
          "Mayfly counts decrease monotonically, so ranks are 6, 5, 4, 3, 2, 1 from site 1 to site 6.",
          "Each site therefore has paired ranks that differ by a constant offset, giving the maximum negative monotonic association.",
          "Using the Spearman formula with these ranks gives r_s = −1, so nitrate and mayfly abundance are perfectly negatively associated in this data set.",
          "This indicates that sites with higher nitrate tend to have lower mayfly abundance, but correlation alone does not prove nitrate causes the decline without further experimental evidence.",
        ],
        commonMistake:
          "Using Pearson on raw counts without ranking, or forgetting to rank each variable separately before applying the Spearman formula.",
        tags: ["Spearman", "calculation", "statistics"],
      },
      {
        id: "t18-2-d7",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem:
          "Paired measurements of soil moisture (% ) and grass shoot mass (g per quadrat) at five quadrats are:\nMoisture: 10, 20, 30, 40, 50\nMass: 4.0, 6.0, 8.0, 10.0, 12.0\nUsing the formula for Pearson’s product-moment correlation coefficient r provided in the examination, calculate r and comment on the strength and direction of the linear association.",
        modelAnswerPoints: [
          "Both variables are continuous and the relationship is linear (mass increases by 2.0 g for every 10% moisture).",
          "Calculation with the provided formula gives r = +1 (perfect positive linear correlation).",
          "Direction: positive — higher moisture is associated with higher mass.",
          "Strength: very strong (|r| = 1 within rounding of the given perfect data).",
        ],
        workedSolution: [
          "Plotting or inspecting the pairs shows mass = 2.0 + 0.2 × moisture, a straight-line relationship suitable for Pearson’s r.",
          "Substitute the five (x, y) pairs into the examination formula for r; with perfectly collinear linear data the numerator matches the denominator and r = +1.",
          "A positive r close to +1 means that as soil moisture increases, grass shoot mass increases in a consistent linear way across these quadrats.",
          "State that r describes association only: it does not by itself prove that moisture causes higher growth without controlled manipulation or additional mechanism evidence.",
        ],
        commonMistake:
          "Reporting r without commenting on direction and strength, or using Spearman when the syllabus expects Pearson for clearly linear continuous data.",
        tags: ["Pearson", "calculation", "statistics"],
      },
      {
        id: "t18-2-d8",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 3,
        marks: 8,
        stem: "In a small grassland plot, three insect species are sampled: species A 45 individuals, species B 45 individuals, species C 10 individuals (total N = 100). Using the Simpson’s index of diversity in the form D = 1 − Σ n_i(n_i − 1) / (N(N − 1)), calculate D for this sample. State the significance of a value of D close to 0 versus close to 1.",
        modelAnswerPoints: [
          "Compute Σ n(n−1): 45×44 + 45×44 + 10×9 = 1980 + 1980 + 90 = 4050.",
          "N(N−1) = 100×99 = 9900.",
          "D = 1 − 4050/9900 ≈ 1 − 0.409 = 0.591 (accept correct rounding).",
          "D nearer 1: higher diversity (more even / low chance two random individuals same species). D nearer 0: lower diversity (more dominated by one or few species).",
        ],
        workedSolution: [
          "First compute each species’ contribution to the double-count term: for A, n = 45 gives 45 × 44 = 1980; for B, the same 1980; for C, 10 × 9 = 90; summing gives Σ n_i(n_i − 1) = 4050.",
          "The denominator for the finite-sample correction is N(N − 1) = 100 × 99 = 9900, so the Simpson dominance component Σ n_i(n_i − 1) / (N(N − 1)) = 4050 / 9900 = 0.4091 to four decimal places.",
          "Simpson’s index of diversity is D = 1 minus that fraction, D = 1 − 0.4091 = 0.5909, which is moderately high for only three species because the two common species are perfectly even at 45 individuals each, which increases evenness relative to a strongly skewed sample of the same richness.",
          "Values of D close to 1 indicate high biodiversity in the sense that the probability that two randomly chosen individuals are different species is large—richness is high and/or abundances are even—whereas values close to 0 indicate that one or a few species dominate and two random draws will usually match, which is characteristic of low diversity under this index.",
        ],
        commonMistake:
          "Using N^2 instead of N(N−1), or inverting the interpretation of D relative to the formula used.",
        tags: ["Simpson", "calculation"],
      },
      {
        id: "t18-2-d9",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Compare the situations in which you would choose Spearman’s rank correlation rather than Pearson’s linear correlation when analysing ecological data. Keep to the distinctions examiners reward.",
        modelAnswerPoints: [
          "Pearson: linear, parametric assumptions, interval/ratio data.",
          "Spearman: ranks, monotonic relationship, outliers or non-normal data, ordinal data.",
        ],
        workedSolution: [
          "Pearson’s correlation should be selected when both variables are measured on continuous scales, the relationship is expected to follow a straight line, and residual structure is compatible with parametric inference after plotting, because it uses the raw magnitudes of deviations and has the highest power when those assumptions hold.",
          "Spearman’s correlation should be selected when variables are naturally ranked, when distributions are strongly skewed or heavy-tailed, when monotonic but clearly non-linear saturating curves are anticipated, or when outliers would disproportionately leverage Pearson’s slope-based metric, because Spearman works on ranks and therefore reflects consistent increasing or decreasing association without assuming linearity.",
          "In biodiversity surveys, Spearman is therefore common for community indices and ordered stress levels, whereas Pearson may be reserved for pairs of continuous physical measurements where a linear response is plausible.",
        ],
        commonMistake:
          "Claiming Spearman ‘always’ better for ecology, or Pearson for small samples regardless of linearity.",
        tags: ["statistics", "comparison"],
      },
      {
        id: "t18-2-d10",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Design a brief field programme to compare plant species diversity between a mown grass verge and an adjacent unmown strip. Include random sampling, choice of quadrats or transects, one measure of diversity you could calculate, and one statistical comparison you could apply to a measured environmental variable and a species count.",
        modelAnswerPoints: [
          "Random coordinates / random starts with systematic offsets in each strip.",
          "Frame quadrats or belt transects along each strip (sessile plants).",
          "Simpson’s D or species richness + evenness discussion; calculate from pooled quadrats per strip.",
          "Pearson or Spearman to relate, e.g., sward height vs species count per quadrat—justify choice.",
        ],
        workedSolution: [
          "Lay two parallel sampling axes, one entirely in the mown treatment and one in the unmown treatment, generate random distances along each using a random-number table to place at least fifteen 0.5 m × 0.5 m quadrats per treatment, recording every vascular plant species and its abundance or cover class per quadrat so that each quadrat is independent under the design.",
          "Use the same quadrat size and the same counting rules in both strips so that differences reflect management, not method, and avoid edge effects by staying a defined distance from boundaries between treatments.",
          "From the tabulated abundances, calculate Simpson’s index of diversity separately for each strip by pooling individuals or by averaging per-quadrat indices according to a pre-stated rule, then compare the two index values qualitatively or with a bootstrap or randomisation test if the scheme extends beyond A-level minimum.",
          "Measure continuous light availability or soil moisture in each quadrat and use Pearson correlation if scatterplots of moisture versus total plant count per quadrat appear linear, otherwise Spearman rank correlation if counts are skewed, explicitly stating that correlation quantifies association between the abiotic gradient and local species density and should be interpreted alongside the diversity indices for a full picture.",
        ],
        commonMistake:
          "No randomisation, or using mark-release-recapture for grass without justification.",
        tags: ["integration", "fieldwork"],
      },
    ],
    flashcards: [
      {
        id: "t18-2-f1",
        noteId: "t18-2",
        difficulty: 1,
        front: "Define ecosystem (9700 style).",
        back: "Community of organisms plus abiotic environment interacting as a system in an area.",
        examPhrasing: "Define ecosystem.",
        tags: ["definitions"],
      },
      {
        id: "t18-2-f2",
        noteId: "t18-2",
        difficulty: 1,
        front: "Define niche (9700 style).",
        back: "Functional role: resources, habitat use, trophic position, interactions.",
        examPhrasing: "Define niche.",
        tags: ["definitions"],
      },
      {
        id: "t18-2-f3",
        noteId: "t18-2",
        difficulty: 2,
        front: "Three levels at which biodiversity is assessed.",
        back: "Ecosystem/habitat variety; species richness and relative abundance; genetic variation within species.",
        examPhrasing: "Explain levels of biodiversity.",
        tags: ["biodiversity"],
      },
      {
        id: "t18-2-f4",
        noteId: "t18-2",
        difficulty: 2,
        front: "Why random sampling?",
        back: "Reduces bias; supports representative estimates and fair comparison.",
        examPhrasing: "Explain the importance of random sampling.",
        tags: ["sampling"],
      },
      {
        id: "t18-2-f5",
        noteId: "t18-2",
        difficulty: 3,
        front: "Line transect vs belt transect — distinction.",
        back: "Line: samples along a narrow line/points. Belt: strip (line + width), often quadrats along line—more area.",
        examPhrasing: "Distinguish line and belt transects.",
        tags: ["transects"],
      },
      {
        id: "t18-2-f6",
        noteId: "t18-2",
        difficulty: 3,
        front: "Lincoln index — word formula.",
        back: "N ≈ (marked first × total second catch) ÷ marked in second catch.",
        examPhrasing: "State the Lincoln index relationship used for population size.",
        tags: ["Lincoln"],
      },
      {
        id: "t18-2-f7",
        noteId: "t18-2",
        difficulty: 4,
        front: "Spearman vs Pearson — one decision rule.",
        back: "Pearson: linear, continuous, parametric OK. Spearman: monotonic / ranked / outliers / ordinal.",
        examPhrasing: "When choose Spearman’s rank correlation over Pearson’s?",
        tags: ["statistics"],
      },
      {
        id: "t18-2-f8",
        noteId: "t18-2",
        difficulty: 4,
        front: "Correlation implies …?",
        back: "Association / pattern; not by itself proof of causation.",
        examPhrasing: "What can safely be concluded from a significant correlation?",
        tags: ["statistics"],
      },
      {
        id: "t18-2-f9",
        noteId: "t18-2",
        difficulty: 5,
        front: "Simpson’s index of diversity D — higher value means …",
        back: "Higher D → greater diversity: lower probability two random individuals are the same species (for standard 1−dominance form).",
        examPhrasing: "State the significance of different values of Simpson’s index of diversity.",
        tags: ["Simpson"],
      },
      {
        id: "t18-2-f10",
        noteId: "t18-2",
        difficulty: 5,
        front: "Mark-release key assumption — one line.",
        back: "Population approximately closed; marks kept; random mixing; recapture unbiased.",
        examPhrasing: "State one assumption of the Lincoln index.",
        tags: ["mark-release"],
      },
    ],
  },

  "t18-3": {
    noteId: "t18-3",
    drills: [
      {
        id: "t18-3-d1",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 2,
        marks: 8,
        stem: "Explain why populations and species can become extinct as a result of climate change, competition, hunting by humans, and degradation and loss of habitats. Develop each mechanism in at least one clear sentence.",
        modelAnswerPoints: [
          "Climate change: altered temperature / rainfall beyond tolerances; phenology mismatch; sea-level / range shift barriers.",
          "Competition: invasive or native competitors reduce resource availability; exclusion.",
          "Hunting: direct mortality faster than recruitment; age structure collapse.",
          "Habitat loss/degradation: area, quality, connectivity reduced; populations too small / inbred.",
        ],
        workedSolution: [
          "Climate change can drive extinction when the rate of environmental shift outpaces adaptive evolution or dispersal, so specialists with narrow thermal or hydric tolerances cannot maintain viable populations in their former range, and even generalists may fail if seasonal cues for breeding or migration no longer match food availability.",
          "Competition from ecologically similar invaders or from native species released from control can depress fecundity and survival by pre-empting food, nesting cavities, or light, so a rare endemic that already exists at carrying capacity may be competitively excluded without any new physical destruction of habitat.",
          "Direct hunting or overharvest by humans removes individuals faster than replacement, preferentially taking large adults or breeding females in some fisheries and megafauna cases, which collapses recruitment and can push small populations below an Allee threshold where survival becomes unlikely even if partial protection later returns.",
          "Habitat degradation and fragmentation reduce the total area of suitable environment, insert edges with novel predation and microclimates, and break metapopulation connectivity, leaving subpopulations too small to buffer demographic stochasticity and inbreeding depression, which raises extinction risk even when climate is otherwise tolerable.",
        ],
        commonMistake:
          "Listing factors as single words (‘pollution’) without the required four mechanisms or extinction logic.",
        tags: ["extinction", "threats"],
      },
      {
        id: "t18-3-d2",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 2,
        marks: 7,
        stem: "Outline reasons for the need to maintain biodiversity.",
        modelAnswerPoints: [
          "Direct / utilitarian: food, medicines, materials, genetic resources for crops.",
          "Ecosystem services: pollination, water regulation, nutrient cycling, climate moderation.",
          "Ethical / aesthetic: intrinsic value, cultural heritage.",
          "Future options / insurance: unknown future uses; resilience.",
        ],
        workedSolution: [
          "Human societies depend on biodiverse sources of food, fibres, timber, and pharmaceuticals, many originally wild species or wild relatives whose genes can be crossed into crops to improve disease resistance, so losing species forecloses resources we do not yet fully catalogue.",
          "Ecosystems with intact species assemblages deliver supporting and regulating services—pollination of crops, purification and storage of fresh water, formation and protection of soils, and modulation of regional climates through evapotranspiration and carbon storage—that degrade when key functional groups disappear.",
          "Independent of utility, many cultures assign ethical and aesthetic value to wild species and landscapes, and biodiversity underpins tourism and identity, so its loss is also a social and heritage loss rather than only a technical resource issue.",
          "Finally, maintaining genetic and species diversity preserves options for future environmental change; redundant species can become critical when conditions shift, which is why insurance and resilience arguments complement immediate economic benefits in policy-level answers.",
        ],
        commonMistake:
          "Only saying ‘medicines from plants’ without ecosystem services or ethical dimensions.",
        tags: ["conservation", "value"],
      },
      {
        id: "t18-3-d3",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 2,
        marks: 8,
        stem: "Outline the roles of zoos, botanic gardens, conserved areas (including national parks and marine parks), ‘frozen zoos’ and seed banks in the conservation of endangered species.",
        modelAnswerPoints: [
          "Zoos / aquaria: captive breeding, research, education, reintroduction stock, insurance populations.",
          "Botanic gardens: ex-situ conservation of rare plants, propagation, research, education.",
          "National / marine parks: in-situ protection of habitats and species; regulation of extractive uses.",
          "Frozen zoos / seed banks: long-term germplasm storage for future use and research.",
        ],
        workedSolution: [
          "Modern accredited zoos maintain demographically and genetically managed captive populations of critically endangered vertebrates, conduct husbandry and veterinary research, engage the public in conservation funding and behaviour change, and sometimes supply individuals for reintroduction once threats in the wild are mitigated.",
          "Botanic gardens curate living collections of threatened plants, propagate material for restoration projects, bank reproductive tissues, and study pests and diseases away from the last wild populations, reducing the risk that a single catastrophe in nature loses the taxon entirely.",
          "National parks and marine protected areas preserve large in-situ ecosystems where natural processes such as predation, disturbance regimes, and recruitment can continue, while regulations limit logging, fishing, mining, and development that would otherwise degrade core habitat for many co-occurring species.",
          "Frozen zoos store gametes and embryos cryogenically, and seed banks dry and freeze seeds at low temperature, providing long-term genetic repositories that can outlast political or funding cycles and support future reintroduction or breeding when technology and site security improve.",
        ],
        commonMistake:
          "Claiming zoos replace the need for protected areas, or omitting frozen zoos/seed banks entirely.",
        tags: ["ex-situ", "in-situ"],
      },
      {
        id: "t18-3-d4",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Describe methods of assisted reproduction used in the conservation of endangered mammals, limited to IVF, embryo transfer and surrogacy.",
        modelAnswerPoints: [
          "IVF: eggs fertilised in vitro; embryos cultured; can select timing and parentage.",
          "Embryo transfer: embryo moved to a recipient female to establish pregnancy.",
          "Surrogacy: related use of another individual (often another subspecies/species in some programmes) to carry pregnancy when dam cannot.",
        ],
        workedSolution: [
          "In vitro fertilisation collects mature oocytes from hormonally stimulated females and combines them with sperm under controlled laboratory conditions, producing embryos that can be cultured before transfer, which helps when natural mating is impossible because individuals are separated by institutions or behaviourally incompatible.",
          "Embryo transfer moves a developed embryo into the uterus of a hormonally prepared recipient female so that pregnancy and birth occur in a surrogate that may be a better physiological match or less endangered, multiplying the genetic contribution of rare parents beyond what natural reproduction would allow per year.",
          "Broader surrogacy programmes in some taxa use related species as gestational carriers when the endangered dam’s uterus is unavailable, always under strict genetic management to ensure offspring are still the target taxon, which illustrates how ARTs link to overall population recovery planning rather than isolated technical tricks.",
        ],
        commonMistake:
          "Describing cloning as if it were listed, or confusing IVF with artificial insemination without embryo culture.",
        tags: ["ART", "mammals"],
      },
      {
        id: "t18-3-d5",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Explain reasons for controlling invasive alien species in conservation management.",
        modelAnswerPoints: [
          "Predation / herbivory on native species unused to them.",
          "Competition for resources; niche displacement.",
          "Disease introduction; hybridisation swamping natives.",
          "Ecosystem engineering / altered fire or hydrology regimes.",
        ],
        workedSolution: [
          "Invasive alien species often arrive without the suite of predators, pathogens, and competitors that limit them in their native range, so their populations can grow rapidly and impose novel predation or grazing pressure on ecologically naive natives that lack effective defences.",
          "They may outcompete natives for space, light, pollinators, or nest sites, shifting community composition toward the invader and sometimes driving local extinctions of specialists that cannot persist in the transformed environment.",
          "Invasives can also vector new diseases or hybridise with rare relatives, genetically swamping locally adapted lineages, and physical engineers like certain plants or mammals can change fire frequency, hydrology, or soil chemistry, locking in a new stable state hostile to the original biodiversity.",
          "Control—mechanical removal, biocontrol where safe, hunting or trapping, and biosecurity prevention—is therefore aimed at reducing these novel interaction rates before they become irreversible.",
        ],
        commonMistake:
          "Saying invasives are ‘bad’ without mechanistic links to natives, or blaming climate change alone.",
        tags: ["invasive", "management"],
      },
      {
        id: "t18-3-d6",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Outline the role in conservation of the International Union for Conservation of Nature (IUCN) and the Convention on International Trade in Endangered Species of Wild Fauna and Flora (CITES).",
        modelAnswerPoints: [
          "IUCN: Red List assessments; categories of extinction risk; science / guidance for priority setting.",
          "CITES: international agreement regulating import/export of listed species; permits; controls trade to reduce overexploitation.",
        ],
        workedSolution: [
          "IUCN coordinates expert networks to assess extinction risk using standardised Red List criteria, publishing global status accounts that governments, NGOs, and funders use to prioritise species and sites, and it issues science-based guidelines for protected area design, species recovery, and sustainable use.",
          "While IUCN categories are advisory, their transparent evidence base underpins national legislation and international targets such as those linked to biodiversity conventions, so they function as the common language of conservation status even when politics lags science.",
          "CITES is a binding treaty for signatory states that lists species in appendices according to threat and trade impact, requiring export permits showing legal capture and non-detrimental harvest for listed taxa, thereby channelling international trade away from endangered species toward sustainable or fully prohibited trade models.",
          "Customs enforcement, species identification training, and cooperation with IUCN data together make CITES a practical trade-control layer complementing in-situ habitat protection for species exploited in global markets.",
        ],
        commonMistake:
          "Saying IUCN enforces laws directly, or that CITES protects habitats rather than regulating international trade.",
        tags: ["IUCN", "CITES", "policy"],
      },
      {
        id: "t18-3-d7",
        noteId: "t18-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which option best describes a primary purpose of CITES?",
        options: [
          { id: "A", text: "To regulate international trade in listed wild species to prevent overexploitation." },
          { id: "B", text: "To fund national park construction in every country equally." },
          { id: "C", text: "To sequence the genomes of all endangered species by 2030." },
          { id: "D", text: "To replace national wildlife laws with optional guidance." },
        ],
        correctOptionId: "A",
        explanation:
          "CITES controls import, export, and re-export of specimens of listed species through a permit system aligned to conservation risk and sustainable use.",
        distractorRationale: {
          B: "CITES is a trade convention, not a general park-funding mechanism.",
          C: "Genome sequencing is not the purpose of CITES.",
          D: "CITES works with national legislation; it does not abolish it.",
        },
        tags: ["CITES", "MCQ"],
      },
      {
        id: "t18-3-d8",
        noteId: "t18-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which is the most accurate characterisation of the IUCN Red List?",
        options: [
          { id: "A", text: "A global standard for assessing extinction risk and publishing species status categories." },
          { id: "B", text: "A list of animals that may be hunted without restriction worldwide." },
          { id: "C", text: "A patent database for genetically modified crops." },
          { id: "D", text: "A certificate that a zoo may keep any species legally." },
        ],
        correctOptionId: "A",
        explanation:
          "The Red List applies standardised criteria (A–E) to classify species into categories from Least Concern to Extinct, summarising extinction risk for conservation planning.",
        distractorRationale: {
          B: "The Red List signals risk; it is not a hunting licence.",
          C: "Patents are unrelated to IUCN species assessments.",
          D: "Zoo licensing is a national regulatory matter, not an IUCN Red List function.",
        },
        tags: ["IUCN", "MCQ"],
      },
      {
        id: "t18-3-d9",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Synthesise how habitat loss and climate change can interact to increase extinction risk for a mountain forest specialist species, and state one conservation response that addresses each driver.",
        modelAnswerPoints: [
          "Habitat loss shrinks area and fragments populations (Allee, inbreeding).",
          "Climate change shifts isotherms upslope; specialist may have nowhere to go if summits are built or deforested.",
          "Responses: protected corridors / restore habitat; assisted migration or ex-situ breeding as context-appropriate.",
        ],
        workedSolution: [
          "Clearing lower-elevation forest for agriculture not only removes individuals directly but leaves the remaining population in smaller, more isolated patches where random demographic fluctuations and inbreeding reduce viability, which is classic small-population ecology even before climate acts.",
          "Warming climates move suitable temperature and moisture envelopes upward along mountain slopes, so a cool-adapted specialist must track that band; if the summit zone is already narrow or degraded, the species has no upslope refuge, producing an ‘escalator to extinction’ unless connectivity to higher ground exists.",
          "Conservation responses pair in-situ expansion and restoration of elevational corridors with strict protected-area management to counter habitat loss, while climate-smart plans may include ex-situ conservation of genetic lines and, in some controversial cases, assisted migration trials where natural dispersal is blocked by human land use.",
        ],
        commonMistake:
          "Treating habitat loss and climate as independent when the question asks for interaction.",
        tags: ["climate", "habitat"],
      },
      {
        id: "t18-3-d10",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Give a concise case for why maintaining genetic diversity within crop wild relatives matters for food security, linking to biodiversity value and one ex-situ conservation method that preserves that diversity.",
        modelAnswerPoints: [
          "Wild relatives carry resistance / stress-tolerance alleles not present in cultivars.",
          "Biodiversity value: future breeding / insurance against pests and climate.",
          "Seed banks store seeds long-term; can supply material for crossing.",
        ],
        workedSolution: [
          "Domesticated varieties are genetically narrowed by selection for yield and uniformity, whereas their wild relatives in natural populations retain standing variation for drought, salinity, disease, and pest resistance that can be crossed or introgressed when new challenges appear in agriculture.",
          "Losing those populations therefore erodes the raw material for adaptive plant breeding, which is a direct utilitarian reason to maintain biodiversity often emphasised alongside cultural and ecosystem-service arguments.",
          "Seed banking in international and national vaults preserves orthodox seeds under controlled humidity and temperature, providing ex-situ insurance that researchers can withdraw for characterisation and crossing if field populations decline, complementing in-situ reserves that allow continued co-evolution with pests and climate in real landscapes.",
        ],
        commonMistake:
          "Only aesthetic arguments, or naming seed banks without explaining genetic insurance for crops.",
        tags: ["integration", "genetic-resources"],
      },
    ],
    flashcards: [
      {
        id: "t18-3-f1",
        noteId: "t18-3",
        difficulty: 1,
        front: "Extinction — four syllabus drivers (headings).",
        back: "Climate change; competition; hunting by humans; habitat degradation/loss.",
        examPhrasing: "Explain factors that can cause extinction.",
        tags: ["extinction"],
      },
      {
        id: "t18-3-f2",
        noteId: "t18-3",
        difficulty: 1,
        front: "One ecosystem service from biodiversity.",
        back: "Examples: pollination, water purification, nutrient cycling, climate regulation.",
        examPhrasing: "Give a reason to maintain biodiversity linked to ecosystem function.",
        tags: ["services"],
      },
      {
        id: "t18-3-f3",
        noteId: "t18-3",
        difficulty: 2,
        front: "Zoo — conservation role (one line).",
        back: "Captive breeding, research, education, insurance population, possible reintroduction.",
        examPhrasing: "Outline the role of zoos in conserving endangered species.",
        tags: ["zoos"],
      },
      {
        id: "t18-3-f4",
        noteId: "t18-3",
        difficulty: 2,
        front: "National park vs marine park — shared idea.",
        back: "In-situ protected areas; regulation of damaging uses; habitat/species conservation.",
        examPhrasing: "State the role of conserved areas in conservation.",
        tags: ["protected-areas"],
      },
      {
        id: "t18-3-f5",
        noteId: "t18-3",
        difficulty: 3,
        front: "Seed bank vs frozen zoo — what is stored?",
        back: "Seed bank: seeds / plant propagules. Frozen zoo: gametes, embryos, other cells cryopreserved.",
        examPhrasing: "Distinguish seed banks and frozen zoos.",
        tags: ["ex-situ"],
      },
      {
        id: "t18-3-f6",
        noteId: "t18-3",
        difficulty: 3,
        front: "IVF — one-line definition (mammals).",
        back: "Oocytes fertilised outside the body; embryos produced in culture for transfer or research.",
        examPhrasing: "Describe IVF as an assisted reproduction method.",
        tags: ["ART"],
      },
      {
        id: "t18-3-f7",
        noteId: "t18-3",
        difficulty: 4,
        front: "Embryo transfer — idea.",
        back: "Embryo placed into recipient uterus to establish pregnancy (carries offspring to term).",
        examPhrasing: "Describe embryo transfer in conservation breeding.",
        tags: ["ART"],
      },
      {
        id: "t18-3-f8",
        noteId: "t18-3",
        difficulty: 4,
        front: "Surrogacy — conservation context.",
        back: "Another female gestates the embryo when intended dam cannot; may be related species in some programmes (managed).",
        examPhrasing: "Describe surrogacy as an assisted reproduction method.",
        tags: ["ART"],
      },
      {
        id: "t18-3-f9",
        noteId: "t18-3",
        difficulty: 5,
        front: "IUCN — two roles.",
        back: "Red List extinction-risk categories; scientific guidance and priority setting (not direct law enforcement).",
        examPhrasing: "Outline the role of IUCN in conservation.",
        tags: ["IUCN"],
      },
      {
        id: "t18-3-f10",
        noteId: "t18-3",
        difficulty: 5,
        front: "CITES — core mechanism.",
        back: "Lists species in appendices; permits control international trade to avoid overexploitation of wild fauna/flora.",
        examPhrasing: "Outline the role of CITES.",
        tags: ["CITES"],
      },
    ],
  },
};
