import type { SubtopicPracticePack } from "./types";

/**
 * Topic 10 (9700 Biology) practice — `data/courses/biology-9700.json` (`t10-1`, `t10-2`).
 *
 * **`t10-2` (Antibiotics)** — Crosswalk to `data/syllabus/biology-9700-learning-outcomes.md` §10.2:
 * d1–d3 penicillin / bacterial cell wall vs viruses; d4–d7 resistance, consequences, mitigation;
 * d8–d10 consolidate mechanism and exam technique (MCQs + discussion).
 *
 * **`t10-1` (Infectious diseases)** — The repository extract `biology-9700-learning-outcomes.md` lists **§10.2
 * only** under Topic 10 (**§10.1 is missing** from the extract). This pack is authored against **standard
 * 9700 Topic 10.1** (pathogens, transmission, named diseases and agents, HIV outline, social/economic
 * discussion). Crosswalk: d1 definitions; d2 transmission routes; d3 cholera / Vibrio; d4 TB /
 * Mycobacterium; d5 malaria / Plasmodium; d6 HIV; d7 social/economic factors; d8–d10 application /
 * comparison / MCQs.
 */
export const BIOLOGY_TOPIC10_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t10-1": {
    noteId: "t10-1",
    drills: [
      {
        id: "t10-1-d1",
        noteId: "t10-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define the term pathogen. State what is meant by an infectious disease in humans, and distinguish clearly between the pathogen and the disease it causes.",
        modelAnswerPoints: [
          "A pathogen is a biological agent (microorganism or virus) that causes disease after entering the host and multiplying or using host cells.",
          "An infectious disease is a disorder caused by a pathogen that can be transmitted from an infected host to another susceptible host (directly or indirectly).",
          "The pathogen is the organism or virus; the disease is the harmful condition or syndrome in the host (signs, symptoms, pathology).",
        ],
        workedSolution: [
          "A pathogen is an organism or virus capable of causing disease when it infects a host; in syllabus work this usually means bacteria, viruses, protoctists, fungi or multicellular parasites that can establish infection and harm tissues or physiology.",
          "An infectious disease is an illness in which a pathogen is transmitted from an infected individual or reservoir to a new host, so the same type of agent can spread in a population through defined routes rather than arising only from non-infectious causes.",
          "It is important to separate the agent from the syndrome: for example, *Mycobacterium tuberculosis* is the bacterial pathogen, whereas tuberculosis is the chronic lung disease that results from infection and the host response.",
          "Similarly, *Plasmodium* is the protoctistan parasite that causes the disease malaria; naming the pathogen and the disease correctly is part of clear biological communication in examination answers.",
        ],
        commonMistake:
          "Using ‘pathogen’ and ‘disease’ interchangeably, or defining a pathogen only as ‘a germ’ without stating it causes disease in a host.",
        tags: ["definitions", "pathogens"],
      },
      {
        id: "t10-1-d2",
        noteId: "t10-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Outline the main modes of transmission of human infectious diseases, giving at least one example route for each of: airborne or droplet spread; faecal–oral (ingestion of contaminated material); vector-borne transmission; and transmission through blood or sexual contact.",
        modelAnswerPoints: [
          "Airborne / droplet: pathogens in droplets or aerosols from breathing, coughing or sneezing can be inhaled or deposited on mucous membranes (e.g. respiratory TB).",
          "Faecal–oral: pathogens leave the gut in faeces and enter a new host via contaminated water, food or hands (e.g. cholera).",
          "Vector-borne: an arthropod picks up a pathogen from an infected host and injects or deposits it into another host (e.g. *Plasmodium* by *Anopheles* mosquitoes).",
          "Blood / sexual: pathogens in blood, semen, vaginal secretions or across placenta (e.g. HIV).",
        ],
        workedSolution: [
          "Many respiratory pathogens spread when an infected person produces droplets or smaller aerosols carrying bacteria or viruses; a susceptible person nearby may inhale them or receive them on conjunctival or nasal surfaces, which is the basis of droplet and airborne transmission exemplified by tuberculosis when infectious lung lesions release organisms into the airways.",
          "Faecal–oral transmission occurs when organisms shed in faeces reach the mouth of a new host, classically through drinking water contaminated with untreated sewage, eating food handled with unwashed hands, or flies moving from faeces to food, which is central to the epidemiology of cholera and several other enteric diseases.",
          "Vector-borne transmission requires a living arthropod intermediate: the mosquito ingests blood containing a parasite or virus, the agent multiplies or develops in the vector, and the next bite transfers infectious forms into a new human host, as with *Plasmodium* transmitted by *Anopheles* species.",
          "Blood-borne and sexual routes involve transfer of infected body fluids—shared needles, transfusion of unscreened blood, sexual intercourse without barrier protection, or from mother to child across the placenta or at birth—which are the principal routes emphasised for blood-borne viruses such as HIV.",
          "Recognising the route is essential for control: sanitation and safe water target faecal–oral spread, bed nets and vector control target malaria, respiratory hygiene and treatment reduce airborne TB spread, and education plus safe clinical practice reduce blood-borne transmission.",
        ],
        commonMistake:
          "Labelling every mosquito bite as ‘faecal–oral’, or claiming cholera is mainly airborne without mentioning water or food contamination.",
        tags: ["transmission", "routes"],
      },
      {
        id: "t10-1-d3",
        noteId: "t10-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe cholera as an example of a bacterial infectious disease, naming the pathogen and outlining how it is typically transmitted to humans and why explosive outbreaks may follow breakdown of safe water supplies.",
        modelAnswerPoints: [
          "Pathogen: *Vibrio cholerae* (a bacterium).",
          "Transmission: mainly faecal–oral—ingestion of water or food contaminated with faeces from infected individuals.",
          "Large outbreaks occur when sewage contaminates drinking water because many people ingest the organism at once.",
        ],
        workedSolution: [
          "Cholera is a severe acute diarrhoeal disease caused by the curved Gram-negative bacterium *Vibrio cholerae*, which infects the small intestine and produces a toxin that causes massive secretion of water and electrolytes into the gut lumen.",
          "The bacterium leaves the body in very high numbers in the watery stools of acute cases; if sanitation is poor, these organisms enter rivers, wells or municipal supplies that are drunk without adequate treatment.",
          "A new host becomes infected by swallowing viable bacteria, most often in contaminated drinking water or on food washed in contaminated water, which is why the route is classified as faecal–oral rather than respiratory.",
          "When a whole community shares one polluted source, many people ingest the pathogen over a short time, producing the pattern of a sharp epidemic curve; restoring chlorination, boiling, or protected supplies breaks the chain.",
        ],
        commonMistake:
          "Naming the wrong organism, or describing cholera as primarily mosquito-borne like malaria.",
        tags: ["cholera", "Vibrio", "water"],
      },
      {
        id: "t10-1-d4",
        noteId: "t10-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Outline tuberculosis (TB) as an example of a bacterial infectious disease, naming the pathogen and describing the principal route by which it spreads between people in crowded conditions.",
        modelAnswerPoints: [
          "Pathogen: *Mycobacterium tuberculosis*.",
          "Spread: airborne / droplet route from the respiratory tract of an infectious person.",
          "Crowding and poor ventilation increase exposure dose and infection risk.",
        ],
        workedSolution: [
          "Tuberculosis is a chronic infectious disease caused mainly by the slow-growing bacterium *Mycobacterium tuberculosis*, which typically establishes infection in the lungs after inhalation.",
          "Infectious pulmonary TB produces lesions from which bacteria reach the branching airways; coughing, speaking or singing generates droplets and droplet nuclei carrying bacilli that can be inhaled deep into the lungs of close contacts.",
          "Transmission is therefore person-to-person through the respiratory route rather than through ingestion like cholera, which is why household and institutional contacts are at highest risk.",
          "Overcrowded housing, prisons, or poorly ventilated workplaces increase the concentration of infectious droplets and the time people spend sharing air, which accelerates spread in disadvantaged communities even though the same organism is involved.",
        ],
        commonMistake:
          "Stating TB spreads by drinking unpasteurised milk only (that is a different historical route for *M. bovis* in some settings, not the main human TB story at this level) or confusing TB with a blood-borne-only infection.",
        tags: ["tuberculosis", "Mycobacterium", "airborne"],
      },
      {
        id: "t10-1-d5",
        noteId: "t10-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Explain malaria as an infectious disease caused by *Plasmodium*, with reference to the role of the *Anopheles* mosquito in transmission and a brief outline of the parasite’s presence in human blood.",
        modelAnswerPoints: [
          "Malaria is caused by *Plasmodium* species (protoctistan parasites), not by bacteria or viruses.",
          "Female *Anopheles* mosquitoes transmit the disease: infectious forms enter the human when the mosquito feeds on blood.",
          "Parasites multiply in liver and red blood cells; blood stages cause periodic fever and anaemia when RBCs rupture.",
        ],
        workedSolution: [
          "Malaria is a protoctistan disease in which sporozoites of *Plasmodium* are injected into human skin when an infected female *Anopheles* mosquito takes a blood meal, so the flying insect is the biological vector, not merely a mechanical carrier on its legs.",
          "After entry, the parasite undergoes exoerythrocytic development in liver cells before stages emerge that invade red blood cells and multiply asexually, producing repeated cycles of RBC rupture that coincide with the classic fever pattern.",
          "Because mature sexual stages (gametocytes) may appear in peripheral blood, another feeding mosquito can ingest them, allowing fertilisation and sporogony in the insect, which completes the life cycle between human and vector.",
          "Diagnostic and public-health answers therefore tie malaria firmly to blood parasites visible in stained blood films in teaching contexts and to vector control (nets, insecticides, reducing breeding sites) rather than only to clean water, which targets different diseases.",
        ],
        commonMistake:
          "Calling *Plasmodium* a bacterium or attributing malaria to poor sanitation alone without the mosquito vector.",
        tags: ["malaria", "Plasmodium", "vector"],
      },
      {
        id: "t10-1-d6",
        noteId: "t10-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Outline human immunodeficiency virus (HIV) infection at the level expected for disease-of-human-importance teaching: identify the type of pathogen, list the main routes by which it is transmitted, and state the long-term consequence for the immune system if untreated.",
        modelAnswerPoints: [
          "HIV is a virus (retrovirus) that infects humans.",
          "Transmission: unprotected sexual intercourse; contaminated blood or blood products; shared injecting equipment; mother-to-child (placental, perinatal, breastfeeding).",
          "The virus targets CD4 helper T lymphocytes; progressive loss leads to severe immunodeficiency (AIDS), increasing susceptibility to opportunistic infections.",
        ],
        workedSolution: [
          "HIV (human immunodeficiency virus) is an RNA virus classified among the retroviruses; it carries reverse transcriptase and integrates a DNA copy into host chromosomes, which is why it establishes lifelong infection in CD4-bearing helper T cells and macrophages.",
          "The routes emphasised in public-health teaching are sexual transmission through exchange of genital secretions, parenteral exposure through transfusions of infected blood or plasma products (now rare where screening exists), sharing needles among injecting drug users, and vertical transmission from an infected mother to her child before or during birth or through breast milk.",
          "As increasing numbers of CD4+ T cells are destroyed or functionally impaired, cell-mediated immunity weakens over years, and the symptomatic stage called AIDS is defined by very low CD4 counts and/or specific opportunistic illnesses that rarely harm people with intact immunity.",
          "This immune collapse explains why untreated HIV is not only a single disease but a gateway to pneumonia, TB, and other infections that become lethal without antiretroviral therapy.",
        ],
        commonMistake:
          "Claiming casual social contact or insect bites transmit HIV, or confusing HIV with a bacterium treatable by ordinary antibiotics.",
        tags: ["HIV", "AIDS", "transmission"],
      },
      {
        id: "t10-1-d7",
        noteId: "t10-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Discuss how social and economic factors can influence the incidence, spread, and impact of infectious diseases in human populations, referring to at least two distinct factors (for example poverty, education, housing, healthcare access, or conflict).",
        modelAnswerPoints: [
          "Poverty correlates with poor nutrition, overcrowding, limited sanitation, and delayed treatment, increasing exposure and severity.",
          "Low education or stigma can reduce uptake of prevention (condoms, vaccination, bed nets) or early testing.",
          "Weak health systems (few clinics, drug stock-outs) limit diagnosis, contact tracing, and continuity of care.",
          "Conflict displaces populations, disrupts water treatment and vaccination, and concentrates people in camps where respiratory and diarrhoeal disease spread.",
        ],
        workedSolution: [
          "Social and economic conditions do not replace biological routes of transmission, but they determine how often people meet the pathogen and how well they survive once infected.",
          "Household poverty is linked to crowded housing without cross-ventilation, which promotes airborne TB; it is also linked to reliance on unsafe water and open defecation, which amplifies cholera when sanitation investment is insufficient.",
          "Even when interventions exist, their benefit depends on access: antiretroviral programmes, TB directly observed therapy, and malaria diagnostics only work if clinics are reachable, drugs are in stock, and patients can afford transport or time away from informal labour.",
          "Education and gender equity shape whether people know how to recognise symptoms, accept HIV testing without extreme stigma, or sleep under insecticide-treated nets consistently, so behavioural and cultural dimensions interact with economics.",
          "Armed conflict illustrates compound risk: destruction of infrastructure halts chlorination and vaccination, while displacement creates dense settlements where measles or cholera explode; thus the same pathogen can produce very different epidemic curves in stable versus fragile states.",
        ],
        commonMistake:
          "Arguing that infectious disease is ‘caused by poverty’ without tying discussion to transmission, treatment access, or malnutrition as mediating mechanisms.",
        tags: ["social", "economic", "discussion"],
      },
      {
        id: "t10-1-d8",
        noteId: "t10-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which pairing correctly matches the named human disease with its pathogen?",
        options: [
          { id: "A", text: "Malaria — *Vibrio cholerae*" },
          { id: "B", text: "Cholera — *Plasmodium falciparum*" },
          { id: "C", text: "Tuberculosis — *Mycobacterium tuberculosis*" },
          { id: "D", text: "HIV/AIDS — *Mycobacterium tuberculosis*" },
        ],
        correctOptionId: "C",
        explanation:
          "Tuberculosis is caused by the bacterium *Mycobacterium tuberculosis*. Malaria is *Plasmodium*; cholera is *Vibrio cholerae*; HIV is a virus, not a mycobacterium.",
        distractorRationale: {
          A: "Malaria is protoctistan (*Plasmodium*), not *Vibrio*.",
          B: "Cholera is bacterial (*Vibrio*), not *Plasmodium*.",
          D: "TB bacteria may cause opportunistic disease in AIDS, but HIV itself is a retrovirus.",
        },
        tags: ["pathogens", "identification"],
      },
      {
        id: "t10-1-d9",
        noteId: "t10-1",
        kind: "mcq",
        difficulty: 3,
        stem: "A refugee camp relies on a single unchlorinated well. Several hundred people develop profuse watery diarrhoea within days. Which transmission route is most consistent with a cholera outbreak in this setting?",
        options: [
          { id: "A", text: "Sexual transmission only" },
          { id: "B", text: "Faecal–oral via contaminated drinking water" },
          { id: "C", text: "Vector-borne via *Anopheles* bites" },
          { id: "D", text: "Airborne spread only" },
        ],
        correctOptionId: "B",
        explanation:
          "Cholera is classically water-borne: *Vibrio cholerae* in faeces contaminates supplies; many people drinking the same source produce a sharp outbreak.",
        distractorRationale: {
          A: "Not the principal route for cholera.",
          C: "That pattern fits malaria (*Plasmodium*), not cholera.",
          D: "Airborne spread fits respiratory agents such as TB, not classical cholera epidemiology.",
        },
        tags: ["cholera", "application"],
      },
      {
        id: "t10-1-d10",
        noteId: "t10-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Compare the control of cholera with the control of malaria in human populations, identifying one main target of intervention for each disease that matches its usual route of transmission (do not simply list drugs).",
        modelAnswerPoints: [
          "Cholera: interrupt faecal–oral spread—safe water, sanitation, hygiene, food protection, rapid case management and rehydration.",
          "Malaria: reduce human–vector contact and vector abundance—bed nets, indoor spraying, environmental management of breeding sites, plus prompt diagnosis/treatment.",
          "Both may use health education, but the primary engineering / vector measures differ because routes differ.",
        ],
        workedSolution: [
          "Because cholera bacteria pass from gut to gut through water and food, the highest-impact public measures are microbiologically safe drinking water (treatment, protected sources, point-of-use disinfection), effective sewage disposal, handwashing, and food hygiene, together with oral rehydration or intravenous fluids to prevent death while transmission is brought under control.",
          "Because malaria parasites must pass through *Anopheles* mosquitoes, control emphasises preventing bites (insecticide-treated nets, repellents, house screening where affordable) and reducing mosquito breeding by draining stagnant water or managing irrigation, supplemented by testing febrile patients and treating confirmed cases to cut the human infectious reservoir for gametocytes.",
          "Drug therapy appears in both programmes, but the question asks for transmission-aligned measures: clean water does not stop malaria mosquitoes, and bed nets do not sterilise cholera-contaminated wells, so strategies must mirror the biology of each route.",
          "International coordination also differs in detail—cholera often triggers emergency water, sanitation, and hygiene (‘WASH’) clusters, whereas malaria programmes track parasite resistance patterns and seasonal chemoprevention in some high-burden settings—but the examination point is matching intervention to route.",
        ],
        commonMistake:
          "Suggesting only ‘give antibiotics’ for cholera without safe water, or claiming bed nets alone will stop a cholera epidemic.",
        tags: ["control", "comparison"],
      },
    ],
    flashcards: [
      {
        id: "t10-1-f1",
        noteId: "t10-1",
        difficulty: 1,
        front: "Define pathogen (exam register).",
        back: "A microorganism or virus that causes disease after infecting a host.",
        examPhrasing: "Define the term pathogen.",
        tags: ["definitions"],
      },
      {
        id: "t10-1-f2",
        noteId: "t10-1",
        difficulty: 1,
        front: "Cholera: pathogen name.",
        back: "*Vibrio cholerae* (bacterium).",
        examPhrasing: "Name the pathogen that causes cholera.",
        tags: ["cholera"],
      },
      {
        id: "t10-1-f3",
        noteId: "t10-1",
        difficulty: 2,
        front: "TB: pathogen + main spread.",
        back: "*Mycobacterium tuberculosis*; airborne / respiratory droplets from infectious lung disease.",
        examPhrasing: "Outline transmission of pulmonary tuberculosis.",
        tags: ["TB"],
      },
      {
        id: "t10-1-f4",
        noteId: "t10-1",
        difficulty: 2,
        front: "Malaria: pathogen genus + vector genus.",
        back: "*Plasmodium*; female *Anopheles* mosquito.",
        examPhrasing: "State the pathogen and vector for malaria.",
        confusionPair: "malaria vs dengue vector",
        tags: ["malaria"],
      },
      {
        id: "t10-1-f5",
        noteId: "t10-1",
        difficulty: 3,
        front: "Three HIV transmission routes (high-yield list).",
        back: "Sexual; blood / shared needles; mother-to-child (vertical).",
        examPhrasing: "Outline how HIV is transmitted.",
        tags: ["HIV"],
      },
      {
        id: "t10-1-f6",
        noteId: "t10-1",
        difficulty: 3,
        front: "Faecal–oral: one-line meaning.",
        back: "Pathogens in faeces reach the mouth via water, food, hands, or fomites.",
        examPhrasing: "Explain faecal–oral transmission.",
        tags: ["transmission"],
      },
      {
        id: "t10-1-f7",
        noteId: "t10-1",
        difficulty: 4,
        front: "Why does overcrowding favour TB spread?",
        back: "More shared airspace and time near infectious droplets; higher dose exposure.",
        examPhrasing: "Relate social conditions to TB incidence.",
        tags: ["social", "TB"],
      },
      {
        id: "t10-1-f8",
        noteId: "t10-1",
        difficulty: 4,
        front: "*Plasmodium* in humans — where do asexual blood stages multiply?",
        back: "Inside red blood cells (after hepatic stages); RBC rupture releases parasites and causes fever peaks.",
        examPhrasing: "Outline the blood stage of *Plasmodium*.",
        tags: ["malaria"],
      },
      {
        id: "t10-1-f9",
        noteId: "t10-1",
        difficulty: 5,
        front: "AIDS vs HIV — distinction.",
        back: "HIV is the virus; AIDS is the advanced immunodeficiency syndrome (very low CD4 / defining illnesses).",
        examPhrasing: "Distinguish HIV infection and AIDS.",
        tags: ["HIV"],
      },
      {
        id: "t10-1-f10",
        noteId: "t10-1",
        difficulty: 5,
        front: "One economic barrier to controlling infectious disease.",
        back: "Cost of transport to clinic, user fees, or lost wages — delays diagnosis and breaks treatment courses.",
        examPhrasing: "Discuss economic factors affecting disease control.",
        tags: ["economic"],
      },
    ],
  },
  "t10-2": {
    noteId: "t10-2",
    drills: [
      {
        id: "t10-2-d1",
        noteId: "t10-2",
        kind: "structured",
        difficulty: 1,
        marks: 6,
        stem: "Outline how penicillin acts on susceptible bacteria, with reference to the bacterial cell wall and why weakening that wall can lead to cell death.",
        modelAnswerPoints: [
          "Penicillin and related beta-lactams interfere with synthesis of peptidoglycan in the bacterial cell wall.",
          "Without a properly cross-linked wall, the bacterium cannot resist internal turgor.",
          "Water enters by osmosis and the cell may burst (osmotic lysis) or leak, so the population stops multiplying.",
        ],
        workedSolution: [
          "Penicillin belongs to the beta-lactam family of antibiotics that target enzymes involved in assembling and cross-linking peptidoglycan, the rigid mesh that surrounds most bacterial cytoplasmic membranes and mechanically withstands high internal osmotic pressure.",
          "When these transpeptidation steps are blocked, newly made wall material is incomplete, so the wall becomes mechanically weak even though some old peptidoglycan may remain for a short time.",
          "Because bacterial cytoplasm is hypertonic relative to many external fluids, water tends to enter down its water potential gradient; a weakened wall cannot resist swelling, and the cell may undergo osmotic lysis or lose viability as the membrane tears away from a defective sacculus.",
          "The net effect at population level is a fall in viable colony counts, which is why penicillin is bactericidal for actively dividing Gram-positive organisms with thick peptidoglycan layers that are especially dependent on continuous wall remodelling.",
        ],
        commonMistake:
          "Saying penicillin ‘dissolves’ the membrane directly or kills human cells the same way; the primary syllabus mechanism is peptidoglycan synthesis inhibition leading to wall failure.",
        tags: ["penicillin", "cell-wall"],
      },
      {
        id: "t10-2-d2",
        noteId: "t10-2",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Explain why antibiotics such as penicillin that target bacterial cell-wall synthesis do not cure viral infections such as influenza or the common cold.",
        modelAnswerPoints: [
          "Viruses are acellular and lack peptidoglycan cell walls.",
          "They replicate only inside host cells using host ribosomes and metabolic machinery.",
          "Penicillin’s target enzymes are bacterial; viruses do not carry out bacterial wall synthesis, so the drug has no specific lethal process to interrupt.",
        ],
        workedSolution: [
          "Viruses consist of a nucleic acid genome packaged with protein (and sometimes envelope) but they are not whole cells; there is no surrounding peptidoglycan layer for penicillin-class drugs to destabilise.",
          "During infection a virus delivers its genome into a host cell and hijacks the host’s transcription, translation, and energy supply to manufacture new virions, whereas bacteria are independent cells with their own peptidoglycan assembly pathway outside human membranes.",
          "Because penicillin binds bacterial transpeptidases that are absent from viruses, the antibiotic cannot block a comparable step in the viral life cycle and does not prevent viral attachment, entry, or genome replication.",
          "Using penicillin against a viral upper respiratory infection therefore exposes the patient to side effects and selection pressure on commensal bacteria without shortening the viral illness, which is a standard reason antibiotics are reserved for confirmed or strongly suspected bacterial complications.",
        ],
        commonMistake:
          "Claiming viruses have ‘thin walls’ that penicillin fails to cross, or that antibiotics kill viruses slowly—viruses lack the drug’s bacterial target altogether.",
        tags: ["viruses", "antibiotics"],
      },
      {
        id: "t10-2-d3",
        noteId: "t10-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Outline how penicillin affects bacteria and, in the same answer, explain why such antibiotics are ineffective against viruses, using contrasting features of bacteria and viruses.",
        modelAnswerPoints: [
          "Penicillin blocks peptidoglycan cross-linking; bacteria lyse or fail to divide when the wall is compromised.",
          "Viruses lack metabolism, cell walls, and the specific enzymes penicillin inhibits.",
          "Viruses need host cells; antibiotics aimed at bacterial walls do not disrupt intracellular viral replication specifically.",
        ],
        workedSolution: [
          "In susceptible bacteria, penicillin interferes with peptidoglycan synthesis so the protective wall cannot be maintained against turgor, leading to bactericidal loss of viability especially in dividing cells.",
          "Viruses are not bounded by peptidoglycan and do not perform bacterial-type cell-wall biogenesis, so there is no equivalent biochemical target for the drug on the virion itself.",
          "Moreover viruses are obligate intracellular parasites: their replication programme runs on host ribosomes and polymerases, whereas penicillin’s classical mechanism is directed at extracytoplasmic bacterial enzymes that viruses simply do not encode.",
          "Therefore a combined outline for examiners contrasts a peptidoglycan-dependent bacterial cell with an acellular virus replicating inside human cytoplasm, making wall-targeting antibiotics irrelevant to the viral pathogen.",
        ],
        commonMistake:
          "Treating the question as two disconnected essays without explicitly contrasting wall synthesis in bacteria with the absence of walls and metabolism in viruses.",
        tags: ["penicillin", "viruses", "syllabus-10.2"],
      },
      {
        id: "t10-2-d4",
        noteId: "t10-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain, using the idea of natural selection, how careless use of antibiotics in human medicine can increase the proportion of resistant bacteria in a population over time.",
        modelAnswerPoints: [
          "Random mutation or gene transfer may confer resistance (e.g. enzyme that destroys penicillin, altered target).",
          "Antibiotic use imposes a strong selective pressure: susceptible bacteria die, resistant survivors reproduce.",
          "Repeated or suboptimal therapy increases advantage for resistant strains; resistance spreads vertically and by horizontal gene transfer.",
        ],
        workedSolution: [
          "Within any large bacterial population, rare variants may already carry plasmid-borne resistance genes or chromosomal mutations that reduce drug binding or pump the antibiotic out of the cell.",
          "When a broad antibiotic course is applied, organisms without those traits are killed or growth-arrested, freeing nutrients and space while resistant clones continue to divide.",
          "If treatment stops too early or uses the wrong drug dose, partially suppressed populations can recover and enrich intermediate resistance levels, and mobile genetic elements can spread resistance between species in the gut or on skin.",
          "Over years this evolutionary filtering is why hospital-associated infections may show multi-drug resistance patterns even though the underlying biochemistry of penicillin has not changed: the ecological conditions favour resistant genotypes.",
        ],
        commonMistake:
          "Saying the antibiotic ‘causes’ mutations directly in a Lamarckian way, instead of selecting pre-existing or newly arisen variants.",
        tags: ["resistance", "selection"],
      },
      {
        id: "t10-2-d5",
        noteId: "t10-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Discuss major consequences of widespread antibiotic resistance for individuals and for healthcare systems.",
        modelAnswerPoints: [
          "Harder-to-treat infections, longer illness, higher mortality.",
          "Need for more toxic or expensive reserve drugs; longer hospital stays.",
          "Increased post-operative and chemotherapy risk when prophylaxis fails.",
          "Greater infection-control costs, isolation, and surveillance burdens.",
        ],
        workedSolution: [
          "For an individual patient, a resistant strain may fail first-line therapy, prolonging fever, tissue damage, and time off work or school while clinicians switch to broader agents that may be more nephrotoxic or poorly tolerated.",
          "In severe sepsis, delay effective empiric coverage is associated with worse outcomes, so resistance translates directly into preventable deaths, not merely inconvenience.",
          "For hospitals, outbreaks of methicillin-resistant *Staphylococcus aureus* or vancomycin-resistant enterococci require contact precautions, dedicated staffing, and environmental cleaning that consume budgets and bed capacity.",
          "Surgical programmes and cancer chemotherapy depend on reliable prophylaxis; when resistance erodes that margin, elective operations may be postponed and neutropenic patients face higher infection rates, which is a system-level consequence beyond any single prescription decision.",
        ],
        commonMistake:
          "Listing consequences only as ‘people get sicker’ without healthcare-system or surgical context.",
        tags: ["resistance", "consequences"],
      },
      {
        id: "t10-2-d6",
        noteId: "t10-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Discuss steps that can be taken to reduce the impact of antibiotic resistance on public health, covering both prudent prescribing and wider infection-control measures.",
        modelAnswerPoints: [
          "Only use antibiotics when bacterial infection is likely or proven; avoid viral colds.",
          "Complete prescribed courses where clinically appropriate; do not share or hoard tablets.",
          "Hospital hygiene: hand washing, isolation, environmental cleaning, antimicrobial stewardship teams.",
          "Surveillance and rapid diagnostics to match drug to pathogen; research into new agents and vaccines.",
          "Agricultural regulation to limit unnecessary antibiotic use in livestock where relevant to resistance reservoirs.",
        ],
        workedSolution: [
          "Clinicians reduce selection pressure by reserving narrow-spectrum drugs for confirmed infections, using local antibiograms to guide empiric choices, and explaining to patients why viral pharyngitis does not need penicillin.",
          "Patients support stewardship by finishing courses that were prescribed to eradicate susceptible subpopulations (when that is the agreed plan), never using leftover pills for self-diagnosed future episodes, and returning for review if symptoms worsen rather than doubling doses informally.",
          "In institutions, universal hand hygiene, cohorting resistant cases, and cleaning high-touch surfaces interrupt cross-transmission so resistant clones do not amplify numerically even when they appear sporadically.",
          "Public-health laboratories track resistance percentages over time, while investment in vaccines (pneumococcal, *Haemophilus*) prevents bacterial disease outright, indirectly cutting antibiotic consumption.",
          "Because resistance genes also circulate among animal-associated bacteria, policies that restrict growth-promoter antibiotic use in agriculture lower the influx of resistance determinants into human food chains, complementing clinical measures.",
        ],
        commonMistake:
          "Suggesting ‘stronger antibiotics for everyone’ as the main solution, which worsens selective pressure without diagnostics.",
        tags: ["stewardship", "mitigation"],
      },
      {
        id: "t10-2-d7",
        noteId: "t10-2",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Discuss the consequences of antibiotic resistance and evaluate practical steps that could reduce its impact, linking your argument to how resistance arises in bacterial populations.",
        modelAnswerPoints: [
          "Resistance arises by selection of heritable traits under antibiotic pressure (mutation / gene transfer).",
          "Consequences: treatment failure, longer hospitalisation, higher costs, poorer surgery/chemotherapy safety nets.",
          "Mitigation: stewardship, hygiene, surveillance, vaccines, agricultural controls, R&D — each reduces selection or spread.",
        ],
        workedSolution: [
          "Antibiotic resistance is fundamentally an evolutionary problem: genetic variants that survive therapy reproduce and may spread resistance plasmids to other species, so the clinical challenge grows even when no new mutations occur in a given patient.",
          "The societal consequences include rising mortality from once-treatable pneumonias and wound infections, increased disability from chronic osteomyelitis, and diversion of nursing time to isolation nursing rather than routine care.",
          "Mitigation must therefore attack both selection and transmission: narrow indications and correct dosing lower the fitness advantage of resistance, while infection prevention stops resistant clones from becoming epidemic strains on wards.",
          "Vaccination and improved sanitation shrink the total bacterial load needing antibiotics, and agricultural controls shrink environmental reservoirs, so the discussion is strongest when individual prescribing choices are connected to population-level gene pools.",
          "No single measure is sufficient, but combining diagnostics, stewardship, engineering (clean water in the community), and research pipelines is the syllabus-style ‘discuss’ answer examiners expect.",
        ],
        commonMistake:
          "Writing only about ‘superbugs’ without explaining selection, or listing interventions with no link to resistance mechanisms.",
        tags: ["discussion", "resistance"],
      },
      {
        id: "t10-2-d8",
        noteId: "t10-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best describes the primary mode of action of penicillin on typical susceptible bacteria?",
        options: [
          { id: "A", text: "It inhibits DNA replication in the bacterial nucleoid." },
          { id: "B", text: "It disrupts synthesis of peptidoglycan in the cell wall." },
          { id: "C", text: "It blocks protein synthesis on eukaryotic 80S ribosomes." },
          { id: "D", text: "It dissolves the viral capsid." },
        ],
        correctOptionId: "B",
        explanation:
          "Classic penicillin action is inhibition of peptidoglycan cross-linking, weakening the bacterial cell wall.",
        distractorRationale: {
          A: "Some antibiotics target DNA; penicillin’s hallmark target is cell-wall synthesis.",
          C: "80S ribosomes are eukaryotic; penicillin is not an 80S inhibitor.",
          D: "Viruses are not the target; capsids are not peptidoglycan.",
        },
        tags: ["penicillin", "mcq"],
      },
      {
        id: "t10-2-d9",
        noteId: "t10-2",
        kind: "mcq",
        difficulty: 3,
        stem: "A patient demands penicillin for a mild runny nose and sore throat diagnosed as viral. Why is prescribing inappropriate?",
        options: [
          { id: "A", text: "Penicillin is metabolised too quickly in the nose." },
          { id: "B", text: "Viruses lack bacterial cell walls and relevant penicillin targets; therapy selects resistant bacteria without treating the virus." },
          { id: "C", text: "Penicillin only works if combined with antiviral protease inhibitors." },
          { id: "D", text: "Penicillin cannot cross the nasal mucosa." },
        ],
        correctOptionId: "B",
        explanation:
          "Antibiotics do not cure uncomplicated viral URTI; unnecessary use risks side effects and drives resistance in commensal bacteria.",
        distractorRationale: {
          A: "Pharmacokinetics is not the core syllabus reason.",
          C: "Penicillin is not an antiviral combination therapy for colds.",
          D: "Absorption is not the main biological objection.",
        },
        tags: ["stewardship", "viruses"],
      },
      {
        id: "t10-2-d10",
        noteId: "t10-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Outline one biochemical mechanism by which a bacterium may become resistant to penicillin and state how that mechanism reduces the drug’s effectiveness.",
        modelAnswerPoints: [
          "Beta-lactamase enzyme hydrolyses the beta-lactam ring so penicillin cannot bind its target.",
          "Or: altered penicillin-binding protein with lower affinity; or efflux / reduced uptake (acceptable if clearly explained).",
          "Result: peptidoglycan synthesis continues despite drug presence.",
        ],
        workedSolution: [
          "Many Gram-negative and some Gram-positive bacteria acquire plasmid genes encoding beta-lactamase periplasmic or extracellular enzymes that cleave the four-membered beta-lactam ring of penicillin before the molecule reaches lethal concentrations at its transpeptidase targets.",
          "Once the ring is opened, the antibiotic loses its acylating activity on PBPs, so cross-linking of peptidoglycan proceeds relatively normally and the organism survives exposure that would kill a non-enzyme-producing sibling.",
          "Alternative exam answers describe chromosomal mutations in penicillin-binding proteins after prolonged exposure in hospitals, lowering drug affinity, or porin loss reducing drug influx in some Gram-negatives; each explanation must tie the molecular change to restored wall synthesis.",
          "The unifying idea is that resistance is a heritable biochemical bypass, not a vague ‘toughness’, which is why combining beta-lactamase inhibitors with certain penicillins can restore activity in some infections.",
        ],
        commonMistake:
          "Saying the bacterium ‘gets used to’ penicillin without naming an enzyme, target change, or barrier mechanism.",
        tags: ["resistance", "mechanism"],
      },
    ],
    flashcards: [
      {
        id: "t10-2-f1",
        noteId: "t10-2",
        difficulty: 1,
        front: "Penicillin: main bacterial target (high level).",
        back: "Peptidoglycan cell-wall synthesis (transpeptidation / cross-linking).",
        examPhrasing: "Outline how penicillin acts on bacteria.",
        tags: ["penicillin"],
      },
      {
        id: "t10-2-f2",
        noteId: "t10-2",
        difficulty: 1,
        front: "Why don’t penicillin-type drugs kill typical viruses?",
        back: "Viruses have no peptidoglycan wall or bacterial wall enzymes; they replicate inside host cells.",
        examPhrasing: "Explain why antibiotics do not affect viruses.",
        tags: ["viruses"],
      },
      {
        id: "t10-2-f3",
        noteId: "t10-2",
        difficulty: 2,
        front: "Peptidoglycan weakness → why cells die.",
        back: "Turgor / osmotic lysis or lethal leakage when the wall cannot withstand internal pressure.",
        examPhrasing: "Explain bacterial death after penicillin exposure.",
        tags: ["cell-wall"],
      },
      {
        id: "t10-2-f4",
        noteId: "t10-2",
        difficulty: 2,
        front: "Beta-lactamase — one line.",
        back: "Enzyme that breaks beta-lactam antibiotics, conferring resistance to many penicillins.",
        examPhrasing: "Give one resistance mechanism to penicillin.",
        tags: ["resistance"],
      },
      {
        id: "t10-2-f5",
        noteId: "t10-2",
        difficulty: 3,
        front: "Antibiotic stewardship — meaning.",
        back: "Coordinated programmes to optimise antibiotic use: right drug, dose, duration, indication.",
        examPhrasing: "What is meant by antibiotic stewardship?",
        tags: ["stewardship"],
      },
      {
        id: "t10-2-f6",
        noteId: "t10-2",
        difficulty: 3,
        front: "One hospital measure that limits resistant strain spread.",
        back: "Rigorous hand hygiene / contact isolation for infected patients / environmental cleaning.",
        examPhrasing: "State an infection-control measure relevant to resistance.",
        tags: ["IPC"],
      },
      {
        id: "t10-2-f7",
        noteId: "t10-2",
        difficulty: 4,
        front: "Selection pressure — exam phrase.",
        back: "Antibiotic kills susceptible cells; resistant survivors reproduce → higher resistance frequency.",
        examPhrasing: "Explain selection for antibiotic resistance.",
        tags: ["selection"],
      },
      {
        id: "t10-2-f8",
        noteId: "t10-2",
        difficulty: 4,
        front: "Why viral colds should not get penicillin (exam trap).",
        back: "No bacterial target; risks side effects and enriches resistant commensals.",
        examPhrasing: "Why avoid antibiotics for viral URTI?",
        tags: ["stewardship"],
      },
      {
        id: "t10-2-f9",
        noteId: "t10-2",
        difficulty: 5,
        front: "Horizontal gene transfer — relevance to resistance.",
        back: "Resistance plasmids can move between bacteria, spreading resistance faster than mutation alone.",
        examPhrasing: "Outline how resistance spreads between bacteria.",
        tags: ["genetics"],
      },
      {
        id: "t10-2-f10",
        noteId: "t10-2",
        difficulty: 5,
        front: "Vaccines vs antibiotics in resistance fight.",
        back: "Preventing infection reduces antibiotic use and selective pressure (e.g. pneumococcal vaccine).",
        examPhrasing: "How can vaccination reduce antibiotic resistance?",
        tags: ["vaccination"],
      },
    ],
  },
};
