import type { SubtopicPracticePack } from "./types";

/**
 * Topic 15 (9700 Biology) practice — `data/courses/biology-9700.json` (`t15-1`, `t15-2`).
 *
 * **`t15-1` (15.1 Control and coordination in mammals)** — Crosswalk to
 * `data/syllabus/biology-9700-learning-outcomes.md` §15.1:
 * d1 endocrine + ADH / glucagon / insulin; d2 nervous vs endocrine; d3 sensory / motor / intermediate
 * neurones + receptor role; d4 taste-bud chemoreceptor → AP; d5 resting potential + maintenance;
 * d6 action potential + refractory + frequency; d7 saltatory conduction; d8 cholinergic synapse;
 * d9 MCQ (myelinated vs C fibre); d10 NMJ + T-tubule + SR + sarcomere ultrastructure + sliding filament.
 *
 * **`t15-2` (15.2 Control and coordination in plants)** — Crosswalk to §15.2:
 * d1–d2 Venus flytrap; d3–d4 auxin / proton pumping / wall acidification; d5–d7 gibberellin in barley
 * germination; d8–d10 consolidate (MCQs + application).
 */
export const BIOLOGY_TOPIC15_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t15-1": {
    noteId: "t15-1",
    drills: [
      {
        id: "t15-1-d1",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 1,
        marks: 6,
        stem: "Describe the main features of the mammalian endocrine system as a control system, and for each of the hormones antidiuretic hormone (ADH), glucagon and insulin state one major target and one principal effect (homeostatic role) you would give in an examination answer.",
        modelAnswerPoints: [
          "Endocrine: hormones secreted into blood by endocrine cells / glands; widespread distribution; relatively slow, prolonged, often co-ordinated with blood flow.",
          "ADH: e.g. kidney collecting ducts — increased water reabsorption / more concentrated urine (water balance).",
          "Glucagon: e.g. liver — glycogen breakdown / raised blood glucose in the fasting state.",
          "Insulin: e.g. liver, muscle, adipose — increased glucose uptake, glycogen synthesis, lower blood glucose after feeding.",
        ],
        workedSolution: [
          "The endocrine system uses chemical messengers, hormones, which after release from endocrine cells or glands diffuse into the blood (or in some local cases act very near the source) and are carried throughout the body, allowing many tissues to be exposed in parallel, though only cells with the appropriate receptors respond.",
          "Compared with a physical nerve cable to each organ, the circulatory system is the distribution network, and effects are generally slower in onset and longer lasting because hormone concentrations rise and fall over minutes to hours and new protein synthesis is often part of the response.",
          "Antidiuretic hormone, released from the posterior pituitary in response to angiotensin II and high plasma osmolarity signals, acts mainly on the collecting ducts and collecting tubule system of the nephron where it increases water permeability, so more water is reabsorated into the medullary interstitium and a smaller volume of more concentrated urine is produced, helping defend extracellular osmolarity and blood pressure.",
          "Glucagon, released from alpha cells of the pancreatic islets when blood glucose is low, acts chiefly on hepatocytes, stimulating glycogenolysis and gluconeogenesis and therefore raising the plasma glucose available for obligate glucose users between meals.",
          "Insulin, released from beta cells in response to raised blood glucose and some amino acids, increases the rate of GLUT4 insertion and other metabolic shifts in muscle and adipose tissue and promotes glycogen synthesis and storage in liver, overall lowering and buffering postprandial blood glucose.",
          "Together these examples illustrate a single endocrine design pattern—release tied to a blood-borne error signal, receptor-mediated responses in only certain targets, and integration with other systems (nervous, renal, digestive) in whole-animal homeostasis.",
        ],
        commonMistake:
          "Listing hormone effects without situating them in ‘blood-borne, widespread, relatively slow, target-cell receptor’ language that defines the endocrine system, or confuse glucagon and insulin (which is which).",
        tags: ["endocrine", "hormones"],
      },
      {
        id: "t15-1-d2",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Compare the main features of the nervous system and the endocrine system as means of co-ordination in mammals, referring to speed, duration, specificity and how signals are distributed.",
        modelAnswerPoints: [
          "Nervous: electrical impulses in neurones; often very fast; synaptic / highly directed pathways; short-lived unless activity sustained.",
          "Endocrine: blood-borne hormones; generally slower; longer-lasting effects; widespread broadcast though only target cells respond (receptors).",
          "Nervous: precise point-to-point and spatial mapping (e.g. single motor unit); endocrine: often broader systemic tuning.",
        ],
        workedSolution: [
          "Nervous co-ordination is built from neurones that generate and propagate all-or-nothing action potentials along membranes specialised for serial transmission, and pass information at synapses using neurotransmitters, so behaviour and reflex arcs can be updated within milliseconds to hundreds of milliseconds when pathways are already wired.",
          "Hormones are secreted in response to neural or endocrine input or direct sensing by endocrine cells, and move with cardiac output to the whole body, meeting target cells that carry specific receptors, so a single releasing episode can modulate the physiology of all receptive tissues in parallel, such as a rise in epinephrine from the adrenal medulla during stress.",
          "Speed and duration differ systematically: a withdrawal reflex and precise motor program can be completed before measurable hormone levels change much, yet insulin elevation after a meal alters whole-body fuel handling for an hour or more, and growth hormone, thyroid hormone or cortisol profiles shape metabolism over much longer time scales than a single action potential train.",
          "Localisation also differs: many neuronal circuits are highly topographic, so a particular spinal motor neurone can select one motor unit, whereas a hormone is delivered everywhere the blood takes it, achieving apparent specificity not by the route but by differential receptor expression, though neuromodulators and nitric oxide blur the boundary at the local circuit level in teaching answers.",
          "Integration between the two is visible when hypothalamic neurosecretory cells both release hormones and command pituitary output while parallel autonomic axons change heart and gut function within one coherent stress or feeding response, which is a fair synthesis line for a compare question.",
        ],
        commonMistake:
          "Claiming hormones are always slow and nerves always fast without conceding that some peptidergic pathways are relatively slow, or that the nervous system can use volume transmission in places.",
        tags: ["comparison", "nervous", "endocrine"],
      },
      {
        id: "t15-1-d3",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Describe the structure and function of a sensory neurone and a motor neurone, state how intermediate (relay) neurones connect them in many pathways, and outline the role of sensory receptor cells in converting stimuli to impulses in sensory neurones.",
        modelAnswerPoints: [
          "Sensory: cell body in dorsal root ganglion; one elongated dendritic process with sensory endings; afferent axon to CNS; transmits impulses to CNS.",
          "Motor: cell body in CNS; efferent axon to effector; transmits impulses to muscle / gland.",
          "Intermediate (association / relay) neurones: located in CNS, connect sensory to motor in reflex arcs and more complex routes.",
          "Receptors: specialised cells or nerve endings; detect stimulus, generate a receptor potential, leading to AP generation in sensory neurone (where threshold reached).",
        ],
        workedSolution: [
          "A typical somatic sensory neurone is a pseudounipolar cell whose cell body lies in a dorsal root ganglion, with a single long process that splits: peripheral branches end as bare nerve endings with specialised transducer proteins or sit alongside specialised cells (e.g. taste cells), while the central process enters the spinal cord to synapse, so its job is afferent transmission from periphery to CNS only.",
          "A somatic lower motor neurone has its cell body in the ventral horn of the grey matter (or in motor nuclei of cranial nerves), a multipolar morphology, and a myelinated efferent axon that extends to the neuromuscular junction on many skeletal muscle fibres, where its function is the final output command to the effector, so the direction and termination differ clearly from a sensory first-order neurone.",
          "In polysynaptic and higher pathways, one or more intermediate neurones, whose somata lie entirely in the CNS, receive synapses from sensory (or other) terminals and, after integration and modulation, make synaptic contact onto motor neurones or onto further chain neurones, allowing reciprocal inhibition, convergence and divergence, and the embedding of the reflex in voluntary planning.",
          "Receptor (transducer) elements convert physical or chemical energy into a change in the membrane of the cell or ending: adequate stimulus depolarises the receptor to a graded receptor potential; if this reaches a critical region, voltage-gated sodium channels in the first trigger zone open and initiate action potentials in the sensory axon, thus translating stimulus property (intensity, duration) into impulse frequency, which is the encoding step examiners expect in outline.",
        ],
        commonMistake:
          "Saying the sensory cell body is ‘in the cord’ (for spinal sensory neurone it is in the DRG) or describing motor and sensory neurones as identical in shape and job.",
        tags: ["neurones", "receptors"],
      },
      {
        id: "t15-1-d4",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe the sequence of events, from stimulus to action potential, in a sensory neurone in the human tongue, using a chemoreceptor cell in a taste bud as the example, at the level expected for outline answers.",
        modelAnswerPoints: [
          "Tastant binds / interacts with chemoreceptors on microvillar membrane of a taste receptor (receptor) cell.",
          "Depolarising receptor (generator) potential in the receptor / release of neurotransmitter if separate cell.",
          "If a separate receptor cell, neurotransmitter excites afferent ending of a sensory neurone; if the fibre itself, local current to trigger zone.",
          "If threshold is reached, voltage-gated channels generate action potential(s) in the sensory (afferent) neurone.",
        ],
        workedSolution: [
          "Within a taste bud, dissolved tastants in saliva contact the apical microvilli of a specialised chemoreceptor cell, where G-protein or ion channel mechanisms produce a depolarising receptor (generator) potential whose magnitude and duration are influenced by tastant identity and concentration.",
          "In the common 9700 picture, the receptor cell is not the same as the afferent axon: when sufficiently depolarised, the receptor cell depolarises its basolateral membrane and, via voltage-gated calcium entry, elicits the calcium-dependent exocytosis of a neurotransmitter (often a subject called ‘gustatory neurotransmission’) onto a synaptic contact on the branch of a cranial sensory nerve’s peripheral ending.",
          "The postsynaptic region of the sensory ending receives this chemical signal, generating excitatory post-synaptic local currents; if the integrated depolarisation reaching the first point with a high density of voltage-gated sodium channels exceeds threshold, a regenerative depolarisation begins—an action potential in the afferent fibre.",
          "Because receptor potentials are graded, a stronger suprathreshold taste stimulus that produces more depolarising current can drive the fibre at higher frequency, and repeated firing in the afferent bundle encodes the sensory message carried centrally for perception, completing the example chain from tastant to impulse.",
        ],
        commonMistake:
          "Omitting the role of a distinct receptor cell and transmitter, if that is the pathway described in your teaching, or saying every sensory ending fires without threshold.",
        tags: ["taste", "action-potential"],
      },
      {
        id: "t15-1-d5",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Describe and explain how the resting potential of a mammalian neurone is generated and maintained, and outline the respective contributions of the sodium–potassium pump and the resting permeability to potassium ions.",
        modelAnswerPoints: [
          "Resting potential is negative inside relative to outside (e.g. about −70 mV), maintained when net ion movement is in steady state, not when all movement stops.",
          "High relative permeability to K+ at rest (leak K+ channels) so inside becomes negative as K+ tends to move out down its concentration gradient.",
          "Sodium is far more concentrated outside, but low resting permeability to Na+ limits inward leak.",
          "Na+/K+ ATPase (pump) moves 3 Na+ out and 2 K+ in per cycle, being electrogenic, helping maintain the ionic gradients and offsetting any slow diffusive dissipation.",
        ],
        workedSolution: [
          "In the resting, non-refractory state, the plasma membrane of the axon and soma is selectively permeable, particularly through always-open (leak) channels that favour K+ efflux, while many voltage-gated sodium channels are closed, making sodium conductance at rest very small by comparison in standard quantitative descriptions of the unmyelinated or resting inter-node segment.",
          "Because the cytosol contains much lower K+ than would be in equilibrium with the extracellular fluid if the membrane were only permeable to passive leaks of other things, the outward movement of a small number of K+ cations, limited by the electrical attraction of the anions left inside, sets up a real stable potential difference, negative inside, whose numeric value in teaching is around −60 to −80 mV depending on the preparation.",
          "A parallel story holds for sodium: there is a large electrochemical driving force for entry, but the resting membrane is relatively impermeable to Na+, so the resting potential is dominated in practice by the potassium battery rather than the sodium battery, which is a standard phrase you may use in exams once explained.",
          "The Na+/K+-ATPase, consuming ATP, actively transports three sodium ions out and two potassium ions in per cycle, continuously rebuilding the transmembrane Na+ and K+ concentration gradients that passive fluxes and synaptic events would otherwise erode, and the slight excess positive charge removed per cycle also contributes a few millivolts to the inside-negative resting potential, which is the electrogenic component examiners like named explicitly.",
        ],
        commonMistake:
          "Saying the pump ‘rests’ the cell without naming K+ leak dominance, or inventing a wrong sign for the resting potential.",
        tags: ["resting-potential", "pump"],
      },
      {
        id: "t15-1-d6",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 3,
        marks: 8,
        stem: "Describe and explain, for a non-myelinated region of a mammalian axon, the change in membrane potential during a single action potential, how the resting potential is restored in the relative refractory period, and the importance of the absolute refractory period in limiting the maximum frequency of firing.",
        modelAnswerPoints: [
          "Resting: near resting potential, Na+ activation gates closed, inactivation gates open, K+ channels mostly closed to fast activation (varies with prep).",
          "Depolarisation to threshold: voltage-gated Na+ channels open, rapid Na+ influx, positive feedback / regenerative local circuit.",
          "Repolarisation: Na+ channels inactivate; voltage-gated K+ channels open, K+ efflux, returning potential toward E_K.",
          "Hyperpolarising after-potential (optional note): extra K+ conductance; Na+ channels must recover from inactivation; Na/K pump re-establish long-term balance.",
          "Absolute refractory: enough Na+ channels inactivated to prevent re-firing; limits minimum interval between full APs, hence max frequency.",
        ],
        workedSolution: [
          "When local depolarisation from an advancing wave or synaptic current reaches a threshold, voltage-gated sodium channels in the active membrane patch begin a concerted conformational sequence: activation gates swing open, sodium conductance rises orders of magnitude, and the membrane potential is driven quickly toward the sodium equilibrium or at least far positive to zero, which is the rising phase and peak of the action potential in textbook curves.",
          "Within about a millisecond, many sodium channels also enter a distinct inactivated state in which the channel is non-conducting even though the still-depolarised membrane would favour opening, and at the same time voltage-gated potassium channels, slower to open, begin to raise potassium permeability so potassium leaves down its electrochemical gradient, returning the transmembrane potential net negative again—this is the repolarising phase together with the decline of unblocked sodium current.",
          "A brief undershoot in some fibres can occur if potassium conductance remains high longer than required to return exactly to the resting value, and during this and the tail of the sodium recovery period the membrane is relatively refractory because some sodium channels are still inactivated, so a larger-than-normal stimulus is needed, whereas during the short absolute period immediately after the spike essentially no new full spike can be launched from that locus, defining a minimum refractory time window.",
          "The absolute refractory period sets the upper limit to how closely spaced identical propagating spikes can be at a single point on the axon, because a second stimulus arriving too soon cannot recruit enough fresh sodium channel opening, so the maximum firing rate is the reciprocal of the minimum effective period up to the biophysical limit of the channel kinetics, which is a standard conceptual answer when you link it explicitly to the overlap of inactivation and recovery.",
        ],
        commonMistake:
          "Confusing inactivation and closing of activation gate as the same thing, or claiming the action potential is conducted without local circuits.",
        tags: ["action-potential", "refractory"],
      },
      {
        id: "t15-1-d7",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe and explain the rapid conduction of an impulse in a myelinated axon, with reference to saltatory (jumping) conduction, nodes of Ranvier, and the distribution of voltage-gated ion channels you would show in a diagram or describe in text.",
        modelAnswerPoints: [
          "Myelin (Schwann / oligodendrocyte wraps) insulates the axolemma between nodes, reducing short-circuiting of transmembrane current.",
          "High density of Na+ (and K+) channels at nodes of Ranvier; channels sparse under myelin (internode).",
          "AP effectively regenerates at each node, depolarising the next, so the wave appears to ‘jump’—saltatory conduction, faster and more energy-efficient for long axons.",
        ],
        workedSolution: [
          "In a myelinated peripheral nerve fibre, Schwann cell wraps lay down compact myelin and leave periodic gaps, the nodes of Ranvier, where the axon membrane is exposed to extracellular fluid and where clusters of voltage-gated sodium and potassium channels are inserted at very high areal density compared with the internodal segment.",
          "Between nodes, the lipid-rich sheath increases effective membrane resistance and reduces capacitance, so a depolarising current that arrives at a node is less dissipated in useless capacitive charging over long continuous membrane and is instead guided longitudinally, allowing the next node, often about a millimetre away in the largest fibres, to be brought to threshold at high speed as if the excitation hopped from gap to gap.",
          "Because each new node re-launches a full-blown all-or-nothing action potential, the regenerative feature of axonal signalling is preserved, while only nodal regions consume large numbers of open channels per millisecond, which is biophysically more economical than a uniformly excitable, thick unmyelinated cylinder of the same conduction need.",
          "In examination descriptions you should name saltatory (jumping) conduction, the nodal high-channel density, the insulating role of myelin, and a brief contrast with continuous conduction in fine unmyelinated C fibres, which is slower for comparable diameter categories.",
        ],
        commonMistake:
          "Saying the impulse ‘skips’ without crossing any membrane at nodes, or that myelin actively pumps the signal, rather than that channels cluster at nodes and current spread is optimised.",
        tags: ["myelin", "saltatory"],
      },
      {
        id: "t15-1-d8",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Describe the main structural features of a cholinergic (acetylcholine-using) chemical synapse between two neurones, and explain how a nerve impulse in the presynaptic terminal leads to a response in the postsynaptic cell, including the role of calcium ions at the presynaptic active zone.",
        modelAnswerPoints: [
          "Synapse: pre terminal; synaptic cleft; post membrane; vesicles; receptors on post membrane.",
          "AP in presynaptic: depolarises terminal; opens voltage-gated Ca2+ channels; Ca2+ influx.",
          "Ca2+ triggers synaptic vesicle fusion / exocytosis of ACh; ACh diffuses, binds receptors on post membrane.",
          "ACh opens ion channels (ligand-gated) — excitatory or inhibitory depending on post receptor type; ACh quickly removed (e.g. AChE).",
        ],
        workedSolution: [
          "The presynaptic bouton of a cholinergic interneurone or lower motor branch contains a cytosolic pool of small clear synaptic vesicles loaded with acetylcholine, clustered near the presynaptic active zone, which faces a narrow 20–40 nm synaptic cleft over which a basal lamina and extracellular matrix sometimes sit, with the postsynaptic membrane of the dendrite or soma holding high densities of cholinergic ligand-gated cation (nicotinic in many examples) or other cholinoreceptor subtypes, plus structural proteins such as those linking to the postsynaptic density seen in micrographs in teaching.",
          "An arriving action potential depolarises the presynaptic bouton, which opens preterminal voltage-gated calcium channels, because calcium is far more concentrated outside; influx of Ca2+ over milliseconds raises local internal calcium, which is the obligate signal for the SNARE–complex fusion machinery to dock a vesicle to the plasmalemma and exocytose acetylcholine quantally into the cleft in packets.",
      "Molecules of acetylcholine then diffuse, bind, and in many excitatory nicotinic synapses directly open a nonselective cation channel that depolarises the postsynaptic cell toward threshold for its own local calcium or sodium electrogenesis, while acetylcholinesterase in the cleft and on postsynaptic folds rapidly cleaves the transmitter, terminating the event so sustained firing in the pre terminal produces discrete postsynaptic potentials whose summation in space and time codes signal strength, which is the full causal chain the syllabus labels.",
        ],
        commonMistake:
          "Saying Ca2+ carries the current through the post synapse, or that ACh re-enters the presynaptic cell unchanged as the main termination step.",
        tags: ["synapse", "acetylcholine"],
      },
      {
        id: "t15-1-d9",
        noteId: "t15-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which option best characterises a core difference between continuous conduction in an unmyelinated C fibre and saltatory conduction in a large myelinated axon of similar physiological importance?",
        options: [
          { id: "A", text: "Only myelinated axons can produce action potentials." },
          { id: "B", text: "Regenerative Na+ current is concentrated at nodes in myelinated fibres, so the impulse effectively jumps, increasing effective speed along the fibre." },
          { id: "C", text: "C fibres are always faster than myelinated A fibres because they are thinner." },
          { id: "D", text: "Myelin is produced by motor neurone axons, not by glial cells." },
        ],
        correctOptionId: "B",
        explanation:
          "Saltatory conduction in myelinated axons relies on channel-rich nodes and insulating internodes, giving faster propagation; unmyelinated axons conduct continuously, more slowly for comparable contexts.",
        distractorRationale: {
          A: "Unmyelinated axons also conduct action potentials—continuous, not saltatory.",
          C: "Thinner, unmyelinated C fibres are generally slower than large myelinated fibres.",
          D: "Myelin is formed by glia (e.g. Schwann cells in the PNS, oligodendrocytes in the CNS), not by neurones as myelin-synthesising cells.",
        },
        tags: ["myelin", "mcq"],
      },
      {
        id: "t15-1-d10",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 4,
        marks: 9,
        stem: "Describe the roles of the neuromuscular junction, the T-tubule (transverse tubule) system and the sarcoplasmic reticulum in eliciting contraction of striated (skeletal) muscle after excitation of a somatic motor neurone. In the same answer, describe the banding pattern and ultrastructure of a sarcomere and explain the sliding-filament model, including the parts played by actin, myosin, troponin, tropomyosin, calcium ions and ATP.",
        modelAnswerPoints: [
          "NMJ: axon depolarises terminal; ACh; post junctional folds; motor end plate depolarisation (EPP); local currents excite surrounding sarcolemma and fibre.",
          "T-tubules: invaginations; carry surface depolarisation deep into fibre to near triads.",
          "SR: Ca2+ store; release via ryanodine / Ca2+ release; SR-ATPase re-sequesters Ca2+ after repolarisation; relaxation.",
          "Sarcomere: Z line to Z line; I band = actin only; A band = actin + myosin; H zone (relaxed) myosin / thick only between thin filaments; M line anchors thick filaments.",
          "Sliding filament: myosin heads form cross-bridges; power stroke; ATP binding detaches; Ca2+ binds troponin, moves tropomyosin to expose myosin-binding sites on actin; cycling continues while Ca2+ and ATP available.",
        ],
        workedSolution: [
          "A motor axon’s action potential invades a terminal bouton, opens calcium channels, elicits ACh release into the cleft, and cationic flow through motor end plate nicotinic channels depolarises the end plate, generating an EPP; when strong enough, this generates a self-propagating action potential along the sarcolemma and down into the T-tubule system of each muscle cell, so every sarcomere region is notified nearly simultaneously rather than from slow radial diffusion of charge alone from the surface.",
          "T-tubules, repeating alongside each A–I junction region in many vertebrate fibres, place the external electrical event immediately adjacent to the terminal cisternae of the sarcoplasmic reticulum, a specialised smooth endomembranous system loaded with calsequestrin-bound calcium, which, through voltage-sensing / calcium-induced calcium release at the triad, dumps calcium ions into the cytosol, raising free calcium from roughly nanomolar to micromolar, which is the signal to contract, while SERCA pump activity later clears calcium into the SR in relaxation once surface excitation has ceased.",
      "A sarcomere, defined between two Z lines, shows in electron images an H zone in the mid-A band in relaxed striated muscle where there is myosin thick filament only, flanked on each side by thin actin filaments from opposing Z lines that interdigitate, with I bands the actin-only extensions beyond the A band, and the Z disc anchoring the thin filaments, while the M line in the A band organises the thick filament backbones — which is the structural vocabulary the exam can ask you to use from a micrograph or diagram without needing artist drawing skills beyond labels.",
      "In the mechanical cycle, the globular myosin heads, previously cocked in part by ATP, bind to the thin filament in the presence of sufficient calcium, perform a change in conformational angle that drags the thin and thick filaments past each other (power stroke), with ADP/ Pi release, then a new ATP binds the head, reducing affinity for actin to detach, hydrolyse ATP to re-cock, and the cycle can repeat, producing a ratcheted sliding so sarcomere length shortens and I bands narrow while the A band width stays the same, which is the key prediction of the sliding-filament model you must be able to narrate, explicitly naming tropomyosin as the strand blocking the groove, troponin as the multimer that binds Ca2+ and repositions the tropomyosin string to expose the myosin binding sites, with ATP and its hydrolysis as the source of the cycling energy rather than a single stroke fuel.",
        ],
        commonMistake:
          "Omitting that Ca2+ release is intracellular and comes from the SR, not from extracellular ‘calcium in the cleft’ in the same way as a synapse, or describing tropomyosin and troponin in vague terms that would work for any protein without mechanical consequence.",
        tags: ["muscle", "NMJ", "sliding-filament"],
      },
    ],
    flashcards: [
      {
        id: "t15-1-f1",
        noteId: "t15-1",
        difficulty: 1,
        front: "Endocrine: two defining delivery features.",
        back: "Hormones in blood; widespread distribution; only cells with matching receptors respond.",
        examPhrasing: "Describe features of the endocrine system.",
        tags: ["endocrine"],
      },
      {
        id: "t15-1-f2",
        noteId: "t15-1",
        difficulty: 1,
        front: "Nervous vs endocrine: speed / duration (one line each).",
        back: "Nervous: very fast, short events; endocrine: slower, often longer lasting systemic effects.",
        examPhrasing: "Compare speed of nervous and endocrine control.",
        tags: ["comparison"],
      },
      {
        id: "t15-1-f3",
        noteId: "t15-1",
        difficulty: 2,
        front: "Sensory vs motor neurone: where is the cell body in a spinal somatic motor neurone vs a first-order somatic sensory neurone?",
        back: "Motor: CNS (ventral horn / motor nuclei). Sensory: dorsal root ganglion (PNS) for the typical pseudounipolar somatic afferent.",
        examPhrasing: "State where the cell bodies of sensory and motor neurones are found.",
        tags: ["neurones"],
      },
      {
        id: "t15-1-f4",
        noteId: "t15-1",
        difficulty: 2,
        front: "Resting potential: which ion dominates passive permeability at rest, and is inside negative or positive?",
        back: "K+ leak dominates; inside negative (e.g. about −70 mV).",
        examPhrasing: "Explain the sign of the resting potential.",
        tags: ["resting"],
      },
      {
        id: "t15-1-f5",
        noteId: "t15-1",
        difficulty: 3,
        front: "Node of Ranvier: why channels cluster there in myelinated axons.",
        back: "AP regenerates; high Na+ (and K+) channel density; myelin insulates between nodes, enabling saltatory conduction.",
        examPhrasing: "Explain role of nodes of Ranvier in myelinated neurones.",
        tags: ["myelin"],
      },
      {
        id: "t15-1-f6",
        noteId: "t15-1",
        difficulty: 3,
        front: "Presynaptic Ca2+ at a chemical synapse — job.",
        back: "Influx through voltage-gated channels triggers vesicle fusion and neurotransmitter exocytosis.",
        examPhrasing: "State the role of calcium ions at a synapse.",
        tags: ["synapse"],
      },
      {
        id: "t15-1-f7",
        noteId: "t15-1",
        difficulty: 4,
        front: "Absolute refractory: one consequence for firing rate.",
        back: "Sets a minimum time between full APs at a locus, limiting maximum frequency.",
        examPhrasing: "Explain the importance of the refractory period in impulse frequency.",
        tags: ["refractory"],
      },
      {
        id: "t15-1-f8",
        noteId: "t15-1",
        difficulty: 4,
        front: "T-tubule vs SR — one job each in muscle excitation–conduction coupling.",
        back: "T-tubule: surface depolarisation deep into the fibre. SR: stores and releases Ca2+; SERCA reuptake for relaxation.",
        examPhrasing: "State roles of T-tubules and sarcoplasmic reticulum in striated muscle.",
        tags: ["muscle"],
      },
      {
        id: "t15-1-f9",
        noteId: "t15-1",
        difficulty: 5,
        front: "Troponin + tropomyosin + Ca2+ (sliding filament).",
        back: "Ca2+ binds troponin; tropomyosin moves off actin’s myosin-binding groove so cross-bridge cycling can occur.",
        examPhrasing: "Explain the role of troponin and tropomyosin in muscle contraction.",
        tags: ["sliding-filament"],
      },
      {
        id: "t15-1-f10",
        noteId: "t15-1",
        difficulty: 5,
        front: "H zone vs I band: what changes in contraction?",
        back: "I band narrows; H zone narrows; A band width constant—consistent with filaments sliding past each other.",
        examPhrasing: "What happens to the H band and I band as a sarcomere shortens?",
        tags: ["sarcomere"],
      },
    ],
  },
  "t15-2": {
    noteId: "t15-2",
    drills: [
      {
        id: "t15-2-d1",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 1,
        marks: 6,
        stem: "Describe the rapid response of the Venus flytrap to stimulation of trigger hairs on the lobes of the modified leaves, and explain, with reference to turgor, how closure of the trap is achieved as a result of the repeated signalling pattern described in the syllabus.",
        modelAnswerPoints: [
          "Hairs (trichomes) on inner surface of the trap when bent generate action potentials in sensory mechanoreceptor / associated pathways.",
          "First (single) deflection: ‘memory’/priming, trap stays open; second stimulation within a time window: rapid closure to capture prey (snap movement).",
          "Closure: rapid turgor (hydraulic) change in lobe / midrib cells, asymmetric growth / cell wall / motor zone mechanics — large volume shift leading to bistable bending / snapping, catching prey; slower later sealing and digestion in teaching level.",
        ],
        workedSolution: [
          "In *Dionaea muscipula* each lobe of the two-lobed snap trap bears several stiff trigger hairs; when a visiting insect or droplet of water deflects a hair this bends the hair base and generates, via stretch-activated and calcium-linked signalling, a depolarising electrical event that in the first phase often corresponds to a touch signal without immediate whole-trap movement, which the plant uses to encode ‘an object has been here’ within a time window, rather than waste snap energy on a false rain hit.",
      "A second (or in some described protocols further) deflection, typically within 20–40 seconds, reaches an integrated threshold, triggering a more concerted set of depolarising waves through phloem-like and internal hydraulic coupling so that the trap transitions rapidly from a metastable, slightly convex open conformation in each lobe to a more closed one, a behaviour known at teaching level for its speed among plants.",
      "The mechanical work is not primarily a slow cell-division process but a rapid, often hydraulically fuelled, cell-scale turgor and wall relaxation / swelling redistribution that leads to a curved sheet snapping between states, and after closure, further slower movements may press the two lobes and seal marginals, which secures the prey for digestion, though the first examination emphasis is the thresholded hair stimulation → rapid lobe movement via turgor-driven mechanics, which you should describe without pretending every molecular detail of the 2020s literature is examinable.",
        ],
        commonMistake:
          "Describing the trap as if it were an animal synapse, or missing the time-windowed double-stimulus logic central to the syllabus story.",
        tags: ["Venus-flytrap"],
      },
      {
        id: "t15-2-d2",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Outline why the first mechanical stimulation of a Venus flytrap trigger hair might not by itself be sufficient to close the trap, and what biological advantage the plant gains from a requirement for further stimulation before the rapid closure is triggered (even if the exact timing parameters are not required numerically in all mark schemes).",
        modelAnswerPoints: [
          "Prevents ‘false positives’: rain, debris, and random touches that do not lead to a prey-sized struggle.",
          "Saves energy and opportunity cost of reopening, digestive enzyme investment, and missed photosynthetic time in an open lobe if nothing nutritious is caught.",
        ],
        workedSolution: [
          "A single inanimate touch such as a raindrop or wind-blown object might otherwise trigger full closure, after which the plant would spend time and energy reopening, repairing minor damage, and potentially digesting an empty ‘meal’, forgoing carbon gain through normal leaf function while the secretory machinery is engaged.",
      "Requiring, in standard textbook treatments, a second or confirmatory deflection of the hairs, usually within a short interval, raises the chance that a struggling insect, not a single passive touch, is present, so the organ invests rapid capture movement mainly when a nutritive return is plausibly being signalled, which is the adaptationist explanation the syllabus can accept when phrased carefully as trade-offs between foraging, defence of tissue, and energy use.",
        ],
        commonMistake:
          "Saying the first touch ‘does nothing’ in all cells—acknowledge priming and threshold logic rather than zero response.",
        tags: ["Venus-flytrap", "selection"],
      },
      {
        id: "t15-2-d3",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Explain how the plant hormone auxin (indole-3-acetic acid) can promote cell elongation in shoot tissues by way of its link to plasma-membrane proton pumps that acidify the apoplast near expanding cell walls, at a standard A-level level of detail.",
        modelAnswerPoints: [
          "Auxin in elongation zones in shoot tip / coleoptile models binds / signals (receptor and signal transduction).",
      "Stimulation of P-type H+-ATPase (proton pump) in plasma membrane, exporting H+ to cell wall (apoplast) space.",
      "Acid pH favours cell-wall loosening: expansins / chemistry of wall polysaccharides, allowing turgor-driven irreversible cell expansion; cell takes up water, elongates; requires sustained synthesis of wall material / turgor in integrated views.",
        ],
        workedSolution: [
      "In many canonical textbook pathways, basipetal or locally elevated auxin in the apical young tissues binds to a nuclear and/or plasma-membrane auxin-receptor and signal pathway that, among other outputs, transcriptionally and post-translationally up-regulates the activity and abundance of the plasma-membrane proton ATPase, which is an electrogenic P-type pump that uses ATP to export protons from the cytosol into the apoplast surrounding the protoplast.",
      "This acidification, shifting the cell-wall environment toward a more optimal pH window for a class of proteins called expansins to disrupt hydrogen bonding between hemicellulose and cellulose microfibrils, and more generally to activate wall-loosening enzyme suites in many integrated plant physiology texts, increases wall extensibility, so the high internal turgor that already inflates the cell can now be converted into an irreversible increase in area and length rather than an elastic return after small strain.",
      "Water then follows the osmotic potential into the vacuole-laden cell, the wall polysaccharide matrix is continuously remodelled, and the net macroscopic outcome is a faster elongation than would occur in low-auxin flanks, which is the acid-growth / proton-pump story that answers ‘auxin, proton pumping, acidify, elongation’ in one coherent story without contradicting the newer molecular literature about exact receptor suites when you are only examined at the 9700 mechanism outline level.",
        ],
        commonMistake:
          "Claiming auxin is itself pumped into the wall, rather than that auxin acts as a signal that drives H+ efflux, or omitting the link between looser wall and turgor-driven expansion.",
        tags: ["auxin", "proton-pump"],
      },
      {
        id: "t15-2-d4",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Contrast phototropic bending in a coleoptile or young shoot, where unequal auxin distribution causes differential elongation, with the more general acid-growth mechanism by which higher auxin on the elongation side of a tissue can increase wall extensibility, stating clearly the levels (organ, tissue, cell) you are referring to in each part of the answer.",
        modelAnswerPoints: [
          "Tropic bending: organ level—light or gravity cue → lateral redistribution of auxin; more auxin in elongating ‘shade’ (or lower) side → faster cell elongation there → organ curvature (phototropism / gravitropism).",
          "At cell / wall level: the higher auxin side of the gradient still uses mechanisms including proton pumping / wall acidification in expanding cells, explaining faster elongation where auxin is higher, consistent with 15.2’s proton-pump point.",
        ],
        workedSolution: [
      "In phototropism, short-wavelength or directional light absorbed unevenly in the growing tip of a shoot or a grass coleoptile re-distributes a pool of IAA to the side away from a unilateral light source, so a lateral gradient of millimetres-scale auxin is established, not merely a high uniform concentration, and because auxin in higher concentration can locally enhance acid growth in those cortical and epidermal cells, they elongate faster, bending the organ toward a light that would otherwise be unfavourable for chloroplast performance.",
      "Gravitropism uses the same type of logic: statolith sedimentation in the root or shoot cap triggers redistribution so that the lower (or, in roots, lower) flanks of the elongation zone get the auxin they need to be regulated appropriately—roots vs shoots differ in their growth responses but both tie organ bending to a gradient of a growth regulator.",
      "What ties these organ-level tropic curvatures to the syllabus 15.2 bullet is the shared micro-mechanism: the cells on the more rapidly elongating side are, in a typical examination narrative, the ones in which the auxin signal more strongly up-regulates proton efflux, wall softening, and water uptake, so tropic response is a spatially patterned deployment of a chemical elongation system rather than a separate mysterious bending force, which is the level-contrast question examiners are hinting you to articulate from organ distribution down to H+ in the apoplast.",
        ],
        commonMistake:
          "Describing tropic curvature without naming auxin redistribution, or conflating ‘more auxin’ with ‘faster cell division’ at the expense of elongation language where the mark scheme is elongation-focussed.",
        tags: ["auxin", "tropism"],
      },
      {
        id: "t15-2-d5",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe the role of the hormone gibberellin in the germination of barley grain, including the relationship between the embryo, the starchy endosperm, and the secretion of amylase that mobilises food reserves for the growing seedling.",
        modelAnswerPoints: [
      "Gibberellin is produced by (or moves from) the embryo to the aleurone layer of the starchy endosperm after imbibition / dormancy break.",
      "Aleurone is stimulated to synthesise and secrete hydrolytic enzymes, especially amylase (alpha-amylase) into the starchy endosperm.",
      "Amylase digests stored starch to maltose and glucose, providing sugars for the embryo’s respiration and growth; gibberellin is thus a key germination hormone in this cereal system.",
        ],
        workedSolution: [
      "A mature barley caryopsis contains a diploid embryo, a starchy endosperm packed with starch granules as stored food, and a thin triploid aleurone layer of protein- and oil-rich living cells that wraps the starchy part and can mount a post-germinative secretory program once hormones signal water uptake has begun and the seed’s dormancy is lifted.",
      "When the imbibing embryo and/or scutellum is activated, a gibberellin signal, moving from the embryo toward the aleurone, is received by the aleurone cells’ gibberellin-responsive transcriptional programme, so these cells de novo express and exocytose a suite of hydrolases, of which the textbook centrepiece is alpha-amylase, into the starchy endosperm across the apoplast, solubilising the starch in situ.",
      "The hydrolysis products, reducing sugars, diffuse back to the scutellum and embryo where they fuel glycolysis and growth of the first root and shoot, and because this entire pipeline does not work if the aleurone is removed or the gibberellin signal is missing in classic experiments, the examination answer treats gibberellin as a molecular ‘start digestion’ key that couples embryonic imbibition to the mobilisation of a large, distant starch reserve, which is the 15.2 / cross-ref 16.3.4 story in compact form.",
        ],
        commonMistake:
          "Saying the embryo itself must digest all starch in place without the aleurone and secreted amylase, or that gibberellin digests starch directly as an enzyme instead of a hormone signal.",
        tags: ["gibberellin", "germination"],
      },
      {
        id: "t15-2-d6",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Outline how a classical ablation or hormone-application experiment in barley seeds can be used to show that the aleurone’s response to gibberellin is required for the normal breakdown of starchy endosperm reserves, and name at least one measured output that implicates the aleurone’s secreted enzymes rather than a purely mechanical imbibition effect.",
        modelAnswerPoints: [
          "Aleurone can be removed surgically: germination and starch mobilisation fail or are greatly reduced without the aleurone, even with imbibition.",
      "Adding gibberellin to de-embryoed half-grain + aleurone (classical 'half-seed' tests) can still induce amylase release into surrounding medium without an intact whole embryo, showing the aleurone is a gibberellin target tissue.",
      "Measuring amylase activity in incubation medium, or endosperm reducing sugar, links enzyme secretion to the hormone.",
        ],
        workedSolution: [
      "In half-seed bioassay designs, a barley grain is longitudinally split, the embryo is discarded on one block, the starchy and aleurone tissues remain, and the half is floated on water or a buffered solution with or without exogenous GA3; after a few days the liquid outside is assayed for alpha-amylase activity by starch–iodine clearing or a reducing-sugar end-point, which rises dramatically in +GA compared with –GA, showing that a tissue block lacking an embryo can still, if the aleurone is present, be hormonally induced to secrete a starch-degrading activity.",
      "If the same experiment is run after scraping away the aleurone before incubation, the +GA flasks often fail to show large amylase production, or show much less, so the locus of GA perception is not the starchy endosperm alone, matching genetic and molecular work that the aleurone transcriptome is GA-responsive.",
      "Therefore the examination-level logic is: spatial separation of scutellar vs aleurone roles, GA as diffusible signal from the embryo in intact seeds, aleurone as the secretory factory, and a quantitative readout in medium sugar or amylase specific activity as the proof that a biochemical pathway, not imbibition alone, is mobilising reserves, which is a fair extension question building on 15.2’s barley bullet.",
        ],
        commonMistake:
          "Citing a growth measurement without any enzyme or sugar data when the question asks for a marker of aleurone enzyme secretion specifically.",
        tags: ["gibberellin", "method"],
      },
      {
        id: "t15-2-d7",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Compare and contrast the Venus flytrap’s rapid, stimulus-thresholded leaf movement and auxin-driven elongation growth in a shoot, at the level of time scale, the nature of the response (reversible or irreversible in the obvious macroscopic sense) and the role of cell-wall chemistry, without claiming unsupported homology between animal nerves and phloem.",
        modelAnswerPoints: [
          "Venus flytrap: very fast, mechanical, typically seconds; trap closure macroscopically quasi-bistable / mechanical snap; not primarily a uniform enlargement of all cell walls in the lobe, though local wall and turgor couples matter; prey capture.",
      "Auxin elongation: slower, hours scale in organ growth; irreversible (growth) in those cells, uses sustained wall remodelling and H+ / expansin mechanisms in elongating files.",
        ],
        workedSolution: [
      "The trap response is a fast motor-like movement of a pre-built structure between metastable rest positions, in which a large fraction of the visible strain can appear within a second, driven by a coordinated depolarising and hydraulic wave and cell-scale turgor shifts, and its biological function is a binary capture event rather than a smooth multi-day increase in organ length, though energy must later be spent to reopen, which is a different timescale and partly slower.",
      "Auxin mediates sustained enlargement of organ area by up-regulated acid growth in only certain files of the growth zone, so the macroscopic result over a day is an irreversible increase in the dimensions of a stem, petiole, or coleoptile, not a bistable snap, and the wall chemistry is continuously remodelled, not just momentarily deformed, which is a fair contrast the syllabus invites when both topics sit under ‘control and co-ordination in plants’.",
      "Neither mechanism should be overdrawn as identical to an animal action potential, but the examination answer can truthfully state that the flytrap is notable for a nearly animal-like speed in the plant kingdom, whereas IAA is notable for a hormonal economy shared across the plant, coordinating plastic growth rather than a snap trap, which is the contrast map you are asked to sketch.",
        ],
        commonMistake:
          "Saying both are exactly the same ‘hormone process’; keep timescale, mechanical snap vs growth, and the role of the flytrap as capture distinct.",
        tags: ["synoptic"],
      },
      {
        id: "t15-2-d8",
        noteId: "t15-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best links auxin to primary cell elongation in a typical A-level (acid-growth) explanation?",
        options: [
          { id: "A", text: "Auxin is pumped directly into the primary cell wall, lowering pH as a solute." },
          { id: "B", text: "Auxin signalling increases H+-ATPase activity, local apoplast acidification, and wall loosening, enabling turgor-driven expansion." },
          { id: "C", text: "Auxin blocks all aquaporin channels, forcing cells to stop elongating until ethylene arrives." },
          { id: "D", text: "Auxin is only active in the root cap and never in shoots." },
        ],
        correctOptionId: "B",
        explanation:
          "The standard syllabus line ties auxin to proton-pumping, wall acidification, and extensibility/turgor-driven elongation.",
        distractorRationale: {
          A: "The hormone is a signal, not a bulk solute in the wall, and the pump exports H+.",
          C: "That contradicts a textbook elongation story and invents a wrong mechanism.",
          D: "Auxin is central in shoot apices and coleoptile models, not only root cap.",
        },
        tags: ["auxin", "mcq"],
      },
      {
        id: "t15-2-d9",
        noteId: "t15-2",
        kind: "mcq",
        difficulty: 2,
        stem: "In barley (cereal) grain germination, where is gibberellin’s main site of action for initiating starch hydrolysis in the stored endosperm, in a typical textbook model?",
        options: [
          { id: "A", text: "The scutellar epithelium only, with no second tissue involved." },
          { id: "B", text: "The aleurone layer, which secretes amylase into the starchy endosperm in response to gibberellin from the embryo." },
          { id: "C", text: "The starchy endosperm cells themselves, which are dead and have no transcription." },
          { id: "D", text: "The pericycle of the first lateral root, which has not yet formed at germination time." },
        ],
        correctOptionId: "B",
        explanation:
          "Gibberellin from the embryo causes the living aleurone to synthesise and secrete amylase that digests the starchy endosperm.",
        distractorRationale: {
          A: "The scutellum takes up products but the classic story emphasises the aleurone as GA-responsive secretor.",
          C: "Starchy cells store starch; they are not the classical GA-sensing amylase factory.",
          D: "Irrelevant tissue for this classical cereal germination pathway.",
        },
        tags: ["gibberellin", "mcq"],
      },
      {
        id: "t15-2-d10",
        noteId: "t15-2",
        kind: "mcq",
        difficulty: 3,
        stem: "A healthy Venus flytrap does not always snap fully shut when a single trigger hair is touched once. In teaching models of this behaviour, which interpretation is most defensible as an adaptive explanation?",
        options: [
          { id: "A", text: "The first touch permanently damages the hair so a second is impossible—pure damage limitation." },
          { id: "B", text: "A time-windowed second (confirmatory) stimulation reduces the chance of ‘false alarms’ and wasted closure on non-prey, saving energy and photosynthetic time." },
          { id: "C", text: "The first touch is ignored because the plant has no action potentials, only phloem flow." },
          { id: "D", text: "A single touch always means successful prey capture, so a second is never needed in nature." },
        ],
        correctOptionId: "B",
        explanation:
          "The thresholded, often double-hit requirement in textbook treatments reduces closure on inanimate, low-value stimuli.",
        distractorRationale: {
          A: "Hairs are reusable in normal operation; the story is integration, not injury.",
          C: "Electrical excitability in the trap is a standard part of the teaching model.",
          D: "Contradicts the very phenomenon in the question stem.",
        },
        tags: ["Venus-flytrap", "mcq"],
      },
    ],
    flashcards: [
      {
        id: "t15-2-f1",
        noteId: "t15-2",
        difficulty: 1,
        front: "Venus flytrap: what stimulates closure (macroscopic).",
        back: "Deflection of trigger hairs on the inner trap lobes; often a second deflection in a time window in textbook accounts.",
        examPhrasing: "Describe the response of the Venus flytrap to hair stimulation.",
        tags: ["Venus-flytrap"],
      },
      {
        id: "t15-2-f2",
        noteId: "t15-2",
        difficulty: 1,
        front: "Venus flytrap closure: main physical mechanism (syllabus level).",
        back: "Rapid turgor / hydraulically driven movement of the lobes, leading to fast trap closure to capture prey.",
        examPhrasing: "Explain how the trap is closed in the Venus flytrap.",
        tags: ["Venus-flytrap"],
      },
      {
        id: "t15-2-f3",
        noteId: "t15-2",
        difficulty: 2,
        front: "Auxin + H+-pump: one-sentence link.",
        back: "Auxin signalling can enhance proton-pumping, acidifying the apoplast, loosening the wall and favouring cell elongation under turgor.",
        examPhrasing: "Explain how auxin is linked to proton pumping in elongation growth.",
        tags: ["auxin"],
      },
      {
        id: "t15-2-f4",
        noteId: "t15-2",
        difficulty: 2,
        front: "Why acidify the cell wall for growth?",
        back: "Low pH allows expansin-mediated and enzymatic loosening of the matrix so walls yield under turgor, enabling irreversible growth.",
        examPhrasing: "Why does acid growth increase extensibility of the cell wall?",
        tags: ["acid-growth"],
      },
      {
        id: "t15-2-f5",
        noteId: "t15-2",
        difficulty: 3,
        front: "Barley germination: gibberellin source → target (classic story).",
        back: "GA from embryo; aleurone responds by secreting amylase into starchy endosperm; starch → sugars for the embryo.",
        examPhrasing: "Describe the role of gibberellin in germination of barley.",
        tags: ["gibberellin"],
      },
      {
        id: "t15-2-f6",
        noteId: "t15-2",
        difficulty: 3,
        front: "Aleurone — two facts.",
        back: "Living layer of cereal grain; gibberellin target tissue secreting hydrolases (e.g. amylase) into the starchy endosperm.",
        examPhrasing: "What is the aleurone layer and what does it do in germination?",
        tags: ["aleurone"],
      },
      {
        id: "t15-2-f7",
        noteId: "t15-2",
        difficulty: 4,
        front: "Venus flytrap vs phototropism: timescale (rough).",
        back: "Trap closure: seconds. Phototropic curvature: much slower, hours as auxin redistributes and cells elongate differentially.",
        examPhrasing: "Contrast rapid plant movement with auxin-mediated growth responses.",
        tags: ["synoptic"],
      },
      {
        id: "t15-2-f8",
        noteId: "t15-2",
        difficulty: 4,
        front: "What does alpha-amylase do in a germinating grain?",
        back: "Hydrolyses stored starch in the starchy endosperm to provide sugars (e.g. maltose, glucose) for the embryo and seedling growth.",
        examPhrasing: "State a role of amylase in barley endosperm mobilisation.",
        tags: ["germination"],
      },
      {
        id: "t15-2-f9",
        noteId: "t15-2",
        difficulty: 5,
        front: "Cross-ref: gibberellin in Topic 16 (very short).",
        back: "Further detail on gene-level GA control and DELLA in some specs—see 16.3 in your full notes; 15.2 needs barley + aleurone + amylase story.",
        examPhrasing: "Where is gibberellin revisited in the syllabus after plants?",
        tags: ["cross-ref"],
      },
      {
        id: "t15-2-f10",
        noteId: "t15-2",
        difficulty: 5,
        front: "Imbibition alone vs GA pathway in barley (concept).",
        back: "Water uptake starts metabolism, but the GA → aleurone → amylase programme specifically mobilises starch; without it, the classical half-seed GA story breaks down.",
        examPhrasing: "Why is imbibition not a complete answer for starch mobilisation?",
        tags: ["germination"],
      },
    ],
  },
};
