import type { SubtopicPracticePack } from "./types";

/**
 * Topic 5 practice — 9700 5.1–5.2 (mitosis, cell cycle, telomeres, stem cells, tumours, stage ID).
 *
 * Crosswalk (drill id -> syllabus intent, not verbatim):
 * t5-1: d1 chromosome structure; d2 mitosis roles (growth, replacement, repair, asexual);
 *       d3 mitotic cycle (G1, S, G2, mitosis, cytokinesis); d4 telomeres; d5 stem cells;
 *       d6 tumours; d7–d10 deepen cycle / identity / MCQs.
 * t5-2: d1–d6 stage behaviour (envelope, spindle, chromosomes); d7–d10 identification /
 *       interpretation / plant vs animal contrasts where syllabus expects.
 */
export const BIOLOGY_TOPIC5_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t5-1": {
    noteId: "t5-1",
    drills: [
      {
        id: "t5-1-d1",
        noteId: "t5-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Describe the structure of a chromosome as recognised in the syllabus, with reference to DNA, histone proteins, sister chromatids, the centromere and telomeres.",
        modelAnswerPoints: [
          "A chromosome contains DNA associated with histone proteins, forming chromatin that can condense for division.",
          "After DNA replication, a chromosome consists of two sister chromatids, each containing an identical DNA molecule, joined at the centromere.",
          "Telomeres are specialised repetitive DNA sequences at the ends of chromosomes.",
        ],
        workedSolution: [
          "At the structural level expected here, each chromosome is built from a long DNA molecule wound around histone proteins so that the genetic material can be packaged and regulated within the nucleus.",
          "When the cell has replicated its DNA in preparation for mitosis, each chromosome is seen as two parallel sister chromatids, where each chromatid contains one complete copy of that chromosome's DNA and they are held together at a constricted region called the centromere.",
          "The centromere is therefore the attachment point that later links each chromatid to spindle microtubules so they can be separated accurately.",
          "Telomeres are non-coding protective regions at the tips of linear chromosomes; their special sequence organisation is linked to end-replication issues and is outlined separately when DNA is copied.",
        ],
        commonMistake:
          "Calling the whole replicated X-shaped unit a ‘chromatid’ instead of recognising that it is one chromosome made of two sister chromatids joined at the centromere.",
        tags: ["chromosome", "structure"],
      },
      {
        id: "t5-1-d2",
        noteId: "t5-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Explain the importance of mitosis in producing genetically identical daughter cells during growth of multicellular organisms, replacement of damaged or dead cells, repair of tissues, and asexual reproduction.",
        modelAnswerPoints: [
          "Mitosis partitions replicated chromosomes so each daughter nucleus receives the same complement of DNA as the parent nucleus had before division.",
          "Growth and tissue repair therefore add cells with the same genetic information as surrounding cells, preserving function.",
          "Replacement of damaged or dead cells restores the same cell types without changing the organism's genotype.",
          "In asexual reproduction, mitotic divisions can generate offspring that are genetically the same as the parent (barring rare mutation).",
        ],
        workedSolution: [
          "Mitosis is the nuclear division that follows DNA replication and separates sister chromatids so that each new nucleus receives one complete copy of every chromosome.",
          "Because the daughter nuclei inherit the same alleles in the same arrangement as the parent cell (assuming no mutation), the daughter cells are genetically identical to the parent cell for nuclear DNA.",
          "During growth of a multicellular organism, repeated rounds of mitosis increase cell number while keeping all somatic lineages matched to the original zygote's genome, which is required for coordinated development and organ function.",
          "When cells die or are damaged, mitosis in surviving stem or progenitor cells replaces them with new cells carrying the same genetic programme, allowing local repair without reshuffling genes.",
          "In asexual reproduction, entire new individuals can arise from mitotic proliferation of parental cells, so offspring inherit the parent's nuclear genome unchanged apart from rare copying errors.",
        ],
        commonMistake:
          "Claiming mitosis ‘mixes’ genetic material like meiosis, or saying daughter cells are ‘similar’ without stating they receive the same chromosome set as the parent nucleus after replication.",
        tags: ["mitosis", "roles"],
      },
      {
        id: "t5-1-d3",
        noteId: "t5-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Outline the mitotic cell cycle, including interphase with growth in G1 and G2 and DNA replication in S phase, followed by mitosis and cytokinesis.",
        modelAnswerPoints: [
          "Interphase is subdivided into G1 (cell growth and routine metabolism), S phase (DNA replication), and G2 (further growth and preparation).",
          "Mitosis is nuclear division that separates sister chromatids into separate nuclei.",
          "Cytokinesis divides the cytoplasm to produce separate daughter cells.",
        ],
        workedSolution: [
          "The mitotic cell cycle begins with interphase, when the cell is not visibly dividing but is metabolically active and, in most cases, increasing in mass.",
          "G1 is the first growth phase after the previous division, during which the cell synthesises proteins and organelles and monitors signals before committing to replicate DNA.",
          "S phase is the synthetic phase in which each chromosome is duplicated so that every chromosome consists of two sister chromatids still joined at the centromere.",
          "G2 follows S phase and allows further growth and synthesis of proteins (such as those needed for spindle formation) before mitosis begins.",
          "Mitosis is the M phase of nuclear division in which condensed chromosomes align and sister chromatids are pulled apart, after which cytokinesis partitions the cytoplasm so that two separate daughter cells are produced.",
        ],
        commonMistake:
          "Placing DNA replication in mitosis itself instead of in S phase of interphase, or omitting G1 and G2 as growth phases around S phase.",
        tags: ["cell-cycle", "interphase"],
      },
      {
        id: "t5-1-d4",
        noteId: "t5-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Outline the role of telomeres in preventing the loss of genes from the ends of chromosomes during DNA replication.",
        modelAnswerPoints: [
          "DNA polymerase cannot fully replicate the extreme ends of linear DNA in the same way as internal regions (end-replication problem).",
          "Telomeres are non-coding repetitive end regions that can be shortened slightly without deleting essential genes.",
          "This buffers coding sequences so functional genes are not lost from chromosome tips each round of replication.",
        ],
        workedSolution: [
          "When DNA is copied, the molecular machinery that synthesises the new strand has difficulty completing the very ends of a linear template, so a small amount of sequence at each tip may not be duplicated perfectly.",
          "Telomeres consist of tandem repeated non-coding DNA at chromosome ends, so successive rounds of replication can shorten these terminal repeats rather than eroding unique genes that code for proteins.",
          "In this way telomeres act as disposable protective caps: their gradual shortening is tolerated up to a limit, whereas immediate loss from coding DNA at every cycle would remove essential genetic information from the ends of chromosomes.",
        ],
        commonMistake:
          "Saying telomeres ‘speed up’ replication or ‘join’ chromosomes randomly, instead of linking them to end protection during incomplete end copying.",
        tags: ["telomeres", "DNA-replication"],
      },
      {
        id: "t5-1-d5",
        noteId: "t5-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Outline the role of stem cells in cell replacement and tissue repair by mitosis.",
        modelAnswerPoints: [
          "Stem cells can divide by mitosis to produce more stem cells (self-renewal) and/or daughter cells that differentiate.",
          "Differentiated cells lost through wear, injury or programmed turnover can be replaced by descendants of stem or progenitor populations.",
          "Local mitotic activity therefore restores tissue structure and function after damage.",
        ],
        workedSolution: [
          "Stem cells are relatively undifferentiated cells that retain the ability to enter the cell cycle and divide by mitosis when signals permit.",
          "Through mitosis, a stem cell can generate daughter cells that remain stem-like and continue the reservoir, or daughters that begin specialising into the mature cell types required by the tissue.",
          "During normal maintenance and after injury, the death or loss of specialised cells triggers signalling that promotes mitosis in the appropriate stem or progenitor niche.",
          "The new cells then differentiate to refill the tissue, which is why stem-cell mitosis is central both to steady cell replacement and to repair after damage.",
        ],
        commonMistake:
          "Treating all mitosis as stem-cell division, or implying stem cells never differentiate, instead of outlining both renewal and production of specialised replacements.",
        tags: ["stem-cells", "repair"],
      },
      {
        id: "t5-1-d6",
        noteId: "t5-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Explain how uncontrolled cell division can result in the formation of a tumour.",
        modelAnswerPoints: [
          "Normally cell division is regulated by checkpoints and signalling so mitosis balances proliferation and differentiation.",
          "If regulatory mechanisms fail, cells can enter mitosis too frequently or fail to stop dividing.",
          "A mass of abnormally dividing cells can accumulate as a tumour (benign if localised; malignant if invasive — syllabus expects uncontrolled division link).",
        ],
        workedSolution: [
          "Healthy tissues control how often cells enter the mitotic cycle by internal checkpoints and external signals, so growth matches need and damaged cells are usually prevented from continuing to divide.",
          "When mutations or other changes disrupt genes that promote or restrain the cell cycle, a cell may ignore stop signals or respond excessively to growth signals.",
          "Such a cell then undergoes mitosis more often than its neighbours, and its descendants inherit the same deregulation, producing an expanding clone.",
          "Continued rounds of uncontrolled mitosis create a growing mass of cells that constitutes a tumour, which can compress surrounding structures and, in malignant disease, may spread if further changes allow invasion.",
        ],
        commonMistake:
          "Saying tumours form only because cells ‘grow bigger’ without mitosis, or confusing tumour formation solely with infection rather than inappropriate proliferation.",
        tags: ["cancer", "regulation"],
      },
      {
        id: "t5-1-d7",
        noteId: "t5-1",
        kind: "mcq",
        difficulty: 2,
        stem: "During which phase of the mitotic cell cycle does DNA replication occur?",
        options: [
          { id: "A", text: "G1 phase" },
          { id: "B", text: "S phase" },
          { id: "C", text: "G2 phase" },
          { id: "D", text: "Anaphase" },
        ],
        correctOptionId: "B",
        explanation:
          "DNA is synthesised during S phase of interphase; by the start of mitosis each chromosome already consists of two sister chromatids.",
        distractorRationale: {
          A: "G1 is primarily growth and preparation before DNA synthesis; replication has not yet occurred.",
          C: "G2 follows replication; the cell prepares for mitosis but does not normally re-replicate the whole genome here.",
          D: "Anaphase is part of mitosis when sister chromatids separate; replication happened earlier in S phase.",
        },
        tags: ["cell-cycle", "S-phase"],
      },
      {
        id: "t5-1-d8",
        noteId: "t5-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which statement best explains why mitosis produces daughter nuclei that are genetically identical to the parent nucleus (before division)?",
        options: [
          { id: "A", text: "Crossing over between homologues randomises alleles before chromatids separate" },
          { id: "B", text: "Each daughter nucleus receives one complete copy of every chromosome derived from sister chromatid separation" },
          { id: "C", text: "The chromosome number is halved so each daughter can fuse with a gamete" },
          { id: "D", text: "Telomeres are removed completely so only coding DNA is inherited" },
        ],
        correctOptionId: "B",
        explanation:
          "After S phase, each chromosome has two genetically identical sister chromatids; mitosis separates them so each daughter nucleus gets the same diploid (or parent) chromosome set.",
        distractorRationale: {
          A: "Crossing over is a feature of meiosis, not standard mitosis.",
          C: "Halving chromosome number describes meiosis, not mitosis.",
          D: "Telomeres are not fully removed in normal mitosis; they protect chromosome ends.",
        },
        tags: ["mitosis", "genetic-identity"],
      },
      {
        id: "t5-1-d9",
        noteId: "t5-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Distinguish cytokinesis from mitosis and state what each achieves in the mitotic cell cycle.",
        modelAnswerPoints: [
          "Mitosis refers to nuclear events that separate sister chromatids into two nuclei.",
          "Cytokinesis is the division of the cytoplasm (and often organelles) between those nuclei.",
          "Together they complete production of two separate daughter cells after one round of nuclear division.",
        ],
        workedSolution: [
          "Mitosis is the sequence of nuclear changes—conventionally described in prophase, metaphase, anaphase and telophase—in which duplicated chromosomes are aligned and sister chromatids are segregated so that two genetically similar nuclei are formed.",
          "Cytokinesis is the separate process that physically splits the cell surface and cytoplasm, for example by a cleavage furrow in many animal cells or by formation of a cell plate in plant cells.",
          "Without cytokinesis, mitosis could still produce two nuclei in one cytoplasm in some cases, but the syllabus treats cytokinesis as the usual completion step that yields two individual daughter cells after mitosis.",
        ],
        commonMistake:
          "Using ‘mitosis’ to mean the whole cell division including cytoplasm splitting, without naming cytokinesis as the cytoplasmic stage.",
        tags: ["cytokinesis", "definitions"],
      },
      {
        id: "t5-1-d10",
        noteId: "t5-1",
        kind: "mcq",
        difficulty: 4,
        stem: "A tissue stem cell divides mitotically. One daughter remains a stem cell and the other begins specialising into a functional epithelial cell. Which idea does this best illustrate?",
        options: [
          { id: "A", text: "Meiotic reduction of chromosome number" },
          { id: "B", text: "Replacement of specialised cells while maintaining a mitotic reservoir" },
          { id: "C", text: "Independent assortment of homologues" },
          { id: "D", text: "Random loss of telomeres from all chromosomes at once" },
        ],
        correctOptionId: "B",
        explanation:
          "Stem-cell mitosis can both renew the stem population and supply differentiating daughters that replace specialised cells—core to replacement and repair.",
        distractorRationale: {
          A: "Meiosis is not involved in routine stem-cell mitosis for tissue maintenance.",
          C: "Independent assortment is a meiotic concept.",
          D: "Telomere shortening is gradual end replication, not simultaneous loss from every chromosome in one division.",
        },
        tags: ["stem-cells", "application"],
      },
    ],
    flashcards: [
      {
        id: "t5-1-f1",
        noteId: "t5-1",
        difficulty: 1,
        front: "Name the main phases of interphase in order and state what happens in S phase.",
        back: "G1, then S, then G2. In S phase DNA is replicated so each chromosome consists of two sister chromatids.",
        examPhrasing: "Outline interphase in the mitotic cell cycle.",
        tags: ["cell-cycle"],
      },
      {
        id: "t5-1-f2",
        noteId: "t5-1",
        difficulty: 1,
        front: "What holds two sister chromatids together before anaphase?",
        back: "The centromere region where sister chromatids are still attached before they separate in anaphase.",
        examPhrasing: "Identify the region joining sister chromatids.",
        confusionPair: "centromere vs telomere",
        tags: ["chromosome"],
      },
      {
        id: "t5-1-f3",
        noteId: "t5-1",
        difficulty: 2,
        front: "List four syllabus contexts where mitosis matters because daughter cells are genetically identical.",
        back: "Growth; replacement of damaged/dead cells; tissue repair; asexual reproduction.",
        examPhrasing: "Explain the importance of mitosis in multicellular organisms.",
        tags: ["mitosis"],
      },
      {
        id: "t5-1-f4",
        noteId: "t5-1",
        difficulty: 2,
        front: "Why are histones mentioned when describing chromosome structure?",
        back: "DNA is wound around histone proteins to package chromatin and regulate access in the nucleus.",
        examPhrasing: "Describe chromosome structure with reference to histones.",
        tags: ["chromatin"],
      },
      {
        id: "t5-1-f5",
        noteId: "t5-1",
        difficulty: 3,
        front: "What problem at chromosome ends do telomeres mitigate during replication?",
        back: "Incomplete copying of linear DNA tips; telomeres are disposable repeated ends so genes are not lost each cycle.",
        examPhrasing: "Outline the role of telomeres in DNA replication.",
        tags: ["telomeres"],
      },
      {
        id: "t5-1-f6",
        noteId: "t5-1",
        difficulty: 3,
        front: "How do stem cells contribute to wound healing in outline?",
        back: "They divide by mitosis; daughters replace lost specialised cells and/or maintain the stem pool.",
        examPhrasing: "Outline the role of stem cells in tissue repair.",
        tags: ["stem-cells"],
      },
      {
        id: "t5-1-f7",
        noteId: "t5-1",
        difficulty: 4,
        front: "One sentence: link loss of cell-cycle control to tumour formation.",
        back: "Unregulated mitosis produces an expanding clone, forming a mass of abnormal cells — a tumour.",
        examPhrasing: "Explain how uncontrolled division forms a tumour.",
        tags: ["cancer"],
      },
      {
        id: "t5-1-f8",
        noteId: "t5-1",
        difficulty: 4,
        front: "After S phase, is the structure called one chromosome or two chromosomes?",
        back: "One chromosome made of two sister chromatids (two DNA molecules), still counted as one chromosome until centromeres split.",
        examPhrasing: "Define sister chromatids.",
        confusionPair: "chromosome number vs chromatid number",
        tags: ["chromosome"],
      },
      {
        id: "t5-1-f9",
        noteId: "t5-1",
        difficulty: 5,
        front: "Where does cytokinesis fit relative to mitosis?",
        back: "After (or completing) telophase — cytoplasm divides so two cells form; mitosis is nuclear.",
        examPhrasing: "Distinguish mitosis and cytokinesis.",
        tags: ["cytokinesis"],
      },
      {
        id: "t5-1-f10",
        noteId: "t5-1",
        difficulty: 5,
        front: "Exam trap: saying DNA replicates during prophase.",
        back: "Replication is in S phase; prophase begins mitosis with already-duplicated chromosomes condensing.",
        examPhrasing: "State when DNA replication occurs in the cell cycle.",
        tags: ["exam-technique"],
      },
    ],
  },

  "t5-2": {
    noteId: "t5-2",
    drills: [
      {
        id: "t5-2-d1",
        noteId: "t5-2",
        kind: "structured",
        difficulty: 1,
        marks: 6,
        stem: "Describe the behaviour of chromosomes and the nuclear envelope from prophase through metaphase in a typical animal cell during mitosis.",
        modelAnswerPoints: [
          "In prophase chromatin condenses into visible chromosomes (each of two chromatids); the nuclear envelope breaks down and the nucleolus disappears.",
          "Spindle microtubules form and attach to kinetochores; chromosomes move.",
          "In metaphase chromosomes align on the metaphase plate (equator) with spindle attachment complete.",
        ],
        workedSolution: [
          "Early in prophase, replicated chromosomes become microscopically visible as they shorten and thicken through condensation, while the nuclear envelope fragments and disappears so spindle microtubules can reach the chromosomes.",
          "In animal cells centrosomes have typically moved apart and microtubules of the spindle extend between poles; kinetochore fibres attach to sister kinetochores on each chromosome.",
          "As prometaphase/metaphase progresses, chromosomes are manoeuvred until they lie in a single plane between the poles, called the metaphase plate, which is the stable alignment before sister chromatids separate.",
          "At metaphase itself, the chromosomes are lined up centrally with spindle tension balancing on sister kinetochores, which is the classic ‘equatorial’ arrangement seen in textbook diagrams and many photomicrographs.",
        ],
        commonMistake:
          "Saying the nuclear envelope reforms at metaphase; it is absent through metaphase in typical animal mitosis and reforms later in telophase.",
        tags: ["prophase", "metaphase"],
      },
      {
        id: "t5-2-d2",
        noteId: "t5-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe chromosome movement during anaphase and the changes that begin in telophase in animal mitosis.",
        modelAnswerPoints: [
          "Anaphase: centromeres split and sister chromatids separate; each chromatid is pulled to opposite poles as a chromosome.",
          "Telophase: chromosomes decondense; nuclear envelopes re-form around each chromosome set; nucleoli reappear.",
        ],
        workedSolution: [
          "Anaphase begins when cohesin holding sister chromatids together is cleaved at the centromere, after which each chromatid is recognised as an individual chromosome.",
          "Motor proteins and shortening kinetochore microtubules move the daughter chromosomes toward opposite spindle poles along the spindle axis, increasing separation between the future two nuclei.",
          "Telophase marks the end of chromosome segregation: chromosomes arrive at the poles and begin to uncoil, so they become less distinct as chromatin again.",
          "Nuclear envelopes reassemble around each complete chromosome set and nucleoli become visible once more, so two genetically identical nuclei are re-established before cytokinesis finishes.",
        ],
        commonMistake:
          "Describing chromatids moving to the same pole or claiming DNA replication occurs during anaphase.",
        tags: ["anaphase", "telophase"],
      },
      {
        id: "t5-2-d3",
        noteId: "t5-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Outline how the spindle behaves during mitosis and how it relates to chromosome separation (names of stages not repeated in detail).",
        modelAnswerPoints: [
          "Spindle microtubules extend between poles (animal cells: centrosomes at poles; plant cells: no centrioles but spindles still form).",
          "Kinetochore microtubules attach to chromosomes and generate force for movement.",
          "Spindle function is essential for orderly segregation of sister chromatids to opposite poles in both plant and animal mitosis.",
        ],
        workedSolution: [
          "The mitotic spindle is a dynamic array of microtubules whose minus ends are focused at spindle poles and whose plus ends project toward the cell equator.",
          "Kinetochore microtubules bind specialised protein structures on centromeres and are the main fibres that shorten or slip to pull chromatids poleward during anaphase.",
          "Polar and astral microtubules help position the spindle and, in animal cells, contribute to cleavage plane positioning later.",
          "Higher plant cells lack centrioles but still assemble spindles from microtubule-organising regions, so chromosome behaviour at each named stage parallels animal mitosis even though pole organisation differs.",
          "Overall, spindle assembly, attachment, and subsequent fibre dynamics convert the chemical regulation of mitosis into the physical separation of duplicated chromosomes.",
        ],
        commonMistake:
          "Calling spindle fibres ‘chromosomes’ or implying they are made of DNA rather than microtubules.",
        tags: ["spindle"],
      },
      {
        id: "t5-2-d4",
        noteId: "t5-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Compare cytokinesis in a typical plant cell with cytokinesis in a typical animal cell with reference to the cell surface membrane and internal structures.",
        modelAnswerPoints: [
          "Animal cells: a cleavage furrow forms as a contractile ring of actin and myosin pinches the cytoplasm.",
          "Plant cells: a cell plate forms across the equator from vesicles (Golgi-derived) that fuse; new cell wall material is laid down.",
          "Both processes separate daughter cytoplasms after mitosis.",
        ],
        workedSolution: [
          "After mitosis, animal cells usually divide the cytoplasm by constriction: a contractile ring under the plasma membrane squeezes inward to form a cleavage furrow that deepens until the two daughter cells are pinched apart.",
          "Plant cells are rigid and cannot furrow inward in the same way; instead, vesicles guided to the former spindle midplane fuse to build a cell plate between the two new nuclei.",
          "The cell plate matures into a new cross-wall with plasmodesmata, while membrane and wall materials complete separation of the daughter protoplasts.",
          "In both kingdoms cytokinesis follows nuclear division, but the membrane–wall specialisations differ because of turgor and the presence of a cell wall in plants.",
        ],
        commonMistake:
          "Saying plant cells use a cleavage furrow like animal cells, or that animal cells form a cell plate.",
        tags: ["cytokinesis", "plant-animal"],
      },
      {
        id: "t5-2-d5",
        noteId: "t5-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "A photomicrograph shows individual chromosomes clearly condensed and scattered through the nucleus, and the nuclear envelope is not visible as a intact sphere. Which mitotic stage is most likely shown, and what would you look for next to confirm it?",
        modelAnswerPoints: [
          "Likely prometaphase or prophase (condensed chromosomes; envelope breaking down or gone).",
          "Confirm by tracking subsequent alignment: metaphase shows chromosomes on the equatorial plate.",
          "Distinguish from metaphase by absence of a single tight metaphase plate line-up.",
        ],
        workedSolution: [
          "Condensed chromosomes that are not yet aligned in one central row usually indicate early mitosis—prophase as condensation proceeds or prometaphase after the envelope has fragmented and spindle attachments are still being made.",
          "The loss of a continuous nuclear envelope outline fits breakdown during prophase–prometaphase rather than telophase, where envelopes are reforming around separated groups.",
          "To confirm the exact stage I would scan the same field for spindle poles and kinetochore attachment patterns and check whether chromosomes are moving toward a single equatorial plane.",
          "If all chromosomes lie with centromeres on one plane, the image would be interpreted as metaphase; if they remain scattered between poles, it remains prophase/prometaphase rather than metaphase.",
        ],
        commonMistake:
          "Labelling any spread of condensed chromosomes as metaphase without checking for equatorial alignment.",
        tags: ["identification", "microscopy"],
      },
      {
        id: "t5-2-d6",
        noteId: "t5-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "A micrograph shows two distinct groups of chromosomes at opposite poles and faint re-forming nuclei. Identify the stage and explain one key feature that distinguishes it from anaphase.",
        modelAnswerPoints: [
          "Telophase: chromosomes at poles, decondensing, nuclear envelopes reforming.",
          "Anaphase shows V-shaped chromosomes moving toward poles but without reorganised nuclei around each set.",
        ],
        workedSolution: [
          "When two separate clusters of chromosomes are visible at opposite spindle poles and each cluster is becoming enclosed by a new nuclear envelope with chromatin loosening, the cell is in telophase.",
          "Telophase follows anaphase; the key difference from a mid-anaphase image is that segregation is complete and the cell is rebuilding interphase-style nuclei rather than actively pulling sister chromatids apart.",
          "In anaphase you would still see many chromosomes midway between poles or clearly trailing along spindle tracks, whereas telophase emphasises polar grouping and nuclear re-formation.",
        ],
        commonMistake:
          "Calling telophase anaphase because both involve chromosomes near poles; telophase is defined by completion of movement and nuclear reassembly.",
        tags: ["telophase", "identification"],
      },
      {
        id: "t5-2-d7",
        noteId: "t5-2",
        kind: "mcq",
        difficulty: 2,
        stem: "In a standard mitosis diagram, sister chromatids are pulled to opposite poles. This movement is characteristic of:",
        options: [
          { id: "A", text: "Prophase" },
          { id: "B", text: "Metaphase" },
          { id: "C", text: "Anaphase" },
          { id: "D", text: "G2 phase" },
        ],
        correctOptionId: "C",
        explanation:
          "Anaphase is defined by separation of sister chromatids and their movement to opposite spindle poles.",
        distractorRationale: {
          A: "Prophase involves condensation and envelope breakdown, not sister separation.",
          B: "Metaphase aligns chromosomes at the equator; chromatids have not yet separated.",
          D: "G2 is part of interphase before mitosis begins.",
        },
        tags: ["anaphase"],
      },
      {
        id: "t5-2-d8",
        noteId: "t5-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which observation best identifies metaphase in an onion root tip squash?",
        options: [
          { id: "A", text: "Chromosomes are maximally scattered toward one pole only" },
          { id: "B", text: "Chromosomes lie lined up at the cell equator" },
          { id: "C", text: "Two separate nuclei are fully re-formed with no spindle" },
          { id: "D", text: "Homologous pairs form tetrads at the equator" },
        ],
        correctOptionId: "B",
        explanation:
          "Metaphase is recognised by chromosomes aligned at the metaphase plate between poles.",
        distractorRationale: {
          A: "Asymmetric scattering does not describe metaphase alignment.",
          C: "Two complete nuclei without spindles suggest telophase/G1 rather than metaphase.",
          D: "Tetrads of homologues describe meiosis I, not mitotic metaphase.",
        },
        tags: ["metaphase", "identification"],
      },
      {
        id: "t5-2-d9",
        noteId: "t5-2",
        kind: "mcq",
        difficulty: 3,
        stem: "During prophase of mitosis in an animal cell, which change is expected?",
        options: [
          { id: "A", text: "Sister chromatids separate and move to poles" },
          { id: "B", text: "The nuclear envelope breaks down and chromosomes condense" },
          { id: "C", text: "A cell plate forms across the equator" },
          { id: "D", text: "DNA replication begins on unreplicated chromosomes" },
        ],
        correctOptionId: "B",
        explanation:
          "Prophase features chromosome condensation and, in animal mitosis, breakdown of the nuclear envelope (and nucleolus disperses).",
        distractorRationale: {
          A: "Sister separation is anaphase.",
          C: "A cell plate is plant cytokinesis, not prophase.",
          D: "Replication occurs in S phase, not prophase.",
        },
        tags: ["prophase"],
      },
      {
        id: "t5-2-d10",
        noteId: "t5-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Explain how you would use chromosome shape in anaphase to distinguish anaphase from metaphase in a photomicrograph.",
        modelAnswerPoints: [
          "After centromere division each chromatid is a V- or J-shaped chromosome moving poleward.",
          "Metaphase chromosomes are typically X-shaped pairs of sister chromatids lined on the equator.",
          "Anaphase shows doubled chromosome number moving toward poles without a single equatorial plate.",
        ],
        workedSolution: [
          "At metaphase each replicated chromosome still has two sister chromatids joined at a centromere, so under the microscope many appear as X- or rod-shaped structures arranged in one plane at the cell centre.",
          "When anaphase begins, centromeres split so each chromatid becomes an independent chromosome, often showing a clear V shape as the centromere leads toward the pole with trailing chromosome arms.",
          "Therefore anaphase images show two mirror-image streams of daughter chromosomes moving away from the former metaphase plate, whereas metaphase shows stationary alignment without such polar migration.",
        ],
        commonMistake:
          "Relying only on ‘chromosomes visible’—both stages show condensed chromosomes; shape and movement distinguish them.",
        tags: ["identification", "anaphase"],
      },
    ],
    flashcards: [
      {
        id: "t5-2-f1",
        noteId: "t5-2",
        difficulty: 1,
        front: "List the four named stages of mitosis in order.",
        back: "Prophase, metaphase, anaphase, telophase (then cytokinesis completes the cell).",
        examPhrasing: "Name the main stages of mitosis.",
        tags: ["stages"],
      },
      {
        id: "t5-2-f2",
        noteId: "t5-2",
        difficulty: 1,
        front: "What happens to the nuclear envelope during prophase–prometaphase in typical animal mitosis?",
        back: "It breaks down (disassembles) so spindle microtubules can attach to chromosomes.",
        examPhrasing: "Describe nuclear envelope behaviour in mitosis.",
        tags: ["prophase"],
      },
      {
        id: "t5-2-f3",
        noteId: "t5-2",
        difficulty: 2,
        front: "What is the metaphase plate?",
        back: "The equatorial plane where chromosomes align before anaphase.",
        examPhrasing: "Define metaphase plate.",
        tags: ["metaphase"],
      },
      {
        id: "t5-2-f4",
        noteId: "t5-2",
        difficulty: 2,
        front: "One visible cue that anaphase has started.",
        back: "Sister chromatids separate and move to opposite poles (V-shaped chromosomes often visible).",
        examPhrasing: "How would you recognise anaphase?",
        confusionPair: "anaphase vs telophase",
        tags: ["anaphase"],
      },
      {
        id: "t5-2-f5",
        noteId: "t5-2",
        difficulty: 3,
        front: "Telophase vs cytokinesis — quick distinction.",
        back: "Telophase: nuclei reform, chromosomes decondense. Cytokinesis: cytoplasm splits (furrow or cell plate).",
        examPhrasing: "Distinguish telophase and cytokinesis.",
        tags: ["telophase"],
      },
      {
        id: "t5-2-f6",
        noteId: "t5-2",
        difficulty: 3,
        front: "Plant vs animal cytokinesis — one phrase each.",
        back: "Plant: cell plate from vesicles. Animal: cleavage furrow (contractile ring).",
        examPhrasing: "Compare cytokinesis in plant and animal cells.",
        tags: ["cytokinesis"],
      },
      {
        id: "t5-2-f7",
        noteId: "t5-2",
        difficulty: 4,
        front: "Spindle: what is it made of and what is its job?",
        back: "Microtubules (and associated proteins); moves and segregates chromosomes during mitosis.",
        examPhrasing: "Outline the role of the spindle in mitosis.",
        tags: ["spindle"],
      },
      {
        id: "t5-2-f8",
        noteId: "t5-2",
        difficulty: 4,
        front: "Root tip squash: how do you spot metaphase?",
        back: "Chromosomes lined at the equator (metaphase plate), often X-shaped pairs still joined.",
        examPhrasing: "Interpret a photomicrograph of metaphase.",
        tags: ["microscopy"],
      },
      {
        id: "t5-2-f9",
        noteId: "t5-2",
        difficulty: 5,
        front: "Why is prometaphase sometimes hard to separate from prophase on a still image?",
        back: "Both show condensed chromosomes and broken envelope; look for attachment/spindle development vs full equatorial alignment for metaphase.",
        examPhrasing: "Identify mitotic stages from microscope slides.",
        tags: ["identification"],
      },
      {
        id: "t5-2-f10",
        noteId: "t5-2",
        difficulty: 5,
        front: "Exam trap: calling telophase ‘two cells’ before cytokinesis finishes.",
        back: "Telophase can have two nuclei in one cell until cytokinesis completes separation.",
        examPhrasing: "Explain why two nuclei may still share one cytoplasm.",
        tags: ["exam-technique"],
      },
    ],
  },
};
