import type { SubtopicPracticePack } from "./types";

/**
 * Topic 13 (9700 Biology) practice — `data/courses/biology-9700.json` (`t13-1`, `t13-2`).
 *
 * **`t13-1`** — Crosswalk to `data/syllabus/biology-9700-learning-outcomes.md` §13.1 + §13.1 continued:
 * d1 structure–function of chloroplasts + grana vs stroma sites; d2 ATP and reduced NADP from LDR
 * used in the Calvin cycle; d3 pigment roles in thylakoid absorption; d4 absorption vs action spectra;
 * d5 chromatography and Rf; d6 cyclic photophosphorylation (PSI only, ATP); d7 non-cyclic
 * (PSII+PSI, photolysis, ATP + reduced NADP); d8 chemiosmotic coupling in photophosphorylation;
 * d9 Calvin cycle three stages; d10 uses of GP and TP beyond the cycle.
 *
 * **`t13-2`** — Crosswalk to §13.2: d1–d2 limiting factors stated and light intensity effects; d3 CO2;
 * d4 temperature; d5 combined limiting / plateau reasoning; d6 DCPIP + chloroplasts, light intensity;
 * d7 wavelength; d8 methylene blue as alternative indicator; d9 whole aquatic plant method; d10
 * extending to CO2/temperature with whole plants and fair comparison.
 */
export const BIOLOGY_TOPIC13_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t13-1": {
    noteId: "t13-1",
    drills: [
      {
        id: "t13-1-d1",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 1,
        marks: 6,
        stem: "Describe how the structure of a chloroplast, as seen in diagrams and electron micrographs, relates to its function in photosynthesis. State clearly where the light-dependent stage and the light-independent stage occur.",
        modelAnswerPoints: [
          "Double envelope encloses stroma containing enzymes (including for the Calvin cycle) and DNA / ribosomes for some chloroplast proteins.",
          "Thylakoids are membranous sacs; stacked grana increase membrane area for pigment–protein complexes and electron transport.",
          "Thylakoid membranes and thylakoid spaces are the site of the light-dependent reactions.",
          "The stroma is the site of the light-independent (Calvin) stage.",
        ],
        workedSolution: [
          "The chloroplast is bounded by a double envelope whose inner membrane controls metabolite exchange between cytosol and stroma, while the fluid stroma houses soluble enzymes of the Calvin cycle, intermediates, and the machinery for some chloroplast protein synthesis.",
          "Photosynthetic pigments and the photosystems are embedded in the thylakoid membranes, and the narrow thylakoid space accumulates protons during electron transport, which is structurally important for chemiosmotic ATP formation.",
          "Grana are stacks of thylakoids that greatly increase the area of membrane available for light harvesting and for the protein complexes of non-cyclic and cyclic electron flow, so a compact organelle still presents a large functional surface.",
          "Because the light-dependent reactions use pigment excitation, water splitting, and proton pumping at the thylakoids, that membrane system is defined as their site, whereas carbon fixation that consumes ATP and reduced NADP proceeds in the stroma, which is therefore the site of the light-independent stage.",
        ],
        commonMistake:
          "Placing the entire Calvin cycle in the grana or claiming light-dependent reactions occur freely in the stroma without reference to thylakoids.",
        tags: ["chloroplast", "ultrastructure"],
      },
      {
        id: "t13-1-d2",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain how energy transferred as ATP and as reduced NADP during the light-dependent stage is used in the light-independent stage of photosynthesis.",
        modelAnswerPoints: [
          "Reduced NADP supplies reducing power (electrons / hydrogen) for reduction reactions in the Calvin cycle.",
          "ATP supplies phosphate-bond energy for phosphorylation steps, including regeneration of RuBP.",
          "Together they convert carbon dioxide into carbohydrate precursors (triose phosphate) rather than powering photochemistry directly.",
        ],
        workedSolution: [
          "In non-cyclic photophosphorylation the chloroplast generates ATP by chemiosmosis and reduced NADP by transferring electrons ultimately derived from water to NADP+, and these products diffuse into the stroma where the Calvin cycle operates.",
          "Reduced NADP is re-oxidised when glycerate 3-phosphate (GP) is reduced to triose phosphate (TP), which is the step that actually stores chemical energy in three-carbon sugar intermediates using the reducing equivalents from the light stage.",
          "ATP is consumed when GP is reduced and again in the regeneration phase where five-carbon ribulose bisphosphate (RuBP) is rebuilt from triose phosphate so the CO2-acceptor cycle can continue.",
          "Therefore the light-dependent stage does not itself assemble hexoses; it charges up ATP and reduced NADP that chemically drive carbon assimilation in the stroma.",
        ],
        commonMistake:
          "Saying light energy ‘directly’ builds glucose in the stroma without mentioning ATP hydrolysis and oxidation of reduced NADP in Calvin-cycle steps.",
        tags: ["LDR", "Calvin", "ATP", "NADPH"],
      },
      {
        id: "t13-1-d3",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe the role of chloroplast pigments—chlorophyll a, chlorophyll b, carotene and xanthophyll—in light absorption in thylakoids.",
        modelAnswerPoints: [
          "Chlorophyll a is the principal pigment directly involved in photochemistry / primary electron transfer in photosystems.",
          "Chlorophyll b (and other accessory pigments) absorb wavelengths chlorophyll a absorbs less well and pass excitation energy to chlorophyll a.",
          "Carotene and xanthophyll (carotenoids) absorb blue–green region light and protect against photo-oxidative damage as well as feeding energy to chlorophyll.",
        ],
        workedSolution: [
          "Chlorophyll a molecules in photosystem reaction centres undergo photoactivation when they absorb photons, initiating stable charge separation that begins electron transport, so they occupy the central role in turning light into chemical redox change.",
          "Chlorophyll b absorbs somewhat different wavelengths from chlorophyll a and is part of the antenna complexes; its excited state transfers resonance energy efficiently to neighbouring chlorophyll a, broadening the spectrum usable for photosynthesis.",
          "Carotenes and xanthophylls are accessory pigments with absorption bands that partly overlap chlorophylls but extend coverage toward shorter wavelengths; they also dissipate excess excitation energy safely, limiting damage from bright light.",
          "Overall the pigment array in thylakoid membranes increases the fraction of sunlight harvested and delivers excitation to reaction-centre chlorophyll a rather than each pigment operating as an independent photosystem.",
        ],
        commonMistake:
          "Treating all four pigments as interchangeable ‘green chlorophyll’ without distinguishing reaction-centre chlorophyll a from accessory and protective carotenoids.",
        tags: ["pigments", "absorption"],
      },
      {
        id: "t13-1-d4",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Distinguish between an absorption spectrum for a chloroplast pigment and an action spectrum for photosynthesis, and explain how comparing them supports the idea that accessory pigments contribute to photosynthetic rate.",
        modelAnswerPoints: [
          "Absorption spectrum plots relative absorbance (or absorption) against wavelength for a pigment extract.",
          "Action spectrum plots a biological measure of photosynthesis (e.g. oxygen evolution or carbon fixation rate) against wavelength of incident light.",
          "Where the action spectrum peak is broader or shifted relative to chlorophyll a alone, accessory pigments are harvesting additional wavelengths.",
        ],
        workedSolution: [
          "An absorption spectrum is obtained with a spectrophotometer on a solution of isolated pigment and shows which wavelengths are absorbed strongly; chlorophyll extracts typically show peaks in the blue and red with low absorption in the green region.",
          "An action spectrum is derived from living material by illuminating with narrow wavebands and measuring photosynthetic activity, so it links wavelength to physiological performance of the whole photosynthetic apparatus, not just one molecule.",
          "If photosynthesis still proceeds at wavelengths where purified chlorophyll a alone absorbs weakly but carotenoids or chlorophyll b absorb well, the action spectrum does not exactly match the chlorophyll a absorption curve, implying energy transfer from those pigments boosts overall rate.",
          "Thus the comparison is evidence that the thylakoid pigment–protein system acts as a cooperative light-harvesting unit rather than only chlorophyll a working in isolation.",
        ],
        commonMistake:
          "Defining both curves as ‘the same graph of photosynthesis’ or claiming the action spectrum is measured on extracted pigments.",
        tags: ["spectra", "action", "absorption"],
      },
      {
        id: "t13-1-d5",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Describe how chromatography can be used to separate chloroplast pigments and how Rf values help identify them. A solvent front moved 8.4 cm from the baseline and a yellow–orange band moved 6.3 cm from the same baseline—calculate the Rf of that pigment.",
        modelAnswerPoints: [
          "Pigment extract is spotted on baseline on chromatography medium; solvent moves by capillarity carrying pigments at different rates according to solubility / affinity.",
          "Rf = distance moved by pigment spot / distance moved by solvent front from baseline (consistent conditions, same run).",
          "Comparison with known standards or literature Rf values aids identification (with caveat that conditions must match).",
          "Calculation: Rf = 6.3 / 8.4 = 0.75.",
        ],
        workedSolution: [
          "In thin-layer or paper chromatography a small spot of pigment extract is applied above the solvent level; as the developing solvent ascends, each pigment partitions between the stationary phase (paper or silica) and mobile phase according to its relative solubility, producing separated bands.",
          "After the run is stopped near the top, the retention factor Rf is defined as the perpendicular distance travelled by the centre of a pigment band divided by the distance travelled by the solvent front, both measured from the origin line, giving a dimensionless ratio between 0 and 1.",
          "Identifying unknown bands relies on comparing Rf values, colour, and fluorescence under UV with simultaneous runs of standard pigments or tabulated values obtained under closely similar solvent and temperature conditions.",
          "For the figures given, Rf = 6.3 cm ÷ 8.4 cm = 0.75, which would be interpreted alongside the colour as consistent with a carotene-type band only if the solvent system and plate type match the reference data used in teaching.",
        ],
        commonMistake:
          "Using the wrong ratio (solvent divided by pigment), or quoting Rf to many decimal places without stating that identification always depends on controlled, comparable conditions.",
        tags: ["chromatography", "Rf"],
      },
      {
        id: "t13-1-d6",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "State that cyclic and non-cyclic photophosphorylation occur in the light-dependent stage. Explain cyclic photophosphorylation in terms of photosystem involvement, photoactivation of chlorophyll, and the main energy product.",
        modelAnswerPoints: [
          "Both cyclic and non-cyclic photophosphorylation are light-dependent pathways.",
          "In cyclic photophosphorylation only photosystem I (PSI) is used in the cyclic route described at this level.",
          "Chlorophyll in PSI is photoactivated (excited) and electrons eventually return, driving proton pumping / ETC linked to ATP synthesis.",
          "ATP is synthesised; reduced NADP is not the net product of this cyclic path.",
        ],
        workedSolution: [
          "The syllabus expects explicit recognition that chloroplast thylakoids support more than one photophosphorylation pattern: cyclic routes and non-cyclic routes both contribute to the light-dependent metabolism of illuminated leaves.",
          "In cyclic photophosphorylation, light excites chlorophyll associated with photosystem I and electrons from PSI are fed through an electron-transport chain that loops back to the same system rather than reducing NADP+ on a net basis.",
          "Photoactivation means absorption raises chlorophyll to an excited electronic state that can donate an electron to an acceptor, initiating the cyclic flow that releases energy as electrons move through carriers.",
          "That released energy supports proton translocation and therefore chemiosmotic synthesis of ATP, while the pathway does not produce reduced NADP as its characteristic output, distinguishing it from non-cyclic flow.",
        ],
        commonMistake:
          "Claiming cyclic photophosphorylation uses photosystem II first, or that it generates reduced NADP as the main extra product.",
        tags: ["cyclic", "PSI", "ATP"],
      },
      {
        id: "t13-1-d7",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Explain non-cyclic photophosphorylation with reference to photosystems I and II, photoactivation of chlorophyll, the oxygen-evolving complex, and the products ATP and reduced NADP.",
        modelAnswerPoints: [
          "Both PSI and PSII participate in the non-cyclic route.",
          "Chlorophyll in reaction centres is photoactivated to drive electron flow from water to NADP+.",
          "The oxygen-evolving complex on the PSII side catalyses photolysis of water, releasing oxygen, protons, and electrons.",
          "Electron transport and chemiosmosis yield ATP; NADP+ is reduced to reduced NADP.",
        ],
        workedSolution: [
          "Non-cyclic photophosphorylation begins when light excites chlorophyll in photosystem II, causing charge separation that starts a chain of redox reactions ultimately connecting to photosystem I.",
          "Electrons lost from PSII are replaced because the oxygen-evolving complex accumulates oxidising equivalents to split water molecules, releasing molecular oxygen as a by-product, protons into the thylakoid lumen, and electrons that enter the chain—this is the syllabus photolysis requirement.",
          "Light absorbed by PSI re-excites electrons delivered from PSII so they reach a sufficiently negative potential to reduce NADP+ via ferredoxin-NADP+ reductase, producing reduced NADP for the Calvin cycle.",
          "As electrons move between carriers, energy is released that pumps protons into the thylakoid space; their facilitated return through ATP synthase drives ATP formation, so both ATP and reduced NADP are net products of the non-cyclic pathway.",
        ],
        commonMistake:
          "Stating that oxygen comes from carbon dioxide splitting, or omitting the oxygen-evolving complex when explaining PSII’s role.",
        tags: ["non-cyclic", "PSII", "photolysis", "NADPH"],
      },
      {
        id: "t13-1-d8",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Explain how energetic electrons passing through the electron transport chain in photophosphorylation lead to ATP synthesis, including the roles of proton movement across the thylakoid membrane and facilitated diffusion through ATP synthase.",
        modelAnswerPoints: [
          "Electrons moving through carriers release energy used to transport protons from stroma into thylakoid space.",
          "Proton concentration builds in the thylakoid space relative to stroma, storing potential energy in an electrochemical gradient.",
          "Protons diffuse down the gradient through ATP synthase channels (facilitated diffusion), coupling flow to phosphorylation of ADP.",
          "Carrier identities and detailed ATP synthase structure are not required beyond this principle.",
        ],
        workedSolution: [
          "As photoactivated electrons pass along the thylakoid electron-transport chain, their stepwise fall to lower energy levels is coupled to active transport of hydrogen ions from the stroma into the thylakoid compartment, which concentrates protons inside the thylakoid space.",
          "Because the thylakoid membrane is relatively impermeable to protons, this pumping generates a steep proton gradient and a charge separation across the membrane, together forming a proton-motive force that stores the energy originally captured from light.",
          "ATP synthase complexes span the membrane and provide aqueous channels through which protons can move back into the stroma by facilitated diffusion, meaning flow is specific, protein-mediated, and down the electrochemical gradient.",
          "The exergonic flow through ATP synthase drives conformational changes that catalyse ADP + Pi -> ATP, so photophosphorylation links electron-transport exergonic steps to ATP formation without requiring detailed naming of every carrier at this level.",
        ],
        commonMistake:
          "Suggesting protons freely leak through the lipid bilayer without ATP synthase, or that oxygen directly powers ATP synthesis.",
        tags: ["chemiosmosis", "ETC", "ATP-synthase"],
      },
      {
        id: "t13-1-d9",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Outline the three main stages of the Calvin cycle: carbon fixation, reduction of GP to triose phosphate, and regeneration of RuBP. Name the key substrates and enzymes expected at this level.",
        modelAnswerPoints: [
          "Rubisco catalyses fixation: CO2 combines with RuBP (5C) -> two molecules of GP (3C).",
          "GP reduced to triose phosphate using reduced NADP and ATP.",
          "RuBP regenerated from triose phosphate in reactions consuming ATP.",
        ],
        workedSolution: [
          "In carbon fixation, the enzyme ribulose bisphosphate carboxylase / oxygenase (rubisco) catalyses the condensation of one molecule of carbon dioxide with one five-carbon acceptor, ribulose bisphosphate, producing an unstable six-carbon intermediate that immediately splits into two three-carbon molecules of glycerate 3-phosphate (GP).",
          "The reduction phase uses phosphate and energy from ATP together with reducing equivalents from reduced NADP to convert GP to triose phosphate (TP), which is the first sugar-level output that can leave the cycle or be rearranged.",
          "Because every turn of the cycle consumes one RuBP but only one CO2, the cycle must regenerate the five-carbon acceptor: a series of transfers and rearrangements among multiple three-carbon and five-carbon sugar phosphates rebuilds RuBP, and these steps require additional ATP hydrolysis.",
          "Stating the three headline stages—fixation by rubisco, reduction of GP to TP with reduced NADP and ATP, and ATP-consuming regeneration of RuBP from TP—captures the syllabus outline without drawing every intermediate structure.",
        ],
        commonMistake:
          "Claiming one CO2 fixes to one TP directly, or naming glucose as the immediate six-carbon product of the first rubisco step.",
        tags: ["Calvin", "rubisco", "RuBP", "GP", "TP"],
      },
      {
        id: "t13-1-d10",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "State how Calvin cycle intermediates are used to produce other molecules in the plant, limited to GP giving some amino acids and TP giving carbohydrates, lipids and amino acids.",
        modelAnswerPoints: [
          "Some amino acid biosynthetic pathways use GP (or derivatives) as a carbon source.",
          "Triose phosphate feeds synthesis of carbohydrates (e.g. sucrose, starch precursors).",
          "TP also supplies carbon skeletons for lipids and additional amino acids.",
        ],
        workedSolution: [
          "Not all glycerate 3-phosphate continues through the full cycle to carbohydrate storage; some flux is diverted into pathways that aminate or transform three-carbon acids, contributing carbon skeletons for certain amino acids as required by the syllabus limit.",
          "Triose phosphate exported from chloroplasts to the cytosol or used internally can be isomerised and condensed to hexose phosphates, which are on routes to sucrose transport in phloem or to starch granule formation in the stroma.",
          "Acetyl-CoA for fatty acid assembly in the plastid or cytosol can ultimately trace back to photosynthetic carbon entering glycolytic / shunt pathways from sugar phosphates derived from TP, and similar carbon backbones plus nitrogen assimilation support a wider set of amino acids than GP alone.",
          "Thus the Calvin cycle is both a regenerating CO2-fixation engine and a hub that feeds anabolic routes the plant uses for growth and storage.",
        ],
        commonMistake:
          "Asserting that lipids are built only from fatty acids ‘imported’ with no link to photosynthate, or that every amino acid comes solely from GP with no role for TP.",
        tags: ["Calvin", "assimilates"],
      },
    ],
    flashcards: [
      {
        id: "t13-1-f1",
        noteId: "t13-1",
        difficulty: 1,
        front: "Where in the chloroplast do LDR and LIR run?",
        back: "LDR: thylakoid membranes / grana; LIR (Calvin): stroma.",
        examPhrasing: "State the sites of the light-dependent and light-independent stages.",
        tags: ["sites"],
      },
      {
        id: "t13-1-f2",
        noteId: "t13-1",
        difficulty: 1,
        front: "What does the light stage ‘charge up’ for the Calvin cycle?",
        back: "ATP and reduced NADP (NADPH).",
        examPhrasing: "Explain the role of ATP and reduced NADP from photophosphorylation.",
        tags: ["LDR", "NADPH"],
      },
      {
        id: "t13-1-f3",
        noteId: "t13-1",
        difficulty: 2,
        front: "Chlorophyll a vs accessory pigments (one sentence each).",
        back: "Chl a: reaction-centre photochemistry. Accessory (chl b, carotenoids): harvest more wavelengths; transfer or protect.",
        examPhrasing: "Describe roles of chloroplast pigments.",
        tags: ["pigments"],
      },
      {
        id: "t13-1-f4",
        noteId: "t13-1",
        difficulty: 2,
        front: "Absorption spectrum vs action spectrum — core difference.",
        back: "Absorption: pigment extract vs wavelength. Action: photosynthetic rate vs wavelength of illumination.",
        examPhrasing: "Distinguish absorption and action spectra.",
        tags: ["spectra"],
      },
      {
        id: "t13-1-f5",
        noteId: "t13-1",
        difficulty: 2,
        front: "Rf — definition.",
        back: "Distance moved by pigment ÷ distance moved by solvent front (same run, baseline reference).",
        examPhrasing: "Define Rf for a pigment in chromatography.",
        tags: ["Rf"],
      },
      {
        id: "t13-1-f6",
        noteId: "t13-1",
        difficulty: 3,
        front: "Cyclic photophosphorylation — PSI / PSII? Main product?",
        back: "PSI only in the cyclic route; ATP (not net reduced NADP).",
        examPhrasing: "Explain cyclic photophosphorylation.",
        tags: ["cyclic"],
      },
      {
        id: "t13-1-f7",
        noteId: "t13-1",
        difficulty: 3,
        front: "Non-cyclic flow — name the O2 source.",
        back: "Photolysis of water at the oxygen-evolving complex (PSII side); NADP+ reduced after PSI.",
        examPhrasing: "Explain non-cyclic photophosphorylation.",
        tags: ["non-cyclic", "water"],
      },
      {
        id: "t13-1-f8",
        noteId: "t13-1",
        difficulty: 3,
        front: "Chemiosmosis in thylakoids — one-line chain.",
        back: "ETC pumps H+ into thylakoid space; H+ return via ATP synthase -> ATP.",
        examPhrasing: "Explain ATP synthesis in photophosphorylation.",
        tags: ["chemiosmosis"],
      },
      {
        id: "t13-1-f9",
        noteId: "t13-1",
        difficulty: 4,
        front: "Calvin fixation step — substrates and enzyme.",
        back: "Rubisco fixes CO2 to RuBP (5C) -> two GP (3C).",
        examPhrasing: "Outline carbon fixation in the Calvin cycle.",
        tags: ["rubisco"],
      },
      {
        id: "t13-1-f10",
        noteId: "t13-1",
        difficulty: 4,
        front: "Calvin outputs beyond the cycle (syllabus limits).",
        back: "GP -> some amino acids; TP -> carbohydrates, lipids, amino acids.",
        examPhrasing: "State uses of Calvin intermediates.",
        tags: ["assimilates"],
      },
    ],
  },
  "t13-2": {
    noteId: "t13-2",
    drills: [
      {
        id: "t13-2-d1",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "State three abiotic factors that can act as limiting factors of photosynthesis in whole plants, as expected in the syllabus.",
        modelAnswerPoints: [
          "Light intensity.",
          "Carbon dioxide concentration.",
          "Temperature.",
        ],
        workedSolution: [
          "Photosynthetic rate in leaves is commonly limited by how much photosynthetically active radiation reaches chloroplasts, so light intensity is treated as a primary limiting factor.",
          "Because rubisco fixes carbon dioxide, the concentration of CO2 available at the chloroplast—shaped by stomatal conductance and boundary-layer mixing—is another standard limiting factor.",
          "The light-independent stage depends on enzyme-catalysed reactions with temperature-sensitive kinetics, and electron transport also responds to temperature, so temperature is the third named limiting factor at this level.",
        ],
        commonMistake:
          "Listing water availability as one of the three named syllabus examples here, or substituting mineral nutrition without tying it to the board’s stated trio.",
        tags: ["limiting", "definitions"],
      },
      {
        id: "t13-2-d2",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain how increasing light intensity affects the rate of photosynthesis when carbon dioxide concentration and temperature are otherwise favourable, and why the rate eventually stops increasing despite brighter light.",
        modelAnswerPoints: [
          "At low light, rate rises roughly with intensity because more photons drive more photochemistry.",
          "A plateau appears when another factor (often CO2 or temperature/enzymes) becomes limiting or when light saturation of photosystems is reached.",
          "Very high light may cause photoinhibition or damage, reducing rate (acceptable if clearly linked).",
        ],
        workedSolution: [
          "When light is the slowest step, raising intensity increases excitation of photosystems, faster electron transport, and faster provision of ATP and reduced NADP, so carbon fixation can accelerate until downstream biochemistry consumes the products as fast as they arrive.",
          "As intensity rises further, the Calvin cycle enzymes and CO2 supply may be unable to use extra ATP and reduced NADP, so the overall rate becomes limited by the dark reactions or CO2 diffusion rather than photon flux, producing a saturating response curve.",
          "At extremely high irradiance, protective mechanisms and possible photoinhibition can prevent indefinite gains, but the core examination idea is the transition from light-limited to light-saturated regimes controlled by whichever factor is slowest.",
        ],
        commonMistake:
          "Claiming rate increases without limit linearly with light, or confusing light compensation point with saturation.",
        tags: ["light", "limiting"],
      },
      {
        id: "t13-2-d3",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain how a shortage of carbon dioxide in the air surrounding a leaf can limit the rate of photosynthesis even when light is bright.",
        modelAnswerPoints: [
          "Rubisco fixes CO2; lower substrate concentration reduces fixation rate.",
          "Stomata may partially close, increasing diffusion resistance from bulk air to chloroplast.",
          "Photochemical products may accumulate if Calvin cycle slows (feedback acceptable at simple level).",
        ],
        workedSolution: [
          "Carbon dioxide is a direct substrate for the carboxylation reaction catalysed by rubisco; if the partial pressure of CO2 at the active site falls, the probability of successful fixation per unit time drops, so gross photosynthesis slows even though photons are abundant.",
          "Leaves acquire CO2 through stomatal pores; if water stress or other signals cause partial closure, the diffusive pathway from atmosphere to mesophyll lengthens in resistance terms, lowering mesophyll CO2 concentration.",
          "When fixation slows while light reactions still run quickly, the consumption of ATP and reduced NADP may fall out of balance with production, and photorespiration may increase relative to carboxylation at low CO2, both of which are reasons bright light cannot rescue a CO2-limited leaf.",
        ],
        commonMistake:
          "Saying CO2 is ‘only’ a product of respiration needed for photosynthesis, or that CO2 limitation affects only the light-dependent stage.",
        tags: ["CO2", "diffusion"],
      },
      {
        id: "t13-2-d4",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain how changing temperature affects the rate of photosynthesis in a typical C3 leaf, referring to enzyme-controlled steps and an optimal range.",
        modelAnswerPoints: [
          "Calvin-cycle enzymes (e.g. rubisco) have temperature-dependent activity with an optimum.",
          "Below optimum, rate often rises as kinetic energy increases; too high leads to denaturation / decline.",
          "Light reactions also temperature-sensitive but syllabus emphasis commonly on stromal enzymes.",
        ],
        workedSolution: [
          "The Calvin cycle is a sequence of enzyme-catalysed reactions, and like most enzymes rubisco and the kinases / phosphatases involved show maximal catalytic rates near a species-specific temperature optimum where tertiary structure is stable and collision frequency is high.",
          "Below that range, increasing temperature generally increases reaction velocity until the optimum, so photosynthesis accelerates if light and CO2 are not limiting; above the optimum, increasing vibration disrupts hydrogen bonding in active sites and may denature proteins, sharply lowering fixation rate.",
          "Thylakoid electron transport and membrane fluidity also respond to temperature, so gross photosynthesis is a composite, but examination answers correctly stress that temperature limits largely through effects on the stromal carbon-reduction pathway when explaining CO2 uptake curves.",
        ],
        commonMistake:
          "Stating that higher temperature always speeds photosynthesis, with no mention of optimum or high-temperature decline.",
        tags: ["temperature", "enzymes"],
      },
      {
        id: "t13-2-d5",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "A student plots photosynthetic rate against light intensity at two temperatures: 15 °C and 30 °C. At low light the curves almost coincide; at high light the 30 °C curve is higher. Explain what this suggests about limiting factors at different parts of the curve.",
        modelAnswerPoints: [
          "At low light, light intensity is the main limiting factor so temperature has little effect.",
          "At higher light, light is less limiting and enzyme/temperature-dependent steps matter.",
          "30 °C is closer to photosynthetic temperature optimum than 15 °C for this plant (assumption explicit).",
        ],
        workedSolution: [
          "When photon flux is very low, the rate of electron transport and ATP formation is the bottleneck, so both temperatures produce similar low rates because extra thermal energy cannot accelerate photochemistry that is already starved of excitations.",
          "Once light is no longer the slowest step, the Calvin cycle’s capacity—dependent on enzyme kinetics influenced by temperature—determines how quickly NADPH and ATP are consumed; the warmer leaf therefore shows a higher plateau if 30 °C lies nearer the optimum than 15 °C.",
          "This pattern illustrates the principle of limiting factors: the overall rate is set by whichever requirement is in shortest supply, and changing temperature mainly shifts the non-light-limited plateau rather than the initial light-limited slope.",
        ],
        commonMistake:
          "Arguing that temperature should affect the low-light slope equally strongly as the plateau, contradicting light-limited kinetics.",
        tags: ["graphs", "limiting"],
      },
      {
        id: "t13-2-d6",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Describe how an investigation could use DCPIP as a redox indicator with a chloroplast suspension to determine the effect of light intensity on the rate of photosynthesis.",
        modelAnswerPoints: [
          "DCPIP is blue when oxidised; reduced DCPIP becomes colourless—absorbance or time to decolourise can be measured.",
          "Isolated chloroplasts supplied with electron donors / Hill reaction context: DCPIP accepts electrons instead of NADP+ in model Hill assays.",
          "Vary light intensity (lamp distance or neutral density); control temperature, chloroplast concentration, DCPIP concentration.",
          "Repeat and compare initial rate of colour loss / absorbance change.",
        ],
        workedSolution: [
          "DCPIP is an artificial electron acceptor that is dark blue when oxidised and turns colourless when reduced, so in a chloroplast suspension undergoing the Hill reaction it substitutes for NADP+ and its spectral change reports electron flow from water splitting through the photosystems.",
          "A practical arrangement keeps chloroplast concentration, buffer pH, DCPIP concentration, and temperature constant while a bench lamp provides illumination; light intensity is varied in a controlled way, for example by changing lamp distance (recording measured irradiance if possible) or using calibrated neutral filters.",
          "Samples are mixed simultaneously and absorbance at the DCPIP peak wavelength is read over time, or the time for the solution to reach a fixed colour endpoint is recorded; faster bleaching at higher intensity indicates a higher initial rate of photosynthetic electron transport.",
          "Dark controls should show little reduction, confirming the response is light-dependent, and repeats allow mean rates to be compared across intensities to reveal saturation or limiting behaviour.",
        ],
        commonMistake:
          "Describing DCPIP as measuring CO2 uptake directly, or forgetting to control chloroplast or dye concentration when comparing intensities.",
        tags: ["DCPIP", "practical"],
      },
      {
        id: "t13-2-d7",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Outline how the same chloroplast–indicator approach could be adapted to investigate the effect of light wavelength on the rate of photosynthesis, naming one practical way to supply different wavelengths.",
        modelAnswerPoints: [
          "Keep total absorbed power comparable if possible or state limitation that different filters transmit different photon fluxes.",
          "Use coloured filters or narrow-band LEDs to restrict wavelength reaching the suspension.",
          "Measure reduction rate of DCPIP (or methylene blue) as proxy for electron transport rate.",
        ],
        workedSolution: [
          "If chloroplasts and DCPIP concentration are held constant, the independent variable becomes the spectral quality of illumination; coloured gelatin or glass filters can be placed between a white light source and the cuvette so mainly blue, green, or red wavebands arrive, or monochromatic LEDs can be used for sharper bands.",
          "The dependent variable remains the initial rate of indicator reduction monitored spectrophotometrically, which should correlate with how efficiently the pigment complement drives electron transport at each wavelength.",
          "Because filters differ in transmittance and photon irradiance, advanced designs attempt to equalise photosynthetically active photon flux between treatments; at A-level, explicitly noting this limitation and still comparing qualitative trends is acceptable if the method is otherwise fair.",
          "Including a dark control and repeating each wavelength improves confidence that differences arise from absorption properties rather than random timing error.",
        ],
        commonMistake:
          "Claiming green light must always give the highest rate because leaves are green, without linking to action spectra and experimental measurement.",
        tags: ["wavelength", "practical"],
      },
      {
        id: "t13-2-d8",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "State how methylene blue could be used alongside a chloroplast suspension in a similar redox-indicator investigation, and what colour change would indicate reduction.",
        modelAnswerPoints: [
          "Methylene blue is another redox indicator acceptable in the syllabus list.",
          "Oxidised methylene blue is blue; reduced form is colourless (leuco form) in many teaching contexts.",
          "Rate of decolourisation parallels photosynthetic electron flow when the dye accepts electrons.",
        ],
        workedSolution: [
          "Methylene blue can accept electrons from illuminated chloroplasts in appropriately buffered suspensions, playing an analogous role to DCPIP as an artificial Hill oxidant that reports the rate of photosynthetic electron transport.",
          "The oxidised dye imparts a blue colour to the mixture, whereas progressive reduction during illumination bleaches the solution as the leuco product accumulates.",
          "Measuring the initial slope of absorbance decrease or time to a defined endpoint allows comparison across light treatments, provided chloroplast and dye concentrations are standardised like in DCPIP protocols.",
        ],
        commonMistake:
          "Reversing the colour change direction or implying methylene blue measures oxygen evolution quantitatively without an electrode.",
        tags: ["methylene-blue", "practical"],
      },
      {
        id: "t13-2-d9",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Describe how an investigation using an aquatic plant such as pondweed could determine the effect of light intensity on the rate of photosynthesis at constant temperature.",
        modelAnswerPoints: [
          "Measure oxygen evolution (e.g. count bubbles per minute or use calibrated sensor) as dependent variable.",
          "Vary lamp distance or use screens; allow equilibration; maintain CO2 (e.g. hydrogencarbonate).",
          "Control temperature with water bath / room stability; repeat for reliability.",
        ],
        workedSolution: [
          "A common arrangement submerges a cutting of aquatic plant in hydrogencarbonate solution that supplies dissolved carbon dioxide while a light source is placed at measured distances to vary irradiance without changing colour quality if a white lamp is used.",
          "The rate of photosynthesis is inferred from the volume or count of oxygen bubbles released per unit time from the cut stem, or more precisely with a dissolved-oxygen probe in a sealed volume, after the plant has equilibrated at each light level.",
          "Temperature is held steady using a thermostatted water bath around the vessel or by allowing the system to settle between short readings in a climate-controlled room, because temperature changes would confound the light-intensity investigation.",
          "Several runs at each distance, with the plant rested briefly in dim light between extremes, help average biological variability and reveal a trend from light-limited to saturating behaviour.",
        ],
        commonMistake:
          "Changing both lamp distance and water temperature simultaneously, or using tap water with no carbon source so CO2 becomes the hidden limiting factor throughout.",
        tags: ["pondweed", "whole-plant"],
      },
      {
        id: "t13-2-d10",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Compare, at the level of fair testing, how you would extend whole-plant investigations to carbon dioxide concentration and to temperature while keeping other factors as controlled as practicable.",
        modelAnswerPoints: [
          "CO2: vary hydrogencarbonate concentration or controlled gas streams; measure gas exchange / bubble rate; constant light and temperature.",
          "Temperature: water bath at set points; measure rate; constant light and CO2.",
          "Acknowledge interacting limits—very high CO2 useless if light low, etc.",
        ],
        workedSolution: [
          "To test carbon dioxide, aquatic systems use a series of sodium hydrogencarbonate concentrations to set graded dissolved inorganic carbon while a fixed lamp distance delivers constant light and a water bath fixes temperature; bubble rate or oxygen sensor readings supply comparable rates across concentrations.",
          "Terrestrial leaf discs or whole plants in sealed chambers could instead receive air premixed to different CO2 partial pressures, but the syllabus emphasises aquatic macrophytes as accessible models.",
          "For temperature, the same lighting and hydrogencarbonate regime is used while the jacket temperature is stepped—for example 15, 25, and 35 °C—and after thermal equilibration photosynthetic rate is recorded, revealing enzyme-driven optima if light and CO2 are non-limiting.",
          "Good experimental narrative recognises that if light is very low, neither elevated CO2 nor warmer stroma may increase rate much, so pilot checks ensure the plant is actually responsive to the factor being manipulated.",
        ],
        commonMistake:
          "Proposing to change CO2 by ‘blowing on the plant’ without a measurable independent variable, or omitting equilibration time when stepping bath temperature.",
        tags: ["design", "comparison"],
      },
    ],
    flashcards: [
      {
        id: "t13-2-f1",
        noteId: "t13-2",
        difficulty: 1,
        front: "Name three limiting factors of photosynthesis (syllabus list).",
        back: "Light intensity; carbon dioxide concentration; temperature.",
        examPhrasing: "State limiting factors of photosynthesis.",
        tags: ["limiting"],
      },
      {
        id: "t13-2-f2",
        noteId: "t13-2",
        difficulty: 1,
        front: "Low light vs high light — what usually limits rate?",
        back: "Low light: photon flux. High light (often): CO2 or Calvin enzymes / temperature.",
        examPhrasing: "Explain effect of light intensity on photosynthetic rate.",
        tags: ["light"],
      },
      {
        id: "t13-2-f3",
        noteId: "t13-2",
        difficulty: 2,
        front: "Why can bright light fail to raise rate if CO2 is low?",
        back: "Rubisco substrate-limited; Calvin cycle can’t use extra ATP/NADPH; stomata may limit diffusion.",
        examPhrasing: "Explain CO2 as a limiting factor.",
        tags: ["CO2"],
      },
      {
        id: "t13-2-f4",
        noteId: "t13-2",
        difficulty: 2,
        front: "Temperature affects photosynthesis mainly through…",
        back: "Enzyme kinetics in the Calvin cycle (optimum; denaturation at high T).",
        examPhrasing: "Explain temperature effects on photosynthesis.",
        tags: ["temperature"],
      },
      {
        id: "t13-2-f5",
        noteId: "t13-2",
        difficulty: 3,
        front: "Principle of limiting factors — one crisp sentence.",
        back: "At any moment the overall rate is set by the factor present in least favourable supply relative to demand.",
        examPhrasing: "Explain limiting factors using a graph.",
        tags: ["theory"],
      },
      {
        id: "t13-2-f6",
        noteId: "t13-2",
        difficulty: 3,
        front: "DCPIP + chloroplasts — what is measured?",
        back: "Rate of dye reduction (blue -> colourless) as proxy for electron transport / Hill activity.",
        examPhrasing: "Describe DCPIP investigation with chloroplasts.",
        tags: ["DCPIP"],
      },
      {
        id: "t13-2-f7",
        noteId: "t13-2",
        difficulty: 3,
        front: "Vary wavelength fairly — name one method + one control worry.",
        back: "Coloured filters or LEDs; photon flux may differ between colours unless balanced.",
        examPhrasing: "Investigate effect of wavelength on photosynthesis.",
        tags: ["wavelength"],
      },
      {
        id: "t13-2-f8",
        noteId: "t13-2",
        difficulty: 4,
        front: "Methylene blue oxidised vs reduced — colour cue.",
        back: "Oxidised: blue; reduced: colourless (typical teaching observation).",
        examPhrasing: "Describe use of methylene blue with chloroplasts.",
        tags: ["methylene-blue"],
      },
      {
        id: "t13-2-f9",
        noteId: "t13-2",
        difficulty: 4,
        front: "Aquatic plant (pondweed) — common response variable.",
        back: "O2 bubble rate or oxygen sensor reading; hydrogencarbonate supplies CO2.",
        examPhrasing: "Describe investigation with aquatic plant and light intensity.",
        tags: ["practical"],
      },
      {
        id: "t13-2-f10",
        noteId: "t13-2",
        difficulty: 5,
        front: "Chloroplast dye assay vs whole plant — one trade-off.",
        back: "Isolated chloroplasts target photochemistry; whole plant integrates stomata and transport but is messier.",
        examPhrasing: "Compare methods to determine photosynthetic rate.",
        tags: ["methods"],
      },
    ],
  },
};
