import type { SubtopicPracticePack } from "./types";

/**
 * Topic 6 practice — 9700 §6.1–6.2 (incl. 6.2 continued): nucleic acids, DNA replication,
 * RNA/mRNA, genetic code, transcription/translation, introns/exons, gene mutations.
 *
 * Crosswalk (drill id -> syllabus intent, not verbatim):
 * t6-1: d1 nucleotide + ATP; d2 purines/pyrimidines; d3 DNA double helix (antiparallel, pairing,
 *       H-bonds, phosphodiester); d4 semi-conservative + S phase; d5 DNA polymerase + ligase +
 *       leading/lagging (5'->3'); d6 mRNA as RNA example; d7–d10 apply / MCQ.
 * t6-2: d1 gene -> polypeptide; d2 universal code; d3 transcription + translation machinery;
 *       d4 template vs non-transcribed strand; d5 introns/exons; d6 mutation definition;
 *       d7 substitution/insertion/deletion effects; d8–d10 MCQs.
 */
export const BIOLOGY_TOPIC6_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t6-1": {
    noteId: "t6-1",
    drills: [
      {
        id: "t6-1-d1",
        noteId: "t6-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Describe the structure of a nucleotide as expected at A Level, and explain how ATP fits the idea of a phosphorylated nucleotide (detailed structural formulae are not required).",
        modelAnswerPoints: [
          "A nucleotide consists of a nitrogenous base linked to a pentose sugar, with one or more phosphate groups attached to the sugar.",
          "The sugar carries a hydroxyl group that can form phosphodiester linkages when nucleotides polymerise.",
          "ATP is adenosine with three phosphate groups; it acts as an immediate energy currency because hydrolysis of terminal phosphates releases usable energy for cellular work.",
        ],
        workedSolution: [
          "In outline, each nucleotide is built from three chemical parts: a nitrogen-containing base covalently bonded to a five-carbon pentose sugar, and at least one phosphate group esterified to that sugar.",
          "The identity of the base (purine or pyrimidine) and whether the sugar is ribose or deoxyribose distinguishes RNA nucleotides from DNA nucleotides, but the same ‘base–sugar–phosphate’ pattern applies to all nucleotide monomers.",
          "When nucleotides join into a chain, the phosphates form phosphodiester bonds between the 3' position of one sugar and the 5' phosphate of the next, which is why polymer direction is described in 5' to 3' terms.",
          "ATP is the nucleotide adenosine triphosphate: it contains the base adenine, ribose, and a chain of three phosphates; because the bonds between the outer phosphates are relatively unstable, enzyme-catalysed hydrolysis can transfer phosphate groups or release energy that drives anabolic reactions, so ATP exemplifies a highly phosphorylated nucleotide with a metabolic role beyond simply being a building block of RNA.",
        ],
        commonMistake:
          "Treating ATP only as ‘energy’ without stating that it is a nucleotide (adenine + ribose + phosphates), or confusing the phosphate count with the base identity.",
        tags: ["nucleotide", "ATP"],
      },
      {
        id: "t6-1-d2",
        noteId: "t6-1",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "State which bases are purines and which are pyrimidines, and relate this classification to their ring structures (structural formulae for individual bases are not required).",
        modelAnswerPoints: [
          "Adenine and guanine are purines and have a double-ring structure.",
          "Cytosine, thymine (in DNA) and uracil (in RNA) are pyrimidines and have a single-ring structure.",
        ],
        workedSolution: [
          "Purine bases are adenine and guanine; each possesses a fused double ring of carbon and nitrogen atoms, which makes the purine skeleton larger than a single aromatic ring.",
          "Pyrimidine bases are cytosine, thymine in DNA, and uracil in RNA; each is built on a single six-membered ring, so pyrimidines are the smaller class.",
          "This size difference matters when DNA packs into a double helix because complementary pairing always places a purine opposite a pyrimidine, giving a uniform width to the double-stranded molecule.",
        ],
        commonMistake:
          "Listing thymine as a purine or uracil only ‘in DNA’, or claiming all bases share the same ring count.",
        tags: ["bases", "purine", "pyrimidine"],
      },
      {
        id: "t6-1-d3",
        noteId: "t6-1",
        kind: "structured",
        difficulty: 2,
        marks: 7,
        stem: "Describe the structure of a DNA molecule as a double helix, including antiparallel strands and complementary base pairing, differences in hydrogen bonding between C–G and A–T pairs, and how nucleotides are linked in each strand.",
        modelAnswerPoints: [
          "DNA consists of two polynucleotide strands wound as a double helix.",
          "The strands run antiparallel (one 5' to 3', the other 3' to 5') so that complementary bases can hydrogen-bond across the helix.",
          "Adenine pairs with thymine and cytosine pairs with guanine; C–G pairs form three hydrogen bonds and A–T pairs form two.",
          "Within each strand, nucleotides are joined by phosphodiester bonds between the 3' hydroxyl of one sugar and the 5' phosphate of the next.",
        ],
        workedSolution: [
          "DNA is made of two long polynucleotide chains coiled around a common axis to form the familiar double helix, with hydrophobic base stacks in the interior and a sugar–phosphate backbone on the outside.",
          "The two chains are antiparallel: if one strand is orientated 5' to 3' as read along its sugar–phosphate backbone, its partner runs in the opposite 3' to 5' direction, which is required for the geometry of complementary pairing and for enzymes that read a template directionally.",
          "Complementary base pairing means that wherever adenine occurs on one strand, thymine lies opposite it, and wherever cytosine occurs, guanine lies opposite it, so the sequence of one strand predicts the sequence of the other.",
          "Hydrogen bonds stabilise these partnerships, but they are not all identical: a guanine–cytosine pair accommodates three hydrogen bonds, whereas an adenine–thymine pair forms two, so regions rich in G–C pairs are slightly harder to melt apart than A–T-rich regions.",
          "Along each strand, successive nucleotides are condensed by phosphodiester linkages that connect the 3' carbon hydroxyl group of one deoxyribose to the phosphate attached to the 5' carbon of the next deoxyribose, producing a strong covalent backbone with the bases projecting inward toward the helix axis.",
        ],
        commonMistake:
          "Reversing which pair has three hydrogen bonds, or describing strands as parallel; also confusing hydrogen bonds between bases (weak, between strands) with phosphodiester bonds (covalent, within a strand).",
        tags: ["DNA", "double-helix"],
      },
      {
        id: "t6-1-d4",
        noteId: "t6-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain what is meant by semi-conservative replication of DNA and identify when this process occurs in the mitotic cell cycle.",
        modelAnswerPoints: [
          "Each daughter DNA double helix contains one parental strand and one newly synthesised strand.",
          "DNA replication occurs during the S phase of interphase (the synthetic phase before mitosis).",
        ],
        workedSolution: [
          "Semi-conservative replication describes how a parental double helix is duplicated so that each of the two daughter molecules conserves half of the original parental molecule.",
          "After unwinding, each separated parental strand acts as a template for complementary base pairing, so new nucleotides are assembled into a daughter strand alongside each original strand.",
          "When synthesis is complete, every new double helix is hybrid: one strand is inherited unchanged from the parent cell and the partner strand has just been polymerised, which is why the mechanism is called semi-conservative rather than conservative or fully dispersive.",
          "In the mitotic cell cycle this genome copying is scheduled in S phase of interphase, after G1 and before G2, so that by the start of mitosis each chromosome already consists of two sister chromatids containing identical DNA molecules.",
        ],
        commonMistake:
          "Saying both strands in a daughter duplex are newly made, or placing bulk DNA replication in G2 or during mitosis instead of S phase.",
        tags: ["replication", "S-phase"],
      },
      {
        id: "t6-1-d5",
        noteId: "t6-1",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Describe semi-conservative replication of DNA during S phase, including the roles of DNA polymerase and DNA ligase and the difference between leading-strand and lagging-strand synthesis as a consequence of DNA polymerase adding nucleotides only in the 5' to 3' direction.",
        modelAnswerPoints: [
          "DNA polymerase catalyses assembly of a new DNA strand complementary to the template by adding deoxynucleotides in the 5' to 3' direction.",
          "On the leading template (read 3' to 5' toward the fork), one new strand can be synthesised continuously in the 5' to 3' direction moving with the fork.",
          "On the other template the 5' to 3' polymerase must work away from the fork, producing short Okazaki fragments that are later joined.",
          "DNA ligase seals nicks by forming phosphodiester bonds between adjacent fragments, completing the lagging strand.",
        ],
        workedSolution: [
          "During S phase, replisome-associated DNA polymerase enzymes move along each single-stranded template and join activated deoxynucleoside triphosphates into a growing daughter strand, always extending the new chain at its 3' end because the enzyme chemistry only supports 5' to 3' polymerisation.",
          "At a replication fork one template strand is orientated so that its 3' to 5' reading direction points toward the approaching fork; the complementary daughter strand can therefore be elongated continuously in the 5' to 3' direction as the fork opens—this is the leading strand synthesis path.",
          "The opposite template runs 5' to 3' toward the fork, which is the ‘wrong’ orientation for continuous 5' to 3' synthesis on that template, so the same polymerase initiates a series of short backward stretches called Okazaki fragments, each started with help of an RNA primer and each elongated 5' to 3' but overall this is lagging strand synthesis.",
          "After primer removal and gap filling, DNA ligase catalyses formation of the final phosphodiester bond between the 3' hydroxyl at the end of one completed fragment and the 5' phosphate at the start of the next, sealing the backbone so the lagging strand becomes one continuous molecule.",
          "Thus the leading/lagging distinction is not a different enzyme preference for chromosome sides but a direct geometric consequence of antiparallel templates combined with a polymerase that can only elongate DNA in the 5' to 3' direction.",
        ],
        commonMistake:
          "Claiming the lagging strand is synthesised 3' to 5', or that ligase inserts new bases rather than sealing sugar–phosphate breaks between pre-made pieces.",
        tags: ["DNA-polymerase", "ligase", "Okazaki"],
      },
      {
        id: "t6-1-d6",
        noteId: "t6-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Describe the structure of an RNA molecule using messenger RNA (mRNA) as your example.",
        modelAnswerPoints: [
          "RNA is usually single-stranded (mRNA is a linear transcript, not a DNA-style double helix).",
          "mRNA contains ribose and the base uracil instead of thymine.",
          "The sequence of ribonucleotides carries codons that specify the amino-acid order for translation.",
        ],
        workedSolution: [
          "Messenger RNA is a polymer of ribonucleotide monomers linked by phosphodiester bonds in a single strand that folds locally but does not form a permanent double helix like genomic DNA.",
          "Each monomer contributes ribose as its sugar and one of the bases A, U, C or G; the presence of uracil instead of thymine is a quick chemical signature distinguishing RNA from DNA.",
          "Because mRNA is transcribed from a DNA template, its nucleotide sequence is complementary to the template strand of the gene and carries the same coding information as the non-transcribed strand (with U replacing T).",
          "Functionally, mRNA acts as an intermediate that exports the coding sequence from the nucleus to the ribosomes in the cytoplasm (in eukaryotes), where ribosomes read successive non-overlapping triplets called codons to assemble a polypeptide.",
        ],
        commonMistake:
          "Describing mRNA as double-stranded like DNA, or stating that mRNA contains thymine.",
        tags: ["mRNA", "RNA"],
      },
      {
        id: "t6-1-d7",
        noteId: "t6-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement correctly compares the hydrogen bonding in complementary base pairs within DNA?",
        options: [
          { id: "A", text: "An A–T pair is held by three hydrogen bonds and a C–G pair by two" },
          { id: "B", text: "A C–G pair is held by three hydrogen bonds and an A–T pair by two" },
          { id: "C", text: "Both A–T and C–G pairs are held by exactly two hydrogen bonds" },
          { id: "D", text: "Hydrogen bonds link the sugar–phosphate backbones of the two strands" },
        ],
        correctOptionId: "B",
        explanation:
          "Guanine–cytosine pairing involves three hydrogen bonds; adenine–thymine involves two. Backbone linkage is covalent (phosphodiester), not hydrogen bonding between bases across strands.",
        distractorRationale: {
          A: "This reverses the bond counts expected for A–T versus C–G.",
          C: "C–G pairs have an extra hydrogen bond compared with A–T.",
          D: "Backbones are held apart; hydrogen bonds stabilise complementary bases between strands.",
        },
        tags: ["base-pairing"],
      },
      {
        id: "t6-1-d8",
        noteId: "t6-1",
        kind: "mcq",
        difficulty: 2,
        stem: "After one round of replication in a semi-conservative system, what is the composition of each DNA double helix?",
        options: [
          { id: "A", text: "Both strands in every duplex are newly synthesised" },
          { id: "B", text: "Each duplex contains one parental strand and one new strand" },
          { id: "C", text: "Parental strands remain base-paired with each other while new strands pair elsewhere" },
          { id: "D", text: "Each duplex contains only parental DNA with no new synthesis" },
        ],
        correctOptionId: "B",
        explanation:
          "Semi-conservative replication produces hybrid duplexes: one conserved template strand plus one daughter strand per molecule.",
        distractorRationale: {
          A: "That would describe fully conservative replication, not semi-conservative.",
          C: "Parental strands separate and each templates a new partner.",
          D: "New synthesis must occur to duplicate the genome.",
        },
        tags: ["semi-conservative"],
      },
      {
        id: "t6-1-d9",
        noteId: "t6-1",
        kind: "mcq",
        difficulty: 3,
        stem: "On the lagging strand at a replication fork, short Okazaki fragments are later joined into one continuous strand. Which enzyme role matches this joining step?",
        options: [
          { id: "A", text: "DNA ligase sealing phosphodiester bonds between adjacent fragments" },
          { id: "B", text: "DNA polymerase removing introns from the primary transcript" },
          { id: "C", text: "RNA polymerase synthesising the entire lagging strand in one piece" },
          { id: "D", text: "DNA ligase breaking hydrogen bonds between complementary bases" },
        ],
        correctOptionId: "A",
        explanation:
          "DNA ligase joins Okazaki fragments by catalysing phosphodiester bond formation; intron removal is RNA processing, not DNA replication.",
        distractorRationale: {
          B: "Intron splicing is not performed by DNA polymerase during replication.",
          C: "RNA polymerase makes RNA; the lagging strand is still DNA, built in short DNA pieces.",
          D: "Ligase works on the sugar–phosphate backbone, not on base-pair hydrogen bonds.",
        },
        tags: ["ligase"],
      },
      {
        id: "t6-1-d10",
        noteId: "t6-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "A student claims that ‘both new DNA strands must grow toward the replication fork because the fork is where unwinding happens.’ Explain why this is incorrect with reference to 5' to 3' polymerisation.",
        modelAnswerPoints: [
          "DNA polymerase extends strands only by adding to the 3' end (5' to 3' synthesis overall).",
          "Only one template orientation allows continuous synthesis toward the fork (leading strand); the other requires fragment synthesis moving away from the fork (lagging strand).",
        ],
        workedSolution: [
          "Although unwinding exposes single-stranded template at the moving fork, DNA polymerase cannot choose to elongate a daughter strand toward the fork unless the template orientation permits continuous 5' to 3' chain growth on that side.",
          "For the leading strand, the exposed template runs 3' to 5' into the fork, so the new complementary strand can be assembled continuously in the 5' to 3' direction while tracking with fork movement.",
          "For the lagging strand, the useful template runs 5' to 3' into the fork, which forces the polymerase to synthesise short stretches in the opposite direction relative to fork advance, because each fragment must still grow 5' to 3' along its local template segment.",
          "Therefore both daughter strands are made by 5' to 3' polymerisation, but only one appears to ‘follow’ the fork continuously; the other is made in pieces that are retrospectively ligated.",
        ],
        commonMistake:
          "Thinking fork movement defines polymerase direction rather than the antiparallel template and the mandatory 3' extension rule.",
        tags: ["leading-strand", "lagging-strand"],
      },
    ],
    flashcards: [
      {
        id: "t6-1-f1",
        noteId: "t6-1",
        difficulty: 1,
        front: "Name the three components of a nucleotide in outline.",
        back: "Nitrogenous base, pentose sugar, phosphate group (one or more).",
        examPhrasing: "Describe the structure of nucleotides.",
        tags: ["nucleotide"],
      },
      {
        id: "t6-1-f2",
        noteId: "t6-1",
        difficulty: 1,
        front: "Which bases are purines and which are pyrimidines?",
        back: "Purines: adenine, guanine (double ring). Pyrimidines: cytosine, thymine (DNA), uracil (RNA) (single ring).",
        examPhrasing: "State the purine/pyrimidine classification of DNA bases.",
        confusionPair: "purine vs pyrimidine",
        tags: ["bases"],
      },
      {
        id: "t6-1-f3",
        noteId: "t6-1",
        difficulty: 2,
        front: "What does antiparallel mean for DNA strands?",
        back: "One runs 5' to 3' while its partner runs 3' to 5' along the sugar–phosphate backbones.",
        examPhrasing: "Describe complementary strands in the DNA double helix.",
        tags: ["DNA"],
      },
      {
        id: "t6-1-f4",
        noteId: "t6-1",
        difficulty: 2,
        front: "How many hydrogen bonds in A–T vs C–G?",
        back: "A–T: two. C–G: three.",
        examPhrasing: "State differences in hydrogen bonding between base pairs.",
        tags: ["base-pairing"],
      },
      {
        id: "t6-1-f5",
        noteId: "t6-1",
        difficulty: 3,
        front: "What bond links nucleotides along one DNA strand?",
        back: "Phosphodiester bond between 3' OH of one sugar and 5' phosphate of the next.",
        examPhrasing: "Describe how nucleotides are linked in DNA.",
        tags: ["backbone"],
      },
      {
        id: "t6-1-f6",
        noteId: "t6-1",
        difficulty: 3,
        front: "Define semi-conservative DNA replication in one sentence.",
        back: "Each new double helix keeps one parental strand and one newly made strand.",
        examPhrasing: "Describe semi-conservative replication.",
        tags: ["replication"],
      },
      {
        id: "t6-1-f7",
        noteId: "t6-1",
        difficulty: 4,
        front: "Roles of DNA polymerase vs DNA ligase (syllabus level).",
        back: "Polymerase adds nucleotides 5' to 3' on a template. Ligase joins Okazaki fragments / seals backbone nicks.",
        examPhrasing: "State the roles of DNA polymerase and DNA ligase in replication.",
        confusionPair: "polymerase vs ligase",
        tags: ["enzymes"],
      },
      {
        id: "t6-1-f8",
        noteId: "t6-1",
        difficulty: 4,
        front: "Leading vs lagging strand — what causes the difference?",
        back: "Both synthesised 5' to 3', but antiparallel templates mean one is continuous toward the fork and the other is fragment-based away from the fork.",
        examPhrasing: "Explain leading and lagging strand replication.",
        tags: ["replication"],
      },
      {
        id: "t6-1-f9",
        noteId: "t6-1",
        difficulty: 5,
        front: "When does DNA replication occur in the mitotic cell cycle?",
        back: "S phase of interphase.",
        examPhrasing: "State when DNA is replicated in the cell cycle.",
        tags: ["S-phase"],
      },
      {
        id: "t6-1-f10",
        noteId: "t6-1",
        difficulty: 5,
        front: "mRNA: one chemical difference from DNA and one structural difference.",
        back: "Uracil replaces thymine; ribose not deoxyribose. Usually single-stranded carrying codons.",
        examPhrasing: "Describe the structure of mRNA.",
        tags: ["mRNA"],
      },
    ],
  },

  "t6-2": {
    noteId: "t6-2",
    drills: [
      {
        id: "t6-2-d1",
        noteId: "t6-2",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Explain the relationship between a gene, a DNA molecule and the polypeptide whose amino-acid sequence it specifies.",
        modelAnswerPoints: [
          "A polypeptide is coded for by a gene.",
          "A gene is a sequence of nucleotides forming part of a DNA molecule.",
        ],
        workedSolution: [
          "A gene is a defined length of DNA that carries the instructions for making a particular polypeptide (or, in some contexts, a functional RNA), so the linear order of nucleotides in that segment is what ultimately determines the order of amino acids joined in the protein.",
          "Because the gene occupies only part of a much longer DNA molecule—such as a chromosome—the same double helix contains many genes arranged along its length, each with its own start and stop signals read by the expression machinery.",
          "When the gene is expressed, the information encoded in its DNA sequence is transcribed and translated so that ribosomes assemble amino acids into the primary structure of the polypeptide specified by that gene.",
        ],
        commonMistake:
          "Calling the entire chromosome ‘one gene’ or saying a gene is a single nucleotide rather than a sequence.",
        tags: ["gene", "polypeptide"],
      },
      {
        id: "t6-2-d2",
        noteId: "t6-2",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Describe the principle of the universal genetic code in terms of DNA base triplets, amino acids, and start and stop signals.",
        modelAnswerPoints: [
          "The sequence of bases in DNA is read in non-overlapping triplets (codons) that correspond to amino acids.",
          "The code is described as universal because the same codon–amino-acid relationships are used across species, with only minor exceptions at A Level.",
          "Some triplets specify start or stop of translation rather than an amino acid.",
        ],
        workedSolution: [
          "The genetic code is the set of rules that maps nucleotide triplets in the coding DNA (via mRNA codons) to particular amino acids during protein synthesis.",
          "Each codon is three consecutive bases in the mRNA (transcribed from DNA), and the ribosome reads these triplets in a fixed frame to decide which aminoacyl-tRNA to incorporate next.",
          "Most codons specify one of the twenty standard amino acids, so a long open reading frame spells out the primary sequence of a polypeptide.",
          "Particular codons act as punctuation: a start codon initiates translation and stop codons terminate protein elongation without inserting an amino acid, releasing the completed polypeptide.",
          "Calling the code universal reflects the observation that the same codon dictionary is shared by bacteria, archaea and eukaryotes, which is why a human gene can sometimes be translated in a bacterial cell if suitable control sequences are provided.",
        ],
        commonMistake:
          "Saying each base rather than each triplet codes for an amino acid, or omitting start/stop roles.",
        tags: ["genetic-code"],
      },
      {
        id: "t6-2-d3",
        noteId: "t6-2",
        kind: "structured",
        difficulty: 3,
        marks: 9,
        stem: "Describe how the information in DNA is used during transcription and translation to construct a polypeptide, including the roles of RNA polymerase, messenger RNA, codons, transfer RNA, anticodons and ribosomes.",
        modelAnswerPoints: [
          "RNA polymerase synthesises a complementary RNA strand (primary transcript) using a DNA template.",
          "mRNA carries the codon sequence from nucleus to cytoplasm in eukaryotes.",
          "Ribosomes bind mRNA and coordinate translation.",
          "tRNA molecules bring amino acids; each tRNA has an anticodon pairing with a codon.",
          "Peptide bonds form between successive amino acids, elongating the polypeptide.",
        ],
        workedSolution: [
          "Transcription begins when RNA polymerase binds upstream of a gene and separates the DNA duplex locally, then moves along the template strand synthesising a single-stranded RNA molecule complementary to that template, using ribonucleoside triphosphates and following base-pairing rules (with U opposite A on the DNA template).",
          "In eukaryotes the initial RNA is processed (see introns separately) to produce mature mRNA that exits the nucleus through nuclear pores and associates with ribosomes in the cytoplasm.",
          "Each three-base codon on the mRNA specifies which amino acid should be added next; the ribosome has sites that hold the mRNA and two adjacent tRNAs so it can check codon–anticodon pairing.",
          "Transfer RNAs are adaptor molecules: one end carries a specific amino acid attached enzymatically, while the anticodon triplet on the other end can hydrogen-bond to the complementary codon on the mRNA when the tRNA enters the ribosome.",
          "When the ribosome catalyses peptide-bond formation, the growing polypeptide is transferred from the tRNA in the P site to the amino acid carried by the tRNA in the A site, after which the ribosome translocates along the mRNA to read the next codon.",
          "This cycle repeats until a stop codon occupies the A site, at which point release factors prompt hydrolysis of the finished polypeptide from the final tRNA and the subunits dissociate, leaving a linear amino-acid chain folded later into a functional protein.",
        ],
        commonMistake:
          "Saying DNA polymerase makes mRNA, or confusing the roles of rRNA ribosomal structure with tRNA adaptor function.",
        tags: ["transcription", "translation"],
      },
      {
        id: "t6-2-d4",
        noteId: "t6-2",
        kind: "structured",
        difficulty: 2,
        marks: 3,
        stem: "State which DNA strand is described as the transcribed or template strand and what the other strand is called during transcription of a gene.",
        modelAnswerPoints: [
          "The template (transcribed) strand is the one read by RNA polymerase to make RNA.",
          "The non-transcribed strand has the same sequence as the RNA (with T instead of U), apart from complementarity orientation.",
        ],
        workedSolution: [
          "During transcription, RNA polymerase uses one of the two DNA strands as a template, synthesising RNA that is complementary to that strand; this strand is therefore called the transcribed strand or template strand.",
          "The partner strand is not copied directly and is referred to as the non-transcribed strand; because base pairing is complementary, its sequence (read in the appropriate direction) matches the mRNA sequence with thymine in place of uracil, which is why it is sometimes called the coding strand in textbooks.",
        ],
        commonMistake:
          "Labelling the wrong strand as template, or claiming both strands are copied into the same mRNA simultaneously.",
        tags: ["template-strand"],
      },
      {
        id: "t6-2-d5",
        noteId: "t6-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain how primary transcripts are modified in eukaryotes to produce messenger RNA that can be translated, with reference to introns and exons.",
        modelAnswerPoints: [
          "The primary transcript contains non-coding introns and coding exons.",
          "Introns are removed and exons are spliced together to form mature mRNA.",
        ],
        workedSolution: [
          "In eukaryotic nuclei, RNA polymerase produces a primary transcript that corresponds to the whole transcription unit, including stretches that will not be translated.",
          "Non-coding intervening sequences are called introns, while exons are the coding segments that will appear in the finished message.",
          "Splicing removes introns from the primary RNA and ligates exons in the correct order, producing a continuous coding sequence on the mature mRNA exported to the cytoplasm.",
          "This processing means the mature mRNA is typically shorter than the primary transcript and can encode a single open reading frame for translation even though the genomic DNA contained gaps corresponding to introns.",
        ],
        commonMistake:
          "Saying introns are removed from DNA rather than from the RNA transcript, or that exons are discarded.",
        tags: ["introns", "exons"],
      },
      {
        id: "t6-2-d6",
        noteId: "t6-2",
        kind: "structured",
        difficulty: 2,
        marks: 3,
        stem: "State what is meant by a gene mutation and what kind of molecular change it refers to.",
        modelAnswerPoints: [
          "A gene mutation is a change in the sequence of base pairs in DNA.",
          "It may result in an altered polypeptide if coding sequence or splicing signals are affected.",
        ],
        workedSolution: [
          "A gene mutation is an inherited or newly arisen alteration to the nucleotide sequence of a gene, meaning the order of base pairs in that stretch of DNA is not identical to the parental sequence.",
          "Because the gene sequence encodes RNA and protein products, a mutation can change a codon, introduce a premature stop, shift the reading frame, or disrupt regulatory elements, any of which may yield a polypeptide with changed amino acids or abnormal length.",
        ],
        commonMistake:
          "Defining mutation only as a visible phenotype change without mentioning DNA sequence, or confusing it with whole-chromosome aneuploidy.",
        tags: ["mutation"],
      },
      {
        id: "t6-2-d7",
        noteId: "t6-2",
        kind: "structured",
        difficulty: 4,
        marks: 8,
        stem: "Explain that gene mutations arise by substitution, deletion or insertion of nucleotides in DNA, and outline how each type may affect the polypeptide produced.",
        modelAnswerPoints: [
          "Substitution replaces one base pair; may change one codon to another (missense), create a stop (nonsense), or be silent if the new codon still specifies the same amino acid.",
          "Insertion/deletion may cause a frameshift, altering many downstream codons and often introducing premature stops.",
          "Insertion/deletion of three bases may add/remove one amino acid without frameshift.",
        ],
        workedSolution: [
          "A substitution mutation exchanges one nucleotide for another; if this falls inside a coding exon, the corresponding codon may specify a different amino acid, producing a missense change that could affect folding or activity.",
          "If the new codon is a stop codon, translation terminates early and a truncated, often non-functional polypeptide results; conversely, some substitutions are silent at the protein level because the genetic code is degenerate and the altered codon still translates to the same amino acid.",
          "Insertions and deletions add or remove one or more base pairs; when the number added or removed is not a multiple of three, the ribosomal reading frame shifts from the site of the mutation onward, so many subsequent amino acids are wrong and a premature stop is frequently encountered, usually producing a severely defective protein.",
          "When exactly three bases are inserted or deleted in-frame, a single extra or missing amino acid may be incorporated without shifting the whole frame, which can be milder though still potentially disruptive if the residue lies in an active site.",
          "Mutations in splice sites or non-coding regulatory regions can also change the polypeptide indirectly by altering exon inclusion or transcript abundance, even though the coding triplets themselves are not simple substitutions in an exon.",
        ],
        commonMistake:
          "Claiming every substitution changes the protein, or forgetting that indels of multiples of three are not frameshifts.",
        tags: ["mutation", "frameshift"],
      },
      {
        id: "t6-2-d8",
        noteId: "t6-2",
        kind: "mcq",
        difficulty: 2,
        stem: "In the standard genetic code, what is the usual role of the codon AUG on mRNA?",
        options: [
          { id: "A", text: "It always acts only as a stop signal" },
          { id: "B", text: "It codes for methionine and commonly serves as the start codon for translation" },
          { id: "C", text: "It specifies uracil incorporation into the growing polypeptide" },
          { id: "D", text: "It signals DNA ligase to join Okazaki fragments" },
        ],
        correctOptionId: "B",
        explanation:
          "AUG codes for methionine (eukaryotes use it as the main start codon). Stop codons are different triplets; DNA ligase is unrelated.",
        distractorRationale: {
          A: "Stop codons are typically UAA, UAG, UGA — not AUG.",
          C: "Amino acids, not bases, are added during translation; uracil is an RNA base.",
          D: "Okazaki joining is DNA replication, not translation.",
        },
        tags: ["genetic-code"],
      },
      {
        id: "t6-2-d9",
        noteId: "t6-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which statement best describes why mature eukaryotic mRNA is usually shorter than the primary RNA transcript from the same gene?",
        options: [
          { id: "A", text: "Because intron sequences are removed and exons are spliced together" },
          { id: "B", text: "Because DNA polymerase deletes exons during replication" },
          { id: "C", text: "Because ribosomes chop the RNA into amino acids" },
          { id: "D", text: "Because each codon is removed after one use" },
        ],
        correctOptionId: "A",
        explanation:
          "RNA splicing removes introns from the primary transcript, producing shorter mature mRNA.",
        distractorRationale: {
          B: "Replication copies DNA; it does not splice RNA.",
          C: "Ribosomes translate mRNA into polypeptides; they do not degrade the whole message into amino acids.",
          D: "Codons are read repeatedly until the mRNA is degraded; they are not consumed one-by-one off the message.",
        },
        tags: ["splicing"],
      },
      {
        id: "t6-2-d10",
        noteId: "t6-2",
        kind: "mcq",
        difficulty: 4,
        stem: "A single nucleotide deletion occurs in the coding region of a gene, not in a multiple of three. Which outcome is most likely?",
        options: [
          { id: "A", text: "Only the first amino acid of the protein changes" },
          { id: "B", text: "A frameshift alters the downstream reading frame, changing many amino acids" },
          { id: "C", text: "The polypeptide lengthens by exactly one amino acid with no other changes" },
          { id: "D", text: "The mutation must be silent because the code is universal" },
        ],
        correctOptionId: "B",
        explanation:
          "Indels not divisible by three shift the triplet frame, scrambling codons downstream.",
        distractorRationale: {
          A: "Downstream not only the first residue is affected once the frame shifts.",
          C: "Adding one amino acid without frame change requires an in-frame three-base insertion, not a single deletion.",
          D: "Universality does not prevent frameshifts from being highly disruptive.",
        },
        tags: ["frameshift"],
      },
    ],
    flashcards: [
      {
        id: "t6-2-f1",
        noteId: "t6-2",
        difficulty: 1,
        front: "Define a gene in relation to DNA.",
        back: "A sequence of nucleotides forming part of a DNA molecule that codes for a polypeptide (or functional RNA).",
        examPhrasing: "State what is meant by a gene.",
        tags: ["gene"],
      },
      {
        id: "t6-2-f2",
        noteId: "t6-2",
        difficulty: 1,
        front: "What is a codon?",
        back: "A triplet of bases on mRNA that specifies an amino acid or start/stop during translation.",
        examPhrasing: "Define codon.",
        tags: ["genetic-code"],
      },
      {
        id: "t6-2-f3",
        noteId: "t6-2",
        difficulty: 2,
        front: "What does ‘universal genetic code’ mean at A Level?",
        back: "Same codon–amino-acid assignments are shared across species (with rare exceptions).",
        examPhrasing: "Describe the universal genetic code.",
        tags: ["genetic-code"],
      },
      {
        id: "t6-2-f4",
        noteId: "t6-2",
        difficulty: 2,
        front: "RNA polymerase — one sentence role.",
        back: "Makes RNA using a DNA template strand during transcription.",
        examPhrasing: "State the role of RNA polymerase.",
        confusionPair: "RNA polymerase vs DNA polymerase",
        tags: ["transcription"],
      },
      {
        id: "t6-2-f5",
        noteId: "t6-2",
        difficulty: 3,
        front: "Anticodon — where is it and what does it do?",
        back: "On tRNA; base-pairs with the complementary mRNA codon in the ribosome.",
        examPhrasing: "Define anticodon.",
        tags: ["tRNA"],
      },
      {
        id: "t6-2-f6",
        noteId: "t6-2",
        difficulty: 3,
        front: "Template strand vs non-transcribed strand — quick contrast.",
        back: "Template: read 3' to 5' by RNA polymerase to build complementary RNA. Non-transcribed: same sequence as RNA (T for U).",
        examPhrasing: "State which strand is transcribed.",
        tags: ["transcription"],
      },
      {
        id: "t6-2-f7",
        noteId: "t6-2",
        difficulty: 4,
        front: "Introns vs exons.",
        back: "Introns: non-coding RNA removed in processing. Exons: coding segments spliced into mature mRNA.",
        examPhrasing: "Explain intron removal and exon joining.",
        confusionPair: "intron vs exon",
        tags: ["splicing"],
      },
      {
        id: "t6-2-f8",
        noteId: "t6-2",
        difficulty: 4,
        front: "Ribosome role in translation.",
        back: "Binds mRNA; positions tRNAs; catalyses peptide-bond formation between amino acids.",
        examPhrasing: "Describe the role of ribosomes in protein synthesis.",
        tags: ["translation"],
      },
      {
        id: "t6-2-f9",
        noteId: "t6-2",
        difficulty: 5,
        front: "Substitution that changes one amino acid — name of effect.",
        back: "Missense mutation (if the new codon codes for a different amino acid).",
        examPhrasing: "Outline effects of substitution mutations.",
        tags: ["mutation"],
      },
      {
        id: "t6-2-f10",
        noteId: "t6-2",
        difficulty: 5,
        front: "Single-base insertion not a multiple of three — main risk.",
        back: "Frameshift: alters every downstream codon; often premature stop and non-functional protein.",
        examPhrasing: "Explain how insertion mutations may affect the polypeptide.",
        tags: ["frameshift"],
      },
    ],
  },
};
