import type { SubtopicPracticePack } from "./types";

/**
 * Topic 16 (9700 Biology) practice — `data/courses/biology-9700.json` (`t16-1` … `t16-3`).
 *
 * **`t16-1` (16.1 Passage of information from parents to offspring)** — Crosswalk to
 * `data/syllabus/biology-9700-learning-outcomes.md` §16.1:
 * d1 haploid / diploid; d2 homologous pairs; d3 need for reduction division;
 * d4 meiosis stages + nuclear envelope / membrane / spindle behaviour;
 * d5 interpret meiosis diagrams / micrographs; d6 crossing over; d7 independent assortment;
 * d8 random fertilisation; d9 MCQ (variation from meiosis); d10 consolidate MI vs MII / diagram reasoning.
 *
 * **`t16-2` (16.2 The roles of genes in determining the phenotype + continued)** — §16.2 + continued:
 * d1 core genetics terms; d2 monohybrid Punnett / genetic diagram; d3 dihybrid;
 * d4 codominance / multiple alleles; d5 sex linkage; d6 interpret examination genetic diagram (linked test cross);
 * d7 epistasis (interpret ratios from a diagram); d8 test cross;
 * d9 chi-squared reasoning on observed vs expected; d10 gene–protein–phenotype (TYR, HBB, F8, HTT) + Le/le gibberellin.
 *
 * **`t16-3` (16.3 Gene control)** — §16.3:
 * d1 structural vs regulatory genes; inducible vs repressible enzymes;
 * d2 lac operon (no cAMP); d3 lac operon MCQ; d4 transcription factors (eukaryotes);
 * d5 gibberellin, DELLA breakdown; d6 compare operon vs TF control; d7 MCQ (regulation);
 * d8 lac repressor / operator logic; d9 DELLA application; d10 repressible vs inducible MCQ.
 */
export const BIOLOGY_TOPIC16_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t16-1": {
    noteId: "t16-1",
    drills: [
      {
        id: "t16-1-d1",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Explain what is meant by a haploid number (n) and a diploid number (2n) in eukaryotes, and relate each to the chromosome complement of typical body cells and of gametes produced by meiosis.",
        modelAnswerPoints: [
          "Haploid (n): one complete set of chromosomes per nucleus (one of each kind in a simple picture); characteristic of mature gametes after meiosis.",
          "Diploid (2n): two sets per nucleus (homologous pairs in somatic cells), one set originally from each parent at fertilisation.",
          "Meiosis halves chromosome number so fusion of two gametes restores the species’ diploid complement in the zygote.",
        ],
        workedSolution: [
          "The haploid number, written n, is the number of chromosomes in a single complete set for the species, so each chromosome type is represented once in the nucleus; in animals this is the chromosome complement found in mature sperm and egg cells after meiosis has finished, because meiosis is the reduction division that separates homologous pairs so each gamete carries only one chromosome from each pair.",
          "The diploid number, 2n, is twice n and corresponds to two full sets in the same nucleus, which in most somatic cells of the organism means every chromosome type is present as a homologous pair—one homologue inherited from the maternal gamete and one from the paternal gamete at fertilisation—so genetic material from both parents is present in parallel in each body cell ready for mitosis and development.",
          "Meiosis is needed precisely because fusion at fertilisation adds the haploid sets from two gametes: if gametes were diploid, chromosome number would double every generation, whereas producing haploid gametes keeps the species’ characteristic 2n constant across generations when two n gametes unite.",
        ],
        commonMistake:
          "Defining n as ‘half the DNA’ without tying it to sets of chromosomes, or claiming all cells in the body are diploid without excepting gametes (and noting odd cases only when the question allows).",
        tags: ["haploid", "diploid"],
      },
      {
        id: "t16-1-d2",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Explain what is meant by homologous pairs of chromosomes, and state how members of a pair resemble each other and how they can differ at the level of DNA sequence.",
        modelAnswerPoints: [
          "A homologous pair: two chromosomes of the same type / length / centromere position (same loci in the same order).",
          "One homologue from each parent (maternal and paternal origin) in a diploid somatic cell.",
          "Same genes at corresponding loci but may carry different alleles (different base sequence).",
        ],
        workedSolution: [
          "In a diploid nucleus immediately before meiosis or during mitosis, a homologous pair consists of two chromosomes that match in overall morphology—length, centromere position, and the linear order of genetic loci—so cytogeneticists can pair them up in karyotypes even before knowing exact sequences.",
          "One member of the pair is the maternal homologue, descended by replication and cell division from the zygote’s maternal chromosome set, and the other is the paternal homologue from the paternal set, which is why the pair embodies the dual inheritance from two parents while still being ‘the same chromosome type’ in genetic terms.",
          "Because the loci align, the pair carries the same genes, but the alleles at many of those loci can differ between homologues—one might code for a functional enzyme and the other for a non-functional variant—so homology is about structural and gene map correspondence, not identity of allele sequence.",
        ],
        commonMistake:
          "Calling sister chromatids ‘homologous’ (they are identical copies after S phase) or saying homologues must have identical DNA.",
        tags: ["homologous", "chromosomes"],
      },
      {
        id: "t16-1-d3",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain why a reduction division is needed during meiosis in the production of gametes, with reference to fertilisation and the maintenance of a stable chromosome number between generations.",
        modelAnswerPoints: [
          "Fertilisation fuses two gametes, each contributing a haploid nucleus.",
          "If gametes were diploid, chromosome number would double each generation (geometric increase).",
          "Meiosis halves chromosome number so the zygote is diploid (species-typical 2n) after fusion.",
        ],
        workedSolution: [
          "Sexual reproduction combines two parental genomes when the haploid sperm and haploid egg fuse, so the first cell of the new individual receives one complete set from each parent; that fusion is only numerically stable if each gamete contributes a single set rather than two.",
          "If meiosis did not halve the chromosome number, a diploid germ cell that underwent only mitosis-like divisions would produce diploid gametes, and their fusion would create a 4n zygote in one generation, then 8n in the next, which is incompatible with the conserved chromosome numbers seen in species karyotypes and would disrupt gene balance and segregation machinery evolved for a particular 2n.",
          "Meiosis therefore acts as the reduction division: one round of chromosome replication is followed by two nuclear divisions that separate homologues and then sister chromatids, yielding four haploid products from one diploid precursor in spermatogenesis (or one functional egg plus polar bodies in oogenesis in many animals), restoring the arithmetic that keeps 2n constant when two n gametes meet at fertilisation.",
        ],
        commonMistake:
          "Saying meiosis ‘reduces DNA’ vaguely without linking to sets of chromosomes and fertilisation, or confusing meiosis with mitosis as the division that maintains n in the life cycle.",
        tags: ["meiosis", "fertilisation"],
      },
      {
        id: "t16-1-d4",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 3,
        marks: 9,
        stem: "Describe the behaviour of chromosomes during meiosis in animal cells, naming the main stages (prophase I, metaphase I, anaphase I, telophase I, prophase II, metaphase II, anaphase II, telophase II) and outlining what happens to the nuclear envelope, the spindle and the cell surface membrane across the process at the level expected in an outline answer.",
        modelAnswerPoints: [
          "Prophase I: homologous chromosomes pair; crossing over; nuclear envelope breaks down; spindle forms.",
          "Metaphase I: bivalents on equator; spindle attaches to kinetochores; independent assortment orientation.",
          "Anaphase I: homologous chromosomes pulled to opposite poles; sister chromatids still paired.",
          "Telophase I: chromosomes may decondense partly; nuclear envelopes may reform; cytokinesis → two haploid cells (each chromosome still duplicated).",
          "Prophase II / metaphase II / anaphase II / telophase II: chromosomes line up singly at equator in II; sister chromatids separated; four haploid nuclei; cytokinesis completes.",
          "Plasma membrane: pinches or forms cleavage furrow in animal cytokinesis between divisions and after telophase II.",
        ],
        workedSolution: [
          "In prophase I, replicated chromosomes condense and homologous chromosomes synapse, allowing crossing over at chiasmata, while in animal cells the nuclear envelope disassembles and the microtubule spindle organised by centrosomes begins to occupy the former nuclear area, nucleating from poles toward the metaphase plate region.",
          "At metaphase I, bivalents—each consisting of four chromatids—align on the spindle equator, and kinetochore microtubules from opposite poles attach to homologous kinetochores so the random facing of each bivalent implements independent assortment of whole homologous pairs when segregation occurs.",
          "Anaphase I is the reduction step: cohesin release between homologues allows spindle forces to pull one entire duplicated chromosome to each pole while sister chromatids remain attached at their centromeres, so each daughter nucleus is haploid in terms of chromosome number but each chromosome still has two chromatids.",
          "Telophase I and cytokinesis divide the cell into two, often with partial nuclear envelope reformation and a furrow of actomyosin contracting the animal cell surface membrane to pinch cytoplasm, producing two cells that enter a brief interkinesis without DNA replication before meiosis II.",
          "Meiosis II resembles mitosis: prophase II sees chromosomes condense again if they had relaxed, metaphase II lines up individual duplicated chromosomes on the equator, anaphase II separates sister chromatids to opposite poles as the centromeres divide, and telophase II packages four haploid nuclei, each now with unduplicated chromosomes, with a second round of cytokinesis completing four genetically distinct gametes in the male pattern, while membrane behaviour again follows the standard contractile ring model in many animal cells.",
        ],
        commonMistake:
          "Stating that sister chromatids separate in anaphase I, or omitting nuclear envelope breakdown/spindle roles entirely when the question names them.",
        tags: ["meiosis", "stages"],
      },
      {
        id: "t16-1-d5",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "A photomicrograph of plant meiosis shows a cell in which pairs of homologous chromosomes lie on the equatorial plane of the spindle, each pair consisting of four chromatids with visible chiasmata. A second image shows chromosomes moving toward opposite poles, but each migrating chromosome still has two chromatids. Identify the main meiotic stages shown and justify your identification from the chromosome arrangements.",
        modelAnswerPoints: [
          "First image: metaphase I — bivalents (tetrads) on metaphase plate; chiasmata indicate prophase I crossing over already occurred.",
          "Second image: anaphase I — homologous chromosomes separate; sister chromatids still attached (V-shaped chromosomes).",
          "Contrast: not metaphase II (single-file duplicated chromosomes) or anaphase II (chromatids separating).",
        ],
        workedSolution: [
          "The first cell is in metaphase I because replicated homologous chromosomes are paired into bivalents—each visible as a four-chromatid unit—and the whole bivalents are aligned on the spindle equator rather than individual duplicated chromosomes lining up independently as they would in metaphase II.",
          "The presence of chiasmata, where non-sister chromatids crossed over in prophase I, is consistent with homologous pairing that has persisted into this congression stage, which is a hallmark of late prophase I through metaphase I in textbook micrographs.",
          "The second cell is in anaphase I because whole homologues are moving to opposite poles while each migrating structure still clearly contains two sister chromatids joined at a centromere, producing the classic ‘V’ shapes of anaphase I chromosomes; if this were anaphase II, we would instead see separation of sister chromatids toward poles after a metaphase II alignment of single duplicated chromosomes.",
        ],
        commonMistake:
          "Labelling any anaphase with two chromatids per chromosome as anaphase II, or missing that bivalents on one plate define metaphase I.",
        tags: ["micrograph", "meiosis"],
      },
      {
        id: "t16-1-d6",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain how crossing over between non-sister chromatids of a homologous pair during meiosis contributes to genetically different gametes, and state at which main stage this occurs.",
        modelAnswerPoints: [
          "Occurs in prophase I (during synapsis of homologues).",
          "Exchange of corresponding segments between non-sister chromatids → recombinant chromatids.",
          "New allele combinations on the same chromosome, different from parental chromosome arrangements.",
        ],
        workedSolution: [
          "In prophase I, when homologous chromosomes are synapsed as a bivalent, enzyme-mediated breakage and rejoining can swap corresponding segments between one maternal and one paternal chromatid that are not sisters, producing recombinant chromatids carrying alleles that were formerly on different parental chromosomes.",
          "Because each gamete receives only one chromatid from the four available in the bivalent after meiosis I and II, the orientation of crossovers means some gametes inherit chromosomes with novel linkage groups—combinations of alleles along the chromosome—that neither parent’s intact chromosome possessed, increasing allelic assortment beyond independent assortment of whole chromosomes alone.",
          "Even a single crossover per bivalent can create two recombinant and two non-recombinant chromatids among the four, so when the cell completes meiosis the pool of gametes carries both parental-type and recombinant chromosomes, enlarging genetic variation in the next generation.",
        ],
        commonMistake:
          "Placing crossing over in metaphase I or claiming sister chromatids normally cross over with each other as the syllabus mechanism.",
        tags: ["crossing-over", "variation"],
      },
      {
        id: "t16-1-d7",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain how the random orientation of homologous pairs at metaphase I and the subsequent separation of sister chromatids at anaphase II together increase the variety of allelic combinations in gametes.",
        modelAnswerPoints: [
          "Metaphase I: each bivalent orients independently on the spindle → maternal/paternal homologues assort independently (for genes on different chromosomes).",
          "2^n possible gamete combinations for chromosome assortment alone (n haploid number).",
          "Anaphase II: which chromatid (post-crossover) enters each gamete adds further combination diversity.",
        ],
        workedSolution: [
          "At metaphase I, the side of the spindle to which the maternal homologue of one chromosome type faces is independent of the facing of the maternal homologue of another type, so for unlinked genes on different chromosomes every meiosis can produce gametes with different mixtures of whole parental chromosomes, up to 2^n combinations for n chromosome pairs in the absence of other constraints.",
          "This independent assortment shuffles entire chromosomes that may already carry different alleles at many loci, so a single individual heterozygous at multiple unlinked genes can generate gametes with many genotypes without any crossing over.",
          "After meiosis I, each duplicated chromosome still consists of two chromatids that may be recombinant or non-recombinant; meiosis II separates those chromatids, so which final DNA molecule enters which gamete adds another layer of combinatorial variation on top of the metaphase I orientation, especially when crossing over has made the two chromatids of a chromosome genetically non-identical.",
        ],
        commonMistake:
          "Saying independent assortment applies to sister chromatids at metaphase I, or confusing segregation of homologues (MI) with segregation of chromatids (MII).",
        tags: ["assortment", "meiosis"],
      },
      {
        id: "t16-1-d8",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain how random fusion of gametes at fertilisation produces genetically different individuals, even when the same two parents produce many offspring.",
        modelAnswerPoints: [
          "Many genetically different gametes from each parent (crossing over, assortment, random alignment).",
          "Which sperm fuses with which egg is chance → many zygote genotype combinations.",
          "Siblings can differ unless identical twins from one zygote.",
        ],
        workedSolution: [
          "Each parent’s germ line, through meiosis, produces large numbers of gametes that differ in chromosome combinations and, at loci heterozygous in the parent, in which alleles are packaged together, so the pool of eggs and the pool of sperm are genetically diverse even before fertilisation.",
          "Fertilisation pairs one sperm with one egg largely at random in outcrossing species, multiplying the parental gametic diversity: a given maternal chromosome complement meeting a given paternal complement is one of many possible unions, so the diploid genotype of each offspring is a fresh shuffle.",
          "Consequently full siblings are not genetically identical except in the special case of monozygotic twins derived from one zygote; otherwise they inherit different mixtures of parental alleles, which is the syllabus point that fertilisation’s randomness creates individual variation at the zygote stage.",
        ],
        commonMistake:
          "Claiming fertilisation itself recombines DNA segments like crossing over, rather than combining whole haploid genomes.",
        tags: ["fertilisation", "variation"],
      },
      {
        id: "t16-1-d9",
        noteId: "t16-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best explains why meiosis increases genetic variation between gametes compared with mitosis from the same diploid precursor cell?",
        options: [
          { id: "A", text: "Meiosis duplicates DNA twice so mutations occur more often." },
          { id: "B", text: "Crossing over, independent assortment of homologues, and separation of recombinant chromatids create new allele combinations in gametes." },
          { id: "C", text: "Meiosis removes introns from chromosomes before gametes form." },
          { id: "D", text: "Mitosis cannot separate sister chromatids, so it never changes allele combinations." },
        ],
        correctOptionId: "B",
        explanation:
          "Meiosis I and II, with crossing over and random orientation of bivalents, reshuffles alleles among gametes; mitosis produces genetically identical daughter cells (barring mutation) in standard teaching.",
        distractorRationale: {
          A: "DNA replicates once before meiosis; there is not a second full S phase between meiosis I and II.",
          C: "RNA splicing removes introns from pre-mRNA; meiosis does not strip introns from chromosomal DNA in this way.",
          D: "Anaphase of mitosis separates sister chromatids; mitosis preserves the cell’s genotype in daughter cells.",
        },
        tags: ["variation", "mcq"],
      },
      {
        id: "t16-1-d10",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Contrast anaphase I and anaphase II in meiosis with reference to what separates, what remains joined during migration in each case, and how a labelled diagram of each stage would differ if examiners asked you to annotate sister chromatids and centromeres.",
        modelAnswerPoints: [
          "Anaphase I: homologous chromosomes separate; sister chromatids remain joined at centromere (each chromosome = two chromatids).",
          "Anaphase II: sister chromatids separate (centromere divides); each chromatid is counted as a chromosome going to a pole.",
          "Diagram: AI shows two chromatids per moving chromosome; AII shows single chromatids moving apart after metaphase II single-file alignment.",
        ],
        workedSolution: [
          "In anaphase I, the release of cohesion between homologous centromeres allows spindle microtubules to drag one replicated chromosome, still composed of two sister chromatids locked together, toward each pole, so the number of centromeres moving to a pole is half the metaphase I count of centromeres in the cell, but each migrating body is X-shaped in diagrams with a single centromere holding two arms that are chromatids.",
          "In anaphase II, cohesion between sister chromatids is cleaved at the centromere, so each former chromatid is pulled independently toward opposite poles as a single-stranded chromosome in textbook drawings, which is why chromatid number at each pole after MII equals the haploid chromosome number and each chromatid is now the DNA unit packaged into the gamete nucleus.",
          "If you annotated diagrams, anaphase I would show two chromatids sharing one kinetochore complex per chromosome until the next division, whereas anaphase II would show sister kinetochores that had faced opposite poles in metaphase II now moving apart with one chromatid each, which is the visual distinction examiners reward when they ask you to interpret or sketch stages.",
        ],
        commonMistake:
          "Drawing anaphase I as if chromatids split, or describing anaphase II as separating homologous pairs.",
        tags: ["anaphase", "meiosis"],
      },
    ],
    flashcards: [
      {
        id: "t16-1-f1",
        noteId: "t16-1",
        difficulty: 1,
        front: "Haploid (n) — chromosome sets in a gamete.",
        back: "One complete set per nucleus; typical gametes after meiosis.",
        examPhrasing: "Explain what is meant by haploid.",
        tags: ["haploid"],
      },
      {
        id: "t16-1-f2",
        noteId: "t16-1",
        difficulty: 1,
        front: "Diploid (2n) — origin of the two sets.",
        back: "Two sets (homologous pairs in somatic cells); one set from each parent at fertilisation.",
        examPhrasing: "Explain what is meant by diploid.",
        tags: ["diploid"],
      },
      {
        id: "t16-1-f3",
        noteId: "t16-1",
        difficulty: 2,
        front: "Homologous pair vs sister chromatids.",
        back: "Homologues: same loci, one from each parent. Sister chromatids: identical copies of one chromosome after DNA replication.",
        examPhrasing: "Distinguish homologous chromosomes and sister chromatids.",
        tags: ["homologous"],
      },
      {
        id: "t16-1-f4",
        noteId: "t16-1",
        difficulty: 2,
        front: "Why is meiosis called a reduction division?",
        back: "Halves chromosome number (2n → n) so fertilisation can restore 2n without doubling every generation.",
        examPhrasing: "Explain the need for a reduction division in gamete formation.",
        tags: ["meiosis"],
      },
      {
        id: "t16-1-f5",
        noteId: "t16-1",
        difficulty: 3,
        front: "Metaphase I vs metaphase II (who lines up?).",
        back: "MI: bivalents (paired homologues). MII: single duplicated chromosomes (pairs of sister chromatids).",
        examPhrasing: "Describe chromosome behaviour at metaphase I and metaphase II.",
        tags: ["stages"],
      },
      {
        id: "t16-1-f6",
        noteId: "t16-1",
        difficulty: 3,
        front: "Crossing over — when and between whom?",
        back: "Prophase I; exchange between non-sister chromatids of a homologous pair.",
        examPhrasing: "Explain the role of crossing over in genetic variation.",
        tags: ["crossing-over"],
      },
      {
        id: "t16-1-f7",
        noteId: "t16-1",
        difficulty: 4,
        front: "Independent assortment — what is random?",
        back: "Orientation of each homologous pair on the metaphase I spindle is independent of other pairs.",
        examPhrasing: "Explain independent assortment in meiosis.",
        tags: ["assortment"],
      },
      {
        id: "t16-1-f8",
        noteId: "t16-1",
        difficulty: 4,
        front: "Anaphase I — what separates?",
        back: "Homologous chromosomes; sister chromatids stay together.",
        examPhrasing: "Describe anaphase I.",
        tags: ["anaphase-I"],
      },
      {
        id: "t16-1-f9",
        noteId: "t16-1",
        difficulty: 5,
        front: "Anaphase II — what separates?",
        back: "Sister chromatids (centromere splits).",
        examPhrasing: "Describe anaphase II.",
        tags: ["anaphase-II"],
      },
      {
        id: "t16-1-f10",
        noteId: "t16-1",
        difficulty: 5,
        front: "Random fertilisation — one consequence.",
        back: "Combines one of many possible sperm with one of many possible eggs → genetically different offspring.",
        examPhrasing: "Explain how fertilisation produces genetic variation.",
        tags: ["fertilisation"],
      },
    ],
  },
  "t16-2": {
    noteId: "t16-2",
    drills: [
      {
        id: "t16-2-d1",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 2,
        marks: 8,
        stem: "Explain the terms gene, locus, allele, dominant, recessive, codominant, linkage, test cross, F1, F2, phenotype, genotype, homozygous and heterozygous as used in transmission genetics at A Level.",
        modelAnswerPoints: [
          "Gene: DNA sequence that codes for a functional product (e.g. polypeptide) / unit of inheritance.",
          "Locus: fixed position of a gene on a chromosome.",
          "Allele: alternative form/version of a gene at a locus.",
          "Dominant: allele expressed in heterozygote phenotype (standard complete dominance).",
          "Recessive: allele not expressed in heterozygote (complete dominance).",
          "Codominant: both alleles contribute distinctly to phenotype in heterozygote.",
          "Linkage: loci on same chromosome tend to be inherited together (unless recombination).",
          "Test cross: cross with homozygous recessive to reveal unknown genotype from offspring ratios.",
          "F1: first filial generation from a cross; F2 from intercrossing F1 (or selfing if appropriate).",
          "Phenotype: observable characteristic; genotype: alleles present.",
          "Homozygous: two identical alleles at a locus; heterozygous: two different alleles.",
        ],
        workedSolution: [
          "A gene is a length of DNA at a particular chromosomal address that typically encodes a functional product such as a polypeptide or functional RNA and behaves as a unit transmitted across generations according to Mendelian rules in simple models.",
          "The locus is that gene’s fixed position along the chromosome map, whereas an allele is any one of the alternative versions of the sequence at that locus—such as a wild-type or a mutant form—that may differ in a few bases or larger regulatory changes.",
          "In a diploid cell, genotype at a locus may be homozygous if both alleles are the same allele type or heterozygous if two different alleles are present; phenotype is the measurable or visible trait outcome, which in complete dominance shows the dominant allele’s trait in the heterozygote while the recessive allele’s trait appears only in the homozygous recessive genotype.",
          "Codominance is the special case where a heterozygote shows both parental traits distinctly—classic textbook examples include both antigen types on red blood cells—rather than a blended or dominant–recessive masking relationship.",
          "Linkage means two or more loci reside on the same chromosome so parental allele combinations tend to be inherited together, with recombination producing a smaller fraction of recombinant gametes depending on map distance.",
          "A test cross mates an individual showing the dominant phenotype but unknown genotype to a homozygous recessive partner so the proportion of recessive offspring reveals whether the unknown parent was heterozygous or homozygous dominant.",
          "F1 denotes the first generation offspring from an initial parental cross, and F2 the generation produced by crossing F1 individuals together (or self-fertilising F1 in plants), which is the standard notation when deriving 3:1 or 9:3:3:1 ratios.",
        ],
        commonMistake:
          "Defining ‘gene’ and ‘allele’ as the same, or saying linkage always prevents recombination entirely.",
        tags: ["definitions", "genetics"],
      },
      {
        id: "t16-2-d2",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "In peas, tall (T) is dominant to short (t). A pure-breeding tall plant is crossed with a pure-breeding short plant. Construct a genetic diagram (Punnett square not mandatory if the written cross is clear) for the F1 and for the F2 produced by selfing F1, and state the expected F2 phenotypic ratio for this monohybrid cross with complete dominance.",
        modelAnswerPoints: [
          "P: TT × tt → all gametes T or t; F1 all Tt (tall phenotype).",
          "F1 self: Tt × Tt; gametes T and t each parent.",
          "Offspring genotypes 1 TT : 2 Tt : 1 tt → phenotypes 3 tall : 1 short.",
        ],
        workedSolution: [
          "The parental cross is homozygous dominant TT with homozygous recessive tt; the tall parent can only produce gametes carrying T and the short parent only t, so every zygote of the F1 generation is genotype Tt, and because T is dominant to t, all F1 plants display the tall phenotype while carrying one recessive allele.",
          "Selfing the F1 corresponds genetically to the cross Tt × Tt; each parent produces equal numbers of T and t gametes under Mendelian assumptions, so combining them in a Punnett square yields zygote genotypes TT, Tt (twice), and tt in a 1:2:1 ratio.",
          "Phenotypically, TT and Tt individuals are tall and tt individuals are short, which collapses the genotypic 1:2:1 to a 3:1 tall:short phenotypic ratio in the F2, which is the classic monohybrid outcome examiners expect you to derive from a labelled genetic diagram with clear gametes and zygotes.",
        ],
        commonMistake:
          "Forgetting to label generations or gametes, or giving 3:1 as a genotypic ratio instead of phenotypic.",
        tags: ["monohybrid", "Punnett"],
      },
      {
        id: "t16-2-d3",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Two unlinked autosomal genes control seed shape and colour in a plant: round (R) is dominant to wrinkled (r), and yellow (Y) is dominant to green (y). A dihybrid heterozygous plant of genotype RrYy is self-fertilised. Using a genetic diagram, predict the F2 phenotypic ratio for the four phenotypes, assuming independent assortment and complete dominance at both loci.",
        modelAnswerPoints: [
          "RrYy produces four gamete types RY, Ry, rY, ry in equal proportion (unlinked).",
          "Self cross = RrYy × RrYy; 4×4 Punnett or branch diagram.",
          "Phenotypes: 9 round yellow : 3 round green : 3 wrinkled yellow : 1 wrinkled green.",
        ],
        workedSolution: [
          "Because the genes are on different chromosomes (or far apart on the same chromosome), the heterozygote RrYy assorts alleles independently, producing four classes of gametes—RY, Ry, rY, and ry—each at one-quarter frequency, which is the gamete row and column header set for a dihybrid Punnett square.",
          "Fertilisation combines these gametes equally in all combinations, giving sixteen zygote boxes; counting phenotypes by applying dominance at each locus separately, any genotype with at least one R and one Y is round yellow, with R and yy is round green, with rr and Y- is wrinkled yellow, and rryy is wrinkled green.",
          "The familiar 9:3:3:1 ratio emerges because nine of sixteen boxes carry both dominant traits, three show dominant round with recessive green, three show recessive wrinkled with dominant yellow, and one box is doubly homozygous recessive for both traits, which is the standard dihybrid prediction you must be able to construct and explain.",
        ],
        commonMistake:
          "Using 3:1 for each gene but forgetting to multiply for combined phenotypes, or assuming linkage without the stem saying so.",
        tags: ["dihybrid", "9:3:3:1"],
      },
      {
        id: "t16-2-d4",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "The ABO blood-group system involves three alleles I^A, I^B and I^O at one locus. Explain why this is described as multiple alleles, outline how I^A and I^B are codominant to each other, and predict the phenotypes (blood groups) of offspring from the cross I^A I^O × I^B I^O using a Punnett square.",
        modelAnswerPoints: [
          "Multiple alleles: more than two allele forms exist in the population at one locus (any diploid carries two).",
          "Codominance: I^A I^B genotype → AB phenotype (both antigens expressed).",
          "Cross I^A I^O × I^B I^O → 1 I^A I^B (AB) : 1 I^A I^O (A) : 1 I^B I^O (B) : 1 I^O I^O (O) phenotypes.",
        ],
        workedSolution: [
          "In the human population the ABO locus has three commonly taught alleles—IA, IB, and IO—so the system exemplifies multiple allelism: although any one person inherits only two alleles, the species-wide pool contains more than two variants, which expands the number of possible diploid genotypes compared with a simple two-allele locus.",
          "IA and IB are codominant because a heterozygote IA IB expresses both carbohydrate antigens on red blood cells, giving blood group AB, whereas IO is recessive to each of IA and IB in the sense that IO IO is group O and IA IO is group A, IB IO is group B in standard serology teaching.",
          "Crossing IA IO with IB IO, each parent makes two gamete types at equal frequency, and the four zygotes IA IB, IA IO, IB IO, and IO IO occur in a 1:1:1:1 ratio, corresponding to AB, A, B, and O phenotypes respectively, which is a compact Punnett exercise combining multiple alleles and codominance in one grid.",
        ],
        commonMistake:
          "Saying an individual has three alleles at once, or confusing IO with the O phenotype without genotype notation.",
        tags: ["codominance", "ABO"],
      },
      {
        id: "t16-2-d5",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Haemophilia is often modelled as an X-linked recessive disorder. A phenotypically normal woman whose father had haemophilia marries a phenotypically normal man. Construct a genetic diagram for the gene on the X chromosome and predict the probability that their first son will have haemophilia, stating any assumptions you make about the mother’s genotype.",
        modelAnswerPoints: [
          "Father with haemophilia → daughter must inherit his X carrying the allele; mother normal phenotype but carrier X^H X^h (using H/h notation).",
          "Husband normal → X^H Y.",
          "Sons receive Y from father and X from mother: 1/2 X^h → 1/2 haemophiliac sons.",
        ],
        workedSolution: [
          "Let X^h carry the recessive disease allele and X^H the dominant normal allele on the X chromosome; a haemophilic male is X^h Y, while a normal male is X^H Y, and a normal homozygous female is X^H X^H while a carrier female is X^H X^h.",
          "The woman’s father was haemophilic (X^h Y), so she necessarily inherited his only X chromosome bearing X^h, and because she is phenotypically normal she must also carry a normal X^H from her mother, making her genotype X^H X^h—a carrier—unless a new mutation is invoked, which we do not assume here.",
          "Her husband is X^H Y; for a son, he inherits the father’s Y with probability one and one of the mother’s X chromosomes with equal probability, so half of her eggs are X^h and half X^H, giving a 50% chance that their first son is X^h Y and therefore haemophilic, which is the standard sex-linkage prediction from a clear genetic diagram with sex chromosomes labelled.",
        ],
        commonMistake:
          "Placing the allele on a Y chromosome or forgetting that the woman must be a carrier given her father’s phenotype.",
        tags: ["sex-linkage", "X-linked"],
      },
      {
        id: "t16-2-d6",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "An examination genetic diagram shows two autosomal loci, A/a and B/b, on one chromosome: a true-breeding dominant AB / AB plant was crossed to a true-breeding recessive ab / ab plant, giving an F1 drawn as AB / ab (coupling). The diagram continues with a test cross of that F1 to ab / ab, with parental gametes AB and ab emphasised. Interpret the diagram: state the gametes the F1 is expected to produce if crossing over is rare, predict the test-cross phenotypic classes, and give their approximate relative frequencies.",
        modelAnswerPoints: [
          "F1 genotype AB/ab (cis/coupling) if no crossover in parents’ chromosomes as given.",
          "Without crossing over: parental gametes AB and ab only → test-cross offspring phenotypes reflect parental types 1:1.",
          "With rare crossing over: small fraction of recombinant Ab and aB gametes → recombinant phenotypes at low frequency; most offspring still parental.",
        ],
        workedSolution: [
          "The P cross fixes one chromosome carrying AB and its homologue carrying ab in the F1 hybrid, which is therefore dihybrid in coupling phase written AB/ab, meaning dominant alleles travel together on one chromatid and recessives on the homologue in the absence of prior recombination.",
          "A test cross to ab/ab mates the F1 to an individual that can only contribute ab gametes, so every offspring phenotype directly reveals which gamete the F1 contributed: AB/ab parentals from AB and ab gametes, and recombinant phenotypes from Ab and aB gametes if those chromatids were produced by crossover in meiosis in the F1.",
          "If crossing over between the loci is rare, most meioses transmit intact parental chromosomes, so roughly half the progeny show both dominant traits and half show both recessive traits in a 1:1 parental split, with a small added minority of mixed phenotypes representing recombinants, which is the linkage pattern examiners contrast with the 1:1:1:1 ratio expected for unlinked dihybrid test crosses.",
        ],
        commonMistake:
          "Predicting 9:3:3:1 or independent 1:1:1:1 ratios as if the genes were on different chromosomes despite the stem stating linkage.",
        tags: ["linkage", "test-cross"],
      },
      {
        id: "t16-2-d7",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "In a dihybrid cross, gene E is epistatic to gene F: homozygous recessive ee masks expression of the F locus, while dominant E- allows yellow (F-) or green (ff) pigment. A cross between dihybrid heterozygotes EeFf × EeFf produces offspring with phenotypic counts 9 yellow : 3 green : 4 unpigmented. Interpret this outcome with reference to epistasis and relate the 9:3:4 ratio to the underlying genotypes (you are not required to name the epistasis type beyond ‘recessive epistasis’).",
        modelAnswerPoints: [
          "Without epistasis dihybrid ratio would be 9:3:3:1 for two visible traits.",
          "ee blocks pigment regardless of F → all ee-- share one unpigmented class.",
          "E-F- yellow; E-ff green; ee-- unpigmented → merges 3 + 1 into 4 for recessive epistatic class.",
        ],
        workedSolution: [
          "A standard complementary dominant system at two loci would yield four phenotypes in a 9:3:3:1 pattern when both loci affect distinguishable traits independently, but here the ee genotype prevents any pigment deposition so both eeF- and eeff individuals look the same unpigmented, collapsing two genotypic boxes that would have been different colours into one phenotypic class.",
          "Among individuals with at least one dominant E allele, the F locus behaves as in a simple dominant/recessive pigment choice: E-F- genotypes from the dihybrid grid are nine-sixteenths and show yellow, while E-ff are three-sixteenths and show green, which accounts for the 9 and 3 terms in the observed ratio.",
          "The ee fraction of the dihybrid square is one-fourth overall, but all of those individuals are phenotypically unpigmented together with no separate 3:1 split visible at the surface, giving four-sixteenths in one class and producing the characteristic 9:3:4 pattern that signals recessive epistasis at E in examination genetics problems.",
        ],
        commonMistake:
          "Trying to memorise ratio names without tracing which genotypes merge when a locus is masked.",
        tags: ["epistasis", "dihybrid"],
      },
      {
        id: "t16-2-d8",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "In tomatoes, red fruit is dominant to yellow. A red-fruited plant from a mixed population is crossed with a known homozygous yellow. Half the offspring are red and half are yellow. Deduce the unknown parent’s genotype, explain why this is a test cross, and state what ratio would have appeared if the red parent had been homozygous dominant.",
        modelAnswerPoints: [
          "Let R = red dominant, r = yellow recessive; tester is rr.",
          "1:1 offspring → unknown must be heterozygous Rr producing R and r gametes.",
          "If unknown were RR, all offspring Rr → all red.",
        ],
        workedSolution: [
          "A test cross reveals the genotype of a dominant-phenotype individual by mating it to a partner that is homozygous recessive, here rr yellow, because the recessive parent contributes only r alleles, so every offspring’s phenotype is determined solely by which allele the dominant-looking parent donates.",
          "A 1:1 red:yellow outcome means half the gametes carried R and half r, which is only possible if the red parent is heterozygous Rr; a homozygous dominant RR parent would transmit R to every zygote, giving genotype Rr for all offspring and an all-red fruit phenotype with no yellows recovered.",
          "Therefore the observed ratio is the classic diagnostic pattern for heterozygosity in a monohybrid test cross, and the experiment’s logic is exactly the syllabus test-cross method even if the word ‘test cross’ does not appear on the examination paper.",
        ],
        commonMistake:
          "Concluding RR from a dominant phenotype despite the 1:1 result, or confusing F2 selfing with a test cross.",
        tags: ["test-cross"],
      },
      {
        id: "t16-2-d9",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 4,
        marks: 8,
        stem: "A geneticist observes 120 offspring from a monohybrid cross where complete dominance and a 3:1 phenotypic ratio are expected. The observed counts are 82 dominant phenotype and 38 recessive phenotype. Calculate chi-squared using χ^2 = Σ((O − E)^2 / E), show working for each class, determine degrees of freedom, compare with the critical value 3.84 at the 5% probability level (table provided in the examination), and state whether the difference between observed and expected is statistically significant.",
        modelAnswerPoints: [
          "Expected: dominant 90, recessive 30 (3/4 and 1/4 of 120).",
          "Contributions: (82−90)^2/90 ≈ 0.71; (38−30)^2/30 ≈ 2.13.",
          "χ^2 ≈ 2.84 (allow small rounding).",
          "df = 1 (two classes − 1); 2.84 < 3.84 → not significant; data consistent with 3:1.",
        ],
        workedSolution: [
          "Under the null hypothesis that the monohybrid mechanism holds with complete dominance, the expected phenotypic ratio is 3 dominant : 1 recessive, so for 120 offspring the expected numbers are (3/4)×120 = 90 dominant and (1/4)×120 = 30 recessive, which are the E values used in the chi-squared formula.",
          "For the dominant class, O − E = 82 − 90 = −8, and (O − E)^2 / E = 64 / 90 ≈ 0.711; for the recessive class, O − E = 38 − 30 = 8, and (O − E)^2 / E = 64 / 30 ≈ 2.133, so summing the contributions gives χ^2 ≈ 0.711 + 2.133 = 2.84 to two decimal places.",
          "There are two phenotype classes, so degrees of freedom equal the number of classes minus one, which is 1 for this goodness-of-fit test in the standard A-level treatment.",
          "The critical value at the 5% significance level for df = 1 is given as 3.84 in the question; since the calculated χ^2 is less than 3.84, we do not reject the null hypothesis, meaning the departure from the expected 3:1 ratio is not statistically significant and the data are consistent with the genetic model within the noise expected from sampling.",
        ],
        commonMistake:
          "Using the wrong expected numbers (e.g. 60:60), forgetting to sum two contributions, or claiming significance when χ^2 is below the critical value.",
        tags: ["chi-squared", "statistics"],
      },
      {
        id: "t16-2-d10",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 4,
        marks: 10,
        stem: "Part A — Explain the relationship between gene, protein and phenotype for: (i) TYR and albinism, (ii) HBB and sickle cell anaemia, (iii) F8 and haemophilia, (iv) HTT and Huntington’s disease. Part B — Explain the role of gibberellin in stem elongation with reference to the dominant Le allele (functional enzyme in gibberellin synthesis) and the recessive le allele (non-functional enzyme).",
        modelAnswerPoints: [
          "TYR → tyrosinase enzyme → melanin synthesis; loss → albinism (lack of pigment).",
          "HBB → β-globin of haemoglobin; sickle allele → altered haemoglobin / sickling red cells → disease phenotype.",
          "F8 → blood clotting factor VIII; defective F8 → impaired clotting → haemophilia.",
          "HTT → huntingtin protein; expanded repeat / mutant form → neurodegenerative Huntington’s phenotype.",
          "Le → active GA biosynthesis enzyme → more gibberellin → stem elongation; le → little/no active enzyme → reduced GA → shorter stem (teaching level).",
        ],
        workedSolution: [
          "The TYR gene encodes tyrosinase, a key enzyme in the pathway that converts tyrosine into melanin pigments in skin, hair, and eyes; when functional alleles fail to produce active enzyme, melanin is not made in the usual way and the individual shows albinism, linking a single gene product loss to a whole-organism colour phenotype.",
          "The HBB gene codes for beta-globin, a subunit of adult haemoglobin; the sickle allele specifies an altered beta-globin that polymerises under deoxygenation, distorting red blood cells into sickle shapes that vaso-occlude and haemolyse, so a DNA change at one locus propagates through protein folding and cell behaviour to the clinical phenotype of sickle cell anaemia.",
          "The F8 gene encodes coagulation factor VIII; mutations that abolish or cripple the protein reduce the efficiency of the clotting cascade, producing the bleeding tendency characteristic of haemophilia A, which illustrates how a plasma protein’s concentration and activity directly map to a whole-body haemostasis phenotype.",
          "The HTT gene encodes huntingtin, a large protein whose mutant form (in Huntington’s disease, associated with expanded CAG repeats in teaching summaries) leads to toxic gain- or altered-function processes in neurones, producing progressive neurodegeneration, which contrasts with simple loss-of-function recessive models while still tying allele → protein behaviour → late-onset neurological phenotype.",
          "In stem elongation, gibberellin promotes growth partly by enabling cell expansion programmes; the dominant Le allele codes for a functional enzyme in gibberellin biosynthesis so active plants make more bioactive gibberellin and grow taller, whereas the recessive le allele specifies a non-functional enzyme, lowering gibberellin levels and restricting internode extension relative to Le lines in the classic genetic demonstration.",
        ],
        commonMistake:
          "Naming genes without the protein or the direction of effect (loss vs toxic gain), or saying le increases GA.",
        tags: ["gene-protein", "gibberellin"],
      },
    ],
    flashcards: [
      {
        id: "t16-2-f1",
        noteId: "t16-2",
        difficulty: 1,
        front: "Locus vs allele.",
        back: "Locus: gene’s position on a chromosome. Allele: variant form of the gene at that locus.",
        examPhrasing: "Distinguish locus and allele.",
        tags: ["definitions"],
      },
      {
        id: "t16-2-f2",
        noteId: "t16-2",
        difficulty: 1,
        front: "Homozygous vs heterozygous.",
        back: "Homozygous: two identical alleles. Heterozygous: two different alleles at a locus.",
        examPhrasing: "Define homozygous and heterozygous.",
        tags: ["genotype"],
      },
      {
        id: "t16-2-f3",
        noteId: "t16-2",
        difficulty: 2,
        front: "Test cross — purpose.",
        back: "Cross with homozygous recessive to deduce unknown genotype from offspring phenotypes.",
        examPhrasing: "Explain a test cross.",
        tags: ["test-cross"],
      },
      {
        id: "t16-2-f4",
        noteId: "t16-2",
        difficulty: 2,
        front: "F1 and F2 (notation).",
        back: "F1: first offspring generation from parental cross. F2: offspring from crossing F1 (or selfing F1).",
        examPhrasing: "What is meant by F1 and F2?",
        tags: ["notation"],
      },
      {
        id: "t16-2-f5",
        noteId: "t16-2",
        difficulty: 3,
        front: "Linkage — one-line definition.",
        back: "Genes on the same chromosome tend to be inherited together unless crossing over separates them.",
        examPhrasing: "Explain linkage of genes.",
        tags: ["linkage"],
      },
      {
        id: "t16-2-f6",
        noteId: "t16-2",
        difficulty: 3,
        front: "χ² test — what does it compare?",
        back: "Observed counts vs expected counts from a hypothesis; large χ² → poorer fit (may be significant).",
        examPhrasing: "State the purpose of the chi-squared test in genetics.",
        tags: ["chi-squared"],
      },
      {
        id: "t16-2-f7",
        noteId: "t16-2",
        difficulty: 4,
        front: "TYR — phenotype link.",
        back: "TYR → tyrosinase → melanin production; defective → albinism.",
        examPhrasing: "Relate TYR to phenotype.",
        tags: ["TYR"],
      },
      {
        id: "t16-2-f8",
        noteId: "t16-2",
        difficulty: 4,
        front: "HBB — phenotype link.",
        back: "HBB → β-globin; sickle allele → abnormal haemoglobin / sickling → sickle cell anaemia.",
        examPhrasing: "Relate HBB to phenotype.",
        tags: ["HBB"],
      },
      {
        id: "t16-2-f9",
        noteId: "t16-2",
        difficulty: 5,
        front: "Le vs le (gibberellin stem length).",
        back: "Le: functional GA synthesis enzyme → more GA → taller. le: non-functional enzyme → less GA → shorter internodes.",
        examPhrasing: "Explain Le and le in stem elongation.",
        tags: ["gibberellin"],
      },
      {
        id: "t16-2-f10",
        noteId: "t16-2",
        difficulty: 5,
        front: "HTT vs F8 — dominant vs X-linked nuance (exam summary).",
        back: "HTT: huntingtin / Huntington’s (autosomal dominant in teaching). F8: factor VIII; haemophilia A often X-linked recessive.",
        examPhrasing: "Relate HTT and F8 to phenotypes.",
        tags: ["HTT", "F8"],
      },
    ],
  },
  "t16-3": {
    noteId: "t16-3",
    drills: [
      {
        id: "t16-3-d1",
        noteId: "t16-3",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Distinguish structural genes from regulatory genes in prokaryotes, and contrast inducible enzymes with repressible enzymes in terms of when transcription is typically high and what sort of small-molecule signals are involved in the standard textbook pictures.",
        modelAnswerPoints: [
          "Structural genes: code for metabolic / house-keeping proteins (e.g. enzymes in a pathway).",
          "Regulatory genes: code for regulators (e.g. repressor proteins) that control other genes’ expression.",
          "Inducible enzymes: transcribed at low rate until an inducer signals ‘turn on’ (e.g. substrate of pathway).",
          "Repressible enzymes: transcribed until a corepressor / end-product signals ‘turn down’ (e.g. excess product).",
        ],
        workedSolution: [
          "Structural genes are the ones whose polypeptide products do the direct biochemical work of the cell, such as the enzymes that digest lactose or synthesise amino acids, whereas regulatory genes encode trans-acting factors—commonly DNA-binding repressors or activators—that adjust the transcription rates of whole operons or sets of targets without themselves being the metabolic catalysts.",
          "Inducible systems keep transcription of a catabolic pathway repressed when the substrate is absent, saving energy, but when an inducer molecule is present—often a metabolite related to the substrate—it interacts with a repressor or regulator so that RNA polymerase gains better access to the structural genes, sharply increasing enzyme production just when the substrate appears.",
          "Repressible systems are typical of anabolic pathways that should run when end product is scarce: transcription proceeds at a high baseline until accumulating end product, or a derivative, acts as a corepressor that helps a repressor shut down the operon, preventing overproduction, which is the opposite logical direction to induction though both use regulatory proteins and operator/promoter logic in teaching models.",
        ],
        commonMistake:
          "Calling lacZ a regulatory gene, or saying inducible means ‘always on’.",
        tags: ["operon", "definitions"],
      },
      {
        id: "t16-3-d2",
        noteId: "t16-3",
        kind: "structured",
        difficulty: 3,
        marks: 8,
        stem: "Explain genetic control of protein production in *Escherichia coli* using the lac operon, including the roles of the operator, promoter, structural genes (lacZ, lacY, lacA), and the lacI regulatory gene encoding the repressor. Include what happens when lactose is absent and when lactose is present (cAMP detail not required).",
        modelAnswerPoints: [
          "Operon: cluster of structural genes under common control; polycistronic mRNA in prokaryote teaching.",
          "lacI: constitutively expressed repressor binds operator in absence of inducer → blocks RNAP progress.",
          "Lactose absent: repressor bound → low transcription of lacZYA.",
          "Lactose present: allolactose (inducer) binds repressor → conformation change → repressor releases operator → transcription of lacZ (β-gal), lacY (permease), lacA (transacetylase) increases.",
        ],
        workedSolution: [
          "The lac operon is a classic polycistronic unit: promoter and operator sequences lie upstream of three structural genes lacZ, lacY, and lacA that encode β-galactosidase, lactose permease, and transacetylase respectively, so one successful transcription event can equip the cell to import and cleave lactose when the operon is ON.",
          "The separate lacI regulatory gene, transcribed from its own promoter, produces a repressor protein that in the absence of inducer binds with high affinity to the operator DNA, a site overlapping the lac promoter region, sterically hindering RNA polymerase from initiating or elongating effectively through the operon, which keeps lac enzyme levels very low when lactose is not in the medium.",
          "When lactose enters the cell and is converted to allolactose, this molecule acts as an inducer by binding the repressor at an allosteric site, changing its shape so it no longer binds the operator tightly; RNA polymerase can then transcribe lacZYA at high rate, producing the proteins needed for lactose catabolism.",
          "This inducible logic couples enzyme synthesis to substrate availability without requiring eukaryotic chromatin remodelling: it is purely cis-regulatory DNA plus a diffusible repressor and a small-molecule signal, which is the level of lac operon explanation the syllabus expects when cAMP–CRP modulation is explicitly excluded from recall.",
        ],
        commonMistake:
          "Saying lactose binds the operator directly, or that lacI is part of the polycistronic mRNA with lacZ.",
        tags: ["lac-operon"],
      },
      {
        id: "t16-3-d3",
        noteId: "t16-3",
        kind: "mcq",
        difficulty: 2,
        stem: "In the lac operon model, which change best describes the immediate molecular effect of the inducer binding the lac repressor?",
        options: [
          { id: "A", text: "The repressor binds the promoter more tightly, excluding RNA polymerase." },
          { id: "B", text: "The repressor’s affinity for the operator decreases, so it detaches and transcription can increase." },
          { id: "C", text: "The inducer hydrolyses lactose directly without translation." },
          { id: "D", text: "lacI is deleted from the chromosome." },
        ],
        correctOptionId: "B",
        explanation:
          "Inducer (allolactose) binds the repressor, causing a conformational change that weakens operator binding, lifting repression.",
        distractorRationale: {
          A: "Repressor binding the operator blocks transcription; inducer frees the operator, not tighter promoter binding.",
          C: "β-galactosidase (lacZ product) cleaves lactose; the inducer is not the enzyme.",
          D: "lacI remains; regulation is allosteric, not gene deletion.",
        },
        tags: ["lac-operon", "mcq"],
      },
      {
        id: "t16-3-d4",
        noteId: "t16-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "State that transcription factors are proteins that bind DNA and explain briefly how they can increase or decrease the rate of transcription of eukaryotic genes without describing every structural class.",
        modelAnswerPoints: [
          "Transcription factors: regulatory proteins that bind specific DNA sequences (promoters, enhancers).",
          "Can recruit / stabilise RNA polymerase II and general factors → increased transcription.",
          "Can block assembly or recruit co-repressors / deacetylases → decreased transcription.",
        ],
        workedSolution: [
          "Transcription factors are gene-regulatory proteins that recognise short DNA motifs in cis-regulatory regions such as core promoters and distal enhancers and make contact, directly or through adaptors, with the basal transcription machinery.",
          "Activators typically help recruit RNA polymerase II and general transcription factors or chromatin-modifying complexes that open local chromatin, increasing the initiation frequency of transcription at target promoters.",
          "Repressive transcription factors can compete for binding sites, mask activation domains, or recruit histone deacetylases and other complexes that compact chromatin or block preinitiation complex formation, thereby lowering the transcription rate of particular genes in differentiated cells.",
        ],
        commonMistake:
          "Claiming transcription factors are always activators or that they act in the cytoplasm on mature mRNA in this syllabus context.",
        tags: ["transcription-factors"],
      },
      {
        id: "t16-3-d5",
        noteId: "t16-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Explain how gibberellin can activate transcription of growth-related genes in plants by causing breakdown of DELLA repressor proteins, which normally inhibit factors that promote transcription.",
        modelAnswerPoints: [
          "DELLA proteins: nuclear repressors that block transcriptional activators of GA-responsive genes when GA is low.",
          "Gibberellin signal → DELLA targeted for proteasomal degradation / removal (pathway overview).",
          "Without DELLA, positive transcription factors function → increased transcription of GA-induced genes → growth responses (e.g. stem elongation components).",
        ],
        workedSolution: [
          "DELLA proteins sit in the nucleus as part of a signalling hub that restrains the expression of gibberellin-responsive growth genes: while they are present, they bind or sequester transcriptional activators or interfere with their DNA binding so downstream promoters fire at a low rate even though the basal machinery is intact.",
          "When gibberellin perception triggers a signalling cascade—through the GID1 receptor family and associated F-box proteins in the textbook summary—DELLA proteins become post-translationally modified so the ubiquitin–proteasome system degrades them, rapidly clearing the repressor from the nucleus.",
          "Removal of DELLA frees activators to recruit RNA polymerase and associated coactivators to promoters of genes whose products implement cell expansion and other GA-dependent programmes, so hormone binding indirectly raises transcription rates by destroying a transcriptional brake, which is the syllabus narrative linking gibberellin, DELLA, and gene expression without requiring every intermediate kinase name.",
        ],
        commonMistake:
          "Saying gibberellin binds DNA directly, or that DELLA activates transcription when present.",
        tags: ["DELLA", "gibberellin"],
      },
      {
        id: "t16-3-d6",
        noteId: "t16-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Compare control of gene expression in the bacterial lac operon with control of a typical eukaryotic gene regulated by transcription factors and distant enhancers, emphasising polycistronic vs monocistronic transcription and the role of chromatin context at a simple outline level.",
        modelAnswerPoints: [
          "lac: operon polycistronic mRNA; negative control by repressor at operator; fast response, no nucleus.",
          "Eukaryote: usually one primary transcript per gene (monocistronic mRNA after processing); combinatorial TF binding; enhancers; chromatin accessibility.",
          "Both: DNA–protein interactions determine transcription rate; signals (small molecules vs hormones) ultimately impinge on regulators.",
        ],
        workedSolution: [
          "The lac operon couples several structural cistrons into one regulatory unit so a single promoter can produce one polycistronic mRNA that is translated into multiple enzymes, with a soluble repressor toggling access in minutes in the cytoplasmic transcription environment of the bacterium.",
          "A typical eukaryotic protein-coding gene is transcribed as part of monocistronic units: RNA polymerase II makes a precursor RNA from one gene’s promoter, and splicing yields mature mRNA exported to the cytoplasm, while multiple enhancer-bound transcription factors integrate developmental and hormonal signals often from kilobases away.",
          "Chromatin packing modulates eukaryotic initiation—nucleosome remodelling and histone marks influence whether activators can bind—whereas bacterial DNA is not packaged in nucleosomes in the same way, so the comparison should stress structural coupling of genes in operons versus modular cis-regulation of individual genes, even though both systems ultimately resolve to regulated recruitment or blockage of RNA polymerase.",
        ],
        commonMistake:
          "Claiming eukaryotes use operons like lac for most protein genes, or ignoring polycistronic mRNA in bacteria.",
        tags: ["comparison", "eukaryotes"],
      },
      {
        id: "t16-3-d7",
        noteId: "t16-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which example best illustrates an inducible catabolic pathway in bacteria?",
        options: [
          { id: "A", text: "The trp operon when tryptophan is abundant." },
          { id: "B", text: "The lac operon when lactose is added to the growth medium." },
          { id: "C", text: "Ribosomal RNA genes in stationary phase." },
          { id: "D", text: "DNA replication initiation at every cell division." },
        ],
        correctOptionId: "B",
        explanation:
          "lac enzymes are induced when lactose (via allolactose) signals presence of a usable carbon source; trp is a classic repressible anabolic operon.",
        distractorRationale: {
          A: "Tryptophan acts as a corepressor for the trp repressible operon, not induction of catabolism.",
          C: "rRNA regulation is not the lac/trp inducible–repressible contrast asked for here.",
          D: "Replication initiation is not the lac inducible enzyme story.",
        },
        tags: ["inducible", "mcq"],
      },
      {
        id: "t16-3-d8",
        noteId: "t16-3",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe the roles of the lac operator sequence and the lac repressor protein in switching the lac operon off when lactose is absent, and explain why mutations that delete the operator can cause constitutive expression of lacZ even if lacI is functional.",
        modelAnswerPoints: [
          "Operator: DNA site where repressor binds to block transcription initiation/elongation of lacZYA.",
          "Repressor: diffusible protein product of lacI; active form binds operator without inducer.",
          "Operator deletion: no binding site → repressor cannot block RNAP → operon stays ON (constitutive).",
        ],
        workedSolution: [
          "The operator is a specific stretch of DNA near the lac promoter that overlaps or lies immediately downstream of RNA polymerase’s binding region so that when the lac repressor tetramer occupies the operator, the physical presence of the protein prevents productive initiation or early elongation of transcription across lacZ.",
          "The repressor molecules are translated continuously from lacI mRNA and diffuse until they encounter the operator; in the absence of allolactose they adopt a DNA-binding-competent conformation with high affinity for that sequence, which is the OFF state for the structural genes.",
          "If the operator is deleted or destroyed by mutation, even a perfectly functional repressor has no high-affinity cis site at the operon, so RNA polymerase is never sterically blocked at that locus and lacZ transcription proceeds at a high constitutive level independent of lactose, which is how cis- versus trans-acting mutations are distinguished in bacterial genetics teaching.",
        ],
        commonMistake:
          "Saying the repressor binds lacZ coding DNA instead of the operator, or that lacI mutation and operator mutation have identical effects.",
        tags: ["lac-operon", "operator"],
      },
      {
        id: "t16-3-d9",
        noteId: "t16-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A gibberellin-deficient mutant accumulates DELLA proteins and shows dwarf growth; application of exogenous gibberellin restores near-wild-type height. Explain this observation using the DELLA repressor narrative and link it to changed transcription of growth-promoting genes.",
        modelAnswerPoints: [
          "Without GA signal, DELLA not degraded → repression of GA-responsive transcriptional activators.",
          "Dwarf: low expression of genes for expansion / stem elongation.",
          "Exogenous GA triggers pathway → DELLA destroyed → activators work → transcription of growth genes increases.",
        ],
        workedSolution: [
          "In the mutant background where bioactive gibberellin is scarce, the nuclear DELLA proteins are not efficiently targeted for destruction, so they persistently bind or sequester transcription factors that would otherwise switch on gibberellin-responsive promoters controlling enzymes and structural proteins needed for rapid stem cell elongation.",
          "The net result is a transcriptional programme skewed toward restraint: growth genes fire at suboptimal rates and the plant exhibits a compact dwarf habit even though the genomic coding sequences for those genes are intact.",
          "Supplying gibberellin exogenously reconstitutes the signal that activates the ubiquitin–proteasome pathway on DELLA, clearing the repressor and permitting activators to recruit RNA polymerase to growth gene promoters, increasing mRNA abundance for expansion-related products and restoring elongation toward the wild-type phenotype, which is the physiological readout of the DELLA–GA genetic switch described in the syllabus.",
        ],
        commonMistake:
          "Attributing dwarfism only to cell walls without mentioning transcriptional derepression.",
        tags: ["DELLA", "application"],
      },
      {
        id: "t16-3-d10",
        noteId: "t16-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Which pairing best matches ‘repressible enzyme system’ vs ‘inducible enzyme system’ in standard bacterial operon teaching?",
        options: [
          { id: "A", text: "Repressible: lac operon when glucose is high. Inducible: trp operon when tryptophan is low." },
          { id: "B", text: "Repressible: trp operon when end-product tryptophan is high. Inducible: lac operon when lactose is present." },
          { id: "C", text: "Both lac and trp are inducible operons controlled only by σ factors." },
          { id: "D", text: "Repressible systems never use repressor proteins." },
        ],
        correctOptionId: "B",
        explanation:
          "Trp is repressible (pathway off when product abundant); lac is inducible (pathway on when lactose signals).",
        distractorRationale: {
          A: "This swaps the standard roles of lac and trp in most textbooks.",
          C: "Both operons use repressor proteins in the classic models; lac is not trp.",
          D: "Repressible systems use repressors aided by corepressor (e.g. tryptophan).",
        },
        tags: ["repressible", "mcq"],
      },
    ],
    flashcards: [
      {
        id: "t16-3-f1",
        noteId: "t16-3",
        difficulty: 1,
        front: "Structural gene vs regulatory gene (prokaryote example).",
        back: "Structural: codes for metabolic enzyme (lacZ). Regulatory: codes for regulator protein (lacI repressor).",
        examPhrasing: "Distinguish structural and regulatory genes.",
        tags: ["operon"],
      },
      {
        id: "t16-3-f2",
        noteId: "t16-3",
        difficulty: 1,
        front: "Inducible enzyme — simple definition.",
        back: "Enzyme production increases when a substrate/signal (inducer) shows the pathway is needed.",
        examPhrasing: "What is an inducible enzyme?",
        tags: ["inducible"],
      },
      {
        id: "t16-3-f3",
        noteId: "t16-3",
        difficulty: 2,
        front: "Repressible enzyme — simple definition.",
        back: "Enzyme production high until end product (corepressor) builds up and switches transcription down.",
        examPhrasing: "What is a repressible enzyme?",
        tags: ["repressible"],
      },
      {
        id: "t16-3-f4",
        noteId: "t16-3",
        difficulty: 2,
        front: "lac operon — what does lacZ encode?",
        back: "β-galactosidase — cleaves lactose to glucose and galactose (and related substrates).",
        examPhrasing: "State the role of lacZ.",
        tags: ["lacZ"],
      },
      {
        id: "t16-3-f5",
        noteId: "t16-3",
        difficulty: 3,
        front: "lacY gene product.",
        back: "Lactose permease — transports lactose into the cell.",
        examPhrasing: "Give the function of lacY.",
        tags: ["lacY"],
      },
      {
        id: "t16-3-f6",
        noteId: "t16-3",
        difficulty: 3,
        front: "Allolactose in lac regulation.",
        back: "Inducer derived from lactose; binds repressor so it releases the operator.",
        examPhrasing: "Explain induction of the lac operon.",
        tags: ["inducer"],
      },
      {
        id: "t16-3-f7",
        noteId: "t16-3",
        difficulty: 4,
        front: "Transcription factor — one-sentence syllabus answer.",
        back: "Protein that binds DNA and increases or decreases transcription rate in eukaryotes.",
        examPhrasing: "State the role of transcription factors.",
        tags: ["TF"],
      },
      {
        id: "t16-3-f8",
        noteId: "t16-3",
        difficulty: 4,
        front: "DELLA + gibberellin (outcome).",
        back: "GA signalling leads to destruction of DELLA repressors → growth genes can be transcribed more.",
        examPhrasing: "Explain how gibberellin activates genes via DELLA.",
        tags: ["DELLA"],
      },
      {
        id: "t16-3-f9",
        noteId: "t16-3",
        difficulty: 5,
        front: "Polycistronic vs monocistronic (lac vs typical eukaryotic mRNA).",
        back: "lac: one mRNA, several genes. Eukaryote: usually one mature mRNA per gene after processing.",
        examPhrasing: "Contrast gene expression in prokaryotes and eukaryotes.",
        tags: ["comparison"],
      },
      {
        id: "t16-3-f10",
        noteId: "t16-3",
        difficulty: 5,
        front: "Operator mutation (cis) effect.",
        back: "Repressor cannot bind site → operon may be constitutively expressed even if lacI normal.",
        examPhrasing: "Explain constitutive lac expression.",
        tags: ["operator"],
      },
    ],
  },
};
