import type { SubtopicPracticePack } from "./types";

/**
 * Topic 17 (9700 Biology) practice — `data/courses/biology-9700.json` (`t17-1`, `t17-2`, `t17-3`).
 *
 * **`t17-1` (17.1 Variation)** — Crosswalk to `data/syllabus/biology-9700-learning-outcomes.md` §17.1:
 * d1 genetic / environmental / combined phenotypic variation with examples; d2 discontinuous vs continuous from definitions and data patterns;
 * d3 genetic basis (few genes vs polygenic + environment); d4–d5 t-test procedure and numeric calculation; d6 limitations of non-significance;
 * d7–d10 consolidation (classification, assumptions, MCQs).
 *
 * **`t17-2` (17.2 Natural and artificial selection)** — Crosswalk to §17.2:
 * d1 natural selection (overproduction, competition, heritable advantage, allele change); d2 stabilising / directional / disruptive;
 * d3 selection vs genetic drift, founder and bottleneck; d4 antibiotic resistance; d5 Hardy–Weinberg conditions;
 * d6–d7 calculation drills (equations stated as given on the data sheet); d8–d10 selective breeding (principles + wheat/rice, maize hybrids, dairy cattle).
 *
 * **`t17-3` (17.3 Evolution)** — Crosswalk to §17.3:
 * d1 evolution as gene-pool change and speciation over time; d2 DNA sequence similarity and phylogenies; d3–d5 isolation and allopatric / sympatric pathways;
 * d6–d10 synoptic MCQs + structured comparisons (barriers, evidence, mechanisms).
 */
export const BIOLOGY_TOPIC17_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t17-1": {
    noteId: "t17-1",
    drills: [
      {
        id: "t17-1-d1",
        noteId: "t17-1",
        kind: "structured",
        difficulty: 1,
        marks: 6,
        stem: "Explain, with one clear example for each case, how phenotypic variation in a population can arise from (a) mainly genetic factors, (b) mainly environmental factors, and (c) an interaction between genetic and environmental factors.",
        modelAnswerPoints: [
          "Genetic example: inherited basis with limited environmental override in normal conditions (e.g. ABO blood group from alleles).",
          "Environmental example: phenotype altered by external conditions without implying a matching inherited change (e.g. suntan from UV exposure).",
          "Combined example: trait with inherited contribution modified by environment (e.g. human height influenced by nutrition and disease as well as alleles).",
          "Phenotype is the observed character; it need not equal genotype when environment contributes.",
        ],
        workedSolution: [
          "Phenotypic variation is the observable differences between individuals for a character, and at 9700 level examiners expect you to separate how much of that variation is explained by inherited differences in DNA sequence, how much by conditions experienced during life, and how often both act together.",
          "A mainly genetic example is the ABO blood group system: an individual’s red-cell antigens reflect inherited alleles at the ABO locus, and ordinary nutrition or climate does not reshuffle those categories within life, so the variation between people is predominantly genetic in origin in the sense the syllabus intends.",
          "A mainly environmental example is the depth of suntan in human skin: melanin-based darkening follows ultraviolet exposure and can differ greatly between genetically similar people who experience different sun histories, so much of the variation in tan intensity at a given age is environmental rather than a change in germ-line sequence.",
          "An interaction example is stature: many alleles and growth-hormone pathways set a genetic potential, yet chronic malnutrition, serious childhood infection, or endocrine disease can depress adult height relative to that potential, so two individuals with similar height-related genotypes can differ in measured height because environments diverged.",
          "Therefore the examination answer should name phenotype explicitly, give contrasting examples, and avoid claiming every trait is ‘purely’ one cause when the syllabus expects you to recognise mixed cases.",
        ],
        commonMistake:
          "Giving only vague ‘genes vs environment’ labels without concrete examples, or citing a trait as purely genetic when syllabus teaching treats it as strongly environmentally modified (or the reverse).",
        tags: ["variation", "phenotype"],
      },
      {
        id: "t17-1-d2",
        noteId: "t17-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Define discontinuous variation and continuous variation. For each definition, name one suitable biological example and state how you would recognise the variation type from the pattern of data in a large sample.",
        modelAnswerPoints: [
          "Discontinuous: distinct categories, no intermediates; examples such as ABO blood groups or many Mendelian either/or traits; histogram shows separate bars / classes.",
          "Continuous: range of values with many intermediates; examples such as height or body mass; histogram tends toward a bell-shaped / unimodal spread.",
        ],
        workedSolution: [
          "Discontinuous variation occurs when individuals can be sorted into discrete classes with clear boundaries, so that between-class phenotypes are absent or not biologically meaningful at the resolution you measure, which is why examiners often illustrate it with blood groups or presence/absence characters.",
          "If you measured thousands of people and plotted ABO type, you would see four separated categories with no intermediate ‘halfway’ blood group, which is the data signature of discontinuity rather than a smooth curve.",
          "Continuous variation occurs when the trait is measured on a scale and most intermediate values are possible, at least after rounding to sensible precision, so a large sample produces a distribution with many bins and a central tendency rather than a few isolated classes.",
          "Human height, though recorded in centimetres, still shows a broad central cluster and tapering tails in large cohorts, matching continuous variation, whereas forcing height into only ‘tall’ and ‘short’ bins in a small survey can misleadingly look discontinuous even though the underlying biology is continuous, which is a nuance you can mention briefly if the question invites data interpretation.",
        ],
        commonMistake:
          "Calling height discontinuous because the table uses rounded classes, or treating every single-gene trait as automatically discontinuous without thinking about measurement scale.",
        tags: ["discontinuous", "continuous"],
      },
      {
        id: "t17-1-d3",
        noteId: "t17-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain the usual genetic basis of discontinuous variation and of continuous variation at A Level standard, linking each to typical gene number and the role of the environment.",
        modelAnswerPoints: [
          "Discontinuous: often one or a few genes; allelic combinations give discrete phenotypic classes; environment often has limited effect.",
          "Continuous: usually polygenic inheritance (many loci with small additive effects) plus environmental modification → broad spectrum of phenotypes.",
        ],
        workedSolution: [
          "Discontinuous variation is typically explained by segregation and assortment at one major locus, or a small number of loci with large phenotypic effects, so that a manageable set of genotypes maps onto a manageable set of phenotypes, as in classic monohybrid or dihybrid ratios when environmental noise is low.",
          "Because each genotype class is distinct, the population falls into a limited number of phenotypic boxes, and unless there is strong environmental masking, intermediates are rare, which matches what you see in textbook Mendelian examples.",
          "Continuous variation, by contrast, usually reflects polygenic architecture: many genes each contribute a small increment to the trait, and when their effects sum with independent assortment, the total phenotype can take many values, especially once non-genetic factors such as diet, microclimate, or maternal effects shift outcomes in parallel.",
          "That combination of many segregating loci and environmental smoothing is the standard explanation for bell-shaped trait distributions, and it is the contrast examiners want against the ‘one gene, clear classes’ picture for discontinuous characters.",
        ],
        commonMistake:
          "Stating that continuous traits are controlled by a single gene, or that polygenic always means no environmental influence.",
        tags: ["polygenic", "genetics"],
      },
      {
        id: "t17-1-d4",
        noteId: "t17-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Describe how you would use a t-test to compare the means of two independent samples of a biological measurement. Include the null hypothesis, how you use the calculated and critical values of t, and how you phrase the statistical conclusion before giving a biological interpretation.",
        modelAnswerPoints: [
          "State H0: no significant difference between the two population means (or sample means reflect the same population).",
          "Calculate t using the formula provided for the examination; determine degrees of freedom; choose significance level (e.g. p = 0.05).",
          "Compare calculated |t| with critical t; if calculated meets/exceeds critical value, reject H0; otherwise fail to reject H0.",
          "Translate decision into words: significant difference vs difference could be due to chance; then interpret in biological context of the investigation.",
        ],
        workedSolution: [
          "The t-test is the standard parametric test for asking whether two sample means are far enough apart that the gap is unlikely to have arisen only from random sampling error, assuming the data are suitable for the test and the samples are independent.",
          "You begin by stating a null hypothesis in plain language, most often that there is no significant difference between the means of the two populations from which the samples were drawn, which fixes what ‘no effect’ means statistically.",
          "You then compute the t statistic from the two means, their spreads, and sample sizes using the expression printed in the mathematical requirements for the examination, and you look up or are given a critical value of t for the appropriate degrees of freedom and chosen probability such as 5%.",
          "If the magnitude of the calculated t is greater than or equal to the critical value, you reject the null hypothesis and conclude the means differ significantly at that level, which is evidence that the treatments or groups are associated with different average measurements, after which you must restate that conclusion in biological terms, for example that the herbivory treatment reduced mean leaf area.",
          "If calculated t is smaller than the critical value, you fail to reject the null hypothesis and must avoid over-claiming: you only state that your data do not provide strong evidence of a difference at that significance level, not that the populations are provably identical.",
        ],
        commonMistake:
          "Omitting H0, comparing the wrong critical value for the degrees of freedom, or jumping from a p-value to a causal biological claim that the experiment cannot support.",
        tags: ["t-test", "statistics"],
      },
      {
        id: "t17-1-d5",
        noteId: "t17-1",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem:
          "Two independent samples of leaf width (mm) are compared.\nLine A: n1 = 12, mean = 42.0, standard deviation s1 = 3.0.\nLine B: n2 = 10, mean = 38.5, standard deviation s2 = 2.5.\nUse t = |x̄1 − x̄2| / √(s1²/n1 + s2²/n2).\nThe critical value of t at the appropriate degrees of freedom and p = 0.05 is 2.10.\n(a) Calculate the value of t.\n(b) State the null hypothesis and your statistical conclusion.\n(c) Give one brief biological conclusion.",
        modelAnswerPoints: [
          "H0: no significant difference between the population mean leaf widths of the two lines.",
          "Difference in means = 42.0 − 38.5 = 3.5 mm.",
          "s1²/n1 = 9.0/12 = 0.75; s2²/n2 = 6.25/10 = 0.625; denominator = √(1.375) = 1.17 (approx).",
          "t = 3.5 / 1.17 = 2.99 (accept 2.9–3.0).",
          "Calculated t > critical t (2.10) → reject H0 at p = 0.05.",
          "Biological conclusion: line A has significantly wider leaves on average than line B under the conditions tested.",
        ],
        workedSolution: [
          "State H0 as no significant difference between the two population means for leaf width.",
          "Compute the difference in sample means: 42.0 − 38.5 = 3.5 mm.",
          "Substitute into the two-sample t formula: t = 3.5 / √(3.0²/12 + 2.5²/10) = 3.5 / √(0.75 + 0.625) = 3.5 / 1.17 ≈ 2.99.",
          "Because 2.99 > 2.10, reject H0 at the 5% level: the observed difference in means is unlikely to be due to chance alone.",
          "Biologically, line A tends to produce wider leaves than line B in this investigation, without claiming proof of a specific gene unless that was tested separately.",
        ],
        commonMistake:
          "Using pooled variance when the question gives separate s1 and s2 for independent samples, or forgetting to compare calculated t with the critical value.",
        tags: ["t-test", "calculation", "statistics"],
      },
      {
        id: "t17-1-d6",
        noteId: "t17-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain why a non-significant result from a t-test comparing two sample means does not prove that the two populations are identical. Relate your answer to what the null hypothesis actually asserts and to sampling variation.",
        modelAnswerPoints: [
          "Non-significant: insufficient evidence to reject H0 at chosen probability; difference could be due to chance.",
          "Does not prove means are exactly equal in the whole population; only that data do not meet the test’s threshold.",
          "Larger samples or lower variability might detect a smaller true difference; biological importance can differ from statistical significance.",
        ],
        workedSolution: [
          "A t-test is designed around a conservative rule: you only reject the null hypothesis when the observed separation between sample means is extreme enough, relative to their scatter and sample sizes, that such an outcome would be rare if the underlying population means were truly the same.",
          "When the calculated t falls below the critical value, you ‘fail to reject’ H0, which is a statement about the strength of evidence in your particular samples, not a mathematical proof that two population means are identical to infinitely many decimal places.",
          "Two populations could differ by a small amount that your experiment lacked power to resolve, especially with small samples or noisy measurements, so absence of statistical significance is not evidence of absence of any biological difference.",
          "Examiners therefore reward answers that separate statistical conclusion (‘no detectable difference at p = 0.05’) from biological over-interpretation (‘the strains are definitely the same’), and that mention sampling variation explicitly.",
        ],
        commonMistake:
          "Writing ‘the populations are the same’ as if that were the direct output of p > 0.05, rather than a failure to reject H0.",
        tags: ["t-test", "statistics"],
      },
      {
        id: "t17-1-d7",
        noteId: "t17-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which set of traits is best classified entirely as examples of discontinuous variation at A Level?",
        options: [
          { id: "A", text: "Human height, leaf length in cloned plants exposed to two fertiliser levels, and enzyme activity in liver tissue." },
          { id: "B", text: "ABO blood group, presence or absence of the ability to taste phenylthiocarbamide (PTC) in many teaching schemes, and seed shape categories such as round vs wrinkled in classic Mendelian peas." },
          { id: "C", text: "Body mass in a large human cohort, bark thickness in a pine plantation, and count of stomata per mm^2 of leaf surface." },
          { id: "D", text: "Rate of photosynthesis measured as continuous CO2 uptake, and chlorophyll concentration extracted from leaf discs." },
        ],
        correctOptionId: "B",
        explanation:
          "These are discrete categorical phenotypes with clear classes. The other options chiefly involve measured quantities that vary continuously or are treated as continuous data.",
        distractorRationale: {
          A: "Height and enzyme activity are typically continuous measurements; fertiliser shifts a quantitative trait.",
          C: "Mass, thickness, and stomatal density are quantitative traits with many intermediates.",
          D: "Rates and concentrations on a continuous scale are not discontinuous categories.",
        },
        tags: ["discontinuous", "mcq"],
      },
      {
        id: "t17-1-d8",
        noteId: "t17-1",
        kind: "mcq",
        difficulty: 2,
        stem: "A student applies a t-test to compare mean reaction times between two groups. Which condition is most important for the standard t-test interpretation taught at this level?",
        options: [
          { id: "A", text: "The two samples must be the same size or the test is always invalid." },
          { id: "B", text: "Measurements should be independent between individuals and approximately suitable for comparing means (often implying rough normality for the underlying distribution in teaching)." },
          { id: "C", text: "The null hypothesis must state that the experimental treatment caused the difference." },
          { id: "D", text: "The test can only be used if raw data are already converted to percentages." },
        ],
        correctOptionId: "B",
        explanation:
          "Independence and appropriate use of means are central; exact equal sample sizes are not a universal requirement for a t-test.",
        distractorRationale: {
          A: "Unequal sample sizes can still be handled by the standard formula; equality is not the core validity condition.",
          C: "H0 is typically ‘no difference’; causation is a biological inference beyond the bare test.",
          D: "Percent conversion is not a prerequisite for a t-test on means.",
        },
        tags: ["t-test", "mcq"],
      },
      {
        id: "t17-1-d9",
        noteId: "t17-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A field biologist records pea flower colour in two meadows as either purple or white only, and separately records nectar volume per flower measured in microlitres. Classify each trait as discontinuous or continuous variation and justify each decision in one sentence.",
        modelAnswerPoints: [
          "Flower colour in two discrete classes → discontinuous.",
          "Nectar volume on a continuous measurement scale with many possible intermediate values → continuous.",
        ],
        workedSolution: [
          "Flower colour is scored here only as purple or white, so every plant falls into one of two distinct phenotypic classes with no intermediate category in the scoring scheme, which matches discontinuous variation at the level of the data table.",
          "Nectar volume is measured as a quantity in microlitres, so unless the instrument truncates everything to a few bins, the trait can take many intermediate values across flowers, producing a quantitative distribution typical of continuous variation.",
          "The contrast examiners want is therefore categorical phenotype versus measured quantity, not the common name of the organism.",
        ],
        commonMistake:
          "Claiming nectar volume is discontinuous because values are written to two decimal places; rounding does not remove underlying continuity if intermediates exist.",
        tags: ["classification"],
      },
      {
        id: "t17-1-d10",
        noteId: "t17-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which statement best matches the usual A Level explanation for continuous variation in a trait such as human height?",
        options: [
          { id: "A", text: "It is usually controlled only by the Y chromosome and is unaffected by nutrition." },
          { id: "B", text: "It is usually polygenic with many genes contributing small effects, and environmental factors can further modify the phenotype." },
          { id: "C", text: "It must be caused entirely by the environment because height changes during life." },
          { id: "D", text: "It always shows a 3 : 1 phenotypic ratio in family data." },
        ],
        correctOptionId: "B",
        explanation:
          "Continuous variation is standardly taught as polygenic plus environmental modification; it does not reduce to one locus or a single Mendelian ratio.",
        distractorRationale: {
          A: "Height is not Y-linked only and is strongly influenced by many autosomal factors and environment.",
          C: "Height has major genetic contributions even though environment matters.",
          D: "3 : 1 ratios arise from single-gene discontinuous examples, not from typical height inheritance.",
        },
        tags: ["continuous", "mcq"],
      },
    ],
    flashcards: [
      {
        id: "t17-1-f1",
        noteId: "t17-1",
        difficulty: 1,
        front: "Phenotypic variation — one-line definition.",
        back: "Differences between individuals in observable characters; phenotype may reflect genotype, environment, or both.",
        examPhrasing: "Explain what is meant by phenotypic variation.",
        tags: ["variation"],
      },
      {
        id: "t17-1-f2",
        noteId: "t17-1",
        difficulty: 1,
        front: "Genetic vs environmental example pair (syllabus classics).",
        back: "Genetic: e.g. ABO blood group. Environmental: e.g. suntan from UV exposure.",
        examPhrasing: "Give one genetic and one environmental source of phenotypic variation.",
        tags: ["examples"],
      },
      {
        id: "t17-1-f3",
        noteId: "t17-1",
        difficulty: 2,
        front: "Discontinuous variation — recognise from data.",
        back: "Distinct categories, few or no intermediates; bar charts show separate classes.",
        examPhrasing: "What is discontinuous variation?",
        tags: ["discontinuous"],
      },
      {
        id: "t17-1-f4",
        noteId: "t17-1",
        difficulty: 2,
        front: "Continuous variation — recognise from data.",
        back: "Range of measurements with many intermediates; often roughly normal in large samples.",
        examPhrasing: "What is continuous variation?",
        tags: ["continuous"],
      },
      {
        id: "t17-1-f5",
        noteId: "t17-1",
        difficulty: 2,
        front: "Genetic basis: discontinuous vs continuous (short).",
        back: "Discontinuous: often one/few major genes. Continuous: usually polygenic + environment.",
        examPhrasing: "Explain the genetic basis of discontinuous and continuous variation.",
        tags: ["polygenic"],
      },
      {
        id: "t17-1-f6",
        noteId: "t17-1",
        difficulty: 3,
        front: "t-test: null hypothesis (means).",
        back: "H0: no significant difference between the two population means being compared.",
        examPhrasing: "State a suitable null hypothesis for a t-test comparing two samples.",
        tags: ["t-test"],
      },
      {
        id: "t17-1-f7",
        noteId: "t17-1",
        difficulty: 3,
        front: "t-test: decision rule vs critical value (p = 0.05).",
        back: "If calculated |t| ≥ critical t, reject H0 (significant difference); otherwise fail to reject H0.",
        examPhrasing: "How do you use the critical value of t?",
        tags: ["t-test"],
      },
      {
        id: "t17-1-f8",
        noteId: "t17-1",
        difficulty: 4,
        front: "Non-significant t-test — what it does NOT prove.",
        back: "It does not prove populations are identical; only that evidence against H0 did not reach the chosen level.",
        examPhrasing: "Why is a non-significant result not proof of no difference?",
        tags: ["statistics"],
      },
      {
        id: "t17-1-f9",
        noteId: "t17-1",
        difficulty: 4,
        front: "Genotype–environment interaction (height).",
        back: "Similar alleles can yield different adult height if nutrition or disease histories differ during growth.",
        examPhrasing: "Explain how two siblings may differ in height despite similar genotypes.",
        tags: ["interaction"],
      },
      {
        id: "t17-1-f10",
        noteId: "t17-1",
        difficulty: 5,
        front: "t-test validity — independence (concept).",
        back: "Each measurement should not be tied to another in a way that breaks independence (e.g. pseudo-replication); teaching also stresses rough normality for parametric t-tests.",
        examPhrasing: "When is a t-test between two means appropriate?",
        tags: ["t-test"],
      },
    ],
  },

  "t17-2": {
    noteId: "t17-2",
    drills: [
      {
        id: "t17-2-d1",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 2,
        marks: 7,
        stem: "Explain why natural selection occurs in populations, using the ideas of reproductive potential, competition for limited resources, differences in survival and reproduction, and inheritance of alleles.",
        modelAnswerPoints: [
          "Populations can produce more offspring than the environment can support → intraspecific competition / struggle for existence.",
          "Heritable variation means some individuals are better adapted and more likely to survive and reproduce.",
          "Those individuals pass advantageous alleles to offspring more often → allele frequencies change over generations.",
        ],
        workedSolution: [
          "Most species could increase in number very quickly if every zygote survived and reproduced, yet in stable habitats energy, nutrients, nesting sites, and mates are finite, so many offspring fail to survive or fail to breed, which sets up competition within and sometimes between species.",
          "Because individuals differ in heritable traits affecting survival and fertility in that environment—camouflage, digestion efficiency, disease resistance, courtship success—some phenotypes leave disproportionately more descendants than others, which is differential reproductive success.",
          "Alleles associated with those successful phenotypes are therefore transmitted to the next generation at higher frequency than alleles associated with poorer performance, so the population gene pool changes across generations in a direction shaped by the environment.",
          "Natural selection is thus a population-level consequence of variable reproduction linked to heritable variation under constraint, not an intentional change within a single organism’s lifetime.",
        ],
        commonMistake:
          "Personifying evolution (‘the species wanted to adapt’) instead of describing differential survival and reproduction of heritable variants.",
        tags: ["natural-selection"],
      },
      {
        id: "t17-2-d2",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Compare stabilising, directional and disruptive natural selection. For each pattern, state which phenotypes are favoured relative to the population mean and describe the typical effect on the spread of variation.",
        modelAnswerPoints: [
          "Stabilising: favours intermediates; selects against extremes; variance often decreases around an unchanged mean.",
          "Directional: favours one extreme; mean shifts toward that extreme.",
          "Disruptive: favours both extremes; can reduce intermediates and increase bimodality / divergence.",
        ],
        workedSolution: [
          "Stabilising selection occurs when intermediate phenotypes have highest fitness, for example human birth mass where very small and very large babies face higher risk, so selection removes extreme values and tightens the distribution around the optimum while leaving the mean near the centre.",
          "Directional selection occurs when the environment changes or a novel selective agent appears so that one tail of the trait distribution has highest fitness, as when darker moths survive bird predation better on soot-darkened bark, shifting the mean colour score over generations toward that favoured extreme.",
          "Disruptive selection occurs when two contrasting environments or mating niches within the same population reward opposite extremes more than intermediates, which can hollow out the middle of the distribution and, if coupled with assortative mating or ecological separation, set the stage for divergence within the population.",
          "Examination answers should keep the three names tied tightly to which part of the distribution is favoured, not merely repeat ‘survival of the fittest’ for all three.",
        ],
        commonMistake:
          "Swapping directional and disruptive definitions, or claiming stabilising always moves the mean sharply.",
        tags: ["selection-modes"],
      },
      {
        id: "t17-2-d3",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Distinguish natural selection, genetic drift, the founder effect and the bottleneck effect as mechanisms that can change allele frequencies. Emphasise which processes are adaptive versus random and why small population size matters for drift.",
        modelAnswerPoints: [
          "Selection: non-random; alleles change frequency because linked phenotypes have different fitness.",
          "Genetic drift: random sampling of alleles between generations; stronger in small populations; can fix or lose alleles.",
          "Founder effect: small group starts new population; allele frequencies may differ by chance from source.",
          "Bottleneck: catastrophic shrinkage; survivors’ allele frequencies may not represent the former gene pool; drift intensifies after bottleneck.",
        ],
        workedSolution: [
          "Natural selection is a systematic bias: if carriers of allele A survive drought better, A rises because the environment consistently rewards that phenotype, so frequency change tracks fitness differences rather than coin tosses at fertilisation.",
          "Genetic drift is the converse in spirit: in every finite population, some individuals happen to leave more offspring by chance even when alleles are neutral, and the smaller the breeding population, the larger the expected random walk in allele frequency from one generation to the next.",
          "The founder effect is a special case of drift at colonisation: when a few individuals establish a new island or lake population, their genotypes may contain a random subset of the mainland’s variation, so rare alleles can become common or common alleles absent without any selective story.",
          "A bottleneck squeezes a once-large population through a severe crash—disease, hunting, climate—so the handful of survivors determine which alleles persist, and subsequent generations rebuild numbers from that narrowed sample, magnifying drift until mutation and migration restore variation.",
          "Therefore examiners expect you to label selection as adaptive (environment-driven) and drift, founder, and bottleneck components as sampling phenomena whose strength scales inversely with effective population size.",
        ],
        commonMistake:
          "Calling all allele-frequency change ‘selection’, or treating founder and bottleneck as selective forces rather than sampling extremes.",
        tags: ["drift", "founder", "bottleneck"],
      },
      {
        id: "t17-2-d4",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Outline how the spread of antibiotic resistance in a bacterial population illustrates natural selection, mentioning variation, differential survival and reproduction, and change in allele frequency.",
        modelAnswerPoints: [
          "Population shows genetic variation in resistance (mutation or horizontal gene transfer).",
          "Antibiotic imposes selection: susceptible bacteria die or reproduce less; resistant forms survive better.",
          "Resistant bacteria reproduce → resistance alleles / genes increase in frequency; misuse increases selection pressure.",
        ],
        workedSolution: [
          "Before treatment, a large bacterial culture typically harbours rare resistant mutants or plasmids carrying resistance genes, so variation in susceptibility is already present rather than created magically by the drug.",
          "When an antibiotic reaches inhibitory concentrations in the host, sensitive cells whose ribosomes, cell-wall enzymes, or efflux systems are vulnerable undergo growth arrest or lysis, whereas cells with protective changes continue dividing, which is differential survival and reproduction.",
          "The surviving lineage transmits resistance determinants vertically to daughter cells and sometimes horizontally by conjugation or transformation, so the frequency of resistance alleles in the population rises over serial generations or serial treatments.",
          "Clinical overuse narrows the effective population of susceptible bacteria in repeated episodes, strengthening directional selection for resistance and explaining why multidrug regimes and stewardship matter beyond the molecular details you must quote in an essay.",
        ],
        commonMistake:
          "Saying the antibiotic ‘causes’ the mutation in a Lamarckian way in the same sentence as selection; separate variation origin from selection sorting it.",
        tags: ["antibiotics"],
      },
      {
        id: "t17-2-d5",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "State the Hardy–Weinberg equations for a two-allele autosomal gene (allelic frequencies p and q). List the conditions under which the principle applies, and explain briefly why violation of any one condition can cause departure from predicted genotype frequencies.",
        modelAnswerPoints: [
          "Equations: p + q = 1; p^2 + 2pq + q^2 = 1 (as given on the data sheet).",
          "Conditions: large population; random mating; no mutation; no migration; no natural selection.",
          "If a condition fails, allele or genotype frequencies can change or non-random mating can reshape genotype ratios without those specific p^2, 2pq, q^2 expectations.",
        ],
        workedSolution: [
          "For one gene with two alleles at frequencies p and q, the Hardy–Weinberg principle uses the two equations provided in the mathematical requirements: first, the allele frequencies sum to unity, and second, the expected genotype frequencies are p^2 for the homozygote of the first allele, 2pq for heterozygotes, and q^2 for the homozygote of the second allele under random union of gametes.",
          "The equilibrium picture requires a very large population so binomial sampling error is negligible, random mating so genotype frequencies follow from allele frequencies alone, no mutation so p and q do not change from new copies, no migration so foreign alleles do not enter, and no selection so all genotypes contribute equally to the next generation’s pool of gametes.",
          "If population size is small, drift randomly shifts p; if mating is assortative, heterozygotes can be fewer than 2pq predicts; mutation and migration inject or remove alleles; selection changes genotype contributions—any of these breaks the assumptions behind the simple quadratic formula, which is why observed counts may deviate from prediction.",
        ],
        commonMistake:
          "Using p^2 + 2pq + q^2 = 1 while forgetting to state that it is a null model for ‘no evolution’ with explicit assumptions.",
        tags: ["hardy-weinberg"],
      },
      {
        id: "t17-2-d6",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "In a large randomly mating population of snails, shell banding is determined by a single gene with two alleles: B (dominant) and b (recessive). Among 800 snails, 32 have the recessive phenotype. Assuming Hardy–Weinberg equilibrium applies and using the equations p + q = 1 and p^2 + 2pq + q^2 = 1 given on the data sheet, calculate q, p, and the expected numbers of homozygous dominant, heterozygous and homozygous recessive individuals (show working).",
        modelAnswerPoints: [
          "Recessive phenotype frequency = 32/800 = 0.04 = q^2.",
          "q = sqrt(0.04) = 0.2; p = 1 − 0.2 = 0.8.",
          "Expected genotype frequencies: p^2 = 0.64, 2pq = 0.32, q^2 = 0.04.",
          "Expected counts ×800: 512 BB, 256 Bb, 32 bb (accept rounding if method clear).",
        ],
        workedSolution: [
          "Only bb individuals show the recessive phenotype, so their observed proportion estimates q^2 under equilibrium: 32 divided by 800 equals 0.04.",
          "Taking the square root gives q = 0.2 because allele frequency is non-negative, then p = 1 − q = 0.8 from the allele equation printed on the data sheet.",
          "The genotype equation p^2 + 2pq + q^2 = 1 yields p^2 = 0.64 for BB, 2pq = 0.32 for heterozygotes carrying the dominant phenotype, and q^2 = 0.04 matching the recessive class.",
          "Multiplying each genotype frequency by the population size 800 predicts 512 homozygous dominant snails, 256 heterozygotes, and 32 homozygous recessive snails, which reproduces the input recessive count by construction and illustrates how a phenotype frequency pins down q in examination calculations.",
        ],
        commonMistake:
          "Using the recessive phenotype frequency as q instead of q^2, or forgetting to convert frequencies back to expected counts.",
        tags: ["hardy-weinberg", "calculation"],
      },
      {
        id: "t17-2-d7",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "In humans, assume a rare autosomal recessive disease affects 1 in 10 000 newborns in a large city where mating is random and the other Hardy–Weinberg assumptions approximately hold. Using p + q = 1 and p^2 + 2pq + q^2 = 1 as given on the data sheet, calculate the frequency of the disease allele q, the carrier (heterozygote) frequency 2pq, and express the carrier proportion as about ‘1 in …’ people (show working).",
        modelAnswerPoints: [
          "Disease phenotype (homozygous recessive) frequency = 1/10 000 = 0.0001 = q^2.",
          "q = sqrt(0.0001) = 0.01; p ≈ 0.99.",
          "Carrier frequency 2pq ≈ 2 × 0.99 × 0.01 = 0.0198 ≈ 0.02.",
          "About 1 in 50 carriers (accept 1 in 51 if rounding explained).",
        ],
        workedSolution: [
          "Let the disease allele be recessive with frequency q; affected infants are genotype aa with frequency q^2 under Hardy–Weinberg, so q^2 = 1/10 000 = 1.0 × 10^-4.",
          "Thus q = 0.01 and p = 1 − q = 0.99 using the allele-frequency equation from the data sheet.",
          "Carriers are heterozygotes at frequency 2pq; substituting gives 2 × 0.99 × 0.01 = 0.0198, which rounds to about 0.02, meaning roughly two percent of the population carries one copy despite the illness being rare in homozygotes.",
          "The reciprocal of 0.0198 is about 50.5, so a conventional examination phrase is ‘approximately 1 in 50 individuals is a carrier’, highlighting how recessive diseases can hide abundant heterozygosity.",
        ],
        commonMistake:
          "Equating disease incidence directly to q rather than q^2, which massively overestimates allele frequency.",
        tags: ["hardy-weinberg", "calculation"],
      },
      {
        id: "t17-2-d8",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe the principles of selective breeding (artificial selection). Explain how breeders change allele frequencies across generations, and outline how disease resistance can be introduced into wheat or rice varieties using selection and crossing.",
        modelAnswerPoints: [
          "Artificial selection: humans choose parents with desired traits; offspring screened; process repeated over generations.",
          "Increases frequency of favourable alleles; may reduce genetic diversity in a pure line if selection is intense.",
          "Disease resistance: cross resistant × elite lines; select progeny showing resistance and agronomic quality; repeat until stable resistant variety.",
        ],
        workedSolution: [
          "Selective breeding is the deliberate choice of which individuals reproduce based on phenotypes humans value—yield, taste, disease reaction—so that alleles correlated with those phenotypes are over-represented in the next generation compared with a random mating baseline.",
          "By repeating selection after each cross, breeders enrich target loci while trying to retain background genes needed for local adaptation, which is why backcrossing schemes appear in advanced syllabuses even when you only outline the logic.",
          "For cereal disease resistance, a donor line carrying a resistance allele to a fungal pathogen may be crossed to a high-yielding but susceptible elite cultivar, and subsequent generations are inoculated or field-tested so that only plants showing strong resistance and acceptable yield are advanced.",
          "Molecular markers sometimes accelerate this, but the examination-level story is phenotypic screening plus crossing until a uniform, true-breeding resistant variety is released to farmers.",
        ],
        commonMistake:
          "Equating artificial selection with genetic engineering; selective breeding sorts existing variation by breeding choice.",
        tags: ["artificial-selection"],
      },
      {
        id: "t17-2-d9",
        noteId: "t17-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Outline how inbreeding and hybridisation are used together in maize improvement to produce vigorous, uniform hybrid varieties, contrasting the roles of pure lines and the F1 hybrid generation.",
        modelAnswerPoints: [
          "Inbreeding (selfing) produces homozygous pure lines that are phenotypically uniform but may show inbreeding depression alone.",
          "Crossing two distinct inbred lines yields F1 hybrids with heterozygosity and hybrid vigour (high yield, uniformity).",
          "Farmers often buy F1 seed each season because F2 segregation breaks uniformity.",
        ],
        workedSolution: [
          "Maize breeders self-pollinate promising plants for many generations until lines become highly homozygous at most loci, which fixes desirable alleles but also exposes deleterious recessives, often lowering vigour within each line—a pattern called inbreeding depression when lines are compared to heterozygous hybrids.",
          "When two genetically distinct inbred lines are crossed, the F1 plants are uniformly heterozygous at loci that differed between parents, and dominant favourable alleles at many loci mask recessive load from either parent, frequently producing taller, higher-yielding, more uniform stands than either parent line alone, which is heterosis or hybrid vigour.",
          "Because the F2 generation segregates genotypes when F1 plants intercross, agronomic uniformity collapses, so commercial maize production replants F1 seed purchased from breeders rather than saving seed, which economically reinforces the breeding cycle.",
        ],
        commonMistake:
          "Claiming hybrid maize is produced only by random outcrossing with no inbred line development step.",
        tags: ["maize", "hybrid"],
      },
      {
        id: "t17-2-d10",
        noteId: "t17-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which scenario best illustrates directional selection?",
        options: [
          { id: "A", text: "Medium-sized eggs survive best; very small and very large eggs die more often, keeping the mean clutch size stable." },
          { id: "B", text: "After a cold snap, only the most cold-tolerant individuals in the tail of the distribution survive and breed, shifting the population mean toward greater cold tolerance." },
          { id: "C", text: "A volcanic island is colonised by four birds carrying a random subset of mainland alleles; no selective difference between genotypes." },
          { id: "D", text: "Two habitats favour opposite colour morphs equally; intermediate morphs are preyed upon most heavily." },
        ],
        correctOptionId: "B",
        explanation:
          "One extreme (highest cold tolerance) is favoured and the mean shifts—classic directional selection.",
        distractorRationale: {
          A: "Selection against both extremes describes stabilising selection.",
          C: "Random sampling during colonisation emphasises founder / drift, not directional fitness differences.",
          D: "Favouring both extremes against intermediates describes disruptive selection.",
        },
        tags: ["directional", "mcq"],
      },
    ],
    flashcards: [
      {
        id: "t17-2-f1",
        noteId: "t17-2",
        difficulty: 1,
        front: "Natural selection — core population argument.",
        back: "Overproduction of offspring → competition → heritable differences in survival/reproduction → allele frequency change.",
        examPhrasing: "Explain why natural selection occurs.",
        tags: ["natural-selection"],
      },
      {
        id: "t17-2-f2",
        noteId: "t17-2",
        difficulty: 1,
        front: "Stabilising selection (one line).",
        back: "Favours intermediate phenotypes; selects against extremes; variance often shrinks.",
        examPhrasing: "What is stabilising selection?",
        tags: ["stabilising"],
      },
      {
        id: "t17-2-f3",
        noteId: "t17-2",
        difficulty: 2,
        front: "Directional selection (one line).",
        back: "Favours one extreme; shifts the population mean in one direction.",
        examPhrasing: "What is directional selection?",
        tags: ["directional"],
      },
      {
        id: "t17-2-f4",
        noteId: "t17-2",
        difficulty: 2,
        front: "Disruptive selection (one line).",
        back: "Favours both extremes; acts against intermediates; can promote divergence.",
        examPhrasing: "What is disruptive selection?",
        tags: ["disruptive"],
      },
      {
        id: "t17-2-f5",
        noteId: "t17-2",
        difficulty: 3,
        front: "Founder effect vs bottleneck (memory hook).",
        back: "Founder: new population from few colonists. Bottleneck: catastrophic shrinkage of an existing population.",
        examPhrasing: "Distinguish founder effect and bottleneck.",
        tags: ["drift"],
      },
      {
        id: "t17-2-f6",
        noteId: "t17-2",
        difficulty: 3,
        front: "Antibiotic resistance — selection wording.",
        back: "Variation exists; antibiotic removes susceptible bacteria; resistant survivors reproduce; resistance increases.",
        examPhrasing: "How does antibiotic resistance illustrate natural selection?",
        tags: ["antibiotics"],
      },
      {
        id: "t17-2-f7",
        noteId: "t17-2",
        difficulty: 4,
        front: "Hardy–Weinberg equations (two-allele).",
        back: "p + q = 1; p^2 + 2pq + q^2 = 1 (provided on data sheet).",
        examPhrasing: "State the Hardy–Weinberg equations.",
        tags: ["hardy-weinberg"],
      },
      {
        id: "t17-2-f8",
        noteId: "t17-2",
        difficulty: 4,
        front: "Hardy–Weinberg equilibrium conditions (list).",
        back: "Large population; random mating; no mutation; no migration; no selection.",
        examPhrasing: "When can the Hardy–Weinberg principle be applied?",
        tags: ["hardy-weinberg"],
      },
      {
        id: "t17-2-f9",
        noteId: "t17-2",
        difficulty: 5,
        front: "Selective breeding — definition.",
        back: "Humans choose parents with desired traits to change allele frequencies in domesticated lines over generations.",
        examPhrasing: "What is selective breeding?",
        tags: ["artificial-selection"],
      },
      {
        id: "t17-2-f10",
        noteId: "t17-2",
        difficulty: 5,
        front: "Syllabus selective-breeding examples (quick triple).",
        back: "Wheat/rice disease resistance; maize inbreds + F1 hybrid vigour; dairy cattle milk yield.",
        examPhrasing: "Give examples of selective breeding from the syllabus.",
        tags: ["examples"],
      },
    ],
  },

  "t17-3": {
    noteId: "t17-3",
    drills: [
      {
        id: "t17-3-d1",
        noteId: "t17-3",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Outline the theory of evolution as a process that produces new species from pre-existing species over time, explicitly linking population gene pools, allele-frequency change between generations, and the eventual development of reproductive isolation.",
        modelAnswerPoints: [
          "Evolution: change in allele frequencies in a population’s gene pool over generations.",
          "Accumulated genetic differences between lineages; can lead to reproductive isolation.",
          "Isolated gene pools diverge → new species can form while sharing ancestry with earlier species.",
        ],
        workedSolution: [
          "At the scale the syllabus emphasises, evolution is not an individual becoming stronger but populations changing genetically: the summed alleles in all breeding individuals—the gene pool—can shift in frequency because of selection, drift, mutation, and migration.",
          "When two lineages experience independent histories of those forces, perhaps because they occupy different environments or because mating is blocked, their genomes accumulate differences in coding and regulatory sequences, which can alter proteins, developmental timing, or behaviour.",
          "If divergence proceeds far enough that successful interbreeding drops—through prezygotic barriers such as mating seasons or postzygotic barriers such as hybrid infertility—the lineages function as separate species under the biological species concept, even though they descended from a common ancestral population, which is the ‘new from old’ headline of evolutionary theory.",
        ],
        commonMistake:
          "Describing evolution as intentional improvement of individuals rather than population-level allele-frequency change with isolation.",
        tags: ["evolution"],
      },
      {
        id: "t17-3-d2",
        noteId: "t17-3",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Discuss how comparison of DNA sequences from homologous genes can reveal evolutionary relationships between species, including how similarity relates to recency of common ancestry and how phylogenetic trees summarise hypotheses about descent.",
        modelAnswerPoints: [
          "Homologous regions aligned; nucleotide differences counted.",
          "Fewer differences → usually closer relationship / more recent common ancestor (assuming broadly similar rates).",
          "Trees diagram branching patterns inferred from molecular (and other) evidence; topology is a hypothesis tested by more data.",
        ],
        workedSolution: [
          "Orthologous genes inherited from a shared ancestor can be sequenced from different species, aligned base by base, and the number of substitutions or indels tabulated, which quantifies how much neutral and selected change has accumulated since lineages split.",
          "Under many models, more similar sequences imply a shorter separation time or a slower substitution rate, so molecular comparisons often recover the same major groupings as morphology, though horizontal transfer and rate variation complicate simple clocks.",
          "Phylogenetic trees depict proposed ancestor–descendant relationships as branches; sister taxa share a node representing their most recent common ancestor, and the whole diagram is a hypothesis summarising current evidence rather than a direct eyewitness history.",
          "Adding taxa or genes can refine tree topology, which is why examiners like language about supporting or revising relationships rather than ‘proving’ them absolutely from one gene alone.",
        ],
        commonMistake:
          "Claiming identical DNA means identical species rank, or that one gene tree can never conflict with species history.",
        tags: ["DNA", "phylogeny"],
      },
      {
        id: "t17-3-d3",
        noteId: "t17-3",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain how genetic isolation between populations contributes to speciation, mentioning reduction of gene flow and the independent action of mutation, natural selection and genetic drift in each lineage.",
        modelAnswerPoints: [
          "Isolation reduces or stops interbreeding → gene flow reduced.",
          "Each population has independent allele-frequency trajectories under mutation, selection, drift.",
          "Genetic divergence can produce reproductive barriers (pre- and postzygotic).",
        ],
        workedSolution: [
          "Speciation requires mechanisms that limit allele exchange, whether geography, ecology, behaviour, or chromosomal incompatibility, because ongoing gene flow would homogenise populations and oppose divergence.",
          "Once effective isolation exists, a novel advantageous mutation can sweep in one range but not the other, or drift can fix neutral variants independently, so allele frequencies and trait means diverge even under similar environments.",
          "As genetic incompatibilities accumulate—mismatched courtship signals, hybrid developmental failure—hybrids become rare or unfit, reinforcing isolation and completing the transition to separate species in the conceptual narrative the mark scheme expects.",
        ],
        commonMistake:
          "Saying isolation instantly creates new species without mentioning divergence time and reproductive barriers.",
        tags: ["speciation", "isolation"],
      },
      {
        id: "t17-3-d4",
        noteId: "t17-3",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Explain how allopatric speciation can follow geographical separation of a formerly continuous species. Include how physical barriers reduce gene flow and how independent evolution in separate ranges can produce reproductive isolation even if secondary contact occurs later.",
        modelAnswerPoints: [
          "Allopatric: speciation with geographical separation.",
          "Barrier (mountain, water, fragmentation) prevents mating and allele exchange.",
          "Populations diverge by selection, drift, mutation under different conditions; reproductive barriers may evolve.",
          "If ranges later overlap, barriers may persist (behavioural, mechanical, genetic) preventing fusion.",
        ],
        workedSolution: [
          "Allopatric speciation begins when a physical feature of the landscape—new mountain uplift, river capture, island formation—splits a continuous population into groups that cannot routinely interbreed because dispersal across the barrier is rare for that organism.",
          "Each fragment then experiences its own selective pressures and sampling history: an island population might evolve smaller size under resource limitation while the mainland retains larger average body size, and neutral colour variants might drift to fixation independently.",
          "Over long periods, chromosomal rearrangements, courtship changes, or ecological niche shifts accumulate until hybrids, if any are produced upon rare contact, show reduced fertility or survival, which are postzygotic barriers.",
          "Should glaciers retreat or land bridges reform, secondary contact tests those barriers: if they hold, the taxa coexist as biological species; if not, populations may merge, so allopatry is best viewed as a stage that permits divergence until intrinsic isolation solidifies.",
        ],
        commonMistake:
          "Naming a barrier but not explaining cessation of gene flow or independent divergence.",
        tags: ["allopatric"],
      },
      {
        id: "t17-3-d5",
        noteId: "t17-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Explain how sympatric speciation can occur without geographical separation, using ecological separation and behavioural separation (including differences in resource use, microhabitat, or breeding time) to show how gene flow can fall within one area.",
        modelAnswerPoints: [
          "Sympatric: divergence in broadly the same geographical area without a classic external barrier.",
          "Ecological separation: different resources / microhabitats reduce encounter and mating.",
          "Behavioural / temporal separation: different signals or breeding seasons reduce interbreeding.",
          "Assortative mating + divergent selection can build reproductive barriers.",
        ],
        workedSolution: [
          "Sympatric speciation is challenging because individuals still share a map location, so reduction of gene flow must come from intrinsic preferences and niche partitioning rather than an obvious mountain range.",
          "If a subset of a fish population specialises on shallow vegetation while another specialises on deep open water, foraging overlap and mating encounters may drop even though a single lake contains both, especially if spawning sites differ.",
          "Temporal isolation reinforces this when breeding seasons cease to overlap: one group spawns in early spring, another in midsummer, so gametes never meet despite geographic overlap, which is a behavioural or physiological barrier under the syllabus heading.",
          "When mating is assortative—individuals prefer partners using the same habitat or signal—selection can tighten differences in traits favoured in each niche, and alleles flow less between incipient species, allowing divergence until hybrids are disfavoured.",
        ],
        commonMistake:
          "Claiming sympatric speciation requires a physical barrier, which contradicts the definition.",
        tags: ["sympatric"],
      },
      {
        id: "t17-3-d6",
        noteId: "t17-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Compare allopatric and sympatric speciation under the headings: typical role of geographical barriers, main mechanisms reducing gene flow, and one strength or limitation of each model in explaining observed biodiversity.",
        modelAnswerPoints: [
          "Allopatric: external barrier stops dispersal; gene flow ends geographically; widely documented in island and vicariance cases.",
          "Sympatric: no complete external barrier; ecological/behavioural/temporal mechanisms reduce gene flow within a shared area; fewer classic textbook examples but syllabus-required.",
        ],
        workedSolution: [
          "Allopatric speciation foregrounds extrinsic landscape change: when valleys or oceans separate populations, the explanation for initial isolation is simple geography, which is easy to map onto fossils and plate tectonics, though not every barrier automatically yields species pairs if divergence is slow.",
          "Sympatric speciation foregrounds intrinsic splitting: host shifts in phytophagous insects, polymorphic mating signals in crickets, or polyploidy in plants can initiate divergence while individuals still live intermingled, which explains some rapid radiations but demands tighter evidence because panmixia could erase differences without strong assortative mating.",
          "A balanced examination answer notes that both pathways reduce gene flow, yet the default narrative for many vertebrate radiations is allopatry first, whereas plants and insects provide textbook sympatric or quasi-sympatric cases, matching the syllabus’s requirement to know both labels and mechanisms.",
        ],
        commonMistake:
          "Stating that sympatric means ‘no isolation’—isolation is present, but not primarily geographical.",
        tags: ["comparison"],
      },
      {
        id: "t17-3-d7",
        noteId: "t17-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Two populations of a moth species are separated when a new mountain range forms. Over time they accumulate genetic differences and fail to produce fertile hybrids when crossed in the laboratory. Which description fits best?",
        options: [
          { id: "A", text: "Sympatric speciation driven solely by behavioural preference with no geographical change." },
          { id: "B", text: "Allopatric speciation initiated by geographical isolation followed by divergence and reproductive isolation." },
          { id: "C", text: "Speciation by genetic drift only, which rules out any role for natural selection." },
          { id: "D", text: "Instantaneous speciation in one generation without allele-frequency change." },
        ],
        correctOptionId: "B",
        explanation:
          "A geographical barrier initiating divergence is the classic allopatric pathway; hybrid infertility indicates evolved reproductive isolation.",
        distractorRationale: {
          A: "Sympatric speciation does not begin with a new mountain barrier splitting the range.",
          C: "Drift and selection can both contribute; drift-only is not implied.",
          D: "Speciation is a population process over many generations, not a single-generation flip.",
        },
        tags: ["allopatric", "mcq"],
      },
      {
        id: "t17-3-d8",
        noteId: "t17-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Aligned protein-coding DNA from the same gene is compared for three bird species. Species P and Q differ by 6 substitutions; P and R differ by 38 substitutions; Q and R differ by 40 substitutions. Which evolutionary inference is most consistent with these data alone?",
        options: [
          { id: "A", text: "P and Q share a more recent common ancestor with each other than either does with R." },
          { id: "B", text: "Species R is not related to P or Q because the substitution counts are non-zero." },
          { id: "C", text: "The gene sequences prove the three species must occupy identical niches today." },
          { id: "D", text: "Greater sequence difference always means faster mutation rate in that lineage only." },
        ],
        correctOptionId: "A",
        explanation:
          "Smaller pairwise divergence between P and Q suggests they diverged more recently from each other than from R, assuming broadly comparable rates along branches.",
        distractorRationale: {
          B: "All compared sequences are homologous; non-zero differences indicate relatedness with divergence, not unrelatedness.",
          C: "Molecular similarity does not determine current ecological niche identity.",
          D: "Rate differences are possible but cannot be concluded from raw counts alone without a clock model.",
        },
        tags: ["DNA", "mcq"],
      },
      {
        id: "t17-3-d9",
        noteId: "t17-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Which barrier to gene flow is best described as postzygotic?",
        options: [
          { id: "A", text: "Different bird songs so mates rarely recognise each other." },
          { id: "B", text: "Flowering at different months so pollen transfer does not occur." },
          { id: "C", text: "Hybrid offspring between two plant lineages are viable but sterile." },
          { id: "D", text: "One butterfly species feeds only on milkweed while a sibling species uses a different host in the same meadow." },
        ],
        correctOptionId: "C",
        explanation:
          "Hybrid sterility acts after a zygote has formed—postzygotic—even though the hybrid appeared viable.",
        distractorRationale: {
          A: "Mate recognition is a prezygotic behavioural barrier.",
          B: "Temporal isolation prevents fertilisation—prezygotic.",
          D: "Ecological separation reduces encounter rate—typically viewed as prezygotic isolation.",
        },
        tags: ["barriers", "mcq"],
      },
      {
        id: "t17-3-d10",
        noteId: "t17-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Which statement about evolution and speciation matches standard A Level teaching?",
        options: [
          { id: "A", text: "Evolution requires every allele change to increase complexity or ‘perfect’ the organism." },
          { id: "B", text: "A gene pool is the total set of alleles in a population, and evolution includes allele-frequency change across generations." },
          { id: "C", text: "Once two populations evolve different mating songs in the same forest, gene flow between them must be zero in every gene." },
          { id: "D", text: "DNA evidence is irrelevant if morphological data are available." },
        ],
        correctOptionId: "B",
        explanation:
          "Evolution is defined at population level as change in allele frequencies; direction is not universally toward complexity.",
        distractorRationale: {
          A: "Evolution has no mandated progressive ladder; fitness is context-dependent.",
          C: "Partial barriers reduce gene flow but rarely imply absolute zero flow at all loci instantly.",
          D: "Molecular data are central to modern relationship inference.",
        },
        tags: ["evolution", "mcq"],
      },
    ],
    flashcards: [
      {
        id: "t17-3-f1",
        noteId: "t17-3",
        difficulty: 1,
        front: "Evolution — population definition (gene pool).",
        back: "Change in allele frequencies in a population’s gene pool from generation to generation.",
        examPhrasing: "Outline the theory of evolution in terms of gene pools.",
        tags: ["evolution"],
      },
      {
        id: "t17-3-f2",
        noteId: "t17-3",
        difficulty: 1,
        front: "Speciation — minimal idea.",
        back: "Lineages diverge until they are reproductively isolated and function as separate species.",
        examPhrasing: "What is speciation?",
        tags: ["speciation"],
      },
      {
        id: "t17-3-f3",
        noteId: "t17-3",
        difficulty: 2,
        front: "DNA sequences and relatedness.",
        back: "More similar homologous sequences usually imply closer evolutionary relationship / more recent common ancestor.",
        examPhrasing: "How can DNA show evolutionary relationships?",
        tags: ["DNA"],
      },
      {
        id: "t17-3-f4",
        noteId: "t17-3",
        difficulty: 2,
        front: "Phylogenetic tree — what it represents.",
        back: "A hypothesis of branching descent based on evidence such as molecular sequences; can be revised with new data.",
        examPhrasing: "What is a phylogenetic tree?",
        tags: ["phylogeny"],
      },
      {
        id: "t17-3-f5",
        noteId: "t17-3",
        difficulty: 3,
        front: "Gene flow vs isolation (one sentence).",
        back: "Gene flow homogenises populations; isolation lets them diverge independently.",
        examPhrasing: "Why does genetic isolation matter for speciation?",
        tags: ["isolation"],
      },
      {
        id: "t17-3-f6",
        noteId: "t17-3",
        difficulty: 3,
        front: "Allopatric speciation — keyword.",
        back: "Geographical separation reduces interbreeding; populations diverge in isolation.",
        examPhrasing: "Explain allopatric speciation.",
        tags: ["allopatric"],
      },
      {
        id: "t17-3-f7",
        noteId: "t17-3",
        difficulty: 4,
        front: "Sympatric speciation — keyword.",
        back: "Divergence without geographical barrier; ecological and/or behavioural separation reduces gene flow in the same area.",
        examPhrasing: "Explain sympatric speciation.",
        tags: ["sympatric"],
      },
      {
        id: "t17-3-f8",
        noteId: "t17-3",
        difficulty: 4,
        front: "Prezygotic vs postzygotic (examples).",
        back: "Pre: mating time, behaviour, mechanical fit. Post: hybrid inviability or sterility.",
        examPhrasing: "Give examples of prezygotic and postzygotic barriers.",
        tags: ["barriers"],
      },
      {
        id: "t17-3-f9",
        noteId: "t17-3",
        difficulty: 5,
        front: "Molecular clock caveat (short).",
        back: "Substitution rates can vary among lineages; trees are best supported with multiple genes and fossils where possible.",
        examPhrasing: "Why might DNA divergence not map simply to time?",
        tags: ["DNA"],
      },
      {
        id: "t17-3-f10",
        noteId: "t17-3",
        difficulty: 5,
        front: "Secondary contact (allopatry reminder).",
        back: "If barrier disappears, species may hybridise or coexist depending on whether reproductive barriers remain strong.",
        examPhrasing: "What can happen when isolated populations meet again?",
        tags: ["allopatric"],
      },
    ],
  },
};
