import type { SubtopicPracticePack } from "./types";

// Topic 2 practice LO crosswalk: each noteId pack maps 9701 section 2.x bullets in
// `data/syllabus/chemistry-9701-learning-outcomes.md` to drill ids in-file (short comments before t2-1–t2-4). No coverage exceptions claimed.

export const CHEMISTRY_TOPIC2_PRACTICE: Record<string, SubtopicPracticePack> = {
  // 9701 2.1: unified scale definitions (u, A_r, relative isotopic mass, M_r, relative formula mass) + weighted-mean and RFM calculations — d1–d10.
  "t2-1": {
    noteId: "t2-1",
    drills: [
      {
        id: "t2-1-d1",
        noteId: "t2-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which statement best defines relative atomic mass, A_r?",
        options: [
          {
            id: "A",
            text: "The weighted mean mass of the atoms of an element compared with 1/12 the mass of one atom of carbon-12.",
          },
          { id: "B", text: "The mass in grams of one mole of the element." },
          { id: "C", text: "The mass number of the most abundant isotope only." },
          { id: "D", text: "The mean mass of an atom compared with the mass of a hydrogen atom." },
        ],
        correctOptionId: "A",
        explanation:
          "A_r is a dimensionless ratio: average atomic mass on the carbon-12 scale (weighted by natural abundances).",
        distractorRationale: {
          B: "That describes molar mass (g mol^-1), not A_r.",
          C: "A_r uses all naturally occurring isotopes weighted by abundance, not only the commonest isotope.",
          D: "The international scale is carbon-12, not hydrogen-1.",
        },
        tags: ["Ar", "isotopes", "definitions", "9701-2.1"],
      },
      {
        id: "t2-1-d2",
        noteId: "t2-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Chlorine has isotopes of mass numbers 35 and 37 with approximate abundances 75% and 25%. What is the best value for A_r of chlorine?",
        options: [
          { id: "A", text: "35.5" },
          { id: "B", text: "36.0" },
          { id: "C", text: "35.0" },
          { id: "D", text: "37.0" },
        ],
        correctOptionId: "A",
        explanation:
          "Weighted mean ≈ (0.75)(35) + (0.25)(37) = 26.25 + 9.25 = 35.5 (to 1 d.p.).",
        distractorRationale: {
          B: "This is the simple mean of 35 and 37, ignoring the unequal abundances.",
          C: "This is the mass number of the lighter isotope only.",
          D: "This is the heavier isotope mass number only.",
        },
        tags: ["isotope-abundance", "weighted-mean", "chlorine"],
      },
      {
        id: "t2-1-d3",
        noteId: "t2-1",
        kind: "mcq",
        difficulty: 2,
        stem: "A compound has M_r = 44.0. Which expression gives its relative molecular mass on the same scale?",
        options: [
          { id: "A", text: "Mass of one molecule / (1/12 mass of one atom of ^12C)" },
          { id: "B", text: "Mass of one mole / Avogadro constant" },
          { id: "C", text: "Mass of one molecule / mass of one atom of ^1H" },
          { id: "D", text: "Sum of mass numbers in the displayed formula" },
        ],
        correctOptionId: "A",
        explanation:
          "M_r is the mass of a molecule (or formula unit) relative to 1/12 the mass of a carbon-12 atom.",
        distractorRationale: {
          B: "That ratio has units of g per atom and is not the dimensionless relative mass definition.",
          C: "Relative masses in modern chemistry are defined on the carbon-12 scale, not hydrogen.",
          D: "Mass numbers are integers for specific isotopes; M_r is a weighted-average comparison to the standard.",
        },
        tags: ["Mr", "definitions", "carbon-12-scale"],
      },
      {
        id: "t2-1-d4",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Define the term relative isotopic mass of a particular isotope on the unified atomic mass scale.",
        modelAnswerPoints: [
          "Relative isotopic mass is the mass of one atom of that isotope compared with 1/12 the mass of one atom of carbon-12 (dimensionless).",
          "Numerically it matches the mass of one atom of the isotope expressed in unified atomic mass units, u, to usual rounding.",
          "It refers to one nuclide, not an element's natural mixture.",
        ],
        workedSolution: [
          "The relative isotopic mass of a specified isotope is the mass of one atom of that isotope compared with one-twelfth of the mass of one neutral atom of the carbon-12 isotope, so it is a dimensionless number on the same scale as A_r and M_r.",
          "Because the unified atomic mass unit, u, is defined as exactly one-twelfth of the mass of a carbon-12 atom, the numerical value of the relative isotopic mass is the same as the conventional atomic mass of that nuclide in u, within usual rounding.",
          "Unlike relative atomic mass, which averages over naturally occurring isotopes of an element, relative isotopic mass refers to a single nuclide.",
        ],
        commonMistake:
          "Confusing relative isotopic mass with mass number A, or with the element's relative atomic mass averaged over isotopes.",
        tags: ["relative-isotopic-mass", "definitions", "9701-2.1"],
      },
      {
        id: "t2-1-d5",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "State what is meant by the terms mass number of a nuclide and relative atomic mass, A_r, of an element that has more than one naturally occurring isotope.",
        modelAnswerPoints: [
          "Mass number A is the proton plus neutron count in one nucleus of that isotope (a whole number for that nuclide).",
          "A_r is the weighted mean mass of atoms of the element compared with 1/12 the mass of one atom of carbon-12 (dimensionless).",
          "Illustrate with one example (e.g., chlorine with A_r ≈ 35.5 from ^35Cl and ^37Cl).",
        ],
        workedSolution: [
          "The mass number, A, of a nuclide is the total number of protons and neutrons in one nucleus of that isotope, so it is always an integer for a specified isotope.",
          "The relative atomic mass, A_r, of an element is the weighted mean mass of its atoms as they occur naturally, compared with one-twelfth of the mass of one neutral carbon-12 atom, and it is therefore usually not a whole number when more than one isotope is present.",
          "For example, natural chlorine consists mainly of isotopes with mass numbers 35 and 37, yet its tabulated A_r is about 35.5 because the lighter isotope is more abundant than the heavier one.",
        ],
        commonMistake:
          "Stating that A_r is always the mass number of the lightest or most common isotope.",
        tags: ["definitions", "mass-number", "Ar", "9701-2.1"],
      },
      {
        id: "t2-1-d6",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "The mass spectrum of neon shows peaks at m/z 20 and 22 with relative peak heights in the ratio 9 : 1. Calculate the relative atomic mass of neon to 2 decimal places.",
        modelAnswerPoints: [
          "Treat peak heights as relative numbers of ions (abundances).",
          "Convert to fractional abundances.",
          "Compute weighted mean m/z as A_r for a monatomic element.",
        ],
        workedSolution: [
          "The peak heights are in the ratio 9 : 1, so treating these as relative numbers of ions gives ten parts in total, of which nine parts correspond to m/z 20 and one part to m/z 22.",
          "The fractional abundances are therefore 9/10 = 0.90 for ^20Ne and 1/10 = 0.10 for ^22Ne.",
          "The relative atomic mass is the weighted mean of the m/z values, so A_r = (0.90 x 20) + (0.10 x 22) = 18 + 2.2 = 20.20 to two decimal places.",
        ],
        commonMistake:
          "Averaging 20 and 22 equally (21.0) instead of using the 9 : 1 abundance ratio.",
        tags: ["mass-spectrum", "abundance", "neon"],
      },
      {
        id: "t2-1-d7",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Define the term relative molecular mass, M_r, for a molecular compound, and define the term relative formula mass for an ionic compound, in each case on the unified atomic mass scale.",
        modelAnswerPoints: [
          "M_r is the mass of one molecule compared with 1/12 the mass of one atom of carbon-12 (dimensionless).",
          "Relative formula mass applies where there are no separate molecules (giant ionic/metallic/network covalent): mass of the formula unit on the same scale.",
          "For ionic compounds the term M_r is often used loosely for the formula unit mass; Cambridge distinguishes relative formula mass wording for non-molecular species.",
        ],
        workedSolution: [
          "The relative molecular mass, M_r, of a molecular substance is the mass of one molecule of that substance compared with one-twelfth of the mass of one neutral atom of the carbon-12 isotope, so it is a dimensionless number on the unified scale.",
          "For giant structures such as ionic lattices, chemists quote the relative formula mass of the formula unit — the smallest repeating set of ions represented by the written formula — again compared with one-twelfth of the mass of a carbon-12 atom.",
          "Cambridge therefore uses relative molecular mass when discrete molecules exist, and relative formula mass language for species such as NaCl or MgO where the stoichiometric formula refers to a formula unit rather than a free molecule.",
        ],
        commonMistake:
          "Claiming that an ionic crystal contains 'molecules' equal to the empirical formula without clarifying the formula-unit convention.",
        tags: ["Mr", "relative-formula-mass", "definitions", "9701-2.1"],
      },
      {
        id: "t2-1-d8",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A sample of magnesium contains three isotopes. Data: 24Mg 78.6%, 25Mg 10.1%, 26Mg 11.3%. Using mass numbers as approximate isotopic masses, calculate A_r of magnesium to 1 decimal place.",
        modelAnswerPoints: [
          "Use A_r = sum (fractional abundance x mass) for each isotope.",
          "Check abundances sum to 100% before converting to fractions.",
          "Give final answer to required precision.",
        ],
        workedSolution: [
          "Each percentage is converted to a decimal fraction, giving 0.786 for ^24Mg, 0.101 for ^25Mg, and 0.113 for ^26Mg, and these fractions add to 1.000 as required.",
          "Using the mass numbers as approximate isotopic masses, the weighted mean is A_r = (0.786 x 24) + (0.101 x 25) + (0.113 x 26).",
          "This evaluates to 18.864 + 2.525 + 2.938 = 24.327, so the relative atomic mass of magnesium is 24.3 to one decimal place.",
        ],
        commonMistake:
          "Forgetting to convert percentages to decimals, leading to impossible A_r values.",
        tags: ["three-isotopes", "weighted-mean", "magnesium"],
      },
      {
        id: "t2-1-d9",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Define the unified atomic mass unit, u, and explain its link to relative atomic mass, A_r.",
        modelAnswerPoints: [
          "State u as 1/12 the mass of one neutral atom of carbon-12.",
          "Relate isotopic mass in u to relative isotopic mass on the same scale.",
          "Relate A_r to weighted mean of relative isotopic masses.",
        ],
        workedSolution: [
          "One unified atomic mass unit, u, is defined as exactly one-twelfth of the mass of one neutral atom of the carbon-12 isotope in its ground state, so all atomic and isotopic masses are referred to this standard amount of mass.",
          "The relative isotopic mass of a nuclide is the ratio of the mass of one atom of that isotope to one unified mass unit, so its numerical value is the same as the mass of that atom expressed in u, apart from small rounding differences.",
          "The relative atomic mass of an element is the abundance-weighted mean of the relative isotopic masses of its naturally occurring isotopes, so it is a dimensionless number on the carbon-12 scale but matches the numerical value of the average atomic mass in u for a mole-based calculation.",
        ],
        commonMistake:
          "Confusing u with the gram or with the mass of one mole of substance.",
        tags: ["u", "definitions", "scale"],
      },
      {
        id: "t2-1-d10",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "Calculate the relative formula mass of aluminium sulfate, Al_2(SO_4)_3, showing how each term arises from the unified atomic mass scale. (A_r: Al = 27.0, S = 32.1, O = 16.0)",
        modelAnswerPoints: [
          "State that relative formula mass is the sum of relative atomic masses in the formula unit on the carbon-12 scale (same numerical scale as u).",
          "Count atoms correctly from brackets and subscripts: 2 Al, 3 S, 12 O.",
          "Sum: (2 x 27.0) + (3 x 32.1) + (12 x 16.0) and give the final value with unitless M_r.",
        ],
        workedSolution: [
          "The relative formula mass of an ionic compound is the mass of one formula unit compared with one-twelfth of the mass of one carbon-12 atom, so it is found by adding the relative atomic masses of all atoms shown in the written formula, using the same unified scale as for A_r and M_r.",
          "In one formula unit of Al_2(SO_4)_3 there are two aluminium atoms, three sulfur atoms, and twelve oxygen atoms, because each sulfate group contains four oxygen atoms and there are three such groups.",
          "The relative formula mass is therefore (2 x 27.0) + (3 x 32.1) + (12 x 16.0) = 54.0 + 96.3 + 192.0 = 342.3, which is quoted without units because it is a relative mass on the carbon-12 scale.",
        ],
        commonMistake:
          "Multiplying the bracket by two from Al_2 twice, or using three oxygen atoms instead of twelve from three SO_4 groups.",
        tags: ["relative-formula-mass", "Mr", "calculation", "9701-2.1"],
      },
    ],
    flashcards: [
      {
        id: "t2-1-f1",
        noteId: "t2-1",
        difficulty: 1,
        front: "What is relative atomic mass (A_r) measured relative to?",
        back: "1/12 the mass of one atom of the carbon-12 isotope (the unified scale).",
        examPhrasing: "Relative atomic mass is the weighted mean mass of atoms of the element on a scale in which one atom of carbon-12 has a mass of exactly 12 units.",
        confusionPair: "A_r vs mass number",
        tags: ["Ar", "definition"],
      },
      {
        id: "t2-1-f2",
        noteId: "t2-1",
        difficulty: 1,
        front: "What is relative molecular mass (M_r)?",
        back: "Mass of a molecule (or formula unit) relative to 1/12 the mass of one ^12C atom; it is dimensionless.",
        examPhrasing: "M_r is the sum of relative atomic masses implied by the molecular formula.",
        confusionPair: "M_r vs molar mass",
        tags: ["Mr", "definition"],
      },
      {
        id: "t2-1-f3",
        noteId: "t2-1",
        difficulty: 2,
        front: "How do you calculate A_r from isotopic abundances?",
        back: "Take the abundance-weighted mean of isotopic masses (often using mass numbers as approximations in introductory calculations).",
        examPhrasing: "Use fractional abundances with isotopic masses to obtain a weighted mean.",
        confusionPair: "simple mean vs weighted mean",
        tags: ["isotopes", "abundance"],
      },
      {
        id: "t2-1-f4",
        noteId: "t2-1",
        difficulty: 2,
        front: "What does the tallest peak in a mass spectrum of an element usually represent?",
        back: "The most abundant isotope (for elements, often the base peak); peak heights reflect relative abundance of ions detected.",
        examPhrasing: "Relative peak intensities correspond to relative abundances of isotopes.",
        confusionPair: "m/z vs A_r directly without weighting",
        tags: ["mass-spectrum"],
      },
      {
        id: "t2-1-f5",
        noteId: "t2-1",
        difficulty: 2,
        front: "Why can A_r be non-integer even though mass numbers are integers?",
        back: "Because natural samples contain a mixture of isotopes; A_r is an average, not a count of nucleons in one nucleus.",
        examPhrasing: "Non-integer A_r reflects isotopic averaging, not fractional protons.",
        confusionPair: "mass number vs A_r",
        tags: ["isotopes", "Ar"],
      },
      {
        id: "t2-1-f6",
        noteId: "t2-1",
        difficulty: 3,
        front: "What is relative formula mass used for?",
        back: "Ionic compounds with no discrete molecules: sum of A_r in the formula unit, on the same carbon-12-relative scale as M_r.",
        examPhrasing: "For giant ionic structures, use formula unit relative mass rather than molecular mass.",
        confusionPair: "M_r vs M_r of formula unit",
        tags: ["ionic", "terminology"],
      },
      {
        id: "t2-1-f7",
        noteId: "t2-1",
        difficulty: 3,
        front: "How do you obtain relative formula mass from a displayed ionic formula?",
        back: "Add the relative atomic masses of all atoms in one formula unit (including atoms inside brackets multiplied by the bracket multiplier).",
        examPhrasing: "RFM is the sum of A_r values implied by the stoichiometric formula.",
        confusionPair: "RFM vs mass of one mole in grams",
        tags: ["relative-formula-mass", "method"],
      },
      {
        id: "t2-1-f8",
        noteId: "t2-1",
        difficulty: 4,
        front: "In percentage-to-empirical problems, why assume 100 g of compound?",
        back: "It turns mass percentages directly into convenient gram amounts without changing the ratio of elements.",
        examPhrasing: "Percentage composition by mass converts cleanly to mass ratio in a 100 g sample.",
        confusionPair: "percent vs mole directly",
        tags: ["percentage", "method"],
      },
      {
        id: "t2-1-f9",
        noteId: "t2-1",
        difficulty: 4,
        front: "State one limitation of using mass numbers instead of precise isotopic masses in A_r calculations.",
        back: "Binding energy effects mean true isotopic masses are not exactly integers; answers are approximations unless precise masses are given.",
        examPhrasing: "Mass number is not identical to isotopic mass in u to many decimal places.",
        confusionPair: "mass number vs isotopic mass",
        tags: ["precision"],
      },
      {
        id: "t2-1-f10",
        noteId: "t2-1",
        difficulty: 5,
        front: "Why must abundances sum to 100% before calculating A_r from tabulated data?",
        back: "So fractional abundances partition unity; otherwise the weighted mean is systematically wrong.",
        examPhrasing: "Normalise abundances to fractions that sum to 1 before averaging.",
        confusionPair: "percentages left unnormalised",
        tags: ["abundance", "error-checking"],
      },
    ],
  },
  // 9701 2.2: mole defined via Avogadro constant L; amount/mass/particle calculations — d1–d10.
  "t2-2": {
    noteId: "t2-2",
    drills: [
      {
        id: "t2-2-d1",
        noteId: "t2-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which statement about the mole is correct?",
        options: [
          { id: "A", text: "One mole of a substance contains L particles, where L is the Avogadro constant." },
          { id: "B", text: "The mole counts only molecules, never ions or atoms." },
          { id: "C", text: "One mole always occupies 24 dm^3 at any temperature." },
          { id: "D", text: "Avogadro constant has units mol^-1 g." },
        ],
        correctOptionId: "A",
        explanation:
          "The mole links macroscopic amount to particle number: N = n x L, with L ≈ 6.02 x 10^23 mol^-1.",
        distractorRationale: {
          B: "Amount of substance applies to any specified elementary entities (atoms, ions, electrons, formula units, etc.) as stated in the formula.",
          C: "Molar gas volume depends on temperature and pressure; 24 dm^3 mol^-1 is not universal.",
          D: "L is mol^-1; grams are not part of its SI unit.",
        },
        tags: ["mole", "Avogadro", "definitions", "9701-2.2"],
      },
      {
        id: "t2-2-d2",
        noteId: "t2-2",
        kind: "mcq",
        difficulty: 1,
        stem: "What is the amount, in mol, of 88 g of carbon dioxide, CO_2? (M_r: CO_2 = 44.0)",
        options: [
          { id: "A", text: "2.0 mol" },
          { id: "B", text: "0.50 mol" },
          { id: "C", text: "4.0 mol" },
          { id: "D", text: "44 mol" },
        ],
        correctOptionId: "A",
        explanation: "n = m/M = 88/44.0 = 2.0 mol.",
        distractorRationale: {
          B: "This results from inverting the ratio or halving incorrectly.",
          C: "This doubles the correct mole amount.",
          D: "This treats M_r numerically as moles instead of dividing mass by molar mass.",
        },
        tags: ["n=m/M", "calculation"],
      },
      {
        id: "t2-2-d3",
        noteId: "t2-2",
        kind: "mcq",
        difficulty: 2,
        stem: "How many chloride ions are in 0.30 mol of MgCl_2?",
        options: [
          { id: "A", text: "0.60 x L" },
          { id: "B", text: "0.30 x L" },
          { id: "C", text: "0.90 x L" },
          { id: "D", text: "0.15 x L" },
        ],
        correctOptionId: "A",
        explanation:
          "Each formula unit MgCl_2 provides 2 Cl^- ions, so n(Cl^-) = 2 x 0.30 = 0.60 mol; N = nL.",
        distractorRationale: {
          B: "This counts formula units of MgCl_2, not chloride ions.",
          C: "This incorrectly uses a stoichiometric factor of 3.",
          D: "This uses half the correct ion amount.",
        },
        tags: ["stoichiometry", "ions", "N=nL"],
      },
      {
        id: "t2-2-d4",
        noteId: "t2-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Define the Avogadro constant, L, giving its value to 3 significant figures and its SI unit.",
        modelAnswerPoints: [
          "L is the number of specified elementary entities per mole of substance.",
          "Value ≈ 6.02 x 10^23 to 3 s.f.",
          "Unit mol^-1.",
        ],
        workedSolution: [
          "The Avogadro constant, L, is the number of elementary entities (atoms, molecules, ions, electrons, formula units, etc., depending on what has been specified) that are present in one mole of that substance.",
          "Its accepted value is 6.02 x 10^23 when expressed to three significant figures.",
          "The SI unit of the Avogadro constant is mol^-1, read as 'per mole', because it converts amount in moles to a counted number of particles.",
        ],
        commonMistake:
          "Writing mol g^-1 or omitting the exponent 10^23, or confusing L with molar mass.",
        tags: ["Avogadro", "definitions", "9701-2.2"],
      },
      {
        id: "t2-2-d5",
        noteId: "t2-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Define the term mole of a specified elementary entity in terms of the Avogadro constant, L.",
        modelAnswerPoints: [
          "One mole contains L particles (entities) of the kind stated.",
          "L is the Avogadro constant (~6.02 x 10^23 mol^-1).",
          "The elementary entity must be specified (atom, molecule, ion, formula unit, etc.).",
        ],
        workedSolution: [
          "One mole of a specified elementary entity is an amount of substance that contains exactly L entities of that kind, where L is the Avogadro constant.",
          "The Avogadro constant is about 6.02 x 10^23 mol^-1, so one mole corresponds to about 6.02 x 10^23 atoms, molecules, ions, formula units or other entities as defined in the question.",
          "It is therefore essential to state what the mole is counting — for example one mole of Cl^- ions is not the same thought experiment as one mole of Cl_2 molecules.",
        ],
        commonMistake:
          "Saying the mole counts only molecules, or omitting the need to name the elementary entity.",
        tags: ["mole", "Avogadro", "definitions", "9701-2.2"],
      },
      {
        id: "t2-2-d6",
        noteId: "t2-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A sample contains 3.61 x 10^24 molecules of glucose, C_6H_12O_6. Calculate the amount in mol and the mass in g. (M_r glucose = 180.0)",
        modelAnswerPoints: ["Use n = N/L.", "Then m = nM.", "Show consistent use of L and M."],
        workedSolution: [
          "The amount in moles is the number of molecules divided by the Avogadro constant, so n = N / L = (3.61 x 10^24) / (6.02 x 10^23), which is 6.00 mol to the precision implied by the data.",
          "Using the same ratio, 3.61 / 0.602 gives about 6.00 mol of glucose.",
          "The mass is then m = nM = 6.00 x 180.0 = 1080 g, which is 1.08 x 10^3 g in standard form.",
        ],
        commonMistake:
          "Multiplying by L instead of dividing when converting particle number to moles.",
        tags: ["N=nL", "glucose"],
      },
      {
        id: "t2-2-d7",
        noteId: "t2-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Deduce the total number of atoms in one mole of ethane, C_2H_6.",
        modelAnswerPoints: [
          "Count atoms per molecule.",
          "Scale by Avogadro constant for one mole of molecules.",
        ],
        workedSolution: [
          "Each molecule of ethane, C_2H_6, contains two carbon atoms and six hydrogen atoms, so there are eight atoms in one molecule.",
          "One mole of ethane contains L molecules, where L is the Avogadro constant.",
          "The total number of atoms in one mole of ethane is therefore 8L, which is about 8 x 6.02 x 10^23 = 4.82 x 10^24 atoms.",
        ],
        commonMistake:
          "Counting only carbon atoms or only hydrogen atoms.",
        tags: ["atom-count", "Avogadro"],
      },
      {
        id: "t2-2-d8",
        noteId: "t2-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A mixture contains 2.0 mol N_2 and 1.0 mol O_2 only. Calculate the total mass of the mixture and the mole fraction of nitrogen.",
        modelAnswerPoints: [
          "Find mass of each gas from m = nM.",
          "Sum masses.",
          "Mole fraction x_i = n_i / n_total.",
        ],
        workedSolution: [
          "The molar mass of nitrogen is 28.0 g mol^-1 and that of oxygen is 32.0 g mol^-1 for the diatomic gases as given.",
          "The mass of nitrogen present is 2.0 mol x 28.0 g mol^-1 = 56.0 g and the mass of oxygen is 1.0 mol x 32.0 g mol^-1 = 32.0 g.",
          "The total mass of the mixture is 56.0 g + 32.0 g = 88.0 g.",
          "The total amount of gas is 2.0 + 1.0 = 3.0 mol, so the mole fraction of nitrogen is 2.0 / 3.0 = 0.67 to two decimal places.",
        ],
        commonMistake:
          "Using mass ratio instead of mole ratio for mole fraction.",
        tags: ["mixture", "mole-fraction"],
      },
      {
        id: "t2-2-d9",
        noteId: "t2-2",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "State what is meant by the term molar mass of a substance, and explain why the same numerical value is used for molar mass in g mol^-1 as for the relative formula mass M_r on the unified scale, even though M_r is dimensionless.",
        modelAnswerPoints: [
          "Molar mass M is the mass per mole of the substance, with SI unit g mol^-1 (or kg mol^-1).",
          "The numerical value of M in g mol^-1 equals the numerical value of M_r because both count the same relative masses per formula unit or molecule.",
          "The mole is tied to L and to the carbon-12 standard, which fixes the scale linking microscopic masses to macroscopic amounts.",
        ],
        workedSolution: [
          "The molar mass, M, of a substance is the mass of one mole of that substance divided by the amount in moles, and it is normally quoted in g mol^-1 at A Level.",
          "Relative formula mass, M_r, is the dimensionless mass of a formula unit or molecule compared with one-twelfth of the mass of a carbon-12 atom, but the same relative atomic masses are used when adding up the formula to obtain the mass of one mole in grams.",
          "Because the mole is defined through the Avogadro constant and the carbon-12 reference, the numerical value of the molar mass expressed in g mol^-1 is the same as the numerical value of M_r, even though M_r itself carries no unit.",
        ],
        commonMistake:
          "Claiming M_r itself has units g mol^-1.",
        tags: ["molar-mass", "definitions", "9701-2.2"],
      },
      {
        id: "t2-2-d10",
        noteId: "t2-2",
        kind: "structured",
        difficulty: 5,
        marks: 8,
        stem: "An element X forms a chloride XCl_2. A 0.0200 mol sample of XCl_2 has mass 2.54 g. Calculate the relative atomic mass of X.",
        modelAnswerPoints: [
          "Find molar mass of XCl_2 from M = m/n.",
          "Subtract 2 x 35.5 for two chlorine atoms (or 2 x 35.5 if A_r Cl taken as 35.5).",
          "State A_r of X.",
        ],
        workedSolution: [
          "The molar mass of XCl_2 is the sample mass divided by the amount in moles, so M(XCl_2) = 2.54 g / 0.0200 mol = 127 g mol^-1.",
          "Each formula unit contains two chlorine atoms, so the molar mass contributed by chlorine is 2 x 35.5 g mol^-1 = 71.0 g mol^-1, and subtracting this from the molar mass of the chloride gives M(X) = 127 - 71.0 = 56.0 g mol^-1.",
          "The relative atomic mass of X is therefore 56.0 on the usual scale, which is the numerical value obtained for the molar mass of the element in g mol^-1.",
        ],
        commonMistake:
          "Subtracting only one chlorine when the formula is XCl_2.",
        tags: ["molar-mass", "halide", "inverse"],
      },
    ],
    flashcards: [
      {
        id: "t2-2-f1",
        noteId: "t2-2",
        difficulty: 1,
        front: "Write the relationship between amount in moles, mass, and molar mass.",
        back: "n = m/M (or m = nM).",
        examPhrasing: "Amount of substance is obtained from mass divided by the molar mass.",
        confusionPair: "divide vs multiply by M",
        tags: ["n=m/M"],
      },
      {
        id: "t2-2-f2",
        noteId: "t2-2",
        difficulty: 1,
        front: "Write the relationship between amount in moles and particle number.",
        back: "N = nL, where L is the Avogadro constant.",
        examPhrasing: "The number of particles equals the amount in moles multiplied by the Avogadro constant.",
        confusionPair: "N=nL vs n=N/L",
        tags: ["Avogadro"],
      },
      {
        id: "t2-2-f3",
        noteId: "t2-2",
        difficulty: 2,
        front: "What elementary entities must you specify when quoting moles of NaCl?",
        back: "Formula units (or pairs of ions Na^+ and Cl^-) — the entity must always be stated explicitly if ambiguous.",
        examPhrasing: "The mole can refer to formula units for ionic compounds.",
        confusionPair: "molecules vs formula units",
        tags: ["ionic", "entities"],
      },
      {
        id: "t2-2-f4",
        noteId: "t2-2",
        difficulty: 2,
        front: "For Al_2(SO_4)_3, how many moles of sulfate ions per mole of salt?",
        back: "3 mol SO_4^2- per 1 mol Al_2(SO_4)_3.",
        examPhrasing: "Use the stoichiometric subscripts outside the bracket as multipliers.",
        confusionPair: "subscript inside vs outside bracket",
        tags: ["stoichiometry", "ions"],
      },
      {
        id: "t2-2-f5",
        noteId: "t2-2",
        difficulty: 2,
        front: "Why is L the same for all substances?",
        back: "It is a universal constant linking the mole to the number of specified entities, independent of chemical identity.",
        examPhrasing: "Avogadro constant is a fundamental constant of nature.",
        confusionPair: "L varies per element",
        tags: ["Avogadro"],
      },
      {
        id: "t2-2-f6",
        noteId: "t2-2",
        difficulty: 3,
        front: "What is the molar mass of hydrated CuSO_4.5H_2O linked to?",
        back: "The mass per mole of the entire hydrated formula unit, including water of crystallisation.",
        examPhrasing: "Hydrate calculations must use the full M of the hydrate.",
        confusionPair: "anhydrous vs hydrated M",
        tags: ["hydrate"],
      },
      {
        id: "t2-2-f7",
        noteId: "t2-2",
        difficulty: 3,
        front: "In n = N/L, why must N count the same entities as n?",
        back: "Because L converts moles of those entities to their number; mixing atoms and molecules breaks the calculation.",
        examPhrasing: "Consistency of the elementary entity is essential.",
        confusionPair: "atoms vs molecules in N",
        tags: ["entities"],
      },
      {
        id: "t2-2-f8",
        noteId: "t2-2",
        difficulty: 4,
        front: "Why is it wrong to say ‘one mole of sulfur’ without further detail?",
        back: "The elementary entity must be specified (e.g. S_8 molecules, S atoms in a lattice, or SO_4^2- ions) because the mole counts stated particles, not an ambiguous name.",
        examPhrasing: "Always state the formula of the species the mole refers to.",
        confusionPair: "element name vs specified entity",
        tags: ["entities", "9701-2.2"],
      },
      {
        id: "t2-2-f9",
        noteId: "t2-2",
        difficulty: 4,
        front: "Why can you not find moles of 'oxygen' from mass of an oxide without a formula?",
        back: "Because oxygen may be present as O, O_2, or O^2- in different compounds; the chemical formula fixes the mole relationship.",
        examPhrasing: "Stoichiometry requires a defined substance and formula.",
        confusionPair: "element mass vs compound moles",
        tags: ["concept"],
      },
      {
        id: "t2-2-f10",
        noteId: "t2-2",
        difficulty: 5,
        front: "What does SI definition of the mole (since 2019) fix conceptually?",
        back: "The mole is defined by fixing Avogadro constant, linking macroscopic chemical amount to a counted number of entities.",
        examPhrasing: "At A Level, focus on N = nL and consistent use of L.",
        confusionPair: "historical vs SI definition detail",
        tags: ["definitions", "SI"],
      },
    ],
  },
  // 9701 2.3 LO crosswalk (drill ids): d1 common ion recall; d2 NH_4^+/PO_4^3- formula; d3 net ionic + spectators;
  // d4 periodic + CaO + Fe(III) sulfate + Zn^2+ + OH^-; d5 full equation + states; d6 empirical def; d7 molecular def + illustration;
  // d8 hydrate / anhydrous / water of crystallisation; d9 % composition -> empirical + molecular via M_r; d10 hydrate x; (ionic equations + balancing in d3, d5).
  "t2-3": {
    noteId: "t2-3",
    drills: [
      {
        id: "t2-3-d1",
        noteId: "t2-3",
        kind: "mcq",
        difficulty: 1,
        stem: "Which row gives the correct formulas for the carbonate ion and the hydrogen carbonate ion?",
        options: [
          { id: "A", text: "CO_3^2- and HCO_3^-" },
          { id: "B", text: "CO_3^- and HCO_3^2-" },
          { id: "C", text: "CO_2^2- and HCO_3^-" },
          { id: "D", text: "CO_3^2- and H_2CO_3" },
        ],
        correctOptionId: "A",
        explanation:
          "The carbonate ion is CO_3^2- and the hydrogen carbonate (bicarbonate) ion is HCO_3^- — both are named species in 9701 2.3.",
        distractorRationale: {
          B: "Carbonate is a 2- anion; hydrogen carbonate carries a single negative charge.",
          C: "The stable carbonate ion is triatomic CO_3^2-, not CO_2^2-.",
          D: "H_2CO_3 is carbonic acid (molecular), not the hydrogen carbonate ion.",
        },
        tags: ["ions", "formulas", "9701-2.3"],
      },
      {
        id: "t2-3-d2",
        noteId: "t2-3",
        kind: "mcq",
        difficulty: 1,
        stem: "What is the correct formula of ammonium phosphate?",
        options: [
          { id: "A", text: "(NH_4)_3PO_4" },
          { id: "B", text: "(NH_4)_2PO_4" },
          { id: "C", text: "NH_4PO_4" },
          { id: "D", text: "(NH_4)_3(PO_4)_2" },
        ],
        correctOptionId: "A",
        explanation:
          "NH_4^+ and PO_4^3- require three ammonium ions per phosphate for neutrality: (NH_4)_3PO_4.",
        distractorRationale: {
          B: "Two NH_4^+ would give total +2, which does not balance PO_4^3-.",
          C: "A single NH_4^+ cannot balance a 3- anion to give a neutral solid.",
          D: "Doubling the anion without matching cations would not give a neutral formula unit.",
        },
        tags: ["ionic-formula", "ions", "9701-2.3"],
      },
      {
        id: "t2-3-d3",
        noteId: "t2-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Aqueous silver nitrate is added to aqueous sodium chloride and a white precipitate forms. Which ionic equation represents the reaction?",
        options: [
          { id: "A", text: "Ag^+(aq) + Cl^-(aq) -> AgCl(s)" },
          { id: "B", text: "AgNO_3(aq) + NaCl(aq) -> AgCl(s) + NaNO_3(aq)" },
          { id: "C", text: "Na^+(aq) + Cl^-(aq) -> NaCl(s)" },
          { id: "D", text: "Ag^+(aq) + NO_3^-(aq) + Na^+(aq) + Cl^-(aq) -> AgCl(s) + NaNO_3(aq)" },
        ],
        correctOptionId: "A",
        explanation:
          "Spectator ions Na^+ and NO_3^- do not take part in forming the precipitate; the net change is Ag^+ with Cl^-.",
        distractorRationale: {
          B: "This is a full molecular equation, not the ionic equation without spectator ions.",
          C: "Sodium chloride is already dissociated in solution; NaCl(s) is not the precipitation process described.",
          D: "Including all ions as if they all react contradicts the spectator role of Na^+ and NO_3^-.",
        },
        tags: ["ionic-equation", "spectators", "9701-2.3"],
      },
      {
        id: "t2-3-d4",
        noteId: "t2-3",
        kind: "structured",
        difficulty: 2,
        marks: 10,
        stem: "(a) Use your knowledge of the Periodic Table to predict the ions formed by calcium and by oxygen when they combine in an ionic oxide. Write the formula of the oxide and explain how the charges balance. (b) Write the formula of iron(III) sulfate, using the Roman numeral to fix the charge on the metal ion. (c) State the charge on the zinc ion in compounds named in the syllabus (e.g. Zn^2+ in salts such as ZnSO_4). (d) Write the formula of the hydroxide ion.",
        modelAnswerPoints: [
          "Group 2 calcium forms Ca^2+; oxide ion is O^2-; neutral binary formula CaO.",
          "Iron(III) means Fe^3+; sulfate is SO_4^2-; neutral formula Fe_2(SO_4)_3.",
          "Zinc forms Zn^2+ cations in the ionic compounds required by 9701 2.3.",
          "Hydroxide ion is OH^-.",
        ],
        workedSolution: [
          "Calcium is in Group 2, so its atoms lose two electrons in ionic compounds to give Ca^2+, while oxygen in Group 16 gains two electrons to give O^2- in an oxide lattice.",
          "One Ca^2+ and one O^2- carry equal and opposite charge magnitudes, so the simplest neutral formula is CaO rather than Ca_2O or CaO_2.",
          "The name iron(III) sulfate indicates iron in the +3 oxidation state, written as Fe^3+, and the sulfate ion is SO_4^2-, so two iron(III) ions together carry +6 and three sulfate ions carry -6, giving the neutral formula Fe_2(SO_4)_3.",
          "Zinc is specified in the syllabus ion list as Zn^2+, so in ionic salts such as zinc sulfate the cation present in aqueous solution and in the lattice is the zinc(II) ion, Zn^2+.",
          "The hydroxide ion, which appears whenever alkalis are discussed and is listed by name in 9701 2.3, has the formula OH^- with a single negative charge.",
        ],
        commonMistake:
          "Writing FeSO_4 for iron(III) sulfate by copying the 1:1 pattern of iron(II) sulfate, or mis-identifying the Roman numeral as a counting subscript rather than the oxidation number of iron.",
        tags: ["periodic-table", "ionic-formula", "oxidation-number", "9701-2.3"],
      },
      {
        id: "t2-3-d5",
        noteId: "t2-3",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Solid sodium carbonate reacts with dilute hydrochloric acid, producing carbon dioxide gas, water and aqueous sodium chloride. Write a balanced chemical equation for the reaction, including appropriate state symbols.",
        modelAnswerPoints: [
          "Correct formulas for Na_2CO_3, HCl, CO_2, H_2O and NaCl.",
          "Balanced stoichiometry (typically Na_2CO_3 + 2HCl -> 2NaCl + H_2O + CO_2).",
          "States: (s) or (aq) for soluble ionic species as appropriate, CO_2(g), H_2O(l).",
        ],
        workedSolution: [
          "Sodium carbonate is an ionic solid, written as Na_2CO_3(s), and hydrochloric acid supplies hydrogen chloride in aqueous solution, written as HCl(aq), while sodium chloride is very soluble so the product is NaCl(aq).",
          "Carbon dioxide leaves the reaction mixture as a gas, CO_2(g), and water is formed as a liquid under normal laboratory conditions, H_2O(l).",
          "Balancing atoms and charge gives Na_2CO_3(s) + 2HCl(aq) -> 2NaCl(aq) + H_2O(l) + CO_2(g), where two moles of acid are required to provide two moles of hydrogen ions to convert one carbonate unit to one molecule of carbonic acid decomposition products as shown.",
        ],
        commonMistake:
          "Omitting state symbols, using HCl(g) for bench acid, or failing to balance hydrogen and chlorine when doubling HCl.",
        tags: ["balanced-equation", "state-symbols", "9701-2.3"],
      },
      {
        id: "t2-3-d6",
        noteId: "t2-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Define the term empirical formula of a compound.",
        modelAnswerPoints: [
          "Shows simplest whole-number ratio of atoms of each element in the compound.",
          "May differ from the molecular formula when a common factor > 1 exists.",
          "Obtained from composition data or by simplifying molecular formula subscripts.",
        ],
        workedSolution: [
          "The empirical formula of a compound is the formula that shows the simplest whole-number ratio in which the atoms of each element are present in the compound.",
          "It is not necessarily identical to the molecular formula when the molecular formula is an integer multiple of the empirical formula.",
          "For example, butane has molecular formula C_4H_10 but empirical formula C_2H_5, because all subscripts in the molecular formula share a common factor of two.",
        ],
        commonMistake:
          "Stating that the empirical formula always equals the number of atoms in one molecule.",
        tags: ["empirical", "definitions", "9701-2.3"],
      },
      {
        id: "t2-3-d7",
        noteId: "t2-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Define the term molecular formula of a compound. Illustrate your answer using propene, C_3H_6, and state its empirical formula.",
        modelAnswerPoints: [
          "Molecular formula gives actual numbers of atoms of each element in one molecule.",
          "Propene molecular formula C_3H_6 stated correctly.",
          "Empirical formula CH_2 obtained by dividing subscripts by their highest common factor.",
        ],
        workedSolution: [
          "The molecular formula of a molecular compound states the actual numbers of atoms of each element contained in one molecule of that substance.",
          "Propene is an alkene with three carbon atoms and six hydrogen atoms in each molecule, so its molecular formula is C_3H_6.",
          "The simplest whole-number ratio of carbon to hydrogen in propene is 1 : 2, obtained by dividing the subscripts in C_3H_6 by three, so the empirical formula is CH_2.",
        ],
        commonMistake:
          "Giving CH_2 as the molecular formula, or claiming the empirical formula must contain more atoms than the molecular formula.",
        tags: ["molecular", "empirical", "definitions", "9701-2.3"],
      },
      {
        id: "t2-3-d8",
        noteId: "t2-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Explain what is meant by the terms water of crystallisation, hydrated salt and anhydrous salt. Use sodium sulfate decahydrate, Na_2SO_4.10H_2O, as an example in your answer.",
        modelAnswerPoints: [
          "Water of crystallisation is water in fixed stoichiometric proportion within an ionic crystal lattice.",
          "Na_2SO_4.10H_2O is a hydrated salt containing that structural water.",
          "Heating to remove the water leaves anhydrous Na_2SO_4 with different M per formula unit.",
        ],
        workedSolution: [
          "Water of crystallisation means water molecules that are incorporated in a definite ratio into the crystal structure of an ionic solid, not merely surface moisture adsorbed on the outside of crystals.",
          "Sodium sulfate decahydrate, Na_2SO_4.10H_2O, is therefore a hydrated salt, because each formula unit of sulfate in the lattice is associated with ten water molecules that are part of the solid structure.",
          "When that structural water is driven off by heating, the anhydrous salt Na_2SO_4 remains, which has a smaller mass per mole of sulfate than the hydrate and may look physically different from the blue or white hydrate forms encountered in the laboratory.",
        ],
        commonMistake:
          "Treating the dot in the hydrate formula as a solvent mixture rather than part of the solid lattice stoichiometry.",
        tags: ["hydrate", "definitions", "9701-2.3"],
      },
      {
        id: "t2-3-d9",
        noteId: "t2-3",
        kind: "structured",
        difficulty: 4,
        marks: 8,
        stem: "A pure compound of carbon, hydrogen and oxygen only has percentage composition by mass 40.0% carbon, 6.7% hydrogen and 53.3% oxygen. Its relative molecular mass is 180.0. Determine the empirical formula and hence the molecular formula of the compound. (A_r: H = 1.0, C = 12.0, O = 16.0)",
        modelAnswerPoints: [
          "Convert mass percentages in a 100 g sample to moles of each element.",
          "Divide by the smallest amount of substance to obtain simplest ratio CH_2O.",
          "Empirical formula mass = 30.0; M_r / empirical mass = 180.0 / 30.0 = 6 gives molecular formula C_6H_12O_6.",
        ],
        workedSolution: [
          "In a 100 g sample the masses are 40.0 g carbon, 6.7 g hydrogen and 53.3 g oxygen, which correspond to n(C) = 40.0 / 12.0 = 3.33 mol, n(H) = 6.7 / 1.0 = 6.7 mol and n(O) = 53.3 / 16.0 = 3.33 mol.",
          "Dividing each amount by 3.33 mol shows that n(C) : n(H) : n(O) is 1.00 : 2.0 : 1.00 to a sensible precision, so the empirical formula is CH_2O with empirical formula mass 12.0 + 2(1.0) + 16.0 = 30.0.",
          "The relative molecular mass is 180.0, and 180.0 / 30.0 = 6.00, so each molecule contains six empirical units and the molecular formula is obtained by multiplying the empirical subscripts by six, giving C_6H_12O_6.",
        ],
        commonMistake:
          "Stopping at the empirical formula when M_r is given, or rounding 6.7/3.33 before recognising the 2 : 1 hydrogen-to-carbon ratio in the empirical unit.",
        tags: ["empirical", "molecular", "percentage-composition", "9701-2.3"],
      },
      {
        id: "t2-3-d10",
        noteId: "t2-3",
        kind: "structured",
        difficulty: 5,
        marks: 8,
        stem: "A sample of hydrated zinc sulfate, ZnSO_4.xH_2O, has mass 2.87 g. After strong heating to constant mass, 1.61 g of anhydrous ZnSO_4 remains. Find the value of x. (M: ZnSO_4 = 161.5 g mol^-1; H_2O = 18.0 g mol^-1)",
        modelAnswerPoints: [
          "Mass of water lost equals initial mass minus final anhydrous mass.",
          "Moles of ZnSO_4 from residue mass and M(ZnSO_4).",
          "Moles of H_2O from water mass and M(H_2O); ratio n(H_2O) : n(ZnSO_4) gives x.",
        ],
        workedSolution: [
          "The mass of water driven off from the lattice is 2.87 g - 1.61 g = 1.26 g, because the residue mass after heating is the anhydrous zinc sulfate only.",
          "The amount of anhydrous zinc sulfate is n(ZnSO_4) = 1.61 g / 161.5 g mol^-1 = 9.97 x 10^-3 mol, which is taken as 0.00997 mol at the precision of the data.",
          "The amount of water lost is n(H_2O) = 1.26 g / 18.0 g mol^-1 = 0.0700 mol.",
          "The ratio n(H_2O) / n(ZnSO_4) is 0.0700 / 0.00997 = 7.02, which rounds to the integer 7, so x = 7 and the sample was the heptahydrate ZnSO_4.7H_2O.",
        ],
        commonMistake:
          "Using the full hydrate mass in n = m/M when finding moles of ZnSO_4 instead of the anhydrous residue mass.",
        tags: ["hydrate", "calculation", "9701-2.3"],
      },
    ],
    flashcards: [
      {
        id: "t2-3-f1",
        noteId: "t2-3",
        difficulty: 1,
        front: "Write the formulas of the sulfate, carbonate and hydrogen carbonate ions.",
        back: "SO_4^2-, CO_3^2- and HCO_3^-.",
        examPhrasing: "Recall common ion formulas required by 9701 2.3.",
        confusionPair: "CO_3^2- vs HCO_3^-",
        tags: ["ions"],
      },
      {
        id: "t2-3-f2",
        noteId: "t2-3",
        difficulty: 1,
        front: "Write the formulas of the ammonium and nitrate ions.",
        back: "NH_4^+ and NO_3^-.",
        examPhrasing: "Named polyatomic cation and anion pair.",
        confusionPair: "NH_4^+ vs NH_3",
        tags: ["ions"],
      },
      {
        id: "t2-3-f3",
        noteId: "t2-3",
        difficulty: 2,
        front: "What is a spectator ion?",
        back: "An ion present in solution that does not change during the reaction and is omitted from the net ionic equation.",
        examPhrasing: "Spectators appear unchanged on both sides of the full ionic equation.",
        confusionPair: "spectator vs reagent ion",
        tags: ["ionic-equation"],
      },
      {
        id: "t2-3-f4",
        noteId: "t2-3",
        difficulty: 2,
        front: "How do you obtain molecular formula from empirical formula and M_r?",
        back: "Find k = M_r / empirical formula mass; multiply all subscripts in the empirical formula by the integer k.",
        examPhrasing: "Molecular formula is a whole-number multiple of the empirical formula.",
        confusionPair: "k from mass vs from ratio",
        tags: ["molecular"],
      },
      {
        id: "t2-3-f5",
        noteId: "t2-3",
        difficulty: 2,
        front: "In CuSO_4.5H_2O, what does the dot mean?",
        back: "It separates the ionic formula unit from water of crystallisation in fixed proportion in the crystal.",
        examPhrasing: "The hydrate formula includes lattice water stoichiometrically.",
        confusionPair: "dot vs ‘+’ in equations",
        tags: ["hydrate"],
      },
      {
        id: "t2-3-f6",
        noteId: "t2-3",
        difficulty: 3,
        front: "When finding x in a hydrate from mass loss, which mass gives n(salt)?",
        back: "The final constant mass after heating (anhydrous salt), not the initial hydrate mass.",
        examPhrasing: "Residue mass corresponds to moles of anhydrous lattice.",
        confusionPair: "initial mass vs residue mass",
        tags: ["hydrate", "method"],
      },
      {
        id: "t2-3-f7",
        noteId: "t2-3",
        difficulty: 3,
        front: "Why must net ionic equations balance charge?",
        back: "Overall charge is conserved; total positive and negative charges on each side must match.",
        examPhrasing: "Balance atoms and charges in ionic equations.",
        confusionPair: "molecular vs ionic balancing",
        tags: ["ionic-equation"],
      },
      {
        id: "t2-3-f8",
        noteId: "t2-3",
        difficulty: 4,
        front: "What do Roman numerals in a name such as copper(II) nitrate indicate?",
        back: "The oxidation number (magnitude of charge) on the metal ion in the compound, here Cu^2+ with NO_3^-.",
        examPhrasing: "Oxidation number in parentheses fixes the cation charge for formula writing.",
        confusionPair: "Roman numeral vs group number",
        tags: ["oxidation-number"],
      },
      {
        id: "t2-3-f9",
        noteId: "t2-3",
        difficulty: 4,
        front: "Give the formula of silver phosphate.",
        back: "Ag_3PO_4 (three Ag^+ balance one PO_4^3-).",
        examPhrasing: "Combine ion charges to give a neutral formula unit.",
        confusionPair: "Ag_3PO_4 vs AgPO_4",
        tags: ["ions", "formula"],
      },
      {
        id: "t2-3-f10",
        noteId: "t2-3",
        difficulty: 5,
        front: "Why are state symbols required in thermochemical and gas-evolution equations?",
        back: "They identify whether species are solid, liquid, aqueous or gaseous, which affects energy balances and which species contribute to gas volumes.",
        examPhrasing: "State symbols make the chemical picture unambiguous to an examiner.",
        confusionPair: "(aq) vs (l) for water",
        tags: ["state-symbols"],
      },
    ],
  },
  // 9701 2.4 LO crosswalk: d1 gas molar volume; d2 reacting masses; d3 limiting reagent; d4 limiting + excess definitions;
  // d5 % yield definition + numeric; d6 solution titration conc.; d7 gas volumes deduce C atoms (stoichiometric deduction); d8 gas vol + purity;
  // d9 hydrocarbon combustion gas ratio; d10 mixture + gas + mass %.
  "t2-4": {
    noteId: "t2-4",
    drills: [
      {
        id: "t2-4-d1",
        noteId: "t2-4",
        kind: "mcq",
        difficulty: 1,
        stem: "Under room conditions, one mole of an ideal gas occupies about 24 dm^3. What volume does 0.25 mol occupy under the same conditions?",
        options: [
          { id: "A", text: "6.0 dm^3" },
          { id: "B", text: "12 dm^3" },
          { id: "C", text: "48 dm^3" },
          { id: "D", text: "96 dm^3" },
        ],
        correctOptionId: "A",
        explanation: "V = n x V_m = 0.25 x 24 = 6.0 dm^3.",
        distractorRationale: {
          B: "This corresponds to 0.50 mol at 24 dm^3 mol^-1.",
          C: "This is 2 mol worth of gas at the stated molar volume.",
          D: "This is 4 mol worth of gas at the stated molar volume.",
        },
        tags: ["gas-volume", "molar-volume", "9701-2.4"],
      },
      {
        id: "t2-4-d2",
        noteId: "t2-4",
        kind: "mcq",
        difficulty: 1,
        stem: "Magnesium burns in oxygen: 2Mg(s) + O_2(g) → 2MgO(s). What mass of magnesium completely reacts with 0.50 mol of O_2? (A_r: Mg = 24.0)",
        options: [
          { id: "A", text: "24.0 g" },
          { id: "B", text: "12.0 g" },
          { id: "C", text: "48.0 g" },
          { id: "D", text: "6.0 g" },
        ],
        correctOptionId: "A",
        explanation:
          "2 mol Mg : 1 mol O_2, so n(Mg) = 2 x 0.50 = 1.00 mol; m = 1.00 x 24.0 = 24.0 g.",
        distractorRationale: {
          B: "This uses 1:1 mole ratio instead of 2:1 for Mg to O_2.",
          C: "This doubles the correct mass.",
          D: "This halves the correct mass.",
        },
        tags: ["reacting-masses", "equation"],
      },
      {
        id: "t2-4-d3",
        noteId: "t2-4",
        kind: "mcq",
        difficulty: 2,
        stem: "N_2(g) + 3H_2(g) → 2NH_3(g). What is the maximum amount, in mol, of NH_3 that can form from 0.20 mol N_2 and 0.60 mol H_2?",
        options: [
          { id: "A", text: "0.40 mol" },
          { id: "B", text: "0.20 mol" },
          { id: "C", text: "0.60 mol" },
          { id: "D", text: "0.80 mol" },
        ],
        correctOptionId: "A",
        explanation:
          "N_2 : H_2 needed = 1 : 3. For 0.20 mol N_2, H_2 required = 0.60 mol, exactly supplied. NH_3 formed = 2 x 0.20 = 0.40 mol.",
        distractorRationale: {
          B: "This might arise from taking stoichiometric coefficient 2 as moles of NH_3 per mole H_2 incorrectly.",
          C: "This equals starting moles of H_2, not moles of product from the balanced equation.",
          D: "This exceeds what the nitrogen amount can produce.",
        },
        tags: ["limiting-reagent", "Haber"],
      },
      {
        id: "t2-4-d4",
        noteId: "t2-4",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Explain what is meant by the terms limiting reagent and excess reagent in a reaction where two or more reactants are mixed according to a balanced chemical equation.",
        modelAnswerPoints: [
          "Limiting reagent is the reactant completely consumed first under the balanced stoichiometry.",
          "It caps the theoretical maximum amount of product.",
          "Excess reagent is supplied beyond the stoichiometric amount needed to consume the limiting reagent, so some remains after reaction.",
        ],
        workedSolution: [
          "The limiting reagent is the reactant that would be entirely used up first if the reaction proceeded to completion according to the balanced equation, because the initial amount of that substance, measured in moles and compared with the required mole ratio, runs out before any other reactant does.",
          "Once the limiting reagent has been consumed, no further product can be made from that particular mixture, so the limiting reagent sets the theoretical maximum amounts of all products that can be obtained.",
          "An excess reagent is any other reactant that has been added in a larger amount than is stoichiometrically required to react with all of the limiting reagent, so when reaction stops a portion of that excess reagent is still present unreacted in the mixture.",
        ],
        commonMistake:
          "Identifying the limiting reagent by the smallest mass without converting each reactant to moles and comparing to the balanced mole ratio.",
        tags: ["limiting-reagent", "excess-reagent", "definitions", "9701-2.4"],
      },
      {
        id: "t2-4-d5",
        noteId: "t2-4",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Define the term percentage yield of a chemical preparation. A synthesis has a theoretical yield of 8.00 g of product, but only 6.40 g is isolated after work-up. Calculate the percentage yield, giving your answer to an appropriate number of significant figures.",
        modelAnswerPoints: [
          "Percentage yield compares actual isolated mass to theoretical maximum from stoichiometry.",
          "Formula: (actual yield / theoretical yield) x 100%.",
          "Substitution 6.40 / 8.00 x 100% = 80.0% with s.f. consistent with data (3 s.f.).",
        ],
        workedSolution: [
          "The percentage yield of a preparation measures how much of the product that could in principle be formed, according to the balanced equation and the limiting reagent, is actually obtained after practical losses and purification steps.",
          "It is calculated as (actual yield / theoretical yield) x 100%, provided both quantities refer to the same chemical product and are expressed in the same units, here grams of dry product.",
          "Substituting the values given, percentage yield = (6.40 g / 8.00 g) x 100% = 0.800 x 100% = 80.0%, which is quoted to three significant figures to match the precision of the mass data supplied.",
        ],
        commonMistake:
          "Dividing theoretical by actual, or forgetting to multiply by 100% when expressing as a percentage.",
        tags: ["percentage-yield", "calculation", "9701-2.4"],
      },
      {
        id: "t2-4-d6",
        noteId: "t2-4",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "20.0 cm^3 of 0.50 mol dm^-3 NaOH neutralises 25.0 cm^3 of H_2SO_4. Calculate the concentration of the acid in mol dm^-3. Equation: 2NaOH + H_2SO_4 -> Na_2SO_4 + 2H_2O.",
        modelAnswerPoints: [
          "Moles of NaOH from n = cV with V in dm^3.",
          "Use 2 : 1 mole ratio NaOH : H_2SO_4 from the equation.",
          "Acid concentration from c = n_acid / V_acid in dm^3.",
        ],
        workedSolution: [
          "The volume of sodium hydroxide is 20.0 cm^3 = 0.0200 dm^3, so the amount of NaOH is n(NaOH) = cV = 0.50 mol dm^-3 x 0.0200 dm^3 = 0.0100 mol.",
          "The balanced equation shows that two moles of sodium hydroxide react with one mole of sulfuric acid, so the amount of acid titrated is n(H_2SO_4) = 1/2 x n(NaOH) = 0.00500 mol.",
          "This amount is contained in 25.0 cm^3 = 0.0250 dm^3 of acid, so the concentration is c(H_2SO_4) = 0.00500 mol / 0.0250 dm^3 = 0.20 mol dm^-3.",
        ],
        commonMistake:
          "Treating the acid as monoprotic in the mole ratio, or failing to convert cm^3 to dm^3.",
        tags: ["titration", "moles-concentration", "9701-2.4"],
      },
      {
        id: "t2-4-d7",
        noteId: "t2-4",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Under the same temperature and pressure, 15.0 cm^3 of a gaseous hydrocarbon C_xH_y is completely burned in excess oxygen. Water is produced as a liquid. The carbon dioxide formed occupies 60.0 cm^3, measured under the same conditions as the hydrocarbon. Deduce the value of x and justify your answer using the stoichiometry of complete combustion.",
        modelAnswerPoints: [
          "Equal T and p mean gas volumes are proportional to amounts in moles for the gaseous species measured.",
          "Each mole of C_xH_y produces x moles of CO_2 on complete combustion, so V(CO_2)/V(C_xH_y) = x.",
          "Compute 60.0 / 15.0 = 4.0 and state x = 4.",
        ],
        workedSolution: [
          "Because the hydrocarbon and the carbon dioxide are measured at the same temperature and pressure, the ratio of their gas volumes equals the ratio of their amounts in moles, so the volume data can be read as a mole ratio between CO_2 formed and hydrocarbon burned.",
          "For complete combustion of a simple hydrocarbon C_xH_y, every mole of molecules consumed produces x moles of CO_2(g), since each carbon atom in the fuel ends up in one molecule of carbon dioxide while water is formed separately as a liquid under the conditions stated.",
          "Therefore the expected volume ratio V(CO_2) / V(C_xH_y) equals x, and substituting the measured volumes gives 60.0 cm^3 / 15.0 cm^3 = 4.0, so x = 4 and the hydrocarbon molecule must contain four carbon atoms.",
        ],
        commonMistake:
          "Treating the result as the total number of atoms rather than only the carbon count, or including liquid water as a gas in the volume argument.",
        tags: ["gas-volumes", "deduction", "9701-2.4"],
      },
      {
        id: "t2-4-d8",
        noteId: "t2-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A 5.00 g impure sample of limestone (mainly CaCO_3) is treated with excess acid until no more gas is evolved. The CO_2 collected at rtp occupies 1.08 dm^3. Calculate the percentage purity of the limestone. (M_r: CaCO_3 = 100.0; molar gas volume at rtp = 24 dm^3 mol^-1)",
        modelAnswerPoints: [
          "Moles of CO_2 from volume.",
          "1:1 mole ratio CaCO_3 : CO_2.",
          "Mass of pure CaCO_3; percentage of 5.00 g.",
        ],
        workedSolution: [
          "The amount of carbon dioxide collected is n(CO_2) = volume / molar volume = 1.08 dm^3 / 24 dm^3 mol^-1 = 0.0450 mol.",
          "Each mole of calcium carbonate that reacts with excess acid typically yields one mole of CO_2, so the sample contained n(CaCO_3) = 0.0450 mol of pure carbonate.",
          "The mass of pure calcium carbonate is m(CaCO_3) = 0.0450 mol x 100.0 g mol^-1 = 4.50 g.",
          "The percentage purity of the limestone is therefore (4.50 g / 5.00 g) x 100% = 90.0%.",
        ],
        commonMistake:
          "Assuming 1 mol CaCO_3 produces 2 mol CO_2.",
        tags: ["purity", "gas-volume"],
      },
      {
        id: "t2-4-d9",
        noteId: "t2-4",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Propane burns completely in excess oxygen: C_3H_8(g) + 5O_2(g) -> 3CO_2(g) + 4H_2O(l). Calculate the volume of carbon dioxide, measured under the same conditions as the propane, formed when 40 cm^3 of propane reacts. Assume water is liquid.",
        modelAnswerPoints: [
          "Under constant temperature and pressure, gas volumes are proportional to moles.",
          "Use stoichiometric volume ratio C_3H_8 : CO_2 from the balanced equation.",
          "State the CO_2 volume with correct units.",
        ],
        workedSolution: [
          "Under the same temperature and pressure, gas volumes are proportional to amounts in moles, and the balanced equation shows that one mole of propane produces three moles of carbon dioxide while water is formed as a liquid and does not contribute to the measured gas volume.",
          "The volume of carbon dioxide is therefore three times the volume of propane consumed, so V(CO_2) = 3 x 40 cm^3 = 120 cm^3.",
          "Hence 120 cm^3 of carbon dioxide is formed, measured under the same conditions as the propane.",
        ],
        commonMistake:
          "Including liquid water as a gas or using a 5:3 ratio from oxygen coefficients instead of propane to CO_2.",
        tags: ["combustion", "gas-volumes"],
      },
      {
        id: "t2-4-d10",
        noteId: "t2-4",
        kind: "structured",
        difficulty: 5,
        marks: 8,
        stem: "2.80 g of a mixture of Mg and MgO reacts with excess dilute H_2SO_4. The hydrogen evolved occupies 960 cm^3 at rtp. Find the percentage by mass of Mg in the mixture. (A_r: Mg = 24.0, O = 16.0; M_r MgO = 40.0; molar gas volume at rtp = 24 dm^3 mol^-1)",
        modelAnswerPoints: [
          "Volume to moles of H_2.",
          "Moles of Mg from Mg + 2H^+ → Mg^2+ + H_2 (1:1 Mg to H_2).",
          "Mass of Mg; mass % in 2.80 g.",
        ],
        workedSolution: [
          "The volume of hydrogen is 960 cm^3 = 0.960 dm^3, so n(H_2) = 0.960 dm^3 / 24 dm^3 mol^-1 = 0.0400 mol.",
          "Magnesium oxide reacts with acid without evolving hydrogen, so all the gas comes from magnesium metal, and n(Mg) = n(H_2) = 0.0400 mol from the 1 : 1 stoichiometry of Mg to H_2.",
          "The mass of magnesium in the sample is m(Mg) = 0.0400 mol x 24.0 g mol^-1 = 0.960 g.",
          "The percentage by mass of magnesium in the 2.80 g mixture is (0.960 g / 2.80 g) x 100% = 34.3%.",
        ],
        commonMistake:
          "Assigning all 2.80 g to magnesium and ignoring MgO which dissolves without producing hydrogen.",
        tags: ["mixture", "Mg-MgO", "gas"],
      },
    ],
    flashcards: [
      {
        id: "t2-4-f1",
        noteId: "t2-4",
        difficulty: 1,
        front: "Under room conditions, what molar volume of an ideal gas is commonly used at A Level?",
        back: "24 dm^3 mol^-1 (rtp — room temperature and pressure).",
        examPhrasing: "One mole of any gas occupies the same volume under the same conditions.",
        confusionPair: "24 dm^3 vs 22.7 dm^3 STP",
        tags: ["molar-volume"],
      },
      {
        id: "t2-4-f2",
        noteId: "t2-4",
        difficulty: 1,
        front: "How do you convert concentration in mol dm^-3 and volume in cm^3 to moles?",
        back: "n = c x V(dm^3) with V = V_cm^3 / 1000.",
        examPhrasing: "Always express volume in dm^3 when using c in mol dm^-3.",
        confusionPair: "cm^3 vs dm^3 factor",
        tags: ["concentration"],
      },
      {
        id: "t2-4-f3",
        noteId: "t2-4",
        difficulty: 2,
        front: "State the principle of using mole ratios from a balanced equation.",
        back: "Coefficients give the ratio in which amounts of substances react and are formed.",
        examPhrasing: "Stoichiometry links moles of reactants and products.",
        confusionPair: "mass ratio vs mole ratio",
        tags: ["stoichiometry"],
      },
      {
        id: "t2-4-f4",
        noteId: "t2-4",
        difficulty: 2,
        front: "What is a limiting reagent?",
        back: "The reactant that is completely consumed first, limiting the maximum extent of reaction.",
        examPhrasing: "Identify limiting reagent by comparing actual mole ratio to required ratio from the equation.",
        confusionPair: "excess vs limiting",
        tags: ["limiting"],
      },
      {
        id: "t2-4-f5",
        noteId: "t2-4",
        difficulty: 2,
        front: "For gases at the same temperature and pressure, what is true about volumes and moles?",
        back: "Volume is proportional to amount in moles; equal moles of different gases occupy equal volumes.",
        examPhrasing: "Avogadro's law underpins reacting gas volumes.",
        confusionPair: "equal volumes vs equal masses",
        tags: ["gas-laws"],
      },
      {
        id: "t2-4-f6",
        noteId: "t2-4",
        difficulty: 3,
        front: "Why does MgO not evolve hydrogen with dilute acid?",
        back: "The oxide supplies O^2- which forms water; there is no oxidation of H^+ to H_2 from the oxide alone in the same way as for the metal.",
        examPhrasing: "Magnesium metal reduces H^+ to H_2; its oxide reacts without H_2 evolution.",
        confusionPair: "metal vs oxide with acid",
        tags: ["MgO", "concept"],
      },
      {
        id: "t2-4-f7",
        noteId: "t2-4",
        difficulty: 3,
        front: "In acid-base titration, when must you use the stoichiometry from the full equation?",
        back: "When converting moles of titrant to moles of analyte if the molar ratio is not 1:1.",
        examPhrasing: "For diprotic acids, two moles of hydroxide may react per mole of acid.",
        confusionPair: "1:1 assumption always",
        tags: ["titration"],
      },
      {
        id: "t2-4-f8",
        noteId: "t2-4",
        difficulty: 4,
        front: "Why is gas volume from carbonate + acid often used to find purity?",
        back: "Moles of CO_2 from volume link directly to moles of carbonate in a 1:1 way for many simple carbonates.",
        examPhrasing: "Gas measurement determines amount of limiting solid reagent.",
        confusionPair: "mass loss vs gas volume",
        tags: ["purity"],
      },
      {
        id: "t2-4-f9",
        noteId: "t2-4",
        difficulty: 4,
        front: "When a question gives gas volumes for all reactants and products, what assumption is usually made?",
        back: "All gases measured at the same temperature and pressure so volume ratios equal mole ratios.",
        examPhrasing: "Gay-Lussac volume combining ratios apply under uniform conditions.",
        confusionPair: "different conditions volumes",
        tags: ["gas-volumes"],
      },
      {
        id: "t2-4-f10",
        noteId: "t2-4",
        difficulty: 5,
        front: "Why must H_2O(l) be excluded from gas volume calculations after combustion in oxygen?",
        back: "Liquid water occupies negligible volume compared to gas phases and does not follow the same molar gas volume rule.",
        examPhrasing: "Only gaseous species contribute to the stated gas volume at rtp.",
        confusionPair: "steam vs liquid water volumes",
        tags: ["combustion"],
      },
    ],
  },
};
