import type { SubtopicPracticePack } from "./types";

/**
 * Topic 8 (Cambridge 9701) — internal LO crosswalk for practice authoring.
 * Source slices: `data/syllabus/chemistry-9701-learning-outcomes.md` §8.1–8.3;
 * `noteId` ↔ `data/courses/chemistry-9701.json` codes `8.1`–`8.3`.
 *
 * 8.1 (t8-1): rate of reaction; collision frequency; effective / non-effective collisions;
 *   concentration and pressure (qualitative, effective collisions); rate from experimental data.
 * 8.2 (t8-2): define E_A; Boltzmann distribution and significance of E_A; temperature effect
 *   via distribution and via effective collision frequency.
 * 8.3 (t8-3): catalyst / catalysis; lower-E_A mechanism; Boltzmann view of catalysis;
 *   pathway diagrams with and without catalyst (section title also names homogeneous vs heterogeneous).
 */
export const CHEMISTRY_TOPIC8_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t8-1": {
    noteId: "t8-1",
    drills: [
      {
        id: "t8-1-d1",
        noteId: "t8-1",
        kind: "mcq",
        difficulty: 1,
        stem: "In kinetics, the rate of reaction is best described as",
        options: [
          { id: "A", text: "the equilibrium constant divided by the time taken to reach equilibrium" },
          { id: "B", text: "the change in concentration (or amount) of a specified substance per unit time" },
          { id: "C", text: "the total energy released by the reaction divided by its duration" },
          { id: "D", text: "the sum of the stoichiometric coefficients divided by time" },
        ],
        correctOptionId: "B",
        explanation:
          "Rate measures how fast a chosen quantity (usually concentration or amount) changes with time for a named species, using the sign convention required by the question.",
        distractorRationale: {
          A: "The equilibrium constant is a thermodynamic ratio at equilibrium, not a derivative with respect to time.",
          C: "Energy change relates to thermochemistry, not the kinetic definition of rate.",
          D: "Stoichiometric coefficients describe mole ratios in the equation, not the definition of rate.",
        },
        tags: ["8.1", "rate-definition"],
      },
      {
        id: "t8-1-d2",
        noteId: "t8-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which pair of statements about molecular collisions is correct for simple collision theory?",
        options: [
          { id: "A", text: "Every collision is effective; only slow collisions fail to react" },
          { id: "B", text: "A non-effective collision lacks sufficient energy or suitable orientation; an effective collision can lead to reaction" },
          { id: "C", text: "An effective collision always has low kinetic energy" },
          { id: "D", text: "Collision frequency depends only on temperature, never on concentration" },
        ],
        correctOptionId: "B",
        explanation:
          "An effective collision is one in which the colliding particles together possess at least the activation energy and a suitable orientation so that bonds can rearrange to form products; otherwise the collision is non-effective.",
        distractorRationale: {
          A: "Many collisions are non-effective because they are energetically or geometrically unsuitable.",
          C: "Effective collisions require at least enough energy along the reaction coordinate, not unusually low energy.",
          D: "Collision frequency increases with concentration (more particles per unit volume) as well as with temperature through speed.",
        },
        tags: ["8.1", "effective-collisions"],
      },
      {
        id: "t8-1-d3",
        noteId: "t8-1",
        kind: "mcq",
        difficulty: 2,
        stem: "For a homogeneous reaction in solution at constant temperature, increasing the concentration of a reactant increases the rate mainly because",
        options: [
          { id: "A", text: "the activation energy of the reaction becomes smaller" },
          { id: "B", text: "the frequency of collisions between reactant particles increases, so the frequency of effective collisions increases" },
          { id: "C", text: "the average kinetic energy of the molecules becomes much larger" },
          { id: "D", text: "the equilibrium constant increases" },
        ],
        correctOptionId: "B",
        explanation:
          "At fixed temperature the fraction of collisions that are effective is roughly constant, but more particles per unit volume raises total collision frequency and therefore the number of effective collisions per second.",
        distractorRationale: {
          A: "For a given elementary pathway, the activation energy barrier is not reduced simply by adding more reactant at the same temperature.",
          C: "Average kinetic energy in the bulk is set by temperature, not by diluting or concentrating a solution at constant T.",
          D: "The equilibrium constant at a given temperature is unchanged by concentration alone.",
        },
        tags: ["8.1", "concentration", "collision-frequency"],
      },
      {
        id: "t8-1-d4",
        noteId: "t8-1",
        kind: "mcq",
        difficulty: 2,
        stem: "For a gas-phase reaction at constant temperature, increasing the total pressure by compression (smaller volume, no inert gas added) increases the initial rate because",
        options: [
          { id: "A", text: "the activation energy always decreases when the gas is compressed" },
          { id: "B", text: "gas molecules are closer together, so collision frequency increases and more effective collisions occur per unit time" },
          { id: "C", text: "compression removes the need for molecular orientation in collisions" },
          { id: "D", text: "pressure changes always shift equilibrium to products" },
        ],
        correctOptionId: "B",
        explanation:
          "Higher pressure at constant temperature means higher number density of reactant molecules in the same volume, which increases collision frequency and hence the frequency of effective collisions if the fraction effective stays similar.",
        distractorRationale: {
          A: "Compression changes concentration (partial pressures), not the intrinsic barrier height for a simple qualitative picture at fixed T.",
          C: "Steric requirements are not removed by pressure; orientation can still matter for effective collisions.",
          D: "Whether equilibrium shifts depends on stoichiometry and conditions; the question concerns why the initial rate increases.",
        },
        tags: ["8.1", "pressure", "gases"],
      },
      {
        id: "t8-1-d5",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem:
          "Define the rate of reaction. Define the frequency of collisions, an effective collision, and a non-effective collision between reactant particles.",
        modelAnswerPoints: [
          "Rate of reaction: change in concentration (or amount) of a specified reactant or product per unit time, with an agreed sign convention so rate is positive for product formation when required.",
          "Frequency of collisions: number of collisions between relevant particles per unit time in the reaction mixture (depends on concentration and temperature among other factors).",
          "Effective collision: collision with sufficient energy and suitable orientation for bond rearrangement leading toward products along the pathway considered.",
          "Non-effective collision: collision that does not lead to reaction, for example because energy is below the threshold or orientation is unsuitable.",
        ],
        workedSolution: [
          "The rate of reaction is defined as the change in concentration, or alternatively the change in amount per unit volume, of a specified chemical species per unit time, and in examination answers I state clearly whether I am following reactant disappearance or product appearance and use the sign convention the question requires so that the quoted rate is positive when products are being formed.",
          "The frequency of collisions is the number of encounters between reactant particles that occur in a given time interval in the mixture, and it increases when more particles occupy the same volume or when they move faster on average at higher temperature.",
          "An effective collision is a collision in which the colliding particles together possess at least the activation energy and meet in a geometry that allows the necessary bonds to break and form so that the system can pass toward products, so such a collision can contribute to chemical change.",
          "A non-effective collision is any collision that does not lead to chemical change, most commonly because the combined kinetic energy along the line of centres is below the activation energy or because the mutual orientation does not expose the reactive sites, so no successful rearrangement occurs even though the particles have collided.",
        ],
        commonMistake:
          "Stating that all collisions react, or defining rate only as 1/total without naming a species and without a per-unit-time concentration change.",
        tags: ["8.1", "definitions"],
      },
      {
        id: "t8-1-d6",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Explain qualitatively why increasing the concentration of a reactant in a homogeneous mixture at constant temperature increases the rate of reaction. Refer explicitly to collision frequency and effective collisions.",
        modelAnswerPoints: [
          "Higher concentration means more reactant particles per unit volume.",
          "Collision frequency between reactant particles therefore increases.",
          "At constant temperature the proportion of collisions that are effective is approximately unchanged, so the frequency of effective collisions increases and the rate increases.",
        ],
        workedSolution: [
          "When the concentration of a reactant is increased at constant temperature, the number of moles of that reactant in each cubic decimetre of solution increases, so its particles are on average closer together in space.",
          "Because particles collide more often when they are closer together, the total number of collisions between reactant species per second in that volume rises, which means the frequency of collisions increases.",
          "At a fixed temperature the distribution of molecular energies is essentially unchanged, so the fraction of collisions that have at least the activation energy and a suitable orientation, and are therefore effective, stays roughly the same; consequently a higher collision frequency produces proportionally more effective collisions per unit time and the measured rate of reaction increases.",
        ],
        commonMistake:
          "Claiming that raising concentration greatly increases average molecular speed at constant temperature, rather than increasing collision frequency.",
        tags: ["8.1", "concentration", "explanation"],
      },
      {
        id: "t8-1-d7",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Explain qualitatively why increasing the total pressure of a gaseous reaction mixture at constant temperature (by decreasing volume, with composition otherwise unchanged) increases the initial rate. Refer to collision frequency and effective collisions.",
        modelAnswerPoints: [
          "Reducing volume at constant temperature increases the number density (concentration) of each gaseous reactant.",
          "Collision frequency therefore increases.",
          "With temperature unchanged the chance that a given collision is effective is similar, so more effective collisions occur per unit time and the initial rate is higher.",
        ],
        workedSolution: [
          "When the volume of a gaseous mixture is decreased at constant temperature while the amounts of reactant gases are unchanged, each gas occupies a smaller space so its partial pressure and its concentration expressed as moles per unit volume both increase.",
          "Higher number density means that gas molecules travel shorter average distances before meeting another molecule, so they collide more frequently per second than before compression.",
          "Because temperature is unchanged, the Maxwell–Boltzmann distribution of energies is essentially the same shape, so the proportion of collisions that are effective remains similar; therefore the increased collision frequency leads directly to a higher frequency of effective collisions and a higher initial rate of reaction.",
        ],
        commonMistake:
          "Confusing total pressure increased by adding inert gas at constant volume (partial pressures unchanged) with compression, which does change reactant partial pressures.",
        tags: ["8.1", "pressure", "gases"],
      },
      {
        id: "t8-1-d8",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "The concentration of reactant X in aqueous solution was 0.80 mol dm^-3 at t = 0 s and 0.56 mol dm^-3 at t = 120 s. Calculate the average rate of disappearance of X over this interval, and state the average rate of reaction with respect to X as a positive quantity if the question defines rate as always positive for the forward direction.",
        modelAnswerPoints: [
          "Change in concentration Delta[X] = 0.56 - 0.80 = -0.24 mol dm^-3.",
          "Average rate of change of [X] = Delta[X]/Delta t = -0.24/120 = -2.0 x 10^-3 mol dm^-3 s^-1 (disappearance).",
          "Positive forward rate with respect to consumption of X = -d[X]/dt = 2.0 x 10^-3 mol dm^-3 s^-1 (or equivalent clear statement).",
          "Units mol dm^-3 s^-1 shown in the final answer.",
        ],
        workedSolution: [
          "The change in concentration of X is Delta[X] = (0.56 - 0.80) mol dm^-3 = -0.24 mol dm^-3, which is negative because X is being consumed over the interval from 0 s to 120 s.",
          "The average rate of change of concentration is Delta[X]/Delta t = (-0.24 mol dm^-3)/(120 s) = -2.0 x 10^-3 mol dm^-3 s^-1, and this negative value correctly describes the average disappearance of X over that 120 s period.",
          "If the examination defines the rate of reaction as a positive quantity for the forward direction while X is a reactant, I report the average rate with respect to X as -d[X]/dt = +2.0 x 10^-3 mol dm^-3 s^-1, which is the magnitude of disappearance expressed in the required convention.",
          "The calculated rate therefore carries units mol dm^-3 s^-1, which are consistent with concentration divided by time.",
        ],
        commonMistake:
          "Dropping the minus sign when computing Delta[X], or omitting units so the numerical answer cannot be checked for consistency.",
        tags: ["8.1", "calculation", "experimental-rate"],
      },
      {
        id: "t8-1-d9",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Hydrogen gas was collected in a gas syringe. The volume reading was 18 cm^3 at 20 s and 52 cm^3 at 60 s. Assuming the volume reading is proportional to the amount of hydrogen formed over this stage, calculate the average rate of formation of hydrogen between 20 s and 60 s in cm^3 s^-1.",
        modelAnswerPoints: [
          "Change in volume Delta V = 52 - 18 = 34 cm^3.",
          "Change in time Delta t = 60 - 20 = 40 s.",
          "Average rate = Delta V/Delta t = 34/40 = 0.85 cm^3 s^-1.",
          "Final answer quoted with correct units.",
        ],
        workedSolution: [
          "Between 20 s and 60 s the volume of hydrogen in the syringe increases from 18 cm^3 to 52 cm^3, so the change in volume is Delta V = (52 - 18) cm^3 = 34 cm^3.",
          "The corresponding time interval is Delta t = (60 - 20) s = 40 s.",
          "The average rate of formation of hydrogen over this interval is therefore Delta V/Delta t = 34 cm^3 / 40 s = 0.85 cm^3 s^-1 when expressed to two significant figures consistent with the data.",
          "The rate carries units cm^3 s^-1 because it is a volume change per unit time, which is the natural measurable quantity in this apparatus-based experiment.",
        ],
        commonMistake:
          "Using the full 52 cm^3 from t = 0 instead of the change between 20 s and 60 s, or dividing by 60 s instead of the interval 40 s.",
        tags: ["8.1", "calculation", "experimental-rate"],
      },
      {
        id: "t8-1-d10",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "For the same reaction as in an aqueous kinetic run, [X] was 1.20 mol dm^-3 at t = 0 s, 0.96 mol dm^-3 at t = 20 s, and 0.78 mol dm^-3 at t = 40 s. (i) Calculate the average rate of disappearance of X over 0–20 s. (ii) Calculate the average rate over 20–40 s. (iii) Explain why the magnitude of the average rate is smaller in the second interval, using the ideas of collision frequency and effective collisions.",
        modelAnswerPoints: [
          "(i) Delta[X] = 0.96 - 1.20 = -0.24 mol dm^-3 over Delta t = 20 s.",
          "(i) Average rate of disappearance (positive convention) = 0.24/20 = 1.2 x 10^-2 mol dm^-3 s^-1.",
          "(ii) Delta[X] = 0.78 - 0.96 = -0.18 mol dm^-3 over Delta t = 20 s.",
          "(ii) Average rate magnitude = 0.18/20 = 9.0 x 10^-3 mol dm^-3 s^-1.",
          "(iii) [X] is lower in the second interval, so collision frequency involving X is lower.",
          "(iii) At constant T the fraction of collisions that are effective is similar, so fewer effective collisions per second and a smaller average rate.",
        ],
        workedSolution: [
          "For part (i), the change in concentration between 0 s and 20 s is Delta[X] = (0.96 - 1.20) mol dm^-3 = -0.24 mol dm^-3 over Delta t = 20 s, so the average rate of disappearance expressed as a positive quantity is -Delta[X]/Delta t = 0.24/20 = 1.2 x 10^-2 mol dm^-3 s^-1.",
          "For part (ii), between 20 s and 40 s we have Delta[X] = (0.78 - 0.96) mol dm^-3 = -0.18 mol dm^-3 over another 20 s interval, giving an average rate of disappearance -Delta[X]/Delta t = 0.18/20 = 9.0 x 10^-3 mol dm^-3 s^-1, which is smaller in magnitude than the value from part (i).",
          "For part (iii), as the reaction proceeds the concentration of X falls, so in each cubic decimetre there are fewer X particles available to collide with other reactant particles at the same temperature, which means the frequency of collisions involving X decreases compared with the start of the reaction.",
          "Because the temperature is unchanged, the proportion of collisions that are effective remains broadly similar, so a lower collision frequency produces fewer effective collisions per unit time and the measured average rate over the second interval is therefore smaller than over the first interval, which matches the numerical comparison from parts (i) and (ii).",
        ],
        commonMistake:
          "Using the initial concentration in the denominator, or claiming that activation energy changes between the two intervals without an external change in conditions.",
        tags: ["8.1", "calculation", "collision-theory"],
      },
    ],
    flashcards: [
      {
        id: "t8-1-f1",
        noteId: "t8-1",
        difficulty: 1,
        front: "Define rate of reaction (9701 register).",
        back: "Change in concentration (or amount per unit volume) of a stated species per unit time, with a clear sign convention.",
        examPhrasing: "Always name the species and whether you mean loss of reactant or gain of product.",
        tags: ["8.1", "definition"],
      },
      {
        id: "t8-1-f2",
        noteId: "t8-1",
        difficulty: 1,
        front: "What is meant by frequency of collisions?",
        back: "Number of collisions between relevant particles per unit time in the mixture.",
        examPhrasing: "Link higher concentration or gas pressure to higher collision frequency.",
        tags: ["8.1", "collisions"],
      },
      {
        id: "t8-1-f3",
        noteId: "t8-1",
        difficulty: 2,
        front: "Effective collision — two requirements?",
        back: "Sufficient energy (at least activation energy along the pathway) and suitable orientation / geometry for bond rearrangement.",
        examPhrasing: "Contrast with non-effective collisions that do not lead to product.",
        confusionPair: "collision vs effective collision",
        tags: ["8.1", "effective"],
      },
      {
        id: "t8-1-f4",
        noteId: "t8-1",
        difficulty: 2,
        front: "Non-effective collision?",
        back: "A collision that does not lead to reaction (typically too little energy or wrong orientation).",
        examPhrasing: "Most collisions are non-effective at moderate temperatures.",
        tags: ["8.1", "non-effective"],
      },
      {
        id: "t8-1-f5",
        noteId: "t8-1",
        difficulty: 2,
        front: "Why does higher [reactant] at constant T increase rate?",
        back: "More particles per unit volume raises collision frequency; similar fraction effective, so more effective collisions per second.",
        examPhrasing: "Use both collision frequency and effective collisions in one chain of reasoning.",
        tags: ["8.1", "concentration"],
      },
      {
        id: "t8-1-f6",
        noteId: "t8-1",
        difficulty: 3,
        front: "Gas reaction: why does compression (smaller V, same T) speed the initial rate?",
        back: "Higher number density / partial pressures increase collision frequency; temperature unchanged so effective fraction similar.",
        examPhrasing: "Distinguish compression from adding inert gas at constant volume.",
        confusionPair: "total pressure vs partial pressure",
        tags: ["8.1", "pressure"],
      },
      {
        id: "t8-1-f7",
        noteId: "t8-1",
        difficulty: 3,
        front: "Average rate from concentration data?",
        back: "Delta[species]/Delta t for the interval; take care with signs and units mol dm^-3 s^-1.",
        examPhrasing: "Show working: substitution, division, units.",
        tags: ["8.1", "calculation"],
      },
      {
        id: "t8-1-f8",
        noteId: "t8-1",
        difficulty: 3,
        front: "Average rate from gas volume vs time?",
        back: "Delta V/Delta t in cm^3 s^-1 (or dm^3 s^-1) for the stated interval.",
        examPhrasing: "Use the correct time window, not always t = 0.",
        tags: ["8.1", "practical"],
      },
      {
        id: "t8-1-f9",
        noteId: "t8-1",
        difficulty: 4,
        front: "Instantaneous rate from a concentration–time graph?",
        back: "Gradient of tangent to the curve at that time; steeper tangent means faster rate at that instant.",
        examPhrasing: "Average chord slope is not always equal to initial instantaneous rate.",
        tags: ["8.1", "graphs"],
      },
      {
        id: "t8-1-f10",
        noteId: "t8-1",
        difficulty: 4,
        front: "Why does rate often fall as a batch reaction proceeds?",
        back: "Reactant concentrations drop, lowering collision frequency; at constant T the fraction effective is similar, so fewer effective collisions per second.",
        examPhrasing: "Tie the falling rate to concentration, not to a mysteriously rising E_A.",
        tags: ["8.1", "interpretation"],
      },
    ],
  },
  "t8-2": {
    noteId: "t8-2",
    drills: [
      {
        id: "t8-2-d1",
        noteId: "t8-2",
        kind: "mcq",
        difficulty: 1,
        stem: "The activation energy, E_A, is defined as",
        options: [
          { id: "A", text: "the enthalpy change of the overall reaction" },
          { id: "B", text: "the minimum energy required for a collision to be effective" },
          { id: "C", text: "the average kinetic energy of all molecules in the sample" },
          { id: "D", text: "the total bond energy of the reactants" },
        ],
        correctOptionId: "B",
        explanation:
          "For Cambridge 9701 Topic 8, E_A is specified as the minimum energy required for a collision to be effective, linking the barrier to successful reaction.",
        distractorRationale: {
          A: "Enthalpy change describes the energy difference between reactant and product states, not the collision threshold.",
          C: "Average kinetic energy is set by temperature on a simple model; it is not the same quantity as the activation barrier.",
          D: "Bond energies describe particular bonds, not the minimum energy for an effective collision along the reaction pathway.",
        },
        tags: ["8.2", "E_A", "definition"],
      },
      {
        id: "t8-2-d2",
        noteId: "t8-2",
        kind: "mcq",
        difficulty: 2,
        stem: "On a Maxwell–Boltzmann distribution of molecular energies at a fixed temperature, the activation energy E_A is most often shown as",
        options: [
          { id: "A", text: "the height of the peak of the curve" },
          { id: "B", text: "a vertical energy marker to the right of the peak; the area under the curve beyond E_A relates to particles able to react on collision" },
          { id: "C", text: "the total area under the whole curve" },
          { id: "D", text: "the energy where the curve touches the horizontal axis on the left" },
        ],
        correctOptionId: "B",
        explanation:
          "E_A marks an energy threshold on the horizontal axis; the fraction of molecules with energy at least E_A is given by the tail area beyond that marker, which controls how many collisions can be effective.",
        distractorRationale: {
          A: "The peak corresponds to the most probable energy, not the activation threshold.",
          C: "The whole curve normalises to the total number of particles, not to E_A.",
          D: "The low-energy side of the distribution describes molecules with little kinetic energy, not the barrier for reaction.",
        },
        tags: ["8.2", "boltzmann"],
      },
      {
        id: "t8-2-d3",
        noteId: "t8-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Compared with a lower temperature, the same gas sample at a higher temperature has a Maxwell–Boltzmann curve that",
        options: [
          { id: "A", text: "has the same peak height and the same peak position" },
          { id: "B", text: "is broader and the peak is shifted to higher energy; the mean energy increases" },
          { id: "C", text: "always has a lower peak no matter the temperature change" },
          { id: "D", text: "shows no molecules with energy greater than E_A" },
        ],
        correctOptionId: "B",
        explanation:
          "Raising temperature increases the average and spread of molecular energies, broadening the distribution and moving probability toward higher energies, which increases the high-energy tail beyond a fixed E_A.",
        distractorRationale: {
          A: "Changing temperature changes the distribution shape and mean energy, not just the label on the axis.",
          C: "Peak height falls when the curve broadens at higher T, but the statement must be tied to the correct physical picture, not a blanket rule without context.",
          D: "There are always some molecules in the high-energy tail; the question is how many lie beyond E_A.",
        },
        tags: ["8.2", "boltzmann", "temperature"],
      },
      {
        id: "t8-2-d4",
        noteId: "t8-2",
        kind: "mcq",
        difficulty: 2,
        stem: "For a fixed activation energy, raising the temperature increases the reaction rate partly because",
        options: [
          { id: "A", text: "molecules collide less frequently but each collision is always effective" },
          { id: "B", text: "molecules move faster on average, so collision frequency increases, and more molecules exceed E_A so more collisions are effective" },
          { id: "C", text: "E_A always decreases in exact proportion to T" },
          { id: "D", text: "the activation energy becomes exactly zero above room temperature" },
        ],
        correctOptionId: "B",
        explanation:
          "The syllabus expects both ideas: the Boltzmann tail beyond E_A grows with temperature, and faster motion increases collision frequency, both increasing the frequency of effective collisions.",
        distractorRationale: {
          A: "Higher temperature increases collision frequency in the gas phase; not every collision is effective.",
          C: "E_A is treated as a property of the pathway for a qualitative discussion at fixed conditions, not as a quantity that tracks T in this simple way.",
          D: "Reactions still require a positive threshold energy in the usual model.",
        },
        tags: ["8.2", "temperature", "collisions"],
      },
      {
        id: "t8-2-d5",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Define the activation energy, E_A, exactly in the terms used in the syllabus for collision-based reaction.",
        modelAnswerPoints: [
          "E_A is the minimum energy required for a collision to be effective.",
          "Effective means the collision can lead to chemical change along the pathway (sufficient energy for the barrier, with orientation where relevant).",
          "E_A is therefore linked to the energy threshold separating non-effective low-energy collisions from collisions that can contribute to reaction.",
          "E_A is a kinetic barrier concept, not the same as the overall enthalpy change Delta H of the reaction.",
        ],
        workedSolution: [
          "The activation energy, E_A, is defined as the minimum energy that colliding particles must provide in a collision if that collision is to be effective.",
          "In this syllabus context an effective collision is one that can lead to chemical change, which requires the colliding particles together to reach or exceed the energy barrier associated with bond rearrangement along the reaction pathway, together with any orientation requirement implied by the mechanism.",
          "Therefore E_A marks the energy threshold on a molecular energy diagram: collisions that involve less combined energy along the reaction coordinate than E_A are classified as non-effective for forming products, whereas those at or above the threshold can be effective if orientation is also suitable.",
        ],
        commonMistake:
          "Defining E_A as the overall enthalpy change of the reaction or as the average kinetic energy of the sample.",
        tags: ["8.2", "definition"],
      },
      {
        id: "t8-2-d6",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Sketch mentally a Maxwell–Boltzmann distribution of molecular energies at one temperature for a gas. Mark E_A on the energy axis. Explain the significance of E_A using the areas under your curve.",
        modelAnswerPoints: [
          "Axes: molecular kinetic energy (horizontal) and number / fraction of molecules (vertical); curve starts at zero, rises to a peak, tails to high energy.",
          "Vertical line at E_A separates lower-energy collisions from those with at least the threshold energy.",
          "Area under the curve to the right of E_A is proportional to molecules with energy >= E_A; only these collisions can be effective (with orientation).",
          "Area to the left corresponds to collisions that cannot surmount the barrier on a simple model.",
        ],
        workedSolution: [
          "I sketch the horizontal axis as molecular kinetic energy and the vertical axis as the number of molecules having energies in a small interval, then draw a curve that begins at the origin, rises to a single maximum, and falls smoothly toward zero at very high energies, which is the characteristic Maxwell–Boltzmann shape at a chosen temperature.",
          "I draw a vertical line on the energy axis at the value labelled E_A, because this is the activation energy that marks the minimum energy required for a collision to be effective according to the syllabus definition.",
          "The area under the curve to the right of the E_A marker represents the fraction of molecules whose kinetic energy is at least equal to the activation energy, and these are the molecules that can in principle participate in effective collisions if orientation is also suitable, so this area is directly related to how many collisions per second can overcome the energy barrier.",
          "The area under the curve to the left of E_A corresponds to molecules whose energies are below the threshold, so collisions involving only such combinations cannot be effective in surmounting the barrier on the simple model, which is why that region represents non-reactive or non-effective collisions for the forward process.",
        ],
        commonMistake:
          "Identifying E_A with the peak of the curve, or claiming the whole area under the curve equals E_A.",
        tags: ["8.2", "boltzmann", "diagram"],
      },
      {
        id: "t8-2-d7",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Explain qualitatively, using the Maxwell–Boltzmann distribution, why increasing the temperature increases the rate of a reaction with a fixed positive activation energy E_A.",
        modelAnswerPoints: [
          "At higher T the distribution spreads and shifts to higher energies.",
          "The peak moves to higher energy and is typically lower because the same total area must still represent all molecules.",
          "The fraction of molecules with energy >= E_A (tail beyond E_A) increases.",
          "Therefore more collisions involve enough energy to be potentially effective, increasing the frequency of effective collisions and the rate.",
        ],
        workedSolution: [
          "When the temperature of the gas or liquid sample is raised, the Maxwell–Boltzmann distribution of molecular kinetic energies becomes broader and its maximum moves to higher energy, reflecting the fact that the average kinetic energy of the molecules increases while the total number of molecules is unchanged.",
          "Because the activation energy E_A is fixed as a vertical marker on the energy axis for that reaction pathway, the fraction of molecules whose energies lie in the tail at or above E_A is given by the relative area under the curve beyond that marker, and this fraction increases when the temperature is raised.",
          "Consequently, a larger proportion of collisions involves partners whose combined energy along the reaction coordinate reaches the minimum required for an effective collision, so the frequency of effective collisions increases even before considering any separate effect of faster motion on collision frequency.",
          "The observed rate therefore increases with temperature in this model because the energy distribution places more molecules on the high-energy side of the barrier where collisions can succeed.",
        ],
        commonMistake:
          "Saying every molecule gains exactly the same extra energy, instead of describing a redistribution with a fatter high-energy tail.",
        tags: ["8.2", "boltzmann", "temperature"],
      },
      {
        id: "t8-2-d8",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Explain qualitatively, in terms of the frequency of effective collisions only, why raising the temperature increases the rate of reaction between gases at constant volume.",
        modelAnswerPoints: [
          "Higher T means higher average molecular speed.",
          "Collision frequency increases because particles meet more often.",
          "A greater fraction of individual collisions involves combined energy at least equal to E_A at higher T.",
          "The frequency of effective collisions (collisions that are both frequent enough and energetic enough) therefore increases, so the measured rate increases.",
        ],
        workedSolution: [
          "When the temperature of a gaseous mixture is increased at constant volume, the average speed of the molecules increases because kinetic energy is proportional to absolute temperature on the idealised model used at this level.",
          "Faster molecules traverse the container more quickly and encounter one another more often, so the total number of collisions per unit time per unit volume, that is the collision frequency, increases compared with the lower-temperature case.",
          "At the same time, a larger share of those collisions involves combined energies that meet or exceed the activation energy E_A, so a greater proportion of collisions is effective in the sense required for bond rearrangement.",
          "Because the rate depends on how many effective collisions occur per second, both the rise in collision frequency and the rise in the effective fraction work together to increase the frequency of effective collisions and therefore increase the measured rate.",
        ],
        commonMistake:
          "Mentioning only collision frequency without the energy threshold, or only the Boltzmann tail without acknowledging faster motion and more frequent collisions.",
        tags: ["8.2", "collisions", "temperature"],
      },
      {
        id: "t8-2-d9",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Give a single coherent account of why an increase in temperature increases reaction rate for a reaction with fixed E_A, explicitly using both (i) the Maxwell–Boltzmann distribution and (ii) the frequency of effective collisions.",
        modelAnswerPoints: [
          "(i) Raising T broadens the Maxwell–Boltzmann curve and shifts probability toward higher molecular energies.",
          "(i) The area under the curve beyond the fixed E_A marker increases, so more molecules can exceed the barrier.",
          "(ii) Higher average speed at higher T increases the number of collisions per unit time per unit volume at unchanged concentration.",
          "(ii) Among those collisions, a greater share meets or exceeds E_A, so each collision is more likely to be effective.",
          "The frequency of effective collisions is proportional to collision frequency multiplied by the fraction that exceed E_A, so both factors increase with T.",
          "Hence the observed rate increases when temperature rises at fixed E_A and fixed concentration.",
        ],
        workedSolution: [
          "From the Maxwell–Boltzmann viewpoint, raising the temperature reshapes the distribution of molecular energies so that a larger fraction of molecules lies in the high-energy tail beyond the fixed activation energy E_A, which means that any randomly chosen collision is more likely to involve partners whose combined energy is sufficient for an effective collision along the pathway.",
          "From the collision-frequency viewpoint, the same temperature rise increases the average speed of molecules in the sample, so at constant concentration they collide more often per second, which increases the raw number of collision events available for reaction even before considering whether each event is effective.",
          "Putting the two ideas together, the frequency of effective collisions is proportional both to how often collisions happen and to what fraction of those collisions clears the energy threshold, so an increase in temperature increases collision frequency while simultaneously increasing the fraction that are energetically effective.",
          "The measured rate therefore rises sharply with temperature for many reactions because both factors multiply in the same direction, which is exactly the combined qualitative explanation expected when the syllabus asks for temperature effects in terms of the distribution and of effective collisions.",
        ],
        commonMistake:
          "Treating the two explanations as contradictory alternatives instead of complementary parts of one argument.",
        tags: ["8.2", "synthesis"],
      },
      {
        id: "t8-2-d10",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Two Maxwell–Boltzmann curves are drawn for the same gas sample at temperatures T_low and T_high, with T_high > T_low. The same E_A line is drawn for both. Describe how the curves differ and how the proportion of molecules with energy >= E_A changes. Relate your answer to reaction rate.",
        modelAnswerPoints: [
          "At T_high the distribution is broader and shifted toward higher energies than at T_low for the same sample size.",
          "The most probable energy increases with temperature, and the peak height typically falls because the same area must represent all molecules.",
          "The same vertical E_A line is drawn on both curves for the reaction considered.",
          "The tail area (fraction of molecules with energy >= E_A) is larger on the T_high curve than on the T_low curve.",
          "Therefore a randomly chosen collision at T_high is more likely to involve enough energy to be potentially effective.",
          "With concentration and other factors fixed, the reaction rate is therefore greater at T_high than at T_low.",
        ],
        workedSolution: [
          "When I sketch two Maxwell–Boltzmann distributions for the same amount of gas, the curve for the higher temperature T_high is shifted toward higher molecular energies and is broader than the curve for T_low, while the peak for T_high is lower than the peak for T_low because the same total probability must still integrate to the whole sample.",
          "If I draw the same vertical activation energy marker E_A on both distributions, the tail region under the curve to the right of E_A is visibly larger for T_high than for T_low, which means that a greater fraction of molecules possesses kinetic energy at least equal to E_A at the higher temperature.",
          "Because reaction rate on this model scales with how many collisions per second exceed the energy threshold with suitable orientation, the larger high-energy tail at T_high implies that a greater proportion of collisions can be effective at that temperature.",
          "Therefore, for fixed concentration and fixed E_A, the reaction proceeds faster at T_high than at T_low, which is how I interpret the pair of Boltzmann curves in terms of the expected change in rate.",
        ],
        commonMistake:
          "Claiming the total number of molecules above E_A decreases when T increases, or forgetting that the curves must be compared at the same E_A line.",
        tags: ["8.2", "boltzmann", "interpretation"],
      },
    ],
    flashcards: [
      {
        id: "t8-2-f1",
        noteId: "t8-2",
        difficulty: 1,
        front: "Define E_A (9701 Topic 8).",
        back: "Minimum energy required for a collision to be effective.",
        examPhrasing: "Quote the syllabus wording for full definitional credit.",
        tags: ["8.2", "definition"],
      },
      {
        id: "t8-2-f2",
        noteId: "t8-2",
        difficulty: 1,
        front: "On an energy distribution, what does the tail beyond E_A represent?",
        back: "Molecules with enough energy that their collisions can be effective (orientation still matters).",
        examPhrasing: "Relate tail area to rate at two temperatures.",
        tags: ["8.2", "boltzmann"],
      },
      {
        id: "t8-2-f3",
        noteId: "t8-2",
        difficulty: 2,
        front: "Higher T: what happens to the Maxwell–Boltzmann peak?",
        back: "Peak moves to higher energy and is typically lower and broader (same area).",
        examPhrasing: "Sketch two curves on one set of axes.",
        confusionPair: "peak energy vs E_A",
        tags: ["8.2", "sketch"],
      },
      {
        id: "t8-2-f4",
        noteId: "t8-2",
        difficulty: 2,
        front: "Why does higher T increase collision frequency?",
        back: "Molecules move faster on average, so they collide more often at the same concentration.",
        examPhrasing: "Pair with Boltzmann tail argument for full temperature explanation.",
        tags: ["8.2", "collisions"],
      },
      {
        id: "t8-2-f5",
        noteId: "t8-2",
        difficulty: 3,
        front: "9701 synthesis: temperature increases rate — two parallel ideas?",
        back: "Larger fraction of molecules >= E_A (distribution) and more collisions per second (speed).",
        examPhrasing: "Use both Boltzmann and effective-collision language in one answer.",
        tags: ["8.2", "exam-technique"],
      },
      {
        id: "t8-2-f6",
        noteId: "t8-2",
        difficulty: 3,
        front: "Does E_A change when you only heat the same reaction?",
        back: "In the basic qualitative model E_A is drawn as a fixed barrier; rate changes because populations and speeds change.",
        examPhrasing: "Do not confuse E_A with Delta H.",
        confusionPair: "E_A vs Delta H",
        tags: ["8.2", "concept"],
      },
      {
        id: "t8-2-f7",
        noteId: "t8-2",
        difficulty: 4,
        front: "Low T vs high T: which has fewer molecules above a fixed E_A?",
        back: "The lower-temperature distribution has a smaller tail beyond E_A.",
        examPhrasing: "Shade the region beyond E_A in an exam sketch.",
        tags: ["8.2", "boltzmann"],
      },
      {
        id: "t8-2-f8",
        noteId: "t8-2",
        difficulty: 4,
        front: "Why is a high-E_A reaction very sensitive to temperature?",
        back: "At moderate T only a tiny tail lies beyond a large E_A; small T changes alter that tail sharply.",
        examPhrasing: "Link narrow tail to strong rate response.",
        tags: ["8.2", "interpretation"],
      },
      {
        id: "t8-2-f9",
        noteId: "t8-2",
        difficulty: 5,
        front: "Exam trap: Celsius on a Boltzmann argument?",
        back: "Distribution plots use molecular energies tied to kelvin temperature internally; convert T to K when comparing absolute temperatures.",
        examPhrasing: "Always check T is in kelvin for ratio arguments.",
        tags: ["8.2", "units"],
      },
      {
        id: "t8-2-f10",
        noteId: "t8-2",
        difficulty: 5,
        front: "Non-effective collision despite high speed — possible?",
        back: "Yes if combined energy along the reaction coordinate is still below E_A or orientation is wrong.",
        examPhrasing: "Effective requires energy threshold and suitable geometry.",
        tags: ["8.2", "precision"],
      },
    ],
  },
  "t8-3": {
    noteId: "t8-3",
    drills: [
      {
        id: "t8-3-d1",
        noteId: "t8-3",
        kind: "mcq",
        difficulty: 1,
        stem: "A catalyst increases the rate of a reaction primarily because it",
        options: [
          { id: "A", text: "increases the equilibrium constant K at the same temperature" },
          { id: "B", text: "provides a different reaction mechanism with a lower activation energy along that pathway" },
          { id: "C", text: "is consumed in the overall stoichiometric equation" },
          { id: "D", text: "lowers the enthalpy change Delta H between reactants and products" },
        ],
        correctOptionId: "B",
        explanation:
          "The syllabus requires that, in the presence of a catalyst, the reaction follows a different mechanism with lower activation energy; thermodynamic quantities for the same overall transformation at the same temperature are unchanged.",
        distractorRationale: {
          A: "K at a given temperature is a thermodynamic constant for the overall reaction; a catalyst changes the path, not the difference in standard states that fixes K.",
          C: "A true catalyst is regenerated; it may appear in elementary steps but is not consumed overall in the balanced equation.",
          D: "Delta H depends on initial and final bulk states; the catalyst provides an alternative route between the same states.",
        },
        tags: ["8.3", "catalyst", "mechanism"],
      },
      {
        id: "t8-3-d2",
        noteId: "t8-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Compared with the uncatalysed reaction at the same temperature, a catalysed route is correctly described by",
        options: [
          { id: "A", text: "the same mechanism and the same E_A" },
          { id: "B", text: "a different mechanism and a lower E_A for the catalysed pathway" },
          { id: "C", text: "a higher E_A so molecules react more slowly" },
          { id: "D", text: "removal of all molecular collisions" },
        ],
        correctOptionId: "B",
        explanation:
          "Catalysis always implies an alternative pathway; the catalytic pathway is drawn with a lower barrier E_A than the uncatalysed route on a reaction pathway diagram.",
        distractorRationale: {
          A: "If the mechanism and E_A were identical, the catalyst would not change the rate in this model.",
          C: "A higher E_A would slow the reaction along that path, which is the opposite of catalysis.",
          D: "Molecules still collide; the catalyst changes how they are brought to the transition region.",
        },
        tags: ["8.3", "E_A", "mechanism"],
      },
      {
        id: "t8-3-d3",
        noteId: "t8-3",
        kind: "mcq",
        difficulty: 2,
        stem: "The catalytic effect may be explained using the Maxwell–Boltzmann distribution at fixed temperature because",
        options: [
          { id: "A", text: "the catalyst removes the activation energy entirely so E_A becomes undefined" },
          { id: "B", text: "the catalysed pathway corresponds to a lower energy threshold, so a larger fraction of molecules has enough energy to react on that pathway" },
          { id: "C", text: "the catalyst cools the mixture so more molecules lie below any barrier" },
          { id: "D", text: "the distribution becomes rectangular at the surface of a catalyst" },
        ],
        correctOptionId: "B",
        explanation:
          "Lowering the effective barrier for the catalysed mechanism moves the threshold marker to lower energy on the same molecular energy axis, increasing the tail population above the new threshold.",
        distractorRationale: {
          A: "There is still a barrier along the catalysed route; it is lower, not absent in the usual diagram.",
          C: "A catalyst is not assumed to cool the bulk; the explanation is about pathway energy, not temperature drop.",
          D: "The Maxwell–Boltzmann shape is not replaced by a rectangle in this qualitative account.",
        },
        tags: ["8.3", "boltzmann"],
      },
      {
        id: "t8-3-d4",
        noteId: "t8-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which example best illustrates heterogeneous catalysis?",
        options: [
          { id: "A", text: "H+(aq) from an acid catalysing ester hydrolysis in the same aqueous solution" },
          { id: "B", text: "Iron surfaces in the Haber process with gaseous N2 and H2" },
          { id: "C", text: "A dissolved transition metal ion and its substrates, all in one solution phase" },
          { id: "D", text: "A spark that initiates combustion, consumed as the reaction proceeds" },
        ],
        correctOptionId: "B",
        explanation:
          "Heterogeneous catalysis involves a catalyst in a different phase from the reactants, commonly a solid catalyst with gaseous reactants, as in the Haber process iron catalyst.",
        distractorRationale: {
          A: "This is homogeneous catalysis: catalyst and reactants share the same phase.",
          C: "All species in one solution phase is homogeneous catalysis, not heterogeneous.",
          D: "A spark is an initiation source, not a regenerated catalytic cycle in the usual sense.",
        },
        tags: ["8.3", "heterogeneous"],
      },
      {
        id: "t8-3-d5",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Explain and use the terms catalyst and catalysis in the context of increasing reaction rate without changing the overall chemical change.",
        modelAnswerPoints: [
          "Catalysis is the process in which a catalyst increases the rate at which a reaction approaches equilibrium.",
          "A catalyst is a substance that provides an alternative pathway and is regenerated, so it is not consumed in the overall stoichiometry.",
          "The same overall reaction occurs, but faster, because the catalysed mechanism has a lower activation energy than the uncatalysed route under the same conditions.",
          "The equilibrium constant at a given temperature is unchanged because reactant and product standard states are unchanged.",
          "Forward and reverse rates are both increased on the simple model, so the system reaches the same equilibrium composition more quickly.",
        ],
        workedSolution: [
          "Catalysis is the phenomenon in which a relatively small quantity of a substance called a catalyst increases the rate of a chemical reaction so that equilibrium is reached sooner, while the initial and final chemical states described by the overall equation remain the same as they would be without the catalyst.",
          "A catalyst is defined as a substance that takes part in elementary steps by binding or activating reactants, reorganising them toward products, and then being released unchanged in amount and identity over a full catalytic cycle, which is why it does not appear as a net consumed reagent in the overall balanced equation.",
          "In examination language I therefore say that catalysis speeds the reaction by offering a different mechanism with a lower activation energy along that catalysed pathway, which increases the frequency of effective collisions or successful passages through the transition region without altering the net chemical change written between reactants and products.",
        ],
        commonMistake:
          "Describing the catalyst as a normal stoichiometric reactant that is used up, or claiming it changes the overall products formed at equilibrium.",
        tags: ["8.3", "definitions"],
      },
      {
        id: "t8-3-d6",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem:
          "Explain, for a reversible reaction at constant temperature, that in the presence of a catalyst the reaction has a different mechanism with lower activation energy. State what happens to the forward and reverse activation barriers on a simple two-path diagram.",
        modelAnswerPoints: [
          "Catalyst introduces an alternative route with different intermediates (different mechanism).",
          "Forward E_A along the catalysed path is lower than uncatalysed forward E_A.",
          "Reverse barrier from products is also lowered similarly so both directions speed up; equilibrium constant unchanged at that T.",
          "On a two-path diagram the catalysed curve shows a lower summit from reactants toward products than the uncatalysed curve.",
          "The return path from products to reactants via the catalyst also crosses a lower maximum than the uncatalysed reverse barrier.",
        ],
        workedSolution: [
          "When a catalyst is present, reactants are converted into products by a sequence of elementary steps that pass through different intermediates and transition states from those on the uncatalysed pathway, so the mechanism is genuinely different even though the overall stoichiometry linking the same bulk reactants to the same bulk products is preserved.",
          "On a reaction pathway diagram the catalysed curve rises from reactants to a transition-state maximum that is lower in energy than the maximum on the uncatalysed curve, which means the activation energy for the forward reaction measured from reactants to the rate-limiting transition state of the catalysed path is smaller than that for the uncatalysed forward path.",
          "For a reversible system at the same temperature, the catalyst lowers the barrier from products back to the same catalytic cycle in the reverse direction as well, so both forward and reverse rates increase and the equilibrium constant, which depends only on the standard Gibbs energies of reactants and products at that temperature, does not change.",
        ],
        commonMistake:
          "Saying only the forward barrier is lowered while ignoring the reverse pathway, which would incorrectly imply a shift in K.",
        tags: ["8.3", "mechanism", "E_A"],
      },
      {
        id: "t8-3-d7",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Explain the catalytic effect in terms of the Maxwell–Boltzmann distribution of molecular energies at a fixed temperature, comparing the uncatalysed pathway with activation energy E_A(uncat) and a catalysed pathway with a lower threshold E_A(cat).",
        modelAnswerPoints: [
          "Same Maxwell–Boltzmann curve at fixed T for the sample.",
          "Lower threshold E_A(cat) < E_A(uncat) means a larger area / fraction of molecules with energy >= threshold.",
          "More collisions can be effective on the catalysed route, so rate increases.",
          "The catalysed pathway is represented by a lower energy marker on the same horizontal energy axis as the uncatalysed E_A.",
          "Orientation requirements may still apply, but more pairs now meet the energy requirement for the catalysed mechanism.",
        ],
        workedSolution: [
          "At a fixed temperature the gas or liquid sample possesses a Maxwell–Boltzmann distribution of molecular energies that is unchanged by the mere presence of a catalyst, because temperature fixes the average energy content of the molecules in the bulk in this qualitative picture.",
          "The uncatalysed reaction requires collisions to supply at least the activation energy E_A(uncat) along the direct pathway, whereas the catalysed mechanism corresponds to a different route whose rate-limiting step is associated with a smaller energy demand E_A(cat) from the same starting Maxwell–Boltzmann population.",
          "When I mark both thresholds on the same energy axis, the fraction of molecules with kinetic energy at least equal to E_A(cat) is larger than the fraction with energy at least equal to E_A(uncat), because the tail integral from a lower energy cut-off is always greater than the tail integral from a higher cut-off on the same curve.",
          "Therefore more molecular pairs can undergo effective collisions or successful reorganisations per second along the catalysed pathway, which is the Boltzmann-based explanation of why the catalysed reaction is faster at the same temperature even though the underlying energy distribution of the molecules has not changed.",
        ],
        commonMistake:
          "Drawing a completely new distribution for the catalysed case instead of the same distribution with a lower threshold line.",
        tags: ["8.3", "boltzmann"],
      },
      {
        id: "t8-3-d8",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem:
          "Construct a reaction pathway (energy profile) diagram for an exothermic reaction, showing one curve without a catalyst and one with an effective catalyst. Label reactants, products, E_A(uncat), E_A(cat), and the overall energy change between reactant and product levels. Explain how your diagram shows that the catalyst does not change Delta H for the overall reaction.",
        modelAnswerPoints: [
          "Vertical axis: energy; horizontal axis: reaction coordinate.",
          "Reactant and product horizontal levels identical for both paths; products lower than reactants for exothermic overall change.",
          "Uncatalysed path has higher summit than catalysed path: E_A(uncat) > E_A(cat).",
          "Vertical gap between reactant and product levels (Delta H) same for both paths.",
          "E_A for each path is measured from the reactant plateau to the respective maximum along that path.",
          "Catalysed and uncatalysed curves share the same start and end energies, so the catalyst changes the barrier, not the overall energy change between reactants and products.",
        ],
        workedSolution: [
          "I draw the vertical axis as enthalpy or general energy and the horizontal axis as extent of reaction or reaction coordinate, then place the reactant energy level on the left and the product energy level on the right, with the product level clearly lower than the reactant level to show an overall exothermic reaction for the stoichiometry considered.",
          "For the uncatalysed pathway I sketch a single curve from the reactant level up to a maximum transition-state region and then down to the product level, and I label the vertical energy difference from reactants to that maximum as E_A(uncat), which is the activation energy barrier for the uncatalysed mechanism.",
          "For the catalysed pathway I sketch a second curve that begins and ends at exactly the same reactant and product horizontal lines but passes through a lower maximum, and I label the smaller barrier from reactants to that catalysed maximum as E_A(cat), satisfying E_A(cat) < E_A(uncat).",
          "Because both curves start on the same reactant line and finish on the same product line, the vertical separation between reactant and product levels, which represents the overall enthalpy change Delta H for the overall reaction, is identical for the catalysed and uncatalysed drawings, which shows pictorially that the catalyst lowers the kinetic barrier without altering the thermodynamic difference between the same initial and final states.",
        ],
        commonMistake:
          "Drawing catalysed products at a different energy from uncatalysed products, which would wrongly imply the catalyst changes Delta H.",
        tags: ["8.3", "pathway", "diagram"],
      },
      {
        id: "t8-3-d9",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Contrast homogeneous catalysis with heterogeneous catalysis. Give one clear example of each type related to reactions you study at this level.",
        modelAnswerPoints: [
          "Homogeneous: catalyst and reactants in the same phase (commonly all aqueous or all gaseous).",
          "Heterogeneous: catalyst in a different phase from reactants (often solid catalyst, fluid reactants).",
          "Homogeneous example: H+(aq) catalysing ester hydrolysis with all species in aqueous solution.",
          "Heterogeneous example: solid iron catalyst with gaseous N2 and H2 in ammonia synthesis.",
          "Contrast: heterogeneous mechanisms often involve adsorption and surface steps at a phase boundary; homogeneous mechanisms occur throughout the bulk phase.",
        ],
        workedSolution: [
          "Homogeneous catalysis occurs when the catalyst is present in the same phase as all of the main reactants, for example when protons in aqueous solution catalyse the hydrolysis of an ester so that every reacting species participates in collisions within a single liquid phase.",
          "Heterogeneous catalysis occurs when the catalyst occupies a different phase from at least one key reactant, which is most familiar when a solid catalyst contacts flowing gases or liquids, as in the iron-based catalyst beds used industrially for the synthesis of ammonia from nitrogen and hydrogen.",
          "The essential contrast I state in an examination is therefore whether a phase boundary dominates the mechanism through adsorption and surface reaction, as in heterogeneous systems, or whether all rate-determining encounters occur homogeneously throughout a single bulk phase, as in typical acid–base or organometallic catalysis in solution.",
          "I therefore pair the definition of homogeneous catalysis with the concrete example of acid-catalysed ester hydrolysis in water, and I pair heterogeneous catalysis with a solid iron catalyst contacting N2 and H2 gases, because those examples make the phase difference explicit to the examiner.",
        ],
        commonMistake:
          "Labelling any large molecule as heterogeneous simply because it is big; enzymes with substrates in solution are usually homogeneous unless immobilised.",
        tags: ["8.3", "homogeneous", "heterogeneous"],
      },
      {
        id: "t8-3-d10",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A reaction pathway diagram is drawn for a reversible reaction at one temperature, with uncatalysed and catalysed curves from the same reactant level to the same product level. Explain how you would interpret the diagram to decide which direction is favoured thermodynamically and which pathway is faster kinetically, and explain why a catalyst does not change the equilibrium composition at that temperature.",
        modelAnswerPoints: [
          "Thermodynamic favour is read from the relative vertical positions of the reactant and product plateaux, not from the barrier heights.",
          "If the product plateau lies below the reactant plateau for the equation as drawn, the forward overall change is exothermic on that profile and influences the equilibrium position at constant T.",
          "The faster kinetic path is identified from the lower energy maximum along the route from reactants to products at the same temperature.",
          "The catalysed curve therefore corresponds to a smaller forward activation energy and a larger forward rate constant when other factors are comparable.",
          "For a reversible system the catalysed reverse path is also lowered from products back to reactants, so the reverse rate constant increases as well.",
          "Because forward and reverse rates are increased together in this simple picture without changing reactant and product energy levels, the equilibrium constant K and the equilibrium composition at that temperature are unchanged.",
        ],
        workedSolution: [
          "I read the thermodynamic favour of the forward reaction from the vertical positions of the reactant and product plateaux on the diagram, because if the product level lies lower in energy than the reactant level for the stoichiometry shown, the forward overall change is exothermic in the sense of that profile and the equilibrium position at constant temperature will reflect that free-energy difference, independent of which kinetic path is drawn.",
          "I read the faster kinetic pathway from the height of the energy maximum along each curve from reactants toward products, because the catalysed route with the lower summit corresponds to the smaller activation energy for the forward direction and therefore to the larger forward rate constant at the same temperature when other factors are comparable.",
          "Because the catalyst must provide a return path that is similarly lowered from products back to reactants if the same cycle operates in reverse, the reverse rate constant increases by a related factor, and on the idealised symmetric diagram both directions are accelerated without changing the ratio of forward to reverse rates at equilibrium.",
          "Equilibrium composition is therefore unchanged at that temperature, which is the same statement as saying the equilibrium constant K is unchanged, because K is fixed by the standard Gibbs energy difference between the same reactant and product states while the catalyst only alters how quickly those states equilibrate.",
        ],
        commonMistake:
          "Claiming that the lower catalysed curve means more product at equilibrium; the product level is unchanged, only the barrier height changes.",
        tags: ["8.3", "interpretation", "pathway"],
      },
    ],
    flashcards: [
      {
        id: "t8-3-f1",
        noteId: "t8-3",
        difficulty: 1,
        front: "Define catalyst (short).",
        back: "Substance that increases reaction rate by a catalysed pathway and is regenerated overall.",
        examPhrasing: "Link to alternative mechanism and lower E_A.",
        tags: ["8.3", "definition"],
      },
      {
        id: "t8-3-f2",
        noteId: "t8-3",
        difficulty: 1,
        front: "Does a catalyst change K at constant T?",
        back: "No — same initial and final states; faster approach to the same equilibrium.",
        examPhrasing: "Forward and reverse rates increase together on the simple model.",
        tags: ["8.3", "equilibrium"],
      },
      {
        id: "t8-3-f3",
        noteId: "t8-3",
        difficulty: 2,
        front: "Homogeneous vs heterogeneous catalyst?",
        back: "Same phase as reactants vs different phase (often solid / fluid interface).",
        examPhrasing: "Name one industrial gas–solid example.",
        confusionPair: "phase of catalyst",
        tags: ["8.3", "types"],
      },
      {
        id: "t8-3-f4",
        noteId: "t8-3",
        difficulty: 2,
        front: "Pathway diagram: what must stay the same when a catalyst is added?",
        back: "Reactant and product energy levels; overall Delta H (for same overall equation).",
        examPhrasing: "Only barrier heights and intermediate wells change.",
        tags: ["8.3", "diagram"],
      },
      {
        id: "t8-3-f5",
        noteId: "t8-3",
        difficulty: 3,
        front: "Boltzmann view: why does lowering E_A (catalysed) speed the reaction at fixed T?",
        back: "Same energy distribution; lower threshold increases fraction of molecules with enough energy for the catalysed route.",
        examPhrasing: "Draw one distribution and two threshold lines.",
        tags: ["8.3", "boltzmann"],
      },
      {
        id: "t8-3-f6",
        noteId: "t8-3",
        difficulty: 3,
        front: "Different mechanism — what does that imply microscopically?",
        back: "Different sequence of elementary steps and transition states; new intermediates on the catalytic cycle.",
        examPhrasing: "Do not say only 'same reaction but faster' without mechanism language.",
        tags: ["8.3", "mechanism"],
      },
      {
        id: "t8-3-f7",
        noteId: "t8-3",
        difficulty: 4,
        front: "Energy profile: label E_A(cat) and E_A(uncat) for forward reaction.",
        back: "Heights from reactant level to each path's maximum; E_A(cat) < E_A(uncat).",
        examPhrasing: "Use a single reactant plateau for both curves.",
        tags: ["8.3", "E_A"],
      },
      {
        id: "t8-3-f8",
        noteId: "t8-3",
        difficulty: 4,
        front: "Why must reverse barrier also fall on a simple catalyst diagram?",
        back: "So both directions speed up and equilibrium position at that T is unchanged.",
        examPhrasing: "Pair with K unchanged.",
        tags: ["8.3", "reversible"],
      },
      {
        id: "t8-3-f9",
        noteId: "t8-3",
        difficulty: 5,
        front: "Exam trap: catalyst and thermodynamic spontaneity?",
        back: "Catalyst cannot make a non-spontaneous overall change spontaneous; it changes rate, not Delta G° for the same states.",
        examPhrasing: "Distinguish kinetics from thermodynamics.",
        confusionPair: "rate vs spontaneity",
        tags: ["8.3", "exam-technique"],
      },
      {
        id: "t8-3-f10",
        noteId: "t8-3",
        difficulty: 5,
        front: "Interpretation: steeper uncatalysed rise on profile — meaning?",
        back: "Higher E_A / slower uncatalysed rate at the same T compared with the lower catalysed barrier.",
        examPhrasing: "Tie barrier height to relative rates, not to different products.",
        tags: ["8.3", "interpretation"],
      },
    ],
  },
};
