import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 30 / 30.1 — Arenes: one course subtopic `t30-1`.
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §30.1; each bullet hit by ≥1 drill id):
 * - Reactions of benzene / methylbenzene: halogenation (a), nitration (b), FC alkylation (c), FC acylation (d),
 *   side-chain oxidation to benzoic acid (e), ring hydrogenation (f) → d2, d3, d4, d5, d6, d7
 * - Electrophilic substitution mechanism; delocalisation / substitution vs addition → d1, d8
 * - Halogenation ring vs side-chain vs conditions → d9
 * - Directing effects of –NH2, –OH, –R, –NO2, –COOH, –COR → d10 (+ d9 context)
 */
export const CHEMISTRY_TOPIC30_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t30-1": {
    noteId: "t30-1",
    drills: [
      {
        id: "t30-1-d1",
        noteId: "t30-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Explain, with reference to the bonding in benzene, why benzene reacts with bromine mainly by electrophilic substitution when a suitable Lewis-acid catalyst is present, rather than by the addition reaction that would be expected for a simple cyclohexene-type alkene.",
        modelAnswerPoints: [
          "Benzene has a planar ring of sp2 carbons with a delocalised π system (σ framework plus ring of electron density above and below the plane).",
          "The delocalised system gives aromatic stabilisation, so the fully conjugated ring is relatively low in energy compared with a hypothetical localised cyclohexatriene addition product.",
          "Electrophilic substitution replaces one ring hydrogen while the aromatic sextet is regenerated at the end of the mechanism, so most of that stabilisation is retained.",
          "Addition across the ring would destroy the continuous delocalisation and yield a much less stable saturated product, so substitution is strongly favoured under electrophilic conditions.",
        ],
        workedSolution: [
          "Benzene consists of six trigonal carbon atoms in a hexagon, each bonded to one hydrogen, with p orbitals overlapping sideways so the six π electrons are delocalised around the ring rather than fixed in three isolated double bonds.",
          "That delocalisation lowers the electronic energy of the molecule compared with any simple alternating-double-bond picture, which is what chemists mean by aromatic stabilisation in benzene.",
          "When an electrophile attacks the ring in electrophilic substitution, a positively charged cyclohexadienyl-type intermediate is formed temporarily, but a base then removes the proton from the carbon that was attacked, restoring the full aromatic π system in the substituted product.",
          "Because the aromatic sextet is present again in the final product, most of the special stability of benzene survives, which is why substitution is accessible under moderate conditions once a strong enough electrophile is generated.",
          "If bromine were to add across two ring carbons in a single step sequence analogous to an alkene, the product would be a dibromocyclohexene or fully saturated addition product without a delocalised benzene ring, which lies much higher in energy, so such addition is not the favourable pathway for benzene under electrophilic aromatic conditions.",
          "Therefore, with a Lewis acid to polarise Br2 and create a powerful electrophile, benzene undergoes substitution to bromobenzene rather than addition chemistry typical of isolated C=C bonds.",
        ],
        commonMistake:
          "Describing benzene as if it were three separate double bonds with no mention of delocalisation, or claiming addition keeps the same aromatic stability.",
        tags: ["aromaticity", "delocalisation", "substitution-vs-addition", "mechanism-concepts"],
      },
      {
        id: "t30-1-d2",
        noteId: "t30-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "State the reagents and conditions required to convert benzene into chlorobenzene. Write a balanced equation for the reaction using molecular formulae for the organic species. Name the electrophile that attacks the ring and outline how it is formed from chlorine and the catalyst.",
        modelAnswerPoints: [
          "Reagents: dry chlorine and a suitable aluminium chloride catalyst (AlCl3); anhydrous conditions are required to avoid catalyst hydrolysis.",
          "Equation: C6H6 + Cl2 -> C6H5Cl + HCl (AlCl3 catalyst).",
          "The attacking species is Cl+ (chloronium / chlorination electrophile often written Cl+–AlCl3 or polarised Cl–Cl–AlCl3).",
          "AlCl3 coordinates to Cl2, polarising the Cl–Cl bond so that one chlorine becomes sufficiently electrophilic to be attacked by the benzene π system.",
        ],
        workedSolution: [
          "Chlorination of the benzene ring is carried out by passing dry chlorine gas into benzene in the presence of anhydrous aluminium chloride as a Lewis-acid catalyst, because chlorine alone is not electrophilic enough to react at a useful rate with the relatively electron-rich but stabilised benzene ring.",
          "The overall transformation can be summarised as C6H6 + Cl2 -> C6H5Cl + HCl, where one ring hydrogen is replaced by chlorine and hydrogen chloride is formed as the inorganic co-product while the catalyst is regenerated in the catalytic cycle.",
          "The electrophile that is usually invoked in the mechanism is an electron-deficient chlorine species, commonly represented as Cl+ in mark schemes, although in reality it is better thought of as a strongly polarised chlorine molecule bound to AlCl3 that behaves like Cl+ toward the ring.",
          "Aluminium chloride accepts a lone pair from a chlorine atom of Cl2, which weakens the Cl–Cl bond and places partial positive charge on the terminal chlorine, allowing benzene’s π electrons to attack that terminal chlorine and begin the substitution sequence.",
        ],
        commonMistake:
          "Using aqueous Cl2 or omitting the Lewis acid, or writing addition of Cl2 across the ring instead of substitution with HCl formed.",
        tags: ["halogenation", "chlorobenzene", "aluminium-chloride", "electrophile"],
      },
      {
        id: "t30-1-d3",
        noteId: "t30-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which set of reagents and conditions is most appropriate for the nitration of benzene to nitrobenzene in the laboratory?",
        options: [
          { id: "A", text: "Dilute HNO3(aq) alone at room temperature." },
          { id: "B", text: "Concentrated HNO3 and concentrated H2SO4, with the mixture maintained roughly between 50 °C and 60 °C." },
          { id: "C", text: "Concentrated HCl and concentrated H2SO4 at reflux." },
          { id: "D", text: "NaNO2 and dilute HCl below 10 °C." },
        ],
        correctOptionId: "B",
        explanation:
          "The syllabus requires a nitrating mixture of concentrated nitric and concentrated sulfuric acids for benzene, at a controlled warm temperature (commonly quoted in the 50–60 °C range) to obtain nitrobenzene at a practical rate without excessive polynitration.",
        distractorRationale: {
          A: "Dilute nitric acid at room temperature is not the standard reagent set for benzene nitration and would not generate the strong electrophile needed efficiently.",
          C: "Hydrochloric acid is not the acid partner used to generate the nitronium ion from nitric acid; concentrated sulfuric acid is required as the dehydrating Brønsted acid.",
          D: "Sodium nitrite with dilute acid below 10 °C is the diazotisation context for arylamines, not electrophilic nitration of benzene.",
        },
        tags: ["nitration", "conditions", "nitrobenzene"],
      },
      {
        id: "t30-1-d4",
        noteId: "t30-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Describe how benzene is converted into methylbenzene by Friedel–Crafts alkylation. Include the names of all main organic reagents, the catalyst, any essential practical condition such as heat, and a balanced equation using structural or semi-structural formulae consistent with C6H6 and CH3Cl as the alkylating agent.",
        modelAnswerPoints: [
          "Reagents: chloromethane, CH3Cl, with anhydrous AlCl3 catalyst; reaction is heated under reflux (or heated) in a dry solvent such as chloromethane or another inert medium.",
          "Equation: C6H6 + CH3Cl -> C6H5CH3 + HCl (AlCl3, heat).",
          "The electrophile is CH3+ (methyl carbocation) or a polarised CH3–Cl–AlCl3 complex that delivers CH3+ character to the ring.",
          "AlCl3 polarises the C–Cl bond of chloromethane so that methyl becomes sufficiently electrophilic for attack by benzene.",
        ],
        workedSolution: [
          "Friedel–Crafts alkylation of benzene to methylbenzene is carried out using chloromethane as the alkyl halide together with anhydrous aluminium chloride as the Lewis-acid catalyst, with the mixture heated under reflux so that substitution occurs at a reasonable rate.",
          "Strictly anhydrous conditions matter because traces of water hydrolyse AlCl3 and destroy the electrophile-generating ability of the catalyst, so apparatus and reagents are kept dry in the usual teaching description of the preparation.",
          "The overall organic transformation can be written as C6H6 + CH3Cl -> C6H5CH3 + HCl, which shows replacement of one ring hydrogen by a methyl group with hydrogen chloride as the by-product while AlCl3 is not consumed in the stoichiometric equation because it is catalytic.",
          "The electrophile is commonly represented as a methyl carbocation, CH3+, formed in association with AlCl4^- after AlCl3 abstracts chloride from chloromethane, although examination answers also accept clear wording about a strongly polarised CH3–Cl–AlCl3 entity that behaves as an alkylating electrophile.",
          "Once the electrophile is present, benzene’s π system attacks it to give an intermediate sigma complex, and loss of a ring proton to AlCl4^- (or a base in the mixture) restores aromaticity and regenerates the aluminium chloride catalyst.",
        ],
        commonMistake:
          "Using CH3OH instead of CH3Cl, or forgetting heat / anhydrous catalyst, or drawing addition of CH3 and Cl across the ring.",
        tags: ["friedel-crafts", "alkylation", "methylbenzene", "aluminium-chloride"],
      },
      {
        id: "t30-1-d5",
        noteId: "t30-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain how benzene is converted into phenylethanone (acetophenone, C6H5COCH3) by Friedel–Crafts acylation. State the organic acylating agent exemplified in the syllabus, the catalyst, the need for heat, and write a balanced equation for the formation of C6H5COCH3 from benzene.",
        modelAnswerPoints: [
          "Acylating agent: ethanoyl chloride, CH3COCl; catalyst: anhydrous AlCl3; heated (reflux) in dry conditions.",
          "Equation: C6H6 + CH3COCl -> C6H5COCH3 + HCl (AlCl3, heat).",
          "The electrophile is the acylium ion CH3CO+ (or RCO+ in general), stabilised by resonance with the carbonyl oxygen.",
          "AlCl3 complexes to the chlorine of the acyl chloride, promoting loss of Cl^- to give the acylium ion which is attacked by benzene.",
        ],
        workedSolution: [
          "Friedel–Crafts acylation installs an acyl group on the ring; for acetophenone the reagent is ethanoyl chloride, CH3COCl, which reacts with benzene in the presence of anhydrous aluminium chloride as catalyst with heating under reflux in a dry environment.",
          "The balanced organic equation is C6H6 + CH3COCl -> C6H5COCH3 + HCl, showing substitution of one ring hydrogen by the CH3CO group and formation of hydrogen chloride, with AlCl3 acting catalytically in the mechanistic cycle.",
          "Heat is applied because the acylation step can be slower than halogenation and because maintaining reflux helps drive the substitution to completion in a reasonable laboratory time while keeping temperature controlled to limit side reactions.",
          "Aluminium chloride coordinates to the chlorine of the acyl chloride, weakening the C–Cl bond so that chloride leaves to generate an acylium cation, CH3C≡O+ ↔ CH3–C+=O, which is a strong linear electrophile attacked by the benzene π system.",
          "After formation of the sigma complex, deprotonation restores the aromatic ring in phenylethanone and regenerates the Lewis acid, which is why only a catalytic amount of AlCl3 is required stoichiometrically in the overall equation even though the acyl chloride must be supplied in full.",
        ],
        commonMistake:
          "Confusing alkylation (CH3Cl) with acylation (CH3COCl), or omitting HCl as a stoichiometric product.",
        tags: ["friedel-crafts", "acylation", "ethanoyl-chloride", "acetophenone"],
      },
      {
        id: "t30-1-d6",
        noteId: "t30-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Describe the complete oxidation of the side-chain of methylbenzene to give benzoic acid as required by the syllabus. State all reagents and conditions in the correct order, identify the organic species present after the alkaline oxidation step before acidification, and write an overall equation from methylbenzene to benzoic acid showing O2 as the oxidant in a simplified whole-number form (other inorganic products may be grouped).",
        modelAnswerPoints: [
          "Step 1: hot alkaline potassium manganate(VII), KMnO4, (often described as reflux with excess MnO4^- in OH^-).",
          "Step 2: acidify with dilute strong acid (e.g. HCl) to protonate benzenecarboxylate to benzoic acid.",
          "After alkaline oxidation the main organic product is the benzenecarboxylate ion, C6H5COO^- (salt with K+).",
          "Overall (simplified): C6H5CH3 + [O] -> C6H5COOH (with Mn2+/MnO2 and water in the real mixture); a compact acceptable form is C6H5CH3 + 2[O] -> C6H5COOH + H2O if [O] is explicitly defined as supplied by manganate.",
        ],
        workedSolution: [
          "The side-chain of methylbenzene is fully oxidised to a carboxylic acid group by heating with hot alkaline potassium manganate(VII), which supplies a powerful oxidising environment that cleaves all three C–H bonds of the methyl group stepwise until the carbon is in the +3 oxidation state of a carboxylate.",
          "Under these strongly basic conditions benzoic acid would be deprotonated, so the species isolated from the alkaline stage after work-up is mainly potassium benzenecarboxylate, written as C6H5COO^- K+ in ionic terms, still attached to the unchanged benzene ring.",
          "The reaction mixture is then cooled and acidified with dilute hydrochloric acid or another strong acid so that benzenecarboxylate is protonated to give benzoic acid, C6H5COOH, which is much less soluble and can be filtered off as a white solid.",
          "Manganate(VII) is reduced in the process, typically to manganese(IV) oxide as a brown precipitate or to Mn2+ in acidic media, but the syllabus focus is on the organic transformation rather than balancing every inorganic redox couple in full detail.",
          "A simplified overall picture acceptable at A-level is to write methylbenzene plus oxidising equivalents from alkaline manganate(VII) giving benzoic acid after acidification, for example C6H5CH3 + 2[O] -> C6H5COOH + H2O when [O] is understood to come from the permanganate under the stated conditions, provided the student separately names KMnO4 in alkali then dilute acid as the practical sequence.",
        ],
        commonMistake:
          "Stopping at benzaldehyde, or acidifying before oxidation is complete, or claiming the methyl becomes CH2OH only.",
        tags: ["side-chain-oxidation", "permanganate", "benzoic-acid", "methylbenzene"],
      },
      {
        id: "t30-1-d7",
        noteId: "t30-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Benzene is hydrogenated using hydrogen gas with a nickel or platinum catalyst and heat. What is the principal organic product?",
        options: [
          { id: "A", text: "cyclohexene" },
          { id: "B", text: "cyclohexane" },
          { id: "C", text: "hexane" },
          { id: "D", text: "cyclohexanol" },
        ],
        correctOptionId: "B",
        explanation:
          "The syllabus requires hydrogenation of the benzene ring to a saturated cyclohexane ring: C6H6 + 3H2 -> C6H12 with Ni or Pt catalyst and heat.",
        distractorRationale: {
          A: "Cyclohexene would imply stopping after one equivalent of hydrogenation of a hypothetical isolated triene, but catalytic hydrogenation of benzene under these conditions goes to the fully saturated cyclohexane.",
          C: "Hexane would require breaking the ring, which does not occur in simple catalytic hydrogenation of benzene.",
          D: "Cyclohexanol would introduce oxygen; hydrogenation with H2 is reduction of the ring only, not hydration to an alcohol.",
        },
        tags: ["hydrogenation", "cyclohexane", "catalyst"],
      },
      {
        id: "t30-1-d8",
        noteId: "t30-1",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Outline the mechanism of electrophilic substitution in which benzene is converted into nitrobenzene. Your answer should include formation of the electrophile from concentrated nitric and sulfuric acids, the attack of benzene on that electrophile with a curly-arrow description in words if not drawn, the nature of the intermediate formed, and the step that restores the aromatic ring.",
        modelAnswerPoints: [
          "Concentrated H2SO4 protonates HNO3; loss of water from protonated nitric acid gives the nitronium ion, NO2+.",
          "A pair of π electrons from benzene forms a bond to NO2+, giving a resonance-stabilised cyclohexadienyl cation (sigma complex / arenium ion).",
          "A base (e.g. HSO4^- or H2O) removes the proton from the carbon that was attacked, reforming the aromatic sextet in nitrobenzene.",
        ],
        workedSolution: [
          "In the nitrating mixture, concentrated sulfuric acid acts as a stronger acid than nitric acid and protonates one of the nitric acid oxygen atoms, after which dehydration generates the nitronium ion, +NO2, which is the linear electrophile that actually attacks benzene.",
          "A curly arrow from the benzene π system to the nitrogen of NO2+ represents formation of a new C–N bond while temporarily breaking the full aromaticity, producing a positively charged intermediate usually drawn as a cyclohexadienyl cation with the nitro group on the saturated carbon that was attacked.",
          "That intermediate is resonance-stabilised because the positive charge is delocalised over several ring positions even though nitrobenzene itself is electron-withdrawing in the product.",
          "A weak base present in the acidic mixture, commonly hydrogensulfate ion from sulfuric acid or a water molecule, then removes the proton from the carbon bearing the nitro group, with the electrons from the C–H bond returning into the ring to recreate the delocalised aromatic π system of nitrobenzene.",
          "This final deprotonation step is fast and drives the overall substitution because it restores the large resonance stabilisation lost when the electrophile first added to the ring.",
        ],
        commonMistake:
          "Claiming NO2+ attacks without acid-catalysed formation, or describing a free-radical chain, or omitting the deprotonation that restores aromaticity.",
        tags: ["mechanism", "nitration", "nitronium", "sigma-complex"],
      },
      {
        id: "t30-1-d9",
        noteId: "t30-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Methylbenzene (toluene) reacts with chlorine. Under which conditions is electrophilic substitution on the aromatic ring the expected predominant pathway?",
        options: [
          { id: "A", text: "UV light and a non-polar solvent, no Lewis acid." },
          { id: "B", text: "Dry Cl2 with anhydrous AlCl3 catalyst (or FeCl3), in the dark or under ordinary laboratory lighting without UV promotion." },
          { id: "C", text: "Aqueous Cl2 at room temperature in sunlight only." },
          { id: "D", text: "Cl2 with a radical initiator at high temperature and no Lewis acid." },
        ],
        correctOptionId: "B",
        explanation:
          "Electrophilic aromatic chlorination needs a polarised Cl2–Lewis acid pair to generate an electrophile attacking the ring; UV with Cl2 favours free-radical chlorination of the alkyl side-chain.",
        distractorRationale: {
          A: "UV with Cl2 promotes homolytic fission and radical substitution on the methyl group rather than Lewis-acid catalysed ring substitution.",
          C: "Aqueous chlorine is not the standard setup for ring chlorination of methylbenzene in the syllabus sense, and ‘sunlight only’ points toward photochemical radical chemistry.",
          D: "High-temperature radical conditions favour side-chain halogenation, not electrophilic substitution on the ring.",
        },
        tags: ["conditions", "side-chain-vs-ring", "chlorination"],
      },
      {
        id: "t30-1-d10",
        noteId: "t30-1",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "For electrophilic substitution on a monosubstituted benzene ring, the syllabus limits directing effects to the groups –NH2, –OH, –R (alkyl), –NO2, –COOH and –COR. Classify each of these classes as ortho–para directing or meta directing and as activating or deactivating toward further electrophilic attack. Then predict the major mononitration product(s) when methylbenzene reacts with concentrated HNO3 and concentrated H2SO4 at about 55 °C, naming the isomers using the 2- and 4- positions relative to the methyl group.",
        modelAnswerPoints: [
          "–NH2 and –OH: ortho–para directors, strongly activating (electron-donating by lone-pair overlap).",
          "–R (alkyl): ortho–para director, activating (weak electron donation / hyperconjugation).",
          "–NO2, –COOH, –COR: meta directors, deactivating (electron-withdrawing by resonance and/or inductive effects).",
          "Methyl is –R, so nitration gives mainly 2-nitromethylbenzene and 4-nitromethylbenzene (ortho and para isomers); para often predominates slightly on steric grounds.",
        ],
        workedSolution: [
          "Amino and hydroxyl substituents possess lone pairs that can overlap with the ring π system, donating electron density especially to the ortho and para positions, so both –NH2 and –OH are ortho–para directors and are strongly activating because they stabilise the sigma complex for attack at those sites.",
          "An alkyl group such as methyl donates weakly by inductive and hyperconjugative electron release, so –R is also an ortho–para director and is activating compared with benzene, although less powerfully than –OH or –NH2.",
          "Nitro, carboxylic acid and acyl groups all contain electronegative oxygen attached in a way that withdraws π electron density from the ring through resonance, which especially destabilises attack at ortho and para positions relative to the substituent, leaving the meta positions comparatively less deactivated; they are therefore meta directors and overall deactivating.",
          "When methylbenzene is nitrated, the methyl group directs the incoming nitronium electrophile to the ortho and para positions, so the major products are 2-nitromethylbenzene (ortho) and 4-nitromethylbenzene (para), with only a minor amount of the 3-isomer under typical conditions.",
          "Steric hindrance at the ortho sites means the para isomer is often formed in comparable or slightly greater amount than each ortho attack pathway would suggest on electronic grounds alone, but both 2- and 4-nitromethylbenzene should be quoted as the main mononitration products at about 55 °C.",
        ],
        commonMistake:
          "Calling methyl a meta director, or claiming –COOH is ortho–para activating, or giving 3-nitromethylbenzene as the main product.",
        tags: ["directing-effects", "nitration", "methylbenzene", "activating-deactivating"],
      },
    ],
    flashcards: [
      {
        id: "t30-1-f1",
        noteId: "t30-1",
        difficulty: 1,
        front: "What reagents catalyse chlorination or bromination of benzene on the ring?",
        back: "Dry Cl2 or Br2 with anhydrous AlCl3 or AlBr3 (Lewis-acid catalyst); dry conditions.",
        examPhrasing: "State the reagents for converting benzene into bromobenzene.",
        tags: ["halogenation", "catalyst"],
      },
      {
        id: "t30-1-f2",
        noteId: "t30-1",
        difficulty: 1,
        front: "Reagents and temperature range for nitration of benzene?",
        back: "Concentrated HNO3 + concentrated H2SO4; warm, typically about 50–60 °C, to give nitrobenzene.",
        examPhrasing: "State the nitrating mixture used for benzene.",
        tags: ["nitration", "conditions"],
      },
      {
        id: "t30-1-f3",
        noteId: "t30-1",
        difficulty: 2,
        front: "Electrophile in aromatic nitration?",
        back: "The nitronium ion, NO2+, formed from nitric acid in concentrated sulfuric acid.",
        examPhrasing: "Identify the electrophile that attacks benzene in nitration.",
        tags: ["nitronium", "mechanism"],
      },
      {
        id: "t30-1-f4",
        noteId: "t30-1",
        difficulty: 2,
        front: "Friedel–Crafts alkylation of benzene to methylbenzene: key organic reagent?",
        back: "Chloromethane CH3Cl + anhydrous AlCl3, heated.",
        examPhrasing: "State reagents for Friedel–Crafts methylation of benzene.",
        tags: ["friedel-crafts", "alkylation"],
      },
      {
        id: "t30-1-f5",
        noteId: "t30-1",
        difficulty: 3,
        front: "Friedel–Crafts acylation: typical acyl chloride and product type?",
        back: "e.g. CH3COCl + AlCl3, heat → aryl ketone (e.g. phenylethanone from benzene).",
        examPhrasing: "State reagents for Friedel–Crafts acylation of benzene with ethanoyl chloride.",
        tags: ["acylation", "ethanoyl-chloride"],
      },
      {
        id: "t30-1-f6",
        noteId: "t30-1",
        difficulty: 3,
        front: "How is benzoic acid made from methylbenzene?",
        back: "Hot alkaline KMnO4 (oxidises –CH3 to –COO^-), then acidify with dilute acid → benzoic acid.",
        examPhrasing: "Describe oxidation of the side-chain of methylbenzene to a carboxylic acid.",
        confusionPair: "ring hydrogenation vs side-chain oxidation",
        tags: ["permanganate", "benzoic-acid"],
      },
      {
        id: "t30-1-f7",
        noteId: "t30-1",
        difficulty: 4,
        front: "Equation for full hydrogenation of benzene?",
        back: "C6H6 + 3H2 -> C6H12 with Ni or Pt catalyst and heat.",
        examPhrasing: "Write the equation for hydrogenation of benzene to cyclohexane.",
        tags: ["hydrogenation", "cyclohexane"],
      },
      {
        id: "t30-1-f8",
        noteId: "t30-1",
        difficulty: 4,
        front: "Why substitution not addition with Br2 + catalyst on benzene?",
        back: "Aromatic stabilisation from delocalised π ring; substitution keeps the sextet; addition would destroy it.",
        examPhrasing: "Explain why benzene undergoes electrophilic substitution rather than addition with bromine.",
        tags: ["aromaticity", "substitution-vs-addition"],
      },
      {
        id: "t30-1-f9",
        noteId: "t30-1",
        difficulty: 5,
        front: "Methylbenzene + Cl2: ring vs side-chain?",
        back: "AlCl3 (Lewis acid), no UV → ring electrophilic substitution; UV light, no Lewis acid → radical substitution on methyl.",
        examPhrasing: "Predict where chlorination occurs depending on conditions.",
        confusionPair: "electrophilic ring vs radical side-chain",
        tags: ["conditions", "toluene"],
      },
      {
        id: "t30-1-f10",
        noteId: "t30-1",
        difficulty: 5,
        front: "Directing: –NO2 vs –CH3 for further electrophilic substitution?",
        back: "–CH3 ortho–para, activating; –NO2 meta, strongly deactivating.",
        examPhrasing: "State directing effects of nitro and methyl groups on a benzene ring.",
        tags: ["directing-effects", "meta", "ortho-para"],
      },
    ],
  },
};
