import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 29 — A Level organic introduction: subtopics `t29-1` … `t29-4`.
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §29.1):
 * - Functional group dictates properties → t29-1-d1, t29-1-f1
 * - General / structural / displayed / skeletal formulae → t29-1-d2, t29-1-d3, t29-1-f2
 * - Systematic nomenclature: aliphatic + single ring ≤6 C (esters/amides 6+6; straight esters/nitriles) → t29-1-d4, t29-1-d5, t29-1-d6, t29-1-f3, t29-1-f4
 * - Aromatic one ring + simple substituents → t29-1-d7, t29-1-d8, t29-1-d9, t29-1-f5
 * - Molecular/formula reasoning from structure → t29-1-d10, t29-1-f6
 *
 * §29.2:
 * - Terminology: electrophilic substitution; addition–elimination → t29-2-d1–d10, t29-2-f1–f4
 *
 * §29.3:
 * - Benzene / aromatic shape: sp², σ bonds, delocalised π → t29-3-d1–d10, t29-3-f1–f5
 *
 * §29.4:
 * - Enantiomers: same except rotation + biological activity → t29-4-d1, t29-4-f1
 * - Optically active; racemic mixture → t29-4-d2, t29-4-d3, t29-4-f2
 * - Plane polarised light: two optical isomers → t29-4-d4, t29-4-d5, t29-4-f3
 * - Chirality in synthesis: different activity; separate racemate; chiral catalyst → t29-4-d6–d10, t29-4-f4–f5
 */
export const CHEMISTRY_TOPIC29_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t29-1": {
    noteId: "t29-1",
    drills: [
      {
        id: "t29-1-d1",
        noteId: "t29-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define what is meant by a functional group in an organic molecule, and explain why knowing the functional group is more useful than knowing only the molecular formula when predicting how the compound will react.",
        modelAnswerPoints: [
          "A functional group is a particular atom or group of atoms attached to a carbon framework that gives a characteristic set of reactions for a class of compound.",
          "It is the site where electron distribution is altered in typical reactions, so it largely determines chemical behaviour.",
          "Molecular formula alone does not show connectivity or which functional groups are present, so different isomers with the same formula can react very differently.",
        ],
        workedSolution: [
          "A functional group is a specific arrangement of atoms, such as a hydroxyl group, carbonyl group, or nitrile group, bonded into an organic structure in a way that defines membership of a homologous series or reactive class.",
          "Because reactions involve making and breaking particular bonds and attacking electron-rich or electron-poor centres, the functional group identifies where those events usually occur and which mechanism types are appropriate, so it is the main predictor of chemical properties.",
          "The molecular formula only states how many atoms of each element are present, so structures with the same formula but different functional groups or connectivity are not distinguished, which is why functional-group identification is essential for reliable prediction of organic reactivity.",
        ],
        commonMistake:
          "Saying the functional group is 'any part of the molecule' without tying it to characteristic reactivity, or claiming molecular formula is sufficient for reaction prediction.",
        tags: ["definitions", "functional-groups", "homologous-series"],
      },
      {
        id: "t29-1-d2",
        noteId: "t29-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "For a simple aliphatic compound, contrast a displayed formula with a skeletal formula. State what information is lost when moving from displayed to skeletal, and state one advantage of skeletal formulae in examination work.",
        modelAnswerPoints: [
          "Displayed formula shows every atom symbol and every covalent bond explicitly, including all C–H bonds in the main chain.",
          "Skeletal formula shows carbon chains as lines or vertices with heteroatoms and functional groups drawn explicitly; hydrogen atoms bonded to carbon are usually omitted unless needed for clarity.",
          "Moving to skeletal loses explicit C–H detail along the skeleton unless added for a particular centre.",
          "Skeletal formulae are quicker to draw and read for larger molecules while keeping functional groups clear.",
        ],
        workedSolution: [
          "In a displayed formula each carbon and hydrogen is written out with its bonds, so the full connectivity and bond order at every centre is visible directly from the diagram without inferring implicit hydrogens.",
          "A skeletal formula represents the carbon skeleton as vertices and line segments, with heteroatoms such as oxygen, nitrogen, or halogens shown explicitly, while hydrogens attached to skeletal carbons are understood to fill valency unless drawn at a stereogenic or functional position.",
          "When you switch from displayed to skeletal you no longer see every C–H bond at a glance, so you must remember that each line junction or chain end is a carbon with enough hydrogens to complete four bonds to that carbon.",
          "The advantage in exam answers is speed and clarity: large frameworks remain legible, and examiners can still see functional groups and ring sizes without cluttered hydrogen labels everywhere along an alkyl chain.",
        ],
        commonMistake:
          "Claiming skeletal formulae show every hydrogen, or forgetting that line ends and vertices imply carbon atoms.",
        tags: ["displayed-formula", "skeletal-formula", "representations"],
      },
      {
        id: "t29-1-d3",
        noteId: "t29-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best describes a general formula for a homologous series?",
        options: [
          { id: "A", text: "It gives the exact connectivity of one member of the series." },
          { id: "B", text: "It expresses composition for each member using n (or similar) to show change in chain length while the functional group pattern stays the same." },
          { id: "C", text: "It is identical to the empirical formula of the first member only." },
          { id: "D", text: "It must include displayed bonds for every carbon–hydrogen interaction." },
        ],
        correctOptionId: "B",
        explanation:
          "A general formula summarises how molecular composition changes between successive members while the functional group type is unchanged, e.g. C_nH_{2n+2} for alkanes in basic treatments.",
        distractorRationale: {
          A: "Connectivity is shown in structural or displayed formulae, not by the general formula alone.",
          C: "The general formula applies across the series, not only to the first member, and need not equal any single empirical formula for all members.",
          D: "General formulae are symbolic composition patterns; bond-by-bond display is not required.",
        },
        tags: ["general-formula", "homologous-series"],
      },
      {
        id: "t29-1-d4",
        noteId: "t29-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Give the systematic IUPAC-style name for CH_3CH(CH_3)CH_2CH_2COOH. State how you chose the parent chain and the numbering direction.",
        modelAnswerPoints: [
          "The principal functional group is carboxylic acid, so the parent is a pentanoic acid chain (five carbons including the carbonyl carbon).",
          "Number from the carboxylic acid carbon as C1 so the substituent methyl receives the lowest locant.",
          "The methyl branch is on C4 of that chain.",
          "Name: 4-methylpentanoic acid.",
        ],
        workedSolution: [
          "The highest-priority functional group here is the carboxylic acid, so the name must end in -oic acid and the parent chain must include the carbonyl carbon as part of the longest continuous chain bearing that group.",
          "The longest chain containing the –COOH group has five carbon atoms, so the parent alkanoic acid is pentanoic acid, and by convention the carbonyl carbon is numbered as position 1.",
          "Numbering from the acid group places the methyl substituent on the fourth carbon of the chain rather than on a higher number if numbered from the wrong end.",
          "The systematic name is therefore 4-methylpentanoic acid, which reports the methyl branch at C4 on a pentanoic acid parent.",
        ],
        commonMistake:
          "Choosing a four-carbon parent that excludes the acid carbon, or numbering from the wrong end so the methyl gets a higher locant than necessary.",
        tags: ["nomenclature", "carboxylic-acids", "aliphatic"],
      },
      {
        id: "t29-1-d5",
        noteId: "t29-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which name correctly describes a six-membered saturated ring bearing a single –CONH_2 group attached by the carbonyl carbon to the ring?",
        options: [
          { id: "A", text: "cyclohexanamide" },
          { id: "B", text: "cyclohexanecarboxamide" },
          { id: "C", text: "aminocyclohexane" },
          { id: "D", text: "cyclohexyl methanamide" },
        ],
        correctOptionId: "B",
        explanation:
          "The amide group is –C(=O)NH_2 attached through the carbonyl carbon to the ring, so the parent is cyclohexanecarboxamide (ring–CO–NH_2).",
        distractorRationale: {
          A: "That name does not correctly express a carboxamide substituent on the ring in standard A Level style.",
          C: "That suggests an amine on the ring, not a primary amide attached via a carbonyl carbon.",
          D: "The usual systematic construction for this connectivity is cyclohexanecarboxamide, not a cyclohexyl methanamide style label at this level.",
        },
        tags: ["nomenclature", "amides", "cyclic"],
      },
      {
        id: "t29-1-d6",
        noteId: "t29-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Name the straight-chain ester formed from propan-1-ol and ethanoic acid using systematic nomenclature. Explain why the syllabus restricts ester names to straight chains at this stage, and state which fragment supplies the -oate part of the name.",
        modelAnswerPoints: [
          "The ester is propyl ethanoate (ethanoic acid / acetic component as the acyl residue; propan-1-ol as the alkoxy fragment).",
          "Straight-chain restriction avoids ambiguity in parent numbering for branched alkoxy groups in basic naming drills.",
          "The -oate portion comes from the carboxylic acid parent after loss of OH (here ethanoate from ethanoic acid).",
        ],
        workedSolution: [
          "When propan-1-ol reacts with ethanoic acid to form an ester, the propyl group is attached through oxygen as –OCH_2CH_2CH_3 and the acyl group from ethanoic acid remains CH_3C(=O)–, so the systematic name is propyl ethanoate.",
          "At this introductory level, restricting esters to straight-chain alkoxy fragments keeps locants and parent choice unambiguous while students are learning priority rules, whereas branched alkoxy chains introduce extra numbering decisions that are deferred until manipulation is secure.",
          "The alkyl or aryl part from the alcohol names the first word (propyl), and the acyl fragment derived from the acid supplies the second word ending in -oate, here ethanoate from ethanoic acid.",
        ],
        commonMistake:
          "Reversing the order to ethyl propanoate, or naming from the wrong acid/alcohol combination.",
        tags: ["esters", "nomenclature", "straight-chain"],
      },
      {
        id: "t29-1-d7",
        noteId: "t29-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which compound is classified as phenol?",
        options: [
          { id: "A", text: "C_6H_5CH_2OH" },
          { id: "B", text: "C_6H_5OH" },
          { id: "C", text: "CH_3CH_2CH_2OH" },
          { id: "D", text: "C_6H_5OCH_3" },
        ],
        correctOptionId: "B",
        explanation:
          "Phenol is hydroxybenzene: the –OH group is bonded directly to an aromatic ring carbon.",
        distractorRationale: {
          A: "That is a primary alcohol on a benzyl carbon; the –OH is not directly attached to the ring.",
          C: "That is a simple aliphatic alcohol with no aromatic ring.",
          D: "That is an aromatic ether (methoxybenzene), not an aromatic hydroxy compound.",
        },
        tags: ["phenol", "functional-groups", "arenes"],
      },
      {
        id: "t29-1-d8",
        noteId: "t29-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A benzene ring bears a carboxylic acid group, a nitro group meta to the acid, and a bromo substituent ortho to the acid on the opposite side from the nitro. Give the systematic name, stating the parent and the locants.",
        modelAnswerPoints: [
          "Parent is benzoic acid; the –COOH group defines carbon 1 of the ring.",
          "Nitro is meta to the acid, so it is at position 3 if the acid is at 1.",
          "Bromo ortho to the acid on the face away from the nitro at 3 places bromine at position 6 (the other ortho position, 2, is adjacent to the nitro).",
          "Systematic name: 6-bromo-3-nitrobenzoic acid.",
        ],
        workedSolution: [
          "For aromatic acids the parent name is benzoic acid and the carbon of the carboxylic acid group is treated as C1 of the ring numbering system, which fixes the reference for all substituents.",
          "A nitro group meta to the acid occupies position 3 on a standard drawing with the acid at the top, because meta means separated by one ring carbon from the acid-bearing carbon.",
          "Bromine ortho to the acid can be at position 2 or 6; specifying it on the side opposite the nitro at 3 selects the position that is ortho to the acid but not adjacent to the nitro substituent, which is position 6 in the usual clockwise numbering from the acid.",
          "Assembling substituents alphabetically gives bromo before nitro, so the name is written 6-bromo-3-nitrobenzoic acid, which communicates the parent acid together with the two ring substituents at the stated locants.",
        ],
        commonMistake:
          "Numbering from the nitro group instead of from the carboxylic acid when benzoic acid is the parent, or inconsistent locants for meta/ortho language.",
        tags: ["aromatic-nomenclature", "benzoic-acid", "multi-substituent"],
      },
      {
        id: "t29-1-d9",
        noteId: "t29-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which name matches 2,4,6-tribromophenol?",
        options: [
          { id: "A", text: "A benzene ring with –OH and three Br atoms at the 2-, 4- and 6-positions relative to the –OH as position 1." },
          { id: "B", text: "A benzene ring with –OH and three Br atoms all meta to one another with no relationship to the –OH." },
          { id: "C", text: "Bromomethane with three phenyl substituents." },
          { id: "D", text: "Propane-1,2,3-triol with three bromine atoms." },
        ],
        correctOptionId: "A",
        explanation:
          "Phenol uses –OH at C1; 2,4,6-tribromo means bromines at the two ortho and the para positions relative to –OH.",
        distractorRationale: {
          B: "The locants 2,4,6 are defined relative to the hydroxy group as principal substituent for phenol naming.",
          C: "That describes an unrelated aliphatic or coupling idea, not tribromophenol.",
          D: "That is unrelated to an aromatic phenol framework.",
        },
        tags: ["phenol", "tribromophenol", "locants"],
      },
      {
        id: "t29-1-d10",
        noteId: "t29-1",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Deduce the molecular formula of chlorobenzene. Then deduce the molecular formula of 2-nitrotoluene (1-methyl-2-nitrobenzene), showing how you account for ring hydrogens replaced by substituents.",
        modelAnswerPoints: [
          "Chlorobenzene: benzene C_6H_6 with one H replaced by Cl gives C_6H_5Cl.",
          "Toluene is methylbenzene C_7H_8; replacing one ring H by NO_2 gives C_7H_7NO_2 for a mononitro derivative with the methyl still present.",
          "Each monosubstitution on the ring removes one hydrogen compared with benzene or adjusts the hydrogen count of the methylbenzene parent accordingly.",
        ],
        workedSolution: [
          "Benzene has molecular formula C_6H_6, and chlorobenzene is formed when one ring hydrogen is replaced by chlorine, so the hydrogen count falls by one and one chlorine atom is added, giving C_6H_5Cl.",
          "Methylbenzene (toluene) has formula C_7H_8 because a methyl group replaces one ring hydrogen of benzene; introducing one nitro group onto the ring replaces a further ring hydrogen, reducing hydrogen by one and adding N and two oxygens, which yields C_7H_7NO_2 for a mononitrotoluene isomer such as 2-nitrotoluene.",
          "The accounting pattern is that every substituent that bonds directly to a ring carbon replaces what would otherwise be a hydrogen on that carbon in the unsubstituted aromatic parent, so you subtract one H per new ring substituent while adding the substituent atoms.",
        ],
        commonMistake:
          "Forgetting to reduce hydrogen count when adding substituents to the ring, or treating the methyl group as if it were removed when nitrating.",
        tags: ["molecular-formula", "aromatic", "counting-atoms"],
      },
    ],
    flashcards: [
      {
        id: "t29-1-f1",
        noteId: "t29-1",
        difficulty: 1,
        front: "What does a functional group determine in an organic compound?",
        back: "The characteristic chemistry and much of the physical behaviour: it is the usual reactive site and defines the compound class.",
        examPhrasing: "Explain why the functional group is important in organic chemistry.",
        tags: ["functional-groups", "definitions"],
      },
      {
        id: "t29-1-f2",
        noteId: "t29-1",
        difficulty: 1,
        front: "What is implied at a vertex or line end in a skeletal formula?",
        back: "A carbon atom, with enough hydrogens attached to complete its valency (usually four single bonds total).",
        examPhrasing: "State what a vertex represents in a skeletal organic structure.",
        tags: ["skeletal-formula"],
      },
      {
        id: "t29-1-f3",
        noteId: "t29-1",
        difficulty: 2,
        front: "Which functional group has highest priority for naming: alcohol or carboxylic acid on the same chain?",
        back: "Carboxylic acid: the chain is named as an alkanoic acid with –COOH at C1.",
        examPhrasing: "Choose the parent name when both –OH and –COOH are present on one chain.",
        tags: ["nomenclature", "priority"],
      },
      {
        id: "t29-1-f4",
        noteId: "t29-1",
        difficulty: 2,
        front: "How is a nitrile named at introductory level?",
        back: "Alkanenitrile for straight chains, e.g. ethanenitrile for CH_3CN; the carbon of the C≡N counts in the parent chain.",
        examPhrasing: "Give the systematic name for a straight-chain nitrile.",
        confusionPair: "nitrile vs isocyanide naming",
        tags: ["nitriles", "nomenclature"],
      },
      {
        id: "t29-1-f5",
        noteId: "t29-1",
        difficulty: 3,
        front: "Parent name when a benzene ring has –COOH?",
        back: "Benzoic acid; the carboxyl carbon is C1 of the ring numbering.",
        examPhrasing: "Name the parent for a substituted aromatic carboxylic acid.",
        tags: ["aromatic", "benzoic-acid"],
      },
      {
        id: "t29-1-f6",
        noteId: "t29-1",
        difficulty: 3,
        front: "Distinguish halogenoarene from halogenoalkane in one sentence.",
        back: "Halogenoarene: halogen bonded directly to an aromatic ring carbon; halogenoalkane: halogen on an sp³ aliphatic carbon.",
        examPhrasing: "Classify C_6H_5Cl versus C_2H_5Cl.",
        confusionPair: "halogenoarene vs halogenoalkane",
        tags: ["classification", "aryl-halide"],
      },
      {
        id: "t29-1-f7",
        noteId: "t29-1",
        difficulty: 4,
        front: "What is an acyl chloride?",
        back: "Contains –C(=O)Cl: a carbonyl carbon bonded to chlorine and to the rest of the R group.",
        examPhrasing: "Identify the functional group in RCOCl.",
        tags: ["acyl-chlorides"],
      },
      {
        id: "t29-1-f8",
        noteId: "t29-1",
        difficulty: 4,
        front: "What distinguishes a primary amide?",
        back: "Carbonyl directly bonded to –NH_2 (general primary amide RCONH_2).",
        examPhrasing: "State the functional group in propanamide.",
        tags: ["amides"],
      },
      {
        id: "t29-1-f9",
        noteId: "t29-1",
        difficulty: 5,
        front: "Give an example of systematic naming with two ring substituents on benzoic acid.",
        back: "e.g. 3-nitrobenzoic acid: NO_2 at position 3 with –COOH at position 1.",
        examPhrasing: "Write the systematic name for a given disubstituted benzoic acid structure.",
        tags: ["aromatic-nomenclature"],
      },
      {
        id: "t29-1-f10",
        noteId: "t29-1",
        difficulty: 5,
        front: "What does 'straight chains only for esters and nitriles' mean in the syllabus?",
        back: "Names expected use unbranched alkyl/alkoxy or unbranched nitrile parent chains at this stage to keep basic naming unambiguous.",
        examPhrasing: "Explain a limitation on ester naming at AS introduction.",
        tags: ["nomenclature", "syllabus-scope"],
      },
    ],
  },

  "t29-2": {
    noteId: "t29-2",
    drills: [
      {
        id: "t29-2-d1",
        noteId: "t29-2",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Define the mechanism term electrophilic substitution in the context of aromatic chemistry. Identify the attacking species type and state what is substituted on the aromatic ring.",
        modelAnswerPoints: [
          "Electrophilic substitution is a reaction in which an electrophile attacks an electron-rich aromatic ring and replaces one ring hydrogen.",
          "The electrophile is an electron-deficient species attracted to the π electron system.",
          "Overall, a hydrogen on the ring is swapped for a new substituent derived from the electrophile.",
        ],
        workedSolution: [
          "Electrophilic substitution describes a mechanism class in which an electrophile, which is an electron-pair acceptor, is attacked by the delocalised π electrons of an aromatic ring in a step that eventually leads to substitution at carbon rather than simple addition across one double bond.",
          "The electrophile may be a generated species such as NO_2^+ in nitration or a halogen carrier in halogenation catalysed by aluminium halide, but in every case it is electron-deficient relative to the aromatic π system.",
          "The net outcome is replacement of one aromatic C–H by a new C–substituent bond, with loss of a proton in the regeneration of aromaticity, which is why the process is classified as substitution on the ring rather than hydrogen abstraction from an alkane.",
        ],
        commonMistake:
          "Calling any reaction on benzene 'addition', or describing the electrophile as a nucleophile.",
        tags: ["electrophilic-substitution", "definitions", "aromatic"],
      },
      {
        id: "t29-2-d2",
        noteId: "t29-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Define addition–elimination as used for carbonyl reactions at A Level. Contrast it in one sentence with electrophilic addition to an alkene.",
        modelAnswerPoints: [
          "Addition–elimination: a nucleophile adds to the carbonyl carbon and a leaving group is later expelled, often after formation of a tetrahedral intermediate, giving substitution at the carbonyl carbon overall.",
          "Electrophilic addition to an alkene adds across the π bond without a comparable elimination step from a carbonyl oxygen leaving group.",
        ],
        workedSolution: [
          "Addition–elimination at a carbonyl begins with nucleophilic attack on the electrophilic carbonyl carbon, which converts the C=O π bond into a single-bonded intermediate, and is followed by reformation of the carbonyl or related linkage when a leaving group such as Cl^- or –OR departs, so the overall result is replacement of the leaving group by the nucleophile.",
          "This label emphasises that two distinct stages occur: bond-making addition to the carbonyl, then loss of a small molecule or ion in an elimination step that restores or rearranges the carbonyl-type environment.",
          "Electrophilic addition to an alkene is different because an electrophile adds across the carbon–carbon double bond and the π system is consumed without the same carbonyl leaving-group chemistry, so the vocabulary marks a different electron flow and intermediate structure.",
        ],
        commonMistake:
          "Labelling simple carbonyl reduction or every nucleophilic attack as 'addition–elimination' without mentioning addition then loss of a leaving group.",
        tags: ["addition-elimination", "carbonyl", "definitions"],
      },
      {
        id: "t29-2-d3",
        noteId: "t29-2",
        kind: "mcq",
        difficulty: 2,
        stem: "The nitration of benzene to nitrobenzene is best classified as:",
        options: [
          { id: "A", text: "nucleophilic substitution" },
          { id: "B", text: "electrophilic substitution" },
          { id: "C", text: "free-radical substitution" },
          { id: "D", text: "electrophilic addition" },
        ],
        correctOptionId: "B",
        explanation:
          "NO_2^+ attacks the aromatic π system and a ring hydrogen is replaced; aromaticity is retained overall — electrophilic substitution.",
        distractorRationale: {
          A: "The attacking species is electrophilic, not a nucleophile attacking a δ+ carbon in an SN sense.",
          C: "Radical chain conditions are not the usual teaching classification for benzene nitration with mixed acid.",
          D: "Addition would destroy the cyclic delocalised system in one step; substitution replaces H.",
        },
        tags: ["electrophilic-substitution", "nitration"],
      },
      {
        id: "t29-2-d4",
        noteId: "t29-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Give one specific example reaction that is classified as electrophilic substitution of an arene, naming the organic starting material, the essential reagents/catalyst, and the main organic product.",
        modelAnswerPoints: [
          "Example: benzene to bromobenzene using Br_2 and an Fe or AlBr_3 catalyst (or AlBr_3 generated in situ).",
          "Electrophilic bromine species attacks the ring; H is replaced by Br.",
        ],
        workedSolution: [
          "A standard illustration is the bromination of benzene, in which benzene is treated with molecular bromine in the presence of a Lewis acid catalyst such as iron powder or aluminium tribromide that polarises Br_2 and helps generate an electrophilic bromine entity capable of attacking the ring.",
          "The organic product is bromobenzene, because one aromatic hydrogen is replaced by bromine while the delocalised ring is regenerated after loss of a proton, which matches the electrophilic substitution classification.",
        ],
        commonMistake:
          "Giving alkane free-radical bromination under UV as the 'arene' example, or omitting the catalyst for benzene bromination.",
        tags: ["electrophilic-substitution", "bromination", "examples"],
      },
      {
        id: "t29-2-d5",
        noteId: "t29-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Acid-catalysed hydrolysis of an acyl chloride to a carboxylic acid is commonly described mechanistically as:",
        options: [
          { id: "A", text: "electrophilic substitution" },
          { id: "B", text: "addition–elimination at the carbonyl carbon" },
          { id: "C", text: "electrophilic addition across C=O only with no elimination" },
          { id: "D", text: "free-radical chain termination" },
        ],
        correctOptionId: "B",
        explanation:
          "Water adds to the carbonyl; chloride leaves — addition then elimination overall at the acyl carbon.",
        distractorRationale: {
          A: "That label belongs to aromatic attack by electrophiles, not nucleophilic acyl substitution.",
          C: "Loss of Cl^- is an elimination step from a tetrahedral intermediate, not addition only.",
          D: "Acyl chloride hydrolysis is polar, not a radical termination step.",
        },
        tags: ["addition-elimination", "acyl-chlorides"],
      },
      {
        id: "t29-2-d6",
        noteId: "t29-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain why benzene typically undergoes electrophilic substitution under the conditions in the syllabus rather than electrophilic addition that would give a cyclohexadiene product, using the idea of aromatic stabilisation in words only.",
        modelAnswerPoints: [
          "Addition would partially localise π bonding and disrupt the especially stable delocalised ring system.",
          "Substitution preserves the delocalised aromatic π system after loss of H+.",
          "Therefore substitution pathways are energetically favoured over simple addition for benzene under those conditions.",
        ],
        workedSolution: [
          "Benzene possesses a delocalised π system that spreads electron density around the ring and lowers the energy of the molecule compared with a hypothetical localised cyclohexatriene arrangement, which is called aromatic stabilisation or resonance stabilisation in introductory language.",
          "Electrophilic addition would consume part of that delocalisation by localising double-bond character in a non-aromatic cyclohexadiene-type framework, which costs a large amount of resonance stabilisation, so such addition is not the usual outcome under standard electrophilic conditions.",
          "Electrophilic substitution replaces one hydrogen while the σ framework and continuous delocalised π cloud can be restored when the intermediate loses a proton, so the aromatic stabilisation is largely retained, which is why substitution predominates over addition for benzene in the reactions named at this level.",
        ],
        commonMistake:
          "Saying 'benzene does not react' or ignoring stabilisation when comparing substitution to addition.",
        tags: ["aromatic-stabilisation", "electrophilic-substitution"],
      },
      {
        id: "t29-2-d7",
        noteId: "t29-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which phrase uses the syllabus term for attack on benzene by NO_2^+?",
        options: [
          { id: "A", text: "nucleophilic addition–elimination" },
          { id: "B", text: "electrophilic substitution" },
          { id: "C", text: "nucleophilic substitution" },
          { id: "D", text: "homolytic photolysis" },
        ],
        correctOptionId: "B",
        explanation:
          "NO_2^+ is an electrophile; it replaces ring hydrogen — electrophilic substitution.",
        distractorRationale: {
          A: "NO_2^+ is electrophilic, and the process is substitution on the ring, not nucleophilic acyl chemistry.",
          C: "The π system of benzene acts as electron source toward the electrophile; the rate-determining chemistry is not SN2 at a saturated carbon.",
          D: "Nitration with mixed concentrated acids is not classified as a photochemical radical homolysis route at this stage.",
        },
        tags: ["terminology", "nitration"],
      },
      {
        id: "t29-2-d8",
        noteId: "t29-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "The reaction of ethanoyl chloride with excess concentrated ammonia is classified overall as nucleophilic acyl substitution described by addition–elimination. Describe the two stages in words (no curly arrows required), naming the nucleophile and the leaving group.",
        modelAnswerPoints: [
          "Stage 1: NH_3 acts as a nucleophile attacking the δ+ carbonyl carbon, with electron pair donation forming a tetrahedral intermediate.",
          "Stage 2: The intermediate collapses, eliminating Cl^- as leaving group and reforming the carbonyl as an amide linkage.",
          "Overall: Cl replaced by –NH_2 (after deprotonation steps) to give ethanamide.",
        ],
        workedSolution: [
          "In the first stage a lone pair on ammonia attacks the electrophilic carbonyl carbon of ethanoyl chloride, which converts the π bond of the carbonyl into a σ single bond to oxygen carrying negative character in a tetrahedral arrangement around that carbon while chlorine remains attached.",
          "In the second stage that intermediate rearranges by expelling chloride ion as a leaving group, which re-forms the C=O double bond and joins nitrogen to the carbonyl carbon as an amide functional group, which is why the mechanism type is described as elimination following addition.",
          "After proton transfers between nitrogen centres in the concentrated ammonia medium, the isolated organic product is ethanamide, CH_3CONH_2, and the overall stoichiometry replaces the chlorine substituent of the acyl chloride with an amino group derived from ammonia.",
        ],
        commonMistake:
          "Calling the process electrophilic substitution, or naming HCl as the nucleophile.",
        tags: ["addition-elimination", "acyl-chlorides", "amides-formation"],
      },
      {
        id: "t29-2-d9",
        noteId: "t29-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which transformation is best described as addition–elimination at a carbonyl carbon?",
        options: [
          { id: "A", text: "Benzene + Br_2 with AlBr_3" },
          { id: "B", text: "Propanoyl chloride + water -> propanoic acid + HCl" },
          { id: "C", text: "Ethene + Br_2" },
          { id: "D", text: "Ethane + Cl_2 under UV" },
        ],
        correctOptionId: "B",
        explanation:
          "Water adds to the carbonyl; Cl^- leaves — nucleophilic acyl substitution via addition–elimination.",
        distractorRationale: {
          A: "That is electrophilic substitution on an aromatic ring, not carbonyl addition–elimination.",
          C: "That is electrophilic addition across a C=C double bond.",
          D: "That is free-radical substitution on an alkane.",
        },
        tags: ["classification", "mechanisms"],
      },
      {
        id: "t29-2-d10",
        noteId: "t29-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Construct a short comparison table in prose (three contrasts) between electrophilic substitution of benzene and addition–elimination at an acyl chloride. Include: attacking species character, fate of the carbonyl or aromatic π system, and one typical product family for each.",
        modelAnswerPoints: [
          "Electrophilic substitution: electrophile attacks aromatic π system; aromaticity restored after H+ loss; products are substituted arenes.",
          "Addition–elimination: nucleophile attacks carbonyl carbon; tetrahedral intermediate then loss of leaving group; products include carboxylic acid derivatives such as amides or acids.",
          "Attacking species: electrophile vs nucleophile respectively.",
        ],
        workedSolution: [
          "In electrophilic substitution of benzene the attacking particle is an electrophile attracted to the electron-rich delocalised ring, whereas in addition–elimination at an acyl chloride the key attacking species is a nucleophile attracted to the partially positive carbonyl carbon, so the electron-flow language is opposite even though both involve electron pair donation from somewhere in the molecule.",
          "During aromatic electrophilic substitution the ring temporarily loses full aromaticity in an intermediate but regains it when a proton is lost, while in acyl addition–elimination the carbonyl π bond is temporarily broken in the tetrahedral intermediate and then re-formed when the leaving group departs, so the π system involved is a carbonyl rather than an aromatic sextet.",
          "Typical product families differ: substituted aromatic compounds such as nitrobenzene or halogenoarenes arise from the first route, whereas carboxylic acids, esters, or amides arise from nucleophilic attack on acyl chlorides by water, alcohols, or ammonia through the addition–elimination pathway.",
        ],
        commonMistake:
          "Using 'substitution' for both without distinguishing electrophilic aromatic attack from nucleophilic acyl substitution.",
        tags: ["comparison", "mechanisms", "terminology"],
      },
    ],
    flashcards: [
      {
        id: "t29-2-f1",
        noteId: "t29-2",
        difficulty: 1,
        front: "Name the mechanism class: benzene + NO_2^+ -> nitrobenzene.",
        back: "Electrophilic substitution.",
        examPhrasing: "Classify the nitration of benzene.",
        tags: ["electrophilic-substitution"],
      },
      {
        id: "t29-2-f2",
        noteId: "t29-2",
        difficulty: 1,
        front: "What two words describe nucleophilic attack on a carbonyl followed by loss of a leaving group?",
        back: "Addition–elimination (overall nucleophilic substitution at the acyl carbon).",
        examPhrasing: "State the mechanism type for hydrolysis of an acyl chloride.",
        tags: ["addition-elimination"],
      },
      {
        id: "t29-2-f3",
        noteId: "t29-2",
        difficulty: 2,
        front: "Electrophile vs nucleophile — one line each.",
        back: "Electrophile: electron-pair acceptor. Nucleophile: electron-pair donor.",
        examPhrasing: "Define electrophile and nucleophile.",
        tags: ["definitions"],
      },
      {
        id: "t29-2-f4",
        noteId: "t29-2",
        difficulty: 2,
        front: "Give one example of an electrophile used with benzene in the syllabus.",
        back: "NO_2^+ (nitration), Br^+ / polarised Br_2 with catalyst (bromination), or R^+ in Friedel–Crafts alkylation (Topic 30 detail).",
        examPhrasing: "Name an electrophile that attacks benzene.",
        tags: ["electrophiles", "examples"],
      },
      {
        id: "t29-2-f5",
        noteId: "t29-2",
        difficulty: 3,
        front: "Leaving group in acyl chloride aminolysis?",
        back: "Chloride ion Cl^- (from the –COCl group).",
        examPhrasing: "Identify the leaving group when an acyl chloride forms an amide with ammonia.",
        tags: ["acyl-chlorides"],
      },
      {
        id: "t29-2-f6",
        noteId: "t29-2",
        difficulty: 3,
        front: "Why is 'substitution' used for benzene nitration?",
        back: "A ring hydrogen is replaced by the nitro group; aromatic delocalisation is retained overall.",
        examPhrasing: "Explain why nitration of benzene is substitution not addition.",
        tags: ["aromatic", "terminology"],
      },
      {
        id: "t29-2-f7",
        noteId: "t29-2",
        difficulty: 4,
        front: "Intermediate shape around carbonyl carbon during addition?",
        back: "Tetrahedral intermediate after nucleophile adds, before leaving group leaves.",
        examPhrasing: "Describe the geometry at the carbonyl carbon immediately after nucleophilic attack.",
        tags: ["addition-elimination"],
      },
      {
        id: "t29-2-f8",
        noteId: "t29-2",
        difficulty: 4,
        front: "Does esterification from acid + alcohol follow addition–elimination language?",
        back: "Yes: nucleophilic acyl substitution — addition of alcohol then elimination of water (acid-catalysed pathway).",
        examPhrasing: "Classify the mechanism of Fischer esterification in terminology terms.",
        tags: ["esters", "mechanisms"],
      },
      {
        id: "t29-2-f9",
        noteId: "t29-2",
        difficulty: 5,
        front: "One-word check: alkene + HBr?",
        back: "Electrophilic addition (not electrophilic substitution).",
        examPhrasing: "Contrast alkene + HBr with benzene + electrophile.",
        confusionPair: "electrophilic addition vs electrophilic substitution",
        tags: ["terminology"],
      },
      {
        id: "t29-2-f10",
        noteId: "t29-2",
        difficulty: 5,
        front: "What is substituted in aromatic electrophilic substitution?",
        back: "Usually a ring hydrogen is replaced by the new substituent.",
        examPhrasing: "State what is replaced in the nitration of benzene.",
        tags: ["electrophilic-substitution"],
      },
    ],
  },

  "t29-3": {
    noteId: "t29-3",
    drills: [
      {
        id: "t29-3-d1",
        noteId: "t29-3",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Describe the hybridisation of carbon atoms in benzene and the shapes of the σ bonds formed between adjacent ring carbons and between each ring carbon and its attached hydrogen.",
        modelAnswerPoints: [
          "Each ring carbon is sp² hybridised with trigonal planar local geometry.",
          "The C–C σ framework arises from overlap of sp² orbitals along the ring edges.",
          "Each C–H bond is a σ bond between sp² carbon and s orbital of hydrogen.",
        ],
        workedSolution: [
          "In benzene every carbon is bonded to two other carbons and one hydrogen in a planar trigonal arrangement, which requires sp² hybridisation so that three sp² hybrid orbitals lie in the molecular plane at about 120° to one another.",
          "The σ framework of the ring consists of sp²–sp² overlap between neighbouring carbon atoms, giving the strong in-plane σ bonds that define the hexagonal ring geometry.",
          "Each carbon–hydrogen bond is formed by overlap between the remaining sp² hybrid orbital on that carbon and the 1s orbital of hydrogen, which is also a σ bond lying in the same plane as the ring.",
        ],
        commonMistake:
          "Stating sp³ hybridisation for ring carbons, or claiming C–H bonds use unhybridised p orbitals.",
        tags: ["sp2", "benzene", "sigma-bonds"],
      },
      {
        id: "t29-3-d2",
        noteId: "t29-3",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain what is meant by a delocalised π system in benzene, and contrast it with the localised π bond in ethene in terms of how many π bonds are drawn between adjacent carbons in a classical diagram.",
        modelAnswerPoints: [
          "Each carbon has an unhybridised p orbital perpendicular to the ring plane; these overlap side-on around the ring.",
          "Six π electrons are shared over all six carbons rather than fixed between two atoms only.",
          "In ethene one localised π bond sits between the two carbons; in benzene π electron density is delocalised around the whole ring.",
        ],
        workedSolution: [
          "After σ bonding, each carbon in benzene still has one electron in a p orbital perpendicular to the plane of the ring, and adjacent p orbitals overlap side-on all the way around the hexagon, which allows π electron density to spread rather than being confined to one isolated π bond.",
          "There are six π electrons from the six p orbitals, and in the delocalised picture they occupy molecular orbitals extending over the entire ring, which is what chemists mean by a delocalised π system contributing extra stability.",
          "In ethene there is exactly one π bond localised between the two sp² carbons of the double bond, whereas in benzene you cannot honestly assign two distinct double bonds to fixed pairs of atoms without breaking equivalence of all C–C bonds, so diagrams use either alternating bonds knowing they are a resonance representation or a circle inside the hexagon to imply delocalisation.",
        ],
        commonMistake:
          "Saying benzene has three isolated π bonds like three ethene units without mentioning delocalisation.",
        tags: ["pi-system", "delocalisation", "benzene"],
      },
      {
        id: "t29-3-d3",
        noteId: "t29-3",
        kind: "mcq",
        difficulty: 1,
        stem: "The H–C–H angle in benzene is closest to:",
        options: [
          { id: "A", text: "109.5°" },
          { id: "B", text: "120°" },
          { id: "C", text: "90°" },
          { id: "D", text: "180°" },
        ],
        correctOptionId: "B",
        explanation:
          "Trigonal planar sp² carbons in the ring give bond angles of about 120°.",
        distractorRationale: {
          A: "That is tetrahedral sp³ geometry, not the planar ring carbons of benzene.",
          C: "That would imply perpendicular d-type arrangements irrelevant here.",
          D: "Linear geometry corresponds to sp or sp centres in chains, not ring carbons in benzene.",
        },
        tags: ["bond-angles", "benzene"],
      },
      {
        id: "t29-3-d4",
        noteId: "t29-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "State the overall shape of the benzene molecule and explain how σ bonding and π overlap together account for the planar hexagonal structure.",
        modelAnswerPoints: [
          "Benzene is planar (a flat regular hexagon).",
          "σ bonds between sp² carbons and to hydrogen lie in one plane.",
          "Side-on p orbital overlap forms the π system above and below that plane, which is only geometrically efficient if the ring is planar.",
        ],
        workedSolution: [
          "Benzene is a planar molecule with the six carbon and six hydrogen nuclei lying in one plane forming a regular hexagon, which is the shape demanded by equal bond angles of 120° at each sp² centre.",
          "The σ skeleton lies entirely in that plane and includes all carbon–carbon σ bonds around the ring plus all carbon–hydrogen σ bonds radiating slightly inside or outside the hexagon perimeter but still coplanar with the ring.",
          "The π system arises from overlap of p orbitals perpendicular to that plane, which is strongest when all contributing atoms are coplanar, so the σ framework and π overlap reinforce the same planar geometry rather than allowing a puckered ring.",
        ],
        commonMistake:
          "Describing benzene as tetrahedral at carbon, or claiming the π bonds lie in the same plane as the σ skeleton.",
        tags: ["shape", "benzene", "planar"],
      },
      {
        id: "t29-3-d5",
        noteId: "t29-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement about C–C bonds in benzene is correct?",
        options: [
          { id: "A", text: "All C–C bond lengths are equal and intermediate between C–C single and C=C double values." },
          { id: "B", text: "There are three long C–C single bonds and three short C=C bonds that never interchange." },
          { id: "C", text: "All C–C bonds are pure single bonds." },
          { id: "D", text: "All C–C bonds are longer than any alkane C–C single bond." },
        ],
        correctOptionId: "A",
        explanation:
          "Delocalisation averages bond order; experimentally all ring C–C distances are equal.",
        distractorRationale: {
          B: "Static alternating single/double contradicts equal bond lengths; the real structure is delocalised.",
          C: "That ignores the π contribution to each ring C–C link.",
          D: "Benzene C–C bonds are shorter than a typical C–C single because of partial double-bond character.",
        },
        tags: ["bond-length", "delocalisation"],
      },
      {
        id: "t29-3-d6",
        noteId: "t29-3",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Identify which electron density in benzene is described as σ and which as π, and state the spatial relationship between them.",
        modelAnswerPoints: [
          "σ electron density lies primarily along the internuclear axes in the molecular plane.",
          "π electron density arises from overlap perpendicular to the plane, above and below the ring.",
        ],
        workedSolution: [
          "σ electrons in benzene are those involved in end-on overlap forming the in-plane framework bonds, including C–C σ bonds that outline the hexagon and each C–H σ bond, so their density is concentrated along the bond directions within the plane of the molecule.",
          "π electrons occupy molecular orbitals formed from side-on overlap of p orbitals, which places electron density in lobes above and below the plane of the ring rather than along the line joining two nuclei in the plane.",
          "Therefore the σ framework is planar while the π system is oriented perpendicular to that plane, which is the standard geometric separation used when explaining spectroscopic and reactivity properties of aromatics.",
        ],
        commonMistake:
          "Placing π density in the same plane as the C–H σ bonds, or calling the ring σ bonds π bonds.",
        tags: ["sigma", "pi", "benzene"],
      },
      {
        id: "t29-3-d7",
        noteId: "t29-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Other simple aromatic molecules such as methylbenzene have aromatic ring carbons that are:",
        options: [
          { id: "A", text: "sp hybridised with linear geometry" },
          { id: "B", text: "sp² hybridised with trigonal planar geometry around each ring carbon" },
          { id: "C", text: "sp³ hybridised because of the methyl group" },
          { id: "D", text: "unhybridised p only with no σ framework" },
        ],
        correctOptionId: "B",
        explanation:
          "Ring carbons remain sp² trigonal planar in methylbenzene; the methyl carbon is sp³ but not the ring.",
        distractorRationale: {
          A: "Ring carbons are not linear sp centres.",
          C: "The methyl carbon is sp³, but each aromatic ring carbon is still sp².",
          D: "σ framework always exists; p orbitals alone cannot describe the whole molecule.",
        },
        tags: ["hybridisation", "methylbenzene"],
      },
      {
        id: "t29-3-d8",
        noteId: "t29-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Using benzene as the example, explain in terms of σ and π bonding why the Kekulé alternating double-bond drawing is an incomplete representation, and describe how a circle inside the hexagon improves the picture without redrawing every orbital.",
        modelAnswerPoints: [
          "Alternating double bonds imply different C–C bond lengths, which is not observed.",
          "A circle indicates six π electrons delocalised over the whole ring.",
          "σ framework is still represented by the hexagon edges.",
        ],
        workedSolution: [
          "The Kekulé forms show three localised double bonds alternating with three single bonds around the ring, which would predict three shorter and three longer carbon–carbon distances if those forms were static, but experiment shows all C–C bonds equal, so neither Kekulé structure alone is a faithful literal picture of electron distribution.",
          "The truth is better captured by resonance between the two Kekulé contributors or, more simply for diagrams, by acknowledging a delocalised π system in which bond order is shared equally between all adjacent ring carbons, which averages bond lengths to a single intermediate value.",
          "Drawing a circle inside the hexagon is a shorthand that the six π electrons are delocalised above and below the plane while the σ skeleton is still the hexagon of σ bonds, so students can show delocalisation without sketching every p orbital lobe in an examination answer.",
        ],
        commonMistake:
          "Claiming the circle replaces σ bonds or that benzene rapidly flips between different bond lengths in the ground state.",
        tags: ["kekule", "delocalisation", "representations"],
      },
      {
        id: "t29-3-d9",
        noteId: "t29-3",
        kind: "mcq",
        difficulty: 3,
        stem: "How many σ bonds does each ring carbon form within the σ-only framework count usually quoted for benzene (to two carbons and one hydrogen)?",
        options: [
          { id: "A", text: "2" },
          { id: "B", text: "3" },
          { id: "C", text: "4" },
          { id: "D", text: "1" },
        ],
        correctOptionId: "B",
        explanation:
          "Each ring C uses three sp² hybrids for three σ bonds: two to adjacent ring carbons and one to hydrogen.",
        distractorRationale: {
          A: "That would omit one of the two C–C σ contributions or the C–H bond.",
          C: "Fourth valency is the p orbital used in π overlap, not an additional σ bond to hydrogen in benzene.",
          D: "Each carbon clearly forms more than one σ bond.",
        },
        tags: ["sigma-bonds", "counting"],
      },
      {
        id: "t29-3-d10",
        noteId: "t29-3",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Outline how sp² hybridisation at a ring carbon provides one p orbital for π bonding while still allowing a planar σ framework in aromatic systems.",
        modelAnswerPoints: [
          "sp² mixing uses one s and two p orbitals to form three coplanar hybrid orbitals at 120°.",
          "One unhybridised p orbital remains perpendicular to that plane.",
          "That p orbital participates in π overlap while hybrids form σ bonds.",
        ],
        workedSolution: [
          "When an atomic p orbital mixes with the valence s orbital in a 2:1 ratio, three sp² hybrid orbitals are produced, each directed toward the corners of an equilateral triangle, which is exactly the geometry needed for a trigonal carbon in a planar ring segment.",
          "Because only two of the three original p orbitals participate in that hybridisation on carbon, one atomic p orbital remains unmixed and points above and below the plane defined by the three sp² lobes.",
          "That remaining p orbital overlaps side-on with equivalent p orbitals on neighbouring ring atoms to build the π system, while the sp² hybrids handle all σ bonding in the plane, which is the textbook partition behind descriptions of aromatic electronic structure.",
        ],
        commonMistake:
          "Claiming all three p orbitals are consumed in hybridisation with none left for π bonding.",
        tags: ["hybridisation", "pi-system"],
      },
    ],
    flashcards: [
      {
        id: "t29-3-f1",
        noteId: "t29-3",
        difficulty: 1,
        front: "Hybridisation of carbon in benzene?",
        back: "sp².",
        examPhrasing: "State the hybridisation of carbon in benzene.",
        tags: ["benzene", "sp2"],
      },
      {
        id: "t29-3-f2",
        noteId: "t29-3",
        difficulty: 1,
        front: "H–C–C angle in benzene?",
        back: "About 120° (trigonal planar).",
        examPhrasing: "Give the bond angle at a ring carbon in benzene.",
        tags: ["bond-angles"],
      },
      {
        id: "t29-3-f3",
        noteId: "t29-3",
        difficulty: 2,
        front: "Where is σ electron density mainly located in benzene?",
        back: "In the molecular plane along bonds between nuclei.",
        examPhrasing: "Describe σ bonding in benzene.",
        tags: ["sigma"],
      },
      {
        id: "t29-3-f4",
        noteId: "t29-3",
        difficulty: 2,
        front: "Where is π electron density mainly located?",
        back: "Above and below the plane of the ring.",
        examPhrasing: "Locate π electron density in benzene.",
        tags: ["pi"],
      },
      {
        id: "t29-3-f5",
        noteId: "t29-3",
        difficulty: 3,
        front: "Why are all C–C bonds equal length in benzene?",
        back: "π bonding is delocalised over the ring, giving each C–C bond the same bond order.",
        examPhrasing: "Explain equal C–C bond lengths in benzene.",
        tags: ["delocalisation"],
      },
      {
        id: "t29-3-f6",
        noteId: "t29-3",
        difficulty: 3,
        front: "What does a circle inside the benzene hexagon mean?",
        back: "A delocalised π system (six π electrons) — shorthand, not a third σ bond.",
        examPhrasing: "Interpret the circle in a benzene skeletal formula.",
        tags: ["representations"],
      },
      {
        id: "t29-3-f7",
        noteId: "t29-3",
        difficulty: 4,
        front: "How many π electrons in benzene?",
        back: "Six.",
        examPhrasing: "State the π electron count in benzene.",
        tags: ["aromaticity"],
      },
      {
        id: "t29-3-f8",
        noteId: "t29-3",
        difficulty: 4,
        front: "σ vs π: which involves side-on overlap?",
        back: "π bonding from side-on p–p overlap; σ from end-on overlap along the internuclear axis.",
        examPhrasing: "Contrast σ and π overlap.",
        confusionPair: "σ vs π overlap",
        tags: ["sigma", "pi"],
      },
      {
        id: "t29-3-f9",
        noteId: "t29-3",
        difficulty: 5,
        front: "Planarity and aromatic stabilisation — one link.",
        back: "Planar ring allows continuous p overlap, maximising delocalisation stabilisation.",
        examPhrasing: "Explain why a planar ring matters for the π system.",
        tags: ["delocalisation"],
      },
      {
        id: "t29-3-f10",
        noteId: "t29-3",
        difficulty: 5,
        front: "Ring carbon in methylbenzene: hybridisation?",
        back: "Aromatic ring carbons remain sp²; methyl carbon is sp³.",
        examPhrasing: "State hybridisation at ring carbons in toluene.",
        tags: ["hybridisation"],
      },
    ],
  },

  "t29-4": {
    noteId: "t29-4",
    drills: [
      {
        id: "t29-4-d1",
        noteId: "t29-4",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define a pair of enantiomers and state two respects in which their physical and chemical properties are the same, and two respects in which they can differ under conditions specified in the syllabus.",
        modelAnswerPoints: [
          "Enantiomers are stereoisomers that are non-superimposable mirror images of one another.",
          "They have identical physical properties such as boiling point and density in an achiral environment, and identical chemical reactivity toward achiral reagents.",
          "They differ in the direction they rotate plane polarised light and may differ in biological activity with chiral receptors.",
        ],
        workedSolution: [
          "Enantiomers are a pair of molecules related as object and mirror image that cannot be superimposed by rotation alone, which arises when a structure lacks an internal plane of symmetry and exists in two chiral forms.",
          "In an achiral laboratory environment they share the same bulk physical properties and give the same reaction outcomes with achiral reagents because the spatial arrangement of atoms relative to achiral probes is energetically equivalent when both mirror forms are considered without chiral influence.",
          "They differ in how they interact with plane polarised light, rotating it through equal angles but in opposite directions, and they may differ markedly in biological activity when the target site is chiral, because each enantiomer fits the receptor environment differently even though the atoms are the same.",
        ],
        commonMistake:
          "Claiming all properties including rotation are identical, or confusing enantiomers with structural isomers.",
        tags: ["enantiomers", "definitions", "chirality"],
      },
      {
        id: "t29-4-d2",
        noteId: "t29-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Define optically active. Define racemic mixture. State how the observed rotation of plane polarised light compares for a pure enantiomer and for a racemic sample of the same compound.",
        modelAnswerPoints: [
          "Optically active: the substance rotates the plane of polarised light.",
          "Racemic mixture: equimolar mixture of two enantiomers.",
          "A pure enantiomer shows a non-zero rotation; a perfect racemic mixture shows zero net rotation.",
        ],
        workedSolution: [
          "A sample is described as optically active if, when plane polarised light is passed through it, the plane of polarisation is rotated measurably, which indicates an excess of one enantiomer over its mirror image in the bulk sample.",
          "A racemic mixture contains equal amounts of the two enantiomers of a chiral substance, so for every molecule that rotates light one way there is a partner that rotates it equally the opposite way on a mole-for-mole basis.",
          "Therefore a single pure enantiomer gives a definite signed rotation angle under standard conditions, whereas an ideal racemic mixture shows no net rotation because the opposing contributions cancel exactly.",
        ],
        commonMistake:
          "Calling any mixture 'racemic' when the two enantiomers are not present in equal amounts.",
        tags: ["optical-activity", "racemic", "definitions"],
      },
      {
        id: "t29-4-d3",
        noteId: "t29-4",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement about a racemic mixture of a chiral compound is correct?",
        options: [
          { id: "A", text: "It contains only one enantiomer." },
          { id: "B", text: "It contains equal amounts of both enantiomers and shows no net rotation of plane polarised light." },
          { id: "C", text: "It is always optically inactive because it contains no chiral molecules." },
          { id: "D", text: "It rotates plane polarised light twice as much as a single enantiomer." },
        ],
        correctOptionId: "B",
        explanation:
          "Racemic = 1:1 enantiomers; rotations cancel so net observed rotation is zero.",
        distractorRationale: {
          A: "That would be an enantiopure sample, not racemic.",
          C: "Racemic mixtures still contain chiral molecules; cancellation makes the bulk sample inactive.",
          D: "Opposite rotations cancel rather than add.",
        },
        tags: ["racemic", "optical-activity"],
      },
      {
        id: "t29-4-d4",
        noteId: "t29-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Describe the effect on plane polarised light when separate samples of equal concentration and path length of two enantiomers of the same chiral molecule are tested in the same polarimeter arrangement.",
        modelAnswerPoints: [
          "Each enantiomer rotates the plane of polarisation by the same magnitude.",
          "The directions of rotation are opposite (dextrorotatory vs laevorotatory convention).",
          "Equal concentration and path length gives equal magnitude for a given wavelength and temperature.",
        ],
        workedSolution: [
          "When plane polarised light passes through a solution of a chiral compound, the electric field vector direction is rotated away from its incident orientation, and enantiomers produce rotations of equal size because the molecular environment seen by the light is mirror-related rather than different in magnitude.",
          "The two enantiomers rotate the plane in opposite directions, which is why one may be labelled dextrorotatory and the other laevorotatory for a given experimental configuration even though other physical constants match.",
          "If concentration and path length are kept identical, the magnitude of the observed angle is the same for each pure enantiomer under the same temperature and wavelength, which is how polarimetry distinguishes enantiomers from achiral materials that give zero rotation.",
        ],
        commonMistake:
          "Saying both rotate light the same way, or that magnitude differs between enantiomers in ideal conditions.",
        tags: ["polarimetry", "enantiomers"],
      },
      {
        id: "t29-4-d5",
        noteId: "t29-4",
        kind: "mcq",
        difficulty: 2,
        stem: "A drug target site in the body is chiral. Compared with its enantiomer, one enantiomer may:",
        options: [
          { id: "A", text: "always have identical boiling point but may differ in biological activity" },
          { id: "B", text: "always have different boiling point" },
          { id: "C", text: "never bind to the same receptor" },
          { id: "D", text: "differ in molar mass" },
        ],
        correctOptionId: "A",
        explanation:
          "Bulk physical properties match in achiral environments; chiral biological environments can discriminate activity.",
        distractorRationale: {
          B: "Boiling points of enantiomers are the same in achiral surroundings.",
          C: "Wording 'never' is too absolute; the syllabus point is that activity may differ, not impossible binding in every hypothetical case.",
          D: "Enantiomers have the same molecular formula and molar mass.",
        },
        tags: ["drugs", "enantiomers", "biology"],
      },
      {
        id: "t29-4-d6",
        noteId: "t29-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain why a chiral drug molecule might have enantiomers with different pharmacological effects even though their reactions with simple achiral acids or bases in a test tube are identical.",
        modelAnswerPoints: [
          "Biological receptors and enzymes are chiral three-dimensional environments.",
          "Each enantiomer fits binding sites differently, so potency, efficacy, or side-effect profile may change.",
          "Achiral reagents do not distinguish mirror images, so non-biological test-tube reactions can match.",
        ],
        workedSolution: [
          "Protein receptors and enzyme active sites are built from chiral amino acids, so their pockets and hydrogen-bond arrays have a handedness that makes the mirror-image drug molecule present different groups at different distances when it attempts to bind.",
          "Consequently one enantiomer may bind strongly and trigger the desired signalling while the other binds weakly, binds an off-target site, or antagonises the target, which appears as different pharmacological activity even though the overall molecular formula is unchanged.",
          "Simple Brønsted acid–base reactions in water depend mainly on electron availability at functional groups that are identical between enantiomers when viewed by a spherically symmetric proton, so those achiral reactions proceed at the same rate and with the same outcome, which is why laboratory identity of some reactions does not predict in vivo identity.",
        ],
        commonMistake:
          "Claiming different molar masses or different boiling points explain the drug difference.",
        tags: ["chirality", "drugs", "biology"],
      },
      {
        id: "t29-4-d7",
        noteId: "t29-4",
        kind: "mcq",
        difficulty: 3,
        stem: "Why might a pharmaceutical process aim to separate a racemic mixture into pure enantiomers?",
        options: [
          { id: "A", text: "Because the racemic mixture always has zero molar mass" },
          { id: "B", text: "Because only one enantiomer may have the desired therapeutic effect while the other is inactive or harmful" },
          { id: "C", text: "Because enantiomers have different molecular formulas" },
          { id: "D", text: "Because racemic mixtures cannot rotate plane polarised light" },
        ],
        correctOptionId: "B",
        explanation:
          "Separation isolates the useful enantiomer and reduces risk from the mirror form.",
        distractorRationale: {
          A: "Molar mass is unchanged and non-zero for racemic samples.",
          C: "Enantiomers share the same molecular formula.",
          D: "Racemic samples have zero net rotation, but that is not why therapeutic separation is done.",
        },
        tags: ["separation", "drugs"],
      },
      {
        id: "t29-4-d8",
        noteId: "t29-4",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Explain what is meant by using a chiral catalyst in the synthesis of a drug, and state how that strategy relates to forming a single pure optical isomer rather than a racemic mixture from a prochiral or achiral precursor.",
        modelAnswerPoints: [
          "A chiral catalyst provides a handed environment that favours formation of one enantiomeric product.",
          "It lowers activation energy for one pathway to one enantiomer compared with its mirror pathway.",
          "That can give enantiomeric excess in the product, avoiding a 50:50 racemic outcome from a symmetrical starting material.",
        ],
        workedSolution: [
          "A chiral catalyst is a catalyst built from chiral ligands or structures so that its active site is not superimposable on its mirror image, which means transition states leading to one product enantiomer can be stabilised differently from those leading to the mirror enantiomer.",
          "When a precursor is symmetric in a way that uncatalysed reaction would produce both mirror products equally, the chiral catalyst interacts more favourably with one approach geometry, so one enantiomer forms faster or with lower energy, giving an excess of that optical isomer in the crude product.",
          "Industrial use of such catalysts is one way to meet the regulatory and safety desire for a single enantiomer drug without later having to discard half the material from a racemic synthesis, because the catalytic step itself breaks the symmetry of product formation.",
        ],
        commonMistake:
          "Suggesting the catalyst changes the molecular formula of the product or converts achiral drugs into different isomers of unrelated structure.",
        tags: ["chiral-catalyst", "synthesis", "enantioselectivity"],
      },
      {
        id: "t29-4-d9",
        noteId: "t29-4",
        kind: "mcq",
        difficulty: 3,
        stem: "Which centre is definitely chiral?",
        options: [
          { id: "A", text: "A carbon bonded to two identical methyl groups and two hydrogens" },
          { id: "B", text: "A carbon bonded to H, CH_3, CH_2CH_3, and CH_2CH_2CH_3" },
          { id: "C", text: "Benzene ring carbon" },
          { id: "D", text: "Carbon in CH_4" },
        ],
        correctOptionId: "B",
        explanation:
          "Four different substituents on carbon gives a chiral centre (stereogenic carbon).",
        distractorRationale: {
          A: "Two identical substituents prevent chirality at that carbon.",
          C: "Aromatic ring carbons in benzene are not tetrahedral stereogenic centres in the usual sense.",
          D: "Methane has four identical hydrogens, so the carbon is not chiral.",
        },
        tags: ["chiral-centre", "classification"],
      },
      {
        id: "t29-4-d10",
        noteId: "t29-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A student synthesises a chiral alcohol from an achiral ketone using NaBH_4 and obtains a racemic mixture. Outline why a racemic outcome is expected from this reagent, and contrast that with what the syllabus highlights when an enantiopure drug is required from a racemic intermediate.",
        modelAnswerPoints: [
          "NaBH_4 delivers hydride to the planar trigonal carbonyl carbon from either face with equal probability.",
          "Attack from opposite faces generates R and S alcohol in equal amounts → racemic if a new chiral centre is formed.",
          "Drug context: racemic product may need resolution into enantiomers or an enantioselective route (e.g. chiral catalyst) to obtain single enantiomer material.",
        ],
        workedSolution: [
          "The carbonyl carbon of a ketone is sp² hybridised with a trigonal planar arrangement, so the π lobe is equally accessible from above and below the plane in the absence of chiral influence, which makes hydride attack from either face equally likely in a simple NaBH_4 reduction.",
          "When reduction creates a new tetrahedral stereogenic centre bearing four different groups, attack from one face gives one enantiomer of the alcohol and attack from the opposite face gives the mirror enantiomer, so equal rates produce a racemic mixture overall.",
          "The syllabus contrasts this kind of achiral reduction with pharmaceutical goals: a racemic drug intermediate may require separation into pure enantiomers if only one enantiomer is therapeutic, or production may be redesigned using chiral catalysts or other enantioselective steps so that the single desired optical isomer is made directly rather than discarding half of a racemic batch.",
        ],
        commonMistake:
          "Claiming NaBH_4 is chiral, or that a racemic product must be optically active.",
        tags: ["racemic", "reduction", "synthesis-context"],
      },
    ],
    flashcards: [
      {
        id: "t29-4-f1",
        noteId: "t29-4",
        difficulty: 1,
        front: "What is an enantiomer?",
        back: "One of a pair of non-superimposable mirror-image molecules.",
        examPhrasing: "Define enantiomers.",
        tags: ["enantiomers"],
      },
      {
        id: "t29-4-f2",
        noteId: "t29-4",
        difficulty: 1,
        front: "What is optical activity?",
        back: "Ability to rotate the plane of plane polarised light.",
        examPhrasing: "Define optically active.",
        tags: ["optical-activity"],
      },
      {
        id: "t29-4-f3",
        noteId: "t29-4",
        difficulty: 2,
        front: "Racemic mixture rotation?",
        back: "No net rotation (equal and opposite contributions).",
        examPhrasing: "State the observed rotation of a racemic mixture.",
        tags: ["racemic"],
      },
      {
        id: "t29-4-f4",
        noteId: "t29-4",
        difficulty: 2,
        front: "Same property for enantiomers in achiral conditions?",
        back: "Boiling point, melting point, density, and reactivity toward achiral reagents match.",
        examPhrasing: "List properties that are identical for enantiomers.",
        tags: ["enantiomers"],
      },
      {
        id: "t29-4-f5",
        noteId: "t29-4",
        difficulty: 3,
        front: "Chiral centre requirement?",
        back: "Usually a carbon with four different substituents (tetrahedral).",
        examPhrasing: "State when a carbon atom is chiral.",
        tags: ["chiral-centre"],
      },
      {
        id: "t29-4-f6",
        noteId: "t29-4",
        difficulty: 3,
        front: "Why can drug enantiomers differ in effect?",
        back: "Biological targets are chiral; binding depends on 3D fit.",
        examPhrasing: "Explain different biological activity of enantiomers.",
        tags: ["drugs", "chirality"],
      },
      {
        id: "t29-4-f7",
        noteId: "t29-4",
        difficulty: 4,
        front: "Why resolve a racemate for a drug?",
        back: "To obtain pure active enantiomer and limit effects from the mirror form.",
        examPhrasing: "Give a reason to separate a racemic drug mixture.",
        tags: ["separation"],
      },
      {
        id: "t29-4-f8",
        noteId: "t29-4",
        difficulty: 4,
        front: "Role of chiral catalyst?",
        back: "Induces enantioselectivity so one enantiomer forms preferentially.",
        examPhrasing: "Explain use of a chiral catalyst in synthesis.",
        tags: ["chiral-catalyst"],
      },
      {
        id: "t29-4-f9",
        noteId: "t29-4",
        difficulty: 5,
        front: "NaBH_4 on achiral ketone forming new stereocentre — product type?",
        back: "Typically racemic mixture of alcohol enantiomers.",
        examPhrasing: "Predict stereochemical outcome of hydride attack on a planar ketone.",
        confusionPair: "racemic vs enantiopure reduction",
        tags: ["synthesis", "racemic"],
      },
      {
        id: "t29-4-f10",
        noteId: "t29-4",
        difficulty: 5,
        front: "Enantiomers and plane polarised light — key idea?",
        back: "Equal and opposite rotation; same magnitude under identical conditions.",
        examPhrasing: "Compare rotation angles for two enantiomers.",
        tags: ["polarimetry"],
      },
    ],
  },
};
