import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 36 / 36.1 — Organic synthesis: one course subtopic `t36-1`.
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §36.1; each bullet hit by ≥1 drill id):
 * - Multi-functional molecules: (a) identify functional groups using syllabus reactions (b) predict properties/reactions → d2, d3, d4, d7
 * - Devise multi-step synthetic routes using syllabus reactions → d5, d6
 * - Analyse a given route: reaction type, reagents each step, possible by-products → d1, d8, d9, d10
 */
export const CHEMISTRY_TOPIC36_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t36-1": {
    noteId: "t36-1",
    drills: [
      {
        id: "t36-1-d1",
        noteId: "t36-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "State what examiners usually expect when they ask you to analyse a given multi-step synthetic route. Explain why mentioning possible by-products is part of a complete analysis, not an optional extra.",
        modelAnswerPoints: [
          "For each step, identify the reaction type (for example nucleophilic substitution, electrophilic addition, oxidation, reduction, hydrolysis, nucleophilic addition-elimination at a carbonyl).",
          "Give the key reagent(s) and essential conditions (for example reflux versus distillation, acidified oxidising agent, ethanolic versus aqueous ammonia).",
          "Describe the structural or functional-group change at that arrow (what functional group is lost or gained).",
          "By-products matter because they follow from the mechanism and stoichiometry (for example HCl from acyl chlorides, further alkylation of amines, over-oxidation if oxidation is not controlled) and show whether the route is chemically realistic.",
        ],
        workedSolution: [
          "When a mark scheme refers to analysing a synthetic route, it is looking for a disciplined commentary on every arrow, not a vague list of chemical names, so a strong answer states the reaction type first because that fixes the mechanism family and therefore what reagents are plausible.",
          "The key reagents must be named together with the conditions that control the outcome, because the same reagent system can give different products depending on whether the mixture is distilled to remove a volatile aldehyde or heated under reflux to drive oxidation all the way to a carboxylic acid.",
          "The analysis must also say how the carbon skeleton or functional groups change at that step, for example primary alcohol to aldehyde then to carboxylic acid, so the examiner can see that you are tracking functional-group interconversions rather than memorising disconnected reagent names.",
          "Possible by-products are central to the syllabus bullet on route analysis because many syllabus reactions release a small molecule such as hydrogen chloride when an acyl chloride is used, or can give mixtures such as secondary and tertiary amines if ammonia is not in excess, and recognising those outcomes proves you understand the chemistry of the step rather than only the major product drawn on the scheme.",
        ],
        commonMistake:
          "Listing reagents for each box without naming reaction types or without commenting on conditions, then omitting any mention of side-products even when the question asks for route analysis.",
        tags: ["route-analysis", "definitions", "by-products", "exam-technique"],
      },
      {
        id: "t36-1-d2",
        noteId: "t36-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "An organic compound P gives an orange-red precipitate with 2,4-dinitrophenylhydrazine reagent, does not give a silver mirror with Tollens' reagent, and decolourises bromine water at room temperature. Deduce which functional groups are present in P and justify each assignment by reference to the tests.",
        modelAnswerPoints: [
          "2,4-DNPH indicates a carbonyl group (aldehyde or ketone).",
          "No reaction with Tollens' reagent argues against a simple aldehyde, so a ketone is the better assignment for the carbonyl.",
          "Decolourisation of bromine water indicates an addition reaction typical of unsaturation, most commonly a C=C double bond in an alkene.",
          "Conclusion: P is consistent with containing both a ketone group and an alkene group, supported by more than one independent test.",
        ],
        workedSolution: [
          "A positive result with 2,4-dinitrophenylhydrazine means that P contains a carbonyl group, because the reagent condenses with the carbonyl carbon to form a coloured hydrazone derivative that precipitates from solution.",
          "Tollens' reagent is a mild oxidising mixture that reduces aldehydes in situ to give a silver mirror on the clean glass, but it does not normally react with ketones under the usual teaching conditions, so the absence of a silver mirror strongly suggests that the carbonyl in P is not a simple aldehyde and is therefore more consistent with a ketone.",
          "Bromine water is decolourised at room temperature when bromine adds across a carbon-carbon double bond in an alkene, so the loss of colour shows that P also contains unsaturation of that kind rather than only aromatic ring bromination under these conditions.",
          "Taken together, the three observations converge on a molecule that contains both a ketone carbonyl and an alkene, and the answer is stronger because each functional group is supported by a different type of chemical evidence rather than by a single ambiguous test.",
        ],
        commonMistake:
          "Assigning an aldehyde despite a negative Tollens' test, or claiming aromatic substitution from bromine water without stating that the usual school test targets C=C in alkenes.",
        tags: ["functional-groups", "tests", "ketone", "alkene", "identification"],
      },
      {
        id: "t36-1-d3",
        noteId: "t36-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which observation is expected when excess solid sodium hydrogen carbonate is added to a solution of 2-hydroxybutanoic acid, CH3CH(OH)CH2COOH(aq)?",
        options: [
          { id: "A", text: "No gas is evolved; the alcohol group neutralises the hydrogencarbonate." },
          { id: "B", text: "Effervescence occurs as CO2 is evolved, because the carboxylic acid is stronger than carbonic acid." },
          { id: "C", text: "A pink colour appears immediately without heating." },
          { id: "D", text: "A sweet-smelling ester layer forms without added acid or heat." },
        ],
        correctOptionId: "B",
        explanation:
          "Carboxylic acids protonate hydrogencarbonate to give carbonic acid, which decomposes to CO2 and water; the alcohol -OH is far too weakly acidic to do this on its own under normal conditions.",
        distractorRationale: {
          A: "Alcohols do not liberate CO2 from hydrogencarbonate; the carboxylic acid group does.",
          C: "That describes acidified manganate(VII) behaviour, not reaction with hydrogencarbonate.",
          D: "Esterification needs an acid catalyst and usually heat; it does not occur simply by mixing alcohol-acid with hydrogencarbonate.",
        },
        tags: ["multi-functional", "acids", "carbonates", "prediction"],
      },
      {
        id: "t36-1-d4",
        noteId: "t36-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "A molecule Q contains both a primary alcohol group and a carboxylic acid group on the same carbon chain. State what happens when Q is warmed with acidified potassium dichromate(VI) under reflux. Explain which functional group is oxidised and what happens to the other under these conditions.",
        modelAnswerPoints: [
          "Acidified dichromate(VI) is an oxidising agent; primary alcohols are oxidised first to aldehydes and then, under reflux with excess oxidant, to carboxylic acids.",
          "The carboxylic acid group is already at the highest oxidation state of that carbon in typical syllabus organic chemistry, so it is not further oxidised by dichromate under these conditions.",
          "Under reflux both stages of alcohol oxidation can occur, so the primary alcohol is ultimately converted to a second carboxylic acid group (or the chain bears two acid groups if they were on different carbons).",
          "The acid group in the starting material remains a carboxylic acid (same functional class) while the alcohol is oxidised.",
        ],
        workedSolution: [
          "Potassium dichromate(VI) in acid is a strong oxidising mixture, and when it is used with a primary alcohol under reflux the alcohol is oxidised in sequence because there is no distillation step to remove an intermediate aldehyde before it is attacked again.",
          "The primary alcohol carbon therefore moves up the oxidation ladder from primary alcohol to aldehyde and then to carboxylic acid, so after prolonged reflux with excess dichromate the alcohol site becomes a carboxylic acid group in the product.",
          "The carboxylic acid group already present in Q is not meaningfully oxidised further by acidified dichromate in A Level organic schemes, because that carbon is already bonded to two oxygen atoms in the acid functional group and is not treated as a further oxidation target in the same way as an alcohol carbon.",
          "So the overall prediction is that the alcohol is oxidised to an extra acid group while the original acid survives, which illustrates how multi-functional molecules react according to the reactivity of each site under the stated conditions.",
        ],
        commonMistake:
          "Claiming the existing -COOH is oxidised to 'CO2 only', or that the alcohol is untouched under reflux with dichromate.",
        tags: ["oxidation", "multi-functional", "alcohols", "acids", "prediction"],
      },
      {
        id: "t36-1-d5",
        noteId: "t36-1",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Using only reagents and reactions in the usual A Level syllabus, outline a two-step synthetic route to convert ethene into ethanoic acid. For each step state the reagents and essential conditions, classify the reaction type, and name the organic intermediate.",
        modelAnswerPoints: [
          "Step 1: hydration of ethene to ethanol using steam with concentrated phosphoric acid catalyst (or dilute sulfuric acid with appropriate conditions as taught) -> electrophilic addition.",
          "Intermediate: ethanol.",
          "Step 2: oxidation of ethanol to ethanoic acid using acidified potassium dichromate(VI) (or acidified potassium manganate(VII)) under reflux with excess oxidant -> oxidation.",
          "Alternative first step via halogenoalkane then hydroxide is acceptable if reagents and substitution are stated clearly.",
        ],
        workedSolution: [
          "Ethene is an alkene, so the first conversion to a functionalised two-carbon chain is electrophilic addition of water across the double bond, which is carried out industrially or in teaching schemes by passing a mixture of ethene and steam over a solid phosphoric acid catalyst, giving ethanol as the addition product.",
          "That step is classified as electrophilic addition because the π bond attacks an electrophilic species derived from the acid catalyst and water completes the addition, and ethanol is therefore the stable intermediate before any oxidation chemistry.",
          "The second step oxidises the primary alcohol ethanol all the way to ethanoic acid by heating under reflux with excess acidified potassium dichromate(VI), which provides dichromate ions as the oxidising agent in acidic solution so that the alcohol is not trapped as ethanal for long enough to escape further oxidation.",
          "This second stage is oxidation of a primary alcohol to a carboxylic acid, and reflux is important because it keeps volatile intermediates in the flask long enough for complete oxidation to the acid rather than stopping at the aldehyde, which would be favoured if the aldehyde were distilled off during the oxidation.",
        ],
        commonMistake:
          "Omitting the catalyst for alkene hydration, or using distillation during oxidation then claiming the major product is ethanoic acid without explaining how the aldehyde is further oxidised.",
        tags: ["multi-step", "alkenes", "alcohols", "oxidation", "synthesis"],
      },
      {
        id: "t36-1-d6",
        noteId: "t36-1",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Devise a multi-step route to prepare phenylamine (aminobenzene) starting from benzene. Give reagents and conditions for each step, classify each transformation, and name one significant by-product or limitation you must control in the sequence.",
        modelAnswerPoints: [
          "Step 1: nitration of benzene using concentrated nitric acid and concentrated sulfuric acid at about 50–60 °C -> electrophilic substitution forming nitrobenzene.",
          "Step 2: reduction of the nitro group to a primary amino group using a reducing system such as tin and concentrated hydrochloric acid (or iron and HCl, or catalytic hydrogenation as taught).",
          "The nitro reduction is classified as reduction (gain of electrons / loss of oxygen at nitrogen).",
          "Polynitration is a risk in step 1 if the temperature is too high; acid vapours and strong corrosive conditions are hazards in both steps.",
        ],
        workedSolution: [
          "Benzene cannot be turned into phenylamine in one syllabus step because the amino group must be introduced via a functional group that can survive the strongly electrophilic aromatic substitution conditions, so the standard plan is nitration followed by reduction of the nitro group.",
          "The first step is electrophilic substitution in which a nitrating acid mixture of concentrated nitric acid and concentrated sulfuric acid is warmed with benzene to about fifty to sixty degrees Celsius so that the electrophile NO2+ attacks the ring and replaces one hydrogen to give nitrobenzene while keeping polynitration under control.",
          "The second step reduces the nitro group on nitrobenzene to a primary aromatic amine; a common laboratory method is tin metal with concentrated hydrochloric acid, which supplies protons and a reducing environment, or iron with hydrochloric acid in textbook alternatives, and the overall change is reduction of nitrogen from the nitro oxidation state to -NH2.",
          "A significant limitation in the first step is that excessive temperature or prolonged heating can introduce a second nitro group, so temperature control is part of good synthetic thinking, and both stages generate corrosive acidic media that must be acknowledged when describing a realistic route.",
        ],
        commonMistake:
          "Attempting to introduce -NH2 directly by nucleophilic substitution on chlorobenzene without very forcing conditions, or nitrating under uncontrolled high temperature and ignoring dinitration risk.",
        tags: ["aromatic", "nitration", "reduction", "amine", "multi-step"],
      },
      {
        id: "t36-1-d7",
        noteId: "t36-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best describes reliable functional-group identification in a molecule that may contain several different functional groups?",
        options: [
          { id: "A", text: "A single positive test is always sufficient to assign every group in the molecule." },
          { id: "B", text: "Negative tests are uninformative and should be ignored when proposing a structure." },
          { id: "C", text: "Converging evidence from several tests, including negative results where relevant, supports assignment of each group." },
          { id: "D", text: "2,4-DNPH alone distinguishes aldehydes from ketones without any further test." },
        ],
        correctOptionId: "C",
        explanation:
          "Multi-functional identification should combine independent observations; a negative Tollens' test, for example, helps exclude a simple aldehyde when a carbonyl is still indicated by 2,4-DNPH.",
        distractorRationale: {
          A: "One test can be ambiguous or compatible with more than one arrangement of groups.",
          B: "Negative results often rule out alternatives and are explicitly useful in syllabus-style reasoning.",
          D: "2,4-DNPH detects carbonyls generally; Tollens' (or other follow-up) is needed to separate aldehyde from ketone.",
        },
        tags: ["identification", "tests", "logic", "multi-functional"],
      },
      {
        id: "t36-1-d8",
        noteId: "t36-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "A synthetic step shows ethanoyl chloride reacting with propan-1-ol in the dry state. Analyse the step by naming the reaction type, stating the organic product, and identifying the small-molecule by-product formed. Explain briefly why anhydrous conditions are used.",
        modelAnswerPoints: [
          "Reaction type: nucleophilic addition-elimination at an acyl chloride (acyl substitution).",
          "Organic product: propyl ethanoate (an ester) formed from ethanoate linked to the propoxy fragment.",
          "By-product: hydrogen chloride gas (or HCl in solution if water were present).",
          "Anhydrous conditions prevent premature hydrolysis of the acyl chloride to ethanoic acid and keep the alcohol as nucleophile rather than losing reagent to side reactions with water.",
        ],
        workedSolution: [
          "Ethanoyl chloride contains a very electrophilic carbonyl carbon bonded to chlorine, so when propan-1-ol approaches, the lone pair on the alcohol oxygen attacks that carbon in the first stage of nucleophilic addition-elimination, which is the mechanism family the syllabus uses for acyl chloride reactions.",
          "After tetrahedral collapse and loss of chloride, the overall result is replacement of Cl on the carbonyl by the propoxy group, which gives the ester propyl ethanoate as the main organic product while the ethanoyl fragment supplies the acyl part of the ester linkage.",
          "Chloride leaves as chloride ion, but a proton is transferred in the usual textbook sequence so that hydrogen chloride is generated as the small acidic molecule alongside the ester, which is why the reaction is often carried out with a base present in more advanced laboratory practice even though the question here only asks you to name the by-product.",
          "Water would compete as a nucleophile and hydrolyse ethanoyl chloride to ethanoic acid, and it would also waste some of the alcohol, so dry conditions are essential to obtain a clean ester product from the acyl chloride route.",
        ],
        commonMistake:
          "Calling the step simple esterification with concentrated sulfuric acid catalyst, or omitting HCl as the inorganic co-product of acyl chloride + alcohol.",
        tags: ["acyl-chloride", "ester", "by-products", "route-analysis", "mechanism"],
      },
      {
        id: "t36-1-d9",
        noteId: "t36-1",
        kind: "mcq",
        difficulty: 3,
        stem: "1-Bromobutane is heated with an excess of concentrated ammonia in ethanol in a sealed tube. Which outcome is most important to mention in a full synthetic analysis?",
        options: [
          { id: "A", text: "The reaction stops at the quaternary ammonium salt as the only product." },
          { id: "B", text: "Further nucleophilic substitution can produce secondary and tertiary amines alongside the primary amine, so excess ammonia limits but does not always eliminate mixtures." },
          { id: "C", text: "No reaction occurs because ammonia is too weak a nucleophile for primary halogenoalkanes." },
          { id: "D", text: "The major organic product is always butan-1-ol." },
        ],
        correctOptionId: "B",
        explanation:
          "NH3 substitutes for Br to give a primary amine, but the product amine can also act as a nucleophile; excess ammonia favours primary amine formation but mixtures remain a syllabus realism point.",
        distractorRationale: {
          A: "Quaternary salts arise from exhaustive alkylation of amines, not as the sole immediate outcome of a single substitution under typical teaching emphasis.",
          C: "Ammonia is a good nucleophile toward primary halogenoalkanes under these conditions.",
          D: "Substitution gives an amine; hydroxide would be needed for alcohol formation under different conditions.",
        },
        tags: ["amines", "by-products", "halogenoalkanes", "synthesis"],
      },
      {
        id: "t36-1-d10",
        noteId: "t36-1",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Consider the two-step route: propene is treated with steam and a phosphoric acid catalyst to give compound A; A is then oxidised with acidified potassium dichromate(VI) under reflux to give compound B. Identify A and B, classify each step, state the reagents/catalyst already implied, and discuss one regiochemical or selectivity point that a good route analysis should mention for the first step.",
        modelAnswerPoints: [
          "Step 1 is electrophilic hydration of propene; with phosphoric acid / steam the major product follows Markovnikov orientation, so A is propan-2-ol for the main pathway.",
          "Step 2 is oxidation of a secondary alcohol under reflux with excess acidified dichromate(VI), so B is propanone (acetone), a ketone.",
          "A selectivity comment is that unsymmetrical alkenes can in principle give mixtures of alcohols if carbocation rearrangements or dual addition modes were significant, but propene hydration is usually taught as giving predominantly propan-2-ol.",
          "By-products in oxidation could include oxidation fragments only if conditions were extreme; under standard controlled reflux of secondary alcohol, the ketone is the syllabus product rather than C-C cleavage.",
        ],
        workedSolution: [
          "Propene adds water across the double bond in the presence of an acid catalyst such as phosphoric acid, which protonates the alkene to give the more stable secondary carbocation at the central carbon, so water then attacks that centre and the major alcohol formed after deprotonation is propan-2-ol, which is therefore compound A in the usual Markovnikov picture.",
          "That first transformation is classified as electrophilic addition of water because the π bond attacks an electrophilic species generated under acidic conditions and the overall result is addition across the original double bond.",
          "The second step treats a secondary alcohol with acidified potassium dichromate(VI) under reflux, and secondary alcohols are oxidised to ketones under these conditions because there is no hydrogen on the carbon bearing the OH to allow further oxidation to a carboxylic acid, so B is propanone.",
          "A careful route analysis notes that propene is unsymmetrical, so regioselectivity matters: the major alcohol is branched at the centre because the intermediate cation is more stable at the secondary position, and although examination questions often assume clean propan-2-ol, the reasoning is part of full synthetic literacy for Topic 36.",
        ],
        commonMistake:
          "Naming propan-1-ol as the sole product of propene + steam under acid without discussing Markovnikov control, or oxidising propan-2-ol to propanoic acid as if it were a primary alcohol.",
        tags: ["alkenes", "hydration", "oxidation", "route-analysis", "selectivity"],
      },
    ],
    flashcards: [
      {
        id: "t36-1-f1",
        noteId: "t36-1",
        difficulty: 1,
        front: "What does a positive 2,4-DNPH test tell you?",
        back: "A carbonyl group is present (aldehyde or ketone); it does not by itself separate those two classes.",
        examPhrasing: "State what can be deduced from a positive result with 2,4-dinitrophenylhydrazine.",
        tags: ["tests", "carbonyl"],
      },
      {
        id: "t36-1-f2",
        noteId: "t36-1",
        difficulty: 1,
        front: "How does Tollens' reagent distinguish aldehydes from ketones?",
        back: "Aldehydes reduce Tollens' reagent and give a silver mirror; simple ketones do not under usual conditions.",
        examPhrasing: "Describe the use of Tollens' reagent to distinguish an aldehyde from a ketone.",
        confusionPair: "Tollens' vs Fehling's",
        tags: ["tests", "aldehyde", "ketone"],
      },
      {
        id: "t36-1-f3",
        noteId: "t36-1",
        difficulty: 2,
        front: "Name three things to state for each arrow when analysing a synthetic route.",
        back: "Reaction type; reagents and key conditions; functional-group / structural change (plus plausible by-products when asked).",
        examPhrasing: "Analyse the steps in the synthetic scheme provided.",
        tags: ["route-analysis", "exam-technique"],
      },
      {
        id: "t36-1-f4",
        noteId: "t36-1",
        difficulty: 2,
        front: "Typical by-product when an acyl chloride reacts with an alcohol?",
        back: "Hydrogen chloride (HCl); water must be excluded to avoid hydrolysing the acyl chloride.",
        examPhrasing: "Identify a by-product of the reaction between an acyl chloride and an alcohol.",
        tags: ["acyl-chloride", "by-products"],
      },
      {
        id: "t36-1-f5",
        noteId: "t36-1",
        difficulty: 3,
        front: "Primary alcohol + acidified K2Cr2O7 under reflux with excess oxidant?",
        back: "Oxidised to the carboxylic acid (via aldehyde if not distilled off).",
        examPhrasing: "State the product when a primary alcohol is oxidised under reflux with acidified dichromate(VI).",
        confusionPair: "reflux vs distillation for oxidation",
        tags: ["oxidation", "alcohols"],
      },
      {
        id: "t36-1-f6",
        noteId: "t36-1",
        difficulty: 3,
        front: "Reagents to reduce a nitrobenzene group to an amino group?",
        back: "Sn + conc HCl (or Fe + HCl, or H2 / catalyst as taught) — reduction of -NO2 to -NH2.",
        examPhrasing: "Give reagents for the reduction of nitrobenzene to phenylamine.",
        tags: ["reduction", "amine", "aromatic"],
      },
      {
        id: "t36-1-f7",
        noteId: "t36-1",
        difficulty: 4,
        front: "Why use excess concentrated ammonia with a halogenoalkane to make a primary amine?",
        back: "Excess NH3 reduces further substitution to secondary/tertiary amines, though some mixture risk remains.",
        examPhrasing: "Explain why ammonia should be in excess when preparing a primary amine from a halogenoalkane.",
        tags: ["amines", "synthesis", "selectivity"],
      },
      {
        id: "t36-1-f8",
        noteId: "t36-1",
        difficulty: 4,
        front: "Secondary alcohol + acidified dichromate under reflux?",
        back: "Oxidised to a ketone (not further to a carboxylic acid).",
        examPhrasing: "State the organic product when a secondary alcohol is oxidised under reflux.",
        tags: ["oxidation", "ketone"],
      },
      {
        id: "t36-1-f9",
        noteId: "t36-1",
        difficulty: 5,
        front: "What does 'retrosynthesis' mean in route planning?",
        back: "Working backwards from the target by disconnecting to known syllabus precursors, then checking each forward step for feasibility and side reactions.",
        examPhrasing: "Outline how you would plan a multi-step synthesis of a stated target molecule.",
        tags: ["retrosynthesis", "planning"],
      },
      {
        id: "t36-1-f10",
        noteId: "t36-1",
        difficulty: 5,
        front: "Bromine water decolourises — what functional group is most commonly being tested at room temperature?",
        back: "C=C in an alkene (electrophilic addition of bromine).",
        examPhrasing: "Interpret decolourisation of bromine water by an unknown organic compound.",
        confusionPair: "alkene vs phenol bromination conditions",
        tags: ["tests", "alkene"],
      },
    ],
  },
};
