import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 34 — Amines, phenylamine / azo, amides, amino acids (`t34-1`–`t34-4`).
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §34.1–34.4; each bullet hit by ≥1 drill id):
 *
 * **34.1** — (a) RHal + NH₃ / ethanol / pressure → d1, d2, d7; (b) RHal + primary amine → d2, d9;
 * (c) amide + LiAlH₄ → d4; (d) nitrile + LiAlH₄ or H₂/Ni → d3, d10; acyl chloride condensation → d5, d7;
 * basicity of aqueous amines → d6, d8.
 *
 * **34.2** — Benzene → nitrobenzene → Sn/HCl → NaOH → phenylamine → d1, d6; Br₂(aq); diazonium cold / warm H₂O → phenol → d2, d3, d9;
 * basicity NH₃ / ethylamine / phenylamine → d4, d7; azo coupling, -N=N-, dyes → d5, d8, d10.
 *
 * **34.3** — NH₃ or RNH₂ + acyl chloride (RT) → d1, d2, d8; acid / alkali hydrolysis → d3, d4; LiAlH₄ reduction → d5;
 * amides weaker bases than amines → d6, d7, d9, d10.
 *
 * **34.4** — Amphoteric / zwitterions / pI → d1, d2, d8; peptide bonds di- / tripeptide → d3, d4, d10;
 * electrophoresis interpretation → d6, d7, d9.
 */
export const CHEMISTRY_TOPIC34_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t34-1": {
    noteId: "t34-1",
    drills: [
      {
        id: "t34-1-d1",
        noteId: "t34-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "State the reagents and conditions used in this syllabus to convert a halogenoalkane into a primary amine. Name the mechanism family and explain briefly why the reaction is not carried out using aqueous ammonia alone as the solvent.",
        modelAnswerPoints: [
          "Reagents: ammonia; solvent: ethanol; conditions: heated under pressure or in a sealed tube.",
          "The conversion is nucleophilic substitution in which NH₃ replaces the halogen on the alkyl chain.",
          "Aqueous ammonia is a poor choice as the sole medium because the halogenoalkane is not very soluble in water and the syllabus specifies ethanolic ammonia with heating under pressure or in a sealed tube to give a practical rate.",
        ],
        workedSolution: [
          "To prepare a primary amine from a halogenoalkane, ammonia is used as the nucleophile in ethanol as solvent, with the mixture heated under pressure or heated in a sealed tube, which matches the board’s required conditions for this substitution route.",
          "The underlying process is nucleophilic substitution, because the lone pair on nitrogen attacks the δ+ carbon bonded to the halogen and the halide ion leaves, giving a primary amine after proton transfers in the usual teaching sequence.",
          "Although ammonia in water exists as NH₃(aq), the syllabus does not present that as the standard solvent for halogenoalkane amination; ethanol dissolves the organic substrate better and heating under pressure (or a sealed tube) raises the temperature safely above ethanol’s normal boiling point so the substitution occurs at an acceptable rate.",
        ],
        commonMistake:
          "Writing only ‘NH₃(aq) at room temperature’ without ethanol and without heated sealed-tube or pressure conditions.",
        tags: ["primary-amines", "halogenoalkanes", "conditions", "substitution"],
      },
      {
        id: "t34-1-d2",
        noteId: "t34-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Contrast how a secondary amine is prepared from a halogenoalkane with how a primary amine is prepared. State the nitrogen-containing reactant in each case and the shared practical conditions.",
        modelAnswerPoints: [
          "Primary amine route: halogenoalkane + ammonia in ethanol, heated under pressure or in a sealed tube.",
          "Secondary amine route: halogenoalkane + a primary amine (not ammonia) in ethanol, heated under pressure or in a sealed tube.",
          "Both routes are nucleophilic substitution on carbon; the nucleophile is NH₃ in the first case and RNH₂ in the second.",
        ],
        workedSolution: [
          "A primary amine is made when the halogenoalkane reacts with ammonia itself, because each ammonia molecule can supply one chain-attached nitrogen after substitution and subsequent proton transfers, giving R–NH₂ as the target primary amine product class.",
          "A secondary amine is made when the halogenoalkane reacts with a primary amine as the nucleophile, because the nitrogen of RNH₂ already carries one alkyl group, so after it replaces the halogen the new C–N bond leaves nitrogen bonded to two alkyl groups overall, which is the defining structural feature of a secondary amine.",
          "In both cases the syllabus expects the same broad practical picture: ethanolic medium with heating under pressure or in a sealed tube, chosen so that the halogenoalkane and the amine-type nucleophile remain in contact at a temperature high enough for substitution to proceed usefully.",
        ],
        commonMistake:
          "Using ammonia as the nucleophile when the question asks for a secondary amine from a halogenoalkane, or naming a tertiary amine as the required nucleophile.",
        tags: ["secondary-amines", "primary-amines", "comparison", "conditions"],
      },
      {
        id: "t34-1-d3",
        noteId: "t34-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which reducing system is not a syllabus-accepted method for converting a nitrile into a primary amine?",
        options: [
          { id: "A", text: "LiAlH₄ (lithium tetrahydridoaluminate(III))." },
          { id: "B", text: "H₂ with a nickel catalyst." },
          { id: "C", text: "Acidified potassium dichromate(VI), reflux." },
          { id: "D", text: "H₂/Ni as an alternative to LiAlH₄ for nitrile reduction." },
        ],
        correctOptionId: "C",
        explanation:
          "The syllabus lists LiAlH₄ or H₂/Ni for nitrile → amine. Acidified dichromate is an oxidising mixture, not a reduction route to an amine.",
        distractorRationale: {
          A: "LiAlH₄ is explicitly required knowledge for nitrile reduction to an amine.",
          B: "Catalytic hydrogenation with H₂/Ni is the second accepted nitrile reduction method.",
          D: "This restates an accepted alternative; it is not a wrong reagent choice for reduction.",
        },
        tags: ["nitriles", "reduction", "reagents"],
      },
      {
        id: "t34-1-d4",
        noteId: "t34-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "State how an amide is converted into an amine in this syllabus. Identify the functional group that is reduced and name a suitable reducing agent.",
        modelAnswerPoints: [
          "Amides are reduced to amines using LiAlH₄.",
          "The carbonyl (C=O) group of the amide is reduced so that the oxygen-containing environment of the acyl carbon is lost and an amine is obtained.",
          "LiAlH₄ supplies hydride equivalents that reduce the amide carbonyl in the required transformation.",
        ],
        workedSolution: [
          "The syllabus requires recall that amides are reduced to amines by lithium tetrahydridoaluminate(III), LiAlH₄, which is a powerful reducing agent capable of converting the amide carbonyl all the way to the amine oxidation level.",
          "In conceptual terms it is the amide’s carbonyl group that is being reduced, because the C=O π system is cleared during the conversion and the nitrogen ends up attached to an alkyl (or hydrogen) framework characteristic of an amine rather than an amide.",
          "Examination answers should name LiAlH₄ explicitly for amide reduction, and should not substitute milder reagents such as NaBH₄ unless a question specifically introduces them, because the learning outcome ties amide reduction to LiAlH₄ in the 9701 content list.",
        ],
        commonMistake:
          "Stating H₂/Ni for amide reduction (that pairing is emphasised for nitriles; amide reduction is tied to LiAlH₄ here).",
        tags: ["amides", "reduction", "LiAlH4"],
      },
      {
        id: "t34-1-d5",
        noteId: "t34-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Ethanoyl chloride is treated with an excess of methylamine at room temperature. Name the organic product type and give its systematic or unambiguous common name. Write a balanced equation showing the organic reactants and products. Explain why excess methylamine is often used practically.",
        modelAnswerPoints: [
          "The product is an N-substituted amide (secondary amide): N-methylethanamide (acceptable: N-methylacetamide).",
          "CH₃COCl + CH₃NH₂ -> CH₃CONHCH₃ + HCl (room temperature).",
          "HCl is formed; excess methylamine acts as a base to neutralise HCl, limiting protonation of the nucleophile and helping the condensation go to completion.",
        ],
        workedSolution: [
          "At room temperature an acyl chloride reacts with an amine in a condensation to form an amide, with hydrogen chloride as the small molecule eliminated alongside formation of the C–N bond of the amide linkage.",
          "Because the nitrogen nucleophile is methylamine, a primary amine, the product is an N-substituted amide in which the ethanoyl fragment is attached to nitrogen that also carries a methyl substituent, which is systematically named N-methylethanamide and is often called N-methylacetamide in informal laboratory language.",
          "A balanced organic equation is CH₃COCl + CH₃NH₂ -> CH₃CONHCH₃ + HCl, showing replacement of Cl on the acyl carbon by the nitrogen of methylamine while the carbonyl oxygen remains part of the amide functional group.",
          "Hydrogen chloride is a strong acid, so if it accumulates it can protonate methylamine and reduce its nucleophilicity; using excess methylamine provides base to neutralise HCl as it forms, which keeps more free amine available and is the usual textbook reason for excess nitrogen nucleophile in acyl chloride aminolysis problems.",
        ],
        commonMistake:
          "Naming a primary amide (ethanamide) instead of the N-substituted product when methylamine is the amine reactant.",
        tags: ["acyl-chlorides", "amides", "condensation", "room-temperature"],
      },
      {
        id: "t34-1-d6",
        noteId: "t34-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best explains why a simple alkylamine such as ethylamine produces an alkaline solution in pure water?",
        options: [
          { id: "A", text: "Ethylamine fully ionises in water to give a strongly acidic solution." },
          { id: "B", text: "The lone pair on nitrogen accepts a proton from water, producing OH⁻ and making the solution weakly alkaline." },
          { id: "C", text: "Ethylamine donates a proton to water, producing H₃O⁺ and an acidic solution." },
          { id: "D", text: "Ethylamine is neutral in water because it cannot act as a Brønsted-Lowry base." },
        ],
        correctOptionId: "B",
        explanation:
          "Amines are weak Brønsted-Lowry bases: RNH₂ + H₂O ⇌ RNH₃⁺ + OH⁻, so pH > 7 but the equilibrium lies mainly to the left.",
        distractorRationale: {
          A: "Alkylamines are weak bases, not strong electrolytes that fully ionise to acid.",
          C: "That would describe an acid donating H⁺ to water, not a base generating OH⁻.",
          D: "Amines clearly have a basic lone pair and do react with water to some extent as bases.",
        },
        tags: ["basicity", "amines", "Brønsted-Lowry"],
      },
      {
        id: "t34-1-d7",
        noteId: "t34-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Describe the condensation reaction of ammonia with an acyl chloride at room temperature. Name the organic product class formed from a simple alkanoyl chloride such as ethanoyl chloride and state one by-product.",
        modelAnswerPoints: [
          "Ammonia reacts with the acyl chloride at room temperature in a condensation reaction.",
          "A primary amide is formed (e.g. ethanamide from ethanoyl chloride).",
          "Hydrogen chloride is produced as by-product.",
        ],
        workedSolution: [
          "Acyl chlorides are highly reactive acylating agents, so ammonia attacks the electrophilic acyl carbon at room temperature without needing the high-temperature conditions associated with some other acylations.",
          "The nitrogen of ammonia replaces chloride on the acyl carbon and the C=O double bond remains, which means the functional group formed is a primary amide, for example ethanamide when the acyl chloride is ethanoyl chloride.",
          "Because Cl leaves as chloride and the NH₂ fragment becomes attached to the carbonyl carbon, a small molecule HCl is eliminated alongside amide formation, which is why the process is classified as condensation in the syllabus sense.",
        ],
        commonMistake:
          "Claiming that an amine (not ammonia) is always used, or that an ester is the product of ammonia + acyl chloride.",
        tags: ["acyl-chlorides", "ammonia", "amides", "condensation"],
      },
      {
        id: "t34-1-d8",
        noteId: "t34-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Explain why aqueous solutions of simple alkylamines are basic. Your answer should use Brønsted-Lowry terminology, an equilibrium expression with ethylamine as the example, and should state whether the base strength is ‘strong’ or ‘weak’ in water and why.",
        modelAnswerPoints: [
          "Amines act as Brønsted-Lowry bases by accepting a proton from water using the nitrogen lone pair.",
          "For ethylamine: C₂H₅NH₂ + H₂O ⇌ C₂H₅NH₃⁺ + OH⁻.",
          "They are weak bases: the equilibrium lies mainly to the left, so only partial conversion to OH⁻ occurs.",
          "Alkyl groups donate electron density inductively, tending to increase basicity compared with ammonia, though water solvation also influences exact ordering.",
        ],
        workedSolution: [
          "In Brønsted-Lowry terms a base is a species that can accept a proton, and simple alkylamines possess a lone pair on nitrogen that can bind H⁺ from a water molecule, which is exactly how they behave in aqueous solution.",
          "For ethylamine the proton-transfer equilibrium can be written as C₂H₅NH₂ + H₂O ⇌ C₂H₅NH₃⁺ + OH⁻, showing that hydroxide ions are generated when ethylamine is dissolved in water, which is why the measured pH rises above 7.",
          "Alkylamines are weak bases in water because the equilibrium lies well to the reactant side for typical concentrations, meaning only a small fraction of amine molecules are protonated at any moment and the concentration of OH⁻ is modest compared with what a strong base would produce.",
          "The ethyl substituent releases electron density towards nitrogen by an inductive effect relative to hydrogen in ammonia, which increases electron density on nitrogen and tends to strengthen basicity, although examination answers should still describe the behaviour as weakly basic overall and can mention that solvation and steric factors prevent a naive ‘more alkyl always means much stronger’ rule from being pushed too far unless the question demands a detailed ranking.",
        ],
        commonMistake:
          "Calling amines strong bases, or omitting OH⁻ in the equilibrium so the reason for alkalinity is unclear.",
        tags: ["basicity", "equilibrium", "ethylamine", "definitions"],
      },
      {
        id: "t34-1-d9",
        noteId: "t34-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which reagent set converts bromoethane into diethylamine (N-ethylethanamine) by the halogenoalkane route specified in the syllabus?",
        options: [
          { id: "A", text: "NH₃ in ethanol, heated under pressure." },
          { id: "B", text: "Ethylamine in ethanol, heated under pressure or in a sealed tube." },
          { id: "C", text: "Ammonia in water at room temperature." },
          { id: "D", text: "Ethanamide with LiAlH₄ only." },
        ],
        correctOptionId: "B",
        explanation:
          "A secondary amine from RBr requires a primary amine nucleophile (here ethylamine), in ethanol with heat under pressure or sealed tube.",
        distractorRationale: {
          A: "That route gives a primary amine (ethylamine), not diethylamine.",
          C: "Aqueous conditions at room temperature do not match the syllabus halogenoalkane amination conditions.",
          D: "LiAlH₄ reduces amides to amines but does not couple two ethyl groups onto nitrogen starting from bromoethane in one step as asked.",
        },
        tags: ["secondary-amines", "reagents", "halogenoalkanes"],
      },
      {
        id: "t34-1-d10",
        noteId: "t34-1",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Compare converting bromoethane into ethylamine by reaction with ammonia in ethanol under pressure with preparing ethylamine by reducing ethanenitrile. State one advantage of the nitrile reduction route in terms of carbon-chain construction.",
        modelAnswerPoints: [
          "Halogenoalkane route: bromoethane + NH₃ in ethanol, heated under pressure or sealed tube → ethylamine (same carbon number as halide).",
          "Nitrile route: ethanenitrile reduced with LiAlH₄ or H₂/Ni → ethylamine.",
          "Nitrile reduction adds the nitrile carbon into the chain that becomes the amine; starting from a halide with one fewer carbon than the target amine, nitrile formation then reduction lengthens the chain in a controlled way.",
        ],
        workedSolution: [
          "The syllabus expects recall that a primary amine can be made from the corresponding halogenoalkane using ammonia in ethanol with heating under pressure or in a sealed tube, so bromoethane is converted to ethylamine without changing the number of carbon atoms in the chain.",
          "The same ethylamine can alternatively be obtained by reducing ethanenitrile, using either LiAlH₄ or hydrogen with a nickel catalyst, both of which deliver hydride or hydrogen equivalents that reduce the carbon–nitrogen triple bond to the amine oxidation level.",
          "The practical synthetic advantage often emphasised for nitrile reduction is that the nitrile carbon becomes part of the amine chain, so if you need an amine with one more carbon than an available halogenoalkane, you can form a nitrile with the extra carbon and then reduce, whereas direct ammonia substitution on the shorter halide cannot increase chain length in that way.",
        ],
        commonMistake:
          "Claiming both routes always change the carbon count identically for every target without noting the extra carbon contributed by the nitrile group.",
        tags: ["nitriles", "synthesis", "comparison", "reduction"],
      },
    ],
    flashcards: [
      {
        id: "t34-1-f1",
        noteId: "t34-1",
        difficulty: 1,
        front: "Conditions: halogenoalkane → primary amine?",
        back: "NH₃ in ethanol, heated under pressure or in a sealed tube.",
        examPhrasing: "State reagents and conditions to prepare a primary amine from a halogenoalkane.",
        tags: ["primary-amines", "conditions"],
      },
      {
        id: "t34-1-f2",
        noteId: "t34-1",
        difficulty: 1,
        front: "What nitrogen nucleophile makes a secondary amine from RHal?",
        back: "A primary amine (RNH₂), not ammonia.",
        examPhrasing: "Identify the amine reactant used to form a secondary amine from a halogenoalkane.",
        confusionPair: "NH₃ vs RNH₂ for substitution",
        tags: ["secondary-amines"],
      },
      {
        id: "t34-1-f3",
        noteId: "t34-1",
        difficulty: 2,
        front: "Reduce an amide to an amine — reagent?",
        back: "LiAlH₄ (lithium tetrahydridoaluminate(III)).",
        examPhrasing: "Name a reagent that reduces an amide to an amine.",
        tags: ["reduction", "amides"],
      },
      {
        id: "t34-1-f4",
        noteId: "t34-1",
        difficulty: 2,
        front: "Reduce a nitrile to an amine — two allowed methods?",
        back: "LiAlH₄ or H₂ with a nickel catalyst.",
        examPhrasing: "State two ways to reduce a nitrile to a primary amine.",
        tags: ["nitriles", "reduction"],
      },
      {
        id: "t34-1-f5",
        noteId: "t34-1",
        difficulty: 2,
        front: "NH₃ + ethanoyl chloride at room temperature → ?",
        back: "Ethanamide + HCl (primary amide + hydrogen chloride).",
        examPhrasing: "Describe the reaction of ammonia with an acyl chloride at room temperature.",
        tags: ["acyl-chlorides", "amides"],
      },
      {
        id: "t34-1-f6",
        noteId: "t34-1",
        difficulty: 3,
        front: "Why is excess amine used with acyl chlorides?",
        back: "To neutralise HCl formed so the nucleophile is not fully protonated.",
        examPhrasing: "Explain why excess amine is used when an acyl chloride reacts with a primary amine.",
        tags: ["acyl-chlorides", "condensation"],
      },
      {
        id: "t34-1-f7",
        noteId: "t34-1",
        difficulty: 3,
        front: "Why are alkylamine solutions weakly basic?",
        back: "Lone pair on N accepts H⁺ from water, forming RNH₃⁺ and OH⁻; equilibrium lies left.",
        examPhrasing: "Explain the basicity of aqueous amine solutions.",
        tags: ["basicity"],
      },
      {
        id: "t34-1-f8",
        noteId: "t34-1",
        difficulty: 4,
        front: "Mechanism family: halogenoalkane + NH₃ → amine?",
        back: "Nucleophilic substitution.",
        examPhrasing: "State the mechanism by which ammonia converts a halogenoalkane to a primary amine.",
        tags: ["mechanism", "substitution"],
      },
      {
        id: "t34-1-f9",
        noteId: "t34-1",
        difficulty: 4,
        front: "Product: propanoyl chloride + methylamine?",
        back: "N-methylpropanamide (+ HCl).",
        examPhrasing: "Name the organic product when propanoyl chloride reacts with methylamine.",
        tags: ["N-substituted-amides"],
      },
      {
        id: "t34-1-f10",
        noteId: "t34-1",
        difficulty: 5,
        front: "Solvent for halogenoalkane + NH₃ amination in syllabus?",
        back: "Ethanol (not aqueous ammonia as the standard stated medium).",
        examPhrasing: "State a suitable solvent for the reaction of a halogenoalkane with ammonia to form a primary amine.",
        tags: ["conditions", "ethanol"],
      },
    ],
  },
  "t34-2": {
    noteId: "t34-2",
    drills: [
      {
        id: "t34-2-d1",
        noteId: "t34-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Outline the preparation of phenylamine starting from benzene. Include nitration reagents and conditions, reduction reagents for the nitro group, and the final treatment needed to obtain free phenylamine rather than its salt.",
        modelAnswerPoints: [
          "Step 1: Benzene is nitrated with concentrated HNO₃ and concentrated H₂SO₄ under controlled warming to give nitrobenzene.",
          "Step 2: Nitrobenzene is reduced with hot tin and concentrated HCl to give the anilinium salt.",
          "Step 3: NaOH(aq) is added to liberate free phenylamine from the salt.",
          "The alkaline workup is essential because acidic reduction leaves the protonated amine.",
        ],
        workedSolution: [
          "The first stage is electrophilic nitration of benzene using mixed concentrated nitric and concentrated sulfuric acids, with the temperature controlled in the usual laboratory range so that nitrobenzene is obtained without excessive dinitration.",
          "The nitro group is then reduced using hot tin metal with concentrated hydrochloric acid, which is the specific metal/acid combination required by the syllabus for this reduction step and which converts nitrobenzene into protonated phenylamine as an anilinium chloride-type salt in the acidic medium.",
          "Because the product in the acidic mixture is the anilinium ion, aqueous sodium hydroxide must be added to deprotonate the ammonium group and allow neutral phenylamine to be formed and isolated, which is why the NaOH(aq) step is not an optional extra but part of the required sequence.",
          "Overall the route is benzene -> nitrobenzene -> reduction in strong acid to the salt -> basification to phenylamine, linking aromatic substitution with nitro-group reduction and simple acid-base workup chemistry.",
        ],
        commonMistake:
          "Omitting the NaOH(aq) step so the answer stops at the anilinium salt, or using Sn/HCl without stating ‘hot’ conditions.",
        tags: ["phenylamine", "synthesis", "nitration", "reduction"],
      },
      {
        id: "t34-2-d2",
        noteId: "t34-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe the reaction of phenylamine with bromine water at room temperature. State what is observed and name a typical organic product.",
        modelAnswerPoints: [
          "The -NH₂ group strongly activates the ring towards electrophilic attack.",
          "Bromine water is decolourised rapidly at room temperature.",
          "A white precipitate of 2,4,6-tribromophenylamine forms.",
          "No iron(III) bromide catalyst is required (contrast with bromination of benzene).",
        ],
        workedSolution: [
          "Phenylamine contains an amino group attached directly to the benzene ring, and the lone pair on nitrogen donates electron density into the ring by resonance, which greatly increases the electron density at ortho and para positions compared with benzene itself.",
          "When bromine water is added at room temperature, electrophilic substitution occurs very readily, so the orange-brown colour of aqueous bromine disappears quickly as Br⁺-equivalent electrophiles are consumed by the activated ring.",
          "Substitution occurs at both ortho positions and the para position, giving 2,4,6-tribromophenylamine as the classic product name in mark schemes, which appears as a white precipitate under typical test-tube conditions.",
          "Unlike bromination of benzene, this reaction does not require a Lewis-acid catalyst such as FeBr₃ because the ring is already so activated that molecular bromine in water is electrophilic enough on its own at room temperature.",
        ],
        commonMistake:
          "Adding FeBr₃ or describing monobromination as the sole expected outcome without mentioning multiple substitution.",
        tags: ["phenylamine", "bromination", "activation"],
      },
      {
        id: "t34-2-d3",
        noteId: "t34-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Phenylamine is treated with sodium nitrite and dilute hydrochloric acid with the temperature kept below 10 °C. Name the organic intermediate formed. State what organic product is obtained if this intermediate solution is then warmed with water, and explain why the low temperature is important in the first step.",
        modelAnswerPoints: [
          "Below 10 °C, benzenediazonium chloride is formed from phenylamine with nitrous acid generated in situ.",
          "Warming the diazonium salt with water converts it to phenol.",
          "Diazonium salts are unstable at higher temperatures, so the reaction must be kept cold during formation.",
        ],
        workedSolution: [
          "Sodium nitrite with dilute acid generates nitrous acid in the mixture, and below about 10 °C phenylamine reacts with nitrous acid to give a diazonium salt, specifically benzenediazonium chloride when hydrochloric acid is the acid used.",
          "If the cold diazonium solution is subsequently warmed with water, the diazonium group is replaced by a hydroxyl group attached to the ring, which means phenol is produced as the final organic product of that second stage.",
          "The syllabus stresses cooling because diazonium salts decompose if warmed too soon; keeping the temperature below 10 °C during formation allows the benzenediazonium ion to build up in solution long enough for further chemistry rather than undergoing violent loss of nitrogen at room temperature during the diazotisation itself.",
        ],
        commonMistake:
          "Naming phenol as the immediate product of the cold step, or omitting the below-10 °C requirement.",
        tags: ["diazonium", "phenol", "temperature"],
      },
      {
        id: "t34-2-d4",
        noteId: "t34-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Place ammonia, ethylamine and phenylamine in order of decreasing basicity in aqueous solution. Explain the order using inductive effects for the alkylamine and lone-pair delocalisation for phenylamine.",
        modelAnswerPoints: [
          "Order: ethylamine > ammonia > phenylamine.",
          "Ethylamine is stronger than ammonia because the ethyl group donates electron density inductively, increasing lone-pair availability on nitrogen.",
          "Phenylamine is weaker than ammonia because the nitrogen lone pair is delocalised into the benzene ring, reducing availability for protonation.",
        ],
        workedSolution: [
          "In water the basicity order required by the syllabus for these three molecules is ethylamine most basic, ammonia intermediate, and phenylamine least basic, which matches the pattern of measured base strengths for simple aliphatic versus aromatic amines.",
          "Ethylamine is more basic than ammonia because the ethyl substituent releases electron density towards the nitrogen through the σ-bond framework, which increases electron density on nitrogen and stabilises the ethylammonium conjugate acid slightly more relative to the free base than is the case for ammonium versus ammonia.",
          "Phenylamine is less basic than ammonia because the amino lone pair overlaps with the π system of the benzene ring, so electron density is shared with the ring and the lone pair is less localised on nitrogen for protonation, which disfavours complete proton transfer to water compared with ammonia where no aromatic delocalisation of that lone pair occurs.",
        ],
        commonMistake:
          "Claiming phenylamine is more basic than ammonia ‘because it has a benzene ring’, or reversing the ethylamine vs ammonia order.",
        tags: ["basicity", "phenylamine", "ethylamine"],
      },
      {
        id: "t34-2-d5",
        noteId: "t34-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement about forming an azo compound from benzenediazonium chloride is correct for the syllabus example?",
        options: [
          { id: "A", text: "Benzenediazonium chloride couples with phenol in NaOH(aq) to give a coloured azo product." },
          { id: "B", text: "The azo group is –C≡N– linking two benzene rings." },
          { id: "C", text: "Azo compounds are colourless and never used commercially." },
          { id: "D", text: "Coupling requires concentrated HNO₃ and heat with benzene." },
        ],
        correctOptionId: "A",
        explanation:
          "The syllabus requires coupling of benzenediazonium chloride with phenol in alkaline solution; phenoxide is a strong nucleophile and the product is a conjugated azo dye.",
        distractorRationale: {
          B: "The azo linkage is –N=N– between the two fragments, not a nitrile triple bond.",
          C: "Azo dyes are often intensely coloured and widely used as dyes.",
          D: "That describes nitration of benzene, not diazonium coupling.",
        },
        tags: ["azo", "coupling", "dyes"],
      },
      {
        id: "t34-2-d6",
        noteId: "t34-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Why is NaOH(aq) added after reducing nitrobenzene with hot Sn/concentrated HCl in the syllabus route to phenylamine?",
        options: [
          { id: "A", text: "To oxidise any leftover tin to SnO₂ for easier filtration." },
          { id: "B", text: "To deprotonate the anilinium salt and liberate free phenylamine." },
          { id: "C", text: "To nitrate the ring a second time." },
          { id: "D", text: "To convert phenylamine into nitrobenzene." },
        ],
        correctOptionId: "B",
        explanation:
          "Acidic reduction gives the protonated amine; hydroxide removes H⁺ to give neutral phenylamine.",
        distractorRationale: {
          A: "Workup may remove acid, but the learning outcome is about freeing the amine from its salt, not oxidising tin as the main purpose.",
          C: "Nitration is the first step from benzene, not an after-step on the amine.",
          D: "That would be the reverse of the reduction just performed.",
        },
        tags: ["phenylamine", "workup", "acid-base"],
      },
      {
        id: "t34-2-d7",
        noteId: "t34-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which basicity statement is correct for 0.1 mol dm⁻³ aqueous solutions of the three molecules?",
        options: [
          { id: "A", text: "phenylamine > ethylamine > ammonia" },
          { id: "B", text: "ethylamine > ammonia > phenylamine" },
          { id: "C", text: "ammonia > phenylamine > ethylamine" },
          { id: "D", text: "phenylamine > ammonia > ethylamine" },
        ],
        correctOptionId: "B",
        explanation:
          "Alkyl electron donation raises basicity vs NH₃; lone-pair delocalisation into the ring lowers arylamine basicity below NH₃.",
        distractorRationale: {
          A: "Phenylamine is the weakest base of the three, not the strongest.",
          C: "Ethylamine is more basic than ammonia, not less.",
          D: "Phenylamine is weaker than ethylamine and weaker than ammonia.",
        },
        tags: ["basicity", "comparison"],
      },
      {
        id: "t34-2-d8",
        noteId: "t34-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Define the azo group and state two syllabus points linking azo compounds to dyes.",
        modelAnswerPoints: [
          "The azo group is –N=N– between two carbon frameworks (often aromatic).",
          "Benzenediazonium chloride couples with phenol in NaOH(aq) to form an azo compound.",
          "Azo compounds are often used as dyes; other azo dyes can be made by similar coupling routes with different aromatic partners.",
        ],
        workedSolution: [
          "An azo compound contains the azo functional group, which is a nitrogen–nitrogen double bond, –N=N–, linking two substituent fragments, and in the 9701 context those fragments are commonly aromatic rings so that conjugation extends across the whole π system.",
          "The required illustrative reaction is coupling of benzenediazonium chloride with phenol in aqueous sodium hydroxide, where mildly alkaline conditions convert phenol largely to phenoxide, which is a better nucleophile for attack on the terminal nitrogen of the diazonium electrophile.",
          "Such products are often intensely coloured because the extended conjugation shifts π–π* absorption into the visible region, which is why the syllabus states that azo compounds are often used as dyes and that other azo dyes can be prepared by similar diazonium-coupling chemistry with different coupling components.",
        ],
        commonMistake:
          "Identifying the azo group as C=N or omitting the dye / similar-route statements.",
        tags: ["azo", "definitions", "dyes"],
      },
      {
        id: "t34-2-d9",
        noteId: "t34-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Starting from phenylamine only, describe how phenol can be made via a diazonium salt. Your answer should name reagents for diazotisation, state the temperature constraint, and describe the second step with water.",
        modelAnswerPoints: [
          "Treat phenylamine with NaNO₂ and dilute acid (e.g. HCl) below 10 °C to form benzenediazonium chloride.",
          "Warm the diazonium solution with water to hydrolyse/replace the diazonium group.",
          "Phenol is formed as the organic product.",
        ],
        workedSolution: [
          "Phenylamine is first converted to a diazonium salt by reaction with nitrous acid generated in situ from sodium nitrite plus dilute hydrochloric acid, and the temperature must be kept below 10 °C during this diazotisation so that benzenediazonium chloride accumulates without premature thermal decomposition.",
          "Once the diazonium ion is available in cold solution, warming the mixture with water supplies hydroxide from water as nucleophile in the usual examination description and promotes loss of N₂ with formation of a hydroxyl group attached to the former diazonium-bearing carbon.",
          "The overall transformation from phenylamine therefore passes through benzenediazonium chloride as intermediate and delivers phenol as the final organic product after the warm-with-water step, which is the standard examination pathway linking arylamine chemistry to phenol synthesis.",
        ],
        commonMistake:
          "Skipping the cold diazonium formation or suggesting direct hydrolysis of phenylamine without diazotisation.",
        tags: ["phenol", "diazonium", "sequence"],
      },
      {
        id: "t34-2-d10",
        noteId: "t34-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which condition difference best distinguishes bromination of phenylamine from bromination of benzene?",
        options: [
          { id: "A", text: "Phenylamine requires FeBr₃ catalyst and heat; benzene reacts in cold bromine water." },
          { id: "B", text: "Phenylamine reacts rapidly with Br₂(aq) at room temperature without a Lewis-acid catalyst; benzene needs a halogen carrier such as FeBr₃." },
          { id: "C", text: "Both require only Br₂(aq) at room temperature with no catalyst." },
          { id: "D", text: "Benzene reacts in bromine water alone at room temperature while phenylamine does not." },
        ],
        correctOptionId: "B",
        explanation:
          "The amino group strongly activates the ring; benzene is far less reactive and needs electrophilic bromine generated with FeBr₃ (or similar).",
        distractorRationale: {
          A: "That reverses the catalyst requirement: phenylamine is more reactive, not less.",
          C: "Benzene does not undergo fast electrophilic substitution with aqueous bromine alone at room temperature.",
          D: "Benzene does not decolourise bromine water without a catalyst; phenylamine does.",
        },
        tags: ["bromination", "comparison", "benzene"],
      },
    ],
    flashcards: [
      {
        id: "t34-2-f1",
        noteId: "t34-2",
        difficulty: 1,
        front: "Benzene → phenylamine: first step?",
        back: "Nitration: conc. HNO₃ + conc. H₂SO₄ → nitrobenzene.",
        examPhrasing: "State reagents for converting benzene to nitrobenzene.",
        tags: ["nitration"],
      },
      {
        id: "t34-2-f2",
        noteId: "t34-2",
        difficulty: 1,
        front: "Reduce nitrobenzene to anilinium salt?",
        back: "Hot Sn + conc. HCl.",
        examPhrasing: "State reagents and conditions to reduce nitrobenzene in the phenylamine route.",
        tags: ["reduction"],
      },
      {
        id: "t34-2-f3",
        noteId: "t34-2",
        difficulty: 2,
        front: "After Sn/HCl reduction, what frees phenylamine?",
        back: "NaOH(aq) — deprotonates anilinium salt.",
        examPhrasing: "State why NaOH(aq) is used after reduction of nitrobenzene.",
        tags: ["workup"],
      },
      {
        id: "t34-2-f4",
        noteId: "t34-2",
        difficulty: 2,
        front: "Phenylamine + Br₂(aq) at room temperature — product?",
        back: "2,4,6-tribromophenylamine (white precipitate); Br₂ decolourises.",
        examPhrasing: "Describe the reaction of phenylamine with bromine water.",
        tags: ["bromination"],
      },
      {
        id: "t34-2-f5",
        noteId: "t34-2",
        difficulty: 3,
        front: "Diazotise phenylamine — reagents and temperature?",
        back: "NaNO₂ + dilute acid; keep below 10 °C → benzenediazonium chloride.",
        examPhrasing: "State conditions for forming a diazonium salt from phenylamine.",
        tags: ["diazonium"],
      },
      {
        id: "t34-2-f6",
        noteId: "t34-2",
        difficulty: 3,
        front: "Warm benzenediazonium chloride with water → ?",
        back: "Phenol (+ N₂ lost).",
        examPhrasing: "State the product when a benzenediazonium salt is warmed with water.",
        tags: ["phenol"],
      },
      {
        id: "t34-2-f7",
        noteId: "t34-2",
        difficulty: 4,
        front: "Basicity: ethylamine, NH₃, phenylamine — order?",
        back: "ethylamine > ammonia > phenylamine.",
        examPhrasing: "State and explain the relative basicities of ethylamine, ammonia and phenylamine.",
        confusionPair: "phenylamine vs ethylamine",
        tags: ["basicity"],
      },
      {
        id: "t34-2-f8",
        noteId: "t34-2",
        difficulty: 4,
        front: "What is the azo group?",
        back: "–N=N– linking two (often aromatic) fragments.",
        examPhrasing: "Identify the azo functional group.",
        tags: ["azo"],
      },
      {
        id: "t34-2-f9",
        noteId: "t34-2",
        difficulty: 5,
        front: "Required azo coupling example?",
        back: "Benzenediazonium chloride + phenol in NaOH(aq) → azo dye.",
        examPhrasing: "Describe coupling of benzenediazonium chloride with phenol.",
        tags: ["azo", "coupling"],
      },
      {
        id: "t34-2-f10",
        noteId: "t34-2",
        difficulty: 5,
        front: "Why alkaline phenol for azo coupling?",
        back: "Phenoxide is a stronger nucleophile than neutral phenol for attack on diazonium.",
        examPhrasing: "Explain why phenol is used in NaOH(aq) in diazonium coupling.",
        tags: ["azo", "mechanism-concepts"],
      },
    ],
  },
  "t34-3": {
    noteId: "t34-3",
    drills: [
      {
        id: "t34-3-d1",
        noteId: "t34-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "State how ethanamide can be prepared from ethanoyl chloride and ammonia. Include the temperature requirement and name the inorganic by-product.",
        modelAnswerPoints: [
          "React ethanoyl chloride with ammonia at room temperature.",
          "The organic product is ethanamide (primary amide).",
          "Hydrogen chloride is formed as by-product.",
        ],
        workedSolution: [
          "The syllabus lists reaction of an acyl chloride with ammonia at room temperature as a route to a primary amide, so ethanoyl chloride is simply treated with ammonia without heating being a requirement in the specification wording.",
          "The nitrogen of ammonia attacks the electrophilic acyl carbon of ethanoyl chloride, chloride leaves, and the product is ethanamide, CH₃CONH₂, which retains the carbonyl group but now has the amide –CONH₂ linkage.",
          "Because H and Cl are eliminated as HCl when the amide N–H bonds are formed in the usual teaching summary, hydrogen chloride is always the small-molecule by-product alongside the amide in this condensation.",
        ],
        commonMistake:
          "Stating reflux or high temperature; the syllabus emphasises room temperature for acyl chloride + ammonia.",
        tags: ["amides", "acyl-chlorides", "ammonia"],
      },
      {
        id: "t34-3-d2",
        noteId: "t34-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Propanoyl chloride reacts with ethylamine at room temperature. Name the organic product and state how this preparation illustrates the syllabus route from a primary amine and an acyl chloride.",
        modelAnswerPoints: [
          "The product is an N-substituted amide: N-ethylpropanamide.",
          "Primary amine + acyl chloride at room temperature gives an amide with the N–H of ammonia replaced by an alkyl group from the amine.",
          "HCl is formed as by-product.",
        ],
        workedSolution: [
          "When a primary amine reacts with an acyl chloride, the nitrogen that carries the alkyl substituent becomes the amide nitrogen, so propanoyl chloride reacting with ethylamine gives N-ethylpropanamide as the systematic name of the N-substituted amide product.",
          "This is exactly the second preparation route required by the syllabus, parallel to ammonia giving a primary amide, except that the nucleophile is RNH₂ rather than NH₃ so the product is a secondary amide rather than a primary amide in the nitrogen-substitution sense.",
          "Hydrogen chloride is still produced, which is why practical descriptions often mention excess amine to mop up acid, but the core examination point is recognition of the amide functional group in the product and the room-temperature acyl chloride chemistry.",
        ],
        commonMistake:
          "Calling the product an imine or an ester, or naming propanamide when an ethyl group remains on nitrogen.",
        tags: ["N-substituted-amides", "acyl-chlorides"],
      },
      {
        id: "t34-3-d3",
        noteId: "t34-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Describe the hydrolysis of ethanamide with aqueous acid under heating. Name the main organic product and state the form in which the nitrogen fragment appears in acidic solution.",
        modelAnswerPoints: [
          "The amide C–N bond is broken on hydrolysis with aqueous acid and heat.",
          "The main organic product is ethanoic acid.",
          "The nitrogen is converted to ammonium ions, NH₄⁺, in the acidic medium.",
        ],
        workedSolution: [
          "Heating ethanamide with aqueous strong acid provides both H⁺ catalysis and water as nucleophile, so hydrolysis occurs in which the amide linkage between the acyl carbon and nitrogen is cleaved to regenerate carboxylic-acid-level functionality.",
          "The carbonyl-containing fragment from a simple primary amide such as ethanamide becomes ethanoic acid, CH₃COOH, which is the main neutral organic species after appropriate workup, and is what mark schemes expect when they ask for the organic product of acidic amide hydrolysis.",
          "The nitrogen originally in the amide is protonated under the acidic conditions and ends up as ammonium ion, NH₄⁺, rather than free ammonia gas, because the excess acid keeps the basic nitrogen fully protonated in solution during and after hydrolysis of a primary amide.",
        ],
        commonMistake:
          "Stating the product is ethanol or ethanal, or claiming free NH₃ is the main nitrogen species in strong acid.",
        tags: ["hydrolysis", "acid", "amides"],
      },
      {
        id: "t34-3-d4",
        noteId: "t34-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Describe the hydrolysis of ethanamide with aqueous alkali under heating. Name the main organic species in the alkaline mixture and explain briefly how dilute mineral acid could be used afterwards if free ethanoic acid were required.",
        modelAnswerPoints: [
          "Alkaline hydrolysis with heat gives the carboxylate salt (e.g. ethanoate if NaOH is used).",
          "Ammonia is released from the nitrogen side under these conditions.",
          "Adding dilute strong acid protonates ethanoate to ethanoic acid.",
        ],
        workedSolution: [
          "When ethanamide is heated with aqueous sodium hydroxide, hydroxide attacks the carbonyl carbon of the amide and the C–N bond cleaves so that the acyl fragment becomes the ethanoate ion, CH₃COO⁻, which remains in solution as its sodium salt if NaOH was the base used.",
          "The nitrogen fragment leaves as ammonia, NH₃, which can escape from hot alkaline solution or dissolve depending on conditions, but the key syllabus contrast with acid hydrolysis is carboxylate plus ammonia rather than carboxylic acid plus ammonium under acidic conditions.",
          "If the desired isolated product is ethanoic acid itself, the alkaline mixture can be cooled and acidified with dilute hydrochloric or sulfuric acid so that ethanoate is protonated to unionised ethanoic acid, which can then be extracted or distilled according to the practical context of the question.",
        ],
        commonMistake:
          "Saying the alkaline product is ethanoic acid directly, without mentioning the carboxylate salt as the immediate organic product in base.",
        tags: ["hydrolysis", "alkali", "amides"],
      },
      {
        id: "t34-3-d5",
        noteId: "t34-3",
        kind: "mcq",
        difficulty: 2,
        stem: "What is the organic product class when propanamide is reduced with LiAlH₄?",
        options: [
          { id: "A", text: "Propanal" },
          { id: "B", text: "Propylamine (propan-1-amine)" },
          { id: "C", text: "Propanoic acid" },
          { id: "D", text: "Propanenitrile" },
        ],
        correctOptionId: "B",
        explanation:
          "LiAlH₄ reduces the amide carbonyl all the way to the amine; the chain length is unchanged so propanamide → propan-1-amine.",
        distractorRationale: {
          A: "Aldehyde is not the stable product of full amide reduction with LiAlH₄ in the syllabus picture.",
          C: "That would be oxidation or hydrolysis, not LiAlH₄ reduction.",
          D: "Nitrile formation is not the outcome of amide reduction here.",
        },
        tags: ["reduction", "LiAlH4"],
      },
      {
        id: "t34-3-d6",
        noteId: "t34-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Explain why ethanamide is a much weaker Brønsted-Lowry base in water than ethylamine. Your answer must refer to lone-pair availability and resonance in the amide.",
        modelAnswerPoints: [
          "In ethylamine the nitrogen lone pair is localised and readily accepts a proton from water.",
          "In ethanamide the nitrogen lone pair is delocalised onto the adjacent carbonyl group by resonance.",
          "Delocalisation reduces lone-pair availability for protonation, so the amide is a very weak base compared with the amine.",
        ],
        workedSolution: [
          "Ethylamine behaves as a typical weak base because the lone pair on its saturated nitrogen is localised in an sp³-like environment and can attack a proton from a water molecule to give ethylammonium and hydroxide according to the usual base equilibrium.",
          "In ethanamide the nitrogen is bonded directly to a carbonyl carbon, and resonance structures can be drawn in which the nitrogen lone pair forms a π bond to carbon while the carbonyl π bond shifts onto oxygen, which means the true electronic structure is a hybrid where lone-pair density is shared between nitrogen and the carbonyl oxygen.",
          "Because that delocalisation stabilises the lone pair in a bonding interaction with the carbonyl π system, less electron density remains available on nitrogen for independent protonation by water, which makes ethanamide a very poor proton acceptor compared with ethylamine and explains why amides are described in the syllabus as much weaker bases than amines.",
        ],
        commonMistake:
          "Arguing only that oxygen is electronegative without mentioning resonance delocalisation of the nitrogen lone pair.",
        tags: ["basicity", "amide", "resonance"],
      },
      {
        id: "t34-3-d7",
        noteId: "t34-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which 0.1 mol dm⁻³ aqueous solution is expected to have the highest pH at 25 °C?",
        options: [
          { id: "A", text: "CH₃CONH₂ (ethanamide)" },
          { id: "B", text: "CH₃CH₂NH₂ (ethylamine)" },
          { id: "C", text: "CH₃COOH (ethanoic acid)" },
          { id: "D", text: "NaCl(aq)" },
        ],
        correctOptionId: "B",
        explanation:
          "Ethylamine is a weak base (pH > 7). Ethanamide is almost neutral; ethanoic acid is acidic; NaCl is ~7.",
        distractorRationale: {
          A: "Amides are very weak bases; pH stays near neutral.",
          C: "Carboxylic acid solutions are acidic.",
          D: "Neutral salt of strong acid and strong base is about pH 7.",
        },
        tags: ["basicity", "pH"],
      },
      {
        id: "t34-3-d8",
        noteId: "t34-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which temperature condition matches the syllabus for preparing an amide from an acyl chloride and ammonia?",
        options: [
          { id: "A", text: "Room temperature" },
          { id: "B", text: "Reflux at 180 °C" },
          { id: "C", text: "0 °C under UV only" },
          { id: "D", text: "Sealed tube at 150 °C" },
        ],
        correctOptionId: "A",
        explanation:
          "The learning outcome specifies ammonia + acyl chloride at room temperature to give an amide.",
        distractorRationale: {
          B: "Acyl chlorides react vigorously at room temperature; extreme reflux is not the stated condition.",
          C: "UV is irrelevant to this syllabus preparation.",
          D: "Sealed-tube heating belongs to halogenoalkane amination, not this acyl chloride route.",
        },
        tags: ["conditions", "acyl-chlorides"],
      },
      {
        id: "t34-3-d9",
        noteId: "t34-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Contrast the products of complete hydrolysis of N-methylethanamide with (i) aqueous acid and heat and (ii) aqueous alkali and heat. Name the organic acid or salt formed in each case and the nitrogen-containing species produced.",
        modelAnswerPoints: [
          "(i) Acid: ethanoic acid and methylammonium ions (e.g. CH₃NH₃⁺) in solution.",
          "(ii) Alkali: ethanoate salt and methylamine released.",
          "Heating is required for practical hydrolysis rates in both media.",
        ],
        workedSolution: [
          "N-Methylethanamide is a secondary amide, so acidic hydrolysis still cleaves the amide bond to give the carboxylic acid derived from the acyl fragment, which is ethanoic acid, while the nitrogen fragment was originally methylammonia-type attached to the carbonyl and becomes methylammonium, CH₃NH₃⁺, under strongly acidic conditions.",
          "Under alkaline hydrolysis the same acyl fragment appears as ethanoate ion in solution with whatever cation the base provides, such as Na⁺ if sodium hydroxide is used, while the nitrogen side is released as methylamine, CH₃NH₂, which is a weak base and would exist partly protonated or free depending on pH but is named as methylamine in the basic hydrolysis product set.",
          "In both cases the syllabus expects awareness that heating is used to achieve hydrolysis in a reasonable time, and the examination contrast is carboxylic acid plus substituted ammonium in acid versus carboxylate plus amine in alkali for N-substituted amides.",
        ],
        commonMistake:
          "Reporting free methylamine as the main nitrogen species in strong acid, or free ethanoic acid as the direct product in hot alkali without mentioning ethanoate.",
        tags: ["hydrolysis", "N-substituted-amides"],
      },
      {
        id: "t34-3-d10",
        noteId: "t34-3",
        kind: "structured",
        difficulty: 4,
        marks: 4,
        stem: "State why LiAlH₄ reduction of an amide stops at the amine oxidation level rather than removing the nitrogen from the molecule, and name the functional group present in the product.",
        modelAnswerPoints: [
          "LiAlH₄ delivers hydride to the electrophilic acyl carbon of the amide.",
          "Oxygen-bound leaving groups are reduced away until the carbon is attached to nitrogen as in an amine.",
          "The product contains a primary or secondary or tertiary amine functional group depending on the starting amide substitution pattern.",
        ],
        workedSolution: [
          "Lithium tetrahydridoaluminate is a powerful source of nucleophilic hydride that attacks the δ+ carbonyl carbon of an amide in a sequence of addition–elimination steps that progressively remove oxygen-based electronegative substituents while the C–N bond remains intact as a σ bond to nitrogen.",
          "Because the reduction targets the carbonyl π system and oxygen leaving ability rather than cleaving the C–N single bond as hydrolysis would, the nitrogen stays bound to that carbon chain and ends up bonded only to hydrogen and/or alkyl groups as in an amine.",
          "Therefore the functional group after complete reduction is an amine, for example a primary amine is obtained from an unsubstituted amide –CONH₂, whereas a secondary amide gives a secondary amine product, which is the syllabus-level outcome statement about reduction of the carbonyl group in amides to amines.",
        ],
        commonMistake:
          "Claiming the product is still an amide or that nitrogen is lost as N₂.",
        tags: ["reduction", "LiAlH4", "functional-groups"],
      },
    ],
    flashcards: [
      {
        id: "t34-3-f1",
        noteId: "t34-3",
        difficulty: 1,
        front: "Amide from acyl chloride + NH₃ — temperature?",
        back: "Room temperature.",
        examPhrasing: "State conditions for the reaction of ammonia with an acyl chloride to form an amide.",
        tags: ["conditions"],
      },
      {
        id: "t34-3-f2",
        noteId: "t34-3",
        difficulty: 1,
        front: "By-product: acyl chloride + amine?",
        back: "HCl.",
        examPhrasing: "Name the small molecule eliminated when an acyl chloride forms an amide.",
        tags: ["condensation"],
      },
      {
        id: "t34-3-f3",
        noteId: "t34-3",
        difficulty: 2,
        front: "Acid hydrolysis of a primary amide — organic product?",
        back: "Carboxylic acid; nitrogen as NH₄⁺ in acid.",
        examPhrasing: "State the products of hydrolysis of an amide with aqueous acid.",
        tags: ["hydrolysis"],
      },
      {
        id: "t34-3-f4",
        noteId: "t34-3",
        difficulty: 2,
        front: "Alkaline hydrolysis of amide — organic anion?",
        back: "Carboxylate salt; ammonia or amine from N side.",
        examPhrasing: "State the products of hydrolysis of an amide with aqueous alkali.",
        tags: ["hydrolysis"],
      },
      {
        id: "t34-3-f5",
        noteId: "t34-3",
        difficulty: 3,
        front: "Reduce propanamide — reagent and product class?",
        back: "LiAlH₄ → propan-1-amine (amine).",
        examPhrasing: "State the reagent and product when an amide is reduced.",
        tags: ["reduction"],
      },
      {
        id: "t34-3-f6",
        noteId: "t34-3",
        difficulty: 3,
        front: "Why are amides weak bases vs amines?",
        back: "N lone pair delocalised into C=O (resonance); less available for H⁺.",
        examPhrasing: "Explain why amides are much weaker bases than amines.",
        tags: ["basicity", "resonance"],
      },
      {
        id: "t34-3-f7",
        noteId: "t34-3",
        difficulty: 4,
        front: "Ethanoyl chloride + excess NH₃ → ?",
        back: "Ethanamide (+ NH₄Cl if acid is neutralised).",
        examPhrasing: "Name the organic product of ethanoyl chloride with ammonia.",
        tags: ["amides"],
      },
      {
        id: "t34-3-f8",
        noteId: "t34-3",
        difficulty: 4,
        front: "Ethanoyl chloride + ethylamine → ?",
        back: "N-ethylethanamide.",
        examPhrasing: "Name the product when ethanoyl chloride reacts with ethylamine.",
        confusionPair: "primary vs N-substituted amide",
        tags: ["N-substituted-amides"],
      },
      {
        id: "t34-3-f9",
        noteId: "t34-3",
        difficulty: 5,
        front: "Heat needed for amide hydrolysis?",
        back: "Yes — hydrolysis is slow without heating in acid or alkali.",
        examPhrasing: "State whether heating is typically used for amide hydrolysis.",
        tags: ["hydrolysis"],
      },
      {
        id: "t34-3-f10",
        noteId: "t34-3",
        difficulty: 5,
        front: "Get free acid after alkaline hydrolysis?",
        back: "Acidify the carboxylate with dilute strong acid.",
        examPhrasing: "Describe how to obtain a carboxylic acid after alkaline amide hydrolysis.",
        tags: ["workup"],
      },
    ],
  },
  "t34-4": {
    noteId: "t34-4",
    drills: [
      {
        id: "t34-4-d1",
        noteId: "t34-4",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Define the isoelectric point of an amino acid and explain what is meant by a zwitterion for a simple α-amino acid in aqueous solution.",
        modelAnswerPoints: [
          "The isoelectric point (pI) is the pH at which the amino acid has zero net charge (no net movement in an electric field).",
          "A zwitterion carries both positive and negative formal charges in the same molecule.",
          "For α-amino acids this is commonly –NH₃⁺ and –COO⁻ on the same species.",
        ],
        workedSolution: [
          "The isoelectric point is defined as the pH value at which the average net charge on the amino acid is zero, which in electrophoresis means the species does not drift systematically toward either electrode because there is no overall excess of positive or negative charge at that pH.",
          "A zwitterion is a molecule that contains separate positively charged and negatively charged sites simultaneously, which sounds contradictory until one remembers that those charges are on different atoms within one molecular framework.",
          "For a simple α-amino acid dissolved in water near neutral pH, internal proton transfer between the carboxylic acid group and the amino group often produces a zwitterionic form written with –NH₃⁺ on nitrogen and –COO⁻ on the carboxylate oxygen, which is the canonical illustration used when examination questions ask for zwitterion structures.",
        ],
        commonMistake:
          "Defining pI as the pH where the molecule has no charges at all, rather than no net charge.",
        tags: ["zwitterion", "isoelectric-point", "definitions"],
      },
      {
        id: "t34-4-d2",
        noteId: "t34-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "An amino acid has isoelectric point pI = 6.0. Predict whether it exists mainly as a net cation, a net anion, or has approximately zero net charge at (i) pH 3.0, (ii) pH 6.0, and (iii) pH 9.0. Justify each answer by comparing pH to pI.",
        modelAnswerPoints: [
          "(i) pH < pI: net positive charge (predominantly cationic form).",
          "(ii) pH = pI: net charge approximately zero (zwitterion dominates).",
          "(iii) pH > pI: net negative charge (predominantly anionic form).",
        ],
        workedSolution: [
          "At pH 3.0 the solution is more acidic than the isoelectric point, so excess protons shift equilibria toward protonated amino groups and unionised or less deprotonated carboxylic acid character, which overall leaves the amino acid carrying more positive than negative charge and therefore behaving as a net cation.",
          "At pH 6.0, equal to the stated pI, the acid–base equilibria balance so that the average net charge is zero, which is exactly the condition used to define the isoelectric point and corresponds to the zwitterionic representation being the dominant conceptual form.",
          "At pH 9.0 the solution is more basic than the isoelectric point, so deprotonation of the carboxylic acid group is essentially complete while the amino group is largely unprotonated, giving an excess of negative over positive charge and therefore a net anionic amino acid species overall.",
        ],
        commonMistake:
          "Reversing the pH > pI and pH < pI assignments for net charge sign.",
        tags: ["isoelectric-point", "charge", "pH"],
      },
      {
        id: "t34-4-d3",
        noteId: "t34-4",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe how two α-amino acid molecules join to form a dipeptide. Identify the new linkage formed and name the small molecule eliminated.",
        modelAnswerPoints: [
          "The carboxyl group of one amino acid reacts with the amino group of another.",
          "An amide (peptide) bond forms between the residues.",
          "Water is eliminated in the condensation.",
        ],
        workedSolution: [
          "In peptide formation the electrophilic carbonyl carbon of one amino acid’s carboxylic acid group is attacked by the nucleophilic lone pair on the nitrogen of the amino group of a second amino acid, after suitable activation in biochemical contexts but at syllabus level the key idea is condensation between –COOH and –NH₂.",
          "The resulting linkage is an amide bond between the two amino-acid-derived fragments, which is what biochemists call a peptide bond and what organic chemists still classify as an amide functional group within the chain.",
          "Because the OH of the acid and an H from the amine combine to leave as a water molecule, the overall process is a condensation reaction, and a dipeptide contains exactly one such peptide bond connecting two residue units.",
        ],
        commonMistake:
          "Calling the peptide bond an ester or saying no small molecule is lost.",
        tags: ["dipeptide", "peptide-bond", "condensation"],
      },
      {
        id: "t34-4-d4",
        noteId: "t34-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "How many peptide (amide) bonds are present in a linear tripeptide formed from three different α-amino acids? Explain your counting in terms of how many condensation steps link the residues.",
        modelAnswerPoints: [
          "A tripeptide contains two peptide bonds.",
          "Three residues require two linkages between adjacent pairs in the chain.",
          "Each peptide bond arises from one condensation between a carboxyl and an amino group.",
        ],
        workedSolution: [
          "A tripeptide is a single chain containing three amino-acid residues in sequence, and between residue 1 and residue 2 there is one peptide bond, and between residue 2 and residue 3 there is a second peptide bond, while the free N-terminus of residue 1 and free C-terminus of residue 3 are not involved in inter-residue amide links.",
          "Therefore the number of peptide bonds equals the number of residues minus one, which is three minus one equals two for a tripeptide.",
          "Each of those bonds was formed by a condensation that eliminated water, so two condensations are required to stitch three monomers into one continuous peptide backbone under the idealised stepwise picture used in teaching.",
        ],
        commonMistake:
          "Answering three peptide bonds, confusing bond count with residue count.",
        tags: ["tripeptide", "peptide-bond"],
      },
      {
        id: "t34-4-d5",
        noteId: "t34-4",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best describes amino acids?",
        options: [
          { id: "A", text: "They are only acids because they contain –COOH." },
          { id: "B", text: "They are amphoteric: they can act as acids or bases because they contain both –COOH and –NH₂ groups." },
          { id: "C", text: "They are only bases because they contain nitrogen." },
          { id: "D", text: "They cannot form internal salts in water." },
        ],
        correctOptionId: "B",
        explanation:
          "Both terminal groups ionise; amino acids react as acids (donate H⁺ from –COOH or –NH₃⁺) and as bases (accept H⁺ at –NH₂ or –COO⁻ context).",
        distractorRationale: {
          A: "They also have a basic amino group; behaviour is amphoteric.",
          C: "The carboxyl group provides acidic character as well.",
          D: "Zwitterions are internal salt forms in water.",
        },
        tags: ["amphoteric", "definitions"],
      },
      {
        id: "t34-4-d6",
        noteId: "t34-4",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "In electrophoresis at constant pH, state where a net positively charged amino-acid species moves relative to the electrodes, where a net negatively charged species moves, and where a species with zero net charge is observed. Use the terms anode and cathode.",
        modelAnswerPoints: [
          "Net positive species (cations) migrate toward the cathode (negative electrode).",
          "Net negative species (anions) migrate toward the anode (positive electrode).",
          "Species with zero net charge show little net migration and remain near the origin.",
        ],
        workedSolution: [
          "Electrophoresis applies an electric field across a supporting medium, and any ion carrying overall positive charge experiences a force toward the negative electrode, which is called the cathode, so proton-excess forms of amino acids drift that way when the buffer pH is below their isoelectric points.",
          "Conversely, species whose average charge is negative, such as deprotonated carboxylate-rich forms at pH above the isoelectric point, are attracted toward the positive electrode, which is the anode, because opposite charges attract in the usual electrostatic picture.",
          "If the amino acid’s average net charge is zero at the buffer pH, which occurs when pH equals the isoelectric point for a simple amino acid without charged side chains, then there is no directional driving force and the band stays close to the point of application rather than migrating strongly toward either electrode.",
        ],
        commonMistake:
          "Sending cations to the anode or anions to the cathode.",
        tags: ["electrophoresis", "electrodes"],
      },
      {
        id: "t34-4-d7",
        noteId: "t34-4",
        kind: "mcq",
        difficulty: 3,
        stem: "A mixture is run at pH 7.0. Species X has pI = 5.0 and species Y has pI = 9.0. Which prediction is correct?",
        options: [
          { id: "A", text: "X moves toward the cathode; Y moves toward the anode." },
          { id: "B", text: "X moves toward the anode; Y moves toward the cathode." },
          { id: "C", text: "Both X and Y move toward the anode." },
          { id: "D", text: "Neither X nor Y moves because pH is 7." },
        ],
        correctOptionId: "B",
        explanation:
          "pH 7 > pI of X → net negative → anode. pH 7 < pI of Y → net positive → cathode.",
        distractorRationale: {
          A: "That reverses the directions for anion and cation.",
          C: "Y is net positive at pH 7, so it should not go to the anode.",
          D: "Neither pI equals 7, so both have net charge at pH 7.",
        },
        tags: ["electrophoresis", "pI"],
      },
      {
        id: "t34-4-d8",
        noteId: "t34-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain in qualitative terms how an α-amino acid can behave as an acid and as a base in aqueous solution, referring to which groups donate or accept protons.",
        modelAnswerPoints: [
          "As an acid: –COOH can donate H⁺ to base (or –NH₃⁺ can donate H⁺ at low pH).",
          "As a base: –NH₂ (or –COO⁻) can accept H⁺.",
          "This dual behaviour makes amino acids amphoteric.",
        ],
        workedSolution: [
          "An α-amino acid contains a carboxylic acid group, which can donate a proton to water or to another base, which is the sense in which the molecule behaves as a Brønsted-Lowry acid, most obviously through deprotonation of –COOH to –COO⁻.",
          "The same molecule also contains an amino group, whose nitrogen lone pair can accept a proton from hydronium or from another acid source, which is Brønsted-Lowry basic behaviour, giving –NH₃⁺ when protonated.",
          "Because both modes are accessible depending on pH, amino acids are classified as amphoteric, and in water they typically exist as equilibria among cationic, zwitterionic and anionic forms rather than as a single fixed charge state across all pH values.",
        ],
        commonMistake:
          "Describing only zwitterion formation with no mention of acid or base role of specific groups.",
        tags: ["amphoteric", "acid-base"],
      },
      {
        id: "t34-4-d9",
        noteId: "t34-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A buffer at pH 6.5 is used for electrophoresis of alanine (pI ≈ 6.0) and lysine (pI ≈ 9.5). Predict the net charge sign of each amino acid at this pH and the direction of migration (anode vs cathode). Ignore detailed side-chain chemistry beyond the pI values given.",
        modelAnswerPoints: [
          "For alanine, pH > pI so net negative charge → migrates toward the anode.",
          "For lysine, pH < pI so net positive charge → migrates toward the cathode.",
          "The two species therefore separate in opposite directions along the field.",
        ],
        workedSolution: [
          "For alanine with isoelectric point about 6.0, a buffer pH of 6.5 is slightly more basic than the pI, which shifts deprotonation equilibria toward the carboxylate form relative to the isoelectric balance, so the molecule carries a small excess negative charge overall and behaves as an anion in the electric field.",
          "Anionic species in electrophoresis move toward the positive electrode, which is the anode, so alanine’s band migrates in the anode direction under these conditions.",
          "For lysine with pI about 9.5, the buffer at 6.5 is much more acidic than the pI, which means both terminal groups and side-chain basic sites are predominantly protonated relative to the isoelectric state, giving net positive charge overall, so lysine behaves as a cation and migrates toward the negative electrode, the cathode.",
          "Therefore at pH 6.5 alanine and lysine move in opposite directions, which is how electrophoresis can separate amino acids that differ in isoelectric point even when the conceptual treatment is kept at the pH-versus-pI comparison level required by the syllabus.",
        ],
        commonMistake:
          "Using the same migration direction for both because both are ‘amino acids’.",
        tags: ["electrophoresis", "pI", "separation"],
      },
      {
        id: "t34-4-d10",
        noteId: "t34-4",
        kind: "mcq",
        difficulty: 2,
        stem: "How many peptide bonds are in a fully formed linear tripeptide?",
        options: [
          { id: "A", text: "1" },
          { id: "B", text: "2" },
          { id: "C", text: "3" },
          { id: "D", text: "4" },
        ],
        correctOptionId: "B",
        explanation:
          "n residues in a linear chain have n − 1 peptide bonds; for n = 3, there are 2 bonds.",
        distractorRationale: {
          A: "That would be only a dipeptide linkage count if one bond were missing.",
          C: "Three residues do not imply three inter-residue peptide bonds.",
          D: "Four bonds would exceed the maximum possible for three residues.",
        },
        tags: ["tripeptide", "peptide-bond"],
      },
    ],
    flashcards: [
      {
        id: "t34-4-f1",
        noteId: "t34-4",
        difficulty: 1,
        front: "What is a zwitterion (amino acid context)?",
        back: "Same molecule with + and − sites, e.g. –NH₃⁺ and –COO⁻.",
        examPhrasing: "Define a zwitterion for an amino acid.",
        tags: ["zwitterion"],
      },
      {
        id: "t34-4-f2",
        noteId: "t34-4",
        difficulty: 1,
        front: "Define isoelectric point (pI).",
        back: "pH at which the amino acid has zero net charge.",
        examPhrasing: "State what is meant by the isoelectric point of an amino acid.",
        tags: ["isoelectric-point"],
      },
      {
        id: "t34-4-f3",
        noteId: "t34-4",
        difficulty: 2,
        front: "pH < pI — net charge?",
        back: "Net positive (cationic).",
        examPhrasing: "Predict the net charge of an amino acid when pH is below its pI.",
        tags: ["charge"],
      },
      {
        id: "t34-4-f4",
        noteId: "t34-4",
        difficulty: 2,
        front: "pH > pI — net charge?",
        back: "Net negative (anionic).",
        examPhrasing: "Predict the net charge when pH is above the pI.",
        tags: ["charge"],
      },
      {
        id: "t34-4-f5",
        noteId: "t34-4",
        difficulty: 3,
        front: "Dipeptide formation — small molecule lost?",
        back: "Water (condensation).",
        examPhrasing: "State the small molecule eliminated when amino acids form a peptide bond.",
        tags: ["peptide-bond"],
      },
      {
        id: "t34-4-f6",
        noteId: "t34-4",
        difficulty: 3,
        front: "Tripeptide — number of peptide bonds?",
        back: "Two.",
        examPhrasing: "State how many peptide bonds are in a tripeptide.",
        confusionPair: "bonds vs residues",
        tags: ["tripeptide"],
      },
      {
        id: "t34-4-f7",
        noteId: "t34-4",
        difficulty: 4,
        front: "Cations in electrophoresis move toward…?",
        back: "Cathode (negative electrode).",
        examPhrasing: "State the electrode toward which a positively charged amino acid migrates.",
        tags: ["electrophoresis"],
      },
      {
        id: "t34-4-f8",
        noteId: "t34-4",
        difficulty: 4,
        front: "Anions in electrophoresis move toward…?",
        back: "Anode (positive electrode).",
        examPhrasing: "State the electrode toward which a negatively charged species migrates.",
        tags: ["electrophoresis"],
      },
      {
        id: "t34-4-f9",
        noteId: "t34-4",
        difficulty: 5,
        front: "At pH = pI, migration?",
        back: "Little net movement; stays near origin.",
        examPhrasing: "Describe electrophoretic behaviour at the isoelectric point.",
        tags: ["isoelectric-point", "electrophoresis"],
      },
      {
        id: "t34-4-f10",
        noteId: "t34-4",
        difficulty: 5,
        front: "Amphoteric means?",
        back: "Can act as acid (donate H⁺) or base (accept H⁺) — amino acids do both.",
        examPhrasing: "Explain why amino acids are described as amphoteric.",
        tags: ["amphoteric"],
      },
    ],
  },
};
