import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 35 — Polymers (35.1–35.3): course subtopics `t35-1` … `t35-3`.
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §35.1–35.3;
 * `data/courses/chemistry-9701.json`):
 *
 * **t35-1 (35.1)** — polyester from diol + dicarboxylic acid / dioyl chloride; polyester from
 * hydroxycarboxylic acid; polyamide from diamine + dicarboxylic acid / dioyl chloride;
 * polyamide from aminocarboxylic acid / amino acids; deduce repeat unit; identify monomer(s)
 * from a polymer section → d1–d10.
 *
 * **t35-2 (35.2)** — predict polymerisation type from monomer(s); deduce type from a polymer
 * fragment → d1–d10.
 *
 * **t35-3 (35.3)** — poly(alkenes) inert / hard to biodegrade; photodegradation; polyesters
 * and polyamides biodegradable by acidic and alkaline hydrolysis → d1–d10.
 */
export const CHEMISTRY_TOPIC35_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t35-1": {
    noteId: "t35-1",
    drills: [
      {
        id: "t35-1-d1",
        noteId: "t35-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define condensation polymerisation and explain how it differs from addition polymerisation in terms of monomer functionality and whether a small molecule is eliminated when each new link forms in the chain.",
        modelAnswerPoints: [
          "Condensation polymerisation is the formation of a polymer by repeated reactions between monomers that are typically bifunctional (or multifunctional), with each new backbone link formed together with elimination of a small molecule such as H2O or HCl.",
          "Addition polymerisation involves monomers with carbon–carbon multiple bonds (commonly alkenes) where chain growth occurs by opening the multiple bond without elimination of a small molecule at each propagation step.",
          "Condensation polymers characteristically contain heteroatom links such as ester or amide groups in the chain backbone, whereas many addition polymers have an all-carbon (or largely carbon) backbone derived from the former double-bond carbons.",
        ],
        workedSolution: [
          "Condensation polymerisation means building a long-chain polymer by a sequence of stepwise reactions in which monomer units join through new covalent bonds to the growing chain while a small molecule such as water or hydrogen chloride is expelled whenever a new link is created.",
          "The monomers that take part are usually chosen so that each can react at two (or more) sites, for example a diol with two hydroxyl groups or a dicarboxylic acid with two carboxylic acid groups, because that is what allows the chain to keep extending rather than stopping after one coupling event.",
          "Addition polymerisation, by contrast, is the process in which unsaturated monomers such as alkenes add to one another across the π bond so that the polymer backbone grows by converting C=C units into C–C single bonds along the chain, and there is no stoichiometric elimination of H2O or HCl each time a monomer adds.",
          "Therefore the key distinction required at A Level is not merely that a long molecule forms, but whether each propagation step is accompanied by loss of a small molecule from pairs of functional groups (condensation) or proceeds by π-bond opening without such elimination (addition).",
        ],
        commonMistake:
          "Describing any polymer-forming reaction as condensation simply because two monomers are used, while ignoring elimination of H2O/HCl or the presence of ester/amide links.",
        tags: ["definitions", "condensation", "addition", "polymerisation"],
      },
      {
        id: "t35-1-d2",
        noteId: "t35-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Describe how a polyester forms when ethane-1,2-diol reacts with hexane-1,6-dicarboxylic acid. State the class of polymer formed, the type of covalent link that repeats in the backbone, and the small molecule eliminated at each ester-forming step. Explain briefly why both monomers must be bifunctional for a high relative molecular mass polymer to build up.",
        modelAnswerPoints: [
          "A polyester forms because each alcohol group can react with a carboxylic acid group to create an ester linkage along the chain.",
          "The repeating backbone linkage is the ester group, –COO– (or –C(=O)–O–), formed between diol-derived oxygen and acid-derived carbonyl carbon.",
          "The small molecule eliminated per ester link formed under direct acid/alcohol condensation is H2O.",
          "Bifunctionality is required so that each monomer can become incorporated with unused reactive sites still available for further condensation, allowing chain growth in two directions rather than stopping after a single coupling.",
        ],
        workedSolution: [
          "When ethane-1,2-diol is heated with hexane-1,6-dicarboxylic acid under conditions that favour esterification, each hydroxyl group of the diol can react with a carboxyl group of the dicarboxylic acid to form an ester linkage, and because there are two hydroxyls per diol molecule and two carboxylic acid groups per dicarboxylic acid molecule, the reaction can repeat many times.",
          "The product is classified as a polyester because the polymer backbone contains repeating ester functional groups, meaning the characteristic link that is propagated along the chain is the ester –COO– unit derived from condensation between alcohol and carboxylic acid functionalities.",
          "Whenever a new ester link is formed by direct esterification between the alcohol and acid groups shown in the syllabus context, the atoms removed as a separate small molecule correspond to H2O, so water is eliminated at each condensation step rather than HCl.",
          "If either partner were only monofunctional, for example a monoalcohol with the diacid, esterification would cap one end of the growing chain without providing a second alcohol site on that monomer to continue propagation, so high Mr polymer could not develop; bifunctional diol and dicarboxylic acid monomers retain two reactive sites each, which is what permits extensive linear growth.",
        ],
        commonMistake:
          "Stating that HCl is eliminated when a dicarboxylic acid reacts with a diol, or calling the product a polyamide.",
        tags: ["polyester", "diol", "dicarboxylic-acid", "ester", "water"],
      },
      {
        id: "t35-1-d3",
        noteId: "t35-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Ethane-1,2-diol is polymerised with ethanedioyl dichloride (dioyl chloride) to form a polyester. Which small molecule is eliminated when each new ester link forms in the chain?",
        options: [
          { id: "A", text: "H2O only." },
          { id: "B", text: "HCl only." },
          { id: "C", text: "CO2 only." },
          { id: "D", text: "No small molecule; the process is addition polymerisation." },
        ],
        correctOptionId: "B",
        explanation:
          "Acyl chlorides react with alcohols to form esters with elimination of HCl at each linkage. Water is the by-product when a dicarboxylic acid is used, not when a dioyl chloride is used.",
        distractorRationale: {
          A: "Water is eliminated when a carboxylic acid condenses with an alcohol, but a dioyl chloride provides –COCl groups, so HCl is lost instead.",
          C: "Decarboxylation is not the standard elimination step for diol + dioyl chloride polyester formation.",
          D: "Chain growth still proceeds by condensation chemistry with loss of HCl, not by alkene-style addition without elimination.",
        },
        tags: ["polyester", "dioyl-chloride", "elimination"],
      },
      {
        id: "t35-1-d4",
        noteId: "t35-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "6-Hydroxyhexanoic acid, HO–(CH2)5–COOH, can polymerise without a second monomer type. Name the class of polymer produced, identify the linkage that repeats in the backbone, state the small molecule eliminated per link, and explain why a single monomer is sufficient in this case.",
        modelAnswerPoints: [
          "The polymer class is polyester (lactone-type / hydroxy-acid polyester route in general terms: self-condensation of a hydroxycarboxylic acid).",
          "The repeating linkage is an ester, –COO–, formed between the hydroxyl group of one monomer unit and the carboxylic acid group of another.",
          "H2O is eliminated for each new ester link when the monomer supplies both –OH and –COOH.",
          "One monomer suffices because it is bifunctional with two complementary groups in the same molecule, so it can self-condense to extend the chain.",
        ],
        workedSolution: [
          "6-Hydroxyhexanoic acid contains both an alcohol group and a carboxylic acid group within the same molecule, so it belongs to the class of hydroxycarboxylic acids that the syllabus treats as monomers capable of forming polyesters by self-condensation.",
          "During polymerisation, the –OH group of one molecule reacts with the –COOH group of another to create an ester linkage in the growing chain, so the repeating backbone functional unit is an ester group, –COO–, rather than an amide.",
          "Each time such an ester link is formed by condensation between alcohol and carboxylic acid functionalities, the elements of water are eliminated, so H2O is the small molecule lost per linking step under the usual direct condensation picture.",
          "A second monomer type is not required because each monomer molecule already carries the two different functional groups that must react together; after one esterification event the oligomer still possesses terminal hydroxyl and carboxylic acid sites that can continue the same condensation chemistry, which is why chain growth can proceed to high Mr from a single monomer species.",
        ],
        commonMistake:
          "Classifying the product as a polyamide because the monomer contains oxygen and hydrogen, or claiming HCl elimination for a carboxylic acid route.",
        tags: ["hydroxycarboxylic-acid", "polyester", "self-condensation"],
      },
      {
        id: "t35-1-d5",
        noteId: "t35-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Hexane-1,6-diamine reacts with hexane-1,6-dioic acid (adipic acid) to form a polymer. Identify the polymer class, name the repeating linkage in the backbone, state the small molecule eliminated when each new link forms, and write one word equation in terms of functional groups (for example diamine + dicarboxylic acid -> polyamide + ?).",
        modelAnswerPoints: [
          "The polymer is a polyamide (nylon-type chemistry in general terms).",
          "The repeating linkage is an amide, –CONH– (peptide-type link between carbonyl carbon and nitrogen).",
          "H2O is eliminated per amide bond formed from amine + carboxylic acid condensation.",
          "Word picture: diamine + dicarboxylic acid -> polyamide + H2O.",
        ],
        workedSolution: [
          "Hexane-1,6-diamine supplies two primary amine groups and adipic acid supplies two carboxylic acid groups, which is exactly the monomer pairing syllabus uses for polyamide formation by condensation between amine and carboxylic acid functionalities.",
          "Each successful coupling between an –NH2 group and a –COOH group creates an amide linkage, –CONH–, so the polymer is classified as a polyamide and the chain backbone contains repeating amide functional groups analogous to peptide bonds.",
          "Because the carboxylic acid component is not an acyl chloride, the condensation step that forms the amide link proceeds with elimination of water, corresponding to the usual amide formation picture from amine plus carboxylic acid under suitable conditions.",
          "In summary, the overall transformation can be described in words as diamine plus dicarboxylic acid giving a polyamide with water as the by-product at each condensation event, which is the small-molecule signature that distinguishes this route from the dioyl chloride route.",
        ],
        commonMistake:
          "Calling the product a polyester, or claiming HCl elimination when both monomers are the acid and amine forms rather than acyl chloride.",
        tags: ["polyamide", "diamine", "dicarboxylic-acid", "water"],
      },
      {
        id: "t35-1-d6",
        noteId: "t35-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Hexane-1,6-diamine reacts with hexanedioyl dichloride, ClOC–(CH2)4–COCl, to form a polymer under laboratory conditions. Name the polymer class, identify the small molecule eliminated per amide link formed, and explain why this elimination product differs from that in the reaction of the same diamine with hexane-1,6-dioic acid.",
        modelAnswerPoints: [
          "The product is a polyamide because amide links form between amine and acyl chloride groups.",
          "HCl is eliminated per link when an amino group attacks an acyl chloride carbonyl with loss of chloride as HCl overall.",
          "With a dicarboxylic acid, –COOH provides –OH for water loss, whereas an acyl chloride provides Cl^- departure, so HCl is lost instead of H2O.",
        ],
        workedSolution: [
          "When a diamine reacts with a dioyl chloride, each nucleophilic attack of a primary amine on an acyl chloride carbonyl leads to substitution at the carbonyl carbon with departure of chloride ion and formation of an amide linkage, so the growing polymer is a polyamide with repeating –CONH– units along the chain.",
          "The overall stoichiometry at each condensation step is consistent with elimination of hydrogen chloride, because the elements lost to the gas phase or acid–base work-up correspond to H+ together with Cl^- arising from the acyl chloride functional group rather than OH from a carboxylic acid.",
          "If the same diamine were instead condensed with hexane-1,6-dioic acid, the amide would be formed from –NH2 and –COOH with elimination of water, because the leaving group attached to the carbonyl carbon in that case is the hydroxyl-derived fragment that departs as part of H2O.",
          "Therefore the identity of the small molecule eliminated is a direct consequence of whether the electrophilic acyl component is supplied as a carboxylic acid (H2O loss) or as an acyl chloride (HCl loss), even though both routes yield a polyamide.",
        ],
        commonMistake:
          "Stating that water is eliminated when an acyl chloride is the acylating agent, or confusing acyl chloride reactivity with anhydride formation.",
        tags: ["polyamide", "dioyl-chloride", "elimination", "HCl"],
      },
      {
        id: "t35-1-d7",
        noteId: "t35-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "The amino acid glycine, H2N–CH2–COOH, can polymerise to form a polypeptide. State the polymer class from the syllabus perspective for condensation polymers of amino acids, describe the linkage that repeats between monomer residues, name the small molecule eliminated per link, and explain in one sentence how this chemistry relates amino acids to the wider polyamide family.",
        modelAnswerPoints: [
          "Condensation polymerisation of amino acids produces a polyamide (polypeptide / protein polymer in living systems).",
          "The repeating linkage is the amide (peptide) bond between the carbonyl carbon of one residue and the nitrogen of the next.",
          "H2O is eliminated when the amino group of one unit condenses with the carboxylic acid group of another.",
          "Amino acids are therefore α-aminocarboxylic acids that self-condense by the same amide-forming principle as diamine + diacid routes.",
        ],
        workedSolution: [
          "Glycine possesses both a primary amino group and a carboxylic acid group on the same two-carbon framework, so it is an amino acid in the precise sense used for Topic 35: a monomer that can undergo condensation polymerisation to give a polyamide.",
          "When many glycine molecules join in a head-to-tail fashion, each new connection forms an amide linkage between the carbonyl carbon of one monomer unit and the nitrogen atom of the next, which is what is meant chemically by a peptide bond in the resulting polypeptide.",
          "Every time such a peptide bond forms by condensation between –NH2 and –COOH on different monomer units, the elements of water are eliminated, so H2O is the small molecule lost per propagation step in the idealised condensation picture.",
          "This shows that amino-acid polymerisation is not a separate exotic mechanism but a member of the same condensation polymerisation family as nylon formation, because the backbone repeat chemistry is still amide formation from complementary nitrogen-containing and carboxyl-derived functionalities.",
        ],
        commonMistake:
          "Calling the product a polyester, or suggesting addition polymerisation across a non-existent C=C bond in glycine.",
        tags: ["amino-acids", "polyamide", "peptide", "condensation"],
      },
      {
        id: "t35-1-d8",
        noteId: "t35-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Hexane-1,6-diamine reacts with hexane-1,6-dioic acid to give a nylon-6,6-type polyamide. Deduce the repeat unit of the polymer chain: start from one amide link formed between the two monomers, show the atoms that belong to the repeating fragment, and indicate continuation bonds at both ends of the repeat unit in the usual examination style.",
        modelAnswerPoints: [
          "One repeat unit contains one diamine-derived –NH–(CH2)6–NH– fragment combined with one diacid-derived –CO–(CH2)4–CO– fragment after amide formation (six-carbon diamine and six-carbon diacid in the classic nylon-6,6 monomer pair).",
          "The minimal repeating segment along the chain corresponds to …–NH–(CH2)6–NH–CO–(CH2)4–CO–… with amide links at each carbonyl–nitrogen junction between residues.",
          "Continuation bonds are shown at both ends of the repeat bracket to show extension of the chain.",
        ],
        workedSolution: [
          "Hexane-1,6-diamine has the form H2N–(CH2)6–NH2 and hexane-1,6-dioic acid has the form HOOC–(CH2)4–COOH, so when an amide bond forms between the amine at one end of a diamine unit and a carboxylic acid group of a diacid unit, the nitrogen of the amide link is still attached to the six-carbon diamine backbone while the carbonyl carbon of the amide is part of the adipoyl-derived fragment.",
          "Along an extended chain, each complete cycle of repeat chemistry can be summarised as incorporating one six-carbon diamine portion and one six-carbon diacid portion per turn of the repeat pattern, which is why the commercial name nylon-6,6 records both six-carbon monomer blocks even though the diacid chain shown here is written as four methylenes between carbonyls in the linear acid formula.",
          "A standard way to display the repeat unit is to bracket a backbone segment such as –NH–(CH2)6–NH–CO–(CH2)4–CO– with outward-facing continuation bonds on the nitrogen and on the terminal carbonyl of the bracketed fragment, making clear that further identical repeats attach through further amide links.",
          "The essential chemical point examiners credit is that the repeat unit must contain both the amide linkage pattern and the correct relative counts of chain atoms supplied by each monomer class, with continuation bonds not accidentally closed into a small ring unless a cyclic lactam case is intended.",
        ],
        commonMistake:
          "Drawing a repeat unit that omits continuation bonds, or swapping the methylene counts so the diacid and diamine contributions are inconsistent with the stated monomers.",
        tags: ["repeat-unit", "polyamide", "nylon"],
      },
      {
        id: "t35-1-d9",
        noteId: "t35-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A section of a polymer chain can be represented as …–O–CH2–CH2–O–CO–(CH2)4–CO–O–CH2–CH2–O–CO–(CH2)4–CO–… . Identify the class of condensation polymer, name the two monomer types from which it is most directly formed, and state the small molecule eliminated when each ester link is made using those monomer classes in their carboxylic acid forms.",
        modelAnswerPoints: [
          "The backbone contains ester links, so the polymer is a polyester.",
          "The ether–oxygen–containing fragment derives from a diol (here ethane-1,2-diol).",
          "The dicarbonyl fragment with four CH2 groups between carbonyls derives from a dicarboxylic acid such as hexane-1,6-dioic acid (adipic acid).",
          "With carboxylic acid monomers, H2O is eliminated per ester formed.",
        ],
        workedSolution: [
          "Inspection of the fragment shows alternating oxygen bridges typical of diol residues, –O–CH2–CH2–O–, and dicarbonyl segments, –CO–(CH2)4–CO–, which are joined through ester functional groups because each diol oxygen is bonded to a carbonyl-derived carbon in an ester arrangement.",
          "Therefore the polymer must be a polyester formed by condensation polymerisation rather than a polyamide, since there are no amide –NH–CO– units in the backbone sequence shown.",
          "The diol monomer that matches the –O–CH2–CH2–O– repeat spacing is ethane-1,2-diol, HO–CH2–CH2–OH, while the dicarboxylic acid monomer that matches the –CO–(CH2)4–CO– fragment is hexane-1,6-dioic acid, HOOC–(CH2)4–COOH, which is the adipic acid skeleton.",
          "When ester links are formed directly from alcohol and carboxylic acid functionalities, each condensation step eliminates water, so H2O is the small molecule lost for each new ester linkage in this diol plus dicarboxylic acid route.",
        ],
        commonMistake:
          "Identifying a polyamide because nitrogen appears absent yet inventing an amine, or naming a hydroxycarboxylic acid as the sole monomer when the fragment clearly alternates diol and diacid residues.",
        tags: ["identify-monomers", "polyester", "diol", "dicarboxylic-acid"],
      },
      {
        id: "t35-1-d10",
        noteId: "t35-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which monomer pair is incapable, on its own, of forming a high relative molecular mass linear polyester by repeated condensation in the sense required in the syllabus (two bifunctional partners that can each extend the chain)?",
        options: [
          { id: "A", text: "Ethane-1,2-diol and benzene-1,4-dicarboxylic acid." },
          { id: "B", text: "Methanol and benzene-1,4-dicarboxylic acid." },
          { id: "C", text: "6-Hydroxyhexanoic acid as the only monomer." },
          { id: "D", text: "Ethane-1,2-diol and ethanedioyl dichloride." },
        ],
        correctOptionId: "B",
        explanation:
          "Methanol is monofunctional (one –OH), so it cannot propagate a polyester chain with a dicarboxylic species; it esterifies once and caps the chain. The other options use bifunctional monomers or a single bifunctional hydroxy acid.",
        distractorRationale: {
          A: "Both monomers are bifunctional, so alternating diol and diacid condensation can extend to high Mr.",
          C: "A single hydroxycarboxylic acid is bifunctional in two different groups, so self-condensation can give a polyester.",
          D: "Diol plus dioyl chloride is a standard bifunctional pair for polyester formation with HCl elimination.",
        },
        tags: ["bifunctionality", "polyester", "monomers"],
      },
    ],
    flashcards: [
      {
        id: "t35-1-f1",
        noteId: "t35-1",
        difficulty: 1,
        front: "What small molecules are commonly eliminated in condensation polymerisation at A Level?",
        back: "Typically H2O (alcohol + carboxylic acid or amine + carboxylic acid) or HCl (alcohol or amine + acyl chloride).",
        examPhrasing: "State a small molecule eliminated during condensation polymerisation.",
        tags: ["condensation", "elimination"],
      },
      {
        id: "t35-1-f2",
        noteId: "t35-1",
        difficulty: 1,
        front: "What linkage repeats in a polyester backbone?",
        back: "The ester link, –COO– (carbonyl linked through oxygen to the chain).",
        examPhrasing: "Name the functional group that repeats in a polyester.",
        tags: ["polyester", "ester"],
      },
      {
        id: "t35-1-f3",
        noteId: "t35-1",
        difficulty: 2,
        front: "What linkage repeats in a polyamide backbone?",
        back: "The amide (peptide) link, –CONH–.",
        examPhrasing: "Identify the repeating linkage in a polyamide formed from a diamine and a dicarboxylic acid.",
        confusionPair: "ester vs amide in polymer backbone",
        tags: ["polyamide", "amide"],
      },
      {
        id: "t35-1-f4",
        noteId: "t35-1",
        difficulty: 2,
        front: "How can a polyester be made from only one monomer type?",
        back: "Use a hydroxycarboxylic acid (–OH and –COOH in one molecule) so the monomer self-condenses with H2O loss.",
        examPhrasing: "Describe formation of a polyester from a hydroxycarboxylic acid.",
        tags: ["hydroxycarboxylic-acid", "polyester"],
      },
      {
        id: "t35-1-f5",
        noteId: "t35-1",
        difficulty: 3,
        front: "Diamine + dioyl chloride: what is eliminated?",
        back: "HCl at each amide link formed from –NH2 and –COCl.",
        examPhrasing: "State the small molecule eliminated when a diamine reacts with a dioyl chloride.",
        tags: ["polyamide", "acyl-chloride", "HCl"],
      },
      {
        id: "t35-1-f6",
        noteId: "t35-1",
        difficulty: 3,
        front: "How do amino acids fit into Topic 35 polymer classes?",
        back: "They are aminocarboxylic acids that condense to polyamides (polypeptides) with peptide (amide) links and H2O elimination.",
        examPhrasing: "Explain how amino acids form condensation polymers.",
        tags: ["amino-acids", "polyamide"],
      },
      {
        id: "t35-1-f7",
        noteId: "t35-1",
        difficulty: 4,
        front: "Why must step-growth monomers usually be at least difunctional?",
        back: "So each coupling still leaves reactive sites that can continue the chain; monofunctional reagents cap the chain.",
        examPhrasing: "Explain the need for bifunctional monomers in condensation polymerisation.",
        tags: ["bifunctionality", "concepts"],
      },
      {
        id: "t35-1-f8",
        noteId: "t35-1",
        difficulty: 4,
        front: "First step when deducing monomers from a polymer segment?",
        back: "Identify ester vs amide links, then split at those bonds and restore H2O or HCl to recover monomer functional groups.",
        examPhrasing: "Outline how to identify monomers from part of a condensation polymer chain.",
        tags: ["deduction", "repeat-unit"],
      },
      {
        id: "t35-1-f9",
        noteId: "t35-1",
        difficulty: 5,
        front: "Diol + dicarboxylic acid vs diol + dioyl chloride: elimination difference?",
        back: "Diacid route eliminates H2O; dioyl chloride route eliminates HCl; both give polyesters.",
        examPhrasing: "Compare polyester formation from a dicarboxylic acid and from a dioyl chloride.",
        confusionPair: "H2O vs HCl elimination",
        tags: ["polyester", "elimination"],
      },
      {
        id: "t35-1-f10",
        noteId: "t35-1",
        difficulty: 5,
        front: "What does a repeat unit show at its ends in exam diagrams?",
        back: "Continuation bonds through the bracketed fragment so the pattern extends indefinitely along the chain.",
        examPhrasing: "Explain how a polymer repeat unit is displayed in structural answers.",
        tags: ["repeat-unit", "diagrams"],
      },
    ],
  },

  "t35-2": {
    noteId: "t35-2",
    drills: [
      {
        id: "t35-2-d1",
        noteId: "t35-2",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Propene, CH3–CH=CH2, is polymerised under suitable conditions to give poly(propene). Predict whether the polymerisation is addition or condensation, justify your answer by reference to the monomer’s bonding and whether a small molecule is eliminated at each propagation step, and name the general structural feature of the polymer backbone that supports your classification.",
        modelAnswerPoints: [
          "Addition polymerisation is predicted.",
          "The monomer contains a C=C bond that opens during propagation without elimination of H2O or HCl at each step.",
          "The backbone is essentially a saturated carbon chain derived from former alkene carbons, not a sequence of ester or amide links formed by condensation between difunctional groups.",
        ],
        workedSolution: [
          "Propene is a simple alkene monomer, so the polymerisation pathway taught for alkenes at A Level is addition polymerisation in which many propene molecules add together by breaking the π component of the carbon–carbon double bond.",
          "Each propagation event incorporates the three-carbon skeleton of one propene unit into the growing chain without stoichiometric loss of a small molecule such as water or hydrogen chloride, which is the key contrast with condensation polymerisation between, for example, diols and diacids.",
          "The product poly(propene) therefore has a backbone made mainly of single carbon–carbon bonds carrying methyl side groups from the monomer, rather than a backbone threaded with ester or amide heteroatom links that would signal condensation chemistry.",
          "Because classification is decided both by monomer structure (π bond available for addition) and by mechanism-level elimination behaviour (no small molecule eliminated per monomer add), the correct prediction for propene is unambiguously addition polymerisation under the usual free-radical or coordination conditions implied by the question.",
        ],
        commonMistake:
          "Calling alkene polymerisation condensation because many monomers join, or inventing H2O elimination for propene.",
        tags: ["addition", "alkene", "prediction"],
      },
      {
        id: "t35-2-d2",
        noteId: "t35-2",
        kind: "mcq",
        difficulty: 2,
        stem: "For which monomer is condensation polymerisation (with elimination of a small molecule when each new backbone link forms) the appropriate classification?",
        options: [
          { id: "A", text: "Ethene, CH2=CH2." },
          { id: "B", text: "6-Aminohexanoic acid, H2N–(CH2)5–COOH." },
          { id: "C", text: "Chloroethene, CH2=CHCl." },
          { id: "D", text: "Tetrafluoroethene, CF2=CF2." },
        ],
        correctOptionId: "B",
        explanation:
          "6-Aminohexanoic acid has –NH2 and –COOH in one molecule, so it self-condenses to a polyamide with H2O elimination. The alkenes polymerise by addition without such elimination.",
        distractorRationale: {
          A: "Ethene polymerises by π-bond opening in addition polymerisation; no H2O/HCl per step.",
          C: "Chloroethene gives poly(chloroethene) by addition across C=C.",
          D: "Tetrafluoroethene forms PTFE by addition polymerisation of the double bond.",
        },
        tags: ["prediction", "condensation", "aminocarboxylic-acid"],
      },
      {
        id: "t35-2-d3",
        noteId: "t35-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Ethane-1,2-diol is mixed with benzene-1,4-dicarboxylic acid (terephthalic acid) under conditions suitable for esterification. Predict the polymerisation type, name the polymer class formed, and state the small molecule eliminated whenever a new ester link is created. Give one sentence linking your prediction to monomer functional groups.",
        modelAnswerPoints: [
          "Condensation polymerisation is predicted.",
          "A polyester is formed from diol + dicarboxylic acid.",
          "H2O is eliminated per ester link from –OH and –COOH groups.",
          "Both monomers are bifunctional with complementary groups that condense rather than adding across C=C.",
        ],
        workedSolution: [
          "Neither monomer possesses a polymerisable carbon–carbon double bond of the alkene type; instead the diol supplies two hydroxyl groups and terephthalic acid supplies two carboxylic acid groups, which is the standard monomer pairing for stepwise esterification that can extend into a macromolecule.",
          "Because each esterification event between alcohol and carboxylic acid eliminates water, the overall process is classified as condensation polymerisation, and the macromolecular product belongs to the polyester family with repeating ester links along the chain.",
          "The small molecule eliminated whenever a new ester linkage is formed in this acid plus alcohol route is therefore H2O, corresponding to removal of the elements of water from the reacting –OH and –COOH groups.",
          "The prediction follows directly from functional-group recognition: bifunctional alcohol and bifunctional carboxylic acid partners undergo condensation with elimination, which is never the mechanism used for simple alkene addition polymerisation.",
        ],
        commonMistake:
          "Predicting addition polymerisation because the aromatic ring contains π bonds unrelated to chain propagation.",
        tags: ["polyester", "condensation", "prediction"],
      },
      {
        id: "t35-2-d4",
        noteId: "t35-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A polymer fragment has the repeating pattern –CH2–CHCl–CH2–CHCl– along the backbone with chlorine atoms as side substituents on every second carbon. Deduce the polymerisation type that produced this chain and identify the monomer. Explain how you would distinguish this case from a polyester segment in a single sentence of structural reasoning.",
        modelAnswerPoints: [
          "Addition polymerisation is deduced.",
          "The backbone is a saturated carbon chain without ester or amide heteroatom links.",
          "The monomer is chloroethene, CH2=CHCl.",
          "A polyester would show –COO– repeat units in the backbone, which are absent here.",
        ],
        workedSolution: [
          "The fragment shows a simple repeating two-carbon motif –CH2–CHCl– joined end to end, which is exactly the repeat pattern expected after addition polymerisation of chloroethene in which each monomer unit adds across its carbon–carbon double bond to become a two-carbon backbone segment bearing a chlorine substituent on the former CHCl carbon.",
          "There are no ester –COO– or amide –CONH– groups embedded in the backbone sequence as written, so the polymer cannot have been built by condensation between diol/diacid or diamine/diacid monomers under the usual Topic 35 picture.",
          "Reintroducing a double bond across one repeat boundary recovers the monomer CH2=CHCl, which is chloroethene (vinyl chloride), confirming both the monomer identity and the addition mechanism.",
          "If this were a polyester segment, you would expect to see periodic oxygen atoms incorporated into ester carbonyl–oxygen–alkyl arrangements along the main chain, not a continuous hydrocarbon-style backbone with only halogen side groups.",
        ],
        commonMistake:
          "Claiming condensation because chlorine is present, or misreading the repeat as a four-carbon monomer without resetting unsaturation.",
        tags: ["deduction", "addition", "chloroethene"],
      },
      {
        id: "t35-2-d5",
        noteId: "t35-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Hexane-1,6-diamine is reacted with hexane-1,6-dioic acid to give a polyamide. Predict the polymerisation type and justify the prediction using both elimination behaviour and the functional groups involved. Contrast this case in one sentence with polymerisation of ethene.",
        modelAnswerPoints: [
          "Condensation polymerisation is predicted.",
          "Amide links form between –NH2 and –COOH with H2O elimination.",
          "Ethene polymerises by addition across C=C without such elimination.",
        ],
        workedSolution: [
          "The monomer pair is a diamine and a dicarboxylic acid, which is the textbook combination for nylon-type polyamide formation in which each new backbone link is an amide group created by nucleophilic acyl substitution between amine and carboxylic acid functionalities under suitable dehydration conditions.",
          "Because each amide-forming step removes the elements of water from the reacting –NH2 and –COOH groups, the polymerisation must be classified as condensation polymerisation rather than addition polymerisation.",
          "This contrasts sharply with ethene, where monomers join by opening a π bond between two sp2 carbons and no water or hydrogen chloride is stoichiometrically eliminated each time a monomer adds to the radical or ionic chain end.",
          "Therefore the prediction for the diamine plus diacid system follows both from the chemical identity of the links formed (amide) and from the obligatory small-molecule elimination signature of condensation step growth.",
        ],
        commonMistake:
          "Predicting addition for any ‘double bond’ imagined in the acid or confusing dehydration with alkene addition.",
        tags: ["polyamide", "condensation", "prediction"],
      },
      {
        id: "t35-2-d6",
        noteId: "t35-2",
        kind: "mcq",
        difficulty: 2,
        stem: "A polymer backbone contains repeating ester functional groups along the chain. Which statement about the polymerisation that formed it is correct?",
        options: [
          { id: "A", text: "The polymer was formed by addition polymerisation of an alkene diester." },
          { id: "B", text: "The polymer was formed by condensation polymerisation with elimination of a small molecule such as H2O or HCl when each ester link was created." },
          { id: "C", text: "The polymer must have been formed from a single alkene monomer without elimination." },
          { id: "D", text: "Ester groups in the backbone prove the monomer was ethyl ethanoate only." },
        ],
        correctOptionId: "B",
        explanation:
          "Repeating ester links in the main chain indicate condensation polyester formation with small-molecule elimination at each linkage, from routes such as diol + dicarboxylic derivative or hydroxycarboxylic acid self-condensation.",
        distractorRationale: {
          A: "Simple alkene addition does not thread ester links into the backbone in the syllabus sense; ester repeats signal condensation step growth.",
          C: "Addition from one alkene gives a hydrocarbon-style backbone without periodic ester carbonyl–oxygen–chain patterns.",
          D: "Many monomer combinations can give polyesters; the repeat pattern does not fix the monomer to ethyl ethanoate.",
        },
        tags: ["deduction", "polyester", "condensation"],
      },
      {
        id: "t35-2-d7",
        noteId: "t35-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A copolymer is prepared from propenenitrile, CH2=CH–CN, and propenoic acid, CH2=CH–COOH, by a route in which only the carbon–carbon double bonds react. Predict the polymerisation type and explain why the presence of two different monomers does not, by itself, imply condensation polymerisation.",
        modelAnswerPoints: [
          "Addition (copolymerisation) is predicted if only C=C bonds react.",
          "Chain growth occurs by π-bond opening without elimination of H2O/HCl per step.",
          "Two monomers can still add in alternating or random fashion in addition copolymerisation.",
        ],
        workedSolution: [
          "Both monomers contain polymerisable carbon–carbon double bonds carrying different substituents, a nitrile group in propenenitrile and a carboxylic acid group in propenoic acid, but the question specifies that propagation occurs exclusively through reaction at those double bonds.",
          "Under that constraint, each propagation event adds a three-carbon unit across the former π bond without requiring loss of water or hydrogen chloride as part of the chain-forming step, which is the defining kinetic picture for addition copolymerisation.",
          "Therefore the correct classification is addition polymerisation (copolymerisation), even though two distinct monomer types are present, because the count of monomer species is not what distinguishes addition from condensation; elimination behaviour and the nature of the new backbone bonds do.",
          "If, instead, the carboxylic acid were to condense with an alcohol on another monomer with elimination of water, you would be in a condensation scenario, but that is explicitly ruled out here by the statement that only the C=C units react.",
        ],
        commonMistake:
          "Assuming ‘two monomers’ always means condensation step growth, or ignoring the question’s constraint about which bonds react.",
        tags: ["copolymer", "addition", "prediction"],
      },
      {
        id: "t35-2-d8",
        noteId: "t35-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A monomer has the structure CH2=CH–CH2OH. Explain why its molecular formula alone does not force a unique prediction between addition polymerisation and condensation polymerisation. State what extra evidence would let you decide in an examination context.",
        modelAnswerPoints: [
          "The monomer contains both a C=C bond (suggesting possible addition) and an –OH group (allowing possible condensation if paired with a suitable carbonyl partner).",
          "Without conditions or product structure, both pathways are chemically conceivable in principle.",
          "Decisive evidence includes stated reaction conditions, which bonds react, or the polymer fragment showing saturated C–C backbone only versus ester/amide links.",
        ],
        workedSolution: [
          "The monomer contains a carbon–carbon double bond, which is the structural prerequisite taught for addition polymerisation of alkenes, so one legitimate prediction in isolation is that the molecule could add across that double bond to give a polymer with a carbon backbone carrying a –CH2OH side group on every repeat unit if propagation occurs at the π bond.",
          "The same monomer also possesses a primary alcohol group, which means that, in a different chemical context, it could in principle participate in condensation chemistry with appropriate partners such as dicarboxylic acids or dioyl chlorides to form ester links, or even intramolecular reactions in other topics, so condensation routes cannot be ruled out from the formula alone without further information.",
          "Because two different polymerisation classes are suggested by different parts of the same structure, the molecular formula or skeletal diagram by itself does not uniquely determine which polymerisation type occurs.",
          "What is required in an exam-style answer is either explicit information about which functional groups react under the stated conditions, or structural evidence from the polymer produced, such as a backbone containing repeating ester groups implying condensation, versus a backbone consistent only with opened C=C units implying addition.",
        ],
        commonMistake:
          "Picking addition polymerisation with no mention of the alcohol, or asserting condensation without a second functional partner or product evidence.",
        tags: ["borderline", "prediction", "reasoning"],
      },
      {
        id: "t35-2-d9",
        noteId: "t35-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which polymer fragment is strongest evidence for condensation polymerisation rather than simple alkene addition polymerisation?",
        options: [
          { id: "A", text: "–CH2–CH(CH3)–CH2–CH(CH3)–" },
          { id: "B", text: "–CH2–CH2–CH2–CH2–" },
          { id: "C", text: "–NH–(CH2)6–NH–CO–(CH2)4–CO–" },
          { id: "D", text: "–CF2–CF2–CF2–CF2–" },
        ],
        correctOptionId: "C",
        explanation:
          "The sequence contains amide (peptide-type) linkages between nitrogen and carbonyl-derived segments, which arise from condensation between amine and carboxylic acid / acyl chloride functionalities. The other repeats are consistent with addition polymer backbones.",
        distractorRationale: {
          A: "This repeat matches poly(propene) from addition polymerisation of propene.",
          B: "A simple carbon chain repeat suggests poly(ethene)-type addition chemistry.",
          D: "A fluorocarbon backbone repeat indicates addition polymerisation of a fluoroalkene.",
        },
        tags: ["deduction", "polyamide", "fragment"],
      },
      {
        id: "t35-2-d10",
        noteId: "t35-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "2-Hydroxypropanoic acid (lactic acid), CH3–CH(OH)–COOH, is polymerised to give a biodegradable polyester (polylactic acid, PLA). Predict the polymerisation type, name the linkage that repeats in the backbone, and state the small molecule eliminated per link. Contrast this with polymerisation of pure propene under typical conditions.",
        modelAnswerPoints: [
          "Condensation polymerisation is predicted.",
          "Repeating ester links form in the backbone.",
          "H2O is eliminated when –OH and –COOH groups on different monomer units react.",
          "Propene polymerises by addition across C=C without such elimination.",
        ],
        workedSolution: [
          "Lactic acid contains both a secondary alcohol group and a carboxylic acid group within one molecule, so it is a hydroxycarboxylic acid monomer of the type syllabus uses for self-condensation to polyesters.",
          "When many lactic acid molecules join head-to-tail through esterification between alcohol and acid sites on different units, the polymer backbone contains repeating ester functional groups, which is why the product is classified chemically as a polyester.",
          "Each esterification step between carboxylic acid and alcohol functionalities eliminates water, so the polymerisation is condensation polymerisation with H2O as the small molecule lost per new ester link in the direct condensation description.",
          "Propene, by contrast, has no carboxylic acid or alcohol group involved in chain formation under typical polymerisation conditions; it adds across its double bond to give poly(propene), which is addition polymerisation without stoichiometric water elimination at each propagation step.",
        ],
        commonMistake:
          "Classifying lactic acid polymerisation as addition because it is a carbon-chain polymer, while ignoring ester link formation.",
        tags: ["PLA", "hydroxycarboxylic-acid", "condensation", "contrast"],
      },
    ],
    flashcards: [
      {
        id: "t35-2-f1",
        noteId: "t35-2",
        difficulty: 1,
        front: "Quick test: C=C monomer, no condensation groups used — type?",
        back: "Addition polymerisation (π-bond opening, no H2O/HCl per step).",
        examPhrasing: "Predict the polymerisation type for an alkene monomer.",
        tags: ["addition", "prediction"],
      },
      {
        id: "t35-2-f2",
        noteId: "t35-2",
        difficulty: 1,
        front: "What backbone features point to condensation polymerisation?",
        back: "Repeating ester (–COO–) or amide (–CONH–) links formed with small-molecule elimination.",
        examPhrasing: "Deduce polymerisation type from a polymer fragment containing ester links.",
        tags: ["deduction", "condensation"],
      },
      {
        id: "t35-2-f3",
        noteId: "t35-2",
        difficulty: 2,
        front: "Two different monomers — always condensation?",
        back: "No: two alkenes can copolymerise by addition if growth is by C=C opening.",
        examPhrasing: "Explain why two monomers do not automatically imply condensation polymerisation.",
        confusionPair: "two monomers vs condensation",
        tags: ["copolymer", "concepts"],
      },
      {
        id: "t35-2-f4",
        noteId: "t35-2",
        difficulty: 2,
        front: "Diol + dicarboxylic acid — type and linkage?",
        back: "Condensation polymerisation; polyester with ester repeats; H2O lost.",
        examPhrasing: "Predict the polymerisation type for ethane-1,2-diol and terephthalic acid.",
        tags: ["polyester", "prediction"],
      },
      {
        id: "t35-2-f5",
        noteId: "t35-2",
        difficulty: 3,
        front: "How to deduce monomer from –CH2–CHX– repeat?",
        back: "Treat as addition polymer of CH2=CHX; reintroduce C=C across the repeat boundary.",
        examPhrasing: "Deduce the monomer from a section of an addition polymer backbone.",
        tags: ["deduction", "addition"],
      },
      {
        id: "t35-2-f6",
        noteId: "t35-2",
        difficulty: 3,
        front: "Aminocarboxylic acid alone — polymerisation type?",
        back: "Condensation to polyamide; peptide/amide links; H2O elimination.",
        examPhrasing: "Predict the polymerisation type for 6-aminohexanoic acid.",
        tags: ["aminocarboxylic-acid", "condensation"],
      },
      {
        id: "t35-2-f7",
        noteId: "t35-2",
        difficulty: 4,
        front: "Monomer has both C=C and –OH — safe one-line rule?",
        back: "No single rule: use stated conditions or product structure to see whether C=C adds or functional groups condense.",
        examPhrasing: "Explain why CH2=CHCH2OH does not fix one polymerisation type without further evidence.",
        tags: ["borderline", "reasoning"],
      },
      {
        id: "t35-2-f8",
        noteId: "t35-2",
        difficulty: 4,
        front: "Lactic acid polymer — addition or condensation?",
        back: "Condensation (self-esterification) polyester; H2O lost; ester repeats.",
        examPhrasing: "Classify polymerisation of 2-hydroxypropanoic acid to PLA.",
        tags: ["PLA", "polyester"],
      },
      {
        id: "t35-2-f9",
        noteId: "t35-2",
        difficulty: 5,
        front: "Deduction order for an unknown polymer fragment?",
        back: "Look for ester/amide in backbone -> condensation; saturated C–C only -> likely addition; then reconstruct monomer(s).",
        examPhrasing: "Describe how to deduce polymerisation type from a displayed polymer section.",
        tags: ["method", "deduction"],
      },
      {
        id: "t35-2-f10",
        noteId: "t35-2",
        difficulty: 5,
        front: "Ester in side chain only vs ester in backbone?",
        back: "Topic classification hinges on how the chain grows: backbone ester repeats imply condensation polyester; side-chain esters can occur on addition polymers but the syllabus fragment tests usually target backbone links.",
        examPhrasing: "Why are ester links in the main chain important for deducing condensation polymerisation?",
        tags: ["deduction", "backbone"],
      },
    ],
  },

  "t35-3": {
    noteId: "t35-3",
    drills: [
      {
        id: "t35-3-d1",
        noteId: "t35-3",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Explain why many poly(alkenes) such as poly(ethene) are described as chemically inert and are therefore difficult to biodegrade. Refer to the types of bonds present in the backbone and to why enzymes and aqueous hydrolysis routes are relatively ineffective.",
        modelAnswerPoints: [
          "The backbone is largely non-polar C–C and C–H single bonds with high bond enthalpies.",
          "There are no hydrolysable ester or amide links in the carbon-chain backbone of simple poly(alkenes).",
          "Biodegradation depends on chemical pathways microorganisms can catalyse; inert hydrocarbon backbones resist enzymatic cleavage under typical environmental conditions.",
        ],
        workedSolution: [
          "Poly(ethene) is built from many ethene units joined by strong carbon–carbon single bonds along the main chain, with carbon–hydrogen bonds completing the valencies of the backbone carbons, so the overall structure is a non-polar hydrocarbon polymer with very high kinetic stability toward nucleophiles and water.",
          "Because the backbone does not contain repeating ester or amide functional groups of the kind that are easily attacked by acid- or enzyme-catalysed hydrolysis, there is no facile hydrolytic ‘zipper’ along the chain comparable to polyester or polyamide degradation.",
          "Microorganisms that biodegrade natural materials often rely on oxidase or hydrolase chemistry targeted at polar functional groups or ester links; a saturated polyolefin offers few such handles, so biodegradation in ambient soil or marine environments is usually extremely slow even if mechanical fragmentation occurs.",
          "That chemical inertness is exactly why examination answers describe many poly(alkenes) as difficult to biodegrade: the dominant backbone bonds are not the hydrolysable heteroatom links syllabus contrasts later in the same topic.",
        ],
        commonMistake:
          "Claiming that poly(ethene) has ester links, or that C–C bonds hydrolyse easily in neutral water without special chemistry.",
        tags: ["polyalkenes", "inert", "biodegradation"],
      },
      {
        id: "t35-3-d2",
        noteId: "t35-3",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe what is meant by photodegradation of a polymer and outline a simple mechanistic picture in terms of light-initiated bond breaking. State one limitation of relying on photodegradation as a complete solution to plastic litter compared with full biodegradation.",
        modelAnswerPoints: [
          "Photodegradation is breakdown initiated or driven by light, often UV, causing bond cleavage or radical chemistry.",
          "Absorbed photons can generate radicals that weaken the chain (chain scission), lowering Mr and mechanical strength.",
          "It may only fragment the material into smaller pieces rather than fully mineralise it, so persistence as microplastics remains a concern.",
        ],
        workedSolution: [
          "Photodegradation means that electromagnetic radiation, particularly ultraviolet light with enough energy per photon, is absorbed by chromophoric groups or impurities in the polymer and initiates chemical reactions that break covalent bonds in the macromolecule.",
          "A common teaching-level description is that radicals formed after homolytic bond cleavage propagate further reactions along the chain, leading to chain scission so that fewer monomer units remain connected in each molecule and the plastic becomes brittle.",
          "Even when photodegradation succeeds in reducing the size of objects exposed on the surface, the process does not automatically guarantee conversion of all carbon in the polymer to carbon dioxide and water on a short timescale, because many pathways stop at oxidised oligomers or small plastic fragments.",
          "Therefore photodegradation is not equivalent to complete benign biodegradation in every environment: buried litter may see little UV, and surface photodegradation can still leave persistent small particles unless further biological or chemical breakdown occurs.",
        ],
        commonMistake:
          "Equating photodegradation with full microbial mineralisation, or ignoring that buried plastics may not see UV.",
        tags: ["photodegradation", "UV", "environment"],
      },
      {
        id: "t35-3-d3",
        noteId: "t35-3",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain why polyesters are more susceptible than simple poly(alkenes) to chemical breakdown under acidic aqueous conditions. Identify the linkage attacked and name the broad classes of organic products formed after extensive acid-catalysed hydrolysis of a polyester made from a diol and a dicarboxylic acid.",
        modelAnswerPoints: [
          "Polyesters contain ester carbonyls that can be protonated and attacked by water (acid-catalysed hydrolysis).",
          "Cleavage regenerates carboxylic acid and alcohol functional groups from the monomer residues.",
          "Poly(alkene) backbones lack these hydrolysable ester links, so acid hydrolysis is far less effective there.",
        ],
        workedSolution: [
          "In a polyester, the backbone is stitched together by ester functional groups, each of which contains an electrophilic carbonyl carbon bonded to an oxygen that is also part of the ether-type linkage to the diol-derived fragment, and acid catalysis increases the electrophilicity of that carbonyl carbon by protonation of the carbonyl oxygen.",
          "Water can therefore act as a nucleophile at the acyl carbon under acidic conditions, leading stepwise to cleavage of ester links so that long chains are converted into shorter fragments and ultimately into molecules bearing free carboxylic acid groups from the original diacid residues and alcohol groups from the diol residues.",
          "That mechanism is simply not available across the main chain of a poly(ethene)-type material, where connectivity is dominated by non-polar carbon–carbon bonds that are not labile to the same mild acid-catalysed hydrolysis chemistry.",
          "Hence polyesters are recognised in the syllabus as polymers that can be degraded by acidic hydrolysis because their defining functional links are chemically vulnerable in a way alkene-addition backbones are not.",
        ],
        commonMistake:
          "Saying the C–C backbone of polyesters hydrolyses first, or giving amine products from polyester hydrolysis.",
        tags: ["polyester", "acid-hydrolysis", "ester"],
      },
      {
        id: "t35-3-d4",
        noteId: "t35-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Describe the outcome of treating a polyester with hot aqueous sodium hydroxide until the polymer chain is fully cleaved at ester links. Name the linkage broken, identify the nucleophile, and state the broad classes of organic products, paying attention to the ionic form of the acid-derived fragment under alkaline conditions.",
        modelAnswerPoints: [
          "Ester links in the backbone are hydrolysed.",
          "Hydroxide ion acts as nucleophile in saponification-type chemistry.",
          "Products include an alcohol (or diol-derived alcohol fragments) and carboxylate salts (not free carboxylic acids at high pH).",
        ],
        workedSolution: [
          "Under alkaline conditions, hydroxide ion attacks the carbonyl carbon of an ester linkage in the polyester backbone in the textbook saponification mechanism, leading to tetrahedral intermediate formation and expulsion of the alkoxide fragment derived from the former alcohol side of the ester.",
          "Because the reaction is conducted in excess aqueous sodium hydroxide, any carboxylic acid groups that would momentarily form from the acyl portion of each ester are immediately deprotonated to carboxylate ions, so the stable organic products from the acid-derived monomer fragments are carboxylate salts rather than neutral acids.",
          "The fragments that came from the diol portion of the polyester appear as alcohols or multiply hydroxylated species depending on structure, but the key syllabus contrast is that base hydrolysis of esters yields carboxylate salts plus alcohols, whereas acid hydrolysis yields carboxylic acids plus alcohols.",
          "Repeating this cleavage along the entire chain converts the macromolecule into small soluble species, which is why alkaline hydrolysis is one of the chemical routes by which polyesters can be broken down more readily than inert polyolefins.",
        ],
        commonMistake:
          "Stating that neutral carboxylic acids are the final organic products from alkaline ester hydrolysis, or omitting OH^- as nucleophile.",
        tags: ["polyester", "alkaline-hydrolysis", "carboxylate"],
      },
      {
        id: "t35-3-d5",
        noteId: "t35-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Polyamides contain repeating amide links in the backbone. Explain why they can be degraded by acidic hydrolysis and state the broad classes of organic products formed after complete hydrolysis of a simple polyamide derived from a diamine and a dicarboxylic acid under strongly acidic aqueous conditions.",
        modelAnswerPoints: [
          "Amide carbonyls can be protonated, making the carbonyl carbon more electrophilic toward water attack.",
          "Hydrolysis cleaves –CONH– links to regenerate amine-derived and carboxylic-acid-derived fragments.",
          "Products are a diamine (often as ammonium-type species under strong acid) and dicarboxylic acid (protonated acid forms possible).",
        ],
        workedSolution: [
          "An amide linkage contains a carbonyl group bonded to nitrogen, and in acid solution the carbonyl oxygen or the amide nitrogen can be protonated, which activates the carbonyl carbon toward nucleophilic attack by water in the hydrolysis mechanism.",
          "Successive hydrolysis events cleave each peptide-like bond along the polyamide chain so that the polymer is eventually reduced to monomer-derived molecules that reflect the original diamine and dicarboxylic acid stoichiometry.",
          "Under strongly acidic aqueous conditions, the nitrogen-containing products are typically obtained in their protonated forms, so examination language often refers to ammonium-type ions derived from the diamine, while the carboxylic acid fragments from the diacid residues exist as neutral acids or further protonated species depending on pH, but still belong to the carboxylic acid product class in broad terms.",
          "This susceptibility to acid hydrolysis is the parallel statement to polyester hydrolysis: both condensation polymer families contain hydrolysable heteroatom links in the backbone, unlike poly(alkenes).",
        ],
        commonMistake:
          "Describing ester hydrolysis products for a polyamide, or forgetting that amide hydrolysis is much slower than ester hydrolysis but still syllabus-relevant.",
        tags: ["polyamide", "acid-hydrolysis", "amide"],
      },
      {
        id: "t35-3-d6",
        noteId: "t35-3",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "A sample of nylon-type polyamide is heated with concentrated aqueous sodium hydroxide until all amide links are cleaved. Predict the broad classes of nitrogen-containing and carbonyl-containing organic products, giving attention to the ionic form of the acid-derived fragment. Contrast this product pattern with acid hydrolysis of the same polyamide in one sentence.",
        modelAnswerPoints: [
          "Amide links are cleaved by hydroxide attack (alkaline hydrolysis).",
          "Amine-containing products are obtained (often discussed as amines under basic conditions).",
          "Acid-derived fragments appear as carboxylate salts in alkali, not neutral acids.",
          "Under acid hydrolysis, carboxylic acid forms are obtained instead of carboxylate salts.",
        ],
        workedSolution: [
          "When a polyamide is treated with hot concentrated aqueous sodium hydroxide, hydroxide ion acts as a nucleophile at the amide carbonyl carbons in a base-promoted hydrolysis pathway analogous in outcome to base hydrolysis of esters, except that the leaving group fragment is an amide nitrogen derivative rather than an alkoxide.",
          "Cleavage of each –CONH– linkage ultimately separates the diamine-derived portion of the repeat unit from the diacid-derived portion, so nitrogen-containing organic products belong to the amine class (or deprotonated amine forms in strongly basic media, though A Level answers often still name amines as the product class from the nitrogen side).",
          "Because the medium is strongly alkaline, any carboxylic acid groups that would correspond to the original dicarboxylic acid monomer are deprotonated, so the stable carbonyl-containing organic species from that side of each cleaved link are carboxylate salts, for example carboxylate anions paired with Na+ counterions.",
          "This contrasts with acid hydrolysis of the same polyamide, where the same amide links break under acid catalysis but the acid-derived fragments are obtained as carboxylic acids (and the amine fragments tend to be protonated), showing that pH controls the ionic form of the small-molecule products even though both routes are hydrolytic degradations of the polyamide.",
        ],
        commonMistake:
          "Writing free carboxylic acids as the main organic products from alkaline hydrolysis in excess NaOH(aq).",
        tags: ["polyamide", "alkaline-hydrolysis", "carboxylate"],
      },
      {
        id: "t35-3-d7",
        noteId: "t35-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which general statement best matches the syllabus comparison between typical poly(alkenes) and polyesters or polyamides regarding ease of chemical breakdown by hydrolysis?",
        options: [
          { id: "A", text: "Poly(alkenes) and polyesters are equally readily hydrolysed in dilute acid because both contain C–C backbones." },
          { id: "B", text: "Polyesters and polyamides contain hydrolysable ester or amide links, whereas many poly(alkenes) lack these labile backbone links, so hydrolysis routes are far more effective for the condensation polymers." },
          { id: "C", text: "Polyamides cannot be hydrolysed under alkaline conditions." },
          { id: "D", text: "Only addition polymers can be biodegradable." },
        ],
        correctOptionId: "B",
        explanation:
          "The syllabus contrasts chemically inert poly(alkene) backbones with condensation polymers that can undergo acidic or alkaline hydrolysis at ester or amide links.",
        distractorRationale: {
          A: "Poly(alkenes) do not contain ester/amide links in the backbone; ester hydrolysis targets those polar links, not simple C–C bonds.",
          C: "Polyamides can be hydrolysed under alkaline conditions; this statement is false.",
          D: "Biodegradability and hydrolytic susceptibility are commonly associated with condensation-type linkages; addition poly(alkenes) are often persistent.",
        },
        tags: ["comparison", "hydrolysis", "syllabus"],
      },
      {
        id: "t35-3-d8",
        noteId: "t35-3",
        kind: "mcq",
        difficulty: 3,
        stem: "A plastic shopping bag made from high-density poly(ethene) is buried in landfill where it is dark, cool, and not exposed to aggressive chemical reagents. Which outcome is most consistent with the syllabus view of poly(alkene) persistence?",
        options: [
          { id: "A", text: "Rapid acid-catalysed backbone hydrolysis to monomers within weeks." },
          { id: "B", text: "Immediate photodegradation because all plastics contain visible-light chromophores that always cleave C–C bonds in the dark." },
          { id: "C", text: "Very slow chemical breakdown under those conditions because the hydrocarbon backbone is inert and there is little UV for photoinitiated routes." },
          { id: "D", text: "Selective enzymatic ester hydrolysis of the backbone under neutral pH." },
        ],
        correctOptionId: "C",
        explanation:
          "Poly(ethene) is a poly(alkene) with a non-polar C–C/C–H backbone; in dark landfill it lacks UV-driven photodegradation and lacks hydrolysable ester/amide links, so persistence is expected.",
        distractorRationale: {
          A: "Poly(ethene) does not have a polyester-style ester backbone susceptible to mild acid hydrolysis on that timescale.",
          B: "Photodegradation requires light exposure; deep landfill is dark, and not all plastics photodegrade rapidly even in light.",
          D: "There are no ester links in the poly(ethene) backbone for esterase-style hydrolysis as described.",
        },
        tags: ["polyethene", "landfill", "persistence"],
      },
      {
        id: "t35-3-d9",
        noteId: "t35-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A manufacturer labels a polymer as ‘degradable’. Explain why this label is chemically ambiguous. Distinguish photodegradation, hydrolytic degradation of polyesters or polyamides, and biodegradation by microorganisms, including one sentence on why photodegradation alone may not remove environmental persistence of plastic fragments.",
        modelAnswerPoints: [
          "‘Degradable’ does not specify mechanism (light, hydrolysis, biodegradation, or combinations).",
          "Photodegradation is light-driven chain scission; hydrolytic degradation cleaves ester/amide links in acid or alkali; biodegradation involves microbial metabolism often after chemical weakening.",
          "Photodegradation can reduce strength and size but may produce microplastics unless further breakdown occurs.",
        ],
        workedSolution: [
          "Without further qualification, the word degradable only asserts that some chemical or physical process can reduce molecular mass or mechanical integrity over time, but it does not tell a chemist whether that process is initiated by ultraviolet light, by attack of water at functional groups, by enzymes in soil, or by industrial processing conditions such as high temperature composting.",
          "Photodegradation specifically refers to pathways where absorption of light energy initiates radical chemistry or other bond-breaking events that lead to chain scission, whereas hydrolytic degradation of polyesters and polyamides refers to nucleophilic cleavage of ester or amide links catalysed or promoted by acidic or alkaline aqueous media as described earlier in the topic.",
          "Biodegradation is a biological outcome in which microorganisms utilise fragments of the polymer as substrates, often after abiotic steps have already introduced oxidised or shorter-chain material, so it is not identical to either photodegradation or simple bench-top hydrolysis even though these processes can be connected in a waste lifecycle.",
          "Even when photodegradation succeeds on a sunlit surface, it may chiefly embrittle the article and shed small oxidised polymer particles rather than fully mineralise every carbon atom rapidly, so environmental persistence of microplastic debris can continue unless subsequent biodegradation or chemical oxidation completes the breakdown.",
        ],
        commonMistake:
          "Treating ‘degradable’, ‘photodegradable’, and ‘biodegradable’ as interchangeable synonyms with identical mechanisms.",
        tags: ["definitions", "environment", "evaluation"],
      },
      {
        id: "t35-3-d10",
        noteId: "t35-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Which modification or polymer choice most directly targets degradation initiated by ultraviolet light rather than by enzyme-catalysed hydrolysis of ester links?",
        options: [
          { id: "A", text: "Incorporating photosensitiser groups or additives that promote UV-initiated chain scission in a polyolefin." },
          { id: "B", text: "Using poly(lactic acid) instead of poly(ethene) for a bottle." },
          { id: "C", text: "Increasing the molar mass of poly(ethene) so hydroxide attacks faster." },
          { id: "D", text: "Cross-linking poly(ethene) so ester hydrolysis is faster." },
        ],
        correctOptionId: "A",
        explanation:
          "Photosensitisers or UV-absorbing additives can channel light energy into radical chemistry that fragments polyolefins; PLA’s susceptibility is more about hydrolysable ester links than UV-only initiation.",
        distractorRationale: {
          B: "PLA is a polyester with hydrolysable ester links; its degradability is often discussed in hydrolysis/composting contexts rather than as a pure UV-initiated polyolefin strategy.",
          C: "Higher Mr does not make hydroxide attack faster on an inert polyolefin backbone; the premise confuses variables.",
          D: "Poly(ethene) does not contain ester links to hydrolyse; cross-linking does not introduce that mechanism.",
        },
        tags: ["photodegradation", "UV", "applications"],
      },
    ],
    flashcards: [
      {
        id: "t35-3-f1",
        noteId: "t35-3",
        difficulty: 1,
        front: "Why are many poly(alkenes) hard to biodegrade?",
        back: "Strong, non-polar C–C/C–H backbone; few handles for hydrolysis or enzymes.",
        examPhrasing: "Explain the environmental persistence of poly(ethene).",
        tags: ["polyalkenes", "persistence"],
      },
      {
        id: "t35-3-f2",
        noteId: "t35-3",
        difficulty: 1,
        front: "What is photodegradation?",
        back: "Light-initiated breakdown of polymers, often UV-driven radical chemistry and chain scission.",
        examPhrasing: "Define photodegradation of plastics.",
        tags: ["photodegradation", "definitions"],
      },
      {
        id: "t35-3-f3",
        noteId: "t35-3",
        difficulty: 2,
        front: "Polyester + hot NaOH(aq) — key organic product classes?",
        back: "Carboxylate salts plus alcohols (saponification-style cleavage of esters).",
        examPhrasing: "State the products of alkaline hydrolysis of a polyester.",
        confusionPair: "acid vs alkali hydrolysis products",
        tags: ["polyester", "alkali"],
      },
      {
        id: "t35-3-f4",
        noteId: "t35-3",
        difficulty: 2,
        front: "Polyester + dilute H+(aq) hydrolysis — acid-derived fragment class?",
        back: "Carboxylic acids (and alcohols from the diol side).",
        examPhrasing: "Give the product classes from acid hydrolysis of a polyester.",
        tags: ["polyester", "acid"],
      },
      {
        id: "t35-3-f5",
        noteId: "t35-3",
        difficulty: 3,
        front: "Polyamide alkaline hydrolysis — carbonyl fragment ionic form?",
        back: "Carboxylate salt under excess alkali.",
        examPhrasing: "Name the form of the acid-derived product when a polyamide is hydrolysed in NaOH(aq).",
        tags: ["polyamide", "alkali"],
      },
      {
        id: "t35-3-f6",
        noteId: "t35-3",
        difficulty: 3,
        front: "Why can polyamides be hydrolysed in acid?",
        back: "Amide links are polar and activated by protonation; water cleaves –CONH– to ammonium-type and acid fragments.",
        examPhrasing: "Explain acid hydrolysis of polyamides.",
        tags: ["polyamide", "acid"],
      },
      {
        id: "t35-3-f7",
        noteId: "t35-3",
        difficulty: 4,
        front: "Photodegradation vs biodegradation — core distinction?",
        back: "Photo is light-driven bond breaking; biodegradation is microbial metabolism, often after chemical breakdown.",
        examPhrasing: "Distinguish photodegradation and biodegradation of polymers.",
        confusionPair: "photo vs bio",
        tags: ["definitions", "environment"],
      },
      {
        id: "t35-3-f8",
        noteId: "t35-3",
        difficulty: 4,
        front: "Limitation of photodegradable litter in landfill?",
        back: "Little UV reaches buried waste, so photoinitiated routes may not operate.",
        examPhrasing: "Give one limitation of relying on photodegradation for waste in landfill.",
        tags: ["photodegradation", "landfill"],
      },
      {
        id: "t35-3-f9",
        noteId: "t35-3",
        difficulty: 5,
        front: "Syllabus: which polymers are noted as biodegradable by acid/base hydrolysis?",
        back: "Polyesters and polyamides (hydrolysable ester or amide links).",
        examPhrasing: "Recognise polymers degraded by acidic and alkaline hydrolysis.",
        tags: ["syllabus", "hydrolysis"],
      },
      {
        id: "t35-3-f10",
        noteId: "t35-3",
        difficulty: 5,
        front: "Why might UV fragmentation still be environmentally problematic?",
        back: "It can create microplastics or small persistent fragments without full mineralisation.",
        examPhrasing: "Evaluate photodegradable plastics as an environmental fix.",
        tags: ["microplastics", "evaluation"],
      },
    ],
  },
};
