import type { SubtopicPracticePack } from "./types";

/**
 * Topic 1 (9701) practice — LO crosswalk to `data/syllabus/chemistry-9701-learning-outcomes.md` §1.1–1.4.
 * Each `noteId` pack has 10 drills; comments map syllabus bullets to stable `id`s (see STRUCTURED_DRILLS.md).
 */
export const CHEMISTRY_TOPIC1_PRACTICE: Record<string, SubtopicPracticePack> = {
  /* 1.1 Particles / radius — LO map: d1 particle charges+masses; d2 mass in nucleus+empty space; d3 E-field beams;
     d4 define p,n,e; d5 Z,A,nucleon terms; d6 mass+charge distribution+neutral atom; d7 count p,n,e in atoms/ions;
     d8 nuclear model evidence; d9 atomic+ionic radius across a period; d10 radius down a group (+ shielding). */
  "t1-1": {
    noteId: "t1-1",
    drills: [
      {
        id: "t1-1-d1",
        noteId: "t1-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which particle has a relative charge of +1 and a relative mass of approximately 1?",
        options: [
          { id: "A", text: "Proton" },
          { id: "B", text: "Neutron" },
          { id: "C", text: "Electron" },
          { id: "D", text: "Beta particle" },
        ],
        correctOptionId: "A",
        explanation:
          "A proton has relative charge +1 and relative mass ~1 on the usual scale; a neutron is ~1 in mass but uncharged, and an electron is −1 with mass ~1/1840.",
        distractorRationale: {
          B: "A neutron is uncharged, so its relative charge is 0.",
          C: "An electron has relative charge −1 and a much smaller relative mass (~1/1840).",
          D: "A beta particle is a high-speed electron; it is negative and very light.",
        },
        tags: ["fundamental-particles", "9701-1.1"],
      },
      {
        id: "t1-1-d2",
        noteId: "t1-1",
        kind: "mcq",
        difficulty: 2,
        stem: "In the nuclear model of the atom, where is almost all of the mass located, and what does that imply about the volume occupied by the nucleus?",
        options: [
          {
            id: "A",
            text: "Almost all mass is in the nucleus, which occupies only a tiny fraction of the atom's total volume",
          },
          { id: "B", text: "Mass is spread evenly through the atom, so the nucleus fills most of the volume" },
          { id: "C", text: "Most mass is in the electron cloud, which is smaller than the nucleus" },
          { id: "D", text: "Mass is shared equally between protons in the nucleus and electrons in shells" },
        ],
        correctOptionId: "A",
        explanation:
          "Protons and neutrons carry almost all mass in a very small, dense nucleus; electrons have negligible mass but occupy most of the atom's volume in shells around the nucleus.",
        distractorRationale: {
          B: "A uniform mass distribution matches the old plum-pudding idea, not the nuclear model supported by scattering evidence.",
          C: "The electron cloud occupies most of the volume but contributes very little mass compared with the nucleus.",
          D: "Electron mass is tiny compared with nucleons, so mass is not shared equally between nucleus and electrons.",
        },
        tags: ["nuclear-model", "mass-distribution", "9701-1.1"],
      },
      {
        id: "t1-1-d3",
        noteId: "t1-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Parallel charged plates produce a uniform electric field. Proton, neutron and electron beams enter horizontally at the same speed midway between the plates, perpendicular to the field. Which statement is correct?",
        options: [
          {
            id: "A",
            text: "The proton is deflected toward the negative plate, the electron toward the positive plate, and the neutron is undeflected",
          },
          {
            id: "B",
            text: "All three beams are deflected toward the positive plate because the field direction is fixed",
          },
          { id: "C", text: "The neutron is deflected most because it has the largest mass" },
          { id: "D", text: "The proton and electron follow the same curved path because they have equal magnitude charge" },
        ],
        correctOptionId: "A",
        explanation:
          "A positive particle is accelerated in the direction of the electric field (toward the negative plate); a negative particle accelerates opposite to the field; an uncharged neutron experiences no electric force and continues in a straight line at constant velocity (ignoring gravity).",
        distractorRationale: {
          B: "Only charged particles are deflected; direction depends on the sign of the charge relative to the field.",
          C: "Mass does not make an uncharged particle deflect in an electric field; there is no electric force on a neutron.",
          D: "Equal magnitude charge gives equal magnitude force, but opposite sign gives opposite acceleration directions, so the paths curve opposite ways.",
        },
        tags: ["electric-field", "beams", "9701-1.1"],
      },
      {
        id: "t1-1-d4",
        noteId: "t1-1",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "State the relative charge and relative mass of a proton, a neutron and an electron on the usual scale where a proton has relative mass about 1.",
        modelAnswerPoints: [
          "Proton: relative charge +1; relative mass ~1.",
          "Neutron: relative charge 0; relative mass ~1.",
          "Electron: relative charge −1; relative mass ~1/1840 (negligible compared with a nucleon).",
        ],
        workedSolution: [
          "On the usual scale used at AS level, a proton has relative charge +1 and relative mass approximately 1.",
          "A neutron has relative charge 0 because it is uncharged, and its relative mass is also approximately 1, similar to a proton.",
          "An electron has relative charge −1 and relative mass about 1/1840, which is so small that electrons contribute almost no mass to the atom compared with the nucleus.",
        ],
        commonMistake: "Giving the neutron a non-zero charge, or stating the electron has positive charge.",
        tags: ["particles", "definitions", "9701-1.1"],
      },
      {
        id: "t1-1-d5",
        noteId: "t1-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Define the terms atomic number, proton number, mass number and nucleon number for a given nuclide.",
        modelAnswerPoints: [
          "Atomic number / proton number (Z): number of protons in the nucleus (identifies the element).",
          "Mass number (A): total number of protons plus neutrons in the nucleus.",
          "Nucleon number is another name for mass number (count of nucleons).",
        ],
        workedSolution: [
          "The atomic number, also called the proton number and symbolised Z, is the number of protons in the nucleus of an atom or ion; it determines which element the species belongs to.",
          "The mass number, symbolised A, is the total number of protons and neutrons in that nucleus.",
          "The nucleon number is the same count as the mass number, because protons and neutrons are the nucleons; therefore neutron number equals A − Z.",
        ],
        commonMistake: "Confusing mass number with relative atomic mass, or defining nucleon number without linking it to protons plus neutrons.",
        tags: ["atomic-number", "mass-number", "9701-1.1"],
      },
      {
        id: "t1-1-d6",
        noteId: "t1-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Describe how mass and electric charge are distributed in a neutral atom of an element.",
        modelAnswerPoints: [
          "Almost all mass is in the tiny, dense nucleus (protons and neutrons).",
          "Positive charge is concentrated in the nucleus (from protons).",
          "Electrons occupy shells in the surrounding volume; in a neutral atom their negative charge balances the nuclear charge.",
        ],
        workedSolution: [
          "Almost all of the mass of a neutral atom is located in its nucleus, because protons and neutrons are much more massive than electrons.",
          "The nucleus is also the region where the atom's positive charge is concentrated, because each proton contributes +1 unit of charge while neutrons are uncharged.",
          "Electrons are found in shells in the space around the nucleus; in a neutral atom the number of electrons equals Z, so the total negative charge of the electrons equals the total positive charge of the nucleus and the atom has no overall charge.",
        ],
        commonMistake: "Placing most mass in the electron shells, or forgetting that charge balance requires equal numbers of protons and electrons in a neutral atom.",
        tags: ["charge", "structure", "9701-1.1"],
      },
      {
        id: "t1-1-d7",
        noteId: "t1-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A neutral atom of phosphorus has mass number 31. A sulfide ion, S^2-, is written as ^34_16S^2-. For each species, state the numbers of protons, neutrons and electrons. Show any arithmetic you use.",
        modelAnswerPoints: [
          "Phosphorus: Z = 15, so 15 protons; A = 31 gives neutrons = 31 − 15 = 16; neutral atom has 15 electrons.",
          "Sulfide ion: Z = 16, so 16 protons; A = 34 gives neutrons = 34 − 16 = 18.",
          "For S^2-, electron count = 16 + 2 = 18 electrons (two more than the neutral sulfur atom).",
        ],
        workedSolution: [
          "Phosphorus has atomic number 15, so a phosphorus atom has 15 protons in its nucleus.",
          "With mass number 31, the number of neutrons is A − Z = 31 − 15 = 16.",
          "Because the phosphorus species is a neutral atom, it has the same number of electrons as protons, which is 15 electrons.",
          "For ^34_16S^2-, the atomic number is 16, so there are 16 protons, and the number of neutrons is 34 − 16 = 18.",
          "A 2− anion has two more electrons than the neutral atom of the same element, so the electron count is 16 + 2 = 18 electrons.",
        ],
        commonMistake: "Using the mass number as the electron count, or subtracting the ionic charge incorrectly when finding electrons.",
        tags: ["ions", "composition", "9701-1.1"],
      },
      {
        id: "t1-1-d8",
        noteId: "t1-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Describe the alpha-particle scattering experiment and explain how its observations support the idea that an atom is mostly empty space with a very small, dense, positively charged nucleus containing most of the atom's mass.",
        modelAnswerPoints: [
          "Experimental arrangement described (alpha particles directed at thin metal foil; detector positions).",
          "Most alphas pass through with little deflection -> mostly empty space/volume.",
          "Very few large-angle scatterings / rare rebounds -> close approach to a small, massive, repulsive positive centre (nucleus).",
        ],
        workedSolution: [
          "In the Geiger–Marsden experiment, a beam of alpha particles was fired at a very thin gold foil and the scattering angles were recorded around the foil.",
          "The majority of alpha particles passed straight through with little or no deflection, which shows that most of the foil's volume does not contain enough mass or charge to repel the alphas strongly; therefore an atom is mostly empty space through which fast alphas can travel.",
          "A very small fraction of alpha particles were scattered through large angles and a tiny number even rebounded, which means those alphas must occasionally pass very close to a small, dense, positively charged object that repels them strongly and contains most of the atom's mass — the nucleus.",
        ],
        commonMistake: "Claiming that large-angle scattering is caused by electrons, or that most alphas rebound from every atom.",
        tags: ["rutherford", "evidence", "9701-1.1"],
      },
      {
        id: "t1-1-d9",
        noteId: "t1-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Explain qualitatively why atomic radius decreases across Period 3 from sodium to argon, and why the ionic radius of Na+ is smaller than the atomic radius of a sodium atom.",
        modelAnswerPoints: [
          "Across Period 3, electrons are added to the same principal shell while nuclear charge increases.",
          "Greater nuclear attraction pulls the outer electron distribution closer, decreasing atomic radius (shielding from inner shells does not increase enough to cancel the rising Z).",
          "Na+ has one fewer electron shell occupied than Na (2,8 vs 2,8,1), so remaining electrons are held closer; also fewer electron-electron repulsions for the same nuclear charge.",
        ],
        workedSolution: [
          "Across Period 3 from sodium to argon, each successive element adds one proton to the nucleus and one electron into the same principal quantum shell (n = 3 for the valence shell), so the outer electrons are at similar average distances but experience a steadily increasing nuclear charge.",
          "Because the added electrons are in the same shell, extra inner-shell shielding does not increase strongly enough to offset the rise in nuclear charge, so the outer electrons are attracted more strongly and the atomic radius decreases across the period.",
          "When a sodium atom forms Na+, the outer 3s electron is removed, so the ion has the electron arrangement of neon with electrons only in inner shells closer to the nucleus.",
          "With fewer electrons than the neutral atom but the same +11 nuclear charge, the remaining electrons are pulled in more tightly, and there is less electron-electron repulsion, so Na+ is much smaller than a sodium atom.",
        ],
        commonMistake: "Saying the ion is larger because 'the nucleus attracts more electrons', or claiming the number of occupied shells increases across Period 3.",
        tags: ["atomic-radius", "ionic-radius", "9701-1.1"],
      },
      {
        id: "t1-1-d10",
        noteId: "t1-1",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "Explain qualitatively why atomic radius increases down Group 1 from lithium to caesium, and why the ionic radius of an iodide ion, I-, is larger than the atomic radius of a neutral iodine atom.",
        modelAnswerPoints: [
          "Down Group 1 each element adds a new occupied principal shell for the outer electron.",
          "Outer electron farther from nucleus and more shielded -> weaker net attraction -> larger radius.",
          "I- has one more electron than I for the same nuclear charge; extra repulsion and occupancy of higher-energy orbitals increase size compared with the neutral atom.",
        ],
        workedSolution: [
          "Going down Group 1 from lithium to caesium, each element has its outermost electron in a higher principal quantum shell than the element above it, so on average that valence electron is farther from the nucleus.",
          "There are also more inner shells below the outer electron, which shield the outer electron from the full nuclear charge, so the outer electron experiences a smaller effective attraction and the atomic radius increases down the group.",
          "For iodine, adding an electron to form I- means there are 54 electrons around a +53 nucleus instead of 53 electrons in the neutral atom.",
          "The additional electron increases electron-electron repulsion and occupies space in the valence region, so the electron cloud expands and the iodide ion is larger than the neutral iodine atom despite having the same nuclear charge.",
        ],
        commonMistake: "Ignoring shielding down a group, or claiming anions are smaller than their parent atoms because 'extra charge pulls harder' without discussing repulsion and electron occupancy.",
        tags: ["trends", "ionic-radius", "9701-1.1"],
      },
    ],
    flashcards: [
      {
        id: "t1-1-f1",
        noteId: "t1-1",
        difficulty: 1,
        front: "Relative charge and mass of a proton?",
        back: "Relative charge +1; relative mass ~1.",
        examPhrasing: "State the relative charge and mass of a proton.",
        tags: ["particles"],
      },
      {
        id: "t1-1-f2",
        noteId: "t1-1",
        difficulty: 1,
        front: "What does atomic number Z equal in a neutral atom?",
        back: "Number of protons in the nucleus; also equals the number of electrons in the neutral atom.",
        examPhrasing: "Define atomic number.",
        confusionPair: "Z vs mass number A",
        tags: ["atomic-number"],
      },
      {
        id: "t1-1-f3",
        noteId: "t1-1",
        difficulty: 2,
        front: "Order of magnitude: atomic diameter vs nuclear diameter?",
        back: "Atom ~10^-10 m; nucleus ~10^-15 m — nucleus is vastly smaller in volume than the atom.",
        examPhrasing: "Give the order of magnitude of an atomic diameter and a nuclear diameter.",
        tags: ["scale"],
      },
      {
        id: "t1-1-f4",
        noteId: "t1-1",
        difficulty: 2,
        front: "Parallel plates: which way does a proton accelerate?",
        back: "In the direction of the electric field (toward the negative plate); an electron accelerates opposite to the field.",
        examPhrasing: "Describe the motion of a proton beam in a uniform electric field between charged plates.",
        tags: ["electric-field"],
      },
      {
        id: "t1-1-f5",
        noteId: "t1-1",
        difficulty: 3,
        front: "What do rare large-angle alpha scatterings imply?",
        back: "A small, dense, positively charged nucleus that can repel alphas strongly on close approach.",
        examPhrasing: "Explain what large-angle scattering indicates about atomic structure.",
        tags: ["nuclear-model"],
      },
      {
        id: "t1-1-f6",
        noteId: "t1-1",
        difficulty: 3,
        front: "Where is almost all the mass of the atom?",
        back: "In the nucleus (protons and neutrons); electron mass is negligible here.",
        examPhrasing: "State where most of the mass of an atom is located.",
        tags: ["mass-distribution"],
      },
      {
        id: "t1-1-f7",
        noteId: "t1-1",
        difficulty: 4,
        front: "Atomic radius across a period (same shell)?",
        back: "Generally decreases: nuclear charge increases while electrons are added to the same principal shell, so outer electrons are pulled closer.",
        examPhrasing: "Explain the trend in atomic radius across Period 3.",
        tags: ["atomic-radius"],
      },
      {
        id: "t1-1-f8",
        noteId: "t1-1",
        difficulty: 4,
        front: "Na atom vs Na+ ion: which is larger?",
        back: "Na atom is larger: the ion loses the outer shell electron(s), so remaining electrons are closer for the same nuclear charge.",
        examPhrasing: "Compare the radius of a sodium atom with its ion.",
        confusionPair: "cation vs anion size trends",
        tags: ["ionic-radius"],
      },
      {
        id: "t1-1-f9",
        noteId: "t1-1",
        difficulty: 5,
        front: "Neutron beam between charged plates?",
        back: "No electric deflection (uncharged); path stays straight at constant velocity if gravity is ignored.",
        examPhrasing: "Describe the behaviour of a neutron beam in a uniform electric field.",
        tags: ["beams"],
      },
      {
        id: "t1-1-f10",
        noteId: "t1-1",
        difficulty: 5,
        front: "Mass number A in terms of nucleons?",
        back: "A equals the number of protons plus neutrons in the nucleus (nucleon number).",
        examPhrasing: "Define mass number.",
        tags: ["mass-number"],
      },
    ],
  },

  /* 1.2 Isotopes — LO map: d1 isotope definition MCQ; d2 notation MCQ; d3 same chemistry MCQ; d4 define isotope;
     d5 explain ^A_Z X; d6 same chemical properties; d7 different physical (mass+density); d8 neutron count calc;
     d9 density ratio calc (same V,n); d10 write nuclide symbol for ion. */
  "t1-2": {
    noteId: "t1-2",
    drills: [
      {
        id: "t1-2-d1",
        noteId: "t1-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which statement defines isotopes of an element correctly?",
        options: [
          { id: "A", text: "Same number of protons in the nucleus, different numbers of neutrons" },
          { id: "B", text: "Same number of neutrons in the nucleus, different numbers of protons" },
          { id: "C", text: "Same mass number but different atomic numbers" },
          { id: "D", text: "Different elements with similar chemical reactivity" },
        ],
        correctOptionId: "A",
        explanation:
          "Isotopes are atoms of the same element, so they share the same proton number (atomic number) but differ in neutron number, giving different mass numbers.",
        distractorRationale: {
          B: "Changing the number of protons changes the element; isotopes differ in neutrons, not protons.",
          C: "Same mass number with different atomic numbers describes different nuclides (isobars), not isotopes of one element.",
          D: "Isotopes are defined within one element; different elements are not isotopes of each other.",
        },
        tags: ["isotopes", "definitions", "9701-1.2"],
      },
      {
        id: "t1-2-d2",
        noteId: "t1-2",
        kind: "mcq",
        difficulty: 2,
        stem: "In the symbol ^14_6C, what do the numbers 14 and 6 represent?",
        options: [
          { id: "A", text: "14 is the mass number (nucleon number); 6 is the atomic number (proton number)" },
          { id: "B", text: "14 is the atomic number; 6 is the neutron number" },
          { id: "C", text: "14 is the number of electrons; 6 is the number of neutrons" },
          { id: "D", text: "14 is the relative atomic mass of carbon; 6 is the charge" },
        ],
        correctOptionId: "A",
        explanation:
          "By convention, the superscript is the mass number A (protons + neutrons) and the subscript is the atomic number Z (protons); here Z = 6 and A = 14, so neutrons = 8.",
        distractorRationale: {
          B: "The subscript is always the proton number for the element symbol shown, not the neutron number.",
          C: "Electron number is not written as the superscript in this nuclide notation, and 6 is the proton count for carbon.",
          D: "Relative atomic mass is a tabulated average for an element; the superscript here labels one nuclide's mass number, not A_r, and no ionic charge is shown.",
        },
        tags: ["notation", "isotopes", "9701-1.2"],
      },
      {
        id: "t1-2-d3",
        noteId: "t1-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which property is expected to be essentially the same for ^79_35Br and ^81_35Br atoms in their ground states?",
        options: [
          { id: "A", text: "Their chemical reactivity with a given reagent under the same conditions" },
          { id: "B", text: "The density of solid bromine made only from each isotope, at the same temperature" },
          { id: "C", text: "The relative atomic mass printed for the element bromine on the Periodic Table" },
          { id: "D", text: "The number of neutrons in each nucleus" },
        ],
        correctOptionId: "A",
        explanation:
          "Isotopes have the same atomic number, so neutral atoms have the same electron configuration and therefore very similar chemical properties; physical differences such as density arise from different nuclear masses.",
        distractorRationale: {
          B: "Density depends on mass per unit volume; different isotopic masses change the molar mass of the substance, so the densities differ slightly for the same structure.",
          C: "The tabulated A_r is a weighted average over all naturally occurring isotopes; it is not a property of one isolated nuclide.",
          D: "Different mass numbers with the same Z mean different neutron counts.",
        },
        tags: ["chemical-properties", "isotopes", "9701-1.2"],
      },
      {
        id: "t1-2-d4",
        noteId: "t1-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define the term isotope in terms of the numbers of protons and neutrons in the nucleus.",
        modelAnswerPoints: [
          "Isotopes are atoms (or nuclides) of the same element.",
          "Same number of protons / same atomic number.",
          "Different number of neutrons / different mass number.",
        ],
        workedSolution: [
          "Isotopes are atoms of the same element, which means they contain the same number of protons in the nucleus and therefore the same atomic number.",
          "They differ in the number of neutrons present in the nucleus, so their mass numbers are different because the mass number counts protons plus neutrons.",
        ],
        commonMistake: "Defining isotopes as atoms with different numbers of electrons; that describes ions, not the meaning of isotopy.",
        tags: ["isotopes", "definition", "9701-1.2"],
      },
      {
        id: "t1-2-d5",
        noteId: "t1-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain the meaning of the notation ^A_Z X for an isotope, stating what each symbol represents.",
        modelAnswerPoints: [
          "X is the chemical symbol of the element.",
          "Z is the atomic number (proton number) written as a subscript.",
          "A is the mass number (nucleon number) written as a superscript.",
        ],
        workedSolution: [
          "In the notation ^A_Z X, the letter X is the chemical symbol that identifies which element is being described.",
          "The subscript Z is the atomic number, which equals the number of protons in the nucleus of that atom or ion.",
          "The superscript A is the mass number, also called the nucleon number, which equals the total number of protons plus neutrons in that nucleus.",
        ],
        commonMistake: "Swapping A and Z, or treating the superscript as the neutron count alone.",
        tags: ["notation", "isotopes", "9701-1.2"],
      },
      {
        id: "t1-2-d6",
        noteId: "t1-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "State that isotopes of the same element have the same chemical properties, and explain why this is so in terms of electrons and the nucleus.",
        modelAnswerPoints: [
          "Statement: chemical properties are essentially the same for different isotopes of one element.",
          "Chemical behaviour is determined largely by electron arrangement (especially outer electrons).",
          "Same Z implies the same number of electrons in a neutral atom, hence the same ground-state electron configuration; neutrons do not change chemistry strongly.",
        ],
        workedSolution: [
          "Isotopes of the same element have essentially the same chemical properties when compared as neutral atoms under the same conditions.",
          "This is because chemical reactions involve the outer electrons bonding and interacting with other species, so chemistry is controlled mainly by electron arrangement rather than by nuclear mass.",
          "Isotopes share the same atomic number, so neutral atoms of each isotope contain the same number of electrons and therefore the same electron configuration; the extra neutrons alter nuclear mass but do not change the electron count, so the chemistry is very similar.",
        ],
        commonMistake: "Claiming that neutrons change the electron configuration of neutral atoms, or that isotopes are different elements.",
        tags: ["chemical-properties", "isotopes", "9701-1.2"],
      },
      {
        id: "t1-2-d7",
        noteId: "t1-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "State that isotopes of the same element have different physical properties, limited by the syllabus to mass and density, and explain briefly why their densities can differ for the same substance and conditions.",
        modelAnswerPoints: [
          "Physical properties can differ between isotopes; focus on mass and density as required.",
          "Different isotopes have different nuclear masses (different neutron counts).",
          "For a fixed amount of substance in a fixed volume, a larger molar mass gives a larger mass, hence a larger density.",
        ],
        workedSolution: [
          "Isotopes of the same element are not identical in every physical respect because their atoms differ in mass: they contain different numbers of neutrons, so the mass number changes while the proton number stays the same.",
          "At this level, the syllabus highlights mass and density as physical properties that can differ between isotopes of the same element.",
          "If you compare the same type of material (for example solid bromine or a particular gas) made from a heavier isotope, one mole contains the same number of formula units but each formula unit has greater mass, so the sample has greater mass for the same volume and therefore a higher density.",
        ],
        commonMistake: "Saying isotopes must have the same density because they are the same element, or listing chemical properties as 'physical differences'.",
        tags: ["physical-properties", "density", "9701-1.2"],
      },
      {
        id: "t1-2-d8",
        noteId: "t1-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "For the neutral atoms ^39_19K and ^41_19K, calculate the number of neutrons in each nucleus and write the full nuclide symbol including A and Z for each species.",
        modelAnswerPoints: [
          "Potassium has Z = 19 protons in both cases.",
          "Neutrons for ^39_19K: 39 − 19 = 20.",
          "Neutrons for ^41_19K: 41 − 19 = 22.",
          "Symbols written correctly as ^39_19K and ^41_19K.",
        ],
        workedSolution: [
          "Both symbols refer to potassium, so the atomic number is Z = 19 and each neutral atom has 19 protons in the nucleus.",
          "For ^39_19K the mass number is 39, so the number of neutrons is A − Z = 39 − 19 = 20.",
          "For ^41_19K the mass number is 41, so the number of neutrons is 41 − 19 = 22.",
          "The two potassium isotopes are therefore written as ^39_19K and ^41_19K, showing the same Z but different A because the neutron count changes.",
        ],
        commonMistake: "Subtracting electrons from A, or changing Z between the two isotopes.",
        tags: ["notation", "calculation", "9701-1.2"],
      },
      {
        id: "t1-2-d9",
        noteId: "t1-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Two sealed flasks of equal volume contain equal amounts, in moles, of Cl2(g) at the same temperature and pressure. Flask P contains only ^35Cl2 and flask Q contains only ^37Cl2. Calculate the ratio (density of Q) / (density of P), treating each molecule as having mass proportional to the sum of the mass numbers of its atoms.",
        modelAnswerPoints: [
          "Same V, T, P and same n implies same number of molecules in each flask.",
          "Mass in each flask is proportional to molar mass; for diatomic molecules use 2 × mass number for each isotope.",
          "M(^35Cl2) proportional to 70 and M(^37Cl2) proportional to 74, so ratio = 74/70 = 1.06 (2 d.p.) or 37/35 as an exact fraction.",
        ],
        workedSolution: [
          "Because the flasks have the same volume and the same amount in moles of gas at the same temperature and pressure, each flask contains the same number of Cl2 molecules.",
          "Density equals mass divided by volume, and the volume is the same for both flasks, so the ratio of densities equals the ratio of the masses of gas present.",
          "Each ^35Cl2 molecule has a total mass number contribution of 35 + 35 = 70, while each ^37Cl2 molecule has 37 + 37 = 74.",
          "With the same number of molecules, the mass ratio is 74 : 70, so (density Q)/(density P) = 74/70 = 37/35 = 1.06 (to two decimal places).",
        ],
        commonMistake: "Using atomic mass 35.5 from the Periodic Table instead of the stated pure isotope molecules, or forgetting to double the mass number for Cl2.",
        tags: ["density", "calculation", "9701-1.2"],
      },
      {
        id: "t1-2-d10",
        noteId: "t1-2",
        kind: "structured",
        difficulty: 5,
        marks: 5,
        stem: "A monatomic anion carries charge 2−, contains 18 electrons and its nucleus contains 16 protons and 18 neutrons. Write the nuclide symbol in the form ^A_Z X^z- for this ion, showing values of A, Z and z.",
        modelAnswerPoints: [
          "Z = 16 identifies sulfur (X = S).",
          "A = protons + neutrons = 16 + 18 = 34.",
          "Correct symbol ^34_16S^2- (or equivalent ordering of charge).",
        ],
        workedSolution: [
          "The ion contains 16 protons in the nucleus, so the atomic number is Z = 16 and the element is sulfur, symbol S.",
          "The mass number is the total number of nucleons, A = 16 + 18 = 34.",
          "The question states a 2− charge, and 18 electrons is consistent with a sulfide ion because electron count = Z + 2 = 16 + 2 = 18.",
          "The ion is therefore written as ^34_16S^2-, with A = 34, Z = 16 and z = 2 for the charge magnitude in a 2− ion.",
        ],
        commonMistake: "Writing the wrong element for Z = 16, or using electron number as the superscript mass number.",
        tags: ["notation", "ions", "9701-1.2"],
      },
    ],
    flashcards: [
      {
        id: "t1-2-f1",
        noteId: "t1-2",
        difficulty: 1,
        front: "Definition: isotope?",
        back: "Same proton number (same element), different neutron number (different mass number).",
        examPhrasing: "Define the term isotope.",
        tags: ["isotopes"],
      },
      {
        id: "t1-2-f2",
        noteId: "t1-2",
        difficulty: 1,
        front: "How are neutrons counted from a nuclide symbol ^A_Z X?",
        back: "Neutrons = A - Z.",
        examPhrasing: "Calculate the number of neutrons in an atom of …",
        tags: ["notation"],
      },
      {
        id: "t1-2-f3",
        noteId: "t1-2",
        difficulty: 2,
        front: "Why do ^35Cl and ^37Cl have almost the same chemistry?",
        back: "Same Z -> same electron count and configuration in neutral atoms; chemistry is controlled mainly by electrons.",
        examPhrasing: "Explain why isotopes of an element have the same chemical properties.",
        tags: ["chemical-properties"],
      },
      {
        id: "t1-2-f4",
        noteId: "t1-2",
        difficulty: 2,
        front: "Give two physical properties that can differ between isotopes (syllabus limit).",
        back: "Mass and density (for the same structure and conditions).",
        examPhrasing: "State physical properties in which isotopes of an element can differ.",
        tags: ["physical-properties"],
      },
      {
        id: "t1-2-f5",
        noteId: "t1-2",
        difficulty: 3,
        front: "In ^A_Z X, which number is always the proton count?",
        back: "Z (subscript) is the atomic / proton number.",
        examPhrasing: "State what is meant by the subscript in a nuclide symbol.",
        tags: ["notation"],
      },
      {
        id: "t1-2-f6",
        noteId: "t1-2",
        difficulty: 3,
        front: "^14C vs ^12C: different chemistry?",
        back: "Essentially no for most purposes: both are carbon (Z = 6) with the same ground-state electron configuration.",
        examPhrasing: "Comment on the chemical similarity of carbon-12 and carbon-14.",
        tags: ["isotopes"],
      },
      {
        id: "t1-2-f7",
        noteId: "t1-2",
        difficulty: 4,
        front: "Why can isotopic gases differ in density at the same T and P?",
        back: "Same moles means same number of molecules; heavier isotopes give larger molar mass, so larger mass in the same volume.",
        examPhrasing: "Explain a density difference between samples of the same compound made from different isotopes.",
        tags: ["density"],
      },
      {
        id: "t1-2-f8",
        noteId: "t1-2",
        difficulty: 4,
        front: "Mass number vs neutron number?",
        back: "Mass number A counts protons + neutrons; neutron number = A − Z.",
        examPhrasing: "Relate mass number to neutron number.",
        confusionPair: "A vs A − Z",
        tags: ["definitions"],
      },
      {
        id: "t1-2-f9",
        noteId: "t1-2",
        difficulty: 5,
        front: "Do isotopes differ in nuclear charge?",
        back: "No: same proton number means the same nuclear charge; they differ in neutron count and therefore nuclear mass.",
        examPhrasing: "Explain whether isotopes of an element have the same nuclear charge.",
        tags: ["isotopes"],
      },
      {
        id: "t1-2-f10",
        noteId: "t1-2",
        difficulty: 5,
        front: "Write the symbol for a magnesium ion with mass number 25 (Z = 12) and charge 2+.",
        back: "^25_12Mg^2+ (12 protons; 13 neutrons; 10 electrons).",
        examPhrasing: "Write the nuclide symbol for this magnesium ion.",
        tags: ["notation"],
      },
    ],
  },

  /* 1.3 Electrons / orbitals (H–Kr) — LO map: d1 p orbital count; d2 subshell energy order (incl. 4s/4p vs 3d);
     d3 s/p/d capacities; d4 shells/subshells/orbitals + n + ground state; d5 N config + Hund; d6 orbital definition;
     d7 explain config by energy + repulsion; d8 Fe full + shorthand + boxes after [Ar]; d9 ion configs from Z+charge;
     d10 s/p shapes + free radical definition. */
  "t1-3": {
    noteId: "t1-3",
    drills: [
      {
        id: "t1-3-d1",
        noteId: "t1-3",
        kind: "mcq",
        difficulty: 1,
        stem: "How many atomic orbitals are present in a complete p sub-shell?",
        options: [
          { id: "A", text: "3" },
          { id: "B", text: "1" },
          { id: "C", text: "6" },
          { id: "D", text: "5" },
        ],
        correctOptionId: "A",
        explanation:
          "A p sub-shell contains three degenerate p orbitals (different spatial orientations), each of which can hold up to two electrons.",
        distractorRationale: {
          B: "One orbital corresponds to an s sub-shell, not a complete p sub-shell.",
          C: "Six is the maximum number of electrons in a filled p sub-shell (3 orbitals × 2 electrons), not the number of orbitals.",
          D: "Five orbitals correspond to a complete d sub-shell.",
        },
        tags: ["orbitals", "subshells", "9701-1.3"],
      },
      {
        id: "t1-3-d2",
        noteId: "t1-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Which sequence shows sub-shells in order of increasing energy for many-electron atoms up to the point where the 4s and 3d sub-shells are both relevant?",
        options: [
          { id: "A", text: "... 3p, 4s, 3d, 4p" },
          { id: "B", text: "... 3p, 3d, 4s, 4p" },
          { id: "C", text: "... 3p, 4p, 4s, 3d" },
          { id: "D", text: "... 4s, 3p, 3d, 4p" },
        ],
        correctOptionId: "A",
        explanation:
          "For the first transition series region, the usual filling order places 4s below 3d for K/Ca, then 3d fills after 4s, followed by 4p once 3d is being occupied.",
        distractorRationale: {
          B: "Placing 3d entirely before 4s contradicts the observed filling for potassium and calcium, where the outer electron enters 4s first.",
          C: "4p lies above 4s and is not filled before 4s in the ground-state build-up sequence.",
          D: "3p is a lower principal shell than n = 4 sub-shells and is filled earlier, not after 4s.",
        },
        tags: ["subshell-order", "9701-1.3"],
      },
      {
        id: "t1-3-d3",
        noteId: "t1-3",
        kind: "mcq",
        difficulty: 4,
        stem: "What is the maximum number of electrons that can occupy a complete d sub-shell?",
        options: [
          { id: "A", text: "10" },
          { id: "B", text: "6" },
          { id: "C", text: "14" },
          { id: "D", text: "5" },
        ],
        correctOptionId: "A",
        explanation:
          "A d sub-shell contains five d orbitals, and each orbital can hold at most two electrons with opposite spins, so the maximum occupancy is 5 × 2 = 10.",
        distractorRationale: {
          B: "Six is the maximum occupancy of a complete p sub-shell (three orbitals), not a d sub-shell.",
          C: "Fourteen is the maximum occupancy of an f sub-shell (seven orbitals), which is beyond the 1.3 scope here.",
          D: "Five is the number of d orbitals, not the maximum electron count.",
        },
        tags: ["d-orbitals", "9701-1.3"],
      },
      {
        id: "t1-3-d4",
        noteId: "t1-3",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Explain the terms shell, sub-shell and orbital, and state what is meant by the principal quantum number n and by the ground-state electronic configuration of an atom.",
        modelAnswerPoints: [
          "Shell: electrons sharing the same principal quantum number n (same main energy level).",
          "Sub-shell: a set of orbitals of the same type within a shell (s, p, d …) with the same n and same sub-shell label.",
          "Orbital: a region in space (quantum state) holding up to two electrons with opposite spins.",
          "n labels the shell and largely controls size/energy of that shell.",
          "Ground state: lowest total electronic energy arrangement for that atom/ion.",
        ],
        workedSolution: [
          "A shell is a group of electrons that share the same principal quantum number n, which is the main energy level label counting outwards from the nucleus.",
          "A sub-shell is a subdivision within a shell that corresponds to one letter type (s, p, d, …), meaning a set of orbitals with the same n and the same sub-shell identity.",
          "An atomic orbital is a region in space around the nucleus associated with a particular quantum state; each orbital can hold at most two electrons, which must have opposite spins if both are present.",
          "The principal quantum number n is a positive integer that identifies which shell an electron principally belongs to and largely determines how far from the nucleus that shell extends on average.",
          "The ground-state electronic configuration is the way electrons are arranged in orbitals so that the total electronic energy is minimised, obeying the Pauli exclusion principle and Hund's rule where relevant.",
        ],
        commonMistake: "Calling an orbital the same thing as a shell, or treating 'orbital' as a fixed circular orbit.",
        tags: ["definitions", "9701-1.3"],
      },
      {
        id: "t1-3-d5",
        noteId: "t1-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "State how many orbitals make up s, p and d sub-shells, and state the maximum number of electrons that can occupy each of these sub-shells when completely filled.",
        modelAnswerPoints: [
          "s: 1 orbital, maximum 2 electrons.",
          "p: 3 orbitals, maximum 6 electrons.",
          "d: 5 orbitals, maximum 10 electrons.",
        ],
        workedSolution: [
          "An s sub-shell consists of a single s orbital, so there is one orbital and it can contain at most two electrons with paired spins.",
          "A p sub-shell contains three separate p orbitals (oriented along perpendicular axes), so there are three orbitals and a maximum of six electrons when every orbital is doubly occupied.",
          "A d sub-shell contains five d orbitals, so there are five orbitals and a maximum of ten electrons when the d sub-shell is completely filled.",
        ],
        commonMistake: "Confusing the number of orbitals with the maximum electron count, or stating six orbitals for p.",
        tags: ["subshells", "9701-1.3"],
      },
      {
        id: "t1-3-d6",
        noteId: "t1-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Write the full ground-state electron configuration of a phosphorus atom (Z = 15), and describe how many electrons occupy each shell and each sub-shell.",
        modelAnswerPoints: [
          "Full configuration: 1s^2 2s^2 2p^6 3s^2 3p^3.",
          "Shell counts: n = 1 has 2 e-; n = 2 has 8 e-; n = 3 has 5 e-.",
          "Sub-shell counts: 3s^2 and 3p^3 stated explicitly.",
        ],
        workedSolution: [
          "Phosphorus has 15 electrons; filling sub-shells in increasing energy order gives the ground-state configuration 1s^2 2s^2 2p^6 3s^2 3p^3.",
          "By shells, the first shell (n = 1) contains two electrons in 1s, the second shell (n = 2) contains eight electrons in 2s and 2p combined, and the third shell (n = 3) contains five electrons in 3s and 3p combined.",
          "By sub-shells, 1s is filled with two electrons, 2s with two, 2p with six, 3s with two, and the outer 3p sub-shell contains three electrons.",
        ],
        commonMistake: "Writing 3p^5 or placing the 3p electrons as an incorrect pair before occupying separate orbitals in explanations of the ground state.",
        tags: ["configuration", "9701-1.3"],
      },
      {
        id: "t1-3-d7",
        noteId: "t1-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain the ground-state electron configuration of nitrogen (1s^2 2s^2 2p^3) in terms of the relative energies of sub-shells and inter-electron repulsion within the 2p set.",
        modelAnswerPoints: [
          "Lower n and lower-energy sub-shells fill first: 1s, then 2s, then 2p.",
          "Pauli exclusion: maximum two electrons per orbital with opposite spins.",
          "Hund's rule: in degenerate 2p orbitals, electrons occupy separate orbitals singly with parallel spins before pairing, reducing repulsion.",
        ],
        workedSolution: [
          "In nitrogen (Z = 7), seven electrons occupy the lowest-energy available orbitals, so the 1s and 2s sub-shells fill completely before electrons enter 2p because those sub-shells lie lower in energy than 2p for this atom.",
          "The Pauli exclusion principle limits each atomic orbital to two electrons with opposite spins, which is why 1s and 2s each hold two electrons.",
          "For the three electrons in 2p, the three p orbitals are degenerate (equal in energy), so Hund's rule applies: the electrons go into three separate p orbitals with parallel spins before any pairing occurs, which keeps them farther apart on average and reduces electron-electron repulsion compared with pairing two electrons in one orbital prematurely.",
        ],
        commonMistake: "Ignoring Hund's rule and pairing two 2p electrons while leaving another p orbital empty in the claimed 'ground state'.",
        tags: ["energy", "repulsion", "9701-1.3"],
      },
      {
        id: "t1-3-d8",
        noteId: "t1-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "For an iron atom (Z = 26), give the full electron configuration, give the shorthand configuration using the previous noble gas, and represent the outer valence sub-shells after [Ar] using electrons-in-boxes notation (label the 3d and 4s sub-shells).",
        modelAnswerPoints: [
          "Full configuration: 1s^2 2s^2 2p^6 3s^2 3p^6 3d^6 4s^2.",
          "Shorthand: [Ar] 3d^6 4s^2.",
          "Boxes: [Ar] then 4s as one box with up/down; 3d as five boxes with six electrons arranged with maximum unpaired spins first, then pairing (four unpaired + one paired).",
        ],
        workedSolution: [
          "Iron has atomic number 26, so a neutral iron atom contains 26 electrons; the ground-state configuration is built up to give 1s^2 2s^2 2p^6 3s^2 3p^6 3d^6 4s^2 when written in full.",
          "Argon (Z = 18) has configuration 1s^2 2s^2 2p^6 3s^2 3p^6, so iron can be written in shorthand as [Ar] 3d^6 4s^2, meaning the argon core plus six electrons in 3d and two in 4s.",
          "In electrons-in-boxes form after [Ar], label the 4s sub-shell as a single box containing one up-spin and one down-spin electron, representing 4s^2.",
          "Label the 3d sub-shell as five boxes; place six electrons so that five go singly with parallel spins across the five boxes first, then the sixth pairs in one box, giving four unpaired and one pair overall, matching 3d^6 in the ground state.",
        ],
        commonMistake: "Writing [Ar] 3d^8 without transferring electrons correctly, or drawing 3d as fully paired when six electrons still leave four unpaired electrons in the ground state.",
        tags: ["iron", "boxes", "9701-1.3"],
      },
      {
        id: "t1-3-d9",
        noteId: "t1-3",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Write the ground-state electron configuration of a Cu+ ion (Z = 29 for copper) and of a Fe2+ ion (Z = 26 for iron), using the usual 3d/4s filling rules for the neutral atoms as your starting point.",
        modelAnswerPoints: [
          "Neutral Cu is [Ar] 3d^10 4s^1; Cu+ removes the 4s electron -> [Ar] 3d^10.",
          "Neutral Fe is [Ar] 3d^6 4s^2; Fe2+ removes 4s electrons first -> [Ar] 3d^6.",
        ],
        workedSolution: [
          "A copper atom is [Ar] 3d^10 4s^1 in its ground state, which is the expected exceptional filling for copper.",
          "When Cu+ forms, the electron removed first comes from the 4s sub-shell because it is the outermost sub-shell occupied in the neutral atom, leaving [Ar] 3d^10 for Cu+.",
          "An iron atom is [Ar] 3d^6 4s^2 in its ground state.",
          "When Fe2+ forms, the two electrons removed come from the 4s sub-shell first (both 4s electrons), leaving the 3d sub-shell unchanged at six electrons, so Fe2+ is [Ar] 3d^6.",
        ],
        commonMistake: "Removing a 3d electron before the 4s electrons when forming Fe2+, or leaving Cu+ as [Ar] 3d^9 4s^1.",
        tags: ["ions", "configuration", "9701-1.3"],
      },
      {
        id: "t1-3-d10",
        noteId: "t1-3",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "Describe and sketch the shapes of s and p atomic orbitals, and define a free radical in terms of electrons.",
        modelAnswerPoints: [
          "s orbital: spherically symmetric about the nucleus.",
          "p orbital: dumbbell-shaped along an axis with a nodal plane through the nucleus.",
          "Sketch implied: sphere for s; dumbbell along one axis for one p orbital (label nucleus / axes).",
          "Free radical: species with one or more unpaired electrons.",
        ],
        workedSolution: [
          "An s orbital has spherical symmetry: the electron probability is the same in all directions at a given distance from the nucleus, so sketches are drawn as a sphere centred on the nucleus.",
          "A p orbital has a dumbbell shape along one axis (for example pz along the z-axis), with two lobes on opposite sides of the nucleus and a nodal plane through the nucleus where electron density falls to zero.",
          "In an exam-style sketch, draw a circle or sphere labelled s around the nucleus for the s orbital, and two lobes on opposite sides of a central point for a p orbital, showing the nucleus at the centre and a plane separating the lobes.",
          "A free radical is defined as a species that contains one or more unpaired electrons, for example a chlorine atom Cl• with seven valence electrons including one unpaired electron in its outer sub-shell.",
        ],
        commonMistake: "Drawing p orbitals without a nodal plane through the nucleus, or defining radicals only as 'reactive' without mentioning unpaired electrons.",
        tags: ["shapes", "radicals", "9701-1.3"],
      },
    ],
    flashcards: [
      {
        id: "t1-3-f1",
        noteId: "t1-3",
        difficulty: 1,
        front: "Maximum electrons in one orbital?",
        back: "Two (opposite spins) by the Pauli exclusion principle.",
        examPhrasing: "State the maximum electron occupancy of a single orbital.",
        tags: ["pauli"],
      },
      {
        id: "t1-3-f2",
        noteId: "t1-3",
        difficulty: 1,
        front: "Typical sub-shell filling order up to 4p?",
        back: "1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p (for the build-up sequence used at AS/A).",
        examPhrasing: "State the order of increasing energy of sub-shells up to 4p.",
        tags: ["subshell-order"],
      },
      {
        id: "t1-3-f3",
        noteId: "t1-3",
        difficulty: 2,
        front: "Degenerate orbitals?",
        back: "Orbitals in the same sub-shell with the same energy (before splitting in fields).",
        examPhrasing: "Define degenerate orbitals.",
        tags: ["definitions"],
      },
      {
        id: "t1-3-f4",
        noteId: "t1-3",
        difficulty: 2,
        front: "Ground state vs excited state?",
        back: "Ground state is lowest overall energy; excited states have electrons promoted to higher levels.",
        examPhrasing: "Explain what is meant by an excited electronic state.",
        tags: ["energy-levels"],
      },
      {
        id: "t1-3-f5",
        noteId: "t1-3",
        difficulty: 3,
        front: "Why does Hund's rule matter for p^3?",
        back: "Keeps electrons unpaired in separate p orbitals with parallel spins, minimising repulsion.",
        examPhrasing: "Apply Hund's rule to nitrogen.",
        tags: ["hunds-rule"],
      },
      {
        id: "t1-3-f6",
        noteId: "t1-3",
        difficulty: 3,
        front: "d sub-shell: how many orbitals and electrons max?",
        back: "Five d orbitals; maximum 10 electrons.",
        examPhrasing: "State the number of orbitals in a d sub-shell.",
        tags: ["d-orbitals"],
      },
      {
        id: "t1-3-f7",
        noteId: "t1-3",
        difficulty: 4,
        front: "Chromium atom ground configuration?",
        back: "[Ar] 3d^5 4s^1 (half-filled d plus one 4s electron is unusually stable).",
        examPhrasing: "Write the electron configuration of chromium.",
        confusionPair: "Cr vs Cu exceptions",
        tags: ["exceptions"],
      },
      {
        id: "t1-3-f8",
        noteId: "t1-3",
        difficulty: 4,
        front: "What is a free radical?",
        back: "A species with one or more unpaired electrons (e.g. Cl•).",
        examPhrasing: "Define a free radical.",
        tags: ["radicals"],
      },
      {
        id: "t1-3-f9",
        noteId: "t1-3",
        difficulty: 5,
        front: "Fe2+ electron configuration?",
        back: "[Ar] 3d^6 (remove 4s electrons first from neutral Fe [Ar] 3d^6 4s^2).",
        examPhrasing: "Write the configuration of the iron(II) ion.",
        tags: ["ions"],
      },
      {
        id: "t1-3-f10",
        noteId: "t1-3",
        difficulty: 5,
        front: "Shape of a p orbital?",
        back: "Dumbbell with a nodal plane through the nucleus separating two lobes.",
        examPhrasing: "Describe the shape of a p orbital.",
        tags: ["shapes"],
      },
    ],
  },

  /* 1.4 Ionisation energy — LO map: d1 first IE definition MCQ; d2 Be vs B MCQ; d3 Mg vs Al MCQ;
     d4 define first IE + Mg equation; d5 attraction + factors (Z, radius, shielding, spin-pair); d6 trend down a group;
     d7 N vs O + pairing; d8 second+third IE equations (Al); d9 large 2nd IE jump (Na); d10 deduce group/config from successive IE jumps. */
  "t1-4": {
    noteId: "t1-4",
    drills: [
      {
        id: "t1-4-d1",
        noteId: "t1-4",
        kind: "mcq",
        difficulty: 1,
        stem: "First ionisation energy is defined as the energy required to …",
        options: [
          { id: "A", text: "Remove one mole of electrons from one mole of gaseous atoms to form one mole of gaseous 1+ ions" },
          { id: "B", text: "Remove one mole of electrons from one mole of solid atoms" },
          { id: "C", text: "Add one mole of electrons to one mole of gaseous atoms" },
          { id: "D", text: "Remove all electrons from one mole of gaseous atoms" },
        ],
        correctOptionId: "A",
        explanation:
          "The standard definition uses gaseous atoms forming gaseous monatomic ions, per mole, for the first electron removed.",
        distractorRationale: {
          B: "The standard enthalpy definition uses gaseous atoms, not the solid lattice.",
          C: "Electron affinity refers to electron gain, not ionisation.",
          D: "Successive removals have separate successive ionisation energies.",
        },
        tags: ["definition", "first-ie"],
      },
      {
        id: "t1-4-d2",
        noteId: "t1-4",
        kind: "mcq",
        difficulty: 3,
        stem: "Why is the first ionisation energy of boron lower than that of beryllium?",
        options: [
          {
            id: "A",
            text: "The electron removed from boron is a higher-energy 2p electron, which is more shielded from the nucleus than beryllium's outer 2s electrons",
          },
          { id: "B", text: "Boron has a smaller nuclear charge than beryllium" },
          { id: "C", text: "Beryllium loses a 2p electron whereas boron loses a 2s electron" },
          { id: "D", text: "Boron has a half-filled 2p sub-shell, which makes it unusually stable" },
        ],
        correctOptionId: "A",
        explanation:
          "Across Be to B, nuclear charge increases, but the outer electron configuration changes from 2s^2 to 2s^2 2p^1; the electron removed first from boron is the single 2p electron, which is higher in energy and more shielded by the filled 2s sub-shell than the 2s electrons in beryllium.",
        distractorRationale: {
          B: "Boron has a greater atomic number (more protons) than beryllium, so nuclear charge does not decrease.",
          C: "Beryllium's first ionisation removes a 2s electron; boron's first ionisation removes the 2p electron.",
          D: "A half-filled 2p sub-shell would be 2p^3 (nitrogen), not boron 2p^1.",
        },
        tags: ["be-b-anomaly", "period-2", "9701-1.4"],
      },
      {
        id: "t1-4-d3",
        noteId: "t1-4",
        kind: "mcq",
        difficulty: 5,
        stem: "Why is the first ionisation energy of aluminium lower than that of magnesium?",
        options: [
          { id: "A", text: "The electron removed from Al is from a higher-energy 3p subshell with more shielding from the 3s electrons" },
          { id: "B", text: "Al has fewer protons than Mg" },
          { id: "C", text: "Mg loses a 3p electron whereas Al loses a 3s electron" },
          { id: "D", text: "Al is more electronegative so it holds electrons more tightly" },
        ],
        correctOptionId: "A",
        explanation:
          "The outer electron in Al is 3p^1, higher in energy and farther on average than Mg's 3s^2 outermost electron in a full subshell.",
        distractorRationale: {
          B: "Aluminium has a higher atomic number than magnesium.",
          C: "It is aluminium that loses the 3p electron more readily in the first ionisation.",
          D: "Higher IE for Mg contradicts 'holds more tightly' for Al here.",
        },
        tags: ["exceptions", "mg-al"],
      },
      {
        id: "t1-4-d4",
        noteId: "t1-4",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Define the term first ionisation energy, IE, for an element, and write the equation, including state symbols, that represents the first ionisation energy of magnesium.",
        modelAnswerPoints: [
          "First IE is the energy required to remove one mole of electrons from one mole of gaseous atoms to form one mole of gaseous 1+ ions.",
          "Equation: Mg(g) -> Mg+(g) + e- (or equivalent with one electron product).",
          "States: gaseous atom and gaseous ion required.",
        ],
        workedSolution: [
          "The first ionisation energy, IE, is the energy required to remove one mole of electrons from one mole of gaseous atoms of the element to form one mole of gaseous monatomic ions each carrying a single positive charge.",
          "For magnesium this process is represented by the equation Mg(g) -> Mg+(g) + e-, which shows one electron being removed from one gaseous magnesium atom to give a gaseous magnesium ion.",
          "State symbols must be (g) for both the magnesium atom and the magnesium ion, because ionisation energy is defined for gaseous species under standard conditions used in data tables.",
        ],
        commonMistake: "Using Mg(s) or omitting state symbols; writing Mg2+ for the first ionisation.",
        tags: ["equation", "definition", "first-ie", "9701-1.4"],
      },
      {
        id: "t1-4-d5",
        noteId: "t1-4",
        kind: "structured",
        difficulty: 2,
        marks: 7,
        stem: "State the general trend in first ionisation energy across a period from left to right. Explain why ionisation energy arises from electrostatic attraction between the nucleus and the electron removed, and outline how nuclear charge, atomic radius, shielding by inner shells and sub-shells, and spin-pair repulsion influence the value observed (including why small reversals can occur between neighbouring elements).",
        modelAnswerPoints: [
          "General trend: first IE increases across a period (with small dips at Group 13 and Group 16 in Periods 2 and 3).",
          "Ionisation works against attraction between nucleus (+) and the electron (−) being removed.",
          "Higher nuclear charge tends to increase attraction if distance/shielding are similar.",
          "Larger atomic/ionic radius places the outer electron farther from the nucleus, weakening attraction and tending to lower IE.",
          "Shielding by inner shells and sub-shells reduces the effective nuclear charge felt by the outer electron.",
          "Spin-pair repulsion in the same orbital makes a paired electron easier to remove than an unpaired one in a degenerate set.",
        ],
        workedSolution: [
          "Across a period from left to right, first ionisation energy generally increases because protons are added to the nucleus while outer electrons remain in the same principal shell, so the outer electrons are attracted more strongly on average; however, small decreases occur between beryllium and boron and between nitrogen and oxygen in Period 2 (and analogous features in Period 3) because sub-shell energy and pairing effects modify the simple trend.",
          "Ionisation energy is the energy needed to remove an electron from a gaseous species, and that process must overcome the electrostatic attraction between the positively charged nucleus and the negatively charged electron being removed.",
          "If nuclear charge increases while the electron being removed remains at a similar distance and shielding does not increase enough to compensate, the attraction becomes stronger and the ionisation energy tends to increase.",
          "If the atomic radius is larger, the outer electron is on average farther from the nucleus, so the electrostatic attraction is weaker and the ionisation energy tends to be lower.",
          "Inner-shell electrons shield the outer electron from the full nuclear charge, and shielding can also depend on which sub-shells lie between the nucleus and the outer electron, so changes in shielding alter the effective nuclear charge experienced by the electron being removed.",
          "Where electrons are paired in the same orbital, spin-pair repulsion increases the electron-electron repulsion energy, so one of the paired electrons can be removed more easily than if it were unpaired in a set of degenerate orbitals, which is why pairing effects can reverse simple trends between neighbouring elements.",
        ],
        commonMistake: "Listing factors without linking each one to stronger or weaker attraction for the specific electron being removed.",
        tags: ["ionisation-energy", "factors", "9701-1.4"],
      },
      {
        id: "t1-4-d6",
        noteId: "t1-4",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain why first ionisation energy decreases going down Group 1 from lithium to caesium.",
        modelAnswerPoints: [
          "Down the group the outer electron is in a higher principal quantum shell each time.",
          "Outer electron is on average farther from the nucleus.",
          "Increased shielding from extra inner shells reduces effective nuclear charge experienced by the outer electron.",
          "Weaker net attraction despite increasing nuclear charge leads to lower first IE.",
        ],
        workedSolution: [
          "Down Group 1 from lithium to caesium, each successive element has its single valence electron in a new, higher principal shell further from the nucleus than in the element above it.",
          "Because the outer electron is on average farther from the nucleus, the electrostatic attraction between that electron and the nucleus becomes weaker if we ignored other effects.",
          "There are also more occupied inner shells beneath the outer electron, and these inner electrons shield the outer electron from the full nuclear charge, reducing the effective nuclear charge it experiences.",
          "Although the actual nuclear charge Z increases down the group, the combined effects of increased distance and increased shielding dominate for the outer ns electron, so the first ionisation energy decreases down Group 1.",
        ],
        commonMistake: "Claiming IE increases down the group because Z increases, without discussing distance and shielding.",
        tags: ["groups", "trends", "9701-1.4"],
      },
      {
        id: "t1-4-d7",
        noteId: "t1-4",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "Explain why first ionisation energy decreases from nitrogen to oxygen, and also decreases from phosphorus to sulfur, using electron configurations in each case.",
        modelAnswerPoints: [
          "N (2p^3) half-filled p sub-shell is relatively stable.",
          "O (2p^4) forces pairing in one 2p orbital -> spin-pair repulsion makes removal easier.",
          "P (3p^3) half-filled p sub-shell is relatively stable.",
          "S (3p^4) forces pairing in one 3p orbital -> spin-pair repulsion makes removal easier.",
        ],
        workedSolution: [
          "Nitrogen has ground-state configuration 1s^2 2s^2 2p^3, and the 2p sub-shell is half-filled with one electron in each of the three degenerate p orbitals, which is a particularly stable arrangement.",
          "Oxygen is 1s^2 2s^2 2p^4, so the fourth 2p electron must pair with an electron already occupying one of the 2p orbitals, increasing electron-electron repulsion in that orbital; the paired electron is therefore easier to remove than any of the singly occupied 2p electrons in nitrogen, giving oxygen a lower first ionisation energy despite its higher nuclear charge.",
          "Phosphorus has configuration 1s^2 2s^2 2p^6 3s^2 3p^3, and the 3p sub-shell is again half-filled with three unpaired electrons in separate p orbitals, which is relatively stable.",
          "Sulfur is 1s^2 2s^2 2p^6 3s^2 3p^4, so pairing occurs in one 3p orbital, introducing extra repulsion and making the easiest electron to remove slightly less tightly bound than in phosphorus, so sulfur has a lower first ionisation energy than phosphorus.",
        ],
        commonMistake: "Arguing only from increasing nuclear charge across the period, without mentioning half-filled stability and pairing repulsion for these two pairs.",
        tags: ["n-o-anomaly", "p-s-anomaly", "9701-1.4"],
      },
      {
        id: "t1-4-d8",
        noteId: "t1-4",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Define the second and third ionisation energies of an element, and write balanced equations with state symbols for the second and third ionisation processes for an aluminium atom (start from Al(g)).",
        modelAnswerPoints: [
          "Second IE: remove 1 mol e- from 1 mol gaseous 1+ ions to form 1 mol gaseous 2+ ions.",
          "Third IE: remove 1 mol e- from 1 mol gaseous 2+ ions to form 1 mol gaseous 3+ ions.",
          "Al+(g) -> Al2+(g) + e- for second ionisation of aluminium.",
          "Al2+(g) -> Al3+(g) + e- for third ionisation of aluminium.",
        ],
        workedSolution: [
          "The second ionisation energy is the energy required to remove one mole of electrons from one mole of gaseous monatomic ions with charge 1+ to form one mole of gaseous monatomic ions with charge 2+.",
          "The third ionisation energy is the energy required to remove one mole of electrons from one mole of gaseous monatomic ions with charge 2+ to form one mole of gaseous monatomic ions with charge 3+.",
          "For aluminium, the first ionisation begins from Al(g), but the second ionisation step is written as Al+(g) -> Al2+(g) + e-, because a gaseous Al+ ion loses one electron to become gaseous Al2+.",
          "The third ionisation step is Al2+(g) -> Al3+(g) + e-, showing removal of one electron from a gaseous 2+ ion to form a gaseous 3+ ion, with all species given the (g) state symbol as required by the definition.",
        ],
        commonMistake: "Writing the second ionisation starting from Al(g) again, or omitting (g) on the ions.",
        tags: ["successive-ie", "equations", "9701-1.4"],
      },
      {
        id: "t1-4-d9",
        noteId: "t1-4",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Suggest why the second ionisation energy of sodium is very much larger than its first ionisation energy.",
        modelAnswerPoints: [
          "Second electron is removed from a stable noble-gas core configuration (Ne-like).",
          "Much higher effective nuclear charge on a core electron (or electron much closer / lower n).",
          "Large energy jump compared with removing the single valence electron in the first step.",
        ],
        workedSolution: [
          "The first ionisation of sodium removes the single 3s valence electron, leaving Na+ with a neon-like core configuration 1s^2 2s^2 2p^6.",
          "The second electron must be removed from that stable, inner noble-gas shell, where it is much closer to the nucleus and much more strongly held.",
          "Therefore a very large increase in ionisation energy is observed between the first and second values.",
        ],
        commonMistake: "Saying only 'more charge' without referencing inner-shell removal after first IE.",
        tags: ["sodium", "successive-ie"],
      },
      {
        id: "t1-4-d10",
        noteId: "t1-4",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "The successive ionisation energies of a Period 3 element E (in kJ mol^-1) begin: 578, 1820, 2750, 11 600, 14 800, 18 400, 23 400, 27 500, 32 000, 38 600, 42 700, 49 400, 53 900, 57 300. Identify the very large jump that marks removal of a core electron after the valence shell is exhausted, deduce the number of valence electrons, state which group of the Periodic Table E belongs to, and write the full ground-state electron configuration of a neutral E atom.",
        modelAnswerPoints: [
          "Large jump occurs between the 3rd and 4th ionisation energies (2750 -> 11 600).",
          "Interpretation: first three electrons are valence electrons; 4th electron is removed from a much lower shell (inner core).",
          "Three valence electrons implies Group 13 in Period 3, so E is aluminium.",
          "Full configuration: 1s^2 2s^2 2p^6 3s^2 3p^1.",
        ],
        workedSolution: [
          "Looking along the successive values, the increases between the first three ionisations are relatively moderate compared with the step from the third value (2750 kJ mol^-1) to the fourth value (11 600 kJ mol^-1), which is a very large jump.",
          "A jump of this size means the fourth electron is being removed from an inner, much more tightly bound shell after the three least tightly bound (valence) electrons have already been removed.",
          "Therefore this atom has three valence electrons; for a Period 3 element, three valence electrons corresponds to Group 13, so the element is aluminium.",
          "A neutral aluminium atom (Z = 13) therefore has the ground-state configuration 1s^2 2s^2 2p^6 3s^2 3p^1, which matches three electrons outside the neon core that are removed before the large jump when a 2p electron must be taken from the inner core.",
        ],
        commonMistake: "Choosing the wrong jump (for example after the first electron only) or assigning Group 3 based on counting without tying the jump to inner-shell removal.",
        tags: ["successive-ie", "deduction", "9701-1.4"],
      },
    ],
    flashcards: [
      {
        id: "t1-4-f1",
        noteId: "t1-4",
        difficulty: 1,
        front: "First ionisation energy: standard conditions phrase?",
        back: "One mole of gaseous atoms loses one mole of electrons to form one mole of gaseous +1 ions.",
        examPhrasing: "Define first ionisation energy.",
        tags: ["definition"],
      },
      {
        id: "t1-4-f2",
        noteId: "t1-4",
        difficulty: 1,
        front: "General IE trend across a period?",
        back: "Increases (with small dips at Group 13 and Group 16 in Periods 2 and 3).",
        examPhrasing: "Describe the trend in first ionisation energy across Period 3.",
        tags: ["trends"],
      },
      {
        id: "t1-4-f3",
        noteId: "t1-4",
        difficulty: 2,
        front: "Why IE decreases down a group?",
        back: "Outer electron farther out and more shielded; weaker attraction despite rising Z.",
        examPhrasing: "Explain the trend in first ionisation energy down Group 17.",
        tags: ["groups"],
      },
      {
        id: "t1-4-f4",
        noteId: "t1-4",
        difficulty: 2,
        front: "Successive IE: what happens to values?",
        back: "Each step is larger; large jumps occur when removing a core electron after a noble-gas-like shell is left.",
        examPhrasing: "Describe successive ionisation energies for an element.",
        tags: ["successive-ie"],
      },
      {
        id: "t1-4-f5",
        noteId: "t1-4",
        difficulty: 3,
        front: "N vs O first IE?",
        back: "N higher than O: half-filled 2p^3 stability vs pairing repulsion in 2p^4.",
        examPhrasing: "Explain why nitrogen has a higher first ionisation energy than oxygen.",
        confusionPair: "N/O vs B/Be direction",
        tags: ["anomalies"],
      },
      {
        id: "t1-4-f6",
        noteId: "t1-4",
        difficulty: 3,
        front: "Mg vs Al first IE?",
        back: "Mg higher: 3s electron removed; Al loses higher-energy, more shielded 3p electron.",
        examPhrasing: "Explain the Mg to Al change in first ionisation energy across Period 3.",
        tags: ["mg-al"],
      },
      {
        id: "t1-4-f7",
        noteId: "t1-4",
        difficulty: 4,
        front: "IE vs electron affinity: sign convention at AS?",
        back: "Ionisation energy is positive energy supplied to remove an electron; electron affinity definitions vary but concern adding an electron.",
        examPhrasing: "Distinguish ionisation energy from electron affinity.",
        tags: ["definitions"],
      },
      {
        id: "t1-4-f8",
        noteId: "t1-4",
        difficulty: 4,
        front: "Why is Ne's first IE very high?",
        back: "Closed-shell noble gas configuration; removing an electron disrupts a stable full valence shell.",
        examPhrasing: "Explain a high first ionisation energy for a noble gas.",
        tags: ["noble-gases"],
      },
      {
        id: "t1-4-f9",
        noteId: "t1-4",
        difficulty: 5,
        front: "Li vs Be first IE?",
        back: "Be higher: greater nuclear charge, same shell; outer 2s electron held more tightly.",
        examPhrasing: "Explain the increase from lithium to beryllium in first ionisation energy.",
        tags: ["period-2"],
      },
      {
        id: "t1-4-f10",
        noteId: "t1-4",
        difficulty: 5,
        front: "Equation for third IE of aluminium?",
        back: "Al2+(g) -> Al3+(g) + e- (all species gaseous).",
        examPhrasing: "Write an equation for the third ionisation energy of aluminium.",
        tags: ["equations"],
      },
    ],
  },
};
