import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 9 — Periodicity (9.1–9.3). Crosswalk (internal LO phrasing):
 *
 * t9-1 (9.1): atomic/ionic radius, melting point, conductivity — qualitative description + structure/bonding
 * explanations for melting and conductivity.
 *
 * t9-2 (9.2): Period 3 elements with O2, Cl2, H2O (Na, Mg); oxide/chloride oxidation numbers; oxides + water + pH;
 * acid/base behaviour of listed oxides and NaOH, Mg(OH)2, Al(OH)3 (amphoteric with NaOH); chlorides + water + pH;
 * trends via bonding/electronegativity; deduce bonding from observations.
 *
 * t9-3 (9.3): predict group properties; deduce position/identity from physical + chemical evidence.
 */
export const CHEMISTRY_TOPIC9_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t9-1": {
    noteId: "t9-1",
    drills: [
      {
        id: "t9-1-d1",
        noteId: "t9-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State what is meant by atomic radius in Period 3, and describe qualitatively how atomic radius changes from sodium to chlorine along the period.",
        modelAnswerPoints: [
          "Atomic radius is a measure of the size of the atom (distance from nucleus to outer shell electrons being considered).",
          "Atomic radius decreases from sodium to chlorine across Period 3.",
          "Nuclear charge increases while electrons are added to the same principal shell, so shielding does not fully offset the greater attraction and the outer electron cloud is pulled inward.",
        ],
        workedSolution: [
          "Atomic radius refers to the size of a gaseous atom, usually represented as the distance from the nucleus to the outermost electrons in the shell that is being filled along Period 3.",
          "Across Period 3 from sodium to chlorine, atomic radius decreases steadily as proton number increases from left to right.",
          "Each successive atom adds one proton and one electron, but the extra electron enters the same principal quantum shell as before, so inner-shell shielding changes little while nuclear charge rises, the effective nuclear charge felt by the valence shell increases, and the valence electrons are held closer to the nucleus.",
        ],
        commonMistake:
          "Saying radius increases because more electrons are added, without stating that they enter the same shell and that nuclear charge rises faster than shielding.",
        tags: ["atomic-radius", "period-3", "definitions"],
      },
      {
        id: "t9-1-d2",
        noteId: "t9-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define metallic bonding and explain briefly why sodium, magnesium and aluminium in Period 3 are described as having giant metallic structures.",
        modelAnswerPoints: [
          "Metallic bonding is the electrostatic attraction between a lattice of positive metal ions and a delocalised sea of electrons from the outer shell.",
          "The electrons are mobile over the whole structure, not confined between two named atoms only.",
          "Na, Mg and Al each form a continuous lattice of metal ions held by that attraction, which is what is meant by giant metallic.",
        ],
        workedSolution: [
          "Metallic bonding is the strong electrostatic attraction between a regular array of positive metal ions and a delocalised sea of outer-shell electrons that belong to the structure as a whole rather than to individual atom pairs.",
          "Because the electrons are delocalised, they can move through the lattice when a potential difference is applied, which is why metallic bonding is linked to electrical conduction in solid metals.",
          "Sodium, magnesium and aluminium each crystallise as a giant lattice of metal ions of increasing charge (Na+, Mg2+, Al3+) permeated by the electron sea, so each is classified as a giant metallic structure rather than a collection of separate small molecules.",
        ],
        commonMistake: "Describing metallic bonding only as atoms sharing electrons without mentioning cations plus a delocalised sea.",
        tags: ["metallic-bonding", "definitions", "period-3"],
      },
      {
        id: "t9-1-d3",
        noteId: "t9-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Describe qualitatively how ionic radius varies for the common ions Na+, Mg2+ and Al3+ in Period 3, and explain the trend in terms of nuclear charge and electron count.",
        modelAnswerPoints: [
          "All three ions are isoelectronic with the neon configuration (10 electrons).",
          "Ionic radius decreases in the order Na+ > Mg2+ > Al3+.",
          "With the same electron arrangement, greater nuclear charge pulls the same electron cloud more tightly inward.",
        ],
        workedSolution: [
          "Sodium, magnesium and aluminium form cations Na+, Mg2+ and Al3+ that all have ten electrons arranged like neon, so they are isoelectronic: the electron count and shell filling are identical in each ion.",
          "Despite that similarity, the nuclear charge rises from 11 protons in Na+ to 12 in Mg2+ to 13 in Al3+, so the same ten-electron cloud experiences progressively stronger attraction from the nucleus.",
          "Therefore the ionic radius decreases across the series in the order Na+ largest, then Mg2+, then Al3+ smallest, because a larger nuclear charge pulls the isoelectronic electron density closer without adding extra shells that would increase shielding distance.",
        ],
        commonMistake: "Claiming Al3+ is largest because aluminium atoms start with more protons in the neutral atom, without comparing the isoelectronic electron count in the ion.",
        tags: ["ionic-radius", "isoelectronic", "period-3"],
      },
      {
        id: "t9-1-d4",
        noteId: "t9-1",
        kind: "mcq",
        difficulty: 2,
        stem: "For the isoelectronic ions Na+, Mg2+ and Al3+, what is the order of increasing ionic radius?",
        options: [
          { id: "A", text: "Na+ < Mg2+ < Al3+" },
          { id: "B", text: "Al3+ < Mg2+ < Na+" },
          { id: "C", text: "Mg2+ < Na+ < Al3+" },
          { id: "D", text: "Al3+ < Na+ < Mg2+" },
        ],
        correctOptionId: "B",
        explanation:
          "Same electron count: greater nuclear charge contracts the electron cloud, so the smallest ion is Al3+ and the largest is Na+.",
        distractorRationale: {
          A: "This order reverses the true size sequence for the isoelectronic set.",
          C: "Na+ cannot be the smallest ion here; it has the lowest nuclear charge among the three.",
          D: "Mg2+ lies between Al3+ and Na+ in ionic radius, not outside that ordering.",
        },
        tags: ["ionic-radius", "isoelectronic"],
      },
      {
        id: "t9-1-d5",
        noteId: "t9-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which Period 3 allotrope is correctly described as simple molecular?",
        options: [
          { id: "A", text: "Silicon" },
          { id: "B", text: "White phosphorus (P4)" },
          { id: "C", text: "Magnesium" },
          { id: "D", text: "Sodium" },
        ],
        correctOptionId: "B",
        explanation:
          "P4 exists as separate P4 molecules held by intermolecular forces; silicon is a giant covalent network and the metals are giant metallic lattices.",
        distractorRationale: {
          A: "Silicon is giant covalent, not simple molecular.",
          C: "Magnesium is giant metallic.",
          D: "Sodium is giant metallic.",
        },
        tags: ["structure", "period-3"],
      },
      {
        id: "t9-1-d6",
        noteId: "t9-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Why does silicon have a much higher melting point than phosphorus (P4)?",
        options: [
          { id: "A", text: "Silicon atoms are heavier" },
          { id: "B", text: "Silicon has a giant covalent network; P4 is simple molecular" },
          { id: "C", text: "Silicon has metallic bonding" },
          { id: "D", text: "P4 has stronger covalent bonds than silicon" },
        ],
        correctOptionId: "B",
        explanation:
          "Melting silicon requires breaking very many strong covalent bonds throughout the lattice, whereas melting P4 mainly overcomes weaker forces between molecules.",
        distractorRationale: {
          A: "Atomic mass alone does not determine melting point when bonding type changes.",
          C: "Silicon is not a metal and does not show metallic bonding.",
          D: "The comparison relevant to melting is giant network versus intermolecular forces, not a claim that P-P bonds exceed Si-Si network bonding in bulk melting behaviour.",
        },
        tags: ["melting-point", "bonding", "structure"],
      },
      {
        id: "t9-1-d7",
        noteId: "t9-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain the variation in electrical conductivity from sodium to argon across Period 3 (include silicon), using the structure and bonding of the elements in each region of the period.",
        modelAnswerPoints: [
          "Na, Mg and Al are metals with giant metallic structures and delocalised electrons, so they conduct electricity well in the solid state.",
          "Silicon is giant covalent and is a semiconductor at room temperature: only a limited number of charge carriers compared with a metal.",
          "P4, S8, Cl2 and Ar do not conduct in the metallic sense because they lack a mobile delocalised electron sea; simple molecular and monatomic argon have no free electrons or ions to carry current through the bulk.",
        ],
        workedSolution: [
          "Sodium, magnesium and aluminium each form a giant metallic lattice in which outer electrons are delocalised over the whole crystal, so when a potential difference is applied those electrons can move through the structure and sustain an electric current, which is why these three elements are good electrical conductors.",
          "Silicon is a giant covalent element in which every silicon atom is covalently bonded in a three-dimensional network; at room temperature only a small fraction of electrons can be promoted into conduction-like states, so silicon conducts much less well than the metals and is classified as a semiconductor whose conductivity rises if the temperature is increased enough to create more charge carriers.",
          "White phosphorus, sulfur and chlorine exist as simple molecular structures in the standard allotropes considered here, and argon is monatomic; none of these arrangements provides a delocalised sea of electrons or mobile ions through the bulk, so they do not show metallic conduction and are treated as electrical non-conductors in the same sense as the metals.",
        ],
        commonMistake: "Calling silicon a metal, or claiming that chlorine molecules conduct electricity like metals because they contain covalent bonds.",
        tags: ["conductivity", "period-3", "structure"],
      },
      {
        id: "t9-1-d8",
        noteId: "t9-1",
        kind: "mcq",
        difficulty: 3,
        stem: "For the isoelectronic anions P3-, S2- and Cl-, which has the largest ionic radius?",
        options: [
          { id: "A", text: "Cl-" },
          { id: "B", text: "S2-" },
          { id: "C", text: "P3-" },
          { id: "D", text: "They are all equal" },
        ],
        correctOptionId: "C",
        explanation:
          "Each ion has 18 electrons; P3- has the smallest nuclear charge in the set, so the electron cloud is least tightly bound and the ion is largest.",
        distractorRationale: {
          A: "Cl- has the highest nuclear charge here, so it is the smallest of the three anions.",
          B: "S2- is intermediate in size between P3- and Cl-.",
          D: "Nuclear charge differs, so the radii cannot all be equal.",
        },
        tags: ["ionic-radius", "isoelectronic"],
      },
      {
        id: "t9-1-d9",
        noteId: "t9-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Describe qualitatively the periodicity across Period 3 from sodium to argon in atomic radius, ionic radius (for the common ions Na+, Mg2+ and Al3+), melting point and electrical conductivity, naming the main structural type for each element where it helps your answer.",
        modelAnswerPoints: [
          "Atomic radius decreases from Na to Cl (argon follows the same outer-shell closure idea for the period end).",
          "For Na+, Mg2+, Al3+, ionic radius decreases with increasing cation charge at constant electron count.",
          "Melting point is not monotonic: it rises through the metals to a maximum at silicon, then falls sharply to molecular phosphorus and remains relatively low through sulfur, chlorine and argon.",
          "Conductivity is high for Na–Al metals, much lower for semiconducting silicon, and negligible for phosphorus, sulfur, chlorine and argon in the usual allotropes.",
        ],
        workedSolution: [
          "Atomic radius decreases from sodium toward chlorine along Period 3 because nuclear charge increases while valence electrons are added into the same principal shell, so the outer electron cloud is drawn inward; argon completes the valence octet for the period and is smaller than sodium but the detailed comparison used in examinations is usually emphasised from Na to Cl for the radius decrease.",
          "For the common cations Na+, Mg2+ and Al3+, all ten-electron species, ionic radius decreases from Na+ to Al3+ because nuclear charge rises while the electron count stays the same, so the cation becomes progressively more compact.",
          "Melting point shows strong periodicity tied to structure: melting increases from sodium toward aluminium as metallic bonding strengthens, reaches a sharp maximum at silicon where a giant covalent network must be disrupted, then drops steeply to phosphorus and stays comparatively low for sulfur and chlorine where only intermolecular forces between molecules are overcome, with argon lowest as monatomic atoms held only by weak dispersion forces.",
          "Electrical conductivity mirrors bonding type: sodium to aluminium conduct well as metals, silicon conducts poorly at room temperature compared with those metals because conduction depends on limited charge carriers in a covalent network, and phosphorus, sulfur, chlorine and argon show no useful metallic conduction because they lack a delocalised electron sea in their standard structures.",
        ],
        commonMistake: "Treating melting point or conductivity as simple smooth trends that follow only nuclear charge, without the change from metallic to giant covalent to simple molecular to monatomic structures.",
        tags: ["periodicity", "melting-point", "conductivity", "radius"],
      },
      {
        id: "t9-1-d10",
        noteId: "t9-1",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "Explain the variation in melting point across Period 3 from sodium to argon in terms of the structure and bonding of the elements. A student claims that melting point should increase smoothly from sodium to argon because nuclear charge increases — explain whether Period 3 data support that claim.",
        modelAnswerPoints: [
          "Na to Al: giant metallic structures; melting reflects how much energy is needed to loosen the ion + sea attraction; trend generally upward with higher cation charge and more delocalised electrons per atom.",
          "Si: giant covalent network; very high melting point because many strong covalent bonds must be broken throughout the lattice.",
          "P4, S8, Cl2: simple molecular; melting breaks weaker intermolecular forces; Ar monatomic with weakest attractions, lowest melting point.",
          "The student's claim is not supported: bonding type and which forces are overcome dominate, not nuclear charge alone.",
        ],
        workedSolution: [
          "From sodium to aluminium the elements are giant metals, so melting means partially overcoming the electrostatic attraction between metal cations and the delocalised electron sea; as you move right, ionic charge in the lattice increases and the metallic bond becomes stronger in a simple picture, so more thermal energy is generally required to melt the solid up to aluminium.",
          "Silicon has the highest melting point in Period 3 because it is giant covalent: every atom is linked by strong covalent bonds in three dimensions, so melting is not merely loosening a sea around fixed ions but disrupting an extended network of strong bonds.",
          "After silicon, phosphorus and sulfur form simple molecular allotropes and chlorine is diatomic molecular, so melting mainly separates molecules by overcoming London dispersion forces (and any dipole contributions where relevant), which needs far less energy than breaking a giant lattice; argon is monatomic and boils or melts at very low temperature because only weak dispersion forces act between atoms.",
          "The student's prediction fails for Period 3 because although nuclear charge rises across the period, the type of particles being separated in melting changes from metallic ions in an electron sea, to covalently locked silicon atoms, to separate molecules and finally single atoms, so the observed pattern shows a peak at silicon and a large drop to phosphorus rather than a smooth rise to argon.",
        ],
        commonMistake: "Arguing that more protons always mean a higher melting point, without identifying what kind of lattice or molecules are being melted.",
        tags: ["melting-point", "structure", "evaluation"],
      },
    ],
    flashcards: [
      {
        id: "t9-1-f1",
        noteId: "t9-1",
        difficulty: 1,
        front: "Trend in atomic radius across Period 3 (Na to Cl)?",
        back: "Decreases: rising nuclear charge with electrons in the same principal shell; shielding rises less than nuclear charge.",
        examPhrasing: "Explain decreasing atomic radius across Period 3.",
        tags: ["atomic-radius"],
      },
      {
        id: "t9-1-f2",
        noteId: "t9-1",
        difficulty: 1,
        front: "Structures across Period 3 (Na to Ar)?",
        back: "Na, Mg, Al giant metallic; Si giant covalent; P4, S8, Cl2 simple molecular; Ar monatomic.",
        examPhrasing: "Relate physical properties to structure across Period 3.",
        tags: ["structure"],
      },
      {
        id: "t9-1-f3",
        noteId: "t9-1",
        difficulty: 2,
        front: "Why is Al3+ smaller than Na+?",
        back: "Same 10-electron count; higher nuclear charge in Al3+ pulls the electron cloud tighter.",
        examPhrasing: "Order ionic radii of Na+, Mg2+, Al3+ and explain.",
        confusionPair: "neutral atom radius vs cation radius",
        tags: ["ionic-radius"],
      },
      {
        id: "t9-1-f4",
        noteId: "t9-1",
        difficulty: 2,
        front: "Why does Si melt at much higher T than S8?",
        back: "Si: giant covalent — many strong covalent bonds to disrupt. S8: simple molecular — mainly intermolecular forces between molecules.",
        examPhrasing: "Compare melting of giant covalent and simple molecular elements.",
        tags: ["melting-point"],
      },
      {
        id: "t9-1-f5",
        noteId: "t9-1",
        difficulty: 3,
        front: "Electrical behaviour of Si at room temperature vs Na?",
        back: "Na: metallic delocalised electrons → good conductor. Si: semiconductor, far fewer mobile carriers than a metal at 298 K.",
        examPhrasing: "Explain why silicon is not a metallic conductor like sodium.",
        tags: ["conductivity", "silicon"],
      },
      {
        id: "t9-1-f6",
        noteId: "t9-1",
        difficulty: 3,
        front: "Why does metallic melting point tend to rise from Na to Al?",
        back: "Increasing cation charge and electron sea contribution strengthen metallic bonding in the giant lattice.",
        examPhrasing: "Explain the melting trend among Period 3 metals.",
        tags: ["metallic-bonding"],
      },
      {
        id: "t9-1-f7",
        noteId: "t9-1",
        difficulty: 4,
        front: "Order of ionic radius: P3-, S2-, Cl-?",
        back: "P3- > S2- > Cl- (same 18 e-; nuclear charge increases left to right in the series written as P, S, Cl).",
        examPhrasing: "Explain anion radii in an isoelectronic set.",
        tags: ["ionic-radius"],
      },
      {
        id: "t9-1-f8",
        noteId: "t9-1",
        difficulty: 4,
        front: "Why is S8 melting point higher than P4?",
        back: "Larger molecules are more polarisable → stronger London dispersion forces between molecules.",
        examPhrasing: "Relate molecular size to intermolecular strength for P4 vs S8.",
        tags: ["intermolecular-forces"],
      },
      {
        id: "t9-1-f9",
        noteId: "t9-1",
        difficulty: 5,
        front: "Why is melting point across Period 3 not a smooth line Na to Ar?",
        back: "Bonding and structure type change: metallic → giant covalent → simple molecular → monatomic; different forces are broken.",
        examPhrasing: "Evaluate a simple nuclear-charge-only argument for melting points in Period 3.",
        tags: ["periodicity", "evaluation"],
      },
      {
        id: "t9-1-f10",
        noteId: "t9-1",
        difficulty: 5,
        front: "Conductivity of Cl2 vs Na?",
        back: "Na conducts via mobile delocalised electrons. Cl2 is simple molecular with no free delocalised sea in the bulk.",
        examPhrasing: "Explain conductivity differences between a Period 3 metal and chlorine.",
        tags: ["conductivity"],
      },
    ],
  },

  "t9-2": {
    noteId: "t9-2",
    drills: [
      {
        id: "t9-2-d1",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Write balanced equations for the reactions of (a) sodium and (b) magnesium with cold water. State how the vigour of the reaction with cold water differs between sodium and magnesium, and give one reason based on the metal reactivity trend in Period 3.",
        modelAnswerPoints: [
          "2Na(s) + 2H2O(l) -> 2NaOH(aq) + H2(g).",
          "Mg(s) + 2H2O(l) -> Mg(OH)2(aq/suspension) + H2(g) accepted as very slow with cold water; allow very slow or slight reaction wording.",
          "Sodium reacts rapidly or vigorously with cold water compared with magnesium.",
          "Sodium is more reactive as a metal in Period 3 than magnesium, so electron loss to form the aqueous ion occurs more readily for sodium under the same conditions.",
        ],
        workedSolution: [
          "Sodium reacts with cold water to produce aqueous sodium hydroxide and hydrogen gas, and the balanced equation is 2Na(s) + 2H2O(l) -> 2NaOH(aq) + H2(g), which conserves sodium, hydrogen and oxygen atoms and shows the alkali formed in solution.",
          "Magnesium can be written as reacting with cold water according to Mg(s) + 2H2O(l) -> Mg(OH)2(aq) + H2(g), but in the laboratory the reaction with cold water is so slow that only slight bubbling may be seen unless the surface is cleaned and conditions are favourable, which is why steam is often used to show a clearer reaction for magnesium.",
          "Under comparable conditions using clean metal and cold water, sodium reacts much more vigorously than magnesium, producing hydrogen quickly and often with enough heat to melt the sodium and ignite the hydrogen if oxygen is present.",
          "This difference matches the trend that sodium lies further left in Period 3 and is a more electropositive metal, so it loses its outer electron more easily to water acting as an oxidising medium, whereas magnesium's higher ionisation energy and developing ionic charge in the lattice make its reaction with cold water much less obvious.",
        ],
        commonMistake: "Claiming magnesium has no reaction with cold water, or unbalancing the sodium–water equation.",
        tags: ["reactivity", "water", "equations"],
      },
      {
        id: "t9-2-d2",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Write balanced equations for the reactions of (a) sodium, (b) magnesium, (c) aluminium, (d) phosphorus and (e) sulfur with excess oxygen to form Na2O, MgO, Al2O3, P4O10 and SO2 respectively. State the oxidation number of phosphorus in P4O10.",
        modelAnswerPoints: [
          "4Na + O2 -> 2Na2O (syllabus core product; peroxide formation is a separate condition).",
          "2Mg + O2 -> 2MgO.",
          "4Al + 3O2 -> 2Al2O3.",
          "P4 + 5O2 -> P4O10.",
          "S + O2 -> SO2 (or S8 + 8O2 -> 8SO2 scaled to the allotrope used).",
          "Oxidation number of phosphorus in P4O10 is +5.",
        ],
        workedSolution: [
          "Sodium burns in limited oxygen to give sodium oxide, and the equation commonly written for the syllabus product Na2O is 4Na(s) + O2(g) -> 2Na2O(s), which balances sodium and oxygen atoms to show two formula units of oxide from four sodium atoms and one oxygen molecule.",
          "Magnesium reacts vigorously when heated in air or oxygen to form magnesium oxide, 2Mg(s) + O2(g) -> 2MgO(s), which is the ionic oxide containing Mg2+ and O2- in a 1:1 lattice.",
          "Aluminium forms a protective oxide layer rapidly and burns in oxygen with a bright flame to give aluminium oxide, written as 4Al(s) + 3O2(g) -> 2Al2O3(s), which balances aluminium and oxygen in the usual 4:3 ratio of atoms to dioxygen molecules.",
          "White phosphorus reacts with excess oxygen to form phosphorus(V) oxide, P4(s) + 5O2(g) -> P4O10(s), which is the acid anhydride used in the Period 3 oxide series.",
          "Sulfur burns in excess oxygen to give sulfur dioxide, written simply as S(s) + O2(g) -> SO2(g), or with S8 as S8(s) + 8O2(g) -> 8SO2(g) if the stable allotrope is emphasised, and SO2 is the syllabus oxide for sulfur in Period 3.",
          "In P4O10 each phosphorus is bonded to oxygen in an environment where oxygen is assigned -2 in the usual oxidation-number rules for oxides, and solving 4x + 10(-2) = 0 for the neutral molecule gives x = +5, so the oxidation number of phosphorus is +5.",
        ],
        commonMistake: "Using P2O5 as the only formula without relating it to P4O10, or assigning +3 to phosphorus in P4O10.",
        tags: ["equations", "oxygen", "oxidation-number"],
      },
      {
        id: "t9-2-d3",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Write balanced equations for the reactions of (a) sodium, (b) magnesium, (c) aluminium, (d) silicon and (e) phosphorus with excess chlorine to give NaCl, MgCl2, AlCl3, SiCl4 and PCl5. For one of the covalent chlorides, state whether you expect simple molecular behaviour in the gas phase.",
        modelAnswerPoints: [
          "2Na + Cl2 -> 2NaCl.",
          "Mg + Cl2 -> MgCl2.",
          "2Al + 3Cl2 -> 2AlCl3.",
          "Si + 2Cl2 -> SiCl4.",
          "2P + 5Cl2 -> 2PCl5 (or P4 + 10Cl2 -> 4PCl5).",
          "SiCl4 (and PCl5) are simple molecular covalent chlorides in the gas/low polymer picture used at A Level.",
        ],
        workedSolution: [
          "Sodium reacts vigorously with chlorine gas to form sodium chloride, 2Na(s) + Cl2(g) -> 2NaCl(s), which is the giant ionic lattice containing Na+ and Cl- ions.",
          "Magnesium burns in chlorine to give magnesium chloride, Mg(s) + Cl2(g) -> MgCl2(s), another ionic chloride with Mg2+ and two chloride ions per formula unit.",
          "Aluminium reacts when heated with chlorine to form aluminium chloride, 2Al(s) + 3Cl2(g) -> 2AlCl3(s or vapour), noting that AlCl3 has significant covalent character in the vapour but is still counted among the Period 3 chlorides in the syllabus list.",
          "Silicon requires heating with chlorine to form silicon tetrachloride, Si(s) + 2Cl2(g) -> SiCl4(l or g), a colourless covalent liquid or gas that hydrolyses in moist air.",
          "Phosphorus reacts with excess chlorine to give phosphorus(V) chloride, which can be written as 2P(s) + 5Cl2(g) -> 2PCl5(s) or equivalently with P4 and scaled coefficients, and PCl5 is a simple molecular chloride in the vapour though it ionises in the solid.",
          "Silicon tetrachloride exists as separate SiCl4 molecules in the gas phase with weak intermolecular forces between molecules, which is the sense in which it is described as simple molecular covalent in contrast to the ionic giant lattices of NaCl and MgCl2.",
        ],
        commonMistake: "Writing Si + Cl2 -> SiCl2, or forgetting to balance chlorine atoms across the Period 3 set.",
        tags: ["chlorine", "equations", "chlorides"],
      },
      {
        id: "t9-2-d4",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "State the oxidation numbers of the Period 3 element in Na2O, MgO, Al2O3, P4O10, SO2 and SO3. Explain briefly how the increase in the highest common oxidation state across the period relates to the number of outer-shell (valence) electrons available for bonding to oxygen.",
        modelAnswerPoints: [
          "Na +1; Mg +2; Al +3; P +5 in P4O10; S +4 in SO2; S +6 in SO3.",
          "Left to right, the maximum oxidation state shown by the oxide series rises with the number of valence electrons that can be involved in covalent bonding to more electronegative oxygen.",
          "Sulfur can use +6 when all valence shell electrons are involved in bonding in SO3 compared with +4 in SO2.",
        ],
        workedSolution: [
          "Using the usual rule that oxygen is -2 in these oxides, sodium in Na2O is +1, magnesium in MgO is +2, aluminium in Al2O3 is +3, phosphorus in neutral P4O10 is +5, sulfur in SO2 is +4 and sulfur in SO3 is +6, and each assignment can be checked by summing oxidation numbers to zero for the neutral formula unit.",
          "Across Period 3 from sodium to sulfur in this list, the Period 3 element becomes more electronegative and has more outer-shell electrons that can be promoted into bonding combinations with oxygen, so the formal oxidation state that oxygen can support in stable oxides rises from +1 through +3 and up to +6 for sulfur in SO3.",
          "The step from SO2 to SO3 is a clear illustration that sulfur's valence shell can accommodate more electron withdrawal by oxygen in SO3, giving the higher +6 state, whereas SO2 leaves sulfur in a lower +4 state with fewer oxygen atoms attached per sulfur in the stoichiometry used here.",
        ],
        commonMistake: "Assigning +5 to sulfur in SO2, or forgetting that each element is referenced to its own formula.",
        tags: ["oxidation-number", "oxides", "valence"],
      },
      {
        id: "t9-2-d5",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Write equations, where a reaction occurs, for the reactions with water of Na2O, MgO, Al2O3, SiO2, P4O10, SO2 and SO3. For each case where a solution forms, state whether the solution is strongly alkaline, weakly alkaline, approximately neutral, weakly acidic or strongly acidic.",
        modelAnswerPoints: [
          "Na2O + H2O -> 2NaOH: strongly alkaline.",
          "MgO + H2O -> Mg(OH)2: sparingly soluble, weakly alkaline.",
          "Al2O3 and SiO2: essentially no reaction with cold water (insoluble oxides).",
          "P4O10 + 6H2O -> 4H3PO4: acidic (phosphoric acid).",
          "SO2 + H2O -> H2SO3: weakly acidic solution.",
          "SO3 + H2O -> H2SO4: strongly acidic.",
        ],
        workedSolution: [
          "Sodium oxide reacts completely with water to form sodium hydroxide, Na2O(s) + H2O(l) -> 2NaOH(aq), and because sodium hydroxide is a strong base that dissociates fully, the resulting solution is strongly alkaline with a very high pH.",
          "Magnesium oxide reacts slowly or to a limited extent to give sparingly soluble magnesium hydroxide, MgO(s) + H2O(l) -> Mg(OH)2(aq or suspension), so only a low concentration of hydroxide ions builds up in saturated solution and the pH is weakly alkaline rather than as high as for sodium hydroxide at equal formal salt concentration.",
          "Aluminium oxide and silicon dioxide are both largely insoluble in cold water and do not give a significant acid or alkali simply by shaking with water, so they are treated as having no practical reaction with water under ordinary laboratory conditions despite silicon dioxide being the anhydride of silicic acid at a very slow timescale.",
          "Phosphorus(V) oxide reacts vigorously with water to form phosphoric acid, P4O10(s) + 6H2O(l) -> 4H3PO4(aq) when balanced to phosphoric acid, producing an acidic solution because phosphoric acid donates protons to water.",
          "Sulfur dioxide dissolves and reacts with water to give sulfurous acid in solution, SO2(g) + H2O(l) -> H2SO3(aq), which is a weak diprotic acid in the acid–base sense, so the pH is acidic but not as low as for a strong acid at comparable concentration.",
          "Sulfur trioxide reacts extremely vigorously with water to form sulfuric acid, SO3(g or l) + H2O(l) -> H2SO4(aq), which is a strong acid, so the solution formed is strongly acidic with a very low pH for reasonable amounts dissolved.",
        ],
        commonMistake: "Claiming SiO2 dissolves to a clear acidic solution in cold water like SO3, or calling MgO solution strongly alkaline like NaOH.",
        tags: ["oxides", "water", "ph"],
      },
      {
        id: "t9-2-d6",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Define a basic oxide and an acidic oxide (acid anhydride). For Na2O, MgO, Al2O3, P4O10, SO2 and SO3, describe the acid–base behaviour toward water and toward dilute acid or alkali as appropriate, including amphoteric behaviour of Al2O3 with hydrochloric acid and with sodium hydroxide (balanced equations).",
        modelAnswerPoints: [
          "Basic oxide: reacts with acids; often gives alkaline solution with water if it reacts (Na2O, MgO).",
          "Acidic oxide: reacts with water to give acid or behaves as acid anhydride (P4O10, SO2, SO3).",
          "Al2O3 amphoteric: Al2O3 + 6HCl -> 2AlCl3 + 3H2O; Al2O3 + 2NaOH + 3H2O -> 2Na[Al(OH)4] or acceptable aluminate.",
        ],
        workedSolution: [
          "A basic oxide is an oxide that reacts with acids to form a salt and water and, when it reacts with water, produces hydroxide ions so the solution becomes alkaline, which is exactly how sodium oxide and magnesium oxide behave in Period 3.",
          "An acidic oxide, also called an acid anhydride when tied to a parent acid, is an oxide that reacts with water to increase the hydrogen ion concentration or reacts with bases to form salts, which matches phosphorus(V) oxide forming phosphoric acid, sulfur dioxide forming sulfurous acid species, and sulfur trioxide forming sulfuric acid.",
          "Sodium oxide and magnesium oxide are therefore classified as basic oxides, phosphorus(V) oxide and the sulfur oxides in this list are acidic oxides, and aluminium oxide is amphoteric because it reacts with hydrochloric acid as a base, Al2O3(s) + 6HCl(aq) -> 2AlCl3(aq) + 3H2O(l), and also reacts with sodium hydroxide solution to form a soluble aluminate, Al2O3(s) + 2NaOH(aq) + 3H2O(l) -> 2Na[Al(OH)4](aq), showing both acid-like and base-like oxide behaviour depending on the reagent.",
        ],
        commonMistake: "Writing Al2O3 as only basic because it reacts with acid, and omitting the reaction with sodium hydroxide that proves amphoteric character.",
        tags: ["acid-base", "amphoteric", "oxides"],
      },
      {
        id: "t9-2-d7",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Describe the acid–base behaviour of NaOH, Mg(OH)2 and Al(OH)3, including equations with dilute hydrochloric acid and, for Al(OH)3, the reaction with aqueous sodium hydroxide. Explain why Al(OH)3 is described as amphoteric.",
        modelAnswerPoints: [
          "NaOH: strong alkali; NaOH + HCl -> NaCl + H2O.",
          "Mg(OH)2: sparingly soluble base; Mg(OH)2 + 2HCl -> MgCl2 + 2H2O.",
          "Al(OH)3 with acid: Al(OH)3 + 3HCl -> AlCl3 + 3H2O.",
          "Al(OH)3 with alkali: Al(OH)3 + NaOH -> Na[Al(OH)4] or equivalent aluminate.",
          "Amphoteric: reacts as acid with base and as base with acid.",
        ],
        workedSolution: [
          "Sodium hydroxide is a strong base that dissociates fully in water and neutralises hydrochloric acid in a simple acid–base reaction, NaOH(aq) + HCl(aq) -> NaCl(aq) + H2O(l), giving a salt solution with no solid hydroxide remaining if stoichiometric acid is added.",
          "Magnesium hydroxide is a base that is only slightly soluble, but the solid or suspension still reacts with acid to dissolve by forming magnesium chloride and water, Mg(OH)2(s) + 2HCl(aq) -> MgCl2(aq) + 2H2O(l), which shows typical Brønsted base behaviour toward protons.",
          "Aluminium hydroxide reacts with hydrochloric acid in the same base-like way, Al(OH)3(s) + 3HCl(aq) -> AlCl3(aq) + 3H2O(l), consuming three moles of acid per mole of hydroxide because each OH- group is protonated in turn.",
          "Aluminium hydroxide also dissolves in excess sodium hydroxide solution by acting as an acid toward hydroxide, for example Al(OH)3(s) + NaOH(aq) -> Na[Al(OH)4](aq), which forms a soluble aluminate complex and shows that the same solid can donate protons to a strong base.",
          "Because aluminium hydroxide neutralises strong acid as a base and also reacts with strong alkali as an acid, it is classified as an amphoteric hydroxide in the Period 3 context, unlike sodium hydroxide which only shows base behaviour or magnesium hydroxide which does not dissolve in excess alkali under normal conditions.",
        ],
        commonMistake: "Claiming Mg(OH)2 dissolves in excess NaOH like Al(OH)3, or omitting the reaction of Al(OH)3 with sodium hydroxide.",
        tags: ["hydroxides", "amphoteric", "acid-base"],
      },
      {
        id: "t9-2-d8",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Write equations for the reactions with water of NaCl, MgCl2, AlCl3, SiCl4 and PCl5, and state the likely approximate pH (neutral, weakly acidic, strongly acidic) of the resulting solutions. Then explain the trend in hydrolysis tendency from NaCl to PCl5 in terms of bonding type and electronegativity of the Period 3 element.",
        modelAnswerPoints: [
          "NaCl dissolves with little hydrolysis: ~neutral pH.",
          "MgCl2: slight acidity possible from very weak interaction but often treated as near neutral at dilute A Level level; accept weakly acidic if justified by polarising Mg2+.",
          "AlCl3 + water -> Al(OH)3 + HCl (overall hydrolysis): acidic.",
          "SiCl4 + 2H2O -> SiO2 + 4HCl (or stepwise): strongly acidic fumes.",
          "PCl5 + 4H2O -> H3PO4 + 5HCl (overall): strongly acidic.",
          "Trend: bonding becomes more covalent and the central atom more electronegative, so water attacks the element–chlorine bonds more readily and HCl is released.",
        ],
        workedSolution: [
          "Sodium chloride dissolves in water mainly by hydration of Na+ and Cl- ions without extensive reaction of chloride with water, NaCl(s) + water -> Na+(aq) + Cl-(aq), so the solution remains approximately neutral because it is the salt of a strong acid and a strong base.",
          "Magnesium chloride is also essentially ionic in the solid and gives Mg2+ and Cl- in solution; any weak acidity comes from slight polarisation of water by Mg2+ but at introductory level the solution is often described as approximately neutral compared with aluminium and the molecular chlorides.",
          "Aluminium chloride reacts vigorously with water because Al3+ is highly polarising and the solid has covalent character; a simplified overall picture is AlCl3(s) + 3H2O(l) -> Al(OH)3(s) + 3HCl(aq), producing hydrochloric acid so the mixture is acidic.",
          "Silicon tetrachloride hydrolyses rapidly, SiCl4(l) + 2H2O(l) -> SiO2(s) + 4HCl(aq), releasing four moles of strong acid per mole if written this way, so the solution is strongly acidic and misty fumes of hydrogen chloride are seen in moist air.",
          "Phosphorus pentachloride hydrolyses to phosphoric and hydrochloric acids, for example PCl5(s) + 4H2O(l) -> H3PO4(aq) + 5HCl(aq) when balanced to those products, giving a strongly acidic mixture.",
          "Across Period 3 the chlorides become progressively more covalent toward silicon and phosphorus, and the central atom becomes more electronegative, so water can act as a nucleophile at the electron-deficient centre more easily, cleaving element–chlorine bonds and releasing HCl, which is why hydrolysis is negligible for NaCl but violent for SiCl4 and PCl5.",
        ],
        commonMistake: "Saying all Period 3 chlorides are covalent molecular, or that NaCl solution is strongly acidic.",
        tags: ["hydrolysis", "chlorides", "ph", "bonding"],
      },
      {
        id: "t9-2-d9",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Explain how the variations in oxidation number in the oxides and in the hydrolysis behaviour of the chlorides across Period 3 are linked to changes in bonding to oxygen or chlorine and to the increasing electronegativity of the Period 3 element from sodium to phosphorus.",
        modelAnswerPoints: [
          "Left: oxides increasingly ionic; oxide ion can be protonated → basic oxide behaviour.",
          "Right: oxides more covalent; element in higher positive oxidation state withdraws electron density from oxygen → acidic oxide / acid anhydride.",
          "Chlorides: ionic NaCl/MgCl2 to increasingly covalent AlCl3, SiCl4, PCl5; higher electronegativity and covalency favour attack by water and HCl release.",
        ],
        workedSolution: [
          "On the left of Period 3, sodium and magnesium form oxides in which bonding to oxygen is predominantly ionic, so oxide ions behave as bases in water and the oxidation states +1 and +2 reflect simple electron transfer to oxygen without extensive covalent sharing of valence electrons beyond the ionic model.",
          "Toward the right, aluminium, phosphorus and sulfur form oxides in which bonding is increasingly covalent, the Period 3 element carries a higher positive oxidation state when fully combined with oxygen, and oxygen's electron density is drawn toward the central atom in a way that stabilises molecular acid anhydrides rather than free oxide ions, which is why the oxides become acidic in character.",
          "The same electronegativity and bonding trend appears in the chlorides: sodium and magnesium chlorides are largely ionic lattices that simply dissolve, aluminium chloride has substantial covalent character and hydrolyses to acidic species, and silicon tetrachloride and phosphorus pentachloride are molecular chlorides whose central atoms are strongly attacked by water, releasing hydrogen chloride and giving strongly acidic solutions.",
        ],
        commonMistake: "Attributing oxide acidity only to 'more oxygen atoms' without mentioning electronegativity and loss of ionic oxide character.",
        tags: ["electronegativity", "trend", "bonding"],
      },
      {
        id: "t9-2-d10",
        noteId: "t9-2",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "A white solid chloride of a Period 3 element melts at a low temperature, does not conduct electricity when molten, and produces white fumes and an acidic solution when added to water. Suggest the type of bonding present and identify the chloride that best fits this pattern. Contrast with one Period 3 chloride that is giant ionic, naming expected observations for that chloride when molten and when dissolved in water.",
        modelAnswerPoints: [
          "Low melting and non-conducting when molten suggest simple molecular covalent chloride, not ions in a lattice.",
          "White fumes and strongly acidic solution on hydrolysis fit SiCl4 or PCl5; SiCl4 is a common textbook match for low-bp molecular tetrachloride.",
          "Contrast: NaCl is giant ionic; molten NaCl conducts; aqueous NaCl is ~neutral.",
        ],
        workedSolution: [
          "A chloride that melts at a low temperature and does not conduct electricity when molten cannot be a giant ionic lattice in the sodium chloride sense, because molten ionic chlorides contain mobile ions that carry charge; the observations instead point to a simple molecular covalent chloride where only weak intermolecular forces break on melting and no ions are free to move in the liquid.",
          "The reaction with water that produces an acidic solution and misty white fumes of hydrogen chloride is characteristic of rapid hydrolysis of a molecular chloride such as silicon tetrachloride or phosphorus pentachloride, and between these, SiCl4 is often the archetype quoted for a volatile molecular tetrachloride of Period 3 with those exact qualitative tests.",
          "By contrast, sodium chloride is a giant ionic chloride: its melting point is high compared with molecular chlorides, molten sodium chloride conducts electricity because Na+ and Cl- ions can move, and dissolving sodium chloride in water gives separate hydrated ions without generating a strongly acidic solution, so the pH remains approximately neutral.",
          "Putting the evidence together, the unknown is best described as a covalent molecular chloride undergoing hydrolysis, whereas sodium chloride illustrates the ionic extreme with conduction in the melt and no acidic hydrolysis to hydrogen chloride under normal dissolution conditions.",
        ],
        commonMistake: "Identifying the unknown as MgCl2, which is ionic and conducts when molten, or as AlCl3 without noting its ionic–covalent complexity.",
        tags: ["deduction", "bonding", "chlorides"],
      },
    ],
    flashcards: [
      {
        id: "t9-2-f1",
        noteId: "t9-2",
        difficulty: 1,
        front: "Oxidation number of P in P4O10?",
        back: "+5 for each phosphorus atom (neutral molecule, O taken as -2).",
        examPhrasing: "Assign oxidation numbers in Period 3 oxides.",
        tags: ["oxidation-number"],
      },
      {
        id: "t9-2-f2",
        noteId: "t9-2",
        difficulty: 1,
        front: "Na2O + H2O → ?",
        back: "2NaOH — strongly alkaline solution.",
        examPhrasing: "Write the equation and state pH for sodium oxide in water.",
        tags: ["oxides"],
      },
      {
        id: "t9-2-f3",
        noteId: "t9-2",
        difficulty: 2,
        front: "SO3 + H2O → ?",
        back: "H2SO4 — strongly acidic.",
        examPhrasing: "Give the acid anhydride reaction for SO3.",
        tags: ["oxides", "acids"],
      },
      {
        id: "t9-2-f4",
        noteId: "t9-2",
        difficulty: 2,
        front: "2Na + 2H2O → ?",
        back: "2NaOH + H2 — vigorous with cold water.",
        examPhrasing: "Write the equation for sodium and cold water.",
        tags: ["reactivity"],
      },
      {
        id: "t9-2-f5",
        noteId: "t9-2",
        difficulty: 3,
        front: "Why is saturated Mg(OH)2 only weakly alkaline?",
        back: "Low solubility limits [OH-] in solution.",
        examPhrasing: "Explain pH after MgO or Mg(OH)2 with water.",
        tags: ["oxides", "solubility"],
      },
      {
        id: "t9-2-f6",
        noteId: "t9-2",
        difficulty: 3,
        front: "SiO2 + cold H2O?",
        back: "No significant reaction; network is insoluble under normal conditions.",
        examPhrasing: "Contrast SiO2 and SiCl4 with water.",
        confusionPair: "SiO2 vs SiCl4 hydrolysis",
        tags: ["oxides"],
      },
      {
        id: "t9-2-f7",
        noteId: "t9-2",
        difficulty: 4,
        front: "Al(OH)3 + NaOH → ?",
        back: "Soluble aluminate, e.g. Na[Al(OH)4] — evidence of amphoteric hydroxide.",
        examPhrasing: "Show aluminium hydroxide reacting as an acid.",
        tags: ["amphoteric"],
      },
      {
        id: "t9-2-f8",
        noteId: "t9-2",
        difficulty: 4,
        front: "Why is aqueous AlCl3 acidic?",
        back: "Al3+ polarises coordinated water / hydrolysis releases H+ (and HCl if solid reacts).",
        examPhrasing: "Explain the pH of aluminium chloride in water.",
        tags: ["hydrolysis"],
      },
      {
        id: "t9-2-f9",
        noteId: "t9-2",
        difficulty: 5,
        front: "Basic → acidic oxide trend: main electronic idea?",
        back: "Rising electronegativity and covalent character: less basic O2- chemistry; more molecular acid anhydride behaviour.",
        examPhrasing: "Explain the acid–base trend in Period 3 oxides.",
        tags: ["acid-base", "trend"],
      },
      {
        id: "t9-2-f10",
        noteId: "t9-2",
        difficulty: 5,
        front: "Observations suggesting a molecular chloride?",
        back: "Low melting, non-conducting melt, rapid hydrolysis and HCl fumes with water.",
        examPhrasing: "Suggest bonding in an unknown chloride from tests.",
        tags: ["deduction", "chlorides"],
      },
    ],
  },

  "t9-3": {
    noteId: "t9-3",
    drills: [
      {
        id: "t9-3-d1",
        noteId: "t9-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define what is meant by a period and by a group in the periodic table, and state one way each label helps you predict chemical behaviour.",
        modelAnswerPoints: [
          "A period is a horizontal row; atoms in the same period are filling the same principal quantum shell in the s- and p-block picture.",
          "A group is a vertical column; main-group members in the same group have the same number of outer-shell electrons in the simple model.",
          "Period guides distance/shielding effects; group guides typical valency and oxide/chloride stoichiometry patterns.",
        ],
        workedSolution: [
          "A period is a horizontal row of the periodic table in which atomic number increases from left to right and, for the main blocks, valence electrons are being added into the same principal quantum shell until that shell is filled at the noble gas at the end of the period.",
          "A group is a vertical column of elements that share the same count of outer-shell electrons in the simplified s- and p-block description, which is why elements in the same group often show related ion charges and similar reaction types with oxygen or water.",
          "Knowing the period helps you judge how far valence electrons are from the nucleus for a given shell filling stage, while knowing the group helps you predict characteristic formulas such as E2O and ECl for Group 1 or EO and ECl2 for Group 2 before you know the element's name.",
        ],
        commonMistake: "Swapping period and group, or claiming a period is a vertical column.",
        tags: ["definitions", "periodicity", "deduction"],
      },
      {
        id: "t9-3-d2",
        noteId: "t9-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Define first ionisation energy. Using Group 1 as an example, state the trend in first ionisation energy from lithium to caesium and predict how the vigour of reaction with cold water changes down the group, giving the electronic reason.",
        modelAnswerPoints: [
          "First ionisation energy is the energy required to remove one mole of electrons from one mole of gaseous atoms to form one mole of gaseous +1 ions: X(g) -> X+(g) + e-.",
          "First ionisation energy decreases down Group 1 from Li to Cs.",
          "Outer electron farther from nucleus and better shielded, so easier to remove.",
          "Reactivity with water generally increases down the group because the outer electron is lost more readily to form M+ in the reaction pathway.",
        ],
        workedSolution: [
          "First ionisation energy is defined as the enthalpy change when one mole of gaseous atoms each loses one electron to form one mole of gaseous +1 ions, written in symbols as X(g) -> X+(g) + e-, and the measurement always refers to gaseous atoms, not metals in the solid lattice.",
          "Down Group 1 from lithium to caesium, first ionisation energy decreases because each step adds a new occupied electron shell, so the outer electron is on average farther from the nucleus and inner electrons provide more shielding of the nuclear charge.",
          "Because less energy is required to remove the outer electron from caesium than from lithium, caesium atoms donate that electron more readily in chemical processes that oxidise the metal.",
          "When alkali metals react with cold water to produce aqueous hydroxide and hydrogen, the rate and vigour generally increase down the group under comparable conditions because the falling ionisation energy makes the initial electron loss to water easier, even though other physical factors such as melting of the metal also influence what you observe.",
        ],
        commonMistake: "Saying first ionisation energy increases down Group 1, or omitting gaseous atoms from the definition.",
        tags: ["ionisation-energy", "group-1", "prediction"],
      },
      {
        id: "t9-3-d3",
        noteId: "t9-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Define an oxidising agent in a redox reaction. For the halogens Cl2, Br2 and I2 reacting with halide ions, state the trend in oxidising power down Group 17 and predict whether bromine will displace iodide ions from aqueous potassium iodide.",
        modelAnswerPoints: [
          "An oxidising agent accepts electrons and is itself reduced.",
          "Oxidising power of the elements decreases down Group 17: Cl2 > Br2 > I2.",
          "Br2 displaces I- to I2 because Br2 is a stronger oxidising agent than I2.",
        ],
        workedSolution: [
          "An oxidising agent is a species that gains electrons in a redox process, so another species loses electrons and is oxidised while the oxidising agent's own oxidation state decreases.",
          "For the halogens, the ability to act as an oxidising agent toward halide ions decreases down Group 17 from chlorine to bromine to iodine, which is summarised by the order Cl2 strongest, then Br2, then I2 weakest among the three diatomic elements commonly compared.",
          "Bromine molecules can therefore accept electrons from iodide ions because bromine sits above iodine in the group and is the stronger oxidising agent of the two elements.",
          "The displacement reaction occurs as Br2(aq) + 2I-(aq) -> 2Br-(aq) + I2(aq or s), which shows bromine oxidising iodide to iodine while bromine is reduced to bromide, so bromine does displace iodide from aqueous potassium iodide under standard conditions.",
        ],
        commonMistake: "Calling the halide ion the oxidising agent, or claiming oxidising strength increases down Group 17.",
        tags: ["oxidising-agent", "group-17", "displacement"],
      },
      {
        id: "t9-3-d4",
        noteId: "t9-3",
        kind: "mcq",
        difficulty: 1,
        stem: "An element forms oxide E2O and chloride ECl. Which main-group pattern is most likely?",
        options: [
          { id: "A", text: "Group 1 (+1)" },
          { id: "B", text: "Group 2 (+2)" },
          { id: "C", text: "Group 17" },
          { id: "D", text: "Group 18" },
        ],
        correctOptionId: "A",
        explanation:
          "E2O and ECl imply a +1 oxidation state with O2- and Cl-, which is the characteristic pattern for Group 1 metals.",
        distractorRationale: {
          B: "Group 2 metals typically form EO and MCl2 for a +2 ion.",
          C: "Halogens do not form E2O and ECl in this alkali-metal stoichiometry.",
          D: "Noble gases do not form these ionic formulas under normal chemistry.",
        },
        tags: ["deduction", "group-trends"],
      },
      {
        id: "t9-3-d5",
        noteId: "t9-3",
        kind: "mcq",
        difficulty: 1,
        stem: "Which property of the halogens F2 to I2 generally increases down the group at 298 K?",
        options: [
          { id: "A", text: "First ionisation energy of the atom" },
          { id: "B", text: "Boiling point of the element" },
          { id: "C", text: "Electronegativity" },
          { id: "D", text: "Oxidising power of the diatomic element" },
        ],
        correctOptionId: "B",
        explanation:
          "Heavier diatomic halogens have more electrons and larger instantaneous dipoles, so dispersion forces between molecules strengthen and boiling points rise down the group.",
        distractorRationale: {
          A: "First ionisation energy decreases down Group 17 as the outer electron is farther from the nucleus.",
          C: "Electronegativity decreases down the group.",
          D: "Oxidising power of X2 generally decreases down Group 17.",
        },
        tags: ["group-17", "trends"],
      },
      {
        id: "t9-3-d6",
        noteId: "t9-3",
        kind: "mcq",
        difficulty: 2,
        stem: "A metal forms MO, MCl2 and M(OH)2 and reacts with dilute acid to release H2. The best classification is",
        options: [
          { id: "A", text: "Group 1 metal" },
          { id: "B", text: "Group 2-like +2 metal" },
          { id: "C", text: "Group 17 non-metal" },
          { id: "D", text: "Noble gas" },
        ],
        correctOptionId: "B",
        explanation:
          "Stable +2 chemistry in the oxide, hydroxide and chloride stoichiometry matches the Group 2 pattern, and the metal displaces hydrogen from dilute acid.",
        distractorRationale: {
          A: "Group 1 would suggest E2O and ECl, not MO and MCl2.",
          C: "A halogen would not match +2 oxide and hydroxide stoichiometry or acid displacement of H2 as a metal does.",
          D: "Noble gases do not form MO, MCl2 or react with dilute acids to release hydrogen.",
        },
        tags: ["deduction", "group-2"],
      },
      {
        id: "t9-3-d7",
        noteId: "t9-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Compared with lithium, sodium is expected to react with cold water",
        options: [
          { id: "A", text: "more slowly" },
          { id: "B", text: "more vigorously" },
          { id: "C", text: "not at all" },
          { id: "D", text: "only if a catalyst is present" },
        ],
        correctOptionId: "B",
        explanation:
          "Down Group 1, lower first ionisation energy makes outer electron loss easier, so reaction with water is generally more vigorous from Li toward Cs under similar conditions.",
        distractorRationale: {
          A: "The reactivity trend with water increases down Group 1, not decreases from Li to Na.",
          C: "Sodium still reacts exothermically with water; 'no reaction' is incorrect.",
          D: "Alkali metal–water reactions do not require a catalyst.",
        },
        tags: ["group-1", "reactivity"],
      },
      {
        id: "t9-3-d8",
        noteId: "t9-3",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Element X is in Group 2 and Period 4. Predict the ion charge in its common ionic compounds, the formula of its oxide, and how its reaction with cold water compares with magnesium, with reasoning.",
        modelAnswerPoints: [
          "+2 ion in compounds (Group 2).",
          "Oxide formula XO.",
          "Calcium reacts with cold water more readily than magnesium, forming the hydroxide and hydrogen.",
        ],
        workedSolution: [
          "Because X is in Group 2, it loses both s-electrons from its outer shell when it forms ionic compounds, so the characteristic ion charge in salts, hydroxides and oxides is +2 rather than +1.",
          "With a +2 oxidation state toward oxide ions, the formula that matches charge balance with O2- is XO, since each X2+ pairs with one O2- in the simplest oxide stoichiometry.",
          "Magnesium reacts only very slowly with cold water unless the surface is cleaned and conditions are favourable, whereas calcium, as the Period 4 Group 2 member, reacts more obviously with cold water to produce calcium hydroxide and hydrogen, because calcium's outer electrons are farther from the nucleus and less tightly bound than magnesium's, making oxidation by water easier under the same conditions.",
        ],
        commonMistake: "Predicting X2O or a +1 ion for a Group 2 element.",
        tags: ["prediction", "group-2"],
      },
      {
        id: "t9-3-d9",
        noteId: "t9-3",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "A gas displaces aqueous bromide ions to bromine but does not oxidise chloride ions under the same conditions. Identify the gas using Group 17 trends. Explain why you should combine this chemical evidence with at least one physical property before asserting the halogen's identity in a laboratory unknown.",
        modelAnswerPoints: [
          "Displacing Br- implies a stronger oxidising agent than Br2.",
          "Failure to oxidise Cl- identifies the gas as Cl2, not a halogen stronger than chlorine.",
          "Physical data such as state at room temperature, colour, or boiling point should agree with chlorine to avoid misidentification from a single test.",
        ],
        workedSolution: [
          "If a gas oxidises bromide ions to bromine, it must be able to accept electrons from bromide while being reduced itself, which requires an oxidising strength at least comparable to bromine's ability acting in the reverse direction, so the gas must sit above bromine in the halogen oxidising series.",
          "Among the common halogens, only species stronger oxidising agents than bromine will convert Br- to Br2, but the observation that chloride ions are not oxidised rules out anything stronger than chlorine under the stated conditions, because a halogen stronger than chlorine would also displace chlorine from chloride; therefore the gas is chlorine, Cl2.",
          "Displacement chemistry alone can be ambiguous if trace impurities or lighting conditions affect colour perception, so the identification should be cross-checked with physical information such as chlorine being a pale green gas at room temperature with a characteristic boiling point trend compared with bromine and iodine, so that chemical and physical lines of evidence converge on the same element.",
        ],
        commonMistake: "Choosing Br2, which cannot oxidise bromide to 'more bromine' from Br- in the simple displacement picture.",
        tags: ["displacement", "halogens", "deduction"],
      },
      {
        id: "t9-3-d10",
        noteId: "t9-3",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "An unknown non-metal element exists as a diatomic molecule at room temperature, has a low boiling point, and shows oxidising power weaker than Cl2 but stronger than I2. Deduce its identity and its probable position in Group 17. Separately, explain why noble gas boiling points increase down Group 18.",
        modelAnswerPoints: [
          "Oxidising trend Cl2 > Br2 > I2 places the unknown as Br2.",
          "Diatomic molecular halogen with low boiling point matches bromine's simple molecular physical behaviour.",
          "Noble gases are monatomic; boiling involves separating atoms held by dispersion forces only.",
          "More electrons and larger polarisable electron cloud down Group 18 strengthen dispersion attractions, so boiling point increases.",
        ],
        workedSolution: [
          "For halogens, oxidising ability decreases from chlorine to bromine to iodine, so a species that is a weaker oxidising agent than chlorine but still stronger than iodine must be bromine, Br2, which sits between chlorine and iodine in Group 17.",
          "Bromine is a diatomic non-metal in its standard elemental form and exists as Br2 molecules held by intermolecular forces, which explains the relatively low boiling point compared with network solids, and that physical picture is consistent with the middle halogens rather than with a giant structure element.",
          "The unknown is therefore deduced to be bromine and to lie in Period 4 of Group 17 directly under chlorine and above iodine, which matches both the redox placement and the molecular physical properties described.",
          "Noble gases are monatomic, so when liquid noble gas boils, only weak London dispersion forces between atoms are overcome, not covalent bonds between atoms in a molecule.",
          "Down Group 18 each atom contains more electrons in shells farther from the nucleus, so the electron cloud is more polarisable and instantaneous dipole attractions between atoms are stronger, requiring more energy to separate the atoms and producing the observed increase in boiling point from helium to heavier noble gases.",
        ],
        commonMistake: "Identifying the unknown as Cl2 despite the stated inequality relative to chlorine, or attributing noble gas boiling trends to breaking covalent bonds.",
        tags: ["deduction", "halogens", "group-18"],
      },
    ],
    flashcards: [
      {
        id: "t9-3-f1",
        noteId: "t9-3",
        difficulty: 1,
        front: "Formulas E2O and ECl suggest?",
        back: "+1 oxidation state; Group 1 metal pattern.",
        examPhrasing: "Deduce the group from oxide and chloride formulas.",
        tags: ["deduction"],
      },
      {
        id: "t9-3-f2",
        noteId: "t9-3",
        difficulty: 1,
        front: "Formulas MO and MCl2 suggest?",
        back: "+2 oxidation state; Group 2 metal pattern.",
        examPhrasing: "Relate stoichiometry to oxidation state.",
        tags: ["deduction"],
      },
      {
        id: "t9-3-f3",
        noteId: "t9-3",
        difficulty: 2,
        front: "Trend in oxidising power of X2 down Group 17?",
        back: "Decreases: Cl2 > Br2 > I2.",
        examPhrasing: "Predict displacement outcomes from oxidising strength.",
        tags: ["group-17"],
      },
      {
        id: "t9-3-f4",
        noteId: "t9-3",
        difficulty: 2,
        front: "Group 1 + cold water: trend down the group?",
        back: "Generally more vigorous: lower IE, outer electron lost more easily.",
        examPhrasing: "Predict vigour of alkali metal + water.",
        tags: ["group-1"],
      },
      {
        id: "t9-3-f5",
        noteId: "t9-3",
        difficulty: 3,
        front: "Why combine several tests to identify an unknown element?",
        back: "Single properties can overlap between elements; converging chemical and physical evidence narrows group, period and identity.",
        examPhrasing: "Evaluate a one-test identification plan.",
        tags: ["method"],
      },
      {
        id: "t9-3-f6",
        noteId: "t9-3",
        difficulty: 3,
        front: "Which Period 3 oxide is the standard amphoteric example?",
        back: "Al2O3 (also Al(OH)3 for hydroxide chemistry).",
        examPhrasing: "Predict acid and base reactions from position near the metal–non-metal boundary.",
        tags: ["prediction"],
      },
      {
        id: "t9-3-f7",
        noteId: "t9-3",
        difficulty: 4,
        front: "Noble gas boiling points down Group 18?",
        back: "Increase: larger electron cloud → stronger London dispersion forces between atoms.",
        examPhrasing: "Explain a physical trend in Group 18.",
        tags: ["group-18"],
      },
      {
        id: "t9-3-f8",
        noteId: "t9-3",
        difficulty: 4,
        front: "Displacement rule for Cl2, Br2, I2 in aqueous halides?",
        back: "A halogen displaces halide ions of elements below it in the group from solution.",
        examPhrasing: "Predict whether a displacement reaction occurs.",
        confusionPair: "oxidising strength vs boiling point down Group 17",
        tags: ["displacement"],
      },
      {
        id: "t9-3-f9",
        noteId: "t9-3",
        difficulty: 5,
        front: "Chemical evidence Br2 vs Cl2 in displacement terms?",
        back: "Cl2 displaces Br- and I-; Br2 displaces I- but not Cl-; match observations to that ladder.",
        examPhrasing: "Deduce a halogen from displacement data.",
        tags: ["deduction"],
      },
      {
        id: "t9-3-f10",
        noteId: "t9-3",
        difficulty: 5,
        front: "What does chloride formula MClx emphasise first about an unknown metal?",
        back: "Primarily oxidation state and therefore group pattern; period needs extra physical or reactivity evidence.",
        examPhrasing: "Separate what a formula tells you about group versus period.",
        tags: ["reasoning"],
      },
    ],
  },
};
