import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 23 (A Level) — Lattice energy / Born–Haber; solution & hydration; entropy; Gibbs.
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §23.1–23.4):
 *
 * **t23-1 (23.1)** — d1–d10: definitions (ΔH_at°, ΔH_latt°, EA), trends (Groups 16/17), cycles (+1/+2, –1/–2), calculations, charge/radius vs |ΔH_latt°|.
 * **t23-2 (23.2)** — d1–d10: ΔH_hyd°, ΔH_sol°, cycles with lattice + hydration, calculations, charge/radius vs |ΔH_hyd°|.
 * **t23-3 (23.3)** — d1–d10: entropy definition, sign prediction (state change, Δn_gas, temperature), ΔS° = ΣS°(products) − ΣS°(reactants).
 * **t23-4 (23.4)** — d1–d10: ΔG° = ΔH° − TΔS°, calculations (consistent J vs kJ), feasibility from sign of ΔG, temperature effect on feasibility.
 *
 * Sign conventions (9701-style): ΔH_latt° is the enthalpy change for M+(g) + X−(g) → MX(s) and is **negative** (exothermic lattice formation from gaseous ions). For the dissolution cycle,
 * ΔH_sol° = Σ ΔH_hyd°(ions) − ΔH_latt° when ΔH_latt° is written with its **signed** value (negative).
 */
export const CHEMISTRY_TOPIC23_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t23-1": {
    noteId: "t23-1",
    drills: [
      {
        id: "t23-1-d1",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define, for an element, the standard enthalpy change of atomisation, ΔH_at°. Define the lattice energy, ΔH_latt°, of an ionic solid MX, stating clearly the physical states in your definition and the sign you expect for an exothermic lattice formation from gaseous ions.",
        modelAnswerPoints: [
          "ΔH_at° is the standard enthalpy change when one mole of gaseous atoms is formed from the element in its standard state under standard conditions.",
          "Lattice energy ΔH_latt° is the standard enthalpy change when one mole of solid ionic compound is formed from its gaseous ions in their standard states (e.g. M+(g) + X−(g) → MX(s) for a 1:1 salt).",
          "Lattice formation from widely separated gaseous ions releases electrostatic stabilisation energy, so ΔH_latt° is negative (exothermic) for a stable ionic lattice.",
        ],
        workedSolution: [
          "The enthalpy of atomisation always refers to producing gaseous atoms from the element as it is normally tabulated under standard states, so for chlorine it is 1/2 Cl2(g) → Cl(g) scaled to one mole of atoms, and for sodium it is Na(s) → Na(g), with each process being endothermic (positive ΔH_at°) because bonds or metallic attractions must be broken.",
          "Lattice energy must be defined with gaseous ions going to the crystalline solid; it is not the same as bond dissociation in a molecular gas. Because bringing oppositely charged ions together from infinite separation to a fixed lattice releases energy, the enthalpy change for M+(g) + X−(g) → MX(s) is exothermic and recorded as a negative value in data tables that follow this convention.",
        ],
        commonMistake:
          "Defining lattice energy as breaking the solid into ions (the reverse process) without stating the direction, or omitting state symbols (g) and (s) in the definition.",
        tags: ["definitions", "lattice-energy", "atomisation"],
      },
      {
        id: "t23-1-d2",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Define the first electron affinity, EA1, of an element. Explain why first electron affinities become **more exothermic** (more negative ΔH) from Group 16 oxygen to Group 16 polonium, and why the first EA of Group 17 chlorine is more exothermic than that of Group 17 iodine.",
        modelAnswerPoints: [
          "First electron affinity is the enthalpy change when one mole of gaseous atoms gains one mole of electrons to form one mole of gaseous 1− ions: X(g) + e− → X−(g).",
          "Down Group 16 the extra electron enters the same valence shell type but the atom is larger with more shielding; nuclear attraction on the added electron is weaker, so less energy is released on attachment and EA1 becomes less exothermic (less negative) from O to Po.",
          "Down Group 17 the same pattern holds: added electron farther from nucleus with more inner shielding, so EA1 becomes less exothermic from Cl to I; chlorine’s first EA is more exothermic than iodine’s.",
        ],
        workedSolution: [
          "Examination definitions must show gaseous atom plus electron giving singly charged gaseous anion for EA1, with standard-state caveats understood even if not repeated every time.",
          "Trend explanations should cite increasing atomic radius and shielding down the group reducing the effective pull on the incoming electron, which weakens the exothermicity of electron gain.",
        ],
        commonMistake:
          "Claiming EA1 becomes more exothermic down Groups 16 or 17, or confusing first EA with second EA for oxygen.",
        tags: ["electron-affinity", "trends", "definitions"],
      },
      {
        id: "t23-1-d3",
        noteId: "t23-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement about lattice enthalpies (formation of one mole of solid from gaseous ions) is correct for isostructural ionic compounds?",
        options: [
          { id: "A", text: "Increasing ionic charge magnitude while holding radii similar makes ΔH_latt° less exothermic." },
          { id: "B", text: "Increasing ionic charge magnitude while holding radii similar makes ΔH_latt° more exothermic (more negative)." },
          { id: "C", text: "Lattice energy is always positive because bonds are formed." },
          { id: "D", text: "Increasing cation radius strongly at constant charges always makes |ΔH_latt°| larger." },
        ],
        correctOptionId: "B",
        explanation:
          "Greater charge product |z+z−| strengthens electrostatic attraction in the Born–Landé sense, so lattice formation from gaseous ions releases more energy (more negative ΔH_latt°) if ion sizes do not simultaneously increase a lot.",
        distractorRationale: {
          A: "That reverses the effect of charge: higher magnitude charges stabilise the lattice more strongly.",
          C: "By the syllabus definition used in Born–Haber work, forming the solid from gaseous ions is exothermic, so ΔH_latt° is negative.",
          D: "Larger ions mean longer interionic distances, weakening attraction; |ΔH_latt°| tends to decrease, not increase, when only radii swell at fixed charges.",
        },
        tags: ["lattice-energy", "charge-radius"],
      },
      {
        id: "t23-1-d4",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "For sodium chloride, NaCl, list the **six** standard steps that together make up the Born–Haber cycle from Na(s) and 1/2 Cl2(g) to NaCl(s), naming each enthalpy change (e.g. atomisation, first ionisation energy, first electron affinity, lattice energy, formation). State the sign (positive or negative) you expect for each step under standard conditions, apart from ΔH_f° which may be given either way depending on data.",
        modelAnswerPoints: [
          "(1) ΔH_at°(Na): Na(s) → Na(g) — endothermic (+).",
          "(2) 1/2 bond enthalpy of Cl2: 1/2 Cl2(g) → Cl(g) — endothermic (+).",
          "(3) IE1(Na): Na(g) → Na+(g) + e− — endothermic (+).",
          "(4) EA1(Cl): Cl(g) + e− → Cl−(g) — exothermic (−) for chlorine.",
          "(5) ΔH_latt°: Na+(g) + Cl−(g) → NaCl(s) — exothermic (−).",
          "(6) ΔH_f°: Na(s) + 1/2 Cl2(g) → NaCl(s) — exothermic (−) for NaCl.",
        ],
        workedSolution: [
          "The cycle links elements in their standard states to gaseous ions and then to the ionic solid, so the vertical sequence is atomisation of metal, bond dissociation of halogen scaled to one atom, removal of the valence electron from the metal atom, addition of the electron to the halogen atom, lattice formation from the ions, and the overall standard enthalpy of formation as the sum of those steps by Hess’s law.",
          "Chlorine’s first electron affinity is exothermic, so it enters the cycle as a negative contribution when written as Cl(g) + e− → Cl−(g), whereas all bond-breaking and ionisation steps are endothermic and positive.",
        ],
        commonMistake:
          "Using Cl2(g) → 2Cl(g) without halving to match one mole of NaCl, or omitting the lattice step direction (gaseous ions to solid).",
        tags: ["born-haber", "naCl", "cycle"],
      },
      {
        id: "t23-1-d5",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Use the following standard data for potassium bromide, KBr(s), to calculate the lattice enthalpy ΔH_latt° for the process K+(g) + Br−(g) → KBr(s). ΔH_f°(KBr, s) = −392 kJ mol−1; ΔH_at°(K) = +89 kJ mol−1; ΔH_at°(Br, from 1/2 Br2) = +112 kJ mol−1; IE1(K) = +419 kJ mol−1; EA1(Br) = −325 kJ mol−1.",
        modelAnswerPoints: [
          "Hess rearrangement: ΔH_latt° = ΔH_f° − ΔH_at°(K) − ΔH_at°(Br) − IE1(K) − EA1(Br).",
          "Substitution: ΔH_latt° = (−392) − (+89) − (+112) − (+419) − (−325).",
          "Arithmetic: ΔH_latt° = −687 kJ mol−1 (3 s.f.).",
          "The large negative value shows strong stabilisation when gaseous ions form the KBr lattice.",
        ],
        workedSolution: [
          "Summing the conventional Born–Haber steps from elements to solid equals ΔH_f°, so ΔH_f° = ΔH_at°(K) + ΔH_at°(Br) + IE1(K) + EA1(Br) + ΔH_latt°, hence ΔH_latt° = ΔH_f° − ΔH_at°(K) − ΔH_at°(Br) − IE1(K) − EA1(Br).",
          "Carefully treat EA1(Br) as −325 in the subtraction: −(−325) contributes +325 algebraically inside the bracket expansion, but the compact formula above already encodes the signs once values are inserted.",
        ],
        commonMistake:
          "Dropping the sign on EA1 or reversing the rearrangement so lattice energy appears with the wrong magnitude or wrong sign.",
        tags: ["born-haber", "calculation", "KBr"],
      },
      {
        id: "t23-1-d6",
        noteId: "t23-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Magnesium oxide, MgO, has a much more exothermic lattice enthalpy than sodium fluoride, NaF. Which **pair** of reasons best explains this in qualitative terms?",
        options: [
          { id: "A", text: "MgO has smaller ions and lower charges than NaF." },
          { id: "B", text: "MgO has higher ionic charges and similar or smaller internuclear distances than NaF, strengthening electrostatic attraction." },
          { id: "C", text: "NaF is covalent whereas MgO is ionic." },
          { id: "D", text: "Lattice enthalpy depends only on ion mass, and Mg is heavier than Na." },
        ],
        correctOptionId: "B",
        explanation:
          "Lattice stabilisation scales strongly with charge product and inversely with interionic distance; Mg2+O2− has double charges compared with Na+F−, giving far more exothermic lattice formation.",
        distractorRationale: {
          A: "Mg2+ and O2− carry higher magnitudes of charge than Na+ and F−, not lower.",
          C: "Both compounds are treated as ionic lattice models at this level; the difference is charge and size, not a simple ionic versus covalent switch in this comparison.",
          D: "Ion mass is not the syllabus explanation for lattice enthalpy trends; charge and radius dominate.",
        },
        tags: ["lattice-energy", "MgO", "qualitative"],
      },
      {
        id: "t23-1-d7",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "For magnesium chloride, MgCl2(s), write the **formation** equation from elements in their standard states that matches ΔH_f°(MgCl2). State which Born–Haber terms require a **second** ionisation energy and which require **twice** the chlorine atomisation and **twice** the first electron affinity of chlorine. Explain briefly why the **second electron affinity of oxygen** is endothermic when constructing a cycle for MgO, but chlorine only needs EA1 for MgCl2.",
        modelAnswerPoints: [
          "Formation: Mg(s) + Cl2(g) → MgCl2(s) (one mole MgCl2 from standard states; use Cl2 not 1/2 Cl2 because two Cl per formula).",
          "Second ionisation energy of magnesium is required because Mg(g) → Mg2+(g) + 2e− is done as IE1 + IE2.",
          "Two moles of Cl atoms are needed, so include 2 × ΔH_at°(Cl from 1/2 Cl2) and 2 × EA1(Cl) for Cl(g) + e− → Cl−(g) twice.",
          "Oxygen gains two electrons overall; the second electron is added to O−(g), where electron–electron repulsion outweighs nuclear attraction, so ΔEA2(O) is positive (endothermic). Chloride only needs one electron per Cl−.",
        ],
        workedSolution: [
          "The stoichiometry of MgCl2 fixes that two chloride ions form per magnesium ion, so every per-atom chlorine step is doubled while magnesium passes through Mg+(g) then Mg2+(g) using successive ionisation energies.",
          "For oxides, the second electron affinity of oxygen is explicitly endothermic in examination cycles because forming O2− from O(g) is modelled as two separate electron additions, the second of which is unfavourable in the gas phase even though lattice stabilisation later compensates in the solid.",
        ],
        commonMistake:
          "Using 1/2 Cl2 with a factor of two inconsistently, or omitting IE2 for Mg2+.",
        tags: ["born-haber", "MgCl2", "second-EA"],
      },
      {
        id: "t23-1-d8",
        noteId: "t23-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which equation correctly represents the **first electron affinity** of fluorine under standard conditions?",
        options: [
          { id: "A", text: "F2(g) + 2e− → 2F−(g)" },
          { id: "B", text: "F(g) + e− → F−(g)" },
          { id: "C", text: "1/2 F2(g) + e− → F−(g)" },
          { id: "D", text: "F(g) → F+(g) + e−" },
        ],
        correctOptionId: "B",
        explanation:
          "Electron affinity is defined per mole of **gaseous atoms** gaining electrons to form gaseous anions; fluorine uses F(g) + e− → F−(g).",
        distractorRationale: {
          A: "That process involves molecular fluorine and two atoms at once; EA1 is defined for atomic fluorine.",
          C: "Atomisation uses 1/2 F2 → F(g), but EA1 is written from F(g), not directly from F2.",
          D: "That represents ionisation of fluorine, not electron gain.",
        },
        tags: ["electron-affinity", "definitions"],
      },
      {
        id: "t23-1-d9",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain, in terms of ionic charge and ionic radius, why the lattice enthalpy of CaO(s) is more exothermic than that of KF(s) **even though** the interionic distance in CaO is not dramatically smaller than in KF.",
        modelAnswerPoints: [
          "Lattice enthalpy magnitude increases with the product of the magnitudes of the ionic charges |z+z−|.",
          "CaO involves doubly charged Ca2+ and O2−, whereas KF involves singly charged K+ and F−, so electrostatic stabilisation is much stronger in CaO.",
          "Although absolute ion sizes influence distance, the charge upgrade from +1/−1 to +2/−2 dominates the comparison in lattice enthalpy data.",
        ],
        workedSolution: [
          "Born–Law style reasoning recognises that potential energy scales approximately as z+z−/r, so doubling both charges multiplies the attractive term by four before detailed radius differences are considered.",
          "Therefore CaO’s lattice formation from gaseous ions is far more exothermic than KF’s even if mean ionic radii do not shrink by a factor that alone would explain the gap.",
        ],
        commonMistake:
          "Attributing the whole difference only to 'smaller ions' without mentioning the change in ionic charges from KF to CaO.",
        tags: ["lattice-energy", "qualitative", "CaO"],
      },
      {
        id: "t23-1-d10",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "Rubidium chloride, RbCl(s), has ΔH_f° = −435 kJ mol−1. Given ΔH_at°(Rb) = +86 kJ mol−1, ΔH_at°(Cl from 1/2 Cl2) = +122 kJ mol−1, IE1(Rb) = +403 kJ mol−1, EA1(Cl) = −349 kJ mol−1, calculate ΔH_latt° for Rb+(g) + Cl−(g) → RbCl(s). Comment on whether rubidium’s position below potassium in Group 1 is consistent with the **less exothermic** lattice enthalpy you obtain compared with a typical textbook value for KCl(s) (more negative than about −720 kJ mol−1).",
        modelAnswerPoints: [
          "ΔH_latt° = ΔH_f° − ΔH_at°(Rb) − ΔH_at°(Cl) − IE1(Rb) − EA1(Cl).",
          "ΔH_latt° = (−435) − 86 − 122 − 403 − (−349) = −697 kJ mol−1 (3 s.f.).",
          "Rb+ is larger than K+ at the same +1 charge, so electrostatic stabilisation of the chloride lattice is weaker than for KCl, giving a less exothermic (less negative) ΔH_latt° than for KCl — consistent with the data comparison requested.",
        ],
        workedSolution: [
          "Rearranging the Born–Haber sum isolates lattice enthalpy as the only unknown once other steps are tabulated, yielding about −697 kJ mol−1 for RbCl under the numbers supplied.",
          "Down Group 1 the cation radius increases, lengthening M+···Cl− contacts and reducing |ΔH_latt°| compared with potassium’s salt, which matches the qualitative expectation even before precise literature comparison.",
        ],
        commonMistake:
          "Comparing lattice values without sign language: 'less exothermic' means algebraically **larger** (less negative) ΔH_latt°, not a more negative number.",
        tags: ["born-haber", "RbCl", "trends"],
      },
    ],
    flashcards: [
      {
        id: "t23-1-f1",
        noteId: "t23-1",
        difficulty: 1,
        front: "What is standard enthalpy of atomisation?",
        back: "Enthalpy change when one mole of gaseous atoms forms from the element in its standard state (e.g. Na(s) → Na(g); 1/2 Cl2(g) → Cl(g)).",
        examPhrasing: "Define the term standard enthalpy change of atomisation, ΔH_at°.",
        tags: ["definitions", "atomisation"],
      },
      {
        id: "t23-1-f2",
        noteId: "t23-1",
        difficulty: 1,
        front: "Define lattice energy ΔH_latt° for MX.",
        back: "Standard enthalpy change when one mole of solid ionic compound forms from its gaseous ions: M+(g) + X−(g) → MX(s); exothermic (negative).",
        examPhrasing: "Define lattice energy for an ionic solid, with states.",
        confusionPair: "lattice formation vs lattice breaking",
        tags: ["lattice-energy", "definitions"],
      },
      {
        id: "t23-1-f3",
        noteId: "t23-1",
        difficulty: 2,
        front: "Define first electron affinity EA1.",
        back: "Enthalpy change when one mole of gaseous atoms gains one mole of electrons to form one mole of gaseous X− ions: X(g) + e− → X−(g).",
        examPhrasing: "Define first electron affinity of an element.",
        tags: ["electron-affinity", "definitions"],
      },
      {
        id: "t23-1-f4",
        noteId: "t23-1",
        difficulty: 2,
        front: "EA1 trend down Group 17?",
        back: "Becomes less exothermic (less negative): added electron farther from nucleus, more shielding.",
        examPhrasing: "Describe the trend in first electron affinities down Group 17.",
        tags: ["trends", "halogens"],
      },
      {
        id: "t23-1-f5",
        noteId: "t23-1",
        difficulty: 3,
        front: "Born–Haber: core steps for NaCl from elements?",
        back: "Na atomisation, 1/2 Cl2 → Cl, IE1(Na), EA1(Cl), lattice formation Na+(g)+Cl−(g)→NaCl(s); sum = ΔH_f°.",
        examPhrasing: "Outline the Born–Haber cycle for sodium chloride.",
        tags: ["born-haber", "NaCl"],
      },
      {
        id: "t23-1-f6",
        noteId: "t23-1",
        difficulty: 3,
        front: "Why is second EA of oxygen endothermic?",
        back: "Adding an electron to O−(g) faces strong electron–electron repulsion in the compact anion; energy must be supplied.",
        examPhrasing: "Explain why the second electron affinity of oxygen is positive.",
        tags: ["electron-affinity", "oxygen"],
      },
      {
        id: "t23-1-f7",
        noteId: "t23-1",
        difficulty: 4,
        front: "Effect of higher ionic charges on |ΔH_latt°|?",
        back: "Increases magnitude (more exothermic lattice formation) if radii do not increase enough to cancel the charge effect.",
        examPhrasing: "Explain how ionic charge affects lattice enthalpy.",
        tags: ["lattice-energy", "charge"],
      },
      {
        id: "t23-1-f8",
        noteId: "t23-1",
        difficulty: 4,
        front: "Effect of larger ionic radius on |ΔH_latt°| at fixed charge?",
        back: "Generally decreases |ΔH_latt°|: ions farther apart, weaker electrostatic attraction per mole of lattice.",
        examPhrasing: "Explain how ionic radius affects lattice enthalpy.",
        confusionPair: "charge effect vs radius effect",
        tags: ["lattice-energy", "radius"],
      },
      {
        id: "t23-1-f9",
        noteId: "t23-1",
        difficulty: 5,
        front: "MgCl2 Born–Haber: what is doubled for chlorine?",
        back: "Atomisation to 2 Cl(g) and EA1 twice (2 × [Cl(g)+e−→Cl−(g)]); plus IE1+IE2 for Mg.",
        examPhrasing: "State which terms are doubled in a Born–Haber cycle for MgCl2.",
        tags: ["born-haber", "MgCl2"],
      },
      {
        id: "t23-1-f10",
        noteId: "t23-1",
        difficulty: 5,
        front: "Hess: how to get ΔH_latt° from ΔH_f° and other steps?",
        back: "ΔH_latt° = ΔH_f° − Σ(other steps with correct signs): atomisations, ionisations, electron affinities as written for forming gaseous ions then lattice.",
        examPhrasing: "Rearrange a Born–Haber cycle to calculate lattice enthalpy.",
        tags: ["born-haber", "calculation"],
      },
    ],
  },
  "t23-2": {
    noteId: "t23-2",
    drills: [
      {
        id: "t23-2-d1",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define the standard enthalpy change of solution, ΔH_sol°, of an ionic compound MX(s). Define the standard enthalpy change of hydration, ΔH_hyd°, of a **single** gaseous ion such as Na+(g), stating the role of water clearly.",
        modelAnswerPoints: [
          "ΔH_sol° is the standard enthalpy change when one mole of solute dissolves completely in enough water to form an infinitely dilute solution (or when one mole of solute forms a solution at a specified concentration if the data refer to that).",
          "For MX(s) → M+(aq) + X−(aq), ΔH_sol° is the enthalpy change for the dissolution process at standard conditions.",
          "ΔH_hyd° for an ion is the standard enthalpy change when one mole of the gaseous ion is surrounded by water to form aqueous ions at infinite dilution: M+(g) → M+(aq) (exothermic for many cations).",
        ],
        workedSolution: [
          "Solution enthalpy always tracks the overall change from crystalline solute to hydrated ions in water, not the stepwise path, so it is a state-function difference between initial solid plus solvent and final solution at the same pressure and temperature standard.",
          "Hydration enthalpy refers only to the gas-to-aq transfer of the ion, capturing ion–dipole interactions with water molecules replacing vacuum separation.",
        ],
        commonMistake:
          "Defining hydration as MX(s) → ions without mentioning the gaseous ion as the starting state, or confusing infinite dilution wording with lattice breaking alone.",
        tags: ["definitions", "solution", "hydration"],
      },
      {
        id: "t23-2-d2",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "For a 1:1 ionic salt MX(s), write the thermochemical cycle that links ΔH_sol°, ΔH_latt°, ΔH_hyd°(M+) and ΔH_hyd°(X−) when ΔH_latt° is defined for M+(g) + X−(g) → MX(s). Derive the equation **with correct signs** used in calculations.",
        modelAnswerPoints: [
          "MX(s) → M+(g) + X−(g) has enthalpy change −ΔH_latt° because it is the reverse of lattice formation.",
          "M+(g) → M+(aq) is ΔH_hyd°(M+); X−(g) → X−(aq) is ΔH_hyd°(X−).",
          "Overall MX(s) → M+(aq) + X−(aq): ΔH_sol° = ΔH_hyd°(M+) + ΔH_hyd°(X−) − ΔH_latt° when ΔH_latt° is the signed value for lattice **formation** from gaseous ions (negative).",
        ],
        workedSolution: [
          "Hess’s law: MX(s) → M+(aq) + X−(aq) can go via MX(s) → M+(g) + X−(g) (reverse of lattice formation, enthalpy −ΔH_latt°) followed by hydrations, so ΔH_sol° = ΔH_hyd°(M+) + ΔH_hyd°(X−) − ΔH_latt° when ΔH_latt° is the **signed** lattice formation enthalpy (negative).",
          "Numerically, subtracting a negative lattice term adds the lattice-breaking cost |ΔH_latt°| to the (negative) hydration sum.",
        ],
        commonMistake:
          "Writing ΔH_sol° = ΔH_latt° + ΔH_hyd without reversing the lattice direction, or adding the lattice enthalpy instead of subtracting the signed formation value.",
        tags: ["cycle", "solution", "lattice", "hydration"],
      },
      {
        id: "t23-2-d3",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Given ΔH_latt°(LiCl, s) = −846 kJ mol−1, ΔH_hyd°(Li+) = −520 kJ mol−1 and ΔH_hyd°(Cl−) = −364 kJ mol−1, calculate ΔH_sol° for LiCl(s) → Li+(aq) + Cl−(aq). State whether dissolution is exothermic or endothermic overall.",
        modelAnswerPoints: [
          "Use ΔH_sol° = ΔH_hyd°(Li+) + ΔH_hyd°(Cl−) − ΔH_latt°.",
          "ΔH_sol° = (−520) + (−364) − (−846) = −38 kJ mol−1 (2 s.f. or 3 s.f. consistent with data).",
          "Negative ΔH_sol° means the overall dissolution process is exothermic under these data.",
        ],
        workedSolution: [
          "Substitute the signed lattice value −846 so subtracting it adds +846 to the sum of the two negative hydration terms, leaving a small negative overall solution enthalpy.",
          "LiCl is a classic borderline case where strong hydration nearly balances the large lattice energy release requirement for vaporising ions, giving a modestly exothermic net dissolution enthalpy.",
        ],
        commonMistake:
          "Using +846 inside the formula without the minus sign in front of ΔH_latt°, or summing lattice and hydrations as if all were endothermic steps.",
        tags: ["calculation", "LiCl", "cycle"],
      },
      {
        id: "t23-2-d4",
        noteId: "t23-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which ion is expected to have the **most exothermic** (most negative) standard enthalpy change of hydration at infinite dilution?",
        options: [
          { id: "A", text: "K+(aq) from K+(g)" },
          { id: "B", text: "Na+(aq) from Na+(g)" },
          { id: "C", text: "Mg2+(aq) from Mg2+(g)" },
          { id: "D", text: "Rb+(aq) from Rb+(g)" },
        ],
        correctOptionId: "C",
        explanation:
          "Hydration enthalpy becomes more exothermic with higher charge density: Mg2+ is smaller and doubly charged compared with Group 1 +1 ions, so ion–dipole interactions with water are strongest among the choices.",
        distractorRationale: {
          A: "K+ is larger and singly charged; hydration is less exothermic than for Mg2+.",
          B: "Na+ is smaller than K+ but still only +1; Mg2+ wins on charge and size combined.",
          D: "Rb+ is the largest +1 ion listed, giving the least exothermic hydration of the alkalis shown.",
        },
        tags: ["hydration", "charge-density"],
      },
      {
        id: "t23-2-d5",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain, in terms of ionic charge and ionic radius, why Mg2+(g) → Mg2+(aq) is much more exothermic than Na+(g) → Na+(aq), and why Cl−(g) → Cl−(aq) is less exothermic than F−(g) → F−(aq) at the same charge magnitude.",
        modelAnswerPoints: [
          "Hydration enthalpy magnitude increases with charge density |z|/r (qualitative language accepted: higher charge and smaller radius strengthen ion–dipole attraction with water).",
          "Mg2+ has higher charge and smaller ionic radius than Na+, so hydration of Mg2+ is far more exothermic.",
          "F− is smaller than Cl− at the same −1 charge, so water can approach closer on average, making hydration of F− more exothermic than Cl−.",
        ],
        workedSolution: [
          "Water molecules orient their δ+ hydrogen toward anions and δ− oxygen toward cations; closer approach and stronger electric field at the ion surface release more energy when the ion is small and/or highly charged.",
          "Therefore trends compare charge first, then radius, for isoelectronic-type series or halide comparisons.",
        ],
        commonMistake:
          "Saying 'larger ion hydrates more strongly because there is more surface' — incorrect for the syllabus radius argument.",
        tags: ["hydration", "qualitative"],
      },
      {
        id: "t23-2-d6",
        noteId: "t23-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Potassium nitrate has an endothermic enthalpy change of solution. Which statement about the **enthalpy cycle** for KNO3(s) → K+(aq) + NO3−(aq) is correct?",
        options: [
          { id: "A", text: "ΔH_sol° is positive, so the sum of hydration enthalpies is more exothermic than |ΔH_latt°|." },
          { id: "B", text: "ΔH_sol° is positive, so breaking the lattice into gaseous ions (reverse of lattice formation) requires more energy than is released hydrating those ions." },
          { id: "C", text: "ΔH_sol° is positive, so lattice formation from gaseous ions is endothermic." },
          { id: "D", text: "ΔH_sol° is positive, so ΔH_latt° is necessarily positive." },
        ],
        correctOptionId: "B",
        explanation:
          "Endothermic dissolution means the lattice-breaking component (−ΔH_latt°, positive magnitude) outweighs the exothermic hydrations: ΔH_sol° = ΔH_hyd(K+) + ΔH_hyd(NO3−) − ΔH_latt° > 0.",
        distractorRationale: {
          A: "That would imply a negative ΔH_sol°, not an endothermic one.",
          C: "Lattice **formation** from gaseous ions remains exothermic (negative ΔH_latt°); the cycle uses its reverse as an endothermic step.",
          D: "ΔH_latt° for formation from gaseous ions is still negative; positivity of ΔH_sol° is about the balance with hydrations, not the sign convention of lattice formation itself.",
        },
        tags: ["KNO3", "endothermic-dissolution", "cycle"],
      },
      {
        id: "t23-2-d7",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "The standard enthalpy change of solution of NaI(s) is +7.5 kJ mol−1. Given ΔH_latt°(NaI, s) = −702 kJ mol−1, calculate the sum ΔH_hyd°(Na+) + ΔH_hyd°(I−). Comment on the relative sizes of lattice and hydration terms.",
        modelAnswerPoints: [
          "From ΔH_sol° = ΔH_hyd°(Na+) + ΔH_hyd°(I−) − ΔH_latt°, rearrange: sum of hydrations = ΔH_sol° + ΔH_latt°.",
          "Sum = (+7.5) + (−702) = −694.5 kJ mol−1 ≈ −695 kJ mol−1 (3 s.f.).",
          "The two hydration steps together are only slightly less exothermic than the lattice formation step is exothermic, leaving a small positive ΔH_sol°.",
        ],
        workedSolution: [
          "Algebraically ΔH_hyd(Na+) + ΔH_hyd(I−) = ΔH_sol° + ΔH_latt° with ΔH_latt° negative, so the sum of hydrations is a large negative number close to the lattice value.",
          "Large iodide lowers hydration exothermicity versus chloride, which shifts NaI toward slightly endothermic dissolution enthalpy even though the iodide lattice is less tight than NaCl.",
        ],
        commonMistake:
          "Subtracting ΔH_sol° from the lattice incorrectly and obtaining the wrong sign on the hydration sum.",
        tags: ["calculation", "NaI", "rearrangement"],
      },
      {
        id: "t23-2-d8",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Describe how you would represent, on an enthalpy level diagram, the route from MX(s) to separated aqueous ions via (i) gaseous ions and (ii) direct dissolution. Label ΔH_sol°, ΔH_latt° and the two hydration enthalpies, showing why the diagram is a valid Hess cycle.",
        modelAnswerPoints: [
          "Draw two routes from MX(s) + solvent on the left to M+(aq) + X−(aq) on the right at the same final level.",
          "Upper route: MX(s) → M+(g) + X−(g) (endothermic step, −ΔH_latt° relative to lattice formation arrow direction) then downward exothermic steps to aqueous ions labelled ΔH_hyd°(M+) and ΔH_hyd°(X−).",
          "Lower route: single arrow labelled ΔH_sol°; Hess’s law: both routes share the same initial and final states so enthalpy sums match.",
        ],
        workedSolution: [
          "The vertical spacing for lattice breaking must be consistent with tabulated lattice **formation** values: breaking MX(s) to ions is the reverse of lattice formation, so it appears as an uphill (+|ΔH_latt|) segment if drawn from solid to gaseous ions.",
          "Hydration arrows from gas to aqueous run downhill for typical ions, and the direct dissolution arrow is the net of the upper path.",
        ],
        commonMistake:
          "Drawing lattice formation from solid instead of from gas, or labelling the wrong direction for the reverse lattice step.",
        tags: ["diagram", "hess", "cycle"],
      },
      {
        id: "t23-2-d9",
        noteId: "t23-2",
        kind: "mcq",
        difficulty: 2,
        stem: "For CaCl2(s) → Ca2+(aq) + 2Cl−(aq), how must hydration terms appear in the energy-cycle equation relative to one mole of CaCl2?",
        options: [
          { id: "A", text: "Use ΔH_hyd°(Ca2+) + ΔH_hyd°(Cl−) only." },
          { id: "B", text: "Use ΔH_hyd°(Ca2+) + 2 ΔH_hyd°(Cl−) − ΔH_latt°(CaCl2)." },
          { id: "C", text: "Use 2 ΔH_hyd°(Ca2+) + ΔH_hyd°(Cl−) − ΔH_latt°(CaCl2)." },
          { id: "D", text: "Ignore the second chloride ion because it is a spectator." },
        ],
        correctOptionId: "B",
        explanation:
          "Per mole CaCl2 there is one Ca2+ and two Cl− in aqueous solution, so chloride hydration is counted twice; lattice enthalpy is for forming CaCl2(s) from Ca2+(g) + 2Cl−(g).",
        distractorRationale: {
          A: "Omits the second chloride ion’s hydration contribution.",
          C: "Doubles calcium hydration incorrectly.",
          D: "Both chloride ions are hydrated in solution; neither is a spectator in the dissolution enthalpy cycle.",
        },
        tags: ["CaCl2", "stoichiometry", "cycle"],
      },
      {
        id: "t23-2-d10",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "Silver chloride is sparingly soluble; for the **standard enthalpy of solution** of AgCl(s), ΔH_sol° = +65 kJ mol−1. Given ΔH_hyd°(Ag+) = −475 kJ mol−1 and ΔH_hyd°(Cl−) = −364 kJ mol−1, calculate ΔH_latt° for Ag+(g) + Cl−(g) → AgCl(s). State whether your answer is consistent with AgCl being much **less soluble** than NaCl in water.",
        modelAnswerPoints: [
          "Rearrange: ΔH_latt° = ΔH_hyd°(Ag+) + ΔH_hyd°(Cl−) − ΔH_sol°.",
          "ΔH_latt° = (−475) + (−364) − (+65) = −904 kJ mol−1 (3 s.f.).",
          "A very exothermic lattice formation means the crystal is strongly stabilised relative to separated gaseous ions, disfavouring dissolution enthalpically; low aqueous solubility is consistent with large |ΔH_latt°| and endothermic ΔH_sol°.",
        ],
        workedSolution: [
          "Inserting the numbers shows a highly negative lattice enthalpy for AgCl, reflecting strong bonding in the solid despite similar 1:1 stoichiometry to NaCl.",
          "Solubility also depends on entropy and Ksp, but the enthalpy story here matches the idea that AgCl is hard to break apart into aqueous ions compared with many alkali halides.",
        ],
        commonMistake:
          "Using ΔH_latt° = ΔH_sol − hydrations without rearranging, which flips the sign and magnitude completely.",
        tags: ["AgCl", "calculation", "solubility"],
      },
    ],
    flashcards: [
      {
        id: "t23-2-f1",
        noteId: "t23-2",
        difficulty: 1,
        front: "Define ΔH_sol° for MX(s).",
        back: "Standard enthalpy change when one mole of solid dissolves to form aqueous ions (infinite dilution wording as syllabus).",
        examPhrasing: "Define standard enthalpy change of solution.",
        tags: ["definitions", "solution"],
      },
      {
        id: "t23-2-f2",
        noteId: "t23-2",
        difficulty: 1,
        front: "Define ΔH_hyd° for M+(g).",
        back: "Standard enthalpy change when one mole of gaseous ions becomes aqueous ions at infinite dilution: M+(g) → M+(aq).",
        examPhrasing: "Define enthalpy change of hydration of an ion.",
        tags: ["definitions", "hydration"],
      },
      {
        id: "t23-2-f3",
        noteId: "t23-2",
        difficulty: 2,
        front: "Key equation linking ΔH_sol°, lattice, hydrations?",
        back: "ΔH_sol° = ΔH_hyd°(M+) + ΔH_hyd°(X−) − ΔH_latt° with ΔH_latt° for M+(g)+X−(g)→MX(s) negative.",
        examPhrasing: "Write an equation for an enthalpy cycle involving solution, lattice and hydration enthalpies.",
        confusionPair: "subtract vs add lattice term",
        tags: ["cycle", "equation"],
      },
      {
        id: "t23-2-f4",
        noteId: "t23-2",
        difficulty: 2,
        front: "Why can ΔH_sol° be +ve for some salts?",
        back: "Lattice breaking (reverse of exothermic lattice formation) can demand more energy than hydrating the gaseous ions releases.",
        examPhrasing: "Explain why some ionic solids dissolve endothermically.",
        tags: ["solution", "endothermic"],
      },
      {
        id: "t23-2-f5",
        noteId: "t23-2",
        difficulty: 3,
        front: "Higher charge → hydration enthalpy?",
        back: "More exothermic (more negative) for similar radius because stronger ion–dipole interactions.",
        examPhrasing: "Explain how ionic charge affects enthalpy of hydration.",
        tags: ["hydration", "charge"],
      },
      {
        id: "t23-2-f6",
        noteId: "t23-2",
        difficulty: 3,
        front: "Larger ionic radius → hydration enthalpy?",
        back: "Generally less exothermic: ion–solvent distances increase, field weaker at solvent.",
        examPhrasing: "Explain how ionic radius affects enthalpy of hydration.",
        tags: ["hydration", "radius"],
      },
      {
        id: "t23-2-f7",
        noteId: "t23-2",
        difficulty: 4,
        front: "Reverse of lattice formation enthalpy?",
        back: "MX(s) → M+(g)+X−(g) is −ΔH_latt°; if ΔH_latt° = −800 kJ mol−1, breaking lattice is +800 kJ mol−1.",
        examPhrasing: "State the enthalpy change for converting one mole of solid to gaseous ions.",
        confusionPair: "formation vs breaking lattice",
        tags: ["lattice-energy", "cycle"],
      },
      {
        id: "t23-2-f8",
        noteId: "t23-2",
        difficulty: 4,
        front: "CaCl2 dissolution: hydration stoichiometry?",
        back: "One Ca2+ hydration + two times Cl− hydration per mole CaCl2.",
        examPhrasing: "Construct an energy cycle for dissolving calcium chloride.",
        tags: ["CaCl2", "stoichiometry"],
      },
      {
        id: "t23-2-f9",
        noteId: "t23-2",
        difficulty: 5,
        front: "Why is Hess valid on the dissolution diagram?",
        back: "Same initial (MX(s)+H2O) and final (dilute aqueous ions) states; enthalpy is a state function.",
        examPhrasing: "Justify use of Hess’s law for enthalpy of solution cycles.",
        tags: ["hess", "cycle"],
      },
      {
        id: "t23-2-f10",
        noteId: "t23-2",
        difficulty: 5,
        front: "Find unknown hydration from ΔH_sol° and ΔH_latt°?",
        back: "ΔH_hyd(missing) = ΔH_sol° + ΔH_latt° − sum of known hydrations (watch stoichiometry).",
        examPhrasing: "Calculate an enthalpy of hydration from solution and lattice data.",
        tags: ["calculation", "rearrangement"],
      },
    ],
  },
  "t23-3": {
    noteId: "t23-3",
    drills: [
      {
        id: "t23-3-d1",
        noteId: "t23-3",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Define entropy, S, in the syllabus sense relating to the number of possible arrangements of the particles and their energy in a given system.",
        modelAnswerPoints: [
          "Entropy is a measure of the number of ways energy can be distributed among the particles (microstates) consistent with the macroscopic state.",
          "Higher entropy means more dispersal of energy and/or more positional disorder — more arrangements available at the same total energy.",
        ],
        workedSolution: [
          "Exam answers should link 'number of arrangements' to microstates and disorder without claiming entropy is 'only disorder' without the energy-distribution idea.",
          "The definition is qualitative at this syllabus level; calculations use standard entropies tabulated from Third-Law considerations.",
        ],
        commonMistake:
          "Saying entropy is simply 'messiness' with no mention of quantised arrangements or energy spreading among particles.",
        tags: ["entropy", "definitions"],
      },
      {
        id: "t23-3-d2",
        noteId: "t23-3",
        kind: "mcq",
        difficulty: 1,
        stem: "What is the sign of the entropy change of the **system** when pure ice melts to liquid water at 0 °C and 1 atm?",
        options: [
          { id: "A", text: "ΔS is negative because hydrogen bonds strengthen." },
          { id: "B", text: "ΔS is positive because the liquid has more motional freedom than the crystal." },
          { id: "C", text: "ΔS is zero because temperature is constant." },
          { id: "D", text: "ΔS is negative because density increases on melting." },
        ],
        correctOptionId: "B",
        explanation:
          "Melting increases positional and vibrational disorder; for the system, ΔS > 0 for solid → liquid at the fusion temperature.",
        distractorRationale: {
          A: "H-bonding detail does not reverse the overall increase in accessible microstates on melting.",
          C: "Constant T does not imply zero entropy change for a phase change with ΔH ≠ 0.",
          D: "Density trends are not the syllabus sign criterion for ΔS on melting.",
        },
        tags: ["melting", "sign-of-ΔS"],
      },
      {
        id: "t23-3-d3",
        noteId: "t23-3",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Predict the sign of ΔS for each process: (i) H2O(l) → H2O(g) at its boiling point, (ii) 2H2(g) + O2(g) → 2H2O(l), (iii) NaCl(s) dissolving to Na+(aq) + Cl−(aq). Justify each in one sentence.",
        modelAnswerPoints: [
          "(i) ΔS > 0: gas has many more accessible microstates than the liquid at the same temperature.",
          "(ii) ΔS < 0: three moles of gas form two moles of liquid, greatly reducing the number of gas molecules and motional freedom.",
          "(iii) ΔS > 0: ions leave a fixed lattice and become mobile in solution, increasing disorder even if water becomes more ordered locally.",
        ],
        workedSolution: [
          "For (ii), the syllabus explicitly expects recognition that decreasing moles of gas gives a negative entropy contribution dominating the overall sign.",
          "Ionic dissolution entropy arguments focus on the crystal → mobile ions picture at this level, acknowledging local hydration order only qualitatively if at all.",
        ],
        commonMistake:
          "Claiming ΔS > 0 for 2H2 + O2 → 2H2O(l) because 'water is disordered' while ignoring the loss of three moles of gas.",
        tags: ["sign-of-ΔS", "gas-moles", "dissolving"],
      },
      {
        id: "t23-3-d4",
        noteId: "t23-3",
        kind: "mcq",
        difficulty: 2,
        stem: "For N2O4(g) ⇌ 2NO2(g), which statement about the standard entropy change (system) for the forward dissociation is correct?",
        options: [
          { id: "A", text: "ΔS° is negative because two moles of gas form from one." },
          { id: "B", text: "ΔS° is positive because the number of gas molecules increases." },
          { id: "C", text: "ΔS° is zero because both species are gases." },
          { id: "D", text: "ΔS° cannot be predicted without bond enthalpies." },
        ],
        correctOptionId: "B",
        explanation:
          "One mole of gas producing two moles of gas increases translational disorder; ΔS° > 0 for the forward reaction as written.",
        distractorRationale: {
          A: "That would be true for the reverse combination 2NO2 → N2O4.",
          C: "Both being gases does not remove the stoichiometric change in amount of substance in the gas phase.",
          D: "Bond enthalpies predict ΔH, not the sign pattern for ΔS from particle-number arguments here.",
        },
        tags: ["gas-moles", "equilibrium"],
      },
      {
        id: "t23-3-d5",
        noteId: "t23-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Use standard molar entropies S° / J K−1 mol−1: N2(g) 192, H2(g) 131, NH3(g) 193. Calculate ΔS° for N2(g) + 3H2(g) → 2NH3(g). Comment on the sign in terms of change in amount of gaseous substance.",
        modelAnswerPoints: [
          "ΔS° = ΣS°(products) − ΣS°(reactants) = 2S°(NH3) − [S°(N2) + 3S°(H2)].",
          "ΔS° = 2(193) − [192 + 3(131)] = 386 − 585 = −199 J K−1 mol−1 (3 s.f.).",
          "Four moles of gas reactants form two moles of gas products, so a decrease in gas moles gives negative ΔS°.",
        ],
        workedSolution: [
          "Carry units J K−1 mol−1 through; the result is per mole of reaction as written (one mole N2).",
          "The stoichiometric compression of gas particle count dominates standard entropy change sign even though ammonia is a more complex molecule.",
        ],
        commonMistake:
          "Using reactants minus products, or forgetting to multiply S°(H2) by three and S°(NH3) by two.",
        tags: ["calculation", "ΔS°", "Haber"],
      },
      {
        id: "t23-3-d6",
        noteId: "t23-3",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Explain the sign of ΔS for the **surroundings** when water boils at 100 °C and 1 atm, given that vaporisation is endothermic for the system.",
        modelAnswerPoints: [
          "During boiling the system absorbs enthalpy from the surroundings at constant pressure.",
          "Energy spreads into the system, so the surroundings lose thermal disorder locally and ΔS_surr is negative for the vaporisation step of the system.",
        ],
        workedSolution: [
          "The syllabus item on temperature change links heat flow to entropy of surroundings qualitatively: endothermic vaporisation withdraws heat from surroundings, lowering their entropy.",
          "This complements ΔS_sys > 0 for H2O(l) → H2O(g); total universe entropy still increases for a spontaneous irreversible boil with superheated surroundings supply.",
        ],
        commonMistake:
          "Claiming ΔS_surr is also positive for boiling in an isolated statement without naming what supplies the heat.",
        tags: ["boiling", "surroundings", "entropy"],
      },
      {
        id: "t23-3-d7",
        noteId: "t23-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Which change **always** increases the entropy of a perfect crystalline substance **without** chemical reaction?",
        options: [
          { id: "A", text: "Cooling the solid from 300 K to 200 K at constant pressure." },
          { id: "B", text: "Heating the solid from 200 K to 300 K at constant pressure." },
          { id: "C", text: "Compressing the solid isothermally to smaller volume." },
          { id: "D", text: "Removing thermal energy reversibly at 0 K." },
        ],
        correctOptionId: "B",
        explanation:
          "For a given substance, raising temperature increases thermal disorder and spreads energy over more accessible vibrational levels, so S increases with T for a stable solid.",
        distractorRationale: {
          A: "Cooling reduces thermal entropy.",
          C: "Reducing volume for a solid typically lowers positional entropy for the crystal as a whole in simple models used at this level.",
          D: "At 0 K a perfect crystal is assigned S → 0 by convention; you cannot remove entropy below the Third-Law reference in this framework.",
        },
        tags: ["temperature", "entropy"],
      },
      {
        id: "t23-3-d8",
        noteId: "t23-3",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Calculate ΔS° for CaCO3(s) → CaO(s) + CO2(g) using S° / J K−1 mol−1: CaCO3(s) 89, CaO(s) 40, CO2(g) 214. State the sign and link it to the appearance of a gaseous product from a solid reactant.",
        modelAnswerPoints: [
          "ΔS° = [S°(CaO) + S°(CO2)] − S°(CaCO3) = (40 + 214) − 89.",
          "ΔS° = +165 J K−1 mol−1 (3 s.f.).",
          "A gas forms from a single solid, increasing the number of gas particles and motional disorder, so ΔS° is positive.",
        ],
        workedSolution: [
          "Apply products minus reactants strictly; solids contribute less absolute entropy than gas, but the CO2 term drives the increase.",
          "Thermal decomposition reactions producing CO2 are classic examples of positive ΔS° in examination entropy questions.",
        ],
        commonMistake:
          "Subtracting the gas entropy twice or using reactants minus products.",
        tags: ["calculation", "carbonate", "decomposition"],
      },
      {
        id: "t23-3-d9",
        noteId: "t23-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which expression is the correct syllabus formula for the standard entropy change of a reaction?",
        options: [
          { id: "A", text: "ΔS° = ΣS°(reactants) − ΣS°(products)" },
          { id: "B", text: "ΔS° = ΣS°(products) − ΣS°(reactants)" },
          { id: "C", text: "ΔS° = ΣS°(products) + ΣS°(reactants)" },
          { id: "D", text: "ΔS° = ΔH° / T for all reactions" },
        ],
        correctOptionId: "B",
        explanation:
          "Standard entropy change of reaction is sum of standard entropies of products minus sum for reactants, each multiplied by stoichiometric coefficient.",
        distractorRationale: {
          A: "That reverses the products and reactants roles.",
          C: "Entropies subtract, not add both sides together for ΔS°.",
          D: "ΔH/T relates to surroundings in equilibrium reasoning, not the general definition of ΔS° from tabulated S° values.",
        },
        tags: ["formula", "ΔS°"],
      },
      {
        id: "t23-3-d10",
        noteId: "t23-3",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "Ammonium nitrate dissolves in water with ΔH_sol° > 0 yet the mixing is observed to occur spontaneously in a beaker at 298 K. Explain how a **positive entropy change of the system** can reconcile this with the Second Law at a qualitative level, without calculating ΔG.",
        modelAnswerPoints: [
          "Spontaneity of an isolated mixing process is governed by total entropy change, not enthalpy alone.",
          "Dissolution increases disorder of ions leaving the crystal lattice and mixing throughout the solvent (large positive ΔS_sys contribution).",
          "Even if ΔH_sol° is endothermic, TΔS can be large enough that overall Gibbs free energy becomes negative (preview of Topic 23.4) — here state in words that entropy gain of the system plus any entropy change of surroundings from heat flow can make the overall process spontaneous.",
        ],
        workedSolution: [
          "The crystal lattice is highly ordered; forming mobile hydrated ions and mixing them in water increases the number of accessible arrangements substantially.",
          "Therefore a modest endothermic enthalpy of solution is compatible with spontaneity when the entropy increase is sufficiently large at the temperature concerned.",
        ],
        commonMistake:
          "Claiming endothermic processes cannot be spontaneous under any conditions.",
        tags: ["NH4NO3", "spontaneity", "entropy"],
      },
    ],
    flashcards: [
      {
        id: "t23-3-f1",
        noteId: "t23-3",
        difficulty: 1,
        front: "Syllabus definition of entropy S?",
        back: "Measure related to the number of possible arrangements of particles and their energy in a system (microstates).",
        examPhrasing: "Define entropy.",
        tags: ["definitions", "entropy"],
      },
      {
        id: "t23-3-f2",
        noteId: "t23-3",
        difficulty: 1,
        front: "Sign of ΔS when a solid melts?",
        back: "ΔS > 0: liquid has greater disorder / more arrangements than the crystal.",
        examPhrasing: "Predict the sign of entropy change when ice melts.",
        tags: ["melting", "sign"],
      },
      {
        id: "t23-3-f3",
        noteId: "t23-3",
        difficulty: 2,
        front: "Sign of ΔS when gas condenses?",
        back: "ΔS < 0 for the system: gas → liquid reduces motional freedom.",
        examPhrasing: "Predict the sign of entropy change when steam condenses.",
        tags: ["condensation", "sign"],
      },
      {
        id: "t23-3-f4",
        noteId: "t23-3",
        difficulty: 2,
        front: "ΔS° formula from tabulated S°?",
        back: "ΔS° = ΣS°(products) − ΣS°(reactants) (include stoichiometric multipliers).",
        examPhrasing: "Calculate ΔS° for a reaction given standard entropies.",
        tags: ["formula", "calculation"],
      },
      {
        id: "t23-3-f5",
        noteId: "t23-3",
        difficulty: 3,
        front: "More moles of gas on product side → ΔS?",
        back: "Usually ΔS > 0 (greater gas particle count increases disorder).",
        examPhrasing: "Explain the sign of ΔS when gas moles increase in a reaction.",
        tags: ["gas-moles", "sign"],
      },
      {
        id: "t23-3-f6",
        noteId: "t23-3",
        difficulty: 3,
        front: "Fewer moles of gas on product side → ΔS?",
        back: "Usually ΔS < 0 (gas is consumed).",
        examPhrasing: "Predict entropy change when gases combine to fewer gas molecules.",
        tags: ["gas-moles", "sign"],
      },
      {
        id: "t23-3-f7",
        noteId: "t23-3",
        difficulty: 4,
        front: "Dissolving NaCl(s): sign of ΔS_sys?",
        back: "Typically ΔS > 0: ordered lattice → mobile ions in solution.",
        examPhrasing: "Predict the entropy change when sodium chloride dissolves in water.",
        confusionPair: "ΔS_sys vs local hydration order",
        tags: ["dissolving", "entropy"],
      },
      {
        id: "t23-3-f8",
        noteId: "t23-3",
        difficulty: 4,
        front: "Units of S° and ΔS°?",
        back: "J K−1 mol−1 (entropy change of reaction has same units per mole of reaction as written).",
        examPhrasing: "State the units of standard entropy.",
        tags: ["units", "entropy"],
      },
      {
        id: "t23-3-f9",
        noteId: "t23-3",
        difficulty: 5,
        front: "Heating a gas at constant p: ΔS?",
        back: "ΔS > 0: more thermal energy spreads over accessible energy levels.",
        examPhrasing: "Predict the sign of entropy change when a gas is heated.",
        tags: ["temperature", "entropy"],
      },
      {
        id: "t23-3-f10",
        noteId: "t23-3",
        difficulty: 5,
        front: "Solid decomposes to solid + gas: ΔS sign?",
        back: "ΔS > 0: gas formation dominates despite one solid product.",
        examPhrasing: "Predict the sign of ΔS for thermal decomposition of a carbonate.",
        tags: ["decomposition", "gas"],
      },
    ],
  },
  "t23-4": {
    noteId: "t23-4",
    drills: [
      {
        id: "t23-4-d1",
        noteId: "t23-4",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "State the Gibbs equation relating standard Gibbs free energy change, standard enthalpy change and standard entropy change at temperature T. State the condition on ΔG for a reaction to be feasible (spontaneous) under the stated conditions in the usual sign convention.",
        modelAnswerPoints: [
          "ΔG° = ΔH° − TΔS° (for standard states at temperature T).",
          "A process is feasible in the forward direction when ΔG < 0 (strictly for the direction written); ΔG > 0 means not feasible as written; ΔG = 0 corresponds to equilibrium for the reaction quotient considered.",
        ],
        workedSolution: [
          "The equation combines enthalpy-driven and entropy-driven contributions, with entropy entering multiplied by temperature to give an energy term with the same units as ΔH when ΔS is in J K−1 mol−1 and T in kelvin.",
          "Feasibility is read from the sign of ΔG for the direction of change specified in the question, not from ΔH alone.",
        ],
        commonMistake:
          "Writing ΔG° = ΔH° + TΔS° or using Celsius directly without converting to kelvin in calculations.",
        tags: ["gibbs", "equation", "feasibility"],
      },
      {
        id: "t23-4-d2",
        noteId: "t23-4",
        kind: "mcq",
        difficulty: 1,
        stem: "For a reaction with ΔH° < 0 and ΔS° < 0, what happens to the likelihood of spontaneity as temperature **increases**?",
        options: [
          { id: "A", text: "The −TΔS° term becomes more negative, so spontaneity always increases." },
          { id: "B", text: "The −TΔS° term becomes more positive (less favourable), so high T disfavours spontaneity." },
          { id: "C", text: "Temperature has no effect because ΔH° is negative." },
          { id: "D", text: "ΔG° becomes more negative because T multiplies a negative ΔS°." },
        ],
        correctOptionId: "B",
        explanation:
          "ΔG° = ΔH° − TΔS° with ΔS° negative gives −TΔS° = +|ΔS°|T, which grows with T and opposes the favourable negative ΔH°, so spontaneity decreases at high T for this sign combination.",
        distractorRationale: {
          A: "With negative ΔS°, −TΔS° is positive and increases with T, not more negative.",
          C: "Entropy term always matters unless ΔS° is exactly zero.",
          D: "That mis-evaluates the sign: negative ΔS° makes −TΔS° positive.",
        },
        tags: ["temperature", "gibbs", "signs"],
      },
      {
        id: "t23-4-d3",
        noteId: "t23-4",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Given ΔH° = +180 kJ mol−1 and ΔS° = +250 J K−1 mol−1 for a reaction at 298 K, calculate ΔG° and state whether the forward reaction is feasible under standard conditions.",
        modelAnswerPoints: [
          "Convert ΔS° to kJ K−1 mol−1: 250 J K−1 mol−1 = 0.250 kJ K−1 mol−1.",
          "TΔS° = 298 × 0.250 = +74.5 kJ mol−1.",
          "ΔG° = ΔH° − TΔS° = +180 − 74.5 = +105.5 kJ mol−1 ≈ +106 kJ mol−1 (3 s.f.).",
          "ΔG° > 0 so the forward reaction is **not** feasible under standard conditions at 298 K.",
        ],
        workedSolution: [
          "Always convert entropy to the same energy unit as enthalpy before subtracting, or convert ΔH to J mol−1; inconsistent units are the commonest arithmetic error.",
          "Endothermic with positive entropy can become feasible at higher T because TΔS grows until it exceeds ΔH.",
        ],
        commonMistake:
          "Using 250 directly as kJ or forgetting to convert J to kJ when ΔH is in kJ mol−1.",
        tags: ["calculation", "units", "gibbs"],
      },
      {
        id: "t23-4-d4",
        noteId: "t23-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "For the same reaction as in the data ΔH° = +180 kJ mol−1, ΔS° = +250 J K−1 mol−1, calculate the **minimum temperature** (kelvin, to 3 s.f.) at which the forward reaction becomes feasible under standard pressure, assuming ΔH° and ΔS° are independent of T.",
        modelAnswerPoints: [
          "Set ΔG° = 0 ⇒ T = ΔH° / ΔS° (only valid when ΔS° > 0 for an endothermic case).",
          "Use consistent units: T = (180 × 10^3 J mol−1) / (250 J K−1 mol−1).",
          "T = 720 K (3 s.f.).",
          "For T > 720 K, TΔS exceeds ΔH so ΔG° < 0 and the forward direction becomes feasible.",
        ],
        workedSolution: [
          "Rearranging ΔH − TΔS < 0 gives T > ΔH/ΔS when ΔS is positive, so the threshold is the ratio at equality.",
          "720 K is far above room temperature, illustrating why some endothermic reactions need heating before they run spontaneously.",
        ],
        commonMistake:
          "Dividing kJ by J without conversion, giving T in wrong order of magnitude.",
        tags: ["temperature-threshold", "gibbs"],
      },
      {
        id: "t23-4-d5",
        noteId: "t23-4",
        kind: "mcq",
        difficulty: 2,
        stem: "Which row correctly matches the signs of ΔH° and ΔS° for the thermal decomposition CaCO3(s) → CaO(s) + CO2(g) and the feasibility at **very high** temperature?",
        options: [
          { id: "A", text: "ΔH° > 0, ΔS° > 0 — feasible at sufficiently high T" },
          { id: "B", text: "ΔH° < 0, ΔS° < 0 — feasible at sufficiently high T" },
          { id: "C", text: "ΔH° > 0, ΔS° < 0 — feasible at all T" },
          { id: "D", text: "ΔH° < 0, ΔS° > 0 — never feasible" },
        ],
        correctOptionId: "A",
        explanation:
          "Carbonate decomposition is endothermic (bond breaking in crystal, forming CO2) and produces gas from solid, so ΔS° > 0; then ΔG° = ΔH° − TΔS° becomes negative at high T.",
        distractorRationale: {
          B: "Decomposition is not exothermic overall under normal conditions, and gas formation gives positive ΔS°, not negative.",
          C: "Positive ΔH with negative ΔS makes ΔG > 0 at all T; never spontaneous forward.",
          D: "Negative ΔH with positive ΔS would be spontaneous at all T, not never feasible.",
        },
        tags: ["CaCO3", "feasibility", "gibbs"],
      },
      {
        id: "t23-4-d6",
        noteId: "t23-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "For 2NO(g) + O2(g) → 2NO2(g), ΔH° = −114 kJ mol−1 and ΔS° = −147 J K−1 mol−1 at 298 K. Calculate ΔG° and comment on feasibility at 298 K. Predict qualitatively how increasing temperature affects feasibility for this sign combination.",
        modelAnswerPoints: [
          "ΔS° = −0.147 kJ K−1 mol−1.",
          "TΔS° = 298 × (−0.147) = −43.8 kJ mol−1.",
          "ΔG° = −114 − (−43.8) = −70.2 kJ mol−1 ≈ −70.2 kJ mol−1 (3 s.f.).",
          "ΔG° < 0 so feasible at 298 K; because ΔS° < 0, increasing T makes −TΔS less negative (more positive ΔG), reducing spontaneity at high T.",
        ],
        workedSolution: [
          "Substitute carefully: ΔG = ΔH − TΔS with negative ΔS gives −TΔS positive, which **adds onto** an already negative ΔH in magnitude terms when evaluating numerically.",
          "This reaction is enthalpy-driven at room temperature but entropy disfavours high-temperature spontaneity.",
        ],
        commonMistake:
          "Computing ΔG = ΔH + TΔS or mishandling the double negative when ΔS is negative.",
        tags: ["calculation", "NO2", "temperature"],
      },
      {
        id: "t23-4-d7",
        noteId: "t23-4",
        kind: "mcq",
        difficulty: 2,
        stem: "A reaction has ΔG° = −200 kJ mol−1 at 298 K. Which statement is correct?",
        options: [
          { id: "A", text: "The forward reaction is not feasible under standard conditions." },
          { id: "B", text: "The forward reaction is feasible under standard conditions." },
          { id: "C", text: "The reaction must be instantaneous." },
          { id: "D", text: "ΔH° must be negative." },
        ],
        correctOptionId: "B",
        explanation:
          "Negative ΔG° means the forward reaction is thermodynamically feasible under standard conditions for the equation as written; kinetics are separate.",
        distractorRationale: {
          A: "Negative ΔG° implies feasibility, not the opposite.",
          C: "Thermodynamic feasibility does not guarantee a fast rate.",
          D: "ΔG° combines ΔH° and TΔS°; ΔH° could be positive if TΔS° is sufficiently positive.",
        },
        tags: ["feasibility", "gibbs"],
      },
      {
        id: "t23-4-d8",
        noteId: "t23-4",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "At 298 K, ΔG° = −95.0 kJ mol−1 for a reaction with ΔS° = −180 J K−1 mol−1. Calculate ΔH° for the reaction as written, stating units.",
        modelAnswerPoints: [
          "Rearrange ΔG° = ΔH° − TΔS° ⇒ ΔH° = ΔG° + TΔS°.",
          "TΔS° = 298 × (−0.180) = −53.64 kJ mol−1.",
          "ΔH° = −95.0 + (−53.64) = −148.64 kJ mol−1 ≈ −149 kJ mol−1 (3 s.f.).",
        ],
        workedSolution: [
          "Convert J K−1 mol−1 to kJ K−1 mol−1 before multiplying by T to keep kJ mol−1 throughout.",
          "Negative ΔS contributes a positive term to ΔH when solving from known ΔG at fixed T.",
        ],
        commonMistake:
          "Solving ΔH = ΔG − TΔS instead of plus TΔS with correct sign substitution.",
        tags: ["rearrangement", "gibbs"],
      },
      {
        id: "t23-4-d9",
        noteId: "t23-4",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Explain why some **exothermic** reactions (ΔH° < 0) can become **non-feasible at high temperature** when ΔS° < 0, using ΔG° = ΔH° − TΔS°. Explain why the same forward reaction is **more** feasible when the temperature is **lowered**, clarifying the sign of −TΔS° when ΔS° is negative.",
        modelAnswerPoints: [
          "With ΔS° < 0, −TΔS° = +|ΔS°|T, which is **positive** and **grows** as T increases.",
          "At sufficiently high T, the positive −TΔS° term can outweigh the negative ΔH°, giving ΔG° > 0 so the forward reaction is no longer feasible despite being exothermic.",
          "When T is lowered, the positive −TΔS° term shrinks, so the negative ΔH° dominates again and ΔG° becomes negative: more feasible at lower T for this sign combination.",
        ],
        workedSolution: [
          "This is the classic entropy penalty for reactions that reduce disorder (e.g. fewer gas molecules): enthalpy favours products at all T, but entropy opposes products more strongly as temperature rises.",
          "The key algebraic point is that a negative ΔS° makes −TΔS° **add positive** contributions to ΔG°, not subtract them.",
        ],
        commonMistake:
          "Claiming exothermic reactions are always spontaneous at any temperature, or mis-signing −TΔS° when ΔS° is negative.",
        tags: ["qualitative", "temperature", "gibbs"],
      },
      {
        id: "t23-4-d10",
        noteId: "t23-4",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "For N2(g) + 3H2(g) ⇌ 2NH3(g), use ΔH° = −92.0 kJ mol−1 and ΔS° = −199 J K−1 mol−1 (3 s.f.). Calculate ΔG° at (i) 298 K and (ii) 800 K, assuming ΔH° and ΔS° are temperature-independent. State at which temperature the forward reaction is **more** thermodynamically favourable and relate this to the entropy contribution.",
        modelAnswerPoints: [
          "ΔS° = −0.199 kJ K−1 mol−1.",
          "(i) ΔG°(298) = −92.0 − 298(−0.199) = −92.0 + 59.3 = −32.7 kJ mol−1.",
          "(ii) ΔG°(800) = −92.0 − 800(−0.199) = −92.0 + 159.2 = +67.2 kJ mol−1 (3 s.f.).",
          "Forward reaction more feasible at 298 K (more negative ΔG°); at higher T the positive −TΔS term (because ΔS° < 0) opposes the exothermic ΔH°, making ΔG° less negative then positive.",
        ],
        workedSolution: [
          "Each kelvin multiplies the entropy penalty for forming fewer gas moles; by 800 K the TΔS magnitude exceeds the exothermic enthalpy benefit in this crude constant-ΔH/ΔS model.",
          "Industrial Haber conditions use pressure and catalysts; thermodynamically alone, lower T favours ammonia by ΔG°, but kinetics need compromise.",
        ],
        commonMistake:
          "Using Celsius 25 instead of 298 K, or forgetting that ΔS° negative makes −TΔS positive.",
        tags: ["Haber", "multi-temperature", "gibbs"],
      },
    ],
    flashcards: [
      {
        id: "t23-4-f1",
        noteId: "t23-4",
        difficulty: 1,
        front: "Gibbs equation?",
        back: "ΔG° = ΔH° − TΔS° (standard states, T in kelvin).",
        examPhrasing: "State the equation relating ΔG°, ΔH° and ΔS°.",
        tags: ["gibbs", "equation"],
      },
      {
        id: "t23-4-f2",
        noteId: "t23-4",
        difficulty: 1,
        front: "When is a reaction feasible?",
        back: "When ΔG < 0 for the direction considered (under the stated conditions).",
        examPhrasing: "State how the sign of ΔG relates to feasibility.",
        tags: ["feasibility", "gibbs"],
      },
      {
        id: "t23-4-f3",
        noteId: "t23-4",
        difficulty: 2,
        front: "ΔH° < 0 and ΔS° > 0: spontaneity vs T?",
        back: "ΔG° < 0 at all T (both terms favour spontaneity): always thermodynamically feasible forward.",
        examPhrasing: "Predict how ΔG varies with temperature for an exothermic reaction with positive ΔS.",
        tags: ["gibbs", "temperature"],
      },
      {
        id: "t23-4-f4",
        noteId: "t23-4",
        difficulty: 2,
        front: "ΔH° > 0 and ΔS° > 0: high T effect?",
        back: "High T increases TΔS term; ΔG becomes more negative — spontaneity more likely at high T.",
        examPhrasing: "Predict the effect of increasing temperature on feasibility for an endothermic reaction with positive entropy change.",
        tags: ["gibbs", "temperature"],
      },
      {
        id: "t23-4-f5",
        noteId: "t23-4",
        difficulty: 3,
        front: "Convert ΔS° from J to kJ for Gibbs calc?",
        back: "Divide by 1000: e.g. 120 J K−1 mol−1 = 0.120 kJ K−1 mol−1.",
        examPhrasing: "Show how you ensure consistent units in ΔG° = ΔH° − TΔS°.",
        confusionPair: "J vs kJ",
        tags: ["units", "gibbs"],
      },
      {
        id: "t23-4-f6",
        noteId: "t23-4",
        difficulty: 3,
        front: "Temperature at which ΔG° = 0 (ΔS° ≠ 0)?",
        back: "T = ΔH° / ΔS° with consistent units (interpret as approximate if data assume constant ΔH, ΔS).",
        examPhrasing: "Calculate the temperature at which a reaction becomes feasible.",
        tags: ["threshold", "gibbs"],
      },
      {
        id: "t23-4-f7",
        noteId: "t23-4",
        difficulty: 4,
        front: "ΔH° < 0, ΔS° < 0: high T?",
        back: "High T makes −TΔS more positive (ΔS negative) — spontaneity decreases as T rises.",
        examPhrasing: "Predict effect of temperature on feasibility when ΔH is negative and ΔS is negative.",
        tags: ["signs", "gibbs"],
      },
      {
        id: "t23-4-f8",
        noteId: "t23-4",
        difficulty: 4,
        front: "ΔG° > 0 means?",
        back: "Forward reaction not feasible under those standard conditions; reverse may be feasible instead.",
        examPhrasing: "Interpret a positive standard Gibbs energy change.",
        tags: ["feasibility", "gibbs"],
      },
      {
        id: "t23-4-f9",
        noteId: "t23-4",
        difficulty: 5,
        front: "Why ΔG not ΔH alone?",
        back: "Entropy contributes TΔS; spontaneity depends on balance of energy and disorder at that T.",
        examPhrasing: "Explain why enthalpy change alone does not determine feasibility.",
        tags: ["gibbs", "entropy"],
      },
      {
        id: "t23-4-f10",
        noteId: "t23-4",
        difficulty: 5,
        front: "CaCO3 decomposition: ΔH and ΔS signs vs high T?",
        back: "ΔH° > 0, ΔS° > 0 ⇒ high T makes ΔG° negative — decomposition more feasible when heated.",
        examPhrasing: "Predict how temperature affects feasibility of carbonate decomposition.",
        tags: ["CaCO3", "gibbs"],
      },
    ],
  },
};
