import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 24 — Electrochemistry (`t24-1`, `t24-2`).
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §24.1–24.2; each bullet hit by ≥1 drill id):
 *
 * **24.1** — predict products (state, series, concentration) → d1–d3, d8, d10; F = Le → d4; Q = It, mass/volume → d5–d7; Avogadro by electrolysis → d9.
 *
 * **24.2** — define E°, E°cell → d1; SHE → d2; measurement methods → d3; E°cell from two E° + polarity/feasibility + ΔG° → d4, d5; oxidising/reducing reactivity → d6; redox from half-equations → d7; qualitative E vs concentration → d8; Nernst quantitative → d9, d10.
 */
export const CHEMISTRY_TOPIC24_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t24-1": {
    noteId: "t24-1",
    drills: [
      {
        id: "t24-1-d1",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define electrolysis. For an electrolytic cell powered by an external supply, state whether oxidation or reduction occurs at the anode and at the cathode, and state the sign convention for these electrodes relative to the supply in the usual laboratory diagram.",
        modelAnswerPoints: [
          "Electrolysis is the use of electrical energy to drive a non-spontaneous redox reaction.",
          "Oxidation (electron loss) occurs at the anode; reduction (electron gain) occurs at the cathode.",
          "In an electrolytic cell the cathode is the negative electrode and the anode is the positive electrode when driven by a d.c. supply (electrons are pushed into the cathode region).",
        ],
        workedSolution: [
          "Electrolysis means using an external source of electrical energy to force a chemical redox change that would not occur spontaneously in that direction under the same overall conditions, so electrical work is converted into chemical change at the electrodes.",
          "At the anode, species lose electrons to the external circuit, which is oxidation by definition, whereas at the cathode, species gain electrons supplied through the circuit, which is reduction.",
          "When the cell is electrolytic rather than galvanic, the power supply makes the cathode negative and the anode positive in the standard teaching convention, so cations in solution are attracted toward the cathode region and anions toward the anode region while electron flow through the metal conductors matches the supply polarity.",
        ],
        commonMistake:
          "Swapping anode and cathode processes, or treating electrolytic electrode signs like a spontaneous Daniell cell without the external supply.",
        tags: ["definitions", "electrolysis", "anode", "cathode"],
      },
      {
        id: "t24-1-d2",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Predict the substances formed at each electrode when molten lead(II) bromide, PbBr2, is electrolysed using inert electrodes. Then predict the substances formed at each electrode when concentrated aqueous sodium chloride (brine) is electrolysed using inert electrodes. In each case write ionic half-equations with state symbols for the electrode processes you choose.",
        modelAnswerPoints: [
          "Molten PbBr2: only Pb2+ and Br- migrate; cathode Pb2+ + 2e- -> Pb(s); anode 2Br-(l) -> Br2(g) + 2e-.",
          "Aqueous concentrated NaCl: Na+ is too high in the redox series to discharge in water; cathode reduces water/H+ effectively to H2.",
          "Anode: high chloride concentration favours 2Cl-(aq) -> Cl2(g) + 2e- over oxygen from hydroxide.",
          "So molten products are lead and bromine; brine products are hydrogen and chlorine under usual conditions.",
        ],
        workedSolution: [
          "In molten lead(II) bromide there are no solvent molecules competing, so lead(II) ions move to the cathode and each ion accepts two electrons according to Pb2+ + 2e- -> Pb(s), giving metallic lead as the cathode product.",
          "Bromide ions are oxidised at the anode to diatomic bromine, 2Br-(l) -> Br2(g) + 2e-, because bromide is the only negative ion present in quantity in the molten salt.",
          "In concentrated aqueous sodium chloride, sodium ions are present but are not reduced in preference to water-derived hydrogen ions under typical laboratory conditions, so the cathode half-reaction is effectively the reduction of aqueous hydrogen species to hydrogen gas, 2H+(aq) + 2e- -> H2(g), or an equivalent water-based formulation consistent with the mark scheme.",
          "At the anode the high chloride concentration shifts competition toward chloride oxidation, so chloride loses electrons according to 2Cl-(aq) -> Cl2(g) + 2e- rather than immediate dominance of hydroxide oxidation to oxygen, which is why brine electrolysis is associated with chlorine gas at the anode and hydrogen at the cathode when inert electrodes are used.",
        ],
        commonMistake:
          "Treating aqueous NaCl like molten NaCl (depositing sodium metal) or predicting oxygen at the anode while ignoring concentrated halide discharge.",
        tags: ["products", "molten", "aqueous", "half-equations"],
      },
      {
        id: "t24-1-d3",
        noteId: "t24-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Dilute aqueous sodium sulfate is electrolysed between inert electrodes. Which row best identifies the gases evolved at the cathode and anode under normal conditions?",
        options: [
          { id: "A", text: "Cathode: H2; Anode: O2" },
          { id: "B", text: "Cathode: H2; Anode: Cl2" },
          { id: "C", text: "Cathode: Na; Anode: O2" },
          { id: "D", text: "Cathode: SO2; Anode: O2" },
        ],
        correctOptionId: "A",
        explanation:
          "Na+ and SO4^2- are not discharged in dilute aqueous solution at inert electrodes; water is oxidised at the anode to O2 and reduced at the cathode to H2.",
        distractorRationale: {
          B: "Chlorine would require substantial chloride concentration; sulfate solutions are not a source of Cl2 at the anode here.",
          C: "Sodium metal is not deposited from aqueous Na+; water is reduced instead.",
          D: "Sulfate is not oxidised to SO2 under these simple electrolysis conditions; OH-/water oxidation dominates at the anode.",
        },
        tags: ["aqueous", "products", "electrolysis"],
      },
      {
        id: "t24-1-d4",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "State the relationship between the Faraday constant F, the Avogadro constant L, and the elementary charge e. Given e = 1.60 x 10^-19 C and L = 6.02 x 10^23 mol^-1, calculate F to three significant figures and state its unit.",
        modelAnswerPoints: [
          "F = L e (charge per mole of electrons).",
          "Substitution: F = (6.02 x 10^23)(1.60 x 10^-19) = 9.63 x 10^4 C mol^-1 (3 s.f.).",
          "Unit is coulombs per mole (C mol^-1).",
        ],
        workedSolution: [
          "The Faraday constant is defined as the magnitude of charge carried by one mole of electrons, and because each electron carries charge e, one mole of electrons carries L times e, which is written F = L e.",
          "Substituting the given values gives F = (6.02 x 10^23 mol^-1)(1.60 x 10^-19 C) = 9.632 x 10^4 C mol^-1, which rounds to 9.63 x 10^4 C mol^-1 to three significant figures.",
          "The unit of F is therefore coulombs per mole, C mol^-1, because it is total charge divided by amount of electrons in one mole.",
        ],
        commonMistake: "Writing F = e/L or omitting powers of ten in the multiplication.",
        tags: ["faraday", "avogadro", "calculations"],
      },
      {
        id: "t24-1-d5",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "A steady current of 1.85 A flows through an electrolytic cell for 18.0 minutes. Calculate (a) the total charge Q passed, and (b) the amount, in mol, of electrons transferred, taking F = 9.65 x 10^4 C mol^-1. Show your working with units.",
        modelAnswerPoints: [
          "Convert time: t = 18.0 x 60 = 1080 s.",
          "Q = I t = 1.85 x 1080 = 2.00 x 10^3 C (to 3 s.f.).",
          "n(e-) = Q / F = (2.00 x 10^3) / (9.65 x 10^4) = 2.07 x 10^-2 mol.",
        ],
        workedSolution: [
          "The time must be expressed in seconds because the ampere is coulombs per second, so 18.0 minutes is 18.0 x 60 = 1080 s.",
          "The charge passed is Q = I t = 1.85 A x 1080 s = 1998 C, which is reported as 2.00 x 10^3 C if three significant figures are used consistently with the data given.",
          "The amount of electrons in moles is obtained from n(e-) = Q / F = (2.00 x 10^3 C) / (9.65 x 10^4 C mol^-1) = 2.07 x 10^-2 mol, which is the chemical amount of electrons that passed through the external circuit during the stated electrolysis interval.",
        ],
        commonMistake: "Using minutes directly in Q = It without converting to seconds.",
        tags: ["charge", "Q=It", "stoichiometry"],
      },
      {
        id: "t24-1-d6",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Aqueous copper(II) sulfate is electrolysed between inert electrodes using a current of 3.00 A for 965 s. The cathode reaction is Cu2+(aq) + 2e- -> Cu(s). Calculate the mass of copper deposited. Use F = 9.65 x 10^4 C mol^-1 and Ar(Cu) = 63.5.",
        modelAnswerPoints: [
          "Q = I t = 3.00 x 965 = 2895 C.",
          "n(e-) = Q / F = 2895 / (9.65 x 10^4) = 3.00 x 10^-2 mol.",
          "n(Cu) = n(e-) / 2 = 1.50 x 10^-2 mol.",
          "Mass Cu = n M = 1.50 x 10^-2 x 63.5 = 0.953 g.",
        ],
        workedSolution: [
          "First the charge passed is Q = I t = 3.00 A x 965 s = 2895 C, assuming the current is steady over the whole period as stated.",
          "This charge corresponds to n(e-) = Q / F = 2895 C / (9.65 x 10^4 C mol^-1) = 3.00 x 10^-2 mol of electrons to the precision implied by these rounded values.",
          "Each copper(II) ion needs two moles of electrons to become one mole of copper atoms, so n(Cu) = n(e-) / 2 = 1.50 x 10^-2 mol of copper metal is produced at the cathode.",
          "The mass deposited is therefore m = n M = 1.50 x 10^-2 mol x 63.5 g mol^-1 = 0.953 g of copper, which is the expected form of numerical answer for a deposit calculation at this level.",
        ],
        commonMistake: "Using a 1:1 mole ratio between Cu and electrons instead of 1:2 for Cu2+ reduction.",
        tags: ["mass", "deposition", "electrolysis"],
      },
      {
        id: "t24-1-d7",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Dilute aqueous NaOH is electrolysed between inert electrodes. The anode half-reaction may be written 4OH-(aq) -> O2(g) + 2H2O(l) + 4e-. A current of 2.00 A runs for 32.2 min. Taking F = 9.65 x 10^4 C mol^-1 and molar gas volume = 24.0 dm^3 mol^-1 at the conditions stated, calculate the volume of oxygen evolved at the anode.",
        modelAnswerPoints: [
          "t = 32.2 x 60 = 1932 s; Q = 2.00 x 1932 = 3864 C.",
          "n(e-) = Q / F = 3864 / (9.65 x 10^4) = 4.00 x 10^-2 mol (to 3 s.f.).",
          "From the half-equation, n(O2) = n(e-) / 4.",
          "n(O2) = 1.00 x 10^-2 mol; V = n x 24.0 = 0.240 dm^3.",
        ],
        workedSolution: [
          "The duration in seconds is 32.2 min x 60 s min^-1 = 1932 s, so the charge passed is Q = I t = 2.00 A x 1932 s = 3864 C.",
          "The amount of electrons transferred is n(e-) = Q / F = 3864 C / (9.65 x 10^4 C mol^-1) = 4.00 x 10^-2 mol when values are combined consistently.",
          "The given anode process shows that four moles of electrons produce one mole of O2 gas, so n(O2) = n(e-) / 4 = 1.00 x 10^-2 mol of dioxygen molecules are formed at the anode under these assumptions.",
          "Using the stated molar gas volume, the volume is V = n(O2) x 24.0 dm^3 mol^-1 = 1.00 x 10^-2 x 24.0 = 0.240 dm^3 of oxygen gas, which completes the link from electrical measurement to gas amount and volume.",
        ],
        commonMistake: "Using a 2:1 or 1:1 electron ratio to O2 instead of 4:1 from the hydroxide oxidation stoichiometry.",
        tags: ["gas-volume", "oxygen", "stoichiometry"],
      },
      {
        id: "t24-1-d8",
        noteId: "t24-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which statement best explains why concentrated aqueous NaCl can give chlorine at the anode, whereas dilute NaCl with inert electrodes more often leads to oxygen evolution at the anode?",
        options: [
          {
            id: "A",
            text: "Higher chloride concentration makes chloride oxidation thermodynamically/kinetically more competitive relative to hydroxide oxidation.",
          },
          { id: "B", text: "Concentrated NaCl lowers the Faraday constant so chloride oxidises first." },
          { id: "C", text: "Dilute NaCl removes Na+ from the electrode so only sulfate can oxidise." },
          { id: "D", text: "Chlorine always forms at the anode whenever sodium ions are present." },
        ],
        correctOptionId: "A",
        explanation:
          "Electrode potentials and discharge competition depend on species present and concentration; high [Cl-] favours Cl2 formation in the brine case.",
        distractorRationale: {
          B: "F is a physical constant; concentration does not change F.",
          C: "The comparison is about chloride vs hydroxide/water at the anode, not sodium removal.",
          D: "Chlorine formation is not guaranteed merely by Na+; it is the high chloride environment that matters.",
        },
        tags: ["concentration", "anode", "chlorine"],
      },
      {
        id: "t24-1-d9",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Outline how the Avogadro constant L can be obtained from an electrolysis experiment in which silver is deposited from aqueous silver nitrate onto a weighed cathode. Your answer should name the key measurements, show how F is obtained from them, and state how L is then calculated if e is known.",
        modelAnswerPoints: [
          "Measure steady current I and time t to find charge Q = I t.",
          "Find mass increase of cathode from dry weighing before and after to obtain mass of Ag deposited.",
          "Use Ag+ + e- -> Ag to convert mass to moles of Ag and hence moles of electrons n(e-) = n(Ag).",
          "Calculate experimental F = Q / n(e-).",
          "With known elementary charge e, L = F / e.",
        ],
        workedSolution: [
          "In a silver coulometry style experiment the student passes a measured direct current I for a measured time interval t, so the total charge passed is Q = I t with time in seconds, and this value is the electrical input to the cell.",
          "The cathode is weighed dry before electrolysis and again after washing and drying once a known interval of electrolysis has finished, and the mass increase gives the mass of silver metal deposited, which is converted to moles of silver using the relative atomic mass of silver.",
          "Because the reduction half-equation is Ag+ + e- -> Ag, one mole of electrons produces one mole of silver atoms, so the chemical amount of electrons passed equals the amount of silver deposited, allowing an experimental estimate of moles of electrons associated with the measured charge.",
          "The experimental Faraday constant is then F_exp = Q / n(e-), expressed in coulombs per mole of electrons, and if the elementary charge e is known from separate measurements, the Avogadro constant follows from the identity F = L e rearranged to L = F_exp / e, linking macroscopic charge and mass data to the microscopic particle count per mole.",
        ],
        commonMistake:
          "Omitting drying/weighing steps, or claiming L is measured directly without going through F and e.",
        tags: ["avogadro", "experimental", "faraday"],
      },
      {
        id: "t24-1-d10",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Predict the anode and cathode half-reactions when aqueous CuSO4 is electrolysed using pure copper electrodes (not inert). Explain briefly how this setup differs from electrolysis with platinum electrodes for the same electrolyte.",
        modelAnswerPoints: [
          "With Cu electrodes in CuSO4, copper dissolves at the anode: Cu(s) -> Cu2+(aq) + 2e-.",
          "Copper plates out at the cathode: Cu2+(aq) + 2e- -> Cu(s).",
          "This is copper refining / transfer where the electrode material participates, rather than only water or sulfate species reacting at inert surfaces.",
          "With inert electrodes, water-derived H2/O2 or Cu2+ discharge patterns depend on conditions; here the dominant anode process is copper oxidation from the anode itself.",
        ],
        workedSolution: [
          "When both electrodes are copper metal dipping into aqueous copper(II) sulfate, the positive anode polarises the copper strip connected to the positive terminal so that copper atoms are oxidised to aqueous copper(II) ions according to Cu(s) -> Cu2+(aq) + 2e-, which thickens the solution in Cu2+ while eroding the anode physically.",
          "At the cathode, copper(II) ions from solution are reduced back to copper metal on the cathode surface, Cu2+(aq) + 2e- -> Cu(s), so copper is transferred from the anode to the cathode when current flows.",
          "This behaviour contrasts with truly inert electrodes such as platinum, where the electrode merely conducts electrons and the reacting species must come from the solution (or adsorbed water/hydroxide), whereas reactive copper electrodes supply metal atoms directly to the oxidation half-reaction at the anode.",
          "Overall, the learner should recognise that prediction of products must include whether the electrode is inert or part of the redox chemistry, which is why the same CuSO4 electrolyte can show different half-reactions depending on electrode material.",
        ],
        commonMistake:
          "Predicting oxygen at the copper anode in this refining context, or ignoring that the anode copper is oxidised.",
        tags: ["reactive-electrodes", "copper", "refining"],
      },
    ],
    flashcards: [
      {
        id: "t24-1-f1",
        noteId: "t24-1",
        difficulty: 1,
        front: "What is electrolysis?",
        back: "Using electrical energy to drive a non-spontaneous redox reaction.",
        examPhrasing: "State what is meant by electrolysis.",
        tags: ["definitions"],
      },
      {
        id: "t24-1-f2",
        noteId: "t24-1",
        difficulty: 1,
        front: "Which electrode is oxidation in electrolysis?",
        back: "The anode (electrons leave the species being oxidised into the external circuit).",
        examPhrasing: "Identify the electrode at which oxidation occurs.",
        tags: ["anode", "oxidation"],
      },
      {
        id: "t24-1-f3",
        noteId: "t24-1",
        difficulty: 2,
        front: "Sign of cathode and anode in an electrolytic cell?",
        back: "Cathode negative, anode positive (when driven by a d.c. supply).",
        examPhrasing: "State the polarity of the electrodes in electrolysis.",
        tags: ["polarity"],
      },
      {
        id: "t24-1-f4",
        noteId: "t24-1",
        difficulty: 2,
        front: "Relationship F, L, and e?",
        back: "F = L e (charge carried by one mole of electrons).",
        examPhrasing: "Write the equation linking F, L and e.",
        tags: ["faraday"],
      },
      {
        id: "t24-1-f5",
        noteId: "t24-1",
        difficulty: 2,
        front: "How is charge Q related to I and t?",
        back: "Q = I t (coulombs = amperes x seconds).",
        examPhrasing: "Calculate charge from current and time.",
        tags: ["Q=It"],
      },
      {
        id: "t24-1-f6",
        noteId: "t24-1",
        difficulty: 3,
        front: "Moles of electrons from Q?",
        back: "n(e-) = Q / F.",
        examPhrasing: "Convert charge passed to amount of electrons.",
        tags: ["stoichiometry"],
      },
      {
        id: "t24-1-f7",
        noteId: "t24-1",
        difficulty: 3,
        front: "Why is aqueous Na+ not reduced to sodium metal at the cathode?",
        back: "Water/H+ is reduced preferentially; sodium is too reactive to deposit from aqueous ions under normal conditions.",
        examPhrasing: "Explain why hydrogen forms at the cathode when aqueous NaCl is electrolysed.",
        confusionPair: "molten NaCl vs aqueous NaCl",
        tags: ["aqueous", "cathode"],
      },
      {
        id: "t24-1-f8",
        noteId: "t24-1",
        difficulty: 4,
        front: "Brine anode product vs dilute chloride?",
        back: "Concentrated Cl- favours Cl2; dilute often favours O2 from OH-/water oxidation.",
        examPhrasing: "Explain the effect of chloride concentration on anode products.",
        tags: ["concentration", "chlorine"],
      },
      {
        id: "t24-1-f9",
        noteId: "t24-1",
        difficulty: 4,
        front: "Half-equation for hydroxide oxidation to oxygen?",
        back: "4OH-(aq) -> O2(g) + 2H2O(l) + 4e- (or equivalent balanced form).",
        examPhrasing: "Write the anode half-equation for oxygen evolution from alkali.",
        tags: ["half-equations", "oxygen"],
      },
      {
        id: "t24-1-f10",
        noteId: "t24-1",
        difficulty: 5,
        front: "How is L found from electrolysis + known e?",
        back: "Find F from Q and moles of electrons from product stoichiometry, then L = F/e.",
        examPhrasing: "Describe determination of the Avogadro constant by an electrolytic method.",
        tags: ["avogadro", "experiment"],
      },
    ],
  },

  "t24-2": {
    noteId: "t24-2",
    drills: [
      {
        id: "t24-2-d1",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define (a) standard electrode (reduction) potential, E°, and (b) standard cell potential, E°cell, making clear the role of standard conditions and the standard hydrogen electrode in the definition of E°.",
        modelAnswerPoints: [
          "(a) E° is the e.m.f. of a half-cell measured relative to the standard hydrogen electrode with the half-equation written as reduction, under standard conditions.",
          "(b) E°cell is the e.m.f. of the complete cell under standard conditions with no current drawn.",
          "Standard conditions include 298 K, 1 atm for gases, 1 mol dm^-3 for aqueous ions as specified, and SHE assigned E° = 0.00 V.",
        ],
        workedSolution: [
          "The standard electrode potential E° is defined as the potential of a half-cell, written as a reduction process, measured against the standard hydrogen reference under agreed standard conditions, so every tabulated E° value is a relative ranking of how strongly that half-equation tends to run as reduction compared with hydrogen ion reduction under the same standard state.",
          "The standard cell potential E°cell is the potential difference of a whole galvanic cell when all species are in their standard states and no significant current flows through the measuring circuit, so it summarises how favourable the overall cell reaction is under those idealised concentrations and pressures.",
          "Because absolute single-electrode potentials are not measured directly in school treatments, the standard hydrogen electrode is assigned a potential of exactly 0.00 V by convention, and other E° values are anchored to that reference, which is why definitions of E° always mention the SHE explicitly.",
        ],
        commonMistake:
          "Defining E° without mentioning reduction direction, standard states, or reference to SHE.",
        tags: ["definitions", "E-zero", "cell-potential"],
      },
      {
        id: "t24-2-d2",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe the standard hydrogen electrode (SHE). Include the phases in contact with the platinum surface, the gas condition, the solution condition, and the conventional value assigned to its potential.",
        modelAnswerPoints: [
          "Platinum electrode, often coated catalytically, dipping into aqueous H+ at 1 mol dm^-3.",
          "Hydrogen gas at 1 atm bubbled over the platinum so H2/H+ equilibrium is established.",
          "Temperature taken as 298 K for standard data tables.",
          "By convention E° for 2H+(aq) + 2e- <=> H2(g) is 0.00 V.",
        ],
        workedSolution: [
          "The standard hydrogen electrode consists of an inert platinum electrode immersed in an aqueous acid solution containing hydrogen ions at standard concentration, usually quoted as 1 mol dm^-3 for the purpose of standard potential tables at 298 K.",
          "Hydrogen gas at standard pressure, taken as 1 atmosphere, is passed over the platinum surface so that gaseous hydrogen and aqueous hydrogen ions can exchange electrons rapidly at the catalytic metal interface, establishing the reference redox equilibrium.",
          "Platinum itself is not consumed as a bulk reactant but provides electrical contact and surface sites for the H+/H2 couple, which is why the SHE is described as a gas electrode on an inert metal.",
          "By international convention the standard potential assigned to the reduction half-equation 2H+(aq) + 2e- -> H2(g) is exactly 0.00 V, which fixes the zero of the electrochemical scale used for all other E° values.",
        ],
        commonMistake:
          "Omitting pressure/concentration standard states, or assigning a non-zero value to SHE.",
        tags: ["SHE", "standard-hydrogen-electrode"],
      },
      {
        id: "t24-2-d3",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Describe practical cell arrangements to measure standard electrode potentials for (a) a metal in contact with its aqueous ions, and (b) two ions of the same element in different oxidation states in the same solution. In each case name the electrode materials and how the cell is connected to a standard hydrogen electrode.",
        modelAnswerPoints: [
          "(a) Metal wire of the element dipping into 1 mol dm^-3 solution of its ions; connect via salt bridge/voltmeter to SHE to read E° for Mz+/M.",
          "(b) Inert platinum electrode in a solution containing both ions (e.g. Fe2+ and Fe3+ at standard concentrations); connect to SHE similarly.",
          "High-resistance voltmeter; no current drawn for accurate e.m.f.",
        ],
        workedSolution: [
          "For a metal ion half-cell such as Cu2+/Cu, a strip of pure copper is immersed in a 1 mol dm^-3 solution of copper(II) ions, and this half-cell is connected to a standard hydrogen electrode through a salt bridge and a high-resistance voltmeter so the spontaneous cell e.m.f. can be read without polarising the electrodes significantly.",
          "The measured potential with sign convention relative to SHE gives the standard reduction potential for Cu2+ + 2e- -> Cu once liquid junction details are ignored at this level, because the copper metal itself is the electron conductor for the couple being studied.",
          "For a redox system with both oxidation states in solution, such as Fe3+ and Fe2+ together, no bulk metal of iron participates, so an inert platinum electrode is placed in a solution containing both ions at standard concentrations and linked to the SHE in the same overall measurement arrangement.",
          "Electrons then transfer at the platinum surface between Fe3+ and Fe2+ without dissolving the electrode, and the measured standard e.m.f. relative to SHE yields E° for Fe3+ + e- -> Fe2+, which completes the description of how two different classes of half-cells are attached to the universal reference.",
        ],
        commonMistake:
          "Using an iron metal electrode for Fe3+/Fe2+ measurement, or omitting the salt bridge/voltmeter idea.",
        tags: ["measurement", "half-cells", "platinum"],
      },
      {
        id: "t24-2-d4",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 3,
        marks: 7,
        stem: "For the cell represented schematically as Zn(s) | Zn2+(aq) || Cu2+(aq) | Cu(s), E°(Cu2+/Cu) = +0.34 V and E°(Zn2+/Zn) = -0.76 V. Calculate E°cell, identify anode and cathode, state the direction of electron flow in the external wire, and calculate ΔG° for the overall cell reaction as written with n = 2 using F = 9.65 x 10^4 C mol^-1.",
        modelAnswerPoints: [
          "More positive reduction potential is Cu2+/Cu, so Cu is cathode; Zn is anode.",
          "E°cell = E°(cathode) - E°(anode) = 0.34 - (-0.76) = +1.10 V.",
          "Electrons flow from Zn electrode to Cu electrode externally.",
          "ΔG° = -n E°cell F = -2 x 1.10 x 9.65 x 10^4 = -2.12 x 10^5 J mol^-1 (approx -212 kJ mol^-1).",
        ],
        workedSolution: [
          "Comparing the two tabulated reduction potentials shows that copper(II) ion has the more positive E°, so its half-equation runs more readily as reduction, which identifies the copper electrode as the cathode where reduction occurs when the cell operates spontaneously as written.",
          "Zinc has the less positive reduction potential, so the zinc half-equation is reversed in spontaneous operation, making solid zinc the anode where zinc is oxidised to zinc ions, and the standard cell potential is therefore E°cell = E°(cathode) - E°(anode) = (+0.34 V) - (-0.76 V) = +1.10 V.",
          "Because the cell reaction is feasible under standard conditions when E°cell is positive, electrons travel through the external metallic connection from the zinc electrode, which supplies them by oxidation, toward the copper electrode, which accepts them for copper ion reduction.",
          "The standard Gibbs energy change follows from ΔG° = -n E°cell F with n = 2 for the two-electron overall transfer implied by combining Zn -> Zn2+ + 2e- with Cu2+ + 2e- -> Cu, giving ΔG° = -2 x 1.10 V x 9.65 x 10^4 C mol^-1 = -2.12 x 10^5 J mol^-1 to three significant figures, which is about -212 kJ per mole of reaction as written and confirms thermodynamic feasibility through its negative sign.",
        ],
        commonMistake:
          "Using E°cell = E°(anode) - E°(cathode) while keeping both as reduction potentials, or wrong sign on ΔG°.",
        tags: ["E-cell", "delta-G", "polarity"],
      },
      {
        id: "t24-2-d5",
        noteId: "t24-2",
        kind: "mcq",
        difficulty: 2,
        stem: "A galvanic cell has E°cell = -0.20 V for a specified overall reaction under standard conditions. Which statement is correct?",
        options: [
          { id: "A", text: "The reaction as written is feasible under standard conditions." },
          { id: "B", text: "The reverse reaction is feasible under standard conditions." },
          { id: "C", text: "No redox process can occur in the cell." },
          { id: "D", text: "E°cell sign does not relate to feasibility." },
        ],
        correctOptionId: "B",
        explanation:
          "Negative E°cell for the reaction as written means non-spontaneous in that direction under standard conditions; the reverse is spontaneous (positive E°cell for the reverse).",
        distractorRationale: {
          A: "A positive E°cell is needed for feasibility of the reaction exactly as written.",
          C: "A cell may still run if conditions differ from standard, and the reverse direction is feasible here under standard states.",
          D: "The sign of E°cell is exactly the feasibility indicator linked to ΔG°.",
        },
        tags: ["feasibility", "E-cell"],
      },
      {
        id: "t24-2-d6",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Given E°(Cl2/Cl-) = +1.36 V and E°(I2/I-) = +0.54 V for the reductions Cl2 + 2e- -> 2Cl- and I2 + 2e- -> 2I-, deduce which halogen is the stronger oxidising agent under standard conditions. Predict whether Cl2 can oxidise I- to I2, giving E°cell for the favourable overall change.",
        modelAnswerPoints: [
          "More positive E° means stronger tendency to be reduced, hence stronger oxidising agent: Cl2 > I2.",
          "Cl2 is reduced; I- is oxidised to I2.",
          "E°cell = 1.36 - 0.54 = +0.82 V, so reaction is feasible under standard conditions.",
        ],
        workedSolution: [
          "Under standard conditions the half-reaction with the more positive reduction potential is the one whose oxidised form is the stronger oxidising agent, so chlorine with E° = +1.36 V is a stronger oxidising agent than iodine with E° = +0.54 V because chloride ion formation from chlorine gas is more favourable thermodynamically than iodide formation from iodine in the ranking sense used here.",
          "If molecular chlorine is mixed with iodide ions, chlorine will tend to be reduced to chloride while iodide is oxidised to iodine, because that arrangement pairs the stronger oxidant with the reductant derived from the weaker oxidant couple.",
          "Treating the reduction of Cl2 as the cathode process and the oxidation of iodide as the reverse of the iodine reduction gives E°cell = E°(cathode) - E°(anode) = 1.36 - 0.54 = +0.82 V, which is positive, so the oxidation of iodide by chlorine is feasible under standard conditions as described qualitatively.",
        ],
        commonMistake:
          "Calling I2 the stronger oxidant because of lower mass, or subtracting potentials in the wrong order.",
        tags: ["oxidising-agent", "reactivity", "halogens"],
      },
      {
        id: "t24-2-d7",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Construct the overall ionic equation for the reaction between acidified aqueous Fe3+ and aqueous I-, given the reduction half-equations Fe3+ + e- -> Fe2+ (E° = +0.77 V) and I2 + 2e- -> 2I- (E° = +0.54 V). Show how you balance electrons and calculate E°cell for your overall equation.",
        modelAnswerPoints: [
          "Iron couple more positive, so Fe3+ reduced; I- oxidised to I2.",
          "Multiply iron half-equation by 2: 2Fe3+ + 2e- -> 2Fe2+.",
          "Reverse iodine reduction: 2I- -> I2 + 2e-.",
          "Add: 2Fe3+ + 2I- -> 2Fe2+ + I2.",
          "E°cell = 0.77 - 0.54 = +0.23 V.",
        ],
        workedSolution: [
          "Comparing standard reduction potentials shows that the iron(III)/iron(II) couple is more positive than the iodine/iodide couple, so in a spontaneous cell under standard conditions iron(III) ions are reduced to iron(II) while iodide ions are oxidised to iodine rather than the other way around.",
          "The reduction half-equation Fe3+ + e- -> Fe2+ must be doubled to 2Fe3+ + 2e- -> 2Fe2+ so that it involves two moles of electrons, matching the two-electron change associated with forming one mole of I2 from iodide.",
          "The iodine half-equation is reversed to oxidation, 2I- -> I2 + 2e-, and when this is added to the doubled iron reduction, the electrons cancel to give the net ionic equation 2Fe3+ + 2I- -> 2Fe2+ + I2, which conserves atoms and charge overall.",
          "The standard cell potential for this net reaction is obtained from the difference of reduction potentials written in reduction form for cathode minus anode couples, E°cell = 0.77 V - 0.54 V = +0.23 V, confirming that the constructed overall equation corresponds to a thermodynamically favoured process under standard conditions.",
        ],
        commonMistake:
          "Unequalised electrons when combining half-equations, or adding two reduction equations without reversing one.",
        tags: ["redox-equations", "half-equations", "E-cell"],
      },
      {
        id: "t24-2-d8",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "For the equilibrium written as a reduction Cu2+(aq) + 2e- <=> Cu(s), predict qualitatively how the electrode potential E changes if (a) [Cu2+] is increased at constant temperature, and (b) [Cu2+] is decreased. Use Le Chatelier reasoning in terms of the reduction equilibrium.",
        modelAnswerPoints: [
          "Increasing [Cu2+] shifts equilibrium toward reduction, making E more positive.",
          "Decreasing [Cu2+] shifts away from reduction, making E less positive (more negative).",
        ],
        workedSolution: [
          "The reduction equilibrium written with Cu2+ on the left responds to an increase in aqueous copper(II) concentration by favouring the forward reduction direction to consume added Cu2+, which corresponds to a higher tendency for reduction and therefore a more positive value of the electrode potential E at fixed temperature.",
          "If [Cu2+] is lowered, the equilibrium shifts toward the left-hand side, disfavouring reduction relative to the standard state, so the measured potential becomes less positive, meaning the couple is a weaker oxidising system than before, which is exactly the qualitative trend predicted without inserting numbers yet.",
        ],
        commonMistake:
          "Stating that E is unchanged because 'it is standard', when the question explicitly changes concentration away from standard.",
        tags: ["concentration", "Le-Chatelier", "electrode-potential"],
      },
      {
        id: "t24-2-d9",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "For the half-equation Fe3+(aq) + e- <=> Fe2+(aq), E° = +0.77 V at 298 K. Calculate E when [Fe3+] = 0.050 mol dm^-3 and [Fe2+] = 0.500 mol dm^-3. Use E = E° + (0.059/z) log([oxidised]/[reduced]) with z = 1.",
        modelAnswerPoints: [
          "Identify [oxidised]/[reduced] = [Fe3+]/[Fe2+] = 0.050/0.500 = 0.10.",
          "log(0.10) = -1.00 (base 10).",
          "Correction term = 0.059/1 x (-1.00) = -0.059 V.",
          "E = 0.77 + (-0.059) = 0.711 V (to 3 s.f.).",
        ],
        workedSolution: [
          "In the Nernst expression requested, the oxidised species is Fe3+ and the reduced species is Fe2+, so the concentration ratio inside the logarithm is [Fe3+]/[Fe2+] = 0.050 / 0.500 = 0.10, which is less than one because the iron(III) concentration is relatively small compared with iron(II).",
          "The base-10 logarithm of 0.10 is exactly -1.00, so the logarithmic term lowers the potential relative to the standard value because the system is shifted toward the reduced side compared with equal standard concentrations.",
          "With z = 1 electron in the half-equation, the Nernst correction at 298 K is (0.059 V) x log(0.10) = -0.059 V when the 0.059/z factor is applied as specified.",
          "Adding this correction to the standard potential gives E = +0.77 V - 0.059 V = 0.711 V, which is the electrode potential under the stated non-standard concentrations and matches the expected numerical precision for an A Level style calculation.",
        ],
        commonMistake:
          "Inverting the log ratio ([Fe2+]/[Fe3+]) or using z = 2 for a one-electron iron couple.",
        tags: ["nernst", "iron", "calculations"],
      },
      {
        id: "t24-2-d10",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "For Cu2+(aq) + 2e- <=> Cu(s), E° = +0.34 V at 298 K. Calculate E when [Cu2+] = 2.0 x 10^-4 mol dm^-3, using E = E° + (0.059/z) log[Cu2+] with z = 2 and omitting the solid from the expression.",
        modelAnswerPoints: [
          "z = 2 so slope is 0.059/2 = 0.0295 V per log unit.",
          "log(2.0 x 10^-4) = -3.699 (base 10).",
          "Correction = 0.0295 x (-3.699) = -0.109 V (approx).",
          "E = 0.34 + (-0.109) = 0.23 V (2 decimal places) or 0.231 V to 3 s.f.",
        ],
        workedSolution: [
          "For the copper(II)/copper metal couple written as a two-electron reduction, the simplified logarithmic term at 298 K uses z = 2 in the denominator, giving a coefficient 0.059/2 = 0.0295 V for each decade change in copper(II) concentration, while the activity of solid copper is taken as one and does not appear inside the logarithm.",
          "The given concentration 2.0 x 10^-4 mol dm^-3 has a base-10 logarithm of log(2.0 x 10^-4) = log(2.0) + log(10^-4) = 0.301 - 4.000 = -3.699 to the precision carried in intermediate working.",
          "Multiplying this logarithm by 0.0295 V yields a correction of about -0.109 V relative to the standard potential, reflecting that very dilute Cu2+ makes reduction less favourable than under standard 1 mol dm^-3 conditions.",
          "Adding the correction to E° gives E approximately +0.34 V - 0.109 V = +0.23 V when rounded in a way consistent with the data, which is the predicted electrode potential for the specified dilute solution at 298 K under the syllabus Nernst approximation.",
        ],
        commonMistake:
          "Using z = 1 for Cu2+ + 2e-, or including solid copper inside the log term.",
        tags: ["nernst", "copper", "calculations"],
      },
    ],
    flashcards: [
      {
        id: "t24-2-f1",
        noteId: "t24-2",
        difficulty: 1,
        front: "Define standard electrode potential E°.",
        back: "e.m.f. of a half-cell vs SHE with half-equation as reduction, under standard conditions.",
        examPhrasing: "Define standard electrode (reduction) potential.",
        tags: ["definitions"],
      },
      {
        id: "t24-2-f2",
        noteId: "t24-2",
        difficulty: 1,
        front: "Define standard cell potential E°cell.",
        back: "e.m.f. of the whole cell under standard conditions (no current).",
        examPhrasing: "Define standard cell potential.",
        tags: ["definitions"],
      },
      {
        id: "t24-2-f3",
        noteId: "t24-2",
        difficulty: 2,
        front: "E°cell from two reduction potentials?",
        back: "E°cell = E°(cathode) - E°(anode), both written as reductions.",
        examPhrasing: "Calculate standard cell potential from standard electrode potentials.",
        tags: ["E-cell"],
      },
      {
        id: "t24-2-f4",
        noteId: "t24-2",
        difficulty: 2,
        front: "Electron flow in a spontaneous galvanic cell?",
        back: "Through the wire from anode to cathode (anode negative, cathode positive).",
        examPhrasing: "Deduce direction of electron flow from electrode polarity.",
        confusionPair: "galvanic vs electrolytic signs",
        tags: ["polarity", "electrons"],
      },
      {
        id: "t24-2-f5",
        noteId: "t24-2",
        difficulty: 3,
        front: "More positive E° implies oxidising or reducing strength?",
        back: "Oxidised form is a stronger oxidising agent; reduced form is a weaker reducing agent vs couples below.",
        examPhrasing: "Deduce relative strengths of oxidising agents using E° values.",
        tags: ["reactivity"],
      },
      {
        id: "t24-2-f6",
        noteId: "t24-2",
        difficulty: 3,
        front: "SHE components at standard?",
        back: "Pt | H+(aq, 1 mol dm^-3) | H2(g, 1 atm); E° = 0.00 V by convention.",
        examPhrasing: "Describe the standard hydrogen electrode.",
        tags: ["SHE"],
      },
      {
        id: "t24-2-f7",
        noteId: "t24-2",
        difficulty: 4,
        front: "Why Pt for Fe3+/Fe2+ measurement?",
        back: "No stable Fe electrode for both ions; Pt is inert conductor at the interface.",
        examPhrasing: "Explain use of a platinum electrode for Fe3+/Fe2+.",
        tags: ["measurement"],
      },
      {
        id: "t24-2-f8",
        noteId: "t24-2",
        difficulty: 4,
        front: "Nernst form for Fe3+ + e- <=> Fe2+ at 298 K?",
        back: "E = E° + 0.059 log([Fe3+]/[Fe2+]) (z = 1).",
        examPhrasing: "Write the Nernst equation for the iron(III)/iron(II) couple.",
        tags: ["nernst"],
      },
      {
        id: "t24-2-f9",
        noteId: "t24-2",
        difficulty: 5,
        front: "Nernst form for Cu2+ + 2e- <=> Cu(s)?",
        back: "E = E° + (0.059/2) log[Cu2+]; solid omitted.",
        examPhrasing: "Apply the Nernst equation to Cu2+/Cu.",
        tags: ["nernst", "copper"],
      },
      {
        id: "t24-2-f10",
        noteId: "t24-2",
        difficulty: 5,
        front: "Link ΔG° and E°cell?",
        back: "ΔG° = -n E°cell F; positive E°cell gives negative ΔG° (feasible as written).",
        examPhrasing: "Use ΔG° = -nE°cellF to relate feasibility to cell potential.",
        tags: ["delta-G", "thermodynamics"],
      },
    ],
  },
};
