import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 21 / 21.1 — Organic synthesis: one course subtopic `t21-1`.
 *
 * LO crosswalk (each bullet in `data/syllabus/chemistry-9701-learning-outcomes.md` §21.1
 * is hit by ≥1 drill id):
 * - Multi-functional-group molecules: identify groups using syllabus reactions/tests → d1, d3, d9
 * - Multi-functional-group molecules: predict properties and reactions → d2
 * - Devise multi-step synthetic routes (syllabus reactions only) → d4, d5, d6, d10
 * - Analyse a route: reaction type, reagents per step, possible by-products → d7, d8, d9, d10
 */
export const CHEMISTRY_TOPIC21_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t21-1": {
    noteId: "t21-1",
    drills: [
      {
        id: "t21-1-d1",
        noteId: "t21-1",
        kind: "structured",
        difficulty: 1,
        marks: 6,
        stem: "Compound X has the structure HOCH_2CH_2COOH (3-hydroxypropanoic acid). List every major organic functional group present in X. For each group, name one simple qualitative chemical test (or observable reaction with a named reagent) from the syllabus that would positively identify that group, and state what you would see for a positive result.",
        modelAnswerPoints: [
          "Primary alcohol: –CH_2OH (alcohol / hydroxyl group).",
          "Carboxylic acid: –COOH (carboxyl group).",
          "A positive test for the acid is effervescence with aqueous sodium hydrogencarbonate (or sodium carbonate), giving CO_2 gas.",
          "A positive test for the primary alcohol is warm acidified potassium dichromate(VI) turning from orange to green on oxidation (or warm acidified KMnO_4 decolourised), noting the acid group is also oxidisable in strong conditions so careful interpretation is needed in mixtures.",
          "Alternatively, warm acidified dichromate distinguishes the alcohol by overall oxidation behaviour alongside the known acidic property from –COOH.",
        ],
        workedSolution: [
          "The molecule HOCH_2CH_2COOH contains a hydroxyl group attached to a saturated carbon that is not part of a carbonyl, so it is classified as a primary alcohol functional group on the CH_2OH end of the chain.",
          "It also contains a carboxylic acid group, –COOH, on the same carbon framework, which is a second distinct functional group responsible for typical weak-acid behaviour in water.",
          "The carboxylic acid can be recognised qualitatively by adding aqueous sodium hydrogencarbonate: bubbles of carbon dioxide form because the acid donates a proton to hydrogencarbonate and the resulting carbonic acid breaks down to CO_2 and H_2O, which is a standard syllabus test for –COOH.",
          "The primary alcohol can be probed using warm acidified potassium dichromate(VI) solution, where partial oxidation of the alcohol lowers chromium(VI) to chromium(III) so the orange dichromate colour changes to green, which is the usual practical sign of oxidation of a primary alcohol in this course.",
          "In a multi-group molecule the learner must name both groups explicitly and tie each test to the correct functionality, acknowledging that vigorous oxidation conditions could eventually affect several sites, so the answers should focus on the characteristic tests taught for alcohol and for carboxylic acid rather than overclaiming single-step selectivity.",
        ],
        commonMistake:
          "Calling the –OH a phenol, or claiming Tollens’ reagent tests an alcohol; Tollens is for aldehydes, not for simple alcohols or carboxylic acids.",
        tags: ["functional-groups", "tests", "alcohol", "carboxylic-acid"],
      },
      {
        id: "t21-1-d2",
        noteId: "t21-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Compound Y is CH_2=CHCH_2CHO (but-3-enal). Predict what happens, with reasons, when separate samples of Y are treated with (i) bromine in an inert organic solvent in the dark and (ii) acidified potassium dichromate(VI) under reflux. State whether the aldehyde group is expected to be oxidised under typical dichromate conditions and name the organic oxidation product family you would aim to describe at this level.",
        modelAnswerPoints: [
          "The molecule contains both an alkene (C=C) and an aldehyde (–CHO).",
          "(i) Br_2 adds across the C=C double bond: bromine decolourises (electrophilic addition), giving a dibromo product on the original alkene carbons.",
          "(ii) Warm acidified dichromate(VI) oxidises the aldehyde group to a carboxylic acid (but-3-enoic acid) under reflux conditions, with the orange to green colour change.",
          "The alkene may also react with strong oxidising agents under harsh reflux; a good answer notes competing oxidation but clearly prioritises aldehyde -> carboxylic acid as the syllabus aldehyde outcome with dichromate.",
        ],
        workedSolution: [
          "But-3-enal contains a terminal carbon–carbon double bond in the propene fragment and an aldehyde carbonyl at the chain end, so two independent reaction sites must be considered when reagents are chosen.",
          "When bromine in an inert solvent is added in the dark, the typical observation is rapid decolourisation of bromine because the alkene undergoes electrophilic addition across the π bond, giving a saturated dibromide unit while the aldehyde group is not the primary target of molecular bromine under these conditions.",
          "When acidified potassium dichromate(VI) is used with heating under reflux, aldehydes are oxidised through to carboxylic acids, so the –CHO group is converted to –COOH while chromium(VI) is reduced, producing the familiar orange-to-green colour change associated with oxidation in practical organic work at A Level.",
          "A strong candidate also remarks that hot acidified dichromate is a powerful oxidant that can attack alkenes in some contexts, but the mark-bearing organic transformation expected for an aldehyde with dichromate is still formation of the corresponding carboxylic acid, which in this case is but-3-enoic acid if the alkene survives the conditions well enough for the exam model.",
          "The prediction therefore combines decolourisation of bromine via the alkene with oxidation of the aldehyde to a carboxylic acid under reflux dichromate, explicitly naming both functional-group behaviours rather than treating the molecule as a single generic ‘unsaturated carbonyl’.",
        ],
        commonMistake:
          "Saying bromine oxidises the aldehyde to an acid (that is dichromate’s job); Br_2 with an alkene is addition, not the same pathway as aldehyde oxidation.",
        tags: ["prediction", "alkene", "aldehyde", "oxidation", "bromine"],
      },
      {
        id: "t21-1-d3",
        noteId: "t21-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which reagent gives a positive result with ethanal but not with propanone under standard laboratory conditions?",
        options: [
          { id: "A", text: "Tollens’ reagent (ammoniacal silver nitrate), warmed gently" },
          { id: "B", text: "Iodoform reagent (I_2 / alkali)" },
          { id: "C", text: "2,4-dinitrophenylhydrazine (Brady’s reagent)" },
          { id: "D", text: "Anhydrous copper(II) sulfate" },
        ],
        correctOptionId: "A",
        explanation:
          "Tollens’ reagent oxidises aldehydes to give a silver mirror; simple ketones such as propanone do not give this positive test under the usual conditions taught for distinguishing aldehydes from ketones.",
        distractorRationale: {
          B: "Both ethanal and propanone can give a positive iodoform test because both are methyl ketones or oxidisable to the CH_3CO– fragment in the ethanal case; it does not separate them cleanly.",
          C: "Both aldehydes and ketones form coloured precipitates with 2,4-DNP, so it confirms a carbonyl but not whether it is aldehyde or ketone.",
          D: "Anhydrous copper(II) sulfate is used as a drying test for water, not as a specific functional-group test for aldehydes versus ketones.",
        },
        tags: ["tests", "aldehyde", "ketone", "tollens"],
      },
      {
        id: "t21-1-d4",
        noteId: "t21-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Starting from ethene as the only organic starting material, and using any inorganic reagents needed, devise a two-step route to ethanoic acid. For each step, state the reagents and essential conditions and write a balanced equation using structural formulae where helpful. Name the type of reaction for each step.",
        modelAnswerPoints: [
          "Step 1: hydration of ethene with steam over an acid catalyst (e.g. H_3PO_4) -> ethanol: CH_2=CH_2 + H_2O -> CH_3CH_2OH (electrophilic addition of water).",
          "Step 2: heat ethanol under reflux with excess acidified K_2Cr_2O_7 -> ethanoic acid, CH_3COOH (oxidation of primary alcohol to carboxylic acid).",
          "Step 1 type: electrophilic addition. Step 2 type: oxidation (orange dichromate(VI) to green chromium(III)).",
        ],
        workedSolution: [
          "A clean two-stage route from ethene alone uses hydration of the double bond to introduce the two-carbon skeleton already bearing the oxidation level needed for eventual acid, so ethene is treated with steam over an acid catalyst such as phosphoric acid to give ethanol according to CH_2=CH_2 + H_2O -> CH_3CH_2OH, which is classified as electrophilic addition of water across the π bond.",
          "The ethanol is then fully oxidised while still a primary alcohol by heating under reflux with excess acidified potassium dichromate(VI), which carries the carbon chain through the aldehyde stage in situ to the carboxylic acid, giving ethanoic acid as the final organic product with the expected orange-to-green colour change as dichromate is consumed.",
          "The first step is therefore electrophilic addition (hydration of an alkene), and the second step is oxidation of a primary alcohol to a carboxylic acid using acidified dichromate under reflux, which matches the standard reagent vocabulary of the syllabus for this transformation.",
          "Balanced attention to conditions matters: reflux with excess oxidant drives the alcohol to the acid rather than stopping at ethanal, and the acid medium is part of the standard reagent description for dichromate oxidations in organic papers.",
          "This two-step answer stays within common 9701 reaction inventory (alkene hydration, alcohol oxidation) and does not require extra carbon-carbon bond forming steps, which keeps the synthesis short and exam-markable.",
        ],
        commonMistake:
          "Stopping oxidation at ethanal when the question asks for ethanoic acid, or writing ethene + H_2O without noting acid catalyst for hydration.",
        tags: ["multi-step", "ethene", "oxidation", "hydration"],
      },
      {
        id: "t21-1-d5",
        noteId: "t21-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which sequence converts 1-bromobutane into butanoic acid in good syllabus style?",
        options: [
          { id: "A", text: "KCN in ethanol, heat; then dilute HCl, heat under reflux" },
          { id: "B", text: "NaOH(aq), heat under reflux; then acidified K_2Cr_2O_7, distill immediately" },
          { id: "C", text: "Conc. H_2SO_4, heat; then steam with H_3PO_4" },
          { id: "D", text: "Anhydrous AlCl_3 with benzene, heat; then KMnO_4 cold dilute" },
        ],
        correctOptionId: "A",
        explanation:
          "Cyanide displaces bromide to give butanenitrile, CH_3CH_2CH_2CH_2CN; hydrolysis of the nitrile with dilute acid under reflux (or alkali then acid work-up) yields butanoic acid.",
        distractorRationale: {
          B: "Hydrolysis of haloalkane with NaOH gives butan-1-ol, but immediate distillation with dichromate is not the standard complete oxidation sequence to carboxylic acid as written, and the conditions are muddled compared with nitrile formation then hydrolysis.",
          C: "Elimination to an alkene plus hydration does not add the carbonyl of a carboxylic acid in one clean pair of steps from the bromide in the way nitrile chemistry does.",
          D: "Friedel–Crafts alkylation with benzene is irrelevant to converting a simple haloalkane to a four-carbon carboxylic acid and introduces an arene ring incorrectly.",
        },
        tags: ["multi-step", "nitrile", "hydrolysis", "haloalkane"],
      },
      {
        id: "t21-1-d6",
        noteId: "t21-1",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "Devise a three-step synthetic route to convert benzene into N-phenylethanamide (acetanilide), C_6H_5NHCOCH_3, using only syllabus reactions. For each step give the organic reactant, the reagents and conditions, the type of reaction, and the major organic product. You may show benzene as C_6H_6 where convenient.",
        modelAnswerPoints: [
          "Step 1: nitration of benzene with concentrated nitric acid and concentrated sulfuric acid, 55–60 °C -> nitrobenzene (electrophilic substitution).",
          "Step 2: reduction of nitrobenzene with tin and concentrated hydrochloric acid (or Fe/HCl), heat -> phenylammonium chloride then phenylamine after alkali work-up (reduction of –NO_2 to –NH_2).",
          "Step 3: acylation of phenylamine with ethanoyl chloride in the presence of a base such as pyridine, or heat ethanoic acid with phenylamine under dehydrating conditions less ideal; preferred is ethanoyl chloride -> N-phenylethanamide plus HCl by-product (nucleophilic substitution at the carbonyl carbon of the acyl chloride).",
          "By-product note: step 3 generates HCl, which is why a base is often present when using acyl chlorides with amines.",
        ],
        workedSolution: [
          "The target N-phenylethanamide contains a benzene ring linked to an amide group –NHCOCH_3, which is most reliably assembled from phenylamine and an acylating agent derived from ethanoic acid, so the carbon skeleton of the ring must first be functionalised with a nitrogen substituent that can later be converted to an amino group.",
          "The first step is therefore electrophilic substitution on benzene using a mixed acid nitrating mixture of concentrated nitric acid and concentrated sulfuric acid at a controlled temperature near 55 °C to give nitrobenzene, C_6H_5NO_2, as the usual mononitration product under these conditions.",
          "The second step reduces the nitro group to a primary aromatic amine using a syllabus reducing system such as tin with concentrated hydrochloric acid under heating, which converts nitrobenzene to phenylammonium ions in the acidic mixture; after treatment with alkali, phenylamine, C_6H_5NH_2, is obtained as the free base product for the next stage.",
          "The third step forms the amide by reacting phenylamine with ethanoyl chloride, where the lone pair on nitrogen attacks the electrophilic carbonyl carbon of the acyl chloride in a nucleophilic substitution–elimination sequence, giving N-phenylethanamide and hydrogen chloride as a small-molecule by-product, often absorbed by added base such as pyridine to avoid protonating the amine starting material.",
          "Each step is named in mechanism class terms as electrophilic aromatic substitution, reduction of nitroarene, and nucleophilic acyl substitution, which matches how synthetic routes are analysed in mark schemes for multi-step aromatic sequences.",
        ],
        commonMistake:
          "Trying to nitrate acetophenone directly to the amide, or using Friedel–Crafts acylation on free phenylamine without recognising that the free –NH_2 group complexes Lewis acids.",
        tags: ["multi-step", "arene", "nitration", "reduction", "amide"],
      },
      {
        id: "t21-1-d7",
        noteId: "t21-1",
        kind: "mcq",
        difficulty: 3,
        stem: "In the esterification CH_3COOH + CH_3CH_2OH <=> CH_3COOCH_2CH_3 + H_2O using concentrated sulfuric acid as catalyst, which species is the main small-molecule by-product that must be considered when driving the equilibrium toward the ester?",
        options: [
          { id: "A", text: "Hydrogen gas" },
          { id: "B", text: "Sulfur dioxide" },
          { id: "C", text: "Water" },
          { id: "D", text: "Carbon monoxide" },
        ],
        correctOptionId: "C",
        explanation:
          "The reaction produces water; removing water (e.g. with a dehydrating agent or Dean–Stark) shifts the equilibrium toward ethyl ethanoate. Sulfuric acid is catalytic and not consumed as SO_2 under normal esterification conditions.",
        distractorRationale: {
          A: "Esterification of carboxylic acids with alcohols is not a redox release of H_2; that would imply a different reaction class.",
          B: "SO_2 is not the routine by-product of acid-catalysed esterification; the small molecule formed alongside ester is water from the condensation step.",
          D: "Carbon monoxide is not formed in this reversible esterification equilibrium.",
        },
        tags: ["by-products", "esterification", "equilibrium"],
      },
      {
        id: "t21-1-d8",
        noteId: "t21-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "A student proposes the route: propanal --(i)--> 1-bromopropane --(ii)--> propanenitrile --(iii)--> propylamine. Analyse each step in terms of reaction type, appropriate reagents and conditions, and state whether the step as written is chemically sound; if not, identify the main error and suggest a corrected first step to reach 1-bromopropane from propanal using syllabus chemistry.",
        modelAnswerPoints: [
          "Step (i) as written is not valid: propanal cannot be converted to 1-bromopropane by simple ‘add HBr’ in the way an alkene can; the carbonyl carbon is not analogous to an alkene for Markovnikov addition to give that haloalkane.",
          "A sound approach from propanal uses reduction of the aldehyde to the primary alcohol (NaBH_4 or LiAlH_4 conditions appropriate to syllabus), then formation of 1-bromopropane from propan-1-ol with NaBr/H_2SO_4 or PBr_3.",
          "Step (ii): nucleophilic substitution of halide by cyanide in ethanolic solution with heat -> nitrile (valid if 1-bromopropane is available).",
          "Step (iii): reduction of nitrile (LiAlH_4 in dry ether, or H_2 / Ni catalyst) -> propylamine (valid).",
          "By-products: e.g. HBr in bromination steps, salts with KCN.",
        ],
        workedSolution: [
          "The proposed first step attempts to go directly from propanal, CH_3CH_2CHO, to 1-bromopropane, CH_3CH_2CH_2Br, but aldehydes do not undergo the same electrophilic addition of hydrogen bromide across a double bond as alkenes, so this transformation is not a standard or correct one-step syllabus route and should be rejected as written.",
          "A chemically sound sequence begins by reducing the aldehyde carbonyl to a primary alcohol using a hydride reagent such as sodium tetrahydridoborate in aqueous ethanol for propanal, giving propan-1-ol, which is an oxidation-level adjustment step classified as carbonyl reduction.",
          "The alcohol is then converted to 1-bromopropane using conditions such as sodium bromide with sulfuric acid or phosphorus tribromide, which is an oxygen-by-bromine substitution on the alcohol, classified as formation of a haloalkane from an alcohol.",
          "From 1-bromopropane, heating with potassium cyanide in ethanol provides a nucleophilic substitution that replaces bromide by cyanide to give propanenitrile, CH_3CH_2CN, with potassium bromide as an inorganic by-product.",
          "Finally, reduction of the nitrile with lithium tetrahydridoaluminate in dry ether (or catalytic hydrogenation) adds hydrogen across the carbon–nitrogen triple bond to give propylamine, CH_3CH_2CH_2NH_2, completing a repaired route while explicitly analysing why the original first step failed.",
        ],
        commonMistake:
          "Treating an aldehyde like an alkene for HBr addition, or forgetting that nitrile -> amine is reduction, not hydrolysis.",
        tags: ["route-analysis", "correction", "nitrile", "aldehyde"],
      },
      {
        id: "t21-1-d9",
        noteId: "t21-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Methylbenzene is warmed under reflux with acidified potassium manganate(VII). What is the usual major organic product?",
        options: [
          { id: "A", text: "Phenylmethanol" },
          { id: "B", text: "Benzoic acid" },
          { id: "C", text: "Benzene" },
          { id: "D", text: "Methylcyclohexane" },
        ],
        correctOptionId: "B",
        explanation:
          "The alkyl side chain (with a benzylic hydrogen) is oxidised by hot acidified manganate(VII) to the carboxylic acid, giving benzoic acid from methylbenzene.",
        distractorRationale: {
          A: "Further oxidation of the primary alcohol at the benzylic position is expected under hot strong oxidising reflux, not isolation of the alcohol as the final product.",
          C: "Oxidation does not strip the side chain back to benzene; it oxidises the methyl group to –COOH.",
          D: "Hot manganate(VII) is an oxidant, not a hydrogenation reagent that would give saturated methylcyclohexane.",
        },
        tags: ["oxidation", "arene", "side-chain"],
      },
      {
        id: "t21-1-d10",
        noteId: "t21-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "The following two-step scheme is proposed to make ethyl 2-hydroxypropanoate from ethanol and ethanoic acid as the only carbon sources: (1) oxidise ethanol to ethanoic acid with acidified K_2Cr_2O_7; (2) heat ethanoic acid with ethanol and a few drops of concentrated H_2SO_4 to form ethyl ethanoate, then ‘add water across the ester’ in one pot to introduce the 2-hydroxy acid fragment. Analyse why this plan cannot yield ethyl 2-hydroxypropanoate as drawn, and outline a syllabus-consistent three-step strategy starting from ethanol that could introduce the extra oxygen at C-2 of the acid chain before forming the desired ester, naming intermediates and realistic by-products.",
        modelAnswerPoints: [
          "Critique: simple acid-catalysed esterification of ethanoic acid with ethanol gives ethyl ethanoate, which has no chiral 2-hydroxy centre on a three-carbon α-hydroxy ester; ‘hydrating an ester’ is not a standard selective route to a 2-hydroxypropanoate framework from that ester.",
          "Carbon count: ethyl 2-hydroxypropanoate is an ester of lactic acid (2-hydroxypropanoic acid) with ethanol; building it requires at least a three-carbon hydroxy acid skeleton, not only two-carbon ethanoic units.",
          "Improved outline from ethanol: partial oxidation to ethanal; nucleophilic addition of HCN (cyanohydrin formation) -> 2-hydroxypropanenitrile; hydrolyse with dilute acid under heat -> 2-hydroxypropanoic acid; Fischer esterification with ethanol/H^+ -> ethyl 2-hydroxypropanoate.",
          "By-products: water in oxidations and esterification; NH_4^+ / salts if acid hydrolysis of nitrile; H_2O from nitrile hydrolysis.",
        ],
        workedSolution: [
          "The target molecule ethyl 2-hydroxypropanoate is the ethyl ester of 2-hydroxypropanoic acid, which contains three carbons with a hydroxyl group on the carbon adjacent to the carboxyl group, whereas ethanoic acid and ethanol together can only supply two-carbon fragments in a straightforward esterification, so the proposed scheme cannot assemble the correct carbon skeleton or oxidation pattern by mere esterification of ethanoic acid.",
          "Moreover, acid-catalysed esterification followed by an unspecified ‘addition of water across the ester’ is not a recognised selective step in the syllabus toolkit for converting ethyl ethanoate into an α-hydroxy ester, and hot aqueous acid would tend toward hydrolysis back to ethanoic acid and ethanol rather than a controlled introduction of a 2-OH group on a three-carbon chain.",
          "A more coherent three-carbon route begins from ethanol by partial oxidation under controlled conditions to ethanal, which is a two-carbon aldehyde still bearing the functional group needed for carbon-chain functionalisation with hydrogen cyanide.",
          "Hydrogen cyanide adds across the carbonyl of ethanal to give 2-hydroxypropanenitrile after acidic work-up of the cyanohydrin formation, which increases the chain to three carbons with the OH on C-2 as required, with no extra carbon source beyond what cyanide supplies in this classic extension step.",
          "Hydrolysis of the nitrile with dilute aqueous acid under heat converts 2-hydroxypropanenitrile to 2-hydroxypropanoic acid, releasing ammonium salts as nitrogen-containing by-products, and final Fischer esterification with ethanol in the presence of a little concentrated sulfuric acid forms ethyl 2-hydroxypropanoate with water as the condensation by-product, which is a chemically honest multi-step narrative aligned with syllabus reactions even if industrial routes differ.",
        ],
        commonMistake:
          "Assuming any ester plus water gives an α-hydroxy acid ester, or ignoring that HCN addition to ethanal is the key C-3 forming step for lactic acid derivatives from two-carbon aldehyde.",
        tags: ["critique", "multi-step", "cyanohydrin", "ester"],
      },
    ],
    flashcards: [
      {
        id: "t21-1-f1",
        noteId: "t21-1",
        difficulty: 1,
        front: "Name two functional groups you could find together in a hydroxy acid.",
        back: "Hydroxyl (alcohol) and carboxylic acid (–COOH).",
        examPhrasing: "Identify the functional groups in a molecule such as HOCH_2COOH.",
        tags: ["functional-groups"],
      },
      {
        id: "t21-1-f2",
        noteId: "t21-1",
        difficulty: 1,
        front: "What does Tollens’ reagent detect?",
        back: "Aldehydes (silver mirror on warming); ketones generally give a negative result under standard conditions.",
        examPhrasing: "State a test to distinguish ethanal from propanone.",
        tags: ["tests", "aldehyde"],
      },
      {
        id: "t21-1-f3",
        noteId: "t21-1",
        difficulty: 2,
        front: "Reagents to convert a primary alcohol to a carboxylic acid?",
        back: "Acidified potassium dichromate(VI) (or manganate(VII)), heat under reflux with excess oxidant.",
        examPhrasing: "State reagents and conditions to oxidise ethanol to ethanoic acid.",
        tags: ["oxidation", "alcohol"],
      },
      {
        id: "t21-1-f4",
        noteId: "t21-1",
        difficulty: 2,
        front: "How do you extend a carbon chain by one carbon from a haloalkane?",
        back: "Heat with KCN in ethanol: RBr + KCN -> RCN + KBr; then hydrolyse nitrile to carboxylic acid or reduce to amine.",
        examPhrasing: "Describe the formation of a nitrile from a haloalkane.",
        confusionPair: "KCN substitution vs KCN with carbonyl compounds",
        tags: ["nitrile", "multi-step"],
      },
      {
        id: "t21-1-f5",
        noteId: "t21-1",
        difficulty: 3,
        front: "Typical reagents to reduce a nitrile to a primary amine?",
        back: "LiAlH_4 in dry ether (or H_2 with Ni catalyst).",
        examPhrasing: "State how propanenitrile can be converted to propylamine.",
        tags: ["reduction", "nitrile"],
      },
      {
        id: "t21-1-f6",
        noteId: "t21-1",
        difficulty: 3,
        front: "What is the usual acid-catalysed side product in esterification?",
        back: "Water; removing it drives the equilibrium toward ester.",
        examPhrasing: "Explain how Le Chatelier’s principle is used in ester formation.",
        tags: ["ester", "equilibrium"],
      },
      {
        id: "t21-1-f7",
        noteId: "t21-1",
        difficulty: 4,
        front: "Reagents for nitration of benzene?",
        back: "Concentrated nitric acid + concentrated sulfuric acid, ~55 °C.",
        examPhrasing: "State reagents and conditions for converting benzene to nitrobenzene.",
        tags: ["nitration", "arene"],
      },
      {
        id: "t21-1-f8",
        noteId: "t21-1",
        difficulty: 4,
        front: "How is nitrobenzene converted to phenylamine?",
        back: "Reduction with Sn/conc HCl (or Fe/HCl), heat; then add alkali to free the amine.",
        examPhrasing: "Describe the reduction of nitrobenzene to phenylamine.",
        tags: ["reduction", "amine"],
      },
      {
        id: "t21-1-f9",
        noteId: "t21-1",
        difficulty: 5,
        front: "What happens to a benzylic CH_3 on methylbenzene with hot acidified MnO_4^-?",
        back: "Side-chain oxidation to –COOH -> benzoic acid.",
        examPhrasing: "Predict the product of oxidising methylbenzene with hot acidified manganate(VII).",
        confusionPair: "ring oxidation vs side-chain oxidation",
        tags: ["oxidation", "arene"],
      },
      {
        id: "t21-1-f10",
        noteId: "t21-1",
        difficulty: 5,
        front: "Why is ethanoyl chloride used with phenylamine instead of ethanoic acid alone?",
        back: "Acyl chlorides react rapidly with amines to give amides; ethanoic acid needs harsher dehydration and is less efficient for direct amide formation.",
        examPhrasing: "Suggest a reagent to convert phenylamine to N-phenylethanamide.",
        tags: ["amide", "acylation"],
      },
    ],
  },
};
