import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 32 — Alcohols (32.1) and Phenol (32.2).
 *
 * LO crosswalk — `data/syllabus/chemistry-9701-learning-outcomes.md`:
 *
 * **32.1 (t32-1)** — internal extract lists one bullet: reaction of alcohols with acyl
 * chlorides to form esters (ethyl ethanoate exemplar). Drills d1–d10 span naming,
 * equations, conditions vs carboxylic-acid esterification, mechanism register, and
 * generalisation to other alcohol/acyl chloride pairs.
 *
 * **32.2 (t32-2)** — phenylamine -> diazonium -> phenol (d2); phenol reactions with
 * NaOH, Na (d4); azo coupling in NaOH(aq) (d5, d8); nitration dilute HNO3 RT (d6);
 * Br2(aq) -> 2,4,6-tribromophenol (d7); acidity of phenol (d1, d3); relative acidities
 * water, phenol, ethanol (d1, d3, d5); mild conditions vs benzene + directing -OH to
 * 2-,4-,6- (d6, d7, d9); other phenolics e.g. naphthol (d10).
 */
export const CHEMISTRY_TOPIC32_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t32-1": {
    noteId: "t32-1",
    drills: [
      {
        id: "t32-1-d1",
        noteId: "t32-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define what is meant by an ester in the context of alcohol chemistry. Describe the reaction between an alcohol and an acyl chloride at the acyl carbonyl group, naming the organic product class and the inorganic by-product formed when ethanol reacts with ethanoyl chloride.",
        modelAnswerPoints: [
          "An ester contains the functional linkage R-C(=O)-O-R' (alkyl alkanoate / derived from carboxylic acid + alcohol parts).",
          "The alcohol oxygen acts as a nucleophile toward the electrophilic carbonyl carbon of the acyl chloride.",
          "The reaction is addition-elimination at the acyl group (not simple alkyl substitution).",
          "Ethanol + ethanoyl chloride gives ethyl ethanoate and hydrogen chloride (HCl).",
        ],
        workedSolution: [
          "An ester is a compound in which a carbonyl carbon is bonded to an alkoxy group, R-C(=O)-O-R', so it can be thought of as formally combining the acyl fragment from the carboxylic acid derivative with the alkyl fragment from the alcohol used in its formation.",
          "When an alcohol meets an acyl chloride, the lone pair on the alcohol oxygen attacks the electron-deficient carbonyl carbon of the acyl chloride, which begins an addition-elimination sequence at that carbonyl centre rather than substitution at the alkyl chain of the alcohol.",
          "After addition, chloride is expelled and the carbonyl is regenerated, which is why the syllabus treats this as addition-elimination at the acyl group, and it is this pathway that makes acyl chlorides react so rapidly with nucleophiles compared with alkyl chlorides.",
          "For the required example, ethanol reacts with ethanoyl chloride to give ethyl ethanoate as the ester product together with hydrogen chloride as the small-molecule by-product, often observed as steamy acidic fumes in the laboratory.",
        ],
        commonMistake:
          "Calling the by-product Cl2 or describing the process as if the alcohol simply 'replaces Cl on the alkyl chain' with no role for the carbonyl carbon.",
        tags: ["definitions", "esters", "acyl-chlorides", "ethyl-ethanoate"],
      },
      {
        id: "t32-1-d2",
        noteId: "t32-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Write a balanced equation for the formation of ethyl ethanoate from ethanol and ethanoyl chloride. State the usual temperature requirement and one practical reason why anhydrous (dry) apparatus is preferred.",
        modelAnswerPoints: [
          "CH3COCl + CH3CH2OH -> CH3COOCH2CH3 + HCl (or displayed formulae consistent with this stoichiometry).",
          "Reaction is typically rapid at room temperature (strong heating usually unnecessary).",
          "Water hydrolyses acyl chlorides to carboxylic acid + HCl, competing with ester formation and lowering yield.",
        ],
        workedSolution: [
          "The equation linking the named reagents to the named ester is CH3COCl + CH3CH2OH -> CH3COOCH2CH3 + HCl, which conserves atoms and shows the ethyl group from ethanol incorporated into the ethoxy side of the ester while the ethanoyl fragment becomes the acyl part of ethyl ethanoate.",
          "In most teaching contexts the reaction is carried out at room temperature because acyl chlorides are so electrophilic that no reflux is required for a practical rate when pure liquid reagents are mixed.",
          "Dry glassware matters because traces of water react with ethanoyl chloride by hydrolysis to give ethanoic acid and hydrogen chloride, which consumes acyl chloride that would otherwise have formed ester, so moisture directly reduces yield and complicates work-up.",
        ],
        commonMistake:
          "Using concentrated H2SO4 and reflux language from Fischer esterification when the stem specifies acyl chloride conditions.",
        tags: ["equations", "ethyl-ethanoate", "conditions"],
      },
      {
        id: "t32-1-d3",
        noteId: "t32-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Propanoyl chloride is added to methanol at room temperature. What is the main organic product?",
        options: [
          { id: "A", text: "Methyl propanoate" },
          { id: "B", text: "Propyl methanoate" },
          { id: "C", text: "Propanal" },
          { id: "D", text: "1-Chloropropane" },
        ],
        correctOptionId: "A",
        explanation:
          "The alcohol supplies the alkyl (methyl) part of the ester name; the acyl chloride supplies the propanoate fragment, giving methyl propanoate plus HCl.",
        distractorRationale: {
          B: "That would reverse which fragment comes from the alcohol versus the acyl chloride.",
          C: "Acyl chloride + alcohol is esterification at the carbonyl, not aldehyde formation from the acyl chloride under these conditions.",
          D: "That would imply simple displacement at the propyl chain, not addition-elimination at the carbonyl carbon.",
        },
        tags: ["naming", "esters", "mcq"],
      },
      {
        id: "t32-1-d4",
        noteId: "t32-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Contrast ester formation using an acyl chloride and an alcohol with esterification using a carboxylic acid and an alcohol in the presence of concentrated sulfuric acid. Your answer should cover reversibility, typical conditions, and the identity of the small-molecule by-product when ethanoyl chloride reacts with ethanol.",
        modelAnswerPoints: [
          "Acyl chloride route: rapid at room temperature; not equilibrium-limited in the same way as acid/alcohol esterification; by-product HCl.",
          "Carboxylic acid route: typically slower, reversible, often needs acid catalyst (e.g. concentrated H2SO4) and heat; water is produced and shifts equilibrium (Le Chatelier ideas acceptable if precise).",
          "Both routes deliver an ester, but acyl chlorides are more reactive toward nucleophilic attack at the carbonyl carbon under mild conditions.",
        ],
        workedSolution: [
          "When an acyl chloride reacts with an alcohol, the carbonyl carbon is highly electrophilic and the addition-elimination pathway to the ester is fast enough to be convenient at room temperature, so the practical procedure does not mirror the long heated reflux often associated with Fischer esterification.",
          "Carboxylic-acid esterification with an alcohol is an equilibrium process that is acid-catalysed and commonly driven by concentrated sulfuric acid as catalyst/dehydrating agent together with heating, and because water is formed alongside the ester, removing water or using excess of one reagent is part of the usual discussion of obtaining useful yields.",
          "For ethanol plus ethanoyl chloride the small molecule co-produced alongside ethyl ethanoate is hydrogen chloride, which is a strong acid gas and is chemically distinct from the water produced when a carboxylic acid condenses with an alcohol.",
        ],
        commonMistake:
          "Stating that acyl chloride esterification is strongly reversible like Fischer esterification, or that the by-product is water.",
        tags: ["comparisons", "esters", "conditions"],
      },
      {
        id: "t32-1-d5",
        noteId: "t32-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement best describes the role of the alcohol oxygen when ethanol attacks ethanoyl chloride?",
        options: [
          { id: "A", text: "It acts as an electrophile toward the carbonyl pi bond." },
          { id: "B", text: "It acts as a nucleophile toward the electrophilic carbonyl carbon." },
          { id: "C", text: "It protonates the carbonyl oxygen before any attack occurs." },
          { id: "D", text: "It abstracts a chloride ion in a single concerted SN2 step at the methyl group of the acyl chloride." },
        ],
        correctOptionId: "B",
        explanation:
          "The alcohol oxygen donates a lone pair to the partially positive carbonyl carbon; the chemistry is acyl addition-elimination, not methyl SN2.",
        distractorRationale: {
          A: "The carbonyl carbon is electrophilic; the alcohol oxygen supplies electrons, so it is nucleophilic, not electrophilic.",
          C: "Protonation of the carbonyl oxygen is not the primary syllabus description of the alcohol's first role in this bimolecular pathway.",
          D: "Substitution at a methyl group of CH3COCl is not the mechanism; attack is at the carbonyl carbon of the acyl group.",
        },
        tags: ["mechanism", "nucleophile", "mcq"],
      },
      {
        id: "t32-1-d6",
        noteId: "t32-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Butan-1-ol reacts with ethanoyl chloride. Name the ester formed and write an equation using molecular formulae or structural fragments consistent with C4H9OH + C2H3OCl -> ester + HCl. State how you decided which alkyl group appears in the alkoxy (-O-R') position of the ester.",
        modelAnswerPoints: [
          "Ester name: butyl ethanoate (butyl from butan-1-ol; ethanoate from ethanoyl chloride).",
          "Equation: CH3CH2CH2CH2OH + CH3COCl -> CH3COOCH2CH2CH2CH3 + HCl (or equivalent clear structural equation).",
          "The alcohol supplies the -O-R' fragment; the acyl chloride supplies the acyl R-C(=O)- portion.",
        ],
        workedSolution: [
          "The alcohol is butan-1-ol, which contributes the butyl chain attached through oxygen in the product, while ethanoyl chloride contributes the two-carbon acyl unit, so the systematic ester name is butyl ethanoate.",
          "A clear equation is CH3CH2CH2CH2OH + CH3COCl -> CH3COOCH2CH2CH2CH3 + HCl, which shows conservation of atoms and places the butoxy group on the carbonyl side of the new C-O single bond.",
          "The naming rule is that the alkyl (or aryl) part of the ester name comes from the alcohol (here butyl from butan-1-ol), whereas the -oate ending comes from the parent acid chain of the acyl chloride (here ethanoate from ethanoyl / ethanoic acid family), which matches how the oxygen of the alcohol becomes the ester linkage oxygen.",
        ],
        commonMistake:
          "Naming the product ethyl butanoate, which swaps the acid-derived and alcohol-derived fragments.",
        tags: ["naming", "equations", "esters"],
      },
      {
        id: "t32-1-d7",
        noteId: "t32-1",
        kind: "mcq",
        difficulty: 2,
        stem: "A student mixes phenol with ethanoyl chloride. Which product is formed under usual room-temperature conditions?",
        options: [
          { id: "A", text: "Phenyl ethanoate (an aryl ester) and HCl" },
          { id: "B", text: "Ethyl phenanoate" },
          { id: "C", text: "Ethanoic acid only" },
          { id: "D", text: "Benzene and ethanol" },
        ],
        correctOptionId: "A",
        explanation:
          "Acyl chlorides acylate phenol similarly to alcohols: the phenolic oxygen attacks the carbonyl carbon, giving an aryl ester and HCl.",
        distractorRationale: {
          B: "That name does not correspond to ethanoyl chloride + phenol; the aryl part comes from phenol, not an imaginary phenanoate fragment in this context.",
          C: "Hydrolysis to ethanoic acid is a different reaction pathway dominated by water, not the intended phenol acylation product.",
          D: "No simple fragmentation to benzene and ethanol occurs in this acylation context.",
        },
        tags: ["esters", "phenol-extension", "mcq"],
      },
      {
        id: "t32-1-d8",
        noteId: "t32-1",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "A multi-step label shows ethanol converted to ethyl ethanoate using ethanoyl chloride, then hydrolysis of the ester with dilute aqueous acid. Write an equation for the hydrolysis of ethyl ethanoate in dilute acid and state whether this sequence is a good industrial route from ethanol to ethanoic acid. Explain your reasoning briefly.",
        modelAnswerPoints: [
          "Acid-catalysed hydrolysis: CH3COOCH2CH3 + H2O <-> CH3COOH + CH3CH2OH (H+ catalyst; equilibrium).",
          "The two-step route is chemically possible but is not singled out as an efficient industrial oxidation of ethanol to ethanoic acid.",
          "Ester hydrolysis returns carboxylic acid plus alcohol, so it is a recovery/hydrolysis step rather than a direct selective oxidation.",
        ],
        workedSolution: [
          "Under dilute aqueous acidic conditions, ethyl ethanoate undergoes acid-catalysed hydrolysis, which can be written as CH3COOCH2CH3 + H2O <-> CH3COOH + CH3CH2OH with H+ as catalyst, emphasising that the ester cleaves to regenerate ethanoic acid and ethanol on the timescale of laboratory hydrolysis discussions.",
          "As a practical route from ethanol to ethanoic acid, making the ester first with ethanoyl chloride and then hydrolysing is wasteful of reagents and steps because the acyl chloride itself is normally made from the acid in the first place, so the net chemistry does not present a streamlined oxidation of ethanol.",
          "Therefore the sequence is intellectually valid for linking functional-group interconversions, but it is not a realistic industrial choice compared with direct oxidation routes to ethanoic acid when the economic target is bulk acid production.",
        ],
        commonMistake:
          "Claiming ester hydrolysis under dilute acid goes to completion in one direction with no equilibrium consideration.",
        tags: ["hydrolysis", "esters", "reasoning"],
      },
      {
        id: "t32-1-d9",
        noteId: "t32-1",
        kind: "structured",
        difficulty: 4,
        marks: 4,
        stem: "In an examination you are asked to show curly-arrow sense for the first addition step of an alcohol R'OH to a general acyl chloride RCOCl. Describe in words how electron pairs move in that first addition step (no curly arrows required): identify the nucleophilic atom, the electrophilic atom, and what happens to the C=O pi bond. Explain why chloride is a superior leaving group compared with -OH in this acyl substitution context.",
        modelAnswerPoints: [
          "Lone pair on alcohol oxygen attacks the carbonyl carbon (electrophilic).",
          "C=O pi electrons move onto carbonyl oxygen (temporary tetrahedral intermediate with sp3 carbonyl carbon).",
          "Later elimination reforms C=O and expels Cl^-; Cl^- is a weak base / good leaving group from the tetrahedral intermediate, whereas -OH would be a poor leaving group unless protonated.",
        ],
        workedSolution: [
          "In the first addition step, the oxygen atom of the alcohol R'OH uses one of its lone pairs to form a bond to the carbonyl carbon of RCOCl, because that carbon is electron-deficient due to the polarised C=O bond and the attached electronegative chlorine.",
          "As that new C-O bond forms, the pi bond of the carbonyl breaks heterolytically so that the electron pair becomes a lone pair on the carbonyl oxygen, giving a tetrahedral arrangement around the former carbonyl carbon with a single C-O bond to the former carbonyl oxygen and a single bond to the incoming alkoxy group.",
          "Chloride ion is an excellent leaving group in the subsequent collapse of the intermediate because it is the conjugate base of a strong acid and departs readily, whereas a hydroxyl group would leave as hydroxide, a strong base and poor leaving group unless it had first been converted to a better leaving group by protonation, which is why acyl chlorides are used instead of trying to acylate directly with carboxylic acids under the same mild conditions.",
        ],
        commonMistake:
          "Describing attack on the alkyl carbon adjacent to the carbonyl rather than on the carbonyl carbon itself.",
        tags: ["mechanism", "addition-elimination", "leaving-group"],
      },
      {
        id: "t32-1-d10",
        noteId: "t32-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Calculate the maximum mass of ethyl ethanoate that could be formed in principle if 4.60 g of ethanol (Mr = 46) reacts with excess ethanoyl chloride. Show your working. State one reason why the actual isolated mass might be lower even with excess acyl chloride.",
        modelAnswerPoints: [
          "n(ethanol) = 4.60 / 46 = 0.100 mol.",
          "1 mol ethanol gives 1 mol ethyl ethanoate, so n(ester) = 0.100 mol.",
          "Mr(ethyl ethanoate, CH3COOC2H5) = 88, so mass = 0.100 × 88 = 8.80 g.",
          "Yield may be reduced by hydrolysis of acyl chloride, transfer losses, incomplete mixing, or handling losses of volatile HCl/ester.",
        ],
        workedSolution: [
          "The amount of ethanol is calculated from its mass and relative molecular mass as n = 4.60 g / 46 g mol^-1 = 0.100 mol, which uses the usual assumption that the sample is pure ethanol as stated.",
          "The stoichiometry between ethanol and ethyl ethanoate in this acylation is one to one, because each ethanol molecule supplies one oxygen that becomes the ester linkage oxygen, so the theoretical amount of ester is also 0.100 mol when ethanoyl chloride is in excess.",
          "The relative molecular mass of ethyl ethanoate is Mr = (2×12 + 4×1 + 16) for the ethyl ethanoate skeleton counted as C4H8O2 in atomic bookkeeping, which evaluates to 88, so the theoretical mass of ester is 0.100 mol × 88 g mol^-1 = 8.80 g.",
          "Even with excess acyl chloride, practical masses fall if moisture hydrolyses some acyl chloride, if volatile ester or HCl escapes during mixing, or if work-up transfers lose material, any of which lowers the isolated yield below the stoichiometric ceiling.",
        ],
        commonMistake:
          "Using Mr = 46 for the ester, or assuming a 1:2 mole ratio between ethanol and ester.",
        tags: ["stoichiometry", "calculations", "esters"],
      },
    ],
    flashcards: [
      {
        id: "t32-1-f1",
        noteId: "t32-1",
        difficulty: 1,
        front: "What two molecular species are formed when ethanol reacts with ethanoyl chloride?",
        back: "Ethyl ethanoate (ester) and hydrogen chloride (HCl).",
        examPhrasing: "State the products when ethanol reacts with ethanoyl chloride.",
        tags: ["ethyl-ethanoate", "products"],
      },
      {
        id: "t32-1-f2",
        noteId: "t32-1",
        difficulty: 1,
        front: "Write the equation for ethanol + ethanoyl chloride.",
        back: "CH3COCl + CH3CH2OH -> CH3COOCH2CH3 + HCl.",
        examPhrasing: "Write an equation for the formation of ethyl ethanoate from ethanol and ethanoyl chloride.",
        tags: ["equations"],
      },
      {
        id: "t32-1-f3",
        noteId: "t32-1",
        difficulty: 2,
        front: "What reaction type occurs at the acyl group when an alcohol attacks an acyl chloride?",
        back: "Addition-elimination (nucleophilic acyl substitution) at the carbonyl carbon.",
        examPhrasing: "Name the mechanism type for alcohol + acyl chloride forming an ester.",
        tags: ["mechanism"],
      },
      {
        id: "t32-1-f4",
        noteId: "t32-1",
        difficulty: 2,
        front: "Why use dry glassware for acyl chloride esterifications?",
        back: "Water hydrolyses acyl chlorides to carboxylic acids + HCl, competing with ester formation.",
        examPhrasing: "Explain why anhydrous conditions are preferred when an acyl chloride reacts with an alcohol.",
        tags: ["conditions", "hydrolysis"],
      },
      {
        id: "t32-1-f5",
        noteId: "t32-1",
        difficulty: 3,
        front: "Methanol + propanoyl chloride gives which ester?",
        back: "Methyl propanoate (+ HCl).",
        examPhrasing: "Name the ester formed from methanol and propanoyl chloride.",
        confusionPair: "methyl propanoate vs propyl methanoate",
        tags: ["naming"],
      },
      {
        id: "t32-1-f6",
        noteId: "t32-1",
        difficulty: 3,
        front: "One difference between Fischer esterification and acyl chloride + alcohol?",
        back: "Fischer is reversible, acid-catalysed, often heated; acyl chloride route is fast at room temperature and gives HCl, not the same equilibrium picture.",
        examPhrasing: "Contrast ester formation using a carboxylic acid with that using an acyl chloride.",
        tags: ["comparisons"],
      },
      {
        id: "t32-1-f7",
        noteId: "t32-1",
        difficulty: 4,
        front: "Which fragment of an ester name comes from the alcohol?",
        back: "The alkyl (or aryl) part before '-yl ...oate', e.g. ethyl in ethyl ethanoate from ethanol.",
        examPhrasing: "Explain how to name an ester from its alcohol and acyl chloride precursors.",
        tags: ["naming"],
      },
      {
        id: "t32-1-f8",
        noteId: "t32-1",
        difficulty: 4,
        front: "What is the ester from butan-1-ol + ethanoyl chloride?",
        back: "Butyl ethanoate.",
        examPhrasing: "Name the ester formed when butan-1-ol reacts with ethanoyl chloride.",
        tags: ["naming"],
      },
      {
        id: "t32-1-f9",
        noteId: "t32-1",
        difficulty: 5,
        front: "Phenol + ethanoyl chloride at room temperature?",
        back: "Phenyl ethanoate (aryl ester) + HCl.",
        examPhrasing: "Predict the organic product when phenol reacts with ethanoyl chloride.",
        tags: ["aryl-ester"],
      },
      {
        id: "t32-1-f10",
        noteId: "t32-1",
        difficulty: 5,
        front: "What is the theoretical mass of ethyl ethanoate from 0.0500 mol ethanol (excess acyl chloride)?",
        back: "0.0500 × 88 = 4.40 g (Mr ethyl ethanoate = 88).",
        examPhrasing: "Calculate the mass of ethyl ethanoate formed from a given amount of ethanol.",
        tags: ["stoichiometry"],
      },
    ],
  },

  "t32-2": {
    noteId: "t32-2",
    drills: [
      {
        id: "t32-2-d1",
        noteId: "t32-2",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Explain why phenol is acidic enough to react with aqueous sodium hydroxide, whereas ethanol does not behave as an acid in the same way with NaOH(aq). Then state and explain the order of acidity phenol, water, and ethanol for the 9701 comparison, including how the phenoxide ion is stabilised.",
        modelAnswerPoints: [
          "Phenol donates the hydroxyl proton to hydroxide, forming phenoxide; equilibrium lies far enough to the right for a practical reaction with NaOH(aq).",
          "Ethanol is a very weak acid; its alkoxide is not formed to a significant extent by mixing with NaOH(aq) in the usual school comparison.",
          "Acidity order: phenol > water > ethanol.",
          "Phenoxide negative charge is delocalised into the aromatic ring (resonance), stabilising the conjugate base relative to ethoxide where charge is localised on oxygen.",
        ],
        workedSolution: [
          "Phenol possesses a hydroxyl proton that is sufficiently acidic for deprotonation by hydroxide ions in aqueous sodium hydroxide, producing phenoxide ion and water, because the equilibrium for loss of that proton is more favourable than for a typical alcohol under comparable conditions.",
          "Ethanol is an extremely weak acid, so mixing ethanol with sodium hydroxide does not give a significant concentration of ethoxide by simple acid-base reaction in the way phenol does; ethanol is better thought of as undergoing reactions with sodium metal rather than as donating protons cleanly to hydroxide in water.",
          "The syllabus order of acid strength is phenol stronger than water, and water stronger than ethanol, which matches the idea that phenol can be deprotonated by carbonate only in more specialised contexts but clearly by hydroxide, while ethanol is weaker still.",
          "The underlying reason is stabilisation of the phenoxide conjugate base by resonance: the negative charge can be delocalised onto ortho and para ring carbons as well as oxygen, spreading charge density, whereas ethoxide has no comparable resonance stabilisation and therefore is a much stronger base, which disfavours ethanol losing its proton.",
        ],
        commonMistake:
          "Claiming ethanol is more acidic than phenol, or that phenol is a strong acid like a mineral acid.",
        tags: ["acidity", "phenol", "ethanol", "water"],
      },
      {
        id: "t32-2-d2",
        noteId: "t32-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Outline a two-step laboratory route from phenylamine to phenol. Include reagents for generating nitrous acid in situ, the temperature constraint for the first step, and what is done after the diazonium salt is formed. Write an equation in words or symbols for the second step showing replacement of the diazonium group by -OH.",
        modelAnswerPoints: [
          "Step 1: phenylamine + NaNO2 + dilute acid (HNO2 in situ), below 10 °C, forms benzenediazonium chloride (or diazonium salt).",
          "Step 2: warm diazonium solution with water; hydrolysis gives phenol + N2 (often written C6H5N2+ -> C6H5OH + N2 with acid context).",
          "Low temperature first step limits decomposition of diazonium salt; warming with water completes conversion to phenol.",
        ],
        workedSolution: [
          "The first step is diazotisation: phenylamine is dissolved with ice cooling and treated with sodium nitrite in the presence of dilute acid so that nitrous acid forms in situ and reacts with the aromatic amine below about 10 °C to give a benzenediazonium salt, which is only moderately stable and must be kept cold during its formation.",
          "The second step is warming of the cold diazonium solution with water, which hydrolyses the diazonium group and releases nitrogen gas while installing a hydroxyl group on the ring, which can be summarised as C6H5N2+(aq) + H2O(l) -> C6H5OH(aq) + N2(g) + H+(aq) in a simplified ionic picture acceptable at A Level if states are consistent with the mark scheme.",
          "The temperature story is therefore deliberate: cold to form the diazonium ion safely, then warming with water to drive its decomposition to phenol, linking amine chemistry to phenol synthesis in the required recall sequence.",
        ],
        commonMistake:
          "Omitting the below 10 °C condition for diazotisation, or warming before diazonium formation is complete.",
        tags: ["synthesis", "diazonium", "phenylamine"],
      },
      {
        id: "t32-2-d3",
        noteId: "t32-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which set places the species in decreasing acid strength (strongest acid first) for the ethanol / water / phenol comparison?",
        options: [
          { id: "A", text: "phenol > water > ethanol" },
          { id: "B", text: "ethanol > water > phenol" },
          { id: "C", text: "water > ethanol > phenol" },
          { id: "D", text: "ethanol > phenol > water" },
        ],
        correctOptionId: "A",
        explanation:
          "Phenol is the strongest weak acid of the three because phenoxide is resonance-stabilised; water is next; ethanol is weakest.",
        distractorRationale: {
          B: "That reverses the entire order; ethanol is weaker than water, not stronger than phenol.",
          C: "Water is not more acidic than phenol in this syllabus trio.",
          D: "Ethanol is the weakest acid of the three, not the strongest.",
        },
        tags: ["acidity", "mcq"],
      },
      {
        id: "t32-2-d4",
        noteId: "t32-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Write balanced equations for (i) phenol reacting with aqueous sodium hydroxide and (ii) phenol reacting with sodium metal. Name the organic salt formed in (i) and identify the gas evolved in (ii).",
        modelAnswerPoints: [
          "(i) C6H5OH + NaOH -> C6H5ONa + H2O (or ionic variants with C6H5O^- + Na+).",
          "Salt: sodium phenoxide.",
          "(ii) 2C6H5OH + 2Na -> 2C6H5ONa + H2; gas is hydrogen.",
        ],
        workedSolution: [
          "Phenol is acidic enough to transfer a proton to hydroxide, so with aqueous sodium hydroxide the molecular-level equation is C6H5OH + NaOH -> C6H5ONa + H2O, and the ionic picture C6H5OH + OH^- -> C6H5O^- + H2O is equally acceptable if sodium ion is understood as spectator.",
          "The ionic solid or solution species derived from phenoxide with sodium ion is named sodium phenoxide, which is the expected product name rather than calling it simply 'phenol sodium'.",
          "With sodium metal, phenol behaves like other OH compounds with active metals: 2C6H5OH + 2Na -> 2C6H5ONa + H2, so hydrogen gas is evolved as each sodium atom is oxidised to Na+ while phenol supplies protons that combine to H2.",
        ],
        commonMistake:
          "Writing Na2O or omitting H2 when phenol reacts with sodium.",
        tags: ["equations", "phenol", "bases", "sodium"],
      },
      {
        id: "t32-2-d5",
        noteId: "t32-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Describe the coupling reaction between phenol and a benzenediazonium salt in alkaline solution. State the class of product formed, how the -N=N- linkage arises, and one reason azo compounds are industrially significant.",
        modelAnswerPoints: [
          "Phenol in NaOH(aq) gives phenoxide, a stronger electron donor to the ring.",
          "Benzenediazonium ion acts as an electrophile; couples at activated positions (especially para to -OH) forming an azo compound.",
          "Azo compounds contain -N=N- between two aromatic fragments; many are coloured dyes.",
        ],
        workedSolution: [
          "In sodium hydroxide solution, phenol is deprotonated in part to phenoxide, which increases electron density on the aromatic ring and makes the ring especially nucleophilic toward external electrophiles while preserving the ortho/para directing pattern associated with the oxygen substituent.",
          "The diazonium ion from benzenediazonium chloride behaves as a mild electrophile that attacks the activated phenoxide ring, typically with coupling at the para position relative to -OH under many conditions, and the product retains the azo linkage -N=N- joining the two aromatic systems.",
          "Such azo compounds are often intensely coloured because the extended conjugated pi system lowers electronic excitation energies, which is why azo coupling chemistry underpins many dyestuffs and pigments in industrial applications.",
        ],
        commonMistake:
          "Describing the diazonium as a nucleophile, or claiming an ether is the main product.",
        tags: ["azo", "coupling", "phenoxide"],
      },
      {
        id: "t32-2-d6",
        noteId: "t32-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Phenol undergoes nitration with dilute nitric acid at room temperature to give mainly 2-nitrophenol and 4-nitrophenol. Explain why these conditions are much milder than those used for benzene nitration. Link your answer to the directing effect of the -OH group and to the relative electron density of the phenol ring compared with benzene.",
        modelAnswerPoints: [
          "The -OH group donates electron density into the ring (lone-pair overlap), activating the ring toward electrophilic substitution.",
          "-OH is ortho/para directing; nitration therefore favours 2- and 4-positions (6-position equivalent to 2 in monosubstituted phenol).",
          "Benzene nitration uses concentrated HNO3/H2SO4 and controlled warming because benzene is less reactive; phenol's activated ring does not need such aggressive nitrating mixture.",
        ],
        workedSolution: [
          "The hydroxyl substituent on phenol interacts with the pi system so that lone-pair electron density is donated into the aromatic ring, which increases the overall electron density compared with benzene and therefore increases the rate at which the ring attacks an electrophilic species such as the nitronium ion.",
          "Because -OH is strongly activating and ortho,para-directing, the major mononitration products under dilute nitric acid at room temperature are 2-nitrophenol and 4-nitrophenol, reflecting attack ortho and para to the oxygen-bearing carbon, which is exactly the substitution pattern the syllabus expects candidates to associate with phenol rather than random ring positions.",
          "Benzene itself is relatively electron-poor in the absence of such donors, so industrial or laboratory benzene nitration is conducted with a much stronger mixed-acid nitrating system and temperature control, whereas phenol is already so activated that dilute nitric acid at room temperature supplies enough electrophile for observable nitration without needing the same forcing conditions.",
        ],
        commonMistake:
          "Stating that phenol requires concentrated H2SO4/HNO3 and high temperature like benzene, or that -OH is meta-directing.",
        tags: ["nitration", "activation", "directing"],
      },
      {
        id: "t32-2-d7",
        noteId: "t32-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Write an equation for the reaction of phenol with excess bromine water at room temperature to form 2,4,6-tribromophenol. Explain why multiple substitution occurs so readily compared with benzene + Br2 in the absence of a Lewis-acid catalyst.",
        modelAnswerPoints: [
          "C6H5OH + 3Br2(aq) -> C6H2Br3OH + 3HBr (or structural tribromophenol).",
          "Phenol ring is strongly activated; bromine is polarised and acts as electrophile without AlBr3.",
          "Multiple ortho/para positions (2,4,6 relative to -OH) are substituted, giving white precipitate of tribromophenol.",
        ],
        workedSolution: [
          "A balanced summary is C6H5OH + 3Br2 -> 2,4,6-tribromophenol + 3HBr when excess bromine water is used, which shows three bromine molecules inserting at the two ortho and one para positions relative to the hydroxyl group on the phenol ring.",
          "The phenolic ring is so strongly activated toward electrophilic substitution that molecular bromine, partially polarised in water, generates sufficient electrophilic character for attack without aluminium bromide catalyst, which contrasts sharply with benzene where a halogen carrier is normally required to generate a strong enough electrophile.",
          "Because the -OH group directs to ortho and para sites and the ring is highly electron-rich, further substitution occurs rapidly after the first bromination until all three activated positions are brominated, which is why the syllabus uses tribromophenol as the characteristic product with bromine water.",
        ],
        commonMistake:
          "Giving monobromophenol as the sole product, or writing FeBr3 as essential for phenol bromination in water.",
        tags: ["bromination", "tribromophenol", "activation"],
      },
      {
        id: "t32-2-d8",
        noteId: "t32-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which condition is essential when forming benzenediazonium chloride from phenylamine before hydrolysing it to phenol?",
        options: [
          { id: "A", text: "Keep the diazotisation mixture below about 10 °C during formation of the diazonium salt." },
          { id: "B", text: "Heat the mixture under reflux at 100 °C while adding NaNO2." },
          { id: "C", text: "Use concentrated sulfuric acid only, with no aqueous solvent." },
          { id: "D", text: "Carry out the reaction in darkness with UV irradiation after warming." },
        ],
        correctOptionId: "A",
        explanation:
          "Diazonium salts decompose if warmed too early; cold diazotisation stabilises the ion long enough for the next step.",
        distractorRationale: {
          B: "High temperature during diazotisation would destroy the diazonium ion rather than form it cleanly.",
          C: "Aqueous acidic diazotisation with NaNO2/H+ is the standard recall pathway, not concentrated sulfuric acid alone as described.",
          D: "UV is not the syllabus-critical control; temperature control is.",
        },
        tags: ["diazonium", "conditions", "mcq"],
      },
      {
        id: "t32-2-d9",
        noteId: "t32-2",
        kind: "mcq",
        difficulty: 3,
        stem: "In electrophilic substitution of phenol, the -OH group directs incoming electrophiles mainly to which ring positions?",
        options: [
          { id: "A", text: "2-, 4- and 6- positions (ortho and para to the carbon bearing -OH)" },
          { id: "B", text: "3- and 5- positions only" },
          { id: "C", text: "Only the 1-position (the ipso carbon)" },
          { id: "D", text: "Exclusively meta positions relative to -OH" },
        ],
        correctOptionId: "A",
        explanation:
          "-OH is a strong ortho,para director; in phenol the two ortho and one para sites correspond to 2-, 4- and 6- in the usual numbering.",
        distractorRationale: {
          B: "Those are meta positions; -OH is not a meta director in this syllabus treatment.",
          C: "Electrophiles do not substitute at the carbon already bonded to oxygen as the main outcome.",
          D: "Meta directing contradicts the activating -OH substituent.",
        },
        tags: ["directing", "mcq"],
      },
      {
        id: "t32-2-d10",
        noteId: "t32-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "2-Naphthol has a hydroxyl group fused to an aromatic system (a phenolic -OH). Predict how its acidity in water compares with ethanol and state whether you expect 2-naphthol to react with NaOH(aq). Briefly justify one parallel with phenol regarding electrophilic substitution under mild conditions.",
        modelAnswerPoints: [
          "2-Naphthol is more acidic than ethanol (phenolic -OH behaviour).",
          "Reacts with NaOH(aq) to form sodium 2-naphthoxide (or analogous salt).",
          "Extended aromatic system stabilises conjugate base by delocalisation; activated ring undergoes electrophilic substitution more readily than benzene, similar to phenol.",
        ],
        workedSolution: [
          "Because 2-naphthol contains a hydroxyl group attached directly to an aromatic carbon, it should be classified as a phenol-type acid, which means it is substantially more acidic in water than ethanol, whose hydroxyl proton is attached to a saturated carbon and gives an alkoxide that is not resonance-stabilised in the same way.",
          "The enhanced acidity implies that 2-naphthol will react with aqueous sodium hydroxide to give the corresponding naphthoxide salt, for example sodium 2-naphthoxide, in the same qualitative sense as phenol forming sodium phenoxide.",
          "For electrophilic substitution, the naphthalene ring bearing a phenolic -OH is strongly activated and ortho,para directed relative to that substituent within its ring, so mild reagents that would leave benzene largely untouched can still react, which is the syllabus 'apply to other phenolic compounds' parallel to phenol's easy bromination with bromine water and mild nitration.",
        ],
        commonMistake:
          "Treating 2-naphthol as a simple alcohol with ethanol-like acidity.",
        tags: ["naphthol", "extension", "acidity"],
      },
    ],
    flashcards: [
      {
        id: "t32-2-f1",
        noteId: "t32-2",
        difficulty: 1,
        front: "Acidity order: phenol, water, ethanol?",
        back: "phenol > water > ethanol (weakest: ethanol).",
        examPhrasing: "State and explain the relative acidities of phenol, water, and ethanol.",
        tags: ["acidity"],
      },
      {
        id: "t32-2-f2",
        noteId: "t32-2",
        difficulty: 1,
        front: "Why is phenol more acidic than ethanol?",
        back: "Phenoxide charge is delocalised into the ring (resonance); ethoxide is not stabilised the same way.",
        examPhrasing: "Explain the acidity of phenol compared with ethanol.",
        tags: ["acidity", "resonance"],
      },
      {
        id: "t32-2-f3",
        noteId: "t32-2",
        difficulty: 2,
        front: "Two steps: phenylamine -> phenol?",
        back: "Cold NaNO2 + dilute acid (<10 °C) -> diazonium salt; then warm with water -> phenol + N2.",
        examPhrasing: "Describe the preparation of phenol from phenylamine.",
        tags: ["synthesis", "diazonium"],
      },
      {
        id: "t32-2-f4",
        noteId: "t32-2",
        difficulty: 2,
        front: "Phenol + NaOH(aq)?",
        back: "Sodium phenoxide + water: C6H5OH + NaOH -> C6H5ONa + H2O.",
        examPhrasing: "Write the equation for phenol reacting with aqueous sodium hydroxide.",
        tags: ["equations", "bases"],
      },
      {
        id: "t32-2-f5",
        noteId: "t32-2",
        difficulty: 3,
        front: "Phenol + Na metal?",
        back: "Sodium phenoxide + H2: 2C6H5OH + 2Na -> 2C6H5ONa + H2.",
        examPhrasing: "Write the equation for phenol reacting with sodium.",
        tags: ["equations", "sodium"],
      },
      {
        id: "t32-2-f6",
        noteId: "t32-2",
        difficulty: 3,
        front: "Phenol + benzenediazonium in NaOH(aq)?",
        back: "Azo compound (-N=N-); often coloured dye.",
        examPhrasing: "Describe the reaction of phenol with a diazonium salt in alkaline solution.",
        tags: ["azo"],
      },
      {
        id: "t32-2-f7",
        noteId: "t32-2",
        difficulty: 4,
        front: "Phenol + dilute HNO3 at room temperature?",
        back: "Mainly 2-nitrophenol and 4-nitrophenol; milder than benzene nitration.",
        examPhrasing: "State the products of nitrating phenol with dilute nitric acid at room temperature.",
        confusionPair: "phenol nitration vs benzene mixed acid",
        tags: ["nitration"],
      },
      {
        id: "t32-2-f8",
        noteId: "t32-2",
        difficulty: 4,
        front: "Phenol + excess Br2(aq)?",
        back: "2,4,6-tribromophenol + HBr; no AlBr3 needed.",
        examPhrasing: "Give the product when phenol reacts with excess bromine water.",
        tags: ["bromination"],
      },
      {
        id: "t32-2-f9",
        noteId: "t32-2",
        difficulty: 5,
        front: "Why milder conditions for phenol than benzene for EAS?",
        back: "-OH activates the ring (donates electron density); benzene needs stronger electrophile/generating conditions.",
        examPhrasing: "Explain why phenol nitrates and brominates under milder conditions than benzene.",
        tags: ["activation"],
      },
      {
        id: "t32-2-f10",
        noteId: "t32-2",
        difficulty: 5,
        front: "Where does -OH on phenol direct electrophiles?",
        back: "Ortho and para: 2-, 4-, 6- positions in standard numbering.",
        examPhrasing: "Recall the directing effect of the hydroxyl group in phenol.",
        tags: ["directing"],
      },
    ],
  },
};
