import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 25 — Acids and bases (`t25-1`) and Partition coefficients (`t25-2`).
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §25.1; each bullet hit by ≥1 drill id):
 * - Conjugate acid / conjugate base; pairs in reactions → d1
 * - Define pH, Ka, pKa, Kw; use in calculations → d2, d3
 * - [H+] and pH: strong acids, strong alkalis, weak acids → d4, d5, d6
 * - Buffer: define; preparation; control pH with equations; uses incl. HCO3- in blood → d7, d8
 * - Calculate pH of buffer solutions → d8
 * - Ksp term; expression; calculate Ksp ↔ concentrations → d9, d10
 * - Common ion effect: explain + calculations → d10
 *
 * LO crosswalk (§25.2):
 * - Partition coefficient Kpc → d1
 * - Calculate / use Kpc (same physical state in both solvents) → d2, d4, d8
 * - Factors affecting Kpc: polarities of solute and solvents → d5, d6, d10
 */
export const CHEMISTRY_TOPIC25_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t25-1": {
    noteId: "t25-1",
    drills: [
      {
        id: "t25-1-d1",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 1,
        marks: 5,
        stem: "Define the terms conjugate acid and conjugate base in the Brønsted-Lowry sense. For the equilibrium NH3(aq) + H2O(l) ⇌ NH4+(aq) + OH-(aq), identify the two conjugate acid-base pairs and state how each pair is related by a single proton difference.",
        modelAnswerPoints: [
          "A Brønsted-Lowry acid donates H+; its conjugate base is the species formed after donation.",
          "A Brønsted-Lowry base accepts H+; its conjugate acid is the species formed after acceptance.",
          "Pairs are NH4+ / NH3 and H2O / OH-.",
          "Each pair differs by one H+ (NH4+ is conjugate acid of NH3; H2O is conjugate acid of OH- in this reaction).",
        ],
        workedSolution: [
          "In the Brønsted-Lowry picture, a conjugate base is what remains when a particular acid has donated a proton to something else, so it is the deprotonated partner in an acid-base pair, while a conjugate acid is what is obtained when a base has accepted a proton from elsewhere.",
          "For the reaction NH3(aq) + H2O(l) ⇌ NH4+(aq) + OH-(aq), ammonia is acting as a base by accepting a proton from water, which therefore acts as an acid in the forward direction, producing ammonium ion and hydroxide ion.",
          "The two conjugate acid-base pairs are NH4+ with NH3 and H2O with OH-, because ammonium is simply ammonia plus one proton, and water is hydroxide plus one proton.",
          "Thus NH4+ is the conjugate acid of base NH3, and H2O is the conjugate acid of base OH-, and in each case the members of the pair are interconverted by loss or gain of exactly one proton, which is the defining structural relationship the syllabus expects students to recognise in proton-transfer equations.",
        ],
        commonMistake:
          "Pairing NH3 with OH- or NH4+ with H2O, which ignores which species donated and which accepted H+ in the forward step.",
        tags: ["conjugate-pairs", "bronsted-lowry", "definitions"],
      },
      {
        id: "t25-1-d2",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Give the mathematical definitions of pH, acid dissociation constant Ka for a weak monobasic acid HA, pKa, and ionic product of water Kw at a stated temperature. Show how [H+(aq)] may be obtained from pH, and write the numerical value of Kw for pure water at 25 °C.",
        modelAnswerPoints: [
          "pH = -log10[H+], with [H+] in mol dm^-3.",
          "Ka = [H+][A-] / [HA] for HA(aq) + H2O(l) ⇌ H+(aq) + A-(aq) at equilibrium.",
          "pKa = -log10Ka.",
          "Kw = [H+][OH-] (mol^2 dm^-6 at 25 °C for pure water Kw = 1.0 × 10^-14).",
          "Rearrangement: [H+] = 10^(-pH).",
        ],
        workedSolution: [
          "pH is defined as the negative base-10 logarithm of the hydrogen ion concentration in aqueous solution, pH = -log10[H+], where [H+] is expressed in mol dm^-3 so that the logarithm is dimensionally consistent with standard data book conventions.",
          "For a weak monobasic acid HA, the acid dissociation constant Ka is the equilibrium constant for the reaction written as HA(aq) + H2O(l) ⇌ H+(aq) + A-(aq), so in dilute solution Ka = [H+][A-] / [HA] when activities are approximated by concentrations in the usual way.",
          "pKa is defined analogously to pH as pKa = -log10Ka, which means stronger acids have larger Ka and therefore smaller pKa values at a given temperature.",
          "The ionic product of water Kw is defined by Kw = [H+][OH-] for the autoprotolysis equilibrium of water; at 25 °C the accepted value for pure water is Kw = 1.0 × 10^-14 mol^2 dm^-6, which links hydrogen and hydroxide ion concentrations in any dilute aqueous system at that temperature.",
          "Rearranging the definition of pH gives [H+] = 10^(-pH), which is the form used when a pH meter reading is converted back to hydrogen ion concentration for further equilibrium calculations.",
        ],
        commonMistake:
          "Omitting the negative sign in pH = -log10[H+], or including [H2O] in the Ka expression for HA in dilute aqueous solution.",
        tags: ["ph", "ka", "pka", "kw", "definitions"],
      },
      {
        id: "t25-1-d3",
        noteId: "t25-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Ethanoic acid has Ka = 1.74 × 10^-5 at 25 °C. Which statement comparing two monobasic acids HA and HB at the same temperature is correct if pKa(HA) < pKa(HB)?",
        options: [
          { id: "A", text: "HA is a weaker acid than HB and has the smaller Ka." },
          { id: "B", text: "HA is a stronger acid than HB and has the larger Ka." },
          { id: "C", text: "HA and HB have the same Ka because pKa is logarithmic." },
          { id: "D", text: "HA donates OH- more readily than HB." },
        ],
        correctOptionId: "B",
        explanation:
          "pKa = -log10Ka, so smaller pKa corresponds to larger Ka and stronger acid for related Brønsted acids.",
        distractorRationale: {
          A: "Smaller pKa means larger Ka, hence stronger, not weaker, acid character.",
          C: "Different pKa values imply different Ka values; the log merely rescales the comparison.",
          D: "Brønsted acids donate H+, not OH-; that option confuses acid behaviour with base behaviour.",
        },
        tags: ["pka", "ka", "acid-strength"],
      },
      {
        id: "t25-1-d4",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Calculate the pH at 25 °C of (a) 0.0800 mol dm^-3 hydrochloric acid and (b) 0.0400 mol dm^-3 aqueous sodium hydroxide. State any assumption you make about the behaviour of the strong acid and strong alkali in water.",
        modelAnswerPoints: [
          "Strong monoprotic acid: [H+] = 0.0800 mol dm^-3, pH = -log10(0.0800) = 1.10 (2 d.p. typical).",
          "Strong alkali: [OH-] = 0.0400 mol dm^-3, pOH = -log10(0.0400) = 1.40.",
          "Using Kw at 25 °C, pH = 14.00 - pOH = 12.60.",
          "Assumption: complete dissociation of HCl and NaOH so stoichiometric ion concentrations equal formal concentrations in dilute solution.",
        ],
        workedSolution: [
          "Hydrochloric acid is a strong monoprotic acid, so in dilute aqueous solution it may be treated as fully dissociated, giving [H+] equal to the formal acid concentration 0.0800 mol dm^-3.",
          "Therefore pH = -log10(0.0800) = 1.0979..., which is reported as 1.10 to two decimal places, consistent with the precision implied by the data.",
          "Sodium hydroxide is a strong base providing one hydroxide ion per formula unit, so [OH-] = 0.0400 mol dm^-3, and pOH = -log10(0.0400) = 1.3979..., which rounds to 1.40 at two decimal places.",
          "At 25 °C the ionic product of water gives pH + pOH = 14.00 for dilute aqueous solutions, so pH = 14.00 - 1.40 = 12.60, which is strongly alkaline as expected for this hydroxide concentration.",
          "The key assumption is complete ionisation of both HCl and NaOH, which is the standard examination model for strong acid and strong alkali pH calculations unless non-ideality is explicitly introduced.",
        ],
        commonMistake:
          "Using [H+] = 0.0400 for NaOH, or forgetting to subtract pOH from 14 when converting from strong alkali to pH.",
        tags: ["ph", "strong-acid", "strong-alkali", "calculations"],
      },
      {
        id: "t25-1-d5",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Calculate the pH at 25 °C of 0.150 mol dm^-3 aqueous ethanoic acid, given Ka = 1.74 × 10^-5 mol dm^-3. State the simplifying assumption used and show that it is reasonable for this concentration.",
        modelAnswerPoints: [
          "Let [H+] = x from dissociation; Ka = x^2 / (c - x) with c = 0.150.",
          "Assume x << c so [H+] ≈ sqrt(Ka × c) = sqrt(1.74 × 10^-5 × 0.150) = 1.61 × 10^-3 mol dm^-3.",
          "pH = -log10(1.61 × 10^-3) = 2.79 (2 d.p.).",
          "Check: x/c ≈ 1.1 %, so neglecting x in (c - x) is acceptable at this level.",
        ],
        workedSolution: [
          "For the weak acid equilibrium CH3COOH ⇌ H+ + CH3COO-, the equilibrium expression Ka = [H+][CH3COO-] / [CH3COOH] may be applied with initial concentration c = 0.150 mol dm^-3 and degree of dissociation small enough that the equilibrium acid concentration is still approximately c.",
          "If the hydrogen ion concentration produced by dissociation is denoted x, then [H+] ≈ [CH3COO-] ≈ x and [CH3COOH] ≈ c - x, so Ka ≈ x^2 / c when x is much smaller than c, giving x ≈ sqrt(Ka × c).",
          "Substituting the numbers, x ≈ sqrt(1.74 × 10^-5 × 0.150) = sqrt(2.61 × 10^-6) = 1.61 × 10^-3 mol dm^-3, so pH = -log10(1.61 × 10^-3) = 2.79 to two decimal places.",
          "To justify the approximation, compare x with c: x/c ≈ (1.61 × 10^-3) / 0.150 ≈ 0.011, which is about 1 %, so replacing (c - x) by c introduces only a small error and the sqrt(Ka × c) route is acceptable unless the mark scheme demands the quadratic.",
          "The result is a weakly acidic pH noticeably greater than that of a strong acid of the same formal concentration, which matches the physical picture of partial dissociation.",
        ],
        commonMistake:
          "Treating ethanoic acid as fully dissociated and using pH = -log10(0.150), which would grossly underestimate the pH.",
        tags: ["weak-acid", "ka", "ph", "calculations"],
      },
      {
        id: "t25-1-d6",
        noteId: "t25-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which mixture is best described as forming an acidic buffer solution in water at 25 °C?",
        options: [
          { id: "A", text: "Excess HCl(aq) mixed with NaOH(aq) to give a neutral solution." },
          { id: "B", text: "NH3(aq) mixed with excess HCl(aq) so only NH4+ and Cl- remain." },
          { id: "C", text: "CH3COOH(aq) mixed with CH3COONa(aq) so both CH3COOH and CH3COO- are present in appreciable amounts." },
          { id: "D", text: "NaOH(aq) mixed with NaCl(aq)." },
        ],
        correctOptionId: "C",
        explanation:
          "An acidic buffer needs a weak acid together with its conjugate base in significant amounts; ethanoic acid plus a soluble source of ethanoate provides that pair.",
        distractorRationale: {
          A: "Strong acid and strong base to neutrality do not leave a weak/conjugate pair in reserve.",
          B: "Excess strong acid converts all ammonia to ammonium; without free NH3 you do not have the NH3/NH4+ buffer pair in the usual sense.",
          D: "Hydroxide with chloride is not a conjugate acid-base buffer system for pH control around a pKa.",
        },
        tags: ["buffers", "definitions"],
      },
      {
        id: "t25-1-d7",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 4,
        marks: 8,
        stem: "(a) Define a buffer solution. (b) Explain how an acidic buffer may be prepared starting from a weak acid HA. (c) Explain, with chemical equations, how such a buffer resists pH change when small amounts of H+ and OH- are added. (d) Describe the role of hydrogencarbonate ion in helping to control blood pH.",
        modelAnswerPoints: [
          "(a) A buffer resists pH change when small amounts of acid or alkali are added (contains weak acid/conjugate base or weak base/conjugate acid pair in appreciable amounts).",
          "(b) Mix weak acid HA with a salt of A- (e.g. NaA) so both HA and A- are present.",
          "(c) Added H+ removed: A- + H+ -> HA; added OH- removed: HA + OH- -> A- + H2O.",
          "(d) Blood buffer: H2CO3 / HCO3- pair; added acid reacts with HCO3-; added base is buffered by H2CO3 (linked to CO2/HCO3- equilibrium).",
        ],
        workedSolution: [
          "(a) A buffer solution is one that resists changes in pH when limited quantities of strong acid or strong alkali are added, because it contains components that can consume added H+ or OH- without shifting the hydrogen ion concentration as sharply as in an unbuffered solution.",
          "(b) An acidic buffer is commonly prepared by dissolving a weak acid HA together with a soluble salt that supplies its conjugate base A-, for example mixing ethanoic acid with sodium ethanoate, so that the equilibrium mixture contains substantial concentrations of both HA and A- in the same solution volume.",
          "(c) When a small amount of extra acid is introduced, most of the added hydrogen ions react with the base component of the buffer according to A-(aq) + H+(aq) -> HA(aq), which converts A- into HA and prevents a large rise in free [H+], whereas when a small amount of alkali is added, hydroxide ions are consumed by the weak acid according to HA(aq) + OH-(aq) -> A-(aq) + H2O(l), which converts HA into A- and prevents a large fall in [H+], so in both directions the added reagent is chemically absorbed by the buffer pair.",
          "(d) In blood, the hydrogencarbonate ion is part of the carbonic acid / hydrogencarbonate buffer system linked to carbon dioxide transport, so added acid can be taken up by HCO3- forming H2CO3 (which is in equilibrium with aqueous CO2), while added base can be neutralised by carbonic acid species, which helps keep extracellular pH within the narrow range compatible with enzyme function and oxygen transport by haemoglobin.",
        ],
        commonMistake:
          "Omitting equations for buffer action, or claiming NaCl alone buffers pH.",
        tags: ["buffers", "equations", "blood-buffer", "definitions"],
      },
      {
        id: "t25-1-d8",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A buffer solution contains 0.250 mol ethanoic acid and 0.400 mol ethanoate ion in 1.00 dm^3 at 25 °C. Given pKa for ethanoic acid = 4.76, calculate (a) the initial pH and (b) the pH after adding 0.0200 mol HCl(aq), assuming negligible volume change.",
        modelAnswerPoints: [
          "(a) pH = pKa + log10([A-]/[HA]) = 4.76 + log10(0.400/0.250) = 4.76 + 0.204 = 4.96.",
          "(b) H+ reacts with CH3COO-: new moles A- = 0.380, HA = 0.270.",
          "pH = 4.76 + log10(0.380/0.270) = 4.76 + 0.148 = 4.91.",
          "Small pH change illustrates buffer action.",
        ],
        workedSolution: [
          "(a) Because both buffer components are in the same 1.00 dm^3 volume, concentration ratio equals mole ratio, so the Henderson-Hasselbalch form pH = pKa + log10([CH3COO-]/[CH3COOH]) may be applied directly as pH = 4.76 + log10(0.400/0.250).",
          "The ratio 0.400/0.250 is 1.60, and log10(1.60) = 0.2041, so pH = 4.76 + 0.204 = 4.96 to two decimal places, which is slightly on the basic side of the pKa because there is more conjugate base than weak acid.",
          "(b) Strong hydrochloric acid supplies H+ which reacts essentially to completion with ethanoate, CH3COO- + H+ -> CH3COOH, so 0.0200 mol A- is consumed and 0.0200 mol HA is formed, giving new amounts n(A-) = 0.380 mol and n(HA) = 0.270 mol in the same 1.00 dm^3.",
          "Reapplying the buffer equation, pH = 4.76 + log10(0.380/0.270) = 4.76 + log10(1.407) = 4.76 + 0.148 = 4.91, which is only 0.05 pH units lower than before despite adding strong acid, demonstrating buffering.",
        ],
        commonMistake:
          "Adding 0.0200 to both HA and A- instead of converting A- to HA, or using pH = pKa without the log term.",
        tags: ["buffers", "henderson-hasselbalch", "calculations"],
      },
      {
        id: "t25-1-d9",
        noteId: "t25-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which expression is the correct solubility product, Ksp, for calcium fluoride, CaF2(s), in equilibrium with its ions in saturated aqueous solution at a given temperature?",
        options: [
          { id: "A", text: "Ksp = [Ca2+][F-]" },
          { id: "B", text: "Ksp = [Ca2+][F-]^2" },
          { id: "C", text: "Ksp = [Ca2+][F-]^2 / [CaF2]" },
          { id: "D", text: "Ksp = [Ca2+] + 2[F-]" },
        ],
        correctOptionId: "B",
        explanation:
          "Ksp uses ion concentrations with stoichiometric powers; the solid is omitted from the expression.",
        distractorRationale: {
          A: "That would correspond to a 1:1 salt such as CaF+, not CaF2.",
          C: "The concentration of the undissolved solid does not appear in Ksp.",
          D: "Ksp is a product of powers of concentrations, not a sum of concentrations.",
        },
        tags: ["ksp", "expressions"],
      },
      {
        id: "t25-1-d10",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "Silver chloride has Ksp = 1.8 × 10^-10 mol^2 dm^-6 at 25 °C. (a) Calculate its molar solubility in pure water. (b) Calculate its molar solubility in 0.10 mol dm^-3 NaCl(aq), explaining in terms of the common ion effect why the value is smaller than in (a).",
        modelAnswerPoints: [
          "(a) AgCl(s) ⇌ Ag+(aq) + Cl-(aq); Ksp = [Ag+][Cl-] = s^2 in pure water.",
          "s = sqrt(1.8 × 10^-10) = 1.34 × 10^-5 mol dm^-3.",
          "(b) [Cl-] ≈ 0.10 from NaCl; [Ag+] = Ksp / [Cl-] = 1.8 × 10^-9 mol dm^-3.",
          "Common ion Cl- shifts equilibrium left (Le Chatelier), lowering solubility.",
        ],
        workedSolution: [
          "(a) For silver chloride the dissolution equilibrium is AgCl(s) ⇌ Ag+(aq) + Cl-(aq), and the solubility product expression is Ksp = [Ag+][Cl-] with the solid omitted as usual.",
          "In pure water, if the molar solubility is s, then [Ag+] = [Cl-] = s at saturation, so Ksp = s^2 and s = sqrt(1.8 × 10^-10) = 1.34 × 10^-5 mol dm^-3 to three significant figures, which is the amount of AgCl that can dissolve per dm^3 at equilibrium.",
          "(b) In 0.10 mol dm^-3 sodium chloride, chloride ion is already present from a fully ionised strong electrolyte, so at equilibrium [Cl-] is dominated by 0.10 mol dm^-3 to a good approximation, and the silver ion concentration must adjust to satisfy Ksp = [Ag+][Cl-].",
          "Therefore [Ag+] = Ksp / 0.10 = (1.8 × 10^-10) / 0.10 = 1.8 × 10^-9 mol dm^-3, which is also the molar solubility of AgCl in this medium because each formula unit of AgCl that dissolves still produces one Ag+.",
          "This is much smaller than in pure water because the added chloride is a common ion that shifts the dissolution equilibrium toward solid AgCl, which is exactly the common ion effect: shared Cl- lowers the equilibrium solubility even though Ksp at that temperature is unchanged.",
        ],
        commonMistake:
          "Using [Cl-] = s + 0.10 but then dropping 0.10, or claiming the common ion increases solubility.",
        tags: ["ksp", "common-ion", "solubility", "calculations"],
      },
    ],
    flashcards: [
      {
        id: "t25-1-f1",
        noteId: "t25-1",
        difficulty: 1,
        front: "What is a conjugate acid-base pair?",
        back: "Two species that differ by one H+: the acid is the protonated form, the base is the deprotonated form (e.g. CH3COOH / CH3COO-).",
        examPhrasing: "Define conjugate acid-base pair.",
        tags: ["conjugate-pairs", "definitions"],
      },
      {
        id: "t25-1-f2",
        noteId: "t25-1",
        difficulty: 1,
        front: "Write the definition of pH in dilute aqueous solution.",
        back: "pH = -log10[H+], with [H+] in mol dm^-3.",
        examPhrasing: "Define pH.",
        tags: ["ph", "definitions"],
      },
      {
        id: "t25-1-f3",
        noteId: "t25-1",
        difficulty: 2,
        front: "Numerical value of Kw for pure water at 25 °C?",
        back: "Kw = [H+][OH-] = 1.0 × 10^-14 mol^2 dm^-6 (so pH + pOH = 14.00 in pure water at 25 °C).",
        examPhrasing: "State the ionic product of water at 25 °C.",
        tags: ["kw", "water"],
      },
      {
        id: "t25-1-f4",
        noteId: "t25-1",
        difficulty: 2,
        front: "Henderson-Hasselbalch equation for acid buffer HA / A-?",
        back: "pH = pKa + log10([A-]/[HA]) when activities ≈ concentrations.",
        examPhrasing: "Write the expression used to calculate pH of an acidic buffer.",
        tags: ["buffers", "equations"],
      },
      {
        id: "t25-1-f5",
        noteId: "t25-1",
        difficulty: 3,
        front: "How does added H+ get removed in an ethanoate / ethanoic acid buffer?",
        back: "CH3COO- + H+ -> CH3COOH, so free [H+] rises only slightly.",
        examPhrasing: "Explain buffer action when acid is added, with an equation.",
        tags: ["buffers", "equations"],
      },
      {
        id: "t25-1-f6",
        noteId: "t25-1",
        difficulty: 3,
        front: "How does added OH- get removed in the same acidic buffer?",
        back: "CH3COOH + OH- -> CH3COO- + H2O.",
        examPhrasing: "Explain buffer action when alkali is added, with an equation.",
        tags: ["buffers", "equations"],
      },
      {
        id: "t25-1-f7",
        noteId: "t25-1",
        difficulty: 4,
        front: "What does Ksp represent for a sparingly soluble salt?",
        back: "The equilibrium constant for dissolution written only with ion concentrations raised to stoichiometric powers; the solid is omitted.",
        examPhrasing: "State what is meant by solubility product.",
        tags: ["ksp", "definitions"],
      },
      {
        id: "t25-1-f8",
        noteId: "t25-1",
        difficulty: 4,
        front: "Ksp for CaF2 in terms of molar solubility s in pure water?",
        back: "[Ca2+] = s, [F-] = 2s, so Ksp = s(2s)^2 = 4s^3.",
        examPhrasing: "Derive Ksp for calcium fluoride from its molar solubility.",
        tags: ["ksp", "solubility"],
      },
      {
        id: "t25-1-f9",
        noteId: "t25-1",
        difficulty: 5,
        front: "What is the common ion effect on solubility?",
        back: "Adding a solution ion already produced by the salt shifts dissolution equilibrium toward the solid, so molar solubility decreases.",
        examPhrasing: "Explain the common ion effect on solubility of a sparingly soluble salt.",
        confusionPair: "common ion decreases vs increases solubility",
        tags: ["common-ion", "ksp"],
      },
      {
        id: "t25-1-f10",
        noteId: "t25-1",
        difficulty: 5,
        front: "For a weak monobasic acid, when is [H+] ≈ sqrt(Ka × c) valid?",
        back: "When dissociation is small so [HA] ≈ c and [H+] from water is negligible compared with that from HA.",
        examPhrasing: "State the approximation used to find [H+] of a weak acid from Ka and c.",
        tags: ["weak-acid", "approximation"],
      },
    ],
  },

  "t25-2": {
    noteId: "t25-2",
    drills: [
      {
        id: "t25-2-d1",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "State what is meant by the partition coefficient, Kpc, for a solute distributed between two immiscible solvents at equilibrium. Specify what must stay the same about the solute in each phase for the syllabus definition to apply directly.",
        modelAnswerPoints: [
          "Kpc is the equilibrium ratio of solute concentrations in two immiscible solvents at a fixed temperature.",
          "The solvent order used in the definition must be stated (e.g. Kpc(org/water) = [solute]_org / [solute]_water).",
          "Solute must be in the same physical state / same molecular species in both phases (no net reaction between solvents).",
        ],
        workedSolution: [
          "The partition coefficient Kpc describes how a single solute distributes itself between two liquid phases that do not mix, once shaking and separation have been allowed to reach equilibrium at a given temperature.",
          "It is defined as the ratio of equilibrium concentrations of that solute in the two solvents, written in the order the question specifies, for example Kpc = [solute] in solvent 1 / [solute] in solvent 2, and because it is a ratio of concentrations it is dimensionless if both concentrations are expressed in the same units such as mol dm^-3.",
          "For the definition to apply in the straightforward way examined at A Level, the solute should be present as the same molecular species in both phases, meaning the same physical state and no acid-base or other reactions that convert it to a different species in one layer only.",
          "If the solute reacted differently in each solvent, the simple concentration ratio would no longer represent a true partition equilibrium of one species between two media.",
        ],
        commonMistake:
          "Defining Kpc as a ratio of masses or moles without mentioning that concentrations are required when layer volumes differ.",
        tags: ["kpc", "definitions", "partition"],
      },
      {
        id: "t25-2-d2",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "At 25 °C, an organic solute X is equilibrated between hexane and water. At equilibrium, [X] in hexane = 0.060 mol dm^-3 and [X] in water = 0.012 mol dm^-3. Calculate Kpc(hexane/water) for X.",
        modelAnswerPoints: [
          "Kpc(hexane/water) = [X]_hexane / [X]_water.",
          "Kpc = 0.060 / 0.012 = 5.0 (dimensionless).",
        ],
        workedSolution: [
          "The partition coefficient in the stated order hexane over water is constructed from the equilibrium concentrations as Kpc(hexane/water) = [X] in hexane divided by [X] in water, because the numerator solvent is hexane in this definition.",
          "Substituting the given equilibrium values gives Kpc = 0.060 mol dm^-3 / 0.012 mol dm^-3 = 5.0 exactly to two significant figures as implied by the data spacing.",
          "A value greater than 1 shows that, for this solute and solvent pair at 25 °C, hexane holds a higher equilibrium concentration than water, so extraction from water into hexane would be thermodynamically favourable in a single equilibrium step.",
        ],
        commonMistake:
          "Inverting the ratio to water/hexane without the question asking for the reciprocal.",
        tags: ["kpc", "calculations", "partition"],
      },
      {
        id: "t25-2-d3",
        noteId: "t25-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Two immiscible solvents P and Q are in equilibrium with solute Y. Kpc(P/Q) = 8.0. What is Kpc(Q/P)?",
        options: [
          { id: "A", text: "8.0" },
          { id: "B", text: "0.125" },
          { id: "C", text: "1.0" },
          { id: "D", text: "64" },
        ],
        correctOptionId: "B",
        explanation:
          "Swapping numerator and denominator inverts Kpc, so Kpc(Q/P) = 1 / Kpc(P/Q) = 1/8.0 = 0.125.",
        distractorRationale: {
          A: "That is Kpc(P/Q), not the reversed order.",
          C: "Only true if the solute partitions equally between P and Q.",
          D: "That would be Kpc squared, not the reciprocal order swap.",
        },
        tags: ["kpc", "definitions"],
      },
      {
        id: "t25-2-d4",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "A solute has Kpc(ether/water) = 5.00 at 25 °C. A mixture is shaken with 150 cm^3 ether and 250 cm^3 water until equilibrium. The total amount of solute present is 0.300 mol. Assuming the solute is un-ionised and the same molecular species in both layers, calculate the amount of solute in each layer at equilibrium.",
        modelAnswerPoints: [
          "Let [solute]_water = c_w mol dm^-3; then [solute]_ether = 5.00 c_w.",
          "Moles in water = c_w × 0.250 = 0.250 c_w; moles in ether = 5c_w × 0.150 = 0.750 c_w.",
          "Total: 0.250 c_w + 0.750 c_w = c_w = 0.300 mol, so c_w = 0.300 mol dm^-3.",
          "Moles water layer = 0.0750 mol; ether layer = 0.225 mol (check sum 0.300).",
        ],
        workedSolution: [
          "Let the equilibrium concentration of the solute in the aqueous phase be c_w mol dm^-3; then, because Kpc(ether/water) is defined as [solute]_ether / [solute]_water = 5.00, the concentration in the ether layer must be 5.00 c_w mol dm^-3 at equilibrium.",
          "The amount in water is concentration times volume, n_water = c_w × (250/1000) dm^3 = 0.250 c_w mol, while the amount in ether is n_ether = 5.00 c_w × (150/1000) = 0.750 c_w mol, where volumes have been converted to dm^3.",
          "Conservation of the solute gives n_water + n_ether = 0.300 mol, so 0.250 c_w + 0.750 c_w = 1.000 c_w = 0.300, hence c_w = 0.300 mol dm^-3.",
          "Substituting back, n_water = 0.250 × 0.300 = 0.0750 mol and n_ether = 0.750 × 0.300 = 0.225 mol, which sum to 0.300 mol as required and show most solute in the ether layer because of the favourable partition and comparable phase volumes.",
        ],
        commonMistake:
          "Using mole ratio equal to Kpc while ignoring different phase volumes.",
        tags: ["kpc", "calculations", "mass-balance"],
      },
      {
        id: "t25-2-d5",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain how the relative polarities of a molecular solute and of two immiscible solvents influence the numerical value of Kpc for that solute between those solvents at a fixed temperature.",
        modelAnswerPoints: [
          "Kpc reflects equilibrium distribution; stronger solute-solvent interactions raise concentration in that phase.",
          "Polar solutes tend to favour polar solvents (e.g. water) by hydrogen bonding / dipole interactions.",
          "Non-polar solutes tend to favour non-polar organic solvents by London forces / weaker polar mismatch.",
          "Changing either solvent changes interaction strengths, so Kpc is not a universal constant for the solute alone.",
        ],
        workedSolution: [
          "At equilibrium the solute distributes so that its chemical potential is equal in both liquid phases, which in practice means that the concentrations reflect the balance of intermolecular attractions between solute and each solvent versus solvent-solvent interactions in the bulk liquids.",
          "A polar solute can engage in strong dipole-dipole or hydrogen-bonding interactions with a polar solvent such as water, which tends to raise its aqueous concentration relative to a non-polar solvent, whereas a non-polar solute interacts more favourably through dispersion forces with a non-polar organic phase, which tends to raise its concentration there.",
          "Therefore the numerical value of Kpc for a given solute depends on the specific solvent pair, because each new solvent changes how strongly the solute is solvated in each phase, shifting the equilibrium concentration ratio even though the solute itself is unchanged chemically.",
          "In examination answers this should be phrased as relative strengths of solute-solvent attractions in the two phases, not merely as the slogan 'like dissolves like' without linking those attractions to the equilibrium concentrations that define Kpc.",
        ],
        commonMistake:
          "Claiming Kpc depends only on the solute, or that polarity always increases Kpc without stating which solvent is in the numerator.",
        tags: ["kpc", "polarity", "explanations"],
      },
      {
        id: "t25-2-d6",
        noteId: "t25-2",
        kind: "mcq",
        difficulty: 2,
        stem: "A non-polar hydrocarbon solute is equilibrated between hexane and water at 25 °C. At equilibrium, in which phase is the solute concentration typically higher?",
        options: [
          { id: "A", text: "Water, because water is denser." },
          { id: "B", text: "Hexane, because dispersion interactions match the non-polar solute better than water." },
          { id: "C", text: "Equal in both phases for any solute." },
          { id: "D", text: "Water, because hexane cannot dissolve hydrocarbons." },
        ],
        correctOptionId: "B",
        explanation:
          "Non-polar solutes are usually solvated more strongly by non-polar solvents, so hexane often holds a higher equilibrium concentration than water.",
        distractorRationale: {
          A: "Density does not determine partition; intermolecular interactions do.",
          C: "Equal concentrations would imply Kpc ≈ 1, which is not generally true.",
          D: "Hexane is a typical non-polar solvent for hydrocarbons; the premise is wrong.",
        },
        tags: ["kpc", "polarity"],
      },
      {
        id: "t25-2-d7",
        noteId: "t25-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which statement about using partition coefficients in calculations is always correct for a neutral molecular solute at equilibrium?",
        options: [
          { id: "A", text: "Kpc equals the ratio of total moles in solvent 1 to total moles in solvent 2, even if volumes differ." },
          { id: "B", text: "Kpc equals the ratio of equilibrium concentrations in the stated solvent order, with the same concentration units in numerator and denominator." },
          { id: "C", text: "Kpc is independent of temperature once concentrations are measured." },
          { id: "D", text: "Kpc must be greater than 1 for extraction into an organic solvent to work." },
        ],
        correctOptionId: "B",
        explanation:
          "By definition Kpc is built from equilibrium concentrations in the specified order; mole ratios need volumes to convert to concentrations.",
        distractorRationale: {
          A: "Mole ratio differs from concentration ratio when phase volumes differ.",
          C: "Partition equilibria are temperature-dependent.",
          D: "Extraction can still occur if Kpc < 1 but the organic phase is chosen as denominator; efficiency depends on Kpc magnitude and volumes, not only Kpc > 1 in one arbitrary order.",
        },
        tags: ["kpc", "definitions"],
      },
      {
        id: "t25-2-d8",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Iodine equilibrates between tetrachloromethane and water at 25 °C with Kpc(CCl4/water) = 85.0 for I2 as the same diatomic species in both layers. The aqueous layer at equilibrium has [I2] = 2.00 × 10^-4 mol dm^-3. Calculate [I2] in the CCl4 layer.",
        modelAnswerPoints: [
          "Kpc = [I2]_CCl4 / [I2]_water = 85.0.",
          "[I2]_CCl4 = 85.0 × 2.00 × 10^-4 = 1.70 × 10^-2 mol dm^-3.",
        ],
        workedSolution: [
          "The partition coefficient is given in the order carbon tetrachloromethane over water, so at equilibrium Kpc(CCl4/water) = [I2] in the CCl4 phase divided by [I2] in the aqueous phase for molecular iodine present in the same form in both immiscible solvents.",
          "Rearranging gives [I2]_CCl4 = Kpc × [I2]_water = 85.0 × 2.00 × 10^-4 mol dm^-3.",
          "Multiplying, 85.0 × 2.00 × 10^-4 = 170 × 10^-4 = 1.70 × 10^-2 mol dm^-3, which shows iodine is heavily concentrated into the non-polar organic layer under these conditions.",
        ],
        commonMistake:
          "Dividing by Kpc instead of multiplying, or treating Kpc as moles ratio.",
        tags: ["kpc", "calculations", "partition"],
      },
      {
        id: "t25-2-d9",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Explain why carrying out several successive extractions of an aqueous solution with separate small portions of an immiscible organic solvent can remove more solute from the water than a single extraction using the same total volume of that organic solvent.",
        modelAnswerPoints: [
          "After each extraction, solute redistributes according to Kpc between fresh organic and remaining aqueous phase.",
          "Each step removes a fraction of solute still in water, lowering aqueous concentration repeatedly.",
          "Fresh solvent each time maintains a driving force for further transfer; one batch reaches one equilibrium partition only.",
        ],
        workedSolution: [
          "When a fixed total volume of organic solvent is split into several portions and each portion is shaken separately with the aqueous phase, the system is brought to partition equilibrium multiple times in sequence, and after each separation the aqueous layer contains less total solute than before that step.",
          "Because Kpc fixes the ratio of equilibrium concentrations between the two phases, lowering the amount remaining in water after one extraction means the next fresh organic portion sees a smaller aqueous concentration but still starts with zero solute in the new organic layer, which maintains a strong concentration gradient favouring further transfer out of the water.",
          "By contrast, one extraction with the entire organic volume at once establishes only a single equilibrium in which a substantial fraction of solute may lawfully remain in water if Kpc and the volume ratio are modest, so the staged process usually leaves less solute in the water for the same total organic solvent used.",
        ],
        commonMistake:
          "Claiming multiple extractions violate mass balance or change Kpc itself.",
        tags: ["kpc", "extraction", "explanations"],
      },
      {
        id: "t25-2-d10",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem: "The same moderately non-polar organic solute is compared at 25 °C in two systems: (i) hexane / water and (ii) ethanol / water, with Kpc defined as [solute]_organic / [solute]_water in each case. Predict whether Kpc(hexane/water) is likely greater or smaller than Kpc(ethanol/water), and justify your answer using polarity and intermolecular attraction ideas.",
        modelAnswerPoints: [
          "Expect Kpc(hexane/water) > Kpc(ethanol/water) for a non-polar solute.",
          "Hexane is non-polar; ethanol is polar (hydrogen bonding).",
          "Non-polar solute interacts more strongly with hexane than with water; ethanol competes more effectively with water for the solute than hexane does relative to polar solvation in water.",
        ],
        workedSolution: [
          "For a moderately non-polar solute, water is a relatively poor solvent because extensive hydrogen bonding in water is poorly replaced by interactions with the solute, whereas a non-polar alkane solvent such as hexane solvates the solute primarily by dispersion forces that match the solute's own low polarity.",
          "Ethanol, although organic, is significantly polar and can hydrogen-bond, so it interacts more favourably with both water-like structures and polar parts of the solute than hexane does, which means the solute's equilibrium concentration in ethanol is usually higher than in hexane for a given aqueous concentration.",
          "Since Kpc is defined as [solute]_organic / [solute]_water in each comparison, a higher preference for hexane over water than for ethanol over water implies a larger concentration ratio in the hexane case, so Kpc(hexane/water) is expected to be greater than Kpc(ethanol/water) for this class of solute.",
          "The argument is therefore framed entirely in terms of relative strengths of solute-solvent attractions in each phase pair, which is what the syllabus means by relating Kpc values to polarities of solute and solvents.",
        ],
        commonMistake:
          "Saying ethanol is 'organic' therefore always extracts better than hexane, without comparing polarities.",
        tags: ["kpc", "polarity", "prediction"],
      },
    ],
    flashcards: [
      {
        id: "t25-2-f1",
        noteId: "t25-2",
        difficulty: 1,
        front: "Define partition coefficient Kpc for two immiscible solvents.",
        back: "Equilibrium ratio of solute concentrations in the two solvents at fixed T, in the stated solvent order; same species in both phases.",
        examPhrasing: "State what is meant by partition coefficient, Kpc.",
        tags: ["kpc", "definitions"],
      },
      {
        id: "t25-2-f2",
        noteId: "t25-2",
        difficulty: 1,
        front: "Why must solvent order be stated in Kpc?",
        back: "Kpc(org/water) is the reciprocal of Kpc(water/org); reversing order inverts the numerical value.",
        examPhrasing: "Explain why Kpc must refer to a defined solvent order.",
        tags: ["kpc", "definitions"],
      },
      {
        id: "t25-2-f3",
        noteId: "t25-2",
        difficulty: 2,
        front: "Kpc(A/B) = 3.0. What is [solute] in A if [solute] in B = 0.020 mol dm^-3?",
        back: "[solute]_A = 3.0 × 0.020 = 0.060 mol dm^-3.",
        examPhrasing: "Calculate concentration in phase A given Kpc(A/B) and concentration in B.",
        tags: ["kpc", "calculations"],
      },
      {
        id: "t25-2-f4",
        noteId: "t25-2",
        difficulty: 2,
        front: "Why cannot you set Kpc equal to n1/n2 if layer volumes differ?",
        back: "Concentration is amount per volume; different volumes mean mole ratio ≠ concentration ratio.",
        examPhrasing: "Identify the error in using a mole ratio as Kpc when volumes differ.",
        tags: ["kpc", "errors"],
      },
      {
        id: "t25-2-f5",
        noteId: "t25-2",
        difficulty: 3,
        front: "Polar solute between hexane and water — which layer usually has higher [solute]?",
        back: "Usually water, because polar solute-solvent interactions (H-bonding/dipole) are stronger there.",
        examPhrasing: "Predict distribution of a polar solute between water and hexane.",
        tags: ["kpc", "polarity"],
      },
      {
        id: "t25-2-f6",
        noteId: "t25-2",
        difficulty: 3,
        front: "What does a very large Kpc(org/water) imply for extraction?",
        back: "Solute strongly prefers the organic phase, so extraction from water into that solvent is efficient at equilibrium.",
        examPhrasing: "Interpret a large partition coefficient into an organic solvent.",
        tags: ["kpc", "extraction"],
      },
      {
        id: "t25-2-f7",
        noteId: "t25-2",
        difficulty: 4,
        front: "Why is Kpc not the same for all solvent pairs for one solute?",
        back: "Different solvents give different solvation strengths, so the equilibrium concentration ratio changes.",
        examPhrasing: "Explain why Kpc depends on the solvents chosen.",
        tags: ["kpc", "polarity"],
      },
      {
        id: "t25-2-f8",
        noteId: "t25-2",
        difficulty: 4,
        front: "Advantage of several small extractions vs one large one (same total organic volume)?",
        back: "Repeated equilibria with fresh solvent remove more solute from water than a single partition step.",
        examPhrasing: "Explain the benefit of repeated solvent extraction.",
        tags: ["kpc", "extraction"],
      },
      {
        id: "t25-2-f9",
        noteId: "t25-2",
        difficulty: 5,
        front: "If Kpc(org/water) ≈ 1, what does that say about extraction efficiency?",
        back: "Similar concentrations in both phases at equilibrium, so separation by one equilibrium partition is inefficient.",
        examPhrasing: "Comment on extraction when Kpc is close to 1.",
        tags: ["kpc", "extraction"],
      },
      {
        id: "t25-2-f10",
        noteId: "t25-2",
        difficulty: 5,
        front: "Condition on solute for simple Kpc use in 9701 style?",
        back: "Same molecular form in both phases; no ionisation or reaction that changes species between layers.",
        examPhrasing: "State the limitation on the solute when applying a partition coefficient.",
        tags: ["kpc", "definitions"],
      },
    ],
  },
};
