import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 11 — Group 17 (halogens). Crosswalk to
 * `data/syllabus/chemistry-9701-learning-outcomes.md` (each § bullet hit by ≥1 drill id):
 *
 * **t11-1 (11.1)** — Colours + volatility trend → d1, d4, d9; bond strength in X2 → d2, d5, d8;
 * id–id forces vs volatility → d3, d6, d7, d10.
 *
 * **t11-2 (11.2)** — Oxidising power of elements → d1, d4, d6, d9; reactions with hydrogen + reactivity → d2, d5, d8;
 * thermal stability of HX + bond strengths → d3, d7, d10.
 *
 * **t11-3 (11.3)** — Reducing power of halide ions → d1, d5, d9; Ag+(aq) then NH3(aq) → d2, d4, d6, d10;
 * conc. H2SO4 + halides (equations) → d3, d7, d8.
 *
 * **t11-4 (11.4)** — Cl2 + cold/hot NaOH, oxidation numbers, disproportionation → d1, d2, d3, d5, d7, d10;
 * water purification, HOCl / ClO^- → d4, d6, d8, d9.
 */
export const CHEMISTRY_TOPIC11_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t11-1": {
    noteId: "t11-1",
    drills: [
      {
        id: "t11-1-d1",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "State the colours of chlorine, bromine and iodine at room temperature under ordinary laboratory conditions (as elements), and describe the trend in volatility from chlorine to iodine.",
        modelAnswerPoints: [
          "Chlorine, Cl2, is a green gas; bromine, Br2, is a red-brown volatile liquid; iodine, I2, is a grey-black solid that sublimes to give a purple vapour.",
          "Volatility decreases from chlorine to iodine: Cl2 is the most volatile (lowest boiling point among the three), then Br2, then I2 is the least volatile (highest boiling point / least tendency to escape as vapour at a given temperature).",
        ],
        workedSolution: [
          "Under ordinary laboratory conditions, chlorine exists as a diatomic gas with a characteristic green colour, bromine is a dense red-brown liquid that readily forms an orange-brown vapour above the liquid, and iodine is a dark grey-black solid that produces a striking purple vapour when warmed because it sublimes rather than boiling like a typical molecular liquid.",
          "Volatility is reflected in how easily the element enters the gas phase at a given temperature, and for chlorine, bromine and iodine the boiling points increase down the group, so chlorine is the most volatile of the three, bromine is intermediate, and iodine is the least volatile, which matches the progression from gas to liquid to solid at room temperature for these three halogens.",
        ],
        commonMistake:
          "Reversing the volatility order or giving bromine as a gas rather than a liquid at room temperature.",
        tags: ["halogens", "physical-properties", "colours", "volatility"],
      },
      {
        id: "t11-1-d2",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Describe and explain the trend in the bond strength of the halogen molecules Cl2, Br2 and I2.",
        modelAnswerPoints: [
          "Bond strength decreases from Cl2 to Br2 to I2 (the Cl–Cl bond is strongest; the I–I bond is weakest among the three).",
          "Halogen atoms become larger down the group, so the bonding pair in X2 lies farther from each nucleus and orbital overlap between the two atoms is less effective.",
          "Weaker overlap gives a longer, weaker covalent bond in I2 than in Cl2.",
        ],
        workedSolution: [
          "For the diatomic molecules Cl2, Br2 and I2, the covalent bond joining the two halogen atoms becomes progressively weaker on moving from chlorine to bromine to iodine, which is the same order as saying the bond dissociation energy is highest for chlorine and lowest for iodine in this set.",
          "Each step down the group adds another principal quantum shell, so the atomic radius increases and the outer p orbitals that overlap to form the sigma bond are more diffuse and farther apart.",
          "Because the bonding electron pair is shared between orbitals that overlap less effectively for larger atoms, the X–X bond length increases and the bond becomes easier to break, which is exactly what is meant by decreasing bond strength from Cl2 to I2.",
        ],
        commonMistake:
          "Claiming bond strength increases down the group, or confusing bond strength within a molecule with strength of intermolecular forces between molecules.",
        tags: ["bond-strength", "halogens", "trends"],
      },
      {
        id: "t11-1-d3",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Interpret the trend in volatility of Cl2, Br2 and I2 in terms of instantaneous dipole–induced dipole (id–id) forces between molecules.",
        modelAnswerPoints: [
          "All three elements are non-polar molecules, yet they have boiling points because temporary dipoles arise and induce dipoles in neighbours (id–id / London forces).",
          "More electrons and larger electron clouds make polarisability greater from Cl2 to I2.",
          "Stronger id–id attraction for heavier, more polarisable molecules means more energy is needed to separate molecules into the gas phase, so volatility decreases from Cl2 to I2.",
        ],
        workedSolution: [
          "Although each X2 molecule is non-polar in the permanent sense, the electron cloud is in constant motion, so at any instant there can be an uneven distribution of charge that creates a temporary instantaneous dipole in one molecule.",
          "That temporary dipole can polarise the electron cloud of a neighbouring molecule, producing an induced dipole, and the resulting attraction between the molecules is the instantaneous dipole–induced dipole interaction that is responsible for condensation of the halogens in the first place.",
          "From Cl2 to I2 the number of electrons per molecule increases and the electron cloud is larger and more easily distorted, so polarisability increases down the set and the id–id attractions between molecules become stronger for a given separation.",
          "Stronger intermolecular attractions mean more thermal energy is required to overcome them and boil the liquid or sublime the solid, which is why iodine is much less volatile than chlorine even though the covalent bond inside each I2 molecule is weaker than the bond inside Cl2.",
        ],
        commonMistake:
          "Explaining boiling points only by stronger X–X bonds down the group; boiling involves overcoming forces between molecules, not breaking the covalent bonds inside X2.",
        tags: ["id-id", "volatility", "intermolecular-forces"],
      },
      {
        id: "t11-1-d4",
        noteId: "t11-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which statement about bond strength in the halogen molecules Cl2, Br2 and I2 is correct?",
        options: [
          { id: "A", text: "The I–I bond is stronger than the Cl–Cl bond." },
          { id: "B", text: "The Cl–Cl bond is stronger than the I–I bond." },
          { id: "C", text: "All three molecules have the same bond strength because each is X–X." },
          { id: "D", text: "The Br–Br bond is the weakest of the three." },
        ],
        correctOptionId: "B",
        explanation:
          "Smaller atoms give better orbital overlap, so the Cl–Cl bond is the strongest; bond strength decreases Cl2 > Br2 > I2.",
        distractorRationale: {
          A: "Iodine atoms are larger with poorer overlap, so the I–I bond is weaker, not stronger, than Cl–Cl.",
          C: "Atomic size and overlap change from Cl to Br to I, so bond dissociation energies are not equal.",
          D: "The weakest of the three is I–I, not Br–Br.",
        },
        tags: ["bond-strength", "mcq"],
      },
      {
        id: "t11-1-d5",
        noteId: "t11-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which sequence shows decreasing volatility (most volatile first) for Cl2, Br2 and I2?",
        options: [
          { id: "A", text: "I2 > Br2 > Cl2" },
          { id: "B", text: "Cl2 > Br2 > I2" },
          { id: "C", text: "Br2 > Cl2 > I2" },
          { id: "D", text: "Cl2 > I2 > Br2" },
        ],
        correctOptionId: "B",
        explanation:
          "Boiling points rise Cl2 < Br2 < I2, so volatility is highest for chlorine and lowest for iodine among these three.",
        distractorRationale: {
          A: "That order would correspond to increasing volatility down the group, which is the opposite of the observed physical states and boiling points.",
          C: "Chlorine is more volatile than bromine, so bromine cannot be placed first in a most-to-least volatile list.",
          D: "Iodine is less volatile than bromine, not intermediate between chlorine and bromine.",
        },
        tags: ["volatility", "mcq"],
      },
      {
        id: "t11-1-d6",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain why instantaneous dipole–induced dipole attractions are stronger between I2 molecules than between Cl2 molecules, even though the covalent bond inside an I2 molecule is weaker than inside Cl2.",
        modelAnswerPoints: [
          "Boiling or sublimation requires overcoming attractions between separate X2 molecules, not breaking the intramolecular X–X bond.",
          "I2 has more electrons and a larger, more polarisable electron cloud than Cl2.",
          "Greater polarisability gives stronger id–id forces, so more energy is needed to vaporise I2, making it less volatile.",
        ],
        workedSolution: [
          "When iodine sublimes or bromine boils, the covalent bonds within each X2 unit largely remain intact; what changes is the separation between whole molecules, so the energy barrier is set by the strength of intermolecular attractions rather than by the intramolecular bond dissociation energy.",
          "An iodine molecule contains many more electrons than a chlorine molecule and those electrons occupy shells farther from the nuclei, which makes the electron cloud of I2 easier to distort when a neighbouring molecule presents a temporary dipole.",
          "That greater polarisability means the instantaneous dipole–induced dipole attractions between iodine molecules are stronger than those between chlorine molecules at comparable distances, so a higher temperature is needed to overcome them and iodine is therefore much less volatile than chlorine despite having a weaker X–X bond inside each molecule.",
        ],
        commonMistake:
          "Arguing that weaker I–I bonds automatically mean lower boiling points, without separating intermolecular id–id effects from intramolecular bond breaking.",
        tags: ["id-id", "volatility", "explanations"],
      },
      {
        id: "t11-1-d7",
        noteId: "t11-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which colour is correctly paired with bromine, Br2, at room temperature?",
        options: [
          { id: "A", text: "Pale green gas" },
          { id: "B", text: "Red-brown liquid" },
          { id: "C", text: "Grey-black solid" },
          { id: "D", text: "Colourless gas" },
        ],
        correctOptionId: "B",
        explanation:
          "Bromine is a volatile red-brown liquid at room temperature; chlorine is green gas and iodine is a dark solid.",
        distractorRationale: {
          A: "That description matches chlorine gas, not bromine.",
          C: "That description matches solid iodine, not bromine.",
          D: "Elemental bromine is deeply coloured, not colourless.",
        },
        tags: ["colours", "mcq"],
      },
      {
        id: "t11-1-d8",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Relate the trend in bond strength of Cl2, Br2 and I2 to atomic radius and bond length, and state how this trend differs from the trend in volatility of the elements.",
        modelAnswerPoints: [
          "Bond strength decreases Cl2 > Br2 > I2 as atoms get larger and the X–X bond becomes longer with less effective overlap.",
          "Volatility also decreases Cl2 > Br2 > I2, but the underlying cause for low volatility of I2 is strong id–id forces between molecules, not strong covalent bonds within each I2.",
          "The two trends run parallel in direction for these three elements, but they rest on different microscopic ideas (intramolecular overlap vs intermolecular polarisability).",
        ],
        workedSolution: [
          "As halogen atoms become larger from chlorine to iodine, the distance between nuclei in the diatomic molecule increases and the bonding orbital overlap becomes less effective, so the covalent X–X bond becomes longer and weaker in the order Cl2 strongest, then Br2, then I2 weakest.",
          "Volatility likewise falls from chlorine to iodine because boiling or sublimation temperatures rise, but the dominant reason iodine is involatile compared with chlorine is that id–id attractions between I2 molecules are much stronger than between Cl2 molecules, not that the bonds inside each molecule are stronger.",
          "Thus both bond strength within X2 and ease of vaporising the element change in the same direction down this trio, but examiners expect candidates to keep separate the language of intramolecular bond weakening and intermolecular attraction strengthening when they explain physical properties.",
        ],
        commonMistake:
          "Using a single explanation (only bond strength or only id–id) for both bond dissociation and boiling point without distinguishing the two scales of interaction.",
        tags: ["bond-strength", "volatility", "concepts"],
      },
      {
        id: "t11-1-d9",
        noteId: "t11-1",
        kind: "mcq",
        difficulty: 1,
        stem: "At room temperature, which halogen is correctly described as a grey-black solid that produces a purple vapour when warmed gently?",
        options: [
          { id: "A", text: "Chlorine" },
          { id: "B", text: "Bromine" },
          { id: "C", text: "Iodine" },
          { id: "D", text: "Astatine" },
        ],
        correctOptionId: "C",
        explanation:
          "Iodine is the familiar dark solid with purple vapour on sublimation; chlorine is a green gas and bromine a red-brown liquid at rtp.",
        distractorRationale: {
          A: "Chlorine is a green gas at room temperature, not a grey-black solid.",
          B: "Bromine is a liquid at room temperature with red-brown vapour, not a grey-black solid with purple vapour.",
          D: "Astatine is not part of the 9701 property set for Cl2, Br2 and I2 in this subsection.",
        },
        tags: ["colours", "iodine", "mcq"],
      },
      {
        id: "t11-1-d10",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Give a coherent account of why chlorine is more volatile than iodine, explicitly using both instantaneous dipole–induced dipole forces and the relative sizes and polarisabilities of Cl2 and I2 molecules.",
        modelAnswerPoints: [
          "Both Cl2 and I2 are non-polar diatomic molecules held in the condensed phase by id–id attractions arising from temporary fluctuating dipoles.",
          "I2 has a larger electron cloud that is more polarisable than that of Cl2.",
          "Stronger id–id attractions between I2 molecules require more thermal energy to separate them into the vapour, so I2 is less volatile.",
          "Reference to lower boiling point / more ready vaporisation for Cl2 completes the link to volatility.",
        ],
        workedSolution: [
          "Chlorine and iodine each consist of non-polar X2 molecules, yet neither would liquefy if there were no forces between molecules, and the type of attraction syllabus candidates are expected to cite for these halogens is instantaneous dipole–induced dipole interaction between neighbouring molecules.",
          "An iodine molecule contains far more electrons than a chlorine molecule and those electrons occupy shells at greater average distance from the nuclei, which makes the whole electron cloud of I2 more polarisable: a temporary dipole on one molecule induces a larger complementary dipole on its neighbour than would occur between two chlorine molecules.",
          "Consequently the total id–id attraction between iodine molecules in the solid or liquid is stronger than that between chlorine molecules, so more heat must be supplied to pull iodine molecules apart into the gas phase.",
          "Chlorine therefore boils at a much lower temperature than iodine sublimes and is described as the more volatile element, even though the covalent bond holding each pair of iodine atoms together is weaker than the bond in Cl2, because volatility in this context is controlled primarily by the intermolecular scale of interaction rather than by the intramolecular bond strength alone.",
        ],
        commonMistake:
          "Stating only that I2 is heavier without linking mass to electron count, polarisability and strength of id–id forces.",
        tags: ["volatility", "id-id", "integrated"],
      },
    ],
    flashcards: [
      {
        id: "t11-1-f1",
        noteId: "t11-1",
        difficulty: 1,
        front: "Colour of Cl2, Br2 and I2 at rtp (typical lab descriptions)?",
        back: "Cl2 green gas; Br2 red-brown liquid; I2 grey-black solid (purple vapour when warmed).",
        examPhrasing: "Describe the colours of chlorine, bromine and iodine.",
        tags: ["colours", "halogens"],
      },
      {
        id: "t11-1-f2",
        noteId: "t11-1",
        difficulty: 1,
        front: "Trend in volatility Cl2 to I2?",
        back: "Volatility decreases: Cl2 most volatile, then Br2, I2 least volatile (higher bp / sublimation temperature).",
        examPhrasing: "Describe the trend in volatility of chlorine, bromine and iodine.",
        tags: ["volatility"],
      },
      {
        id: "t11-1-f3",
        noteId: "t11-1",
        difficulty: 2,
        front: "Trend in X–X bond strength Cl2, Br2, I2?",
        back: "Strongest Cl–Cl; weakest I–I — larger atoms, poorer overlap, longer weaker bonds.",
        examPhrasing: "Explain the trend in bond strength of the halogen molecules.",
        tags: ["bond-strength"],
      },
      {
        id: "t11-1-f4",
        noteId: "t11-1",
        difficulty: 2,
        front: "Why do non-polar halogen molecules attract each other?",
        back: "Temporary dipoles induce dipoles in neighbours — instantaneous dipole–induced dipole (London) forces.",
        examPhrasing: "Interpret volatility in terms of instantaneous dipole–induced dipole forces.",
        tags: ["id-id"],
      },
      {
        id: "t11-1-f5",
        noteId: "t11-1",
        difficulty: 3,
        front: "Why is I2 less volatile than Cl2 if the I–I bond is weaker?",
        back: "Boiling/sublimation breaks intermolecular id–id attractions; I2 is more polarisable so those attractions are stronger than for Cl2.",
        examPhrasing: "Explain boiling points of the halogens using id–id forces.",
        confusionPair: "intra- vs intermolecular",
        tags: ["volatility", "id-id"],
      },
      {
        id: "t11-1-f6",
        noteId: "t11-1",
        difficulty: 3,
        front: "What increases down Cl2, Br2, I2 for intermolecular attractions?",
        back: "Electron count and polarisability of the molecule — stronger id–id forces for I2.",
        examPhrasing: "Relate polarisability to strength of id–id forces between halogen molecules.",
        tags: ["id-id"],
      },
      {
        id: "t11-1-f7",
        noteId: "t11-1",
        difficulty: 4,
        front: "Physical state at rtp: Cl2, Br2, I2?",
        back: "Gas; liquid; solid — matching the volatility / bp trend.",
        examPhrasing: "State the physical states of chlorine, bromine and iodine at room temperature.",
        tags: ["physical-properties"],
      },
      {
        id: "t11-1-f8",
        noteId: "t11-1",
        difficulty: 4,
        front: "Bond length trend in X2 down Cl to I?",
        back: "Bonds get longer as atoms get larger (Cl–Cl shortest, I–I longest in the set).",
        examPhrasing: "Relate atomic radius to bond length in halogen molecules.",
        tags: ["bond-strength"],
      },
      {
        id: "t11-1-f9",
        noteId: "t11-1",
        difficulty: 5,
        front: "Vapour colour above solid/liquid iodine vs bromine?",
        back: "Iodine: purple vapour; bromine: orange-brown vapour.",
        examPhrasing: "Describe observations when bromine and iodine vaporise.",
        confusionPair: "I2 vs Br2 vapour colour",
        tags: ["colours"],
      },
      {
        id: "t11-1-f10",
        noteId: "t11-1",
        difficulty: 5,
        front: "One sentence: why does bp increase Cl2 to I2?",
        back: "Stronger id–id attractions between more polarisable molecules need more energy to reach the gas phase.",
        examPhrasing: "Explain the increase in boiling temperature down Cl2, Br2, I2.",
        tags: ["volatility", "id-id"],
      },
    ],
  },
  "t11-2": {
    noteId: "t11-2",
    drills: [
      {
        id: "t11-2-d1",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Describe the relative reactivity of the halogens F2, Cl2, Br2 and I2 as oxidising agents, and state what is being oxidised or reduced when, for example, chlorine oxidises bromide ions in solution.",
        modelAnswerPoints: [
          "Oxidising strength decreases in the order F2 > Cl2 > Br2 > I2 (fluorine is the strongest oxidising agent among the halogens; iodine is the weakest in this series).",
          "An oxidising agent gains electrons and is itself reduced; the species oxidised loses electrons.",
          "When Cl2 oxidises Br–, chlorine atoms gain electrons (Cl2 reduced to Cl–) and bromide is oxidised to Br2.",
        ],
        workedSolution: [
          "As oxidising agents, the halogen elements are compared by their tendency to gain electrons and form halide ions, and the standard pattern taught is that reactivity falls from fluorine through chlorine and bromine to iodine, so fluorine is the strongest oxidising agent and iodine the weakest among F2, Cl2, Br2 and I2.",
          "In any redox act described as oxidation of a reductant by a halogen, the halogen molecules are the oxidising agents because each halogen atom can accept an electron to become X–, which means the halogen element is reduced while whatever donates electrons is oxidised.",
          "A concrete illustration is chlorine reacting with aqueous bromide ions: each chlorine atom in Cl2 can be reduced to chloride, while bromide ions give up electrons to form bromine, so bromide is oxidised, chlorine is reduced, and the relative positions of Cl2 and Br2 on the oxidising scale explain why this displacement is spontaneous under standard conditions.",
        ],
        commonMistake:
          "Reversing the oxidising strength order or labelling the halogen as oxidised when it gains electrons.",
        tags: ["oxidising-agents", "halogens", "redox"],
      },
      {
        id: "t11-2-d2",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe how fluorine, chlorine and bromine react with hydrogen, including balanced equations with state symbols where a reaction occurs readily, and explain their relative reactivity in these reactions.",
        modelAnswerPoints: [
          "F2 reacts explosively with H2 even in the dark: H2(g) + F2(g) -> 2HF(g).",
          "Cl2 reacts with H2 in a photochemical radical chain on exposure to sunlight (or explodes with an electric spark): H2(g) + Cl2(g) -> 2HCl(g).",
          "Br2 reacts with H2 only on heating with a catalyst (Pt): H2(g) + Br2(g) -> 2HBr(g).",
          "Reactivity falls F2 > Cl2 > Br2 because bond strength in H–X decreases HF > HCl > HBr and the H–H bond must be broken while the halogen bond becomes weaker down the halogens, but the dominant syllabus comparison is that fluorine removes the kinetic barrier most effectively and iodine does not combine directly with hydrogen in the same way under normal conditions.",
        ],
        workedSolution: [
          "Fluorine combines with hydrogen extremely vigorously, and the reaction can be represented as H2(g) + F2(g) -> 2HF(g), where both reactants are gases and hydrogen fluoride is also gaseous under typical descriptions, reflecting that almost no activation energy is needed once the gases mix.",
          "Chlorine reacts with hydrogen in daylight by a free-radical chain mechanism initiated by light breaking Cl2 into atoms, and the overall equation is again H2(g) + Cl2(g) -> 2HCl(g), but the reaction is much less spontaneous in the dark than fluorine plus hydrogen, which shows chlorine is a weaker oxidising agent than fluorine toward hydrogen.",
          "Bromine combines with hydrogen only when the mixture is heated and a catalyst such as platinum is present, giving H2(g) + Br2(g) -> 2HBr(g), which demonstrates a further drop in reactivity compared with chlorine because more severe conditions are required to achieve a useful rate.",
          "The relative reactivity sequence therefore matches the oxidising power trend: fluorine pulls electron density from hydrogen most aggressively, chlorine does so under photochemical initiation, bromine needs thermal activation and catalysis, and the explanation expected in outline is that the H–X bond formed is very strong for HF while the X–X bond becomes weaker down the group but the increasing size of the halogen atom changes how effectively the halogen can attack H2 under mild conditions, with fluorine standing out as uniquely violent.",
        ],
        commonMistake:
          "Claiming Br2 reacts rapidly with H2 at room temperature without light or heat, or omitting state symbols when the question asks for them.",
        tags: ["hydrogen-halides", "equations", "reactivity"],
      },
      {
        id: "t11-2-d3",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Describe the relative thermal stabilities of the hydrogen halides HF, HCl, HBr and HI, and explain the trend in terms of bond strengths.",
        modelAnswerPoints: [
          "Thermal stability decreases HF > HCl > HBr > HI (HI is the least stable thermally; HF the most stable).",
          "On heating, HI decomposes most readily to H2 and I2; HBr similarly at higher temperature; HCl needs very high temperature in typical teaching contexts.",
          "The H–X bond becomes longer and weaker from HF to HI, so less energy is needed to break it homolytically during thermal decomposition.",
        ],
        workedSolution: [
          "When hydrogen halides are compared for how easily they decompose on heating to regenerate hydrogen and the halogen, hydrogen iodide is the least thermally stable, hydrogen bromide is more stable than HI but less stable than hydrogen chloride, and hydrogen fluoride is the most resistant to thermal breakdown in this series.",
          "The qualitative decomposition picture is that HI can be made to give H2 and I2 at moderate laboratory heating, HBr requires more vigorous conditions than HI, and HCl is stable enough that special very hot conditions are needed before significant decomposition is observed, which matches the bond-strength argument rather than a random ordering.",
          "The explanation is that the covalent bond between hydrogen and the halogen becomes progressively longer and weaker as the halogen atom enlarges from fluorine to iodine, because overlap between the small hydrogen 1s orbital and the halogen bonding orbital is best for fluorine and poorest for iodine.",
          "Weaker H–X bonds mean less energy must be supplied to break them during pyrolysis, so thermal stability falls from HF to HI even though the volatility of the pure hydrogen halides has its own complications with hydrogen bonding in HF.",
        ],
        commonMistake:
          "Reversing the thermal stability order or confusing ease of thermal decomposition with acid strength in water.",
        tags: ["hydrogen-halides", "thermal-stability", "bond-strength"],
      },
      {
        id: "t11-2-d4",
        noteId: "t11-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which halogen is the strongest oxidising agent among F2, Cl2, Br2 and I2?",
        options: [
          { id: "A", text: "I2" },
          { id: "B", text: "Br2" },
          { id: "C", text: "Cl2" },
          { id: "D", text: "F2" },
        ],
        correctOptionId: "D",
        explanation:
          "Fluorine has the greatest tendency to gain electrons to form F–, so F2 is the strongest oxidising agent in the series.",
        distractorRationale: {
          A: "Iodine is the weakest oxidising agent of the four molecular halogens listed.",
          B: "Bromine is a weaker oxidising agent than both chlorine and fluorine.",
          C: "Chlorine is very oxidising but still weaker than fluorine.",
        },
        tags: ["oxidising-agents", "mcq"],
      },
      {
        id: "t11-2-d5",
        noteId: "t11-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which hydrogen halide is the least thermally stable (most readily decomposed by heat to H2 + X2)?",
        options: [
          { id: "A", text: "HF" },
          { id: "B", text: "HCl" },
          { id: "C", text: "HBr" },
          { id: "D", text: "HI" },
        ],
        correctOptionId: "D",
        explanation:
          "The H–I bond is the weakest; HI therefore decomposes more easily on heating than HF, HCl or HBr.",
        distractorRationale: {
          A: "HF has the strongest H–X bond in the series and is the most thermally stable hydrogen halide.",
          B: "HCl is more thermally stable than HBr and HI.",
          C: "HBr is more stable than HI but less stable than HCl.",
        },
        tags: ["thermal-stability", "mcq"],
      },
      {
        id: "t11-2-d6",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Explain why a mixture of hydrogen and chlorine can remain unchanged in the dark yet react explosively in bright sunlight, with reference to initiation of a chain reaction.",
        modelAnswerPoints: [
          "In the dark there is insufficient energy to break Cl–Cl bonds homolytically to start the reaction.",
          "UV / bright light provides energy to form chlorine radicals from Cl2.",
          "Radicals propagate a chain: Cl· attacks H2, H· attacks Cl2, regenerating radicals until termination.",
        ],
        workedSolution: [
          "Hydrogen and chlorine molecules are stable in the dark at room temperature because the Cl–Cl bond and the H–H bond have substantial dissociation energies, so there is almost no thermal population of chlorine atoms or hydrogen atoms to begin the redox pathway that eventually forms hydrogen chloride.",
          "Bright sunlight contains ultraviolet photons able to break Cl–Cl bonds homolytically, producing chlorine radicals, and those radicals are highly reactive toward H2, generating hydrogen atoms that in turn attack Cl2.",
          "Once a small concentration of radicals exists, propagation steps cycle many times for each initial photon absorption, which is why the overall combination H2(g) + Cl2(g) -> 2HCl(g) can become explosively fast in sunlight even though the same sealed mixture might appear unchanged for long periods in a cupboard.",
        ],
        commonMistake:
          "Saying light 'speeds up molecules' without mentioning homolytic fission of Cl2 and radical chain propagation.",
        tags: ["hydrogen", "chlorine", "photochemistry"],
      },
      {
        id: "t11-2-d7",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Write a balanced equation with state symbols for the reaction of hydrogen with bromine in the presence of a hot platinum catalyst. Explain why this reaction needs more vigorous conditions than the reaction of hydrogen with chlorine under sunlight.",
        modelAnswerPoints: [
          "H2(g) + Br2(g) -> 2HBr(g) (catalyst shown in words or over arrow).",
          "The Br–Br bond is weaker than Cl–Cl but the first propagation step forming HBr from H2 + Br· is endothermic / higher activation barrier compared with the chlorine analogue.",
          "Overall rate is much slower without heat and Pt, so more vigorous conditions are required than for the photochemical H2 + Cl2 reaction.",
        ],
        workedSolution: [
          "When hydrogen gas is passed with bromine vapour over heated platinum, the metal surface adsorbs both gases and lowers the activation energy for bond breaking and making enough that the overall transformation can be written as H2(g) + Br2(g) -> 2HBr(g) with gaseous hydrogen bromide as product.",
          "Compared with the hydrogen–chlorine photochemical reaction, the hydrogen–bromine system has a less favourable first chain step energetically in the gas-phase radical mechanism taught in outline, so spontaneous radical propagation at room temperature in diffuse light is not reliable.",
          "Therefore syllabus comparisons state that bromine reacts with hydrogen only on heating with a catalyst, whereas chlorine reacts with hydrogen in sunlight without needing a metal catalyst, which reflects both the lower oxidising power of bromine than chlorine and the higher barrier to sustaining a fast radical chain for hydrogen bromide formation under mild conditions.",
        ],
        commonMistake:
          "Writing an ionic mechanism for a gas-phase combination that is taught as radical chemistry, or omitting the catalyst when describing bromine.",
        tags: ["hydrogen", "bromine", "equations"],
      },
      {
        id: "t11-2-d8",
        noteId: "t11-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Why does HI have lower thermal stability than HCl?",
        options: [
          { id: "A", text: "The H–I bond is weaker than the H–Cl bond, so HI decomposes more easily on heating." },
          { id: "B", text: "Iodine is more electronegative than chlorine, so HI is less polar." },
          { id: "C", text: "HI molecules have weaker id–id forces than HCl molecules." },
          { id: "D", text: "HI is a weaker acid in water than HCl." },
        ],
        correctOptionId: "A",
        explanation:
          "Thermal decomposition breaks the H–X bond; the H–I bond is longer and weaker than H–Cl, so HI is less stable to heat.",
        distractorRationale: {
          B: "Chlorine is more electronegative than iodine; the question concerns bond strength to thermal decomposition, not electronegativity reversal.",
          C: "Intermolecular forces affect boiling points, not the primary syllabus explanation for thermal cracking of HX to H2 + X2.",
          D: "Acid strength in aqueous solution is a different property from thermal stability of the gaseous hydrogen halide molecule.",
        },
        tags: ["thermal-stability", "mcq"],
      },
      {
        id: "t11-2-d9",
        noteId: "t11-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Aqueous chloride, bromide and iodide are treated separately with chlorine water. Which observation sequence is expected?",
        options: [
          { id: "A", text: "No change with Cl–; orange colour with Br–; brown solution / black solid with I–." },
          { id: "B", text: "Brown with Cl–; no change with Br–; orange with I–." },
          { id: "C", text: "All three give a white precipitate only." },
          { id: "D", text: "Cl– reduces Cl2 to give I2." },
        ],
        correctOptionId: "A",
        explanation:
          "Cl2 oxidises Br– to Br2 (orange) and I– to I2 (brown with CS2 layer / black solid with starch context), but cannot oxidise Cl–.",
        distractorRationale: {
          B: "Chloride cannot be oxidised by chlorine; bromide and iodide are oxidised, not left unchanged in that pattern.",
          C: "Displacement colours appear for Br– and I–; there is no simple 'white precipitate only' pattern for all three with chlorine water alone.",
          D: "Chloride is already the lowest common oxidation state of chlorine in aqueous halide form and is not oxidised to iodine.",
        },
        tags: ["oxidising-agents", "displacement", "mcq"],
      },
      {
        id: "t11-2-d10",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Integrate bond-strength ideas to compare (i) the thermal stability of HCl and HI and (ii) the relative ease of reaction of Cl2 and I2 with hydrogen under similar mild conditions.",
        modelAnswerPoints: [
          "(i) H–Cl bond stronger than H–I, so HI decomposes more readily on heating than HCl.",
          "(ii) Cl2 is a stronger oxidising agent than I2, so Cl2 reacts with H2 under sunlight whereas I2 does not combine directly with H2 under mild conditions in the syllabus picture.",
          "Both comparisons link to decreasing bond strength Cl–Cl vs I–I and H–Cl vs H–I and to the fall in oxidising power down the halogens.",
        ],
        workedSolution: [
          "For thermal stability, hydrogen iodide contains the weakest hydrogen–halogen bond in the hydrogen halide series relevant here, so when heated it more readily splits into hydrogen and iodine than hydrogen chloride does, because the H–Cl bond is shorter and stronger and therefore requires more energy to homolyse in a thermal decomposition sense.",
          "For reaction with hydrogen under mild conditions, chlorine molecules are strong enough oxidising agents that, once radicals are initiated by light, a chain rapidly converts H2 and Cl2 to hydrogen chloride, whereas iodine is such a weak oxidising agent that it does not undergo a comparable direct combination with hydrogen at room temperature in the standard teaching sequence.",
          "Thus bond-strength arguments explain why HI is fragile to heat while HF and HCl resist decomposition better, while oxidising-strength arguments explain why halogen–hydrogen reactivity falls from chlorine toward iodine even though the halogen–halogen bond also weakens down the group, because the rate-limiting steps in forming HX are not identical to simply breaking X2 bonds in isolation.",
        ],
        commonMistake:
          "Using only 'larger atoms' without explicitly naming stronger/weaker H–X bonds and stronger/weaker oxidising ability of X2.",
        tags: ["integrated", "bond-strength", "oxidising-agents"],
      },
    ],
    flashcards: [
      {
        id: "t11-2-f1",
        noteId: "t11-2",
        difficulty: 1,
        front: "Oxidising strength order F2 to I2?",
        back: "F2 > Cl2 > Br2 > I2 — halogens gain electrons more readily at the top of the group.",
        examPhrasing: "Describe the relative reactivity of the halogens as oxidising agents.",
        tags: ["oxidising-agents"],
      },
      {
        id: "t11-2-f2",
        noteId: "t11-2",
        difficulty: 1,
        front: "Equation H2 + Cl2 (sunlight)?",
        back: "H2(g) + Cl2(g) -> 2HCl(g) — photochemical radical chain.",
        examPhrasing: "Describe the reaction of chlorine with hydrogen.",
        tags: ["hydrogen", "equations"],
      },
      {
        id: "t11-2-f3",
        noteId: "t11-2",
        difficulty: 2,
        front: "H2 + F2 conditions?",
        back: "Reacts very vigorously (explosively) even in the dark: H2(g) + F2(g) -> 2HF(g).",
        examPhrasing: "Describe the reaction of fluorine with hydrogen.",
        tags: ["hydrogen", "fluorine"],
      },
      {
        id: "t11-2-f4",
        noteId: "t11-2",
        difficulty: 2,
        front: "H2 + Br2 conditions?",
        back: "Heat + Pt catalyst: H2(g) + Br2(g) -> 2HBr(g).",
        examPhrasing: "Describe the reaction of bromine with hydrogen.",
        tags: ["hydrogen", "bromine"],
      },
      {
        id: "t11-2-f5",
        noteId: "t11-2",
        difficulty: 3,
        front: "Thermal stability order HF … HI?",
        back: "HF most stable; HI least — weaker H–X bond lower down.",
        examPhrasing: "Describe the relative thermal stabilities of the hydrogen halides.",
        tags: ["thermal-stability"],
      },
      {
        id: "t11-2-f6",
        noteId: "t11-2",
        difficulty: 3,
        front: "Why does HI decompose more easily than HCl on heating?",
        back: "H–I is longer and weaker than H–Cl, so less energy breaks the bond to form H2 + I2.",
        examPhrasing: "Explain thermal stability of hydrogen halides in terms of bond strengths.",
        tags: ["thermal-stability", "bond-strength"],
      },
      {
        id: "t11-2-f7",
        noteId: "t11-2",
        difficulty: 4,
        front: "Why does Cl2 displace Br2 from Br– but not Cl2 from Cl–?",
        back: "Cl2 is a stronger oxidising agent than Br2 but not than itself — cannot oxidise Cl– further under simple displacement conditions.",
        examPhrasing: "Explain displacement reactions using relative oxidising power.",
        confusionPair: "oxidising vs reducing terminology",
        tags: ["oxidising-agents"],
      },
      {
        id: "t11-2-f8",
        noteId: "t11-2",
        difficulty: 4,
        front: "What starts the H2 + Cl2 chain in sunlight?",
        back: "UV photons homolytically break Cl2 to Cl· radicals that attack H2.",
        examPhrasing: "Explain the relative reactivity of chlorine with hydrogen.",
        tags: ["photochemistry"],
      },
      {
        id: "t11-2-f9",
        noteId: "t11-2",
        difficulty: 5,
        front: "Does I2 react directly with H2 under mild conditions?",
        back: "No in the usual syllabus comparison — I2 is too weak an oxidising agent for that convenient direct combination.",
        examPhrasing: "Compare reactivity of halogens with hydrogen.",
        tags: ["iodine", "hydrogen"],
      },
      {
        id: "t11-2-f10",
        noteId: "t11-2",
        difficulty: 5,
        front: "Strongest H–X bond among HF, HCl, HBr, HI?",
        back: "H–F is strongest (HF most thermally stable in the series).",
        examPhrasing: "Relate bond strength to thermal stability of hydrogen halides.",
        tags: ["bond-strength"],
      },
    ],
  },
  "t11-3": {
    noteId: "t11-3",
    drills: [
      {
        id: "t11-3-d1",
        noteId: "t11-3",
        kind: "structured",
        difficulty: 1,
        marks: 4,
        stem: "Describe the relative reactivity of the halide ions F–, Cl–, Br– and I– as reducing agents, and identify which ion is most readily oxidised in aqueous solution by a powerful oxidising agent.",
        modelAnswerPoints: [
          "Reducing strength increases in the order F– < Cl– < Br– < I– (iodide is the strongest reducing agent among the halide ions; fluoride is the weakest).",
          "A reducing agent donates electrons and is itself oxidised.",
          "I– is most readily oxidised to I2 (or higher oxidation states with very strong oxidants) under comparable conditions.",
        ],
        workedSolution: [
          "Halide ions can all act as reducing agents by donating a lone pair and an electron in redox processes, but the ease with which they lose electrons increases dramatically down the group because the ionic radius increases and the outermost electrons are farther from the nucleus and more shielded.",
          "Therefore fluoride ion is a very poor reducing agent under normal aqueous conditions, chloride is weak, bromide is stronger, and iodide is the strongest reducing agent in the set F– to I–, which is why iodide is oxidised by reagents that leave chloride untouched.",
          "When a powerful oxidising agent is added to a mixture containing several halides, iodide is oxidised first in the usual qualitative picture, which matches calling I– the most readily oxidised halide ion in this comparison.",
        ],
        commonMistake:
          "Reversing the reducing strength order or confusing reducing strength of X– with oxidising strength of X2.",
        tags: ["halide-ions", "reducing-agents"],
      },
      {
        id: "t11-3-d2",
        noteId: "t11-3",
        kind: "structured",
        difficulty: 2,
        marks: 6,
        stem: "Describe and explain what is observed when separate aqueous solutions containing chloride, bromide and iodide ions are treated first with aqueous silver nitrate, then with dilute aqueous ammonia as appropriate. Include the formula of each silver halide precipitate and state which precipitates dissolve in dilute ammonia.",
        modelAnswerPoints: [
          "With Ag+(aq) from AgNO3(aq): Cl– gives white AgCl(s); Br– gives cream AgBr(s); I– gives yellow AgI(s).",
          "AgCl(s) dissolves in dilute NH3(aq) by forming a soluble diamminesilver(I) complex (exact formula [Ag(NH3)2]+ not required by the syllabus statement).",
          "AgBr(s) is partially soluble in dilute NH3(aq); AgI(s) is insoluble in dilute NH3(aq) (needs concentrated ammonia in practice to dissolve appreciably).",
          "Colours and solubility differences allow distinction of the three halide ions.",
        ],
        workedSolution: [
          "When silver nitrate solution is added to a solution containing chloride ions, a white precipitate of silver chloride appears because the ionic product exceeds the solubility product for AgCl, and the same type of precipitation occurs for bromide as a cream precipitate of silver bromide and for iodide as a yellow precipitate of silver iodide, so the initial test both confirms halide presence and begins to distinguish which halide is present from colour.",
          "If dilute aqueous ammonia is then added to the white silver chloride precipitate, it dissolves because ammonia molecules coordinate to silver(I) ions to form a soluble diamminesilver complex ion in solution, which removes free Ag+ concentration and pulls the equilibrium so that solid AgCl can no longer persist.",
          "Silver bromide is less soluble than silver chloride in ammonia chemistry at comparable concentrations, so in dilute ammonia only partial dissolution of the cream precipitate is expected in the qualitative picture taught, whereas silver iodide is so insoluble that it is essentially unaffected by dilute ammonia and the yellow solid remains.",
          "The overall sequence AgNO3 then NH3 is therefore a standard analytical path: all three halides give insoluble silver salts with characteristic colours, but only chloride behaves as fully dissolving in dilute ammonia among the three in the simple dichotomy candidates memorise, with bromide intermediate and iodide not dissolving in dilute ammonia.",
        ],
        commonMistake:
          "Claiming all three silver halides dissolve equally in dilute ammonia, or confusing cream AgBr with white AgCl without describing the ammonia step.",
        tags: ["silver-test", "qualitative-analysis"],
      },
      {
        id: "t11-3-d3",
        noteId: "t11-3",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "Write balanced equations, including state symbols where helpful, for solid sodium chloride and solid sodium bromide reacting separately with concentrated sulfuric acid. Then write a balanced equation for solid sodium iodide with concentrated sulfuric acid showing oxidation of iodide by the acid to iodine, with sulfur in H2SO4 reduced to a lower oxidation state species (accept either SO2 or H2S as the sulfur-containing reduction product if balanced consistently).",
        modelAnswerPoints: [
          "NaCl: NaCl(s) + H2SO4(l) -> NaHSO4(s) + HCl(g) (or Na2SO4/HCl variants if balanced and consistent).",
          "NaBr: NaBr(s) + H2SO4(l) -> NaHSO4(s) + HBr(g) followed by redox: 2HBr(g) + H2SO4(l) -> Br2(g) + SO2(g) + 2H2O(l) (overall redox may be combined in one overall equation with correct stoichiometry).",
          "NaI: iodide reduces H2SO4; a creditworthy form is 8NaI(s) + 9H2SO4(l) -> 4I2(s) + H2S(g) + 8NaHSO4(s) + 4H2O(l) or equivalent balanced scheme producing I2 plus a reduced sulfur species.",
          "Explanation in words: chloride is too weak a reductant to reduce concentrated sulfuric acid; bromide and especially iodide are strong enough reductants that hot concentrated acid is reduced while the halogen is liberated.",
        ],
        workedSolution: [
          "Solid sodium chloride reacts with concentrated sulfuric acid in a simple acid–salt displacement that can be written as NaCl(s) + H2SO4(l) -> NaHSO4(s) + HCl(g), where hydrogen chloride escapes as a misty gas and no change in oxidation number of chlorine occurs because chloride is not a strong enough reducing agent to reduce sulfur in sulfuric acid under these conditions.",
          "Sodium bromide first behaves similarly to produce hydrogen bromide, NaBr(s) + H2SO4(l) -> NaHSO4(s) + HBr(g), but hydrogen bromide is a reducing gas that can reduce hot concentrated sulfuric acid in a second redox step such as 2HBr(g) + H2SO4(l) -> Br2(g) + SO2(g) + 2H2O(l), which accounts for orange fumes of bromine and the acidic gas sulfur dioxide.",
          "Sodium iodide is a stronger reducing system: iodide ion reduces sulfuric acid substantially, and one self-consistent balanced overall picture is 8NaI(s) + 9H2SO4(l) -> 4I2(s) + H2S(g) + 8NaHSO4(s) + 4H2O(l), which shows solid iodine forming together with hydrogen sulfide gas and hydrogen sulfate salts, reflecting that iodide is oxidised through zero to iodine while some sulfur in the +6 acid is reduced as far as –2 in H2S.",
          "Mark schemes may also accept balanced routes via HI formation followed by redox to I2 with SO2, but the key chemical idea examined is that concentrated sulfuric acid oxidises bromide and iodide but not chloride, and that equations must show electron transfer between halide and sulfur-containing species, not only proton transfer.",
        ],
        commonMistake:
          "Writing only NaI + H2SO4 -> NaHSO4 + HI with no redox to I2, or omitting a reduced sulfur product when iodide is stated to reduce the acid.",
        tags: ["concentrated-sulfuric-acid", "equations", "redox"],
      },
      {
        id: "t11-3-d4",
        noteId: "t11-3",
        kind: "mcq",
        difficulty: 1,
        stem: "Which halide ion is the strongest reducing agent among Cl–, Br– and I–?",
        options: [
          { id: "A", text: "Cl–" },
          { id: "B", text: "Br–" },
          { id: "C", text: "I–" },
          { id: "D", text: "They are all equal." },
        ],
        correctOptionId: "C",
        explanation:
          "Iodide loses electrons most easily among the three; reducing strength increases down the group for X–.",
        distractorRationale: {
          A: "Chloride is the weakest reducing agent of the three halide ions listed.",
          B: "Bromide is intermediate; iodide is a stronger reducing agent than bromide.",
          D: "Ease of oxidation differs markedly from chloride to iodide.",
        },
        tags: ["reducing-agents", "mcq"],
      },
      {
        id: "t11-3-d5",
        noteId: "t11-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Aqueous AgNO3 is added to an unknown halide solution, giving a cream precipitate. The precipitate is partially soluble in dilute NH3(aq). Which halide is most consistent with these observations?",
        options: [
          { id: "A", text: "Chloride" },
          { id: "B", text: "Bromide" },
          { id: "C", text: "Iodide" },
          { id: "D", text: "Fluoride" },
        ],
        correctOptionId: "B",
        explanation:
          "AgBr is cream and shows partial dissolution in dilute ammonia; AgCl is white and dissolves more completely; AgI is yellow and does not dissolve in dilute ammonia.",
        distractorRationale: {
          A: "Silver chloride is white, not cream, and typically dissolves more readily in dilute ammonia than the cream AgBr case described.",
          C: "Silver iodide is yellow and remains largely insoluble in dilute ammonia.",
          D: "Fluoride does not give a characteristic insoluble AgF precipitate in the same qualitative way and is not the usual unknown in this test sequence.",
        },
        tags: ["silver-test", "mcq"],
      },
      {
        id: "t11-3-d6",
        noteId: "t11-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain why dilute aqueous silver nitrate followed by dilute aqueous ammonia can distinguish chloride from iodide, referring to precipitate colour and behaviour toward ammonia.",
        modelAnswerPoints: [
          "AgCl is white; AgI is yellow.",
          "AgCl dissolves in dilute NH3(aq) forming a soluble silver–ammine complex.",
          "AgI is not soluble in dilute NH3(aq), so the yellow solid persists.",
        ],
        workedSolution: [
          "When silver nitrate is added, chloride gives a white precipitate of silver chloride whereas iodide gives a yellow precipitate of silver iodide, so even before any ammonia is added the colour difference already signals which halide is likely present.",
          "If dilute ammonia is added to the tube containing silver chloride, the white solid dissolves because ammonia coordinates silver ions strongly enough to shift equilibria so that chloride re-enters solution as the diamminesilver(I) complex forms.",
          "The same dilute ammonia treatment applied to silver iodide does not dissolve the precipitate in the syllabus-level description, because silver iodide is so insoluble that dilute ammonia cannot pull enough silver into complexed form, so the yellow silver iodide solid remains visible, which cleanly distinguishes iodide from chloride in the two-step test.",
        ],
        commonMistake:
          "Saying iodide precipitate is white, or that AgI dissolves completely in dilute ammonia like AgCl.",
        tags: ["silver-test", "qualitative-analysis"],
      },
      {
        id: "t11-3-d7",
        noteId: "t11-3",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Write a balanced equation for the reaction of hydrogen bromide (formed when NaBr meets concentrated H2SO4) with more hot concentrated sulfuric acid to give bromine, sulfur dioxide and water. Assign oxidation numbers to bromine and sulfur in the key species to show that bromide has been oxidised and sulfuric acid reduced.",
        modelAnswerPoints: [
          "2HBr(g) + H2SO4(l) -> Br2(g) + SO2(g) + 2H2O(l) (or balanced ionic equivalent consistent with states).",
          "In HBr, Br is –1; in Br2, Br is 0, so bromine is oxidised.",
          "In H2SO4, S is +6; in SO2, S is +4, so sulfur is reduced.",
        ],
        workedSolution: [
          "After hydrogen bromide has been formed beside bisulfate salts, further hot concentrated sulfuric acid can oxidise HBr in a gas-phase style redox summarised by 2HBr(g) + H2SO4(l) -> Br2(g) + SO2(g) + 2H2O(l), which conserves atoms and shows bromine appearing as coloured vapour alongside sulfur dioxide.",
          "In hydrogen bromide the oxidation number of bromine is –1 because hydrogen is taken as +1 in combined hydrogen compounds, whereas in diatomic bromine each atom is in oxidation state zero, so each bromide ion equivalent has lost one electron overall and bromine has been oxidised from –1 to 0.",
          "In sulfuric acid the sulfur atom is in the +6 oxidation state characteristic of the sulfate group, but in sulfur dioxide sulfur is +4 with two oxygen atoms at –2 each on the usual assignment, so sulfur has gained electron density overall and has been reduced while bromide was the reductant.",
        ],
        commonMistake:
          "Leaving bromine as Br– in products, or assigning sulfur in SO2 as +6.",
        tags: ["concentrated-sulfuric-acid", "oxidation-numbers", "equations"],
      },
      {
        id: "t11-3-d8",
        noteId: "t11-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Why does concentrated H2SO4 oxidise NaI but not NaCl under comparable laboratory conditions?",
        options: [
          { id: "A", text: "I– is a stronger reducing agent than Cl–, so iodide can reduce sulfur in H2SO4 while chloride cannot." },
          { id: "B", text: "Chlorine is more electronegative than iodine, so Cl– is a stronger reducing agent." },
          { id: "C", text: "NaI is more soluble than NaCl, so more reaction occurs." },
          { id: "D", text: "H2SO4 only acts as an acid with ionic halides, never as an oxidising agent." },
        ],
        correctOptionId: "A",
        explanation:
          "Reducing power of halide ions increases down the group; iodide reduces hot concentrated sulfuric acid, chloride does not.",
        distractorRationale: {
          B: "Higher electronegativity of chlorine means Cl– holds electrons more tightly and is a weaker reducing agent than I–, not stronger.",
          C: "Solubility is not the primary syllabus explanation for selective oxidation of iodide by concentrated sulfuric acid.",
          D: "Concentrated sulfuric acid clearly behaves as an oxidising agent toward Br– and I– despite also being acidic.",
        },
        tags: ["redox", "mcq"],
      },
      {
        id: "t11-3-d9",
        noteId: "t11-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "State the colour of each silver halide precipitate formed when AgNO3(aq) is added to solutions of chloride, bromide and iodide. Explain in one sentence why the silver iodide precipitate is not expected to dissolve in dilute aqueous ammonia.",
        modelAnswerPoints: [
          "AgCl white; AgBr cream; AgI yellow.",
          "AgI is too insoluble / formation constant of the ammine complex is insufficient with dilute NH3 to dissolve the precipitate in the syllabus-level description.",
        ],
        workedSolution: [
          "Addition of silver nitrate to chloride, bromide and iodide solutions produces respectively a white precipitate of silver chloride, a cream precipitate of silver bromide and a yellow precipitate of silver iodide, and these colours are the first-line evidence used before any ammonia is considered.",
          "Silver iodide has an extremely low solubility product, so even when ammonia tries to complex Ag+ ions, the equilibrium does not move far enough in dilute ammonia to redissolve the solid in the qualitative picture taught, which is why candidates are expected to say the yellow precipitate remains in dilute ammonia unlike white silver chloride.",
        ],
        commonMistake:
          "Calling AgBr white or AgI cream, which collapses the distinction the test relies on.",
        tags: ["silver-test", "colours"],
      },
      {
        id: "t11-3-d10",
        noteId: "t11-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Combine the silver–ammine test and the concentrated sulfuric acid behaviour to contrast chloride and iodide: (i) observations with AgNO3(aq) and dilute NH3(aq), and (ii) one key redox contrast when each solid halide meets hot concentrated H2SO4.",
        modelAnswerPoints: [
          "(i) AgCl white, dissolves in dilute NH3; AgI yellow, insoluble in dilute NH3.",
          "(ii) NaCl gives HCl(g) / acid displacement without reducing S(VI); NaI reduces H2SO4 with I2 and a reduced sulfur species such as H2S or SO2 depending on conditions.",
          "Underlying idea: I– is a far stronger reducing agent than Cl–.",
        ],
        workedSolution: [
          "In the qualitative cation test, chloride and iodide both precipitate insoluble silver salts, but silver chloride is white and dissolves when dilute ammonia is added because diamminesilver(I) formation competes successfully against the solubility product, whereas silver iodide is yellow and remains as a solid in dilute ammonia because its lattice is too stable for that level of complexation to clear the precipitate.",
          "When the solid sodium salts are treated with hot concentrated sulfuric acid, sodium chloride behaves as a source of hydrogen chloride gas via proton transfer to bisulfate without changing chloride oxidation state, because chloride is too weak a reductant to reduce sulfur from +6 under these conditions.",
          "Sodium iodide, by contrast, supplies iodide ions that are strong reductants, so sulfuric acid is reduced while iodide is oxidised to iodine and gases such as hydrogen sulfide or sulfur dioxide can appear depending on stoichiometry and temperature, which is the sharp chemical contrast examiners want alongside the analytical colour sequence in part (i).",
        ],
        commonMistake:
          "Treating both halides as non-reducing toward sulfuric acid, or claiming AgI dissolves like AgCl in dilute ammonia.",
        tags: ["integrated", "qualitative-analysis", "redox"],
      },
    ],
    flashcards: [
      {
        id: "t11-3-f1",
        noteId: "t11-3",
        difficulty: 1,
        front: "Reducing strength of halide ions down the group?",
        back: "Increases: F– weakest reductant; I– strongest among Cl–, Br–, I–.",
        examPhrasing: "Describe the relative reactivity of halide ions as reducing agents.",
        tags: ["reducing-agents"],
      },
      {
        id: "t11-3-f2",
        noteId: "t11-3",
        difficulty: 1,
        front: "AgCl colour + dilute NH3?",
        back: "White precipitate; dissolves in dilute ammonia (ammine complex forms).",
        examPhrasing: "Describe the reaction of chloride ions with aqueous silver ions followed by aqueous ammonia.",
        tags: ["silver-test"],
      },
      {
        id: "t11-3-f3",
        noteId: "t11-3",
        difficulty: 2,
        front: "AgBr colour + dilute NH3?",
        back: "Cream precipitate; partially soluble in dilute NH3.",
        examPhrasing: "Describe the silver test for bromide including ammonia step.",
        tags: ["silver-test"],
      },
      {
        id: "t11-3-f4",
        noteId: "t11-3",
        difficulty: 2,
        front: "AgI colour + dilute NH3?",
        back: "Yellow precipitate; not soluble in dilute NH3 (stays).",
        examPhrasing: "Describe the silver test for iodide including ammonia step.",
        tags: ["silver-test"],
      },
      {
        id: "t11-3-f5",
        noteId: "t11-3",
        difficulty: 3,
        front: "NaCl + conc H2SO4 main observation?",
        back: "Steamy/misty HCl(g); NaHSO4 formed — chloride does not reduce the acid.",
        examPhrasing: "Describe the reaction of chloride ions with concentrated sulfuric acid.",
        tags: ["sulfuric-acid"],
      },
      {
        id: "t11-3-f6",
        noteId: "t11-3",
        difficulty: 3,
        front: "NaBr + conc H2SO4 key redox products?",
        back: "HBr formed then oxidised: Br2 (brown fumes) + SO2 among products.",
        examPhrasing: "Explain the reaction of bromide ions with concentrated sulfuric acid with an equation.",
        tags: ["sulfuric-acid", "redox"],
      },
      {
        id: "t11-3-f7",
        noteId: "t11-3",
        difficulty: 4,
        front: "NaI + conc H2SO4 — why more redox than NaCl?",
        back: "I– is a strong reductant; reduces S(VI) while forming I2 (and reduced sulfur gases).",
        examPhrasing: "Explain the reaction of iodide ions with concentrated sulfuric acid.",
        confusionPair: "NaCl vs NaI with conc H2SO4",
        tags: ["sulfuric-acid", "redox"],
      },
      {
        id: "t11-3-f8",
        noteId: "t11-3",
        difficulty: 4,
        front: "Formula of white silver chloride precipitate?",
        back: "AgCl.",
        examPhrasing: "Give the formula of the precipitate formed when chloride reacts with silver nitrate.",
        tags: ["silver-test"],
      },
      {
        id: "t11-3-f9",
        noteId: "t11-3",
        difficulty: 5,
        front: "Oxidation number change Br– to Br2?",
        back: "–1 to 0 — each bromide loses one electron (oxidised).",
        examPhrasing: "Assign oxidation numbers in the oxidation of bromide by sulfuric acid.",
        tags: ["oxidation-numbers"],
      },
      {
        id: "t11-3-f10",
        noteId: "t11-3",
        difficulty: 5,
        front: "Why can Cl2 oxidise I– but not Cl–?",
        back: "I– is a stronger reductant; Cl– cannot reduce Cl2 — relative reducing/oxidising abilities.",
        examPhrasing: "Explain displacement of iodine from iodide by chlorine.",
        tags: ["reducing-agents", "oxidising-agents"],
      },
    ],
  },
  "t11-4": {
    noteId: "t11-4",
    drills: [
      {
        id: "t11-4-d1",
        noteId: "t11-4",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Write a balanced equation for the reaction of chlorine with cold dilute aqueous sodium hydroxide. Assign oxidation numbers to chlorine in each chlorine-containing product and state why the reaction is described as a disproportionation.",
        modelAnswerPoints: [
          "Cl2(g) + 2NaOH(aq) -> NaCl(aq) + NaClO(aq) + H2O(l) (or ionic equivalent).",
          "In Cl2, Cl is 0; in Cl–, Cl is –1; in ClO–, Cl is +1.",
          "The same element (chlorine) is simultaneously oxidised and reduced, which defines disproportionation.",
        ],
        workedSolution: [
          "Chlorine reacts with cold dilute sodium hydroxide solution to give chloride, chlorate(I) (hypochlorite) and water in the balanced molecular form Cl2(g) + 2NaOH(aq) -> NaCl(aq) + NaClO(aq) + H2O(l), which conserves atoms and shows one mole of chlorine gas producing one mole of chloride and one mole of hypochlorite per two moles of alkali in the usual stoichiometry.",
          "In the reactant Cl2 each chlorine atom is in oxidation state zero as required for an element in its standard state, whereas in sodium chloride chlorine is present as chloride at –1 and in sodium chlorate(I) the chlorine in the hypochlorite ion is in the +1 oxidation state when oxygen is taken as –2 and the overall ion charge is –1.",
          "Because some chlorine atoms have been reduced from 0 to –1 while others have been oxidised from 0 to +1 within the same overall reaction, chlorine is both oxidising and reducing itself, which is exactly what chemists mean by a disproportionation of an element in an intermediate oxidation state.",
        ],
        commonMistake:
          "Giving chlorate(V) NaClO3 products for cold dilute alkali, which belongs to the hot concentrated case.",
        tags: ["chlorine", "disproportionation", "cold-alkali"],
      },
      {
        id: "t11-4-d2",
        noteId: "t11-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Write a balanced equation for the reaction of chlorine with hot concentrated aqueous sodium hydroxide. Assign oxidation numbers to chlorine in each chlorine-containing species and confirm that the reaction is a disproportionation of chlorine.",
        modelAnswerPoints: [
          "3Cl2(g) + 6NaOH(aq) -> 5NaCl(aq) + NaClO3(aq) + 3H2O(l) (hot conc).",
          "Cl2: Cl 0; Cl–: Cl –1; ClO3–: Cl +5.",
          "Chlorine is both oxidised (to chlorate(V)) and reduced (to chloride), so disproportionation occurs.",
        ],
        workedSolution: [
          "When chlorine is passed into hot concentrated sodium hydroxide solution, a different stoichiometry dominates that can be written as 3Cl2(g) + 6NaOH(aq) -> 5NaCl(aq) + NaClO3(aq) + 3H2O(l), showing that most of the chlorine ends up as chloride but one-sixth of the chlorine atoms in the product set appear in chlorate(V).",
          "In the diatomic reactant the oxidation number of chlorine is still zero, in chloride it is –1, and in the chlorate ion each chlorine is in the +5 oxidation state when each oxygen is –2 and the overall ion charge is –1, which is a large upward shift compared with the starting element.",
          "Because chlorine atoms are reduced to chloride and other chlorine atoms are oxidised to chlorate(V) starting from oxidation state zero in Cl2, the element chlorine undergoes disproportionation again, but this time spanning the –1 and +5 states rather than the –1 and +1 states seen with cold dilute alkali.",
        ],
        commonMistake:
          "Using the cold alkali products when the stem specifies hot concentrated alkali.",
        tags: ["chlorine", "disproportionation", "hot-alkali"],
      },
      {
        id: "t11-4-d3",
        noteId: "t11-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Contrast the products when chlorine reacts with cold dilute NaOH(aq) versus hot concentrated NaOH(aq), and link each case to the oxidation numbers of chlorine in the chlorine-containing anions formed.",
        modelAnswerPoints: [
          "Cold dilute: Cl– (–1) and ClO– (+1).",
          "Hot concentrated: Cl– (–1) and ClO3– (+5).",
          "Both are disproportionations but the higher positive oxidation state reached under hot conditions is chlorate(V), not chlorate(I).",
        ],
        workedSolution: [
          "With cold dilute sodium hydroxide, chlorine disproportionates into chloride ion at oxidation state –1 and hypochlorite ion at +1, which corresponds to the mild oxidising bleach chemistry of chlorate(I) solutions without driving the system to the more oxidised chlorate(V).",
          "With hot concentrated sodium hydroxide, the same zero oxidation state of elemental chlorine splits mainly into chloride still at –1 but also into chlorate(V) at +5, which shows the alkali can force a deeper internal redox among chlorine atoms when enough thermal energy and high hydroxide concentration are available.",
          "In both situations chlorine starts at oxidation number zero in Cl2 and ends in at least two different oxidation states in the salts, so both reactions are disproportionations, but the positive end point differs between +1 hypochlorite under cold dilute conditions and +5 chlorate under hot concentrated conditions.",
        ],
        commonMistake:
          "Stating that only one of the reactions is disproportionation, or assigning +3 to chlorate(V).",
        tags: ["disproportionation", "comparison"],
      },
      {
        id: "t11-4-d4",
        noteId: "t11-4",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "Explain the use of chlorine in drinking-water treatment, including a balanced equation for its reaction with water and identification of the species that kill bacteria. State how raising pH shifts the position of the aqueous chlorine equilibrium and the role of ClO^-.",
        modelAnswerPoints: [
          "Cl2(aq) + H2O(l) <=> HCl(aq) + HOCl(aq) (or Cl2 + H2O -> H+ + Cl– + HOCl in ionic form).",
          "Bactericidal species: mainly HOCl and, in alkaline water, hypochlorite ion ClO^- from deprotonation of HOCl.",
          "Higher pH removes H+ and shifts equilibrium toward ClO^-; both HOCl and ClO^- act as disinfectants though penetration properties differ.",
        ],
        workedSolution: [
          "Chlorine is dissolved in water to take advantage of the equilibrium Cl2(aq) + H2O(l) <=> HCl(aq) + HOCl(aq), which produces both strong acid and hypochlorous acid, HOCl, the latter being the neutral oxidising species chiefly responsible for killing bacteria by oxidising essential biomolecules in the cell.",
          "In more alkaline drinking water, hypochlorous acid partially deprotonates to hypochlorite ion, ClO^-, which is still an active disinfectant in the syllabus picture alongside HOCl, and the board expects candidates to name both HOCl and ClO^- as the bactericidal species derived from dissolved chlorine rather than citing Cl2(aq) alone.",
          "Raising pH consumes hydrogen ions from the acid side of related equilibria, which shifts the speciation toward hypochlorite, so the balance between HOCl and ClO^- changes even though total active chlorine from the dose remains tied to the initial chlorine addition.",
        ],
        commonMistake:
          "Claiming only Cl2(g) disinfects with no mention of HOCl / ClO^- formation in water.",
        tags: ["water-treatment", "equilibrium"],
      },
      {
        id: "t11-4-d5",
        noteId: "t11-4",
        kind: "mcq",
        difficulty: 2,
        stem: "In the reaction of chlorine with cold dilute NaOH(aq), what is the oxidation number of chlorine in the chlorate(I) (hypochlorite) product ion?",
        options: [
          { id: "A", text: "–1" },
          { id: "B", text: "0" },
          { id: "C", text: "+1" },
          { id: "D", text: "+5" },
        ],
        correctOptionId: "C",
        explanation:
          "In ClO– with O taken as –2, chlorine must be +1 to give overall charge –1.",
        distractorRationale: {
          A: "That is the oxidation number of chloride, Cl–, not hypochlorite.",
          B: "Zero is the oxidation number of chlorine in Cl2, not in ClO–.",
          D: "+5 is the oxidation state of chlorine in chlorate(V), ClO3–, formed with hot concentrated alkali, not cold dilute.",
        },
        tags: ["oxidation-numbers", "mcq"],
      },
      {
        id: "t11-4-d6",
        noteId: "t11-4",
        kind: "mcq",
        difficulty: 2,
        stem: "Which equation best represents the formation of bactericidal species when chlorine is used to treat water?",
        options: [
          { id: "A", text: "Cl2(g) + H2O(l) <=> 2HCl(aq)" },
          { id: "B", text: "Cl2(aq) + H2O(l) <=> HCl(aq) + HOCl(aq)" },
          { id: "C", text: "Cl2(g) + 2NaOH(aq) -> NaCl(aq) + NaClO(aq) + H2O(l)" },
          { id: "D", text: "3Cl2(g) + 6NaOH(aq) -> 5NaCl(aq) + NaClO3(aq) + 3H2O(l)" },
        ],
        correctOptionId: "B",
        explanation:
          "Disinfection uses chlorine dissolved in water forming HOCl (and then ClO^- in alkaline water), not only HCl and not the alkali disproportionation equations.",
        distractorRationale: {
          A: "That stoichiometry omits HOCl, the key hypochlorous acid disinfectant species.",
          C: "That is cold alkali disproportionation of chlorine, not the primary dissolution equilibrium in drinking water chlorination.",
          D: "That is hot alkali chlorate formation, not the water-treatment context in the stem.",
        },
        tags: ["water-treatment", "mcq"],
      },
      {
        id: "t11-4-d7",
        noteId: "t11-4",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Explain why the reaction of chlorine with cold dilute sodium hydroxide is classified as a redox reaction of chlorine with itself, using the terms oxidation, reduction and disproportionation.",
        modelAnswerPoints: [
          "Some Cl (0) becomes Cl– (–1): gain of electrons, reduction.",
          "Some Cl (0) becomes ClO– (+1): loss of electrons, oxidation.",
          "Same element undergoes oxidation and reduction together: disproportionation.",
        ],
        workedSolution: [
          "In the cold dilute sodium hydroxide reaction, elemental chlorine begins with each atom in oxidation state zero, but in the products chloride ions carry chlorine at –1, which corresponds to each such chlorine atom gaining one electron compared with the element and therefore being reduced.",
          "Simultaneously, hypochlorite ions contain chlorine at +1, which corresponds to chlorine atoms that have lost one electron relative to the element and have therefore been oxidised.",
          "Because oxidation and reduction both happen to chlorine atoms within the same overall process without requiring a different element to be the oxidising or reducing partner, the reaction is described as disproportionation of chlorine, which is a special case of redox chemistry where an intermediate oxidation state splits into higher and lower states.",
        ],
        commonMistake:
          "Saying sodium is oxidised or reduced; sodium oxidation state stays +1 throughout.",
        tags: ["disproportionation", "definitions"],
      },
      {
        id: "t11-4-d8",
        noteId: "t11-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Write the acid–base equilibrium linking HOCl and ClO^- in water. Explain briefly why both HOCl and ClO^- are cited as bactericidal active species when chlorine disinfects water at different pH values.",
        modelAnswerPoints: [
          "HOCl + H2O <=> H3O+ + ClO^- (or HOCl <=> H+ + ClO^-).",
          "HOCl is the dominant undissociated acid in mildly acidic water and penetrates cells effectively.",
          "At higher pH, ClO^- dominates but still acts as an oxidising disinfectant in bulk water chemistry.",
        ],
        workedSolution: [
          "Hypochlorous acid is a weak acid in water, so it sets up the equilibrium HOCl + H2O <=> H3O+ + ClO^- or simply HOCl <=> H+ + ClO^-, which shows how raising pH by removing hydrogen ions shifts the position toward hypochlorite ion without stopping all active chlorine chemistry.",
          "In slightly acidic drinking water, a large fraction of active chlorine exists as HOCl, which is uncharged and diffuses into bacterial cells relatively easily, where it oxidises enzymes and membranes, which is why HOCl is emphasised as the primary bactericidal molecular form immediately after chlorine dissolves.",
          "As pH rises toward typical treated water values, a greater proportion of the same active chlorine inventory is present as hypochlorite ion, ClO^-, which is still an oxidising chlorate(I)-derived species that kills bacteria in the bulk water even though its cell penetration differs from HOCl, which is why syllabuses name both HOCl and ClO^- as killing species rather than only one form.",
        ],
        commonMistake:
          "Treating ClO^- as non-oxidising or ignoring the equilibrium link to HOCl.",
        tags: ["water-treatment", "equilibrium"],
      },
      {
        id: "t11-4-d9",
        noteId: "t11-4",
        kind: "mcq",
        difficulty: 3,
        stem: "Which product set is expected when Cl2 reacts with hot concentrated NaOH(aq)?",
        options: [
          { id: "A", text: "NaCl and NaClO only" },
          { id: "B", text: "NaCl and NaClO3" },
          { id: "C", text: "NaClO only" },
          { id: "D", text: "NaCl and Cl2" },
        ],
        correctOptionId: "B",
        explanation:
          "Hot concentrated alkali gives chloride and chlorate(V); NaClO is the cold dilute product pattern.",
        distractorRationale: {
          A: "That pair is characteristic of cold dilute alkali, not hot concentrated conditions.",
          C: "Chlorine cannot disproportionate to hypochlorite alone without chloride; hot alkali also does not stop at only NaClO.",
          D: "Chlorine is consumed in the disproportionation; unreacted Cl2 is not the intended product slate.",
        },
        tags: ["hot-alkali", "mcq"],
      },
      {
        id: "t11-4-d10",
        noteId: "t11-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Integrate 11.4 ideas: (i) identify each disproportionation of chlorine with alkali by the chlorine oxidation states involved, and (ii) explain how adding chlorine to water supplies both HOCl and, depending on pH, ClO^- for disinfection, with one balanced equation for chlorine + water.",
        modelAnswerPoints: [
          "(i) Cold dilute: 0 -> –1 and 0 -> +1; hot conc: 0 -> –1 and 0 -> +5.",
          "(ii) Cl2(aq) + H2O(l) <=> HCl(aq) + HOCl(aq); HOCl deprotonates to ClO^- at higher pH.",
          "Both HOCl and ClO^- kill bacteria (active chlorine species).",
        ],
        workedSolution: [
          "When chlorine reacts with cold dilute sodium hydroxide, chlorine in oxidation state zero in Cl2 is converted partly to chloride at –1 and partly to hypochlorite at +1, which is a narrow disproportionation span appropriate to mild conditions, whereas with hot concentrated alkali the same starting zero is still partly reduced to –1 but is partly oxidised all the way to chlorate(V) at +5, showing a deeper disproportionation under forcing conditions.",
          "Those two disproportionation patterns are both interpreted by tracking oxidation numbers on chlorine atoms in reactants and products, and in each case more than one final oxidation state of chlorine proves that chlorine is simultaneously oxidised and reduced.",
          "For water treatment, dissolving chlorine establishes Cl2(aq) + H2O(l) <=> HCl(aq) + HOCl(aq), which introduces hypochlorous acid, HOCl as the immediate bactericidal molecular form, and because HOCl is a weak acid, the hydrogen ion concentration in the finished water determines how much is present as neutral HOCl versus as hypochlorite ion ClO^- after deprotonation.",
          "Public health chemistry therefore cites both HOCl and ClO^- as active species because real supplies span a range of pH where speciation shifts even though the chlorine dose is introduced as Cl2, and both forms retain oxidising power toward bacterial biochemistry.",
        ],
        commonMistake:
          "Mixing up +1 hypochlorite conditions with +5 chlorate conditions, or omitting HOCl from the water equilibrium.",
        tags: ["integrated", "disproportionation", "water-treatment"],
      },
    ],
    flashcards: [
      {
        id: "t11-4-f1",
        noteId: "t11-4",
        difficulty: 1,
        front: "Cl2 + cold dilute NaOH products?",
        back: "NaCl + NaClO + H2O — Cl from 0 to –1 and +1 (disproportionation).",
        examPhrasing: "Write an equation for chlorine with cold dilute aqueous sodium hydroxide.",
        tags: ["cold-alkali"],
      },
      {
        id: "t11-4-f2",
        noteId: "t11-4",
        difficulty: 1,
        front: "Cl2 + hot conc NaOH products?",
        back: "NaCl + NaClO3 + H2O pattern: Cl 0 to –1 and +5.",
        examPhrasing: "Write an equation for chlorine with hot concentrated sodium hydroxide.",
        tags: ["hot-alkali"],
      },
      {
        id: "t11-4-f3",
        noteId: "t11-4",
        difficulty: 2,
        front: "Oxidation number of Cl in ClO–?",
        back: "+1 (with O as –2).",
        examPhrasing: "Assign oxidation numbers in the reaction of chlorine with cold dilute NaOH.",
        tags: ["oxidation-numbers"],
      },
      {
        id: "t11-4-f4",
        noteId: "t11-4",
        difficulty: 2,
        front: "Oxidation number of Cl in ClO3–?",
        back: "+5.",
        examPhrasing: "Assign oxidation numbers in the hot alkali chlorate product.",
        tags: ["oxidation-numbers"],
      },
      {
        id: "t11-4-f5",
        noteId: "t11-4",
        difficulty: 3,
        front: "Define disproportionation.",
        back: "Same element oxidised and reduced in one reaction (e.g. Cl2 -> Cl– + ClO–).",
        examPhrasing: "Recognise disproportionation in the reaction of chlorine with alkali.",
        tags: ["disproportionation"],
      },
      {
        id: "t11-4-f6",
        noteId: "t11-4",
        difficulty: 3,
        front: "Cl2 + H2O equilibrium products?",
        back: "HCl + HOCl; HOCl (and ClO^- at higher pH) kill bacteria.",
        examPhrasing: "Explain the use of chlorine in water purification with an equation.",
        tags: ["water-treatment"],
      },
      {
        id: "t11-4-f7",
        noteId: "t11-4",
        difficulty: 4,
        front: "Why is HOCl named as a disinfectant species?",
        back: "Weak acid from Cl2 in water; uncharged HOCl penetrates cells and oxidises biomolecules.",
        examPhrasing: "Explain the production of HOCl when chlorine treats water.",
        tags: ["water-treatment"],
      },
      {
        id: "t11-4-f8",
        noteId: "t11-4",
        difficulty: 4,
        front: "Role of ClO^- at higher pH?",
        back: "Deprotonated form of HOCl; still an active chlorine disinfectant in solution.",
        examPhrasing: "Include ClO^- when explaining chlorine disinfection.",
        tags: ["water-treatment"],
      },
      {
        id: "t11-4-f9",
        noteId: "t11-4",
        difficulty: 5,
        front: "Cold vs hot alkali: higher positive oxidation state of Cl?",
        back: "Hot conc gives ClO3– (+5); cold dilute gives ClO– (+1).",
        examPhrasing: "Contrast chlorine reactions with cold and hot aqueous sodium hydroxide.",
        confusionPair: "NaClO vs NaClO3 conditions",
        tags: ["disproportionation"],
      },
      {
        id: "t11-4-f10",
        noteId: "t11-4",
        difficulty: 5,
        front: "In Cl2 + cold NaOH, is Na+ oxidised?",
        back: "No — Na stays +1; only chlorine changes oxidation number.",
        examPhrasing: "Interpret the disproportionation of chlorine with alkali.",
        tags: ["oxidation-numbers"],
      },
    ],
  },
};
