import type { SubtopicPracticePack } from "./types";

/**
 * 9701 Topic 37 / 37.1–37.4 — Chromatography & NMR: `t37-1` … `t37-4`.
 *
 * LO crosswalk (`data/syllabus/chemistry-9701-learning-outcomes.md` §37.1–37.4;
 * `data/courses/chemistry-9701.json`):
 *
 * **t37-1 (37.1 TLC)** — stationary / mobile phase; Rf; solvent front & baseline; interpret Rf;
 * explain Rf differences (stationary interaction; solubility in mobile phase).
 *
 * **t37-2 (37.2 GC/LC)** — stationary (high-bp non-polar liquid on support); mobile (inert gas);
 * retention time; % composition from chromatograms; retention vs stationary-phase interaction.
 *
 * **t37-3 (37.3 ^13C NMR)** — deduce environments / possible structures from a simple spectrum;
 * predict or explain number of peaks for a given molecule.
 *
 * **t37-4 (37.4 proton NMR)** — δ, integration, splitting (n+1, singlet–multiplet); structures;
 * predict shifts/patterns; TMS; deuterated solvents (e.g. CDCl3); D2O exchange for O–H / N–H.
 */
export const CHEMISTRY_TOPIC37_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t37-1": {
    noteId: "t37-1",
    drills: [
      {
        id: "t37-1-d1",
        noteId: "t37-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "State what is meant by the following in thin-layer chromatography (TLC): (i) stationary phase, (ii) mobile phase, (iii) Rf value, (iv) baseline, and (v) solvent front.",
        modelAnswerPoints: [
          "Stationary phase: the fixed adsorbent layer on the plate (e.g. aluminium oxide on a solid support) with which analytes interact as they are carried along.",
          "Mobile phase: the solvent (or solvent mixture) that moves through the stationary layer by capillary action, carrying dissolved sample with it.",
          "Rf: the ratio (distance moved by the centre of the spot) / (distance moved by the solvent front), measured from the baseline under the same run conditions.",
          "Baseline: the origin line on which the sample is spotted before development.",
          "Solvent front: the leading edge of the solvent after the plate has been run for a set time.",
        ],
        workedSolution: [
          "In TLC the stationary phase is the thin, porous layer fixed to the plate — in this syllabus aluminium oxide on a support is the textbook example — and analytes spend part of their time adsorbed on that polar surface rather than dissolved only in the moving solvent.",
          "The mobile phase is the developing solvent or mixture that rises through the layer by capillary action; its polarity is chosen so that components partition between adsorption on the stationary phase and dissolution in the moving liquid.",
          "The retention factor Rf is defined as the distance travelled by the centre of a component spot divided by the distance travelled by the solvent front, both measured from the baseline, which makes it a dimensionless position on the plate for that solvent and stationary phase.",
          "The baseline is the horizontal line near the bottom of the plate where the mixture is applied as a small spot before the tank is sealed and development begins, so all distance measurements for Rf are referenced to that line.",
          "The solvent front is the highest wet line reached by the mobile phase when development is stopped, and its distance from the baseline is the denominator in the Rf ratio, representing how far the solvent has carried analytes in that run.",
        ],
        commonMistake:
          "Measuring Rf from the top of the plate downward, or using the spot height above the tank base instead of distance from the baseline.",
        tags: ["definitions", "tlc", "rf", "phases"],
      },
      {
        id: "t37-1-d2",
        noteId: "t37-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Two spots on the same TLC plate are measured from the baseline. The solvent front travelled 8.0 cm and a compound A travelled 2.0 cm. What is the Rf of A?",
        options: [
          { id: "A", text: "0.25" },
          { id: "B", text: "4.0" },
          { id: "C", text: "0.50" },
          { id: "D", text: "2.0" },
        ],
        correctOptionId: "A",
        explanation:
          "Rf = (distance spot) / (distance solvent front) = 2.0 / 8.0 = 0.25, a value between 0 and 1 when measured correctly from the baseline.",
        distractorRationale: {
          B: "That is the inverse ratio (front/spot), not Rf.",
          C: "That would correspond to the spot travelling half the front distance, not one quarter.",
          D: "That is the raw spot distance in cm, not the dimensionless Rf.",
        },
        tags: ["rf", "calculations", "tlc"],
      },
      {
        id: "t37-1-d3",
        noteId: "t37-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "On a polar aluminium oxide TLC layer developed with hexane, compound X has Rf = 0.80 while compound Y has Rf = 0.15. Explain which compound is more strongly retained by the stationary phase and which is relatively more soluble in the mobile phase, using ideas of polarity and partitioning.",
        modelAnswerPoints: [
          "Lower Rf means less net movement with the solvent, so Y is more strongly held on the polar stationary surface (stronger adsorption / slower elution).",
          "Higher Rf means X spends a greater fraction of time in the mobile phase, so X is relatively more soluble in the non-polar hexane mobile phase.",
          "Polar analytes interact more strongly with the polar oxide surface, so they tend to stay nearer the baseline when the mobile phase is non-polar.",
          "Less polar analytes partition favourably into non-polar solvent and travel closer to the solvent front.",
        ],
        workedSolution: [
          "Because Rf is the ratio of spot distance to solvent-front distance, the compound with the smaller Rf, Y at 0.15, has moved a smaller fraction of the solvent’s path and therefore is more strongly retained on the polar aluminium oxide layer, which corresponds to stronger attractive interactions between Y and that polar stationary surface during development.",
          "Compound X with the larger Rf of 0.80 has travelled a much larger fraction of the solvent’s distance, which means it has partitioned more effectively into the moving hexane phase and is therefore relatively more soluble in that non-polar mobile phase compared with Y under the same run.",
          "Hexane is a very non-polar eluent, so polar functional groups in a molecule are attracted strongly to the polar oxide adsorption sites and are not pulled along quickly, which is why the more polar-like component in a pair is expected to show the lower Rf when developed with a non-polar solvent on a polar layer.",
          "By contrast, a molecule that is predominantly hydrocarbon-like experiences weaker specific attraction to the oxide surface and is carried more readily in hexane, giving a higher Rf nearer the solvent front, which matches X being the less strongly surface-bound member of the pair in this experiment.",
        ],
        commonMistake:
          "Claiming the higher-Rf substance is ‘more polar’ on a polar stationary phase with a non-polar solvent — the usual elution order is the opposite.",
        tags: ["rf", "polarity", "partitioning", "tlc"],
      },
      {
        id: "t37-1-d4",
        noteId: "t37-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which change is most likely to **increase** the Rf of a moderately polar organic compound on polar Al2O3 TLC if everything else is kept the same?",
        options: [
          { id: "A", text: "Use a more polar mobile phase (stronger eluent)." },
          { id: "B", text: "Use a completely non-polar mobile phase with even lower eluting power than before." },
          { id: "C", text: "Spot the sample above the solvent level in the tank so it never wets." },
          { id: "D", text: "Switch to a less polar stationary phase while keeping the same polar solvent." },
        ],
        correctOptionId: "A",
        explanation:
          "A more polar solvent competes better for the polar surface and dissolves the polar analyte more readily, so the spot is carried further and Rf increases (up to the limit set by the solvent front).",
        distractorRationale: {
          B: "Weaker elution by a less polar solvent usually **decreases** Rf for polar analytes on polar layers because adsorption dominates.",
          C: "If the spot is not wetted and developed, no meaningful chromatography occurs.",
          D: "The syllabus example stresses polar Al2O3; a less polar adsorbent changes the whole selectivity picture and is not the standard ‘increase Rf’ lever compared with solvent polarity.",
        },
        tags: ["mobile-phase", "rf", "tlc"],
      },
      {
        id: "t37-1-d5",
        noteId: "t37-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A student defines Rf as ‘how fast the compound moves’. Improve this definition and state two practical reasons why Rf for the same compound is not perfectly reproducible between different laboratories even when the same nominal adsorbent is used.",
        modelAnswerPoints: [
          "Rf is a **position ratio** (spot distance / solvent-front distance) from the baseline after a defined development, not a speed.",
          "Temperature affects solvent viscosity and evaporation at the solvent front.",
          "Tank saturation / degree of equilibration with vapour changes effective elution strength.",
          "Exact solvent composition, plate activation, and run distance/time also alter partitioning.",
        ],
        workedSolution: [
          "A better definition is that Rf is the ratio of the distance travelled by the centre of the component spot from the baseline to the distance travelled by the solvent front from the same baseline after chromatography has been stopped, which captures where the compound ends up relative to the solvent rather than quoting an uncontrolled ‘speed’.",
          "Even for one compound, that ratio is sensitive to temperature because viscosity and vapour pressure of the developer change, which alters how strongly and how quickly analytes partition between the stationary layer and the moving phase during the run.",
          "Whether the development tank is properly equilibrated with solvent vapour before the plate is inserted also changes how sharply the solvent front advances and how much the stationary phase is pre-conditioned, so two groups using ‘the same’ solvent formula can still get slightly different Rf values if tank handling differs.",
          "Minor batch differences in plate activity, small drifts in solvent composition (evaporation of the more volatile cosolvent), and stopping the run at slightly different front heights all feed into spot position, which is why published Rf values are treated as indicative unless conditions are tightly matched.",
        ],
        commonMistake:
          "Treating Rf as a rate constant with units, or forgetting that the denominator must be the solvent-front distance from the baseline.",
        tags: ["rf", "definitions", "tlc"],
      },
      {
        id: "t37-1-d6",
        noteId: "t37-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Two colourless amino acids are separated on polar silica TLC using an aqueous ammonia / propan-2-ol mixture. Which statement best interprets equal Rf values for both spots?",
        options: [
          { id: "A", text: "The two amino acids necessarily have identical structures." },
          { id: "B", text: "Under these conditions both compounds partition similarly between stationary and mobile phases, so they are not resolved." },
          { id: "C", text: "Equal Rf proves one amino acid is the hydrate of the other." },
          { id: "D", text: "Equal Rf means the solvent front did not move." },
        ],
        correctOptionId: "B",
        explanation:
          "Rf is an equilibrium partition fingerprint for a given system; coincidentally similar Rf values mean similar net retention — no separation — not proof of identity.",
        distractorRationale: {
          A: "Different isomers or derivatives can sometimes co-elute; equal Rf is not a structural proof.",
          C: "Hydration is one of many unrelated speculations; chromatography alone would not establish that.",
          D: "If the front did not move, both distances would be zero and the experiment failed; equal non-zero Rf means both spots moved the same fraction of the front distance.",
        },
        tags: ["interpretation", "rf", "tlc"],
      },
      {
        id: "t37-1-d7",
        noteId: "t37-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Calculate the Rf of a spot whose centre is 4.6 cm above the baseline when the solvent front is 9.2 cm above the baseline on the same plate. A second spot has Rf = 0.30 on a repeat run where the front reached 10.0 cm. How far from the baseline is the centre of the second spot? Comment on whether comparing raw cm distances between the two runs without converting to Rf would be valid.",
        modelAnswerPoints: [
          "Rf1 = 4.6 / 9.2 = 0.50 (dimensionless).",
          "For the second run, spot distance = Rf × (front distance) = 0.30 × 10.0 cm = 3.0 cm.",
          "Raw cm distances depend on how far the front was allowed to travel; Rf normalises for that.",
          "Comparing only cm spot heights across runs with different front heights mixes run length with chemistry.",
        ],
        workedSolution: [
          "For the first plate the retention factor is obtained by dividing the spot migration measured from the baseline by the solvent-front migration from the same baseline, giving Rf = 4.6 cm / 9.2 cm = 0.50, which is a pure number between 0 and 1 as required.",
          "In the second experiment the student already knows Rf = 0.30 and observes a solvent front 10.0 cm above the baseline, so the spot centre must lie at a distance 0.30 × 10.0 cm = 3.0 cm above the baseline, because Rf is defined as that ratio rearranged to spot distance equals Rf times front distance.",
          "The reason Rf is defined as a ratio rather than quoting a spot height alone is that stopping development early or late changes the absolute centimetre positions even when the partitioning chemistry is unchanged, so the ratio to the front removes the arbitrary run length from the comparison.",
          "Therefore comparing raw spot heights from two runs with different front distances would be misleading if one run was simply stopped sooner, whereas comparing Rf values (or recalculating spot distance from Rf and the actual front in each run) keeps the chemical interpretation consistent.",
        ],
        commonMistake:
          "Averaging cm distances from runs with different solvent-front heights, or reporting Rf > 1 because the ruler zero was misplaced.",
        tags: ["rf", "calculations", "tlc"],
      },
      {
        id: "t37-1-d8",
        noteId: "t37-1",
        kind: "mcq",
        difficulty: 1,
        stem: "In ascending TLC, what primarily drives the mobile phase through the stationary layer?",
        options: [
          { id: "A", text: "Capillary action in the porous layer." },
          { id: "B", text: "An external electric field applied along the plate." },
          { id: "C", text: "Centrifugal force spinning the plate." },
          { id: "D", text: "Photochemical excitation of the adsorbent." },
        ],
        correctOptionId: "A",
        explanation:
          "Solvent rises (or moves) by capillary flow in the porous stationary bed; the syllabus treats this as the physical basis for development alongside partition/adsorption chemistry.",
        distractorRationale: {
          B: "That describes electrophoresis-like methods, not standard TLC.",
          C: "Rotational planar chromatography exists but is not the default syllabus mechanism.",
          D: "UV may visualise spots but does not pump bulk solvent through the layer.",
        },
        tags: ["tlc", "mobile-phase"],
      },
      {
        id: "t37-1-d9",
        noteId: "t37-1",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "A neutral hydrocarbon and a neutral alcohol of similar size are run on polar Al2O3 TLC with a non-polar alkane developer. Predict which compound has the **lower** Rf and justify your answer using interactions with the stationary phase and relative solubility in the mobile phase.",
        modelAnswerPoints: [
          "The alcohol has the lower Rf (stays lower on the plate) under these conditions.",
          "The –OH group hydrogen-bonds / interacts strongly with the polar oxide surface, increasing adsorption.",
          "The hydrocarbon has weaker specific attraction to the polar surface and partitions more readily into the non-polar alkane mobile phase.",
          "Therefore the alcohol is carried less far relative to the solvent front than the hydrocarbon.",
        ],
        workedSolution: [
          "For a polar aluminium oxide stationary phase developed with a non-polar alkane, the neutral alcohol is expected to show the lower Rf because its hydroxyl group can engage in hydrogen-bonding and dipole interactions with surface oxide and hydroxyl sites, which keeps a larger fraction of molecules adsorbed at any instant.",
          "That stronger attraction to the stationary phase means less effective transport in the direction of solvent flow, so the alcohol spot remains closer to the baseline while the solvent front advances, producing a smaller spot-distance to front-distance ratio.",
          "The hydrocarbon, lacking a polar hydrogen-bonding substituent, experiences comparatively weaker specific binding to the polar layer and instead dissolves more favourably in the non-polar mobile phase, so it is eluted nearer the solvent front and acquires a higher Rf.",
          "Overall the pattern matches the syllabus expectation that differences in Rf reflect the balance between affinity for the polar stationary phase and solubility in the chosen mobile phase, and here polarity of the analyte tilts that balance toward stronger retention for the alcohol.",
        ],
        commonMistake:
          "Arguing from molecular mass alone when polarity and hydrogen bonding dominate on polar layers with non-polar developers.",
        tags: ["rf", "polarity", "tlc"],
      },
      {
        id: "t37-1-d10",
        noteId: "t37-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Why must Rf always lie between 0 and 1 when distances are measured correctly from the baseline to the solvent front?",
        options: [
          { id: "A", text: "The spot cannot move farther than the solvent that carries it; both distances use the same baseline reference." },
          { id: "B", text: "Rf is defined as the log of the concentration, which is always negative." },
          { id: "C", text: "Because the spot always moves twice as fast as the solvent front." },
          { id: "D", text: "Because Rf is the mass of sample divided by the mass of the plate." },
        ],
        correctOptionId: "A",
        explanation:
          "The analyte partitions into the mobile phase but does not outrun the solvent front in normal development, so spot distance ≤ front distance and the ratio lies in [0, 1].",
        distractorRationale: {
          B: "Rf is a simple distance ratio, not a logarithm of concentration.",
          C: "A spot cannot systematically move twice as fast as the advancing wetting front in standard TLC.",
          D: "Rf is dimensionless from distances, not a mass ratio of sample to plate.",
        },
        tags: ["rf", "definitions", "tlc"],
      },
    ],
    flashcards: [
      {
        id: "t37-1-f1",
        noteId: "t37-1",
        difficulty: 1,
        front: "What is the stationary phase in the syllabus TLC example?",
        back: "A polar adsorbent such as aluminium oxide on a solid support.",
        examPhrasing: "Name a typical stationary phase used in thin-layer chromatography.",
        tags: ["tlc", "definitions"],
      },
      {
        id: "t37-1-f2",
        noteId: "t37-1",
        difficulty: 1,
        front: "What is the mobile phase in TLC?",
        back: "The liquid solvent (or mixture) that moves through the layer and carries sample with it — polar or non-polar depending on the separation.",
        examPhrasing: "State what is meant by the mobile phase in thin-layer chromatography.",
        tags: ["tlc", "definitions"],
      },
      {
        id: "t37-1-f3",
        noteId: "t37-1",
        difficulty: 2,
        front: "Define Rf.",
        back: "Distance moved by the spot (from baseline) divided by distance moved by the solvent front (from the same baseline).",
        examPhrasing: "Define the Rf value for a component in TLC.",
        tags: ["rf", "definitions"],
      },
      {
        id: "t37-1-f4",
        noteId: "t37-1",
        difficulty: 2,
        front: "What are the baseline and solvent front?",
        back: "Baseline: line where the sample is spotted. Solvent front: furthest line the solvent has reached when development stops.",
        examPhrasing: "Explain the terms baseline and solvent front in TLC.",
        tags: ["tlc", "definitions"],
      },
      {
        id: "t37-1-f5",
        noteId: "t37-1",
        difficulty: 3,
        front: "On polar Al2O3 with a non-polar developer, does a polar or non-polar analyte usually have the lower Rf?",
        back: "The more polar analyte is retained more strongly → lower Rf (stays nearer the baseline).",
        examPhrasing: "Explain differences in Rf for two compounds on a polar stationary phase using a non-polar mobile phase.",
        confusionPair: "polar analyte Rf vs non-polar analyte Rf",
        tags: ["rf", "polarity"],
      },
      {
        id: "t37-1-f6",
        noteId: "t37-1",
        difficulty: 3,
        front: "Why does increasing mobile-phase polarity often raise Rf of polar compounds on polar TLC?",
        back: "A stronger eluent competes for the surface and keeps more analyte in the moving phase.",
        examPhrasing: "Explain how changing solvent polarity can change Rf.",
        tags: ["mobile-phase", "rf"],
      },
      {
        id: "t37-1-f7",
        noteId: "t37-1",
        difficulty: 4,
        front: "Rf = 0.40 and front is 7.5 cm. How far is the spot?",
        back: "0.40 × 7.5 cm = 3.0 cm from the baseline.",
        examPhrasing: "Calculate the distance moved by a spot given its Rf and the solvent-front distance.",
        tags: ["rf", "calculations"],
      },
      {
        id: "t37-1-f8",
        noteId: "t37-1",
        difficulty: 4,
        front: "Two substances have the same Rf. Are they necessarily the same compound?",
        back: "No — different compounds can co-elute under a given system; further tests are needed.",
        examPhrasing: "Comment on using TLC Rf alone to prove identity.",
        tags: ["interpretation", "tlc"],
      },
      {
        id: "t37-1-f9",
        noteId: "t37-1",
        difficulty: 5,
        front: "In one sentence, what physical process moves solvent in ascending TLC?",
        back: "Capillary action draws solvent through the porous stationary layer.",
        examPhrasing: "Outline how the mobile phase travels in TLC.",
        tags: ["tlc"],
      },
      {
        id: "t37-1-f10",
        noteId: "t37-1",
        difficulty: 5,
        front: "Why compare spot distance to solvent-front distance rather than quoting spot cm only?",
        back: "The ratio removes dependence on how far the run was allowed to proceed.",
        examPhrasing: "Explain why Rf is defined as a ratio of distances.",
        tags: ["rf", "definitions"],
      },
    ],
  },

  "t37-2": {
    noteId: "t37-2",
    drills: [
      {
        id: "t37-2-d1",
        noteId: "t37-2",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "For gas–liquid chromatography (GLC), state what is meant by (i) the stationary phase, (ii) the mobile phase, and (iii) retention time.",
        modelAnswerPoints: [
          "Stationary phase: a high boiling point **non-polar** liquid coated on a solid support inside the column.",
          "Mobile phase: an **unreactive carrier gas** that sweeps vaporised sample through the column.",
          "Retention time: the time from injection until that component’s peak maximum reaches the detector (under fixed flow/temperature/programme).",
        ],
        workedSolution: [
          "In GLC the stationary phase is an involatile liquid layer with a high boiling point, chosen to be non-polar in the syllabus wording, which is spread thinly on an inert particulate support packed or coated inside the column so analytes can dissolve into and out of that film as they are transported by gas.",
          "The mobile phase is a steady stream of carrier gas such as helium or nitrogen that does not intentionally react with the sample at column temperature and simply acts as an inert conveyor pushing vaporised molecules repeatedly through the partitioning zone.",
          "The retention time of a component is the elapsed time between injection and the appearance of its chromatographic peak at the detector, measured consistently to the same peak feature (usually the maximum), and it lengthens when the analyte spends more time dissolved in the stationary liquid rather than the gas phase.",
        ],
        commonMistake:
          "Calling the carrier gas the stationary phase, or describing the stationary phase as the gas.",
        tags: ["definitions", "gc", "retention-time"],
      },
      {
        id: "t37-2-d2",
        noteId: "t37-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which gas is most plausibly described as an ‘unreactive’ carrier for routine GLC?",
        options: [
          { id: "A", text: "Helium or nitrogen" },
          { id: "B", text: "Chlorine" },
          { id: "C", text: "Hydrogen chloride" },
          { id: "D", text: "Fluorine" },
        ],
        correctOptionId: "A",
        explanation:
          "Inert monatomic or diatomic gases that do not attack the column or sample at operating temperature are used as mobile phases.",
        distractorRationale: {
          B: "Chlorine is reactive and would destroy many columns and analytes.",
          C: "HCl is acidic and reactive toward many functional groups.",
          D: "Fluorine is extremely reactive and unsuitable as a carrier.",
        },
        tags: ["gc", "mobile-phase"],
      },
      {
        id: "t37-2-d3",
        noteId: "t37-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "A GLC trace shows two well-separated peaks. Peak A has relative peak area 45 and peak B has relative peak area 135, where areas are proportional to the amounts detected for these two components under the stated conditions. Calculate the percentage by amount of each component in the mixture and state the assumption you make about detector response.",
        modelAnswerPoints: [
          "Total relative area = 45 + 135 = 180.",
          "%A = (45/180) × 100% = 25.0%.",
          "%B = (135/180) × 100% = 75.0%.",
          "Assumes equal response per mole (or per mass, depending on context) so area ∝ amount — syllabus uses proportional areas for percentage composition.",
        ],
        workedSolution: [
          "The syllabus treatment interprets relative peak areas on a chromatogram as proportional to the amounts of each component contributing to those peaks, so the first step is to add the given relative areas to obtain a total measure of 45 + 135 = 180 arbitrary area units representing the whole mixture signal in this two-component case.",
          "The fraction attributed to component A is therefore 45/180, which multiplies to 0.250 and hence 25.0% of the mixture by this area-based measure, while component B accounts for the remaining fraction 135/180 = 0.750, i.e. 75.0%.",
          "These percentages are the mole- or mass-fraction estimates implied by the syllabus when it says areas are proportional to composition, provided the detector responds similarly for the two substances on a per-mole basis in this idealised question.",
          "In real instruments response factors differ between molecules, but for examination-style interpretation you explicitly assume that equal relative area means equal relative amount in the injected mixture unless a response-factor correction is supplied.",
        ],
        commonMistake:
          "Quoting 45% and 135% without normalising areas to sum to 100%.",
        tags: ["gc", "percent-composition", "calculations"],
      },
      {
        id: "t37-2-d4",
        noteId: "t37-2",
        kind: "mcq",
        difficulty: 2,
        stem: "On a column with a non-polar stationary liquid, which analyte is expected to have the **longer** retention time?",
        options: [
          { id: "A", text: "A branched alkane isomer compared with the straight-chain isomer of the same molecular formula." },
          { id: "B", text: "The straight-chain isomer compared with a highly branched isomer of the same formula." },
          { id: "C", text: "Helium carrier gas compared with nitrogen carrier gas (same column, same analytes)." },
          { id: "D", text: "A fully ionised salt compared with a neutral alkane of similar mass." },
        ],
        correctOptionId: "B",
        explanation:
          "A straight-chain alkane has greater surface area for van der Waals contact with a non-polar stationary liquid than a compact branched isomer, so it dissolves more strongly and is retained longer.",
        distractorRationale: {
          A: "Branching reduces effective contact surface; the branched isomer is usually **less** retained than the linear isomer on non-polar phases.",
          C: "Carrier identity changes flow/diffusion but the question targets analyte–stationary interaction, not carrier choice.",
          D: "Involatile salts are not typical GLC analytes without derivatisation; the comparison is chemically unrealistic for basic GLC.",
        },
        tags: ["retention-time", "gc", "intermolecular-forces"],
      },
      {
        id: "t37-2-d5",
        noteId: "t37-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain, in terms of interaction with the stationary phase, why a polar ester generally has a **longer** retention time than a non-polar alkane of similar volatility on a **non-polar** GLC stationary liquid.",
        modelAnswerPoints: [
          "Retention reflects time spent dissolved in the stationary liquid vs swept in gas.",
          "Even on a non-polar phase, polar groups introduce dipole–dipole and stronger van der Waals contributions than a simple alkane.",
          "Stronger overall attraction to the stationary film slows elution → later peak.",
          "Volatility being ‘similar’ removes the crude boiling-point shortcut so intermolecular detail dominates.",
        ],
        workedSolution: [
          "Retention time lengthens whenever a molecule repeatedly transfers into the stationary film and spends less of each passage interval in the mobile gas, so any explanation must compare how strongly each analyte interacts with the high-boiling liquid coating the support.",
          "Although the stationary phase is classified as non-polar, it is not a vacuum: polar ester carbonyl and C–O dipoles can engage in stronger permanent-dipole and dispersion interactions with the hydrocarbon-like stationary film than a purely alkane structure of comparable size, because the electron distribution in the ester offers additional polarisable and dipolar contact motifs along the chain.",
          "Those stronger net attractions mean the ester spends a larger fraction of its residence time partitioned into the stationary phase, so it is carried down the column more slowly and appears at the detector later than the alkane when volatility is stated to be in the same practical range.",
          "If volatility were very different, boiling point would dominate first-pass thinking, but the stem equalises that issue so the examination answer stays focused on stationary-phase interaction strength as the syllabus requires for retention-time explanations.",
        ],
        commonMistake:
          "Claiming polar analytes always elute **before** non-polar ones regardless of stationary polarity — always tie the argument to the phase actually used.",
        tags: ["retention-time", "gc", "intermolecular-forces"],
      },
      {
        id: "t37-2-d6",
        noteId: "t37-2",
        kind: "mcq",
        difficulty: 2,
        stem: "A chromatogram integrates three peaks with relative areas 10 : 15 : 25. What is the approximate mole-percent of the first component?",
        options: [
          { id: "A", text: "20%" },
          { id: "B", text: "10%" },
          { id: "C", text: "33%" },
          { id: "D", text: "40%" },
        ],
        correctOptionId: "A",
        explanation:
          "Total area = 50; first fraction = 10/50 = 0.20 → 20%.",
        distractorRationale: {
          B: "That is the raw ‘10’ label, not a percentage of the mixture.",
          C: "That would correspond to about one third of the total area, which is too high for the smallest peak.",
          D: "That would require the first peak to be the largest contributor, but 10 < 15 < 25.",
        },
        tags: ["percent-composition", "gc"],
      },
      {
        id: "t37-2-d7",
        noteId: "t37-2",
        kind: "structured",
        difficulty: 4,
        marks: 4,
        stem: "Contrast GLC with TLC for (i) physical state of mobile phase, (ii) what ‘retention’ is called on the planar method, and (iii) one requirement that makes a sample suitable for routine GLC.",
        modelAnswerPoints: [
          "GLC mobile phase: unreactive gas. TLC mobile phase: liquid developer.",
          "TLC uses Rf (ratio of distances) rather than a time-based retention time.",
          "GLC needs sufficient volatility / thermal stability to vaporise without decomposing under column conditions.",
        ],
        workedSolution: [
          "Gas–liquid chromatography always uses a gaseous mobile phase, the carrier gas, whereas thin-layer chromatography uses a liquid solvent that permeates the solid stationary layer, so the moving phase differs in physical state even when both methods separate by repeated partitioning.",
          "On a TLC plate retention is reported as an Rf value constructed from distances along the developed plate, whereas in GLC the analogous qualitative idea is captured by retention time measured on a time axis from injection to peak detection under controlled flow.",
          "A practical constraint for GLC is that analytes must be volatile enough to enter the gas phase in the injector and column oven and must not thermally decompose under those temperatures, which is why involatile salts or very large polymers are usually unsuitable without chemical derivatisation, unlike many TLC samples that only need solubility in a liquid eluent.",
        ],
        commonMistake:
          "Saying TLC has a ‘retention time’ identical in definition to GLC — planar chromatography uses distance ratios.",
        tags: ["gc", "tlc", "comparison"],
      },
      {
        id: "t37-2-d8",
        noteId: "t37-2",
        kind: "mcq",
        difficulty: 3,
        stem: "If a component’s peak is sharp and appears early, which statement about its interaction with a standard non-polar GLC stationary phase is most consistent?",
        options: [
          { id: "A", text: "It spends relatively little time dissolved in the stationary liquid." },
          { id: "B", text: "It is irreversibly adsorbed at the injector." },
          { id: "C", text: "It must be more polar than a later-eluted branched alkane." },
          { id: "D", text: "It has infinite solubility in the stationary phase." },
        ],
        correctOptionId: "A",
        explanation:
          "Short retention means the analyte partitions preferentially into the moving gas phase under the conditions used, i.e. weaker retention by the stationary liquid.",
        distractorRationale: {
          B: "Irreversible adsorption would remove the peak or give severe tailing, not a clean early peak.",
          C: "Polarity is not deducible from retention alone without knowing all structures and conditions.",
          D: "Infinite stationary solubility would increase, not decrease, retention time.",
        },
        tags: ["retention-time", "gc"],
      },
      {
        id: "t37-2-d9",
        noteId: "t37-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Three gaseous or readily vaporised hydrocarbons P, Q and R are injected into the same GLC column with non-polar stationary liquid. Retention times increase in the order P < Q < R. Arrange them in order of increasing strength of overall interaction with the stationary phase and link that order to the detector arrival times.",
        modelAnswerPoints: [
          "Weakest interaction: P (shortest retention, arrives first).",
          "Intermediate: Q.",
          "Strongest interaction: R (longest retention, arrives last).",
          "Stronger stationary-phase interaction means more time in the film → later peak.",
        ],
        workedSolution: [
          "Because retention time measures how long the sample band is delayed inside the column, the component P with the smallest retention time spends the smallest average fraction of its journey dissolved in the stationary liquid and therefore exhibits the weakest net attraction to that non-polar film under the stated temperature and flow.",
          "Component Q sits between P and R, so its intermediate retention time implies intermediate partitioning: more stationary dissolution than P but less than R, which matches an intermediate strength of overall dispersion-type interaction with the hydrocarbon-like stationary phase for these related analytes.",
          "Component R, arriving last with the longest retention time, must interact most strongly with the stationary liquid so that each plug of carrier gas carries it forward more slowly, which is exactly the syllabus link between retention time and strength of interaction with the stationary phase.",
          "Thus the order of increasing interaction strength is P < Q < R, which is the same order as increasing retention time and increasing delay before the detector sees each peak maximum.",
        ],
        commonMistake:
          "Reversing the order and claiming the first peak has the strongest stationary-phase binding.",
        tags: ["retention-time", "gc"],
      },
      {
        id: "t37-2-d10",
        noteId: "t37-2",
        kind: "mcq",
        difficulty: 4,
        stem: "Liquid chromatography (LC) variants also appear in the syllabus title ‘Gas / liquid chromatography’. Which pairing is correct for **classical GLC**?",
        options: [
          { id: "A", text: "Mobile: gas; stationary: non-volatile liquid on solid support." },
          { id: "B", text: "Mobile: liquid; stationary: gas trapped in the column." },
          { id: "C", text: "Mobile: supercritical water; stationary: ice." },
          { id: "D", text: "Mobile: packed solid only; stationary: absent." },
        ],
        correctOptionId: "A",
        explanation:
          "GLC is gas mobile phase + liquid stationary phase — the syllabus wording you must reproduce in definitions.",
        distractorRationale: {
          B: "That inverts the GLC phase roles.",
          C: "That is not the standard GLC taught for 9701.",
          D: "A column with no stationary separation phase is not chromatography in the usual sense.",
        },
        tags: ["definitions", "gc"],
      },
    ],
    flashcards: [
      {
        id: "t37-2-f1",
        noteId: "t37-2",
        difficulty: 1,
        front: "GLC stationary phase (syllabus wording)?",
        back: "High boiling point **non-polar** liquid on a solid support.",
        examPhrasing: "Describe the stationary phase used in gas–liquid chromatography.",
        tags: ["gc", "definitions"],
      },
      {
        id: "t37-2-f2",
        noteId: "t37-2",
        difficulty: 1,
        front: "GLC mobile phase?",
        back: "An unreactive carrier gas sweeping sample through the column.",
        examPhrasing: "State what is meant by the mobile phase in GLC.",
        tags: ["gc", "definitions"],
      },
      {
        id: "t37-2-f3",
        noteId: "t37-2",
        difficulty: 2,
        front: "Define retention time.",
        back: "Time from injection until that component’s peak reaches the detector (same measurement convention each time).",
        examPhrasing: "Define retention time in gas chromatography.",
        tags: ["retention-time", "definitions"],
      },
      {
        id: "t37-2-f4",
        noteId: "t37-2",
        difficulty: 2,
        front: "Longer retention time ↔ stationary phase interaction?",
        back: "Stronger interaction with the stationary liquid → longer retention.",
        examPhrasing: "Explain retention time in terms of the stationary phase.",
        tags: ["retention-time", "gc"],
      },
      {
        id: "t37-2-f5",
        noteId: "t37-2",
        difficulty: 3,
        front: "Areas 20 and 80 — percentage composition?",
        back: "20/(20+80)=20% and 80% for the two components (ideal response).",
        examPhrasing: "Interpret peak areas as percentage composition of a mixture.",
        tags: ["percent-composition", "gc"],
      },
      {
        id: "t37-2-f6",
        noteId: "t37-2",
        difficulty: 3,
        front: "Why must GLC analytes be volatile?",
        back: "They must enter the gas phase to be carried by the mobile gas through the column.",
        examPhrasing: "State a key sample requirement for GLC.",
        tags: ["gc"],
      },
      {
        id: "t37-2-f7",
        noteId: "t37-2",
        difficulty: 4,
        front: "Straight-chain vs branched alkane on non-polar GLC — which is retained longer?",
        back: "Straight chain — larger surface area for van der Waals contact with the non-polar liquid.",
        examPhrasing: "Explain a retention difference between hydrocarbon isomers on a non-polar stationary phase.",
        confusionPair: "branching vs retention on non-polar GLC",
        tags: ["retention-time", "isomers"],
      },
      {
        id: "t37-2-f8",
        noteId: "t37-2",
        difficulty: 4,
        front: "TLC Rf vs GLC retention time — conceptual difference?",
        back: "Rf is a distance ratio on a plate; retention time is a clock time to the detector in a column.",
        examPhrasing: "Contrast how retention is reported in TLC and GLC.",
        tags: ["tlc", "gc"],
      },
      {
        id: "t37-2-f9",
        noteId: "t37-2",
        difficulty: 5,
        front: "Why assume peak area ∝ amount when reading % composition?",
        back: "Ideal case: similar detector response per mole; otherwise apply response factors.",
        examPhrasing: "State the assumption when deducing % composition from peak areas.",
        tags: ["percent-composition", "gc"],
      },
      {
        id: "t37-2-f10",
        noteId: "t37-2",
        difficulty: 5,
        front: "Name two common carrier gases.",
        back: "Helium and nitrogen (both relatively inert under normal GLC conditions).",
        examPhrasing: "Give examples of carrier gases used in gas chromatography.",
        tags: ["gc", "mobile-phase"],
      },
    ],
  },

  "t37-3": {
    noteId: "t37-3",
    drills: [
      {
        id: "t37-3-d1",
        noteId: "t37-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "For ethanoic acid CH3COOH, predict how many **chemically distinct carbon environments** appear in a broadband proton-decoupled ^13C NMR spectrum and identify each environment in words.",
        modelAnswerPoints: [
          "Two peaks.",
          "Methyl carbon of the CH3 group in a different environment from the carbonyl carbon.",
          "The two carbons are not related by symmetry in the molecule.",
        ],
        workedSolution: [
          "In a broadband-decoupled ^13C spectrum each magnetically distinct carbon nucleus gives its own signal, and ethanoic acid contains only two carbon atoms that are not symmetry-equivalent because the carboxyl group and the methyl group occupy clearly different bonding environments.",
          "Therefore two peaks are expected, one arising from the methyl carbon attached to three hydrogens and singly bonded to the carbonyl carbon, and the other arising from the carbonyl carbon doubly bonded to oxygen and singly bonded to the methyl carbon and hydroxyl group.",
          "There is no molecular symmetry operation that interchanges these two carbons while leaving the structure unchanged, so the count of lines is two, which is the standard prediction question style for a simple functionalised two-carbon acid.",
        ],
        commonMistake:
          "Reporting four peaks by confusing ^13C with proton environments, or missing the carbonyl as a separate environment.",
        tags: ["c13-nmr", "peak-count"],
      },
      {
        id: "t37-3-d2",
        noteId: "t37-3",
        kind: "mcq",
        difficulty: 1,
        stem: "How many ^13C NMR signals does benzene C6H6 show?",
        options: [
          { id: "A", text: "1" },
          { id: "B", text: "3" },
          { id: "C", text: "6" },
          { id: "D", text: "12" },
        ],
        correctOptionId: "A",
        explanation:
          "All six aromatic carbons are symmetry-equivalent in the planar regular hexagon, so only one ^13C environment exists.",
        distractorRationale: {
          B: "Three would imply a lower symmetry ring pattern, not benzene.",
          C: "Six distinct lines would require all carbons inequivalent, which is false for benzene.",
          D: "Twelve confuses atoms with environments and ignores symmetry.",
        },
        tags: ["c13-nmr", "symmetry"],
      },
      {
        id: "t37-3-d3",
        noteId: "t37-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A molecule has molecular formula C3H6O. Its proton-decoupled ^13C spectrum shows **three** lines. Deduce whether propanone (acetone) or propanal is consistent with this spectrum and justify your answer by counting carbon environments for each isomer.",
        modelAnswerPoints: [
          "Propanal CH3CH2CHO has three inequivalent carbons → three ^13C signals — consistent.",
          "Propanone (CH3)2C=O has two carbon environments (two equivalent methyls + carbonyl) → two signals — inconsistent.",
          "Therefore the spectrum matches propanal, not propanone.",
        ],
        workedSolution: [
          "Start from the observation of three distinct ^13C resonances, which means three magnetically non-equivalent carbon sites in the actual molecule under rapid conditions on the NMR timescale.",
          "Propanal contains a methyl group, a CH2 group adjacent to the CHO unit, and a distinct aldehyde carbonyl carbon; none of these three positions is related to another by symmetry, so three separate environments and three peaks are predicted, matching the data.",
          "Propanone instead possesses two methyl groups attached to the same carbonyl carbon in a symmetric way, making those two methyl carbons equivalent, which collapses the prediction to only two ^13C environments (one line for the pair of methyls and one for the carbonyl), contradicting the experimental three-line spectrum.",
          "Hence the C3H6O isomer consistent with three ^13C signals is propanal rather than propanone, illustrating how carbon-13 peak counting distinguishes simple carbonyl isomers at this syllabus level.",
        ],
        commonMistake:
          "Assuming different functional-group isomers always give the same number of ^13C peaks without checking symmetry.",
        tags: ["c13-nmr", "isomers", "deduction"],
      },
      {
        id: "t37-3-d4",
        noteId: "t37-3",
        kind: "mcq",
        difficulty: 2,
        stem: "How many ^13C signals does 2-chloropropane (CH3CHClCH3) show?",
        options: [
          { id: "A", text: "2" },
          { id: "B", text: "3" },
          { id: "C", text: "1" },
          { id: "D", text: "6" },
        ],
        correctOptionId: "A",
        explanation:
          "The two terminal methyl groups are symmetry-related through the CHCl centre → one methyl signal + one CH signal = 2 peaks.",
        distractorRationale: {
          B: "There are only three carbons total but two methyls are equivalent.",
          C: "The CHCl carbon is not equivalent to the methyl carbons.",
          D: "Six would confuse with proton count or ignore symmetry.",
        },
        tags: ["c13-nmr", "symmetry"],
      },
      {
        id: "t37-3-d5",
        noteId: "t37-3",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem: "Explain why a carbonyl carbon in a simple ketone usually appears **further downfield** (higher δ) in ^13C NMR than an sp^3 saturated carbon in the same molecule.",
        modelAnswerPoints: [
          "Chemical shift reflects electron density / magnetic shielding around the nucleus.",
          "The carbonyl carbon is sp^2 hybridised with a polar C=O bond; partial positive charge on carbon deshields it.",
          "π-bonding framework and attached oxygen withdraw electron density compared with a saturated C–C/C–H environment.",
        ],
        workedSolution: [
          "Chemical shift positions in carbon-13 NMR track how effectively electrons shield the nucleus from the external magnetic field, so environments with lower local electron density resonate at higher δ values on the usual spectrum scale.",
          "In a ketone the carbonyl carbon is doubly bonded to an electronegative oxygen atom, which polarises the bond and leaves that carbon relatively electron-deficient compared with a tetrahedral sp^3 carbon bearing only σ bonds to carbon and hydrogen.",
          "That deshielding, together with the different hybridisation and anisotropic magnetic effects associated with the π system, moves the carbonyl resonance downfield from the typical saturated alkyl carbon lines in the same spectrum, which is the qualitative reasoning the syllabus expects when comparing peak positions in simple molecules.",
        ],
        commonMistake:
          "Saying ‘heavier atoms resonate lower’ without mentioning electron withdrawal / deshielding.",
        tags: ["c13-nmr", "chemical-shift"],
      },
      {
        id: "t37-3-d6",
        noteId: "t37-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Methane CH4 versus ethane C2H6 — how many ^13C environments in each?",
        options: [
          { id: "A", text: "CH4: 1; C2H6: 1" },
          { id: "B", text: "CH4: 4; C2H6: 2" },
          { id: "C", text: "CH4: 1; C2H6: 2" },
          { id: "D", text: "CH4: 2; C2H6: 3" },
        ],
        correctOptionId: "A",
        explanation:
          "All hydrogens are equivalent on methane; ethane has symmetric CH3 groups related by rotation averaging — both give a single carbon environment.",
        distractorRationale: {
          B: "Four environments would treat each proton separately — wrong spectroscopy.",
          C: "Ethane’s two carbons are equivalent by symmetry.",
          D: "Neither molecule has multiple inequivalent carbons.",
        },
        tags: ["c13-nmr", "symmetry"],
      },
      {
        id: "t37-3-d7",
        noteId: "t37-3",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem: "Methylbenzene (toluene) has formula C7H8. Predict the number of ^13C NMR signals and assign each distinct carbon type (e.g. methyl, ipso aromatic, etc.), using the plane of symmetry of the monosubstituted ring.",
        modelAnswerPoints: [
          "Five signals.",
          "One line for the methyl carbon.",
          "Four distinct aromatic carbons: ipso to CH3, ortho pair equivalent, meta pair equivalent, unique para.",
        ],
        workedSolution: [
          "Toluene consists of a methyl group attached to a benzene ring, and the question requires counting symmetry-distinct carbons in the proton-decoupled ^13C spectrum rather than proton environments.",
          "The methyl carbon is unique and unrelated by symmetry to any ring carbon, so it contributes its own resonance separate from all aromatic lines.",
          "The monosubstituted benzene ring has a vertical mirror plane through the substituent and the para carbon, which makes the two ortho ring carbons symmetry-equivalent to each other and the two meta ring carbons symmetry-equivalent to each other, while the ipso carbon bonded to the methyl and the para carbon opposite the substituent each occupy unique positions.",
          "Adding these aromatic types gives four distinct aromatic ^13C environments plus the methyl peak, which totals five signals, matching the standard teaching picture for methylbenzene at A Level.",
        ],
        commonMistake:
          "Claiming six aromatic lines — forgetting pairwise equivalence of ortho and meta carbons in toluene.",
        tags: ["c13-nmr", "symmetry", "aromatic"],
      },
      {
        id: "t37-3-d8",
        noteId: "t37-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Which compound gives **three** distinct peaks in broadband-decoupled ^13C NMR?",
        options: [
          { id: "A", text: "Propanal (CH3CH2CHO)" },
          { id: "B", text: "Propanone ((CH3)2C=O)" },
          { id: "C", text: "Ethene" },
          { id: "D", text: "Benzene" },
        ],
        correctOptionId: "A",
        explanation:
          "Propanal has three inequivalent carbons (CH3, CH2, CHO). Propanone has two environments (equivalent methyls + carbonyl). Ethene and benzene each show a single ^13C environment.",
        distractorRationale: {
          B: "The two methyl groups are symmetry-equivalent, so only two ^13C lines appear.",
          C: "Both sp^2 carbons of ethene are equivalent → one signal.",
          D: "All six aromatic carbons are equivalent in benzene → one signal.",
        },
        tags: ["c13-nmr", "peak-count"],
      },
      {
        id: "t37-3-d9",
        noteId: "t37-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A compound Z has molecular formula C2H6O. Its proton-decoupled ^13C NMR spectrum shows **exactly two** carbon signals. Deduce whether Z is ethanol or methoxymethane (dimethyl ether) and justify your answer by counting symmetry-distinct carbon environments for each isomer.",
        modelAnswerPoints: [
          "Ethanol CH3CH2OH has two inequivalent carbons (CH3 and CH2) → two ^13C signals — consistent.",
          "Dimethyl ether CH3OCH3 has two methyl groups related by symmetry → one ^13C environment → one signal — inconsistent.",
          "Therefore Z is ethanol.",
        ],
        workedSolution: [
          "The molecular formula C2H6O covers both ethanol and dimethyl ether, so the spectroscopic data must decide between them on the basis of symmetry in the carbon skeleton.",
          "In ethanol the carbon of the methyl group is bonded to three hydrogens and to a CH2 group, whereas the CH2 carbon is bonded to two hydrogens, an oxygen and the methyl carbon; no symmetry operation interchanges these two carbons, so two distinct ^13C resonances are expected, matching the observation of exactly two lines.",
          "In dimethyl ether a plane of symmetry bisects the C–O–C unit and interchanges the two methyl groups, making those methyl carbons magnetically equivalent, which collapses the prediction to a single ^13C environment and therefore only one peak, contradicting the two-line spectrum.",
          "Hence compound Z must be ethanol rather than dimethyl ether, which is a standard illustration of how ^13C peak counting distinguishes oxygen positional isomers at this level.",
        ],
        commonMistake:
          "Forgetting the mirror symmetry of dimethyl ether and predicting two methyl peaks there.",
        tags: ["c13-nmr", "isomers", "deduction"],
      },
      {
        id: "t37-3-d10",
        noteId: "t37-3",
        kind: "mcq",
        difficulty: 4,
        stem: "How many ^13C NMR signals does **butanone** (CH3CH2COCH3) show?",
        options: [
          { id: "A", text: "3" },
          { id: "B", text: "4" },
          { id: "C", text: "2" },
          { id: "D", text: "5" },
        ],
        correctOptionId: "B",
        explanation:
          "The ethyl CH3, ethyl CH2, carbonyl carbon, and acetyl CH3 are all in different environments (the two methyl groups are not symmetry-related), so four ^13C lines appear.",
        distractorRationale: {
          A: "Three would require two carbons to be accidentally equivalent; they are not in butanone.",
          C: "Two peaks correspond to propanone ((CH3)2C=O), not butanone.",
          D: "The molecule contains only four carbon atoms, so five signals are impossible.",
        },
        tags: ["c13-nmr", "peak-count"],
      },
    ],
    flashcards: [
      {
        id: "t37-3-f1",
        noteId: "t37-3",
        difficulty: 1,
        front: "What does each peak in a broadband-decoupled ^13C spectrum represent?",
        back: "One magnetically distinct carbon environment (symmetry-equivalent carbons share a peak).",
        examPhrasing: "State what is meant by a carbon environment in ^13C NMR.",
        tags: ["c13-nmr", "definitions"],
      },
      {
        id: "t37-3-f2",
        noteId: "t37-3",
        difficulty: 1,
        front: "How many ^13C signals for benzene?",
        back: "One — all six ring carbons are equivalent.",
        examPhrasing: "Predict the number of peaks in the ^13C NMR spectrum of benzene.",
        tags: ["c13-nmr", "symmetry"],
      },
      {
        id: "t37-3-f3",
        noteId: "t37-3",
        difficulty: 2,
        front: "Ethanoic acid CH3COOH — number of ^13C peaks?",
        back: "Two (methyl carbon and carboxyl carbon).",
        examPhrasing: "Predict the number of ^13C NMR signals for ethanoic acid.",
        tags: ["c13-nmr", "peak-count"],
      },
      {
        id: "t37-3-f4",
        noteId: "t37-3",
        difficulty: 2,
        front: "Why does a ketone carbonyl carbon appear at higher δ than an alkyl sp^3 carbon?",
        back: "Lower electron density / deshielding from the polar C=O bond and sp^2 environment.",
        examPhrasing: "Explain why a carbonyl carbon is further downfield than an alkyl carbon in ^13C NMR.",
        tags: ["c13-nmr", "chemical-shift"],
      },
      {
        id: "t37-3-f5",
        noteId: "t37-3",
        difficulty: 3,
        front: "C3H6O with three ^13C lines — propanal or propanone?",
        back: "Propanal (three inequivalent carbons); propanone would give only two lines.",
        examPhrasing: "Use ^13C data to distinguish carbonyl isomers with the same molecular formula.",
        confusionPair: "propanal vs propanone ^13C peak count",
        tags: ["c13-nmr", "deduction"],
      },
      {
        id: "t37-3-f6",
        noteId: "t37-3",
        difficulty: 3,
        front: "2-chloropropane (CH3CHClCH3) — ^13C signals?",
        back: "Two (equivalent terminal methyls + central CHCl).",
        examPhrasing: "Predict the number of ^13C environments in 2-chloropropane.",
        tags: ["c13-nmr", "symmetry"],
      },
      {
        id: "t37-3-f7",
        noteId: "t37-3",
        difficulty: 4,
        front: "Toluene (methylbenzene) — how many ^13C lines?",
        back: "Five (methyl + four distinct aromatic carbons by symmetry).",
        examPhrasing: "Predict the number of ^13C NMR signals for methylbenzene.",
        tags: ["c13-nmr", "aromatic"],
      },
      {
        id: "t37-3-f8",
        noteId: "t37-3",
        difficulty: 4,
        front: "Ethanol vs dimethyl ether — ^13C peak count?",
        back: "Ethanol: 2; dimethyl ether: 1 (symmetrical).",
        examPhrasing: "Distinguish C2H6O isomers using ^13C NMR.",
        tags: ["c13-nmr", "isomers"],
      },
      {
        id: "t37-3-f9",
        noteId: "t37-3",
        difficulty: 5,
        front: "Methane vs ethane — ^13C environments?",
        back: "Each gives one signal (ethane: two equivalent carbons by rotation/symmetry).",
        examPhrasing: "State how many ^13C peaks methane and ethane each show.",
        tags: ["c13-nmr", "symmetry"],
      },
      {
        id: "t37-3-f10",
        noteId: "t37-3",
        difficulty: 5,
        front: "Butanone CH3CH2COCH3 — ^13C signals?",
        back: "Four — all four carbons are in different environments.",
        examPhrasing: "Predict the number of ^13C NMR signals for butanone.",
        tags: ["c13-nmr", "peak-count"],
      },
    ],
  },

  "t37-4": {
    noteId: "t37-4",
    drills: [
      {
        id: "t37-4-d1",
        noteId: "t37-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Describe the use of tetramethylsilane (TMS) as the reference compound in ^1H (proton) NMR spectroscopy, including why its chemical shift is defined as δ = 0 and two reasons why it is a practical standard for organic samples.",
        modelAnswerPoints: [
          "Chemical shifts δ are reported relative to TMS assigned as zero on the δ scale.",
          "TMS has twelve equivalent shielded methyl protons giving a single sharp peak upfield.",
          "It is chemically inert, volatile, and soluble in many organic solvents so a trace can be added without reacting.",
        ],
        workedSolution: [
          "In proton NMR the horizontal chemical-shift axis is calibrated so that the signal from the silicon-bound methyl protons of tetramethylsilane is taken as the reference point δ = 0, and all other resonances are quoted as parts per million downfield or upfield of that standard under the same field and solvent conditions.",
          "TMS is chosen partly because all twelve protons are chemically equivalent in the highly symmetrical (CH3)4Si molecule, producing one very sharp singlet that is easy to recognise and lies at unusually high shielding (low δ) compared with most organic analytes, which keeps sample peaks on the positive-δ side of the spectrum.",
          "It is also volatile and chemically inert toward typical laboratory reagents at room temperature, and it dissolves in common NMR solvents as a small additive, which means a tiny amount can be mixed into the tube to mark the reference frequency without interfering with the chemistry of the compound being studied.",
        ],
        commonMistake:
          "Claiming TMS is used because it is strongly deshielded — it is the opposite; it is strongly shielded and defined as zero.",
        tags: ["proton-nmr", "tms", "definitions"],
      },
      {
        id: "t37-4-d2",
        noteId: "t37-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain why deuterated solvents such as CDCl3 are used when recording a proton (^1H) NMR spectrum of an organic compound, whereas ordinary chloroform CHCl3 would be unsuitable as the bulk solvent.",
        modelAnswerPoints: [
          "The spectrometer detects ^1H nuclei; CDCl3 contributes essentially no ^1H signal at high isotopic purity.",
          "CHCl3 would give a large solvent proton peak that swamps or overlaps analyte signals.",
          "Deuterium is NMR-active at a different frequency so lock/shim can use the deuterium signal without masking proton spectra.",
        ],
        workedSolution: [
          "Proton NMR observes hydrogen-1 nuclei only at the proton channel frequency, so the solvent should contribute minimal ^1H magnetisation if you want clean spectra of the dissolved analyte at typical concentrations.",
          "Deuterated chloroform replaces almost all C–H bonds with C–D bonds, and at the isotopic purity used in NMR solvents the residual ^1H impurity is tiny, whereas neat CHCl3 would present a huge sharp resonance from its single proton on every solvent molecule, dominating the spectrum and overlapping many sample peaks.",
          "The deuterium nuclei in CDCl3 are instead used for the field-frequency lock channel in Fourier-transform instruments, which stabilises the magnetic field while leaving the proton spectrum window essentially free except for a known small residual CHCl3 impurity peak that students learn to ignore or integrate around.",
        ],
        commonMistake:
          "Saying deuterium is ‘NMR-inactive’ — it is active but at a different frequency; the point is it is not observed on the ^1H channel.",
        tags: ["proton-nmr", "deuterated-solvent", "cdcl3"],
      },
      {
        id: "t37-4-d3",
        noteId: "t37-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Describe how D2O exchange can be used to identify O–H and N–H protons in a proton (^1H) NMR spectrum. State what change you expect in the spectrum when a few drops of D2O are shaken with an acidic OH-containing sample in a suitable solvent system.",
        modelAnswerPoints: [
          "Labile O–H / N–H protons exchange with deuterons from D2O forming OD/ND and HDO.",
          "After exchange those exchangeable ^1H sites are largely replaced by ^2H, which is not observed on a ^1H spectrum.",
          "The corresponding broad OH/NH signal disappears or greatly diminishes; a residual HDO peak may appear near δ ~4.7 depending on conditions.",
        ],
        workedSolution: [
          "Protons attached to oxygen or nitrogen in many functional groups are sufficiently acidic or labile that they can exchange rapidly with deuterium oxide when D2O is introduced, converting R–OH into R–OD (and generating HDO) or protonated amine/amide N–H sites into N–D analogues in a dynamic equilibrium that averages on the NMR timescale.",
          "Because the spectrometer is tuned to detect ^1H only, any site that loses its proton to the solvent pool and becomes deuterated no longer contributes intensity to the proton spectrum, which is exactly how exchange is exploited as a qualitative assignment tool.",
          "In a teaching experiment you therefore expect broad OH or NH resonances that were visible before D2O addition to shrink or vanish after shaking and re-measurement, while most C–H signals remain essentially unchanged, and a small HDO resonance may appear at a characteristic chemical shift traceable to residual water isotopologues.",
        ],
        commonMistake:
          "Claiming **all** peaks disappear — only exchangeable protons are removed from the ^1H spectrum.",
        tags: ["proton-nmr", "d2o-exchange"],
      },
      {
        id: "t37-4-d4",
        noteId: "t37-4",
        kind: "mcq",
        difficulty: 2,
        stem: "For a first-order alkyl chain fragment –CH2–CH3, how many lines does each group show in ^1H NMR due to coupling to the **other** group (ignore long-range couplings)?",
        options: [
          { id: "A", text: "CH2 quartet; CH3 triplet" },
          { id: "B", text: "CH2 triplet; CH3 quartet" },
          { id: "C", text: "CH2 doublet; CH3 doublet" },
          { id: "D", text: "Both singlets" },
        ],
        correctOptionId: "A",
        explanation:
          "The CH2 protons see 3 equivalent neighbours on the attached methyl carbon → n + 1 = 4 (quartet). The CH3 protons see 2 neighbours on CH2 → n + 1 = 3 (triplet).",
        distractorRationale: {
          B: "That swaps the multiplicity patterns for the two groups.",
          C: "Doublets would imply only one proton neighbour for each set.",
          D: "Singlets would mean no coupling, which is false for an ethyl fragment.",
        },
        tags: ["proton-nmr", "splitting", "n-plus-one"],
      },
      {
        id: "t37-4-d5",
        noteId: "t37-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "For iodomethane CH3I, predict the approximate chemical shift region of the methyl protons in ^1H NMR (relative to TMS) and the splitting pattern, giving reasons in terms of electronegativity / deshielding and neighbour protons.",
        modelAnswerPoints: [
          "Attached iodine is very polarisable and strongly deshields adjacent protons → δ higher than a simple alkane (typically a few ppm downfield of TMS, in the functionalised methyl region).",
          "All three protons are equivalent on the NMR timescale.",
          "There are no vicinal proton neighbours on carbon, so the signal is a singlet (n + 1 with n = 0).",
        ],
        workedSolution: [
          "The methyl group in iodomethane is bonded directly to iodine, a heavy halogen whose polarisability withdraws electron density from the C–H bonds through the σ framework and also contributes to deshielding through neighbour anisotropy effects, so the resonance is found further downfield from tetramethylsilane than a hydrocarbon methyl such as in ethane.",
          "All three hydrogen atoms are attached to the same carbon and are related by the threefold rotational symmetry of the CH3 group, so they are chemically equivalent and give a single averaged chemical shift rather than separate lines.",
          "Because there are no other hydrogen-bearing carbons bonded to that methyl carbon, there are no vicinal ^1H coupling partners, so the multiplicity follows the n + 1 rule with n = 0 and the peak remains a singlet in a simple first-order picture.",
        ],
        commonMistake:
          "Predicting a quartet by miscounting neighbours that are not attached to the **same** carbon as the observed protons.",
        tags: ["proton-nmr", "chemical-shift", "splitting"],
      },
      {
        id: "t37-4-d6",
        noteId: "t37-4",
        kind: "mcq",
        difficulty: 2,
        stem: "Which chemical shift range is **most typical** for an aldehyde proton (–CHO) in ^1H NMR relative to TMS?",
        options: [
          { id: "A", text: "δ ≈ 9–10" },
          { id: "B", text: "δ ≈ 0–1" },
          { id: "C", text: "δ ≈ 3–4" },
          { id: "D", text: "δ ≈ 6–8 only (never above 8)" },
        ],
        correctOptionId: "A",
        explanation:
          "The aldehyde proton is strongly deshielded by the anisotropic carbonyl group and lies well downfield, commonly around δ 9–10 in simple aldehydes.",
        distractorRationale: {
          B: "That is the TMS / highly shielded alkyl region, not an aldehyde.",
          C: "That region is more typical of protons α to electronegative atoms in ethers/esters, not the formyl proton itself.",
          D: "Aldehyde protons routinely appear beyond δ 8; aromatic protons occupy ~6.5–8 but aldehyde is further downfield.",
        },
        tags: ["proton-nmr", "chemical-shift"],
      },
      {
        id: "t37-4-d7",
        noteId: "t37-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A simple ^1H spectrum shows signals at δ ≈ 1.1 (relative area 3), δ ≈ 2.4 (relative area 2) and δ ≈ 9.8 (relative area 1). Deduce a plausible structure consistent with the integration, typical chemical-shift regions, and first-order splitting patterns (treat the low-field signal as an aldehyde proton).",
        modelAnswerPoints: [
          "Integration 3 : 2 : 1 matches CH3, CH2, and aldehyde H in CH3CH2CHO (propanal).",
          "δ ~9–10 for 1H is characteristic of an aldehyde proton deshielded by the C=O group.",
          "Methyl triplet: adjacent CH2 has two equivalent protons → n + 1 = 3.",
          "Methylene quartet: adjacent CH3 has three equivalent protons → n + 1 = 4.",
          "Aldehyde proton shows coupling to the adjacent CH2 (commonly described as a triplet at introductory level).",
        ],
        workedSolution: [
          "The integration ratio 3 : 2 : 1 immediately suggests a fragment containing a three-proton methyl, a two-proton methylene, and a one-proton site, which matches the proton inventory of propanal CH3CH2CHO if the single proton is the aldehyde hydrogen.",
          "The resonance near δ 9.8 lies in the region expected for an aldehyde proton attached to a carbonyl carbon, where strong deshielding from the anisotropic C=O π system pulls the signal far downfield from typical alkyl positions.",
          "The upfield three-proton signal near δ 1.1 is characteristic of a methyl group not directly bonded to very electronegative atoms; it is split into a triplet because the attached CH2 group bears two magnetically equivalent protons, giving n + 1 = 3 for first-order coupling.",
          "The two-proton signal near δ 2.4 lies slightly deshielded compared with a simple alkane methyl because the CH2 is α to an electron-withdrawing carbonyl group, and it appears as a quartet because the neighbouring methyl supplies three equivalent coupling partners, so n + 1 = 4.",
          "The aldehyde proton is coupled to the adjacent CH2 protons and therefore shows further fine structure (commonly analysed as a triplet at introductory level), completing a self-consistent assignment to propanal under the data given.",
        ],
        commonMistake:
          "Assigning the aldehyde proton to the δ ~1 region or calling the methyl a quartet through miscounting neighbour protons.",
        tags: ["proton-nmr", "deduction", "integration", "splitting"],
      },
      {
        id: "t37-4-d8",
        noteId: "t37-4",
        kind: "mcq",
        difficulty: 3,
        stem: "A broad ^1H resonance at δ ~4–6 that disappears after D2O shake is most likely due to which type of proton?",
        options: [
          { id: "A", text: "Exchangeable O–H or N–H" },
          { id: "B", text: "Aromatic C–H" },
          { id: "C", text: "TMS reference protons" },
          { id: "D", text: "Vinylic =C–H in a non-polar alkene" },
        ],
        correctOptionId: "A",
        explanation:
          "Labile OH/NH protons exchange with D2O and are removed from the ^1H spectrum; aromatic and vinylic C–H do not exchange on that timescale.",
        distractorRationale: {
          B: "Aromatic protons do not vanish with D2O; they remain as sharp multiplets near δ 6–8.",
          C: "TMS is added deliberately and does not exchange away with D2O in this context.",
          D: "Alkenic C–H is not acidic enough to exchange with D2O under simple shake conditions.",
        },
        tags: ["proton-nmr", "d2o-exchange"],
      },
      {
        id: "t37-4-d9",
        noteId: "t37-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "For ethyl ethanoate CH3COOCH2CH3, predict the **relative integration ratio** of the three resolved proton environments in the ^1H spectrum and assign each ratio to a fragment (acyl methyl, oxymethylene, or ethyl methyl). State the expected splitting pattern of each signal in a simple first-order analysis.",
        modelAnswerPoints: [
          "Integration ratio 3 : 2 : 3 for acyl CH3 : OCH2 : terminal CH3 (same total as molecular formula).",
          "Acyl methyl is a singlet (no vicinal H on the carbonyl carbon).",
          "OCH2 is a quartet (neighbouring CH3 gives n + 1 = 4).",
          "Terminal CH3 is a triplet (neighbouring CH2 gives n + 1 = 3).",
        ],
        workedSolution: [
          "Ethyl ethanoate contains six aliphatic protons arranged as three chemically distinct groups: the acetyl methyl attached to the carbonyl carbon, the methylene group bonded to oxygen, and the terminal methyl of the ethyl fragment, with populations three, two and three respectively, so the relative integration ratio read off well-separated peaks should be 3 : 2 : 3 when baselines are corrected.",
          "The acetyl methyl protons are attached to a carbonyl carbon that bears no hydrogen atoms, so there are no vicinal ^1H coupling partners on the adjacent atom in the usual sense and the resonance appears as a singlet at introductory level.",
          "The oxymethylene protons are adjacent to the ethyl methyl group’s carbon which bears three equivalent hydrogens, so n + 1 predicts a quartet for the CH2 signal, while those methyl protons see the CH2 as two equivalent neighbours and therefore appear as a triplet.",
          "Together the integration and splitting pattern distinguishes the ester from isomeric arrangements that would give different multiplicity combinations even when raw molecular formulas look similar.",
        ],
        commonMistake:
          "Calling the acetyl methyl a quartet by coupling across the oxygen to CH2 — coupling is transmitted through bonds; the carbonyl carbon has no H, so singlet.",
        tags: ["proton-nmr", "integration", "splitting"],
      },
      {
        id: "t37-4-d10",
        noteId: "t37-4",
        kind: "mcq",
        difficulty: 4,
        stem: "The ^1H NMR spectrum of benzene C6H6 shows one signal. Which statement best explains the multiplicity and chemical-shift environment?",
        options: [
          { id: "A", text: "All six aromatic protons are equivalent by symmetry → singlet; δ typically ~7.3 due to ring current deshielding." },
          { id: "B", text: "Each proton couples to five neighbours to give a sextet at δ ~2." },
          { id: "C", text: "Benzene shows three separate doublets because there are three types of π bond." },
          { id: "D", text: "Benzene protons are absent from ^1H NMR because they exchange with CDCl3." },
        ],
        correctOptionId: "A",
        explanation:
          "Equivalent aromatic protons collapse to one chemical shift; coupling between equivalent spins does not split the line in the usual simple picture, giving a singlet near δ 7.3.",
        distractorRationale: {
          B: "Benzene aromatic protons are not at δ ~2, and the simple equivalence argument gives a singlet, not a sextet.",
          C: "π-bond types do not create three distinct proton environments in benzene.",
          D: "Aromatic C–H does not exchange with chloroform under normal conditions.",
        },
        tags: ["proton-nmr", "aromatic", "symmetry"],
      },
    ],
    flashcards: [
      {
        id: "t37-4-f1",
        noteId: "t37-4",
        difficulty: 1,
        front: "What is TMS in proton NMR?",
        back: "Tetramethylsilane (CH3)4Si — reference set to δ = 0; inert volatile singlet.",
        examPhrasing: "Describe the use of TMS in ^1H NMR.",
        tags: ["proton-nmr", "tms"],
      },
      {
        id: "t37-4-f2",
        noteId: "t37-4",
        difficulty: 1,
        front: "Why use CDCl3 not CHCl3 as NMR solvent?",
        back: "Avoids a huge solvent ^1H peak; deuterium used for lock.",
        examPhrasing: "State why deuterated solvents are used in proton NMR.",
        tags: ["proton-nmr", "cdcl3"],
      },
      {
        id: "t37-4-f3",
        noteId: "t37-4",
        difficulty: 2,
        front: "What does D2O shake do to an O–H peak?",
        back: "Exchanges OH for OD — the ^1H signal disappears or shrinks (labile H removed).",
        examPhrasing: "Describe identifying O–H / N–H protons using D2O.",
        tags: ["proton-nmr", "d2o-exchange"],
      },
      {
        id: "t37-4-f4",
        noteId: "t37-4",
        difficulty: 2,
        front: "n + 1 rule — what is n?",
        back: "Number of equivalent ^1H atoms on **directly bonded** neighbour carbons (syllabus: singlet–multiplet).",
        examPhrasing: "Predict multiplicity using the n + 1 rule.",
        tags: ["proton-nmr", "splitting"],
      },
      {
        id: "t37-4-f5",
        noteId: "t37-4",
        difficulty: 3,
        front: "Ethyl fragment –CH2CH3 first-order pattern?",
        back: "CH3 triplet; CH2 quartet.",
        examPhrasing: "State the splitting pattern for an ethyl group in ^1H NMR.",
        confusionPair: "triplet vs quartet on ethyl",
        tags: ["proton-nmr", "splitting"],
      },
      {
        id: "t37-4-f6",
        noteId: "t37-4",
        difficulty: 3,
        front: "Typical aldehyde proton δ range?",
        back: "About δ 9–10 (strongly deshielded).",
        examPhrasing: "Give the usual chemical-shift region for an aldehyde proton.",
        tags: ["proton-nmr", "chemical-shift"],
      },
      {
        id: "t37-4-f7",
        noteId: "t37-4",
        difficulty: 4,
        front: "What does peak **area** (integration) tell you in ^1H NMR?",
        back: "Relative numbers of protons in each environment (ratio of H counts).",
        examPhrasing: "Explain how integration is used in proton NMR.",
        tags: ["proton-nmr", "integration"],
      },
      {
        id: "t37-4-f8",
        noteId: "t37-4",
        difficulty: 4,
        front: "Ethyl ethanoate — acetyl CH3 multiplicity?",
        back: "Singlet (no H on the bonded carbonyl carbon).",
        examPhrasing: "Predict the splitting of the acetyl methyl in ethyl ethanoate.",
        tags: ["proton-nmr", "splitting"],
      },
      {
        id: "t37-4-f9",
        noteId: "t37-4",
        difficulty: 5,
        front: "Benzene ^1H NMR — how many signals and approximate δ?",
        back: "One singlet; aromatic region ~δ 7.3 (ring current).",
        examPhrasing: "Describe the ^1H NMR spectrum of benzene.",
        tags: ["proton-nmr", "aromatic"],
      },
      {
        id: "t37-4-f10",
        noteId: "t37-4",
        difficulty: 5,
        front: "When does a proton environment show a **multiplet** beyond quartet in basic syllabi?",
        back: "Many non-equivalent neighbours or overlapping couplings / second-order effects — syllabus lists multiplet as catch-all.",
        examPhrasing: "What is meant by a multiplet in proton NMR?",
        tags: ["proton-nmr", "splitting"],
      },
    ],
  },
};
