import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC18_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t18-1": {
    noteId: "t18-1",
    drills: [
      {
        id: "t18-1-d1",
        noteId: "t18-1",
        kind: "mcq",
        difficulty: 1,
        stem: "What is the direction of the electric field at a point?",
        options: [
          { id: "A", text: "Direction of force on a positive test charge" },
          { id: "B", text: "Direction of force on a negative test charge" },
          { id: "C", text: "Direction of electron drift velocity" },
          { id: "D", text: "Direction of decreasing potential only" },
        ],
        correctOptionId: "A",
        explanation: "Electric field direction is defined by the force on a small positive test charge.",
        distractorRationale: {
          B: "A negative test charge would feel force opposite to field direction.",
          C: "Electron drift is opposite to conventional current and does not define E.",
          D: "Potential gradient is related, but definition is via force per unit positive charge.",
        },
        tags: ["electric-field", "definition", "field-direction"],
      },
      {
        id: "t18-1-d2",
        noteId: "t18-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which statement about electric field lines is correct?",
        options: [
          { id: "A", text: "They can cross at points of zero field" },
          { id: "B", text: "Their density indicates field strength" },
          { id: "C", text: "They start on negative charges and end on positive charges" },
          { id: "D", text: "They represent possible paths of electrons only" },
        ],
        correctOptionId: "B",
        explanation:
          "Closer field lines indicate stronger electric field; crossing is impossible because field direction is unique at each point.",
        distractorRationale: {
          C: "Field lines run from positive to negative, not vice versa.",
          D: "Field lines are conceptual direction maps, not literal particle tracks.",
        },
        tags: ["field-lines", "representation", "strength"],
      },
      {
        id: "t18-1-d3",
        noteId: "t18-1",
        kind: "mcq",
        difficulty: 3,
        stem: "A charge experiences force 2.4 x 10^-5 N in an electric field. If the charge is 3.0 x 10^-9 C, field strength is",
        options: [
          { id: "A", text: "8.0 x 10^3 N C^-1" },
          { id: "B", text: "7.2 x 10^-14 N C^-1" },
          { id: "C", text: "8.0 x 10^-15 N C^-1" },
          { id: "D", text: "7.2 x 10^4 N C^-1" },
        ],
        correctOptionId: "A",
        explanation: "E = F/q = (2.4 x 10^-5)/(3.0 x 10^-9) = 8.0 x 10^3 N C^-1.",
        distractorRationale: {
          B: "This comes from multiplying F and q instead of dividing.",
          C: "Power-of-ten handling is incorrect by many orders of magnitude.",
          D: "This may result from using q = 3.3 x 10^-10 C accidentally.",
        },
        tags: ["field-strength", "calculation", "formula"],
      },
      {
        id: "t18-1-d4",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define electric field strength E and state its unit.",
        modelAnswerPoints: [
          "Electric field strength is force per unit positive test charge.",
          "E = F/q.",
          "Unit is N C^-1 (equivalently V m^-1).",
        ],
        workedSolution: [
          "Definition must mention positive test charge.",
          "Either SI unit form gains credit if correctly stated.",
        ],
        commonMistake: "Defining E as force times charge.",
        tags: ["definition", "units", "core-knowledge"],
      },
      {
        id: "t18-1-d5",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A small charge of +4.0 x 10^-8 C is placed at a point where the electric field is 1.5 x 10^4 N C^-1.\nCalculate the force and state its direction relative to the field.",
        modelAnswerPoints: [
          "Use F = qE.",
          "F = 4.0 x 10^-8 x 1.5 x 10^4 = 6.0 x 10^-4 N.",
          "For positive charge, force is in same direction as field.",
          "State final answer with unit and direction.",
        ],
        workedSolution: [
          "Substitute magnitude first, then handle direction from charge sign.",
          "Positive test charges define the field direction by convention.",
        ],
        commonMistake: "Reversing direction for a positive charge.",
        tags: ["force-in-field", "sign-convention", "application"],
      },
      {
        id: "t18-1-d6",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "At a point, a negative charge -2.0 x 10^-6 C experiences force 1.0 x 10^-2 N due east.\nFind the electric field strength magnitude and its direction.",
        modelAnswerPoints: [
          "Magnitude E = F/|q| = (1.0 x 10^-2)/(2.0 x 10^-6) = 5.0 x 10^3 N C^-1.",
          "Force on negative charge is opposite to field direction.",
          "So field direction is west.",
          "Quote magnitude and direction clearly.",
        ],
        workedSolution: [
          "Use absolute charge for magnitude then infer direction from sign.",
          "Direction logic is a standard exam trap in field questions.",
        ],
        commonMistake: "Stating field direction east because force is east.",
        tags: ["negative-charge", "direction", "field-strength"],
      },
      {
        id: "t18-1-d7",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "A point in space has electric field vectors from two sources: E1 = 3.0 x 10^3 N C^-1 east and E2 = 4.0 x 10^3 N C^-1 north.\nDetermine resultant field magnitude and direction.",
        modelAnswerPoints: [
          "Resultant magnitude E = sqrt(E1^2 + E2^2).",
          "E = sqrt((3.0 x 10^3)^2 + (4.0 x 10^3)^2) = 5.0 x 10^3 N C^-1.",
          "Direction angle theta = tan^-1(4/3) = 53 degrees north of east.",
          "State vector direction relative to a cardinal axis.",
        ],
        workedSolution: [
          "Perpendicular fields add as vectors, not scalars.",
          "Use right-triangle method for magnitude and angle.",
          "Include direction phrase to secure full method marks.",
        ],
        commonMistake: "Adding 3.0 x 10^3 and 4.0 x 10^3 directly to get 7.0 x 10^3.",
        tags: ["vector-addition", "resultant-field", "two-dimensional"],
      },
      {
        id: "t18-1-d8",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Describe three properties of electric field lines around isolated charges and explain what each property tells you physically.",
        modelAnswerPoints: [
          "Lines start on positive charges and end on negative charges (or infinity).",
          "Line direction indicates force direction on a positive test charge.",
          "Line density indicates relative field strength.",
          "Lines never cross because the field at a point has only one direction.",
        ],
        workedSolution: [
          "State each property and link to physical interpretation.",
          "Any three well-explained properties can earn full credit.",
          "Avoid treating field lines as material paths of particles.",
        ],
        commonMistake: "Claiming field lines can intersect where fields cancel.",
        tags: ["field-lines", "explanation", "conceptual-depth"],
      },
      {
        id: "t18-1-d9",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A charged particle of charge +6.0 x 10^-9 C and mass 3.0 x 10^-6 kg is released from rest in a uniform electric field of 2.5 x 10^4 N C^-1.\nFind (a) initial acceleration and (b) speed after 4.0 ms.",
        modelAnswerPoints: [
          "Electric force F = qE = 6.0 x 10^-9 x 2.5 x 10^4 = 1.5 x 10^-4 N.",
          "Acceleration a = F/m = (1.5 x 10^-4)/(3.0 x 10^-6) = 50 m s^-2.",
          "With u = 0, v = at = 50 x 4.0 x 10^-3 = 0.20 m s^-1.",
          "Direction is along field because charge is positive.",
        ],
        workedSolution: [
          "Treat electric force as constant in a uniform field.",
          "Then apply constant-acceleration kinematics.",
          "Keep milliseconds converted to seconds before substitution.",
        ],
        commonMistake: "Using t = 4.0 instead of 4.0 x 10^-3 s.",
        tags: ["field-to-motion", "multi-step", "kinematics-link"],
      },
      {
        id: "t18-1-d10",
        noteId: "t18-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Two parallel metal plates create approximately horizontal electric field lines in the central region.\nExplain how you would use a charged test particle to verify both the direction and approximate uniformity of the field, including expected observations.",
        modelAnswerPoints: [
          "Release a small positive test particle at different points between plates.",
          "Direction of initial acceleration gives field direction from positive to negative plate.",
          "If field is uniform, force and acceleration magnitude are approximately constant at different central positions.",
          "Trajectories should show similar curvature for same initial conditions in central region.",
          "Near plate edges, deviations indicate fringing and non-uniformity.",
        ],
        workedSolution: [
          "Tie observations to F = qE and a = qE/m.",
          "A consistent acceleration magnitude implies near-constant E.",
          "Mention edge effects to show awareness of practical non-ideal behavior.",
        ],
        commonMistake: "Concluding the field is perfectly uniform everywhere including edges.",
        tags: ["experimental-reasoning", "uniformity", "high-mark"],
      },
    ],
    flashcards: [
      {
        id: "t18-1-f1",
        noteId: "t18-1",
        difficulty: 1,
        front: "Define electric field strength.",
        back: "Force per unit positive test charge: E = F/q.",
        examPhrasing: "State both formula and positive-test-charge convention.",
        tags: ["definition", "electric-field"],
      },
      {
        id: "t18-1-f2",
        noteId: "t18-1",
        difficulty: 1,
        front: "What is the SI unit of electric field strength?",
        back: "N C^-1 (equivalently V m^-1).",
        examPhrasing: "Either SI equivalent is acceptable.",
        tags: ["units", "field-strength"],
      },
      {
        id: "t18-1-f3",
        noteId: "t18-1",
        difficulty: 2,
        front: "What does electric field line density represent?",
        back: "Relative electric field strength; denser lines mean stronger field.",
        examPhrasing: "Do not interpret line count as charge quantity directly.",
        tags: ["field-lines", "representation"],
      },
      {
        id: "t18-1-f4",
        noteId: "t18-1",
        difficulty: 2,
        front: "Why can electric field lines never cross?",
        back: "Because field direction at a point is unique.",
        examPhrasing: "Crossing would imply two directions of force at one point.",
        tags: ["field-lines", "direction"],
      },
      {
        id: "t18-1-f5",
        noteId: "t18-1",
        difficulty: 3,
        front: "How does force direction compare to field direction for a negative charge?",
        back: "Force is opposite to field direction.",
        examPhrasing: "Use sign of q with F = qE.",
        confusionPair: "Field direction vs force on electron",
        tags: ["charge-sign", "direction"],
      },
      {
        id: "t18-1-f6",
        noteId: "t18-1",
        difficulty: 3,
        front: "What equation links electric force and field?",
        back: "F = qE.",
        examPhrasing: "For magnitude use |F| = |q|E.",
        tags: ["formula", "force"],
      },
      {
        id: "t18-1-f7",
        noteId: "t18-1",
        difficulty: 4,
        front: "How do you find resultant electric field from two perpendicular components?",
        back: "Use vector addition: E = sqrt(E_x^2 + E_y^2), angle from tan^-1(E_y/E_x).",
        examPhrasing: "Field is a vector; scalar addition loses method marks.",
        tags: ["vectors", "resultant"],
      },
      {
        id: "t18-1-f8",
        noteId: "t18-1",
        difficulty: 4,
        front: "What region between parallel plates is closest to uniform field behavior?",
        back: "The central region away from plate edges.",
        examPhrasing: "Fringing causes edge non-uniformity.",
        tags: ["uniform-field", "practical"],
      },
      {
        id: "t18-1-f9",
        noteId: "t18-1",
        difficulty: 5,
        front: "What is the common direction error in electric-field questions?",
        back: "Using force direction on an electron as the field direction.",
        examPhrasing: "Field direction is defined by positive test charge.",
        confusionPair: "Electron force direction vs field direction",
        tags: ["exam-errors", "direction"],
      },
      {
        id: "t18-1-f10",
        noteId: "t18-1",
        difficulty: 5,
        front: "Quick exam checklist for field-strength calculations?",
        back: "Pick correct equation (E=F/q or F=qE), handle charge sign for direction, keep powers of ten and units consistent.",
        examPhrasing: "Method clarity often secures follow-through marks.",
        tags: ["exam-technique", "calculation"],
      },
    ],
  },
  "t18-2": {
    noteId: "t18-2",
    drills: [
      {
        id: "t18-2-d1",
        noteId: "t18-2",
        kind: "mcq",
        difficulty: 1,
        stem: "In a uniform electric field, field strength E is equal to",
        options: [
          { id: "A", text: "Vd" },
          { id: "B", text: "V/d" },
          { id: "C", text: "d/V" },
          { id: "D", text: "V + d" },
        ],
        correctOptionId: "B",
        explanation: "For parallel plates with uniform field, potential gradient gives E = V/d.",
        distractorRationale: {
          C: "This is reciprocal and has wrong units.",
          D: "Addition has no physical meaning for field strength.",
        },
        tags: ["uniform-field", "potential-gradient", "formula"],
      },
      {
        id: "t18-2-d2",
        noteId: "t18-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Two plates are 4.0 mm apart with p.d. 600 V. Field strength between plates is",
        options: [
          { id: "A", text: "1.5 x 10^5 V m^-1" },
          { id: "B", text: "2.4 x 10^6 V m^-1" },
          { id: "C", text: "2.4 x 10^3 V m^-1" },
          { id: "D", text: "1.5 x 10^2 V m^-1" },
        ],
        correctOptionId: "A",
        explanation: "E = V/d = 600/(4.0 x 10^-3) = 1.5 x 10^5 V m^-1.",
        distractorRationale: {
          B: "This comes from using d = 2.5 x 10^-4 m incorrectly.",
          C: "This uses d = 0.25 m by failing mm conversion.",
          D: "Unit conversion and powers of ten are both mishandled.",
        },
        tags: ["numerical", "unit-conversion", "parallel-plates"],
      },
      {
        id: "t18-2-d3",
        noteId: "t18-2",
        kind: "mcq",
        difficulty: 3,
        stem: "An electron enters a uniform electric field to the right. Which statement is true?",
        options: [
          { id: "A", text: "It accelerates to the right because E is to the right" },
          { id: "B", text: "It has zero electric force if speed is constant" },
          { id: "C", text: "It accelerates to the left due to negative charge" },
          { id: "D", text: "Its force is perpendicular to the field" },
        ],
        correctOptionId: "C",
        explanation: "Electric force is F = qE; for q negative, force and acceleration are opposite the field.",
        distractorRationale: {
          B: "Field exerts force regardless of initial speed.",
          D: "Electric force in uniform electrostatic field is collinear with E.",
        },
        tags: ["charge-sign", "motion", "uniform-field"],
      },
      {
        id: "t18-2-d4",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State two features of a uniform electric field and sketch how field lines are represented.",
        modelAnswerPoints: [
          "Field strength and direction are constant throughout the region.",
          "Field lines are straight, parallel, and equally spaced.",
          "Direction is from positive plate to negative plate.",
        ],
        workedSolution: [
          "For text answers, describe the sketch features explicitly.",
          "Equal spacing is the key visual indicator of uniformity.",
        ],
        commonMistake: "Drawing converging lines, which indicate non-uniform field.",
        tags: ["description", "field-lines", "uniformity"],
      },
      {
        id: "t18-2-d5",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Parallel plates are separated by 6.0 mm with p.d. 900 V.\n(a) Find electric field strength.\n(b) Find force on charge +2.0 x 10^-9 C placed between plates.",
        modelAnswerPoints: [
          "E = V/d = 900/(6.0 x 10^-3) = 1.5 x 10^5 V m^-1.",
          "Use F = qE.",
          "F = 2.0 x 10^-9 x 1.5 x 10^5 = 3.0 x 10^-4 N.",
          "Force direction is from positive to negative plate.",
        ],
        workedSolution: [
          "Convert mm to m before substitution.",
          "Use field value from part (a) directly for part (b).",
        ],
        commonMistake: "Using d = 6.0 m instead of 6.0 x 10^-3 m.",
        tags: ["multi-step", "plates", "force-calculation"],
      },
      {
        id: "t18-2-d6",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "An oil droplet of charge -3.0 x 10^-15 C is suspended at rest in a vertical uniform electric field between plates.\nWeight of droplet is 9.0 x 10^-14 N.\nDetermine field strength and field direction.",
        modelAnswerPoints: [
          "At equilibrium, electric force magnitude equals weight: |q|E = W.",
          "E = W/|q| = (9.0 x 10^-14)/(3.0 x 10^-15) = 30 N C^-1.",
          "Electric force on negative charge must be upward to balance weight.",
          "Therefore field direction is downward.",
        ],
        workedSolution: [
          "Use force balance for suspended condition (net force zero).",
          "Direction requires careful sign reasoning for negative charge.",
        ],
        commonMistake: "Saying field points upward because force on droplet is upward.",
        tags: ["equilibrium", "millikan-style", "direction"],
      },
      {
        id: "t18-2-d7",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "A proton enters horizontally between parallel plates with initial speed 2.0 x 10^6 m s^-1.\nPlate length is 0.040 m, field strength is 8.0 x 10^4 N C^-1 downward.\nFind vertical deflection while inside the field.\nTake proton mass 1.67 x 10^-27 kg and charge 1.60 x 10^-19 C.",
        modelAnswerPoints: [
          "Horizontal speed gives time in field: t = L/u = 0.040/(2.0 x 10^6) = 2.0 x 10^-8 s.",
          "Vertical acceleration a = qE/m = (1.60 x 10^-19 x 8.0 x 10^4)/(1.67 x 10^-27) = 7.66 x 10^12 m s^-2.",
          "Initial vertical speed is zero, so y = (1/2)at^2.",
          "y = 0.5 x 7.66 x 10^12 x (2.0 x 10^-8)^2 = 1.53 x 10^-3 m downward.",
        ],
        workedSolution: [
          "Treat horizontal and vertical motions independently.",
          "Uniform field gives constant vertical acceleration.",
          "Direction follows proton (positive charge) and field direction.",
        ],
        commonMistake: "Using total speed in SUVAT for vertical motion.",
        tags: ["particle-deflection", "kinematics", "parallel-plates"],
      },
      {
        id: "t18-2-d8",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Electrons are accelerated from rest through p.d. 1200 V, then enter a region of uniform electric field 3.0 x 10^4 N C^-1 at right angles to their initial velocity.\n(a) Find entry speed.\n(b) State and explain the path shape in the field.",
        modelAnswerPoints: [
          "Energy gain: eV = (1/2)mv^2.",
          "v = sqrt(2eV/m) = sqrt((2 x 1.60 x 10^-19 x 1200)/(9.11 x 10^-31)) = 2.05 x 10^7 m s^-1.",
          "In field region, horizontal velocity stays constant while vertical acceleration is constant.",
          "Hence trajectory is parabolic.",
        ],
        workedSolution: [
          "Use energy method for entry speed from accelerating p.d.",
          "Then apply projectile-style reasoning with electric acceleration replacing g.",
          "Mention opposite deflection direction to field for electrons.",
        ],
        commonMistake: "Assuming path is circular because force exists.",
        tags: ["electron-gun", "trajectory", "energy-link"],
      },
      {
        id: "t18-2-d9",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A pair of plates must produce field strength 2.0 x 10^5 V m^-1 across a 3.5 mm gap.\n(a) Find required p.d.\n(b) If maximum safe p.d. is 600 V, discuss whether design meets requirement.",
        modelAnswerPoints: [
          "Use V = Ed.",
          "V = 2.0 x 10^5 x 3.5 x 10^-3 = 700 V.",
          "Required p.d. exceeds safe limit of 600 V.",
          "Design does not meet requirement unless gap is reduced or target E lowered.",
        ],
        workedSolution: [
          "Rearrange E = V/d to solve for V.",
          "Compare calculated operational value directly with constraint.",
          "Provide concise engineering conclusion for exam evaluation mark.",
        ],
        commonMistake: "Concluding it is safe because 700 is close to 600.",
        tags: ["design-check", "evaluation", "uniform-field"],
      },
      {
        id: "t18-2-d10",
        noteId: "t18-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Explain why a parallel-plate setup gives only approximately uniform field in practice, and describe two modifications that improve field uniformity for particle-deflection experiments.",
        modelAnswerPoints: [
          "Field is near-uniform only in central region because edges show fringing where lines spread out.",
          "Finite plate size and imperfect alignment cause non-uniformity.",
          "Using larger plates relative to gap increases central uniform region.",
          "Using guard rings or shielding can reduce edge distortions.",
          "Keeping plate separation small and parallel improves consistency of E = V/d assumption.",
        ],
        workedSolution: [
          "Start with ideal model, then identify practical deviations.",
          "Each modification must be linked to reduced fringing or improved geometry.",
          "Explicitly connect to experimental accuracy in deflection measurements.",
        ],
        commonMistake: "Stating uniformity can be made perfect with higher voltage only.",
        tags: ["practical-physics", "fringing", "evaluation"],
      },
    ],
    flashcards: [
      {
        id: "t18-2-f1",
        noteId: "t18-2",
        difficulty: 1,
        front: "What is the field-strength relation for parallel plates?",
        back: "E = V/d.",
        examPhrasing: "d must be in metres for SI consistency.",
        tags: ["formula", "parallel-plates"],
      },
      {
        id: "t18-2-f2",
        noteId: "t18-2",
        difficulty: 1,
        front: "How are uniform electric-field lines drawn?",
        back: "Straight, parallel, equally spaced lines.",
        examPhrasing: "Direction is from positive plate to negative plate.",
        tags: ["field-lines", "uniformity"],
      },
      {
        id: "t18-2-f3",
        noteId: "t18-2",
        difficulty: 2,
        front: "What is the force on a charge in a uniform electric field?",
        back: "F = qE.",
        examPhrasing: "Direction depends on sign of q.",
        tags: ["force", "charge-sign"],
      },
      {
        id: "t18-2-f4",
        noteId: "t18-2",
        difficulty: 2,
        front: "What causes edge effects in parallel-plate fields?",
        back: "Field lines spread near plate edges (fringing), reducing uniformity.",
        examPhrasing: "Uniform-field assumptions are best in central region.",
        tags: ["fringing", "practical"],
      },
      {
        id: "t18-2-f5",
        noteId: "t18-2",
        difficulty: 3,
        front: "How do you find speed after acceleration through p.d. V?",
        back: "Use eV = (1/2)mv^2 for a single electron.",
        examPhrasing: "Applies when starting from rest and neglecting losses.",
        tags: ["energy", "electron"],
      },
      {
        id: "t18-2-f6",
        noteId: "t18-2",
        difficulty: 3,
        front: "What path does a charged particle follow in a uniform electric field at right angles to initial velocity?",
        back: "A parabola.",
        examPhrasing: "Uniform horizontal velocity plus constant vertical acceleration.",
        tags: ["trajectory", "kinematics"],
      },
      {
        id: "t18-2-f7",
        noteId: "t18-2",
        difficulty: 4,
        front: "Why is an electron deflected opposite to field direction?",
        back: "Because q is negative, so F = qE is opposite to E.",
        examPhrasing: "Sign handling is key in direction marks.",
        confusionPair: "Field direction vs electron acceleration",
        tags: ["direction", "electrons"],
      },
      {
        id: "t18-2-f8",
        noteId: "t18-2",
        difficulty: 4,
        front: "How can field uniformity be improved experimentally?",
        back: "Use large well-aligned plates, small gap, and guard-ring design.",
        examPhrasing: "Aim to minimize fringing in measurement region.",
        tags: ["experimental", "uniform-field"],
      },
      {
        id: "t18-2-f9",
        noteId: "t18-2",
        difficulty: 5,
        front: "Most common conversion error in E = V/d problems?",
        back: "Leaving d in mm or cm instead of metres.",
        examPhrasing: "Convert geometry units before substitution.",
        tags: ["errors", "units"],
      },
      {
        id: "t18-2-f10",
        noteId: "t18-2",
        difficulty: 5,
        front: "How do you structure high-mark uniform-field deflection answers?",
        back: "Find time in field from horizontal motion, find vertical acceleration from qE/m, then use vertical SUVAT and direction from charge sign.",
        examPhrasing: "Clear separation of axes maximizes method marks.",
        tags: ["exam-technique", "particle-deflection"],
      },
    ],
  },
  "t18-3": {
    noteId: "t18-3",
    drills: [
      {
        id: "t18-3-d1",
        noteId: "t18-3",
        kind: "mcq",
        difficulty: 1,
        stem: "Coulomb's law for two point charges in vacuum is",
        options: [
          { id: "A", text: "F = Q1Q2/(4pi epsilon0 r)" },
          { id: "B", text: "F = Q1Q2/(4pi epsilon0 r^2)" },
          { id: "C", text: "F = 4pi epsilon0 Q1Q2 r^2" },
          { id: "D", text: "F = epsilon0 Q1Q2/r^2" },
        ],
        correctOptionId: "B",
        explanation: "Electrostatic force between point charges follows inverse-square separation dependence.",
        distractorRationale: {
          C: "This inverts the proportionalities incorrectly.",
          D: "Missing 1/(4pi epsilon0) factor and wrong constant form.",
        },
        tags: ["coulomb-law", "formula", "inverse-square"],
      },
      {
        id: "t18-3-d2",
        noteId: "t18-3",
        kind: "mcq",
        difficulty: 2,
        stem: "If separation of two fixed charges is doubled, electrostatic force magnitude becomes",
        options: [
          { id: "A", text: "Four times larger" },
          { id: "B", text: "Twice as large" },
          { id: "C", text: "Half as large" },
          { id: "D", text: "One quarter as large" },
        ],
        correctOptionId: "D",
        explanation: "Since F proportional 1/r^2, doubling r reduces force by factor 4.",
        distractorRationale: {
          B: "This incorrectly assumes direct proportionality with r.",
          C: "This assumes inverse first power instead of inverse square.",
        },
        tags: ["inverse-square", "proportionality", "coulomb-law"],
      },
      {
        id: "t18-3-d3",
        noteId: "t18-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Two charges +Q and -Q are separated by distance r. The force between them is",
        options: [
          { id: "A", text: "Repulsive with magnitude proportional 1/r" },
          { id: "B", text: "Attractive with magnitude proportional 1/r^2" },
          { id: "C", text: "Zero because net charge is zero" },
          { id: "D", text: "Repulsive with magnitude proportional 1/r^2" },
        ],
        correctOptionId: "B",
        explanation: "Opposite charges attract, and Coulomb magnitude still obeys inverse-square law.",
        distractorRationale: {
          C: "Net system charge does not imply zero mutual force.",
          D: "Repulsion applies only to like charges.",
        },
        tags: ["attraction-repulsion", "conceptual", "law-application"],
      },
      {
        id: "t18-3-d4",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State Coulomb's law in words and equation form.",
        modelAnswerPoints: [
          "Force magnitude between two point charges is proportional to product of charges.",
          "Force is inversely proportional to square of separation.",
          "In vacuum: F = Q1Q2/(4pi epsilon0 r^2), acting along line joining charges.",
        ],
        workedSolution: [
          "Word statement should include both proportionalities and direction line of action.",
          "Equation should include dielectric constant factor for full-credit precision.",
        ],
        commonMistake: "Omitting the square on r.",
        tags: ["definition", "equation", "core-law"],
      },
      {
        id: "t18-3-d5",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Two point charges +3.0 x 10^-6 C and +5.0 x 10^-6 C are 0.20 m apart in vacuum.\nCalculate force magnitude.\nTake 1/(4pi epsilon0) = 8.99 x 10^9 N m^2 C^-2.",
        modelAnswerPoints: [
          "Use F = kQ1Q2/r^2.",
          "F = (8.99 x 10^9)(3.0 x 10^-6)(5.0 x 10^-6)/(0.20)^2.",
          "F = 3.37 N.",
          "Force is repulsive because charges are like.",
        ],
        workedSolution: [
          "Substitute carefully with scientific notation and square distance.",
          "Include interaction type (attractive/repulsive) from charge signs.",
        ],
        commonMistake: "Using r instead of r^2 in denominator.",
        tags: ["numerical", "like-charges", "coulomb-constant"],
      },
      {
        id: "t18-3-d6",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Charges +2.0 muC and -8.0 muC are separated by 0.30 m.\n(a) Find force magnitude.\n(b) Explain how magnitude changes if each charge is doubled but separation unchanged.",
        modelAnswerPoints: [
          "Magnitude F = k|Q1Q2|/r^2 = 8.99 x 10^9 x (2.0 x 10^-6 x 8.0 x 10^-6)/(0.30)^2 = 1.60 N.",
          "Interaction is attractive because signs are opposite.",
          "If each charge doubles, product Q1Q2 becomes four times larger.",
          "Force magnitude therefore becomes four times larger.",
        ],
        workedSolution: [
          "For magnitude, use absolute product and handle direction separately.",
          "Scaling arguments can be done from proportional relation without recalculation.",
        ],
        commonMistake: "Saying force doubles when both charges double.",
        tags: ["scaling", "opposite-charges", "proportionality"],
      },
      {
        id: "t18-3-d7",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Three charges lie on a line: q1 = +4.0 nC at x=0, q2 = +1.0 nC at x=0.20 m, q3 = -2.0 nC at x=0.50 m.\nFind resultant force on q2, including direction.",
        modelAnswerPoints: [
          "Force on q2 due to q1 is repulsive to the right: F21 = k|q1q2|/(0.20)^2 = 8.99 x 10^-7 N.",
          "Force on q2 due to q3 is attractive to the right: F23 = k|q2q3|/(0.30)^2 = 2.00 x 10^-7 N.",
          "Both forces act right, so resultant is additive.",
          "F_result = 1.10 x 10^-6 N to the right.",
        ],
        workedSolution: [
          "Draw directions first before arithmetic to avoid sign mistakes.",
          "Use pairwise Coulomb forces then vector sum along one dimension.",
          "Maintain nC to C conversion in each step.",
        ],
        commonMistake: "Subtracting forces despite both acting in same direction.",
        tags: ["superposition", "one-dimensional", "resultant-force"],
      },
      {
        id: "t18-3-d8",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Two identical positive charges q are fixed 0.40 m apart.\nA third charge +1.5 nC placed midway experiences force 3.0 x 10^-6 N from either fixed charge.\nFind q.",
        modelAnswerPoints: [
          "Midpoint distance to each fixed charge is r = 0.20 m.",
          "Use F = kqQ/r^2 with Q = 1.5 x 10^-9 C.",
          "q = Fr^2/(kQ) = (3.0 x 10^-6 x 0.20^2)/(8.99 x 10^9 x 1.5 x 10^-9).",
          "q = 8.9 x 10^-9 C (about 8.9 nC).",
        ],
        workedSolution: [
          "Question gives force from either one fixed charge, not resultant.",
          "Keep track of nC conversion and square distance.",
          "Result is positive since stated identical positive charges.",
        ],
        commonMistake: "Using 0.40 m instead of 0.20 m in Coulomb equation.",
        tags: ["inverse-problem", "midpoint", "calculation"],
      },
      {
        id: "t18-3-d9",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A charged dust particle of mass 2.0 x 10^-8 kg remains stationary 0.10 m above a fixed point charge +6.0 x 10^-7 C.\nDetermine sign and magnitude of dust charge.\nTake g = 9.81 m s^-2.",
        modelAnswerPoints: [
          "For equilibrium, upward electric force must balance weight mg.",
          "Weight is downward, so electric force must be upward.",
          "Above a positive source, field is upward; to get upward force, dust charge must be positive.",
          "Set kQq/r^2 = mg and solve q = mgr^2/(kQ) = (2.0 x 10^-8 x 9.81 x 0.10^2)/(8.99 x 10^9 x 6.0 x 10^-7) = 3.6 x 10^-13 C.",
        ],
        workedSolution: [
          "Determine sign physically before algebra to avoid sign confusion.",
          "Use magnitude equation after direction reasoning.",
          "Include unit and sign in final answer.",
        ],
        commonMistake: "Choosing negative dust charge because force 'must oppose gravity'.",
        tags: ["equilibrium", "sign-analysis", "applied-coulomb"],
      },
      {
        id: "t18-3-d10",
        noteId: "t18-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Two charges +Q and -4Q are fixed 0.30 m apart on x-axis.\nFind the position(s) on the x-axis where net electric force on a positive test charge is zero.\nShow reasoning about direction as well as magnitude.",
        modelAnswerPoints: [
          "Between charges, both fields point from +Q to -4Q, so they cannot cancel there.",
          "Possible cancellation must be outside interval on side of smaller-magnitude source +Q.",
          "Let point be distance x to left of +Q: distances to +Q and -4Q are x and x+0.30.",
          "Set kQ/x^2 = k(4Q)/(x+0.30)^2 -> (x+0.30)^2 = 4x^2.",
          "Positive solution gives x+0.30 = 2x -> x = 0.30 m.",
          "So zero-force point is 0.30 m to left of +Q (and none between or to right).",
        ],
        workedSolution: [
          "Direction argument is essential before solving magnitude equation.",
          "Using field or force on positive test charge gives same cancellation location.",
          "Select physically valid root after algebra.",
        ],
        commonMistake: "Trying to find a midpoint cancellation between opposite charges.",
        tags: ["null-point", "reasoning", "high-mark"],
      },
    ],
    flashcards: [
      {
        id: "t18-3-f1",
        noteId: "t18-3",
        difficulty: 1,
        front: "State Coulomb's law equation in vacuum.",
        back: "F = Q1Q2/(4pi epsilon0 r^2) in magnitude form.",
        examPhrasing: "Force acts along line joining the charges.",
        tags: ["coulomb-law", "equation"],
      },
      {
        id: "t18-3-f2",
        noteId: "t18-3",
        difficulty: 1,
        front: "How does electrostatic force vary with separation?",
        back: "Inverse-square: F proportional 1/r^2.",
        examPhrasing: "Doubling r gives one-quarter force.",
        tags: ["inverse-square", "proportionality"],
      },
      {
        id: "t18-3-f3",
        noteId: "t18-3",
        difficulty: 2,
        front: "How does force change if both charges are doubled?",
        back: "Force becomes four times larger (product Q1Q2 increases by 4).",
        examPhrasing: "Use product scaling before numeric substitution.",
        tags: ["scaling", "charges"],
      },
      {
        id: "t18-3-f4",
        noteId: "t18-3",
        difficulty: 2,
        front: "What determines whether Coulomb force is attractive or repulsive?",
        back: "Relative signs of charges: unlike attract, like repel.",
        examPhrasing: "Direction marks depend on sign logic.",
        tags: ["attraction-repulsion", "signs"],
      },
      {
        id: "t18-3-f5",
        noteId: "t18-3",
        difficulty: 3,
        front: "What principle is used for forces from multiple charges?",
        back: "Superposition: resultant force is vector sum of individual forces.",
        examPhrasing: "Add components with direction, not magnitudes only.",
        tags: ["superposition", "resultants"],
      },
      {
        id: "t18-3-f6",
        noteId: "t18-3",
        difficulty: 3,
        front: "Why is net force not necessarily zero when net charge is zero?",
        back: "Forces depend on local fields and positions, not only total charge.",
        examPhrasing: "Zero net charge does not imply zero field everywhere.",
        confusionPair: "Net charge zero vs force zero",
        tags: ["conceptual", "field-vs-charge"],
      },
      {
        id: "t18-3-f7",
        noteId: "t18-3",
        difficulty: 4,
        front: "Where is null point for two unlike unequal charges usually found?",
        back: "Outside the interval, on side of smaller-magnitude charge.",
        examPhrasing: "Direction analysis precedes equation solving.",
        tags: ["null-point", "opposite-charges"],
      },
      {
        id: "t18-3-f8",
        noteId: "t18-3",
        difficulty: 4,
        front: "What constant is often denoted by k in Coulomb calculations?",
        back: "k = 1/(4pi epsilon0) = 8.99 x 10^9 N m^2 C^-2.",
        examPhrasing: "Using k form simplifies substitution.",
        tags: ["constants", "coulomb-constant"],
      },
      {
        id: "t18-3-f9",
        noteId: "t18-3",
        difficulty: 5,
        front: "Most frequent algebra error in Coulomb-law work?",
        back: "Forgetting to square distance or squaring only numeric part.",
        examPhrasing: "Write r^2 explicitly before plugging numbers.",
        tags: ["errors", "algebra"],
      },
      {
        id: "t18-3-f10",
        noteId: "t18-3",
        difficulty: 5,
        front: "How should a high-mark force-superposition answer be structured?",
        back: "Determine direction of each force, calculate magnitudes separately, then perform signed/vector sum with final direction statement.",
        examPhrasing: "Direction-first setup prevents sign loss.",
        tags: ["exam-technique", "multi-step"],
      },
    ],
  },
  "t18-4": {
    noteId: "t18-4",
    drills: [
      {
        id: "t18-4-d1",
        noteId: "t18-4",
        kind: "mcq",
        difficulty: 1,
        stem: "Electric field strength E at distance r from a point charge Q is",
        options: [
          { id: "A", text: "E = Q/(4pi epsilon0 r)" },
          { id: "B", text: "E = Q/(4pi epsilon0 r^2)" },
          { id: "C", text: "E = 4pi epsilon0 Q r^2" },
          { id: "D", text: "E = epsilon0 Q/r^2" },
        ],
        correctOptionId: "B",
        explanation: "Point-charge field follows inverse-square dependence with distance.",
        distractorRationale: {
          C: "This inverts physical proportionalities.",
          D: "Missing the 1/(4pi epsilon0) factor.",
        },
        tags: ["point-charge-field", "formula", "inverse-square"],
      },
      {
        id: "t18-4-d2",
        noteId: "t18-4",
        kind: "mcq",
        difficulty: 2,
        stem: "At distance r from a positive point charge, field direction is",
        options: [
          { id: "A", text: "Radially inward" },
          { id: "B", text: "Tangential to circle around charge" },
          { id: "C", text: "Radially outward" },
          { id: "D", text: "Zero on any spherical surface" },
        ],
        correctOptionId: "C",
        explanation: "Field lines emerge outward from positive charges.",
        distractorRationale: {
          B: "Tangential direction would apply to circular motion vectors, not electrostatic fields.",
          D: "Field can be non-zero and constant in magnitude on a sphere of fixed r.",
        },
        tags: ["direction", "field-lines", "positive-charge"],
      },
      {
        id: "t18-4-d3",
        noteId: "t18-4",
        kind: "mcq",
        difficulty: 3,
        stem: "If distance from a point charge is tripled, field strength changes by factor",
        options: [
          { id: "A", text: "1/3" },
          { id: "B", text: "1/6" },
          { id: "C", text: "1/9" },
          { id: "D", text: "9" },
        ],
        correctOptionId: "C",
        explanation: "Because E proportional 1/r^2, tripling r gives E/9.",
        distractorRationale: {
          B: "Not consistent with inverse-square dependence.",
          D: "This reverses the proportionality.",
        },
        tags: ["scaling", "inverse-square", "quick-check"],
      },
      {
        id: "t18-4-d4",
        noteId: "t18-4",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define a point charge and state the equation for field strength due to a point charge in vacuum.",
        modelAnswerPoints: [
          "A point charge is treated as having negligible physical size compared with distances involved.",
          "Field strength depends on source charge and distance from it.",
          "E = Q/(4pi epsilon0 r^2).",
        ],
        workedSolution: [
          "Exam definition focuses on modeling assumption of negligible size.",
          "State equation with inverse-square dependence explicitly.",
        ],
        commonMistake: "Calling any small charge a point charge without distance context.",
        tags: ["definitions", "model", "equation"],
      },
      {
        id: "t18-4-d5",
        noteId: "t18-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Calculate electric field strength 0.50 m from an isolated point charge +8.0 x 10^-9 C.\nTake 1/(4pi epsilon0) = 8.99 x 10^9 N m^2 C^-2.",
        modelAnswerPoints: [
          "Use E = kQ/r^2.",
          "E = (8.99 x 10^9)(8.0 x 10^-9)/(0.50)^2.",
          "E = 2.88 x 10^2 N C^-1.",
          "Direction is radially outward from the charge.",
        ],
        workedSolution: [
          "Convert to standard form before substitution.",
          "Report both magnitude and direction for complete answer.",
        ],
        commonMistake: "Using denominator r instead of r^2.",
        tags: ["numerical", "point-charge", "direction"],
      },
      {
        id: "t18-4-d6",
        noteId: "t18-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "At a point 0.12 m from a point charge, field magnitude is 3.0 x 10^4 N C^-1.\nFind charge magnitude producing this field in vacuum.",
        modelAnswerPoints: [
          "Rearrange E = kQ/r^2 to Q = Er^2/k.",
          "Q = (3.0 x 10^4 x 0.12^2)/(8.99 x 10^9).",
          "Q = 4.8 x 10^-8 C.",
          "Magnitude only requested; sign requires direction information.",
        ],
        workedSolution: [
          "Inverse problems require careful rearrangement before numbers.",
          "Use squared distance first to minimize calculator mistakes.",
        ],
        commonMistake: "Multiplying by k instead of dividing by k.",
        tags: ["rearrangement", "inverse-problem", "field-equation"],
      },
      {
        id: "t18-4-d7",
        noteId: "t18-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Two points P and Q are at 0.20 m and 0.35 m from the same point charge.\nFind ratio E_P/E_Q and explain physically why it has this value.",
        modelAnswerPoints: [
          "E proportional 1/r^2 for same source charge.",
          "E_P/E_Q = (r_Q/r_P)^2 = (0.35/0.20)^2 = 3.06.",
          "Field is stronger closer to source because field lines spread over larger area with distance.",
          "Hence P has about three times stronger field than Q.",
        ],
        workedSolution: [
          "Use ratio method to avoid carrying constants k and Q.",
          "Physical explanation should mention geometric spreading with distance.",
          "Round ratio appropriately.",
        ],
        commonMistake: "Using simple distance ratio 0.35/0.20 without squaring.",
        tags: ["ratios", "inverse-square", "explanation"],
      },
      {
        id: "t18-4-d8",
        noteId: "t18-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A charge -5.0 x 10^-9 C is at the origin.\nDetermine field vectors at points A(0.30 m,0) and B(0,0.40 m), giving magnitude and direction at each point.",
        modelAnswerPoints: [
          "Magnitude at A: E_A = k|Q|/0.30^2 = (8.99 x 10^9 x 5.0 x 10^-9)/0.09 = 4.99 x 10^2 N C^-1.",
          "Because source is negative, direction at A is toward origin, i.e. along -x.",
          "Magnitude at B: E_B = k|Q|/0.40^2 = (8.99 x 10^9 x 5.0 x 10^-9)/0.16 = 2.81 x 10^2 N C^-1.",
          "Direction at B is toward origin, i.e. along -y.",
        ],
        workedSolution: [
          "Compute magnitudes separately because distances differ.",
          "Field from negative charge points inward everywhere.",
          "Express direction using axis notation for full clarity.",
        ],
        commonMistake: "Pointing fields away from origin despite negative source charge.",
        tags: ["vector-field", "cartesian-points", "negative-charge"],
      },
      {
        id: "t18-4-d9",
        noteId: "t18-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A proton is released from rest at 0.25 m from a fixed point charge +2.0 x 10^-8 C.\nFind initial acceleration of the proton.\nTake proton charge 1.60 x 10^-19 C, mass 1.67 x 10^-27 kg.",
        modelAnswerPoints: [
          "Field at proton position: E = kQ/r^2 = (8.99 x 10^9 x 2.0 x 10^-8)/(0.25)^2 = 2.88 x 10^3 N C^-1.",
          "Force on proton: F = qE = 1.60 x 10^-19 x 2.88 x 10^3 = 4.61 x 10^-16 N.",
          "Acceleration a = F/m = (4.61 x 10^-16)/(1.67 x 10^-27) = 2.76 x 10^11 m s^-2.",
          "Direction is radially away from source because both charges are positive.",
        ],
        workedSolution: [
          "Use two-stage method: source field then force on particle.",
          "Very large acceleration is realistic for tiny mass particles.",
          "Direction follows repulsion for like charges.",
        ],
        commonMistake: "Using source charge value as moving-particle charge.",
        tags: ["two-stage", "particle-motion", "point-charge-field"],
      },
      {
        id: "t18-4-d10",
        noteId: "t18-4",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Explain how experimental data of E versus r for an isolated charged sphere can be used to test the point-charge model.\nState what graph would confirm the model and what deviations may indicate.",
        modelAnswerPoints: [
          "For point-charge behavior outside sphere, E = kQ/r^2.",
          "Therefore plotting E against 1/r^2 should give a straight line through origin (within uncertainty).",
          "Gradient corresponds to kQ.",
          "Systematic deviations can indicate non-point geometry effects, nearby charges, or measurement error.",
          "At distances comparable to sphere radius, simple point approximation may break down.",
        ],
        workedSolution: [
          "Specify transformed-variable graph to linearize inverse-square law.",
          "Include both confirmation criterion and plausible causes of deviation.",
          "Tie interpretation back to model assumptions.",
        ],
        commonMistake: "Using E vs r linearity as test for inverse-square law.",
        tags: ["data-analysis", "model-testing", "high-mark"],
      },
    ],
    flashcards: [
      {
        id: "t18-4-f1",
        noteId: "t18-4",
        difficulty: 1,
        front: "Write field equation for a point charge in vacuum.",
        back: "E = Q/(4pi epsilon0 r^2) in magnitude form.",
        examPhrasing: "Equivalent form: E = kQ/r^2.",
        tags: ["formula", "point-charge"],
      },
      {
        id: "t18-4-f2",
        noteId: "t18-4",
        difficulty: 1,
        front: "How does field direction depend on sign of source charge?",
        back: "Away from positive charges, toward negative charges.",
        examPhrasing: "Field direction is defined for positive test charge.",
        tags: ["direction", "charge-sign"],
      },
      {
        id: "t18-4-f3",
        noteId: "t18-4",
        difficulty: 2,
        front: "What happens to E if distance from source doubles?",
        back: "E becomes one quarter.",
        examPhrasing: "Inverse-square scaling is high-yield in MCQs.",
        tags: ["scaling", "inverse-square"],
      },
      {
        id: "t18-4-f4",
        noteId: "t18-4",
        difficulty: 2,
        front: "What is k in the expression E = kQ/r^2?",
        back: "k = 8.99 x 10^9 N m^2 C^-2.",
        examPhrasing: "k = 1/(4pi epsilon0).",
        tags: ["constants", "vacuum-permittivity"],
      },
      {
        id: "t18-4-f5",
        noteId: "t18-4",
        difficulty: 3,
        front: "How can unknown Q be found from measured E at known r?",
        back: "Rearrange to Q = Er^2/k.",
        examPhrasing: "Sign of Q needs directional information too.",
        tags: ["rearrangement", "calculations"],
      },
      {
        id: "t18-4-f6",
        noteId: "t18-4",
        difficulty: 3,
        front: "What graph tests the inverse-square field model best?",
        back: "Plot E against 1/r^2 for a straight-line test.",
        examPhrasing: "Linearized graphs are often required for AO3 marks.",
        tags: ["graphing", "model-testing"],
      },
      {
        id: "t18-4-f7",
        noteId: "t18-4",
        difficulty: 4,
        front: "Why is a charge treated as a point charge?",
        back: "When observation distances are much larger than charge's physical size.",
        examPhrasing: "This is a modeling approximation, not literal zero size.",
        tags: ["model-assumption", "point-charge"],
      },
      {
        id: "t18-4-f8",
        noteId: "t18-4",
        difficulty: 4,
        front: "Common direction error for field of negative point charge?",
        back: "Drawing field vectors outward instead of inward.",
        examPhrasing: "Always relate direction to force on a positive test charge.",
        tags: ["errors", "direction"],
      },
      {
        id: "t18-4-f9",
        noteId: "t18-4",
        difficulty: 5,
        front: "In a two-stage problem with moving charge near source, what sequence should be used?",
        back: "Find source field at location, then use F = qE for moving charge, then dynamics if required.",
        examPhrasing: "Separating source and test quantities prevents substitution mistakes.",
        tags: ["problem-solving", "multi-step"],
      },
      {
        id: "t18-4-f10",
        noteId: "t18-4",
        difficulty: 5,
        front: "Top exam-check for inverse-square answers?",
        back: "Run a ratio sanity check: farther points must have weaker field by squared distance factor.",
        examPhrasing: "Quick scaling checks catch arithmetic slips.",
        tags: ["exam-technique", "sanity-check"],
      },
    ],
  },
  "t18-5": {
    noteId: "t18-5",
    drills: [
      {
        id: "t18-5-d1",
        noteId: "t18-5",
        kind: "mcq",
        difficulty: 1,
        stem: "Electric potential at a point is best defined as",
        options: [
          { id: "A", text: "Force per unit charge at that point" },
          { id: "B", text: "Potential energy per unit positive charge" },
          { id: "C", text: "Work done by charge per unit distance" },
          { id: "D", text: "Current per unit voltage" },
        ],
        correctOptionId: "B",
        explanation: "Electric potential is electric potential energy per unit charge relative to a reference.",
        distractorRationale: {
          C: "This mixes work and distance, related to force not potential directly.",
          D: "This is reciprocal resistance, unrelated to potential definition.",
        },
        tags: ["electric-potential", "definition", "scalar"],
      },
      {
        id: "t18-5-d2",
        noteId: "t18-5",
        kind: "mcq",
        difficulty: 2,
        stem: "Potential V at distance r from point charge Q in vacuum is",
        options: [
          { id: "A", text: "V = Q/(4pi epsilon0 r)" },
          { id: "B", text: "V = Q/(4pi epsilon0 r^2)" },
          { id: "C", text: "V = 4pi epsilon0 Qr" },
          { id: "D", text: "V = epsilon0 Q/r^2" },
        ],
        correctOptionId: "A",
        explanation: "Potential of a point charge varies inversely with distance (1/r), not 1/r^2.",
        distractorRationale: {
          B: "This is field dependence, not potential dependence.",
          C: "Potential does not increase linearly with r for a point charge.",
          D: "Constant factor and distance dependence are both incorrect.",
        },
        tags: ["point-potential", "formula", "comparison-with-field"],
      },
      {
        id: "t18-5-d3",
        noteId: "t18-5",
        kind: "mcq",
        difficulty: 3,
        stem: "A +2.0 nC charge moves through potential difference 500 V. Change in electric potential energy is",
        options: [
          { id: "A", text: "+1.0 x 10^-6 J" },
          { id: "B", text: "-1.0 x 10^-6 J" },
          { id: "C", text: "+2.5 x 10^11 J" },
          { id: "D", text: "-2.5 x 10^11 J" },
        ],
        correctOptionId: "A",
        explanation: "Delta U = q Delta V = 2.0 x 10^-9 x 500 = 1.0 x 10^-6 J.",
        distractorRationale: {
          B: "Negative sign would depend on moving to lower potential for positive q.",
          C: "This results from dividing instead of multiplying q and V.",
          D: "Magnitude and sign are both non-physical from incorrect arithmetic.",
        },
        tags: ["potential-energy", "calculation", "delta-u"],
      },
      {
        id: "t18-5-d4",
        noteId: "t18-5",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define electric potential and state its SI unit.",
        modelAnswerPoints: [
          "Electric potential is potential energy per unit positive charge at a point.",
          "Equivalent definition: work done per unit positive charge moving from infinity/reference point.",
          "SI unit is volt (V), where 1 V = 1 J C^-1.",
        ],
        workedSolution: [
          "Definition should include per-unit-charge idea clearly.",
          "Unit relation J C^-1 often gains explicit unit mark.",
        ],
        commonMistake: "Confusing potential with field strength.",
        tags: ["definition", "units", "core-concept"],
      },
      {
        id: "t18-5-d5",
        noteId: "t18-5",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Find electric potential 0.25 m from a point charge -6.0 x 10^-9 C.\nTake k = 8.99 x 10^9 N m^2 C^-2.",
        modelAnswerPoints: [
          "Use V = kQ/r.",
          "V = (8.99 x 10^9)(-6.0 x 10^-9)/0.25.",
          "V = -2.16 x 10^2 V.",
          "Negative sign reflects negative source charge.",
        ],
        workedSolution: [
          "Potential is scalar, so sign comes directly from Q sign.",
          "Do not square r in potential formula.",
        ],
        commonMistake: "Using r^2 denominator and getting field expression instead.",
        tags: ["point-potential", "sign", "numerical"],
      },
      {
        id: "t18-5-d6",
        noteId: "t18-5",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A proton moves from point A at +120 V to point B at -80 V.\n(a) Determine potential difference V_B - V_A.\n(b) Find change in electric potential energy.",
        modelAnswerPoints: [
          "Delta V = V_B - V_A = -80 - 120 = -200 V.",
          "Use Delta U = q Delta V.",
          "Delta U = (1.60 x 10^-19)(-200) = -3.2 x 10^-17 J.",
          "Negative Delta U means electric potential energy decreases.",
        ],
        workedSolution: [
          "Subtract potentials in correct order as requested.",
          "Then apply charge sign of proton (positive) directly.",
        ],
        commonMistake: "Using magnitude 200 V without sign and losing energy-direction meaning.",
        tags: ["potential-difference", "energy-change", "sign-handling"],
      },
      {
        id: "t18-5-d7",
        noteId: "t18-5",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Show that for radial field of a point charge, E = -dV/dr gives consistency between V = kQ/r and E = kQ/r^2.",
        modelAnswerPoints: [
          "Start with V = kQ/r = kQ r^-1.",
          "Differentiate: dV/dr = -kQ r^-2.",
          "Hence E = -dV/dr = kQ/r^2.",
          "Sign indicates field points in direction of decreasing potential.",
        ],
        workedSolution: [
          "This links scalar potential to vector field magnitude in radial symmetry.",
          "Keep algebra symbolic to show full derivation cleanly.",
          "Comment on sign meaning for direction interpretation.",
        ],
        commonMistake: "Differentiating 1/r as 1/r^2 without negative sign.",
        tags: ["calculus-link", "field-potential", "derivation"],
      },
      {
        id: "t18-5-d8",
        noteId: "t18-5",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Two point charges are on x-axis: +4.0 nC at x=0 and -2.0 nC at x=0.30 m.\nCalculate electric potential at midpoint x=0.15 m.",
        modelAnswerPoints: [
          "Potential is scalar sum: V = k(Q1/r1 + Q2/r2).",
          "Here r1 = r2 = 0.15 m.",
          "V = 8.99 x 10^9[(4.0 x 10^-9/0.15) + (-2.0 x 10^-9/0.15)].",
          "V = 8.99 x 10^9 x (2.0 x 10^-9/0.15) = 1.20 x 10^2 V.",
        ],
        workedSolution: [
          "Unlike field, potential adds algebraically without vector components.",
          "Keep charge signs during summation.",
          "Equal distances simplify factorization.",
        ],
        commonMistake: "Trying to vector-add potentials as if they were fields.",
        tags: ["superposition", "potential", "midpoint"],
      },
      {
        id: "t18-5-d9",
        noteId: "t18-5",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "An electron starts from rest and is accelerated through potential difference 450 V.\nFind its final speed.\nTake e = 1.60 x 10^-19 C and m_e = 9.11 x 10^-31 kg.",
        modelAnswerPoints: [
          "Electrical work equals kinetic-energy gain: eV = (1/2)mv^2.",
          "v = sqrt(2eV/m).",
          "v = sqrt((2 x 1.60 x 10^-19 x 450)/(9.11 x 10^-31)) = 1.26 x 10^7 m s^-1.",
          "Speed is magnitude; electron direction is opposite field if discussed.",
        ],
        workedSolution: [
          "Use magnitude form for energy conversion.",
          "Potential difference sets energy gain independent of path.",
          "State assumptions: non-relativistic at this speed.",
        ],
        commonMistake: "Using q = -e and concluding negative speed.",
        tags: ["accelerating-potential", "electron", "energy"],
      },
      {
        id: "t18-5-d10",
        noteId: "t18-5",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Compare electric field and electric potential as descriptions of electrostatic space.\nYour answer should include: scalar/vector nature, superposition method, relation to work/energy, and one exam situation where potential is the easier method.",
        modelAnswerPoints: [
          "Electric field is a vector (force per unit positive charge); potential is a scalar (energy per unit charge).",
          "Fields from sources add vectorially; potentials add algebraically with sign.",
          "Work/energy changes are often simpler via Delta U = q Delta V.",
          "Potential is convenient for multi-charge energy or accelerating-p.d. problems where direction details are secondary.",
          "Field is preferred when force direction/particle trajectory is required.",
        ],
        workedSolution: [
          "Structure answer as explicit contrasts to secure comparison marks.",
          "Give one concrete application example for method selection.",
          "Include both conceptual and computational advantages.",
        ],
        commonMistake: "Stating potential is a vector because it has positive/negative values.",
        tags: ["comparison", "evaluation", "high-mark"],
      },
    ],
    flashcards: [
      {
        id: "t18-5-f1",
        noteId: "t18-5",
        difficulty: 1,
        front: "Define electric potential.",
        back: "Potential energy per unit positive charge at a point.",
        examPhrasing: "Equivalent: work done per unit positive charge from reference.",
        tags: ["definition", "potential"],
      },
      {
        id: "t18-5-f2",
        noteId: "t18-5",
        difficulty: 1,
        front: "What is the unit of electric potential?",
        back: "Volt, V = J C^-1.",
        examPhrasing: "Keep J C^-1 in derivation questions.",
        tags: ["units", "volt"],
      },
      {
        id: "t18-5-f3",
        noteId: "t18-5",
        difficulty: 2,
        front: "What is potential due to a point charge?",
        back: "V = kQ/r.",
        examPhrasing: "Potential has 1/r dependence, unlike field's 1/r^2.",
        tags: ["point-charge", "formula"],
      },
      {
        id: "t18-5-f4",
        noteId: "t18-5",
        difficulty: 2,
        front: "How is change in potential energy related to potential difference?",
        back: "Delta U = q Delta V.",
        examPhrasing: "Sign of q and Delta V controls energy increase/decrease.",
        tags: ["energy", "potential-difference"],
      },
      {
        id: "t18-5-f5",
        noteId: "t18-5",
        difficulty: 3,
        front: "Is electric potential a scalar or vector quantity?",
        back: "Scalar.",
        examPhrasing: "This is why potentials add algebraically.",
        tags: ["scalar", "superposition"],
      },
      {
        id: "t18-5-f6",
        noteId: "t18-5",
        difficulty: 3,
        front: "How are electric field and potential linked in one dimension?",
        back: "E = -dV/dr (radial form for point charge).",
        examPhrasing: "Field points toward decreasing potential.",
        tags: ["field-potential", "gradient"],
      },
      {
        id: "t18-5-f7",
        noteId: "t18-5",
        difficulty: 4,
        front: "Why can potential be negative?",
        back: "Reference choice (often infinity = 0) and source charge sign can make V below zero.",
        examPhrasing: "Negative potential does not mean 'no energy'; it means lower relative energy.",
        tags: ["sign", "reference-level"],
      },
      {
        id: "t18-5-f8",
        noteId: "t18-5",
        difficulty: 4,
        front: "When is potential usually easier than field in multi-charge problems?",
        back: "When only energy or potential value is needed, because scalar addition is simpler.",
        examPhrasing: "Avoid unnecessary vector decomposition.",
        tags: ["method-choice", "problem-solving"],
      },
      {
        id: "t18-5-f9",
        noteId: "t18-5",
        difficulty: 5,
        front: "Common confusion between field and potential formulas?",
        back: "Using 1/r^2 in potential or 1/r in field calculations.",
        examPhrasing: "Memorize pair: E ~ 1/r^2, V ~ 1/r.",
        confusionPair: "Point-field formula vs point-potential formula",
        tags: ["errors", "formula-memory"],
      },
      {
        id: "t18-5-f10",
        noteId: "t18-5",
        difficulty: 5,
        front: "High-yield exam flow for accelerating-potential questions?",
        back: "Convert electrical energy gain qV to kinetic energy change, solve speed, then check reasonableness and sign interpretation.",
        examPhrasing: "Energy method is usually shortest and most robust.",
        tags: ["exam-technique", "accelerating-potential"],
      },
    ],
  },
};
