import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC15_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t15-1": {
    noteId: "t15-1",
    drills: [
      {
        id: "t15-1-d1",
        noteId: "t15-1",
        kind: "mcq",
        difficulty: 1,
        stem: "What is meant by one mole of a substance?",
        options: [
          { id: "A", text: "The mass equal to one gram" },
          { id: "B", text: "6.02 x 10^23 particles of the substance" },
          { id: "C", text: "Any gas occupying 1.0 m^3 at room temperature" },
          { id: "D", text: "The amount with mass number 12" },
        ],
        correctOptionId: "B",
        explanation:
          "A mole is the amount of substance containing Avogadro constant number of specified particles.",
        distractorRationale: {
          C: "Volume depends on state conditions and is not the definition of mole.",
          D: "Mass number 12 is linked to carbon-12 calibration, not the definition itself.",
        },
        tags: ["mole", "avogadro-constant", "definition"],
      },
      {
        id: "t15-1-d2",
        noteId: "t15-1",
        kind: "mcq",
        difficulty: 2,
        stem: "A sample has amount of substance n = 0.40 mol. How many molecules does it contain?",
        options: [
          { id: "A", text: "2.4 x 10^22" },
          { id: "B", text: "6.0 x 10^22" },
          { id: "C", text: "2.4 x 10^23" },
          { id: "D", text: "6.0 x 10^23" },
        ],
        correctOptionId: "C",
        explanation:
          "Use N = nN_A = 0.40 x 6.02 x 10^23 = 2.41 x 10^23 molecules.",
        distractorRationale: {
          B: "This often comes from using n = 0.10 mol by mistake.",
          D: "This equals one mole, not 0.40 mol.",
        },
        tags: ["particle-number", "mole-calculation", "avogadro-constant"],
      },
      {
        id: "t15-1-d3",
        noteId: "t15-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Which relation correctly links mass m, molar mass M, and amount n?",
        options: [
          { id: "A", text: "n = M/m" },
          { id: "B", text: "n = mM" },
          { id: "C", text: "n = m/M" },
          { id: "D", text: "n = m + M" },
        ],
        correctOptionId: "C",
        explanation:
          "Amount of substance equals mass divided by molar mass, with consistent units.",
        distractorRationale: {
          B: "Multiplying gives wrong dimensions.",
          D: "Addition is physically meaningless here.",
        },
        tags: ["molar-mass", "equation", "units"],
      },
      {
        id: "t15-1-d4",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define Avogadro constant and state its unit.",
        modelAnswerPoints: [
          "Avogadro constant N_A is the number of specified particles in one mole.",
          "Its value is about 6.02 x 10^23 mol^-1.",
          "Unit is per mole (mol^-1).",
        ],
        workedSolution: [
          "State it as particles per mole, not as a pure count alone.",
          "Include both approximate value and unit for full credit.",
        ],
        commonMistake: "Writing unit as mol instead of mol^-1.",
        tags: ["definitions", "avogadro-constant", "units"],
      },
      {
        id: "t15-1-d5",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A gas sample has mass 0.176 g and molar mass 44.0 g mol^-1.\n(a) Calculate amount of substance.\n(b) Find number of molecules.",
        modelAnswerPoints: [
          "n = m/M = 0.176 / 44.0 = 4.00 x 10^-3 mol.",
          "Use N = nN_A.",
          "N = 4.00 x 10^-3 x 6.02 x 10^23 = 2.41 x 10^21 molecules.",
          "Quote answer to sensible significant figures.",
        ],
        workedSolution: [
          "Use grams consistently because molar mass is in g mol^-1.",
          "Convert from moles to molecules in the second step using N_A.",
          "Keep powers of ten explicit to avoid calculator slips.",
        ],
        commonMistake: "Converting 0.176 g to kg while leaving M in g mol^-1.",
        tags: ["molar-mass", "particle-number", "multi-step"],
      },
      {
        id: "t15-1-d6",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A flask contains 3.01 x 10^22 argon atoms.\n(a) Find amount of argon in moles.\n(b) If molar mass of argon is 40.0 g mol^-1, find mass in grams.",
        modelAnswerPoints: [
          "n = N/N_A = (3.01 x 10^22)/(6.02 x 10^23) = 5.00 x 10^-2 mol.",
          "Use m = nM.",
          "m = 5.00 x 10^-2 x 40.0 = 2.00 g.",
          "State final mass with unit.",
        ],
        workedSolution: [
          "Part (a) reverses the usual N = nN_A relation.",
          "Part (b) directly applies m = nM after finding n.",
          "Track powers of ten carefully across division step.",
        ],
        commonMistake: "Dividing by 10^22 instead of 10^23 in Avogadro constant.",
        tags: ["reverse-calculation", "atoms", "molar-mass"],
      },
      {
        id: "t15-1-d7",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Two gas containers each hold 0.50 mol at the same temperature.\nContainer X has He, container Y has N2.\n(a) Compare number of molecules.\n(b) Compare total mass and explain.",
        modelAnswerPoints: [
          "Both have same amount n, so both contain same number of molecules: nN_A.",
          "Each contains 0.50 x 6.02 x 10^23 molecules.",
          "Mass differs because m = nM and molar masses differ (M_He much smaller than M_N2).",
          "So Y (N2) has greater mass.",
        ],
        workedSolution: [
          "Equal moles imply equal number of entities regardless of gas identity.",
          "Mass comparison requires molar mass, not Avogadro constant.",
          "Separate particle-count argument from mass argument for clarity.",
        ],
        commonMistake: "Assuming heavier molecules mean fewer molecules at the same n.",
        tags: ["conceptual", "mole", "comparisons"],
      },
      {
        id: "t15-1-d8",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A sealed bulb contains oxygen gas O2 of mass 0.96 g.\nTake molar mass of O2 as 32.0 g mol^-1.\n(a) Calculate amount of O2.\n(b) Determine number of O2 molecules.\n(c) Determine number of oxygen atoms.",
        modelAnswerPoints: [
          "n = m/M = 0.96/32.0 = 3.0 x 10^-2 mol.",
          "Number of molecules = nN_A = 3.0 x 10^-2 x 6.02 x 10^23 = 1.81 x 10^22.",
          "Each molecule has 2 atoms.",
          "Number of atoms = 2 x 1.81 x 10^22 = 3.61 x 10^22.",
        ],
        workedSolution: [
          "Compute moles first from mass and molar mass.",
          "Convert to molecules with Avogadro constant.",
          "Apply molecular composition factor to go from molecules to atoms.",
        ],
        commonMistake: "Forgetting to multiply by 2 when counting oxygen atoms.",
        tags: ["stoichiometric-counting", "molecules-vs-atoms", "exam-style"],
      },
      {
        id: "t15-1-d9",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A gas sample contains 1.20 x 10^24 molecules and has mass 88.0 g.\nCalculate its molar mass.",
        modelAnswerPoints: [
          "First find amount: n = N/N_A = (1.20 x 10^24)/(6.02 x 10^23) = 1.99 mol.",
          "Use M = m/n.",
          "M = 88.0/1.99 = 44.2 g mol^-1.",
          "Molar mass is about 44 g mol^-1.",
        ],
        workedSolution: [
          "This is an inverse problem: particles -> moles -> molar mass.",
          "Do not round n too early because it controls final M accuracy.",
          "Include correct molar-mass unit in final line.",
        ],
        commonMistake: "Using N_A/N instead of N/N_A when finding moles.",
        tags: ["inverse-problem", "molar-mass", "particle-number"],
      },
      {
        id: "t15-1-d10",
        noteId: "t15-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A mixture contains 0.30 mol of CH4 and 0.20 mol of CO2.\n(a) Calculate total number of molecules in the mixture.\n(b) Find total mass, taking M(CH4)=16.0 g mol^-1 and M(CO2)=44.0 g mol^-1.\n(c) Determine the fraction of molecules that are CO2.",
        modelAnswerPoints: [
          "Total moles = 0.30 + 0.20 = 0.50 mol.",
          "Total molecules = 0.50N_A = 3.01 x 10^23.",
          "Mass CH4 = 0.30 x 16.0 = 4.8 g; mass CO2 = 0.20 x 44.0 = 8.8 g.",
          "Total mass = 13.6 g.",
          "Molecular fraction CO2 = 0.20/0.50 = 0.40 (40%).",
        ],
        workedSolution: [
          "Treat each component separately for mass before adding.",
          "Particle count in a mixture is still based on total amount in moles.",
          "For molecular fraction, moles can be used directly because each mole has N_A molecules.",
        ],
        commonMistake: "Using mass fraction instead of molecular fraction in part (c).",
        tags: ["gas-mixtures", "mole-fraction", "multi-step"],
      },
    ],
    flashcards: [
      {
        id: "t15-1-f1",
        noteId: "t15-1",
        difficulty: 1,
        front: "Define one mole.",
        back: "One mole is the amount of substance containing 6.02 x 10^23 specified particles.",
        examPhrasing: "A mole contains Avogadro number of entities.",
        tags: ["mole", "definition"],
      },
      {
        id: "t15-1-f2",
        noteId: "t15-1",
        difficulty: 1,
        front: "State the value and unit of Avogadro constant.",
        back: "N_A is approximately 6.02 x 10^23 mol^-1.",
        examPhrasing: "Avogadro constant gives particles per mole.",
        tags: ["avogadro-constant", "units"],
      },
      {
        id: "t15-1-f3",
        noteId: "t15-1",
        difficulty: 2,
        front: "Write the equation linking particles N, moles n, and N_A.",
        back: "N = nN_A.",
        examPhrasing: "Use n = N/N_A when rearranging.",
        tags: ["equation", "particle-number"],
      },
      {
        id: "t15-1-f4",
        noteId: "t15-1",
        difficulty: 2,
        front: "Write the relation between mass, molar mass, and amount.",
        back: "n = m/M and equivalently m = nM.",
        examPhrasing: "Keep mass and molar-mass units consistent.",
        tags: ["molar-mass", "formula"],
      },
      {
        id: "t15-1-f5",
        noteId: "t15-1",
        difficulty: 3,
        front: "If two samples each contain 1.0 mol of different gases, what is definitely equal?",
        back: "They contain the same number of molecules, N_A each.",
        examPhrasing: "Equal moles imply equal numbers of entities.",
        confusionPair: "Equal number of molecules vs equal mass",
        tags: ["concept", "comparisons"],
      },
      {
        id: "t15-1-f6",
        noteId: "t15-1",
        difficulty: 3,
        front: "How do you convert molecule count to atom count for O2?",
        back: "Multiply number of O2 molecules by 2.",
        examPhrasing: "Account for particles per molecule explicitly.",
        tags: ["counting-particles", "molecules-vs-atoms"],
      },
      {
        id: "t15-1-f7",
        noteId: "t15-1",
        difficulty: 4,
        front: "What is the likely unit error in mole calculations with gases?",
        back: "Mixing kg with g mol^-1 (or g with kg mol^-1) without conversion.",
        examPhrasing: "Unit consistency is essential before substitution.",
        tags: ["units", "pitfalls"],
      },
      {
        id: "t15-1-f8",
        noteId: "t15-1",
        difficulty: 4,
        front: "How do you find molar mass from mass and particle count?",
        back: "Find n from N/N_A, then calculate M = m/n.",
        examPhrasing: "Use a two-stage approach: particles -> moles -> M.",
        tags: ["inverse-method", "molar-mass"],
      },
      {
        id: "t15-1-f9",
        noteId: "t15-1",
        difficulty: 5,
        front: "In a gas mixture, what equals mole fraction of a component?",
        back: "Its molecular fraction (number fraction), assuming entities are molecules.",
        examPhrasing: "x_i = n_i / n_total.",
        confusionPair: "Mole fraction vs mass fraction",
        tags: ["mixtures", "fractions"],
      },
      {
        id: "t15-1-f10",
        noteId: "t15-1",
        difficulty: 5,
        front: "Exam checklist for mole questions?",
        back: "Identify target quantity, choose correct relation, check units, keep powers of ten explicit, round at the end.",
        examPhrasing: "Method marks reward clear sequence plus correct units.",
        tags: ["exam-technique", "problem-solving"],
      },
    ],
  },
  "t15-2": {
    noteId: "t15-2",
    drills: [
      {
        id: "t15-2-d1",
        noteId: "t15-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which equation is the ideal-gas equation of state?",
        options: [
          { id: "A", text: "pV = nRT" },
          { id: "B", text: "pV = nR/T" },
          { id: "C", text: "p/T = nRV" },
          { id: "D", text: "pV = RT/n" },
        ],
        correctOptionId: "A",
        explanation: "For an ideal gas, pressure, volume, and temperature satisfy pV = nRT.",
        distractorRationale: {
          B: "Temperature should multiply in denominator only after rearranging pV/T = nR.",
          C: "This has incorrect dimensions.",
          D: "This applies only for n = 1 and still with wrong placement.",
        },
        tags: ["ideal-gas-equation", "equation-recall"],
      },
      {
        id: "t15-2-d2",
        noteId: "t15-2",
        kind: "mcq",
        difficulty: 2,
        stem: "In pV = nRT, temperature T must be measured in",
        options: [
          { id: "A", text: "degrees Celsius" },
          { id: "B", text: "Kelvin" },
          { id: "C", text: "Fahrenheit" },
          { id: "D", text: "Either Celsius or Kelvin with same result" },
        ],
        correctOptionId: "B",
        explanation: "Thermodynamic equations require absolute temperature in kelvin.",
        distractorRationale: {
          C: "Fahrenheit is not used in SI gas equations.",
          D: "Using Celsius introduces an offset error.",
        },
        tags: ["temperature-scale", "ideal-gases"],
      },
      {
        id: "t15-2-d3",
        noteId: "t15-2",
        kind: "mcq",
        difficulty: 3,
        stem:
          "A fixed amount of ideal gas is heated at constant volume from 300 K to 360 K. If initial pressure is 1.50 x 10^5 Pa, final pressure is",
        options: [
          { id: "A", text: "1.25 x 10^5 Pa" },
          { id: "B", text: "1.50 x 10^5 Pa" },
          { id: "C", text: "1.80 x 10^5 Pa" },
          { id: "D", text: "2.16 x 10^5 Pa" },
        ],
        correctOptionId: "C",
        explanation:
          "At constant V and n, p proportional T, so p2 = p1(T2/T1) = 1.50 x 10^5 x (360/300) = 1.80 x 10^5 Pa.",
        distractorRationale: {
          B: "Pressure changes when temperature changes at fixed volume.",
          D: "This over-scales by applying ratio twice.",
        },
        tags: ["constant-volume", "pressure-temperature", "proportionality"],
      },
      {
        id: "t15-2-d4",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State the ideal-gas equation and define each symbol.",
        modelAnswerPoints: [
          "Equation: pV = nRT.",
          "p is pressure, V is gas volume, n is amount of substance, T is absolute temperature.",
          "R is universal gas constant.",
        ],
        workedSolution: [
          "Write symbols with SI units where possible (Pa, m^3, mol, K).",
          "Mention that T is absolute temperature to secure key concept mark.",
        ],
        commonMistake: "Stating T in degrees Celsius.",
        tags: ["definitions", "equation-of-state", "symbols"],
      },
      {
        id: "t15-2-d5",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A cylinder contains 0.25 mol of gas at pressure 1.2 x 10^5 Pa and temperature 300 K.\nCalculate the gas volume. Take R = 8.31 J mol^-1 K^-1.",
        modelAnswerPoints: [
          "Use V = nRT/p.",
          "V = (0.25 x 8.31 x 300)/(1.2 x 10^5).",
          "V = 5.19 x 10^-3 m^3.",
          "Equivalent to 5.19 L.",
        ],
        workedSolution: [
          "Rearrange equation before substitution to reduce algebra mistakes.",
          "Keep SI pressure units and kelvin throughout.",
          "Optional conversion to litres can be quoted after SI answer.",
        ],
        commonMistake: "Using p = 1.2 x 10^5 kPa instead of Pa.",
        tags: ["calculation", "volume", "ideal-gas-equation"],
      },
      {
        id: "t15-2-d6",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A fixed mass of ideal gas occupies 2.4 x 10^-3 m^3 at 290 K and 9.5 x 10^4 Pa.\nThe gas is compressed isothermally to 1.6 x 10^-3 m^3.\nFind final pressure.",
        modelAnswerPoints: [
          "For isothermal fixed mass, pV = constant.",
          "p1V1 = p2V2.",
          "p2 = p1V1/V2 = 9.5 x 10^4 x (2.4/1.6).",
          "p2 = 1.43 x 10^5 Pa.",
        ],
        workedSolution: [
          "Isothermal means temperature unchanged, enabling Boyle-law form.",
          "Use volume ratio directly with consistent powers of ten.",
          "State pressure with appropriate significant figures.",
        ],
        commonMistake: "Using temperature ratio even though process is isothermal.",
        tags: ["isothermal", "boyle-law", "compression"],
      },
      {
        id: "t15-2-d7",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "A gas sample at 27 degrees C and pressure 1.00 x 10^5 Pa has volume 3.00 x 10^-3 m^3.\nIt is heated at constant pressure to 87 degrees C.\nCalculate final volume.",
        modelAnswerPoints: [
          "Convert temperatures: T1 = 300 K, T2 = 360 K.",
          "At constant pressure and fixed amount, V proportional T.",
          "V2 = V1(T2/T1) = 3.00 x 10^-3 x (360/300).",
          "V2 = 3.60 x 10^-3 m^3.",
        ],
        workedSolution: [
          "Use Charles-law proportionality only after converting to kelvin.",
          "Maintain same pressure condition explicitly in method.",
          "Final answer may also be given as 3.60 L.",
        ],
        commonMistake: "Using 87/27 instead of 360/300.",
        tags: ["constant-pressure", "temperature-conversion", "gas-laws"],
      },
      {
        id: "t15-2-d8",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A vessel of volume 1.80 x 10^-2 m^3 contains nitrogen gas at 2.40 x 10^5 Pa and 320 K.\n(a) Find amount of gas.\n(b) Find gas mass, taking molar mass of N2 as 28.0 g mol^-1.\nUse R = 8.31 J mol^-1 K^-1.",
        modelAnswerPoints: [
          "n = pV/(RT) = (2.40 x 10^5 x 1.80 x 10^-2)/(8.31 x 320) = 1.62 mol.",
          "Use m = nM.",
          "m = 1.62 x 28.0 = 45.4 g.",
          "Equivalent SI mass is 4.54 x 10^-2 kg.",
        ],
        workedSolution: [
          "Part (a) uses full equation of state in rearranged form.",
          "Part (b) links amount to mass using molar mass.",
          "Keep track of g vs kg in final reporting.",
        ],
        commonMistake: "Taking molar mass as 28.0 kg mol^-1.",
        tags: ["combined-application", "moles-and-mass", "equation-of-state"],
      },
      {
        id: "t15-2-d9",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A gas initially has p1 = 1.2 x 10^5 Pa, V1 = 4.0 x 10^-3 m^3, T1 = 300 K.\nAfter a change, p2 = 2.0 x 10^5 Pa and T2 = 400 K.\nDetermine V2.",
        modelAnswerPoints: [
          "For fixed amount, pV/T = constant.",
          "p1V1/T1 = p2V2/T2.",
          "V2 = V1 x (p1/p2) x (T2/T1).",
          "V2 = 4.0 x 10^-3 x (1.2/2.0) x (400/300) = 3.2 x 10^-3 m^3.",
        ],
        workedSolution: [
          "Use the combined-gas relation for simultaneous p and T changes.",
          "Substitute ratios to reduce arithmetic handling of powers of ten.",
          "Check result trend: increased p tends to reduce V, increased T tends to increase V.",
        ],
        commonMistake: "Using T1/T2 instead of T2/T1 in rearranged expression.",
        tags: ["combined-gas-law", "state-change", "reasonableness-check"],
      },
      {
        id: "t15-2-d10",
        noteId: "t15-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A 3.0 L tyre is inflated from 2.2 x 10^5 Pa at 290 K to 3.0 x 10^5 Pa at 315 K.\nAssume tyre volume remains constant and air behaves ideally.\n(a) Determine ratio of final to initial amount of gas n2/n1.\n(b) If initial amount is 0.274 mol, find final amount and additional moles added.",
        modelAnswerPoints: [
          "At constant V, n proportional p/T because n = pV/(RT).",
          "n2/n1 = (p2/p1)(T1/T2) = (3.0/2.2)(290/315) = 1.25 (approx).",
          "n2 = 1.25 x 0.274 = 0.343 mol.",
          "Added amount = n2 - n1 = 0.069 mol.",
        ],
        workedSolution: [
          "Use ratio form to avoid repeated substitution of constants V, R.",
          "Carry enough significant figures in ratio before applying to n1.",
          "Interpret result physically: higher pressure despite warmer tyre implies added gas.",
        ],
        commonMistake: "Assuming n is constant and treating it as simple pressure-temperature relation.",
        tags: ["variable-amount", "applications", "high-yield"],
      },
    ],
    flashcards: [
      {
        id: "t15-2-f1",
        noteId: "t15-2",
        difficulty: 1,
        front: "State the ideal-gas equation.",
        back: "pV = nRT.",
        examPhrasing: "Use SI units: p in Pa, V in m^3, T in K.",
        tags: ["equation", "ideal-gases"],
      },
      {
        id: "t15-2-f2",
        noteId: "t15-2",
        difficulty: 1,
        front: "What value of R is used in SI calculations?",
        back: "R = 8.31 J mol^-1 K^-1 (approximately).",
        examPhrasing: "R is the universal gas constant.",
        tags: ["constants", "units"],
      },
      {
        id: "t15-2-f3",
        noteId: "t15-2",
        difficulty: 2,
        front: "Why must temperature be in kelvin for gas equations?",
        back: "Kelvin is an absolute scale proportional to molecular kinetic energy.",
        examPhrasing: "Celsius must be converted before substitution.",
        confusionPair: "Celsius vs kelvin in proportional laws",
        tags: ["temperature", "pitfalls"],
      },
      {
        id: "t15-2-f4",
        noteId: "t15-2",
        difficulty: 2,
        front: "For fixed n and T, how are pressure and volume related?",
        back: "p is inversely proportional to V, so pV = constant.",
        examPhrasing: "This is Boyle's law form of the ideal-gas equation.",
        tags: ["boyle-law", "proportionality"],
      },
      {
        id: "t15-2-f5",
        noteId: "t15-2",
        difficulty: 3,
        front: "For fixed n and p, how are volume and temperature related?",
        back: "V is directly proportional to T (in kelvin).",
        examPhrasing: "V/T = constant at constant pressure.",
        tags: ["charles-law", "proportionality"],
      },
      {
        id: "t15-2-f6",
        noteId: "t15-2",
        difficulty: 3,
        front: "For fixed n and V, how are pressure and temperature related?",
        back: "p is directly proportional to T (in kelvin).",
        examPhrasing: "p/T = constant at constant volume.",
        tags: ["pressure-law", "proportionality"],
      },
      {
        id: "t15-2-f7",
        noteId: "t15-2",
        difficulty: 4,
        front: "Write the combined relation between two states for fixed gas amount.",
        back: "p1V1/T1 = p2V2/T2.",
        examPhrasing: "Derived from pV = nRT with constant n.",
        tags: ["combined-gas-law", "state-variables"],
      },
      {
        id: "t15-2-f8",
        noteId: "t15-2",
        difficulty: 4,
        front: "How can n be found from macroscopic gas measurements?",
        back: "Use n = pV/(RT).",
        examPhrasing: "Then use m = nM if mass is required.",
        tags: ["amount-of-substance", "applications"],
      },
      {
        id: "t15-2-f9",
        noteId: "t15-2",
        difficulty: 5,
        front: "How do you check if a gas-calculation answer is physically sensible?",
        back: "Check trend with variable changes, verify SI units, and confirm magnitude order (e.g. litres vs m^3).",
        examPhrasing: "Reasonableness checks can catch ratio inversions.",
        tags: ["exam-technique", "quality-control"],
      },
      {
        id: "t15-2-f10",
        noteId: "t15-2",
        difficulty: 5,
        front: "Most frequent high-mark error in equation-of-state questions?",
        back: "Using Celsius directly or inconsistent pressure/volume units.",
        examPhrasing: "Convert first, then substitute.",
        tags: ["common-errors", "high-yield"],
      },
    ],
  },
  "t15-3": {
    noteId: "t15-3",
    drills: [
      {
        id: "t15-3-d1",
        noteId: "t15-3",
        kind: "mcq",
        difficulty: 1,
        stem: "In the kinetic model of an ideal gas, gas pressure is caused by",
        options: [
          { id: "A", text: "Mutual attraction between molecules" },
          { id: "B", text: "Collisions of molecules with container walls" },
          { id: "C", text: "Weight of gas molecules only" },
          { id: "D", text: "Chemical reactions among molecules" },
        ],
        correctOptionId: "B",
        explanation:
          "Molecules transfer momentum to walls during collisions, producing force and hence pressure.",
        distractorRationale: {
          C: "Weight contributes only tiny hydrostatic gradients in many contexts.",
          D: "Ideal-gas pressure does not require reactions.",
        },
        tags: ["kinetic-theory", "pressure-origin", "microscopic-model"],
      },
      {
        id: "t15-3-d2",
        noteId: "t15-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which assumption is part of the ideal-gas kinetic model?",
        options: [
          { id: "A", text: "Molecules have significant own volume compared with container volume" },
          { id: "B", text: "Collisions between molecules are perfectly inelastic" },
          { id: "C", text: "Intermolecular forces are negligible except during collisions" },
          { id: "D", text: "All molecules move at exactly the same speed" },
        ],
        correctOptionId: "C",
        explanation:
          "Ideal-gas theory assumes negligible intermolecular forces except during instantaneous collisions.",
        distractorRationale: {
          B: "Collisions are modeled as elastic, not inelastic.",
          D: "Speeds are distributed, not identical.",
        },
        tags: ["assumptions", "ideal-gas-model"],
      },
      {
        id: "t15-3-d3",
        noteId: "t15-3",
        kind: "mcq",
        difficulty: 3,
        stem: "For an ideal gas sample, mean translational kinetic energy per molecule is proportional to",
        options: [
          { id: "A", text: "Pressure only" },
          { id: "B", text: "Volume only" },
          { id: "C", text: "Absolute temperature" },
          { id: "D", text: "Molar mass only" },
        ],
        correctOptionId: "C",
        explanation:
          "Mean molecular kinetic energy is (3/2)kT, directly proportional to absolute temperature.",
        distractorRationale: {
          B: "Volume alone does not determine molecular kinetic energy.",
          D: "At fixed T, different gases have same mean kinetic energy per molecule.",
        },
        tags: ["mean-kinetic-energy", "temperature", "boltzmann"],
      },
      {
        id: "t15-3-d4",
        noteId: "t15-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State three key assumptions of the kinetic theory model for an ideal gas.",
        modelAnswerPoints: [
          "Molecules are in continuous random motion.",
          "Collisions (molecule-molecule and molecule-wall) are perfectly elastic.",
          "Intermolecular forces are negligible except during collisions and molecular volume is negligible compared with container volume.",
        ],
        workedSolution: [
          "Any three valid assumptions gain credit if clearly stated.",
          "Do not mix assumptions with consequences unless linked explicitly.",
        ],
        commonMistake: "Claiming molecules move in straight lines without mentioning collisions.",
        tags: ["assumptions", "theory", "core-knowledge"],
      },
      {
        id: "t15-3-d5",
        noteId: "t15-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Explain, using momentum change, how gas molecules exert pressure on container walls.",
        modelAnswerPoints: [
          "A molecule striking a wall reverses its normal velocity component in an elastic collision.",
          "Its momentum changes, so by Newton's second law there is a force on the molecule.",
          "By Newton's third law, wall experiences equal opposite force from molecule.",
          "Many collisions per second produce steady macroscopic pressure (force per unit area).",
        ],
        workedSolution: [
          "Link microscopic momentum transfer to macroscopic pressure definition p = F/A.",
          "Mention collision rate to justify time-averaged steady pressure.",
        ],
        commonMistake: "Describing pressure as due only to molecule weight, not collisions.",
        tags: ["momentum", "pressure", "newton-laws"],
      },
      {
        id: "t15-3-d6",
        noteId: "t15-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "State the relation between pressure p and root-mean-square speed c_rms for a gas of density rho, and use it to find c_rms when p = 1.01 x 10^5 Pa and rho = 1.20 kg m^-3.",
        modelAnswerPoints: [
          "Use p = (1/3)rho c_rms^2.",
          "So c_rms = sqrt(3p/rho).",
          "c_rms = sqrt((3 x 1.01 x 10^5)/1.20) = 5.02 x 10^2 m s^-1.",
          "c_rms is about 502 m s^-1.",
        ],
        workedSolution: [
          "Rearrange before substitution to minimize algebra errors.",
          "Check that high molecular speeds are reasonable for gases at room conditions.",
        ],
        commonMistake: "Using c_rms = 3p/rho without square root.",
        tags: ["crms", "kinetic-equation", "numerical"],
      },
      {
        id: "t15-3-d7",
        noteId: "t15-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "For an ideal gas, mean translational kinetic energy per molecule is E_bar = (3/2)kT.\n(a) Calculate E_bar at T = 300 K using k = 1.38 x 10^-23 J K^-1.\n(b) Explain why this supports using kelvin in gas laws.",
        modelAnswerPoints: [
          "E_bar = (3/2)kT = 1.5 x 1.38 x 10^-23 x 300 = 6.21 x 10^-21 J.",
          "Kinetic energy is proportional to absolute temperature T.",
          "Kelvin has true zero at zero thermal energy limit.",
          "Hence proportional gas relations require absolute, not Celsius, scale.",
        ],
        workedSolution: [
          "Part (a) is direct substitution with scientific notation.",
          "Part (b) links microscopic energy interpretation to macroscopic gas-law usage.",
          "Emphasize the additive offset issue in Celsius.",
        ],
        commonMistake: "Using T = 27 instead of 300 K.",
        tags: ["boltzmann-constant", "mean-kinetic-energy", "temperature-scale"],
      },
      {
        id: "t15-3-d8",
        noteId: "t15-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "One mole of helium and one mole of oxygen are both at 350 K.\n(a) Compare mean kinetic energy per molecule.\n(b) Compare rms speeds qualitatively and justify.",
        modelAnswerPoints: [
          "Mean kinetic energy per molecule depends only on T: same for both gases.",
          "For rms speed, c_rms proportional 1/sqrt(M) at fixed T.",
          "Helium has smaller molar mass than oxygen, so helium has larger c_rms.",
          "This does not contradict equal mean kinetic energy because mass differs.",
        ],
        workedSolution: [
          "Separate energy-per-molecule statement from speed statement.",
          "Use c_rms = sqrt(3RT/M) or equivalent proportional form.",
          "Heavier molecules move more slowly on average at same T.",
        ],
        commonMistake: "Assuming equal temperature means equal molecular speeds for all gases.",
        tags: ["comparative-reasoning", "crms", "mean-energy"],
      },
      {
        id: "t15-3-d9",
        noteId: "t15-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A gas has pressure 2.5 x 10^5 Pa and density 3.2 kg m^-3.\n(a) Calculate c_rms.\n(b) If pressure doubles at constant density, determine new c_rms and explain.",
        modelAnswerPoints: [
          "c_rms = sqrt(3p/rho) = sqrt((3 x 2.5 x 10^5)/3.2) = 4.84 x 10^2 m s^-1.",
          "At constant rho, c_rms proportional sqrt(p).",
          "Doubling p multiplies c_rms by sqrt(2).",
          "New c_rms = 4.84 x 10^2 x 1.414 = 6.84 x 10^2 m s^-1.",
        ],
        workedSolution: [
          "Use direct formula for part (a).",
          "Part (b) is quicker with proportional reasoning than full recomputation.",
          "State trend clearly: higher pressure at same density implies higher molecular speed scale.",
        ],
        commonMistake: "Doubling c_rms when pressure doubles.",
        tags: ["proportionality", "crms", "kinetic-model"],
      },
      {
        id: "t15-3-d10",
        noteId: "t15-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Describe why real gases deviate from ideal-gas behavior at high pressure and low temperature.\nYour answer should reference kinetic-theory assumptions and include one consequence for pV = nRT calculations.",
        modelAnswerPoints: [
          "At high pressure, molecular volume is no longer negligible compared with container volume.",
          "At low temperature, intermolecular attractions become significant.",
          "These effects break ideal assumptions of point particles and negligible forces.",
          "Measured pV can differ from nRT prediction; equation gives increasing error.",
          "Corrections/models (e.g., effective volume and attraction terms) may be needed for precision.",
        ],
        workedSolution: [
          "Frame answer around assumptions first, then state how each fails.",
          "Connect microscopic failure to macroscopic equation deviation.",
          "Mention practical implication: ideal-gas estimates become less reliable in these regimes.",
        ],
        commonMistake: "Saying deviations happen because molecules stop moving.",
        tags: ["real-vs-ideal", "limitations", "evaluation"],
      },
    ],
    flashcards: [
      {
        id: "t15-3-f1",
        noteId: "t15-3",
        difficulty: 1,
        front: "What microscopic process causes gas pressure?",
        back: "Momentum transfer during molecular collisions with container walls.",
        examPhrasing: "Pressure arises from force due to rate of momentum change per unit area.",
        tags: ["pressure-origin", "kinetic-theory"],
      },
      {
        id: "t15-3-f2",
        noteId: "t15-3",
        difficulty: 1,
        front: "State one key ideal-gas assumption about collisions.",
        back: "Collisions are perfectly elastic.",
        examPhrasing: "No net kinetic-energy loss in collisions.",
        tags: ["assumptions", "collisions"],
      },
      {
        id: "t15-3-f3",
        noteId: "t15-3",
        difficulty: 2,
        front: "State one key ideal-gas assumption about intermolecular forces.",
        back: "Intermolecular forces are negligible except during collisions.",
        examPhrasing: "Molecules move freely between collisions.",
        tags: ["assumptions", "forces"],
      },
      {
        id: "t15-3-f4",
        noteId: "t15-3",
        difficulty: 2,
        front: "Write the kinetic-theory relation linking pressure and rms speed.",
        back: "p = (1/3)rho c_rms^2.",
        examPhrasing: "Equivalent form: c_rms = sqrt(3p/rho).",
        tags: ["equation", "crms"],
      },
      {
        id: "t15-3-f5",
        noteId: "t15-3",
        difficulty: 3,
        front: "What is mean translational kinetic energy per molecule for an ideal gas?",
        back: "E_bar = (3/2)kT.",
        examPhrasing: "Depends only on absolute temperature.",
        tags: ["mean-kinetic-energy", "boltzmann"],
      },
      {
        id: "t15-3-f6",
        noteId: "t15-3",
        difficulty: 3,
        front: "At the same temperature, do all gases have same mean kinetic energy per molecule?",
        back: "Yes, for ideal gases.",
        examPhrasing: "Mean kinetic energy depends on T, not gas identity.",
        confusionPair: "Equal kinetic energy vs equal speed",
        tags: ["conceptual", "temperature"],
      },
      {
        id: "t15-3-f7",
        noteId: "t15-3",
        difficulty: 4,
        front: "At fixed temperature, how does c_rms depend on molar mass M?",
        back: "c_rms proportional 1/sqrt(M).",
        examPhrasing: "From c_rms = sqrt(3RT/M).",
        tags: ["speed-distribution", "molar-mass"],
      },
      {
        id: "t15-3-f8",
        noteId: "t15-3",
        difficulty: 4,
        front: "Why do real gases deviate from ideal behavior at high pressure?",
        back: "Molecular volume becomes significant, so particles are no longer effectively point-like.",
        examPhrasing: "Finite molecular size reduces free volume available.",
        tags: ["real-gases", "limitations"],
      },
      {
        id: "t15-3-f9",
        noteId: "t15-3",
        difficulty: 5,
        front: "Why do real gases deviate from ideal behavior at low temperature?",
        back: "Intermolecular attractions become significant and alter pressure-volume behavior.",
        examPhrasing: "Negligible-force assumption fails as thermal energy falls.",
        tags: ["real-gases", "intermolecular-forces"],
      },
      {
        id: "t15-3-f10",
        noteId: "t15-3",
        difficulty: 5,
        front: "Exam method for kinetic-theory explanation questions?",
        back: "State assumptions, connect to molecular motion/collisions, then translate to macroscopic relation with clear physics language.",
        examPhrasing: "Link micro model -> momentum change -> pressure/temperature relation.",
        tags: ["exam-technique", "explanations"],
      },
    ],
  },
};
