import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC20_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t20-1": {
    noteId: "t20-1",
    drills: [
      {
        id: "t20-1-d1",
        noteId: "t20-1",
        kind: "mcq",
        difficulty: 1,
        stem: "What is the direction of a magnetic field line at any point?",
        options: [
          { id: "A", text: "Direction of force on a negative charge at rest" },
          { id: "B", text: "Direction of force on a north pole placed there" },
          { id: "C", text: "Direction of electron flow in a conductor" },
          { id: "D", text: "Direction of electric field in vacuum" },
        ],
        correctOptionId: "B",
        explanation: "Magnetic field direction is defined as the direction of force on an isolated north pole.",
        distractorRationale: {
          B: "This is the standard definition of magnetic field direction.",
          C: "Electron flow is a current concept and does not define field-line direction.",
          D: "Electric and magnetic fields are different vector fields.",
        },
        tags: ["field-lines", "definitions", "magnetic-field"],
      },
      {
        id: "t20-1-d2",
        noteId: "t20-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which pattern best represents the field around a long straight current-carrying wire?",
        options: [
          { id: "A", text: "Parallel straight lines" },
          { id: "B", text: "Radial lines outward from the wire" },
          { id: "C", text: "Concentric circles centered on the wire" },
          { id: "D", text: "A uniform field only inside the wire" },
        ],
        correctOptionId: "C",
        explanation: "The magnetic field around a straight wire forms concentric circles around the conductor.",
        distractorRationale: {
          B: "Radial patterns are associated with point-source electric fields.",
          C: "Correct topology for a long straight conductor.",
          D: "Field exists outside the wire and is not uniform only inside.",
        },
        tags: ["field-patterns", "straight-wire", "right-hand-rule"],
      },
      {
        id: "t20-1-d3",
        noteId: "t20-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Two regions have magnetic flux densities 0.20 T and 0.40 T. Which statement is correct?",
        options: [
          { id: "A", text: "The first region has stronger field because 0.20 is smaller." },
          { id: "B", text: "The second region has stronger field because B is larger." },
          { id: "C", text: "Both fields are equal because tesla is a derived unit." },
          { id: "D", text: "Field strength cannot be compared without electric field data." },
        ],
        correctOptionId: "B",
        explanation: "Magnetic flux density magnitude directly indicates magnetic field strength.",
        distractorRationale: {
          B: "Larger B means greater magnetic force on suitable moving charges/currents.",
          C: "Derived-unit status does not affect direct numerical comparison.",
          D: "Magnetic field strength can be compared independently.",
        },
        tags: ["flux-density", "comparison", "units"],
      },
      {
        id: "t20-1-d4",
        noteId: "t20-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define magnetic flux density B and state its SI unit.",
        modelAnswerPoints: [
          "B is a measure of magnetic field strength based on force effects.",
          "For a conductor at right angles to field, B = F/(IL).",
          "SI unit is tesla (T).",
        ],
        workedSolution: [
          "State a force-based definition linked to current-carrying conductor or moving charge.",
          "Include unit explicitly for the final mark.",
        ],
        commonMistake: "Giving unit as N C^-1, which is for electric field strength.",
        tags: ["definitions", "flux-density", "units"],
      },
      {
        id: "t20-1-d5",
        noteId: "t20-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Sketch and describe the magnetic field pattern around a bar magnet.",
        modelAnswerPoints: [
          "Field lines emerge from the north pole and enter the south pole outside the magnet.",
          "Lines form closed loops through and around the magnet.",
          "Field is stronger where lines are closer together, especially near poles.",
          "Arrows indicate direction from N to S outside the magnet.",
        ],
        workedSolution: [
          "Label poles and draw symmetric curved lines.",
          "Ensure arrows and line density both communicate direction and relative strength.",
        ],
        commonMistake: "Drawing lines that start or end in empty space instead of loops.",
        tags: ["bar-magnet", "field-lines", "representation"],
      },
      {
        id: "t20-1-d6",
        noteId: "t20-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain why magnetic field lines never cross.",
        modelAnswerPoints: [
          "Field line tangent gives unique field direction at a point.",
          "If lines crossed, two directions would exist at one point.",
          "That is physically impossible for a single vector field value.",
          "So crossing lines are not allowed in valid field maps.",
        ],
        workedSolution: [
          "Use the vector definition of field direction at a point.",
          "Link directly to the contradiction created by crossing lines.",
        ],
        commonMistake: "Saying lines do not cross only because of drawing convention.",
        tags: ["field-lines", "vector-field", "conceptual"],
      },
      {
        id: "t20-1-d7",
        noteId: "t20-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A straight conductor of length 0.060 m carries 2.0 A at right angles to a uniform field and experiences force 0.024 N. Calculate B.",
        modelAnswerPoints: [
          "Use F = BIL for conductor at 90 degrees.",
          "Rearrange to B = F/(IL).",
          "B = 0.024 / (2.0 x 0.060).",
          "B = 0.20 T.",
        ],
        workedSolution: [
          "Identify that angle factor is 1 at right angles.",
          "Substitute in SI units directly to get tesla.",
        ],
        commonMistake: "Using length in cm without converting to m.",
        tags: ["calculation", "flux-density", "force-on-conductor"],
      },
      {
        id: "t20-1-d8",
        noteId: "t20-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Describe how iron filings and a plotting compass can be used together to map a magnetic field around a magnet.",
        modelAnswerPoints: [
          "Iron filings show approximate field pattern and relative strength by spacing.",
          "A plotting compass gives local field direction at chosen points.",
          "Move compass point-to-point and mark tangent directions.",
          "Join direction marks to form field lines with arrows.",
          "Repeat in multiple regions to build full map.",
        ],
        workedSolution: [
          "Filings are qualitative and can clump, so compass measurements refine direction.",
          "Combining both methods gives both pattern shape and direction reliably.",
        ],
        commonMistake: "Assuming iron filings alone provide exact directional arrows.",
        tags: ["experimental-method", "field-mapping", "compass"],
      },
      {
        id: "t20-1-d9",
        noteId: "t20-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A beam of electrons enters a uniform magnetic field region and curves. Explain what this shows about magnetic fields and charged particles.",
        modelAnswerPoints: [
          "A moving charge in magnetic field experiences magnetic force.",
          "Force is perpendicular to velocity and field direction.",
          "Perpendicular force changes direction of motion, producing curvature.",
          "Speed may stay approximately constant if no work is done by magnetic force.",
          "Curvature direction depends on sign of charge.",
        ],
        workedSolution: [
          "State force-direction property first, then connect to curved path.",
          "Mention the sign dependence to explain electron versus positive particle behavior.",
        ],
        commonMistake: "Claiming magnetic field force acts along the motion and speeds the particle up.",
        tags: ["charged-particles", "qualitative", "deflection"],
      },
      {
        id: "t20-1-d10",
        noteId: "t20-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "Compare uniform and non-uniform magnetic fields and explain one practical consequence of each for charged-particle motion.",
        modelAnswerPoints: [
          "Uniform field has constant magnitude and direction over region (parallel equally spaced lines).",
          "Non-uniform field has varying magnitude and/or direction (uneven spacing/curved pattern).",
          "In uniform field, charged particle can follow predictable circular/arc path for fixed speed component.",
          "In non-uniform field, path curvature changes along trajectory.",
          "This affects design and control precision in beam steering devices.",
        ],
        workedSolution: [
          "Use field-line geometry language to distinguish the two cases.",
          "Then connect each case to resulting motion predictability and engineering use.",
        ],
        commonMistake: "Confusing non-uniform field with field reversal only.",
        tags: ["uniform-field", "non-uniform-field", "applications"],
      },
    ],
    flashcards: [
      {
        id: "t20-1-f1",
        noteId: "t20-1",
        difficulty: 1,
        front: "How is magnetic field direction defined at a point?",
        back: "It is the direction of force on a free north pole placed at that point.",
        examPhrasing: "Field direction follows force on an isolated north pole.",
        tags: ["definitions", "field-direction"],
      },
      {
        id: "t20-1-f2",
        noteId: "t20-1",
        difficulty: 1,
        front: "What does close spacing of magnetic field lines indicate?",
        back: "A stronger magnetic field (larger flux density).",
        examPhrasing: "Line density gives qualitative field strength.",
        tags: ["field-lines", "strength"],
      },
      {
        id: "t20-1-f3",
        noteId: "t20-1",
        difficulty: 2,
        front: "Why can magnetic field lines not cross?",
        back: "Because field direction at one point must be unique.",
        examPhrasing: "Crossing would imply two field directions at one point.",
        tags: ["field-lines", "conceptual"],
      },
      {
        id: "t20-1-f4",
        noteId: "t20-1",
        difficulty: 2,
        front: "State the SI unit of magnetic flux density.",
        back: "Tesla (T).",
        examPhrasing: "Magnetic flux density B is measured in tesla.",
        tags: ["units", "flux-density"],
      },
      {
        id: "t20-1-f5",
        noteId: "t20-1",
        difficulty: 3,
        front: "Give a force-based expression for B using a straight conductor at right angles.",
        back: "B = F/(IL).",
        examPhrasing: "From F = BIL for 90 degrees orientation.",
        tags: ["equations", "force-on-conductor"],
      },
      {
        id: "t20-1-f6",
        noteId: "t20-1",
        difficulty: 3,
        front: "What is the magnetic field pattern around a long straight wire?",
        back: "Concentric circular field lines centered on the wire.",
        examPhrasing: "Use right-hand grip rule to set direction.",
        tags: ["straight-wire", "patterns"],
      },
      {
        id: "t20-1-f7",
        noteId: "t20-1",
        difficulty: 4,
        front: "How do you identify field direction experimentally?",
        back: "Use a plotting compass; the needle aligns tangentially with the local field.",
        examPhrasing: "Compass north end points along the magnetic field line direction.",
        tags: ["experimental", "compass"],
      },
      {
        id: "t20-1-f8",
        noteId: "t20-1",
        difficulty: 4,
        front: "What is the key difference between uniform and non-uniform magnetic fields?",
        back: "Uniform fields have constant B and direction; non-uniform fields vary with position.",
        examPhrasing: "Uniform fields are shown by parallel equally spaced lines.",
        tags: ["uniform-field", "comparison"],
      },
      {
        id: "t20-1-f9",
        noteId: "t20-1",
        difficulty: 5,
        front: "Why does a magnetic field change direction but not speed of a moving charge?",
        back: "Magnetic force is perpendicular to velocity, so it does no work.",
        examPhrasing: "Perpendicular force changes momentum direction, not kinetic energy.",
        confusionPair: "Direction change vs speed change",
        tags: ["charged-particles", "work-done"],
      },
      {
        id: "t20-1-f10",
        noteId: "t20-1",
        difficulty: 5,
        front: "What is a common diagram error in magnetic field maps?",
        back: "Missing arrows or crossing lines, which make direction ambiguous or impossible.",
        examPhrasing: "Valid field maps require directional arrows and non-crossing lines.",
        tags: ["exam-technique", "diagram-quality"],
      },
    ],
  },
  "t20-2": {
    noteId: "t20-2",
    drills: [
      {
        id: "t20-2-d1",
        noteId: "t20-2",
        kind: "mcq",
        difficulty: 1,
        stem: "A straight conductor carries current in a magnetic field. When is magnetic force maximum?",
        options: [
          { id: "A", text: "Conductor parallel to field lines" },
          { id: "B", text: "Conductor at 45 degrees to field lines" },
          { id: "C", text: "Conductor perpendicular to field lines" },
          { id: "D", text: "Force is independent of angle" },
        ],
        correctOptionId: "C",
        explanation: "From F = BIL sin(theta), force is maximum when theta = 90 degrees.",
        distractorRationale: {
          B: "At 45 degrees, force is lower by a sin(45) factor.",
          C: "Perpendicular orientation gives sin(theta) = 1.",
          D: "Angle dependence is explicit in the sine factor.",
        },
        tags: ["force-on-conductor", "angles", "equation"],
      },
      {
        id: "t20-2-d2",
        noteId: "t20-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Which rule gives the direction of force on a current-carrying conductor in a magnetic field?",
        options: [
          { id: "A", text: "Right-hand grip rule" },
          { id: "B", text: "Fleming's left-hand rule" },
          { id: "C", text: "Lenz's law" },
          { id: "D", text: "Right-hand palm rule for electric field" },
        ],
        correctOptionId: "B",
        explanation: "Fleming's left-hand rule links field, current, and force directions for motors.",
        distractorRationale: {
          B: "Correct directional rule for motor effect.",
          C: "Lenz's law predicts induced-current direction, not motor-force direction.",
          D: "This is not a standard rule in this syllabus context.",
        },
        tags: ["direction-rules", "motor-effect"],
      },
      {
        id: "t20-2-d3",
        noteId: "t20-2",
        kind: "mcq",
        difficulty: 3,
        stem: "A wire segment of length 0.12 m carries 3.0 A at right angles to B = 0.50 T. Force magnitude is",
        options: [
          { id: "A", text: "0.06 N" },
          { id: "B", text: "0.18 N" },
          { id: "C", text: "1.80 N" },
          { id: "D", text: "0.72 N" },
        ],
        correctOptionId: "B",
        explanation: "F = BIL = 0.50 x 3.0 x 0.12 = 0.18 N.",
        distractorRationale: {
          B: "Correct substitution with right-angle condition.",
          C: "Decimal-place error from multiplying by 10.",
          D: "Would correspond to using L = 0.48 m incorrectly.",
        },
        tags: ["numerical", "force-calculation", "right-angles"],
      },
      {
        id: "t20-2-d4",
        noteId: "t20-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State the equation for force on a straight current-carrying conductor in a uniform magnetic field and define symbols.",
        modelAnswerPoints: [
          "F = BIL sin(theta).",
          "B is flux density, I current, L conductor length in field.",
          "theta is angle between conductor/current direction and magnetic field.",
        ],
        workedSolution: [
          "Include sine angle factor for full generality.",
          "If right angle is given, simplify to F = BIL.",
        ],
        commonMistake: "Omitting the sine term in non-right-angle situations.",
        tags: ["formula", "definitions", "core-knowledge"],
      },
      {
        id: "t20-2-d5",
        noteId: "t20-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A 0.080 m wire carries 4.0 A in a 0.30 T field at 30 degrees to the field. Calculate the force.",
        modelAnswerPoints: [
          "Use F = BIL sin(theta).",
          "F = 0.30 x 4.0 x 0.080 x sin(30 degrees).",
          "sin(30 degrees) = 0.50.",
          "F = 4.8 x 10^-2 N.",
        ],
        workedSolution: [
          "Angle factor reduces force below the right-angle case.",
          "Keep calculator in degree mode for trig function.",
        ],
        commonMistake: "Using cos(30) instead of sin(30).",
        tags: ["trigonometric-factor", "calculation", "angles"],
      },
      {
        id: "t20-2-d6",
        noteId: "t20-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Describe how reversing the current direction affects the force direction on a conductor in a fixed magnetic field.",
        modelAnswerPoints: [
          "Force direction reverses when current reverses.",
          "Magnitude is unchanged if current magnitude is unchanged.",
          "This follows from vector cross-product relation (or left-hand rule).",
          "Motor effect can therefore be controlled by current polarity.",
        ],
        workedSolution: [
          "Apply Fleming's left-hand rule before and after reversal.",
          "Only one vector reverses, so force reverses.",
        ],
        commonMistake: "Claiming both force and field reverse when only current is reversed.",
        tags: ["direction", "current-reversal", "motor-effect"],
      },
      {
        id: "t20-2-d7",
        noteId: "t20-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A horizontal wire in a magnetic field experiences upward force of 0.36 N. The field is 0.60 T and effective wire length is 0.20 m. Determine the current.",
        modelAnswerPoints: [
          "Assume wire is perpendicular to field so F = BIL.",
          "I = F/(BL).",
          "I = 0.36 / (0.60 x 0.20).",
          "I = 3.0 A.",
        ],
        workedSolution: [
          "Rearrange first to avoid substitution mistakes.",
          "Use SI units throughout to keep answer in amperes.",
        ],
        commonMistake: "Dividing by B only and forgetting length factor.",
        tags: ["inverse-calculation", "current", "force-on-conductor"],
      },
      {
        id: "t20-2-d8",
        noteId: "t20-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Two parallel wire sections of equal length carry equal currents in opposite directions in the same uniform field. Explain the force directions and the resulting turning effect on a rectangular coil.",
        modelAnswerPoints: [
          "For opposite current directions, magnetic forces on opposite sides are opposite.",
          "In a coil, one side is pushed up while the other is pushed down (or vice versa).",
          "These equal opposite forces form a couple.",
          "A couple produces turning effect (torque) with little net translation.",
          "This is the basis of motor action on a current loop.",
        ],
        workedSolution: [
          "Apply left-hand rule separately to each side.",
          "Then combine forces into torque concept rather than net-force concept.",
        ],
        commonMistake: "Adding opposite forces as zero and concluding no effect at all.",
        tags: ["coil", "torque", "motor-principle"],
      },
      {
        id: "t20-2-d9",
        noteId: "t20-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A coil has 50 turns, each side length in field 0.040 m, carrying 1.5 A in B = 0.25 T. Calculate force on one side and total couple force pair (two active sides).",
        modelAnswerPoints: [
          "Force on one conductor side for one turn: F1 = BIL = 0.25 x 1.5 x 0.040 = 0.015 N.",
          "For 50 turns, force per side = 50 x 0.015 = 0.75 N.",
          "Opposite side has equal magnitude opposite direction.",
          "Couple consists of two 0.75 N forces separated by coil width.",
          "Total net force is approximately zero while torque is non-zero.",
        ],
        workedSolution: [
          "Multiply by number of turns only after finding single-turn force.",
          "Distinguish force magnitude from torque, which also needs separation distance.",
        ],
        commonMistake: "Doubling force for both sides and calling it net force.",
        tags: ["multi-turn-coil", "forces", "motor-effect"],
      },
      {
        id: "t20-2-d10",
        noteId: "t20-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "Explain why split-ring commutators are needed in simple d.c. motors and relate this to force direction on each half-turn.",
        modelAnswerPoints: [
          "Without commutation, current direction in coil would remain fixed in coil frame.",
          "After half-turn, torque would reverse and oppose continued rotation.",
          "Split-ring commutator reverses coil current every half-turn.",
          "This keeps turning effect in same rotational sense.",
          "So motor can continue rotating in one direction.",
        ],
        workedSolution: [
          "Tie explanation to force reversal conditions from left-hand rule.",
          "Emphasize timing: reversal must occur each half-turn.",
        ],
        commonMistake: "Saying commutator increases magnetic field strength directly.",
        tags: ["dc-motor", "commutator", "extended-response"],
      },
    ],
    flashcards: [
      {
        id: "t20-2-f1",
        noteId: "t20-2",
        difficulty: 1,
        front: "State the motor-effect force equation for a straight conductor.",
        back: "F = BIL sin(theta).",
        examPhrasing: "At 90 degrees, this reduces to F = BIL.",
        tags: ["equation", "motor-effect"],
      },
      {
        id: "t20-2-f2",
        noteId: "t20-2",
        difficulty: 1,
        front: "Which rule predicts direction of force on a current in a magnetic field?",
        back: "Fleming's left-hand rule.",
        examPhrasing: "First finger = field, second = current, thumb = force.",
        tags: ["direction", "rules"],
      },
      {
        id: "t20-2-f3",
        noteId: "t20-2",
        difficulty: 2,
        front: "How does force vary with current for fixed B, L, and angle?",
        back: "Force is directly proportional to current I.",
        examPhrasing: "From F = BIL sin(theta), increase I and force rises linearly.",
        tags: ["proportionality", "current"],
      },
      {
        id: "t20-2-f4",
        noteId: "t20-2",
        difficulty: 2,
        front: "When is force on a current-carrying conductor zero?",
        back: "When current direction is parallel or anti-parallel to the field (theta = 0 or 180 degrees).",
        examPhrasing: "Because sin(theta) = 0.",
        tags: ["angles", "zero-force"],
      },
      {
        id: "t20-2-f5",
        noteId: "t20-2",
        difficulty: 3,
        front: "What happens to force direction if current is reversed?",
        back: "Force direction reverses.",
        examPhrasing: "Reverse one vector and the motor-force direction flips.",
        tags: ["current-reversal", "direction"],
      },
      {
        id: "t20-2-f6",
        noteId: "t20-2",
        difficulty: 3,
        front: "Why do opposite sides of a rectangular coil form a couple in a magnetic field?",
        back: "Equal and opposite forces act on sides carrying current in opposite directions, creating torque.",
        examPhrasing: "Net force is small, but turning moment is non-zero.",
        tags: ["coil", "torque"],
      },
      {
        id: "t20-2-f7",
        noteId: "t20-2",
        difficulty: 4,
        front: "What is the practical role of a split-ring commutator?",
        back: "It reverses coil current every half-turn to keep torque in one rotational direction.",
        examPhrasing: "Commutation prevents torque reversal each half-cycle.",
        tags: ["dc-motor", "commutator"],
      },
      {
        id: "t20-2-f8",
        noteId: "t20-2",
        difficulty: 4,
        front: "Which variables increase motor force on one active side?",
        back: "Larger B, larger I, longer active length L, and angle closer to 90 degrees.",
        examPhrasing: "Force scales with BIL sin(theta).",
        tags: ["design-factors", "equation-use"],
      },
      {
        id: "t20-2-f9",
        noteId: "t20-2",
        difficulty: 5,
        front: "Why is it wrong to add coil-side forces as a net translational force in motor analysis?",
        back: "The forces are opposite and mainly form a couple, so torque matters more than net force.",
        examPhrasing: "Motor action relies on turning effect, not linear acceleration.",
        confusionPair: "Net force vs torque",
        tags: ["exam-technique", "torque-analysis"],
      },
      {
        id: "t20-2-f10",
        noteId: "t20-2",
        difficulty: 5,
        front: "What is the most common trig error in force-on-conductor questions?",
        back: "Using cosine or wrong reference angle instead of sin(theta) where theta is between current and field.",
        examPhrasing: "Define theta first, then evaluate sin(theta).",
        tags: ["pitfalls", "trigonometry"],
      },
    ],
  },
  "t20-3": {
    noteId: "t20-3",
    drills: [
      {
        id: "t20-3-d1",
        noteId: "t20-3",
        kind: "mcq",
        difficulty: 1,
        stem: "A charged particle moves in a magnetic field. Magnetic force is always",
        options: [
          { id: "A", text: "parallel to the particle velocity" },
          { id: "B", text: "perpendicular to both velocity and magnetic field" },
          { id: "C", text: "in the same direction as magnetic field" },
          { id: "D", text: "opposite to electric force only" },
        ],
        correctOptionId: "B",
        explanation: "The magnetic part of Lorentz force is perpendicular to both v and B.",
        distractorRationale: {
          B: "Correct geometry of magnetic force direction.",
          C: "Force along B would not produce observed circular deflection.",
          D: "Magnetic and electric forces are distinct and not generally opposite.",
        },
        tags: ["lorentz-force", "direction", "core-concept"],
      },
      {
        id: "t20-3-d2",
        noteId: "t20-3",
        kind: "mcq",
        difficulty: 2,
        stem: "For a positive charge q moving at speed v at right angles to B, magnetic force magnitude is",
        options: [
          { id: "A", text: "F = q/Bv" },
          { id: "B", text: "F = qvB" },
          { id: "C", text: "F = qv/B" },
          { id: "D", text: "F = B/(qv)" },
        ],
        correctOptionId: "B",
        explanation: "At 90 degrees, F = Bqv sin(theta) gives F = Bqv.",
        distractorRationale: {
          B: "Correct magnetic-force expression at right angles.",
          C: "Division by B is dimensionally incorrect here.",
          D: "Inverse form is physically and dimensionally wrong.",
        },
        tags: ["equations", "moving-charge", "right-angle"],
      },
      {
        id: "t20-3-d3",
        noteId: "t20-3",
        kind: "mcq",
        difficulty: 3,
        stem: "An electron and a proton enter the same uniform magnetic field with equal speed and direction. Which statement is true?",
        options: [
          { id: "A", text: "Both curve in the same direction with same radius." },
          { id: "B", text: "They curve in opposite directions; proton has larger radius." },
          { id: "C", text: "Both travel straight because charges cancel." },
          { id: "D", text: "Electron has larger radius because it is lighter." },
        ],
        correctOptionId: "B",
        explanation: "Opposite charge signs reverse force direction; radius r = mv/(qB) is larger for proton due to greater mass magnitude ratio.",
        distractorRationale: {
          B: "Correct sign and radius-mass reasoning.",
          C: "Particles do not interact to cancel forces in this setup.",
          D: "Lower mass gives smaller radius at same |q|, v, and B.",
        },
        tags: ["particle-comparison", "radius", "sign-of-charge"],
      },
      {
        id: "t20-3-d4",
        noteId: "t20-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State the equation for magnetic force on a moving charge and define all symbols.",
        modelAnswerPoints: [
          "F = Bqv sin(theta).",
          "B is flux density, q charge, v speed.",
          "theta is angle between velocity and magnetic field.",
        ],
        workedSolution: [
          "Use magnitude form first, then mention right-angle simplification if relevant.",
          "Sign of charge affects force direction, not magnitude expression.",
        ],
        commonMistake: "Using I instead of q in moving-charge equation.",
        tags: ["formula", "definitions", "moving-charge"],
      },
      {
        id: "t20-3-d5",
        noteId: "t20-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A proton (q = 1.60 x 10^-19 C) moves at 3.0 x 10^6 m s^-1 perpendicular to B = 0.40 T. Calculate magnetic force magnitude.",
        modelAnswerPoints: [
          "Use F = Bqv for 90 degrees.",
          "F = 0.40 x 1.60 x 10^-19 x 3.0 x 10^6.",
          "F = 1.92 x 10^-13 N.",
          "Quote to suitable significant figures.",
        ],
        workedSolution: [
          "Collect powers of ten separately to reduce calculator slips.",
          "Answer unit is newton because this is a force.",
        ],
        commonMistake: "Using charge value without power of ten.",
        tags: ["numerical", "proton", "force"],
      },
      {
        id: "t20-3-d6",
        noteId: "t20-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain why a charged particle moving parallel to a magnetic field is not deflected.",
        modelAnswerPoints: [
          "Magnetic force has factor sin(theta).",
          "For parallel motion, theta = 0 degrees.",
          "So sin(theta) = 0 and magnetic force is zero.",
          "Without sideways force, path remains straight.",
        ],
        workedSolution: [
          "Use equation and geometry together in explanation.",
          "Mention that field can still exist even though force is zero.",
        ],
        commonMistake: "Saying there is no field when no force is observed.",
        tags: ["angle-dependence", "conceptual", "deflection"],
      },
      {
        id: "t20-3-d7",
        noteId: "t20-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "An alpha particle (q = +3.2 x 10^-19 C, m = 6.6 x 10^-27 kg) enters a 0.50 T field perpendicularly at 2.0 x 10^6 m s^-1. Calculate radius of path.",
        modelAnswerPoints: [
          "For circular motion, magnetic force provides centripetal force: qvB = mv^2/r.",
          "Rearrange to r = mv/(qB).",
          "r = (6.6 x 10^-27 x 2.0 x 10^6)/(3.2 x 10^-19 x 0.50).",
          "r = 8.25 x 10^-2 m.",
        ],
        workedSolution: [
          "Use magnitude of charge in radius formula.",
          "Keep scientific notation organized for both numerator and denominator.",
        ],
        commonMistake: "Using v^2 in numerator after rearranging incorrectly.",
        tags: ["circular-motion", "radius", "alpha-particle"],
      },
      {
        id: "t20-3-d8",
        noteId: "t20-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A particle enters a uniform magnetic field at angle to field lines and follows a helical path. Explain why this occurs.",
        modelAnswerPoints: [
          "Velocity has components parallel and perpendicular to field.",
          "Perpendicular component experiences magnetic force and causes circular motion.",
          "Parallel component experiences no magnetic force and remains constant.",
          "Combined motions produce a helix.",
          "Pitch depends on parallel speed and circular period.",
        ],
        workedSolution: [
          "Resolve velocity into components first.",
          "Treat each component response separately, then superpose motions.",
        ],
        commonMistake: "Assuming entire speed is unchanged directionally in a straight line.",
        tags: ["helical-motion", "velocity-components", "explanation"],
      },
      {
        id: "t20-3-d9",
        noteId: "t20-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "An electron enters a 0.20 T field at right angles with speed 4.0 x 10^7 m s^-1. Calculate (a) radius and (b) time period of circular motion. Use e = 1.60 x 10^-19 C, m_e = 9.11 x 10^-31 kg.",
        modelAnswerPoints: [
          "Radius: r = mv/(qB) = (9.11 x 10^-31 x 4.0 x 10^7)/(1.60 x 10^-19 x 0.20) = 1.14 x 10^-3 m.",
          "Period relation: T = 2pi r / v or T = 2pi m/(qB).",
          "Using T = 2pi m/(qB): T = 2pi x 9.11 x 10^-31 / (1.60 x 10^-19 x 0.20).",
          "T = 1.79 x 10^-10 s.",
          "Direction is opposite to that for a positive charge.",
        ],
        workedSolution: [
          "Use magnitude of electron charge in calculations.",
          "Period independent of speed in non-relativistic uniform-field model.",
        ],
        commonMistake: "Using negative sign of charge to produce negative radius or period.",
        tags: ["electron", "radius-and-period", "high-value"],
      },
      {
        id: "t20-3-d10",
        noteId: "t20-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "Describe and compare magnetic and electric deflection of charged particles in terms of force direction, speed change, and path shape.",
        modelAnswerPoints: [
          "Electric force acts along/against field direction depending on charge sign.",
          "Magnetic force acts perpendicular to both velocity and magnetic field.",
          "Electric field can change speed (does work), magnetic field alone does not.",
          "Electric deflection often gives parabolic or accelerated trajectories.",
          "Magnetic deflection gives circular/helical motion for appropriate velocity components.",
        ],
        workedSolution: [
          "Structure answer by category: direction, energy/work, trajectory.",
          "Use clear contrasts rather than isolated facts.",
        ],
        commonMistake: "Claiming both fields always conserve particle kinetic energy.",
        tags: ["comparison", "electric-vs-magnetic", "extended-response"],
      },
    ],
    flashcards: [
      {
        id: "t20-3-f1",
        noteId: "t20-3",
        difficulty: 1,
        front: "State the magnetic-force equation for a moving charge.",
        back: "F = Bqv sin(theta).",
        examPhrasing: "At right angles, F = Bqv.",
        tags: ["equation", "moving-charge"],
      },
      {
        id: "t20-3-f2",
        noteId: "t20-3",
        difficulty: 1,
        front: "What is the force direction relative to velocity and magnetic field?",
        back: "Perpendicular to both velocity and field.",
        examPhrasing: "Use cross-product or hand-rule direction.",
        tags: ["direction", "lorentz-force"],
      },
      {
        id: "t20-3-f3",
        noteId: "t20-3",
        difficulty: 2,
        front: "When is magnetic force on a moving charge zero?",
        back: "When velocity is parallel/anti-parallel to B, or when particle is stationary.",
        examPhrasing: "Because sin(theta) is zero when theta = 0 or 180 degrees.",
        tags: ["angle-effects", "zero-force"],
      },
      {
        id: "t20-3-f4",
        noteId: "t20-3",
        difficulty: 2,
        front: "Write the radius formula for circular motion of a charged particle in uniform B.",
        back: "r = mv/(qB) using charge magnitude.",
        examPhrasing: "Derived from qvB = mv^2/r.",
        tags: ["radius", "circular-motion"],
      },
      {
        id: "t20-3-f5",
        noteId: "t20-3",
        difficulty: 3,
        front: "How does radius depend on particle speed at fixed q and B?",
        back: "Radius is directly proportional to speed.",
        examPhrasing: "Higher speed gives larger circular path radius.",
        tags: ["proportionality", "radius"],
      },
      {
        id: "t20-3-f6",
        noteId: "t20-3",
        difficulty: 3,
        front: "How does charge sign affect magnetic deflection?",
        back: "It reverses deflection direction.",
        examPhrasing: "Magnitude is unaffected if |q| is unchanged.",
        tags: ["charge-sign", "deflection"],
      },
      {
        id: "t20-3-f7",
        noteId: "t20-3",
        difficulty: 4,
        front: "Why can magnetic force change direction of motion without changing speed?",
        back: "Force is perpendicular to motion, so no work is done.",
        examPhrasing: "Kinetic energy remains constant in pure magnetic deflection.",
        tags: ["work-done", "energy"],
      },
      {
        id: "t20-3-f8",
        noteId: "t20-3",
        difficulty: 4,
        front: "What path is produced when velocity has both parallel and perpendicular components to B?",
        back: "A helical path.",
        examPhrasing: "Circular transverse motion plus constant forward motion.",
        tags: ["helical-motion", "components"],
      },
      {
        id: "t20-3-f9",
        noteId: "t20-3",
        difficulty: 5,
        front: "How does magnetic deflection differ from electric deflection in energy change?",
        back: "Magnetic deflection alone does not change kinetic energy, electric deflection can.",
        examPhrasing: "Electric fields can do work; magnetic fields (alone) cannot.",
        confusionPair: "Deflection vs acceleration-work",
        tags: ["comparison", "energy-principles"],
      },
      {
        id: "t20-3-f10",
        noteId: "t20-3",
        difficulty: 5,
        front: "What is a high-frequency error in charged-particle magnetic calculations?",
        back: "Dropping powers of ten or using signed charge in magnitude equations for r or T.",
        examPhrasing: "Use charge magnitude for scalar radius/period results.",
        tags: ["exam-technique", "numerical-quality"],
      },
    ],
  },
  "t20-4": {
    noteId: "t20-4",
    drills: [
      {
        id: "t20-4-d1",
        noteId: "t20-4",
        kind: "mcq",
        difficulty: 1,
        stem: "Magnetic field direction around a long straight wire is found using",
        options: [
          { id: "A", text: "Fleming's left-hand rule" },
          { id: "B", text: "Right-hand grip rule" },
          { id: "C", text: "Lenz's law" },
          { id: "D", text: "Kirchhoff's first law" },
        ],
        correctOptionId: "B",
        explanation: "Thumb indicates current direction, curled fingers indicate magnetic field direction.",
        distractorRationale: {
          B: "Correct rule for straight-wire field direction.",
          C: "Lenz's law is for induced current direction.",
          D: "Kirchhoff's laws are circuit current/voltage laws.",
        },
        tags: ["right-hand-rule", "straight-wire", "direction"],
      },
      {
        id: "t20-4-d2",
        noteId: "t20-4",
        kind: "mcq",
        difficulty: 2,
        stem: "For a long straight wire, how does magnetic flux density B vary with distance r from the wire?",
        options: [
          { id: "A", text: "B proportional r" },
          { id: "B", text: "B proportional 1/r" },
          { id: "C", text: "B proportional r^2" },
          { id: "D", text: "B independent of r" },
        ],
        correctOptionId: "B",
        explanation: "Field strength around a long straight wire decreases inversely with radial distance.",
        distractorRationale: {
          B: "Correct inverse-distance dependence.",
          C: "Quadratic increase is opposite to observed decay.",
          D: "Only an ideal solenoid center approximates uniform B over region.",
        },
        tags: ["straight-wire", "variation", "proportionality"],
      },
      {
        id: "t20-4-d3",
        noteId: "t20-4",
        kind: "mcq",
        difficulty: 3,
        stem: "What is the field pattern inside an ideal long solenoid carrying steady current?",
        options: [
          { id: "A", text: "Weak random curved lines" },
          { id: "B", text: "Uniform parallel lines along solenoid axis" },
          { id: "C", text: "Concentric circles around each turn with no resultant field" },
          { id: "D", text: "Radial lines away from center" },
        ],
        correctOptionId: "B",
        explanation: "Inside a long solenoid, fields from turns combine to form near-uniform axial field.",
        distractorRationale: {
          B: "Correct idealized internal field description.",
          C: "Resultant does not cancel; superposition reinforces axial component.",
          D: "Radial pattern is not solenoid internal behavior.",
        },
        tags: ["solenoid", "field-pattern", "superposition"],
      },
      {
        id: "t20-4-d4",
        noteId: "t20-4",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Describe the magnetic field around a long straight current-carrying wire, including direction and relative strength.",
        modelAnswerPoints: [
          "Field lines are concentric circles centered on the wire.",
          "Direction is given by right-hand grip rule.",
          "Field strength decreases with distance from wire.",
        ],
        workedSolution: [
          "Use both geometric pattern and directional rule for complete answer.",
          "Mention inverse-distance trend for strength mark.",
        ],
        commonMistake: "Drawing straight parallel lines around the wire.",
        tags: ["straight-wire", "description", "field-lines"],
      },
      {
        id: "t20-4-d5",
        noteId: "t20-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Two long parallel wires carry currents in the same direction. Explain the force between the wires.",
        modelAnswerPoints: [
          "Each wire produces magnetic field at location of the other.",
          "Current in each wire experiences magnetic force due to the other's field.",
          "For same current direction, forces are attractive.",
          "Magnitude depends on current values and separation.",
        ],
        workedSolution: [
          "Apply right-hand rule to determine field direction from one wire.",
          "Then apply force rule for current in the second wire.",
        ],
        commonMistake: "Assuming like currents repel by analogy with electric charges.",
        tags: ["parallel-wires", "interaction", "forces"],
      },
      {
        id: "t20-4-d6",
        noteId: "t20-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain why a solenoid behaves like a bar magnet.",
        modelAnswerPoints: [
          "Current loops in solenoid create magnetic dipole contributions.",
          "Fields superpose to produce distinct north and south ends.",
          "Inside field is approximately uniform and strong.",
          "Outside pattern resembles bar-magnet field lines.",
        ],
        workedSolution: [
          "Describe superposition from many turns to justify macroscopic magnet behavior.",
          "Identify end polarity using current direction rules.",
        ],
        commonMistake: "Saying solenoid produces electric field only.",
        tags: ["solenoid", "bar-magnet-analogy", "superposition"],
      },
      {
        id: "t20-4-d7",
        noteId: "t20-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A solenoid has 1200 turns m^-1 and carries 2.5 A. Magnetic flux density at center is 3.8 x 10^-3 T. Calculate the permeability mu using B = mu nI.",
        modelAnswerPoints: [
          "Rearrange: mu = B/(nI).",
          "mu = (3.8 x 10^-3)/(1200 x 2.5).",
          "mu = 1.27 x 10^-6 H m^-1 (or N A^-2).",
          "Value is close to permeability of free space.",
        ],
        workedSolution: [
          "Use consistent SI units: n in m^-1, I in A, B in T.",
          "State appropriate unit for permeability.",
        ],
        commonMistake: "Using n as total turns instead of turns per metre.",
        tags: ["solenoid-equation", "numerical", "permeability"],
      },
      {
        id: "t20-4-d8",
        noteId: "t20-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Compare the magnetic field at the center of (a) a single circular loop and (b) a multi-turn coil with same current and radius.",
        modelAnswerPoints: [
          "Both produce field perpendicular to plane at center.",
          "Field direction from right-hand rule for current around loop.",
          "Multi-turn coil gives larger B because contributions from turns add.",
          "Approximately B scales with number of turns N for same geometry.",
          "So multi-turn arrangement is preferred for stronger fields.",
        ],
        workedSolution: [
          "Treat single-loop field as base contribution.",
          "Then use superposition argument for N-turn enhancement.",
        ],
        commonMistake: "Assuming extra turns split current and weaken field automatically.",
        tags: ["coil", "superposition", "field-strength"],
      },
      {
        id: "t20-4-d9",
        noteId: "t20-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A Hall probe is moved radially away from a long straight wire carrying constant current. Predict and explain the graph of B against r.",
        modelAnswerPoints: [
          "B decreases as r increases.",
          "Expected relationship is inverse: B proportional 1/r.",
          "Graph is a decreasing curve (rectangular hyperbola type).",
          "Doubling r halves B, all else fixed.",
          "Scatter may occur from probe alignment and external fields.",
        ],
        workedSolution: [
          "State ideal law first, then practical deviations.",
          "Use ratio statement to interpret data points quickly.",
        ],
        commonMistake: "Predicting linear fall to zero with distance.",
        tags: ["experimental-interpretation", "straight-wire", "graphs"],
      },
      {
        id: "t20-4-d10",
        noteId: "t20-4",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "Discuss how changing current, number of turns per unit length, and core material affects solenoid magnetic field strength, with one use-case implication.",
        modelAnswerPoints: [
          "From B = mu nI, increasing I increases B linearly.",
          "Increasing turns per metre n also increases B linearly.",
          "Using ferromagnetic core increases effective permeability mu greatly.",
          "Combined changes can produce much stronger electromagnets.",
          "This enables stronger lifting force or actuator torque in devices.",
        ],
        workedSolution: [
          "Organize response around each parameter in the equation.",
          "Then connect to practical electromagnet performance outcome.",
        ],
        commonMistake: "Claiming number of turns affects field only outside the solenoid.",
        tags: ["electromagnets", "parameter-effects", "applications"],
      },
    ],
    flashcards: [
      {
        id: "t20-4-f1",
        noteId: "t20-4",
        difficulty: 1,
        front: "Which rule gives field direction around a straight wire?",
        back: "Right-hand grip rule.",
        examPhrasing: "Thumb along current, curled fingers show field direction.",
        tags: ["rules", "straight-wire"],
      },
      {
        id: "t20-4-f2",
        noteId: "t20-4",
        difficulty: 1,
        front: "How are field lines arranged around a long straight wire?",
        back: "As concentric circles centered on the wire.",
        examPhrasing: "Spacing increases with distance as field weakens.",
        tags: ["patterns", "wire-field"],
      },
      {
        id: "t20-4-f3",
        noteId: "t20-4",
        difficulty: 2,
        front: "How does B vary with distance from a long straight wire?",
        back: "B is inversely proportional to distance r.",
        examPhrasing: "Doubling r halves B for fixed current.",
        tags: ["proportionality", "distance-effect"],
      },
      {
        id: "t20-4-f4",
        noteId: "t20-4",
        difficulty: 2,
        front: "What is the force interaction for two parallel currents in same direction?",
        back: "The wires attract.",
        examPhrasing: "Opposite current directions produce repulsion.",
        tags: ["parallel-wires", "force-direction"],
      },
      {
        id: "t20-4-f5",
        noteId: "t20-4",
        difficulty: 3,
        front: "Why is field inside an ideal long solenoid nearly uniform?",
        back: "Field contributions from many turns add along axis and edge effects are reduced in the central region.",
        examPhrasing: "Represented by parallel equally spaced internal lines.",
        tags: ["solenoid", "uniform-field"],
      },
      {
        id: "t20-4-f6",
        noteId: "t20-4",
        difficulty: 3,
        front: "State the solenoid relation linking B, mu, n, and I.",
        back: "B = mu n I.",
        examPhrasing: "n is turns per metre, not total turns.",
        tags: ["equation", "solenoid"],
      },
      {
        id: "t20-4-f7",
        noteId: "t20-4",
        difficulty: 4,
        front: "How does increasing current affect solenoid field strength?",
        back: "B increases linearly with current.",
        examPhrasing: "If I doubles, B doubles when mu and n are constant.",
        tags: ["parameter-effects", "current"],
      },
      {
        id: "t20-4-f8",
        noteId: "t20-4",
        difficulty: 4,
        front: "How does a ferromagnetic core change solenoid field?",
        back: "It increases effective permeability and strongly increases B.",
        examPhrasing: "Core material changes mu term in B = mu nI.",
        tags: ["core-material", "electromagnets"],
      },
      {
        id: "t20-4-f9",
        noteId: "t20-4",
        difficulty: 5,
        front: "Why do same-direction currents attract at wire level?",
        back: "Each wire lies in the magnetic field of the other and experiences force toward the other wire.",
        examPhrasing: "Current-field interaction explains attraction without electrostatic analogy.",
        confusionPair: "Current attraction vs charge repulsion analogy",
        tags: ["parallel-wires", "conceptual"],
      },
      {
        id: "t20-4-f10",
        noteId: "t20-4",
        difficulty: 5,
        front: "Common high-mark error in solenoid calculations?",
        back: "Using total turns N directly where turns per metre n is required.",
        examPhrasing: "Convert n correctly before substitution.",
        tags: ["exam-technique", "solenoid-calculation"],
      },
    ],
  },
  "t20-5": {
    noteId: "t20-5",
    drills: [
      {
        id: "t20-5-d1",
        noteId: "t20-5",
        kind: "mcq",
        difficulty: 1,
        stem: "An emf is induced in a circuit when there is a change in",
        options: [
          { id: "A", text: "resistance only" },
          { id: "B", text: "magnetic flux linkage through the circuit" },
          { id: "C", text: "wire length only" },
          { id: "D", text: "mass of the conductor" },
        ],
        correctOptionId: "B",
        explanation: "Faraday's law states induced emf is associated with rate of change of flux linkage.",
        distractorRationale: {
          B: "This is the direct condition for electromagnetic induction.",
          C: "Length alone does not induce emf without changing flux conditions.",
          D: "Conductor mass is irrelevant to induction law.",
        },
        tags: ["faraday-law", "induced-emf", "core-definition"],
      },
      {
        id: "t20-5-d2",
        noteId: "t20-5",
        kind: "mcq",
        difficulty: 2,
        stem: "Which law gives the direction of induced current?",
        options: [
          { id: "A", text: "Fleming's left-hand rule" },
          { id: "B", text: "Lenz's law" },
          { id: "C", text: "Right-hand grip rule" },
          { id: "D", text: "Newton's third law" },
        ],
        correctOptionId: "B",
        explanation: "Lenz's law states induced current direction opposes the change causing it.",
        distractorRationale: {
          B: "Correct directional principle for induction.",
          C: "Right-hand grip rule gives field around known current, not induced-current direction.",
          D: "Newton's laws do not set induced-current direction.",
        },
        tags: ["lenz-law", "direction", "induction"],
      },
      {
        id: "t20-5-d3",
        noteId: "t20-5",
        kind: "mcq",
        difficulty: 3,
        stem: "A coil has 200 turns. Flux through each turn changes uniformly from 3.0 x 10^-4 Wb to zero in 0.020 s. Magnitude of induced emf is",
        options: [
          { id: "A", text: "0.30 V" },
          { id: "B", text: "3.0 V" },
          { id: "C", text: "30 V" },
          { id: "D", text: "300 V" },
        ],
        correctOptionId: "B",
        explanation: "E = N Delta(phi)/Delta(t) = 200 x (3.0 x 10^-4)/0.020 = 3.0 V.",
        distractorRationale: {
          B: "Correct use of flux-linkage rate formula.",
          C: "Factor-of-10 error from decimal misplacement.",
          D: "Factor-of-100 error from compounding mistakes.",
        },
        tags: ["faraday-law", "calculation", "turns"],
      },
      {
        id: "t20-5-d4",
        noteId: "t20-5",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State Faraday's law of electromagnetic induction.",
        modelAnswerPoints: [
          "Induced emf is proportional to rate of change of magnetic flux linkage.",
          "For N turns, E = -N d(phi)/dt in sign form.",
          "Negative sign represents Lenz's law direction convention.",
        ],
        workedSolution: [
          "Mention flux linkage rather than flux alone for coils with multiple turns.",
          "Sign explanation secures conceptual accuracy.",
        ],
        commonMistake: "Writing induced emf proportional to flux itself rather than its rate of change.",
        tags: ["faraday-law", "statement", "core-knowledge"],
      },
      {
        id: "t20-5-d5",
        noteId: "t20-5",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A straight conductor of length 0.15 m moves at 6.0 m s^-1 perpendicular to B = 0.40 T. Calculate induced emf between its ends.",
        modelAnswerPoints: [
          "Use motional emf relation E = B l v for perpendicular motion.",
          "E = 0.40 x 0.15 x 6.0.",
          "E = 0.36 V.",
          "Unit is volt.",
        ],
        workedSolution: [
          "Ensure velocity is perpendicular to both conductor and field in this simplified formula.",
          "All values are already SI, so direct substitution is valid.",
        ],
        commonMistake: "Using l in cm, giving emf 100 times too small.",
        tags: ["motional-emf", "numerical", "conductors"],
      },
      {
        id: "t20-5-d6",
        noteId: "t20-5",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain Lenz's law in terms of energy conservation.",
        modelAnswerPoints: [
          "Induced current creates magnetic effects opposing the original flux change.",
          "Opposition means external work is needed to keep changing flux.",
          "This prevents spontaneous energy gain from induction process.",
          "So Lenz's law is consistent with conservation of energy.",
        ],
        workedSolution: [
          "State 'opposes change' clearly, then connect to required mechanical/electrical work.",
          "Avoid framing opposition as stopping all change; it resists it.",
        ],
        commonMistake: "Saying induced current always opposes magnetic field itself, not the change in flux.",
        tags: ["lenz-law", "energy-conservation", "explanation"],
      },
      {
        id: "t20-5-d7",
        noteId: "t20-5",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A 500-turn coil experiences uniform flux-per-turn change from 8.0 x 10^-5 Wb to 2.0 x 10^-5 Wb in 0.010 s. Calculate induced emf magnitude.",
        modelAnswerPoints: [
          "Delta(phi) per turn = 6.0 x 10^-5 Wb.",
          "Flux linkage change = N Delta(phi) = 500 x 6.0 x 10^-5 = 3.0 x 10^-2 Wb-turn.",
          "E = Delta(Nphi)/Delta(t) = 3.0 x 10^-2 / 0.010.",
          "E = 3.0 V.",
        ],
        workedSolution: [
          "Compute change first, then multiply by turns to avoid sign/scale confusion.",
          "Magnitude requested, so ignore sign from direction convention.",
        ],
        commonMistake: "Using initial flux only instead of flux change.",
        tags: ["flux-linkage", "coil", "calculation"],
      },
      {
        id: "t20-5-d8",
        noteId: "t20-5",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A metal rod slides on conducting rails in uniform magnetic field, forming a closed circuit with resistor. Explain why the rod experiences magnetic drag when moving.",
        modelAnswerPoints: [
          "Rod motion changes magnetic flux through the circuit area.",
          "Induced emf drives current around loop.",
          "Current-carrying rod in magnetic field experiences force (motor effect).",
          "By Lenz's law, this force opposes the rod's motion.",
          "External work is required to maintain constant speed.",
        ],
        workedSolution: [
          "Link induction and motor effect as a coupled process.",
          "Use opposition-to-change idea to determine drag direction.",
        ],
        commonMistake: "Attributing drag only to mechanical friction with rails.",
        tags: ["induction-systems", "energy-transfer", "lenz-law"],
      },
      {
        id: "t20-5-d9",
        noteId: "t20-5",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A generator coil rotates in uniform magnetic field. Describe why output emf is alternating and why amplitude increases with angular speed.",
        modelAnswerPoints: [
          "Flux linkage through coil changes cyclically as coil rotates.",
          "Rate of change of flux linkage changes sign every half-turn.",
          "So induced emf reverses direction periodically (a.c.).",
          "Higher angular speed increases rate of flux change.",
          "Therefore peak emf magnitude increases with rotation speed.",
        ],
        workedSolution: [
          "Use Faraday law qualitatively: emf linked to slope of flux-linkage-time graph.",
          "Sign reversal explains alternating nature directly.",
        ],
        commonMistake: "Saying emf alternates because current source polarity is switched externally.",
        tags: ["ac-generator", "qualitative", "faraday-law"],
      },
      {
        id: "t20-5-d10",
        noteId: "t20-5",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A search coil (N = 100) linked to a magnet has flux per turn changing from +4.0 x 10^-5 Wb to -2.0 x 10^-5 Wb in 5.0 ms.\n(a) Calculate average induced emf magnitude.\n(b) Explain the sign change physically.",
        modelAnswerPoints: [
          "Total flux change per turn = 6.0 x 10^-5 Wb (crosses zero and reverses).",
          "Flux linkage change = N Delta(phi) = 100 x 6.0 x 10^-5 = 6.0 x 10^-3 Wb-turn.",
          "Delta(t) = 5.0 ms = 5.0 x 10^-3 s.",
          "Average emf magnitude = 6.0 x 10^-3 / 5.0 x 10^-3 = 1.2 V.",
          "Sign change indicates reversal of flux direction relative to chosen area normal.",
        ],
        workedSolution: [
          "Handle sign carefully: crossing from positive to negative increases total change magnitude.",
          "Convert milliseconds to seconds before final division.",
        ],
        commonMistake: "Using 2.0 x 10^-5 as total change and ignoring reversal through zero.",
        tags: ["sign-convention", "advanced-calculation", "flux-reversal"],
      },
    ],
    flashcards: [
      {
        id: "t20-5-f1",
        noteId: "t20-5",
        difficulty: 1,
        front: "What change causes induced emf in a circuit?",
        back: "A change in magnetic flux linkage through the circuit.",
        examPhrasing: "Induction requires changing Nphi, not static flux.",
        tags: ["induction", "faraday-law"],
      },
      {
        id: "t20-5-f2",
        noteId: "t20-5",
        difficulty: 1,
        front: "State Faraday's law in equation form.",
        back: "E = - d(Nphi)/dt (or magnitude E = Delta(Nphi)/Delta(t)).",
        examPhrasing: "Negative sign encodes Lenz-law direction.",
        tags: ["equation", "faraday-law"],
      },
      {
        id: "t20-5-f3",
        noteId: "t20-5",
        difficulty: 2,
        front: "What does Lenz's law state?",
        back: "Induced current direction opposes the change in magnetic flux that produces it.",
        examPhrasing: "Opposes the change, not necessarily the original field itself.",
        tags: ["lenz-law", "direction"],
      },
      {
        id: "t20-5-f4",
        noteId: "t20-5",
        difficulty: 2,
        front: "Give the motional-emf formula for a rod moving perpendicularly in uniform B.",
        back: "E = B l v.",
        examPhrasing: "Valid for perpendicular geometry.",
        tags: ["motional-emf", "formula"],
      },
      {
        id: "t20-5-f5",
        noteId: "t20-5",
        difficulty: 3,
        front: "Why does faster flux change produce larger induced emf?",
        back: "Because emf is proportional to rate of change of flux linkage.",
        examPhrasing: "Steeper Nphi-time gradient means larger |E|.",
        tags: ["rate-of-change", "faraday"],
      },
      {
        id: "t20-5-f6",
        noteId: "t20-5",
        difficulty: 3,
        front: "How does increasing number of turns affect induced emf for same flux change rate per turn?",
        back: "Emf increases proportionally with number of turns N.",
        examPhrasing: "Use E proportional N d(phi)/dt.",
        tags: ["turns", "coil-effects"],
      },
      {
        id: "t20-5-f7",
        noteId: "t20-5",
        difficulty: 4,
        front: "Why does a moving conductor in a closed loop experience magnetic drag?",
        back: "Induced current creates magnetic force opposing the motion (Lenz's law).",
        examPhrasing: "External work is needed to keep speed constant.",
        tags: ["magnetic-braking", "energy"],
      },
      {
        id: "t20-5-f8",
        noteId: "t20-5",
        difficulty: 4,
        front: "Why is generator output alternating for a rotating coil?",
        back: "Flux-linkage rate changes sign every half-turn, reversing emf polarity.",
        examPhrasing: "Periodic sign reversal gives alternating emf/current.",
        tags: ["ac-generator", "waveform"],
      },
      {
        id: "t20-5-f9",
        noteId: "t20-5",
        difficulty: 5,
        front: "What does the minus sign in Faraday's law represent physically?",
        back: "Direction set by Lenz's law: induced effects oppose flux-linkage change.",
        examPhrasing: "It enforces energy-conservation-consistent opposition.",
        confusionPair: "Opposes flux vs opposes flux change",
        tags: ["sign-convention", "lenz-law"],
      },
      {
        id: "t20-5-f10",
        noteId: "t20-5",
        difficulty: 5,
        front: "Common pitfall in induction calculations with time units?",
        back: "Forgetting to convert ms to s, causing emf errors by factors of 1000.",
        examPhrasing: "Always convert to SI before substitution.",
        tags: ["exam-technique", "unit-control"],
      },
    ],
  },
};
