import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC7_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t7-1": {
    noteId: "t7-1",
    drills: [
      {
        id: "t7-1-d1",
        noteId: "t7-1",
        kind: "mcq",
        difficulty: 1,
        stem: "For a progressive wave, what does the wavelength represent?",
        options: [
          { id: "A", text: "Distance travelled by the wave in 1 s" },
          { id: "B", text: "Maximum displacement of particles" },
          { id: "C", text: "Distance between adjacent points in phase" },
          { id: "D", text: "Time taken for one oscillation" },
        ],
        correctOptionId: "C",
        explanation:
          "Wavelength is a spatial period: the shortest distance between points oscillating in phase.",
        distractorRationale: {
          B: "Maximum displacement is amplitude, not wavelength.",
          D: "Time for one oscillation is period.",
        },
        tags: ["progressive-waves", "definitions", "wavelength"],
      },
      {
        id: "t7-1-d2",
        noteId: "t7-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem:
          "On a CRO display, one complete cycle of a signal occupies 4.0 horizontal divisions and the peak-to-peak height is 6.0 vertical divisions.\nTime-base setting is 2.0 ms div⁻¹ and y-gain is 0.50 V div⁻¹.\nDetermine (a) the period, (b) the frequency, and (c) the peak voltage.",
        modelAnswerPoints: [
          "(a) Period T = (4.0 divisions)(2.0 ms div⁻¹) = 8.0 ms = 8.0 × 10⁻³ s.",
          "(b) Frequency f = 1/T = 1/(8.0 × 10⁻³ s) = 125 Hz.",
          "(c) Peak-to-peak voltage V_pp = (6.0 divisions)(0.50 V div⁻¹) = 3.0 V.",
          "Peak voltage V_0 = V_pp / 2 = 3.0 V / 2 = 1.5 V.",
        ],
        workedSolution: [
          "Horizontal scale gives time: multiply divisions by time-base setting for period.",
          "Frequency is the reciprocal of period in seconds.",
          "Vertical scale gives peak-to-peak voltage from divisions times y-gain; amplitude is half of peak-to-peak for a symmetric trace.",
        ],
        commonMistake: "Using peak-to-peak voltage as the peak amplitude without dividing by 2.",
        tags: ["cro", "time-base", "y-gain", "frequency-amplitude"],
      },
      {
        id: "t7-1-d3",
        noteId: "t7-1",
        kind: "mcq",
        difficulty: 3,
        stem:
          "Which statement about particle motion in a progressive wave is correct?",
        options: [
          { id: "A", text: "Particles move with the wavefront over long distances." },
          { id: "B", text: "Energy is transferred, but particles oscillate about equilibrium." },
          { id: "C", text: "Both energy and matter are transported permanently in the direction of travel." },
          { id: "D", text: "Particles stay fixed while wave speed changes." },
        ],
        correctOptionId: "B",
        explanation:
          "Progressive waves transfer energy through the medium while particles execute oscillatory motion around fixed equilibrium positions.",
        distractorRationale: {
          C: "Bulk matter transport does not occur in ideal wave propagation.",
          D: "Particles do oscillate; they are not fixed.",
        },
        tags: ["energy-transfer", "particle-motion", "conceptual"],
      },
      {
        id: "t7-1-d4",
        noteId: "t7-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Define amplitude, period and frequency for a progressive wave. State the relation between period and frequency.",
        modelAnswerPoints: [
          "Amplitude: maximum displacement from equilibrium.",
          "Period T: time for one complete oscillation.",
          "Frequency f: number of oscillations per second.",
          "Relation: f = 1/T (or T = 1/f).",
        ],
        workedSolution: [
          "Give each definition in terms of particle oscillation.",
          "Conclude with reciprocal relation between period and frequency.",
        ],
        commonMistake: "Defining frequency as time for one oscillation (confusing with period).",
        tags: ["definitions", "period-frequency", "core-terms"],
      },
      {
        id: "t7-1-d5",
        noteId: "t7-1",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "A wave source produces 120 oscillations in 15 s. The wavelength in the medium is 0.45 m.\nCalculate (a) frequency (b) wave speed.",
        modelAnswerPoints: [
          "Frequency f = number/time = 120/15 = 8.0 Hz.",
          "Use v = f lambda.",
          "v = 8.0 x 0.45 = 3.6 m s^-1.",
          "State answers with units.",
        ],
        workedSolution: [
          "Find f directly from count-rate information.",
          "Substitute frequency and wavelength into wave equation for speed.",
        ],
        commonMistake: "Using T = 120/15 instead of f = 120/15.",
        tags: ["frequency", "wave-equation", "multi-step"],
      },
      {
        id: "t7-1-d6",
        noteId: "t7-1",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "A progressive wave has displacement equation y = 3.0 x 10^-3 sin(40pi t - 5pi x), where y is in m, t in s and x in m.\nDetermine amplitude, frequency, wavelength and speed.",
        modelAnswerPoints: [
          "Amplitude A = 3.0 x 10^-3 m.",
          "Angular frequency omega = 40pi rad s^-1, so f = omega/(2pi) = 20 Hz.",
          "Wave number k = 5pi rad m^-1, so lambda = 2pi/k = 0.40 m.",
          "Speed v = f lambda = 20 x 0.40 = 8.0 m s^-1.",
        ],
        workedSolution: [
          "Compare with standard form y = A sin(omega t - kx).",
          "Extract omega and k, then convert to f and lambda.",
          "Compute wave speed either via f lambda or omega/k.",
        ],
        commonMistake: "Taking wavelength as 5pi m directly from the coefficient of x.",
        tags: ["wave-equation-form", "parameters", "algebra"],
      },
      {
        id: "t7-1-d7",
        noteId: "t7-1",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "A boat sends water waves of frequency 2.5 Hz. Crest spacing is 1.8 m in deep water and 1.2 m near shore.\nAssuming source frequency stays constant, calculate wave speed in both regions and explain the change.",
        modelAnswerPoints: [
          "Deep water speed: v = f lambda = 2.5 x 1.8 = 4.5 m s^-1.",
          "Near shore speed: v = 2.5 x 1.2 = 3.0 m s^-1.",
          "Wave speed decreases near shore.",
          "Frequency is fixed by source, so wavelength decreases when speed decreases.",
        ],
        workedSolution: [
          "Apply v = f lambda separately for each medium condition.",
          "Use constant-source-frequency argument to interpret wavelength change.",
        ],
        commonMistake: "Assuming frequency changes when entering shallower water.",
        tags: ["changing-medium", "wave-speed", "interpretation"],
      },
      {
        id: "t7-1-d8",
        noteId: "t7-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "At t = 0, two points P and Q on a wave are 0.30 m apart along the direction of travel. The wavelength is 0.80 m.\n(a) Calculate phase difference between P and Q in radians.\n(b) If the frequency is 25 Hz, find their time delay.",
        modelAnswerPoints: [
          "Phase difference Delta phi = 2pi(Delta x/lambda) = 2pi(0.30/0.80) = 0.75pi rad.",
          "Fraction of cycle = Delta x/lambda = 0.375.",
          "Period T = 1/f = 1/25 = 0.040 s.",
          "Time delay Delta t = 0.375 x 0.040 = 0.015 s.",
        ],
        workedSolution: [
          "Convert spatial separation into cycle fraction using Delta x/lambda.",
          "Use this fraction for both phase and time calculations.",
          "Relate time delay to period, not directly to frequency without inversion.",
        ],
        commonMistake: "Using pi(Delta x/lambda) instead of 2pi(Delta x/lambda).",
        tags: ["phase-difference", "time-delay", "wave-geometry"],
      },
      {
        id: "t7-1-d9",
        noteId: "t7-1",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem:
          "A loudspeaker emits sound isotropically with power 2.0 W.\n(a) Find intensity at distance 4.0 m.\n(b) Find intensity at 12 m.\n(c) State intensity ratio I(4.0 m) : I(12 m).",
        modelAnswerPoints: [
          "Use I = P/(4pi r^2).",
          "At 4.0 m: I = 2.0/(4pi x 16) = 9.95 x 10^-3 W m^-2.",
          "At 12 m: I = 2.0/(4pi x 144) = 1.11 x 10^-3 W m^-2.",
          "Inverse-square gives ratio 9 : 1.",
        ],
        workedSolution: [
          "Treat source as point source in free space.",
          "Compute each intensity with the same power and different radius.",
          "Cross-check with inverse-square scaling: tripled distance gives one-ninth intensity.",
        ],
        commonMistake: "Using I proportional 1/r instead of 1/r^2.",
        tags: ["intensity", "inverse-square", "sound-waves"],
      },
      {
        id: "t7-1-d10",
        noteId: "t7-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A wave pulse travels along a string segment AB of length 3.6 m in 0.24 s. The driving source frequency is 15 Hz.\n(a) Calculate wave speed.\n(b) Calculate wavelength.\n(c) Determine phase difference between A and B at one instant.\n(d) State whether A and B are in phase.",
        modelAnswerPoints: [
          "Speed v = distance/time = 3.6/0.24 = 15 m s^-1.",
          "Wavelength lambda = v/f = 15/15 = 1.0 m.",
          "Separation AB = 3.6 lambda, so phase difference = 2pi x 3.6 = 7.2pi rad.",
          "Equivalent principal phase difference = 0.2 x 2pi = 0.4pi rad.",
          "Not in phase because separation is not an integer multiple of lambda.",
        ],
        workedSolution: [
          "Use transit data first to get speed independently.",
          "Obtain wavelength from speed-frequency relation.",
          "Convert spatial separation into cycle count and then phase.",
          "Check in-phase condition: Delta x = n lambda.",
        ],
        commonMistake: "Concluding points are in phase because 3.6 is close to 4 wavelengths.",
        tags: ["combined-waves", "phase", "high-yield"],
      },
    ],
    flashcards: [
      {
        id: "t7-1-f1",
        noteId: "t7-1",
        difficulty: 1,
        front: "State the wave equation linking speed, frequency and wavelength.",
        back: "v = f lambda.",
        examPhrasing: "Wave speed equals frequency multiplied by wavelength.",
        tags: ["formula", "wave-equation"],
      },
      {
        id: "t7-1-f2",
        noteId: "t7-1",
        difficulty: 1,
        front: "Define wavelength.",
        back: "Shortest distance between two adjacent points in phase on a wave.",
        examPhrasing: "Distance between neighbouring points oscillating in phase.",
        tags: ["definition", "wavelength"],
      },
      {
        id: "t7-1-f3",
        noteId: "t7-1",
        difficulty: 2,
        front: "Define amplitude for a progressive wave.",
        back: "Maximum displacement of a particle from its equilibrium position.",
        examPhrasing: "Amplitude is the peak displacement from mean position.",
        confusionPair: "amplitude vs wavelength",
        tags: ["definition", "amplitude"],
      },
      {
        id: "t7-1-f4",
        noteId: "t7-1",
        difficulty: 2,
        front: "What is meant by phase difference of 2pi rad?",
        back: "The points differ by one full cycle and are in phase.",
        examPhrasing: "2pi rad corresponds to one complete oscillation.",
        tags: ["phase", "cycles"],
      },
      {
        id: "t7-1-f5",
        noteId: "t7-1",
        difficulty: 3,
        front: "How are period and frequency related?",
        back: "f = 1/T and T = 1/f.",
        examPhrasing: "Frequency is the reciprocal of period.",
        confusionPair: "period vs frequency",
        tags: ["period", "frequency"],
      },
      {
        id: "t7-1-f6",
        noteId: "t7-1",
        difficulty: 3,
        front: "In a progressive wave, what is transferred and what is not?",
        back: "Energy is transferred through the medium; particles oscillate locally with no net transport.",
        examPhrasing: "Progressive waves transfer energy without bulk transfer of matter.",
        tags: ["energy-transfer", "particle-model"],
      },
      {
        id: "t7-1-f7",
        noteId: "t7-1",
        difficulty: 4,
        front: "Write a general expression for phase difference in terms of path difference.",
        back: "Delta phi = 2pi(Delta x/lambda).",
        examPhrasing: "Phase difference is proportional to fraction of wavelength.",
        tags: ["phase-difference", "formula"],
      },
      {
        id: "t7-1-f8",
        noteId: "t7-1",
        difficulty: 4,
        front: "For waves crossing a boundary, what quantity is set by the source and remains constant?",
        back: "Frequency remains constant across the boundary.",
        examPhrasing: "At a boundary, f is unchanged; v and lambda may change.",
        confusionPair: "constant frequency vs constant wavelength",
        tags: ["boundaries", "wave-properties"],
      },
      {
        id: "t7-1-f9",
        noteId: "t7-1",
        difficulty: 5,
        front: "State the inverse-square relation for intensity from a point source.",
        back: "I proportional 1/r^2 and I = P/(4pi r^2).",
        examPhrasing: "Intensity falls with square of distance from point source.",
        tags: ["intensity", "inverse-square"],
      },
      {
        id: "t7-1-f10",
        noteId: "t7-1",
        difficulty: 5,
        front: "Exam checkpoint: when are two points on a progressive wave in phase?",
        back: "When separation is n lambda and phase difference is 2npi (n integer).",
        examPhrasing: "In-phase condition: path difference = integer number of wavelengths.",
        tags: ["exam-technique", "phase-condition"],
      },
    ],
  },
  "t7-2": {
    noteId: "t7-2",
    drills: [
      {
        id: "t7-2-d1",
        noteId: "t7-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which wave is longitudinal?",
        options: [
          { id: "A", text: "Microwaves in vacuum" },
          { id: "B", text: "Sound waves in air" },
          { id: "C", text: "Light waves in glass" },
          { id: "D", text: "Waves on a taut string" },
        ],
        correctOptionId: "B",
        explanation:
          "Sound in air propagates by compressions and rarefactions with particle oscillation parallel to propagation.",
        distractorRationale: {
          C: "Light is electromagnetic and transverse.",
          D: "String waves are transverse under normal conditions.",
        },
        tags: ["longitudinal", "examples", "classification"],
      },
      {
        id: "t7-2-d2",
        noteId: "t7-2",
        kind: "mcq",
        difficulty: 2,
        stem:
          "In a transverse wave, particle oscillation is",
        options: [
          { id: "A", text: "parallel to direction of energy transfer" },
          { id: "B", text: "random relative to wave travel" },
          { id: "C", text: "perpendicular to direction of energy transfer" },
          { id: "D", text: "always circular about equilibrium" },
        ],
        correctOptionId: "C",
        explanation:
          "The defining feature of a transverse wave is displacement perpendicular to propagation direction.",
        distractorRationale: {
          B: "Oscillation has a definite direction, not random orientation.",
          D: "Circular motion is not a required property.",
        },
        tags: ["transverse", "definitions", "particle-motion"],
      },
      {
        id: "t7-2-d3",
        noteId: "t7-2",
        kind: "mcq",
        difficulty: 3,
        stem:
          "A student states that water waves are purely transverse. Which is the best correction?",
        options: [
          { id: "A", text: "Correct, all water waves are exactly transverse." },
          { id: "B", text: "Incorrect, water waves are purely longitudinal only." },
          { id: "C", text: "Surface water waves involve both transverse and longitudinal motion." },
          { id: "D", text: "Water waves are not mechanical waves." },
        ],
        correctOptionId: "C",
        explanation:
          "Real surface water waves involve complex particle paths, with both up-down and back-forth components.",
        distractorRationale: {
          B: "Not purely longitudinal at the surface.",
          D: "Water waves require a medium, so they are mechanical.",
        },
        tags: ["wave-models", "surface-waves", "conceptual-accuracy"],
      },
      {
        id: "t7-2-d4",
        noteId: "t7-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "State one key difference between transverse and longitudinal waves and give one example of each.",
        modelAnswerPoints: [
          "Transverse: oscillations perpendicular to wave direction.",
          "Longitudinal: oscillations parallel to wave direction.",
          "Valid transverse example: electromagnetic wave or wave on a string.",
          "Valid longitudinal example: sound wave in air.",
        ],
        workedSolution: [
          "Define each by displacement direction relative to propagation.",
          "Then support with one clear physical example each.",
        ],
        commonMistake: "Listing examples without stating displacement-direction difference.",
        tags: ["comparison", "examples", "definitions"],
      },
      {
        id: "t7-2-d5",
        noteId: "t7-2",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "A sound wave in air has wavelength 0.68 m and frequency 500 Hz.\n(a) Calculate speed of sound.\n(b) State whether the wave is transverse or longitudinal.",
        modelAnswerPoints: [
          "Use v = f lambda.",
          "v = 500 x 0.68 = 340 m s^-1.",
          "Sound in air is longitudinal.",
          "Particle oscillations are parallel to propagation.",
        ],
        workedSolution: [
          "Compute speed first using wave equation.",
          "Classify sound using the particle-motion model of air compressions.",
        ],
        commonMistake: "Calling sound transverse because wavefronts look like lines in diagrams.",
        tags: ["sound", "classification", "numerical"],
      },
      {
        id: "t7-2-d6",
        noteId: "t7-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "Explain what compressions and rarefactions are in a longitudinal wave. Why do they correspond to pressure variation?",
        modelAnswerPoints: [
          "Compression: region of higher particle density/pressure.",
          "Rarefaction: region of lower particle density/pressure.",
          "Longitudinal oscillation moves particles closer together and further apart periodically.",
          "Pressure depends on local particle spacing and collision rate, so it oscillates with the wave.",
        ],
        workedSolution: [
          "Describe particle crowding and spreading along propagation line.",
          "Link density change physically to pressure change.",
          "State that pressure and density variations move with the wave.",
        ],
        commonMistake: "Describing compressions as points where particles are stationary.",
        tags: ["compressions", "rarefactions", "pressure-wave"],
      },
      {
        id: "t7-2-d7",
        noteId: "t7-2",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "A slinky demonstration shows longitudinal pulses travelling rightward. A marked coil oscillates with amplitude 2.0 cm and frequency 4.0 Hz.\nFind (a) period and (b) maximum speed of that coil assuming SHM motion.",
        modelAnswerPoints: [
          "Period T = 1/f = 1/4.0 = 0.25 s.",
          "Amplitude A = 2.0 cm = 0.020 m.",
          "Maximum particle speed in SHM: v_max = omega A = 2pi f A.",
          "v_max = 2pi x 4.0 x 0.020 = 0.50 m s^-1 (approx).",
        ],
        workedSolution: [
          "Treat individual coil motion as oscillatory even though wave propagates along slinky.",
          "Convert amplitude to SI units before substitution.",
        ],
        commonMistake: "Using wave speed instead of particle maximum speed.",
        tags: ["particle-motion", "shm-link", "longitudinal-wave"],
      },
      {
        id: "t7-2-d8",
        noteId: "t7-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Two wave descriptions are given:\nI: oscillation parallel to energy transfer, with compressions.\nII: oscillation perpendicular to energy transfer, can be polarised.\nIdentify each as transverse/longitudinal and justify.",
        modelAnswerPoints: [
          "I is longitudinal because oscillation is parallel and compressions occur.",
          "Compressions/rarefactions are signature of longitudinal waves.",
          "II is transverse because oscillation is perpendicular.",
          "Ability to be polarised is a defining property of transverse waves.",
        ],
        workedSolution: [
          "Use displacement-direction criterion first.",
          "Use compression and polarisation clues as supporting evidence.",
          "Present each identification with explicit reason.",
        ],
        commonMistake: "Treating polarisation as possible for both wave types.",
        tags: ["identification", "polarisation-link", "reasoning"],
      },
      {
        id: "t7-2-d9",
        noteId: "t7-2",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem:
          "Explain why electromagnetic waves can travel through vacuum but sound waves cannot.",
        modelAnswerPoints: [
          "Electromagnetic waves are oscillating electric and magnetic fields.",
          "They do not require material particles as a propagation medium.",
          "Sound is a mechanical disturbance involving particle collisions/compressions.",
          "Without particles (vacuum), no mechanical compression-rarefaction pattern can be transmitted.",
        ],
        workedSolution: [
          "Contrast the propagation mechanism of EM fields vs mechanical particle motion.",
          "Conclude with medium requirement for sound and no such requirement for EM.",
        ],
        commonMistake: "Saying sound cannot travel in vacuum because frequency is too low.",
        tags: ["em-vs-sound", "medium", "fundamentals"],
      },
      {
        id: "t7-2-d10",
        noteId: "t7-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A wave in a solid has speed 5100 m s^-1 and frequency 1.7 kHz.\n(a) Calculate wavelength.\n(b) The source is replaced by one at 3.4 kHz while medium is unchanged. State new wavelength.\n(c) Explain briefly why medium properties affect speed but source affects frequency.",
        modelAnswerPoints: [
          "Initial wavelength lambda = v/f = 5100/1700 = 3.0 m.",
          "At 3.4 kHz: lambda = 5100/3400 = 1.5 m.",
          "In fixed medium, wave speed depends on material properties (elastic/inertial).",
          "Frequency is set by source oscillation rate.",
          "Hence changing source changes f (and lambda), not v in same medium.",
        ],
        workedSolution: [
          "Perform two wavelength calculations with the same speed.",
          "Then separate roles of source and medium conceptually.",
          "State proportional relationship lambda proportional 1/f for constant v.",
        ],
        commonMistake: "Doubling frequency and also doubling speed in unchanged medium.",
        tags: ["medium-properties", "frequency-source", "analysis"],
      },
    ],
    flashcards: [
      {
        id: "t7-2-f1",
        noteId: "t7-2",
        difficulty: 1,
        front: "Define a transverse wave.",
        back: "A wave in which particle oscillation is perpendicular to direction of energy transfer.",
        examPhrasing: "Displacement is at right angles to propagation direction.",
        tags: ["definition", "transverse"],
      },
      {
        id: "t7-2-f2",
        noteId: "t7-2",
        difficulty: 1,
        front: "Define a longitudinal wave.",
        back: "A wave in which particle oscillation is parallel to direction of energy transfer.",
        examPhrasing: "Displacement is along the direction of propagation.",
        tags: ["definition", "longitudinal"],
      },
      {
        id: "t7-2-f3",
        noteId: "t7-2",
        difficulty: 2,
        front: "What are compressions and rarefactions?",
        back: "Alternating regions of high and low pressure/density in a longitudinal wave.",
        examPhrasing: "Compression: high pressure; rarefaction: low pressure region.",
        tags: ["longitudinal", "pressure-variation"],
      },
      {
        id: "t7-2-f4",
        noteId: "t7-2",
        difficulty: 2,
        front: "Give one example each of transverse and longitudinal waves.",
        back: "Transverse: electromagnetic wave. Longitudinal: sound in air.",
        examPhrasing: "Use named examples linked to correct classification.",
        confusionPair: "sound vs light wave type",
        tags: ["examples", "classification"],
      },
      {
        id: "t7-2-f5",
        noteId: "t7-2",
        difficulty: 3,
        front: "Can longitudinal waves be polarised?",
        back: "No. Polarisation is a property of transverse waves only.",
        examPhrasing: "Only transverse oscillations can be restricted to one plane.",
        tags: ["polarisation", "wave-type"],
      },
      {
        id: "t7-2-f6",
        noteId: "t7-2",
        difficulty: 3,
        front: "Why can sound not travel in vacuum?",
        back: "Sound needs particles to transmit compressions and rarefactions; vacuum has no particles.",
        examPhrasing: "Sound is a mechanical wave requiring a material medium.",
        tags: ["sound", "medium-requirement"],
      },
      {
        id: "t7-2-f7",
        noteId: "t7-2",
        difficulty: 4,
        front: "What stays unchanged for waves passing into another medium: speed, frequency, or wavelength?",
        back: "Frequency stays unchanged; speed and wavelength may change.",
        examPhrasing: "Boundary condition: source fixes frequency.",
        confusionPair: "constant frequency vs constant speed",
        tags: ["boundary-behaviour", "wave-properties"],
      },
      {
        id: "t7-2-f8",
        noteId: "t7-2",
        difficulty: 4,
        front: "How is wave speed in a medium determined conceptually?",
        back: "By medium properties (elastic restoring effects and inertia), not by source amplitude.",
        examPhrasing: "In a given medium, v is set by material properties.",
        tags: ["wave-speed", "medium-dependence"],
      },
      {
        id: "t7-2-f9",
        noteId: "t7-2",
        difficulty: 5,
        front: "What is the key model limitation in calling water waves 'transverse'?",
        back: "Surface water particles have mixed motion (both vertical and horizontal components), so not purely transverse.",
        examPhrasing: "Water surface waves are often approximated as transverse but are not strictly pure.",
        tags: ["model-limitations", "surface-waves"],
      },
      {
        id: "t7-2-f10",
        noteId: "t7-2",
        difficulty: 5,
        front: "Exam checkpoint: how should you justify wave-type classification in structured answers?",
        back: "State displacement direction relative to propagation, then add a characteristic feature (e.g., polarisation or compressions).",
        examPhrasing: "Classification marks require criterion plus supporting feature.",
        tags: ["exam-technique", "classification"],
      },
    ],
  },
  "t7-3": {
    noteId: "t7-3",
    drills: [
      {
        id: "t7-3-d1",
        noteId: "t7-3",
        kind: "mcq",
        difficulty: 1,
        stem: "The Doppler effect for sound is best described as",
        options: [
          { id: "A", text: "Change in wave speed due to source motion only" },
          { id: "B", text: "Apparent change in observed frequency due to relative motion" },
          { id: "C", text: "Change in amplitude because of diffraction" },
          { id: "D", text: "Production of harmonics at high speed" },
        ],
        correctOptionId: "B",
        explanation:
          "Doppler effect is a perceived frequency change caused by relative motion between source and observer in a medium.",
        distractorRationale: {
          C: "Diffraction affects spread, not the Doppler definition.",
          D: "Harmonics are unrelated to Doppler mechanism.",
        },
        tags: ["doppler-effect", "definitions"],
      },
      {
        id: "t7-3-d2",
        noteId: "t7-3",
        kind: "mcq",
        difficulty: 2,
        stem:
          "A car horn approaches a stationary listener. Compared with emitted frequency, the listener hears",
        options: [
          { id: "A", text: "Lower frequency and longer wavelength in air" },
          { id: "B", text: "Higher frequency and shorter wavelength in front of source" },
          { id: "C", text: "No change because speed of sound is constant" },
          { id: "D", text: "Higher frequency behind source only" },
        ],
        correctOptionId: "B",
        explanation:
          "Moving source compresses wavefronts ahead of it, reducing wavelength there and increasing observed frequency.",
        distractorRationale: {
          C: "Wave speed in medium is near constant, but observed frequency can still change.",
          D: "Behind source wavelengths are stretched, giving lower frequency.",
        },
        tags: ["approaching-source", "wavelength-change", "conceptual"],
      },
      {
        id: "t7-3-d3",
        noteId: "t7-3",
        kind: "mcq",
        difficulty: 3,
        stem:
          "Sound speed is 340 m s^-1. A source emits 600 Hz and moves toward a stationary observer at 20 m s^-1. What frequency is heard?",
        options: [
          { id: "A", text: "566 Hz" },
          { id: "B", text: "600 Hz" },
          { id: "C", text: "638 Hz" },
          { id: "D", text: "676 Hz" },
        ],
        correctOptionId: "C",
        explanation:
          "For moving source toward stationary observer: f' = f v/(v - u_s) = 600 x 340/320 = 637.5 Hz.",
        distractorRationale: {
          B: "No-shift value ignores relative motion.",
          D: "This arises from using the wrong denominator or observer formula.",
        },
        tags: ["doppler-formula", "moving-source", "numerical"],
      },
      {
        id: "t7-3-d4",
        noteId: "t7-3",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Explain qualitatively why pitch rises as an ambulance approaches and falls after it passes.",
        modelAnswerPoints: [
          "Ahead of moving source, emitted wavefronts are closer together (shorter wavelength).",
          "Behind source, wavefronts are farther apart (longer wavelength).",
          "In same medium, sound speed is approximately constant.",
          "Since f = v/lambda, shorter lambda gives higher observed frequency and longer lambda gives lower frequency.",
        ],
        workedSolution: [
          "Describe wavefront spacing relative to source motion.",
          "Then connect wavelength shift to observed frequency via wave equation.",
        ],
        commonMistake: "Stating that the source emits a different frequency when moving.",
        tags: ["qualitative-doppler", "sirens", "pitch"],
      },
      {
        id: "t7-3-d5",
        noteId: "t7-3",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Speed of sound is 330 m s^-1. A stationary source emits 500 Hz. An observer moves toward the source at 15 m s^-1.\nCalculate observed frequency.",
        modelAnswerPoints: [
          "Use moving-observer formula: f' = f(v + u_o)/v.",
          "f' = 500 x (330 + 15)/330.",
          "f' = 522.7 Hz.",
          "Observed frequency approx 523 Hz.",
        ],
        workedSolution: [
          "Choose formula for moving observer (source stationary).",
          "Approaching observer uses plus sign in numerator.",
        ],
        commonMistake: "Using moving-source formula when source is stationary.",
        tags: ["moving-observer", "formula-selection", "calculation"],
      },
      {
        id: "t7-3-d6",
        noteId: "t7-3",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "A whistle emits 800 Hz. Sound speed is 340 m s^-1. The source moves away from a stationary observer at 25 m s^-1.\nFind observed frequency and percentage decrease.",
        modelAnswerPoints: [
          "Moving source away: f' = f v/(v + u_s).",
          "f' = 800 x 340/365 = 745 Hz (approx).",
          "Frequency decrease = 800 - 745 = 55 Hz.",
          "Percentage decrease = (55/800) x 100 = 6.9% (approx).",
        ],
        workedSolution: [
          "Use plus in denominator for receding source.",
          "Compute shifted frequency then compare with emitted value.",
        ],
        commonMistake: "Using minus sign for a receding source.",
        tags: ["receding-source", "percentage-change", "doppler"],
      },
      {
        id: "t7-3-d7",
        noteId: "t7-3",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "Two cyclists move toward each other. One carries a 700 Hz buzzer and rides at 8 m s^-1. The other (observer) rides at 6 m s^-1 toward the source. Speed of sound is 340 m s^-1.\nCalculate frequency heard.",
        modelAnswerPoints: [
          "Use combined relation: f' = f(v + u_o)/(v - u_s).",
          "Substitute f' = 700 x (340 + 6)/(340 - 8).",
          "f' = 700 x 346/332 = 729.5 Hz.",
          "Observed frequency approx 730 Hz.",
        ],
        workedSolution: [
          "Approaching observer increases numerator; approaching source decreases denominator.",
          "Keep sign conventions consistent with physical approach.",
        ],
        commonMistake: "Adding both speeds directly to sound speed without formula structure.",
        tags: ["both-moving", "sign-convention", "advanced-calculation"],
      },
      {
        id: "t7-3-d8",
        noteId: "t7-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A stationary listener records 920 Hz as a source approaches and 760 Hz as it moves away along the same line. Assume constant source speed and v = 340 m s^-1.\nCalculate source frequency and source speed.",
        modelAnswerPoints: [
          "Approach: 920 = f x 340/(340 - u_s).",
          "Recede: 760 = f x 340/(340 + u_s).",
          "Ratio: 920/760 = (340 + u_s)/(340 - u_s) gives u_s = 32.3 m s^-1.",
          "Substitute into either equation: f approx 833 Hz.",
        ],
        workedSolution: [
          "Form two equations for approach and recession cases.",
          "Divide equations to eliminate f first.",
          "Solve for speed, then back-substitute to find emitted frequency.",
        ],
        commonMistake: "Using same denominator sign for both approach and recession.",
        tags: ["inverse-problem", "algebra", "sirens"],
      },
      {
        id: "t7-3-d9",
        noteId: "t7-3",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem:
          "State two assumptions in standard Doppler calculations for sound and discuss one practical reason measured values may differ from prediction.",
        modelAnswerPoints: [
          "Assumption: motion along line joining source and observer (radial component considered).",
          "Assumption: uniform medium with constant sound speed and negligible wind effects.",
          "Assumption: source frequency remains constant.",
          "Practical deviation example: wind, acceleration, reflection, or off-axis motion alters measured shift.",
        ],
        workedSolution: [
          "List assumptions explicitly to secure method marks.",
          "Then relate one real-world effect to how it changes effective radial speed or sound speed.",
        ],
        commonMistake: "Claiming Doppler formulas account automatically for any direction of motion.",
        tags: ["assumptions", "model-validity", "evaluation"],
      },
      {
        id: "t7-3-d10",
        noteId: "t7-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A detector moves directly toward a stationary 1.20 kHz source in still air. It records 1.28 kHz.\nTake v = 343 m s^-1.\n(a) Find detector speed.\n(b) If the detector then moves away at same speed, predict detected frequency.\n(c) Comment on symmetry of shifts in Hz.",
        modelAnswerPoints: [
          "Moving observer toward source: 1280 = 1200(v + u_o)/v.",
          "(v + u_o)/v = 1280/1200 = 1.0667, so u_o = 0.0667v = 22.9 m s^-1.",
          "Away at same speed: f' = 1200(v - 22.9)/v = 1120 Hz (approx).",
          "Upward shift is +80 Hz, downward shift is -80 Hz for moving observer at same speed.",
          "Symmetry in Hz occurs here for observer-motion case with same speed magnitude.",
        ],
        workedSolution: [
          "Rearrange observer formula to isolate velocity ratio first.",
          "Use same magnitude with opposite sign for receding case.",
          "Compare absolute differences from 1200 Hz to discuss symmetry.",
        ],
        commonMistake: "Applying moving-source formula even though source is stationary.",
        tags: ["moving-observer", "multi-part", "interpretation"],
      },
    ],
    flashcards: [
      {
        id: "t7-3-f1",
        noteId: "t7-3",
        difficulty: 1,
        front: "Define the Doppler effect for sound.",
        back: "Apparent change in observed frequency due to relative motion between source and observer.",
        examPhrasing: "Observed frequency changes when there is relative radial motion.",
        tags: ["definition", "doppler"],
      },
      {
        id: "t7-3-f2",
        noteId: "t7-3",
        difficulty: 1,
        front: "Approaching source: does observed pitch increase or decrease?",
        back: "Increase.",
        examPhrasing: "Approach gives higher observed frequency.",
        tags: ["qualitative", "approach"],
      },
      {
        id: "t7-3-f3",
        noteId: "t7-3",
        difficulty: 2,
        front: "Receding source: does observed pitch increase or decrease?",
        back: "Decrease.",
        examPhrasing: "Recession gives lower observed frequency.",
        tags: ["qualitative", "recede"],
      },
      {
        id: "t7-3-f4",
        noteId: "t7-3",
        difficulty: 2,
        front: "Write formula for stationary observer and source moving toward observer.",
        back: "f' = f v/(v - u_s).",
        examPhrasing: "Use minus in denominator for approaching source.",
        confusionPair: "source-motion vs observer-motion formula",
        tags: ["formula", "moving-source"],
      },
      {
        id: "t7-3-f5",
        noteId: "t7-3",
        difficulty: 3,
        front: "Write formula for stationary source and observer moving toward source.",
        back: "f' = f(v + u_o)/v.",
        examPhrasing: "Use plus in numerator for approaching observer.",
        confusionPair: "numerator sign vs denominator sign",
        tags: ["formula", "moving-observer"],
      },
      {
        id: "t7-3-f6",
        noteId: "t7-3",
        difficulty: 3,
        front: "What physical quantity remains approximately fixed in standard Doppler sound questions in still air?",
        back: "Speed of sound in the medium.",
        examPhrasing: "Take v as constant for given medium conditions unless stated otherwise.",
        tags: ["assumptions", "sound-speed"],
      },
      {
        id: "t7-3-f7",
        noteId: "t7-3",
        difficulty: 4,
        front: "What sign choice corresponds to source moving away from observer?",
        back: "Use plus in denominator: f' = f v/(v + u_s).",
        examPhrasing: "Receding source stretches wavelength and lowers observed frequency.",
        tags: ["sign-convention", "source-motion"],
      },
      {
        id: "t7-3-f8",
        noteId: "t7-3",
        difficulty: 4,
        front: "Why does Doppler shift depend on radial motion component?",
        back: "Only motion along the line joining source and observer changes spacing of arriving wavefronts.",
        examPhrasing: "Use velocity component along line of sight.",
        tags: ["radial-component", "geometry"],
      },
      {
        id: "t7-3-f9",
        noteId: "t7-3",
        difficulty: 5,
        front: "Give one practical effect that can cause discrepancy from ideal Doppler predictions.",
        back: "Examples: wind, acceleration, reflections, or off-axis trajectories.",
        examPhrasing: "Model assumes uniform still medium and steady radial speeds.",
        tags: ["limitations", "real-world"],
      },
      {
        id: "t7-3-f10",
        noteId: "t7-3",
        difficulty: 5,
        front: "Exam checkpoint for Doppler problems with formulas?",
        back: "Identify who moves, choose correct sign convention, substitute with units, then check shift direction is physically sensible.",
        examPhrasing: "Method marks rely on correct formula selection before arithmetic.",
        tags: ["exam-technique", "problem-solving"],
      },
    ],
  },
  "t7-4": {
    noteId: "t7-4",
    drills: [
      {
        id: "t7-4-d1",
        noteId: "t7-4",
        kind: "mcq",
        difficulty: 1,
        stem: "Which has the shortest wavelength in the electromagnetic spectrum?",
        options: [
          { id: "A", text: "Radio waves" },
          { id: "B", text: "Microwaves" },
          { id: "C", text: "Ultraviolet" },
          { id: "D", text: "Gamma rays" },
        ],
        correctOptionId: "D",
        explanation:
          "Gamma rays occupy the highest-frequency, shortest-wavelength end of the electromagnetic spectrum.",
        distractorRationale: {
          B: "Microwaves are much longer wavelength than UV or gamma.",
          C: "UV is shorter than visible but longer than X-rays and gamma.",
        },
        tags: ["em-spectrum", "ordering", "basics"],
      },
      {
        id: "t7-4-d2",
        noteId: "t7-4",
        kind: "mcq",
        difficulty: 2,
        stem:
          "All electromagnetic waves in vacuum have the same",
        options: [
          { id: "A", text: "wavelength" },
          { id: "B", text: "frequency" },
          { id: "C", text: "speed" },
          { id: "D", text: "photon energy" },
        ],
        correctOptionId: "C",
        explanation:
          "In vacuum all electromagnetic waves propagate at c = 3.00 x 10^8 m s^-1.",
        distractorRationale: {
          B: "Frequency varies across the spectrum.",
          D: "Photon energy depends on frequency.",
        },
        tags: ["vacuum-speed", "em-properties"],
      },
      {
        id: "t7-4-d3",
        noteId: "t7-4",
        kind: "mcq",
        difficulty: 3,
        stem:
          "A wave has frequency 9.0 x 10^14 Hz in vacuum. Which region is it in?",
        options: [
          { id: "A", text: "Infrared" },
          { id: "B", text: "Visible" },
          { id: "C", text: "Ultraviolet" },
          { id: "D", text: "Microwave" },
        ],
        correctOptionId: "C",
        explanation:
          "Visible frequencies are roughly 4.0 x 10^14 to 7.5 x 10^14 Hz, so 9.0 x 10^14 Hz is ultraviolet.",
        distractorRationale: {
          B: "Upper visible range is lower than 9.0 x 10^14 Hz.",
          D: "Microwaves are far lower frequency.",
        },
        tags: ["frequency-ranges", "classification"],
      },
      {
        id: "t7-4-d4",
        noteId: "t7-4",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "State two wave properties common to all electromagnetic waves and give one key difference between adjacent regions.",
        modelAnswerPoints: [
          "All EM waves are transverse.",
          "All EM waves travel at c in vacuum.",
          "They all can show wave phenomena such as reflection/refraction/diffraction/interference.",
          "Difference between regions: wavelength, frequency and hence photon energy.",
        ],
        workedSolution: [
          "Give universal properties first.",
          "Then state that neighbouring regions differ by frequency/wavelength scale, not by fundamental wave type.",
        ],
        commonMistake: "Claiming different EM regions travel at different speeds in vacuum.",
        tags: ["common-properties", "comparison", "theory"],
      },
      {
        id: "t7-4-d5",
        noteId: "t7-4",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Calculate wavelength in vacuum for radiation of frequency 6.0 x 10^9 Hz.",
        modelAnswerPoints: [
          "Use c = f lambda.",
          "lambda = c/f = (3.00 x 10^8)/(6.0 x 10^9).",
          "lambda = 5.0 x 10^-2 m.",
          "This is 5.0 cm (microwave region).",
        ],
        workedSolution: [
          "Rearrange c = f lambda to isolate wavelength.",
          "Compute in SI then convert to cm if useful for interpretation.",
        ],
        commonMistake: "Using c = 3.00 x 10^6 m s^-1.",
        tags: ["em-calculation", "wavelength", "units"],
      },
      {
        id: "t7-4-d6",
        noteId: "t7-4",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "Place these in order of increasing frequency: infrared, gamma, radio, ultraviolet, visible. Then state one typical use for any two of them.",
        modelAnswerPoints: [
          "Order (low to high f): radio, infrared, visible, ultraviolet, gamma.",
          "Any valid application for two regions, e.g. radio for communications.",
          "Infrared for thermal imaging/heating.",
          "Ultraviolet for sterilisation and gamma for radiotherapy/tracing are also valid.",
        ],
        workedSolution: [
          "Recall spectrum from longest wavelength/lowest frequency to shortest/highest.",
          "Attach realistic applications matching penetration/energy characteristics.",
        ],
        commonMistake: "Placing ultraviolet below visible in frequency.",
        tags: ["ordering", "applications", "spectrum-knowledge"],
      },
      {
        id: "t7-4-d7",
        noteId: "t7-4",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "Visible light of wavelength 620 nm enters glass of refractive index 1.50.\n(a) Calculate speed in glass.\n(b) Calculate wavelength in glass.\n(c) State whether frequency changes.",
        modelAnswerPoints: [
          "Speed in glass v = c/n = 3.00 x 10^8 / 1.50 = 2.00 x 10^8 m s^-1.",
          "Frequency unchanged at boundary.",
          "Wavelength in glass lambda_g = lambda_0 / n = 620/1.50 = 413 nm (approx).",
          "Hence wavelength decreases in denser optical medium.",
        ],
        workedSolution: [
          "Use refractive-index relation for speed.",
          "Keep frequency constant crossing boundary.",
          "Use v = f lambda or lambda_0/n to find new wavelength.",
        ],
        commonMistake: "Changing frequency when light enters another medium.",
        tags: ["refraction", "em-waves", "boundary-effects"],
      },
      {
        id: "t7-4-d8",
        noteId: "t7-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Explain why higher-frequency electromagnetic radiation is generally more hazardous to living tissue.",
        modelAnswerPoints: [
          "Photon energy increases with frequency (E = hf).",
          "Higher-energy photons can ionise atoms/molecules.",
          "Ionisation can damage DNA and cellular structures.",
          "So UV, X-rays and gamma are more biologically hazardous than radio/microwave under comparable exposure contexts.",
        ],
        workedSolution: [
          "Link hazard to quantum energy per photon.",
          "Then connect ionisation potential to biological damage mechanisms.",
        ],
        commonMistake: "Assuming hazard depends only on wave amplitude, not frequency/energy.",
        tags: ["biological-effects", "hf", "ionisation"],
      },
      {
        id: "t7-4-d9",
        noteId: "t7-4",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem:
          "A transmitter emits at 100 MHz with power 40 W isotropically.\n(a) Find wavelength in air (take c = 3.00 x 10^8 m s^-1).\n(b) Find intensity at 50 m assuming point-source spreading.",
        modelAnswerPoints: [
          "Frequency f = 100 MHz = 1.00 x 10^8 Hz.",
          "Wavelength lambda = c/f = 3.00 m.",
          "Intensity I = P/(4pi r^2) = 40/(4pi x 50^2).",
          "I = 1.27 x 10^-3 W m^-2 (approx).",
        ],
        workedSolution: [
          "Convert frequency units first (MHz to Hz).",
          "Use c = f lambda for wavelength.",
          "Apply inverse-square intensity relation for isotropic emission.",
        ],
        commonMistake: "Using 100 Hz instead of 100 MHz in wavelength calculation.",
        tags: ["radio-waves", "intensity", "unit-conversion"],
      },
      {
        id: "t7-4-d10",
        noteId: "t7-4",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A remote-sensing system can use either infrared (lambda = 1.0 x 10^-6 m) or microwave (lambda = 3.0 x 10^-2 m).\n(a) Compare their frequencies.\n(b) State which provides greater diffraction around obstacles.\n(c) State which gives better spatial resolution and explain.",
        modelAnswerPoints: [
          "f_IR = c/lambda = 3.0 x 10^8 / 1.0 x 10^-6 = 3.0 x 10^14 Hz.",
          "f_mw = 3.0 x 10^8 / 3.0 x 10^-2 = 1.0 x 10^10 Hz.",
          "Microwaves (longer wavelength) diffract more strongly around obstacles/openings.",
          "Infrared (shorter wavelength) gives better spatial resolution because diffraction spreading is less.",
          "Higher frequency corresponds to shorter wavelength and typically finer detail capability.",
        ],
        workedSolution: [
          "Calculate frequencies from wavelength inversions.",
          "Apply diffraction principle: longer wavelength gives greater spreading.",
          "Relate resolution to smaller diffraction blur for shorter wavelengths.",
        ],
        commonMistake: "Assuming higher diffraction always implies better imaging resolution.",
        tags: ["applications", "diffraction-tradeoff", "reasoning"],
      },
    ],
    flashcards: [
      {
        id: "t7-4-f1",
        noteId: "t7-4",
        difficulty: 1,
        front: "What is the speed of electromagnetic waves in vacuum?",
        back: "c = 3.00 x 10^8 m s^-1.",
        examPhrasing: "All electromagnetic waves travel at c in vacuum.",
        tags: ["constant-c", "core-fact"],
      },
      {
        id: "t7-4-f2",
        noteId: "t7-4",
        difficulty: 1,
        front: "State the wave relation for EM waves in vacuum.",
        back: "c = f lambda.",
        examPhrasing: "Use c, not medium speed, for vacuum calculations.",
        tags: ["formula", "vacuum"],
      },
      {
        id: "t7-4-f3",
        noteId: "t7-4",
        difficulty: 2,
        front: "Order these from low to high frequency: radio, microwave, infrared, visible, ultraviolet, X-ray, gamma.",
        back: "Radio < microwave < infrared < visible < ultraviolet < X-ray < gamma.",
        examPhrasing: "Frequency increases as wavelength decreases across spectrum.",
        tags: ["ordering", "spectrum"],
      },
      {
        id: "t7-4-f4",
        noteId: "t7-4",
        difficulty: 2,
        front: "Which EM region has longest wavelength?",
        back: "Radio waves.",
        examPhrasing: "Radio is the low-frequency, long-wavelength end.",
        confusionPair: "radio vs gamma extremes",
        tags: ["extremes", "spectrum"],
      },
      {
        id: "t7-4-f5",
        noteId: "t7-4",
        difficulty: 3,
        front: "Which EM region has highest frequency and energy?",
        back: "Gamma rays.",
        examPhrasing: "Gamma rays occupy the highest-frequency end of the EM spectrum.",
        tags: ["extremes", "energy"],
      },
      {
        id: "t7-4-f6",
        noteId: "t7-4",
        difficulty: 3,
        front: "What happens to EM wave frequency when passing from air into glass?",
        back: "Frequency stays the same.",
        examPhrasing: "At boundaries, frequency is fixed by source; speed and wavelength change.",
        confusionPair: "frequency change vs wavelength change",
        tags: ["boundary", "frequency"],
      },
      {
        id: "t7-4-f7",
        noteId: "t7-4",
        difficulty: 4,
        front: "How does photon energy depend on frequency?",
        back: "E = hf, so higher frequency means higher photon energy.",
        examPhrasing: "Photon energy is directly proportional to frequency.",
        tags: ["quantum-link", "hf"],
      },
      {
        id: "t7-4-f8",
        noteId: "t7-4",
        difficulty: 4,
        front: "Give one practical use of microwaves and one of infrared.",
        back: "Microwaves: satellite/mobile communication or cooking. Infrared: thermal imaging or remote controls.",
        examPhrasing: "Link each region to an application consistent with its wavelength/penetration.",
        tags: ["applications", "microwave", "infrared"],
      },
      {
        id: "t7-4-f9",
        noteId: "t7-4",
        difficulty: 5,
        front: "Why are UV, X-rays and gamma classed as ionising (in general) more than radio and microwaves?",
        back: "Their photons carry much higher energy, often enough to remove electrons from atoms.",
        examPhrasing: "Ionisation risk increases with photon energy (higher frequency).",
        tags: ["ionising-radiation", "hazard"],
      },
      {
        id: "t7-4-f10",
        noteId: "t7-4",
        difficulty: 5,
        front: "Exam checkpoint for EM-spectrum answers?",
        back: "Quote correct order, state frequency-wavelength inverse relation, and use c = f lambda with consistent SI units.",
        examPhrasing: "Method marks are often in ordering plus correct equation use.",
        tags: ["exam-technique", "spectrum-skills"],
      },
    ],
  },
  "t7-5": {
    noteId: "t7-5",
    drills: [
      {
        id: "t7-5-d1",
        noteId: "t7-5",
        kind: "mcq",
        difficulty: 1,
        stem: "Polarisation is a property shown by",
        options: [
          { id: "A", text: "all waves" },
          { id: "B", text: "longitudinal waves only" },
          { id: "C", text: "transverse waves only" },
          { id: "D", text: "sound waves in air only" },
        ],
        correctOptionId: "C",
        explanation:
          "Only transverse waves can have oscillations restricted to one plane, which is what polarisation does.",
        distractorRationale: {
          B: "Longitudinal waves cannot be plane-polarised.",
          D: "Sound in air is longitudinal and not polarisable.",
        },
        tags: ["polarisation", "transverse-waves"],
      },
      {
        id: "t7-5-d2",
        noteId: "t7-5",
        kind: "mcq",
        difficulty: 2,
        stem:
          "Unpolarised light passes through one ideal polariser. The transmitted intensity is",
        options: [
          { id: "A", text: "unchanged" },
          { id: "B", text: "halved" },
          { id: "C", text: "doubled" },
          { id: "D", text: "reduced to one quarter" },
        ],
        correctOptionId: "B",
        explanation:
          "An ideal polariser transmits one component from randomly oriented planes, giving I = I0/2 for unpolarised incident light.",
        distractorRationale: {
          C: "Polariser cannot increase intensity.",
          D: "Quarter occurs with two polarisers at specific relative angle after first halving.",
        },
        tags: ["intensity", "ideal-polariser", "malus-context"],
      },
      {
        id: "t7-5-d3",
        noteId: "t7-5",
        kind: "mcq",
        difficulty: 3,
        stem:
          "Two ideal polarisers have transmission axes at 90 degrees. Unpolarised light enters the first. Intensity emerging from second is",
        options: [
          { id: "A", text: "I0/2" },
          { id: "B", text: "I0/4" },
          { id: "C", text: "0" },
          { id: "D", text: "I0" },
        ],
        correctOptionId: "C",
        explanation:
          "After first polariser, light is plane-polarised. A second analyser at 90 degrees blocks that plane completely.",
        distractorRationale: {
          B: "Quarter would occur at 45 degrees between axes, not 90 degrees.",
          D: "No transmission increase through crossed pair.",
        },
        tags: ["crossed-polarisers", "intensity", "conceptual"],
      },
      {
        id: "t7-5-d4",
        noteId: "t7-5",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Explain what is meant by plane-polarised light and state what this tells us about the nature of light.",
        modelAnswerPoints: [
          "Plane-polarised light has oscillations confined to one plane/direction perpendicular to travel.",
          "A polariser selects one vibration direction from many possible directions in unpolarised light.",
          "Only transverse waves can be polarised.",
          "Therefore light has transverse-wave nature.",
        ],
        workedSolution: [
          "Define polarisation operationally (restriction of oscillation direction).",
          "Use the polarisation criterion to infer transverse character of light.",
        ],
        commonMistake: "Saying polarisation shows light is longitudinal.",
        tags: ["definition", "evidence-for-transverse", "light"],
      },
      {
        id: "t7-5-d5",
        noteId: "t7-5",
        kind: "structured",
        difficulty: 3,
        marks: 4,
        stem:
          "Unpolarised light of intensity 180 W m^-2 passes through an ideal polariser, then through a second polariser at 60 degrees to the first.\nCalculate final intensity.",
        modelAnswerPoints: [
          "After first polariser: I1 = I0/2 = 90 W m^-2.",
          "Apply Malus law at second: I2 = I1 cos^2 60 degrees.",
          "cos^2 60 degrees = 0.25.",
          "I2 = 90 x 0.25 = 22.5 W m^-2.",
        ],
        workedSolution: [
          "Use initial halving for unpolarised to polarised transmission.",
          "Then use angle-dependent Malus law for analyser.",
        ],
        commonMistake: "Applying cos theta instead of cos^2 theta.",
        tags: ["malus-law", "intensity", "two-polarisers"],
      },
      {
        id: "t7-5-d6",
        noteId: "t7-5",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "Derive intensity transmitted by an analyser at angle theta to incident plane-polarised light and name the law used.",
        modelAnswerPoints: [
          "Resolve electric field amplitude E into component along analyser axis: E_parallel = E0 cos theta.",
          "Intensity is proportional to square of amplitude.",
          "So I proportional E_parallel^2 = E0^2 cos^2 theta.",
          "Hence I = Imax cos^2 theta (Malus law).",
        ],
        workedSolution: [
          "Start from vector projection of field amplitude.",
          "Use intensity-amplitude-squared relation.",
          "State final named law clearly.",
        ],
        commonMistake: "Assuming intensity is proportional to field amplitude directly.",
        tags: ["derivation", "malus-law", "field-model"],
      },
      {
        id: "t7-5-d7",
        noteId: "t7-5",
        kind: "structured",
        difficulty: 4,
        marks: 5,
        stem:
          "Two ideal polaroids are crossed (90 degrees). A third ideal polaroid is inserted between them at 45 degrees to each.\nIf incident unpolarised intensity is I0, find transmitted intensity in terms of I0.",
        modelAnswerPoints: [
          "After first polariser: I1 = I0/2.",
          "After middle polariser at 45 degrees: I2 = I1 cos^2 45 = (I0/2) x 1/2 = I0/4.",
          "After last polariser (45 degrees to middle): I3 = I2 cos^2 45 = (I0/4) x 1/2.",
          "Final intensity I3 = I0/8.",
        ],
        workedSolution: [
          "Apply halving first, then Malus law sequentially at each relative angle.",
          "Note non-zero transmission despite outer pair being crossed because middle polariser rotates transmitted plane in stages.",
        ],
        commonMistake: "Assuming final intensity must remain zero whenever first and last are crossed.",
        tags: ["three-polariser", "malus-law", "advanced-concept"],
      },
      {
        id: "t7-5-d8",
        noteId: "t7-5",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Describe one practical application of polarisation and explain the physics of how it works.",
        modelAnswerPoints: [
          "Valid example: Polaroid sunglasses reducing glare from horizontal reflections.",
          "Reflected glare from horizontal surfaces is partially horizontally polarised.",
          "Sunglasses have vertical transmission axis, reducing horizontal component intensity.",
          "Result is reduced glare and improved contrast/visibility.",
        ],
        workedSolution: [
          "Name a concrete device/application.",
          "Link it to orientation of polarisation relative to transmission axis.",
          "Explain observed benefit in terms of reduced transmitted intensity of unwanted component.",
        ],
        commonMistake: "Claiming sunglasses block all light equally regardless of orientation.",
        tags: ["applications", "glare-reduction", "physics-explanation"],
      },
      {
        id: "t7-5-d9",
        noteId: "t7-5",
        kind: "structured",
        difficulty: 5,
        marks: 6,
        stem:
          "An analyser is rotated while viewing plane-polarised light of fixed intensity 64 W m^-2 before the analyser.\n(a) Find maximum and minimum transmitted intensities for an ideal analyser.\n(b) Find transmitted intensity at 30 degrees.\n(c) Explain the angular variation shape.",
        modelAnswerPoints: [
          "For ideal analyser: I = Imax cos^2 theta with Imax = 64 W m^-2.",
          "Maximum at theta = 0 degrees: 64 W m^-2.",
          "Minimum at theta = 90 degrees: 0 W m^-2.",
          "At 30 degrees: I = 64 cos^2 30 = 64 x 0.75 = 48 W m^-2.",
          "Cos^2 dependence gives periodic variation with period 180 degrees.",
        ],
        workedSolution: [
          "Recognise given intensity is Imax for aligned analyser.",
          "Use Malus law for any angle.",
          "State periodicity from cosine-squared behaviour.",
        ],
        commonMistake: "Using period 360 degrees for intensity pattern instead of 180 degrees.",
        tags: ["analyser-rotation", "malus-law", "graph-interpretation"],
      },
      {
        id: "t7-5-d10",
        noteId: "t7-5",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Light of intensity I0 is unpolarised. It passes through two ideal polarisers with unknown relative angle theta and emerges with intensity I0/6.\nFind theta.",
        modelAnswerPoints: [
          "After first polariser: I1 = I0/2.",
          "After second: I2 = I1 cos^2 theta = (I0/2) cos^2 theta.",
          "Set (I0/2) cos^2 theta = I0/6 -> cos^2 theta = 1/3.",
          "cos theta = 1/sqrt(3) (principal acute solution).",
          "theta = cos^-1(1/sqrt(3)) = 54.7 degrees (also equivalent 125.3 degrees etc.).",
        ],
        workedSolution: [
          "Model transmission in two stages: unpolarised halving then Malus law.",
          "Cancel I0 early to simplify algebra.",
          "Take inverse cosine and quote principal angle in 0-90 degrees unless otherwise required.",
        ],
        commonMistake: "Forgetting first-polariser halving and solving cos^2 theta = 1/6.",
        tags: ["inverse-malus", "algebra", "high-difficulty"],
      },
    ],
    flashcards: [
      {
        id: "t7-5-f1",
        noteId: "t7-5",
        difficulty: 1,
        front: "What does polarisation show about a wave?",
        back: "That the wave is transverse.",
        examPhrasing: "Only transverse waves can be plane-polarised.",
        tags: ["core-idea", "polarisation"],
      },
      {
        id: "t7-5-f2",
        noteId: "t7-5",
        difficulty: 1,
        front: "What is plane-polarised light?",
        back: "Light whose electric field oscillates in one plane/direction only.",
        examPhrasing: "Oscillations are restricted to a single plane perpendicular to propagation.",
        tags: ["definition", "light"],
      },
      {
        id: "t7-5-f3",
        noteId: "t7-5",
        difficulty: 2,
        front: "How does an ideal polariser affect unpolarised light intensity?",
        back: "Transmitted intensity is halved: I = I0/2.",
        examPhrasing: "First ideal polariser gives 50% transmission for unpolarised input.",
        tags: ["intensity", "ideal-polariser"],
      },
      {
        id: "t7-5-f4",
        noteId: "t7-5",
        difficulty: 2,
        front: "State Malus law.",
        back: "I = Imax cos^2 theta for analyser angle theta to polarisation direction.",
        examPhrasing: "Transmitted intensity follows cosine-squared dependence.",
        tags: ["malus-law", "formula"],
      },
      {
        id: "t7-5-f5",
        noteId: "t7-5",
        difficulty: 3,
        front: "What happens for crossed ideal polarisers?",
        back: "No transmission (I = 0) when axes are at 90 degrees.",
        examPhrasing: "Crossed polarisers extinguish ideally plane-polarised light.",
        confusionPair: "crossed vs parallel polarisers",
        tags: ["crossed-polarisers", "intensity"],
      },
      {
        id: "t7-5-f6",
        noteId: "t7-5",
        difficulty: 3,
        front: "Why can inserting a third polariser between crossed polarisers allow transmission?",
        back: "It rotates the transmitted polarisation in stages, so each subsequent projection is non-zero.",
        examPhrasing: "Sequential projections can produce non-zero net transmission.",
        tags: ["three-polariser", "conceptual"],
      },
      {
        id: "t7-5-f7",
        noteId: "t7-5",
        difficulty: 4,
        front: "Give one real-world use of polarisation filters.",
        back: "Reducing reflected glare in sunglasses or enhancing contrast in photography.",
        examPhrasing: "Polaroids preferentially absorb one plane of vibration.",
        tags: ["applications", "filters"],
      },
      {
        id: "t7-5-f8",
        noteId: "t7-5",
        difficulty: 4,
        front: "If analyser angle changes from 0 degrees to 90 degrees, how does intensity change?",
        back: "It decreases from Imax to 0 following I = Imax cos^2 theta.",
        examPhrasing: "Intensity varies as cosine squared with analyser angle.",
        confusionPair: "cos theta vs cos^2 theta dependence",
        tags: ["angle-dependence", "graphs"],
      },
      {
        id: "t7-5-f9",
        noteId: "t7-5",
        difficulty: 5,
        front: "What periodicity does Malus-law intensity show with analyser rotation?",
        back: "Period 180 degrees because cos^2(theta + 180 degrees) = cos^2 theta.",
        examPhrasing: "Intensity repeats every half turn, not full turn.",
        tags: ["periodicity", "malus-law"],
      },
      {
        id: "t7-5-f10",
        noteId: "t7-5",
        difficulty: 5,
        front: "Exam checkpoint for polarisation calculations?",
        back: "Use stage-by-stage intensity flow: halve for first ideal polariser on unpolarised light, then apply Malus law for each analyser angle.",
        examPhrasing: "Most errors come from skipping the initial I0/2 step.",
        tags: ["exam-technique", "calculation-strategy"],
      },
    ],
  },
};
