import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC11_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t11-1": {
    noteId: "t11-1",
    drills: [
      {
        id: "t11-1-d1",
        noteId: "t11-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which statement about alpha radiation is correct?",
        options: [
          { id: "A", text: "It consists of electrons emitted from the nucleus." },
          { id: "B", text: "It consists of two protons and two neutrons." },
          { id: "C", text: "It is a high-energy electromagnetic wave." },
          { id: "D", text: "It has no mass and no charge." },
        ],
        correctOptionId: "B",
        explanation: "An alpha particle is a helium-4 nucleus, containing two protons and two neutrons.",
        distractorRationale: {
          C: "This describes gamma radiation.",
          D: "Alpha particles have significant mass and charge +2e.",
        },
        tags: ["alpha-radiation", "nuclear-model", "definitions"],
      },
      {
        id: "t11-1-d2",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Describe the alpha-particle scattering experiment and explain what the observations suggest about the structure of the atom.",
        modelAnswerPoints: [
          "Fast alpha particles are directed at a thin gold foil and their paths are detected (e.g. by fluorescence on a screen).",
          "Most alpha particles pass through with little deflection, showing most of the atom is empty space.",
          "A small fraction are scattered through large angles, including some back-scattering.",
          "Large-angle scattering requires a massive, positively charged nucleus occupying a very small volume.",
          "Electrons occupy the space outside this nucleus in the nuclear model.",
        ],
        workedSolution: [
          "In the experiment, most alphas travel straight through the foil because they miss the tiny nucleus.",
          "Occasional close approaches to a dense positive nucleus produce strong electrostatic repulsion and large deflections.",
          "The combined evidence rules out a uniform positive charge spread through the atom (plum-pudding model).",
          "Instead, mass and positive charge are concentrated in a small nucleus with electrons at larger distances.",
        ],
        commonMistake:
          "Stating that alpha particles are absorbed by electrons without mentioning the role of the massive nucleus in large-angle scattering.",
        tags: ["rutherford-scattering", "nuclear-model", "experimental-evidence"],
      },
      {
        id: "t11-1-d3",
        noteId: "t11-1",
        kind: "mcq",
        difficulty: 3,
        stem:
          "A nucleus undergoes beta-minus decay. Which change in proton number Z and nucleon number A is correct?",
        options: [
          { id: "A", text: "Z increases by 1, A unchanged" },
          { id: "B", text: "Z decreases by 1, A unchanged" },
          { id: "C", text: "Z unchanged, A decreases by 1" },
          { id: "D", text: "Z decreases by 2, A decreases by 4" },
        ],
        correctOptionId: "A",
        explanation:
          "In beta-minus decay, a neutron changes into a proton, electron, and antineutrino, so Z increases by 1 while A stays constant.",
        distractorRationale: {
          C: "Nucleon number does not change in beta decay.",
          D: "This is associated with alpha emission.",
        },
        tags: ["beta-decay", "nuclear-equations", "proton-number"],
      },
      {
        id: "t11-1-d4",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem:
          "Define isotope and explain why isotopes of the same element have similar chemical properties but different nuclear stability.",
        modelAnswerPoints: [
          "Isotopes are nuclei with the same proton number but different nucleon (mass) number.",
          "Same proton number means same electron arrangement in neutral atoms, giving similar chemical behavior.",
          "Different neutron number changes nuclear forces and stability, so radioactive behavior can differ.",
        ],
        workedSolution: [
          "Start by identifying proton number as the defining feature of element identity.",
          "Link chemistry to electron structure, then link stability to neutron-proton balance.",
          "Conclude that chemical similarity does not imply identical nuclear properties.",
        ],
        commonMistake: "Saying isotopes have different proton numbers.",
        tags: ["isotopes", "atomic-structure", "stability"],
      },
      {
        id: "t11-1-d5",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "The count rate from a source is 420 counts per minute, with a background count rate of 60 counts per minute.\n(a) Determine the net source count rate.\n(b) State why background subtraction is necessary.",
        modelAnswerPoints: [
          "Net count rate = measured count rate - background count rate.",
          "Net count rate = 420 - 60 = 360 counts per minute.",
          "Background radiation contributes counts unrelated to the source.",
          "Subtracting background gives a better estimate of source activity trend.",
        ],
        workedSolution: [
          "Use subtraction before any half-life analysis so data represent the source only.",
          "Quote both raw and net values clearly with units.",
          "Mention random environmental sources as reason for correction.",
        ],
        commonMistake: "Adding background to measured count rate.",
        tags: ["background-radiation", "count-rate", "experimental-technique"],
      },
      {
        id: "t11-1-d6",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A sample has initial activity 1600 Bq. Its half-life is 3.0 h.\nCalculate the activity after 9.0 h.",
        modelAnswerPoints: [
          "Time elapsed corresponds to 9.0 / 3.0 = 3 half-lives.",
          "Activity after 1 half-life: 800 Bq; after 2 half-lives: 400 Bq; after 3 half-lives: 200 Bq.",
          "Equivalent calculation: A = A0 x (1/2)^3.",
          "Final activity is 200 Bq.",
        ],
        workedSolution: [
          "Convert elapsed time into number of half-lives first.",
          "Apply repeated halving or index form consistently.",
          "Keep units in becquerel throughout.",
        ],
        commonMistake: "Dividing by 3 instead of halving three times.",
        tags: ["half-life", "activity-calculation", "radioactivity"],
      },
      {
        id: "t11-1-d7",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Write balanced nuclear equations for the following decays:\n(a) alpha decay of 238U\n(b) beta-minus decay of 14C\n(c) gamma emission from an excited 60Co nucleus.",
        modelAnswerPoints: [
          "Alpha: 238U -> 234Th + 4He (proton and nucleon numbers balanced).",
          "Beta-minus: 14C -> 14N + e- + antineutrino.",
          "Gamma: 60Co* -> 60Co + gamma.",
          "A and Z checks should be consistent in each equation.",
        ],
        workedSolution: [
          "For alpha, reduce A by 4 and Z by 2.",
          "For beta-minus, keep A same and increase Z by 1; include emitted electron.",
          "For gamma, no change in A or Z because only excess nuclear energy is emitted.",
        ],
        commonMistake: "Changing nucleon number during gamma emission.",
        tags: ["nuclear-equations", "alpha-beta-gamma", "symbolic-representation"],
      },
      {
        id: "t11-1-d8",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A detector records net count rate data from a freshly prepared source:\n0 min: 960 counts min^-1\n4 min: 680 counts min^-1\n8 min: 480 counts min^-1\n12 min: 340 counts min^-1\n16 min: 240 counts min^-1\nEstimate the half-life of the source from the data.",
        modelAnswerPoints: [
          "Half of 960 is 480 counts min^-1.",
          "Data show 480 counts min^-1 at 8 min, indicating one half-life of about 8 min.",
          "Check consistency: 960 to about 240 is two half-lives over 16 min.",
          "Estimated half-life is approximately 8 min.",
        ],
        workedSolution: [
          "Identify a pair of values with ratio close to 2:1 to estimate one half-life interval.",
          "Use extra points to validate trend against exponential decay.",
          "State estimate with suitable uncertainty language if needed.",
        ],
        commonMistake: "Assuming linear decrease and averaging differences directly.",
        tags: ["half-life-estimation", "data-interpretation", "experimental-physics"],
      },
      {
        id: "t11-1-d9",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Compare alpha, beta and gamma radiations in terms of ionising ability, penetrating power and behavior in electric/magnetic fields.",
        modelAnswerPoints: [
          "Alpha is most strongly ionising but least penetrating; stopped by paper or a few cm of air.",
          "Beta has intermediate ionisation and penetration; typically stopped by a few mm of aluminium.",
          "Gamma is weakly ionising but highly penetrating; reduced by thick lead/concrete.",
          "Alpha and beta are deflected in opposite directions in fields due to opposite charges; gamma is undeflected.",
        ],
        workedSolution: [
          "Present each radiation type side-by-side for direct comparison.",
          "Link ionisation trend to particle charge/mass and energy loss per unit path.",
          "Mention field deflection as key evidence for charge nature.",
        ],
        commonMistake: "Stating gamma is not ionising at all.",
        tags: ["radiation-properties", "ionisation", "penetration"],
      },
      {
        id: "t11-1-d10",
        noteId: "t11-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A school stores a beta source for routine demonstrations. Propose a safety protocol covering handling, shielding, storage, monitoring and waste/disposal principles.",
        modelAnswerPoints: [
          "Apply time-distance-shielding principles: minimize exposure time and maximize distance using tongs.",
          "Use appropriate shielding (e.g., plastic/aluminium for beta) and avoid high-Z shielding that increases bremsstrahlung unnecessarily.",
          "Store source in labeled, secure lead-lined or approved container when not in use.",
          "Monitor with detector before/after use and keep exposure records.",
          "Follow local radiation regulations for trained personnel, controlled areas, and disposal via licensed routes.",
        ],
        workedSolution: [
          "Frame protocol around practical lab workflow: preparation, use, and post-use checks.",
          "Include reasoned shielding choice specific to beta radiation.",
          "Demonstrate awareness of legal compliance and dose management culture.",
        ],
        commonMistake: "Assuming one shielding strategy suits all radiation types.",
        tags: ["radiation-safety", "risk-control", "applied-physics"],
      },
    ],
    flashcards: [
      {
        id: "t11-1-f1",
        noteId: "t11-1",
        difficulty: 1,
        front: "What is an isotope?",
        back: "Nuclei with the same proton number but different nucleon number.",
        examPhrasing: "Isotopes of an element share Z but differ in neutron count and hence A.",
        tags: ["isotopes", "definitions"],
      },
      {
        id: "t11-1-f2",
        noteId: "t11-1",
        difficulty: 1,
        front: "What does 1 becquerel (Bq) mean?",
        back: "One decay per second.",
        examPhrasing: "Activity is measured in Bq, where 1 Bq = 1 s^-1.",
        tags: ["activity", "units"],
      },
      {
        id: "t11-1-f3",
        noteId: "t11-1",
        difficulty: 2,
        front: "State the composition and charge of an alpha particle.",
        back: "Two protons and two neutrons, charge +2e.",
        examPhrasing: "Alpha radiation is emission of a helium nucleus (4He2+).",
        tags: ["alpha-radiation", "particle-properties"],
      },
      {
        id: "t11-1-f4",
        noteId: "t11-1",
        difficulty: 2,
        front: "How do Z and A change in beta-minus decay?",
        back: "Z increases by 1, A remains unchanged.",
        examPhrasing: "A neutron converts to proton, emitting an electron and antineutrino.",
        confusionPair: "beta-minus vs beta-plus changes in proton number",
        tags: ["beta-decay", "nuclear-numbers"],
      },
      {
        id: "t11-1-f5",
        noteId: "t11-1",
        difficulty: 3,
        front: "Why is background count rate subtracted in experiments?",
        back: "To isolate counts from the source by removing environmental and cosmic contributions.",
        examPhrasing: "Corrected count rate = measured count rate - background count rate.",
        tags: ["background-radiation", "measurement"],
      },
      {
        id: "t11-1-f6",
        noteId: "t11-1",
        difficulty: 3,
        front: "Define half-life.",
        back: "The time taken for activity (or number of undecayed nuclei) to fall to half its value.",
        examPhrasing: "Half-life is constant for a given nuclide and independent of external conditions.",
        tags: ["half-life", "radioactive-decay"],
      },
      {
        id: "t11-1-f7",
        noteId: "t11-1",
        difficulty: 4,
        front: "How does gamma emission affect proton and nucleon numbers?",
        back: "Neither changes; only nuclear energy decreases.",
        examPhrasing: "Gamma emission is de-excitation of a nucleus without changing Z or A.",
        confusionPair: "gamma emission vs particle emission",
        tags: ["gamma-radiation", "nuclear-transitions"],
      },
      {
        id: "t11-1-f8",
        noteId: "t11-1",
        difficulty: 4,
        front: "Rank alpha, beta, gamma by ionising power.",
        back: "Alpha highest, beta intermediate, gamma lowest.",
        examPhrasing: "Ionising ability generally inversely correlates with penetration for these radiations.",
        tags: ["ionisation", "comparison"],
      },
      {
        id: "t11-1-f9",
        noteId: "t11-1",
        difficulty: 5,
        front: "What is the core reason radioactive decay is described as random?",
        back: "Individual nuclei decay unpredictably, but large samples show predictable statistical behavior.",
        examPhrasing: "Decay probability per unit time is constant for each nucleus in a given nuclide.",
        tags: ["randomness", "statistical-physics"],
      },
      {
        id: "t11-1-f10",
        noteId: "t11-1",
        difficulty: 5,
        front: "State three practical dose-reduction principles in radiation work.",
        back: "Minimize time, maximize distance, and use suitable shielding.",
        examPhrasing: "ALARA-style control is implemented through time-distance-shielding strategy.",
        tags: ["radiation-safety", "exam-application"],
      },
    ],
  },
  "t11-2": {
    noteId: "t11-2",
    drills: [
      {
        id: "t11-2-d1",
        noteId: "t11-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which particle is a lepton?",
        options: [
          { id: "A", text: "Proton" },
          { id: "B", text: "Neutron" },
          { id: "C", text: "Electron" },
          { id: "D", text: "Pion" },
        ],
        correctOptionId: "C",
        explanation: "Electrons are leptons; protons and neutrons are baryons made of quarks.",
        distractorRationale: {
          B: "Neutrons are baryons, not leptons.",
          D: "Pions are mesons.",
        },
        tags: ["leptons", "particle-classification", "standard-model-basics"],
      },
      {
        id: "t11-2-d2",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "In beta-minus decay a neutron becomes a proton, and in beta-plus decay a proton becomes a neutron.\nFor each process, state how the quark composition of the nucleon changes.",
        modelAnswerPoints: [
          "Beta-minus: one down quark changes to an up quark inside the nucleon (udd to uud overall for neutron to proton).",
          "Beta-plus: one up quark changes to a down quark (uud to udd overall for proton to neutron).",
          "Emitted lepton and antilepton/neutrino conserve lepton number; quark change accounts for nucleon identity change.",
          "Charge of nucleon increases by +e in beta-minus and decreases by +e in beta-plus, consistent with d to u and u to d respectively.",
        ],
        workedSolution: [
          "Beta-minus converts n (udd) to p (uud) by d to u, raising nucleon charge from 0 to +1e.",
          "Beta-plus converts p (uud) to n (udd) by u to d, lowering nucleon charge from +1e to 0.",
          "The weak interaction changes quark flavour; the emitted e- and antineutrino (or e+ and neutrino) carry the remaining quantum numbers.",
        ],
        commonMistake:
          "Describing beta decay as emission of a quark from the nucleus rather than a flavour change within a nucleon.",
        tags: ["beta-decay", "quark-flavour", "nucleon-composition"],
      },
      {
        id: "t11-2-d3",
        noteId: "t11-2",
        kind: "mcq",
        difficulty: 3,
        stem: "In electron-positron annihilation at low initial kinetic energy, the typical final products are",
        options: [
          { id: "A", text: "a proton and an antiproton" },
          { id: "B", text: "one gamma photon only" },
          { id: "C", text: "two gamma photons" },
          { id: "D", text: "a neutron and an antineutron" },
        ],
        correctOptionId: "C",
        explanation:
          "Two photons are produced to conserve both energy and momentum when the pair annihilates near rest.",
        distractorRationale: {
          B: "Single-photon outcome cannot satisfy momentum conservation in this context.",
          D: "This pair requires much higher energy than electron rest-mass annihilation releases.",
        },
        tags: ["antimatter", "annihilation", "conservation-laws"],
      },
      {
        id: "t11-2-d4",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Distinguish between hadrons, baryons and mesons, with one example of each.",
        modelAnswerPoints: [
          "Hadrons are particles that experience the strong interaction.",
          "Baryons are hadrons made of three quarks (e.g., proton or neutron).",
          "Mesons are hadrons made of a quark-antiquark pair (e.g., pion).",
        ],
        workedSolution: [
          "Use category structure clearly: hadrons split into baryons and mesons.",
          "Attach a concrete example to each to secure application marks.",
        ],
        commonMistake: "Calling electrons hadrons.",
        tags: ["hadrons", "baryons", "mesons"],
      },
      {
        id: "t11-2-d5",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Using quark charges (+2/3e for up, -1/3e for down), calculate the charges of\n(a) proton (uud)\n(b) neutron (udd).",
        modelAnswerPoints: [
          "Proton charge: +2/3 +2/3 -1/3 = +1 (in units of e).",
          "So proton has charge +e.",
          "Neutron charge: +2/3 -1/3 -1/3 = 0.",
          "So neutron is neutral.",
        ],
        workedSolution: [
          "Add fractional quark charges algebraically.",
          "Express final answers in units of elementary charge e.",
          "Check proton/neutron results match known macroscopic charges.",
        ],
        commonMistake: "Assigning +1e to each up quark.",
        tags: ["quark-charge", "calculation", "nucleons"],
      },
      {
        id: "t11-2-d6",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "State the lepton number before and after beta-minus decay and show that lepton number is conserved.",
        modelAnswerPoints: [
          "Initial nucleus has lepton number 0 from nuclear constituents.",
          "Beta-minus decay emits an electron (lepton number +1) and an electron antineutrino (lepton number -1).",
          "Total lepton number after decay is +1 + (-1) = 0.",
          "Lepton number is therefore conserved.",
        ],
        workedSolution: [
          "Track leptons separately from baryons.",
          "Use sign convention for particle and antiparticle lepton numbers.",
          "Conclude with explicit conservation statement.",
        ],
        commonMistake: "Forgetting the antineutrino term.",
        tags: ["lepton-number", "beta-decay", "conservation-laws"],
      },
      {
        id: "t11-2-d7",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Explain what is meant by antimatter and compare pair production with annihilation, including one conservation law common to both.",
        modelAnswerPoints: [
          "Antimatter particles have same mass as corresponding matter particles but opposite charge and opposite relevant quantum numbers.",
          "Pair production converts energy (typically a gamma photon near nucleus) into particle-antiparticle pair.",
          "Annihilation is reverse: particle and antiparticle convert mass-energy into photons/other particles.",
          "Both processes obey conservation laws such as charge conservation and energy-momentum conservation.",
        ],
        workedSolution: [
          "Define antimatter first in terms of particle properties.",
          "Present pair production and annihilation as inverse transformations.",
          "Name at least one law that must hold in both directions.",
        ],
        commonMistake: "Claiming antimatter has negative mass.",
        tags: ["antimatter", "pair-production", "annihilation"],
      },
      {
        id: "t11-2-d8",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A gamma photon of energy 2.4 MeV produces an electron-positron pair near a nucleus.\n(a) Show that pair production is energetically possible.\n(b) Calculate the total kinetic energy shared by the pair.\nTake electron rest-mass energy = 0.511 MeV.",
        modelAnswerPoints: [
          "Minimum required rest energy for pair: 2 x 0.511 = 1.022 MeV.",
          "Since 2.4 MeV > 1.022 MeV, pair production is possible.",
          "Total kinetic energy of pair = 2.4 - 1.022 = 1.378 MeV.",
          "Nucleus is needed to assist momentum conservation.",
        ],
        workedSolution: [
          "Compare photon energy with threshold rest-mass energy first.",
          "Subtract rest-energy requirement from photon energy for kinetic remainder.",
          "Include momentum-conservation role of nearby nucleus for full-credit explanation.",
        ],
        commonMistake: "Using only one electron rest-mass energy at threshold.",
        tags: ["pair-production", "rest-energy", "threshold-calculation"],
      },
      {
        id: "t11-2-d9",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Classify the following particles and state one interaction they do or do not experience:\nproton, neutron, pion, electron, electron neutrino.",
        modelAnswerPoints: [
          "Proton and neutron: baryons (hadrons), so they experience strong interaction.",
          "Pion: meson (hadron), also experiences strong interaction.",
          "Electron and electron neutrino: leptons, do not experience strong interaction.",
          "Electron interacts electromagnetically; neutrino has no electric charge and interacts via weak interaction.",
        ],
        workedSolution: [
          "Group by hadron/lepton first, then refine hadrons into baryon/meson.",
          "Attach one interaction statement to each class for contrast.",
          "Highlight neutrino as weak-interaction lepton with no EM interaction.",
        ],
        commonMistake: "Classifying neutrinos as hadrons because they come from nuclei.",
        tags: ["classification", "interactions", "standard-model"],
      },
      {
        id: "t11-2-d10",
        noteId: "t11-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "An isolated interaction is proposed:\nproton + electron -> neutron + electron neutrino\nEvaluate whether charge, baryon number and lepton number are conserved, and comment on physical plausibility.",
        modelAnswerPoints: [
          "Charge: initial +1 + (-1) = 0; final neutron 0 and neutrino 0, so charge conserved.",
          "Baryon number: initial proton gives +1, electron 0; final neutron +1 and neutrino 0, so conserved.",
          "Lepton number: initial electron +1; final neutrino +1, so conserved.",
          "Process can be interpreted as electron capture-type weak interaction under suitable nuclear context, though a free proton-electron system requires specific conditions.",
        ],
        workedSolution: [
          "Compute each conserved quantity independently to avoid mixing signs.",
          "State conservation verdict clearly for each law.",
          "Finish by distinguishing algebraic conservation from whether reaction is likely in free space vs bound nuclear environment.",
        ],
        commonMistake: "Assigning baryon number to electrons or neutrinos.",
        tags: ["conservation-laws", "baryon-number", "lepton-number"],
      },
    ],
    flashcards: [
      {
        id: "t11-2-f1",
        noteId: "t11-2",
        difficulty: 1,
        front: "What is a hadron?",
        back: "A particle made of quarks that experiences the strong interaction.",
        examPhrasing: "Hadrons are divided into baryons and mesons.",
        tags: ["hadrons", "definitions"],
      },
      {
        id: "t11-2-f2",
        noteId: "t11-2",
        difficulty: 1,
        front: "Give quark composition of proton and neutron.",
        back: "Proton: uud. Neutron: udd.",
        examPhrasing: "Use quark charges to verify proton +1e and neutron 0e.",
        tags: ["quarks", "nucleons"],
      },
      {
        id: "t11-2-f3",
        noteId: "t11-2",
        difficulty: 2,
        front: "How are baryons and mesons different?",
        back: "Baryons contain three quarks; mesons contain quark-antiquark pairs.",
        examPhrasing: "Both are hadrons and so participate in strong interaction.",
        tags: ["baryons", "mesons"],
      },
      {
        id: "t11-2-f4",
        noteId: "t11-2",
        difficulty: 2,
        front: "What defines a lepton in this syllabus context?",
        back: "A fundamental particle that does not experience strong interaction, e.g., electron or neutrino.",
        examPhrasing: "Leptons carry lepton number; corresponding antiparticles carry opposite lepton number.",
        tags: ["leptons", "classification"],
      },
      {
        id: "t11-2-f5",
        noteId: "t11-2",
        difficulty: 3,
        front: "State baryon number values for baryons, antibaryons and leptons.",
        back: "Baryons: +1, antibaryons: -1, leptons and photons: 0.",
        examPhrasing: "Baryon number is conserved in all observed reactions.",
        tags: ["baryon-number", "conservation"],
      },
      {
        id: "t11-2-f6",
        noteId: "t11-2",
        difficulty: 3,
        front: "What happens in pair production?",
        back: "Energy converts into a particle-antiparticle pair, commonly e- and e+.",
        examPhrasing: "A nearby nucleus is usually required for momentum conservation.",
        confusionPair: "pair production vs radioactive decay",
        tags: ["pair-production", "energy-conversion"],
      },
      {
        id: "t11-2-f7",
        noteId: "t11-2",
        difficulty: 4,
        front: "What happens in annihilation of an electron and positron?",
        back: "They convert their mass and kinetic energy into photons, often two gamma photons.",
        examPhrasing: "Two-photon production near rest satisfies momentum conservation.",
        tags: ["annihilation", "antimatter"],
      },
      {
        id: "t11-2-f8",
        noteId: "t11-2",
        difficulty: 4,
        front: "Why is an antineutrino emitted in beta-minus decay?",
        back: "To conserve lepton number, energy, and momentum in the decay process.",
        examPhrasing: "Including neutrino/antineutrino resolves apparent conservation-law gaps.",
        tags: ["beta-decay", "neutrinos", "conservation-laws"],
      },
      {
        id: "t11-2-f9",
        noteId: "t11-2",
        difficulty: 5,
        front: "What is the minimum gamma-photon energy for e- e+ pair production?",
        back: "At least 1.022 MeV, equal to twice electron rest-mass energy.",
        examPhrasing: "Any excess above 1.022 MeV appears as kinetic energy of products.",
        tags: ["threshold-energy", "rest-mass-energy"],
      },
      {
        id: "t11-2-f10",
        noteId: "t11-2",
        difficulty: 5,
        front: "Exam strategy: how do you test if a proposed particle reaction is valid?",
        back: "Check conservation of charge, baryon number, lepton number, and energy-momentum systematically.",
        examPhrasing: "A valid equation must satisfy all relevant conservation laws simultaneously.",
        tags: ["exam-technique", "reaction-checking"],
      },
    ],
  },
};
