import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC24_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t24-1": {
    noteId: "t24-1",
    drills: [
      {
        id: "t24-1-d1",
        noteId: "t24-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Ultrasound used for medical imaging is sound with frequency",
        options: [
          { id: "A", text: "below 20 Hz" },
          { id: "B", text: "between 20 Hz and 20 kHz" },
          { id: "C", text: "above 20 kHz" },
          { id: "D", text: "above 20 MHz only" },
        ],
        correctOptionId: "C",
        explanation: "Ultrasound is defined as sound waves with frequencies above human hearing (20 kHz).",
        distractorRationale: {
          B: "This is the approximate audible range for humans.",
          C: "Correct definition of ultrasound.",
          D: "Diagnostic ultrasound often uses MHz frequencies, but the definition is above 20 kHz.",
        },
        tags: ["ultrasound", "definition", "frequency"],
      },
      {
        id: "t24-1-d2",
        noteId: "t24-1",
        kind: "mcq",
        difficulty: 2,
        stem: "What is the main role of coupling gel in ultrasound scanning?",
        options: [
          { id: "A", text: "To cool the transducer electrically" },
          { id: "B", text: "To eliminate air gaps and improve transmission" },
          { id: "C", text: "To increase X-ray absorption in tissue" },
          { id: "D", text: "To reduce blood flow speed" },
        ],
        correctOptionId: "B",
        explanation: "Gel removes air between probe and skin. Air causes large reflection because of acoustic-impedance mismatch.",
        distractorRationale: {
          B: "Correct: transmission improves when air gaps are removed.",
          C: "X-ray absorption is unrelated to ultrasound gel.",
          D: "Gel has no physiological flow-control purpose.",
        },
        tags: ["acoustic-impedance", "coupling-gel", "image-quality"],
      },
      {
        id: "t24-1-d3",
        noteId: "t24-1",
        kind: "mcq",
        difficulty: 3,
        stem:
          "In pulse-echo ultrasound, an echo is received 130 microseconds after emission. If sound speed in tissue is 1540 m s^-1, the reflector depth is",
        options: [
          { id: "A", text: "0.050 m" },
          { id: "B", text: "0.100 m" },
          { id: "C", text: "0.200 m" },
          { id: "D", text: "0.400 m" },
        ],
        correctOptionId: "B",
        explanation:
          "Depth = vt/2 = 1540 x 130 x 10^-6 / 2 = 0.100 m. Divide by 2 because time includes outward and return paths.",
        distractorRationale: {
          B: "Correct use of pulse-echo distance relation.",
          C: "This comes from forgetting to divide by 2.",
          D: "This includes both a missing divide-by-2 and arithmetic slip.",
        },
        tags: ["pulse-echo", "time-of-flight", "calculations"],
      },
      {
        id: "t24-1-d4",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State two advantages and one limitation of ultrasound imaging in medicine.",
        modelAnswerPoints: [
          "Advantages include non-ionising radiation and real-time imaging.",
          "It is relatively safe for fetal monitoring and soft-tissue observation.",
          "Limitation: poor penetration through bone / poor imaging through gas-filled regions.",
        ],
        workedSolution: [
          "Name clear practical advantages, not generic statements such as 'it is better'.",
          "Give one explicit limitation linked to wave behavior in different media.",
        ],
        commonMistake: "Claiming ultrasound gives the highest image resolution of all modalities in all tissues.",
        tags: ["benefits", "limitations", "medical-imaging"],
      },
      {
        id: "t24-1-d5",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "An ultrasound pulse reflects from a tissue boundary. The time between transmission and reception is 78 microseconds.\nAssume speed in tissue = 1500 m s^-1.\nCalculate the boundary depth.",
        modelAnswerPoints: [
          "Use depth = vt/2.",
          "Depth = 1500 x 78 x 10^-6 / 2.",
          "Depth = 5.85 x 10^-2 m.",
          "Depth is about 5.9 cm.",
        ],
        workedSolution: [
          "Convert microseconds to seconds before substitution.",
          "Halve the total path length because reflection is a round-trip.",
          "State final answer with unit and suitable significant figures.",
        ],
        commonMistake: "Using t = 78 s or omitting the factor of 10^-6.",
        tags: ["numerical", "pulse-echo", "units"],
      },
      {
        id: "t24-1-d6",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Explain why ultrasound is strongly reflected at an air-tissue boundary but transmits better between similar soft tissues.",
        modelAnswerPoints: [
          "Reflection depends on acoustic-impedance mismatch at the boundary.",
          "Air and tissue have very different acoustic impedances, giving large reflection.",
          "Similar soft tissues have closer impedances, so less reflection and more transmission.",
          "This is why gel improves probe-skin coupling by removing air.",
        ],
        workedSolution: [
          "Use the term acoustic impedance and compare both boundary cases.",
          "Link concept directly to practical scanning setup for full explanation marks.",
        ],
        commonMistake: "Attributing reflection differences only to wave frequency without impedance discussion.",
        tags: ["acoustic-impedance", "boundaries", "conceptual"],
      },
      {
        id: "t24-1-d7",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Describe how the Doppler ultrasound method can be used to measure blood-flow speed and direction.",
        modelAnswerPoints: [
          "Moving red blood cells reflect ultrasound with a frequency shift (Doppler effect).",
          "If cells move towards probe, received frequency increases; away from probe, it decreases.",
          "Magnitude of frequency shift is related to component of blood velocity along beam direction.",
          "Measured shift is processed to estimate flow speed and direction.",
        ],
        workedSolution: [
          "Separate sign (direction) and magnitude (speed) interpretation of frequency shift.",
          "Mention that the measured component is along the ultrasound beam.",
          "Use clear terminology: transmitted frequency, reflected frequency, frequency shift.",
        ],
        commonMistake: "Saying Doppler shift depends only on blood pressure and not velocity.",
        tags: ["doppler", "blood-flow", "frequency-shift"],
      },
      {
        id: "t24-1-d8",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A transducer emits ultrasound at 4.0 MHz.\nA reflected wave from blood cells is detected at 4.0006 MHz.\n(a) State whether blood is moving towards or away from the transducer.\n(b) Calculate the frequency shift.\n(c) Suggest one factor that can cause uncertainty in speed estimation.",
        modelAnswerPoints: [
          "Detected frequency is higher, so blood is moving towards the transducer.",
          "Frequency shift = 4.0006 MHz - 4.0 MHz = 0.0006 MHz = 600 Hz.",
          "Uncertainty source: unknown beam-angle alignment with flow direction / signal noise / tissue motion.",
          "Only velocity component along beam is measured, which affects inferred true speed.",
        ],
        workedSolution: [
          "Read sign of shift first to infer direction.",
          "Convert MHz difference carefully into Hz.",
          "For part (c), explain why geometry or noise propagates into velocity uncertainty.",
        ],
        commonMistake: "Reporting shift as 0.6 Hz instead of 600 Hz.",
        tags: ["doppler-calculation", "measurement-uncertainty", "data-interpretation"],
      },
      {
        id: "t24-1-d9",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Compare A-scan and B-scan ultrasound output and state one clinical context where each is useful.",
        modelAnswerPoints: [
          "A-scan displays echo amplitude against time/depth as a one-dimensional trace.",
          "B-scan converts echo intensities into brightness to form a two-dimensional cross-sectional image.",
          "A-scan can be used for distance/thickness measurements (e.g., eye dimensions).",
          "B-scan is widely used for fetal or abdominal imaging.",
        ],
        workedSolution: [
          "State display format differences clearly before giving examples.",
          "Choose contexts that match each mode's strengths (measurement vs imaging).",
        ],
        commonMistake: "Describing both scans as identical except for probe size.",
        tags: ["a-scan", "b-scan", "applications"],
      },
      {
        id: "t24-1-d10",
        noteId: "t24-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A pulse-echo system records echoes from two boundaries at 40 microseconds and 92 microseconds after transmission.\nAssume sound speed in tissue is 1540 m s^-1.\n(a) Find each boundary depth.\n(b) Find thickness of the tissue layer between the boundaries.\n(c) Explain one practical reason why this method can be less reliable near bone.",
        modelAnswerPoints: [
          "Depth1 = 1540 x 40 x 10^-6 / 2 = 3.08 x 10^-2 m.",
          "Depth2 = 1540 x 92 x 10^-6 / 2 = 7.08 x 10^-2 m.",
          "Layer thickness = depth2 - depth1 = 4.00 x 10^-2 m (4.0 cm).",
          "Near bone, strong reflection/attenuation reduces transmitted signal and can obscure deeper echoes.",
        ],
        workedSolution: [
          "Compute two round-trip depths separately before subtraction.",
          "Retain consistent units to avoid cm/m mixing in the final difference.",
          "Link reliability issue to wave interaction with high-impedance boundaries such as bone.",
        ],
        commonMistake: "Subtracting times first and then forgetting divide-by-2 in thickness calculation.",
        tags: ["multi-echo", "layer-thickness", "limitations"],
      },
    ],
    flashcards: [
      {
        id: "t24-1-f1",
        noteId: "t24-1",
        difficulty: 1,
        front: "Define ultrasound.",
        back: "Sound with frequency greater than 20 kHz.",
        examPhrasing: "Ultrasound is beyond the upper limit of normal human hearing.",
        tags: ["definition", "frequency"],
      },
      {
        id: "t24-1-f2",
        noteId: "t24-1",
        difficulty: 1,
        front: "Why is coupling gel used in ultrasound scanning?",
        back: "To remove air gaps and improve transmission from probe to skin.",
        examPhrasing: "Gel reduces reflection losses due to acoustic-impedance mismatch at air interfaces.",
        tags: ["coupling-gel", "acoustic-impedance"],
      },
      {
        id: "t24-1-f3",
        noteId: "t24-1",
        difficulty: 2,
        front: "State the pulse-echo depth formula.",
        back: "Depth = vt/2, where t is round-trip echo time.",
        examPhrasing: "The factor 1/2 accounts for outward and return travel paths.",
        tags: ["formula", "pulse-echo"],
      },
      {
        id: "t24-1-f4",
        noteId: "t24-1",
        difficulty: 2,
        front: "What determines reflected intensity at a boundary in ultrasound?",
        back: "Difference in acoustic impedance between the two media.",
        examPhrasing: "Larger impedance mismatch gives stronger reflection.",
        tags: ["reflection", "impedance"],
      },
      {
        id: "t24-1-f5",
        noteId: "t24-1",
        difficulty: 3,
        front: "How does Doppler ultrasound indicate flow direction?",
        back: "Frequency increase means motion towards probe; decrease means motion away.",
        examPhrasing: "The sign of Doppler shift gives direction of velocity component along beam.",
        confusionPair: "Direction from shift sign vs speed from shift magnitude",
        tags: ["doppler", "flow-direction"],
      },
      {
        id: "t24-1-f6",
        noteId: "t24-1",
        difficulty: 3,
        front: "State one major safety advantage of ultrasound over X-rays.",
        back: "Ultrasound is non-ionising, reducing risk of ionisation-related tissue damage.",
        examPhrasing: "Diagnostic ultrasound does not ionise atoms in tissue.",
        tags: ["safety", "non-ionising"],
      },
      {
        id: "t24-1-f7",
        noteId: "t24-1",
        difficulty: 4,
        front: "How does A-scan differ from B-scan?",
        back: "A-scan gives 1D amplitude-depth trace; B-scan gives 2D brightness image.",
        examPhrasing: "B-scan maps echo intensity to pixel brightness for sectional imaging.",
        tags: ["a-scan", "b-scan"],
      },
      {
        id: "t24-1-f8",
        noteId: "t24-1",
        difficulty: 4,
        front: "Why are gas-filled organs hard to image with ultrasound?",
        back: "Air causes strong reflection/scattering, limiting penetration and image clarity.",
        examPhrasing: "Large impedance mismatch at gas-tissue boundaries degrades useful transmitted signal.",
        tags: ["limitations", "gas-boundary"],
      },
      {
        id: "t24-1-f9",
        noteId: "t24-1",
        difficulty: 5,
        front: "What geometry factor commonly biases Doppler speed estimates?",
        back: "Angle between ultrasound beam and true flow direction.",
        examPhrasing: "Doppler measures only the velocity component parallel to the beam.",
        tags: ["measurement", "uncertainty"],
      },
      {
        id: "t24-1-f10",
        noteId: "t24-1",
        difficulty: 5,
        front: "Exam checklist for pulse-echo depth questions?",
        back: "Convert units, use depth = vt/2, keep significant figures sensible, and state medium wave speed used.",
        examPhrasing: "Method marks reward correct round-trip interpretation and consistent units.",
        tags: ["exam-technique", "calculations"],
      },
    ],
  },
  "t24-2": {
    noteId: "t24-2",
    drills: [
      {
        id: "t24-2-d1",
        noteId: "t24-2",
        kind: "mcq",
        difficulty: 1,
        stem: "X-rays are best described as",
        options: [
          { id: "A", text: "longitudinal sound waves" },
          { id: "B", text: "high-frequency electromagnetic waves" },
          { id: "C", text: "streams of alpha particles" },
          { id: "D", text: "visible light with lower energy" },
        ],
        correctOptionId: "B",
        explanation: "X-rays are electromagnetic waves with very short wavelength and high photon energy.",
        distractorRationale: {
          B: "Correct wave type and frequency description.",
          C: "Alpha particles are nuclei, not photons.",
          D: "X-rays have much higher energy than visible light.",
        },
        tags: ["x-rays", "electromagnetic-spectrum", "definition"],
      },
      {
        id: "t24-2-d2",
        noteId: "t24-2",
        kind: "mcq",
        difficulty: 2,
        stem: "In an X-ray tube, increasing accelerating potential mainly increases",
        options: [
          { id: "A", text: "maximum photon energy" },
          { id: "B", text: "filament lifetime only" },
          { id: "C", text: "number of neutrons emitted" },
          { id: "D", text: "half-life of the target material" },
        ],
        correctOptionId: "A",
        explanation: "Higher tube voltage gives electrons more kinetic energy, raising possible maximum X-ray photon energy.",
        distractorRationale: {
          B: "Filament life is not the main directly controlled imaging variable.",
          C: "X-ray tubes do not operate by neutron emission.",
          D: "Target half-life is irrelevant here.",
        },
        tags: ["x-ray-tube", "accelerating-potential", "photon-energy"],
      },
      {
        id: "t24-2-d3",
        noteId: "t24-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Which tissue generally appears whiter on a radiograph?",
        options: [
          { id: "A", text: "Lung tissue (air-rich)" },
          { id: "B", text: "Soft muscle tissue" },
          { id: "C", text: "Adipose tissue" },
          { id: "D", text: "Bone" },
        ],
        correctOptionId: "D",
        explanation: "Bone attenuates X-rays strongly, so fewer photons reach detector and the region appears lighter.",
        distractorRationale: {
          B: "Soft tissue has moderate attenuation and appears grey.",
          C: "Fat attenuates less than bone.",
          D: "Correct: strong attenuation by high-density, higher-Z tissue.",
        },
        tags: ["attenuation", "image-contrast", "radiograph"],
      },
      {
        id: "t24-2-d4",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State how X-rays are produced in a medical X-ray tube.",
        modelAnswerPoints: [
          "Electrons are emitted from a heated cathode (thermionic emission).",
          "They are accelerated through a high potential difference towards a metal anode target.",
          "Rapid deceleration/inner-shell interactions in target produce X-ray photons.",
        ],
        workedSolution: [
          "Mention both electron acceleration and interaction at target.",
          "Credit is gained for clear sequence from cathode to X-ray emission.",
        ],
        commonMistake: "Saying X-rays come from heating the target directly without electron acceleration.",
        tags: ["x-ray-production", "tube-components", "core-process"],
      },
      {
        id: "t24-2-d5",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "An X-ray photon has wavelength 2.5 x 10^-11 m.\nCalculate its energy.\nUse h = 6.63 x 10^-34 J s and c = 3.00 x 10^8 m s^-1.",
        modelAnswerPoints: [
          "Use E = hc/lambda.",
          "E = (6.63 x 10^-34 x 3.00 x 10^8)/(2.5 x 10^-11).",
          "E = 7.96 x 10^-15 J.",
          "Equivalent to about 49.7 keV.",
        ],
        workedSolution: [
          "Substitute values in SI units and keep powers of ten explicit.",
          "Optional conversion to eV gives clinically familiar energy scale.",
        ],
        commonMistake: "Using E = hf but substituting wavelength value for f directly.",
        tags: ["photon-energy", "wavelength", "calculation"],
      },
      {
        id: "t24-2-d6",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Explain why lead is commonly used for shielding in X-ray rooms and protective aprons.",
        modelAnswerPoints: [
          "Lead has high atomic number and high density.",
          "These properties increase probability of X-ray absorption/attenuation.",
          "So transmission through shielding is reduced significantly.",
          "This lowers dose to staff and surrounding tissues.",
        ],
        workedSolution: [
          "State physical properties first, then connect to attenuation outcome.",
          "Conclude with radiation-protection purpose in terms of dose reduction.",
        ],
        commonMistake: "Claiming lead 'reflects' X-rays like a mirror.",
        tags: ["radiation-protection", "lead-shielding", "attenuation"],
      },
      {
        id: "t24-2-d7",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "A beam intensity falls to 32% of its initial value after passing through 4.0 cm of tissue.\nAssume exponential attenuation I = I0 e^(-mu x).\n(a) Determine mu.\n(b) State unit of mu.",
        modelAnswerPoints: [
          "I/I0 = 0.32 = e^(-mu x).",
          "mu = -ln(0.32)/0.040.",
          "mu = 28.5 m^-1 (approximately).",
          "Unit of attenuation coefficient is m^-1.",
        ],
        workedSolution: [
          "Convert 4.0 cm to 0.040 m before substitution.",
          "Take natural logarithm to isolate mu from exponential form.",
          "Quote value and unit explicitly.",
        ],
        commonMistake: "Using log base 10 without adjusting or keeping x in cm.",
        tags: ["attenuation-law", "exponential", "units"],
      },
      {
        id: "t24-2-d8",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Describe two ways image contrast in X-ray imaging can be improved and explain the physics behind each.",
        modelAnswerPoints: [
          "Use contrast media (e.g., iodine or barium) to increase attenuation differences in selected regions.",
          "Higher-Z contrast agents absorb more X-rays, making target structures more distinguishable.",
          "Adjust tube voltage: lower kVp can increase differential attenuation between tissues.",
          "Digital post-processing/windowing can enhance visible contrast without altering original exposure.",
        ],
        workedSolution: [
          "Provide one acquisition-based method and one material or processing method.",
          "For each method, tie improvement to attenuation/energy dependence or signal handling.",
        ],
        commonMistake: "Saying only 'increase intensity' without explaining contrast mechanism.",
        tags: ["contrast", "imaging-optimization", "clinical-technique"],
      },
      {
        id: "t24-2-d9",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A patient receives an absorbed dose of 2.0 mGy from an X-ray examination.\n(a) Convert this to Gy.\n(b) If 0.15 kg of tissue is irradiated uniformly, calculate energy absorbed.\n(c) State one reason dose should be kept as low as practical.",
        modelAnswerPoints: [
          "2.0 mGy = 2.0 x 10^-3 Gy.",
          "Dose D = E/m, so E = Dm.",
          "E = 2.0 x 10^-3 x 0.15 = 3.0 x 10^-4 J.",
          "Dose minimization reduces probability of ionisation-related biological damage.",
        ],
        workedSolution: [
          "Start with unit conversion from mGy to Gy.",
          "Apply definition of absorbed dose directly with correct mass.",
          "Conclude with ALARA-style safety reasoning.",
        ],
        commonMistake: "Using E = D/m instead of E = Dm.",
        tags: ["dose", "unit-conversion", "radiation-safety"],
      },
      {
        id: "t24-2-d10",
        noteId: "t24-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Evaluate trade-offs when selecting X-ray exposure settings for chest imaging.\nYour answer should include at least: image quality, patient dose, and one equipment/technique factor.",
        modelAnswerPoints: [
          "Higher exposure can improve signal and reduce quantum noise, but increases patient dose.",
          "Very low exposure reduces dose but may produce noisy images and diagnostic uncertainty.",
          "Tube voltage/current-time settings influence both penetration and detector signal.",
          "Collimation and filtration help reduce unnecessary tissue irradiation while preserving useful image quality.",
          "Optimal settings balance diagnostic adequacy with minimum justified dose.",
        ],
        workedSolution: [
          "Structure answer as balanced evaluation, not one-sided recommendation.",
          "Explicitly connect each setting change to both image-quality and dose consequences.",
          "Mention practical optimization methods such as collimation/filtration/technique protocols.",
        ],
        commonMistake: "Assuming maximum exposure is always best because images look clearer.",
        tags: ["optimization", "alara", "evaluation"],
      },
    ],
    flashcards: [
      {
        id: "t24-2-f1",
        noteId: "t24-2",
        difficulty: 1,
        front: "What type of radiation are X-rays?",
        back: "High-frequency electromagnetic radiation.",
        examPhrasing: "X-rays are ionising EM photons with short wavelength.",
        tags: ["definition", "em-spectrum"],
      },
      {
        id: "t24-2-f2",
        noteId: "t24-2",
        difficulty: 1,
        front: "Where are electrons produced in an X-ray tube?",
        back: "At the heated cathode via thermionic emission.",
        examPhrasing: "A hot filament emits electrons that are accelerated to the anode.",
        tags: ["x-ray-tube", "cathode"],
      },
      {
        id: "t24-2-f3",
        noteId: "t24-2",
        difficulty: 2,
        front: "How does increasing tube voltage affect X-ray photons?",
        back: "It increases the maximum photon energy and beam penetration.",
        examPhrasing: "Higher accelerating potential gives electrons greater kinetic energy before target impact.",
        tags: ["tube-voltage", "photon-energy"],
      },
      {
        id: "t24-2-f4",
        noteId: "t24-2",
        difficulty: 2,
        front: "Why does bone appear bright on many radiographs?",
        back: "Bone attenuates X-rays strongly, so fewer photons reach the detector there.",
        examPhrasing: "Greater attenuation corresponds to lighter image regions in standard display mappings.",
        tags: ["contrast", "bone-attenuation"],
      },
      {
        id: "t24-2-f5",
        noteId: "t24-2",
        difficulty: 3,
        front: "State the photon-energy equation in terms of wavelength.",
        back: "E = hc/lambda.",
        examPhrasing: "Use SI units to calculate photon energy in joules.",
        tags: ["equation", "photon-energy"],
      },
      {
        id: "t24-2-f6",
        noteId: "t24-2",
        difficulty: 3,
        front: "What is absorbed dose and its SI unit?",
        back: "Energy absorbed per unit mass; SI unit is gray (Gy = J kg^-1).",
        examPhrasing: "Absorbed dose quantifies deposited ionising-radiation energy in tissue.",
        tags: ["dose", "units"],
      },
      {
        id: "t24-2-f7",
        noteId: "t24-2",
        difficulty: 4,
        front: "Why is lead effective as X-ray shielding?",
        back: "Its high atomic number and density produce strong attenuation.",
        examPhrasing: "Lead reduces transmitted intensity, lowering unintended exposure.",
        tags: ["shielding", "lead", "safety"],
      },
      {
        id: "t24-2-f8",
        noteId: "t24-2",
        difficulty: 4,
        front: "State the exponential attenuation law for X-rays in matter.",
        back: "I = I0 e^(-mu x).",
        examPhrasing: "Attenuation coefficient mu has unit m^-1 when x is in metres.",
        tags: ["attenuation-law", "equation"],
      },
      {
        id: "t24-2-f9",
        noteId: "t24-2",
        difficulty: 5,
        front: "What is ALARA in medical imaging?",
        back: "As Low As Reasonably Achievable: minimize dose while obtaining diagnostic-quality images.",
        examPhrasing: "Dose optimization must preserve clinical usefulness, not merely reduce exposure.",
        tags: ["radiation-protection", "alara"],
      },
      {
        id: "t24-2-f10",
        noteId: "t24-2",
        difficulty: 5,
        front: "Common confusion in X-ray safety questions?",
        back: "Mixing image brightness/contrast ideas with dose magnitude without linking to exposure settings.",
        examPhrasing: "Always separate image-quality metrics from patient-dose metrics before evaluating trade-offs.",
        confusionPair: "Image quality optimization vs dose minimization",
        tags: ["exam-technique", "evaluation"],
      },
    ],
  },
  "t24-3": {
    noteId: "t24-3",
    drills: [
      {
        id: "t24-3-d1",
        noteId: "t24-3",
        kind: "mcq",
        difficulty: 1,
        stem: "PET stands for",
        options: [
          { id: "A", text: "Particle Emission Tomography" },
          { id: "B", text: "Positron Emission Tomography" },
          { id: "C", text: "Photon Energy Tracking" },
          { id: "D", text: "Positional Electron Tomography" },
        ],
        correctOptionId: "B",
        explanation: "PET is Positron Emission Tomography, based on positron-emitting tracers and coincidence detection.",
        distractorRationale: {
          B: "Correct expansion.",
          C: "Not the medical acronym used in imaging.",
          D: "PET uses positrons from nuclear decay, not positional electron mapping.",
        },
        tags: ["pet", "acronym", "basics"],
      },
      {
        id: "t24-3-d2",
        noteId: "t24-3",
        kind: "mcq",
        difficulty: 2,
        stem: "In PET, annihilation of a positron with an electron typically produces",
        options: [
          { id: "A", text: "one gamma photon of variable energy" },
          { id: "B", text: "two gamma photons emitted in opposite directions" },
          { id: "C", text: "an alpha particle and a neutron" },
          { id: "D", text: "two X-ray photons at 10 keV each" },
        ],
        correctOptionId: "B",
        explanation: "Electron-positron annihilation produces two 511 keV gamma photons traveling approximately 180 degrees apart.",
        distractorRationale: {
          B: "Correct PET annihilation signature used for coincidence detection.",
          C: "These are nuclear particles not produced by annihilation.",
          D: "Energy and radiation type are incorrect.",
        },
        tags: ["annihilation", "gamma-photons", "coincidence"],
      },
      {
        id: "t24-3-d3",
        noteId: "t24-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Why does PET provide functional information about tissue?",
        options: [
          { id: "A", text: "It directly measures bone density only" },
          { id: "B", text: "Tracer uptake reflects metabolic/biochemical activity" },
          { id: "C", text: "It uses ultrasound reflections from organs" },
          { id: "D", text: "It measures electrical resistance of tissue" },
        ],
        correctOptionId: "B",
        explanation: "PET tracers participate in physiological processes, so uptake patterns map tissue function, not just structure.",
        distractorRationale: {
          B: "Correct functional-imaging principle.",
          C: "Ultrasound is a separate modality.",
          D: "Electrical resistance is not PET signal basis.",
        },
        tags: ["functional-imaging", "tracer-uptake", "pet-principle"],
      },
      {
        id: "t24-3-d4",
        noteId: "t24-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Outline the sequence of events from tracer injection to PET image formation.",
        modelAnswerPoints: [
          "A positron-emitting radiotracer is introduced and accumulates in target tissues.",
          "Positrons annihilate with electrons, producing two opposite 511 keV gamma photons.",
          "Coincidence detection of paired photons is used to reconstruct tracer distribution image.",
        ],
        workedSolution: [
          "Keep sequence in logical order: tracer -> annihilation -> detection -> reconstruction.",
          "Mention coincidence requirement explicitly for method mark.",
        ],
        commonMistake: "Stating PET detects positrons directly traveling to detectors.",
        tags: ["process", "pet-imaging", "sequence"],
      },
      {
        id: "t24-3-d5",
        noteId: "t24-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A positron annihilation produces two photons each of energy 511 keV.\n(a) Calculate total annihilation energy in MeV.\n(b) Convert this total to joules.\nUse 1 eV = 1.60 x 10^-19 J.",
        modelAnswerPoints: [
          "Total energy = 2 x 511 keV = 1022 keV = 1.022 MeV.",
          "In eV, total = 1.022 x 10^6 eV.",
          "Energy in joules = 1.022 x 10^6 x 1.60 x 10^-19 J.",
          "E = 1.64 x 10^-13 J.",
        ],
        workedSolution: [
          "Add energies from both photons before converting units.",
          "Use standard eV-to-joule conversion with scientific notation.",
          "Report final value with suitable significant figures.",
        ],
        commonMistake: "Converting 511 keV as if it were already in MeV or joules.",
        tags: ["annihilation-energy", "unit-conversion", "calculation"],
      },
      {
        id: "t24-3-d6",
        noteId: "t24-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Explain why PET detectors are arranged in a ring around the patient and why coincidence timing is required.",
        modelAnswerPoints: [
          "Ring geometry allows detection of photon pairs from many directions.",
          "Opposite detectors can register the paired annihilation photons.",
          "Coincidence timing ensures both photons come from the same annihilation event.",
          "This reduces random background events and improves localization along a line of response.",
        ],
        workedSolution: [
          "Discuss geometry and timing as separate design requirements.",
          "Link coincidence to both noise rejection and spatial reconstruction.",
        ],
        commonMistake: "Saying ring arrangement is only to maximize patient comfort.",
        tags: ["detector-geometry", "coincidence", "signal-processing"],
      },
      {
        id: "t24-3-d7",
        noteId: "t24-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "A PET tracer has activity 240 MBq at preparation.\nIf half-life is 110 minutes, find activity after 220 minutes.\nState one implication for scan scheduling.",
        modelAnswerPoints: [
          "220 minutes is two half-lives.",
          "Activity after two half-lives: 240/4 = 60 MBq.",
          "Equivalent decay law method gives same result.",
          "Rapid decay means tracer production and scanning must be time-coordinated.",
        ],
        workedSolution: [
          "Identify number of half-lives before calculating activity.",
          "Include units (MBq) in final numerical answer.",
          "Interpret practical effect: delayed scans reduce count rates and image quality.",
        ],
        commonMistake: "Subtracting half-life values linearly instead of applying halving process.",
        tags: ["activity", "half-life", "clinical-logistics"],
      },
      {
        id: "t24-3-d8",
        noteId: "t24-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Compare PET and CT in terms of the type of information each primarily provides, and explain why PET/CT combination is clinically useful.",
        modelAnswerPoints: [
          "PET primarily gives functional/metabolic information from tracer uptake.",
          "CT primarily gives anatomical/structural detail from X-ray attenuation.",
          "PET alone can localize abnormal function less precisely anatomically.",
          "Combining PET with CT overlays function on structure, improving diagnosis and treatment planning.",
        ],
        workedSolution: [
          "Keep modality roles distinct: function vs anatomy.",
          "Then justify fusion imaging as complementary rather than redundant.",
        ],
        commonMistake: "Claiming PET and CT are identical except PET uses higher energy photons.",
        tags: ["pet-vs-ct", "hybrid-imaging", "clinical-application"],
      },
      {
        id: "t24-3-d9",
        noteId: "t24-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A PET center receives a tracer dose of 500 MBq at 08:00.\nHalf-life is 110 min.\nEstimate activity at 11:40.\nThen comment on how this affects image count statistics if scan protocol is unchanged.",
        modelAnswerPoints: [
          "Time elapsed from 08:00 to 11:40 is 220 min (two half-lives).",
          "Activity becomes 500/4 = 125 MBq.",
          "Lower activity gives fewer detected events for same acquisition time.",
          "This can increase statistical noise unless scan time or dose strategy is adjusted.",
        ],
        workedSolution: [
          "Convert clock times to elapsed minutes before using half-life logic.",
          "Relate final activity to expected count-rate trend qualitatively.",
          "Explain imaging consequence in terms of signal statistics.",
        ],
        commonMistake: "Using three half-lives because of approximate mental rounding of time interval.",
        tags: ["time-decay", "count-statistics", "protocol"],
      },
      {
        id: "t24-3-d10",
        noteId: "t24-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Evaluate key benefits and risks of PET imaging for oncology follow-up.\nInclude at least one physics-based benefit, one clinical benefit, and one radiation-safety consideration.",
        modelAnswerPoints: [
          "Physics-based benefit: sensitive detection of metabolically active regions via positron-emitting tracers.",
          "Clinical benefit: can reveal active disease and treatment response before structural changes are obvious.",
          "PET may improve staging and management decisions when integrated with anatomical imaging.",
          "Risk: ionising radiation exposure from tracer (and CT if combined).",
          "Use requires justification and optimization to balance diagnostic value against dose.",
        ],
        workedSolution: [
          "Present balanced argument: not only advantages.",
          "Anchor benefits in PET signal mechanism, not generic statements.",
          "State explicit safety principle: justified indication and optimized protocol.",
        ],
        commonMistake: "Assuming PET has no radiation risk because it is called a scan.",
        tags: ["evaluation", "oncology", "radiation-risk"],
      },
    ],
    flashcards: [
      {
        id: "t24-3-f1",
        noteId: "t24-3",
        difficulty: 1,
        front: "What does PET stand for?",
        back: "Positron Emission Tomography.",
        examPhrasing: "PET uses positron-emitting radiotracers and coincidence gamma detection.",
        tags: ["acronym", "pet-basics"],
      },
      {
        id: "t24-3-f2",
        noteId: "t24-3",
        difficulty: 1,
        front: "What particles annihilate in PET signal generation?",
        back: "A positron and an electron.",
        examPhrasing: "Annihilation yields two gamma photons emitted in nearly opposite directions.",
        tags: ["annihilation", "particles"],
      },
      {
        id: "t24-3-f3",
        noteId: "t24-3",
        difficulty: 2,
        front: "What is the typical energy of each annihilation photon in PET?",
        back: "511 keV.",
        examPhrasing: "Paired 511 keV photons are used for coincidence detection.",
        tags: ["energy", "gamma-photons"],
      },
      {
        id: "t24-3-f4",
        noteId: "t24-3",
        difficulty: 2,
        front: "Why is coincidence timing important in PET?",
        back: "It helps identify photon pairs from the same annihilation event and reject random counts.",
        examPhrasing: "Coincident detection defines a line of response for image reconstruction.",
        tags: ["coincidence", "reconstruction"],
      },
      {
        id: "t24-3-f5",
        noteId: "t24-3",
        difficulty: 3,
        front: "Why is PET considered functional imaging?",
        back: "Tracer uptake reflects physiological/metabolic activity rather than just anatomy.",
        examPhrasing: "PET maps biochemical behavior in vivo.",
        tags: ["functional-imaging", "tracer-uptake"],
      },
      {
        id: "t24-3-f6",
        noteId: "t24-3",
        difficulty: 3,
        front: "How does tracer half-life affect PET workflow?",
        back: "Activity drops quickly, so preparation, transport, and scanning must be tightly timed.",
        examPhrasing: "Short half-life isotopes require coordinated scheduling to preserve count rates.",
        tags: ["half-life", "workflow"],
      },
      {
        id: "t24-3-f7",
        noteId: "t24-3",
        difficulty: 4,
        front: "Primary difference between PET and CT information?",
        back: "PET gives functional/metabolic data; CT gives structural/anatomical detail.",
        examPhrasing: "Hybrid PET/CT combines complementary datasets.",
        tags: ["pet-vs-ct", "modality-comparison"],
      },
      {
        id: "t24-3-f8",
        noteId: "t24-3",
        difficulty: 4,
        front: "What is activity measured in?",
        back: "Becquerel (Bq), where 1 Bq = 1 decay per second.",
        examPhrasing: "Clinical tracer activity is often reported in MBq.",
        tags: ["activity", "units"],
      },
      {
        id: "t24-3-f9",
        noteId: "t24-3",
        difficulty: 5,
        front: "Why can reduced tracer activity degrade PET image quality?",
        back: "Fewer detected events increase statistical noise if scan settings are unchanged.",
        examPhrasing: "Lower count statistics weaken signal-to-noise performance.",
        tags: ["count-statistics", "image-quality"],
      },
      {
        id: "t24-3-f10",
        noteId: "t24-3",
        difficulty: 5,
        front: "Key safety principle for PET use?",
        back: "Use justified indications and optimize protocol to keep ionising-radiation dose as low as reasonably achievable.",
        examPhrasing: "Diagnostic value must outweigh radiation risk.",
        confusionPair: "Functional sensitivity vs radiation burden",
        tags: ["safety", "optimization", "evaluation"],
      },
    ],
  },
};
