import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC2_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t2-1": {
    noteId: "t2-1",
    drills: [
      {
        id: "t2-1-d1",
        noteId: "t2-1",
        kind: "mcq",
        difficulty: 1,
        stem: "A cyclist starts from rest and accelerates uniformly at 1.8 m s^-2 for 6.0 s. What is the cyclist's final velocity?",
        options: [
          { id: "A", text: "10.8 m s^-1" },
          { id: "B", text: "5.4 m s^-1" },
          { id: "C", text: "7.8 m s^-1" },
          { id: "D", text: "64.8 m s^-1" },
        ],
        correctOptionId: "A",
        explanation:
          "Use v = u + at with u = 0, a = 1.8 m s^-2, t = 6.0 s. So v = 0 + (1.8)(6.0) = 10.8 m s^-1.",
        distractorRationale: {
          B: "This is (1/2)at, which confuses mean velocity with final velocity.",
          C: "This comes from arithmetic error in multiplying 1.8 by 6.0.",
          D: "This is at^2, which has displacement form and wrong units for velocity.",
        },
        tags: ["suvat", "v=u+at", "constant-acceleration", "units"],
      },
      {
        id: "t2-1-d2",
        noteId: "t2-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which statement about a velocity-time graph is correct?",
        options: [
          { id: "A", text: "The gradient is acceleration and the area under the graph is displacement." },
          { id: "B", text: "The gradient is displacement and the area under the graph is acceleration." },
          { id: "C", text: "The gradient is speed and the area under the graph is distance only." },
          { id: "D", text: "The area under the graph is always zero if velocity changes sign." },
        ],
        correctOptionId: "A",
        explanation:
          "For a v-t graph, slope = dv/dt = acceleration. Signed area = integral of v dt = displacement.",
        distractorRationale: {
          B: "This swaps the two core interpretations and is a frequent graph-reading error.",
          C: "Speed is not the gradient of v-t; area can represent signed displacement, not always distance.",
          D: "A sign change can reduce net area but does not force it to be zero.",
        },
        tags: ["graphs", "velocity-time", "gradient", "area"],
      },
      {
        id: "t2-1-d3",
        noteId: "t2-1",
        kind: "mcq",
        difficulty: 2,
        stem: "A ball is projected vertically upward with speed 15 m s^-1. Taking upward as positive and g = 9.81 m s^-2, which equation setup is correct for finding time to maximum height?",
        options: [
          { id: "A", text: "0 = 15 - 9.81t" },
          { id: "B", text: "0 = 15 + 9.81t" },
          { id: "C", text: "15 = -9.81 + t" },
          { id: "D", text: "0 = 15 - 4.905t^2" },
        ],
        correctOptionId: "A",
        explanation:
          "At the highest point v = 0, with u = +15 and a = -9.81. So v = u + at gives 0 = 15 - 9.81t.",
        distractorRationale: {
          B: "This uses the wrong sign for acceleration under the chosen upward-positive convention.",
          C: "This is dimensionally invalid: you cannot add acceleration and time directly.",
          D: "This is based on displacement form and does not directly express v = 0 at turning point.",
        },
        tags: ["vertical-motion", "sign-convention", "free-fall", "v=u+at"],
      },
      {
        id: "t2-1-d4",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A train moving at 12.0 m s^-1 accelerates uniformly at 0.80 m s^-2 for 15.0 s. Calculate (i) its final velocity and (ii) the distance traveled during this interval.",
        modelAnswerPoints: [
          "Use v = u + at to find final velocity.",
          "Use either s = ut + (1/2)at^2 or s = ((u+v)/2)t for displacement.",
          "State final answers with units.",
        ],
        workedSolution: [
          "Given: u = 12.0 m s^-1, a = 0.80 m s^-2, t = 15.0 s.",
          "Final velocity: v = u + at = 12.0 + (0.80)(15.0) = 24.0 m s^-1.",
          "Displacement: s = ut + (1/2)at^2 = (12.0)(15.0) + 0.5(0.80)(15.0)^2.",
          "s = 180 + 90 = 270 m.",
          "Answers: (i) 24.0 m s^-1, (ii) 270 m.",
        ],
        commonMistake:
          "Using s = vt with final velocity only, which overestimates distance when acceleration is present.",
        tags: ["suvat", "multi-step", "kinematics-basics"],
      },
      {
        id: "t2-1-d5",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 2,
        marks: 5,
        stem: "A stone is thrown vertically upward at 18.0 m s^-1 from a balcony. Take upward as positive and g = 9.81 m s^-2. Find (i) time to reach maximum height and (ii) the maximum height above the release point.",
        modelAnswerPoints: [
          "At maximum height, set v = 0.",
          "Use v = u + at for time.",
          "Use v^2 = u^2 + 2as (or equivalent) for height.",
          "Maintain consistent signs and quote units.",
        ],
        workedSolution: [
          "Given u = +18.0 m s^-1, a = -9.81 m s^-2, v = 0 at top.",
          "From v = u + at: 0 = 18.0 - 9.81t, so t = 18.0/9.81 = 1.84 s.",
          "From v^2 = u^2 + 2as: 0 = (18.0)^2 + 2(-9.81)s.",
          "So s = (18.0)^2 / (2 x 9.81) = 16.5 m (3 s.f.).",
          "Answers: (i) 1.84 s, (ii) 16.5 m above release point.",
        ],
        commonMistake:
          "Assigning a = +9.81 while also taking upward as positive, causing a negative time or incorrect height.",
        tags: ["free-fall", "turning-point", "signs", "v2=u2+2as"],
      },
      {
        id: "t2-1-d6",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "A particle moves in a straight line with constant acceleration. It has velocity 6.0 m s^-1 at point P and 18.0 m s^-1 at point Q, 96 m from P. Calculate (i) the acceleration and (ii) the time from P to Q.",
        modelAnswerPoints: [
          "Identify u, v, s from statement.",
          "Use v^2 = u^2 + 2as to obtain a first.",
          "Then use v = u + at to find t.",
          "Use correct units and sensible significant figures.",
        ],
        workedSolution: [
          "Given: u = 6.0 m s^-1, v = 18.0 m s^-1, s = 96 m.",
          "Use v^2 = u^2 + 2as:",
          "(18.0)^2 = (6.0)^2 + 2a(96).",
          "324 = 36 + 192a => 288 = 192a => a = 1.50 m s^-2.",
          "Now use v = u + at: 18.0 = 6.0 + (1.50)t.",
          "t = 12.0/1.50 = 8.0 s.",
          "Answers: (i) 1.50 m s^-2, (ii) 8.0 s.",
        ],
        commonMistake:
          "Trying s = ut + (1/2)at^2 first with both t and a unknown, then getting stuck in unnecessary algebra.",
        tags: ["equation-selection", "v2=u2+2as", "time-elimination"],
      },
      {
        id: "t2-1-d7",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 3,
        marks: 6,
        stem: "A motorcycle travels along a straight road. It decelerates uniformly from 28 m s^-1 to 10 m s^-1 in 6.0 s, then continues at 10 m s^-1 for 12.0 s. Calculate the total distance traveled in the 18.0 s interval.",
        modelAnswerPoints: [
          "Split motion into two stages.",
          "Stage 1 distance from average velocity x time or suvat.",
          "Stage 2 distance from constant speed x time.",
          "Add both distances for total.",
        ],
        workedSolution: [
          "Stage 1 (uniform deceleration): u = 28, v = 10, t = 6.0 s.",
          "s1 = ((u + v)/2)t = ((28 + 10)/2)(6.0) = 19 x 6.0 = 114 m.",
          "Stage 2 (constant speed): s2 = vt = (10)(12.0) = 120 m.",
          "Total distance = s1 + s2 = 114 + 120 = 234 m.",
        ],
        commonMistake:
          "Using one constant acceleration model over full 18 s, ignoring that acceleration is zero in second stage.",
        tags: ["piecewise-motion", "average-velocity", "distance"],
      },
      {
        id: "t2-1-d8",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 4,
        marks: 7,
        stem: "A ball is projected horizontally from the edge of a cliff at 14.0 m s^-1 and lands 35.0 m away from the foot of the cliff. Neglect air resistance. Calculate (i) the time of flight and (ii) the height of the cliff. Take g = 9.81 m s^-2.",
        modelAnswerPoints: [
          "Horizontal motion gives time via x = u_x t (a_x = 0).",
          "Vertical motion starts with u_y = 0 and uses s_y = (1/2)gt^2 in magnitude.",
          "State assumptions: independent horizontal and vertical components.",
          "Give final values with units.",
        ],
        workedSolution: [
          "Horizontal component: x = 35.0 m, u_x = 14.0 m s^-1.",
          "t = x/u_x = 35.0/14.0 = 2.50 s.",
          "Vertical component: initial vertical velocity u_y = 0, downward displacement h.",
          "h = (1/2)gt^2 = 0.5 x 9.81 x (2.50)^2.",
          "h = 4.905 x 6.25 = 30.7 m (3 s.f.).",
          "Answers: (i) 2.50 s, (ii) 30.7 m.",
        ],
        commonMistake:
          "Using resultant launch speed as vertical initial speed; for horizontal projection u_y is zero.",
        tags: ["projectile", "component-method", "independence-of-motion"],
      },
      {
        id: "t2-1-d9",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 4,
        marks: 8,
        stem: "A lift moves vertically upward from rest with constant acceleration for 3.0 s, reaches a speed of 4.5 m s^-1, then moves at constant speed for 5.0 s, and finally decelerates uniformly to rest in 2.0 s. Calculate (i) the total distance moved and (ii) the magnitude of deceleration in the final stage.",
        modelAnswerPoints: [
          "Determine acceleration stage displacement from average velocity or suvat.",
          "Constant-speed stage displacement from s = vt.",
          "Final-stage deceleration magnitude from change in velocity over time.",
          "Final-stage displacement from average velocity x time.",
          "Sum stage displacements.",
        ],
        workedSolution: [
          "Stage 1: u = 0, v = 4.5, t = 3.0 s.",
          "s1 = ((u + v)/2)t = ((0 + 4.5)/2)(3.0) = 6.75 m.",
          "Stage 2: constant speed 4.5 m s^-1 for 5.0 s.",
          "s2 = vt = 4.5 x 5.0 = 22.5 m.",
          "Stage 3: decelerates from 4.5 to 0 in 2.0 s.",
          "a3 = (v - u)/t = (0 - 4.5)/2.0 = -2.25 m s^-2, so magnitude = 2.25 m s^-2.",
          "s3 = ((4.5 + 0)/2)(2.0) = 4.5 m.",
          "Total distance = s1 + s2 + s3 = 6.75 + 22.5 + 4.5 = 33.75 m (~33.8 m).",
          "Answers: (i) 33.8 m, (ii) 2.25 m s^-2.",
        ],
        commonMistake:
          "Treating deceleration as negative distance; displacement in each upward stage remains positive here.",
        tags: ["multi-stage", "velocity-time-area", "deceleration"],
      },
      {
        id: "t2-1-d10",
        noteId: "t2-1",
        kind: "structured",
        difficulty: 5,
        marks: 9,
        stem: "In an experiment to determine g, a steel sphere is released from rest and the fall time t is measured electronically for different drop heights s. A best-fit graph of s (y-axis) against t^2 (x-axis) has gradient 4.86 m s^-2 and intercept +0.012 m. (i) Determine g from the graph. (ii) State what the positive intercept suggests. (iii) Give two improvements to reduce uncertainty/systematic error.",
        modelAnswerPoints: [
          "Use model s = (1/2)gt^2 so gradient = g/2.",
          "Compute g = 2 x gradient.",
          "Interpret non-zero intercept as systematic offset (e.g., release/timing delay or zero-height offset).",
          "Give realistic improvements linked to the setup and data quality.",
        ],
        workedSolution: [
          "For free fall from rest, s = (1/2)gt^2 + c, where c is intercept if systematic offset exists.",
          "Given gradient m = 4.86 m s^-2, then g = 2m = 9.72 m s^-2.",
          "The positive intercept (+0.012 m) indicates a systematic error, such as measured drop height being consistently too large or an effective timing delay equivalent to extra apparent distance.",
          "Improvement 1: use larger range of heights and more repeats at each height, then average times to reduce random scatter.",
          "Improvement 2: calibrate release and sensor alignment (or use synchronized electromagnetic release and light gate) to minimize trigger delay and zero-offset error.",
        ],
        commonMistake:
          "Using the gradient directly as g and ignoring that the graph is s against t^2, not v against t.",
        tags: ["experiment", "graph-analysis", "g-determination", "uncertainty"],
      },
    ],
    flashcards: [
      {
        id: "t2-1-f1",
        noteId: "t2-1",
        difficulty: 1,
        front: "State the condition for using the suvat equations.",
        back: "They are valid only for motion with constant acceleration over the interval considered.",
        examPhrasing: "The equations of uniformly accelerated motion apply only when acceleration is constant.",
        confusionPair: "constant acceleration vs constant velocity",
        tags: ["fundamental-condition", "suvat"],
      },
      {
        id: "t2-1-f2",
        noteId: "t2-1",
        difficulty: 1,
        front: "On a velocity-time graph, what do gradient and area represent?",
        back: "Gradient gives acceleration; signed area under the graph gives displacement.",
        examPhrasing: "Acceleration is obtained from the gradient of the v-t graph, while displacement is the area under the v-t graph.",
        confusionPair: "velocity-time vs displacement-time graph interpretation",
        tags: ["graphs", "gradient", "area"],
      },
      {
        id: "t2-1-f3",
        noteId: "t2-1",
        difficulty: 2,
        front: "Why must you define a positive direction before solving vertical motion problems?",
        back: "Because velocity and acceleration are signed vectors; inconsistent signs cause wrong equations and non-physical answers.",
        examPhrasing: "A fixed sign convention ensures direction is handled consistently in vector quantities.",
        confusionPair: "speed (scalar) vs velocity (vector)",
        tags: ["sign-convention", "vertical-motion"],
      },
      {
        id: "t2-1-f4",
        noteId: "t2-1",
        difficulty: 2,
        front: "When is v^2 = u^2 + 2as especially useful in exam questions?",
        back: "When time is not given or not needed, because this equation links v, u, a, and s directly without t.",
        examPhrasing: "Use v^2 = u^2 + 2as to eliminate time from constant-acceleration problems.",
        confusionPair: "equations with t vs equation without t",
        tags: ["equation-choice", "time-elimination"],
      },
      {
        id: "t2-1-f5",
        noteId: "t2-1",
        difficulty: 2,
        front: "At maximum height in vertical projection, which quantity is zero and which is not necessarily zero?",
        back: "Instantaneous velocity is zero; acceleration is not zero (it is still ±g depending on sign convention).",
        examPhrasing: "At the turning point, v = 0 but a remains constant due to gravity.",
        confusionPair: "v=0 vs a=0 at turning point",
        tags: ["free-fall", "turning-point"],
      },
      {
        id: "t2-1-f6",
        noteId: "t2-1",
        difficulty: 3,
        front: "For a horizontally launched projectile (neglect air resistance), what are a_x and a_y?",
        back: "a_x = 0 and a_y = -g if upward is positive (or +g if downward is positive).",
        examPhrasing: "Horizontal acceleration is zero; vertical acceleration is constant and equal to g downward.",
        confusionPair: "horizontal velocity constant vs horizontal acceleration zero",
        tags: ["projectile", "components"],
      },
      {
        id: "t2-1-f7",
        noteId: "t2-1",
        difficulty: 3,
        front: "How do you extract g from an s against t^2 graph for free fall from rest?",
        back: "From s = (1/2)gt^2, gradient m = g/2, so g = 2m.",
        examPhrasing: "For a plot of s versus t^2, twice the gradient gives the gravitational field strength.",
        confusionPair: "plotting s vs t^2 vs plotting v vs t",
        tags: ["experiment", "graph-gradient", "g"],
      },
      {
        id: "t2-1-f8",
        noteId: "t2-1",
        difficulty: 4,
        front: "A question gives one motion in separate phases. What is the safest method?",
        back: "Model each phase separately, carry final velocity of one phase as initial velocity of the next, and sum displacements as required.",
        examPhrasing: "Piecewise constant-acceleration analysis is required when the motion changes regime.",
        confusionPair: "single-stage suvat vs piecewise modeling",
        tags: ["multi-stage", "method"],
      },
      {
        id: "t2-1-f9",
        noteId: "t2-1",
        difficulty: 4,
        front: "Why can a speed-time graph give total distance directly, while a velocity-time graph may not?",
        back: "Speed is always non-negative, so area is total distance. Velocity is signed, so areas below axis subtract, giving displacement.",
        examPhrasing: "Distance is obtained from area under a speed-time graph; area under a velocity-time graph gives displacement.",
        confusionPair: "distance vs displacement from graph area",
        tags: ["graphs", "distance-displacement"],
      },
      {
        id: "t2-1-f10",
        noteId: "t2-1",
        difficulty: 5,
        front: "What does a non-zero intercept on an s against t^2 free-fall graph usually indicate in practical work?",
        back: "A systematic offset, such as release/timer delay or consistent height-zero error, rather than random scatter.",
        examPhrasing: "A non-zero intercept implies a systematic error in the measurement model.",
        confusionPair: "random uncertainty vs systematic error",
        tags: ["practical", "systematic-error", "data-analysis"],
      },
    ],
  },
};
