import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC3_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t3-1": {
    noteId: "t3-1",
    drills: [
      {
        id: "t3-1-d1",
        noteId: "t3-1",
        kind: "mcq",
        difficulty: 1,
        stem: "For a body of constant mass, which statement is Newton's second law?",
        options: [
          { id: "A", text: "Resultant force equals mass x acceleration." },
          { id: "B", text: "Resultant force equals mass x velocity." },
          { id: "C", text: "Resultant force equals momentum." },
          { id: "D", text: "Resultant force is always equal to weight." },
        ] as const,
        correctOptionId: "A",
        explanation:
          "For constant mass motion, Newton's second law is F = ma. The most general form is F = dp/dt.",
        distractorRationale: {
          B: "Velocity is not the time-rate quantity in the law; acceleration is.",
          C: "Force equals rate of change of momentum, not momentum itself.",
          D: "Weight is only one force; resultant force is the vector sum of all forces.",
        },
        tags: ["newtons-second-law", "definitions", "constant-mass"],
      },
      {
        id: "t3-1-d2",
        noteId: "t3-1",
        kind: "mcq",
        difficulty: 2,
        stem: "A 2.0 kg trolley accelerates at 3.5 m s^-2 to the right. What is the resultant force on it?",
        options: [
          { id: "A", text: "1.75 N to the right" },
          { id: "B", text: "5.5 N to the right" },
          { id: "C", text: "7.0 N to the right" },
          { id: "D", text: "7.0 N to the left" },
        ] as const,
        correctOptionId: "C",
        explanation: "F = ma = 2.0 x 3.5 = 7.0 N, in the same direction as acceleration.",
        distractorRationale: {
          B: "This is an arithmetic error from incorrect multiplication.",
          D: "Resultant force has same direction as acceleration, so it must be rightward.",
        },
        tags: ["newtons-second-law", "calculation", "direction"],
      },
      {
        id: "t3-1-d3",
        noteId: "t3-1",
        kind: "mcq",
        difficulty: 2,
        stem: "A ball's momentum changes from +3.2 to -1.8 kg m s^-1 in 0.25 s. What is the average force?",
        options: [
          { id: "A", text: "-20 N" },
          { id: "B", text: "-5.0 N" },
          { id: "C", text: "+5.0 N" },
          { id: "D", text: "+20 N" },
        ] as const,
        correctOptionId: "A",
        explanation:
          "Delta p = -1.8 - (+3.2) = -5.0 kg m s^-1. F_avg = Delta p / Delta t = -5.0 / 0.25 = -20 N.",
        distractorRationale: {
          B: "This omits division by the time interval.",
          C: "Sign error from ignoring opposite direction of final momentum.",
          D: "Magnitude right, sign wrong.",
        },
        tags: ["impulse", "momentum-change", "sign-convention"],
      },
      {
        id: "t3-1-d4",
        noteId: "t3-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "State Newton's first, second, and third laws in precise exam language.",
        modelAnswerPoints: [
          "First law: a body remains at rest or in uniform straight-line motion unless acted on by a resultant external force.",
          "Second law: resultant force equals rate of change of momentum, in the direction of that change.",
          "Third law: when body A exerts a force on body B, body B exerts an equal and opposite force on body A.",
          "Clarify that third-law pairs act on different bodies.",
        ],
        workedSolution: [
          "Write each law as a condition plus consequence rather than a slogan.",
          "Include 'resultant external force' for first law to avoid ambiguity.",
          "Use momentum form for second law to show the most general statement.",
          "Explicitly mention different bodies for third law; this is often the mark discriminator.",
        ],
        commonMistake:
          "Writing the second law as force proportional to velocity, or saying third-law forces cancel on one object.",
        tags: ["newtons-laws", "definitions", "exam-technique"],
      },
      {
        id: "t3-1-d5",
        noteId: "t3-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A 0.40 kg puck moves east at 10 m s^-1 and leaves a stick moving west at 6.0 m s^-1. Contact time is 0.030 s. Take east positive. Find (i) impulse and (ii) average force on the puck.",
        modelAnswerPoints: [
          "Initial momentum p_i = 0.40 x 10 = +4.0 kg m s^-1.",
          "Final momentum p_f = 0.40 x (-6.0) = -2.4 kg m s^-1.",
          "Impulse J = Delta p = p_f - p_i = -6.4 N s.",
          "Average force F = Delta p / Delta t = -6.4 / 0.030 = -213 N (3 s.f.).",
          "Direction is west.",
        ],
        workedSolution: [
          "Convert both velocities to signed values before multiplying by mass.",
          "Find change in momentum with final minus initial, preserving sign.",
          "Use J = Delta p directly; this is the impulse on the puck.",
          "Divide by contact time to obtain average force.",
          "State magnitude and direction clearly in words.",
        ],
        commonMistake:
          "Using speed instead of signed velocity, giving positive Delta p and wrong force direction.",
        tags: ["impulse", "average-force", "one-dimensional-motion"],
      },
      {
        id: "t3-1-d6",
        noteId: "t3-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A 5.0 kg block is pulled horizontally by 22 N on a rough floor. A resistive force of 7.0 N acts opposite motion. Calculate acceleration and distance moved in 4.0 s from rest.",
        modelAnswerPoints: [
          "Resultant force = 22 - 7.0 = 15 N.",
          "Acceleration a = F/m = 15/5.0 = 3.0 m s^-2.",
          "From rest, distance s = ut + 0.5at^2 = 0 + 0.5 x 3.0 x 4.0^2.",
          "s = 24 m.",
        ],
        workedSolution: [
          "Identify and subtract forces along one axis to get resultant force.",
          "Apply F = ma for constant mass to get acceleration.",
          "Use kinematics with u = 0 because the block starts from rest.",
          "Substitute carefully: s = 0.5 x 3.0 x 16.",
          "Quote distance to sensible precision.",
        ],
        commonMistake: "Using pulling force alone in F = ma and forgetting the opposing resistive force.",
        tags: ["resultant-force", "free-body-reasoning", "kinematics-link"],
      },
      {
        id: "t3-1-d7",
        noteId: "t3-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A 3.0 kg crate on a 20 degree incline is attached to a light string parallel to the slope. Friction is 2.5 N up the slope. If the crate accelerates 1.2 m s^-2 down the slope, find the tension in the string. Take g = 9.81 m s^-2.",
        modelAnswerPoints: [
          "Resolve forces along slope with down-slope positive.",
          "Component of weight down slope: mg sin20 = 3.0 x 9.81 x sin20 = 10.1 N.",
          "Equation: 10.1 - T - 2.5 = ma = 3.0 x 1.2 = 3.6.",
          "So T = 10.1 - 2.5 - 3.6 = 4.0 N (approx).",
        ],
        workedSolution: [
          "Choose a sign convention first to avoid algebraic reversals.",
          "Write all parallel-to-slope forces with signs: weight component positive, tension and friction negative.",
          "Apply Newton's second law to the chosen axis.",
          "Rearrange for tension and evaluate numerically.",
          "Check reasonableness: tension is smaller than downslope weight component, consistent with downslope acceleration.",
        ],
        commonMistake:
          "Using mg instead of mg sin(theta), or putting friction in the same direction as motion.",
        tags: ["inclined-plane", "newtons-second-law", "force-resolution"],
      },
      {
        id: "t3-1-d8",
        noteId: "t3-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A rocket test cart of mass 12 kg ejects gas so its mass decreases to 11.5 kg in 1.0 s. Its speed increases from 4.0 to 7.5 m s^-1 in the same direction. Calculate the average resultant force using momentum form.",
        modelAnswerPoints: [
          "Initial momentum p_i = 12 x 4.0 = 48 kg m s^-1.",
          "Final momentum p_f = 11.5 x 7.5 = 86.25 kg m s^-1.",
          "Delta p = 86.25 - 48 = 38.25 kg m s^-1.",
          "Average resultant force F = Delta p / Delta t = 38.25 N.",
          "State that momentum form is required because mass is changing.",
        ],
        workedSolution: [
          "Avoid F = ma directly because m is not constant over the interval.",
          "Compute momentum at start and end from p = mv.",
          "Take the difference to find change in momentum.",
          "Divide by time interval to get average resultant force.",
          "Include units and direction (same as momentum increase).",
        ],
        commonMistake: "Using average mass in F = ma without justification instead of using F = dp/dt.",
        tags: ["variable-mass", "momentum-form", "average-force"],
      },
      {
        id: "t3-1-d9",
        noteId: "t3-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A 65 kg student stands in a lift. The lift accelerates upward at 1.6 m s^-2 for 2.0 s, then moves at constant speed. (a) Find the normal reaction on the student during acceleration. (b) Find the impulse delivered by the floor to the student during the 2.0 s interval.",
        modelAnswerPoints: [
          "Take upward positive. For student: R - mg = ma.",
          "R = m(g + a) = 65(9.81 + 1.6) = 742 N.",
          "Floor force on student is reaction R upward.",
          "Net impulse = m Delta v = ma Delta t = 65 x 1.6 x 2.0 = 208 N s upward.",
          "Impulse from floor alone is R Delta t = 742 x 2.0 = 1484 N s upward.",
          "Weight gives downward impulse mg Delta t = 1276 N s; difference equals net impulse 208 N s.",
        ],
        workedSolution: [
          "Part (a): apply Newton's second law to the student as a single body.",
          "Because acceleration is upward, reaction must exceed weight.",
          "Part (b): interpret wording carefully; floor impulse is not the same as net impulse.",
          "Compute contact-force impulse directly using J = F Delta t for constant R.",
          "Cross-check by subtracting weight impulse to recover net impulse m Delta v.",
        ],
        commonMistake:
          "Giving m Delta v as the floor's impulse without accounting for simultaneous weight impulse.",
        tags: ["contact-force", "impulse-decomposition", "applied-newton-laws"],
      },
      {
        id: "t3-1-d10",
        noteId: "t3-1",
        kind: "structured",
        difficulty: 5,
        marks: 8,
        stem: "A 0.18 kg tennis ball approaches a racket at 28 m s^-1 and leaves in the opposite direction at 34 m s^-1. Contact lasts 6.0 ms. (a) Determine average force on the ball. (b) If the force-time graph is triangular with this contact duration and zero force at start/end, estimate peak force.",
        modelAnswerPoints: [
          "Take outgoing direction positive: u = -28 m s^-1, v = +34 m s^-1.",
          "Delta p = m(v-u) = 0.18[34 - (-28)] = 11.16 kg m s^-1.",
          "Average force F_avg = Delta p / Delta t = 11.16 / 0.0060 = 1.86 x 10^3 N.",
          "Triangle area gives impulse: 0.5 x F_peak x Delta t = Delta p.",
          "F_peak = 2 Delta p / Delta t = 2 x 11.16 / 0.0060 = 3.72 x 10^3 N.",
        ],
        workedSolution: [
          "Use signed velocities because direction reverses during collision.",
          "Convert milliseconds to seconds before dividing by time.",
          "Compute average force from impulse over interval.",
          "For triangular force profile, area under graph equals impulse.",
          "Rearrange area relation to obtain peak force and compare with average force (peak should be larger).",
        ],
        commonMistake:
          "Using Delta v as 34 - 28 instead of 34 - (-28), which halves the momentum change.",
        tags: ["collision-impulse", "force-time-graph", "high-difficulty"],
      },
    ] as const,
    flashcards: [
      {
        id: "t3-1-f1",
        noteId: "t3-1",
        difficulty: 1,
        front: "Define linear momentum and give its SI unit.",
        back: "Linear momentum p = mv (vector). SI unit: kg m s^-1.",
        examPhrasing: "Momentum is the product of mass and velocity, and is a vector quantity.",
        confusionPair: "Momentum vs kinetic energy",
        tags: ["definitions", "momentum"],
      },
      {
        id: "t3-1-f2",
        noteId: "t3-1",
        difficulty: 1,
        front: "State Newton's second law in its most general form.",
        back: "Resultant force equals the rate of change of momentum.",
        examPhrasing: "The resultant external force on a body is equal to dp/dt in the direction of the change.",
        confusionPair: "F=ma vs F=dp/dt",
        tags: ["newtons-second-law", "core-law"],
      },
      {
        id: "t3-1-f3",
        noteId: "t3-1",
        difficulty: 2,
        front: "Under what condition does F = ma follow from F = dp/dt?",
        back: "When mass is constant so dp/dt = m dv/dt = ma.",
        examPhrasing: "For constant mass motion, Newton's second law reduces to F = ma.",
        confusionPair: "constant mass vs variable mass",
        tags: ["derivation", "conditions"],
      },
      {
        id: "t3-1-f4",
        noteId: "t3-1",
        difficulty: 2,
        front: "Define impulse and link it to momentum.",
        back: "Impulse J = integral(F dt) (or F Delta t for constant force) and equals Delta p.",
        examPhrasing: "Impulse is the change in momentum of a body.",
        confusionPair: "force vs impulse",
        tags: ["impulse", "momentum-change"],
      },
      {
        id: "t3-1-f5",
        noteId: "t3-1",
        difficulty: 2,
        front: "How are mass and weight different?",
        back: "Mass is inertia (kg). Weight is gravitational force W = mg (N).",
        examPhrasing: "Mass is an intrinsic scalar; weight is a force dependent on local g.",
        confusionPair: "mass vs weight",
        tags: ["units", "definitions"],
      },
      {
        id: "t3-1-f6",
        noteId: "t3-1",
        difficulty: 3,
        front: "Why do action-reaction forces not cancel in one free-body diagram?",
        back: "They act on different bodies, so only one appears on any single-body diagram.",
        examPhrasing: "Third-law pairs are equal and opposite forces on different interacting bodies.",
        confusionPair: "third-law pair vs balanced forces",
        tags: ["newtons-third-law", "free-body"],
      },
      {
        id: "t3-1-f7",
        noteId: "t3-1",
        difficulty: 3,
        front: "What does area under a force-time graph represent?",
        back: "Impulse, equal to the change in momentum.",
        examPhrasing: "The signed area under an F-t graph gives Delta p.",
        confusionPair: "area vs gradient on F-t graph",
        tags: ["graphs", "impulse"],
      },
      {
        id: "t3-1-f8",
        noteId: "t3-1",
        difficulty: 4,
        front: "In 1D momentum questions, why must you choose a sign convention first?",
        back: "Because momentum is vector; wrong signs give incorrect Delta p and force direction.",
        examPhrasing: "State positive direction explicitly and keep signed velocities throughout.",
        confusionPair: "speed vs velocity",
        tags: ["signs", "exam-technique"],
      },
      {
        id: "t3-1-f9",
        noteId: "t3-1",
        difficulty: 4,
        front: "When mass changes, why is momentum form safer than F = ma?",
        back: "Because F = dp/dt remains valid, while F = ma assumes constant mass.",
        examPhrasing: "Use rate of change of momentum when system mass is not constant.",
        confusionPair: "rocket motion vs constant-mass motion",
        tags: ["variable-mass", "law-application"],
      },
      {
        id: "t3-1-f10",
        noteId: "t3-1",
        difficulty: 5,
        front: "A question asks for 'impulse by the floor'. Why might this differ from m Delta v?",
        back: "m Delta v is net impulse from all forces; floor impulse excludes weight impulse.",
        examPhrasing: "Identify whether impulse requested is net or from a specific force.",
        confusionPair: "net impulse vs single-force impulse",
        tags: ["advanced-reasoning", "impulse"],
      },
    ] as const,
  },
  "t3-2": {
    noteId: "t3-2",
    drills: [
      {
        id: "t3-2-d1",
        noteId: "t3-2",
        kind: "mcq",
        difficulty: 1,
        stem: "For an object moving through air, drag force acts in which direction?",
        options: [
          { id: "A", text: "Always upward" },
          { id: "B", text: "Always downward" },
          { id: "C", text: "Opposite to velocity" },
          { id: "D", text: "In direction of acceleration" },
        ] as const,
        correctOptionId: "C",
        explanation: "Drag opposes relative motion between object and fluid.",
        distractorRationale: {
          B: "Direction depends on velocity, not fixed downward.",
          D: "Acceleration direction is set by resultant force, not drag alone.",
        },
        tags: ["drag", "qualitative-forces"],
      },
      {
        id: "t3-2-d2",
        noteId: "t3-2",
        kind: "mcq",
        difficulty: 2,
        stem: "A falling object has reached terminal velocity. Which statement is correct?",
        options: [
          { id: "A", text: "Weight is zero." },
          { id: "B", text: "Drag is zero." },
          { id: "C", text: "Resultant force is zero and speed is constant." },
          { id: "D", text: "Acceleration equals g downward." },
        ] as const,
        correctOptionId: "C",
        explanation:
          "At terminal speed, drag balances weight so resultant force and acceleration are zero.",
        distractorRationale: {
          B: "Drag is not zero; it balances weight.",
          D: "If acceleration were g, speed would still be changing.",
        },
        tags: ["terminal-velocity", "force-balance"],
      },
      {
        id: "t3-2-d3",
        noteId: "t3-2",
        kind: "mcq",
        difficulty: 2,
        stem: "A 0.50 kg object falls with weight 4.9 N and upward drag 1.4 N. What is its acceleration?",
        options: [
          { id: "A", text: "7.0 m s^-2 downward" },
          { id: "B", text: "2.8 m s^-2 downward" },
          { id: "C", text: "2.8 m s^-2 upward" },
          { id: "D", text: "9.8 m s^-2 downward" },
        ] as const,
        correctOptionId: "A",
        explanation:
          "Resultant downward force = 4.9 - 1.4 = 3.5 N. a = F/m = 3.5/0.50 = 7.0 m s^-2 downward.",
        distractorRationale: {
          B: "This halves the force again incorrectly.",
          C: "Direction is wrong because weight exceeds drag.",
          D: "Would only be true if drag were negligible.",
        },
        tags: ["newtons-second-law", "resistive-motion", "calculation"],
      },
      {
        id: "t3-2-d4",
        noteId: "t3-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Describe how speed and acceleration change for an object dropped from rest in air until terminal velocity is reached.",
        modelAnswerPoints: [
          "Initially speed is zero and drag is very small, so acceleration is close to g downward.",
          "As speed increases, drag increases upward.",
          "Resultant downward force decreases, so acceleration decreases in magnitude.",
          "Speed continues to increase but approaches a constant terminal value where acceleration becomes zero.",
        ],
        workedSolution: [
          "Start from force balance at release: weight dominates.",
          "Link larger speed to larger drag qualitatively.",
          "Translate changing resultant force into changing acceleration via F = ma.",
          "Conclude with balanced forces and constant speed at terminal velocity.",
        ],
        commonMistake: "Stating acceleration stays at g throughout the fall.",
        tags: ["qualitative-description", "terminal-velocity"],
      },
      {
        id: "t3-2-d5",
        noteId: "t3-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A 75 kg cyclist has constant driving force 240 N on level ground. Resistive force is 12v (N), where v is in m s^-1. (a) Find terminal speed. (b) Find acceleration at v = 10 m s^-1.",
        modelAnswerPoints: [
          "At terminal speed, resultant force is zero: 240 = 12v_t.",
          "v_t = 20 m s^-1.",
          "At v = 10, resistive force = 12 x 10 = 120 N.",
          "Resultant force = 240 - 120 = 120 N forward.",
          "a = F/m = 120/75 = 1.6 m s^-2 forward.",
        ],
        workedSolution: [
          "Use force-balance condition for part (a), not kinematics.",
          "For part (b), evaluate drag from the model at stated speed.",
          "Compute resultant force as driving minus resistive.",
          "Apply Newton's second law with total mass.",
          "Check sign: acceleration forward because driving force still exceeds drag.",
        ],
        commonMistake:
          "Using terminal-speed equation in part (b) and setting acceleration to zero at all speeds.",
        tags: ["drag-model", "terminal-speed", "resultant-force"],
      },
      {
        id: "t3-2-d6",
        noteId: "t3-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A ball is projected vertically upward through air. Explain the direction of acceleration during ascent, at the highest point, and during descent before terminal speed.",
        modelAnswerPoints: [
          "During ascent, velocity upward so drag is downward; weight also downward, so acceleration is downward and can exceed g in magnitude.",
          "At highest point, speed is instantaneously zero so drag is very small; acceleration is approximately g downward due to weight.",
          "During descent, velocity downward so drag is upward; acceleration remains downward but less than g in magnitude.",
          "As descent continues, acceleration tends to zero as terminal speed is approached.",
        ],
        workedSolution: [
          "Determine drag direction from velocity at each phase.",
          "Add weight direction, which is always downward.",
          "Infer resultant force direction and relative size.",
          "Map resultant force to acceleration direction and magnitude.",
        ],
        commonMistake: "Claiming acceleration is zero at the top because velocity is zero.",
        tags: ["upward-projection", "air-resistance", "conceptual"],
      },
      {
        id: "t3-2-d7",
        noteId: "t3-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A 0.80 kg object falls with drag force D = 0.40v^2 (N), where v is downward speed in m s^-1. Take g = 9.8 m s^-2. (a) Derive an expression for acceleration in terms of v. (b) Find acceleration at v = 3.0 m s^-1. (c) Find terminal speed.",
        modelAnswerPoints: [
          "Take downward positive: resultant force = mg - D = 0.80 x 9.8 - 0.40v^2.",
          "a = (mg - 0.40v^2)/0.80 = 9.8 - 0.50v^2.",
          "At v = 3.0: a = 9.8 - 0.50(9) = 5.3 m s^-2 downward.",
          "Terminal speed when a = 0: 9.8 - 0.50v_t^2 = 0.",
          "v_t^2 = 19.6 so v_t = 4.43 m s^-1.",
        ],
        workedSolution: [
          "Write force equation with consistent sign convention before substituting numbers.",
          "Substitute D model into Newton's second law and simplify.",
          "Evaluate expression at the given speed for part (b).",
          "Use a = 0 condition for terminal speed and solve algebraically.",
          "Reject negative root for speed magnitude.",
        ],
        commonMistake: "Taking drag in the same direction as weight while object is descending.",
        tags: ["speed-dependent-drag", "terminal-condition", "algebraic-modelling"],
      },
      {
        id: "t3-2-d8",
        noteId: "t3-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Two spheres of same size but masses 0.20 kg and 0.60 kg are dropped in air from rest. Explain, using force arguments, which has the greater terminal speed.",
        modelAnswerPoints: [
          "For similar size/shape, drag at a given speed is approximately similar for both.",
          "Heavier sphere has larger weight mg.",
          "Terminal speed occurs when drag equals weight.",
          "To balance larger weight, heavier sphere needs larger drag, requiring higher speed.",
          "Hence the 0.60 kg sphere has greater terminal speed.",
        ],
        workedSolution: [
          "Compare weights first using W = mg.",
          "State terminal condition D = W.",
          "Use qualitative relation that drag increases with speed.",
          "Infer which sphere needs larger speed for drag to match its weight.",
          "Conclude with a clear comparative statement.",
        ],
        commonMistake: "Saying both terminal speeds are equal because both experience the same g.",
        tags: ["comparative-reasoning", "terminal-velocity", "qualitative-forces"],
      },
      {
        id: "t3-2-d9",
        noteId: "t3-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A parachutist of mass 82 kg descends at 54 m s^-1 just before parachute deployment. Immediately after deployment, upward drag becomes 1800 N while weight is unchanged. (a) Find acceleration just after deployment. (b) Explain how speed and acceleration evolve afterward until new terminal speed.",
        modelAnswerPoints: [
          "Weight W = mg = 82 x 9.8 = 804 N downward.",
          "Net force just after opening = 1800 - 804 = 996 N upward.",
          "a = F/m = 996/82 = 12.1 m s^-2 upward.",
          "Because velocity is still downward initially, upward acceleration means rapid deceleration.",
          "As speed falls, drag decreases, so upward resultant decreases.",
          "Eventually drag equals weight; acceleration becomes zero at a lower terminal downward speed.",
        ],
        workedSolution: [
          "Choose downward as positive or upward as positive, but keep signs consistent.",
          "Compute forces immediately after canopy opens at the stated instant.",
          "Determine acceleration from resultant force and mass.",
          "Interpret sign physically relative to current motion direction.",
          "Describe feedback process: lower speed -> lower drag -> smaller upward resultant.",
          "End with balanced-force condition at new terminal speed.",
        ],
        commonMistake:
          "Assuming upward acceleration means immediate upward motion rather than downward motion slowing first.",
        tags: ["parachute-dynamics", "transient-motion", "high-difficulty"],
      },
      {
        id: "t3-2-d10",
        noteId: "t3-2",
        kind: "structured",
        difficulty: 5,
        marks: 8,
        stem: "Sketch and annotate qualitative (i) v-t and (ii) a-t graphs for a body dropped from rest in air with significant drag. Then state what graph features would differ in vacuum.",
        modelAnswerPoints: [
          "v-t in air: starts at 0, rises with decreasing gradient, approaches horizontal asymptote at terminal speed.",
          "a-t in air: starts near g downward, decreases toward 0 as drag builds.",
          "Both graphs should be linked by gradient relation: gradient of v-t is a.",
          "In vacuum: v-t is straight line through origin with constant gradient g.",
          "In vacuum: a-t is horizontal line at g (constant).",
          "No terminal speed in vacuum because no drag.",
        ],
        workedSolution: [
          "Use force argument to set initial acceleration and later change.",
          "Translate acceleration behavior to v-t curvature.",
          "State asymptotic behavior explicitly for terminal speed case.",
          "Contrast with vacuum where only weight acts so acceleration is constant.",
          "Check internal consistency between the two sketches.",
        ],
        commonMistake:
          "Drawing v-t as linear in air or drawing a-t crossing below zero during normal fall from rest.",
        tags: ["graph-interpretation", "qualitative-modelling", "exam-style"],
      },
    ] as const,
    flashcards: [
      {
        id: "t3-2-f1",
        noteId: "t3-2",
        difficulty: 1,
        front: "How does drag generally vary with speed in this syllabus context?",
        back: "Drag increases as speed increases.",
        examPhrasing: "A larger speed through a fluid gives a larger resistive force.",
        confusionPair: "constant drag vs speed-dependent drag",
        tags: ["drag", "core-idea"],
      },
      {
        id: "t3-2-f2",
        noteId: "t3-2",
        difficulty: 1,
        front: "Define terminal velocity.",
        back: "The constant speed reached when resultant force is zero.",
        examPhrasing: "Terminal speed occurs when drag equals weight for vertical fall.",
        confusionPair: "terminal velocity vs zero velocity",
        tags: ["terminal-velocity", "definitions"],
      },
      {
        id: "t3-2-f3",
        noteId: "t3-2",
        difficulty: 2,
        front: "Why is initial acceleration of a dropped object in air close to g?",
        back: "At release speed is near zero, so drag is very small and weight dominates.",
        examPhrasing: "Resultant force is initially approximately mg downward.",
        confusionPair: "initial vs terminal conditions",
        tags: ["falling-motion", "acceleration"],
      },
      {
        id: "t3-2-f4",
        noteId: "t3-2",
        difficulty: 2,
        front: "At terminal velocity, do forces vanish?",
        back: "No. Forces are non-zero but balanced, giving zero resultant force.",
        examPhrasing: "Constant speed implies zero acceleration, not zero forces.",
        confusionPair: "balanced forces vs no forces",
        tags: ["force-balance", "exam-pitfall"],
      },
      {
        id: "t3-2-f5",
        noteId: "t3-2",
        difficulty: 3,
        front: "For an object moving upward in air, what are directions of weight and drag?",
        back: "Both weight and drag act downward.",
        examPhrasing: "Drag always opposes velocity, so during ascent it acts downward.",
        confusionPair: "drag direction vs motion direction",
        tags: ["upward-motion", "forces"],
      },
      {
        id: "t3-2-f6",
        noteId: "t3-2",
        difficulty: 3,
        front: "Can speed increase while acceleration decreases in magnitude?",
        back: "Yes. In falling with drag, speed rises while acceleration drops from near g to 0.",
        examPhrasing: "A positive velocity gradient can reduce with time while remaining positive.",
        confusionPair: "speeding up vs increasing acceleration",
        tags: ["kinematics", "qualitative-graphs"],
      },
      {
        id: "t3-2-f7",
        noteId: "t3-2",
        difficulty: 3,
        front: "What condition determines terminal speed in horizontal driving problems?",
        back: "Driving force equals resistive force, so resultant force is zero.",
        examPhrasing: "Set forward and resistive forces equal to solve for limiting speed.",
        confusionPair: "equilibrium vs rest",
        tags: ["driving-force", "terminal-speed"],
      },
      {
        id: "t3-2-f8",
        noteId: "t3-2",
        difficulty: 4,
        front: "At the highest point of vertical motion in air, is acceleration zero?",
        back: "No. Velocity is zero instantaneously, but weight still gives downward acceleration.",
        examPhrasing: "Zero velocity does not imply zero acceleration.",
        confusionPair: "v=0 vs a=0",
        tags: ["projection", "conceptual-pitfall"],
      },
      {
        id: "t3-2-f9",
        noteId: "t3-2",
        difficulty: 4,
        front: "Why does a heavier object of similar shape often have higher terminal speed?",
        back: "It has larger weight, so requires larger drag to balance; larger drag needs higher speed.",
        examPhrasing: "Greater mg shifts force balance to a higher speed.",
        confusionPair: "effect of mass on terminal speed",
        tags: ["comparative-dynamics", "terminal-velocity"],
      },
      {
        id: "t3-2-f10",
        noteId: "t3-2",
        difficulty: 5,
        front: "In parachute deployment, how can acceleration be upward while velocity is downward?",
        back: "If drag exceeds weight, resultant force is upward, so the downward motion decelerates.",
        examPhrasing: "Acceleration direction follows resultant force, not velocity direction.",
        confusionPair: "sign of velocity vs sign of acceleration",
        tags: ["advanced-sign-reasoning", "parachute-motion"],
      },
    ] as const,
  },
  "t3-3": {
    noteId: "t3-3",
    drills: [
      {
        id: "t3-3-d1",
        noteId: "t3-3",
        kind: "mcq",
        difficulty: 1,
        stem: "Which condition is required for conservation of linear momentum of a system?",
        options: [
          { id: "A", text: "No internal forces act." },
          { id: "B", text: "Resultant external force is zero (or external impulse is negligible)." },
          { id: "C", text: "Kinetic energy is constant." },
          { id: "D", text: "All bodies have equal mass." },
        ] as const,
        correctOptionId: "B",
        explanation:
          "Momentum is conserved when resultant external force on the chosen system is zero.",
        distractorRationale: {
          C: "Kinetic energy is only conserved in elastic collisions, not all momentum-conserving ones.",
          D: "Equal masses are not required for momentum conservation.",
        },
        tags: ["conservation-condition", "definitions"],
      },
      {
        id: "t3-3-d2",
        noteId: "t3-3",
        kind: "mcq",
        difficulty: 2,
        stem: "A 0.40 kg cart at +5.0 m s^-1 sticks to a 0.60 kg cart at rest on a smooth track. Common velocity is:",
        options: [
          { id: "A", text: "+2.0 m s^-1" },
          { id: "B", text: "+3.0 m s^-1" },
          { id: "C", text: "+5.0 m s^-1" },
          { id: "D", text: "-2.0 m s^-1" },
        ] as const,
        correctOptionId: "A",
        explanation:
          "Initial momentum = 0.40 x 5.0 = 2.0. Total mass = 1.0 kg. v = 2.0/1.0 = +2.0 m s^-1.",
        distractorRationale: {
          B: "Would imply momentum increase without external impulse.",
          C: "Would ignore increased combined mass after sticking.",
          D: "Direction wrong; initial momentum is positive.",
        },
        tags: ["inelastic-collision", "calculation"],
      },
      {
        id: "t3-3-d3",
        noteId: "t3-3",
        kind: "mcq",
        difficulty: 2,
        stem: "In a head-on elastic collision, which additional relation is valid (besides momentum conservation)?",
        options: [
          { id: "A", text: "Relative speed of approach equals relative speed of separation." },
          { id: "B", text: "Both objects have equal momentum after collision." },
          { id: "C", text: "Objects must stick together." },
          { id: "D", text: "Total momentum after collision is zero." },
        ] as const,
        correctOptionId: "A",
        explanation:
          "For elastic head-on collisions, either KE is conserved or relative approach speed equals relative separation speed.",
        distractorRationale: {
          B: "Not generally true; depends on masses and initial speeds.",
          C: "Sticking indicates perfectly inelastic, not elastic.",
          D: "Only true if initial total momentum is zero.",
        },
        tags: ["elastic-collision", "extra-condition"],
      },
      {
        id: "t3-3-d4",
        noteId: "t3-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain why internal forces do not change total momentum of a system.",
        modelAnswerPoints: [
          "Internal forces occur in equal and opposite pairs between parts of the system.",
          "Their impulses are equal and opposite over the same interaction time.",
          "So net internal impulse on the whole system is zero.",
          "Only external impulse can change total system momentum.",
        ],
        workedSolution: [
          "Use Newton's third law to justify equal and opposite internal force pairs.",
          "Translate force-pair idea into impulse-pair cancellation.",
          "Conclude with external impulse criterion for total momentum change.",
        ],
        commonMistake: "Saying internal forces are absent rather than present but self-cancelling in total.",
        tags: ["system-thinking", "impulse-view"],
      },
      {
        id: "t3-3-d5",
        noteId: "t3-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Cart A (0.50 kg) at +3.2 m s^-1 collides with cart B (0.30 kg) at -1.0 m s^-1. After collision, A moves at +1.4 m s^-1. Find B's velocity after collision.",
        modelAnswerPoints: [
          "Initial momentum p_i = (0.50)(3.2) + (0.30)(-1.0) = 1.6 - 0.3 = 1.3 kg m s^-1.",
          "Final momentum p_f = (0.50)(1.4) + 0.30v_B = 0.7 + 0.30v_B.",
          "Set p_i = p_f: 1.3 = 0.7 + 0.30v_B.",
          "0.30v_B = 0.6 so v_B = +2.0 m s^-1.",
        ],
        workedSolution: [
          "Write signed momenta for each object before collision.",
          "Express unknown final momentum with algebraic variable.",
          "Apply conservation in one dimension and solve linear equation.",
          "Interpret sign of final answer to state direction.",
        ],
        commonMistake:
          "Using speeds without signs, especially for the cart initially moving in negative direction.",
        tags: ["1d-collision", "signed-velocity", "conservation"],
      },
      {
        id: "t3-3-d6",
        noteId: "t3-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A 0.25 kg lump of clay at 8.0 m s^-1 strikes and sticks to a 0.75 kg block at rest on a smooth surface. Find final speed and percentage loss of kinetic energy.",
        modelAnswerPoints: [
          "Momentum before = 0.25 x 8.0 = 2.0 kg m s^-1.",
          "Total mass after = 1.00 kg, so v = 2.0/1.00 = 2.0 m s^-1.",
          "Initial KE = 0.5 x 0.25 x 8.0^2 = 8.0 J.",
          "Final KE = 0.5 x 1.00 x 2.0^2 = 2.0 J.",
          "Percentage loss = (8.0 - 2.0)/8.0 x 100 = 75%.",
        ],
        workedSolution: [
          "Use momentum conservation first because sticking collision is inelastic.",
          "Then evaluate KE before and after separately.",
          "Compare to quantify energy transformed to non-kinetic forms.",
          "State final percentage clearly with units where relevant.",
        ],
        commonMistake: "Assuming KE is conserved because momentum is conserved.",
        tags: ["inelastic-collision", "energy-change", "calculation"],
      },
      {
        id: "t3-3-d7",
        noteId: "t3-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A 0.40 kg trolley moving at +5.0 m s^-1 collides elastically head-on with a 0.60 kg trolley moving at -1.0 m s^-1. Find both final velocities.",
        modelAnswerPoints: [
          "Momentum equation: 0.40(5.0) + 0.60(-1.0) = 0.40v1 + 0.60v2, so 1.4 = 0.40v1 + 0.60v2.",
          "Elastic relative-speed condition: speed of approach = speed of separation.",
          "Approach speed = 5.0 - (-1.0) = 6.0, so v2 - v1 = 6.0.",
          "Solve simultaneously to get v1 = -2.2 m s^-1 and v2 = +3.8 m s^-1.",
        ],
        workedSolution: [
          "Set up conservation of momentum with signed velocities.",
          "Add second independent equation using elastic-collision relation.",
          "Rearrange relative-speed equation into linear form in v1, v2.",
          "Substitute into momentum equation and solve.",
          "Check physically: lighter trolley reverses direction; heavier moves right faster.",
        ],
        commonMistake:
          "Using v1 - v2 = 6.0 without attention to order, causing swapped or wrong-sign answers.",
        tags: ["elastic-collision", "simultaneous-equations", "advanced-1d"],
      },
      {
        id: "t3-3-d8",
        noteId: "t3-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A 0.20 kg firework shell moving east at 12 m s^-1 explodes into two fragments: 0.05 kg and 0.15 kg. The 0.05 kg fragment moves north at 20 m s^-1. Find velocity vector of the 0.15 kg fragment.",
        modelAnswerPoints: [
          "Initial momentum: p_x = 0.20 x 12 = 2.4 kg m s^-1 east, p_y = 0.",
          "Fragment 1 momentum: p1_x = 0, p1_y = 0.05 x 20 = 1.0 kg m s^-1 north.",
          "Conservation in x: 2.4 = 0 + 0.15v2x -> v2x = 16 m s^-1 east.",
          "Conservation in y: 0 = 1.0 + 0.15v2y -> v2y = -6.67 m s^-1 (south).",
          "Speed = sqrt(16^2 + 6.67^2) = 17.3 m s^-1.",
          "Direction = tan^-1(6.67/16) = 22.6 degrees south of east.",
        ],
        workedSolution: [
          "Resolve total momentum into perpendicular axes before and after explosion.",
          "Use two separate conservation equations, one per axis.",
          "Solve component velocities for the second fragment.",
          "Recombine components for magnitude and direction.",
          "Include directional wording with compass convention.",
        ],
        commonMistake: "Trying to conserve speed instead of vector momentum components.",
        tags: ["2d-momentum", "explosion", "vector-components"],
      },
      {
        id: "t3-3-d9",
        noteId: "t3-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A 0.12 kg ball strikes a bat and rebounds. Ball momentum changes from +0.48 to -1.20 kg m s^-1 in 8.0 ms. (a) Find impulse on ball and average force on ball. (b) State impulse on bat by ball.",
        modelAnswerPoints: [
          "Delta p_ball = -1.20 - (+0.48) = -1.68 N s.",
          "Impulse on ball is -1.68 N s (opposite initial positive direction).",
          "Average force on ball F = Delta p / Delta t = -1.68/0.0080 = -210 N.",
          "By Newton's third law, impulse on bat by ball is +1.68 N s.",
          "Magnitudes equal, directions opposite on different bodies.",
        ],
        workedSolution: [
          "Use signed momentum values directly to compute impulse.",
          "Convert milliseconds to seconds before force calculation.",
          "Interpret sign as direction for force on ball.",
          "Apply action-reaction impulse symmetry for bat impulse.",
          "State clearly that equal/opposite impulses act on different bodies.",
        ],
        commonMistake:
          "Giving same signed impulse for both ball and bat instead of opposite directions.",
        tags: ["impulse", "third-law", "collision-analysis"],
      },
      {
        id: "t3-3-d10",
        noteId: "t3-3",
        kind: "structured",
        difficulty: 5,
        marks: 8,
        stem: "Two skaters on frictionless ice push apart. Initially both are at rest. Skater A has mass 52 kg and moves west at 1.8 m s^-1 after push-off. Skater B has mass 68 kg. (a) Find B's velocity. (b) If push contact lasts 0.40 s, find average interaction force magnitude on each skater and explain equality.",
        modelAnswerPoints: [
          "Initial total momentum is zero.",
          "Take east positive: p_A = 52(-1.8) = -93.6 kg m s^-1.",
          "So p_B = +93.6 kg m s^-1 and v_B = 93.6/68 = +1.38 m s^-1 east.",
          "Impulse magnitude on each skater equals magnitude of momentum change = 93.6 N s.",
          "Average force magnitude = J/Delta t = 93.6/0.40 = 234 N.",
          "Forces are equal in magnitude and opposite in direction by Newton's third law.",
        ],
        workedSolution: [
          "Use system momentum conservation for part (a), with explicit sign convention.",
          "Compute momentum change of either skater from rest to final state.",
          "Convert that momentum change to impulse magnitude over contact time.",
          "Calculate average force from impulse/time.",
          "Explain equality of force magnitudes via third-law interaction pair.",
        ],
        commonMistake:
          "Assuming heavier skater experiences larger force rather than equal force over same contact time.",
        tags: ["momentum-from-rest", "interaction-forces", "high-difficulty"],
      },
    ] as const,
    flashcards: [
      {
        id: "t3-3-f1",
        noteId: "t3-3",
        difficulty: 1,
        front: "State conservation of linear momentum.",
        back: "Total linear momentum of a system remains constant if resultant external force is zero.",
        examPhrasing: "Momentum before interaction equals momentum after interaction for an isolated system.",
        confusionPair: "momentum conservation vs force balance on one object",
        tags: ["conservation", "definitions"],
      },
      {
        id: "t3-3-f2",
        noteId: "t3-3",
        difficulty: 1,
        front: "What is the key sign rule in 1D collision calculations?",
        back: "Use signed velocities, not speeds.",
        examPhrasing: "Choose positive direction and retain algebraic signs throughout.",
        confusionPair: "speed vs velocity",
        tags: ["sign-convention", "exam-technique"],
      },
      {
        id: "t3-3-f3",
        noteId: "t3-3",
        difficulty: 2,
        front: "What type of collision is it when objects stick together?",
        back: "Perfectly inelastic collision.",
        examPhrasing: "Bodies move with a common velocity after impact.",
        confusionPair: "inelastic vs elastic",
        tags: ["collision-types", "definitions"],
      },
      {
        id: "t3-3-f4",
        noteId: "t3-3",
        difficulty: 2,
        front: "Is kinetic energy always conserved when momentum is conserved?",
        back: "No. KE is conserved only in elastic collisions.",
        examPhrasing: "Momentum conservation does not imply kinetic-energy conservation.",
        confusionPair: "momentum vs kinetic-energy conservation",
        tags: ["energy-distinction", "pitfalls"],
      },
      {
        id: "t3-3-f5",
        noteId: "t3-3",
        difficulty: 3,
        front: "How do you solve 2D momentum problems?",
        back: "Resolve momenta into perpendicular components and conserve each component separately.",
        examPhrasing: "Apply sum p_x before = sum p_x after and sum p_y before = sum p_y after.",
        confusionPair: "vector sum vs scalar speed",
        tags: ["2d-method", "vectors"],
      },
      {
        id: "t3-3-f6",
        noteId: "t3-3",
        difficulty: 3,
        front: "What additional relation can be used in head-on elastic collisions?",
        back: "Relative speed of approach equals relative speed of separation.",
        examPhrasing: "Along line of impact: u1 - u2 = -(v1 - v2).",
        confusionPair: "elastic relation vs momentum equation",
        tags: ["elastic-collision", "equations"],
      },
      {
        id: "t3-3-f7",
        noteId: "t3-3",
        difficulty: 3,
        front: "In explosion problems, why can fragments move in opposite directions from rest?",
        back: "Initial momentum is zero, so vector sum of final fragment momenta must be zero.",
        examPhrasing: "Fragment momenta are equal and opposite in total.",
        confusionPair: "explosion energy release vs momentum conservation",
        tags: ["explosions", "vector-balance"],
      },
      {
        id: "t3-3-f8",
        noteId: "t3-3",
        difficulty: 4,
        front: "What is external impulse's role in momentum change of a system?",
        back: "External impulse equals change in total system momentum.",
        examPhrasing: "Delta p_system = integral(F_external dt).",
        confusionPair: "internal vs external impulse",
        tags: ["impulse-formulation", "system-choice"],
      },
      {
        id: "t3-3-f9",
        noteId: "t3-3",
        difficulty: 4,
        front: "Why do internal interaction forces not appear in system-level momentum equations?",
        back: "Their impulses cancel in pairs, so net internal contribution to total momentum change is zero.",
        examPhrasing: "Only external forces can alter total momentum of the chosen system.",
        confusionPair: "single-body forces vs system forces",
        tags: ["internal-forces", "reasoning"],
      },
      {
        id: "t3-3-f10",
        noteId: "t3-3",
        difficulty: 5,
        front: "A marker asks for a conservation statement before equations. What should you write?",
        back: "State that external horizontal forces are negligible during collision, therefore total horizontal momentum is conserved.",
        examPhrasing: "Because resultant external impulse is negligible over impact, momentum before equals momentum after.",
        confusionPair: "stating condition vs jumping to formula",
        tags: ["exam-style", "justification"],
      },
    ] as const,
  },
};
