import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC8_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t8-1": {
    noteId: "t8-1",
    drills: [
      {
        id: "t8-1-d1",
        noteId: "t8-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which condition is required for a stationary wave to form?",
        options: [
          { id: "A", text: "One progressive wave only" },
          { id: "B", text: "Two coherent waves of same frequency traveling in opposite directions" },
          { id: "C", text: "Two waves with equal speed traveling in the same direction" },
          { id: "D", text: "Any two waves with different frequencies" },
        ],
        correctOptionId: "B",
        explanation:
          "Stationary waves form when two coherent waves of the same frequency and similar amplitude superpose while traveling oppositely.",
        distractorRationale: {
          C: "Waves in the same direction produce another progressive wave pattern.",
          D: "Different frequencies do not produce stable stationary nodes.",
        },
        tags: ["stationary-waves", "superposition", "conditions"],
      },
      {
        id: "t8-1-d2",
        noteId: "t8-1",
        kind: "mcq",
        difficulty: 2,
        stem: "In a stationary wave, the distance between two adjacent nodes is",
        options: [
          { id: "A", text: "lambda/4" },
          { id: "B", text: "lambda/2" },
          { id: "C", text: "lambda" },
          { id: "D", text: "2lambda" },
        ],
        correctOptionId: "B",
        explanation:
          "Node-to-node spacing in a stationary wave is half a wavelength, while node-to-nearest-antinode is quarter wavelength.",
        distractorRationale: {
          C: "A full wavelength spans every second node, not adjacent ones.",
          D: "This is too large by a factor of four.",
        },
        tags: ["nodes", "wavelength", "geometry"],
      },
      {
        id: "t8-1-d3",
        noteId: "t8-1",
        kind: "mcq",
        difficulty: 3,
        stem:
          "A string fixed at both ends has length 0.80 m and wave speed 160 m s^-1. What is the fundamental frequency?",
        options: [
          { id: "A", text: "100 Hz" },
          { id: "B", text: "160 Hz" },
          { id: "C", text: "200 Hz" },
          { id: "D", text: "320 Hz" },
        ],
        correctOptionId: "A",
        explanation:
          "For the first harmonic on a string fixed at both ends, lambda = 2L = 1.60 m, so f = v/lambda = 160/1.60 = 100 Hz.",
        distractorRationale: {
          B: "This ignores the 2L condition for the fundamental wavelength.",
          C: "This incorrectly uses lambda = L/2.",
          D: "This is the second harmonic value multiplied again in error.",
        },
        tags: ["harmonics", "strings", "fundamental-frequency"],
      },
      {
        id: "t8-1-d4",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define node and antinode for a stationary wave and state their displacement behavior.",
        modelAnswerPoints: [
          "A node is a point of zero displacement at all times.",
          "An antinode is a point of maximum displacement amplitude.",
          "Different points between nodes oscillate in phase within one loop but adjacent loops are in antiphase.",
        ],
        workedSolution: [
          "Use displacement language, not intensity language.",
          "State the permanent zero condition for nodes explicitly.",
          "Include the phase relationship for exam completeness.",
        ],
        commonMistake: "Saying nodes are points where particles are always at maximum speed.",
        tags: ["definitions", "nodes", "antinodes"],
      },
      {
        id: "t8-1-d5",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A stationary wave on a rope has adjacent nodes 0.30 m apart. Calculate the wavelength and the distance from a node to the nearest antinode.",
        modelAnswerPoints: [
          "Adjacent node spacing = lambda/2.",
          "So lambda = 2 x 0.30 = 0.60 m.",
          "Node-to-nearest-antinode spacing = lambda/4.",
          "Hence distance = 0.60/4 = 0.15 m.",
        ],
        workedSolution: [
          "Start from the standard node spacing relation.",
          "Find lambda first, then use quarter-wavelength for node-antinode separation.",
          "Quote both values with consistent units.",
        ],
        commonMistake: "Taking node spacing directly as one full wavelength.",
        tags: ["wavelength", "node-spacing", "calculation"],
      },
      {
        id: "t8-1-d6",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A pipe closed at one end has length 0.25 m and contains air where wave speed is 340 m s^-1. Find the fundamental frequency.",
        modelAnswerPoints: [
          "For closed-end fundamental mode, L = lambda/4.",
          "So lambda = 4L = 1.00 m.",
          "Use f = v/lambda = 340/1.00.",
          "Fundamental frequency = 340 Hz.",
        ],
        workedSolution: [
          "Closed pipe supports a displacement node at closed end and antinode at open end.",
          "That geometry gives quarter-wavelength in the first mode.",
          "Substitute carefully into wave equation.",
        ],
        commonMistake: "Using lambda = 2L, which is for strings/open-open pipes.",
        tags: ["air-columns", "closed-pipe", "fundamental"],
      },
      {
        id: "t8-1-d7",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Explain why no net energy is transferred along a stationary wave, even though points on the medium oscillate.",
        modelAnswerPoints: [
          "A stationary wave is formed by two oppositely directed progressive waves carrying equal energy flux.",
          "Energy transfer in one direction is balanced by equal transfer in the opposite direction.",
          "So there is local oscillatory exchange of kinetic and potential energy but no net transport of energy.",
          "Nodes have zero displacement and no oscillatory energy exchange at that point.",
        ],
        workedSolution: [
          "Separate local oscillation from net propagation.",
          "State explicitly that opposed energy fluxes cancel.",
          "Link this to stationary nodes and antinodes for physical interpretation.",
        ],
        commonMistake: "Claiming stationary waves carry the same net power as progressive waves.",
        tags: ["energy-transfer", "conceptual", "superposition"],
      },
      {
        id: "t8-1-d8",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A stretched string of length 1.20 m fixed at both ends resonates at 150 Hz in the third harmonic.\n(a) Determine the fundamental frequency.\n(b) Determine wave speed on the string.",
        modelAnswerPoints: [
          "For fixed ends, nth harmonic frequency fn = nf1.",
          "Given f3 = 150 Hz, fundamental f1 = 150/3 = 50 Hz.",
          "At fundamental, lambda1 = 2L = 2.40 m.",
          "Wave speed v = f1 lambda1 = 50 x 2.40 = 120 m s^-1.",
        ],
        workedSolution: [
          "Use harmonic ratio first to get f1 from f3.",
          "Then apply geometry of first mode for wavelength.",
          "Finish with v = f lambda using fundamental pair.",
        ],
        commonMistake: "Using lambda = 1.20 m for the fundamental on a string fixed at both ends.",
        tags: ["harmonics", "resonance", "wave-speed"],
      },
      {
        id: "t8-1-d9",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A closed organ pipe has fundamental frequency 220 Hz. Take speed of sound as 330 m s^-1.\n(a) Calculate pipe length.\n(b) State the next two resonant frequencies above fundamental.",
        modelAnswerPoints: [
          "For a closed pipe, f1 = v/(4L).",
          "L = v/(4f1) = 330/(4 x 220) = 0.375 m.",
          "Closed pipe supports odd harmonics only.",
          "Next two resonances are 3f1 = 660 Hz and 5f1 = 1100 Hz.",
        ],
        workedSolution: [
          "Rearrange quarter-wave equation to obtain L.",
          "Remember mode pattern for closed pipes excludes even multiples.",
          "List higher resonances in ascending order.",
        ],
        commonMistake: "Giving 440 Hz as the next resonance as if even harmonics were allowed.",
        tags: ["closed-pipe", "odd-harmonics", "resonance"],
      },
      {
        id: "t8-1-d10",
        noteId: "t8-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A sonometer string is adjusted to produce resonance with a 256 Hz tuning fork at length 0.625 m in the first mode.\n(a) Calculate wave speed.\n(b) If tension is increased so speed rises by 25%, calculate the new first-mode resonant frequency for the same length.\n(c) Explain briefly why raising tension raises pitch.",
        modelAnswerPoints: [
          "First mode on fixed string has lambda = 2L = 1.25 m.",
          "Wave speed initially v = f lambda = 256 x 1.25 = 320 m s^-1.",
          "New speed = 1.25 x 320 = 400 m s^-1.",
          "New frequency f = v/lambda = 400/1.25 = 320 Hz.",
          "Higher tension increases wave speed, so mode frequencies increase for fixed length.",
        ],
        workedSolution: [
          "Use standing-wave geometry before numeric substitution.",
          "Apply percentage increase directly to speed, then recalculate frequency with unchanged lambda.",
          "Conclude with physical relation between tension, speed, and pitch.",
        ],
        commonMistake: "Assuming wavelength changes in the first mode when string length is unchanged.",
        tags: ["sonometer", "tension", "exam-application"],
      },
    ],
    flashcards: [
      {
        id: "t8-1-f1",
        noteId: "t8-1",
        difficulty: 1,
        front: "What condition forms a stationary wave?",
        back: "Two coherent waves of the same frequency traveling in opposite directions superpose.",
        examPhrasing:
          "Stationary waves arise from superposition of equal-frequency opposite-traveling waves.",
        tags: ["stationary-waves", "conditions"],
      },
      {
        id: "t8-1-f2",
        noteId: "t8-1",
        difficulty: 1,
        front: "Define a node in a stationary wave.",
        back: "A node is a point of zero displacement at all times.",
        examPhrasing: "Node: permanent zero amplitude point.",
        tags: ["node", "definition"],
      },
      {
        id: "t8-1-f3",
        noteId: "t8-1",
        difficulty: 2,
        front: "Define an antinode in a stationary wave.",
        back: "An antinode is a point where displacement amplitude is maximum.",
        examPhrasing: "Antinode: point of greatest oscillation amplitude.",
        tags: ["antinode", "definition"],
      },
      {
        id: "t8-1-f4",
        noteId: "t8-1",
        difficulty: 2,
        front: "Distance between adjacent nodes equals what fraction of wavelength?",
        back: "lambda/2.",
        examPhrasing: "Node-to-node spacing is half a wavelength.",
        confusionPair: "node-node spacing vs node-antinode spacing",
        tags: ["wavelength", "spacing"],
      },
      {
        id: "t8-1-f5",
        noteId: "t8-1",
        difficulty: 3,
        front: "For a string fixed at both ends, what is the fundamental wavelength?",
        back: "lambda1 = 2L.",
        examPhrasing: "First harmonic on a fixed string contains half a wavelength in the length.",
        tags: ["strings", "fundamental-mode"],
      },
      {
        id: "t8-1-f6",
        noteId: "t8-1",
        difficulty: 3,
        front: "For a pipe closed at one end, what is the fundamental wavelength?",
        back: "lambda1 = 4L.",
        examPhrasing: "First mode in a closed pipe is a quarter-wave mode.",
        confusionPair: "closed-pipe quarter wave vs open-open half wave",
        tags: ["air-columns", "closed-pipe"],
      },
      {
        id: "t8-1-f7",
        noteId: "t8-1",
        difficulty: 4,
        front: "Why is there no net energy transfer in a stationary wave?",
        back: "Equal energy flows in opposite directions cancel, so no net power travels along the medium.",
        examPhrasing: "Stationary waves store and exchange energy locally without net transport.",
        tags: ["energy", "conceptual"],
      },
      {
        id: "t8-1-f8",
        noteId: "t8-1",
        difficulty: 4,
        front: "Which harmonics are allowed in a pipe closed at one end?",
        back: "Only odd harmonics: f1, 3f1, 5f1, ...",
        examPhrasing: "Even harmonics are absent in a closed-open air column.",
        tags: ["harmonics", "resonance"],
      },
      {
        id: "t8-1-f9",
        noteId: "t8-1",
        difficulty: 5,
        front: "State the harmonic frequency relation for a string fixed at both ends.",
        back: "fn = n f1, for n = 1, 2, 3, ...",
        examPhrasing: "All integer harmonics are supported for fixed-fixed boundaries.",
        tags: ["harmonics", "formula"],
      },
      {
        id: "t8-1-f10",
        noteId: "t8-1",
        difficulty: 5,
        front: "Exam check: why must displacement nodes and pressure nodes not be confused in air columns?",
        back: "Displacement and pressure standing-wave patterns are quarter-cycle out of phase spatially, so node positions differ by lambda/4.",
        examPhrasing:
          "State clearly whether the question refers to particle displacement or pressure variation.",
        confusionPair: "displacement nodes vs pressure nodes",
        tags: ["exam-technique", "air-columns"],
      },
    ],
  },
  "t8-2": {
    noteId: "t8-2",
    drills: [
      {
        id: "t8-2-d1",
        noteId: "t8-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Diffraction is best described as",
        options: [
          { id: "A", text: "splitting white light into colors" },
          { id: "B", text: "bending/spreading of waves after passing through a gap or around an edge" },
          { id: "C", text: "reflection of light from a plane mirror" },
          { id: "D", text: "complete absorption of waves by a barrier" },
        ],
        correctOptionId: "B",
        explanation:
          "Diffraction is the spreading of waves as they pass through apertures or around obstacles.",
        distractorRationale: {
          C: "Reflection changes direction at a boundary, not spreading from an aperture.",
          D: "Absorption reduces amplitude but is not diffraction.",
        },
        tags: ["diffraction", "definition"],
      },
      {
        id: "t8-2-d2",
        noteId: "t8-2",
        kind: "mcq",
        difficulty: 2,
        stem: "Diffraction is most pronounced when aperture width a is",
        options: [
          { id: "A", text: "much larger than wavelength lambda" },
          { id: "B", text: "about equal to wavelength lambda" },
          { id: "C", text: "independent of wavelength" },
          { id: "D", text: "zero regardless of wavelength" },
        ],
        correctOptionId: "B",
        explanation:
          "Strong diffraction occurs when aperture size is comparable to wavelength. If a >> lambda, spreading is small.",
        distractorRationale: {
          C: "Wavelength strongly affects diffraction angle.",
          D: "No aperture means no transmitted wave pattern.",
        },
        tags: ["aperture", "wavelength", "conditions"],
      },
      {
        id: "t8-2-d3",
        noteId: "t8-2",
        kind: "mcq",
        difficulty: 3,
        stem:
          "Monochromatic light of wavelength 500 nm passes through a single slit of width 0.25 mm. Using sin theta = lambda/a for first minimum, what is theta?",
        options: [
          { id: "A", text: "0.11 degrees" },
          { id: "B", text: "1.15 degrees" },
          { id: "C", text: "11.5 degrees" },
          { id: "D", text: "0.011 degrees" },
        ],
        correctOptionId: "A",
        explanation:
          "sin theta = 5.0 x 10^-7 / 2.5 x 10^-4 = 2.0 x 10^-3, so theta approx 0.0020 rad = 0.11 degrees.",
        distractorRationale: {
          B: "Tenfold overestimate from unit conversion slip.",
          C: "Two orders of magnitude too large for these values.",
          D: "Tenfold underestimate from decimal placement error.",
        },
        tags: ["single-slit", "small-angle", "calculation"],
      },
      {
        id: "t8-2-d4",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State two everyday observations that show diffraction of sound and explain briefly why sound diffracts strongly.",
        modelAnswerPoints: [
          "Sound can be heard around corners or through doorways.",
          "Speech is heard from adjacent rooms without line of sight.",
          "Sound wavelengths are comparable to door/gap sizes, so diffraction is significant.",
        ],
        workedSolution: [
          "Give concrete observations then connect to lambda relative to obstacle size.",
          "Use wavelength-size argument explicitly.",
        ],
        commonMistake: "Attributing the effect only to reflection with no mention of diffraction.",
        tags: ["sound", "applications", "wavelength-scale"],
      },
      {
        id: "t8-2-d5",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Light of wavelength 6.0 x 10^-7 m passes through a slit of width 3.0 x 10^-5 m.\nCalculate the first-minimum diffraction angle.",
        modelAnswerPoints: [
          "Use first minimum relation sin theta = lambda/a.",
          "sin theta = (6.0 x 10^-7)/(3.0 x 10^-5) = 2.0 x 10^-2.",
          "theta approx 0.020 rad.",
          "theta approx 1.15 degrees.",
        ],
        workedSolution: [
          "Compute the sine ratio first and check it is much less than 1.",
          "Convert radians to degrees only at final step if needed.",
          "Quote to suitable significant figures.",
        ],
        commonMistake: "Inverting the ratio as a/lambda.",
        tags: ["single-slit", "formula-use", "numerical"],
      },
      {
        id: "t8-2-d6",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A microwave with wavelength 3.0 cm passes through two openings: X has width 1.0 cm, Y has width 12 cm.\nState which opening gives greater diffraction and justify quantitatively.",
        modelAnswerPoints: [
          "Greater diffraction occurs when a is closer to lambda or smaller relative to lambda.",
          "For X: a/lambda = 1.0/3.0 = 0.33.",
          "For Y: a/lambda = 12/3.0 = 4.0.",
          "Therefore X gives much wider spreading.",
        ],
        workedSolution: [
          "Compare non-dimensional ratio a/lambda for both gaps.",
          "Lower ratio corresponds to larger angular spread.",
          "State final comparison clearly.",
        ],
        commonMistake: "Choosing larger opening as having greater diffraction because more wave passes through.",
        tags: ["comparative-reasoning", "microwaves", "aperture-ratio"],
      },
      {
        id: "t8-2-d7",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Describe how a single-slit diffraction pattern changes when slit width is halved while wavelength and screen distance are constant.",
        modelAnswerPoints: [
          "First minima satisfy sin theta = lambda/a.",
          "Halving a doubles theta for each minimum (small-angle approximation context).",
          "So central maximum becomes about twice as wide on the screen.",
          "Pattern spreads out and fringes are further apart.",
        ],
        workedSolution: [
          "Use inverse relation between angular width and slit width.",
          "Translate angular change into screen spacing change at fixed distance.",
          "Mention central maximum explicitly as exam focus.",
        ],
        commonMistake: "Stating brightness increases simply because width decreases without considering transmitted intensity.",
        tags: ["pattern-changes", "single-slit", "analysis"],
      },
      {
        id: "t8-2-d8",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "In a single-slit experiment, slit width is 0.20 mm and screen distance is 2.5 m. Monochromatic light of wavelength 600 nm is used.\n(a) Calculate angular position of first minimum.\n(b) Estimate width of central maximum on the screen.",
        modelAnswerPoints: [
          "First minimum: sin theta = lambda/a = (6.0 x 10^-7)/(2.0 x 10^-4) = 3.0 x 10^-3.",
          "theta approx 3.0 x 10^-3 rad.",
          "Half-width of central maximum y1 approx L theta = 2.5 x 3.0 x 10^-3 = 7.5 x 10^-3 m.",
          "Full central width = 2y1 = 1.5 x 10^-2 m = 1.5 cm.",
        ],
        workedSolution: [
          "Use first-minimum relation and small-angle assumption.",
          "Calculate distance from center to first minimum first.",
          "Double that value to get full central maximum width.",
        ],
        commonMistake: "Reporting y1 as full width instead of half-width.",
        tags: ["screen-geometry", "single-slit", "exam-numerical"],
      },
      {
        id: "t8-2-d9",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Explain why radio waves can diffract around buildings more effectively than visible light, and state one communication consequence.",
        modelAnswerPoints: [
          "Diffraction is stronger when wavelength is comparable with obstacle/aperture size.",
          "Radio wavelengths are much longer than visible-light wavelengths.",
          "So for the same building dimensions, radio has larger diffraction angles.",
          "Consequence: non-line-of-sight reception is more feasible for radio than for optical signals.",
        ],
        workedSolution: [
          "Use relative wavelength scales to compare diffraction strengths.",
          "Avoid vague statements like 'radio is stronger'; focus on geometry and wavelength.",
          "Link physics to communication coverage behavior.",
        ],
        commonMistake: "Claiming visible light cannot diffract at all.",
        tags: ["em-spectrum", "applications", "reasoning"],
      },
      {
        id: "t8-2-d10",
        noteId: "t8-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "An unknown monochromatic source is tested with a single slit of width 1.5 x 10^-4 m. On a screen 3.0 m away, the central maximum width is measured as 2.4 cm.\nEstimate the wavelength and identify likely spectral region.",
        modelAnswerPoints: [
          "Central width w = 2L(lambda/a), so lambda = wa/(2L).",
          "Substitute: lambda = (2.4 x 10^-2)(1.5 x 10^-4)/(2 x 3.0).",
          "lambda = 6.0 x 10^-7 m.",
          "This is about 600 nm, in visible (orange-red) region.",
        ],
        workedSolution: [
          "Relate measured full central width to first-minimum geometry.",
          "Keep powers of ten explicit to avoid arithmetic drift.",
          "Interpret numerical wavelength against EM-spectrum ranges.",
        ],
        commonMistake: "Using w = Llambda/a and forgetting the factor of 2 for full central maximum.",
        tags: ["inverse-problem", "wavelength-estimation", "high-yield"],
      },
    ],
    flashcards: [
      {
        id: "t8-2-f1",
        noteId: "t8-2",
        difficulty: 1,
        front: "What is diffraction?",
        back: "The spreading/bending of waves when passing through gaps or around edges.",
        examPhrasing: "Diffraction is appreciable when aperture size is comparable to wavelength.",
        tags: ["definition", "diffraction"],
      },
      {
        id: "t8-2-f2",
        noteId: "t8-2",
        difficulty: 1,
        front: "When is diffraction strongest?",
        back: "When aperture/obstacle size is of the same order as wavelength.",
        examPhrasing: "Strong diffraction occurs for a approximately lambda.",
        tags: ["conditions", "wavelength"],
      },
      {
        id: "t8-2-f3",
        noteId: "t8-2",
        difficulty: 2,
        front: "Single-slit first-minimum condition?",
        back: "sin theta = lambda/a (for the first minimum).",
        examPhrasing: "For m-th minimum, a sin theta = m lambda.",
        tags: ["single-slit", "formula"],
      },
      {
        id: "t8-2-f4",
        noteId: "t8-2",
        difficulty: 2,
        front: "What happens to diffraction angle if slit width is reduced?",
        back: "Diffraction angle increases (pattern spreads more).",
        examPhrasing: "theta is inversely related to slit width a.",
        confusionPair: "slit width decrease vs fringe width decrease",
        tags: ["trend", "single-slit"],
      },
      {
        id: "t8-2-f5",
        noteId: "t8-2",
        difficulty: 3,
        front: "Why does sound diffract noticeably through doorways?",
        back: "Sound wavelengths are often similar to doorway dimensions, giving large diffraction.",
        examPhrasing: "Comparable wavelength and aperture size causes strong spreading.",
        tags: ["sound", "applications"],
      },
      {
        id: "t8-2-f6",
        noteId: "t8-2",
        difficulty: 3,
        front: "How does central maximum width vary with wavelength in single-slit diffraction?",
        back: "It increases with wavelength.",
        examPhrasing: "Central width w proportional lambda for fixed slit and screen distance.",
        tags: ["pattern-width", "proportionality"],
      },
      {
        id: "t8-2-f7",
        noteId: "t8-2",
        difficulty: 4,
        front: "Why does visible light show little diffraction at ordinary doors/windows?",
        back: "Visible wavelengths are tiny compared with door/window dimensions, so diffraction angles are very small.",
        examPhrasing: "If a >> lambda, spreading is minimal.",
        tags: ["scale-argument", "visible-light"],
      },
      {
        id: "t8-2-f8",
        noteId: "t8-2",
        difficulty: 4,
        front: "State a valid small-angle link between diffraction angle and screen displacement.",
        back: "For small theta, tan theta approx theta approx y/L.",
        examPhrasing: "Use y approx L theta in radians for screen geometry.",
        tags: ["small-angle", "screen-calculation"],
      },
      {
        id: "t8-2-f9",
        noteId: "t8-2",
        difficulty: 5,
        front: "Exam trap: central maximum width in single-slit is measured between which points?",
        back: "Between the first minima on either side of the center (full width = 2y1).",
        examPhrasing: "Do not confuse center-to-first-minimum distance with full central width.",
        confusionPair: "half-width vs full-width",
        tags: ["exam-technique", "measurement"],
      },
      {
        id: "t8-2-f10",
        noteId: "t8-2",
        difficulty: 5,
        front: "How can diffraction be used to estimate wavelength experimentally?",
        back: "Measure diffraction angle or fringe geometry, then rearrange diffraction equations to solve for lambda.",
        examPhrasing: "From single-slit data: lambda = a sin theta (or using screen form).",
        tags: ["experimental-method", "wavelength"],
      },
    ],
  },
  "t8-3": {
    noteId: "t8-3",
    drills: [
      {
        id: "t8-3-d1",
        noteId: "t8-3",
        kind: "mcq",
        difficulty: 1,
        stem: "Constructive interference occurs when path difference between two coherent waves is",
        options: [
          { id: "A", text: "n lambda" },
          { id: "B", text: "(n + 1/2)lambda" },
          { id: "C", text: "lambda/4 only" },
          { id: "D", text: "independent of path difference" },
        ],
        correctOptionId: "A",
        explanation: "Maxima occur when waves arrive in phase: path difference n lambda.",
        distractorRationale: {
          B: "This is the condition for destructive interference.",
          C: "Quarter wavelength is not a general maximum condition.",
        },
        tags: ["interference", "path-difference", "conditions"],
      },
      {
        id: "t8-3-d2",
        noteId: "t8-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which is necessary for a stable two-source interference pattern?",
        options: [
          { id: "A", text: "Large difference in frequencies" },
          { id: "B", text: "Coherent sources with constant phase difference" },
          { id: "C", text: "Any two independent bulbs" },
          { id: "D", text: "Sources of equal amplitude only, regardless of phase" },
        ],
        correctOptionId: "B",
        explanation:
          "Stable fringes require coherence: same frequency and fixed phase relationship over time.",
        distractorRationale: {
          C: "Independent bulbs are not coherent and produce no stable fringes.",
          D: "Equal amplitude alone is insufficient without phase stability.",
        },
        tags: ["coherence", "young-double-slit", "fringes"],
      },
      {
        id: "t8-3-d3",
        noteId: "t8-3",
        kind: "mcq",
        difficulty: 3,
        stem:
          "In Young's double-slit setup, wavelength is 600 nm, slit separation is 0.30 mm, and screen distance is 2.0 m. Fringe spacing is",
        options: [
          { id: "A", text: "1.0 mm" },
          { id: "B", text: "2.0 mm" },
          { id: "C", text: "4.0 mm" },
          { id: "D", text: "0.40 mm" },
        ],
        correctOptionId: "C",
        explanation:
          "Use w = lambda D/a = (6.0 x 10^-7 x 2.0)/(3.0 x 10^-4) = 4.0 x 10^-3 m = 4.0 mm.",
        distractorRationale: {
          B: "This underestimates by factor of two from arithmetic error.",
          D: "This is a tenfold underestimate from unit conversion mistake.",
        },
        tags: ["young-double-slit", "fringe-spacing", "calculation"],
      },
      {
        id: "t8-3-d4",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define coherence and explain why two slits fed by one monochromatic source are coherent.",
        modelAnswerPoints: [
          "Coherent sources emit waves with constant phase difference and same frequency.",
          "A single source split into two paths preserves frequency.",
          "Relative phase remains fixed, so stable interference fringes form.",
        ],
        workedSolution: [
          "Give formal coherence definition first.",
          "Then link physically to wavefront splitting in Young's apparatus.",
        ],
        commonMistake: "Defining coherence as simply equal amplitudes.",
        tags: ["coherence", "definitions", "young-experiment"],
      },
      {
        id: "t8-3-d5",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "In an interference setup, two paths to point P are 2.400 mm and 2.700 mm. Wavelength is 0.300 mm.\nDetermine whether P is a maximum or minimum.",
        modelAnswerPoints: [
          "Path difference = 2.700 - 2.400 = 0.300 mm.",
          "Delta = 1 lambda.",
          "Integer lambda gives constructive interference.",
          "So P is a maximum (bright fringe).",
        ],
        workedSolution: [
          "Compute path difference before deciding fringe type.",
          "Match to constructive or destructive condition using n lambda and (n + 1/2)lambda.",
        ],
        commonMistake: "Using absolute path values without taking difference.",
        tags: ["path-difference", "classification", "fringes"],
      },
      {
        id: "t8-3-d6",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Young's double-slit apparatus has lambda = 500 nm, slit separation a = 0.25 mm, screen distance D = 1.5 m.\nCalculate fringe spacing.",
        modelAnswerPoints: [
          "Use w = lambda D / a.",
          "w = (5.0 x 10^-7 x 1.5)/(2.5 x 10^-4).",
          "w = 3.0 x 10^-3 m.",
          "Fringe spacing = 3.0 mm.",
        ],
        workedSolution: [
          "Convert all values to SI before substitution.",
          "Check answer scale is mm, typical for lab geometry.",
        ],
        commonMistake: "Using wavelength in nm directly without SI conversion.",
        tags: ["young-double-slit", "formula-application", "numerical"],
      },
      {
        id: "t8-3-d7",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Explain how fringe spacing changes if each of the following is increased separately: (i) wavelength, (ii) screen distance, (iii) slit separation.",
        modelAnswerPoints: [
          "From w = lambda D / a.",
          "Increasing wavelength increases fringe spacing.",
          "Increasing screen distance increases fringe spacing.",
          "Increasing slit separation decreases fringe spacing.",
        ],
        workedSolution: [
          "Quote governing proportional relation first.",
          "Then discuss each variable while holding others constant.",
          "Use direct/inverse language clearly.",
        ],
        commonMistake: "Stating all increases make fringes wider.",
        tags: ["proportionality", "young-equation", "conceptual"],
      },
      {
        id: "t8-3-d8",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "In a double-slit experiment, fringe spacing is 1.8 mm when D = 1.2 m and a = 0.40 mm.\n(a) Calculate wavelength.\n(b) Determine new fringe spacing if D is doubled and a is halved.",
        modelAnswerPoints: [
          "Use w = lambda D/a so lambda = wa/D.",
          "lambda = (1.8 x 10^-3)(4.0 x 10^-4)/1.2 = 6.0 x 10^-7 m.",
          "For new setup, w' proportional D/a, so factor change = (2)/(1/2) = 4.",
          "w' = 4 x 1.8 mm = 7.2 mm.",
        ],
        workedSolution: [
          "Part (a): rearrange and substitute in SI.",
          "Part (b): use scaling to avoid repeat long calculation.",
          "Keep track of both geometry changes simultaneously.",
        ],
        commonMistake: "Applying only one geometry change factor in part (b).",
        tags: ["inverse-calculation", "scaling", "fringe-spacing"],
      },
      {
        id: "t8-3-d9",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Two coherent sources emit in phase. At point Q, path lengths are 1.865 m and 1.950 m for wavelength 0.010 m.\n(a) Find phase difference at Q.\n(b) State whether interference is constructive or destructive.",
        modelAnswerPoints: [
          "Path difference Delta = 1.950 - 1.865 = 0.085 m.",
          "Delta/lambda = 0.085/0.010 = 8.5 wavelengths.",
          "Phase difference = 2pi x 8.5 = 17pi rad (equivalent to pi mod 2pi).",
          "Half-integer multiple implies destructive interference (minimum).",
        ],
        workedSolution: [
          "Find fractional wavelength path difference first.",
          "Convert to phase via 2pi(Delta/lambda).",
          "Classify fringe from integer vs half-integer criterion.",
        ],
        commonMistake: "Ignoring the fractional 0.5 in 8.5 and labeling as constructive.",
        tags: ["phase-difference", "classification", "advanced"],
      },
      {
        id: "t8-3-d10",
        noteId: "t8-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A student obtains poor-contrast fringes in a Young's double-slit experiment. Suggest and explain three practical improvements based on interference physics.",
        modelAnswerPoints: [
          "Improve coherence by using monochromatic source and single-source slit arrangement.",
          "Reduce ambient light and increase optical stability to avoid phase fluctuations.",
          "Adjust slit widths to more similar intensities from each slit for better contrast.",
          "Increase screen distance moderately to enlarge fringe spacing for clearer observation.",
          "Ensure slits are narrow and well-defined to sustain diffraction and overlap region.",
        ],
        workedSolution: [
          "Contrast depends on stable phase and comparable amplitudes from both paths.",
          "Practical setup quality (alignment, vibration isolation, dark room) supports stable fringes.",
          "Geometry choices can improve resolvability without violating coherence requirements.",
        ],
        commonMistake: "Suggesting two independent lamps as a stronger light source.",
        tags: ["experimental-skills", "fringe-contrast", "exam-evaluation"],
      },
    ],
    flashcards: [
      {
        id: "t8-3-f1",
        noteId: "t8-3",
        difficulty: 1,
        front: "Condition for constructive interference?",
        back: "Path difference = n lambda (n = 0, 1, 2, ...).",
        examPhrasing: "Maxima occur when phase difference is 2npi.",
        tags: ["constructive", "conditions"],
      },
      {
        id: "t8-3-f2",
        noteId: "t8-3",
        difficulty: 1,
        front: "Condition for destructive interference?",
        back: "Path difference = (n + 1/2)lambda.",
        examPhrasing: "Minima occur at odd multiples of pi phase difference.",
        tags: ["destructive", "conditions"],
      },
      {
        id: "t8-3-f3",
        noteId: "t8-3",
        difficulty: 2,
        front: "Define coherent sources.",
        back: "Sources with the same frequency and constant phase difference.",
        examPhrasing: "Coherence is required for stable fringes.",
        tags: ["coherence", "definition"],
      },
      {
        id: "t8-3-f4",
        noteId: "t8-3",
        difficulty: 2,
        front: "Young's fringe spacing formula?",
        back: "w = lambda D / a.",
        examPhrasing: "Fringe spacing is proportional to wavelength and screen distance, inversely proportional to slit separation.",
        tags: ["young-double-slit", "formula"],
      },
      {
        id: "t8-3-f5",
        noteId: "t8-3",
        difficulty: 3,
        front: "What happens to fringe spacing if slit separation increases?",
        back: "Fringe spacing decreases.",
        examPhrasing: "w inversely proportional a.",
        confusionPair: "increase a vs increase D",
        tags: ["trends", "fringes"],
      },
      {
        id: "t8-3-f6",
        noteId: "t8-3",
        difficulty: 3,
        front: "How is phase difference related to path difference?",
        back: "Delta phi = 2pi(Delta x/lambda).",
        examPhrasing: "Use modulo 2pi when classifying maxima/minima.",
        tags: ["phase", "path-difference"],
      },
      {
        id: "t8-3-f7",
        noteId: "t8-3",
        difficulty: 4,
        front: "Why use a monochromatic source in interference experiments?",
        back: "Multiple wavelengths overlap different fringe patterns and reduce visibility.",
        examPhrasing: "Single wavelength gives one clear fringe spacing.",
        tags: ["experimental", "coherence"],
      },
      {
        id: "t8-3-f8",
        noteId: "t8-3",
        difficulty: 4,
        front: "What determines fringe contrast besides coherence?",
        back: "Relative amplitudes/intensities from the two slits; best contrast when similar.",
        examPhrasing: "Visibility falls when one source dominates intensity.",
        tags: ["contrast", "practical"],
      },
      {
        id: "t8-3-f9",
        noteId: "t8-3",
        difficulty: 5,
        front: "Exam check: what unit consistency is essential in using w = lambda D / a?",
        back: "All lengths must be in the same unit system (typically SI) before substitution.",
        examPhrasing: "Common error: mixing nm, mm, and m without conversion.",
        tags: ["exam-technique", "units"],
      },
      {
        id: "t8-3-f10",
        noteId: "t8-3",
        difficulty: 5,
        front: "Why are two independent lasers usually not treated as coherent in basic lab conditions?",
        back: "Their relative phase drifts with time, so stable fringe patterns are not maintained.",
        examPhrasing: "Coherence requires fixed phase relation, not merely same color.",
        confusionPair: "same wavelength vs stable phase",
        tags: ["coherence", "advanced-concept"],
      },
    ],
  },
  "t8-4": {
    noteId: "t8-4",
    drills: [
      {
        id: "t8-4-d1",
        noteId: "t8-4",
        kind: "mcq",
        difficulty: 1,
        stem: "For a diffraction grating, what does N usually denote?",
        options: [
          { id: "A", text: "Number of slits per unit length" },
          { id: "B", text: "Total number of maxima observed" },
          { id: "C", text: "Refractive index of grating material" },
          { id: "D", text: "Order number of spectrum line" },
        ],
        correctOptionId: "A",
        explanation:
          "N is line density, commonly given in lines per mm or per m. Grating spacing d = 1/N in consistent units.",
        distractorRationale: {
          B: "Number of maxima depends on wavelength/order limits, not definition of N.",
          D: "Order is denoted by m, not N.",
        },
        tags: ["diffraction-grating", "definitions", "line-density"],
      },
      {
        id: "t8-4-d2",
        noteId: "t8-4",
        kind: "mcq",
        difficulty: 2,
        stem: "The grating equation for principal maxima is",
        options: [
          { id: "A", text: "a sin theta = m lambda" },
          { id: "B", text: "d sin theta = m lambda" },
          { id: "C", text: "d cos theta = m lambda" },
          { id: "D", text: "2d sin theta = m lambda" },
        ],
        correctOptionId: "B",
        explanation:
          "For normal incidence and principal maxima from adjacent slits, path difference is d sin theta = m lambda.",
        distractorRationale: {
          C: "Cosine form is not the principal maximum condition.",
        },
        tags: ["equation", "principal-maxima", "notation"],
      },
      {
        id: "t8-4-d3",
        noteId: "t8-4",
        kind: "mcq",
        difficulty: 3,
        stem:
          "A grating has 500 lines mm^-1 and is used with light of wavelength 600 nm. What is the highest possible order?",
        options: [
          { id: "A", text: "m = 1" },
          { id: "B", text: "m = 2" },
          { id: "C", text: "m = 3" },
          { id: "D", text: "m = 4" },
        ],
        correctOptionId: "C",
        explanation:
          "d = 1/(500 x 10^3) = 2.0 x 10^-6 m. Since sin theta <= 1, m <= d/lambda = 2.0 x 10^-6 / 6.0 x 10^-7 = 3.33, so highest integer order is 3.",
        distractorRationale: {
          B: "Second order exists but is not the highest possible.",
          D: "Fourth order would require sin theta > 1, impossible.",
        },
        tags: ["order-limit", "grating-spacing", "constraints"],
      },
      {
        id: "t8-4-d4",
        noteId: "t8-4",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define grating spacing d and explain how to obtain it from a grating labeled 600 lines mm^-1.",
        modelAnswerPoints: [
          "Grating spacing d is distance between adjacent slits/lines.",
          "Convert 600 lines mm^-1 to 6.00 x 10^5 lines m^-1.",
          "d = 1/N = 1/(6.00 x 10^5) = 1.67 x 10^-6 m.",
        ],
        workedSolution: [
          "State definition, then do careful unit conversion first.",
          "Only after conversion should reciprocal be taken.",
        ],
        commonMistake: "Using d = 1/600 directly in metres.",
        tags: ["spacing", "unit-conversion", "definitions"],
      },
      {
        id: "t8-4-d5",
        noteId: "t8-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A grating has 400 lines mm^-1 and light wavelength is 500 nm.\nCalculate the first-order diffraction angle.",
        modelAnswerPoints: [
          "N = 400 mm^-1 = 4.00 x 10^5 m^-1, so d = 2.50 x 10^-6 m.",
          "For m = 1, use d sin theta = lambda.",
          "sin theta = (5.00 x 10^-7)/(2.50 x 10^-6) = 0.200.",
          "theta = 11.5 degrees.",
        ],
        workedSolution: [
          "Convert line density to spacing first.",
          "Apply m = 1 relation and then inverse sine.",
          "Quote angle with sensible precision.",
        ],
        commonMistake: "Using line density value directly in place of d in equation.",
        tags: ["first-order", "calculation", "grating-equation"],
      },
      {
        id: "t8-4-d6",
        noteId: "t8-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Using a grating of spacing 1.8 x 10^-6 m, a first-order maximum is seen at 19.5 degrees.\nCalculate wavelength.",
        modelAnswerPoints: [
          "Use d sin theta = m lambda with m = 1.",
          "lambda = d sin theta = 1.8 x 10^-6 x sin(19.5 degrees).",
          "lambda = 6.00 x 10^-7 m (approximately).",
          "So wavelength is about 600 nm.",
        ],
        workedSolution: [
          "Rearrange formula before substitution.",
          "Check final value is in visible range for plausibility.",
        ],
        commonMistake: "Using degrees in calculator incorrectly (radian mode error).",
        tags: ["wavelength-determination", "inverse-use", "practical"],
      },
      {
        id: "t8-4-d7",
        noteId: "t8-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Explain why higher-order spectra from a diffraction grating are more spread out angularly but usually dimmer.",
        modelAnswerPoints: [
          "Angular position satisfies d sin theta = m lambda; larger m gives larger theta.",
          "Angular dispersion increases with order for a given wavelength interval.",
          "Energy is distributed among multiple orders and finite slit effects reduce intensity envelopes.",
          "Hence higher-order lines are further apart but less bright.",
        ],
        workedSolution: [
          "Use order dependence in the grating equation to justify increased separation.",
          "Then discuss qualitative intensity sharing and envelope effects.",
          "Keep 'spread out' and 'brightness' as separate physical ideas.",
        ],
        commonMistake: "Assuming brightness must increase with order because angle is larger.",
        tags: ["dispersion", "intensity", "qualitative"],
      },
      {
        id: "t8-4-d8",
        noteId: "t8-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A grating has 700 lines mm^-1 and is illuminated normally by sodium light (lambda = 589 nm).\n(a) Find the first-order angle.\n(b) Determine whether second order is possible.",
        modelAnswerPoints: [
          "Convert N: 700 mm^-1 = 7.00 x 10^5 m^-1, so d = 1.43 x 10^-6 m.",
          "For m = 1: sin theta1 = lambda/d = 5.89 x 10^-7 / 1.43 x 10^-6 = 0.412.",
          "theta1 approx 24.3 degrees.",
          "For m = 2: sin theta2 = 2lambda/d = 0.824, so second order is possible.",
          "theta2 approx 55.5 degrees.",
        ],
        workedSolution: [
          "Perform spacing conversion carefully before trigonometry.",
          "Check physical viability via sin theta <= 1 for each order.",
          "If viable, calculate and report corresponding angle.",
        ],
        commonMistake: "Concluding second order impossible without checking numeric sine value.",
        tags: ["order-check", "sodium-light", "exam-calculation"],
      },
      {
        id: "t8-4-d9",
        noteId: "t8-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Two wavelengths, 510 nm and 520 nm, are observed in first order with a grating spacing of 2.0 x 10^-6 m.\nEstimate angular separation between the two first-order lines.",
        modelAnswerPoints: [
          "For each wavelength in first order, sin theta = lambda/d.",
          "theta1 = sin^-1(510 x 10^-9 / 2.0 x 10^-6) = sin^-1(0.255) approx 14.8 degrees.",
          "theta2 = sin^-1(520 x 10^-9 / 2.0 x 10^-6) = sin^-1(0.260) approx 15.1 degrees.",
          "Angular separation delta theta approx 0.3 degrees.",
        ],
        workedSolution: [
          "Compute the two diffraction angles independently.",
          "Subtract to find the line separation in degrees.",
          "Show intermediate ratios to reduce calculator mistakes.",
        ],
        commonMistake: "Subtracting wavelengths first and using one inverse sine directly without approximation context.",
        tags: ["spectral-separation", "resolution-idea", "numerical"],
      },
      {
        id: "t8-4-d10",
        noteId: "t8-4",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A student measures the angle between the +1 and -1 order green lines from a diffraction grating as 36.0 degrees. The grating is 300 lines mm^-1.\n(a) Calculate the wavelength.\n(b) State two likely systematic errors in this method and their effect direction.",
        modelAnswerPoints: [
          "Half-angle to one first order is theta = 18.0 degrees.",
          "N = 300 mm^-1 = 3.00 x 10^5 m^-1, so d = 3.33 x 10^-6 m.",
          "For m = 1, lambda = d sin theta = 3.33 x 10^-6 x sin 18.0 degrees = 1.03 x 10^-6 m.",
          "Likely systematic error: incorrect zero-angle reference -> shifts lambda high or low consistently.",
          "Likely systematic error: grating not normal to incident beam -> asymmetric orders, biased angle estimate.",
        ],
        workedSolution: [
          "Convert total separation to half-angle before applying equation.",
          "Calculate d from line density in SI, then evaluate wavelength.",
          "For evaluation marks, tie each error source to directional bias in measured theta and therefore lambda.",
        ],
        commonMistake: "Using the full 36.0 degrees as theta in d sin theta = m lambda.",
        tags: ["experimental-evaluation", "angle-geometry", "high-level"],
      },
    ],
    flashcards: [
      {
        id: "t8-4-f1",
        noteId: "t8-4",
        difficulty: 1,
        front: "Diffraction grating equation for normal incidence?",
        back: "d sin theta = m lambda.",
        examPhrasing: "m is order number (0, +/-1, +/-2, ...).",
        tags: ["grating-equation", "core-formula"],
      },
      {
        id: "t8-4-f2",
        noteId: "t8-4",
        difficulty: 1,
        front: "How is grating spacing d related to line density N?",
        back: "d = 1/N (with N in lines per metre).",
        examPhrasing: "Convert lines per mm to lines per m before inversion.",
        tags: ["spacing", "line-density"],
      },
      {
        id: "t8-4-f3",
        noteId: "t8-4",
        difficulty: 2,
        front: "What is order m = 0 called?",
        back: "The central (zero-order) maximum.",
        examPhrasing: "At m = 0, theta = 0 for normal incidence.",
        tags: ["orders", "pattern"],
      },
      {
        id: "t8-4-f4",
        noteId: "t8-4",
        difficulty: 2,
        front: "How do you find the highest possible order from d and lambda?",
        back: "Use m <= d/lambda from sin theta <= 1 and take largest integer m.",
        examPhrasing: "Maximum order is floor(d/lambda).",
        tags: ["order-limit", "constraint"],
      },
      {
        id: "t8-4-f5",
        noteId: "t8-4",
        difficulty: 3,
        front: "Why do gratings produce sharper principal maxima than double slits?",
        back: "Many slits interfere, giving narrower and more intense principal maxima at specific angles.",
        examPhrasing: "Increasing number of coherent sources narrows principal maxima.",
        tags: ["multi-slit", "pattern-quality"],
      },
      {
        id: "t8-4-f6",
        noteId: "t8-4",
        difficulty: 3,
        front: "What is angular dispersion in grating context?",
        back: "Rate of change of diffraction angle with wavelength, indicating spectral spread.",
        examPhrasing: "Higher orders generally give greater angular separation for close wavelengths.",
        tags: ["dispersion", "spectra"],
      },
      {
        id: "t8-4-f7",
        noteId: "t8-4",
        difficulty: 4,
        front: "Why must angles often be halved when using measured separation between symmetric orders?",
        back: "Equation uses angle from central axis to one order, not total separation between +m and -m.",
        examPhrasing: "theta = (measured +m to -m angle)/2.",
        confusionPair: "single-side angle vs total spread angle",
        tags: ["geometry", "exam-technique"],
      },
      {
        id: "t8-4-f8",
        noteId: "t8-4",
        difficulty: 4,
        front: "What setup condition ensures straightforward use of d sin theta = m lambda?",
        back: "Incident beam normal (perpendicular) to grating.",
        examPhrasing: "Non-normal incidence needs modified path-difference treatment.",
        tags: ["assumptions", "setup"],
      },
      {
        id: "t8-4-f9",
        noteId: "t8-4",
        difficulty: 5,
        front: "Common conversion trap with grating labels like 600 lines mm^-1?",
        back: "Forgetting that this is 6.00 x 10^5 lines m^-1, causing d to be wrong by 10^3.",
        examPhrasing: "Unit conversion errors dominate grating calculation mistakes.",
        tags: ["units", "pitfalls"],
      },
      {
        id: "t8-4-f10",
        noteId: "t8-4",
        difficulty: 5,
        front: "Why are multiple wavelength lines easier to resolve with a high-line-density grating?",
        back: "Smaller d gives larger diffraction angles and typically greater angular separation between nearby wavelengths.",
        examPhrasing: "Higher line density increases dispersion and improves practical spectral resolution.",
        tags: ["resolution", "design-choice"],
      },
    ],
  },
};
