import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC25_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t25-1": {
    noteId: "t25-1",
    drills: [
      {
        id: "t25-1-d1",
        noteId: "t25-1",
        kind: "mcq",
        difficulty: 1,
        stem: "A standard candle in astronomy is an object that",
        options: [
          { id: "A", text: "has known luminosity" },
          { id: "B", text: "has known surface temperature only" },
          { id: "C", text: "has the same colour as the Sun" },
          { id: "D", text: "is at a known distance from Earth" },
        ],
        correctOptionId: "A",
        explanation:
          "A standard candle is a source with known absolute luminosity so its distance can be inferred from measured flux.",
        distractorRationale: {
          B: "Temperature alone is insufficient unless luminosity is also known.",
          C: "Colour similarity does not provide an absolute luminosity calibration.",
          D: "Distance is usually the unknown determined using standard candles.",
        },
        tags: ["standard-candle", "definitions", "luminosity"],
      },
      {
        id: "t25-1-d2",
        noteId: "t25-1",
        kind: "mcq",
        difficulty: 2,
        stem:
          "The apparent brightness (flux) of a star is 2.0 x 10^-10 W m^-2. Its luminosity is 8.0 x 10^26 W.\nWhat is the best estimate of its distance?",
        options: [
          { id: "A", text: "1.8 x 10^17 m" },
          { id: "B", text: "5.6 x 10^17 m" },
          { id: "C", text: "1.8 x 10^18 m" },
          { id: "D", text: "5.6 x 10^18 m" },
        ],
        correctOptionId: "B",
        explanation:
          "Using b = L/(4pi d^2), d = sqrt(L/(4pi b)) = sqrt(8.0 x 10^26 / (4pi x 2.0 x 10^-10)) approx 5.6 x 10^17 m.",
        distractorRationale: {
          C: "A common error from omitting the 4pi factor before square rooting.",
          D: "Typically from inverting b/L or misreading the exponent sign.",
        },
        tags: ["inverse-square-law", "distance", "numerical"],
      },
      {
        id: "t25-1-d3",
        noteId: "t25-1",
        kind: "mcq",
        difficulty: 3,
        stem:
          "Two identical Cepheid variables are observed. Star X appears four times brighter than star Y.\nAssuming no absorption, the ratio dY/dX is",
        options: [
          { id: "A", text: "2" },
          { id: "B", text: "4" },
          { id: "C", text: "1/2" },
          { id: "D", text: "1/4" },
        ],
        correctOptionId: "A",
        explanation:
          "For equal luminosity, brightness b proportional 1/d^2. If bX = 4bY, then dY^2 = 4dX^2, so dY/dX = 2.",
        distractorRationale: {
          B: "Distance scales with square root of brightness ratio, not directly.",
          C: "This reverses which star is farther.",
          D: "This applies an inverse and square incorrectly.",
        },
        tags: ["brightness-ratio", "standard-candle", "proportionality"],
      },
      {
        id: "t25-1-d4",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define luminosity and apparent brightness for a star.",
        modelAnswerPoints: [
          "Luminosity is total power emitted by a star in all directions.",
          "Apparent brightness (flux) is power received per unit area at the observer.",
          "Brightness depends on both luminosity and distance.",
        ],
        workedSolution: [
          "State luminosity as an intrinsic property of the source.",
          "State brightness as a measured quantity at Earth in W m^-2.",
        ],
        commonMistake: "Using luminosity and brightness as interchangeable terms.",
        tags: ["definitions", "luminosity", "flux"],
      },
      {
        id: "t25-1-d5",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A Type Ia supernova has luminosity 1.0 x 10^36 W.\nIts measured flux at Earth is 2.2 x 10^-14 W m^-2.\nCalculate its distance.",
        modelAnswerPoints: [
          "Use b = L/(4pi d^2).",
          "Rearrange to d = sqrt(L/(4pi b)).",
          "d = sqrt(1.0 x 10^36 / (4pi x 2.2 x 10^-14)).",
          "d approx 6.0 x 10^24 m.",
        ],
        workedSolution: [
          "Insert values with full powers of ten before calculator evaluation.",
          "A result of order 10^24 to 10^25 m is plausible for supernova distances in other galaxies.",
        ],
        commonMistake: "Forgetting the square root after rearranging for d.",
        tags: ["supernovae", "distance-estimation", "calculation"],
      },
      {
        id: "t25-1-d6",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A star is moved from distance d to distance 3d from Earth.\nDetermine how its apparent brightness changes and justify mathematically.",
        modelAnswerPoints: [
          "Brightness follows inverse-square relation: b proportional 1/d^2.",
          "At 3d, b_new/b_old = (d/3d)^2 = 1/9.",
          "So brightness decreases to one-ninth of its original value.",
        ],
        workedSolution: [
          "Use a ratio form to avoid substitution of unknown luminosity.",
          "Distance increase by factor 3 gives brightness decrease by factor 3^2.",
        ],
        commonMistake: "Assuming brightness falls to one-third instead of one-ninth.",
        tags: ["inverse-square-law", "ratios", "exam-technique"],
      },
      {
        id: "t25-1-d7",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Explain why Cepheid variable stars can be used as standard candles.\nInclude reference to an observational property and how distance is then found.",
        modelAnswerPoints: [
          "Cepheids show periodic brightness variation with measurable period.",
          "There is a period-luminosity relation, so luminosity can be inferred from period.",
          "Once luminosity is known, measured flux gives distance via inverse-square law.",
          "This allows distances to remote galaxies to be estimated.",
        ],
        workedSolution: [
          "The key chain is period measurement -> luminosity calibration -> flux measurement -> distance.",
          "A complete answer links observational data to a quantitative distance method.",
        ],
        commonMistake: "Stating only that Cepheids are bright without mentioning the period-luminosity relation.",
        tags: ["cepheids", "reasoning", "distance-ladder"],
      },
      {
        id: "t25-1-d8",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Two supernovae, S1 and S2, are both Type Ia.\nS1 has measured flux 9.0 x 10^-15 W m^-2 and S2 has 4.0 x 10^-14 W m^-2.\n(a) Determine d1/d2.\n(b) State which is farther.",
        modelAnswerPoints: [
          "Type Ia implies equal luminosity assumption.",
          "For equal L, b proportional 1/d^2 so d1/d2 = sqrt(b2/b1).",
          "d1/d2 = sqrt((4.0 x 10^-14)/(9.0 x 10^-15)) = sqrt(4.44) approx 2.11.",
          "S1 is farther because it has lower flux.",
        ],
        workedSolution: [
          "Use brightness ratio with square root rather than separate absolute calculations.",
          "The dimmer object is farther under equal-luminosity conditions.",
        ],
        commonMistake: "Using d1/d2 = b2/b1 without taking square root.",
        tags: ["type-ia", "ratio-method", "comparative-distance"],
      },
      {
        id: "t25-1-d9",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A galaxy contains a Cepheid with known luminosity 2.5 x 10^30 W.\nThe measured flux is 8.8 x 10^-21 W m^-2.\n(a) Calculate distance in metres.\n(b) Convert to parsecs using 1 pc = 3.09 x 10^16 m.",
        modelAnswerPoints: [
          "d = sqrt(L/(4pi b)) = sqrt(2.5 x 10^30 / (4pi x 8.8 x 10^-21)).",
          "d approx 4.75 x 10^24 m.",
          "Distance in parsecs = 4.75 x 10^24 / 3.09 x 10^16.",
          "d approx 1.54 x 10^8 pc.",
        ],
        workedSolution: [
          "Part (a) applies the standard-candle equation directly.",
          "Part (b) is a unit conversion only, so keep significant figures consistent.",
        ],
        commonMistake: "Dividing by 3.09 x 10^16 before taking square root.",
        tags: ["parsec-conversion", "cepheid", "multi-step"],
      },
      {
        id: "t25-1-d10",
        noteId: "t25-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Discuss two limitations or sources of uncertainty when using standard candles to determine cosmic distances.\nFor each, state how the inferred distance may be affected.",
        modelAnswerPoints: [
          "Interstellar absorption/extinction reduces observed flux, making object appear farther than it is if uncorrected.",
          "Uncertainty in intrinsic luminosity calibration (e.g. scatter in period-luminosity relation) changes inferred distance scale.",
          "Misclassification (object not truly of the assumed standard-candle class) introduces systematic error.",
          "Instrumental/measurement errors in flux propagate through square-root relation into distance uncertainty.",
        ],
        workedSolution: [
          "Distance is derived from d = sqrt(L/(4pi b)), so any error in L or b affects d.",
          "Lower measured b or overestimated L both bias distance high; opposite errors bias distance low.",
          "Strong answers identify both physical and observational uncertainties.",
        ],
        commonMistake: "Listing uncertainties without explaining their effect on inferred distance.",
        tags: ["evaluation", "uncertainty", "astronomical-measurement"],
      },
    ],
    flashcards: [
      {
        id: "t25-1-f1",
        noteId: "t25-1",
        difficulty: 1,
        front: "What is a standard candle?",
        back: "An astronomical object with known luminosity used to infer distance from observed flux.",
        examPhrasing: "Define a standard candle in terms of known intrinsic luminosity.",
        tags: ["definition", "standard-candle"],
      },
      {
        id: "t25-1-f2",
        noteId: "t25-1",
        difficulty: 1,
        front: "Define stellar luminosity.",
        back: "Luminosity is total power emitted by a star per second.",
        examPhrasing: "State luminosity as an intrinsic power output.",
        tags: ["luminosity", "core-definition"],
      },
      {
        id: "t25-1-f3",
        noteId: "t25-1",
        difficulty: 2,
        front: "Define apparent brightness (flux).",
        back: "Flux is power received per unit area at the observer, usually in W m^-2.",
        examPhrasing: "State apparent brightness as received power per unit area.",
        tags: ["flux", "definitions"],
      },
      {
        id: "t25-1-f4",
        noteId: "t25-1",
        difficulty: 2,
        front: "Write the relation between luminosity, flux and distance.",
        back: "b = L/(4pi d^2).",
        examPhrasing: "Use the inverse-square law for isotropic emission.",
        tags: ["equation", "inverse-square-law"],
      },
      {
        id: "t25-1-f5",
        noteId: "t25-1",
        difficulty: 3,
        front: "How does flux change if distance doubles?",
        back: "Flux becomes one-quarter, since b proportional 1/d^2.",
        examPhrasing: "Apply inverse-square scaling to compare apparent brightness.",
        tags: ["proportionality", "distance-effect"],
      },
      {
        id: "t25-1-f6",
        noteId: "t25-1",
        difficulty: 3,
        front: "Why are Cepheid variables useful as standard candles?",
        back: "Their pulsation period gives luminosity through the period-luminosity relation.",
        examPhrasing: "Explain period measurement as route to intrinsic luminosity.",
        tags: ["cepheids", "distance-ladder"],
      },
      {
        id: "t25-1-f7",
        noteId: "t25-1",
        difficulty: 4,
        front: "Give one reason Type Ia supernovae are used as distance indicators.",
        back: "They have similar peak luminosities, so measured flux can be used to estimate distance.",
        examPhrasing: "State why Type Ia supernovae approximate standard candles.",
        tags: ["type-ia", "applications"],
      },
      {
        id: "t25-1-f8",
        noteId: "t25-1",
        difficulty: 4,
        front: "How does interstellar dust affect standard-candle distances if ignored?",
        back: "Dust dims flux, so distance is overestimated.",
        examPhrasing: "Relate extinction to bias in inferred distance.",
        confusionPair: "low intrinsic luminosity vs dust extinction",
        tags: ["extinction", "uncertainty"],
      },
      {
        id: "t25-1-f9",
        noteId: "t25-1",
        difficulty: 5,
        front: "If luminosity estimate is too high, how is inferred distance affected?",
        back: "Distance is overestimated because d proportional sqrt(L).",
        examPhrasing: "Use dependence of distance on square root of luminosity.",
        tags: ["error-propagation", "reasoning"],
      },
      {
        id: "t25-1-f10",
        noteId: "t25-1",
        difficulty: 5,
        front: "Exam checklist for standard-candle calculations?",
        back: "Use b = L/(4pi d^2), rearrange carefully, keep powers of ten explicit, then check if distance scale is astrophysically plausible.",
        examPhrasing: "Method marks reward correct rearrangement and physically sensible final magnitude.",
        tags: ["exam-technique", "calculation-strategy"],
      },
    ],
  },

  "t25-2": {
    noteId: "t25-2",
    drills: [
      {
        id: "t25-2-d1",
        noteId: "t25-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which equation links a star's luminosity L, radius R and surface temperature T?",
        options: [
          { id: "A", text: "L = 4pi R^2 sigma T^4" },
          { id: "B", text: "L = 4pi R sigma T^2" },
          { id: "C", text: "L = sigma T^4 / (4pi R^2)" },
          { id: "D", text: "L = 4pi R^2 sigma T" },
        ],
        correctOptionId: "A",
        explanation:
          "Treating a star as an approximate black body gives L = area x sigma T^4 = 4pi R^2 sigma T^4.",
        distractorRationale: {
          B: "Area term must be proportional to R^2, and temperature dependence is T^4.",
          C: "This inverts the Stefan-Boltzmann relation.",
          D: "Temperature power should be 4, not 1.",
        },
        tags: ["stefan-boltzmann", "stellar-radii", "equation"],
      },
      {
        id: "t25-2-d2",
        noteId: "t25-2",
        kind: "mcq",
        difficulty: 2,
        stem:
          "Two stars have the same surface temperature. Star P has four times the luminosity of star Q.\nThe ratio RP/RQ is",
        options: [
          { id: "A", text: "2" },
          { id: "B", text: "4" },
          { id: "C", text: "1/2" },
          { id: "D", text: "1/4" },
        ],
        correctOptionId: "A",
        explanation:
          "At equal T, L proportional R^2. So RP/RQ = sqrt(LP/LQ) = sqrt(4) = 2.",
        distractorRationale: {
          B: "Radius scales with square root of luminosity ratio, not directly.",
          C: "This reverses the relative size relationship.",
          D: "This is both inverted and unsquared.",
        },
        tags: ["ratio", "constant-temperature", "luminosity-radius"],
      },
      {
        id: "t25-2-d3",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "State Wien's displacement law and use it to estimate the peak surface temperature of a star whose peak emission wavelength is 480 nm.\nTake Wien constant b = 2.90 x 10^-3 m K.",
        modelAnswerPoints: [
          "Wien's displacement law: peak wavelength lambda_max is inversely proportional to absolute temperature T (lambda_max T = constant b).",
          "Rearrange to T = b/lambda_max.",
          "Convert wavelength: 480 nm = 4.80 x 10^-7 m.",
          "T = (2.90 x 10^-3)/(4.80 x 10^-7) = 6.04 x 10^3 K (about 6000 K).",
          "Temperature must be in kelvin.",
        ],
        workedSolution: [
          "Wien's law links the wavelength at maximum spectral intensity to surface temperature using lambda_max T = b.",
          "Substitute b = 2.90 x 10^-3 m K and lambda_max = 4.80 x 10^-7 m to obtain T = 6.0 x 10^3 K.",
          "This temperature scale is typical of a Sun-like stellar photosphere.",
        ],
        commonMistake: "Using Celsius temperature or forgetting to convert nanometres to metres.",
        tags: ["wiens-law", "peak-wavelength", "temperature-estimate"],
      },
      {
        id: "t25-2-d4",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State the Stefan-Boltzmann law as applied to a star and define all symbols.",
        modelAnswerPoints: [
          "L = 4pi R^2 sigma T^4.",
          "L is luminosity, R is stellar radius, T is surface temperature (K).",
          "sigma is the Stefan-Boltzmann constant.",
        ],
        workedSolution: [
          "The equation combines surface area of a sphere with black-body power per unit area.",
          "Temperature must be absolute temperature in kelvin.",
        ],
        commonMistake: "Using Celsius temperature in the T^4 term.",
        tags: ["definitions", "stefan-boltzmann", "symbols"],
      },
      {
        id: "t25-2-d5",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A star has luminosity 9.2 x 10^26 W and surface temperature 5800 K.\nTake sigma = 5.67 x 10^-8 W m^-2 K^-4.\nCalculate the star's radius.",
        modelAnswerPoints: [
          "Rearrange to R = sqrt(L/(4pi sigma T^4)).",
          "Substitute R = sqrt(9.2 x 10^26 / (4pi x 5.67 x 10^-8 x 5800^4)).",
          "R approx 6.9 x 10^8 m.",
          "Result is close to the solar radius scale.",
        ],
        workedSolution: [
          "Compute T^4 carefully since it dominates denominator magnitude.",
          "Use square root only after evaluating full denominator.",
        ],
        commonMistake: "Forgetting the square root when solving for R.",
        tags: ["radius-calculation", "numerical", "stellar-properties"],
      },
      {
        id: "t25-2-d6",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Star A and Star B have the same luminosity.\nIf TA = 2TB, determine RA/RB.",
        modelAnswerPoints: [
          "Use L proportional R^2T^4.",
          "With equal L: RA^2TA^4 = RB^2TB^4.",
          "RA/RB = (TB/TA)^2 = (1/2)^2 = 1/4.",
          "So Star A has one-quarter the radius of Star B.",
        ],
        workedSolution: [
          "Higher temperature can compensate for smaller area to keep luminosity constant.",
          "Use ratio algebra to avoid introducing constants.",
        ],
        commonMistake: "Using RA/RB = TB/TA instead of squared relation.",
        tags: ["ratio-analysis", "constant-luminosity", "algebra"],
      },
      {
        id: "t25-2-d7",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "A star has radius 2.0R_sun and surface temperature 0.80T_sun.\nFind its luminosity in terms of L_sun.",
        modelAnswerPoints: [
          "Use L/L_sun = (R/R_sun)^2 (T/T_sun)^4.",
          "L/L_sun = 2.0^2 x 0.80^4.",
          "L/L_sun = 4 x 0.4096 = 1.6384.",
          "Luminosity is about 1.64L_sun.",
        ],
        workedSolution: [
          "Radius increases luminosity by area factor 4.",
          "Lower temperature decreases luminosity strongly via fourth-power factor.",
          "Net effect is modest increase above solar luminosity.",
        ],
        commonMistake: "Applying the temperature factor as 0.80^2 instead of 0.80^4.",
        tags: ["relative-luminosity", "power-laws", "exam-style"],
      },
      {
        id: "t25-2-d8",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A star emits luminosity 3.2 x 10^28 W and has surface temperature 1.20 x 10^4 K.\n(a) Calculate its radius.\n(b) State whether this radius is likely larger or smaller than the Sun and justify with your result.",
        modelAnswerPoints: [
          "R = sqrt(L/(4pi sigma T^4)).",
          "R = sqrt(3.2 x 10^28 / (4pi x 5.67 x 10^-8 x (1.20 x 10^4)^4)).",
          "R approx 4.66 x 10^8 m.",
          "This is smaller than the Sun (about 6.96 x 10^8 m).",
        ],
        workedSolution: [
          "Despite high luminosity, very high temperature means high power per unit area.",
          "Therefore a comparatively smaller surface area can still deliver large luminosity.",
        ],
        commonMistake: "Assuming any very luminous star must have very large radius without calculation.",
        tags: ["interpretation", "radius-estimation", "stefan-boltzmann"],
      },
      {
        id: "t25-2-d9",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Explain qualitatively why red giants can have very large luminosities despite relatively low surface temperatures compared with blue main-sequence stars.",
        modelAnswerPoints: [
          "Luminosity depends on both temperature and surface area.",
          "Red giants have very large radii, giving very large emitting area (4pi R^2).",
          "The large area can compensate for lower T^4 term.",
          "Hence total luminosity can still be high.",
        ],
        workedSolution: [
          "Use L proportional R^2T^4 as framework for explanation.",
          "A valid answer balances competing effects of radius and temperature.",
        ],
        commonMistake: "Claiming low temperature always implies low luminosity regardless of radius.",
        tags: ["stellar-types", "qualitative-reasoning", "hr-context"],
      },
      {
        id: "t25-2-d10",
        noteId: "t25-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A distant star has measured flux 1.8 x 10^-9 W m^-2 at Earth and distance 2.0 x 10^18 m.\nIts surface temperature is 6200 K.\n(a) Determine luminosity.\n(b) Determine radius.\nTake sigma = 5.67 x 10^-8 W m^-2 K^-4.",
        modelAnswerPoints: [
          "Use L = 4pi d^2 b = 4pi x (2.0 x 10^18)^2 x 1.8 x 10^-9.",
          "L approx 9.05 x 10^28 W.",
          "Then R = sqrt(L/(4pi sigma T^4)).",
          "R = sqrt(9.05 x 10^28 / (4pi x 5.67 x 10^-8 x 6200^4)).",
          "R approx 9.3 x 10^9 m.",
        ],
        workedSolution: [
          "Part (a) reconstructs intrinsic luminosity from measured flux and distance.",
          "Part (b) combines that luminosity with surface temperature to infer radius.",
          "Chain-method questions require disciplined substitution and unit tracking.",
        ],
        commonMistake: "Substituting flux directly into Stefan-Boltzmann equation as if it were luminosity.",
        tags: ["combined-application", "stellar-radius", "multi-step"],
      },
    ],
    flashcards: [
      {
        id: "t25-2-f1",
        noteId: "t25-2",
        difficulty: 1,
        front: "State the stellar Stefan-Boltzmann equation.",
        back: "L = 4pi R^2 sigma T^4.",
        examPhrasing: "Relate luminosity to stellar radius and surface temperature.",
        tags: ["equation", "stefan-boltzmann"],
      },
      {
        id: "t25-2-f2",
        noteId: "t25-2",
        difficulty: 1,
        front: "How does luminosity scale with radius at fixed temperature?",
        back: "L proportional R^2.",
        examPhrasing: "At constant T, luminosity follows surface-area scaling.",
        tags: ["radius-effect", "proportionality"],
      },
      {
        id: "t25-2-f3",
        noteId: "t25-2",
        difficulty: 2,
        front: "How does luminosity scale with temperature at fixed radius?",
        back: "L proportional T^4.",
        examPhrasing: "Use fourth-power dependence in temperature comparisons.",
        tags: ["temperature-effect", "power-law"],
      },
      {
        id: "t25-2-f4",
        noteId: "t25-2",
        difficulty: 2,
        front: "What happens to luminosity if temperature doubles and radius is unchanged?",
        back: "Luminosity becomes 16 times larger.",
        examPhrasing: "Apply L proportional T^4 for fixed R.",
        tags: ["quick-ratio", "temperature-scaling"],
      },
      {
        id: "t25-2-f5",
        noteId: "t25-2",
        difficulty: 3,
        front: "What happens to luminosity if radius doubles and temperature is unchanged?",
        back: "Luminosity becomes 4 times larger.",
        examPhrasing: "Apply L proportional R^2 for fixed T.",
        tags: ["quick-ratio", "radius-scaling"],
      },
      {
        id: "t25-2-f6",
        noteId: "t25-2",
        difficulty: 3,
        front: "Why can a cooler star still be very luminous?",
        back: "A very large radius gives large emitting area that can outweigh lower T^4.",
        examPhrasing: "Explain competing effects in L proportional R^2T^4.",
        tags: ["qualitative", "stellar-comparisons"],
      },
      {
        id: "t25-2-f7",
        noteId: "t25-2",
        difficulty: 4,
        front: "Which temperature unit must be used in the T^4 term?",
        back: "Kelvin.",
        examPhrasing: "Use absolute temperature in Stefan-Boltzmann calculations.",
        confusionPair: "Celsius vs kelvin in T^4",
        tags: ["units", "common-errors"],
      },
      {
        id: "t25-2-f8",
        noteId: "t25-2",
        difficulty: 4,
        front: "How do you rearrange for radius from L = 4pi R^2 sigma T^4?",
        back: "R = sqrt(L/(4pi sigma T^4)).",
        examPhrasing: "Show algebraic rearrangement before substitution.",
        tags: ["rearrangement", "method"],
      },
      {
        id: "t25-2-f9",
        noteId: "t25-2",
        difficulty: 5,
        front: "If L is known with 10% uncertainty, what is the approximate percentage uncertainty in R (assuming T exact)?",
        back: "About 5%, since R proportional sqrt(L).",
        examPhrasing: "Use power dependence to estimate propagated uncertainty.",
        tags: ["uncertainty", "reasoning"],
      },
      {
        id: "t25-2-f10",
        noteId: "t25-2",
        difficulty: 5,
        front: "Exam strategy for stellar-radius problems from observational data?",
        back: "Find luminosity first from flux and distance if needed, then apply Stefan-Boltzmann and check radius order of magnitude against known stellar scales.",
        examPhrasing: "Method marks reward a clear two-stage chain and unit consistency.",
        tags: ["exam-technique", "multi-step"],
      },
    ],
  },

  "t25-3": {
    noteId: "t25-3",
    drills: [
      {
        id: "t25-3-d1",
        noteId: "t25-3",
        kind: "mcq",
        difficulty: 1,
        stem: "Hubble's law is commonly written as",
        options: [
          { id: "A", text: "v = H0 d" },
          { id: "B", text: "v = d/H0" },
          { id: "C", text: "d = H0/v^2" },
          { id: "D", text: "v^2 = H0 d" },
        ],
        correctOptionId: "A",
        explanation: "For relatively nearby cosmological scales, recession speed is proportional to distance: v = H0d.",
        distractorRationale: {
          B: "This inverts the relationship and gives wrong dimensions.",
          C: "No squared-velocity dependence appears in Hubble's law.",
          D: "Squaring velocity is not part of the linear relation.",
        },
        tags: ["hubbles-law", "equation-recall", "cosmology"],
      },
      {
        id: "t25-3-d2",
        noteId: "t25-3",
        kind: "mcq",
        difficulty: 2,
        stem:
          "A galaxy has recessional speed 4.2 x 10^6 m s^-1.\nTake H0 = 2.1 x 10^-18 s^-1.\nIts distance is",
        options: [
          { id: "A", text: "2.0 x 10^24 m" },
          { id: "B", text: "8.8 x 10^23 m" },
          { id: "C", text: "5.0 x 10^12 m" },
          { id: "D", text: "8.8 x 10^24 m" },
        ],
        correctOptionId: "A",
        explanation:
          "From v = H0d, d = v/H0 = 4.2 x 10^6 / 2.1 x 10^-18 = 2.0 x 10^24 m.",
        distractorRationale: {
          B: "This comes from incorrect arithmetic handling of powers of ten.",
          C: "This ignores the very small value of H0 and is far too small cosmologically.",
          D: "Typically from dividing by 4.8 x 10^-19 or calculator-entry error.",
        },
        tags: ["distance-from-hubble", "numerical", "units"],
      },
      {
        id: "t25-3-d3",
        noteId: "t25-3",
        kind: "mcq",
        difficulty: 3,
        stem: "An estimate for the age of the universe from Hubble data is based on",
        options: [
          { id: "A", text: "t approx 1/H0" },
          { id: "B", text: "t approx H0" },
          { id: "C", text: "t approx H0^2" },
          { id: "D", text: "t approx v/H0" },
        ],
        correctOptionId: "A",
        explanation:
          "Since H0 has units s^-1, 1/H0 has units of time and gives an order-of-magnitude age estimate.",
        distractorRationale: {
          B: "H0 itself has units s^-1, not time.",
          C: "H0^2 has units s^-2 and cannot represent age.",
          D: "v/H0 gives distance, not time.",
        },
        tags: ["age-of-universe", "hubble-constant", "dimensional-analysis"],
      },
      {
        id: "t25-3-d4",
        noteId: "t25-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State Hubble's law and define all quantities.",
        modelAnswerPoints: [
          "Hubble's law: v = H0d.",
          "v is recessional speed of a galaxy and d is its distance.",
          "H0 is the Hubble constant (gradient of v-d graph).",
        ],
        workedSolution: [
          "A complete definition includes physical meaning and units of H0 (s^-1 or km s^-1 Mpc^-1).",
          "Law describes large-scale expansion, not motion through static space only.",
        ],
        commonMistake: "Confusing H0 with a universal constant that is fixed for all cosmic epochs.",
        tags: ["definitions", "hubbles-law", "graph-interpretation"],
      },
      {
        id: "t25-3-d5",
        noteId: "t25-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Using H0 = 70 km s^-1 Mpc^-1, calculate the recessional speed of a galaxy 120 Mpc away.",
        modelAnswerPoints: [
          "Use v = H0d.",
          "v = 70 x 120 = 8400 km s^-1.",
          "Equivalent SI speed is 8.4 x 10^6 m s^-1.",
        ],
        workedSolution: [
          "Units are already matched (km s^-1 Mpc^-1 with Mpc), so direct multiplication is valid.",
          "Convert to SI only if requested.",
        ],
        commonMistake: "Converting Mpc to metres unnecessarily and mixing units mid-calculation.",
        tags: ["hubble-graph", "unit-handling", "calculation"],
      },
      {
        id: "t25-3-d6",
        noteId: "t25-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A galaxy has redshift z = 0.020.\nFor small z, take v approx cz with c = 3.0 x 10^8 m s^-1.\nUsing H0 = 2.2 x 10^-18 s^-1, estimate distance.",
        modelAnswerPoints: [
          "v approx cz = 3.0 x 10^8 x 0.020 = 6.0 x 10^6 m s^-1.",
          "Use d = v/H0.",
          "d = 6.0 x 10^6 / 2.2 x 10^-18 = 2.73 x 10^24 m.",
          "Distance is of order 10^24 m.",
        ],
        workedSolution: [
          "First convert redshift to speed using small-z approximation.",
          "Then apply Hubble's law in rearranged form.",
        ],
        commonMistake: "Treating z directly as distance without converting to speed first.",
        tags: ["redshift", "hubbles-law", "two-stage"],
      },
      {
        id: "t25-3-d7",
        noteId: "t25-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Estimate the age of the universe using H0 = 2.2 x 10^-18 s^-1.\nGive your answer in seconds and years (1 year = 3.15 x 10^7 s).",
        modelAnswerPoints: [
          "Use t approx 1/H0.",
          "t = 1 / (2.2 x 10^-18) = 4.55 x 10^17 s.",
          "Convert years: t = 4.55 x 10^17 / 3.15 x 10^7.",
          "t approx 1.44 x 10^10 years.",
        ],
        workedSolution: [
          "Inverse of H0 gives characteristic expansion timescale.",
          "Unit conversion shows age in billions of years.",
          "Result is about 14 billion years, consistent with accepted order of magnitude.",
        ],
        commonMistake: "Using t = H0 and getting a tiny number with incorrect units.",
        tags: ["age-estimate", "hubble-time", "conversion"],
      },
      {
        id: "t25-3-d8",
        noteId: "t25-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Explain two observational pieces of evidence that support the Big Bang model.",
        modelAnswerPoints: [
          "Galactic redshifts follow Hubble's law, indicating large-scale expansion.",
          "Cosmic microwave background radiation is relic thermal radiation from the early hot universe.",
          "Relative abundances of light elements (e.g. H, He) agree with Big Bang nucleosynthesis predictions.",
          "Together these support an early hot dense state and subsequent expansion.",
        ],
        workedSolution: [
          "A strong answer names evidence and links each to what it implies physically.",
          "Avoid listing evidence without describing why it supports the model.",
        ],
        commonMistake: "Giving only one piece of evidence or omitting interpretation.",
        tags: ["big-bang", "evidence", "evaluation"],
      },
      {
        id: "t25-3-d9",
        noteId: "t25-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Describe the meaning of the statement 'space itself is expanding'.\nWhy does this differ from galaxies simply moving through static space from one explosion point?",
        modelAnswerPoints: [
          "Expansion means large-scale distances between galaxies increase with time.",
          "No unique central explosion point is required in three-dimensional space.",
          "Any observer sees distant galaxies receding approximately according to Hubble's law.",
          "This is a metric expansion of space, not ordinary debris motion from a central location.",
        ],
        workedSolution: [
          "Use raisin-bread or balloon-surface style analogy if helpful, while noting limitations.",
          "Key idea: recession pattern is homogeneous on large scales.",
        ],
        commonMistake: "Claiming the Big Bang occurred at one point in pre-existing space with all galaxies flying away from it.",
        tags: ["cosmological-expansion", "conceptual", "misconceptions"],
      },
      {
        id: "t25-3-d10",
        noteId: "t25-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A linear fit to a recession-speed vs distance graph gives gradient 68 km s^-1 Mpc^-1 with uncertainty +/- 4 km s^-1 Mpc^-1.\n(a) Estimate Hubble time in years using the central value.\n(b) Explain qualitatively how the gradient uncertainty affects the age estimate.",
        modelAnswerPoints: [
          "Convert H0 = 68 km s^-1 Mpc^-1 to s^-1: H0 approx 2.20 x 10^-18 s^-1.",
          "Hubble time t0 approx 1/H0 approx 4.55 x 10^17 s approx 1.44 x 10^10 years.",
          "Age estimate is inversely related to H0, so larger H0 gives smaller age.",
          "With uncertainty in H0, age has corresponding fractional uncertainty of similar size.",
        ],
        workedSolution: [
          "Use 1 Mpc = 3.09 x 10^22 m and 1 km = 10^3 m for unit conversion.",
          "Because t proportional 1/H0, percentage uncertainty in t is approximately percentage uncertainty in H0.",
          "Discuss trend direction clearly: steeper slope implies younger inferred universe.",
        ],
        commonMistake: "Assuming age is directly proportional to H0.",
        tags: ["data-interpretation", "uncertainty", "hubble-constant"],
      },
    ],
    flashcards: [
      {
        id: "t25-3-f1",
        noteId: "t25-3",
        difficulty: 1,
        front: "State Hubble's law.",
        back: "v = H0d.",
        examPhrasing: "Recessional speed is proportional to distance for distant galaxies.",
        tags: ["hubbles-law", "equation"],
      },
      {
        id: "t25-3-f2",
        noteId: "t25-3",
        difficulty: 1,
        front: "What does H0 represent on a v-d graph?",
        back: "The gradient (slope) of the best-fit line.",
        examPhrasing: "Identify H0 as the proportionality constant in Hubble's law.",
        tags: ["graph", "hubble-constant"],
      },
      {
        id: "t25-3-f3",
        noteId: "t25-3",
        difficulty: 2,
        front: "What is the unit of H0 in SI?",
        back: "s^-1.",
        examPhrasing: "Show that H0 has inverse-time dimensions.",
        tags: ["units", "dimensional-analysis"],
      },
      {
        id: "t25-3-f4",
        noteId: "t25-3",
        difficulty: 2,
        front: "How is an approximate universe age found from Hubble data?",
        back: "Use t approx 1/H0.",
        examPhrasing: "Estimate cosmic age from inverse Hubble constant.",
        tags: ["age-estimate", "hubble-time"],
      },
      {
        id: "t25-3-f5",
        noteId: "t25-3",
        difficulty: 3,
        front: "For small redshift, how is recessional speed estimated?",
        back: "v approx cz.",
        examPhrasing: "Use low-z approximation linking redshift and speed.",
        tags: ["redshift", "approximation"],
      },
      {
        id: "t25-3-f6",
        noteId: "t25-3",
        difficulty: 3,
        front: "Name one key observational evidence for the Big Bang besides galaxy redshifts.",
        back: "Cosmic microwave background radiation.",
        examPhrasing: "State one observational pillar of the Big Bang model.",
        tags: ["big-bang", "evidence"],
      },
      {
        id: "t25-3-f7",
        noteId: "t25-3",
        difficulty: 4,
        front: "How does a larger measured H0 affect inferred age t approx 1/H0?",
        back: "Larger H0 implies smaller inferred age.",
        examPhrasing: "Use inverse proportionality between Hubble constant and age.",
        confusionPair: "direct vs inverse dependence on H0",
        tags: ["reasoning", "uncertainty"],
      },
      {
        id: "t25-3-f8",
        noteId: "t25-3",
        difficulty: 4,
        front: "What does 'expanding universe' mean in cosmology?",
        back: "On large scales, distances between galaxies increase as space expands.",
        examPhrasing: "Describe expansion as metric expansion of space.",
        tags: ["conceptual", "cosmology"],
      },
      {
        id: "t25-3-f9",
        noteId: "t25-3",
        difficulty: 5,
        front: "Why is there no unique center of expansion in standard Big Bang cosmology?",
        back: "Expansion is of space itself and appears similar from any galaxy on large scales.",
        examPhrasing: "Distinguish cosmological expansion from an explosion in pre-existing space.",
        tags: ["misconceptions", "deep-concept"],
      },
      {
        id: "t25-3-f10",
        noteId: "t25-3",
        difficulty: 5,
        front: "Exam workflow for Hubble-law numericals?",
        back: "Keep units consistent, apply v = H0d or d = v/H0, convert at the end, and check order of magnitude against galactic scales.",
        examPhrasing: "Method marks require equation choice, unit handling, and sensible interpretation.",
        tags: ["exam-technique", "numerical-strategy"],
      },
    ],
  },
};
