import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC16_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t16-1": {
    noteId: "t16-1",
    drills: [
      {
        id: "t16-1-d1",
        noteId: "t16-1",
        kind: "mcq",
        difficulty: 1,
        stem: "What is internal energy of a system?",
        options: [
          { id: "A", text: "Total kinetic and potential energies of its particles" },
          { id: "B", text: "Only kinetic energy of bulk motion of the system" },
          { id: "C", text: "Only gravitational potential energy relative to Earth" },
          { id: "D", text: "Energy transferred electrically to the system" },
        ],
        correctOptionId: "A",
        explanation:
          "Internal energy is the sum of random microscopic kinetic energy and intermolecular potential energy.",
        distractorRationale: {
          B: "Internal energy is microscopic and includes potential energy as well.",
          C: "This is external potential energy, not the system's internal energy.",
          D: "Electrical transfer can change internal energy but is not its definition.",
        },
        tags: ["internal-energy", "definition", "microscopic-model"],
      },
      {
        id: "t16-1-d2",
        noteId: "t16-1",
        kind: "mcq",
        difficulty: 2,
        stem: "For an ideal gas, internal energy depends primarily on",
        options: [
          { id: "A", text: "Pressure only" },
          { id: "B", text: "Volume only" },
          { id: "C", text: "Absolute temperature" },
          { id: "D", text: "Container shape" },
        ],
        correctOptionId: "C",
        explanation:
          "For an ideal gas, intermolecular potential energy is negligible, so internal energy depends on temperature.",
        distractorRationale: {
          B: "Volume change alone does not fix internal energy without temperature information.",
          D: "Geometry does not set internal energy directly.",
        },
        tags: ["ideal-gas", "temperature", "internal-energy"],
      },
      {
        id: "t16-1-d3",
        noteId: "t16-1",
        kind: "mcq",
        difficulty: 3,
        stem: "During melting of ice at 0 degC, the internal energy of the sample",
        options: [
          { id: "A", text: "Decreases because bonds are broken" },
          { id: "B", text: "Stays constant because temperature is constant" },
          { id: "C", text: "Increases due to increase in potential energy between particles" },
          { id: "D", text: "Increases due only to increase in average kinetic energy" },
        ],
        correctOptionId: "C",
        explanation:
          "At constant temperature in a phase change, supplied energy mainly increases intermolecular potential energy.",
        distractorRationale: {
          B: "Constant temperature does not imply constant internal energy during phase change.",
          D: "Average kinetic energy is tied to temperature, which stays constant.",
        },
        tags: ["phase-change", "potential-energy", "internal-energy-change"],
      },
      {
        id: "t16-1-d4",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define internal energy and state its two microscopic components.",
        modelAnswerPoints: [
          "Internal energy is the total microscopic energy stored in a system.",
          "It includes random kinetic energy of particles.",
          "It includes potential energy due to intermolecular forces/separation.",
        ],
        workedSolution: [
          "A complete definition must include both kinetic and potential microscopic terms.",
          "Do not confuse internal energy with bulk kinetic or external potential energies.",
        ],
        commonMistake: "Describing internal energy as only random kinetic energy for all materials.",
        tags: ["definition", "components", "core-knowledge"],
      },
      {
        id: "t16-1-d5",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A gas sample is heated while volume is kept constant.\nDescribe the microscopic change and state what happens to internal energy.",
        modelAnswerPoints: [
          "Average molecular kinetic energy increases.",
          "This corresponds to a rise in absolute temperature.",
          "For an ideal gas, internal energy increases.",
          "No statement about work is needed here; focus is internal-energy change.",
        ],
        workedSolution: [
          "At constant volume, heating raises temperature and hence molecular kinetic-energy scale.",
          "For ideal gases, this directly means an increase in internal energy.",
          "Microscopic explanation should mention faster random motion.",
        ],
        commonMistake: "Saying internal energy cannot change when volume is fixed.",
        tags: ["heating", "constant-volume", "microscopic-interpretation"],
      },
      {
        id: "t16-1-d6",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Explain why internal energy can increase during melting even though temperature stays constant.",
        modelAnswerPoints: [
          "Temperature constant implies average kinetic energy stays approximately constant.",
          "Supplied energy is used to overcome intermolecular attractions.",
          "Intermolecular potential energy increases.",
          "Therefore total internal energy increases.",
        ],
        workedSolution: [
          "Separate kinetic and potential parts of internal energy clearly.",
          "In phase change, added energy changes structure rather than temperature.",
          "Hence constant T does not mean constant U.",
        ],
        commonMistake: "Assuming DeltaT = 0 means no change in internal energy.",
        tags: ["phase-change", "latent-heat", "reasoning"],
      },
      {
        id: "t16-1-d7",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "Two equal masses of the same liquid are heated by equal energies.\nSample A rises by 10 K; sample B is initially at a higher temperature and rises by 10 K as well.\nCompare their changes in internal energy and justify.",
        modelAnswerPoints: [
          "Both receive equal energy inputs.",
          "For this comparison with no phase change, equal heating energy implies equal increase in internal energy.",
          "Equal temperature rise in equal masses of same liquid supports this consistency.",
          "Initial absolute temperature does not by itself force different DeltaU here.",
        ],
        workedSolution: [
          "Internal-energy change is linked to energy transferred to the system.",
          "Given equal masses and equal thermal-energy input in same phase, DeltaU is equal.",
          "Do not infer larger DeltaU just because one started hotter.",
        ],
        commonMistake: "Claiming the hotter sample must gain more internal energy for the same added energy.",
        tags: ["comparative-reasoning", "internal-energy-change", "conceptual"],
      },
      {
        id: "t16-1-d8",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "State and explain one situation where temperature decreases but internal energy does not decrease by the same proportion.",
        modelAnswerPoints: [
          "Example: gas doing work during rapid expansion with cooling.",
          "Temperature decrease indicates reduced average molecular kinetic energy.",
          "Internal energy includes both kinetic and potential parts.",
          "Potential-energy changes and work interactions mean DeltaU is not proportional to temperature drop in general substances.",
        ],
        workedSolution: [
          "Use an example where multiple factors affect internal energy.",
          "Temperature tracks kinetic-energy scale but not full internal-energy content in all cases.",
          "Exam answers gain credit by naming both components and linking to process details.",
        ],
        commonMistake: "Treating internal energy as always directly proportional to Celsius temperature for any material.",
        tags: ["advanced-concept", "temperature-vs-internal-energy", "evaluation"],
      },
      {
        id: "t16-1-d9",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A fixed amount of ideal gas is heated from 300 K to 360 K.\n(a) State how average molecular kinetic energy changes.\n(b) State how internal energy changes.\n(c) Give the ratio of final to initial average molecular kinetic energy.",
        modelAnswerPoints: [
          "Average molecular kinetic energy is proportional to T.",
          "So it increases, and the ratio is 360/300 = 1.20.",
          "For an ideal gas, internal energy increases accordingly.",
          "Hence both kinetic-energy scale and internal energy increase by 20%.",
        ],
        workedSolution: [
          "Use proportionality E_bar proportional T for part (a).",
          "Part (b) follows ideal-gas internal-energy dependence on temperature.",
          "Ratio method avoids unnecessary constants.",
        ],
        commonMistake: "Using Celsius ratio 87/27 instead of kelvin ratio 360/300.",
        tags: ["ideal-gas", "proportionality", "exam-application"],
      },
      {
        id: "t16-1-d10",
        noteId: "t16-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A student writes: 'Internal energy is just heat inside a body.'\nCritique this statement using precise thermodynamics language.",
        modelAnswerPoints: [
          "Internal energy is a state property of the system, not a transfer process.",
          "It consists of microscopic kinetic and potential energy contributions.",
          "Heat (thermal energy transfer) refers to energy in transit due to temperature difference.",
          "A system contains internal energy; it does not 'contain heat' as a stored quantity.",
          "Correct language improves interpretation of first-law questions.",
        ],
        workedSolution: [
          "Start by separating system property (U) from transfer quantity (Q).",
          "Then define each term precisely and relate to exam conventions.",
          "Conclude with why wording matters for sign and process reasoning.",
        ],
        commonMistake: "Using heat and internal energy interchangeably in definitions.",
        tags: ["terminology", "exam-language", "high-order"],
      },
    ],
    flashcards: [
      {
        id: "t16-1-f1",
        noteId: "t16-1",
        difficulty: 1,
        front: "Define internal energy.",
        back: "Internal energy is the total microscopic kinetic and potential energy of particles in a system.",
        examPhrasing: "State that internal energy includes both random kinetic and intermolecular potential components.",
        tags: ["definition", "internal-energy"],
      },
      {
        id: "t16-1-f2",
        noteId: "t16-1",
        difficulty: 1,
        front: "Name the two components of internal energy.",
        back: "Random molecular kinetic energy and intermolecular potential energy.",
        examPhrasing: "List both microscopic components explicitly for full credit.",
        tags: ["components", "recall"],
      },
      {
        id: "t16-1-f3",
        noteId: "t16-1",
        difficulty: 2,
        front: "For an ideal gas, what mainly determines internal energy?",
        back: "Absolute temperature.",
        examPhrasing: "For an ideal gas, U depends only on T.",
        tags: ["ideal-gas", "temperature"],
      },
      {
        id: "t16-1-f4",
        noteId: "t16-1",
        difficulty: 2,
        front: "Why can internal energy rise during melting at constant temperature?",
        back: "Supplied energy increases intermolecular potential energy while average kinetic energy stays about constant.",
        examPhrasing: "Explain phase-change energy in terms of potential-energy increase.",
        tags: ["phase-change", "latent-heat"],
      },
      {
        id: "t16-1-f5",
        noteId: "t16-1",
        difficulty: 3,
        front: "Does constant temperature always mean constant internal energy?",
        back: "No. During phase changes, internal energy can change at constant temperature.",
        examPhrasing: "State that DeltaT = 0 does not imply DeltaU = 0 in all processes.",
        confusionPair: "constant temperature vs constant internal energy",
        tags: ["conceptual", "common-errors"],
      },
      {
        id: "t16-1-f6",
        noteId: "t16-1",
        difficulty: 3,
        front: "What microscopic change corresponds to heating a gas?",
        back: "Average molecular kinetic energy increases.",
        examPhrasing: "Link temperature rise to increased random molecular motion.",
        tags: ["microscopic-model", "heating"],
      },
      {
        id: "t16-1-f7",
        noteId: "t16-1",
        difficulty: 4,
        front: "In precise language, is heat a stored quantity?",
        back: "No. Heat refers to thermal energy transfer, not stored energy.",
        examPhrasing: "Use 'internal energy stored' and 'heat transferred'.",
        confusionPair: "heat vs internal energy",
        tags: ["terminology", "exam-precision"],
      },
      {
        id: "t16-1-f8",
        noteId: "t16-1",
        difficulty: 4,
        front: "How does internal energy differ from bulk kinetic energy?",
        back: "Internal energy concerns random microscopic motion/interactions; bulk kinetic energy is macroscopic motion of the whole body.",
        examPhrasing: "Distinguish internal from external mechanical energies.",
        tags: ["distinction", "mechanics-vs-thermo"],
      },
      {
        id: "t16-1-f9",
        noteId: "t16-1",
        difficulty: 5,
        front: "Why is kelvin preferred when linking microscopic kinetic energy to temperature?",
        back: "Microscopic kinetic-energy relations are proportional to absolute temperature, so kelvin avoids offset errors.",
        examPhrasing: "Use absolute temperature in proportional thermodynamic relations.",
        tags: ["temperature-scale", "kinetic-theory"],
      },
      {
        id: "t16-1-f10",
        noteId: "t16-1",
        difficulty: 5,
        front: "Exam check for internal-energy explanations?",
        back: "State system, identify process, separate kinetic/potential contributions, and use precise transfer language.",
        examPhrasing: "Method marks reward clear micro-to-macro explanation.",
        tags: ["exam-technique", "high-yield"],
      },
    ],
  },
  "t16-2": {
    noteId: "t16-2",
    drills: [
      {
        id: "t16-2-d1",
        noteId: "t16-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which equation states the first law of thermodynamics for a system?",
        options: [
          { id: "A", text: "DeltaU = Q - W" },
          { id: "B", text: "DeltaU = Q + W" },
          { id: "C", text: "DeltaU = W - Q" },
          { id: "D", text: "DeltaU = Q/W" },
        ],
        correctOptionId: "A",
        explanation:
          "Using the common convention where W is work done by the system, first law is DeltaU = Q - W.",
        distractorRationale: {
          B: "This sign would apply only with a different work convention that must be stated.",
          C: "This reverses transfer terms incorrectly for the stated convention.",
          D: "Thermodynamic first law is an energy-balance sum, not a ratio.",
        },
        tags: ["first-law", "equation", "sign-convention"],
      },
      {
        id: "t16-2-d2",
        noteId: "t16-2",
        kind: "mcq",
        difficulty: 2,
        stem: "A gas receives 500 J of thermal energy and does 200 J of work on surroundings. What is DeltaU?",
        options: [
          { id: "A", text: "+700 J" },
          { id: "B", text: "+300 J" },
          { id: "C", text: "-300 J" },
          { id: "D", text: "-700 J" },
        ],
        correctOptionId: "B",
        explanation: "DeltaU = Q - W = 500 - 200 = +300 J.",
        distractorRationale: {
          C: "Would result from reversing sign of Q or W.",
          D: "Combines both sign and arithmetic errors.",
        },
        tags: ["numerical", "energy-balance", "signs"],
      },
      {
        id: "t16-2-d3",
        noteId: "t16-2",
        kind: "mcq",
        difficulty: 3,
        stem: "In an adiabatic process for a closed system, which is true?",
        options: [
          { id: "A", text: "Q = 0, so DeltaU = -W (for W done by system)" },
          { id: "B", text: "W = 0, so DeltaU = Q" },
          { id: "C", text: "DeltaU = 0 always" },
          { id: "D", text: "Temperature must remain constant" },
        ],
        correctOptionId: "A",
        explanation:
          "Adiabatic means no thermal-energy transfer (Q = 0), so internal-energy change is due to work interaction.",
        distractorRationale: {
          B: "Adiabatic does not mean no work.",
          C: "DeltaU can change in adiabatic expansion or compression.",
          D: "Isothermal and adiabatic are different process conditions.",
        },
        tags: ["adiabatic", "first-law", "processes"],
      },
      {
        id: "t16-2-d4",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State the first law of thermodynamics and define each symbol in the chosen sign convention.",
        modelAnswerPoints: [
          "First law: DeltaU = Q - W (with W as work done by system).",
          "DeltaU is change in internal energy; Q is thermal energy transferred to system.",
          "W is work done by system on surroundings.",
        ],
        workedSolution: [
          "A correct equation must be accompanied by clear sign convention wording.",
          "Equivalent forms are acceptable only if symbols are consistently defined.",
        ],
        commonMistake: "Writing an equation without stating what sign convention for work is used.",
        tags: ["definition", "equation", "sign-convention"],
      },
      {
        id: "t16-2-d5",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A gas loses 150 J of thermal energy and 60 J of work is done on the gas.\nUsing DeltaU = Q - W with W as work done by gas, calculate DeltaU.",
        modelAnswerPoints: [
          "Q = -150 J (energy leaves system).",
          "Work done on gas means W = -60 J in this convention.",
          "DeltaU = Q - W = -150 - (-60).",
          "DeltaU = -90 J.",
        ],
        workedSolution: [
          "Translate words to signs before substitution.",
          "Work done on system is negative W when W is defined as by system.",
          "Careful sign handling gives the final decrease in internal energy.",
        ],
        commonMistake: "Taking W = +60 J despite statement 'done on the gas'.",
        tags: ["signs", "worked-example", "energy-accounting"],
      },
      {
        id: "t16-2-d6",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "In an isochoric (constant-volume) heating process, 420 J of thermal energy is supplied.\nState the work done and hence determine DeltaU.",
        modelAnswerPoints: [
          "At constant volume, boundary work done by gas is zero.",
          "So W = 0.",
          "DeltaU = Q - W = Q.",
          "DeltaU = +420 J.",
        ],
        workedSolution: [
          "No volume change implies no pDeltaV work in this context.",
          "Hence all supplied thermal energy increases internal energy.",
          "State both sign and unit in final answer.",
        ],
        commonMistake: "Assuming any heating must involve positive work by the gas.",
        tags: ["isochoric", "first-law-application", "direct-case"],
      },
      {
        id: "t16-2-d7",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "A gas expands and does 320 J of work while its internal energy decreases by 80 J.\nCalculate the thermal energy transfer Q and state its direction.",
        modelAnswerPoints: [
          "Use DeltaU = Q - W.",
          "Substitute: -80 = Q - 320.",
          "Q = +240 J.",
          "Positive Q means thermal energy transferred to the gas.",
        ],
        workedSolution: [
          "Rearrange to Q = DeltaU + W.",
          "Compute Q = -80 + 320 = +240 J.",
          "Despite expansion cooling effect, there is net thermal input.",
        ],
        commonMistake: "Assuming expansion always implies Q is negative.",
        tags: ["inverse-problem", "sign-interpretation", "multi-step"],
      },
      {
        id: "t16-2-d8",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Explain, using the first law, why rapid adiabatic expansion of a gas can reduce its temperature.",
        modelAnswerPoints: [
          "Adiabatic process has Q = 0.",
          "During expansion, gas does positive work on surroundings (W > 0).",
          "From DeltaU = Q - W, DeltaU is negative.",
          "For a gas, lower internal energy corresponds to lower average molecular kinetic energy and lower temperature.",
        ],
        workedSolution: [
          "Start with process condition (adiabatic), then identify sign of work.",
          "Apply the first law symbolically before discussing microscopic interpretation.",
          "Conclude with temperature consequence for gases.",
        ],
        commonMistake: "Saying temperature falls because no work is done in adiabatic processes.",
        tags: ["adiabatic-expansion", "explanation", "concept-link"],
      },
      {
        id: "t16-2-d9",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A closed system undergoes two stages.\nStage 1: Q1 = +600 J, W1 = +250 J (by system).\nStage 2: Q2 = -180 J, W2 = -70 J.\nFind total change in internal energy.",
        modelAnswerPoints: [
          "Use DeltaU = Q - W for each stage.",
          "DeltaU1 = 600 - 250 = +350 J.",
          "DeltaU2 = -180 - (-70) = -110 J.",
          "Total DeltaU = DeltaU1 + DeltaU2 = +240 J.",
        ],
        workedSolution: [
          "Evaluate each stage separately to avoid sign confusion.",
          "A negative W in stage 2 means work done on the system.",
          "Summing stage changes gives net state change.",
        ],
        commonMistake: "Adding all magnitudes without preserving signs.",
        tags: ["multi-stage", "energy-balance", "exam-style"],
      },
      {
        id: "t16-2-d10",
        noteId: "t16-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Compare isothermal and adiabatic expansion of an ideal gas in terms of Q, DeltaU, and W.\nAssume W is work done by the gas and give concise first-law-based reasoning.",
        modelAnswerPoints: [
          "Isothermal ideal-gas expansion: DeltaU = 0 because U depends only on T and T is constant.",
          "Hence from first law, Q = W (positive) for expansion.",
          "Adiabatic expansion: Q = 0 by definition.",
          "Then DeltaU = -W, so DeltaU is negative when gas does work.",
          "Thus temperature stays constant in isothermal case but falls in adiabatic expansion.",
        ],
        workedSolution: [
          "Apply the same first-law framework to both processes with different constraints.",
          "For isothermal ideal gas, use U(T) dependence to set DeltaU.",
          "For adiabatic, set Q first, then infer DeltaU from work sign.",
        ],
        commonMistake: "Stating Q = 0 for isothermal expansion.",
        tags: ["comparison", "isothermal-vs-adiabatic", "high-order"],
      },
    ],
    flashcards: [
      {
        id: "t16-2-f1",
        noteId: "t16-2",
        difficulty: 1,
        front: "State the first law (with W as work done by system).",
        back: "DeltaU = Q - W.",
        examPhrasing: "Define the sign convention explicitly before substituting values.",
        tags: ["first-law", "equation"],
      },
      {
        id: "t16-2-f2",
        noteId: "t16-2",
        difficulty: 1,
        front: "If Q is positive, what does it mean?",
        back: "Thermal energy is transferred to the system.",
        examPhrasing: "Positive Q denotes energy input by heating.",
        tags: ["sign-convention", "q"],
      },
      {
        id: "t16-2-f3",
        noteId: "t16-2",
        difficulty: 2,
        front: "If W is positive in DeltaU = Q - W, what does it mean?",
        back: "The system does work on the surroundings.",
        examPhrasing: "State work direction when assigning signs.",
        tags: ["sign-convention", "work"],
      },
      {
        id: "t16-2-f4",
        noteId: "t16-2",
        difficulty: 2,
        front: "In an isochoric process, what is W?",
        back: "W = 0 (no boundary work from volume change).",
        examPhrasing: "At constant volume, first law reduces to DeltaU = Q.",
        tags: ["isochoric", "special-case"],
      },
      {
        id: "t16-2-f5",
        noteId: "t16-2",
        difficulty: 3,
        front: "What condition defines an adiabatic process?",
        back: "Q = 0 (no thermal-energy transfer).",
        examPhrasing: "Adiabatic does not imply constant temperature.",
        confusionPair: "adiabatic vs isothermal",
        tags: ["adiabatic", "processes"],
      },
      {
        id: "t16-2-f6",
        noteId: "t16-2",
        difficulty: 3,
        front: "For adiabatic expansion with W > 0, what is sign of DeltaU?",
        back: "DeltaU is negative because DeltaU = -W when Q = 0.",
        examPhrasing: "State the sign chain clearly: Q = 0, W > 0, therefore DeltaU < 0.",
        tags: ["adiabatic", "signs"],
      },
      {
        id: "t16-2-f7",
        noteId: "t16-2",
        difficulty: 4,
        front: "For ideal-gas isothermal change, what is DeltaU?",
        back: "DeltaU = 0 because internal energy depends only on temperature.",
        examPhrasing: "Then Q = W follows from first law for that convention.",
        tags: ["isothermal", "ideal-gas"],
      },
      {
        id: "t16-2-f8",
        noteId: "t16-2",
        difficulty: 4,
        front: "How do you avoid sign errors in first-law numericals?",
        back: "Write the convention, assign signs from wording, then substitute into one consistent equation.",
        examPhrasing: "Method marks reward explicit sign assignment.",
        tags: ["exam-technique", "sign-handling"],
      },
      {
        id: "t16-2-f9",
        noteId: "t16-2",
        difficulty: 5,
        front: "Why is first law an energy-conservation statement?",
        back: "It balances internal-energy change with energy transfers by heating and work.",
        examPhrasing: "Use first law as a bookkeeping equation for closed-system processes.",
        tags: ["energy-conservation", "theory"],
      },
      {
        id: "t16-2-f10",
        noteId: "t16-2",
        difficulty: 5,
        front: "Common wording trap in thermodynamics answers?",
        back: "Mixing 'work done by system' with 'work done on system' without adjusting sign.",
        examPhrasing: "State direction with every work term.",
        confusionPair: "work by system vs work on system",
        tags: ["pitfalls", "exam-language"],
      },
    ],
  },
};
