import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC13_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t13-1": {
    noteId: "t13-1",
    drills: [
      {
        id: "t13-1-d1",
        noteId: "t13-1",
        kind: "mcq",
        difficulty: 1,
        stem: "What is meant by gravitational field strength g at a point?",
        options: [
          { id: "A", text: "Force per unit mass on a small test mass" },
          { id: "B", text: "Potential energy per unit mass at that point" },
          { id: "C", text: "Mass per unit volume of the region" },
          { id: "D", text: "Force per unit area due to weight" },
        ],
        correctOptionId: "A",
        explanation: "Gravitational field strength is defined by g = F/m for a small test mass.",
        distractorRationale: {
          B: "This defines gravitational potential, not field strength.",
          C: "This is density.",
          D: "This is pressure.",
        },
        tags: ["definition", "gravitational-field-strength"],
      },
      {
        id: "t13-1-d2",
        noteId: "t13-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which SI unit is correct for gravitational field strength?",
        options: [
          { id: "A", text: "N kg^-1 only" },
          { id: "B", text: "m s^-2 only" },
          { id: "C", text: "Either N kg^-1 or m s^-2" },
          { id: "D", text: "J kg^-1" },
        ],
        correctOptionId: "C",
        explanation: "Since g = F/m and also acceleration of free fall, both N kg^-1 and m s^-2 are equivalent.",
        distractorRationale: {
          B: "This is valid, but not the only valid equivalent form.",
          C: "Correct: both unit forms represent the same quantity.",
          D: "J kg^-1 is the unit of gravitational potential.",
        },
        tags: ["units", "equivalence"],
      },
      {
        id: "t13-1-d3",
        noteId: "t13-1",
        kind: "mcq",
        difficulty: 3,
        stem: "Near Earth's surface, which graph best represents g against altitude h for small changes in h?",
        options: [
          { id: "A", text: "A perfectly horizontal line with no change at all" },
          { id: "B", text: "A slight decrease as h increases" },
          { id: "C", text: "A slight increase as h increases" },
          { id: "D", text: "A random variation unrelated to h" },
        ],
        correctOptionId: "B",
        explanation: "From g = GM/r^2, increasing distance from Earth's centre causes a small decrease in g.",
        distractorRationale: {
          B: "Correct trend for increasing altitude.",
          C: "This is opposite to the inverse-square relation.",
          D: "g changes systematically with distance, not randomly.",
        },
        tags: ["inverse-square", "earth-field", "graphs"],
      },
      {
        id: "t13-1-d4",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define gravitational field strength and state why it is a vector quantity.",
        modelAnswerPoints: [
          "Gravitational field strength is force per unit mass on a small test mass: g = F/m.",
          "Its direction is the direction of gravitational force on a test mass.",
          "So it has both magnitude and direction, therefore it is a vector.",
        ],
        workedSolution: [
          "Start with the formal definition and equation.",
          "Then mention direction toward attracting mass to justify vector nature.",
        ],
        commonMistake: "Giving only unit or magnitude but no directional statement.",
        tags: ["definition", "vector"],
      },
      {
        id: "t13-1-d5",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A probe of mass 2.5 kg is acted on by a gravitational force of 19.5 N. Calculate local gravitational field strength.",
        modelAnswerPoints: [
          "Use g = F/m.",
          "g = 19.5 / 2.5.",
          "g = 7.8 N kg^-1.",
          "Equivalent unit is 7.8 m s^-2.",
        ],
        workedSolution: [
          "Substitute directly into the definition equation.",
          "Quote either standard unit form, or both.",
        ],
        commonMistake: "Multiplying F and m instead of dividing.",
        tags: ["calculation", "g-equals-f-over-m"],
      },
      {
        id: "t13-1-d6",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Explain why all objects in the same gravitational field have the same free-fall acceleration when air resistance is negligible.",
        modelAnswerPoints: [
          "Weight is W = mg, so force is proportional to mass.",
          "Using Newton's second law: a = F/m.",
          "Therefore a = mg/m = g, independent of object mass.",
          "This applies when resistive forces are negligible.",
        ],
        workedSolution: [
          "Link gravitational force law with Newton's second law.",
          "Show mass cancellation explicitly for full reasoning marks.",
        ],
        commonMistake: "Claiming heavier objects always fall faster without considering drag.",
        tags: ["free-fall", "newton-second-law", "reasoning"],
      },
      {
        id: "t13-1-d7",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "At a mountain station, g is measured as 9.78 m s^-2. At sea level nearby, g is 9.81 m s^-2. Give two physical reasons for this difference.",
        modelAnswerPoints: [
          "Mountain station is further from Earth's centre, reducing g by inverse-square effect.",
          "Earth is not a perfect sphere, so radius varies with latitude.",
          "Earth's rotation gives a small effective reduction in measured weight/field strength.",
          "Any two valid, well-explained reasons gain credit.",
        ],
        workedSolution: [
          "State geometrical distance effect first as primary reason.",
          "Then add shape or rotation effects as secondary contributors.",
        ],
        commonMistake: "Saying g differs because object mass changed.",
        tags: ["earth-variation", "qualitative"],
      },
      {
        id: "t13-1-d8",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A graph of weight W against mass m is a straight line through origin with gradient 9.76.\n(a) Interpret the gradient physically.\n(b) Find the weight of 3.4 kg at this location.\n(c) Explain one reason gradient may differ from 9.81.",
        modelAnswerPoints: [
          "For W = mg, gradient of W-m graph equals local g.",
          "So local g = 9.76 N kg^-1.",
          "W = 3.4 x 9.76 = 33.184 N (about 33.2 N).",
          "Difference from 9.81 can arise due to altitude/latitude/local geology/experimental uncertainty.",
        ],
        workedSolution: [
          "Use linear model interpretation before numerical substitution.",
          "Compute weight using the measured local field strength.",
          "End with a physical source of variation.",
        ],
        commonMistake: "Using 9.81 automatically despite provided graph gradient.",
        tags: ["graphs", "weight", "data-interpretation"],
      },
      {
        id: "t13-1-d9",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A body has mass 65 kg on Earth where g = 9.81 N kg^-1 and on a moon where g = 1.62 N kg^-1.\n(a) State its mass on the moon.\n(b) Calculate weight on Earth and on the moon.\n(c) Compare the two values and explain.",
        modelAnswerPoints: [
          "Mass is invariant: 65 kg on both bodies.",
          "Earth weight = 65 x 9.81 = 637.65 N.",
          "Moon weight = 65 x 1.62 = 105.3 N.",
          "Weight changes because g changes with gravitational field, while mass is amount of matter.",
        ],
        workedSolution: [
          "Separate clearly the ideas of mass and weight.",
          "Use W = mg twice with different g values.",
          "Interpret physically to secure explanation mark.",
        ],
        commonMistake: "Changing mass value when moving to a different celestial body.",
        tags: ["mass-vs-weight", "comparative"],
      },
      {
        id: "t13-1-d10",
        noteId: "t13-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A research balloon rises vertically from sea level to high altitude. Suggest a practical method to determine how g varies with height using onboard measurements. Include apparatus, quantities measured, and one major uncertainty.",
        modelAnswerPoints: [
          "Use a calibrated accelerometer in free-fall mode or pendulum method with known length and period relation.",
          "Record altitude with pressure sensor/GPS and corresponding inferred g values.",
          "Control for non-gravitational forces (drag, vibration) and calibrate instruments before flight.",
          "Plot g against altitude and compare trend with inverse-square expectation.",
          "Major uncertainty: drag/air motion affects effective acceleration measurements.",
        ],
        workedSolution: [
          "Propose a realistic measurement approach and identify independent/dependent variables.",
          "Include data-processing step (graph/trend) to link with theory.",
          "Discuss one dominant error source and mitigation.",
        ],
        commonMistake: "Describing only theory without any measurable experimental quantities.",
        tags: ["experimental-design", "high-level", "evaluation"],
      },
    ],
    flashcards: [
      {
        id: "t13-1-f1",
        noteId: "t13-1",
        difficulty: 1,
        front: "Define gravitational field strength.",
        back: "Gravitational field strength at a point is force per unit mass on a small test mass there.",
        examPhrasing: "g = F/m, directed toward the attracting mass.",
        tags: ["definition", "g"],
      },
      {
        id: "t13-1-f2",
        noteId: "t13-1",
        difficulty: 1,
        front: "What two equivalent SI units can be used for g?",
        back: "N kg^-1 and m s^-2.",
        examPhrasing: "These are equivalent because 1 N = 1 kg m s^-2.",
        tags: ["units"],
      },
      {
        id: "t13-1-f3",
        noteId: "t13-1",
        difficulty: 2,
        front: "How is weight related to mass and field strength?",
        back: "Weight is W = mg.",
        examPhrasing: "Weight is the gravitational force on a body.",
        confusionPair: "weight vs mass",
        tags: ["weight", "formula"],
      },
      {
        id: "t13-1-f4",
        noteId: "t13-1",
        difficulty: 2,
        front: "Why is g treated as approximately constant near Earth's surface?",
        back: "For small height changes compared with Earth's radius, the inverse-square change is very small.",
        examPhrasing: "Use constant g model for near-surface problems unless stated otherwise.",
        tags: ["assumptions", "model"],
      },
      {
        id: "t13-1-f5",
        noteId: "t13-1",
        difficulty: 3,
        front: "If mass doubles in the same location, what happens to weight and g?",
        back: "Weight doubles, but g stays the same because g is a property of location, not object mass.",
        examPhrasing: "From W = mg, W proportional m for fixed g.",
        tags: ["proportionality", "concept"],
      },
      {
        id: "t13-1-f6",
        noteId: "t13-1",
        difficulty: 3,
        front: "Why do objects fall with same acceleration in vacuum?",
        back: "Because a = F/m = mg/m = g, so mass cancels.",
        examPhrasing: "Neglecting drag, free-fall acceleration is independent of object mass.",
        tags: ["free-fall", "newton-laws"],
      },
      {
        id: "t13-1-f7",
        noteId: "t13-1",
        difficulty: 4,
        front: "Name two reasons g varies slightly across Earth's surface.",
        back: "Variation in distance from Earth's centre (shape/altitude) and Earth's rotation effects.",
        examPhrasing: "Local geology can also cause small anomalies.",
        tags: ["earth-field", "variation"],
      },
      {
        id: "t13-1-f8",
        noteId: "t13-1",
        difficulty: 4,
        front: "What does the gradient of a W against m graph represent?",
        back: "It represents local gravitational field strength g.",
        examPhrasing: "Linear relation W = mg gives slope g.",
        tags: ["graphs", "interpretation"],
      },
      {
        id: "t13-1-f9",
        noteId: "t13-1",
        difficulty: 5,
        front: "State a common exam trap involving mass and weight on another planet.",
        back: "Mass is unchanged; only weight changes because g is different.",
        examPhrasing: "Always keep mass in kg invariant unless matter is added/removed.",
        confusionPair: "mass vs weight",
        tags: ["exam-technique", "pitfalls"],
      },
      {
        id: "t13-1-f10",
        noteId: "t13-1",
        difficulty: 5,
        front: "How does g change with radial distance r from Earth's centre?",
        back: "Outside Earth, g decreases as 1/r^2.",
        examPhrasing: "g = GM/r^2 for a point mass or spherical mass distribution.",
        tags: ["inverse-square", "extension"],
      },
    ],
  },
  "t13-2": {
    noteId: "t13-2",
    drills: [
      {
        id: "t13-2-d1",
        noteId: "t13-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which expression gives the gravitational force between two point masses m1 and m2 separated by distance r?",
        options: [
          { id: "A", text: "F = Gm1m2/r^2" },
          { id: "B", text: "F = Gm1m2/r" },
          { id: "C", text: "F = G(m1 + m2)/r^2" },
          { id: "D", text: "F = Gm1m2r^2" },
        ],
        correctOptionId: "A",
        explanation: "Newton's law of gravitation is F = Gm1m2/r^2.",
        distractorRationale: {
          B: "This misses inverse-square dependence.",
          C: "Masses multiply rather than add in this law.",
          D: "Force decreases with distance; it does not increase with r^2.",
        },
        tags: ["newton-gravitation", "formula"],
      },
      {
        id: "t13-2-d2",
        noteId: "t13-2",
        kind: "mcq",
        difficulty: 2,
        stem: "If separation between two masses is doubled, the gravitational force becomes",
        options: [
          { id: "A", text: "2F" },
          { id: "B", text: "F/2" },
          { id: "C", text: "F/4" },
          { id: "D", text: "4F" },
        ],
        correctOptionId: "C",
        explanation: "From inverse-square law, F proportional 1/r^2, so doubling r gives one quarter force.",
        distractorRationale: {
          B: "This assumes inverse-first-power instead of inverse-square.",
          C: "Correct inverse-square scaling.",
          D: "Opposite trend to attractive force-distance relation.",
        },
        tags: ["inverse-square", "ratio"],
      },
      {
        id: "t13-2-d3",
        noteId: "t13-2",
        kind: "mcq",
        difficulty: 3,
        stem: "Two masses 3m and m are separated by distance r. What is force on each mass due to the other?",
        options: [
          { id: "A", text: "Force on 3m is three times force on m" },
          { id: "B", text: "Force on m is three times force on 3m" },
          { id: "C", text: "Forces have equal magnitude and opposite direction" },
          { id: "D", text: "Only larger mass experiences gravitational force" },
        ],
        correctOptionId: "C",
        explanation: "By Newton's third law, interaction forces are equal and opposite.",
        distractorRationale: {
          B: "Magnitude is equal despite different accelerations.",
          C: "Correct action-reaction pair statement.",
          D: "Both bodies exert and experience gravitational force.",
        },
        tags: ["newton-third-law", "interaction"],
      },
      {
        id: "t13-2-d4",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State Newton's law of gravitation in words and symbols.",
        modelAnswerPoints: [
          "Any two point masses attract each other along line joining their centres.",
          "Force is proportional to product of masses.",
          "Force is inversely proportional to square of separation: F = Gm1m2/r^2.",
        ],
        workedSolution: [
          "Give both verbal and symbolic forms for full clarity.",
          "Mention direction explicitly along line of centres.",
        ],
        commonMistake: "Omitting inverse-square dependence.",
        tags: ["definition", "core-law"],
      },
      {
        id: "t13-2-d5",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Two satellites of masses 400 kg and 600 kg are 2.0 x 10^3 m apart. Take G = 6.67 x 10^-11 N m^2 kg^-2. Calculate gravitational force between them.",
        modelAnswerPoints: [
          "Use F = Gm1m2/r^2.",
          "Substitute: F = 6.67 x 10^-11 x 400 x 600 / (2.0 x 10^3)^2.",
          "F = 4.00 x 10^-9 N (approximately).",
          "Force is attractive along line joining satellites.",
        ],
        workedSolution: [
          "Square separation carefully in scientific notation.",
          "Track powers of ten before final rounding.",
        ],
        commonMistake: "Forgetting to square the distance.",
        tags: ["numerical", "scientific-notation"],
      },
      {
        id: "t13-2-d6",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "For two stars with fixed separation, one star's mass is tripled while the other is unchanged.\n(a) How does force change?\n(b) Explain in one sentence using proportionality.",
        modelAnswerPoints: [
          "From F proportional m1m2, tripling one mass triples product m1m2.",
          "So new force is 3F.",
          "Separation unchanged, so r^2 factor unchanged.",
          "Hence net scaling factor is 3.",
        ],
        workedSolution: [
          "Use proportional form to avoid unnecessary substitution.",
          "State unchanged quantities explicitly.",
        ],
        commonMistake: "Tripling force and then dividing by 3 again for no reason.",
        tags: ["proportionality", "reasoning"],
      },
      {
        id: "t13-2-d7",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Show using Newton's second law that two isolated masses attracting each other accelerate toward each other with different magnitudes if their masses differ.",
        modelAnswerPoints: [
          "Interaction force magnitude on each mass is same by Newton's third law.",
          "Acceleration of first mass: a1 = F/m1.",
          "Acceleration of second mass: a2 = F/m2.",
          "If m1 ≠ m2, then a1 ≠ a2; smaller mass has larger acceleration magnitude.",
        ],
        workedSolution: [
          "Separate force symmetry from acceleration asymmetry.",
          "Use a = F/m to explain why equal forces do not imply equal accelerations.",
        ],
        commonMistake: "Assuming equal force implies equal acceleration regardless of mass.",
        tags: ["newton-laws", "conceptual-proof"],
      },
      {
        id: "t13-2-d8",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A mass m is midway between two equal masses M separated by distance 2d. Determine net gravitational force on m and explain physically.",
        modelAnswerPoints: [
          "Each M exerts force F = GMm/d^2 on m.",
          "Directions are opposite along same line.",
          "Equal magnitudes cancel, so resultant force is zero.",
          "Midpoint between equal masses is a neutral point on that line.",
        ],
        workedSolution: [
          "Compute one force magnitude, then use symmetry for the second.",
          "Vector cancellation gives exact zero net force.",
        ],
        commonMistake: "Adding magnitudes without considering opposite directions.",
        tags: ["superposition", "symmetry", "fields"],
      },
      {
        id: "t13-2-d9",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Two equal masses M are fixed at x = -0.40 m and x = +0.40 m. A small test mass lies on x-axis at x = +0.10 m.\nExpress the net gravitational force on the test mass in terms of G, M, and m.",
        modelAnswerPoints: [
          "Distances to left and right masses are 0.50 m and 0.30 m respectively.",
          "Force toward right mass: Fr = GMm/(0.30)^2 to +x direction.",
          "Force toward left mass: Fl = GMm/(0.50)^2 to -x direction.",
          "Net force: Fnet = GMm[(1/0.30^2) - (1/0.50^2)] toward +x.",
        ],
        workedSolution: [
          "Assign directions before combining terms.",
          "Use scalar signed-axis method for clean expression.",
        ],
        commonMistake: "Using 0.40 m as both distances instead of position-based distances.",
        tags: ["1d-superposition", "algebra"],
      },
      {
        id: "t13-2-d10",
        noteId: "t13-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A binary system has masses m and 2m separated by distance r.\n(a) Write the gravitational force magnitude.\n(b) Determine ratio of accelerations of m and 2m.\n(c) Explain briefly how momentum conservation is consistent with your result.",
        modelAnswerPoints: [
          "Force magnitude is F = G(m)(2m)/r^2 = 2Gm^2/r^2.",
          "Acceleration of m: a_m = F/m = 2Gm/r^2.",
          "Acceleration of 2m: a_2m = F/(2m) = Gm/r^2.",
          "So a_m : a_2m = 2 : 1.",
          "Equal and opposite interaction forces over same time give equal and opposite momentum changes.",
        ],
        workedSolution: [
          "Use force expression once, then divide by each mass for accelerations.",
          "Connect with impulse-momentum idea to explain consistency.",
        ],
        commonMistake: "Giving acceleration ratio as 1:2 because of mass ratio confusion.",
        tags: ["binary-systems", "ratio", "momentum-link"],
      },
    ],
    flashcards: [
      {
        id: "t13-2-f1",
        noteId: "t13-2",
        difficulty: 1,
        front: "State Newton's law of gravitation formula.",
        back: "F = Gm1m2/r^2.",
        examPhrasing: "Attractive force along the line joining mass centres.",
        tags: ["formula"],
      },
      {
        id: "t13-2-f2",
        noteId: "t13-2",
        difficulty: 1,
        front: "What is the SI unit of G?",
        back: "N m^2 kg^-2.",
        examPhrasing: "Equivalent base-unit form is m^3 kg^-1 s^-2.",
        tags: ["constants", "units"],
      },
      {
        id: "t13-2-f3",
        noteId: "t13-2",
        difficulty: 2,
        front: "How does gravitational force scale with distance?",
        back: "It follows inverse-square scaling: F proportional 1/r^2.",
        examPhrasing: "Doubling r gives one quarter F.",
        tags: ["inverse-square"],
      },
      {
        id: "t13-2-f4",
        noteId: "t13-2",
        difficulty: 2,
        front: "How does force scale if one mass doubles and other factors fixed?",
        back: "Force doubles because F proportional m1m2.",
        examPhrasing: "Any mass scaling directly scales force by same factor.",
        tags: ["proportionality"],
      },
      {
        id: "t13-2-f5",
        noteId: "t13-2",
        difficulty: 3,
        front: "Are gravitational interaction forces on two masses equal?",
        back: "Yes, equal magnitude and opposite direction by Newton's third law.",
        examPhrasing: "Forces are equal even when masses are different.",
        confusionPair: "force vs acceleration",
        tags: ["newton-third-law"],
      },
      {
        id: "t13-2-f6",
        noteId: "t13-2",
        difficulty: 3,
        front: "If forces are equal, why can accelerations differ?",
        back: "Because a = F/m; different masses give different accelerations.",
        examPhrasing: "Smaller mass accelerates more under same force.",
        tags: ["newton-second-law"],
      },
      {
        id: "t13-2-f7",
        noteId: "t13-2",
        difficulty: 4,
        front: "What happens to net force at midpoint between two equal masses on a line?",
        back: "Net force is zero due to equal and opposite contributions.",
        examPhrasing: "Use vector superposition, not scalar addition.",
        tags: ["superposition", "symmetry"],
      },
      {
        id: "t13-2-f8",
        noteId: "t13-2",
        difficulty: 4,
        front: "What is a reliable method for multi-mass gravity problems?",
        back: "Calculate each force vector separately, assign directions, then add components.",
        examPhrasing: "Direction errors are the most common source of lost marks.",
        tags: ["method", "exam-technique"],
      },
      {
        id: "t13-2-f9",
        noteId: "t13-2",
        difficulty: 5,
        front: "Which distance should be used in F = Gm1m2/r^2 for spheres?",
        back: "Centre-to-centre distance between the masses (if treating as point masses/spherical masses).",
        examPhrasing: "Not surface separation unless explicitly converted.",
        confusionPair: "surface distance vs centre distance",
        tags: ["geometry", "pitfalls"],
      },
      {
        id: "t13-2-f10",
        noteId: "t13-2",
        difficulty: 5,
        front: "What quick check helps catch inverse-square mistakes?",
        back: "Test an easy ratio: if r doubles, your expression must give F/4.",
        examPhrasing: "Use scaling checks before finalizing numerical answers.",
        tags: ["quality-check", "ratios"],
      },
    ],
  },
  "t13-3": {
    noteId: "t13-3",
    drills: [
      {
        id: "t13-3-d1",
        noteId: "t13-3",
        kind: "mcq",
        difficulty: 1,
        stem: "What is the gravitational field strength at distance r from a point mass M?",
        options: [
          { id: "A", text: "g = GM/r^2" },
          { id: "B", text: "g = GMr^2" },
          { id: "C", text: "g = GM/r" },
          { id: "D", text: "g = Mr^2/G" },
        ],
        correctOptionId: "A",
        explanation: "For a point mass, gravitational field strength magnitude is g = GM/r^2.",
        distractorRationale: {
          B: "This incorrectly increases with distance.",
          C: "Missing inverse-square dependence.",
          D: "Dimensional form is incorrect.",
        },
        tags: ["point-mass-field", "formula"],
      },
      {
        id: "t13-3-d2",
        noteId: "t13-3",
        kind: "mcq",
        difficulty: 2,
        stem: "At what direction does the gravitational field of a point mass act?",
        options: [
          { id: "A", text: "Radially outward from the mass" },
          { id: "B", text: "Radially inward toward the mass" },
          { id: "C", text: "Tangential to circular path" },
          { id: "D", text: "Perpendicular to radial line always upward" },
        ],
        correctOptionId: "B",
        explanation: "Gravitational interaction is attractive, so field direction is toward the mass.",
        distractorRationale: {
          B: "Correct direction for attractive field.",
          C: "Tangential direction is velocity direction in orbit, not field direction.",
          D: "Field direction is radial, not globally upward.",
        },
        tags: ["direction", "field-lines"],
      },
      {
        id: "t13-3-d3",
        noteId: "t13-3",
        kind: "mcq",
        difficulty: 3,
        stem: "A test mass moves from distance r to 2r from a point mass. How does g change?",
        options: [
          { id: "A", text: "g doubles" },
          { id: "B", text: "g halves" },
          { id: "C", text: "g becomes one quarter" },
          { id: "D", text: "g unchanged" },
        ],
        correctOptionId: "C",
        explanation: "Because g proportional 1/r^2, doubling distance reduces g by factor 4.",
        distractorRationale: {
          B: "This corresponds to inverse-first-power relation.",
          C: "Correct inverse-square scaling.",
          D: "Field strength clearly depends on distance.",
        },
        tags: ["scaling", "inverse-square"],
      },
      {
        id: "t13-3-d4",
        noteId: "t13-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Show that g = GM/r^2 can be obtained from Newton's law of gravitation and g = F/m.",
        modelAnswerPoints: [
          "Start with F = GMm/r^2 for a test mass m near mass M.",
          "Use definition g = F/m.",
          "So g = (GMm/r^2)/m = GM/r^2.",
        ],
        workedSolution: [
          "Introduce the test mass explicitly so cancellation is clear.",
          "Conclude with point-mass field expression.",
        ],
        commonMistake: "Cancelling wrong mass or leaving m in final expression for g.",
        tags: ["derivation", "definitions-link"],
      },
      {
        id: "t13-3-d5",
        noteId: "t13-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Take G = 6.67 x 10^-11 N m^2 kg^-2 and Earth mass M = 5.97 x 10^24 kg. At r = 6.37 x 10^6 m, calculate g.",
        modelAnswerPoints: [
          "Use g = GM/r^2.",
          "Substitute values with r squared.",
          "g = (6.67 x 10^-11 x 5.97 x 10^24) / (6.37 x 10^6)^2.",
          "g is about 9.8 m s^-2.",
        ],
        workedSolution: [
          "Handle powers of ten carefully and square radius first.",
          "Result should be close to known near-surface value, acting as a reasonableness check.",
        ],
        commonMistake: "Using diameter instead of radius for Earth distance.",
        tags: ["earth-g", "numerical", "constants"],
      },
      {
        id: "t13-3-d6",
        noteId: "t13-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "At altitude where distance from Earth's centre is 2.0R, express g in terms of g0 (field strength at R).",
        modelAnswerPoints: [
          "g0 = GM/R^2.",
          "At 2R, g = GM/(2R)^2 = GM/(4R^2).",
          "Hence g = g0/4.",
          "This is inverse-square scaling with radius factor 2.",
        ],
        workedSolution: [
          "Write both expressions symbolically before taking ratio.",
          "Avoid substituting numbers unnecessarily.",
        ],
        commonMistake: "Giving g0/2 due to linear-distance assumption.",
        tags: ["ratio-method", "orbital-radius"],
      },
      {
        id: "t13-3-d7",
        noteId: "t13-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "A satellite orbits where g = 3.2 m s^-2. If Earth's surface field is 9.8 m s^-2 and Earth radius is R, estimate orbital radius in terms of R.",
        modelAnswerPoints: [
          "Use ratio g/g0 = (R^2/r^2).",
          "So r/R = sqrt(g0/g).",
          "r/R = sqrt(9.8/3.2) = sqrt(3.0625) = 1.75.",
          "Orbital radius is about 1.75R.",
        ],
        workedSolution: [
          "Set up inverse-square ratio directly for efficiency.",
          "Interpret radius as from Earth's centre, not altitude above surface.",
        ],
        commonMistake: "Treating 1.75R as altitude rather than orbital radius.",
        tags: ["satellite", "ratios", "interpretation"],
      },
      {
        id: "t13-3-d8",
        noteId: "t13-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Two point masses M1 and M2 lie on x-axis at x = 0 and x = L. Derive an expression for the point between them where net gravitational field is zero.",
        modelAnswerPoints: [
          "Let zero-field point be distance x from M1, so distance from M2 is L - x.",
          "Set field magnitudes equal: GM1/x^2 = GM2/(L - x)^2.",
          "Cancel G and take square roots: sqrt(M1)/x = sqrt(M2)/(L - x).",
          "Rearrange: x = L sqrt(M1)/(sqrt(M1) + sqrt(M2)).",
        ],
        workedSolution: [
          "Use field superposition with opposite directions between the masses.",
          "After squaring/square-rooting, keep algebra clean to avoid sign errors.",
        ],
        commonMistake: "Equating forces on arbitrary test mass without recognizing equivalent field equation.",
        tags: ["zero-field-point", "algebraic-derivation"],
      },
      {
        id: "t13-3-d9",
        noteId: "t13-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A planet has mass 4.0 x 10^24 kg and radius 5.0 x 10^6 m. Calculate escape of g at surface and weight of a 70 kg lander there. Use G = 6.67 x 10^-11.",
        modelAnswerPoints: [
          "Surface field strength: g = GM/R^2.",
          "g = (6.67 x 10^-11 x 4.0 x 10^24)/(5.0 x 10^6)^2 = 10.672 m s^-2 (about 10.7).",
          "Weight of lander: W = mg = 70 x 10.672 = 747 N (about 7.5 x 10^2 N).",
          "State units clearly.",
        ],
        workedSolution: [
          "Compute g first using planetary data.",
          "Then convert field strength to weight for given mass.",
        ],
        commonMistake: "Using Earth g by default instead of calculated local value.",
        tags: ["planetary-field", "application"],
      },
      {
        id: "t13-3-d10",
        noteId: "t13-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A mission profile requires orbital radius where g is exactly 12% of Earth's surface value g0.\n(a) Determine r in terms of Earth radius R.\n(b) Find altitude above surface in terms of R.\n(c) Explain why high-altitude satellites still experience significant gravity.",
        modelAnswerPoints: [
          "Use g/g0 = R^2/r^2 = 0.12.",
          "So r/R = 1/sqrt(0.12) = 2.89 (approximately).",
          "Altitude h = r - R = (2.89 - 1)R = 1.89R.",
          "Gravity remains non-zero at large distance because inverse-square decay is gradual, not abrupt cutoff.",
        ],
        workedSolution: [
          "Solve ratio first, then convert radius to altitude carefully.",
          "Interpretation mark comes from explaining continuous field behavior.",
        ],
        commonMistake: "Assuming astronauts are weightless because gravity is zero.",
        tags: ["high-altitude", "ratios", "conceptual"],
      },
    ],
    flashcards: [
      {
        id: "t13-3-f1",
        noteId: "t13-3",
        difficulty: 1,
        front: "Give the point-mass field strength formula.",
        back: "g = GM/r^2.",
        examPhrasing: "Direction is radially inward toward mass M.",
        tags: ["formula"],
      },
      {
        id: "t13-3-f2",
        noteId: "t13-3",
        difficulty: 1,
        front: "How is gravitational field direction shown around a point mass?",
        back: "Field lines are radial and directed inward.",
        examPhrasing: "Arrows point toward the mass creating the field.",
        tags: ["field-lines"],
      },
      {
        id: "t13-3-f3",
        noteId: "t13-3",
        difficulty: 2,
        front: "What happens to g if r is tripled?",
        back: "g becomes one ninth of original value.",
        examPhrasing: "Inverse-square scaling gives factor 1/3^2.",
        tags: ["ratios"],
      },
      {
        id: "t13-3-f4",
        noteId: "t13-3",
        difficulty: 2,
        front: "Near Earth, how are g and distance from centre related?",
        back: "Outside Earth, g decreases with square of radial distance from centre.",
        examPhrasing: "Use centre-to-point radius, not altitude alone.",
        tags: ["earth-model", "inverse-square"],
      },
      {
        id: "t13-3-f5",
        noteId: "t13-3",
        difficulty: 3,
        front: "How do you convert orbital radius to altitude?",
        back: "Altitude h = r - Rplanet.",
        examPhrasing: "Many exam errors come from quoting r as h.",
        confusionPair: "radius vs altitude",
        tags: ["orbital-geometry"],
      },
      {
        id: "t13-3-f6",
        noteId: "t13-3",
        difficulty: 3,
        front: "Can net gravitational field be zero at some point between two masses?",
        back: "Yes, between them where field magnitudes are equal and opposite.",
        examPhrasing: "Position is closer to the smaller mass if masses are unequal.",
        tags: ["superposition", "null-point"],
      },
      {
        id: "t13-3-f7",
        noteId: "t13-3",
        difficulty: 4,
        front: "What ratio method helps avoid repeated substitution for g at two radii?",
        back: "Use g1/g2 = r2^2/r1^2 from g proportional 1/r^2.",
        examPhrasing: "Ratio form reduces calculator and powers-of-ten errors.",
        tags: ["method", "ratios"],
      },
      {
        id: "t13-3-f8",
        noteId: "t13-3",
        difficulty: 4,
        front: "What physical quantity does g represent operationally?",
        back: "Acceleration of free fall at that location when resistive forces are negligible.",
        examPhrasing: "Numerically equal to force per unit mass and to free-fall acceleration.",
        tags: ["interpretation"],
      },
      {
        id: "t13-3-f9",
        noteId: "t13-3",
        difficulty: 5,
        front: "Why does the point-mass model work well for planets outside the planet?",
        back: "Spherically symmetric mass acts as if all mass were concentrated at centre for external points.",
        examPhrasing: "Use centre distance when applying g = GM/r^2 externally.",
        tags: ["model-justification"],
      },
      {
        id: "t13-3-f10",
        noteId: "t13-3",
        difficulty: 5,
        front: "What exam check confirms your computed orbital g is plausible?",
        back: "If radius is larger than surface radius, g must be smaller than surface g0.",
        examPhrasing: "Monotonic inverse-square trend is a quick sanity check.",
        tags: ["sanity-check", "exam-technique"],
      },
    ],
  },
  "t13-4": {
    noteId: "t13-4",
    drills: [
      {
        id: "t13-4-d1",
        noteId: "t13-4",
        kind: "mcq",
        difficulty: 1,
        stem: "Gravitational potential at a point is defined as",
        options: [
          { id: "A", text: "Force per unit mass" },
          { id: "B", text: "Potential energy per unit mass" },
          { id: "C", text: "Potential energy per unit volume" },
          { id: "D", text: "Work done per unit charge" },
        ],
        correctOptionId: "B",
        explanation: "Gravitational potential is potential energy per unit mass.",
        distractorRationale: {
          C: "Potential is not defined per unit volume.",
          D: "Per unit charge refers to electric potential.",
        },
        tags: ["definition", "gravitational-potential"],
      },
      {
        id: "t13-4-d2",
        noteId: "t13-4",
        kind: "mcq",
        difficulty: 2,
        stem: "Which expression is correct for gravitational potential V at distance r from point mass M (zero at infinity)?",
        options: [
          { id: "A", text: "V = +GM/r" },
          { id: "B", text: "V = -GM/r" },
          { id: "C", text: "V = -GMr" },
          { id: "D", text: "V = -GM/r^2" },
        ],
        correctOptionId: "B",
        explanation: "With zero at infinity, gravitational potential for a point mass is negative: V = -GM/r.",
        distractorRationale: {
          C: "Potential is inverse-r, not proportional to r.",
          D: "Inverse-square form is for field strength g, not potential.",
        },
        tags: ["formula", "sign-convention"],
      },
      {
        id: "t13-4-d3",
        noteId: "t13-4",
        kind: "mcq",
        difficulty: 3,
        stem: "What is the relation between gravitational field strength g and potential V for radial distance r from point mass?",
        options: [
          { id: "A", text: "g = V/r" },
          { id: "B", text: "g = -dV/dr (radial)" },
          { id: "C", text: "g = +dV/dr always" },
          { id: "D", text: "g = Vr" },
        ],
        correctOptionId: "B",
        explanation: "Field is the negative gradient of potential; in 1D radial form g = -dV/dr.",
        distractorRationale: {
          B: "Correct calculus relation between potential and field.",
          C: "Sign is wrong for conservative attractive field.",
          D: "Dimensionally inconsistent.",
        },
        tags: ["field-potential-link", "calculus"],
      },
      {
        id: "t13-4-d4",
        noteId: "t13-4",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define gravitational potential and explain why it is negative when zero is chosen at infinity.",
        modelAnswerPoints: [
          "Gravitational potential is work done per unit mass by an external agent in bringing mass from infinity to the point slowly.",
          "Equivalent to potential energy per unit mass.",
          "It is negative because energy is released when bringing mass in from infinity in an attractive field.",
        ],
        workedSolution: [
          "State reference level first (infinity).",
          "Then connect sign to attractive nature of gravity.",
        ],
        commonMistake: "Saying potential is always positive like electric potential examples with positive charges.",
        tags: ["definition", "reference-level"],
      },
      {
        id: "t13-4-d5",
        noteId: "t13-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "For Earth, take M = 5.97 x 10^24 kg, R = 6.37 x 10^6 m, G = 6.67 x 10^-11. Calculate gravitational potential at Earth's surface.",
        modelAnswerPoints: [
          "Use V = -GM/R.",
          "Substitute values: V = -(6.67 x 10^-11 x 5.97 x 10^24)/(6.37 x 10^6).",
          "V about -6.25 x 10^7 J kg^-1.",
          "Negative sign must be retained.",
        ],
        workedSolution: [
          "Apply point-mass potential formula with radius from centre.",
          "Check magnitude order around 10^7 J kg^-1 for Earth surface.",
        ],
        commonMistake: "Dropping the negative sign in final answer.",
        tags: ["earth-potential", "numerical"],
      },
      {
        id: "t13-4-d6",
        noteId: "t13-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A 2.0 kg mass moves from where potential is -8.0 x 10^6 J kg^-1 to -5.0 x 10^6 J kg^-1.\nFind change in gravitational potential energy.",
        modelAnswerPoints: [
          "Delta V = Vf - Vi = (-5.0 x 10^6) - (-8.0 x 10^6) = +3.0 x 10^6 J kg^-1.",
          "Delta U = m Delta V.",
          "Delta U = 2.0 x 3.0 x 10^6 = 6.0 x 10^6 J.",
          "Positive change means potential energy increased (mass moved to weaker field).",
        ],
        workedSolution: [
          "Compute potential difference first with sign care.",
          "Then multiply by mass for energy change.",
        ],
        commonMistake: "Using absolute values and missing sign of potential difference.",
        tags: ["potential-difference", "energy-change"],
      },
      {
        id: "t13-4-d7",
        noteId: "t13-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Derive escape speed formula v_e = sqrt(2GM/R) by energy conservation for a mass launched from radius R to infinity.",
        modelAnswerPoints: [
          "At launch: total energy E = (1/2)mv_e^2 - GMm/R.",
          "For just escape, final speed at infinity is zero and potential is zero, so Efinal = 0.",
          "Set initial total energy to zero: (1/2)mv_e^2 = GMm/R.",
          "Hence v_e = sqrt(2GM/R).",
        ],
        workedSolution: [
          "Use zero total energy condition for minimum escape.",
          "Mass m cancels, showing escape speed independent of projectile mass.",
        ],
        commonMistake: "Using mgh with constant g over very large distance.",
        tags: ["escape-speed", "energy-method", "derivation"],
      },
      {
        id: "t13-4-d8",
        noteId: "t13-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Show that for a point mass M, potential difference between radii r1 and r2 is Delta V = GM(1/r2 - 1/r1). State sign for r2 > r1.",
        modelAnswerPoints: [
          "Use V(r) = -GM/r.",
          "Delta V = V2 - V1 = (-GM/r2) - (-GM/r1).",
          "So Delta V = GM(1/r1 - 1/r2) equivalently GM(1/r2 - 1/r1) with reversed order convention.",
          "For outward move r2 > r1, Delta V is positive if defined as V2 - V1.",
        ],
        workedSolution: [
          "Substitute carefully and track minus signs step by step.",
          "State your chosen order clearly to avoid sign ambiguity.",
        ],
        commonMistake: "Losing one negative sign and concluding potential gets more negative farther away.",
        tags: ["potential-difference", "signs", "algebra"],
      },
      {
        id: "t13-4-d9",
        noteId: "t13-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A satellite of mass 1200 kg is moved from circular orbit radius 7.0 x 10^6 m to 1.4 x 10^7 m from Earth's centre.\nTake GM = 3.99 x 10^14 m^3 s^-2.\nCalculate change in gravitational potential energy.",
        modelAnswerPoints: [
          "Potential energy U = -GMm/r.",
          "Delta U = U2 - U1 = -GMm(1/r2 - 1/r1).",
          "Delta U = -3.99 x 10^14 x 1200 x [(1/1.4 x 10^7) - (1/7.0 x 10^6)].",
          "Delta U is positive, about +3.42 x 10^10 J.",
        ],
        workedSolution: [
          "Moving to larger radius increases (makes less negative) potential energy.",
          "Compute reciprocal radii first to minimize arithmetic errors.",
        ],
        commonMistake: "Forgetting that potential energy is negative and misreading sign of change.",
        tags: ["satellite-energy", "potential-energy"],
      },
      {
        id: "t13-4-d10",
        noteId: "t13-4",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A spacecraft performs radial transfer from r = 2.0R to r = 3.0R around a planet.\n(a) Express Delta V and Delta U/m in terms of GM and R.\n(b) Compare local field strengths at start and finish.\n(c) Explain why potential changes linearly with 1/r, not with r.",
        modelAnswerPoints: [
          "Using V = -GM/r, Delta V = Vf - Vi = -GM/(3R) + GM/(2R) = GM/(6R).",
          "Specific potential-energy change Delta U/m equals Delta V = GM/(6R).",
          "Field strengths: gi = GM/(2R)^2 = GM/(4R^2), gf = GM/(3R)^2 = GM/(9R^2).",
          "So gf/gi = (1/9)/(1/4) = 4/9.",
          "Potential is integral of field with respect to r; integrating 1/r^2 gives 1/r dependence.",
        ],
        workedSolution: [
          "Work with symbolic expressions to preserve clarity.",
          "Compute field ratio separately after potential part.",
          "Connect calculus relation between field and potential for conceptual depth.",
        ],
        commonMistake: "Assuming potential obeys inverse-square like field strength.",
        tags: ["advanced-symbolic", "field-vs-potential", "integration-idea"],
      },
    ],
    flashcards: [
      {
        id: "t13-4-f1",
        noteId: "t13-4",
        difficulty: 1,
        front: "Define gravitational potential.",
        back: "Potential energy per unit mass at a point in a gravitational field.",
        examPhrasing: "Also interpreted as work done per unit mass bringing mass from infinity to that point.",
        tags: ["definition"],
      },
      {
        id: "t13-4-f2",
        noteId: "t13-4",
        difficulty: 1,
        front: "State point-mass potential formula with zero at infinity.",
        back: "V = -GM/r.",
        examPhrasing: "Negative sign reflects attractive field and infinity reference.",
        tags: ["formula", "sign"],
      },
      {
        id: "t13-4-f3",
        noteId: "t13-4",
        difficulty: 2,
        front: "What is the SI unit of gravitational potential?",
        back: "J kg^-1.",
        examPhrasing: "Equivalent to m^2 s^-2.",
        tags: ["units"],
      },
      {
        id: "t13-4-f4",
        noteId: "t13-4",
        difficulty: 2,
        front: "How are potential energy and potential related for mass m?",
        back: "U = mV and Delta U = m Delta V.",
        examPhrasing: "Use this to convert per-unit-mass results to total energy.",
        tags: ["conversion", "energy"],
      },
      {
        id: "t13-4-f5",
        noteId: "t13-4",
        difficulty: 3,
        front: "How does potential change with increasing r for a point mass?",
        back: "It increases toward zero (becomes less negative) as r increases.",
        examPhrasing: "At infinity, V approaches 0 from below.",
        confusionPair: "more negative vs less negative",
        tags: ["sign-interpretation"],
      },
      {
        id: "t13-4-f6",
        noteId: "t13-4",
        difficulty: 3,
        front: "State relation between field and potential in radial form.",
        back: "g = -dV/dr.",
        examPhrasing: "Field points in direction of decreasing potential.",
        tags: ["calculus-link"],
      },
      {
        id: "t13-4-f7",
        noteId: "t13-4",
        difficulty: 4,
        front: "Why is escape speed independent of spacecraft mass?",
        back: "In energy equation, mass appears in both kinetic and potential terms and cancels.",
        examPhrasing: "v_e = sqrt(2GM/R) has no spacecraft-mass term.",
        tags: ["escape-speed", "reasoning"],
      },
      {
        id: "t13-4-f8",
        noteId: "t13-4",
        difficulty: 4,
        front: "What is a frequent sign error in potential questions?",
        back: "Dropping the negative sign in V = -GM/r or mishandling Delta V = Vf - Vi.",
        examPhrasing: "Write substitution line explicitly before simplification.",
        tags: ["pitfalls", "exam-technique"],
      },
      {
        id: "t13-4-f9",
        noteId: "t13-4",
        difficulty: 5,
        front: "How do potential and field differ in distance dependence?",
        back: "Potential varies as 1/r, field varies as 1/r^2.",
        examPhrasing: "Field is the spatial derivative (gradient) of potential.",
        confusionPair: "V vs g distance law",
        tags: ["comparison", "high-yield"],
      },
      {
        id: "t13-4-f10",
        noteId: "t13-4",
        difficulty: 5,
        front: "What consistency check helps in orbital potential-energy calculations?",
        back: "Moving to larger radius should increase U (less negative), so Delta U should be positive.",
        examPhrasing: "Use physical trend checks to validate sign before final answer.",
        tags: ["sanity-check", "orbital-energy"],
      },
    ],
  },
};
