import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC23_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t23-1": {
    noteId: "t23-1",
    drills: [
      {
        id: "t23-1-d1",
        noteId: "t23-1",
        kind: "mcq",
        difficulty: 1,
        stem: "What is meant by mass defect of a nucleus?",
        options: [
          { id: "A", text: "The mass lost when an atom is ionised" },
          { id: "B", text: "The difference between proton and neutron masses" },
          { id: "C", text: "The difference between total nucleon mass and nuclear mass" },
          { id: "D", text: "The decrease in mass during beta decay only" },
        ],
        correctOptionId: "C",
        explanation:
          "Mass defect is the difference between the sum of separate nucleon masses and the actual mass of the bound nucleus.",
        distractorRationale: {
          B: "Proton and neutron have different masses, but this is not mass defect.",
          C: "Correct definition linked to nuclear binding.",
          D: "Mass defect applies to all nuclei, not only beta decay processes.",
        },
        tags: ["mass-defect", "definitions", "nuclear-structure"],
      },
      {
        id: "t23-1-d2",
        noteId: "t23-1",
        kind: "mcq",
        difficulty: 2,
        stem: "Which equation correctly links binding energy E_b to mass defect Delta m?",
        options: [
          { id: "A", text: "E_b = Delta m / c^2" },
          { id: "B", text: "E_b = Delta m c^2" },
          { id: "C", text: "E_b = m / Delta c^2" },
          { id: "D", text: "E_b = Delta m g h" },
        ],
        correctOptionId: "B",
        explanation:
          "Einstein's mass-energy relation gives nuclear binding energy as E_b = Delta m c^2.",
        distractorRationale: {
          B: "Correct mass-energy conversion relation.",
          C: "This has no physical meaning in this context.",
          D: "mgh is gravitational potential energy, unrelated to binding energy.",
        },
        tags: ["binding-energy", "equations", "mass-energy-equivalence"],
      },
      {
        id: "t23-1-d3",
        noteId: "t23-1",
        kind: "mcq",
        difficulty: 3,
        stem:
          "Nucleus X has binding energy 64 MeV and nucleon number 16. Nucleus Y has binding energy 112 MeV and nucleon number 28. Which has greater stability per nucleon?",
        options: [
          { id: "A", text: "X, because 64 MeV is larger than 112 MeV" },
          { id: "B", text: "Y, because total binding energy is larger" },
          {
            id: "C",
            text: "They are equally stable per nucleon because both have 4.0 MeV per nucleon",
          },
          { id: "D", text: "Neither, because stability depends on charge only" },
        ],
        correctOptionId: "C",
        explanation:
          "Binding energy per nucleon is X = 64/16 = 4.0 MeV and Y = 112/28 = 4.0 MeV, so stability per nucleon is equal.",
        distractorRationale: {
          B: "Incorrect: larger total does not guarantee larger per nucleon.",
          C: "Correct: equal binding energy per nucleon implies equal stability per nucleon.",
          D: "Charge alone is not the stability criterion used here.",
        },
        tags: ["binding-energy-per-nucleon", "stability", "comparison"],
      },
      {
        id: "t23-1-d4",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define (a) mass defect and (b) nuclear binding energy.",
        modelAnswerPoints: [
          "Mass defect is the difference between the total mass of separate nucleons and the mass of the nucleus.",
          "Nuclear binding energy is the energy needed to separate a nucleus completely into individual nucleons.",
          "Equivalently, it is the energy released when nucleons bind to form the nucleus.",
        ],
        workedSolution: [
          "Give both definitions in terms of nucleons and complete separation.",
          "Credit is gained for clear physics meaning, not only formula symbols.",
        ],
        commonMistake: "Defining binding energy as energy to remove one nucleon only.",
        tags: ["definitions", "mass-defect", "binding-energy"],
      },
      {
        id: "t23-1-d5",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A nucleus has mass defect 0.0080 u.\n(a) Calculate binding energy in joules using 1 u = 1.66 x 10^-27 kg and c = 3.00 x 10^8 m s^-1.\n(b) Convert your answer to MeV using 1 eV = 1.60 x 10^-19 J.",
        modelAnswerPoints: [
          "Delta m = 0.0080 x 1.66 x 10^-27 = 1.33 x 10^-29 kg.",
          "E_b = Delta m c^2 = 1.33 x 10^-29 x (3.00 x 10^8)^2 = 1.20 x 10^-12 J.",
          "In eV: E_b = (1.20 x 10^-12)/(1.60 x 10^-19) = 7.48 x 10^6 eV.",
          "Binding energy is 7.48 MeV (about 7.5 MeV).",
        ],
        workedSolution: [
          "Convert atomic mass unit to kg first, then apply E = mc^2.",
          "Use eV conversion at the final stage to avoid compounding rounding error.",
          "State both joule and MeV answers with units.",
        ],
        commonMistake: "Using c instead of c^2 in the energy calculation.",
        tags: ["numerical", "unit-conversion", "mass-energy"],
      },
      {
        id: "t23-1-d6",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "Nucleus A has total binding energy 56 MeV and nucleon number 8.\nNucleus B has total binding energy 120 MeV and nucleon number 20.\nDetermine which is more stable per nucleon.",
        modelAnswerPoints: [
          "For A, binding energy per nucleon = 56/8 = 7.0 MeV.",
          "For B, binding energy per nucleon = 120/20 = 6.0 MeV.",
          "Higher binding energy per nucleon implies greater stability.",
          "Therefore nucleus A is more stable per nucleon.",
        ],
        workedSolution: [
          "Compare per nucleon values, not total binding energy.",
          "State the stability criterion explicitly for full method marks.",
        ],
        commonMistake: "Choosing B because its total binding energy is larger.",
        tags: ["stability", "binding-energy-per-nucleon", "comparison"],
      },
      {
        id: "t23-1-d7",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "The mass of a helium-4 nucleus is 4.0015 u.\nTake proton mass = 1.0073 u and neutron mass = 1.0087 u.\n(a) Calculate mass defect.\n(b) Find binding energy in MeV using 1 u = 931.5 MeV/c^2.",
        modelAnswerPoints: [
          "Mass of separate nucleons = 2(1.0073) + 2(1.0087) = 4.0320 u.",
          "Mass defect Delta m = 4.0320 - 4.0015 = 0.0305 u.",
          "Binding energy E_b = Delta m x 931.5 MeV = 0.0305 x 931.5.",
          "E_b = 28.4 MeV (approximately).",
        ],
        workedSolution: [
          "Compute unbound nucleon mass before subtracting measured nuclear mass.",
          "Use given conversion directly in MeV to avoid SI reconversion.",
          "Maintain clear intermediate values for exam method credit.",
        ],
        commonMistake: "Subtracting in the wrong order and getting negative mass defect.",
        tags: ["helium-4", "mass-defect", "mev-conversion"],
      },
      {
        id: "t23-1-d8",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "Explain why energy is released when light nuclei fuse and when very heavy nuclei undergo fission.\nUse the binding-energy-per-nucleon concept.",
        modelAnswerPoints: [
          "Nuclei move toward products with higher binding energy per nucleon.",
          "Higher binding energy per nucleon means nucleons are in a lower energy (more tightly bound) state.",
          "For light nuclei, fusion increases binding energy per nucleon.",
          "For very heavy nuclei, fission increases binding energy per nucleon in daughter nuclei.",
          "Increase in total binding energy corresponds to energy released to surroundings.",
        ],
        workedSolution: [
          "Use comparative binding-energy-per-nucleon reasoning rather than memorised statements.",
          "Link 'higher binding energy' to lower total nuclear energy explicitly.",
          "Conclude with energy release as the difference in nuclear energy states.",
        ],
        commonMistake: "Saying all fission and all fusion always release energy without condition.",
        tags: ["fusion", "fission", "energy-release", "evaluation"],
      },
      {
        id: "t23-1-d9",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "An isotope has nucleon number 62 and total binding energy 520 MeV.\n(a) Calculate binding energy per nucleon.\n(b) Another isotope with nucleon number 56 has binding energy per nucleon 8.6 MeV.\nState which isotope is more stable per nucleon and justify.",
        modelAnswerPoints: [
          "For first isotope, binding energy per nucleon = 520/62 = 8.39 MeV (approx).",
          "Second isotope has 8.6 MeV per nucleon.",
          "Greater binding energy per nucleon indicates greater stability per nucleon.",
          "Hence the nucleon-56 isotope is more stable per nucleon.",
        ],
        workedSolution: [
          "Round the first value sensibly before comparison.",
          "Comparison must be based on per nucleon values only.",
          "Include explicit stability statement with criterion.",
        ],
        commonMistake: "Comparing 520 MeV directly with 8.6 MeV.",
        tags: ["stability-comparison", "numerical", "exam-precision"],
      },
      {
        id: "t23-1-d10",
        noteId: "t23-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "A reaction is\n2H + 3H -> 4He + n.\nGiven masses: m(2H)=2.0141 u, m(3H)=3.0160 u, m(4He)=4.0026 u, m(n)=1.0087 u.\n(a) Determine mass defect for the reaction.\n(b) Determine energy released per reaction in MeV.\n(c) State one reason why controlled fusion remains technically challenging.",
        modelAnswerPoints: [
          "Reactant mass = 2.0141 + 3.0160 = 5.0301 u.",
          "Product mass = 4.0026 + 1.0087 = 5.0113 u.",
          "Mass defect = 5.0301 - 5.0113 = 0.0188 u.",
          "Energy released = 0.0188 x 931.5 = 17.5 MeV (approx).",
          "Challenge: sustaining sufficiently high temperature and confinement time to overcome Coulomb repulsion and maintain net energy gain.",
        ],
        workedSolution: [
          "Use total mass of each side before subtraction.",
          "Positive mass defect here indicates release of nuclear energy.",
          "Final part needs a physics-based engineering constraint, not a vague statement.",
        ],
        commonMistake: "Adding neutron mass to reactants instead of products.",
        tags: ["fusion-reaction", "mass-defect", "application"],
      },
    ],
    flashcards: [
      {
        id: "t23-1-f1",
        noteId: "t23-1",
        difficulty: 1,
        front: "Define mass defect.",
        back: "Mass defect is the difference between total separate nucleon mass and actual nuclear mass.",
        examPhrasing: "Delta m = sum of nucleon masses - nucleus mass.",
        tags: ["mass-defect", "definition"],
      },
      {
        id: "t23-1-f2",
        noteId: "t23-1",
        difficulty: 1,
        front: "Define nuclear binding energy.",
        back: "It is the energy required to separate a nucleus completely into individual nucleons.",
        examPhrasing: "Equivalent to energy released on nucleus formation.",
        tags: ["binding-energy", "definition"],
      },
      {
        id: "t23-1-f3",
        noteId: "t23-1",
        difficulty: 2,
        front: "State the equation linking binding energy and mass defect.",
        back: "E_b = Delta m c^2.",
        examPhrasing: "Use SI units consistently when calculating in joules.",
        tags: ["equation", "mass-energy"],
      },
      {
        id: "t23-1-f4",
        noteId: "t23-1",
        difficulty: 2,
        front: "What conversion links u and MeV/c^2?",
        back: "1 u = 931.5 MeV/c^2.",
        examPhrasing: "So Delta m in u gives E directly in MeV via x931.5.",
        tags: ["conversion", "mev"],
      },
      {
        id: "t23-1-f5",
        noteId: "t23-1",
        difficulty: 3,
        front: "Why is binding energy per nucleon useful?",
        back: "It allows fair comparison of nuclear stability across different mass numbers.",
        examPhrasing: "Higher E_b per nucleon generally implies greater stability.",
        tags: ["stability", "comparison"],
      },
      {
        id: "t23-1-f6",
        noteId: "t23-1",
        difficulty: 3,
        front: "Why can both fusion and fission release energy?",
        back: "Both can move nuclei toward products with higher binding energy per nucleon.",
        examPhrasing: "Energy release equals increase in total binding energy.",
        confusionPair: "Total binding energy vs binding energy per nucleon",
        tags: ["fusion", "fission", "energy-release"],
      },
      {
        id: "t23-1-f7",
        noteId: "t23-1",
        difficulty: 4,
        front: "In mass-defect calculations, what subtraction order avoids sign errors?",
        back: "Use unbound nucleon mass minus bound nuclear mass.",
        examPhrasing: "Delta m should be positive for a bound nucleus.",
        tags: ["calculation-technique", "pitfalls"],
      },
      {
        id: "t23-1-f8",
        noteId: "t23-1",
        difficulty: 4,
        front: "What common mistake appears in stability comparisons?",
        back: "Comparing total binding energy instead of binding energy per nucleon.",
        examPhrasing: "Always normalise by nucleon number A.",
        tags: ["exam-technique", "stability"],
      },
      {
        id: "t23-1-f9",
        noteId: "t23-1",
        difficulty: 5,
        front: "What does a larger binding energy per nucleon imply physically?",
        back: "Nucleons are in a lower-energy, more strongly bound state.",
        examPhrasing: "More energy is required to separate the nucleus per nucleon.",
        tags: ["interpretation", "nuclear-stability"],
      },
      {
        id: "t23-1-f10",
        noteId: "t23-1",
        difficulty: 5,
        front: "Exam checklist for binding-energy questions?",
        back: "Compute masses carefully, keep units explicit, convert at the end, and state stability criterion using E_b per nucleon.",
        examPhrasing: "Method marks reward clear mass accounting and justified comparisons.",
        tags: ["exam-technique", "problem-solving"],
      },
    ],
  },
  "t23-2": {
    noteId: "t23-2",
    drills: [
      {
        id: "t23-2-d1",
        noteId: "t23-2",
        kind: "mcq",
        difficulty: 1,
        stem: "What is radioactive decay?",
        options: [
          { id: "A", text: "Ionisation of atoms by heating" },
          { id: "B", text: "Random spontaneous disintegration of unstable nuclei" },
          { id: "C", text: "Fusion of light nuclei at high temperature" },
          { id: "D", text: "A process that requires an external trigger each time" },
        ],
        correctOptionId: "B",
        explanation:
          "Radioactive decay is a spontaneous and random process in unstable nuclei, unaffected by normal physical conditions.",
        distractorRationale: {
          B: "Correct statement of randomness and spontaneity.",
          C: "Fusion is a different nuclear process.",
          D: "Decay does not require external triggering.",
        },
        tags: ["radioactive-decay", "definitions", "randomness"],
      },
      {
        id: "t23-2-d2",
        noteId: "t23-2",
        kind: "mcq",
        difficulty: 2,
        stem: "The decay constant lambda has SI unit",
        options: [
          { id: "A", text: "s" },
          { id: "B", text: "s^-1" },
          { id: "C", text: "Bq" },
          { id: "D", text: "J s^-1" },
        ],
        correctOptionId: "B",
        explanation: "From activity A = lambda N, lambda must have units of per second.",
        distractorRationale: {
          B: "Correct unit for a probability rate per nucleus.",
          C: "Bq is unit of activity, not decay constant.",
        },
        tags: ["decay-constant", "units", "activity"],
      },
      {
        id: "t23-2-d3",
        noteId: "t23-2",
        kind: "mcq",
        difficulty: 3,
        stem:
          "A sample has half-life 8.0 h. What fraction of original undecayed nuclei remains after 24 h?",
        options: [
          { id: "A", text: "1/2" },
          { id: "B", text: "1/3" },
          { id: "C", text: "1/8" },
          { id: "D", text: "1/16" },
        ],
        correctOptionId: "C",
        explanation:
          "24 h corresponds to 3 half-lives, so remaining fraction is (1/2)^3 = 1/8.",
        distractorRationale: {
          B: "Decay is exponential, not linear in time.",
          C: "Correct use of repeated halving.",
          D: "Would correspond to 4 half-lives (32 h).",
        },
        tags: ["half-life", "exponential-decay", "fractions"],
      },
      {
        id: "t23-2-d4",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define (a) decay constant and (b) half-life.",
        modelAnswerPoints: [
          "Decay constant lambda is the probability per unit time that a given nucleus decays.",
          "Half-life is the time for the number of undecayed nuclei (or activity) to fall to half its initial value.",
          "Half-life is related by T_(1/2) = ln2/lambda.",
        ],
        workedSolution: [
          "Include probabilistic wording for decay constant.",
          "Half-life definition can be in terms of N or A since both are proportional.",
        ],
        commonMistake: "Defining half-life as time for all nuclei to decay.",
        tags: ["definitions", "half-life", "decay-constant"],
      },
      {
        id: "t23-2-d5",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "A sample has initial activity 960 Bq and half-life 6.0 h.\nFind the activity after 18 h.",
        modelAnswerPoints: [
          "18 h corresponds to 3 half-lives.",
          "Activity halves every half-life.",
          "A = 960 x (1/2)^3 = 120 Bq.",
          "Final activity is 120 Bq.",
        ],
        workedSolution: [
          "Use ratio method for integer number of half-lives.",
          "Could also use A = A0 exp(-lambda t) with same result.",
        ],
        commonMistake: "Subtracting equal activity amounts instead of halving.",
        tags: ["activity", "half-life-calculation", "core-skill"],
      },
      {
        id: "t23-2-d6",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem:
          "The decay constant of a radionuclide is 2.31 x 10^-4 s^-1.\n(a) Calculate its half-life.\n(b) State the answer in minutes.",
        modelAnswerPoints: [
          "Use T_(1/2) = ln2/lambda.",
          "T_(1/2) = 0.693/(2.31 x 10^-4) = 3.00 x 10^3 s.",
          "Convert to minutes: 3.00 x 10^3 / 60 = 50.0 min.",
          "Half-life is 50.0 min.",
        ],
        workedSolution: [
          "Substitute lambda in s^-1 to obtain time in seconds first.",
          "Unit conversion to minutes is separate final step.",
        ],
        commonMistake: "Using log10 instead of natural log relation with 0.693.",
        tags: ["decay-constant", "half-life", "unit-conversion"],
      },
      {
        id: "t23-2-d7",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem:
          "A source has initial undecayed nuclei N0 = 4.8 x 10^20 and decay constant lambda = 1.6 x 10^-5 s^-1.\n(a) Calculate initial activity.\n(b) Find N after 2.0 x 10^4 s.",
        modelAnswerPoints: [
          "Initial activity A0 = lambda N0 = 1.6 x 10^-5 x 4.8 x 10^20 = 7.68 x 10^15 Bq.",
          "Use N = N0 exp(-lambda t).",
          "lambda t = 1.6 x 10^-5 x 2.0 x 10^4 = 0.32.",
          "N = 4.8 x 10^20 exp(-0.32) = 3.49 x 10^20.",
        ],
        workedSolution: [
          "Part (a) directly applies A = lambda N.",
          "Part (b) uses exponential decay with consistent SI units.",
          "Keep intermediate exponent value before calculator evaluation.",
        ],
        commonMistake: "Using N = N0(1-lambda t), which is not valid for finite time intervals.",
        tags: ["activity-equation", "exponential-model", "multi-step"],
      },
      {
        id: "t23-2-d8",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A detector records count rate from a source as 620 counts min^-1.\nBackground count rate is 140 counts min^-1.\n(a) Find net source count rate.\n(b) If source net count rate after some time is 120 counts min^-1, what fraction of original activity remains?\n(c) Determine number of elapsed half-lives.",
        modelAnswerPoints: [
          "Initial net source rate = 620 - 140 = 480 counts min^-1.",
          "Later net source rate = 120 counts min^-1.",
          "Fraction remaining = 120/480 = 1/4.",
          "1/4 corresponds to two half-lives.",
        ],
        workedSolution: [
          "Background subtraction is required before decay analysis.",
          "Count rate is proportional to activity, so fraction ratios are valid.",
          "Map fraction to powers of 1/2 to get half-life count.",
        ],
        commonMistake: "Using total detected count rates without subtracting background.",
        tags: ["background-radiation", "count-rate", "half-life"],
      },
      {
        id: "t23-2-d9",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem:
          "A nuclide has half-life 5.0 days.\n(a) Derive its decay constant in day^-1 and s^-1.\n(b) Find the time for activity to fall to 20% of initial value.",
        modelAnswerPoints: [
          "lambda = ln2 / 5.0 = 0.1386 day^-1.",
          "In s^-1: lambda = 0.1386 / 86400 = 1.60 x 10^-6 s^-1.",
          "Use A/A0 = exp(-lambda t).",
          "For A/A0 = 0.20, t = -ln(0.20)/lambda = 1.609/0.1386 = 11.6 days.",
        ],
        workedSolution: [
          "Keep consistent time units for each part.",
          "Use natural logarithms for exponential-decay rearrangement.",
          "Final time should exceed one half-life, consistent with 20% remaining.",
        ],
        commonMistake: "Assuming 20% corresponds to a whole-number of half-lives.",
        tags: ["logarithms", "decay-constant", "non-integer-half-lives"],
      },
      {
        id: "t23-2-d10",
        noteId: "t23-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem:
          "Two isotopes P and Q have initial activities 4.0 kBq and 4.0 kBq.\nHalf-lives are 2.0 h (P) and 6.0 h (Q).\n(a) After 6.0 h, calculate activity of each and total activity.\n(b) Determine what percentage of total activity is from Q.\n(c) Explain briefly why longer-half-life isotopes dominate activity at late times.",
        modelAnswerPoints: [
          "For P after 6.0 h (3 half-lives): A_P = 4.0 x (1/2)^3 = 0.50 kBq.",
          "For Q after 6.0 h (1 half-life): A_Q = 4.0 x (1/2) = 2.0 kBq.",
          "Total activity = 0.50 + 2.0 = 2.50 kBq.",
          "Percentage from Q = (2.0/2.50) x 100 = 80%.",
          "Longer-half-life isotopes decay more slowly, so their activity falls less steeply and they become the larger contributor over time.",
        ],
        workedSolution: [
          "Treat each isotope independently before summing activities.",
          "Use fractional form of decay for exact half-life multiples.",
          "Interpretation part should reference relative decay rates, not initial activity differences.",
        ],
        commonMistake: "Adding half-lives directly as if the isotopes were a single source.",
        tags: ["mixed-sources", "comparative-decay", "high-mark"],
      },
    ],
    flashcards: [
      {
        id: "t23-2-f1",
        noteId: "t23-2",
        difficulty: 1,
        front: "What is radioactive decay?",
        back: "Random spontaneous disintegration of unstable nuclei.",
        examPhrasing: "It is unaffected by temperature, pressure, or chemical state.",
        tags: ["radioactivity", "definition"],
      },
      {
        id: "t23-2-f2",
        noteId: "t23-2",
        difficulty: 1,
        front: "Define activity.",
        back: "Activity is the number of decays per unit time: A = -dN/dt = lambda N.",
        examPhrasing: "SI unit is becquerel (Bq), equal to s^-1.",
        tags: ["activity", "definitions"],
      },
      {
        id: "t23-2-f3",
        noteId: "t23-2",
        difficulty: 2,
        front: "Define decay constant lambda.",
        back: "Probability per unit time that an individual nucleus decays.",
        examPhrasing: "Unit of lambda is s^-1.",
        tags: ["decay-constant", "probability"],
      },
      {
        id: "t23-2-f4",
        noteId: "t23-2",
        difficulty: 2,
        front: "State the half-life relation with decay constant.",
        back: "T_(1/2) = ln2 / lambda.",
        examPhrasing: "Equivalent form: lambda = 0.693 / T_(1/2).",
        tags: ["half-life", "equations"],
      },
      {
        id: "t23-2-f5",
        noteId: "t23-2",
        difficulty: 3,
        front: "Write the exponential law for undecayed nuclei.",
        back: "N = N0 exp(-lambda t).",
        examPhrasing: "Activity obeys same form: A = A0 exp(-lambda t).",
        tags: ["exponential-decay", "models"],
      },
      {
        id: "t23-2-f6",
        noteId: "t23-2",
        difficulty: 3,
        front: "Why can half-life be found from activity data?",
        back: "Because activity is directly proportional to number of undecayed nuclei.",
        examPhrasing: "A/A0 = N/N0 for the same nuclide.",
        tags: ["activity", "half-life"],
      },
      {
        id: "t23-2-f7",
        noteId: "t23-2",
        difficulty: 4,
        front: "How should detector background be handled in decay calculations?",
        back: "Subtract background count rate from measured count rate before applying decay equations.",
        examPhrasing: "Use net source count rate for proportional comparisons.",
        tags: ["background", "experimental-technique"],
      },
      {
        id: "t23-2-f8",
        noteId: "t23-2",
        difficulty: 4,
        front: "What is the main shape of a decay graph A vs t?",
        back: "An exponential decrease, steep initially then flattening.",
        examPhrasing: "It is not a straight-line decrease with time.",
        confusionPair: "Exponential decay vs linear drop",
        tags: ["graphs", "interpretation"],
      },
      {
        id: "t23-2-f9",
        noteId: "t23-2",
        difficulty: 5,
        front: "Why do long-half-life isotopes dominate mixed-source activity at late times?",
        back: "Their activity decays more slowly, so shorter-half-life components become negligible first.",
        examPhrasing: "Dominance depends on decay rate, not only initial activity.",
        tags: ["mixed-sources", "advanced-reasoning"],
      },
      {
        id: "t23-2-f10",
        noteId: "t23-2",
        difficulty: 5,
        front: "Exam checklist for radioactive-decay questions?",
        back: "Define symbols, subtract background if needed, keep time units consistent, use exponential/half-life form correctly, and quote final units.",
        examPhrasing: "Most lost marks come from unit inconsistency and wrong decay model.",
        tags: ["exam-technique", "problem-solving"],
      },
    ],
  },
};
