import type { SubtopicPracticePack } from "./types";

export const PHYSICS_TOPIC22_PRACTICE: Record<string, SubtopicPracticePack> = {
  "t22-1": {
    noteId: "t22-1",
    drills: [
      {
        id: "t22-1-d1",
        noteId: "t22-1",
        kind: "mcq",
        difficulty: 1,
        stem: "Which expression gives the energy of a photon?",
        options: [
          { id: "A", text: "E = hf" },
          { id: "B", text: "E = h/f" },
          { id: "C", text: "E = hc f" },
          { id: "D", text: "E = mc^2 for all photons at rest" },
        ],
        correctOptionId: "A",
        explanation: "Photon energy is quantised and given by Planck's relation E = hf.",
        distractorRationale: {
          B: "Frequency multiplies h, not divides it.",
          C: "Multiplying by c gives incorrect dimensions.",
          D: "Photons have no rest state in this context; use E = hf and p = E/c.",
        },
        tags: ["photon-energy", "planck-constant", "equation-recall"],
      },
      {
        id: "t22-1-d2",
        noteId: "t22-1",
        kind: "mcq",
        difficulty: 2,
        stem: "A photon has frequency 6.0 x 10^14 Hz. Which is closest to its momentum?",
        options: [
          { id: "A", text: "1.3 x 10^-27 kg m s^-1" },
          { id: "B", text: "4.0 x 10^-19 kg m s^-1" },
          { id: "C", text: "2.0 x 10^-40 kg m s^-1" },
          { id: "D", text: "6.0 x 10^14 kg m s^-1" },
        ],
        correctOptionId: "A",
        explanation: "Use p = hf/c. Substitution gives p about 1.3 x 10^-27 kg m s^-1.",
        distractorRationale: {
          B: "This is near photon energy in joules, not momentum.",
          C: "Over-dividing by powers of ten gives an unrealistically tiny value.",
          D: "Frequency itself is not momentum.",
        },
        tags: ["photon-momentum", "numerical", "constants"],
      },
      {
        id: "t22-1-d3",
        noteId: "t22-1",
        kind: "mcq",
        difficulty: 3,
        stem: "When wavelength of electromagnetic radiation decreases, photon momentum",
        options: [
          { id: "A", text: "decreases because p is proportional to lambda" },
          { id: "B", text: "increases because p = h/lambda" },
          { id: "C", text: "stays constant for all photons" },
          { id: "D", text: "becomes zero below visible wavelengths" },
        ],
        correctOptionId: "B",
        explanation: "Photon momentum is inversely proportional to wavelength: p = h/lambda.",
        distractorRationale: {
          B: "Correct inverse dependence.",
          C: "Momentum changes with wavelength/frequency.",
          D: "There is no such wavelength cutoff for photon momentum becoming zero.",
        },
        tags: ["wavelength", "inverse-proportionality", "photon-model"],
      },
      {
        id: "t22-1-d4",
        noteId: "t22-1",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State equations for photon energy and photon momentum in terms of frequency and wavelength.",
        modelAnswerPoints: [
          "Photon energy: E = hf.",
          "Photon momentum: p = E/c.",
          "Equivalent momentum form: p = h/lambda.",
        ],
        workedSolution: [
          "Start from Planck relation E = hf.",
          "Combine with c = f lambda to obtain p = hf/c = h/lambda.",
        ],
        commonMistake: "Writing p = hc/lambda (this is energy, not momentum).",
        tags: ["definitions", "equations", "core-knowledge"],
      },
      {
        id: "t22-1-d5",
        noteId: "t22-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Calculate energy of a 450 nm photon. Use h = 6.63 x 10^-34 J s and c = 3.00 x 10^8 m s^-1.",
        modelAnswerPoints: [
          "Use E = hc/lambda.",
          "Convert wavelength: 450 nm = 4.50 x 10^-7 m.",
          "E = (6.63 x 10^-34 x 3.00 x 10^8)/(4.50 x 10^-7).",
          "E = 4.42 x 10^-19 J.",
        ],
        workedSolution: [
          "Converting nm to m is required before substitution.",
          "Keep scientific notation through the arithmetic to avoid exponent errors.",
        ],
        commonMistake: "Using 450 as metres instead of 450 nm.",
        tags: ["calculation", "wavelength-conversion", "photon-energy"],
      },
      {
        id: "t22-1-d6",
        noteId: "t22-1",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "A photon has energy 8.0 x 10^-19 J.\n(a) Find its frequency.\n(b) Find its wavelength.",
        modelAnswerPoints: [
          "f = E/h = (8.0 x 10^-19)/(6.63 x 10^-34) = 1.21 x 10^15 Hz.",
          "Use lambda = c/f.",
          "lambda = (3.00 x 10^8)/(1.21 x 10^15) = 2.49 x 10^-7 m.",
          "Wavelength is about 249 nm.",
        ],
        workedSolution: [
          "Find frequency first using Planck's relation.",
          "Then convert frequency to wavelength with c = f lambda.",
        ],
        commonMistake: "Using lambda = f/c instead of c/f.",
        tags: ["multi-step", "frequency", "wavelength"],
      },
      {
        id: "t22-1-d7",
        noteId: "t22-1",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Determine momentum of a 620 nm photon and compare it with that of a 310 nm photon.",
        modelAnswerPoints: [
          "Use p = h/lambda.",
          "For 620 nm: p = 6.63 x 10^-34 / 6.20 x 10^-7 = 1.07 x 10^-27 kg m s^-1.",
          "For 310 nm: p = 6.63 x 10^-34 / 3.10 x 10^-7 = 2.14 x 10^-27 kg m s^-1.",
          "Halving wavelength doubles momentum.",
        ],
        workedSolution: [
          "Compute each momentum from wavelength directly.",
          "Use ratio reasoning to verify: p proportional 1/lambda.",
        ],
        commonMistake: "Assuming shorter wavelength means lower momentum.",
        tags: ["comparison", "momentum", "proportionality"],
      },
      {
        id: "t22-1-d8",
        noteId: "t22-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A laser emits 2.5 mW monochromatic light of wavelength 500 nm.\n(a) Find energy per photon.\n(b) Find number of photons emitted each second.",
        modelAnswerPoints: [
          "Photon energy: E = hc/lambda = 3.98 x 10^-19 J.",
          "Power P = energy per second.",
          "Photon rate N = P/E = (2.5 x 10^-3)/(3.98 x 10^-19).",
          "N = 6.28 x 10^15 photons s^-1.",
        ],
        workedSolution: [
          "First evaluate single-photon energy from wavelength.",
          "Then divide total energy per second by energy per photon.",
          "Units confirm output as photons per second.",
        ],
        commonMistake: "Multiplying P by E instead of dividing.",
        tags: ["laser", "photon-rate", "applications"],
      },
      {
        id: "t22-1-d9",
        noteId: "t22-1",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Show that p = E/c for photons is consistent with E = hf and c = f lambda.",
        modelAnswerPoints: [
          "Start with E = hf.",
          "From c = f lambda, write f = c/lambda.",
          "So E = h(c/lambda) = hc/lambda.",
          "Since p = h/lambda, substitute to get E = pc and hence p = E/c.",
        ],
        workedSolution: [
          "Use algebraic substitution between wave and photon expressions.",
          "Final statement should include the derived relation explicitly.",
        ],
        commonMistake: "Treating p = E/c as unrelated fact without showing linkage.",
        tags: ["derivation", "consistency", "photon-relations"],
      },
      {
        id: "t22-1-d10",
        noteId: "t22-1",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A beam contains photons of two wavelengths: 400 nm and 800 nm. Equal numbers of each arrive every second.\n(a) Compare photon energies.\n(b) Compare total power carried by each wavelength group.\n(c) State one experimental implication for detector response.",
        modelAnswerPoints: [
          "Energy is inversely proportional to wavelength, so 400 nm photons have twice energy of 800 nm photons.",
          "Equal photon arrival rates imply power proportional to energy per photon.",
          "So the 400 nm group carries twice the power of the 800 nm group.",
          "A detector sensitive to deposited energy per second would register a larger signal for the 400 nm component.",
        ],
        workedSolution: [
          "Use E = hc/lambda to establish 2:1 energy ratio.",
          "Power = photon rate x energy per photon; rates are equal by statement.",
          "Tie conclusion to a measurable consequence.",
        ],
        commonMistake: "Assuming equal photon counts imply equal power regardless of wavelength.",
        tags: ["reasoning", "power", "high-yield"],
      },
    ],
    flashcards: [
      {
        id: "t22-1-f1",
        noteId: "t22-1",
        difficulty: 1,
        front: "State Planck's relation for photon energy.",
        back: "E = hf.",
        examPhrasing: "Photon energy is proportional to frequency.",
        tags: ["planck-relation", "energy"],
      },
      {
        id: "t22-1-f2",
        noteId: "t22-1",
        difficulty: 1,
        front: "Write photon momentum in terms of wavelength.",
        back: "p = h/lambda.",
        examPhrasing: "Use p = h/lambda for numerical momentum questions.",
        tags: ["momentum", "wavelength"],
      },
      {
        id: "t22-1-f3",
        noteId: "t22-1",
        difficulty: 2,
        front: "Write photon momentum in terms of energy.",
        back: "p = E/c.",
        examPhrasing: "For photons, E = pc.",
        tags: ["momentum-energy", "equation"],
      },
      {
        id: "t22-1-f4",
        noteId: "t22-1",
        difficulty: 2,
        front: "How are frequency and wavelength related for light in vacuum?",
        back: "c = f lambda.",
        examPhrasing: "Use c = f lambda to convert between f and lambda.",
        tags: ["wave-relation", "vacuum"],
      },
      {
        id: "t22-1-f5",
        noteId: "t22-1",
        difficulty: 3,
        front: "What happens to photon energy when wavelength halves?",
        back: "Photon energy doubles because E is inversely proportional to wavelength.",
        examPhrasing: "From E = hc/lambda, halving lambda doubles E.",
        tags: ["proportionality", "conceptual"],
      },
      {
        id: "t22-1-f6",
        noteId: "t22-1",
        difficulty: 3,
        front: "What happens to photon momentum when wavelength doubles?",
        back: "Momentum halves because p is inversely proportional to wavelength.",
        examPhrasing: "From p = h/lambda, larger lambda gives smaller p.",
        tags: ["proportionality", "momentum"],
      },
      {
        id: "t22-1-f7",
        noteId: "t22-1",
        difficulty: 4,
        front: "How do you find photon emission rate from laser power?",
        back: "Calculate E per photon, then use rate = P/E.",
        examPhrasing: "Photon rate equals energy per second divided by energy per photon.",
        tags: ["applications", "laser"],
      },
      {
        id: "t22-1-f8",
        noteId: "t22-1",
        difficulty: 4,
        front: "Most common unit conversion trap for photon questions?",
        back: "Forgetting to convert nm to m before using E = hc/lambda or p = h/lambda.",
        examPhrasing: "Always use SI units in substitutions.",
        tags: ["units", "pitfalls"],
      },
      {
        id: "t22-1-f9",
        noteId: "t22-1",
        difficulty: 5,
        front: "Why does higher-frequency radiation transfer more energy per photon?",
        back: "Because E is directly proportional to f via E = hf.",
        examPhrasing: "Energy quantisation links higher frequency to larger quantum energy.",
        tags: ["quantisation", "frequency"],
      },
      {
        id: "t22-1-f10",
        noteId: "t22-1",
        difficulty: 5,
        front: "Equal photon count but different wavelength: what sets power difference?",
        back: "Power difference comes from different energy per photon, P proportional N_dot x E.",
        examPhrasing: "At equal arrival rate, shorter wavelength gives greater power.",
        confusionPair: "equal photon number vs equal power",
        tags: ["reasoning", "power", "exam-technique"],
      },
    ],
  },

  "t22-2": {
    noteId: "t22-2",
    drills: [
      {
        id: "t22-2-d1",
        noteId: "t22-2",
        kind: "mcq",
        difficulty: 1,
        stem: "Which statement about the photoelectric effect is correct?",
        options: [
          { id: "A", text: "Electrons are emitted only if intensity is large enough, regardless of frequency" },
          { id: "B", text: "Electrons are emitted only if photon frequency exceeds a threshold value" },
          { id: "C", text: "Emission starts after a measurable time delay while electrons absorb many waves" },
          { id: "D", text: "Kinetic energy of emitted electrons depends mainly on intensity" },
        ],
        correctOptionId: "B",
        explanation: "Emission requires photon energy above work function, giving a threshold frequency.",
        distractorRationale: {
          B: "Correct threshold-frequency condition.",
          C: "Emission is effectively immediate when frequency is above threshold.",
          D: "Maximum kinetic energy depends on frequency, not intensity.",
        },
        tags: ["threshold-frequency", "core-idea", "photoelectric-effect"],
      },
      {
        id: "t22-2-d2",
        noteId: "t22-2",
        kind: "mcq",
        difficulty: 2,
        stem: "For light above threshold frequency, increasing intensity at fixed frequency mainly increases",
        options: [
          { id: "A", text: "maximum kinetic energy of emitted electrons" },
          { id: "B", text: "stopping potential required to halt most energetic electrons" },
          { id: "C", text: "photoelectron emission rate (photoelectric current)" },
          { id: "D", text: "work function of the metal surface" },
        ],
        correctOptionId: "C",
        explanation: "At fixed frequency, higher intensity means more photons per second, so more emitted electrons.",
        distractorRationale: {
          B: "Stopping potential tracks maximum kinetic energy, which stays set by frequency.",
          C: "Correct: more photons above threshold gives greater emission rate.",
          D: "Work function is material dependent and does not increase with intensity.",
        },
        tags: ["intensity", "photoelectric-current", "experimental-trends"],
      },
      {
        id: "t22-2-d3",
        noteId: "t22-2",
        kind: "mcq",
        difficulty: 3,
        stem: "A metal has work function 2.2 eV. Incident photons have energy 3.0 eV. Maximum kinetic energy is",
        options: [
          { id: "A", text: "0.8 eV" },
          { id: "B", text: "2.2 eV" },
          { id: "C", text: "3.0 eV" },
          { id: "D", text: "5.2 eV" },
        ],
        correctOptionId: "A",
        explanation: "Use E_photon = phi + K_max, so K_max = 3.0 - 2.2 = 0.8 eV.",
        distractorRationale: {
          B: "This is the work function, not kinetic energy.",
          C: "All photon energy does not become kinetic energy; some frees the electron.",
          D: "Adding rather than subtracting is incorrect.",
        },
        tags: ["work-function", "einstein-equation", "energy-balance"],
      },
      {
        id: "t22-2-d4",
        noteId: "t22-2",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Define work function and threshold frequency for a photoemissive surface.",
        modelAnswerPoints: [
          "Work function phi is minimum energy needed to remove an electron from the surface.",
          "Threshold frequency f0 is minimum radiation frequency that causes emission.",
          "They are linked by phi = h f0.",
        ],
        workedSolution: [
          "Both definitions refer to minimum conditions for emission.",
          "Linking equation shows energy-frequency equivalence.",
        ],
        commonMistake: "Describing work function as energy of emitted electron.",
        tags: ["definitions", "threshold", "work-function"],
      },
      {
        id: "t22-2-d5",
        noteId: "t22-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Ultraviolet light of frequency 1.2 x 10^15 Hz shines on a metal of threshold frequency 8.0 x 10^14 Hz.\nCalculate maximum kinetic energy of emitted electrons.",
        modelAnswerPoints: [
          "Use K_max = h(f - f0).",
          "K_max = 6.63 x 10^-34 x (1.2 x 10^15 - 8.0 x 10^14).",
          "K_max = 2.65 x 10^-19 J.",
          "Equivalent energy is about 1.66 eV.",
        ],
        workedSolution: [
          "Subtract frequencies first to reduce arithmetic mistakes.",
          "Convert to eV only after obtaining joules if required.",
        ],
        commonMistake: "Using K_max = hf0 instead of h(f - f0).",
        tags: ["calculation", "threshold-frequency", "kinetic-energy"],
      },
      {
        id: "t22-2-d6",
        noteId: "t22-2",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "In a photoelectric experiment, stopping potential is 1.8 V.\n(a) Determine K_max in eV.\n(b) Determine K_max in joules.",
        modelAnswerPoints: [
          "K_max = eV_s, so in eV it is 1.8 eV.",
          "In joules: K_max = 1.8 x 1.60 x 10^-19.",
          "K_max = 2.88 x 10^-19 J.",
          "State both units clearly.",
        ],
        workedSolution: [
          "For electrons, energy in eV equals stopping potential in volts numerically.",
          "Then convert using 1 eV = 1.60 x 10^-19 J.",
        ],
        commonMistake: "Dividing by electron charge instead of multiplying.",
        tags: ["stopping-potential", "unit-conversion", "photoelectrons"],
      },
      {
        id: "t22-2-d7",
        noteId: "t22-2",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Explain two observations of the photoelectric effect that cannot be explained by a purely classical wave model of light.",
        modelAnswerPoints: [
          "Existence of threshold frequency: below f0 no emission regardless of intensity.",
          "Emission is effectively instantaneous with suitable frequency.",
          "Maximum kinetic energy depends on frequency rather than intensity.",
          "These are explained by photons with quantised energy hf.",
        ],
        workedSolution: [
          "State each observation and then contrast with classical prediction.",
          "Conclude with photon model explanation using one-photon one-electron interaction.",
        ],
        commonMistake: "Only listing observations without linking to model failure.",
        tags: ["evidence", "wave-particle", "evaluation"],
      },
      {
        id: "t22-2-d8",
        noteId: "t22-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A metal is illuminated with two different frequencies. For f1 = 7.5 x 10^14 Hz, stopping potential is 0.40 V. For f2 = 9.0 x 10^14 Hz, stopping potential is 1.02 V.\nUse this data to estimate Planck constant h.",
        modelAnswerPoints: [
          "Use eV_s = hf - phi, so gradient of V_s against f is h/e.",
          "Delta V_s = 1.02 - 0.40 = 0.62 V.",
          "Delta f = 9.0 x 10^14 - 7.5 x 10^14 = 1.5 x 10^14 Hz.",
          "h = e(Delta V_s/Delta f) = (1.60 x 10^-19)(0.62/1.5 x 10^14).",
          "h approx 6.6 x 10^-34 J s.",
        ],
        workedSolution: [
          "Using differences removes unknown work function.",
          "Apply h = e slope with careful handling of scientific notation.",
          "Result should be close to accepted Planck constant.",
        ],
        commonMistake: "Using one data point alone without accounting for unknown phi.",
        tags: ["graph-method", "planck-constant", "data-analysis"],
      },
      {
        id: "t22-2-d9",
        noteId: "t22-2",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "For a certain metal, work function is 2.5 eV.\n(a) Calculate threshold frequency.\n(b) Determine whether 450 nm light causes emission.\n(c) If emission occurs, find K_max.",
        modelAnswerPoints: [
          "Threshold frequency f0 = phi/h = (2.5 x 1.60 x 10^-19)/(6.63 x 10^-34) = 6.03 x 10^14 Hz.",
          "Photon frequency for 450 nm is f = c/lambda = 6.67 x 10^14 Hz.",
          "Since f > f0, emission occurs.",
          "K_max = h(f - f0) = 4.24 x 10^-20 J (about 0.265 eV).",
        ],
        workedSolution: [
          "Convert work function from eV to joules for use with h in SI.",
          "Compare incident and threshold frequencies before computing K_max.",
        ],
        commonMistake: "Comparing wavelength directly to frequency threshold without conversion.",
        tags: ["threshold-check", "work-function", "multi-step"],
      },
      {
        id: "t22-2-d10",
        noteId: "t22-2",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A student claims: 'Brighter light always ejects faster photoelectrons.' Critically evaluate this claim using photon theory and the stopping potential concept.",
        modelAnswerPoints: [
          "At fixed frequency above threshold, brighter light increases photon flux, so more electrons are emitted per second.",
          "Maximum kinetic energy is set by hf - phi, so it depends on frequency and material work function.",
          "Stopping potential measures maximum kinetic energy, so at fixed frequency it stays unchanged when only intensity changes.",
          "Claim is therefore false in general; brightness controls current, not maximum speed.",
        ],
        workedSolution: [
          "Separate quantity affected by intensity (current) from quantity affected by frequency (K_max).",
          "Use eV_s = K_max as direct experimental link.",
        ],
        commonMistake: "Using 'more photons' to argue each electron gets more energy.",
        tags: ["critical-reasoning", "stopping-potential", "exam-language"],
      },
    ],
    flashcards: [
      {
        id: "t22-2-f1",
        noteId: "t22-2",
        difficulty: 1,
        front: "State Einstein's photoelectric equation.",
        back: "hf = phi + K_max.",
        examPhrasing: "Photon energy equals work function plus maximum electron kinetic energy.",
        tags: ["einstein-equation", "core-equation"],
      },
      {
        id: "t22-2-f2",
        noteId: "t22-2",
        difficulty: 1,
        front: "What is work function phi?",
        back: "Minimum energy needed to liberate an electron from a metal surface.",
        examPhrasing: "Define work function as an energy threshold.",
        tags: ["work-function", "definition"],
      },
      {
        id: "t22-2-f3",
        noteId: "t22-2",
        difficulty: 2,
        front: "What is threshold frequency f0?",
        back: "Minimum frequency of incident radiation that causes photoemission.",
        examPhrasing: "Below f0, no photoelectrons are emitted.",
        tags: ["threshold-frequency", "definition"],
      },
      {
        id: "t22-2-f4",
        noteId: "t22-2",
        difficulty: 2,
        front: "How is stopping potential related to maximum kinetic energy?",
        back: "K_max = eV_s.",
        examPhrasing: "Stopping potential gives maximum photoelectron kinetic energy.",
        tags: ["stopping-potential", "kinetic-energy"],
      },
      {
        id: "t22-2-f5",
        noteId: "t22-2",
        difficulty: 3,
        front: "At fixed frequency above threshold, what does increasing intensity change most?",
        back: "It increases emission rate/current, not K_max.",
        examPhrasing: "Intensity controls number of emitted electrons per second.",
        tags: ["intensity", "photoelectric-current"],
      },
      {
        id: "t22-2-f6",
        noteId: "t22-2",
        difficulty: 3,
        front: "What determines maximum photoelectron kinetic energy?",
        back: "Incident frequency and work function via K_max = hf - phi.",
        examPhrasing: "Frequency sets electron energy; intensity sets current.",
        confusionPair: "frequency effect vs intensity effect",
        tags: ["kinetic-energy", "conceptual"],
      },
      {
        id: "t22-2-f7",
        noteId: "t22-2",
        difficulty: 4,
        front: "How do you estimate h from photoelectric data?",
        back: "Plot V_s against f; gradient is h/e so h = e x gradient.",
        examPhrasing: "Use linear relation eV_s = hf - phi.",
        tags: ["graphs", "planck-constant", "practical"],
      },
      {
        id: "t22-2-f8",
        noteId: "t22-2",
        difficulty: 4,
        front: "Why does no measurable delay support the photon model?",
        back: "Each electron absorbs one photon in a single interaction, so sufficient-energy events eject electrons immediately.",
        examPhrasing: "Immediate emission contradicts gradual classical energy build-up.",
        tags: ["evidence", "photon-model"],
      },
      {
        id: "t22-2-f9",
        noteId: "t22-2",
        difficulty: 5,
        front: "One high-mark check when using eV in photoelectric calculations?",
        back: "Keep units consistent; convert eV to J before combining with SI constants unless ratio form avoids conversion.",
        examPhrasing: "Unit discipline avoids factor-1.60 x 10^-19 errors.",
        tags: ["units", "exam-technique"],
      },
      {
        id: "t22-2-f10",
        noteId: "t22-2",
        difficulty: 5,
        front: "How does threshold wavelength relate to threshold frequency?",
        back: "lambda0 = c/f0 and emission occurs for wavelengths shorter than lambda0.",
        examPhrasing: "Use equivalent threshold condition in frequency or wavelength form.",
        tags: ["threshold-wavelength", "conditions"],
      },
    ],
  },

  "t22-3": {
    noteId: "t22-3",
    drills: [
      {
        id: "t22-3-d1",
        noteId: "t22-3",
        kind: "mcq",
        difficulty: 1,
        stem: "The de Broglie wavelength of a particle is given by",
        options: [
          { id: "A", text: "lambda = h/p" },
          { id: "B", text: "lambda = hp" },
          { id: "C", text: "lambda = p/h" },
          { id: "D", text: "lambda = mv/h^2" },
        ],
        correctOptionId: "A",
        explanation: "Matter waves are described by de Broglie's relation lambda = h/p.",
        distractorRationale: {
          B: "This gives wrong dimensions and trend.",
          C: "This is reciprocal of the correct relation.",
          D: "No standard de Broglie form contains h squared.",
        },
        tags: ["de-broglie", "equation-recall", "wave-particle-duality"],
      },
      {
        id: "t22-3-d2",
        noteId: "t22-3",
        kind: "mcq",
        difficulty: 2,
        stem: "Which particle has the largest de Broglie wavelength if all have same momentum magnitude?",
        options: [
          { id: "A", text: "electron" },
          { id: "B", text: "proton" },
          { id: "C", text: "alpha particle" },
          { id: "D", text: "all have same wavelength" },
        ],
        correctOptionId: "D",
        explanation: "De Broglie wavelength depends on momentum only: lambda = h/p.",
        distractorRationale: {
          B: "Particle identity is irrelevant when momentum is fixed.",
          C: "Mass differences matter only via momentum, already specified equal.",
          D: "Correct conclusion from lambda = h/p.",
        },
        tags: ["conceptual", "momentum-dependence", "duality"],
      },
      {
        id: "t22-3-d3",
        noteId: "t22-3",
        kind: "mcq",
        difficulty: 3,
        stem: "Electron diffraction is significant evidence for",
        options: [
          { id: "A", text: "electrons have no momentum" },
          { id: "B", text: "electrons only behave as waves and never as particles" },
          { id: "C", text: "wave-like behaviour of matter particles" },
          { id: "D", text: "classical wave theory being complete for all phenomena" },
        ],
        correctOptionId: "C",
        explanation: "Diffraction of electrons demonstrates matter-wave behaviour.",
        distractorRationale: {
          B: "Electrons also show particle behaviour in many experiments.",
          C: "Correct interpretation of diffraction evidence.",
          D: "Classical wave theory alone cannot explain full quantum behaviour.",
        },
        tags: ["electron-diffraction", "evidence", "matter-waves"],
      },
      {
        id: "t22-3-d4",
        noteId: "t22-3",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "State de Broglie hypothesis and write the associated equation.",
        modelAnswerPoints: [
          "Moving particles can exhibit wave-like behaviour.",
          "Each particle is associated with a wavelength.",
          "de Broglie wavelength: lambda = h/p.",
        ],
        workedSolution: [
          "A concise answer should include both concept and formula.",
          "Momentum form is preferred because it is general.",
        ],
        commonMistake: "Writing lambda proportional p instead of inversely proportional.",
        tags: ["definition", "de-broglie", "core-knowledge"],
      },
      {
        id: "t22-3-d5",
        noteId: "t22-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Calculate the de Broglie wavelength of an electron with momentum 3.0 x 10^-24 kg m s^-1.",
        modelAnswerPoints: [
          "Use lambda = h/p.",
          "lambda = (6.63 x 10^-34)/(3.0 x 10^-24).",
          "lambda = 2.21 x 10^-10 m.",
          "Answer is about 0.22 nm.",
        ],
        workedSolution: [
          "Direct substitution with SI units gives wavelength in metres.",
          "Nanometre conversion helps physical interpretation.",
        ],
        commonMistake: "Using lambda = p/h.",
        tags: ["numerical", "electron", "de-broglie-wavelength"],
      },
      {
        id: "t22-3-d6",
        noteId: "t22-3",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "An electron is accelerated from rest through potential difference 150 V.\nFind its de Broglie wavelength. Use e = 1.60 x 10^-19 C and m_e = 9.11 x 10^-31 kg.",
        modelAnswerPoints: [
          "Kinetic energy gained: eV = 2.40 x 10^-17 J.",
          "Use p = sqrt(2mE_k) = sqrt(2 x 9.11 x 10^-31 x 2.40 x 10^-17) = 6.61 x 10^-24 kg m s^-1.",
          "Then lambda = h/p = (6.63 x 10^-34)/(6.61 x 10^-24).",
          "lambda = 1.00 x 10^-10 m.",
        ],
        workedSolution: [
          "Potential energy conversion gives electron kinetic energy.",
          "Find momentum from non-relativistic kinetic relation, then apply de Broglie.",
        ],
        commonMistake: "Treating eV numerically as volts instead of joules in SI step.",
        tags: ["accelerated-electron", "multi-step", "applications"],
      },
      {
        id: "t22-3-d7",
        noteId: "t22-3",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Compare de Broglie wavelengths of an electron and a proton that have the same kinetic energy.",
        modelAnswerPoints: [
          "For fixed kinetic energy, momentum p = sqrt(2mE).",
          "Larger mass gives larger momentum.",
          "Since lambda = h/p, larger momentum means smaller wavelength.",
          "So electron has much larger de Broglie wavelength than proton at same kinetic energy.",
        ],
        workedSolution: [
          "Use proportional reasoning: p proportional sqrt(m) for constant E.",
          "Then lambda proportional 1/sqrt(m), so lighter particle has longer wavelength.",
        ],
        commonMistake: "Assuming equal kinetic energy implies equal momentum.",
        tags: ["comparison", "mass-effect", "reasoning"],
      },
      {
        id: "t22-3-d8",
        noteId: "t22-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "Explain why wave effects are usually negligible for macroscopic objects, using de Broglie wavelength arguments.",
        modelAnswerPoints: [
          "de Broglie wavelength is lambda = h/p.",
          "Macroscopic objects have large mass and momentum in everyday motion.",
          "Hence lambda is extremely small compared with object size and experimental apertures.",
          "Diffraction/interference effects become unobservable in normal conditions.",
        ],
        workedSolution: [
          "Frame argument around the scale of h relative to macroscopic momentum.",
          "Conclude that classical mechanics appears valid when matter wavelengths are tiny.",
        ],
        commonMistake: "Saying macroscopic objects have no associated wavelength.",
        tags: ["scale-analysis", "classical-limit", "evaluation"],
      },
      {
        id: "t22-3-d9",
        noteId: "t22-3",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A neutron of mass 1.67 x 10^-27 kg has speed 1200 m s^-1.\n(a) Calculate its de Broglie wavelength.\n(b) State whether crystal diffraction is plausible and justify briefly.",
        modelAnswerPoints: [
          "Momentum p = mv = 1.67 x 10^-27 x 1200 = 2.00 x 10^-24 kg m s^-1.",
          "lambda = h/p = 6.63 x 10^-34 / 2.00 x 10^-24 = 3.32 x 10^-10 m.",
          "This wavelength is of order 10^-10 m.",
          "Order matches interatomic spacing in crystals, so diffraction is plausible.",
        ],
        workedSolution: [
          "Find momentum first from mass and speed.",
          "Compare wavelength scale with known lattice spacing to assess diffraction possibility.",
        ],
        commonMistake: "Judging plausibility without any scale comparison.",
        tags: ["neutrons", "diffraction", "order-of-magnitude"],
      },
      {
        id: "t22-3-d10",
        noteId: "t22-3",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "Discuss how wave-particle duality provides a unified picture for radiation and matter. Include one experiment for light and one for matter.",
        modelAnswerPoints: [
          "Radiation shows wave behaviour (e.g., interference/diffraction) and particle behaviour (photoelectric effect).",
          "Matter shows particle behaviour (localized detections) and wave behaviour (electron diffraction).",
          "Duality means neither purely classical wave nor purely classical particle models are complete alone.",
          "Quantum theory uses complementary descriptions depending on the measurement context.",
        ],
        workedSolution: [
          "Present parallel examples: one for photons, one for matter particles.",
          "Conclude with contextual use of models rather than contradiction.",
        ],
        commonMistake: "Claiming objects switch permanently between wave and particle states.",
        tags: ["synthesis", "duality", "extended-response"],
      },
    ],
    flashcards: [
      {
        id: "t22-3-f1",
        noteId: "t22-3",
        difficulty: 1,
        front: "State de Broglie equation.",
        back: "lambda = h/p.",
        examPhrasing: "Matter wavelength is inversely proportional to momentum.",
        tags: ["de-broglie", "equation"],
      },
      {
        id: "t22-3-f2",
        noteId: "t22-3",
        difficulty: 1,
        front: "What key experiment supports wave nature of electrons?",
        back: "Electron diffraction by crystals.",
        examPhrasing: "Diffraction is evidence of electron matter waves.",
        tags: ["evidence", "electron-diffraction"],
      },
      {
        id: "t22-3-f3",
        noteId: "t22-3",
        difficulty: 2,
        front: "At fixed momentum, how does particle mass affect de Broglie wavelength?",
        back: "No effect directly; wavelength depends only on momentum.",
        examPhrasing: "lambda is set by p in lambda = h/p.",
        tags: ["conceptual", "momentum"],
      },
      {
        id: "t22-3-f4",
        noteId: "t22-3",
        difficulty: 2,
        front: "At fixed kinetic energy, which has larger de Broglie wavelength: electron or proton?",
        back: "Electron, because lighter mass gives smaller momentum at same kinetic energy.",
        examPhrasing: "For equal E_k, lambda is larger for smaller mass.",
        tags: ["comparison", "mass-dependence"],
      },
      {
        id: "t22-3-f5",
        noteId: "t22-3",
        difficulty: 3,
        front: "Why are matter-wave effects hard to see for everyday objects?",
        back: "Their momenta are large, so de Broglie wavelengths are extremely small.",
        examPhrasing: "Macroscopic wavelengths are too small to diffract appreciably.",
        tags: ["macroscopic-limit", "applications"],
      },
      {
        id: "t22-3-f6",
        noteId: "t22-3",
        difficulty: 3,
        front: "How do you get momentum from accelerating potential for electrons?",
        back: "Use eV = E_k, then p = sqrt(2mE_k).",
        examPhrasing: "Combine energy gain from potential with kinetic formula.",
        tags: ["accelerating-potential", "method"],
      },
      {
        id: "t22-3-f7",
        noteId: "t22-3",
        difficulty: 4,
        front: "What wavelength scale is typical for electron diffraction in crystals?",
        back: "Around 10^-10 m, comparable to atomic spacings.",
        examPhrasing: "Diffraction is strongest when lambda matches lattice spacing scale.",
        tags: ["scale", "crystals"],
      },
      {
        id: "t22-3-f8",
        noteId: "t22-3",
        difficulty: 4,
        front: "What does wave-particle duality say in one sentence?",
        back: "Quantum objects can display wave-like or particle-like behaviour depending on the experiment.",
        examPhrasing: "Use complementary, not mutually exclusive, descriptions.",
        tags: ["duality", "interpretation"],
      },
      {
        id: "t22-3-f9",
        noteId: "t22-3",
        difficulty: 5,
        front: "Key comparison: photoelectric effect vs electron diffraction?",
        back: "Photoelectric effect shows particle-like photons; electron diffraction shows wave-like matter.",
        examPhrasing: "Together they support duality for both radiation and matter.",
        confusionPair: "wave evidence vs particle evidence",
        tags: ["evidence", "cross-links"],
      },
      {
        id: "t22-3-f10",
        noteId: "t22-3",
        difficulty: 5,
        front: "Exam strategy for duality essays?",
        back: "Give at least one clear experiment for each side and explain what observation each model accounts for.",
        examPhrasing: "Link observations explicitly to model predictions.",
        tags: ["exam-technique", "extended-response"],
      },
    ],
  },

  "t22-4": {
    noteId: "t22-4",
    drills: [
      {
        id: "t22-4-d1",
        noteId: "t22-4",
        kind: "mcq",
        difficulty: 1,
        stem: "In the Bohr model, line spectra arise because electrons in atoms",
        options: [
          { id: "A", text: "can occupy any energy continuously" },
          { id: "B", text: "emit all wavelengths equally at all times" },
          { id: "C", text: "have quantised energy levels and emit photons during transitions" },
          { id: "D", text: "lose energy continuously while orbiting" },
        ],
        correctOptionId: "C",
        explanation: "Atomic energy levels are discrete; transitions give photons of specific energies.",
        distractorRationale: {
          B: "Equal emission at all wavelengths would give continuous spectra.",
          C: "Correct explanation for discrete spectral lines.",
          D: "Continuous loss would not produce stable quantised line spectra.",
        },
        tags: ["energy-levels", "line-spectra", "bohr-model"],
      },
      {
        id: "t22-4-d2",
        noteId: "t22-4",
        kind: "mcq",
        difficulty: 2,
        stem: "A photon is emitted when an electron in an atom moves",
        options: [
          { id: "A", text: "from lower to higher energy level" },
          { id: "B", text: "between levels of equal energy" },
          { id: "C", text: "from higher to lower energy level" },
          { id: "D", text: "in a circular path of constant radius" },
        ],
        correctOptionId: "C",
        explanation: "Emission occurs when electron energy decreases; difference is carried by photon.",
        distractorRationale: {
          B: "No energy difference means no photon energy.",
          C: "Correct direction for photon emission.",
          D: "No transition means no spectral photon.",
        },
        tags: ["transitions", "emission", "atomic-model"],
      },
      {
        id: "t22-4-d3",
        noteId: "t22-4",
        kind: "mcq",
        difficulty: 3,
        stem: "An atomic transition has energy difference 3.0 eV. The emitted photon wavelength is closest to",
        options: [
          { id: "A", text: "1240 nm" },
          { id: "B", text: "620 nm" },
          { id: "C", text: "413 nm" },
          { id: "D", text: "155 nm" },
        ],
        correctOptionId: "C",
        explanation: "Use lambda(nm) approx 1240/E(eV). So lambda approx 1240/3.0 = 413 nm.",
        distractorRationale: {
          B: "This corresponds to about 2.0 eV, not 3.0 eV.",
          C: "Correct inverse relation gives 413 nm.",
          D: "This would require about 8.0 eV transition.",
        },
        tags: ["energy-wavelength", "line-spectra", "numerical"],
      },
      {
        id: "t22-4-d4",
        noteId: "t22-4",
        kind: "structured",
        difficulty: 1,
        marks: 3,
        stem: "Explain what is meant by discrete atomic energy levels and how this leads to line spectra.",
        modelAnswerPoints: [
          "Electrons can occupy only specific allowed energies in atoms.",
          "Transitions between levels involve fixed energy differences.",
          "Photons emitted/absorbed have energies hf equal to these differences, giving discrete lines.",
        ],
        workedSolution: [
          "A continuous range of energies would produce continuous spectra instead.",
          "Discrete energies map directly to discrete wavelengths/frequencies.",
        ],
        commonMistake: "Saying line spectra come from random photon energies.",
        tags: ["definitions", "spectra", "conceptual-link"],
      },
      {
        id: "t22-4-d5",
        noteId: "t22-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "An electron drops from level E3 = -1.5 eV to E2 = -3.4 eV.\n(a) Find photon energy in eV.\n(b) Find wavelength in nm.",
        modelAnswerPoints: [
          "Photon energy is magnitude of level difference: DeltaE = 1.9 eV.",
          "Use lambda(nm) = 1240/DeltaE(eV).",
          "lambda = 1240/1.9 = 653 nm.",
          "Line lies in red region of visible spectrum.",
        ],
        workedSolution: [
          "Subtract carefully with sign: emitted energy is positive magnitude.",
          "Use eV-based shortcut or convert to SI before using E = hc/lambda.",
        ],
        commonMistake: "Using negative photon energy because level values are negative.",
        tags: ["level-difference", "wavelength", "visible-light"],
      },
      {
        id: "t22-4-d6",
        noteId: "t22-4",
        kind: "structured",
        difficulty: 2,
        marks: 4,
        stem: "Radiation of wavelength 486 nm is absorbed by hydrogen atoms from a lower state.\nCalculate energy of each absorbed photon in eV.",
        modelAnswerPoints: [
          "Use E = hc/lambda or E(eV) = 1240/lambda(nm).",
          "E = 1240/486 = 2.55 eV.",
          "Absorbed photon raises electron to higher level by this energy difference.",
          "Energy is positive because absorption adds energy to atom.",
        ],
        workedSolution: [
          "Using nm-eV shortcut speeds exam calculation.",
          "Interpret energy as atomic level separation for that transition.",
        ],
        commonMistake: "Using 486 m in formula due to missing nano conversion.",
        tags: ["absorption", "photon-energy", "calculation"],
      },
      {
        id: "t22-4-d7",
        noteId: "t22-4",
        kind: "structured",
        difficulty: 3,
        marks: 5,
        stem: "Why do gases at low pressure produce emission line spectra, while hot solids often produce continuous spectra?",
        modelAnswerPoints: [
          "Low-pressure gases have isolated atoms with discrete electronic transitions.",
          "Each transition emits specific photon energies, giving line spectra.",
          "In solids, closely spaced states and broad interactions allow many nearby energies.",
          "This leads to near-continuous distribution of emitted wavelengths.",
        ],
        workedSolution: [
          "Contrast isolated-atom transitions with dense-state behaviour in solids.",
          "Link microscopic state structure to macroscopic spectral pattern.",
        ],
        commonMistake: "Attributing spectral type only to temperature without state-structure reasoning.",
        tags: ["spectral-types", "atomic-physics", "explanation"],
      },
      {
        id: "t22-4-d8",
        noteId: "t22-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "An atom has levels at -5.6 eV, -3.4 eV, and -1.2 eV.\n(a) List all possible emission photon energies.\n(b) Identify which transition gives shortest wavelength.",
        modelAnswerPoints: [
          "Possible downward differences: 2.2 eV (-1.2 to -3.4), 4.4 eV (-1.2 to -5.6), 2.2 eV (-3.4 to -5.6).",
          "Distinct emission energies are 2.2 eV and 4.4 eV.",
          "Shortest wavelength corresponds to largest energy.",
          "So transition -1.2 eV to -5.6 eV gives shortest wavelength.",
        ],
        workedSolution: [
          "Compute all downward transition differences systematically.",
          "Use E proportional 1/lambda to pick shortest wavelength transition.",
        ],
        commonMistake: "Selecting highest final energy level as shortest wavelength source.",
        tags: ["energy-level-diagram", "transitions", "analysis"],
      },
      {
        id: "t22-4-d9",
        noteId: "t22-4",
        kind: "structured",
        difficulty: 4,
        marks: 6,
        stem: "A spectral line has wavelength 434 nm.\n(a) Calculate corresponding photon energy in J and eV.\n(b) Explain how this can be used to infer an atomic energy-level gap.",
        modelAnswerPoints: [
          "E = hc/lambda = (6.63 x 10^-34 x 3.00 x 10^8)/(4.34 x 10^-7) = 4.58 x 10^-19 J.",
          "In eV: E = 4.58 x 10^-19 / 1.60 x 10^-19 = 2.86 eV.",
          "Photon energy equals transition energy difference between two levels.",
          "So measured wavelength gives direct value of atomic level separation.",
        ],
        workedSolution: [
          "Convert wavelength to metres before SI substitution.",
          "Then convert joules to eV for convenient comparison with level diagrams.",
        ],
        commonMistake: "Confusing photon energy with absolute value of one energy level.",
        tags: ["spectroscopy", "energy-gap", "units"],
      },
      {
        id: "t22-4-d10",
        noteId: "t22-4",
        kind: "structured",
        difficulty: 5,
        marks: 7,
        stem: "A hydrogen discharge tube is viewed through a spectrometer. Explain why only specific wavelengths are observed and how this supports quantised atomic energy levels rather than a classical orbital model.",
        modelAnswerPoints: [
          "Observed spectrum consists of discrete lines, not a continuum.",
          "Each line corresponds to a photon from a specific electron transition with fixed DeltaE.",
          "Using hf = DeltaE links measured frequencies to level differences.",
          "Classical orbiting-electron model predicts continuous radiation as electron energy changes continuously.",
          "Line spectra therefore support quantised allowed energies in atoms.",
        ],
        workedSolution: [
          "Describe observation first, then connect mathematically via hf = DeltaE.",
          "Contrast explicitly with classical expectation to complete evaluation.",
        ],
        commonMistake: "Stating quantisation without discussing observed spectral discreteness.",
        tags: ["spectrometer", "evaluation", "quantisation-evidence"],
      },
    ],
    flashcards: [
      {
        id: "t22-4-f1",
        noteId: "t22-4",
        difficulty: 1,
        front: "Why are atomic spectra often line spectra?",
        back: "Because electrons transition between discrete energy levels, producing photons of specific energies.",
        examPhrasing: "Discrete level differences produce discrete wavelengths.",
        tags: ["line-spectra", "energy-levels"],
      },
      {
        id: "t22-4-f2",
        noteId: "t22-4",
        difficulty: 1,
        front: "When is a photon emitted in an atom?",
        back: "When an electron moves from higher to lower energy level.",
        examPhrasing: "Emission corresponds to a downward transition.",
        tags: ["emission", "transitions"],
      },
      {
        id: "t22-4-f3",
        noteId: "t22-4",
        difficulty: 2,
        front: "When is a photon absorbed in an atom?",
        back: "When an electron gains exactly the energy needed to move to a higher level.",
        examPhrasing: "Absorption requires photon energy matching an allowed level gap.",
        tags: ["absorption", "transitions"],
      },
      {
        id: "t22-4-f4",
        noteId: "t22-4",
        difficulty: 2,
        front: "How is transition energy related to photon frequency?",
        back: "DeltaE = hf.",
        examPhrasing: "Use photon relation to connect spectra and level gaps.",
        tags: ["delta-e", "frequency"],
      },
      {
        id: "t22-4-f5",
        noteId: "t22-4",
        difficulty: 3,
        front: "How is transition energy related to photon wavelength?",
        back: "DeltaE = hc/lambda.",
        examPhrasing: "Shorter wavelength means larger transition energy.",
        tags: ["delta-e", "wavelength"],
      },
      {
        id: "t22-4-f6",
        noteId: "t22-4",
        difficulty: 3,
        front: "What transition gives shortest emitted wavelength?",
        back: "The transition with the largest energy drop.",
        examPhrasing: "Maximum DeltaE corresponds to minimum lambda.",
        tags: ["comparisons", "spectral-lines"],
      },
      {
        id: "t22-4-f7",
        noteId: "t22-4",
        difficulty: 4,
        front: "Why can one atom produce several spectral lines?",
        back: "Multiple possible pairs of energy levels allow multiple transition energies.",
        examPhrasing: "Each allowed transition contributes one line frequency.",
        tags: ["level-diagrams", "multiple-lines"],
      },
      {
        id: "t22-4-f8",
        noteId: "t22-4",
        difficulty: 4,
        front: "Why are level energies often shown as negative values?",
        back: "Zero is chosen at ionisation limit; bound states have lower (negative) energies relative to this reference.",
        examPhrasing: "Negative sign indicates bound electrons.",
        tags: ["energy-reference", "atomic-levels"],
      },
      {
        id: "t22-4-f9",
        noteId: "t22-4",
        difficulty: 5,
        front: "How does spectroscopy provide evidence for quantisation?",
        back: "Measured discrete wavelengths imply discrete transition energies, which require quantised atomic levels.",
        examPhrasing: "Line spectra are direct evidence against continuous-energy classical models.",
        tags: ["evidence", "spectroscopy", "quantisation"],
      },
      {
        id: "t22-4-f10",
        noteId: "t22-4",
        difficulty: 5,
        front: "Exam check for energy-level questions using eV and J?",
        back: "Keep one unit system per step and convert deliberately: 1 eV = 1.60 x 10^-19 J.",
        examPhrasing: "Unit consistency prevents large numerical errors in spectra calculations.",
        confusionPair: "level values vs transition energy",
        tags: ["units", "exam-technique", "high-yield"],
      },
    ],
  },
};
